### ISSUE TITLE
when launching mpv.net from the preview window, no audio is played with the video

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#10]
Hi Revan, Stax, and all Contributors,

When previewing a video, and press "E" to view the resulting video with mpv.net, older versions of staxrip (like 1.7.x.x) did play the audio along with the video. That was useful !
I have not tested many releases of StaxRip for a while, but now I am testing 2.0.2.0 and it seems that audio is not piped to mpv.net.
Is is possible to have the audio back?

**Comment by Revan654** [comment]
It all depends on the container and if the video can sync up with the audio. VS is very limited in this area and usually has to be tunneled through VSpipe. Which can strip the audio out. This is more of a mpv / mpv.net issue rather then StaxRip issue. I suggest asking there resp.

**Comment by 44vince44** [comment]
Just for information: in the mean time a workaround is to add in the mpv.conf file the line:
audio-file-auto=all
