### ISSUE TITLE
Implementation of a new CPU-based MPEG2/4 encoder

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1000]
need a new encoder = CPU-MPEG-2/4

now available intel-mpeg-2(VGA/GPU) 
uses QSVEnc(VGA/GPU) due to which the image and fps deteriorate

![001](https://user-images.githubusercontent.com/95682410/232467625-43b4424d-7176-49c7-a702-9cdc6e37725c.jpg)

**Comment by Dendraspis** [comment]
This one?  🤨 

![image](https://user-images.githubusercontent.com/50659978/232497114-984a3f2c-b436-438c-b14d-e9c56243d67b.png)

**Comment by Discograp** [comment]
> This one? 🤨
> 
> ![image](https://user-images.githubusercontent.com/50659978/232497114-984a3f2c-b436-438c-b14d-e9c56243d67b.png)

uses QSVEnc due to which the image and fps deteriorate

**Comment by Dendraspis** [comment]
Okay, now I get it.
GPU does not automatically mean, that it's worse. QSVEnc uses Intels QuickSyncVideo, that is meant to do such things, which should be CPU based, even if it works with GPU assistance. As far as I remember GPU is only mentioned for reading the source, which can be disabled by using `--avsw`, but that won't harm the quality.
If in doubt, use ffmpeg.

Nevertheless MPEG2/4 is too old to be worked on. I let this request open, but won't put any effort into it. We have to concentrate on new encoders like VVEnc or tool updates and sadly my time is limited.

**Comment by Discograp** [comment]
Yes, we'll have to use the handbrake
These codecs are old - but also old movies/series :D
and some video files - (2023y)modern files save mpeg-ts

and mpeg-4 converts well vp9-8bit :D
