### ISSUE TITLE
Please! change the avisyntfps

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1001]
Please! change the avisyntfps

AssumeFPS = AssumeFPS($select:msg:Select a Frame Rate;23.976|24000, 1001;24;25;29.970|30000, 1001;30;47.952|48000, 1001;48;50;59.940|60000, 1001;60;120;144;240$)
AssumeFPS Source File = AssumeFPS(%media_info_video:FrameRate%)
ChangeFPS = ChangeFPS($select:msg:Select a Frame Rate;23.976|24000, 1001;24;25;29.970|30000, 1001;30;47.952|48000, 1001;48;50;59.940|60000, 1001;60;120;144;240$)
ConvertFPS = ConvertFPS($select:msg:Select a Frame Rate;23.976|24000, 1001;24;25;29.970|30000, 1001;30;47.952|48000, 1001;48;50;59.940|60000, 1001;60;120;144;240$)

![001](https://user-images.githubusercontent.com/95682410/233236544-5b565b93-6fb0-49aa-968c-bb5e6257966e.jpg)

**Comment by Dendraspis** [comment]
Duplicate: #995
