### ISSUE TITLE
RT_Stats filters and their description are displayed cut off in the window

### ISSUE THREAD

**Issue by firezt** [staxrip/staxrip#1002]
**Describe the bug**
RT_Stats filters and their description appear "cut off" in the window, as title says, for some reason.
And it also has a small delay to be shown when clicked.

**Expected behavior**
The filters and description should be displayed correctly like the other items in the window and without delay to be displayed.

**How to reproduce the issue**
1. Go to `Apps` (or press `F9`)
2. Click on `AviSynth` section
3. Look for `RT_Stats` and click on it

That's it.

**Provide information**
There's no error message. I'm on the latest version of StaxRip, 2.16.0.

**Additional context**
For reference, screenshot using scale factor at 1.05:
![StaxRip_dF7lf0wln3](https://user-images.githubusercontent.com/87192386/233898864-19f73955-5f6b-4c31-9fd8-477a202459c1.png)

Using 1.00 or less helps a bit, however the available filters and description are still displayed on the right for whatever reason. It's the only item that has this behavior.

Thanks for reading.

**Comment by Dendraspis** [comment]
Because there are so many functions, the text is pretty long. You can solve this issue by lowering the UI Scale (like you did) or you simple make the Apps window a bit higher, so the function names fit in.  🙂 

Another solution is barely possible.
