### ISSUE TITLE
pSharp (bug)

### ISSUE THREAD

**Issue by Pawelemwelt** [staxrip/staxrip#1003]
------------------------- System Environment -------------------------

StaxRip    : v2.16.0
Windows    : Windows 10 Enterprise 2009
Language   : Russian (Belarus)
CPU        : Pentium(R) Dual-Core CPU       T4300  @ 2.10GHz
GPU        : NVIDIA GeForce G 105M
Resolution : 1366 x 768
DPI        : 96
Code Page  : 1251

----------------------- Media Info Source File -----------------------

D:\Cor_Kalom_S_Erwache_2160p.mkv

General
Complete name            : D:\Cor_Kalom_S_Erwache_2160p.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 10.1 MiB
Duration                 : 11 s 917 ms
Overall bit rate         : 7 141 kb/s
Frame rate               : 60.000 FPS
Writing application      : Lavf58.76.100
Writing library          : Lavf58.76.100
ErrorDetectionType       : Per level 1

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : Constrained Baseline@L5.2
Format settings          : 1 Ref Frames
Format, CABAC            : No
Format, Reference frames : 1 frame
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 11 s 917 ms
Width                    : 3 840 pixels
Height                   : 2 160 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 60.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Writing library          : x264 core 164 r3081 19856cc
Default                  : Yes
Forced                   : No

Audio
ID                       : 2
Format                   : AAC LC
Format/Info              : Advanced Audio Codec Low Complexity
Codec ID                 : A_AAC-2
Duration                 : 11 s 915 ms
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 46.875 FPS (1024 SPF)
Compression mode         : Lossy
Default                  : Yes
Forced                   : No

------------------------------ Demux MKV ------------------------------

mkvextract 75.0

"D:\Soft Portable\StaxRip-v2.16.0-x64\Apps\Support\MKVToolNix\mkvextract.exe" --ui-language en D:\Cor_Kalom_S_Erwache_2160p.mkv tracks 1:D:\Cor_Kalom_S_Erwache_2160p_temp\ID1.aac

Extracting track 1 with the CodecID 'A_AAC' to the file 'D:\Cor_Kalom_S_Erwache_2160p_temp\ID1.aac'. Container format: raw AAC file with ADTS headers

Start:    23:12:14
End:      23:12:19
Duration: 00:00:04

General
Complete name         : D:\Cor_Kalom_S_Erwache_2160p_temp\ID1.aac
Format                : ADTS
Format/Info           : Audio Data Transport Stream
File size             : 237 KiB
Overall bit rate mode : Variable

Audio
Format                : AAC LC
Format/Info           : Advanced Audio Codec Low Complexity
Format version        : Version 4
Codec ID              : 2
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 237 KiB (100%)

-------------------------- Demux timestamps --------------------------

mkvextract 75.0

"D:\Soft Portable\StaxRip-v2.16.0-x64\Apps\Support\MKVToolNix\mkvextract.exe" --ui-language en timestamps_v2 D:\Cor_Kalom_S_Erwache_2160p.mkv 0:D:\Cor_Kalom_S_Erwache_2160p_temp\Cor_Kalom_S_Erwache_2160p_timestamps.txt

Start:    23:12:19
End:      23:12:21
Duration: 00:00:01

---------------------- Indexing using ffmsindex ----------------------

"D:\Soft Portable\StaxRip-v2.16.0-x64\Apps\Plugins\Dual\ffms2\ffmsindex.exe" D:\Cor_Kalom_S_Erwache_2160p.mkv D:\Cor_Kalom_S_Erwache_2160p_temp\temp.ffindex

Writing index... done.

Start:    23:12:21
End:      23:12:23
Duration: 00:00:02

------------------------------ Exception ------------------------------

System.InvalidOperationException: Последовательность не содержит элементов
   в System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   в StaxRip.VideoScript.GetAvsLoadCode(String script, String scriptAlready) в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 530
   в StaxRip.VideoScript.GetAVSLoadCodeFromImports(String code) в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 602
   в StaxRip.VideoScript.ModifyAVSScript(String script) в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 614
   в StaxRip.VideoScript.ModifyScript(String script, ScriptEngine engine) в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 331
   в StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath, Boolean flipVertical) в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 296
   в StaxRip.VideoScript.GetInfo() в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 649
   в StaxRip.VideoScript.GetFrameCount() в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 663
   в StaxRip.VideoScript.GetSeconds() в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 659
   в StaxRip.MainForm.AviSynthListView_ScriptChanged() в D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:строка 6193
   в StaxRip.FiltersListView.OnChanged() в D:\Code\Github\staxrip\staxrip\Source\Controls\FiltersListView.vb:строка 275
   в StaxRip.FiltersListView._Lambda$__14-0(VideoScript script) в D:\Code\Github\staxrip\staxrip\Source\Controls\FiltersListView.vb:строка 32
   в StaxRip.VideoScript.RaiseChanged() в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 26
   в StaxRip.VideoScript.AddFilter(VideoFilter filter) в D:\Code\Github\staxrip\staxrip\Source\Video\VideoScript.vb:строка 103
   в StaxRip.FiltersListView.AddClick(VideoFilter filter) в D:\Code\Github\staxrip\staxrip\Source\Controls\FiltersListView.vb:строка 265
   в StaxRip.UI.MenuItemEx._Closure$__31-0`1._Lambda$__0() в D:\Code\Github\staxrip\staxrip\Source\UI\Menu.vb:строка 452
   в StaxRip.UI.MenuItemEx.OnClick(EventArgs e) в D:\Code\Github\staxrip\staxrip\Source\UI\Menu.vb:строка 672
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

~~В версии StaxRip-v2.13.0-x64 такой проблемы нет. В версии StaxRip-v2.16.0-x64 происходит вылет приложения при добавлении фильтра pSharp.~~
Translation:
StaxRip v2.13.0 does not have this problem, StaxRip v2.16.0 crashes when using a pSharp filter.

**Comment by Dendraspis** [comment]
Which CPU do you use?

**Comment by Dendraspis** [comment]
Because `pSharp` should be not integrated:
Which script/dll did you import/load? What dependancies does it bave? Link?

**Comment by Discograp** [comment]
Простите что вмешиваюсь, но больше не обновляйте софт СтаксРип - его скрипты/коды слишком новые для вашей устаревшей системы

**Comment by Discograp** [comment]
кстати - какой фирмы у вас ноут? найдите или сами - прочистите от пыли цпу и гпу и смените термопасту их ние - ноут станет шустрее и тише =)))))))

**Comment by Dendraspis** [comment]
Please use English only ... you too, @Discograp Thanks.

**Comment by Discograp** [comment]
Translation:
StaxRip v2.13.0 does not have this problem, StaxRip v2.16.0 crashes when === the software instantly closes when it selects the filter-pSharp

**Comment by Dendraspis** [comment]
This should be fixed in v2.17.0, that came out today.
Please reopen this issue, if you still get an error message.
