### ISSUE TITLE
Update AviSynth+ SMDegrain filter to the latest version

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1004]
**Is your feature request related to a problem? Please describe.**
StaxRip currently uses older version of SMDegrain filter

**Describe the solution you'd like**
I would like to use latest SMDegrain filters with its new 4K capabilities and flags.
AviSynth site contains outdated information about filter http://avisynth.nl/index.php/SMDegrain
But if you follow top link with up to date information https://htmlpreview.github.io/?https://github.com/Dogway/Avisynth-Scripts/blob/master/SMDegrain/SMDegrain.html you will find out that there is latest v4.3.0d version

**Describe alternatives you've considered**
For me no alternatives, because this filter is the most used by me to degrain older rips.
I have tried to use all of denoise filters included in StaxRip and found that only SMDegrain works best for me.

**Explain why the feature matters to you**
I would like to use latest SMDegrain filters with its new 4K capabilities and flags

**Comment by Dendraspis** [comment]
Thanks.
I'll update it as soon as I'm back at home. In the meantime you can update SMDegrain by yourself and use it. Unless there are new dependencies, it should work without issues. Otherwise you have to import/load the dependencies manually.

**Comment by IevgenSobko** [comment]
@Dendraspis I believe that needs also AviSynth upgrade.
I have tried to put new version, but it didn't work with complaining about old AviSynth used by StaxRip

**Comment by Dendraspis** [comment]
StaxRip uses AviSynth+ v3.7.2, which is the latest version. If you can wait, I'll figure it out and think it will be available in the next release in about 2 months.

**Comment by IevgenSobko** [comment]
Sure, np. 
I'm just starting to use this great tool after Xvid4PS and still need some time to learn it.

**Comment by madey83** [comment]
latest version of avisynth you can find there: https://gitlab.com/uvz/AviSynthPlus-Builds/-/tree/main

avisynth_updater.bat will update your system file, but you need to replace avisynth files from Staxrip folder with new downloaded...

For me it works without any issue...

**Comment by Dendraspis** [comment]
Thanks, even it does not belong here.

**Comment by Discograp** [comment]
> latest version of avisynth you can find there: https://gitlab.com/uvz/AviSynthPlus-Builds/-/tree/main
> 
> avisynth_updater.bat will update your system file, but you need to replace avisynth files from Staxrip folder with new downloaded...
> 
> For me it works without any issue...

Thanks!

**Comment by IevgenSobko** [comment]
> this version is already in StaxRip
Are you sure? Because it contains developer branch builds 3.7.3 and SMDegrain checks whether it is 3.7.3 and doesn't want to work with StaxRip that uses 3.7.2

**Comment by Dendraspis** [comment]
Both will be updated in the next release....
