### ISSUE TITLE
Constant frame rate does not work and wrong display fps in windows explorer

### ISSUE THREAD

**Issue by Ragnaroeko** [staxrip/staxrip#1006]
![Staxrip fps false](https://user-images.githubusercontent.com/70485372/235884065-047d4004-b69f-4068-a9a6-a06782d06738.jpg)

Problem 1:

All videos I convert with staxrip v2.15.0 show the wrong fps in Windows File Explorer. Instead of 23.97, 23.81 fps is displayed. Media Info shows 23.976 (24000/1001) fps.

Nevertheless, something can't be right, all videos that I have converted with Handbrake, DVDFab or Movavi, for example, also show the correct fps of 23.97 in Windows Explorer! Only videos converted with Staxrip show 23.81 fps in Explorer.

And it doesn't matter if I chose List Hardware or List Software in Staxrip.
Is there an error here?

---

Problem 2:

I have an AMD Ryzen™ 7 PRO 4750G that I work with, I deliberately don't use an extra graphics card, so I easily save 200 watts of electricity. (I have noticed that very fast conversion often leads to a poorer image result, so I am satisfied with my computer solution as it is and without an extra graphics card.)

I started with staxrip v2.14.0 for the first time, at the moment I'm working with stax 2.15.0, before that I only had Handbrake, Movavi or DVDFab programs. What I miss is that I can't create a video with a constant frame rate, regardless of the setting, software or hardware option. For hardware (AMD H.265) I tried all available options (CQP, CBR, VBR) with all sorts of different settings. Normally you should get a constant frame rate with CBR, right? Anyway, I always have a variable frame rate after encoding, never a constant one, no matter what I choose.
can't staxrip do that? or what on earth am I doing wrong?

I also tried the option (Rate Control 3 in the menu) Strict CBR. Here, however, I immediately get a termination and an error message after the start. So I don't know what to do anymore!

I think the program is cool!

Can someone please take a look at these 2 problems and help me?

For problem 1, does staxrip have a problem with the fps bitrate because it is displayed differently in explorer?
and to problem 2, how can I set a constant frame rate?

greetings from Germany

**Comment by Ragnaroeko** [comment]
Hi! :-)

i have (re)encoded videos! 

I try to keep it short.
I converted 14 pieces of 4k UHD video to 1080p, of which 3 pieces were HDR10+, 8 pieces HDR10, the rest normal. all videos had in Media Info: 

Refresh rate mode : Constant
Frame Rate : 23.976 (24000/1001) FPS

i also converted about 20 1080p videos with staxrip from version 2.14 and 2.15.

after converting with staxrip, media info says:
Frame rate mode: variable <--- that's what I meant! I don't get a constant with stax!
Frame rate : 23.976 FPS or is displayed
23.976 (24000/1001) fps

it doesn't matter, all videos are displayed in the file explorer with 23.81 fps after converting and it's only the videos that I changed with staxrip! and it doesn't matter whether I stax the bit rate or not. after reading it in with staxrip, it also says 23.976 in the window at the top!

I have now also added the latest version of mkvtoolnix gui to stax version 76.0 the problem still persists.

I don't know where the error could be. maybe it's because of mkvtoolnix, i also added audio tracks or subtitles with the last 3 program versions, it wasn't a problem afterwards, the videos all still had the constant frame rate of 23.976 (24000/1001) FPS. However, these were all videos that previously had a constant frame rate. staxripp always says variable after converting, no matter what happens or changes to stax! It also doesn't matter whether I do it with a hardware encoder or with x265 (encode software) it's always variable later in the video and the fps is always displayed in the file explorer with 23.81 fps, always! for all converted videoso with stax ripp! as you can see in my photo! If I use Handbrake, movavi or DVDFab, the fps are displayed correctly in windows file explorer. funny error is that :-(


i would like to be able to set in staxrip that i can set the image repetition to constant and not to variable, how does that work?

**Comment by Ragnaroeko** [comment]
![Staxrip fps false mux 2](https://user-images.githubusercontent.com/70485372/236053626-52f2b61f-06b3-456d-a88a-eff3d7a0bb64.jpg)

I just re-copied the original video with Staxripp and Video and Audio "Copy/Mux" without converting. The error occurred the video is no longer 23.97, it is now displayed in Windows File Explorer with 23.81 fps! The phenomenon could be due to mkvtoolnix? However, the error would then also be present in the new version v76. I also have the v74, the same thing happens!

If I split the original video (23.97 fps) into the individual tracks (VIDEO and audio) and then put them back together again with mkvtoolnix gui, the fps of 23.97 is correct afterwards. I didn't specify any fps in mkvtool just put it back together!

In my opinion, the problem should be with Staxrip, maybe something is wrong with the transfer to mkvtoolnix!?
The same video has 23.81 fps when muxing with stax behind!

**Comment by Dendraspis** [comment]
`Frame Rate` in MediaInfo can be set for the Video track as well as for the entire movie/container, which can be seen under `General` section. Is there a difference? Did you compare?

What about the mentioned filters?

What about the media info of the mentioned `.hevc` file in the temp folder?

In the project options there is a checkbox to extract timestamps. Disable it or delete the path of the timestamps file inside the container options if there is one. If timestamps were set/created, this could help.

New `MKVToolNix` version won't help, because this is a parameter/caller issue, if it is related to that.

**Comment by Ragnaroeko** [comment]
![Staxrip fps false mux 3](https://user-images.githubusercontent.com/70485372/236059006-1c40c470-f6ff-4e0c-b59a-ec83c59f4e4f.jpg)

here is a HEVC file, I don't need to make a new one because I haven't deleted everything yet.

after encoding with stax and muxing after, the video also shows 23.81 fps! although it says 23.97 fps everywhere in the settings!

PS:
Under General is
Video #0 : HEVC at 3 911 kb/s
Aspect : 1920 x 808 (2,376) at 23,976 fps

Nothing says 23.81 fps here either!
I really have no idea where this is caused in stax!

**Comment by Dendraspis** [comment]
Okay, but what says Explorer about the HEVC file?

> here is a HEVC file, I don't need to make a new one because I haven't deleted everything yet.

You would do if you would read and follow my questions and instructions, especially regarding timestamps.

It's hard to tell for me at this point, but it looks like you just have to disable/remove the timestamps.  🤔

**Comment by Ragnaroeko** [comment]
![Staxrip fps false mux 4](https://user-images.githubusercontent.com/70485372/236065282-82b59266-1cbf-4dbd-8b65-b9c534658f67.jpg)

See photo, no conversion! only mux with staxrip, why is variable again and from cfr to vfr? or does it not matter whether it says variable or constant or cfr or vfr and so on?

I just muxed the video as you told me and afterwards it also shows 23.81fps in windows explorer. like all videso i made with staxrip. and that only happens with staxrip!

----

the windows explorer doesn't show anything else with the hevc file, no fps, it's too stupid for that ;-)
my friend thanks for your help, but i'm not an expert, i know some things, but not everything. I have to ultimately rely on the information that is displayed to me. I just noticed that the file explorer only shows these 23.81 fps for videos that I created with Stax. there must still be a reason why he only does this with these videos that were created with stax. I don't want to have shot to the wind all the time, converting the video if the audio tracks suddenly run asynchronously or other surprises arise. I can't watch every film afterwards to see if everything fits ;-) as written, I'm not a program author, I don't know everything and still more than many others ;-)

my brother knew more, he is a programmer for audi cars, but he has zero time.

I know what you mean by time stamps, I just don't know where to look for them or where to delete them. with the editor i think i found this file with lots of numbers, is that this file? (Beast - Hunters Without Mercy (2022)_timestamps.txt)? then again I don't know! in the head is only:
# time code format v2
0.00
42.00
83.00
125.00
167.00
209.00
.......................

and otherwise just pay...

**Comment by Ragnaroeko** [comment]
I have followed all your instructions!

It worked, I also deleted the time stamp in the container and muxed it again. now the data match and the win stupid explorer also shows correctly at 23.97 fps!

;-)

thank you friend! sleep well!

it's now 1:18 am for me, I have to work tomorrow.

PS: are you from Germany?

Best regards

**Comment by darkcity87** [comment]
Is it possible to add option ''Do not include source timestamps to output video''?
Converting vfr>cfr needed source timestamps for source filter but cant be added to output container, or situation any framerate change source timestamps cant be added to output container.

**Comment by Discograp** [comment]
No
this is a ''data'' error - old mediainfo

''staxrip'' as a victim of a false accusation

''staxrip'' shows ''data'' from ''mediainfo''

=========================

Nein
Dies ist ein Datenfehler - alte Medieninfo

staxrip als Opfer einer falschen Anschuldigung

staxrip zeigt Daten aus mediainfo

**Comment by Discograp** [comment]
I do not understand what is the problem?

showing different video files

==================

Ich verstehe nicht, was ist das Problem?

Zeigen Sie verschiedene Videos

![123](https://user-images.githubusercontent.com/95682410/236114681-c877a16a-2ecf-429f-ae06-b3a95cca5a66.jpg)

**Comment by Discograp** [comment]
when encoding and saving - the software used a suitable fps

**Comment by Dendraspis** [comment]
The reason is simple:
Whenever there are timestamps, the frame rate becomes `Variable`, even the timestamps themself indicate constant frame rate.
Extracting timestamps is enabled by default because it helps with some issues a user could have. Having "variable" frame rate in media infos is the unpleasant downside, but it's just cosmetics, because the video will be handled well by a player without issues.

Yes, I am, but nevertheless the language on GitHub (and Discord) is English, so everybody can join and follow a conversation.


> Is it possible to add option ''Do not include source timestamps to output video''?

Nope, you can disable the extraction via `Options » Timestamps` in general and also limit it to VFR files only.

> If this is hard to implement can you uncheck ''Extrack timestamps from mkv'' by default

You can do it by your own without loaded source file and re-save it as (new) template, optionally make it a startup template.

**Comment by Discograp** [comment]
for 1920*904

![123](https://user-images.githubusercontent.com/95682410/236125175-0f81fa57-967c-487c-b8f2-327fcbb912e6.jpg)

**Comment by Dendraspis** [comment]
Source was 808px high (mod 8), I don't know why the encoded video has a height of 904px. 😵‍💫

**Comment by Ragnaroeko** [comment]
@Discograp you: "Ich verstehe nicht, was ist das Problem?

Zeigen Sie verschiedene Videos"

----

Ich schreibe das jetzt Mal auf deutsch! Es geht nicht um verschiedene Videos! Weil/warum? Weil jedes Video das ich besitze in MediaInfo unter Video (ID:1) bei der Zeile: Modus der  Bildwiederholungsrate: "konstant" anzeigt. Und wenn ich das mit Staxrip konvertiert habe steht hinterher immer, Modus der Bilderwiederholungsrate = "variabel" drin. Und ich glaube das ich so ziemlich alles mit Staxrip an verfügbaren Optionen ausprobiert habe was man probieren kann, zumindest zum großen Teil und trotzdem steht hinter immer "variabel" in MediaInfo wenn ich das Video aufrufe. Wie geschrieben das hat mich gewundert. Dazu ist nirgendwo eine genauere Doku Erklärung zu finden und ich möchte mehr Wissen was ich da eigentlich ausführe beim codieren und warum und wieso das dann so ist. Die Beste Bild Qualität erreiche ich wenn ich ein UHD Video auf 1080p umwandle oder auf QHD (2560x1440p), ist ja klar das das so ist, da bei UHD noch mehr Informationen im Bildmaterial verfügbar sind. 

Und irgendwann ist mir aufgefallen das im Windows Datei Explorer anstatt 23.97 fps, 23,81 fps angezeigt wurde, aber nur bei den Videos die ich mit Staxrip konvertiert hatte. (Und das tritt nur bei Staxrip auf) Das fant ich halt komisch und hatte Angst das später beim Abspielen vielleicht die Audio Spur asynchron laufen könnte oder sonst sowas in der Art. Und weil ich im gesamten Internet nichts dazu gefunden hatte, dachte ich mir ich frage jetzt einfach mal direkt hier in Github. Wenn ich die Timestamp weg lasse (bzw. neu Muxe ohne Timestamp passt es und der Explorer zeigt 23,97 fps an. 

Ich will eben auf Nummer sicher gehen, weil wenn ich das Quellmaterial erstmal gelöscht habe kann ich das nicht mehr ändern!

(Ich hatte auch schnell bemerkt das meine Hardware integrierte AMD Grafikkarte in der CPU nicht alle Optionen unterstützt die mit H.265 möglich sind. Zum Beispiel keine B Frames und so weiter. Die besten Ergebnisse sind mit x265 zu erzielen, hier kann man viel mehr Optionen ausführen und mit der Einstellung Medium oder Slow ist das Videobild einfach genauer, schärfer und besser, so die derzeitige Erfahrung. Das konvertieren dauert halt dann länger, ist halt so.)

Warum im Datei Explorer die fps da anders angezeigt werden und warum variabel so schnell änderbar ist auf konstant und welche Auswirkungen das genau hat, weiß ich zwar immer noch nicht so genau... aber ich werde mir euere (Dankbar!) Antworten nochmal genau anschauen. Ich versuche ja dazu zu lernen, danke schon mal an ALLE ;-)

---

Translate with Google!

@Discograp you: "I don't understand, what's the problem?

Show different videos"

----

I'll write this in German now! It's not about different videos! Because/why? Because every video I have in MediaInfo under Video (ID:1) at the line: Frame rate mode: shows "constant". And when I've converted it with Staxrip, it always says frame rate mode = "variable". And I think I've tried pretty much every option available with Staxrip that you can try, at least for the most part, and yet it always says "variable" in MediaInfo when I view the video. As written, I was surprised. There is no more detailed documentation anywhere to be found and I would like to know more about what I am actually doing when coding and why and why that is the case. I achieve the best image quality when I convert a UHD video to 1080p or to QHD (2560x1440p), it is clear that this is the case, since with UHD even more information is available in the image material.

And at some point I noticed that instead of 23.97 fps, 23.81 fps was displayed in Windows File Explorer, but only for the videos that I had converted with Staxrip. (And that only occurs with Staxrip) I found that strange and was afraid that the audio track might run asynchronously later when playing or something like that. And because I couldn't find anything about it on the entire Internet, I thought to myself just ask right here in Github. If I omit the timestamp (or new Muxe without a timestamp, it fits and Explorer shows 23.97 fps.

I just want to be on the safe side because once I've deleted the source material I can't change it!

(I also quickly noticed that my hardware-integrated AMD graphics card in the CPU does not support all the options that are possible with H.265. For example, no B frames and so on. The best results can be achieved with x265, you can do a lot more here Run the options and with the Medium or Slow setting, the video image is simply more accurate, sharper and better, according to current experience. Converting then takes longer, that's just the way it is.)

I still don't know exactly why the fps are displayed differently in File Explorer and why variable can be changed so quickly to constant and what the exact effects are... but I'll take a close look at your (thankful!) answers . I'm trying to learn, thanks to EVERYONE ;-)

**Comment by Discograp** [comment]
bitrate and fps always change = always

in this video - FPS was repaired - the frame became full

==================================

immer ändernde Bitrate und fps = immer

dieses Video - FPS wurde repariert - der Rahmen wurde vollwertiger

**Comment by Discograp** [comment]
> Source was 808px high (mod 8), I don't know why the encoded video has a height of 904px. 😵‍💫

nope /// source 1920*904

**Comment by Dendraspis** [comment]
> > Source was 808px high (mod 8), I don't know why the encoded video has a height of 904px. 😵‍💫
> 
> nope /// source 1920*904

Look at the very first screenshot, especially the texts "Coder StaxRip" and "Original file"  😊

**Comment by Dendraspis** [comment]
The datetime format is:  `dd.MM.yyyy`  😉

**Comment by Discograp** [comment]
> The datetime format is: `dd.MM.yyyy` 😉

yes

![channels4_profile](https://user-images.githubusercontent.com/95682410/236359964-b4e9b7c3-3cc6-4fbe-bed6-7190538e71b5.jpg)

**Comment by Dendraspis** [comment]
Just a short addition to this topic:

Make sure this (default) setting is still set, so timestamps are only extracted, when the source file is MKV and has a variable frame rate (according to MediaInfo):

![image](https://github.com/staxrip/staxrip/assets/50659978/972f9482-14c2-43fb-b33e-98619e714b50)
