### ISSUE TITLE
NVenc Missing/wrong default --bref-mode parameters

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#1007]
**Describe the bug**
Current version of staxrip only 3 parameters for --bref-mode
disabled (default)
each
middle
when select disable (default) its remove ''--bref-mode'' parameter, because real default parameter ''auto'', log file shows
''B frames       3 frames [ref mode: middle]''

---------------------

real default parameters shown in NVenc help
   --bref-mode <string>         set B frame reference mode
                                  - auto (default)
                                  - disabled
                                  - each
                                  - middle

----------------------

**Expected behavior**

Need to add ''auto'' and make it default
Make when select ''disabled'' it sould be added to parameters

**How to reproduce the issue**

Encode with ''disabled'' selected log file shows ''[ref mode: middle]''

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version
StaxRip v2.16
i replace nvenc with lastest version NVEncC_7.24_x64

------------

encode parameters
cqp 20:23:25 --codec h265 --preset quality --output-depth 10 --profile main10 --aq --aq-temporal --lookahead 32

------------

log
NVEncC (x64) 7.24 (r2526) by rigaya, Apr 25 2023 10:16:32 (VC 1929/Win)
OS Version     Windows 11 x64 (22621) [UTF-8]
CPU            AMD Ryzen 5 3600 6-Core Processor [4.00GHz] (6C/12T)
GPU            #0: NVIDIA GeForce RTX 3060 (3584 cores, 1852 MHz)[PCIe3x16][531.79]
NVENC / CUDA   NVENC API 12.0, CUDA 12.1, schedule mode: auto
Input Buffers  CUDA, 44 frames
Input Info     VapourSynthMT r54(yv12(10bit))->p010 [AVX2], 1920x1080, 24000/1001 fps
Vpp Filters    copyHtoD
               ssim psnr (yv12(10bit))
Output Info    H.265/HEVC main10 @ Level auto
               1920x1080p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   CQP  I:20  P:23  B:25
ChromaQPOffset cb:0  cr:0
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       3 frames [ref mode: middle]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on
CU max / min   auto / auto
Others         mv:auto

**Comment by Dendraspis** [comment]
Thanks. Will be fixed when I'm back in a few weeks.
When you want to use this parameter right now, you can use the custom parameter section to add it.

**Comment by Discograp** [comment]
use CPU x265 main10 for 24fps

nvidia 265 main10 GPU badly encodes 24 or 25fps = main10 encodes well 29.97fps or more

or use 264 high Nvidia for 24 or 25fps
