### ISSUE TITLE
(Help) InterFrame

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1008]
do not understand
in BIOS disabled E-cores - 4 pieces

In Hybrid software - in vapour / avi mode, this interframe works without errors
in vapoursynth mode - I do not specify CPU cores
in avisynth mode - I specify 8 CPU cores

video https://drive.google.com/file/d/1jNmmp2EyPpInpT1edYEHA3bzbfDKv6MK/view?usp=share_link

![channels4_profile](https://github.com/staxrip/staxrip/assets/95682410/b6df6d66-97b5-4952-9d05-be6802f321dc)

**Comment by Dendraspis** [comment]
Honestly (without watching the video) I don't understand your question nor what your problem is.  🫤

**Comment by Discograp** [comment]
interframe is broken - does not work

all users will do as I did in this video
