### ISSUE TITLE
Still does not work right, ever

### ISSUE THREAD

**Issue by Adramelramalech** [staxrip/staxrip#101]
Is any body actually using this to encode videos without any issue? Why is it I can't do nothing within this program without issue? I give it settings, it disregards my settings. I can't do templates, batch, multiple jobs, change the script, anything. Think about each and every function of this app, all of them, that, none of that works for me. For me to encode a video I have to fight with stax, open and close stax many times and fight some more before I can get any encode to encode with and how I want. I will make a damn video if I have too. I had enough. This stax does not work right at all, ever.

**Comment by stax76** [comment]
Possible reasons:

You use it in a way it is not designed for or there is a problem with the design, you are not describing a design problem however but only general discomfort, the reason might be because staxrip might not reflect how you used to work or prefer to work, in that case you have to find another application.

You don't understand certain core concepts.

There are bugs.

The biggest issue is lack of good documentation, this might get addressed this year!

**Comment by 44vince44** [comment]
@ Adramelramalech :

We are many people using staxrip to encode videos, I am one of them, I encode videos from many sources (mp4, avi, wmv, flv, ts) to MKV, using x265, and I have no problems at all!
First check this thing: if you have asked staxrup upon first use to store settings in C:\Program Files\Staxrip, then you need to grant read/write/modify permissions for this folder to you as a user. Check this point first.
Stax and the other contributors are doing an excellent job, and the application is very good once you get used to it.

**Comment by Adramelramalech** [comment]
I have how any body is using this nor I have any idea how I could possibly be using it wrong. Open stax. Apply settings. Open source. Click next. Click start. Right? So when I do these steps why is it that stax disregards my settings and uses its own settings? I am not stupid. Nor am I dumb. 

I will start recording video and posting video. This is something I have been dealing with years. I never once actually thought it worked and I am shocked people are using this.

**Comment by Adramelramalech** [comment]
Okay. Not even a full 20 minutes later. I open stax. I click on my saved template. I click add source. I click next and start.
What is this? THESE ARE NOT MY SETTINGS

Error Video encoding using x265 3.2+9-971180b (2.0.2.0)

Video encoding using x265 3.2+9-971180b failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


--------------- Video encoding using x265 3.2+9-971180b ---------------

"C:\Users\************\OneDrive - ************\Desktop\StaxRip-x64-2.0.2.0-stable\Apps\Support\avs2pipemod\avs2pipemod64.exe" -y4mp  | "C:\Users\************\OneDrive - ************\Desktop\StaxRip-x64-2.0.2.0-stable\Apps\Encoders\x265\x265.exe" --pass 1 --bitrate 7767 --output-depth 10 --frames 0 --y4m --stats .stats --output NUL -

avs2pipemod  ver 1.1.1
built on Aug 15 2016 00:32:12
Usage: avs2pipemod [option] input.avs
e.g. avs2pipemod -wav=24bit input.avs > output.wav
avs2pipemod -y4mt=10:11 input.avs | x264 - --demuxer y4m -o tff.mkv
avs2pipemod -rawvideo -trim=1000,0 input.avs > output.yuv
-wav[=8bit|16bit|24bit|32bit|float  default unset]
output wav format audio(WAVEFORMATEX) to stdout.
if optional arg is set, audio sample type of input will be converted
to specified value.
-extwav[=8bit|16bit|24bit|32bit|float  default unset]
output wav extensible format audio(WAVEFORMATEXTENSIBLE) containing
channel-mask to stdout.
if optional arg is set, audio sample type of input will be converted
to specified value.
-rawaudio[=8bit|16bit|24bit|32bit|float  default unset]
output raw pcm audio(without any header) to stdout.
if optional arg is set, audio sample type of input will be converted
to specified value.
-y4mp[=sar  default 0:0]
output yuv4mpeg2 format video to stdout as progressive.
-y4mt[=sar  default 0:0]
output yuv4mpeg2 format video to stdout as tff interlaced.
-y4mb[=sar  default 0:0]
output yuv4mpeg2 format video to stdout as bff interlaced.
-rawvideo[=vflip default unset]
output rawvideo(without any header) to stdout.
-info  - output information about aviscript clip.
-filters - output external plugin filters/functions list to stdout.
-benchmark - do benchmark avs script, and output results to stdout.
-dumptxt - dump pixel values as tab separated text to stdout.
-trim[=first_frame,last_frame  default 0,0]
add Trim(first_frame,last_frame) to input script.
in info, this option is ignored.
-dll[=path to avisynth.dll  default "avisynth"]        specify which avisynth.dll is used.
note1 : in yuv4mpeg2 output mode, RGB input that has 720pix height or more
will be converted to YUV with Rec.709 coefficients instead of Rec.601.
note2 : in fact, it is a spec violation to use WAVEFORMATEX(-wav option)
except 8bit/16bit PCM.
however, there are some applications that accept such invalid files
instead of supporting WAVEFORMATEXTENSIBLE.
note3 : '-extwav' supports only general speaker positions.
Chan. MS channels                Description
----- -------------------------  ----------------
1    FC                         Mono
2    FL FR                      Stereo
3    FL FR BC                   First Surround
4    FL FR BL BR                Quadro
5    FL FR FC BL BR             like Dpl II (without LFE)
6    FL FR FC LF BL BR          Standard Surround
7    FL FR FC LF BL BR BC       With back center
8    FL FR FC LF BL BR FLC FRC  With front center left/right
x265 [error]: unable to open input file <->



StaxRip.ErrorAbortException: Video encoding using x265 3.2+9-971180b failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


--------------- Video encoding using x265 3.2+9-971180b ---------------

"C:\Users\************\OneDrive - ************\Desktop\StaxRip-x64-2.0.2.0-stable\Apps\Support\avs2pipemod\avs2pipemod64.exe" -y4mp  | "C:\Users\************\OneDrive - ************\Desktop\StaxRip-x64-2.0.2.0-stable\Apps\Encoders\x265\x265.exe" --pass 1 --bitrate 7767 --output-depth 10 --frames 0 --y4m --stats .stats --output NUL -

avs2pipemod  ver 1.1.1
built on Aug 15 2016 00:32:12
Usage: avs2pipemod [option] input.avs
e.g. avs2pipemod -wav=24bit input.avs > output.wav
avs2pipemod -y4mt=10:11 input.avs | x264 - --demuxer y4m -o tff.mkv
avs2pipemod -rawvideo -trim=1000,0 input.avs > output.yuv
-wav[=8bit|16bit|24bit|32bit|float  default unset]
output wav format audio(WAVEFORMATEX) to stdout.
if optional arg is set, audio sample type of input will be converted
to specified value.
-extwav[=8bit|16bit|24bit|32bit|float  default unset]
output wav extensible format audio(WAVEFORMATEXTENSIBLE) containing
channel-mask to stdout.
if optional arg is set, audio sample type of input will be converted
to specified value.
-rawaudio[=8bit|16bit|24bit|32bit|float  default unset]
output raw pcm audio(without any header) to stdout.
if optional arg is set, audio sample type of input will be converted
to specified value.
-y4mp[=sar  default 0:0]
output yuv4mpeg2 format video to stdout as progressive.
-y4mt[=sar  default 0:0]
output yuv4mpeg2 format video to stdout as tff interlaced.
-y4mb[=sar  default 0:0]
output yuv4mpeg2 format video to stdout as bff interlaced.
-rawvideo[=vflip default unset]
output rawvideo(without any header) to stdout.
-info  - output information about aviscript clip.
-filters - output external plugin filters/functions list to stdout.
-benchmark - do benchmark avs script, and output results to stdout.
-dumptxt - dump pixel values as tab separated text to stdout.
-trim[=first_frame,last_frame  default 0,0]
add Trim(first_frame,last_frame) to input script.
in info, this option is ignored.
-dll[=path to avisynth.dll  default "avisynth"]        specify which avisynth.dll is used.
note1 : in yuv4mpeg2 output mode, RGB input that has 720pix height or more
will be converted to YUV with Rec.709 coefficients instead of Rec.601.
note2 : in fact, it is a spec violation to use WAVEFORMATEX(-wav option)
except 8bit/16bit PCM.
however, there are some applications that accept such invalid files
instead of supporting WAVEFORMATEXTENSIBLE.
note3 : '-extwav' supports only general speaker positions.
Chan. MS channels                Description
----- -------------------------  ----------------
1    FC                         Mono
2    FL FR                      Stereo
3    FL FR BC                   First Surround
4    FL FR BL BR                Quadro
5    FL FR FC BL BR             like Dpl II (without LFE)
6    FL FR FC LF BL BR          Standard Surround
7    FL FR FC LF BL BR BC       With back center
8    FL FR FC LF BL BR FLC FRC  With front center left/right
x265 [error]: unable to open input file <->


   at StaxRip.Proc.Start() in C:\Users\frank\Daten\Projekte\VB\staxrip\General\Proc.vb:line 338
   at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in C:\Users\frank\Daten\Projekte\VB\staxrip\Encoding\x265Enc.vb:line 65
   at StaxRip.x265Enc.Encode() in C:\Users\frank\Daten\Projekte\VB\staxrip\Encoding\x265Enc.vb:line 42
   at StaxRip.GlobalClass.ProcessVideo() in C:\Users\frank\Daten\Projekte\VB\staxrip\General\GlobalClass.vb:line 227
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in C:\Users\frank\Daten\Projekte\VB\staxrip\General\GlobalClass.vb:line 137

**Comment by Adramelramalech** [comment]
3x times now, been here for almost an hour still have yet to start anything. Why is it I select template then source it does not index, ever until I press start/next but then sometimes I select template source and it auto indexes?

I am sorry to say but this application does not work

**Comment by 44vince44** [comment]
Adramelramalech, the parameters shown in the command line for x265 means that you have not configured it correctly (1 pass 7767: not correct way to use x265).
So I will help you out with this.
Please do these steps then tell me if encounter any problems.
1) download latest staxrip 2.0.6.2 so we are talking about the same version
2) once you extract it to a folder on your desktop, and use it for the first time, ask to save settings in the same folder
3) Go to main window > Apps > Manage
    there you will browse all the apps and check that their status is ok. If not you have to fix.
    You can leave as "not ok" are DGIndexIM, DGIndexNV, dsmux, Haali Splitter, MPC-HC, MPC-BE.
   All apps except those must be OK.

Once you tell me this is valid, I will continue.

**Comment by Adramelramalech** [comment]
I know that. You do not need to tell me how to use x265. I am the last person on the planet you would ever need to tell about x265. Thats the issue. Why is stax using those settings when I specifically told it to use my settings. Exactly what I mean, I give stax settings, it says nah, I aint using those and it decides to use its own crappy settings somehow. One more time, i am not retarded. I am not dumb or stupid. I know what I am doing. that is why i am literally trying to tell someone, anyone that stax does not work. I give an application specific settings and it disregards that, then there is a n issue here

**Comment by 44vince44** [comment]
BTW, I don't think that putting the app in the one drive folder is recommended.

**Comment by Adramelramalech** [comment]
it's on my desktop. i have onedrive desktop back up on

**Comment by 44vince44** [comment]
Did you check the apps have status OK?

**Comment by 44vince44** [comment]
IS Avisynth+ OK?

**Comment by Asphxiated** [comment]
I agree, I can't get this to work, here is a log of trying to have FFmpeg pipe a y4m stream to x265 but then x265 says it can't find the file...

x265 M-3.4+6-g73f96ff39-gcc11.0.0 Patman

"C:\Program Files\StaxRip-x64-2.1.3.0-stable\Apps\Encoders\ffmpeg\ffmpeg.exe" -threads 1 -hwaccel dxva2 -i "D:\Videos\Altered Carbon S01E06 2160p HDR.mkv" -f yuv4mpegpipe -strict -1 -loglevel fatal -hide_banner - | "C:\Program Files\StaxRip-x64-2.1.3.0-stable\Apps\Encoders\x265\x265.exe" --crf 19 --output-depth 10 --hevc-aq --aq-mode 3 --me star --max-merge 4 --fades --frame-threads 3 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --hdr10 --colorprim bt2020 --colormatrix bt2020nc --transfer smpte2084 --range limited --max-cll "10000,1992" --hdr10-opt --repeat-headers --hrd --aud --input-depth 10 --deblock -2:-3 --frames 64297 --y4m --output "D:\Videos\TOS 2160p HDR_temp\TOS.Atmos.5.1.mkv_out.hevc" -

x265 [error]: unable to open input file <->

technically gives me error code 0x1 but says that its meaning is pretty vague.
