### ISSUE TITLE
Aomenc default parameters

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#1012]
Somehow i noticed setting on gui --arnr-strength=0 and adding custom --arnr-strength=0 making different videos so i checked to internet, according to this docs some default parameters need to change.

https://github.com/master-of-zen/Av1an/blob/master/docs/Encoders/aomenc.md

--arnr-maxframes=7
--arnr-strength=5
--lag-in-frames=35

--------------

According to document default
--kf-min-dist=12
--kf-max-dist=9999

staxrip default
--kf-min-dist=0
--kf-max-dist=9999

i suggest dont change staxrip default but change encoder profil to
--kf-min-dist=12
--kf-max-dist=240 or 300
let it added to encoder parameters

---------------

i think --tile-columns=  or --tile-rows= when set to 0 it should be removed from encode parameters.
encoder profile remain --tile-columns=2 --tile-rows=1

---------------

staxrip always adding this 3 parameters

--coeff-cost-upd-freq=0
--mode-cost-upd-freq=0
--mv-cost-upd-freq=0

its not clear what is default on any document i dont see any reason its added always i suggest add empty option to remove from encoding parameters and make empty parameter default
(i didnt see any suggesion they should be always added)

---------------

--static-thresh=0
also always added its not needed to added always
according to this document https://api.encoding.com/reference/adv-av1-libaom
static-thresh=(default=0) but on this doc some defaults wrong i dont trust to much i suggest when set to (0) it should be removed from encoding parameters or stay safe add checkbox to activate in encode parameter and make it not checked by default
(i didnt see any suggesion it should be always added)

----------------

https://forum.doom9.org/showthread.php?p=1965028#post1965028
according to BlueSwordM defaults should be these
--qm-min=5
--qm-max=9

------------

https://forum.doom9.org/showthread.php?t=183907
Although these 3 parameters not defaults BlueSwordM suggested always use. I hope encoder profil change according to. if you think they should be leave as it is i can understand.

```
--enable-qm=1
This enables quantization matrices for aomenc. I have 0 idea why it’s not enabled by default, as it provides free psy and coding gains. Always leave it on no matter what. There are no penalties for enabling it. For reference, the default min-qm table is 5, and the default max-qm table is 9, which is a good choice of constants.
Smaller QM table = steeper quantization matrix(bigger differences between each step)
Bigger QM table = flatter quantization matrix(smaller differences between each step)

--aq-mode=1
I pretty much always recommend aq-mode=1, since encoders are usually not very good at giving bits to low variance spots, and aomenc is no exception to that(in fact, IÂ’d argue it’s not very good at it in the 1st place). It would be nice if the aq-mode=1 also had an AC bias like in x264/x265’s aq-modes

--enable-dnl-denoising=0
disable that pesky denoising was added in 2020, being --enable-dnl-denoising=0.
This bypasses the denoiser entirely, restoring the normal 1st pass speed, making the normal encoding process a bit faster, and giving a higher quality output. In live-action content, it does quite well, which is why I always recommend enabling it for that kind of content. 

```

**Comment by Dendraspis** [comment]
The problem is, that the site, you're referring to, is not the official one not it reflects the official default values. StaxRip tries to stick to the default values, sadly `AOMEnc` does not provide proper default settings for each parameter. But it is what it is...
Nevertheless I made some changes:

```
i suggest dont change staxrip default but change encoder profil to
--kf-min-dist=12
--kf-max-dist=240 or 300
let it added to encoder parameters
```
✔️ 

```
i think --tile-columns= or --tile-rows= when set to 0 it should be removed from encode parameters.
encoder profile remain --tile-columns=2 --tile-rows=1
```
✔️ 

```
staxrip always adding this 3 parameters
--coeff-cost-upd-freq=0
--mode-cost-upd-freq=0
--mv-cost-upd-freq=0
its not clear what is default on any document i dont see any reason its added always i suggest add empty option to remove from encoding parameters and make empty parameter default
(i didnt see any suggesion they should be always added)
```
✔️ 

```
--static-thresh=0
also always added its not needed to added always
according to this document https://api.encoding.com/reference/adv-av1-libaom
static-thresh=(default=0) but on this doc some defaults wrong i dont trust to much i suggest when set to (0) it should be removed from encoding parameters or stay safe add checkbox to activate in encode parameter and make it not checked by default
(i didnt see any suggesion it should be always added)
```
❌ The default value is unclear, so it will be added always to keep consistency. 

```
https://forum.doom9.org/showthread.php?p=1965028#post1965028
according to BlueSwordM defaults should be these
--qm-min=5
--qm-max=9
```
❌  The default values `8 / 15` are taken from the command line help, I don't see any reason to change them.

```
Although these 3 parameters not defaults BlueSwordM suggested always use. I hope encoder profil change according to. if you think they should be leave as it is i can understand.
``` 
❌ Those suggestions are just suggestions, so it's the user who has to chose the best parameters for their needs.

**Comment by darkcity87** [comment]
@Dendraspis 
Thanks.

--arnr-maxframes=7
--arnr-strength=5
I tested when selecting 0 these parameters removed but selecting 0 and adding custom parameters 0 make different videos so for these parameters defaults not 0. So i test again with --arnr-maxframes=7 --arnr-strength=5 and selected 0 (removed parameters) make same ivf video output so defaults should be --arnr-maxframes=7 --arnr-strength=5.

Can you make added when selected 0 and encoder profile 
--arnr-maxframes=7
--arnr-strength=5
they can be added always no harm

-----------
--lag-in-frames=35
selecting 25 removes from parameters but when encoding Encoder parameters shows this
g_lag_in_frames              = 35
so default should be 35 it can be added always

**Comment by Dendraspis** [comment]
```
Can you make added when selected 0 and encoder profile
--arnr-maxframes=7
--arnr-strength=5
they can be added always no harm
```
✔️  Yeah, loos like this are the default values.

```
--lag-in-frames=35
selecting 25 removes from parameters but when encoding Encoder parameters shows this
g_lag_in_frames = 35
so default should be 35 it can be added always
```
✔️ 

Thank you.
