### ISSUE TITLE
Quick Sync Video - Many missing settings under Encoding Options 

### ISSUE THREAD

**Issue by anthony75smith75** [staxrip/staxrip#1016]
Intel Quick Sync Video has many missing settings under "Encoding Options." They can be manually added in under "Other - Custom" and work well this way but the configuration convenience is sorely missed. Other Encoders such as Nvidia and AMD(VCE) have all the necessary options present so these should be very easy to add for QSV.

Examples of missing settings I have tested and found working well in the "Other - Custom" section:
--vpp-tweak brightness=0.0,contrast=1.0,gamma=1.0,saturation=1.0 
--vpp-unsharp 
--vpp-colorspace hdr2sdr=hable,source_peak=1000.0,ldr_nits=100.0

**Comment by Discograp** [comment]
try this 7,42 https://github.com/rigaya/QSVEnc/releases

- Now QSVEnc will continue working even if it fails to initialize OpenCL

**Comment by Dendraspis** [comment]
> so these should be very easy to add for QSV

Not really. 😅  Copying is often impossible, because of various differences, and even they are the same, you have to check every option and compare it with the documentation. And that's truly time consuming, especially for an encoder, that is barely used by the users.

So you would like to have those VPP-parameters included?

**Comment by anthony75smith75** [comment]
Would be useful as it makes StaxRip more consistent and is convenient and useful for us users. Have tested the above options at least and found them to be working well. I can test some other options if you need help. QSV barely used? Seems to encode well, though not as fast as Nvidia and AMD GPU encoders.

**Comment by Discograp** [comment]
this problem in intel gpu - QSVEnc - GPU newbie

AMD/ATI and Nvidia - experienced

**Comment by Dendraspis** [comment]
> QSV barely used? Seems to encode well, though not as fast as Nvidia and AMD GPU encoders.

According to the last poll I started a while ago:  yes.
The thing is, that x265 is the encoder to go with when it comes to quality and file size. Also it's CPU independent and has a very good documentation, so the chance is higher to get help with some tweaks. 
x265 cannot apply filters like `--vpp-unsharp`, but therefore you have AviSynth/VapourSynth with a lot more possibilities. 

But when I have some time, I'll try to add some more parameters.

**Comment by anthony75smith75** [comment]
Agree there are many more options on x265 and even more with the addition of VapourSynth. It can actually end up as a brutal overload scenario for someone who doesn't encode all the time. Some simple optimized profiles actually included with StaxRip could help in this area. Do you have a best size quality profile for x265 that you could share?

**Comment by Dendraspis** [comment]
Oh sorry, seems I haven't seen your post.  🥴 

> Do you have a best size quality profile for x265 that you could share?

The most important rule in encoding is: There ist no "best setting" that fits all needs and expectations. Beside the biggest compromise between quality and file size, there are differences in visual recognition - don't know how to call it better. One would say a given setting is the best, whereas you see flickering, ghosting or similar. The best way is to chose a difficult source file with fast movement as well as slow scenes with darker colors and try a few settings out and compare the results.

But basically the best way to start is using 10bit output depth and the *Slow* preset:
`--preset slow --output-depth 10 --profile main10`
One of those very often discussed parameters is `--aq-mode 3`, that some prefer over the default `2`, but I disagree at all.
Depending on your preferences, using one or both of these settings might be good for you:
`--no-sao`  and/or `--no-strong-intra-smoothing`
Oh yeah, and choose `--crf 20` as starting point.

But we're off topic now....
I keep your request in mind any maybe someone else posts some explicit parameters, because to be honest for the moment I don't wanna waste time on this encoder looking for missing or wrong parameters.

**Comment by anthony75smith75** [comment]
Thanks for the x265 options above. Have actually used the Intel QSV Encoder some more and can highly recommend this Encoder! It is much slower than other GPU encoders, (AMD/VCE, Nvidia/NVEnc) but the quality is MUCH BETTER! B and LTR frames are supported along with very easy HDR to SDR conversion. (Not easy with x265 and other Staxrip options) Built in GPU Detail Enhancer and DeNoise Reduction options (also not available with x265) work a treat with sharpness and cleaning up older grainy film sources. Feeling this GPU encoder finally rivals x265 CPU encoding for file size and quality. Seriously NOT a waste of time! Please add the missing options: HDR->SDR and Tweak as I have tested these and can confirm they work perfect!

**Comment by Dendraspis** [comment]
> It is much slower than other GPU encoders, (AMD/VCE, Nvidia/NVEnc) but the quality is MUCH BETTER!

Could be related to more efficient settings that makes it slower, but better. It might be the same like using Preset `Slow` over `Medium`. Nevertheless it is always a subjective decision, some would agree, some disagree. But as long as you're happy with it: Go with it.  👍 

> very easy HDR to SDR conversion

Indeed.

> Built in GPU Detail Enhancer and DeNoise Reduction options (also not available with x265)

One of the most common examples could be [FFT3DGPU](http://avisynth.nl/index.php/FFT3DGPU), that is built-in. Even if not, other scripts can be imported/used individually.

> work a treat with sharpness and cleaning up older grainy film sources

Always very personal preferences regarding the look and result.  😁 

> Please add the missing options: HDR->SDR and Tweak as I have tested these and can confirm they work perfect!

I'll try to implement them for the next release.

**Comment by anthony75smith75** [comment]
Thanks for your support. The end result is indeed always subjective as people evaluate a quality encode differently. Where are the AviSynth presets for HDR to SDR conversion? I have never actually been able to find any settings for this in Staxrip using AviSynth and x265.

**Comment by Dendraspis** [comment]
Pretty simple: Right-click on AVS Filters box, then `Add/Insert/Replace » Color » HDR to SDR`.  😁

**Comment by anthony75smith75** [comment]
Thank you for adding many of the missing features and options. Don't know how to reopen this issue and am hoping that it can still be seen. Noticed some less used options are still missing like the extra de-noise and de-interlace tabs the other GPU encoders have. Have added --vpp-pmd in the OTHER section at end (for extra noise removal) and found it working perfectly in addition with the current (BETTER Intel QSV hardware) de-noise option already present. I suspect the many extra de-interlace options will also work perfectly though I have not actually tested these. All nice to have options in the GUI, though we need the best Intel QSV hardware ones listed first or in a more prominent way as these are better and should be tried first.

**Comment by anthony75smith75** [comment]
As some of you will know, this page lists the many options available on the Intel QSV encoder command line. Some options are more useful than others and not every option actually works in every scenario either. Therefore, important to have some order in our Staxrip presentation of these many options. 

https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-pmd-param1value1param2value2

**Comment by Dendraspis** [comment]
I have added `--vpp-pmd` and `--vpp-denoise` for the next release.

I know there are more missing, so if you need/find one, please reopen this issue and write it/them down (preferable with a link to the Option like above) and I'll try to add them asap.
