### ISSUE TITLE
Crash when adding an AA filter

### ISSUE THREAD

**Issue by Izorkin** [staxrip/staxrip#1017]
**Describe the bug**
Crash when adding an Anta-Aliasing filter.

**How to reproduce the issue**
1. Open video file.
2. Change source to FFVideoSource.
3. Add Anta-Aliasing filter MAA2.

**Provide information**
- Used StaxRip version 2.19.0.

**Comment by Discograp** [comment]
Requirements
- Progressive - input only

or = or am i wrong?

**Comment by Izorkin** [comment]
Yes, scan type - progressive.
Mediainfo:
```
Format                      : VC-1
Format profile              : Advanced@L3
Codec ID                    : V_MS/VFW/FOURCC / WVC1
Codec ID/Hint               : Microsoft
Duration                    : 22 min 37 s
Bit rate                    : 10.5 Mb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Compression mode            : Lossy
Bits/(Pixel*Frame)          : 0.211
Stream size                 : 1.66 GiB (94%)
Title                       : VC-1 Video / ~9000 kbps / 1080p / 23.976 fps / 16:9 / Advanced Profile 3
Language                    : English
Default                     : Yes
Forced                      : No
```

**Comment by Izorkin** [comment]
If use manual avs script from console:
```
x265.exe --reader-options library=...\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll ... test.avs
...
avs+ [INFO]: using external Avisynth library from: "Z:\#Apps\Video\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll"
avs+ [INFO]: AviSynth+ 3.7.3 (r3982, 3.7, x86_64)
```
Encoding does not start.
If change AviSynth.dll to version AviSynth+ 3.7.2 (r3661, 3.7, x86_64) then it starts working fine.
```
x265.exe --reader-options library=c:\Windows\System32\AviSynth.dll ... test.avs
...x265.exe --reader-options library=c:\Windows\System32\AviSynth.dll
...
avs+ [INFO]: using external Avisynth library from: "c:\Windows\System32\AviSynth.dll"
avs+ [INFO]: AviSynth+ 3.7.2 (r3661, 3.7, x86_64)
avs+ [INFO]: 1920x1080 fps 24000/1001 i420p8 frames 0 - ...
raw  [INFO]: output file: "...\test.hevc"
```

**Comment by Dendraspis** [comment]
Please copy/move StaxRip from `Z:\#Apps\Video\StaxRip\` to `D:\StaxRip\` or even better a local drive and test it again to exclude `#Apps` as possible culprit.
Also make sure you have all permissions on that drive/folder.

**Comment by Izorkin** [comment]
Error:
```
Script Error

Cannot load file 'C:/StaxRip-v2.19.0-x64/Apps/Plugins/AVS/JPSDR/Plugins_JPSDR.dll'. Platform returned code 1114:
A dynamic link library (DLL) initialization routine failed

(C:\StaxRip-v2.19.0-x64\Video\Example_temp\Example.avs, line 6)
```

**Comment by Dendraspis** [comment]
What CPU do you have on that machine?

**Comment by Izorkin** [comment]
Xeon X3470. This is on the second computer.
On main computer, program silently closes, even if run it from `C:\StaxRip-v2.19.0-x64\`.

I assume that the problem may be with AviSynth itself. Opened the ticket - https://github.com/AviSynth/AviSynthPlus/issues/361

**Comment by Dendraspis** [comment]
That's why providing information is so important.  😉 

[Intel OpenCL drivers could be required for some processors (Xeon, ...) to run some filters (KNLMeansCL, QTGMC, ...)](https://github.com/staxrip/staxrip/wiki/Intel-OpenCL-drivers-could-be-required-for-some-processors-%28Xeon%2C-...%29-to-run-some-filters-%28KNLMeansCL%2C-QTGMC%2C-...%29)

In your case you have to use another version of JPSDR, probably the AVX version instead of AVX2.

**Comment by Izorkin** [comment]
> In your case you have to use another version of JPSDR, probably the AVX version instead of AVX2.

Thanks. Problem resolved!
