### ISSUE TITLE
QSVEnc 7.43

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1018]
when I replaced the files in staxrip (2.19.00), I did not automatically determine that this was not a new version and continued to work.

before when I changed it, then I determined that it was new and offered to change the name

====================

replaced NVEnc (7.23) with the new files

Everything is fine

PS https://github.com/rigaya/QSVEnc/issues/146#issue-1740767449

**Comment by Dendraspis** [comment]
This is not a bug or issue in any way - it's a feature that exists for years meanwhile. When you change a version, there are some days of tolerance to the next "app version wrong" message.

So the only problem here is that rigaya was too fast releasing a new version.  😄 ..or you wanting the newest versions too quick. 😉
