### ISSUE TITLE
Allow opus as valid input for MP4 container when using MP4Box

### ISSUE THREAD

**Issue by jalba69** [staxrip/staxrip#102]
Hi stax,

Like said on the forum, MP4Box allows since last summer opus as input for audio, will be nice to allow it in Staxrip too.

Right now we get a warning when trying to use opus and mp4 container.

(Flac input is also supported in version 0.9 of MP4Box from the Filters Branch but 0.9 have some little issues for now so i won't recommend using it in Staxrip for now, version 1.0 should not take too long to come out tho and hopefully it will be fixed by then ) see https://github.com/gpac/gpac/issues/1133

Thank you.

**Comment by stax76** [comment]
Last build has it enabled.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS
