### ISSUE TITLE
SVPflow & FFTW could be updated...

### ISSUE THREAD

**Issue by Nuihc88** [staxrip/staxrip#1020]
Regarding this entry in the changelog of StaxRip v2.20.0:
> - Update Dual plugins
>   - SVPflow v4.2.0.133 (due to usage changes (red rectangle around the video frame))

The last SVPflow2 versions to not have that problem were v4.3.0.161 builds. The GPL'd SVPflow1 v4.5.200 library isn't affected by this problem either. [Here's a link to my copies of these files](https://www.mediafire.com/file/8nsvbvsm94ahvsq/SVPFlow.7z/file) (renamed to match StaxRip naming convention).

PS. Also FFTW could be updated from v3.3.8 to v3.3.10 [from here](https://forum.videohelp.com/attachments/61295-1634326839/FFTW-3.3.10-DLLs.rar), has some quality regression fix and updating manually hasn't caused any problems for me yet.

**Comment by Dendraspis** [comment]
Also related:  https://github.com/staxrip/staxrip/issues/1013#issuecomment-1567724346

**Comment by Dendraspis** [comment]
Thank you for providing those files and links. Both apps/filters are updated and ready for the next release.  👍

**Comment by Nuihc88** [comment]
@Dendraspis
Is there a reason FFTW was rolled all the way back to v3.3.5 (from 2016) in StaxRip v2.23.0 release?
Seems like a mistake as the official windows builds are never up to date or maintained / supported in any meaningful way.

**Comment by Dendraspis** [comment]
Yes, compatibility reasons when using filters, that use FFTW.

As far as I can see `v3.3.5` is the latest version for Windows and that version works without issues so far. So it seems there are some differences between those OS versions and/or functions changed and so cause errors.

**Comment by Nuihc88** [comment]
@Dendraspis That's weird, it should always remain backwards compatible from what i've read.

Can you show me the steps needed to encounter those compatibility problem(s)?

I have previously compiled FFTW a few times as a dependency for another project, so if i am able to reproduce those errors on my end, i could look into what is causing them. It could be something simple like a compiler switch or needing to compile in XP compatibility mode for a filter requiring it...

**Comment by Dendraspis** [comment]
And I also would expect it to be the same, but it is not for whatever reason. Took me a while to find out what caused the error message due to cascaded dependencies. At least it's pretty easy to reproduce it:
Open a file (shouldn't matter what type of file), choose `VapourSynth` and add `Noise » TemporalDegrain2`.

With `v2.22.0`:
![image](https://github.com/staxrip/staxrip/assets/50659978/6cd2c15f-f1ac-4a79-862c-b90e0cf01335)

With `v2.23.0`:
![image](https://github.com/staxrip/staxrip/assets/50659978/b9a2cc9f-1e0d-4790-ba34-c79a6b468456)



PS:  Please stop pinging me - I see every message in my notifications.  🙂

**Comment by Nuihc88** [comment]
While trying to reproduce the problem i encountered a bunch of unrelated errors relating to still being on Win7 and newer Python & MKVToolNix dropping support for it, but luckily compatible versions still exist [here](https://github.com/adang1345/PythonWin7) & [here](https://forum.videohelp.com/threads/405407-NON-OFFICIAL-Windows-builds-of-MKVtoolnix/page5#post2696022).

As i was spending most of the day setting up a fresh development environment in VirtualBox, i was also researching possible causes and found [this fairly recent commit](https://github.com/FFTW/fftw3/commit/a983a1f01f216bb55aacb3ae5dccea4c03b58bc9) about an issue concerning Cmake builds always requiring SIMD support at run time, which looked like a very likely cause for random errors or crashes, but while looking for more detailed instructions as my early compilations were all failing few seconds in, i then happened to discover some very recently [patched 64bit FFTW 3.3.10 builds](https://www.mediafire.com/file/ywrbo83ybfdhdzj/win-64_fftw-3.3.10-nompi_h38027f0_108.7z/file) already existing on conda-forge software repository...

Only after downloading those newer patched .dlls and copy-pasting the filenames from StaxRip for testing i realized what was actually going on here: On v2.20.0 those files were named libfftw3f-3.dll & libfftw3-3.dll, while on v2.21.0 & v2.22.0 those files were named libfftw3f-3.dll & libfftw3**l**-3.dll, so i removed the L and the error was gone.

**Comment by Dendraspis** [comment]
After just renaming the file, I get another error message:
![image](https://github.com/staxrip/staxrip/assets/50659978/e4b20374-e2cf-4eda-8c84-de00cb461ef3)

But after many tries, copying and renaming I've managed to update it to `v3.3.10` without error messages, at least for what I've tested.  🙄 

So the next release will be `FFTW v3.3.10` again.  👍

**Comment by Nuihc88** [comment]
Did some more research and looks like the file with 'f' in it's name is for single precision, while the file with 'l' in it's name is for long-double precision, the file with no extra letters being for regular double precision.

On some compilers on the Windows platform long-double and double are sometimes interchangeable due to both effectively running as double precision, but it's not necessarily always the case. So unless there are more errors, using the patched single and double precision builds and the unpatched long-double precision build is probably for the best; although i'm not sure which, if any, plugins actually use the long-double precision version at all; guess some might preferencially use the most precise one found.

**Comment by Dendraspis** [comment]
Currently there should be the regular v3.3.10 dlls with `f`  and `l` in the name as well as a patched v3.3.10 dll for the non-specific file name.

That was the only combination I could find that worked for multiple filters without producing error messages or crashing StaxRip.

But I will test your combo, too....

**Comment by Nuihc88** [comment]
The 'date modified' tells me it's the wrong version in there at the moment; dated 2016 rather than 2023.
Also, even the v3.3.8 that was there in v2.20.0 would be a better option than going back to v3.3.5.....

If there are unresolved errors left, i can continue looking into them as long as i can reproduce them.

**Comment by Dendraspis** [comment]
> even the v3.3.8 that was there in v2.20.0 would be a better option than going back to v3.3.5

Totally blind because of archives and renames.  😅   Was happy to find a combination, that works.
But I have checked your combo and it also works for me, at least I couldn't find a filter that doesn't like it.

So it will be used for the next release. Thanks.
