### ISSUE TITLE
Trim function

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1022]
function - Go to TIME

make it visible and place it on the top left

![321](https://github.com/staxrip/staxrip/assets/95682410/c5709b85-d08d-45d7-ab7f-e220ffc79813)

**Comment by Dendraspis** [comment]
> make it visible

As proven by you via screenshot, it is already visible, so **done**.

> place it on the top left

Just grab it and move it to the upper right?!  🤓 
"Right", because in the upper left there are already the video information placed.  😁

**Comment by Discograp** [comment]
just start the preview
and you will see / understand

**Comment by Dendraspis** [comment]
I have done it before answering you - no problem found.  🤔
