### ISSUE TITLE
AOMEnc has wrong "Matrix Coefficients" parameter as selectable option

### ISSUE THREAD

**Issue by pat-e** [staxrip/staxrip#1023]
This is in Version StaxRip v2.20.0

The AOMEnc has the wrong selectable option under "AV1 Specific 6" for "Matrix Coefficients":

Selectable is "BT2020NC", but it should be "BT2020NCL" (so the L is missing):
![wrong_matrix_coefficients](https://github.com/staxrip/staxrip/assets/11069987/e6622fe1-6c6e-4c88-80f2-bc5a24cead6f)

Thanks in Advance.

**Comment by Discograp** [comment]
Please! add the media info of the file

**Comment by Dendraspis** [comment]
Thanks for the report - will be fixed in the next release.  👍

**Comment by pat-e** [comment]
@Discograp : You can get the parameters directly from the AOMEnc.exe within the Staxrip direcotry:

Use Powershell:

Go to folder "Staxrip\Apps\Encoders\AOMEnc" and enter

.\aomenc.exe --help | select-string -Pattern matrix-coefficients -Context 0,1

![aomenc_parameters](https://github.com/staxrip/staxrip/assets/11069987/f8377467-5000-4707-aa6b-2793899d2e56)

There you can see, that the parameter is "bt2020ncl" 😄 
So no need for media info of the file, as simply the parameter missed the "L" at the end.

Thanks to @Dendraspis for fixing it. 👍
