### ISSUE TITLE
SVT-AV1 update - speeding up the higher quality presets by 30-40%

### ISSUE THREAD

**Issue by neoOpus** [staxrip/staxrip#1024]
[Intel and Netflix's SVT-AV1 gains up to 40% performance boost, AMD Ryzen will benefit too](https://www.neowin.net/news/intel-and-netflixs-svt-av1-gains-up-to-40-performance-boost-amd-ryzen-will-benefit-too/) 

Encoder

Improve the tradeoffs for the random access mode across presets M1-M13:
Speeding up the higher quality presets by 30-40%
Improving the BD-rate by 1-4% for the faster presets
Improve the tradeoffs for the low delay mode for both screen content and non-screen content encoding modes
Add a toggle to remove the legacy one-frame buffer at the input of the pipeline allowing the low delay mode to operate at sub-frame processing latencies
Add a new API allowing the user to specify quantization offsets for a region of interest per frame

**Comment by Dendraspis** [comment]
I guess the purpose of copying the changelog is requesting an update?

**Comment by neoOpus** [comment]
[**@Dendraspis**](https://github.com/Dendraspis) commented on [Jun 20, 2023, 3:20 PM EDT](https://github.com/staxrip/staxrip/issues/1024#issuecomment-1599374744 "2023-06-20T19:20:16Z - Replied by Github Reply Comments"):
> I guess the purpose of copying the changelog is requesting an update?

It's important to tell people about the change and make it happen faster. Some developers might not know about it for a week or two. I understand that is not the proper way to do it, but I am unable to formulate requests properly.

**Comment by Dendraspis** [comment]
A short "please update SVT-AV1, here is the link" would have been fine. 😁
I will update it soon. 👍

**Comment by darkcity87** [comment]
![Ekran görüntüsü 2023-06-24 111221](https://github.com/staxrip/staxrip/assets/12258051/eb64cf91-4030-44f9-9baa-115a90a7ef0e)
https://gitlab.com/AOMediaCodec/SVT-AV1
You can update yourself untill next update.

**Comment by Dendraspis** [comment]
Updated, therefore closed.  😁
