### ISSUE TITLE
Quick Sync slower with every sucessive Windows version.

### ISSUE THREAD

**Issue by sportniik** [staxrip/staxrip#1025]
I have been using StaxRip for past few months and have experienced very odd behavior from Intel quick sync Hw acceleration.

I have tried to use Quick sync on Win 8.1 , 10 and 11. What I experienced is drop in FPS in converting a TS MPEG-2 file to MP4 h.264.
In WIN 8.1 I get 450 FPS , 400 FPS in WIN 10 and 350 FPS in WIN 11.
I take QSVEncC (Intel) encoder with h.264. Under decoder I chose QSVEnc Hardware.

Does someone have explanation for this? I use no dGPU. I have tried this on same computer with same hardware. Anyone with similar experience?

Thank you for answers!

**Comment by Dendraspis** [comment]
Did you use the same StaxRip and QSCEnc versions with the same settings on all Windows versions?
Or did you experienced it across different/newer versions of StaxRip and QSCEnc?

**Comment by sportniik** [comment]
Same StaxRip and QSVEncC, same settings same hardware. I was using a Coffee Lake i7, that is all in terms of acceleration.
I will install a WIN2GO all 3 versions on a fast USB with rufus and see if this behavior persists.
I would have tried that on a i5 1135G7 (tiger lake), but there are no graphic drivers for Win 8.1 version and QSV would not work.

**Comment by sportniik** [comment]
OK. I finally did it. I tested WIN 11 WIN 10 and WIN 8.1 performance. Same result. WIN 11 gets 350-400 FPS. WIN 10 400 FPS. WIN 8.1 gets 460 FPS.
BUT !!! I also went to PC with tiger lake CPU and Iris Xe iGPU and WIN 11. There with same settings same StaxRip FPS were ONLY 350 and no more. So absolutely ridiculous.

BUT! I do not think this is StaxRip fault. I also tested performance in DVDFab 12 and it also underperformed in Win 11 / 10 in both Coffeee and Tiger lake CPUs.

**Comment by Discograp** [comment]
look

![12222](https://github.com/staxrip/staxrip/assets/95682410/9b232ea9-b0cf-4628-89f6-5427cba78ec2)

**Comment by sportniik** [comment]
Discograp thank you for guide! But sadly has not changed much. It raises FPS for ca 20 frames, but slows down the process also. So from 9 min to 17 min. I think the problem is solely in bad drivers and sloppy new OS.

I was interested, if drivers in older OS runs faster than in new one for other user too.

If someone wants to try, just take rufus and install the WIN2GO on a USB or external SSD and boot WIN from it; no need to make a clean install on internal drives.

**Comment by Discograp** [comment]
Weird

different problems appear when I use QSVEnc 265
and when I use 264 then there are no problems

**Comment by sportniik** [comment]
But as I have mentioned. It is not StaxRip, it also happens in other encoding software like DVDFab 12. Performance drops more with newer hardware/drivers.
As I pointed out, Iris Xe graphics were the poorest of all and they should have been by far stronger than 8th gen UHD630.

**Comment by Dendraspis** [comment]
In that case I agree, that it should (or must) be related to Windows, QSVEncC or/and the used drivers for each OS. Would be interesting to find out what and why as the speed difference is pretty huge, but that is nothing we can discuss here.

Because it seems not being related to StaxRip, I'll close it. If there are hints it could be related to StaxRip, feel free to reopen it.
