### ISSUE TITLE
About MP4Box and mediainfo reporting mp4box metadata.

### ISSUE THREAD

**Issue by jalba69** [staxrip/staxrip#103]
Hi Stax,

related issues : 
https://github.com/staxrip/staxrip/issues/53 and also in particular this one closed but apparently it doesn't work in last beta 2.0.6.2 for what i could see when testing it on a fresh profile : https://github.com/staxrip/staxrip/issues/64

There is 2 ways to fix this, adding for the video track the same thing a on audio tracks when no specific title is set by the user: **:name="**  at the end of the video stream
`-add video.mp4#video:name="`
`-add video_stream.hevc#video:name="`
Leaving it empty like this brings no metadata for the tittle of the video stream, same as it is doing on the audio stream.

Another possibility is to add the **-no-test** switch in MP4box, this removes the metadata and also  the "Encoded date" & "Tagged date" data from the mp4

Thank you.

**Comment by Patman86** [comment]
Hi Jalba,

I've opened a pull request for that

[fix tagging mp4 files](https://github.com/staxrip/staxrip/pull/108/commits/9327c3018c8796d1e7fe71032de3c7ec5a97549d)

**Comment by jalba69** [comment]
Hi Patman86,

Perfect, this should fix the weird display of MP4Box version as tittle for the video track in Mediainfo.

Thanks a lot
