### ISSUE TITLE
3 passes(x264)

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1031]
when I change the mode to 3 passes(x264)

Then

after 1 pass shows the 3rd pass, should show the 2nd pass

and after 2nd pass it shows the 2nd pass, should show the 3rd pass

PS

![002 Davinci](https://github.com/staxrip/staxrip/assets/95682410/4082d0e8-a07a-43a9-ab60-327655a00dbd)

**Comment by Dendraspis** [comment]
Where?!

**Comment by Discograp** [comment]
up

**Comment by Dendraspis** [comment]
That's how multi pass works. 😁
