### ISSUE TITLE
NVEnc and QSVEnc

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1032]
saw a lot of fixes 

If I upgrade later, then these fixes will be lost?

NVEnc and QSVEnc

**Comment by Dendraspis** [comment]
What do you mean by "lost"? You can update whenever you want. Or is there anybody who forces you to update now?  😯

Download, extract and import all needed settings by hand is the recommended way to update StaxRip.
You could also copy the Settings folder to the new destination or use the user profile folder to share the settings, but that can cause unwanted side effects, so if there aren't tons of settings, events , etc, it's better to set it up by hand.

**Comment by Discograp** [comment]
ok

1- https://github.com/staxrip/staxrip/issues/1031#issue-1780041278

2- https://github.com/staxrip/staxrip/issues/1022#issue-1762537963

**Comment by Dendraspis** [comment]
What do you try to tell me?
