### ISSUE TITLE
bug prores 422 mov clip = clip.resize.Bicubic(matrix_s = '709', format = vs.YUV420P8)

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#1033]
i make prores 422 Hq mov by topaz video ai

file index and load 

VapourSynth auto add line 

clip = clip.resize.Bicubic(matrix_s = '709', format = vs.YUV420P8)
preview or encoding start error

maybe  matrix_s = '709' 

i change line 

clip = core.fmtc.resample (clip, css="420")
clip = mvsfunc.ToYUV(clip, matrix='709')
clip = core.fmtc.bitdepth (clip, bits=8)

**Comment by Dendraspis** [comment]
1. Can you provide a short sample file? Because it doesn't produce any errors with my test files.
2. The auto chroma subsampling to 4:2:0 can be enabled and disabled in the settings:
![image](https://github.com/staxrip/staxrip/assets/50659978/de63dec3-2cb5-43af-b5f5-2e32c8126ebe)

**Comment by DandyClubs** [comment]
[https://ibb.co/przDxVf](error image)

[https://we.tl/t-omVpB5SSS7](test video)

Topaz Video Ai 3.3.0 
prores 422 HQ 


> 1. Can you provide a short sample file? Because it doesn't produce any errors with my test files.
> 
>     2. The auto chroma subsampling to 4:2:0 can be enabled and disabled in the settings:
>        ![image](https://user-images.githubusercontent.com/50659978/250782466-de63dec3-2cb5-43af-b5f5-2e32c8126ebe.png)

**Comment by Dendraspis** [comment]
Okay, now I understand what your problem is. 😅

I think this is a (very interesting) bug in the old VapourSynth R54 version we use in StaxRip. We will update to the newest VapourSynth version soon (no promise), so I doubt I will fix it for the old one, but we'll see and I definitely try to check it with the latest VapourSynth R63 when implementing.

**Comment by Dendraspis** [comment]
Would it be possible to share your sample one more time?

**Comment by DandyClubs** [comment]
[Test Video](https://we.tl/t-lZpDzucfbO)

**Comment by Dendraspis** [comment]
Great, thanks. And with the newest VapourSynth it's the same problem.

I'll test a bit and come back then...
