### ISSUE TITLE
Direct encoders feed

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1036]
Would be possible to have direct feed to the encoders, without having to pass thru a frame server?

Many of the included ones can directly read a video stream, such as x26* and NVEnc.

Could you expose them directly, using StaxRip just as a GUI for them?

**Comment by Dendraspis** [comment]
Nope, that's the main structure of StaxRip, which is not a GUI for one or multiple encoders. GUIs mostly use libraries so they can open the source, convert it internally (mostly with ffmpeg-libraries) to feed the library, StaxRip on the other hand uses command line binaries and AviSynth/VapourSynth to feed them.
StaxRip is meant to be used as a man in the middle between a video file, AviSynth/VapourSynth and an encoder.
