### ISSUE TITLE
Allow .bmp extensions for cover picture when using MKV container

### ISSUE THREAD

**Issue by jalba69** [staxrip/staxrip#104]
Hi Stax,

right now when browsing for a picture to use as cover in the MKV container only jpg & png are allowed via the browse files selector, .bmp's can be added too.

Thanks

**Comment by stax76** [comment]
Hello jalba69,

last build supports it.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS
