### ISSUE TITLE
problem occurred when  I converted  flac in mkv to aac in mp4 

### ISSUE THREAD

**Issue by exgilgamesh** [staxrip/staxrip#1040]
Error Audio Encoding 2 (v2.22.0)

Audio Encoding 2 returned exit code: 2 (0x2)

-------------------------- Audio Encoding 2 --------------------------

qaac 2.80

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 --normalize "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2.flac" -o "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2_1831780736.m4a"

ERROR: 193: CoreAudioToolbox.dll

StaxRip.ErrorAbortException: Audio Encoding 2 returned exit code: 2 (0x2)

-------------------------- Audio Encoding 2 --------------------------

qaac 2.80

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 --normalize "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2.flac" -o "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2_1831780736.m4a"

ERROR: 193: CoreAudioToolbox.dll

   在 StaxRip.Proc.Start() 位置 D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:行号 361
   在 StaxRip.GUIAudioProfile.Encode() 位置 D:\Code\Github\staxrip\staxrip\Source\General\AudioProfile.vb:行号 853
   在 StaxRip.GlobalClass._Closure$__._Lambda$__120-5() 位置 D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:行号 337
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 StaxRip.GlobalClass.ProcessJob(String jobPath) 位置 D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:行号 371

**Comment by exgilgamesh** [comment]
------------------------- System Environment -------------------------

StaxRip    : v2.22.0
Windows    : Windows 10 Home China 2009
Language   : Chinese (Simplified, China)
CPU        : AMD Ryzen 9 7945HX with Radeon Graphics
GPU        : NVIDIA GeForce RTX 4060 Laptop GPU
Resolution : 2560 x 1600
DPI        : 144
Code Page  : 936

----------------------- Media Info Source File -----------------------

C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv

General
Complete name                : C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv
Format                       : Matroska
Format version               : Version 4
File size                    : 1.28 GiB
Duration                     : 24 min 2 s
Overall bit rate mode        : Variable
Overall bit rate             : 7 654 kb/s
Frame rate                   : 23.976 FPS
Encoded date                 : 2018-08-13 09:44:39 UTC
Writing application          : mkvmerge v19.0.0 ('Brave Captain') 64-bit
Writing library              : libebml v1.3.5 + libmatroska v1.4.8

Video
ID                           : 1
Format                       : AVC
Format/Info                  : Advanced Video Codec
Format profile               : High@L4.1
Format settings              : CABAC / 4 Ref Frames
Format, CABAC                : Yes
Format, Reference frames     : 4 frames
Codec ID                     : V_MPEG4/ISO/AVC
Duration                     : 24 min 2 s
Bit rate                     : 5 032 kb/s
Width                        : 1 920 pixels
Height                       : 1 080 pixels
Display aspect ratio         : 16:9
Frame rate mode              : Constant
Frame rate                   : 23.976 (24000/1001) FPS
Color space                  : YUV
Chroma subsampling           : 4:2:0
Bit depth                    : 8 bits
Scan type                    : Progressive
Bits/(Pixel*Frame)           : 0.101
Stream size                  : 865 MiB (66%)
Writing library              : x264 core 155 r2901 7d0ff22
Default                      : Yes
Forced                       : No

Audio #1
ID                           : 2
Format                       : FLAC
Format/Info                  : Free Lossless Audio Codec
Codec ID                     : A_FLAC
Duration                     : 24 min 2 s
Bit rate mode                : Variable
Bit rate                     : 1 360 kb/s
Channel(s)                   : 2 channels
Channel layout               : L R
Sampling rate                : 48.0 kHz
Frame rate                   : 11.719 FPS (4096 SPF)
Bit depth                    : 24 bits
Compression mode             : Lossless
Stream size                  : 234 MiB (18%)
Writing library              : libFLAC 1.2.1 (2007-09-17)
Default                      : Yes
Forced                       : No
MD5 of the unencoded content : A51D1B599891A26FA9E152EB899190AE

Audio #2
ID                           : 3
Format                       : FLAC
Format/Info                  : Free Lossless Audio Codec
Codec ID                     : A_FLAC
Duration                     : 24 min 2 s
Bit rate mode                : Variable
Bit rate                     : 1 259 kb/s
Channel(s)                   : 2 channels
Channel layout               : L R
Sampling rate                : 48.0 kHz
Frame rate                   : 11.719 FPS (4096 SPF)
Bit depth                    : 24 bits
Compression mode             : Lossless
Stream size                  : 216 MiB (16%)
Writing library              : libFLAC 1.2.1 (2007-09-17)
Default                      : No
Forced                       : No
MD5 of the unencoded content : 069DACC19E61F4AD60BE3038784540D9

Menu
00                           : 00:00.000                             : en:Chapter 01
00                           : 01:18.996                             : en:Chapter 02
00                           : 02:49.044                             : en:Chapter 03
00                           : 12:14.067                             : en:Chapter 04
00                           : 22:51.078                             : en:Chapter 05

------------------------- Demux xml chapters -------------------------

mkvextract 77.0

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Support\MKVToolNix\mkvextract.exe "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv" --ui-language en chapters "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_chapters.xml"

File 'C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv': container: Matroska
Track ID 0: video (AVC/H.264/MPEG-4p10)
Track ID 1: audio (FLAC)
Track ID 2: audio (FLAC)
Chapters: 5 entries

Start:    14:52:07
End:      14:52:08
Duration: 00:00:00

------------------------- Demux ogg chapters -------------------------

mkvextract 77.0

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Support\MKVToolNix\mkvextract.exe "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv" --ui-language en chapters "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_chapters.txt" --simple

File 'C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv': container: Matroska
Track ID 0: video (AVC/H.264/MPEG-4p10)
Track ID 1: audio (FLAC)
Track ID 2: audio (FLAC)
Chapters: 5 entries

Start:    14:52:08
End:      14:52:08
Duration: 00:00:00

---------------------------- Configuration ----------------------------

Template                : Automatic Workflow
Video Encoder Profile   : NVEncC (Nvidia) | H.264
Container/Muxer Profile : MP4 (mp4box)

--------------------------- AviSynth Script ---------------------------

AddAutoloadDir("C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\FrameServer\AviSynth\plugins")

LoadPlugin("C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Plugins\Dual\ffms2\ffms2.dll")
tcFile = "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_timestamps.txt" # timestamps file path
Exist(tcFile) ? FFVideoSource("C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv", cachefile="C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2].mkv", cachefile="C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\temp.ffindex")

------------------------- Source Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 34576
Time      : 24:02.107
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 34576
Time      : 24:02.107
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

---------------------- Media Info Audio Source 1 ----------------------

General
Complete name                : C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID1.flac
Format                       : FLAC
Format/Info                  : Free Lossless Audio Codec
File size                    : 234 MiB
Duration                     : 24 min 2 s
Overall bit rate mode        : Variable
Overall bit rate             : 1 360 kb/s

Audio
Format                       : FLAC
Format/Info                  : Free Lossless Audio Codec
Duration                     : 24 min 2 s
Bit rate mode                : Variable
Bit rate                     : 1 360 kb/s
Channel(s)                   : 2 channels
Channel layout               : L R
Sampling rate                : 48.0 kHz
Bit depth                    : 24 bits
Compression mode             : Lossless
Stream size                  : 234 MiB (100%)
Writing library              : libFLAC 1.2.1 (2007-09-17)
MD5 of the unencoded content : A51D1B599891A26FA9E152EB899190AE

---------------------- Media Info Audio Source 2 ----------------------

General
Complete name                : C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2.flac
Format                       : FLAC
Format/Info                  : Free Lossless Audio Codec
File size                    : 216 MiB
Duration                     : 24 min 2 s
Overall bit rate mode        : Variable
Overall bit rate             : 1 259 kb/s

Audio
Format                       : FLAC
Format/Info                  : Free Lossless Audio Codec
Duration                     : 24 min 2 s
Bit rate mode                : Variable
Bit rate                     : 1 259 kb/s
Channel(s)                   : 2 channels
Channel layout               : L R
Sampling rate                : 48.0 kHz
Bit depth                    : 24 bits
Compression mode             : Lossless
Stream size                  : 216 MiB (100%)
Writing library              : libFLAC 1.2.1 (2007-09-17)
MD5 of the unencoded content : 069DACC19E61F4AD60BE3038784540D9

----------------------- Error Audio Encoding 2 -----------------------

Audio Encoding 2 returned exit code: 2 (0x2)


-------------------------- Audio Encoding 2 --------------------------

qaac 2.80

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 --normalize "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2.flac" -o "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2_1831780736.m4a"

ERROR: 193: CoreAudioToolbox.dll

-------------------------- Audio Encoding 2 --------------------------

qaac 2.80

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 --normalize "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2.flac" -o "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID2_1831780736.m4a"

ERROR: 193: CoreAudioToolbox.dll

Start:    14:55:21
End:      14:55:21
Duration: 00:00:00

----------------------- Error Audio Encoding 1 -----------------------

Audio Encoding 1 returned exit code: 2 (0x2)


-------------------------- Audio Encoding 1 --------------------------

qaac 2.80

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 --normalize "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID1.flac" -o "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID1_1831780735.m4a"

ERROR: 193: CoreAudioToolbox.dll

-------------------------- Audio Encoding 1 --------------------------

qaac 2.80

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 --normalize "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID1.flac" -o "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\ID1_1831780735.m4a"

ERROR: 193: CoreAudioToolbox.dll

Start:    14:55:21
End:      14:55:21
Duration: 00:00:00

--------------------------- Video encoding ---------------------------

NVEncC 7.30

C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe --avsdll C:\Users\lenovo\Desktop\StaxRip-v2.22.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll  --cqp 18 -i "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_new.avs" -o "C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_new_out.h264"

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
C:\Users\lenovo\Desktop\转码测试\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_temp\[NoBody][DARLING in the FRANXX][10][BDRip][1920x1080_AVC_FLACx2]_new_out.h264
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Start:    14:55:21
End:      14:55:21
Duration: 00:00:00

**Comment by exgilgamesh** [comment]
<img width="473" alt="image" src="https://github.com/staxrip/staxrip/assets/43791454/530b963d-db9d-46a0-a829-88e39aa12609">
<img width="846" alt="image" src="https://github.com/staxrip/staxrip/assets/43791454/b41685f3-e040-4821-833f-249dcb85be85">

I used auto settings and I have added dll files

**Comment by exgilgamesh** [comment]
If I change the encoder  to ffmpeg，it will work！

**Comment by Dendraspis** [comment]
Seems you are missing `libFLAC` to be able to feed CoreAudioToolbox with FLACs. These might help you:

https://github.com/K3V1991/QuickTime-Files-for-qaac
https://github.com/xiph/flac
https://github.com/libsndfile/libsndfile

If `qaac64.exe --check` looks like this, everything should work:
```
qaac 2.80, CoreAudioToolbox 7.10.9.0
libsoxconvolver 0.1.0
libsoxr-0.1.3
libsndfile-1.2.0
libFLAC 1.4.3
```

**Comment by Discograp** [comment]
> If I change the encoder to ffmpeg，it will work！

if you want to just change the audio codec without video encoding
then use the "shutter encoder"
