### ISSUE TITLE
Audio-track

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1043]
Please! check the function, changes only in MP3 (default-select)

![321](https://github.com/staxrip/staxrip/assets/95682410/6c98f62c-fbba-41e0-b38f-39b2ba58b3dc)

**Comment by Dendraspis** [comment]
I don't understand what your problem is. It would have been better to fill out the template and/or provide more information, especially how to test/reproduce the problem you have. I won't start investigating because of "check that"...

**Comment by Dendraspis** [comment]
No need to close this issue, just tell me what the problem is and how to reproduce it...

**Comment by Discograp** [comment]
when I choose another codec, it reports an error at startup

when I select the MP3 codec, it processes normally, but when I open this MP3 audio track in another software with visualization, then it shows only the beginning and the continuation is 0, but there is sound

![123](https://github.com/staxrip/staxrip/assets/95682410/9ba5685b-ea12-4a32-a310-fa0a9ef50bbd)

**Comment by Dendraspis** [comment]
"another" in your case means "AAC with qaac", because you get this missing app message only, because qaac needs it to work.

As of MP3 it should be encoded with ffmpeg, so I don't know what this problem should be. Maybe it's your music visualizer software?

**Comment by Discograp** [comment]
auto select doesn't work

![123](https://github.com/staxrip/staxrip/assets/95682410/1a6995f7-de32-4006-8f96-ec43ac7a737c)

![321](https://github.com/staxrip/staxrip/assets/95682410/d07b7b93-d443-413b-89f1-f2cbd2f7d4f2)

**Comment by Dendraspis** [comment]
Sorry, I still don't understand. What do you mean by "auto select"?

**Comment by Discograp** [comment]
auto-select doesn't work at start of processing

you need to change it manually then processing starts normally without errors

**Comment by Discograp** [comment]
like this - https://github.com/staxrip/staxrip/issues/1040#issue-1796105003

**Comment by Dendraspis** [comment]
I repeat myself:  what do you mean by "auto select"?

What do you expect StaxRip to do (different)?

On your screenshots you have `Copy/Mux` selected. In that mode the source files are copied to the new container - without encoding.

**Comment by Discograp** [comment]
Example
uploading 1080p 23.976fps 111mb.mkv with audio OPUS

I select filters for the video and process, and the audio track in the Copy / Muh mode

then everything works fine

and when I upload the same thing and after the settings of the filters / codec / container

I change the audio track from opus to an alternative one - for example AAC - automatic change

then this error comes up on startup

![1111111111](https://github.com/staxrip/staxrip/assets/95682410/f43e1943-20bc-446e-aa83-caba948e00b9)

and if - I additionally change the Encoder manually to ffmpeg - then everything works fine

![2222222222222](https://github.com/staxrip/staxrip/assets/95682410/779e55a3-0525-4f71-8fcd-7b3cbb5f3d23)

**Comment by Dendraspis** [comment]
I repeat myself:
*"[..] because you get this missing app message only, because **qaac needs it to work**."*


And all links you might need can be found here, as you mentioned before:
https://github.com/staxrip/staxrip/issues/1040#issuecomment-1638893133


So is there still anything you need help with?

**Comment by Discograp** [comment]
my communication with you is rude
because I am using a double translation

I do not know how to help
found a reason and a solution - and you're just lazy

![0033](https://github.com/staxrip/staxrip/assets/95682410/452057aa-065a-4bf4-a40e-17100a1224ca)

**Comment by Dendraspis** [comment]
> and you're just lazy

Are you serious?

**Comment by Discograp** [comment]
is this not a bug?

![0033](https://github.com/staxrip/staxrip/assets/95682410/4bca55df-38d5-48f5-aefa-3ac7f59250a3)

**Comment by Dendraspis** [comment]
If you mean the `Apple Application Support` window:  **NO!**, like I said already multiple times.

**Comment by Discograp** [comment]
ok

that is, this automatic mode is not an automatic mode, and must be manually changed to a suitable one.

**Comment by Dendraspis** [comment]
Automatic = Best encoder that can be used, not just the best available one.
This is made on purpose. If you don't want to use the best encoder (qaac), choose another one manually.

**Comment by Discograp** [comment]
ok

automatic encoder change not working
StaxRip does not see the QAAC file/folder, so QAAC and FDKAAC do not work - only FFmpeg works

**Comment by Discograp** [comment]
what's the problem with adding this fix to release 2,23,0???

**Comment by Dendraspis** [comment]
There is nothing to fix (related to this topic).

**Comment by Discograp** [comment]
the problem is your laziness
this fix is too lazy to add to release 2.23.0

**Comment by Discograp** [comment]
aaaaaaaaaaaa I understand the problem ........

please send this folder to my mail - humanoid86@mail.ru

I repeat
I use double translation - so I understand very poorly what is written in English

**Comment by Discograp** [comment]
very weird
Handbrake
Topaz Video
Davinci Resolve Studio and 3 others

when converting audio to MP3 - they process well without errors
and only in StaxRip this error

when I select the MP3 codec, it processes normally, but when I open this MP3 audio track in another software with visualization, then it shows only the beginning and the continuation is 0

**Comment by Discograp** [comment]
by the way - this message should appear if qaas / fdkaas are manually selected

while auto mode should ignore and choose ffmpeg or alternative

![0033](https://github.com/staxrip/staxrip/assets/95682410/64439999-0101-4c07-8e44-ad1ff301dd2d)

**Comment by Discograp** [comment]
...automatic mode does not work, because I changed the script to use outdated qaac - if you want ffmpeg - then you have to manually change all the settings every time...

**Comment by jlw4049** [comment]
@Discograp you just don't understand how to use the software. 

This is FREE software and you are not his customer. 

If you want qaac to work then get the required files it's not legal for him to provide them to you. 

Additionally you should close this issue and setup a template to do your encoding with.

**Comment by Discograp** [comment]
change in AAC - works without errors

change in MP3 - works with errors

![001 sr](https://github.com/staxrip/staxrip/assets/95682410/d65cdd0b-98fe-47b6-9e2a-5e790d961eec)
![002 sr](https://github.com/staxrip/staxrip/assets/95682410/80761c1e-5ae8-402f-9d33-9f7152cf1c9c)
