### ISSUE TITLE
AOMEnc - Rate Mode "CQ (Constrained Quality)",  "--target-bitrate=xxxx"  is missing

### ISSUE THREAD

**Issue by pat-e** [staxrip/staxrip#1044]
When using AOMEnc with "Constrained Quality", in addition to selecting the CQ Level, there should be the option for selecting the parameter "target-bitrate":

The Result could look like:

![aomenc_parameters_cq_target-bitrate](https://github.com/staxrip/staxrip/assets/11069987/3acf6539-e6eb-4ffe-a527-7c8a57ce16de)

The result would be: The encoder will use the selected quantizer, but will always stay below the selected bitrate

**Comment by Dendraspis** [comment]
Thanks, will be fixed in the next release.
