### ISSUE TITLE
SVT-AV1 - Improve Integration: View Bitrate, Add Encoder Options

### ISSUE THREAD

**Issue by vanontom** [staxrip/staxrip#1045]
SVT-AV1 integration into StaxRip can be improved. Most importantly, there does not seem to be any way to **view bitrate** during encoding (only generic progress is shown, and "average system encoding speed" is occasionally reported). Maybe SVT-AV1 has made this impossible? I've tried using "--progress 2" but the extremely high amount of reports will usually hang or crash StaxRip within a few minutes. 

Other integration issues: Many important **encoder options are missing** from UI (for example: --tune, --film-grain, --enable-overlays, --enable-tf, --scd). Also, CRF seems to now be the default mode (not CQP). I've tried using other AV1 encoders but they are slower and much more complex (but I will keep learning and testing). If any screenshots are needed I will be happy to provide.

**Comment by Dendraspis** [comment]
Thanks, no screenshots needed. I know that SVT-AV1 is a little bit abandoned within StaxRip as it is not that often used. But I'll try to update and add some settings, probably for `v2.24` or later.

>  Also, CRF seems to now be the default mode (not CQP)

From the CLI help:
`default is 0 [0: CRF or CQP (if "--aq-mode" is 0), 1: VBR, 2: CBR]`
...I'll take care of that, too.

**Comment by vanontom** [comment]
@Dendraspis Thank you for taking a look at this! Any updates, big or small, are appreciated. Do you think it will be possible to view the bitrate in the UI (progress bar) at some point? I notice that via ffmpeg (vs using SvtAv1EncApp) does show bitrate, so that is an option that could help in the meantime.

**Comment by Dendraspis** [comment]
> Do you think it will be possible to view the bitrate in the UI progress bar at some point?

For `SvtAv1EncApp` I doubt that, because the encoder itself doesn't provide the necessary information, so the only way would be to find somebody, who is willed to modify the encoder.  😕

**Comment by vanontom** [comment]
@Dendraspis Received 2.23 release notification, read release notes, and this is already implemented!? Checking it out now. The SVT-AV1 encoder settings look fantastic, really nice work! Thank you again, this is awesome and appreciated. Feel free to close this issue. (I'm not sure of ettiquette. And the bitrate issue is kind of separate involving unlikely encoder modification anyway.)

**Comment by Dendraspis** [comment]
Thanks, I'll have a look at it later and fix it asap. Seems there are some `"` missing.  🙄

**Comment by Dendraspis** [comment]
Here is the fix - just replace the EXE file:
[StaxRip v2.23.1.zip](https://github.com/staxrip/staxrip/files/12159316/StaxRip.v2.23.1.zip)


> Feel free to close this issue.
Let us wait for the answer from @Patman86 regarding the additional information. Then we can close it anyway.

**Comment by vanontom** [comment]
> Here is the fix - just replace the EXE file: [StaxRip v2.23.1.zip](https://github.com/staxrip/staxrip/files/12159316/StaxRip.v2.23.1.zip)

It is indeed all working smoothly now! (Opened same project, completed.) An easy fix, that's always nice at least.

> Let us wait for the answer from @Patman86 regarding the additional information. Then we can close it anyway.

Sounds great! "So you're telling me there's a [chance](https://www.youtube.com/watch?v=zMRrNY0pxfM)..."

**Comment by Patman86** [comment]
svt-av1 already has a switch that provides a few more pieces of information, but nobody uses it... `(--progress 2)` I have nevertheless taken a look at it... Here is the first preview

![image](https://github.com/staxrip/staxrip/assets/54327252/796e4e45-4d24-4d08-a113-314ee902bcd8)

**Comment by vanontom** [comment]
Whoa, @Patman86 that would be incredibly useful.

I've found `--progress 2` hangs StaxRip regularly (window stops responding, have to force closed, I assume because of massive amount or excessive rate of reporting). While default `--progress 1` does not share enough info (progress total and fps at long intervals). I don't know why they though bitrate was not important enough to include.

**Comment by Dendraspis** [comment]
> I've found `--progress 2` hangs StaxRip regularly (window stops responding and have to end task, I assume because of excessive rate or total amount reporting). 

Fixed. 😁

Patman offers me his build the next days, so the extended progress will be available in the next or the one after the next release.

**Comment by vanontom** [comment]
Thank you guys so much. All SVT-AV1 users (I hope there are many of us and growing?!) will really appreciate and enjoy this. I am amazed at the response to this issue, I thought it might just be vaguely glanced at and "added to the pile". <3

**Comment by Patman86** [comment]
I've uploaded SVT in my Mindfactory share 😁

**Comment by Dendraspis** [comment]
Thank you.

I will modify StaxRip for the next release, so it will work fine with the changes.

**Comment by vanontom** [comment]
Just wanted to say everything is working great here (thanks to 2.24)! Bitrate is magically [showing](https://i.imgur.com/3Hc8w2d.png) in progress bar (and `--progress 2` set). 😲 Encoding settings are beautifully implemented and working perfectly. So many fixes in so little time. 😃

**Comment by Dendraspis** [comment]
Thanks for the feedback and the kind words.

The next release will include the new `SvtAv1EncApp` mod by himself and some adjustments in StaxRip to provide an extended progress text/bar.

So I close this now .... have fun.
