### ISSUE TITLE
Event Command Criteria optional OR

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#1049]
![image](https://github.com/staxrip/staxrip/assets/48299282/2f23b06e-2cad-46fb-8523-06c62bc3d74e)

If it isn't too much work would an option OR work between multiple of the same criteria? This likely will be a lot of work. I think just doing it based on Video Encoding profile as I requested would be likely easier.

**Comment by Dendraspis** [comment]
I had a deeper look at the events and I don't see any better solution than the one that is already implemented. There is also no way I create special conditions for certain criteria - that would lead to pure chaos, sorry.

The best solution I see:
Create an event with the first  3 criteria, including `Target Filename Without Extension <Contains> dovi`. Then you clone this event and there you replace `dovi` with `dv`.
When you chose good event names you should also remain a good overview.  🤔

**Comment by jlw4049** [comment]
Thanks you adding the encoder profile filter is more than enough. Thank you very much!
