### ISSUE TITLE
Beta 2.0.6.2 cropping is restricted

### ISSUE THREAD

**Issue by jalba69** [staxrip/staxrip#105]
Hi Stax,

Like said on the forum the cropping seems restricted right now for the areas, probably since last renderer implementation for the preview maybe, only decided to restart with Staxrip2.x a couple of days before you added this and can't say for sure.

Anyways before in 1.7.0.6 we could do this 
https://streamable.com/dmchx
Moving freely in the cropping window.

Now in last 2.0.6.2 when trying to crop we are restricted to a certain area : 
https://streamable.com/98v5d
For example when starting to crop from the left side we can't even reach the half part of the screen compared to before where we could go to the other side of the screen less a few pixels to get a valid crop parameter. 

I'm not sure if it's a limitation of the new renderer or something wrong on my side yet but the cropping using the crop tool is quite limited now.

Thanks a lot for all ;)

**Comment by 44vince44** [comment]
I confirm, there is a bug in the cropping window. Cropping is limited.
Example: 
A video in portrait format, size 1080x1920. Cannot remove more than 144 pixels vertically

**Comment by stax76** [comment]
Seem to work, please re-test.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS

**Comment by 44vince44** [comment]
The cropping is now better than before, but there is a problem when cropping, closing the crop window, reopening the crop window, the values are lost.
Here is the max crop that you can do now, and this is OK:
On a video 1920x1080, now you can crop to 640x360
On a video 1080x1920, now you can crop to 360x640
On a video 3840x2160, now you can crop to 1280x720
On a video 2160x3840, now you can crop to 720x1280
    
**But there is a problem**. Take a 3840x2160 video, crop it to 1280x720, close the crop window,
reopen the crop window, and see that the crop values have changed to 1280x1680 !!
Take a 1920x1080 video, crop to 640x360. Close the crop window, reopen the crop window, the 
crop values have changes to 640x840 !!!

**Comment by stax76** [comment]
Thanks for the bug report, wasn't my best day when I programmed it, fix will be out in a minute.

**Comment by 44vince44** [comment]
This is fixed indeed. Thank you Stax!
