### ISSUE TITLE
Horizontal scroll bar for File Batch and Jobs windows

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#1050]
**Is your feature request related to a problem? Please describe.**
You really can't see long paths to see what you have queued up in either window

**Describe the solution you'd like**
Just a fixed horizontal scroll bar for both

![image](https://github.com/staxrip/staxrip/assets/48299282/b6d3863e-dd51-4c0b-85b3-bec65f6d6552)

**Comment by Dendraspis** [comment]
Might be a stupid question, but: 
Why don't you just *stretch* the window? 

As far as I remember the scrollbars were hidden on purpose, and basically I agree with that.  😅

**Comment by jlw4049** [comment]
Stretching it is fine if the horizontal scroll bars are problematic to implement. I understand GUI frameworks are sometimes a pain in the butt lol.

**Comment by Dendraspis** [comment]
Especially on 20 years old GUI frameworks.  😬 
The Event Command Editor was sort of unusable without the scrollbars and stretching the window also stretched the command section, so I had to tweak it a bit. But here the best solution (also for me  😬)  is to leave it as it is, sorry.

**Comment by jlw4049** [comment]
Not a problem thanks!
