### ISSUE TITLE
Project file not found when attempting to process batch files

### ISSUE THREAD

**Issue by jessielw** [staxrip/staxrip#1051]
**Describe the bug**
StaxRip is looking for non existing project files. The files don't exist until the batch has started, however, it's causing an error if you try to press Load OR actually when processing the file sometimes you'll get a pop up with the same bug.

**Expected behavior**
Not to look for a project file unless it's actually started processing the file

**How to reproduce the issue**
This one is a little more difficult to reproduce. I queued up all 3 seasons of avatar the last airbender and this happened on the episodes in the screen shot. Initially I thought this was a long path error, but that is enabled in the OS as well as the encoder that I'm using.

**Provide information**
Latest version of StaxRip
Here is the error when I press `Load` when I click the episode and press load. 
![image](https://github.com/staxrip/staxrip/assets/48299282/38f28205-e54d-496f-a930-508d68f4bbe1)
I however do expect this to happen since in reality it shouldn't have a project file yet, at least to my knowledge. 

The real issue is when I'm actually trying to encode
![image](https://github.com/staxrip/staxrip/assets/48299282/938c159f-6914-4073-93cf-aa31202c1da5)

Some odd things I've noticed is the path like `C:\Users\jlwServerWin\Desktop\StaxRip-v2.22.0-x64\Settings\Batch Projects\M--bhdstudio-downloads-Avatar.The.Last.Airbender.S01.BluRay.1080p.FLAC.2.0.AVC.REMUX-FraMeSToR- BHDStudio.3.5.5 (02-05-23) VapourSynth - Batch - avatar - Avatar.The.Last.Airbender.S01E19.The.Siege.of.the.North.Part.1.1080p.FLAC.2.0.AVC.REMUX-FraMeSToR.mkv.srip` 

This is clearly not a real path. Not really sure what is going on here.

**Comment by jlw4049** [comment]
**EDIT:**
The bug is actually triggered when using an **Event Command** that automatically runs with **After Project Loaded**
![image](https://github.com/staxrip/staxrip/assets/48299282/8736c72e-0faa-45ca-bd8c-5ef21452432a)


Adjusting this to **Before Processing** seems to allow it to work

**Comment by jlw4049** [comment]
The above did not solve it. It allowed some more to work but some others failed again

**Comment by jlw4049** [comment]
Update: I played around with it for a bit. Shortening the template project name seemed to have fixed it. The ones that couldn't encode are now encoding. I'll update in the morning if they all get through with this change. 

![image](https://github.com/staxrip/staxrip/assets/48299282/57dfb179-ef59-4f7d-8c7e-c82b1a6ff8d0)

**Comment by jlw4049** [comment]
Update it allowed more of them to run but didn't solve it. 

So tbh I'm not sure as it right now.

**Comment by Dendraspis** [comment]
I'll have a look at it at some point, but File Batch is something I never use in my workflow, so don't expect a quick fix.  😕 
But I think it helps a lot to know, that it is a path length issue and also the mention of your file path, so I can try to reproduce it.

- So have I understood it correctly, that using *Single File* does work, but *File Batch* doesn't?
- Which OS do you use?

**Comment by jlw4049** [comment]
Yes, it opens the the file fine in **Single File** mode via drag and drop but **File Batch** fails.
Windows 10 64bit latest version for this machine.

**Comment by gkalemis** [comment]
The problem still persists. File Batch with very long path + file name does not work. Same single file is OK. If I truncate the file name then I can use file batch. The problem, I think, is that no temp directory is created.

Same Windows 10 64 bit.

**Comment by Dendraspis** [comment]
Maybe I have found something ... the latest comment was very helpful!

Will be implemented with the next release...
