### ISSUE TITLE
Follow up #1044: AOMEnc - Constrained Quality - Target Bitrate not "changeable" 

### ISSUE THREAD

**Issue by pat-e** [staxrip/staxrip#1052]
Follow up of Ticket #1044 

Now I can select "Constrained Quality", but the value for "Target Bitrate" of 5000 seems to be "fixed" and no matter what is typed in / selected as value, it always reverts to 5000.

**Comment by Dendraspis** [comment]
Confirmed and already fixed. The next release is coming soon...

**Comment by Dendraspis** [comment]
Next release within the next 35 hours....  ⏳

**Comment by pat-e** [comment]
Short update: Seems to work now:
![aom_works](https://github.com/staxrip/staxrip/assets/11069987/de92dac1-6475-4381-84b0-590a93b3eaed)
