### ISSUE TITLE
ffmpeg progress bar is broken on v2.24.0-x64

### ISSUE THREAD

**Issue by craposoup** [staxrip/staxrip#1054]
The Progress bar stopped working during ffmpeg rendering on staxrip v2.24.0-x64, the blue progress bar is missing.

![image](https://github.com/staxrip/staxrip/assets/49623148/9971d630-0cbc-4f16-96fb-6406d2463cd8)

**Comment by Dendraspis** [comment]
Encoder?

**Comment by craposoup** [comment]
yes, ffmpeg, I updated the screen shot above.

To recreate:
set deinterlace to QTGMC, medium or any other setting.
set output anyting, I choose ffv1 > AVI
open any interlaced mpeg file
add job.

Same settings works fine in previous version.

**Comment by Dendraspis** [comment]
Thank you.
It's fixed and will be available in the next release.

**Comment by craposoup** [comment]
Awesome, thankyou!

**Comment by craposoup** [comment]
Also, app temporaldegrain2 still does not work.

![image](https://github.com/staxrip/staxrip/assets/49623148/e9b2c7d7-73a8-49d6-9a46-095296e96b81)

**Comment by zuba0012** [comment]
Seems to be happening again when using v2.28.0-x64 with the included ffmpeg 6.0 N-111762-ga1928dff2c-x64-gcc13.2.0, I was converting hevc to prores using vapoursynth script, was fine in older versions like v2.19.0.
