### ISSUE TITLE
Feature Request: Make Video Comparison tool accept .avs files

### ISSUE THREAD

**Issue by Samhayne** [staxrip/staxrip#1055]
May I request a feature?
I'm heavily using StaxRip's Video Comparison tool.

Big disappointment today when the UI looked like I could load an .avs script in there for comparison - but it didn't work as expected.
![image](https://github.com/staxrip/staxrip/assets/7030482/aa5f9a4b-b0fc-4624-a060-e1b3c859fab1)

Would be so helpful when comparing sources with different framerate / frame count / frame interpolation or where one video has a slight offset.

It looks like StaxRip is under the hood generating an .avs file in "C:\Users\[User]\AppData\Local\Temp" as soon as a video is loaded in the Video Comparison tool - but manipulating this .avs is useless as the comparison tool doesn't seem to reload it ever.

**Comment by Dendraspis** [comment]
Better: You could compare the filtered/tuned output with the original file without encoding at high quality to prevent wrong settings due to encoding quality loss.

Even better: You could fine tune settings and directly compare them with the source file.

**Comment by Dendraspis** [comment]
And even better:  It's already implemented for the next release.  🥳 

Because this was pretty tricky, there might be some bugs and space for improvements, but it works, as long as you don't add filters/settings, that require new dependency loadings. Feel free to report everything apart from that.  😅

**Comment by Samhayne** [comment]
Wow. That was lightning-fast! How awesome is this??
SO looking forward to the next release.

Thanks, @Dendraspis !

**Comment by Dendraspis** [comment]
Let's see how it works for you and others first.  😅 

The release will be published this week....

**Comment by Samhayne** [comment]
Uuh! The new version is out for two days already!
Tested it out and it works wonderfully for me.
The way I used it, I didn't find any quirks.

Only noticed a minor unrelated annoyance.
But I'll rather create a new feature request for that. :)

Thanks again so much, @Dendraspis!

**Comment by Dendraspis** [comment]
Yeah, there is a lot of space for improvements, but yeah.
Have fun using it...
