### ISSUE TITLE
Add avs_libplacebo

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1058]
I want to propose the integration of [avs_libplacebo](https://github.com/Asd-g/avslibplacebo) in StaxRip as general purpose filter.

It can provide **very fast** access by Vulkan libraries to:

- debanding
- resampling
- shader
- tone mapping

and we are talking about 1000+ fps for some functions. Moreover, it includes filters that can't be found anywhere else (yet).

I have tried on my own but I can't find a proper way to integrate the resolution slider with the parameters to pass to the filter itself such as when resizing.

**Comment by Dendraspis** [comment]
Will be available in the next release.

**Comment by tormento** [comment]
@Dendraspis I saw you added in the plugins directory but I see no integration in Staxrip.
