### ISSUE TITLE
StaxRip v2.25.0 trojan

### ISSUE THREAD

**Issue by legosoff** [staxrip/staxrip#1061]
Hi, Dendraspis! StaxRip v2.25.0 the antivirus reported to block.
https://radikal.host/i/F35ZWQ

**Comment by Dendraspis** [comment]
Yeah, this is because of the UPX-packed tools that are included. 

If you're not comfortable with them, replace them (should olny affect encoders) with other/stock/official binaries or compile them by yourself.

**Comment by legosoff** [comment]
I understand you, the antivirus is disabled and now everything is fine, there is no problem. Thank you.
