### ISSUE TITLE
Trojan Detected in 2.25.0

### ISSUE THREAD

**Issue by jmf866** [staxrip/staxrip#1064]
Microsoft Defender detected a trojan in StaxRip-v2.25.0-x64.7z
Trojan:Script/Wacatac.B!ml

https://www.virustotal.com/gui/file/4517f390883186dc71d0e27c4c40d194b3fecbbf547dad9804549280980c9e3e/detection

**Comment by Dendraspis** [comment]
See also: #1053  and  #1061

To make it short:
Those are false positives, seems like the newest version of UPX, that is used you pack some tools, confuses some AV engines.
