### ISSUE TITLE
Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by SergePD** [staxrip/staxrip#1065]
Cannot download v2.25.0, Windows found Trojan:Script/Wacatac.B!ml in the file.

**Comment by legosoff** [comment]
I had the same one Trojan v2.25.0. I won't install it yet, I'm waiting to fix it.

**Comment by legosoff** [comment]
The antivirus is disabled and now everything is fine, there is no problem.

**Comment by Dendraspis** [comment]
Please have a look at #1061.

I'll think about it for the next release, but all files are clean.
