### ISSUE TITLE
"Don't show again" checkbox for Video Comparison (S)ave PNG confirmation window

### ISSUE THREAD

**Issue by Samhayne** [staxrip/staxrip#1067]
I noticed that for the Video Comparison tool in newer StaxRip versions there's a confirmation window each time a user saves pictures.

Can we get a "Don't show again" checkbox for people who want to save several reference pictures in a row?

Somewhat like this:
![image](https://github.com/staxrip/staxrip/assets/7030482/5964baf5-cbd2-49b0-a61a-4974a7e5949e)

...or any other way to keep the modal popup from showing up each time if undesired.

**Comment by Dendraspis** [comment]
> in newer StaxRip versions

Since `StaxRip v2.1.1.5 Beta`, so for over 3 years.  😁

I'll think about it...

**Comment by Samhayne** [comment]
Thx, @Dendraspis. If it can be done in a reasonable time and you don’t have to convert a simple message box into a full-blown window or something like that I’d welcome it.

I first thought picture saving broke it as nothing would react anymore afterwards… when I eventually realised that there is an unexpected message box displayed on another monitor, blocking all inout.

But I can just hit S and Enter afterwards each time to close the message box. It’s just less comfortable than it was before.



I’m still mainly using StaxRip 1.7.0.6 as there was a phase where a lot of bugs and quirks were introduced. But the current version look good and maybe I should finally switch to a newer versions and recreate my templates to wirk with the “new” format.

As the flexible architecture of StaxRip makes it perfectly possible to upgrade most of its components manually you can stick with an ancient version for a long time - if you want to. :)

**Comment by Dendraspis** [comment]
> I’m still mainly using StaxRip 1.7.0.6

Basically there's no problem using an old version, as long as you update some tools by yourself. Depending on what you use, you might have to deal with missing parameters or functionality. But it's up to you.

> But I can just hit S and Enter afterwards each time to close the message box. It’s just less comfortable than it was before.

Totally understand you.
I'll come back to this when I have some time to realize it....

**Comment by Dendraspis** [comment]
Solution was easier than I thought initially.  😅 
But the possibility will be available in the next release, have fun with it.  👍

**Comment by Samhayne** [comment]
So glad to hear my bold request didn't cause too much pain on your side!
Thanks so much for looking into it... and solving it. @Dendraspis!

**Comment by Samhayne** [comment]
Great solution!! Love it, @Dendraspis !

![image](https://github.com/staxrip/staxrip/assets/7030482/0d8990d8-fe70-4d04-a057-ec64a5837f7f)
