### ISSUE TITLE
Frame rate change QSVEn

### ISSUE THREAD

**Issue by sportniik** [staxrip/staxrip#1069]
**The issue:**
I can't change frame rate of source file.

**Desired behaviour:**
Changing a 1080 50fps video to 720 25fps

**How to reproduce the issue:**
My source are all sort of video files. From .ts to MKV.
For output I choose QSVEncC H.264 (QSVEnc hardware decoder) and MP4

Avs filters (I really do not understand that part, so this is more guess and push a button method) ; anyway here I get FFVideosource ; I tried to add frame rate options like change/assume FPS etc ... and it didn't work.

**Conclusion:**
If some knows a way to change FPS of output file in regard to source, I would be very grateful. I prefer QSVEncC, cause I get the highest speed with QSV (I run on UHD iGPU).

**Comment by Dendraspis** [comment]
🤔   Maybe that can help you:

![image](https://github.com/staxrip/staxrip/assets/50659978/f9bd0852-7867-4a20-ac5b-a3c3e3545f36)

![image](https://github.com/staxrip/staxrip/assets/50659978/b7d11fc7-4771-49d6-9cfc-5849ab1eefd1)

Just in case:
Make sure you don't use settings or templates from old releases.

**Comment by sportniik** [comment]
Thanx for swift replay!

I have tried adding "Change FPS". But it only works, if hardware decoder is AviSynth/VapourSynth.

If I choose QSV hardware or software decoder, it changes FSP value only in "target" window. Just like on 2nd screenshot you posted (in source window is 25 in target window is 50). But when I click add job + start; in processing window is again unchanged (in your case it would stay 25fps).

So decoder is the source I think. AviSynth/VapourSynth works flawlessly, but QSV does not change fsp when processing, it only changes in "target window" before you click add job and start.

**Comment by Dendraspis** [comment]
StaxRip is mainly built to use and work with AviSynth or VapourSynth, and those filters like `ChangeFPS()` are part of that. So when you select another decoder, for whatever reason, the frameservers are bypassed, including all filters and scripts that are set, and you get just what the selected decoder outputs.

**Comment by sportniik** [comment]
That is a bit disappointing, cause frame rate is kind of a basic parameter to set. And 2nd reason is, I use QSV decoder, cause it is much faster than all others under QSVEncC. AS/VS decoders only give me about 110fps converting, QSV hardware gives me 450fps. And since I have a lot to convert, I have no choice, but to use faster decoder.
Thanx anyway for replay!

**Comment by Dendraspis** [comment]
That's the downside of the speed gain, because it is not read directly.
But yeah, huge difference.  🫤

You're welcome. I close this now....
