### ISSUE TITLE
There's no Audio Codec Option in Criteria

### ISSUE THREAD

**Issue by MuhammadBayiz** [staxrip/staxrip#1074]
**Is your feature request related to a problem? Please describe.**
I'm Trying to make a Event Commander to auto passthru AAC 2ch but i can't find any option for Audio codec in Criteria Section I've tried other options but they seem useless for this usage

**Describe the solution you'd like**
Add an option for Audio Codec With full information of the audio In Criteria like (Codec, Channels, Sample Rate, Bitrate...) (Most Important is the codec and the channel for my situation). 

**Describe alternatives you've considered**
I've tried File>First Audio But this only Shows The audio file name which is just the language name of the audio also ive tried every possible alternative but no use.

**Explain why the feature matters to you**
since I've started using staxrip I've Missed the Auto Audio Passthru Feature from Other GUIs.

**Additional context**
N/A

**Comment by Dendraspis** [comment]
- Bitrate ✔️ 
- Channels ✔️ 
- Codec ✔️ 

Will be added in the next release, so stay patient.  😁

**Comment by MuhammadBayiz** [comment]
Amazing! 🤯 thanks I'll be waiting for it
