### ISSUE TITLE
StartAutoCrop Doesn't add Crop Filter

### ISSUE THREAD

**Issue by MuhammadBayiz** [staxrip/staxrip#1075]
**Describe the bug**
I'm using Event Command with this Command and when this command runs it dosn't add Cropping as a filter if there's any cropping it only adds it when i press Crop Button or i use ShowCropDialog and then close the dialoge afterwards

**Expected behavior**
it should start auto cropping and if there's any cropping needed it should add it to the filter list

**How to reproduce the issue**
Tools> Event Command> Add>
https://imgur.com/a/TEpuCxi

- Used StaxRip version
v2.25.0

**Comment by Dendraspis** [comment]
Indeed, thanks for the report. Seems you're the first who uses this feature.  😅 

I've fixed it for the next release, so I close this for now...

**Comment by MuhammadBayiz** [comment]
Finding that feature was like finding a gold mine, thanks for the fix ;)
