### ISSUE TITLE
SVT-AV1 multipass

### ISSUE THREAD

**Issue by daynyxx** [staxrip/staxrip#1076]
**Describe the bug**
When enabling multipass with svt-av1 the command output adds both ```--passes 2``` and ```--pass 1``` which gives the error ```[SVT-Error]: --passes is not accepted in combination with --pass```.

**Expected behavior**
Command should be as it is now without the extra ```--passes 2``` argument.

Example:
Current command: ```"D:\Program Files\StaxRip\Apps\FrameServer\VapourSynth\vspipe.exe" "D:\Video\To Convert\Star Trek TOS\S01E02_temp\S01E02_new.vpy" - --y4m | "D:\Program Files\StaxRip\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe" --input - --width 1440 --height 1080 --output "D:\Video\To Convert\Star Trek TOS\S01E02_temp\S01E02_new_out.ivf" --frames 72754 --passes 2 --pass 1 --stats "D:\Video\To Convert\Star Trek TOS\S01E02_temp\S01E02_new_out_2pass.log" --rc 0 --progress 2```

Expected Command: ```"D:\Program Files\StaxRip\Apps\FrameServer\VapourSynth\vspipe.exe" "D:\Video\To Convert\Star Trek TOS\S01E02_temp\S01E02_new.vpy" - --y4m | "D:\Program Files\StaxRip\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe" --input - --width 1440 --height 1080 --output "D:\Video\To Convert\Star Trek TOS\S01E02_temp\S01E02_new_out.ivf" --frames 72754 --pass 1 --stats "D:\Video\To Convert\Star Trek TOS\S01E02_temp\S01E02_new_out_2pass.log" --rc 0 --progress 2```

**How to reproduce the issue**

1. Open video file to encode
2. Select AV1 -> SVT-AV1
3. Enable multipass
4. Encode fails

**Provide information**

Log file: [S01E02_new_staxrip.log](https://github.com/staxrip/staxrip/files/12328827/S01E02_new_staxrip.log)

**Comment by Dendraspis** [comment]
Thanks for the very detailed report. Very interesting, because the docs sound like you need both.  🙄 

Anyway: it's fixed for the next release by removing the `--passes` parameter.
