### ISSUE TITLE
QTGMC now requires field order to be defined.

### ISSUE THREAD

**Issue by harrypm** [staxrip/staxrip#1077]
In older versions of staxrip QTGMC would work with any input weather it be digital tapes with BFF or analog with TFF but now requires manual `AssumeTFF()` or `AssumeBFF()` to correctly de-interlace outherwise the resulting files are just jittery.

Tested with decoded VHS TFF and MiniDV BFF media for sanity checking with FFVideoSource under AVS filters.

So now this requires 2 templates for each field type but never the less has removed a drag and drop convenience.

Example of now edited commands.

`AssumeTFF()QTGMC(preset="Placebo", InputType=0, sourceMatch=3, sharpness=0.3, tr2=2, ediThreads=16)`

`AssumeBFF()QTGMC(preset="Placebo", InputType=0, sourceMatch=3, sharpness=0.3, tr2=2, ediThreads=16)`

**Comment by Dendraspis** [comment]
I've check some Interlaced source files and they work good without `Assume*FF`.  
So basically no addition is needed, at least as long as your source or intended target file doesn't need it.   🤔

**Comment by Discograp** [comment]
try this - no filter - such as QTGMC

![001 sr](https://github.com/staxrip/staxrip/assets/95682410/f092f976-b8c1-4980-8158-139c4c085b4d)

**Comment by harrypm** [comment]
For context It has proper TFF flagging. 

I am going FFV1 25i/29.97i --> QTGMC --> FFV1 50p/59.94p 

I had this issue with `v2.13.0` as I upgraded to it but then testing `v2.25.0` its utterly breaking output files using the same templates.

[TFF FFV1 PAL 25i file I am using](https://drive.google.com/file/d/1ELAN3mVQD0k9J8oMgmHDxIoxd3pEkZcb/view?usp=drive_link)

Here is my templates which work fine on `v2.13.0` 

[Templates.zip](https://github.com/staxrip/staxrip/files/12377280/Templates.zip)

**Comment by Dendraspis** [comment]
Just to clarify:
Did/do you use the same template like you used in `v2.13` by copying the file(s) or did you recreate it from scratch?

**Comment by harrypm** [comment]
Exact same templates copyed yes.

**Comment by Dendraspis** [comment]
That could be the problem. It's pretty important to start with a clean instance, especially when there were bigger internal changes like in `StaxRip v2.25`.

Here is how it looks like for me after opening the file and selecting QTGMC with Fast preset:

**Preview:**
![image](https://github.com/staxrip/staxrip/assets/50659978/cfec3989-c7f6-4a64-8e98-e95a643e7c5b)

**Settings:**
![image](https://github.com/staxrip/staxrip/assets/50659978/268ab67f-b7a6-4847-ace3-7c20faaaa3ff)

**Comment by Discograp** [comment]
That's what I assumed, and it's been confirmed...
for HD/SD content you need a minimum of 49fps if you want to use 265/HEVC codec
