### ISSUE TITLE
Device

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1078]
v. 2.25.0

![001 sr](https://github.com/staxrip/staxrip/assets/95682410/6b80fd38-2264-4d59-b747-91e7b40ea686)

PS
By the way, I have i-GPU 770 and d-GPU RTX 3060-12

why does it show 12 devices?

**Comment by Dendraspis** [comment]
https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#-d---device-string-or-int

**Comment by Discograp** [comment]
understandable - an error in the QSVenc
