### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1079]
Please! add these permissions and your forgotten fixes to the display of Pass-1-2-3 and Interframe

![Resize](https://github.com/staxrip/staxrip/assets/95682410/ed50d939-703a-470e-a0e8-4dbf084ae96b)

7680 x auto = 7680 x 0
3840 x auto = 3840 x 0
3200 x auto = 3200 x 0
2560 x auto = 2560 x 0

1920 x auto = 1920 x 0
1720 x auto = 1720 x 0
1440 x auto = 1440 x 0
1280 x auto = 1280 x 0

960 x auto = 960 x 0
860 x auto = 860 x 0
720 x auto = 720 x 0
640 x auto = 640 x 0
480 x auto = 480 x 0
320 x auto = 320 x 0

**Comment by Dendraspis** [comment]
What do you mean by "permissions"? And why can't you fill out the template?

**Comment by Discograp** [comment]
the translation is wrong = display resolution

**Comment by Discograp** [comment]
I already changed the template, I thought it would be useful for other people to do x2 upscaling

**Comment by Dendraspis** [comment]
I've added some more for the next release, the current state is:

```
7680 x auto = 7680 x 0
5760 x auto = 5760 x 0
3840 x auto = 3840 x 0
3200 x auto = 3200 x 0
2560 x auto = 2560 x 0
1920 x auto = 1920 x 0
1680 x auto = 1680 x 0
1280 x auto = 1280 x 0
960 x auto = 960 x 0
720 x auto = 720 x 0
640 x auto = 640 x 0
480 x auto = 480 x 0
320 x auto = 320 x 0
```

**Comment by Discograp** [comment]
Please! add these your forgotten fixes to the display of Pass-1-2-3 and Interframe

**Comment by Dendraspis** [comment]
>  fixes to the display of Pass-1-2-3

Nothing wrong with the current state, everything works as intended. If you don't think so, open a separate issue.

> Interframe

Always start with fresh setting files and everything should work. Otherwise use #1046 and provide additional information.
