### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#1082]
Please! Change this function. So that when "Activation" completely ignores the image.
and sometimes it doesn't work. and you have to do a "resize" in another software, then load it into "StaxRip"

![001 sr](https://github.com/staxrip/staxrip/assets/95682410/76eb846c-30f7-4191-be12-170529057434)

**Comment by Dendraspis** [comment]
What you're writing makes absolutely no sense.

**Comment by Discograp** [comment]
ok
