### ISSUE TITLE
VS FIlters Hardcoded Subs error in 2.27.0

### ISSUE THREAD

**Issue by wrzlpete** [staxrip/staxrip#1088]
**Describe the bug**
When adding hardcoded subtitles in a VS Filters setting, the following error occurs
"Python exception "no attribute with the name sub exists. Did you mistype a plugin namespace?"
This did not happen up to 2.25.0.

**Expected behavior**
No error ;)

**How to reproduce the issue**
Open Staxrip 2.27.0
Change AVS Filters to VS Filters
Load a mkv Video file with ass subtitles included (drag drop in my case)
Use "Tools -> Advanced -> Add Hardcoded Subtitle" option
Error occurs

**Provide information**
- Used StaxRip version 2.27.0

**Additional context**
I was using my own filter settings up to 2.25.0 that worked fine, now they do not work anymore. I first thought it was an incompatibility in the code I was using, but since I tried to recreate the functions in my filters from scratch the error also happened.

![error](https://github.com/staxrip/staxrip/assets/74388493/720febe4-51e9-4be1-8b8e-707c0206188a)

**Comment by Dendraspis** [comment]
Thanks for the report.
I've fixed it for the next release that's coming later. If you encounter the same issue, make sure you use a clean instance with fresh settings. If it still happens, please re-open this issue.
