### ISSUE TITLE
Extract Playlist Pop-up empty

### ISSUE THREAD

**Issue by Morku** [staxrip/staxrip#1090]
**Describe the bug**

With Staxrip 2.26.0 and 2.27.0:

1. Click on Source
2. Click on Blu-ray Folder
3. Select a Blu-ray Folder (BDMV, CERTIFICATE)
4. the Pop-up is empty

![grafik](https://github.com/staxrip/staxrip/assets/6276915/f09a0545-8888-41d9-825c-9aa6d11680a8)

**Expected behavior**

With 2.25.0 and previous version, follow exact same steps above, but you get:

![stax25](https://github.com/staxrip/staxrip/assets/6276915/fa401f54-59c3-4bb1-ad8a-0e92a3db0c88)

**Comment by Dendraspis** [comment]
Sadly I can't reproduce it, because it works for me.
Have you tries different sources? Do you use the same setting files from your `v2.25` instance or do you use a clean one with fresh settings?

![image](https://github.com/staxrip/staxrip/assets/50659978/acb7441f-e029-435d-a355-6f65a515092a)

**Comment by Morku** [comment]
@Dendraspis 

Yes, other BD sources appears the same where 2.25.0 does not have the issue.

![grafik](https://github.com/staxrip/staxrip/assets/6276915/db81c743-be35-48a9-9ff8-6d8ce7390ec8)

I use a fresh setting, since settings move 2.25 to 2.26 did not work anyway.

Even when I extract 2.27.0 on a fresh folder to have an inital start (it asks for settings location, I always use the first option to store settings in Staxrip folder), the issue is the same.

**Comment by Morku** [comment]
Same issue with 2.28.0

**Comment by Dendraspis** [comment]
With the help of a contributor we could reproduce it and find the answer:

Please download this file: [libFLAC.zip](https://github.com/staxrip/staxrip/files/12437920/libFLAC.zip)
..and extract it into `.\Apps\Audio\eac3to` by overwriting the existing dll file.

Can you confirm, that it works for you then?

**Comment by Morku** [comment]
Yes, it fix the issue :) Thank you so much.

**Comment by Dendraspis** [comment]
You're welcome. Thanks for the report.  👍
