### ISSUE TITLE
Crop preview window is distorted on 2.26.0/2.27.0

### ISSUE THREAD

**Issue by Morku** [staxrip/staxrip#1091]
**Describe the bug**

When click on Crop, the preview image looks wrong. Like using a false, shifted Range. This only happen on 2.26.0 and 2.27.0. When I use 2.25.0, everything is fine.

![1](https://github.com/staxrip/staxrip/assets/6276915/f77ad061-8ff9-4e1d-8cde-897c54774320)

When I click Preview, the video looks fine as expected (2.27.0, 2.26.0, 2.25.0):

![2](https://github.com/staxrip/staxrip/assets/6276915/fd682e09-69d2-48ec-986c-82f253cbff80)

**Expected behavior**

On 2.25.0 everything looks fine in Crop:

![3](https://github.com/staxrip/staxrip/assets/6276915/09151e66-16ba-4b4a-a3b4-d65cd24e05c5)

**How to reproduce the issue**

Index and load a video and click on Crop.

I have tried another videosource -> same issue
I tried different Indexer (FFVideoSource and DGSource) -> same issue
I tried fresh new Setting -> same issue

Example video: https://www.dropbox.com/scl/fi/v9nqsq9wnj90mkdfxwvwi/Video.mkv?rlkey=yr1yn82iu3wda9gqlyt6kzcc0&dl=1

It all comes down to the current Staxrip version.

**Provide information**

Windows 11 Version 22H2 (Build 22621.2134)
NVIDIA GPU driver 536.99

**Comment by Dendraspis** [comment]
This is because you haven't read the [Changelog](https://github.com/staxrip/staxrip/blob/master/Changelog.md#v2260-2023-08-22) 😉  - it's a feature since `v2.26` that is enabled by default:

```
- Add option to tonemap videos in Crop window
- Add option to enhance contrast in Crop window for easier cropping
```

You can disable it in the template/options.
