### ISSUE TITLE
Auto scrolling for Deezy

### ISSUE THREAD

**Issue by THGhost** [staxrip/staxrip#1092]
Right now, during the encoding process when using Deezy, it shows the current percentage. But you need to scroll all the way down to the bottom of the window to see it. Would it be possible to have it automatically scroll to the bottom every time it refreshes with a new percentage?

![sdjnghksdf](https://github.com/staxrip/staxrip/assets/32550606/48d0ff59-c342-4898-bc01-18ed80563cf7)

Notice how underneath "---- Step 3 of 3 ---- [DEE encode]", you can't see past the 41.1% reading due to the window not scrolling automatically.

**Comment by Dendraspis** [comment]
Thanks for the report, will be fixed in the next release coming later...
