### ISSUE TITLE
HDR tonemapping in Crop window

### ISSUE THREAD

**Issue by THGhost** [staxrip/staxrip#1096]
In v2.28.0, possibly in v2.27.0 as well, if you have "Tonemapping for HDR videos" enabled (enabled by default), the Crop window will apply tonemapping to not only HDR videos, but also to 4K SDR videos, resulting in the colours looking extremely blown out.

Tonemapping disabled:
![1](https://github.com/staxrip/staxrip/assets/32550606/45977f98-5383-463e-8a2b-b283afd61a14)

Tonemapping enabled:
![2](https://github.com/staxrip/staxrip/assets/32550606/1eaaabe4-2fa6-4fd0-a48d-ebcd0d063532)

**Comment by Dendraspis** [comment]
I know, this was the first part of the new feature. Because of the important bugfixes I had no time to extend it yet.

I guess the next release will come with an option to exclude 8bit sources. 😄

**Comment by THGhost** [comment]
Haha, no worries 😁 Just something I noticed and thought was odd. Had a eureka moment when I thought about disabling the tonemapping feature.

**Comment by Dendraspis** [comment]
Damn, I outsmarted myself - it is already implemented.  😂   

So it must be your source file. Can you share the Media Info of the source file and/or a screenshot of StaxRip's main window?

**Comment by THGhost** [comment]
![Screenshot_20230826-005042~3](https://github.com/staxrip/staxrip/assets/32550606/f1988f3b-e860-4536-89c4-d85f75850886)
![Screenshot_20230826-005116~3](https://github.com/staxrip/staxrip/assets/32550606/0fa65351-9fcf-435d-a72f-1e7e039354ea)

**Comment by Dendraspis** [comment]
I managed to outsmart myself twice, sorry.  🤦‍♂️ 

A better/proper way to identify HDR content is added, so it will be fixed in the next release.
