### ISSUE TITLE
New SMDegrain Light Grain is too aggressive

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1098]
**Describe the bug**

New SMDegrain Light Grain is too aggressive.
It shaves too much grain and I wouldn't name it Light Grain.
My compression test shows reduction from about 230 Mb to 130 Mb file size with new SMDegrain Light Grain and it is comparable with a result of aggresive 2 pass SMDegrain filtering with a very grainy source from [SMDegrain documentation](https://raw.githack.com/Dogway/Avisynth-Scripts/master/SMDegrain/SMDegrain.html) 
Who advised you to use `prefilter=3` for it? I think it is the reason.
I'm still playing with it will post more info later if find something interesting.

**Comment by Dendraspis** [comment]
Oh yeah, `prefilter=3` adds a deblocker aswell. I have changed all presets back to the default setting: `prefilter=-1`.

Thanks for the report, it will be fixed in the next release...
