### ISSUE TITLE
nVEnc (Rigaya) subrburn

### ISSUE THREAD

**Issue by fmohican** [staxrip/staxrip#11]
Line 402 from NVEnc.vb
`New StringParam With {.Switch = "--vpp-subrbun", .Text = "Subrbun"},`
to
`New StringParam With {.Switch = "--vpp-subburn", .Text = "Subburn"},`

Rigaya change the function name, so `-vpp-subrbun" will return error.

**Comment by gnucian** [comment]
> Line 402 from NVEnc.vb
> `New StringParam With {.Switch = "--vpp-subrbun", .Text = "Subrbun"},`
> to
> `New StringParam With {.Switch = "--vpp-subbun", .Text = "Subbun"},`
> 
> Rigaya change the function name, so `-vpp-subrbun" will return error.

It's '--vpp-subburn', not '--vpp-subbun'.

**Comment by fmohican** [comment]
To be more precise
`New StringParam With {.Switch = "--vpp-subburn filename=", .Text = "Subburn", .BrowseFile = True},`
however i don't know how to add quote to filename

Rigaya: https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-subburn-param1value1param2value2

```
Example1: burn in subtitle from the track of the input file
--vpp-subburn track=1

Example2: burn in PGS subtitle from file
--vpp-subburn filename="subtitle.sup"

Example3: burn in ASS subtitle from file which charcter code is Shift-JIS
--vpp-subburn filename="subtitle.sjis.ass",charcode=sjis,shaping=complex
```

**Comment by Revan654** [comment]
This already Exists in the Encoder. Just Add "" for Quotes.

**Comment by fmohican** [comment]
@Revan654 check you're encoder
https://github.com/staxrip/staxrip/blob/master/Encoding/NVEnc.vb#L403
and check function name & call its different, the function should be called like:
```
--vpp-subburn filename="path\to\sub\MySubSaa.ass",charcode=utf-8,shaping=complex
```

**Comment by fmohican** [comment]
@stax76

**Comment by Revan654** [comment]
> 
> 
> @Revan654 check you're encoder
> https://github.com/staxrip/staxrip/blob/master/Encoding/NVEnc.vb#L403
> and check function name & call its different, the function should be called like:
> 
> ```
> --vpp-subburn filename="path\to\sub\MySubSaa.ass",charcode=utf-8,shaping=complex
> ```

I added subrbun and Testing Tool rejected the Change. Saying --vpp-subburn should be used instead. When I get time I'll Make some changes to the Encoder.

**Comment by stax76** [comment]
I've made a change on this. It still don't have dedicated GUI support for every parameter however, that would be a bit dull work...
