### ISSUE TITLE
little bug in Preview window with Zoom In - Zoom Out

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#110]
Hello Stax and all Contributors,

The Zoom In / Zoom Out commands inside the Preview window are inverted:
- when you click Zoom In, the image gets smaller, it should get bigger
- when you click Zoom Out, the image gets bigger, it should get smaller

It's a small bug with no major impact on usage.
Thanks

**Comment by stax76** [comment]
Hello, last build corrects it.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS

**Comment by 44vince44** [comment]
Hi Stax! Yes, now the naming is correct indeed. Many thanks !!!
