### ISSUE TITLE
ShowPreview skips to the next EventCommand Before Closing

### ISSUE THREAD

**Issue by MuhammadBayiz** [staxrip/staxrip#1102]
**Describe the bug**
ShowPreview Command will be Skipped/ignored to the next command before i close the preview, I have setted "AddJob & ShowJobsDialoge" Command that runs After "ShowPreview" the problem is Preview Window Shows and Immediately "AddJob & ShowJobsDialoge" Runs Before I Close the Preview Windows Which Kills The point of Previewing Before Adding The Job
 

**Expected behavior**
Both "AddJob & ShowJobs" Waits for me to close the Preview Window Then They Should Run

**How to reproduce the issue**
Create a "ShowPreview" EventCommand And "AddJob & ShowJobsDialoge" Command Also That Runs Aftr it Immediately on the Same Position Example They Both Run When the Source is loaded

**Comment by Dendraspis** [comment]
There will be a new command `ShowPreviewDialog` that you can use for that purpose. Will be available in the next release...

**Comment by MuhammadBayiz** [comment]
Awesome thanks!
