### ISSUE TITLE
Bluray Playlists not shown and is thus not selectable.

### ISSUE THREAD

**Issue by OnbekendHH** [staxrip/staxrip#1103]
Starting with Version 2.27, selecting a Bluray Playlist is no longer possible. The List is simply left blank. 
![2023-08-26 18_31_42-StaxRip - Processing](https://github.com/staxrip/staxrip/assets/7472445/503faa16-6276-49c9-a814-ac219573d0a4)

**Comment by Dendraspis** [comment]
Please take a look at #1090, especially at my fix [here](https://github.com/staxrip/staxrip/issues/1090#issuecomment-1693113037).
