### ISSUE TITLE
Crop not working

### ISSUE THREAD

**Issue by legosoff** [staxrip/staxrip#1104]
StaxRip 2.27 and 2.28 crop not working,  StaxRip 2.25 works great. 
https://radikal.host/i/F50gvT

**Comment by Dendraspis** [comment]
I thought you asked already on Discord?

Disable Tonemappingin `Options > Image > Crop`, I don't know why it's not working for you, asserting that you use a clean instance with fresh settings.

**Comment by legosoff** [comment]
Yes, it's already working. Thank you.
