### ISSUE TITLE
Audio Codec has Abnormal Criteria Matching

### ISSUE THREAD

**Issue by MuhammadBayiz** [staxrip/staxrip#1105]
**Describe the bug**
Recently  i opend a feature request to add audio codec and other audio related info to Criteria Options and with the recent Versions of 2.27 and 2.28 it has been added but now the audio matching doesnt match excatly what i ask it for, so I'm trying to create an auto audio passthru for AAC with 2 Channels and i have setted the Settings as Shown Below:
![image](https://github.com/staxrip/staxrip/assets/63660736/5cabec20-25f0-4a69-bc0c-bf2de8a770d8)
as you can see the rules are if the first audio codec contains AAC and has 2 channel it shoula load the copy/mux profile for the first audio but that's not the case when testing it i tried loading a video with the following Codec and Audio info:
`
EAC3 6ch 48kHz 768Kbps Korean (ID1 Korean.eac3)
`
with that audio the rule matches it and loads Copy/Mux Profile which is wrong the audio codec doesn't have AAC and surely its not 2 channel (even though i have Selected Match all in the Criteria) My Default Audio Profile That Loads on start up isn't Copy/Mux Its a Custom AAC With 2 Channel Profile Which mean if the audio already has aac with 2 channel it should load copy/mux if not then my default profile which is aac with 2 channel should be selected.

**Expected behavior**
Would like it to work as expected like it matches the desired Audio Codec & Channel

**How to reproduce the issue**
Create an Event Command with the info in the screenshot and try an EAC3 Audio

MediaInfo:
https://privatebin.net/?80b6866a7c4330fa#D4U9AWC39DzMfLr1mBS73ydCSxBSHPHKkzcMx3vXhBHH

**Additional context**
Also its mentionable to say that There's Three Audio Bitrate Options 
![image](https://github.com/staxrip/staxrip/assets/63660736/0a5798f1-93fb-4efb-a85a-1f7be0d8ce65)

The "Audio Bitrate" Option Might be a bug because theres already Audio Bitrate for profile 1 & 2

**Comment by Discograp** [comment]
+ mp3 "damaged"

**Comment by MuhammadBayiz** [comment]
> * mp3 "damaged"

What Do you mean?
 I don't use mp3 container

**Comment by Dendraspis** [comment]
I try to find a similar source file with a 6ch eac3 audio track, test it and come back to you..

**Comment by Discograp** [comment]
Mr. Dendrapsis is too lazy to check - mp3 with a defect

![mp3](https://github.com/staxrip/staxrip/assets/95682410/077457e1-548b-4fe4-b45c-972cbc62e0a3)

**Comment by MuhammadBayiz** [comment]
> In your case you should be fine setting the default profile to `Copy/Mux` and set a criteria for `Codec Not Contains AAC` and `Channels Is Not 2` to set your Stereo-AAC-profile.

Before i report the issue i tried this way in 2.27 didn't work but now that you mentioned it in 2.28 its working!! thanks a lot for the quick and the greate support you providing :)

**Comment by MuhammadBayiz** [comment]
Now after two days of using it this way i haven't had any issue until this audio came up 
`EAC3 2ch 48kHz 128Kbps Korean (ID1 Korean {Korean}.eac3)`

So I'm thinking since i have set "Match All" the ruling did matched with 2 channel as for the other condition of "Contains not" "AAC" i think that it matched it wrongly since "Enhanced AC3" has two "A" and a "C"+ in it probably it matched because of that, it's just a thought, maybe we can use regex for contains condition to solve this and enhance the feature?

[Mediainfo](https://privatebin.net/?05530d47edf8120a#9kMoJka3br23ogVutFoqWb99sKBRjrWFDPf9m3gaEJDd) 

[Audio File](https://drive.google.com/file/d/1GzBywIDSxvSBbMYfqjz-bIASnt8M-Kql/view?usp=drive_link)

**Comment by MuhammadBayiz** [comment]
Sorry i forget to do further clarification on the issue i faced, i set the criteria to match audio that are not "AAC" and "2 Channels" and to load my AAC-Stereo Profile for them, that audio with "Eac3" "2 Channel" didn't match the conditions (meaning the criteria thought they were AAC 2CH) and the profile "Copy/Mux" loaded for them

**Comment by Dendraspis** [comment]
Can you post the exact criterias you've set now?

**Comment by MuhammadBayiz** [comment]
Surely
![Screenshot_20230831-124000_Shadow PC](https://github.com/staxrip/staxrip/assets/63660736/e23ece53-683e-49fc-a32e-bf70fd1a6541)

**Comment by Dendraspis** [comment]
Great, so after looking at your screenshot I found the problem:  me.  😅

Of course you have to use `Match any` instead of `Match all`.

**Comment by MuhammadBayiz** [comment]
So they both were mixed? Lol 
Let me try match any

**Comment by MuhammadBayiz** [comment]
Yup that solved it. thanks for investigating
Although this way they're sorta confusing since match any/all means the opposite but nowing that makes it work hehe

**Comment by Dendraspis** [comment]
>  this way they're sorta confusing since match any/all means the opposite

This is a logical thinking and interpretation thing, that could have confused me too.  😅 
Instead of thinking toward your goal, just try to think in terms of those two criteria:

`EAC3 Contains Not AAC`  ✔️ 
`2 Is Not 2` ❌ 

✔️  and  ❌  »  ❌ 
✔️  or    ❌  »»  ✔️

**Comment by MuhammadBayiz** [comment]
Got it sorta, now i think about it, it makes sense
