### ISSUE TITLE
ffms2/ffmpeg progress bar is broken on v2.28.0-x64

### ISSUE THREAD

**Issue by zuba0012** [staxrip/staxrip#1109]
Fixed previously in v2.25.0 for issue #1054 but bug seems to have returned and happening with ffms2 indexing or ffmpeg conversion. Changing theme, scale factor doesn't make a difference. Running latest Windows 10 version. Happens when using fresh run of v2.28.0-x64 with the included ffms2 v3.0.1.0 1329+20 ad42af1 StvG and ffmpeg v6.0 N-111762-ga1928dff2c-x64-gcc13.2.0, for former just indexing any hevc .mkv and for latter, I was converting hevc to prores using vapoursynth script, was fine in older versions like v2.19.0.

![image](https://github.com/staxrip/staxrip/assets/71300396/73c4eb44-a32a-435a-8645-08a9c1cc2c09)

![image](https://github.com/staxrip/staxrip/assets/71300396/1ae2d8c3-6946-48d2-b6b3-76ba14e30bac)

**Comment by Dendraspis** [comment]
When you use fresh/clean settings without transferring them from older StaxRip versions, it should work.

![image](https://github.com/staxrip/staxrip/assets/50659978/a4632d7c-780b-4740-8362-4d7d5601b8eb)

**Comment by Dendraspis** [comment]
I have investigated a bit more and I found the problem - on frame numbers >10000 there is no gap after `=`.

Will be fixed for the next release...
