### ISSUE TITLE
Update: QSVEnc 3.29 

### ISSUE THREAD

**Issue by kunjar** [staxrip/staxrip#111]
Hi,

Will the next beta or stable build include QSVEnc 3.29?

https://rigaya34589.blog.fc2.com/blog-entry-1206.html

Thanks

**Comment by Patman86** [comment]
Hi kunjar,

thx for request. There are some tools that need to be updated, see [here](https://github.com/staxrip/staxrip/issues/58#issuecomment-572775850)

**Comment by stax76** [comment]
Last build has a newer version.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS
