### ISSUE TITLE
x265 Setting aq-bias-strength and hist-threshold Gives Error

### ISSUE THREAD

**Issue by bosox188** [staxrip/staxrip#1110]
**Describe the bug**
When encoding an x265 video and setting aq-mode to either 3 or 5, an option to set aq-bias-strength appears, which is supposed to control the dark level bias for those modes. However, in the current version of Staxrip, setting aq-bias-strength to anything other than its default value of 1.00 leads to an error when trying to run the encode. Similarly, setting the hist-threshold option to anything other than its default value also leads to an error when trying to run the encode (the hist-threshold error is independent of aq-mode or aq-bias-strength setting).

**Expected behavior**
When aq-mode is set to either 3 or 5, aq-bias-strength should work as an adjustable option as it's supposed to be in the Patman mod version of x265 that StaxRip includes. Additionally hist-threshold should either work as an adjustable option or be removed from the GUI if it's no longer used in x265.

**How to reproduce the issue**

Reproducing aq-bias strength issue:
1. Open any video file, set encoder to x265.
2. Set aq-mode to either 3 or 5, which will reveal the aq-bias-strength option.
3. Set aq-bias-strength to a value other than 1.00 (I used 0.90).
4. Attempt to run the encode.

Reproducing hist-threshold issue:
1. Open any video file, set encoder to x265.
2. Set hist-threshold to a value other than the default of 0.03 (I used 0.01).
3. Attempt to run the encode.

**Provide information**

Log for aq-bias-strength error: https://pastebin.com/m3UgHDJA
Log for hist-threshold error: https://pastebin.com/mqmkNzVk

These errors are occuring in the latest StaxRip version (v2.28) and from what I have checked, the errors also exist in every version back to at least v2.22. The last working version that I have used is v2.13.

Another important note is that both of these errors are occurring with the x265.exe that was included with StaxRip (which I believe is the Patman modded x265). For the aq-bias-strength issue, I tested it out after subbing in a version of the DJATOM Mod x265 (v3.5+131-aMod), and after doing so, aq-bias-strength worked and encoded just fine. However, that did not resolve the hist-threshold error. I also tried taking the Patman modded x265 from Patman's page and using it in replacement, and in that case both errors would still occur.

**Additional context**
Part of the reason I discovered this issue is because I had a prior encoding profile from v2.13 that included non-default settings for aq-bias-strength and hist-threshold. However, when testing for these errors, I used a clean copy of v2.28 without any settings/templates/profiles imported from an older version.

**Comment by Dendraspis** [comment]
Thanks for the very detailed report.

The `--aq-bias-strength` issue is already fixed and will be available in the next release.

Sadly the `--hist-threshold` parameter is currently missing in the builds, but @Patman86 will fix it for the release after the next one.
