### ISSUE TITLE
Log File - Source Media Info is missing

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1114]
I just noticed that in the latest version, the log file is missing the media info of the source file. Only the target media info is added.

Needless to say that this is essential and existed in the previous versions. To have the media info of both the source and target in the log.

**Comment by Dendraspis** [comment]
A damn old bug, but I've fixed the problem for now, so that the media info is also added when processing a job.

Will be fixed in the next release...

**Comment by Zodler** [comment]
I noticed a bug with **Media Info Target File** also.
Please look into that too.
Sometimes it outputs only one line.

**Comment by Dendraspis** [comment]
Please open a new issue and provide proper information, especially on reproduction.
