### ISSUE TITLE
Thumbnail created notification blocks the Staxrip window

### ISSUE THREAD

**Issue by nulledone** [staxrip/staxrip#1115]
Basically when you focus on the staxrip, sometimes it puts the "Thumbnail creation finished" window to the background, completely blocking the app.

Video explanation is attached.

https://github.com/staxrip/staxrip/assets/29547468/a9460a88-fcc2-4a8c-83d5-c6439b1b6d88

Possible solutions;

1. Allow moving main window when this popup exist.
2. Make notification window accessible when clicking on app icon.
3. Integrate this notification to the UI on the bottom (kind of like adding notifications bar to the app, but will take lot of work. may be of use for notifying jobs finished as well.)

**Comment by Dendraspis** [comment]
The video was pretty helpful. Sadly I can't reproduce the problem, no matter how often I try.

Nevertheless I've changed the code a bit, so maybe it will work with the next release for you.
Let's keep this issue open till be have your feedback with the next release....
