### ISSUE TITLE
Please Add AV1 Option in VCEEncC for RDNA3 GPU

### ISSUE THREAD

**Issue by scweeny** [staxrip/staxrip#1117]
Thank you as always for your work.

My request is to add AV1 codec to AMD VCEEncC.

VCEEncC already has the ability to encode AV1 codec in Staxrip,  it's just not enabled yet.

You probably already know this,

Here's a link to VCEEncC's Option List.

https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md

Thank you.

**Comment by Dendraspis** [comment]
Thanks, also for the direct link.  🙂 
Will be added in the next release...  👍

**Comment by kmapache** [comment]
If convenient, please add the AMF encoder option for ffmpeg by the way. Thank you

**Comment by scweeny** [comment]
> Thanks, also for the direct link. 🙂 Will be added in the next release... 👍
Thanks for your work.. ^^
