### ISSUE TITLE
Add new Tune=2 SSIM to Svtav1

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#1118]
They added new tune SSIM with v1.7
--tune -Specifies whether to use PSNR or VQ as the tuning metric [0 = VQ, 1 = PSNR, 2 = SSIM]-
--tune 2 (SSIM)

https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/CHANGELOG.md?ref_type=heads

https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md#encoder-global-options

**Comment by Dendraspis** [comment]
Obviously I missed that one. Will be added with the next release...
