### ISSUE TITLE
Resize resolutions

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#1119]
Can you change (1680 x auto = 1680 x 0) to (1440 x auto = 1440 x 0).
Also can you add (2880 x auto = 2880 x 0) for 4k 4/3

1680 not match to any standard resolution but 1440/1080=4/3 there is also 1600/900=16/9 but not much popular

**Comment by Dendraspis** [comment]
Gladfully I know what you're talking about.. Next time please fill out the feature request template...
And you know, that you can add/change/replace them by your own?

But I'll add them when I fix the typo on `1680`....

**Comment by darkcity87** [comment]
I know i can change, since they are standard 4/3 resolution i thought its more convenient to change release level so every new updates gets with standard resolution.

**Comment by Dendraspis** [comment]
I guess most people do it manually, but I've added both.
Nevertheless 4:3 is a bit old school, but for now they are in. 😄
