### ISSUE TITLE
Subtitle region codes get erased

### ISSUE THREAD

**Issue by THGhost** [staxrip/staxrip#1120]
**Describe the bug**
StaxRip v2.29. Subtitles that have region codes assigned to them, e.g. eng-US, bg-BG, da-DK, etc, get erased alongside their languages when inputted into StaxRip.

**Expected behavior**
Region codes and languages should be carried over and display correctly in the Container Options window.

**How to reproduce the issue**
Assign a region code to any subtitle inside an .mkv file, input it into StaxRip and open the Container Options window. 

**Provide information**
Source file in MKVToolNix GUI (note the subtitle region codes):
![1](https://github.com/staxrip/staxrip/assets/32550606/560bfbf6-1d01-49cc-9e35-f24083097efa)

Source file inside StaxRip's Container Options window (note the lack of region codes & languages except for those with track names):
![2](https://github.com/staxrip/staxrip/assets/32550606/d91080e6-e1e3-41fd-af41-03b5c7e182d9)
(The Netherlands subtitle's language didn't carry over despite having "Netherlands" as its track name, but that's a separate issue.)

**Comment by Dendraspis** [comment]
Could you please provide a short sample file with those subtitles? Would make it a lot easier to find the exact problem.

I guess it has to do with the latest language fix that prevents StaxRip from crashing. But some of those languages should not have been cleared out.  🫤

**Comment by THGhost** [comment]
https://mega.nz/file/e4sxjZzR#VdJrWROm_-phGOYF75Jm8W8ooJcAJK1W8wU7bs_KgQk

**Comment by Dendraspis** [comment]
Thanks, I'll try to find a solution till the next release.

**Comment by cacafuti8888** [comment]
Hi, same issue. Don't remember this happening in previous versions or i missed it happening.

**Comment by THGhost** [comment]
Any progress on this? I hope so :)

**Comment by gkalemis** [comment]
In version 2.28 subtitle language is parsed correctly. In 2.29 the names ID XX are undertermined

**Comment by THGhost** [comment]
> In version 2.28 subtitle language is parsed correctly. In 2.29 the names ID XX are undertermined

Yep, something definitely went wrong after 2.28.

**Comment by THGhost** [comment]
Just FYI, this is still a problem with v.2.3.0.

**Comment by Dendraspis** [comment]
Sorry for the late response. 
I'm aware of this language issue, sadly it is not that easy to solve. I'll try my best to fix it for the next release...

**Comment by cacafuti8888** [comment]
> Sorry for the late response. I'm aware of this language issue, sadly it is not that easy to solve. I'll try my best to fix it for the next release...

Not a problem, take all the time you need. Stick on 2.28 until it's fixed. Thanks for the message

**Comment by Dendraspis** [comment]
Here is a hotfix for this issue. It would be nice if you could test it and give me some feedback:
[StaxRip v2.30.2.zip](https://github.com/staxrip/staxrip/files/13714377/StaxRip.v2.30.2.zip)

**IMPORTANT:** 
Replace the `StaxRip.exe` from `v2.30` with this one. Be aware, that there is also a new Subtitle Demux Mode that demuxes *all* subtitles. This one is the default setting, if you use existing/old templates. Beside that there should be no side effects.

**Comment by cacafuti8888** [comment]
> Here is a hotfix for this issue. It would be nice if you could test it and give me some feedback:
> [StaxRip v2.30.2.zip](https://github.com/staxrip/staxrip/files/13714377/StaxRip.v2.30.2.zip)
> 
> **IMPORTANT:** 
> Replace the `StaxRip.exe` from `v2.30` with this one. Be aware, that there is also a new Subtitle Demux Mode that demuxes *all* subtitles. This one is the default setting in case you use existing/old templates. Beside that there should be no side effects.

Tested with one file, so good so far. I'll try with more files and post the results

**Comment by THGhost** [comment]
The hotfix works, subtitle region codes are still removed inside StaxRip but they aren't erased entirely like before. No "Undetermined" for every track anymore, except for Filipino subtitles for some reason. Would it be possible to have the subtitle region codes left untouched? e.g. "eng-US" is no longer replaced with "eng"?

**Comment by Dendraspis** [comment]
That will be the next step, that might take a bit, so maybe for the release after the next one.
Somehow pretty difficult, but it should be doable.

But good news that the 3-letter-language-codes are working again. Thanks for the feedback. 👍

**Comment by Dendraspis** [comment]
So I have changed a few things here and there and ... you'll see it in the next release.

The implementation might be a bit incomplete, so if you notice anything, please gimme a hint on the Discord (#staxrip-related), write a post below or open a new issue.
