### ISSUE TITLE
Ability to encode multiple audio files using custom settings without loading a video

### ISSUE THREAD

**Issue by abdulkaddir** [staxrip/staxrip#1123]
**Is your feature request related to a problem? Please describe.**
No, Not really but it would be a nice feature to have. workaround is possible but it requires user to add a video just for encoding the audio.

**Describe the solution you'd like**
The audio tab should have option to add multiple files which the user can encode according to his audio profile without loading a video.

Currently stax allows the user to add 1 audio file and then the user can right click>execute to encode the file using his desired profile. 
I think it should be possible to pipe multiple files through ffmpeg to your desired encoder. it can be done by sequentially feeding all the files that the user adds to ffmpeg>encoder using the job list feature. this is one suggestion but i think it can also be implemented other ways.

**Describe alternatives you've considered**
Alternative is adding files 1 by 1 and executing in the dialog box. or loading a dummy video and adding multiple files to the container so that each one is encoded and present in temp folder.

**Explain why the feature matters to you**
would be helpful is mass encoding lossless to lossy audio or any other situation where user just needs to encode the audio without encoding the video.

**Comment by darkcity87** [comment]
You can only encode audio from video files ''video profile>copy mux''.
For audio files you can use [https://github.com/jlw4049/FFMPEG-Audio-Encoder](https://github.com/jlw4049/FFMPEG-Audio-Encoder)
it support batch encodes, job quene, encoder profiles

**Comment by THGhost** [comment]
I'd very much like this feature to, especially since StaxRip now has proper EAC3 encoding with DeeZy. Having to import multiple audio files individually and click "Execute" on every single one of them is rather tedious.

**Comment by Dendraspis** [comment]
Looks like I have totally forgotten to answer....

So it is possible to drag & drop audio files into the audio fields at the bottom of the main window. After setting up the wanted profile, you can right-click on the text field and select `Execute`. Your audio file will be converted without any need to load a video file.

**Comment by abdulkaddir** [comment]
yup but its one at a time, i wanted a feature where you could select multiple at once and execute,

**Comment by Dendraspis** [comment]
So basically something like `Execute All` ?  🤔

**Comment by abdulkaddir** [comment]
yup but execute would also do, but as you can see the column only allows you to select one audio file. if you could select many followed by clicking execute to encode them all then that is what i am referring to.

**Comment by Dendraspis** [comment]
I will think about it, but keep in mind, that StaxRip is a Video Encoder GUI at first place....

**Comment by Dendraspis** [comment]
The next main version, `v2.42` will have an `Execute all` command implemented. Due to the fact, that this is not an Audio Encoder GUI, I won't spend a lot of time to build in some fancy stuff.

Hope it will useful for you anyway...

**Comment by jessielw** [comment]
> yup but its one at a time, i wanted a feature where you could select multiple at once and execute,

You can use the deezy command line to do what you want outside of staxrip, if your intention is batch encoding. DeeZy supports the **positional** input, this can be files or folders, note you need to utilize the [glob](https://www.geeksforgeeks.org/how-to-use-glob-function-to-find-files-recursively-in-python/) feature if you are interested in batching entire directories. 

Here is an example command line:
```
DeeZy encode ddp --dee "PATH TO DEE" -t 0 -b 768 -c 6 input.mkv
```
Note: in the above example we're setting the **-t** arg which is for **audio** to **0**, which would be the first track. 

Example command line with multiple inputs:
```
DeeZy encode ddp --dee "PATH TO DEE" -t 0 -b 768 -c 6 input.mkv input2.mkv input3.mkv
```
Note: notice how you can keep appending files you want completed? Keep in mind if there is spaces in the file name you should quote them (you can also quote each one) e.g. `"input3.mkv"`

**The Power of glob**
Example command line with a directory utilizing glob to select all mkv's in a single folder:
```
DeeZy encode ddp --dee "PATH TO DEE" -t 0 -b 768 -c 6 "directory/nested_path/*.mkv"
```

Example command line with a directory utilizing glob to recursively select all mkv's in a directory path: 
```
DeeZy encode ddp --dee "PATH TO DEE" -t 0 -b 768 -c 6 "directory/nested_path/**/*.mkv"
```

The command line interface is powerful and built for this particular use case. Currently there is a downside to using it in command line. This has to do with **audio delay**. When paired with **StaxRip**, **StaxRip** is handling the delay detection and feeding it as an argument to **DeeZy** like so `-d=10ms`. The benefit to this is that the delay is removed from the audio, making it **1:1** with the video. 

If you don't supply an `-o`, the program will automatically append **[delay 0]** to the file name if there is a delay detected, but it won't automatically remove it without the delay being fed before hand. I had intentions of coding it up to add a new arg that actually removes the delay, but it's not something I've gotten around to yet. 

Also when utilizing it in **batch** mode, it will assign the **-t** (track) arg to **ALL** files. So if you we're to specify **-t 1** (the second track) and a file does not have the second track, it will error and continue processing the other ones. 

You can find more examples and the repository link [here](https://github.com/jessielw/DeeZy).
