### ISSUE TITLE
Cutting filter disappears / does not work properly when a field filter is set.

### ISSUE THREAD

**Issue by Flyk3** [staxrip/staxrip#1124]
When I cut a video via Preview, then set a QTGMC Progressive Field filter, the cutting disappears and an error message appears:
> The cutting filter settings don't match with the cutting settings used in the preview. This can usually be fixed by opening and closing the preview.

Opening and closing the preview window solves the problem, but takes a long time with the QTGMC filter activated.

**How to reproduce the issue**
1. Download StaxRip v2.29.
2. Load a video file into it.
3. Cut it via preview:
![image](https://github.com/staxrip/staxrip/assets/145803606/88c798e8-2917-44b4-b1a3-bd6c1dc0314f)
4. Set the field filter: Field -> Deinterlace -> QTGMC -> QTGMC... -> Fast -> Progressive Full Repair. The cutting disappears and following error message appears:
![image](https://github.com/staxrip/staxrip/assets/145803606/7db073c6-c1f4-4ac0-9179-33cc6ea6a743)
The code for the Field-Filter: `QTGMC(preset="Fast", InputType=3, sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8)`

Now I don't select the filter manually each time, instead I have saved it in my template. If I now import a video file, cut it and then activate the filter, no error message appears, but StaxRip will ignore the cutting. It would encode the complete video.
However, you can trigger the error message if you click on Crop after activating the filter.

I didn't have that problem before, so I tried old versions of StaxRip. The problem only exists since v2.26. With v2.25 everything works fine.

**Comment by Valdiralita** [comment]
Same problem but more general repro:

1. Cut in preview
2. Change script

**Comment by Ding-adong** [comment]
What have you done now?

Cutting kept on disappearing.

**Comment by Dendraspis** [comment]
Took me a bit, but I have solved it now for the next release. At least the part that caused this issue.
I'll close this issue and hope, that the fix won't create other issues/bugs. My tests run fine, but as always...
