### ISSUE TITLE
x264 2-pass mode

### ISSUE THREAD

**Issue by mnejing** [staxrip/staxrip#1126]
So I've been considering swapping to StaxRip from MeGUI, because I do prefer having a bit more granular control that I can't quite get from MeGUI. 

I've been more or less copying over a profile I've created and refined the way I like, and while I've managed to get most everything translated, I keep noticing something in the command line box. When I have 2-pass mode selected, the command line is still showing "--pass 1" which, of course, is less than 2. 

I've yet to even bother encoding something solely because that's not being reflected accurately. Selecting any 264 profile and trying to change it to 2-pass always results in the command line showing "--pass 1". I really don't want to test if that's just a UI bug or if it's actually passing that to the command line. 

To replicate, literally just pick or create an x264 profile and set the mode to 2pass (or 3pass if you'd like, it's the same). This behavior was noticed a few versions ago, and still happens in the most recent release.

**Comment by mnejing** [comment]
So turns out not quite a bug? It's just weird display thing. On the main profile editing dialog, the command line says --pass 1. But if I look at the detailed command line (F4), it's got what I expect. Not sure why there is a discrepancy, or why, if the command line is overly long and complex cause of avs2pipemod, it's even displayed at all. 

Anyway, disregard, sorry.

**Comment by Dendraspis** [comment]
As you've already found out, the `--pass 1` parameter indicates the **first pass**, not the amount of passes. Using `Show Command Line (F4)` you can show all passes with each independent configuration if needed/wished.
So everything is okay.

> Perhaps a way to just directly edit the command line?

In that case you have to use the `Command Line` encoder and set everything manually.

**Comment by rchef7** [comment]
Ffj
