### ISSUE TITLE
Video Comparison: Long file names can make feature unusable

### ISSUE THREAD

**Issue by Samhayne** [staxrip/staxrip#1127]
**Describe the bug**

When the width of the clip tabs exceeds the entire window width, the shown frame will start flickering and the tool will become unusable.

**Expected behavior**

Window should be able to handle tabs that exceed the window's width by their size.

**How to reproduce the issue**

1. Compare two files with long file names.
2. If needed, reduce the width of the window until it is smaller than the tabs of the two clips.
3. Observe flickering of the the video clips making the comparison tool unusable.

**Provide information**

Occurring with StaxRip v2.29.0 and at least the version before.
Not happening in an old version I'm still using (Staxrip 1.7.0.6)
My OS: Windows 11

https://github.com/staxrip/staxrip/assets/7030482/7a35979d-9810-4138-a0e3-8f6d1e6629d4

**Comment by Dendraspis** [comment]
Will be fixed in the next release.....
