### ISSUE TITLE
Integrate avslibplacebo

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1132]
[avslibplacebo](https://github.com/Asd-g/avslibplacebo) is a high speed library for AVS+, ported from vs-placebo

It allows debanding, resampling (mitchell to native is magic), shader and tone mapping (even external LUT with tetrahedral interpolation) all by gpu with very good results and speed.

What about integrating in StaxRip? I have tried with the resampling part but I can't get the slider to work properly in my Staxrip command template.

**Comment by Dendraspis** [comment]
`avs_libplacebo` was already implemented and included in `StaxRip v2.25`....

**Comment by tormento** [comment]
Please read the last part too. I have issues integrating it, would you help me?

**Comment by Dendraspis** [comment]
You don't have to integrate it, because everything is already there .... just use it.  🤔

**Comment by Dendraspis** [comment]
There are no presets (yet), just open the Code Editor and put in the filter call you like, for example:
`libplacebo_Deband(2)`
