### ISSUE TITLE
Two questions about CPU load:

### ISSUE THREAD

**Issue by Pawelemwelt** [staxrip/staxrip#1133]
1) [StaxRip v2.9.0] (and earlier, up to) - 2.19.0] periodically (one or two cases per 100 normal launches) the StaxRip.exe process continues to load the CPU by 7-6%, sometimes from 10-30% in parallel with the Encoder x264 process. Solution to the problem = The StaxRip.exe process can be killed, the program will close and Encoder x264 will start working at 90% (you will have to combine the resulting audio + video files manually). Normally, the StaxRip.exe process takes up 0-0.1% CPU.
What does the StaxRip.exe process do when it simultaneously loads the CPU by 6-30% throughout the encoding time?
2) [StaxRip v2.29.0] The avs2pipemod64.exe file occupies 40% CPU (Load on HDD 2.9mbit\s), Encoder x264 50% (Load on HDD 0.1mbit\s). Killing the avs2pipemod64.exe process causes MKVTool to launch and move on to the next task.
StaxRip v2.19.0 without the parallel process avs2pipemod64.exe shows 40% higher video processing speed than StaxRip v2.29.0 with the parallel process avs2pipemod64.exe.
What does the avs2pipemod64.exe process do? Is it possible to get rid of it?

**Comment by Dendraspis** [comment]
1. If your setup is identical, there should be no difference. The only thing StaxRip does is watching and providing the information from the tools.
2. It reads the source file, converts it and pipes/forwards it to the encoder. Yes, in the options set `Pipe = None` [Not available with VapourSynth].
