### ISSUE TITLE
Filters (question and wish)

### ISSUE THREAD

**Issue by Pawelemwelt** [staxrip/staxrip#1134]
1) how to mirror a video (in the program you can rotate the video left and right, and also flip it from bottom to top, but how to mirror it)?
2) is it possible to mirror PART of the video (for example, a game Stream, in which I need to mirror the window with the Streamer, and leave the rest of the video unchanged, or vice versa)? Maybe you know about the presence of a similar filter in some other program?

**Comment by Dendraspis** [comment]
1. `FlipHorizontal()` - see AviSynth documentation
2. It should be possible, but nothing I can cover here....
