### ISSUE TITLE
Strange CPU load, what is it? (Pause/work mode)

### ISSUE THREAD

**Issue by Pawelemwelt** [staxrip/staxrip#1135]
I have been using Staxrip since version 1.8 or 2.0 and the problem occurs periodically.
At the time when I noticed this, 5% of the file had been processed (the program was on Pause).
Below is the data from the task manager (video processing mode and pause mode)
v.2.19.0
Pause Mode
Staxrip
>Staxrip 30% (WHAT DOES Staxrip DO?)
>Console window host 0%
>H 264 encoder 0%

Work mode
Staxrip
>Staxrip 30-32% (WHAT DOES Staxrip KEEP DOING?)
>Console window host 0%
>H 264 encoder 50-60%

About ten hours passed, the Staxrip process did not stop loading the processor by 30%.

A solution (but a bad one) is to kill the Staxrip process and H 264 encoder to continue working at full capacity of 90-95% (you will have to combine video and audio manually).

**Comment by Dendraspis** [comment]
Kind of a duplicate to #1133.

Sadly I wasn't able to observe that yet. Basically while encoding, StaxRip just watches and outputs the tool data.
The only procedures, that are called within StaxRip, are those, who require StaxRip to handle the information provided by the tool it executes. 

If you have a reproducible setup, please let me know - I would like to see and handle this issue....
