### ISSUE TITLE
--enable-qm on SVT-AV1 not being set to 1

### ISSUE THREAD

**Issue by McMasterGold** [staxrip/staxrip#1137]
When activating the "Enable quantisation matrices" option in the Rate Control menu of SVT-AV1, the appended parameter is "--enable-qm" which causes the following error:

Error Video encoding (v2.29.0)

Video encoding returned exit code: 1 (0x1)

--------------------------- Video encoding ---------------------------

SvtAv1EncApp 1.7.0-0+13-b922871f-[Mod-by-Patman]-x64-msvc1937

C:\StaxRip-v2.29.0-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll -y4mp "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2.avs" | C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --input - --width 1920 --height 1080 --output "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2_out.ivf" --frames 3000 --rc 0 --crf 38 --progress 2 --preset 4 --enable-qm --qm-max 9 --qm-min 0 --irefresh-type 2 --tile-rows 0 --tile-columns 0

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.7.0-0+13-b922871f [Mod by Patman]
Svt[info]: SVT [build]  :	Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Aug 29 2023 11:12:17
Svt[info]: -------------------------------------------
avs2pipemod[info]: writing 3000 frames of 60/1 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-10bit progressive video.
[SVT-Error]: No argument found for token `--enable-qm`
Error in configuration, could not begin encoding! ... 
Run C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --help for a list of options
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 0.003 sec.
avs2pipemod[error]: only wrote 0 of 3000 frames.

StaxRip.ErrorAbortException: Video encoding returned exit code: 1 (0x1)

--------------------------- Video encoding ---------------------------

SvtAv1EncApp 1.7.0-0+13-b922871f-[Mod-by-Patman]-x64-msvc1937

C:\StaxRip-v2.29.0-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll -y4mp "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2.avs" | C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --input - --width 1920 --height 1080 --output "E:\Videos\2023-10-02 00-17-20_temp\2023-10-02 00-17-20_new2_out.ivf" --frames 3000 --rc 0 --crf 38 --progress 2 --preset 4 --enable-qm --qm-max 9 --qm-min 0 --irefresh-type 2 --tile-rows 0 --tile-columns 0

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.7.0-0+13-b922871f [Mod by Patman]
Svt[info]: SVT [build]  :	Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Aug 29 2023 11:12:17
Svt[info]: -------------------------------------------
avs2pipemod[info]: writing 3000 frames of 60/1 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-10bit progressive video.
[SVT-Error]: No argument found for token `--enable-qm`
Error in configuration, could not begin encoding! ... 
Run C:\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --help for a list of options
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 0.003 sec.
avs2pipemod[error]: only wrote 0 of 3000 frames.

   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 353
   at StaxRip.SvtAv1Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Code\Github\staxrip\staxrip\Source\Encoding\SvtAv1Enc.vb:line 74
   at StaxRip.SvtAv1Enc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\SvtAv1Enc.vb:line 40
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 373

----------

The correct parameter is "--enable-qm 1", and the workaround is to place it as a custom parameter. With it, the encoding proceeds properly.

The log file is here: https://pastebin.com/Le3VZ65c

**Comment by Dendraspis** [comment]
`--enable-qm` is already fixed in #1122 and will be available with the next release.
