### ISSUE TITLE
Please add Constant Quality Mode to AV1 Nvenc

### ISSUE THREAD

**Issue by Kartus22** [staxrip/staxrip#1139]
Hello Good Master,

Please add Constant Quality Mode to AV1 Nvenc, i have tested it in another Encoding Software and its working fine, would be very nice if you can do that.

CQP is not working Accurately and is wasting much Bitrate for nothing.

EDIT:

Found CQ, we need to use VBR Quality First and set Bitrate to 0, then go to the Rate Control Tab and we need to Check Constant Quality Mode.

Maybe you can adjust it to be more visible?

![image](https://github.com/staxrip/staxrip/assets/72146704/3e05c9f2-51ee-4408-8793-4690ed59d340)
![image](https://github.com/staxrip/staxrip/assets/72146704/fcdba82f-4738-4592-9533-0b8bc9f9bdec)

**Comment by Augur1989** [comment]
i can confirm that the CQ calculation does not work correctly for AV1 nvenc in the latest staxrip version. a fix would be very appreciated.

**Comment by Kartus22** [comment]
I found CQ
![image](https://github.com/staxrip/staxrip/assets/72146704/a0bc65ad-1ab5-4413-8874-6679a5cffa9c)

**Comment by fromdetroit7** [comment]
that's just the way it works, can't be tweaked...same as hevc

**Comment by Dendraspis** [comment]
Will be added in the next release as this is a separate parameter.

Little addition to your statement here:
> Found CQ, we need to use VBR Quality First and set Bitrate to 0, then go to the Rate Control Tab and we need to Check Constant Quality Mode.

When you enable `Constant Quality Mode` the bitrate is set to `0` autimatically - no need to set it by yourself.
