### ISSUE TITLE
Error transcoding x265 HEVC to XviD

### ISSUE THREAD

**Issue by JK98062** [staxrip/staxrip#114]
Hi all,

Recently ran into an issue while Transcoding a video from x265 HEVC to XviD. I think the problem could possibly be related to the Color Space being 10bit (P010) on the Source File and YV12 on the Output File.

I’ve attached three files to here: [StaxRip | ProtectedText](https://www.protectedtext.com/StaxRip)
(Pass is staxrip)
The three files are as follows:
1. MediaInfo of Source File
2. StaxRip Error Message
3. Complete StaxRip Transcode Log

Any suggestions as to what I should do?

**Comment by 44vince44** [comment]
Yes you are right, it's a bit depth problem. You have to use the AVS+ filter: ConvertBits(8)
It is in Staxrip filters entries. Insert (under the source filter) by selecting:
Color > Convert > ConvertBits
Choose 8.

**Comment by JK98062** [comment]
That did the trick, just ran the same Transcode with the ConvertBits Filter added and it completed successfully.

Thanks for your help @44vince44

**Comment by 44vince44** [comment]
You're welcome JK!
