### ISSUE TITLE
HDR10 on AV1 videos

### ISSUE THREAD

**Issue by TERMINATOR461997** [staxrip/staxrip#1140]
I'm having an issue where I am trying to convert x265 HDR10 videos to AV1 HDR10. However, no matter the setting it is always encoding a 10Bit SDR video. I am using the SvtAv1EncApp encoder with an MKV container. I also tried using the correct color-space (2.2.1. Color Configuration) from the AV1 Metadata Handling Specification:

https://aomediacodec.github.io/av1-hdr10plus/#UsingHDR10plus

I am using the "LG New York HDR UHD 4K Demo" video to make sure the video is formatted correctly, but it still outputs SDR content. What am I doing wrong here? Does Staxrip not support HDR10 AV1 encoding yet?

Thank for you help.

**Comment by jeryll7** [comment]
Hi, unless you'll post full log from staxrip encoding session, no one will be able to tell you what you are doing wrong ... we can only guess...
SvtAv1EncApp is able to encode HDR10 videos properly, but you'll need to feed it with proper HDR info extracted from the source media. Staxrip ATM only support automatic VUI metadata injection only for AVC, HEVC encoders. For other encoders you must manually copy/set needed VUI values and those missing in the GUI manually add into custom section. Check your command line if it contains this part "`--enable-hdr 1 --color-primaries value --transfer-characteristics value --matrix-coefficients value --content-light value,value --mastering-display G(x,y)B(x,y)R(x,y)WP(x,y)L(max,min)`" ... if not you'll not get properly encoded AV1 HDR stream with SvtAv1EncApp encoder (for example for the "LG New York HDR UHD 4K Demo" the set of HDR VUI values extracted from source looks like this (translated to SvtAv1EncApp commands) `--enable-hdr 1 --color-primaries 9 --transfer-characteristics 16 --matrix-coefficients 9 --content-light 0,0 --mastering-display G(0.265,0.69)B(0.15,0.06)R(0.68,0.32)WP(0.3127,0.329)L(1200.0,0.05)`).

**Comment by TERMINATOR461997** [comment]
No need for the log file, you just explained what I did wrong. I assumed the HDR info would be automatically extracted and used in the new file like x265 does. So I have to manually extract the file, then add the code to the custom code box to make the file retain the HDT information. Thank you for the assistance. 

Any chance this is something we can make automatic; or is that up to the developer of SvtAv1encApp?
