### ISSUE TITLE
Broken progress bar when using mkvtoolnix

### ISSUE THREAD

**Issue by firezt** [staxrip/staxrip#1143]
**Describe the bug**
When mkvtoolnix is performing a task such as demuxing, the progress bar doesn't show any color as it did before.

**Expected behavior**
Show the color according to the theme in the progress bar to indicate how much work has been done.

**How to reproduce the issue**
Just try to demux some .mkv source.

**Provide information**
StaxRip v2.29.0

Screenshot of the described bug:
![1](https://github.com/staxrip/staxrip/assets/87192386/b92e4299-59fc-4b78-a3c1-4d862c4dadfe)

Thanks for reading.

**Comment by zuba0012** [comment]
Please note, this also still occurs with **ffmsindex**.

**Comment by Dendraspis** [comment]
Both should be fixed in the next release...
