### ISSUE TITLE
Default

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1148]
Hello! Downloaded and began using version v.2.29.0

when inputting any video into the software. Then I select a x264 or x265 CPU and their profile 422 8/10-bit and click to start processing.

in the x264 codec, profile 422 and 8/10-bit = after processing it produces i420 and 8-bit = automatic change of CSP does not work, you need to manually change input/output 422 and 8/10-bit

in the x265 codec, the profile is 422 and 10/8-bit = after processing it produces i420 and 10-bit = automatic change and manual change of input/output CSP does not work

in the QSVenc profile by default there is a forced auto-selection of CQP Value, with terrible levels

in the NVenc profile these levels are wonderful, but the forced auto-selection of NVenc 264/265 by default selects ineffective modes = preset P4-Default and profile Main = need to be changed to the preset (264/265)Default and profile (264)High+(265)Main

QSVenc need to change the CQP Value to QP1-I 18 / QP2-P 18 / QP3-B 18 < Constant QP
QSVenc need to change the CQP Value to QP1-I 18 / QP2-P 18 / QP3-B 18 < ICQ

Please fix these bugs, StaxRip is a wonderful software!

**Comment by Andrasolin** [comment]
x265 8-bit main Still Picture

this mode also does not work - the regular MAIN profile is activated...

**Comment by Dendraspis** [comment]
> in the QSVenc profile by default there is a forced auto-selection of CQP Value, with terrible levels

What do you mean by that? The default settings? These are mostly the default encoder settings.


I'll have a look the next days, but for the next time please open one issue per topic/bug group.

**Comment by Dendraspis** [comment]
> in the x264 codec, profile 422 and 8/10-bit = after processing it produces i420 and 8-bit = automatic change of CSP does not work, you need to manually change input/output 422 and 8/10-bit

❌  Can't reproduce it.

> in the x265 codec, the profile is 422 and 10/8-bit = after processing it produces i420 and 10-bit = automatic change and manual change of input/output CSP does not work

❌  Can't reproduce it.

> in the QSVenc profile by default there is a forced auto-selection of CQP Value, with terrible levels

I've changed some default values, but those are still up the the user to be adjusted to their needs.

> in the NVenc profile these levels are wonderful, but the forced auto-selection of NVenc 264/265 by default selects ineffective modes = preset P4-Default and profile Main = need to be changed to the preset (264/265)Default and profile (264)High+(265)Main

❓  I don't understand:  Why should they be changed? There is no technical reason to do so. If you want another values, save a preset and you're good to go.

> QSVenc need to change the CQP Value to QP1-I 18 / QP2-P 18 / QP3-B 18 < Constant QP
QSVenc need to change the CQP Value to QP1-I 18 / QP2-P 18 / QP3-B 18 < ICQ

❌  There are no encoder-wise defaults (speaking of the docs). In terms of quality there is no "suggested" setting, because it varies on the input file and the other settings. So if you don't like the values, create your own preset or overwrite the existing one.

**Comment by Andrasolin** [comment]
oh. ok. 

when profiles other than the base ones are needed. I will use another software

**Comment by Dendraspis** [comment]
> when profiles other than the base ones are needed. I will use another software

After reading this sentence I highly recommend you to switch to an One-Click-Encoder or anything else, should be the best solution for all parties. 🫤
