### ISSUE TITLE
SMDegrain & MDegrain Denoise Filter

### ISSUE THREAD

**Issue by phanluchoacom** [staxrip/staxrip#1149]
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).

Hello,

I have used your Staxrip soft and I try to denoise my video using 1 of this tool (SMDegrain or MDegrain). I choose MDegrain for test it but can I ask how can I know that filter apply to denoise my video ? Because I cannot see it on the command to encode when encode.

Thanks!

**Comment by madey83** [comment]
you can find it inside **staxrip.log** from temp folder created based on movie name...
