### ISSUE TITLE
X265 Encoding with three passes not working

### ISSUE THREAD

**Issue by VEGAX265** [staxrip/staxrip#115]
I have not been able to use Staxrip to encode three pass for many versions.
The program runs all three passes but the hevc file is output on pass two.

![pass1](https://user-images.githubusercontent.com/44779244/75076931-5b99f000-54cf-11ea-8de6-e77e8353469f.jpg)

![pass2](https://user-images.githubusercontent.com/44779244/75076944-618fd100-54cf-11ea-9220-f844acfb69e4.jpg)

![pass3](https://user-images.githubusercontent.com/44779244/75076952-65235800-54cf-11ea-873a-afab94db38a1.jpg)

[NVECapture_X265_VEGA_staxrip.log](https://github.com/staxrip/staxrip/files/4238306/NVECapture_X265_VEGA_staxrip.log)

two pass works just fine, I m not sure what I am doing wrong to make it not output the hevc file on the third pass.

**Comment by Patman86** [comment]
Hi VEGA,

your screenshots and your log file show that the second pass has already saved and the third no longer. Look at the output file under x265 info in all three passes. I think it's a bug of Staxrip.

**Comment by VEGAX265** [comment]
Thanks I wasn't sure if its a bug in Staxrip or avspipemod64 or x265.  I can use the command prompt and copy the lines that staxrip generates and swap the output files from pass 2 to pass 3 and it works just fine.

I can easily put the code generated in a batch with pass 2 and 3 reversed and it works just fine as well.

I think its just a bug that is calling the wrong pass to be ran second.

![pass2](https://user-images.githubusercontent.com/44779244/75187388-f38a1a80-5717-11ea-8bff-fcb49f4a34bf.jpg)

![pass3](https://user-images.githubusercontent.com/44779244/75187396-f84ece80-5717-11ea-8e59-0bc27aad36d3.jpg)

**Comment by stax76** [comment]
Does it work with the last build?

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS

**Comment by VEGAX265** [comment]
StaxRip-x64-2.0.7.3 is working great for 3 pass now.
It works as a clean install as well as overwriting the older 2.0.6.0 files.
Let me know if you want me to test against the other betas in that folder.

Thank you
