### ISSUE TITLE
Variable framerate MP4

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1151]
What can I do with a vfr MP4?

With MKV Staxrip can extract timestamps but with that container?

In my lazy mind I would convert it to mkv then process.

Isn't there a more direct way?

**Comment by Dendraspis** [comment]
I'm not into MP4 that much, but it all depends how VFR video files *work* inside the MP4 container, maybe it is not necessary to extract anything. I would just give it a try with very low encoding settings `(CRF40/VeryFast)` and see what happens, maybe play a bit with the settings, but conversion to CFR should be fine.

**Comment by tormento** [comment]
I remember.

You could add support for [mp4fpsmod](https://github.com/nu774/mp4fpsmod), where

`-p, --print <file>    Output current timecodes into timecode-v2 format.`
