### ISSUE TITLE
Subtitles from mkv drop off

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1152]
![image](https://github.com/staxrip/staxrip/assets/34553588/f651e5a3-fbeb-4d66-babb-8d6dbcf07c10)

StaxRip drop off other subtitles than eng...

or can't properly recognizes subtitles like below:

![image](https://github.com/staxrip/staxrip/assets/34553588/282b2694-1574-4f66-9368-5f36680bbd27)

**Comment by Dendraspis** [comment]
Duplicate:  #1120

Hope I can fix it soon...
