### ISSUE TITLE
nvenc av1 cqp, qp i, qp p, qp b values capped 0-51 instead 0-255

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#1153]
**Describe the bug**
On staxrip nvenc av1 encoder cqp, qp i, qp p, qp b  values all capped to 0-51 but unlike h264/h265 av1 takes value 0-255, because cqp capped encoding cqp 51 make big files.

**Expected behavior**
Allow av1 cqp, qp i, qp p, qp b values between 0-255

**Provide information**

https://github.com/rigaya/NVEnc/issues/511#issuecomment-1646346347

**Comment by Andrasolin** [comment]
color range: Limited - default

![изображение](https://github.com/staxrip/staxrip/assets/150133906/4f832d20-1021-4525-8123-48d2692a4474)

**Comment by Dendraspis** [comment]
Where do you have the information from? There is no document/data that confirmes that..

**Comment by darkcity87** [comment]
There is no document but you can see link from first comment nvenc developer mention av1 qp range 0-255 also when encoding vbr mode  qp range shown on encoding screen.
i update nvenc manually to 7.39

![Ekran görüntüsü 2023-12-07 045416](https://github.com/staxrip/staxrip/assets/12258051/112097ee-5b59-48de-9188-bfab3b18b6ce)

**Comment by Andrasolin** [comment]
![изображение](https://github.com/staxrip/staxrip/assets/150133906/d171e28c-9d12-4dd9-a66e-0358e957e3a0)

weird situation. The problem seems to be in your "driver" - I'm using Nvidia SD 546.01

**Comment by darkcity87** [comment]
i am talking about av1 not h265 or h264

**Comment by Andrasolin** [comment]
![изображение](https://github.com/staxrip/staxrip/assets/150133906/b521fbf6-7937-4f86-886a-2425b5539b0f)
