### ISSUE TITLE
Two/Three-pass gives failure generating stream header in x265

### ISSUE THREAD

**Issue by DKB0512** [staxrip/staxrip#1155]
Hello there,

So I want to ask that whenever I try to encode a BD Remux file using two/three-pass, I am getting the error : "failure generating stream header in x265" but it works fine during the normal single-pass quality mode.

When I use the same two/three-pass script for normal Web-DL episodes, it works fine.

More specifically, I am getting something like this only during the two/three-pass preset : 
![image](https://github.com/staxrip/staxrip/assets/23116307/c094c405-5d42-4712-bf87-32fb3a9b2ff9)

**Comment by Dendraspis** [comment]
Without the log file or at least the whole command line, it's just guessing. In general 2pass works normally, can't reproduce this message.

Nevertheless try enabling `--repeat-headers`, that should fix your problem.
