### ISSUE TITLE
NVencC

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1157]
Hello! Is this new profile working properly? I'll probably go back to version 2.29.0, this version requires fewer clicks

![Nvenc](https://github.com/staxrip/staxrip/assets/150133906/3c14e95b-ef8b-4335-a3b3-9e0330438c0e)

**Comment by Dendraspis** [comment]
Yes, looks as intended.

> I'll probably go back to version 2.29.0, this version requires fewer clicks

If you don't like the default settings, simply edit or clone the profile?! Don't understand the problem. 😕
