### ISSUE TITLE
Can't open Lagarith or Huffyuv or H264 source

### ISSUE THREAD

**Issue by Gomam0n-afk** [staxrip/staxrip#116]
Sources recorded with AmarecTV
LOG : (from H264 attempt)

EDIT : i found out using uncompressed audio made everything work , i used to use MP3 compression on the source and that made it impossible for staxrip to decode it , i guess you can close this issue now.

-------------------------- System Environment --------------------------

StaxRip    : 2.0.6.0
Windows    : Windows 10 Enterprise LTSC 2019 1809
Language   : French (France)
CPU        : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
GPU        : NVIDIA GeForce GTX 1060 6GB
Resolution : 1920 x 1080
DPI        : 96

------------------------ MediaInfo Source File ------------------------

C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi

General
Complete name        : C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi
Format               : AVI
Format/Info          : Audio Video Interleave
File size            : 12.6 MiB
Duration             : 2 s 560 ms
Overall bit rate     : 41.4 Mb/s

Video
ID                   : 0
Format               : AVC
Format/Info          : Advanced Video Codec
Codec ID             : H264
Duration             : 2 s 560 ms
Bit rate             : 39.4 Mb/s
Width                : 720 pixels
Height               : 576 pixels
Display aspect ratio : 5:4
Frame rate           : 25.000 FPS
Standard             : PAL
Color space          : YUV
Chroma subsampling   : 4:2:0
Bits/(Pixel*Frame)   : 3.799
Stream size          : 12.0 MiB (95%)

Audio
ID                   : 1
Format               : MPEG Audio
Codec ID             : 55
Codec ID/Hint        : MP3
Duration             : 2 s 544 ms
Bit rate             : 320 kb/s
Channel(s)           : 2 channels
Sampling rate        : 48.0 kHz
Compression mode     : Lossy
Stream size          : 99.4 KiB (1%)
Alignment            : Aligned on interleaves

----------- Error Demux audio using ffmpeg 2019-09-27 Patman -----------

Demux audio using ffmpeg 2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

-------------- Demux audio using ffmpeg 2019-09-27 Patman --------------

C:\Users\Gomam0n\Documents\StaxRIP\Apps\Encoders\ffmpeg\ffmpeg.exe -i "C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1"

[avi @ 000001d1f4887840] non-interleaved AVI
Input #0, avi, from 'C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi':
Duration: 00:00:02.56, start: 0.000000, bitrate: 41350 kb/s
Stream #0:0: Video: h264 (High 4:4:4 Predictive) (H264 / 0x34363248), yuv422p(progressive), 720x576 [SAR 1:1 DAR 5:4], 41619 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 320 kb/s
[NULL @ 000001d1f496e4c0] Unable to find a suitable output format for 'C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1'
C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1: Invalid argument

-------------- Demux audio using ffmpeg 2019-09-27 Patman --------------

C:\Users\Gomam0n\Documents\StaxRIP\Apps\Encoders\ffmpeg\ffmpeg.exe -i "C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1"

[avi @ 000001d1f4887840] non-interleaved AVI
Input #0, avi, from 'C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi':
Duration: 00:00:02.56, start: 0.000000, bitrate: 41350 kb/s
Stream #0:0: Video: h264 (High 4:4:4 Predictive) (H264 / 0x34363248), yuv422p(progressive), 720x576 [SAR 1:1 DAR 5:4], 41619 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 320 kb/s
[NULL @ 000001d1f496e4c0] Unable to find a suitable output format for 'C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1'
C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1: Invalid argument

Start:    17:42:23
End:      17:42:24
Duration: 00:00:00

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: Demux audio using ffmpeg 2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

-------------- Demux audio using ffmpeg 2019-09-27 Patman --------------

C:\Users\Gomam0n\Documents\StaxRIP\Apps\Encoders\ffmpeg\ffmpeg.exe -i "C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1"

[avi @ 000001d1f4887840] non-interleaved AVI
Input #0, avi, from 'C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740).avi':
Duration: 00:00:02.56, start: 0.000000, bitrate: 41350 kb/s
Stream #0:0: Video: h264 (High 4:4:4 Predictive) (H264 / 0x34363248), yuv422p(progressive), 720x576 [SAR 1:1 DAR 5:4], 41619 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 320 kb/s
[NULL @ 000001d1f496e4c0] Unable to find a suitable output format for 'C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1'
C:\Users\Gomam0n\Desktop\amarectv310\amarec(20200223-1740)_temp\amarec(20200223-1740) ID1: Invalid argument

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 340
   at StaxRip.ffmpegDemuxer.DemuxAudio(String sourcefile, AudioStream stream, AudioProfile ap, Project proj) in D:\Projekte\VB\staxrip\General\Demux.vb:line 361
   at StaxRip.ffmpegDemuxer.Run(Project proj) in D:\Projekte\VB\staxrip\General\Demux.vb:line 311
   at StaxRip.MainForm.Demux() in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 3113
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 1967

I used to be able to encode from Lagarith sources i have no idea why it's not working anymore ...

**Comment by stax76** [comment]
Thanks for the bug report. Please upload one or more sample files. I don't know if AVI supports 
H264, probably not.

**Comment by Revan654** [comment]
When I forked the Original project, I removed Lagarith or Huffyuv completely since it's a dated format/codec and no longer in development. The Last update was over 10 years ago. Not sure if it was added back in or not.

AVI doesn't really support it, I know most hardware doesn't.
