### ISSUE TITLE
ffmpeg can't read vpy file

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#1160]
i use last staxrip 2.30

---------------------- Error Video encoding x265 ----------------------

Video encoding x265 returned exit code: -22 (0xFFFFFFEA)

------------------------- Video encoding x265 -------------------------

ffmpeg N-112998-g1f56bfc986-20231216

C:\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -f vapoursynth -i C:\Endoding\Lossless.vpy -c:v libx265 -an -y -hide_banner C:\Endoding\Lossless_out.h265

[in#0 @ 000001952abceb40] Unknown input format: 'vapoursynth'
Error opening input file C:\Endoding\Lossless.vpy.
Error opening input files: Invalid argument

error ffmpeg encoding

**Comment by Dendraspis** [comment]
This issue should be solved with the next release coming out next week.

If not, please re-open this issue and I try to look at it asap.
