### ISSUE TITLE
Frames To Be Encoded in vvencFFapp dont work

### ISSUE THREAD

**Issue by amirhamdidz** [staxrip/staxrip#1161]
"Frames To Be Encoded" in "vvencFFapp" dont work
![FTBE](https://github.com/staxrip/staxrip/assets/154467169/67ad45a8-35f4-44f0-9c04-fdf72b6a2f3a)

**Comment by Dendraspis** [comment]
This is not a bug in the first place. The value is calculated properly when a source file is loaded.
