### ISSUE TITLE
New qvbr mode missing multi pass options

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#1162]
**Describe the bug**
1.New qvbr mode missing multi pass options
2.In ui new qvbr mode ''quality value'' named ''QP'' i think ''qp'' specific to cqp mode

**Expected behavior**
1. like vbr mode there should be multi pass options
2. instead ''QP'' it should be ''vbr quality'' or ''target quality''.
in vbr mode named ''VBR Quality''

**Provide information**
From Nvencc help document:
1.
   --multipass <string>         multipass mode for VBR, CBR mode
                                  none, 2pass-quarter, 2pass-full

2.
   --qvbr <float>               set bitrate for QVBR mode (kbps)
                                  same as "--vbr 0 --vbr-quality <float>"

   --vbr-quality <float>        target quality for VBR mode (0-51, 0=auto)

vbr mode:
![vbr](https://github.com/staxrip/staxrip/assets/12258051/2f7a0a84-31b9-4178-aa36-7abfaab7403c)

new qvbr mode:
![qvbr no multipass](https://github.com/staxrip/staxrip/assets/12258051/caaa5a99-3689-464f-a62e-2d51501e7cd5)
![qvbr qp](https://github.com/staxrip/staxrip/assets/12258051/88324249-ea49-4328-b6d9-85032359eb7c)

**Comment by Dendraspis** [comment]
1. This has to be clarified by rigaya first as that could be a documentation issue. So we have to wait...
2. Yeah, I think I can (and will) rename it.  😁

**Comment by Dendraspis** [comment]
Confirmed, fixed, closed. 😁
