### ISSUE TITLE
NVEncC Mode:QVRB - QP setting disappears..

### ISSUE THREAD

**Issue by SergePD** [staxrip/staxrip#1163]
**Describe the bug**
In NVEncC setting when you chose Mode:QVRB - QP setting is a dropdown box. If you change Mode to CQP: Constant QP and select "Show advanced QP settings" you have 3 dropdown boxes (QP I,P and B). If you change mod back to QVBR that three dropdown boxes stay and you cannot control qvbr parameter any more, QP dropbox is missing.

**Expected behavior**
You have to have a way to control qvbr value after chanding Mode from CQP to QVBR.

**How to reproduce the issue**

1. Go to 'NVEncC (Nvidia - H.265'
2. Click on 'Encoder Options' "Basic"
3. Mode "QVBR" --> "CQP" --> **mark** "Show advanced QP settings"
4. Mode "QVBR"
Now no more QP dropbox, only QP I, P and B

**Provide information**

- Used StaxRip version
- v2.30

**Comment by Dendraspis** [comment]
Thanks for the report. I have fixed it, so everything should work as intended in the next release.
