### ISSUE TITLE
Error Audio Encoding 1 (v2.30.0)  Audio Encoding 1 returned exit code: 2 (0x2)

### ISSUE THREAD

**Issue by rahatbracu** [staxrip/staxrip#1166]
Error Audio Encoding 1 (v2.30.0)

Audio Encoding 1 returned exit code: 2 (0x2)

-------------------------- Audio Encoding 1 --------------------------

qaac 2.80

C:\Users\rahat\Downloads\Compressed\StaxRip-v2.30.0-x64\StaxRip-v2.30.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 "C:\Users\rahat\Downloads\manga\Adventure.Time.Distant.Lands.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM\Adventure.Time.Distant.Lands.S01E01.BMO.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM_temp\ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.flac" -o "\\?\C:\Users\rahat\Downloads\manga\Adventure.Time.Distant.Lands.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM\Adventure.Time.Distant.Lands.S01E01.BMO.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM_temp\ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.m4a"

qaac 2.80, CoreAudioToolbox 7.10.9.0
ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.m4a
AAC-LC Encoder, TVBR q54, Quality 96
ERROR: \\?\UNC\?\C:\Users\rahat\Downloads\manga\Adventure.Time.Distant.Lands.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM\Adventure.Time.Distant.Lands.S01E01.BMO.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM_temp\ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.m4a: The network path was not found.

StaxRip.ErrorAbortException: Audio Encoding 1 returned exit code: 2 (0x2)

-------------------------- Audio Encoding 1 --------------------------

qaac 2.80

C:\Users\rahat\Downloads\Compressed\StaxRip-v2.30.0-x64\StaxRip-v2.30.0-x64\Apps\Audio\qaac\qaac64.exe --tvbr 50 "C:\Users\rahat\Downloads\manga\Adventure.Time.Distant.Lands.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM\Adventure.Time.Distant.Lands.S01E01.BMO.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM_temp\ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.flac" -o "\\?\C:\Users\rahat\Downloads\manga\Adventure.Time.Distant.Lands.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM\Adventure.Time.Distant.Lands.S01E01.BMO.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM_temp\ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.m4a"

qaac 2.80, CoreAudioToolbox 7.10.9.0
ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.m4a
AAC-LC Encoder, TVBR q54, Quality 96
ERROR: \\?\UNC\?\C:\Users\rahat\Downloads\manga\Adventure.Time.Distant.Lands.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM\Adventure.Time.Distant.Lands.S01E01.BMO.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-BLURANiUM_temp\ID1 English {DTS-HD Master Audio __2F__ 5.1 __2F__ 48}_4199819156.m4a: The network path was not found.

   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 353
   at StaxRip.GUIAudioProfile.Encode() in D:\Code\Github\staxrip\staxrip\Source\General\AudioProfile.vb:line 862
   at StaxRip.GlobalClass._Closure$__._Lambda$__120-4() in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 336
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 379

**Comment by Dendraspis** [comment]
I'm going to change that for the next release as qaac seems to not like the mixed UNC network path names.
Quick resolution for you:  Shorten the file name and maybe the folder name too to get a shorter file path with less than 260 characters.
