### ISSUE TITLE
SvtAv1EncApp v1.8 crashes with slower than default presets with default options --enable-restoration 1 and --enable-tf 1

### ISSUE THREAD

**Issue by AlisaFmla** [staxrip/staxrip#1173]
SvtAv1EncApp version 1.8 in slow presets with default options: --enable-restoration 1, --enable-tf 1, does not work!
Please check and if so, fix it.

**Comment by kuzon3** [comment]
It works but only with default options. Any custom setting will break the encoder. Quick fix is downgrade the encoder or download the official 1.8.0 svt-av1 encoder from gitlab.

**Comment by AlisaFmla** [comment]
Yes, it's a now small, but still issue, isn't it?

**Comment by Dendraspis** [comment]
> Quick fix is downgrade the encoder or download the official 1.8.0 svt-av1 encoder from gitlab.

@kuzon3 I assume you have tested and verified that?

**Comment by kuzon3** [comment]
Yes at the moment I'm using the official build from gitlab

**Comment by AlisaFmla** [comment]
> What means "does not work"? What happens? Do you get an error message? Which one?

Starting with preset 9 (Very fast) and slower, the encoder throws the most confusing exception and that's it:
Error Video encoding ------------------------

Video encoding returned exit code: -1073741795 (0xC000001D)

**Comment by Dendraspis** [comment]
This seems to happen to all presets slower than the default one (10).
I'll take care of it for the next release...

**Comment by Dendraspis** [comment]
> Starting with preset 9 (Very fast) and slower, the encoder throws the most confusing exception and that's it: Error Video encoding ------------------------
> 
> Video encoding returned exit code: -1073741795 (0xC000001D)

That means that the tool is crashing/stopping without an error message or so, we just get an exit code.

> download the official 1.8.0 svt-av1 encoder from gitlab.

As far as I know there is no official `SvtAv1EncApp` binary available. Do you have build one on your own?

**Comment by AlisaFmla** [comment]
Yes, no official SvtAv1EncApp binary available, and build it is the problem for most people.

**Comment by Dendraspis** [comment]
I agree with that, even don't understand why they do not provide official binaries.  😕 
So we are investigating that, I let you know when we have found the culprit....

**Comment by Dendraspis** [comment]
Okay guys, it seems to be a Microsoft issue...

Please head over to [Patman86's SvtAv1EncApp Mod](https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases/tag/v1.8.0-1%2B3) and download the ***GCC*** version, extract it and replace  `.\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe` with this one, then you're fine.

The next release will have the *GCC* version included....

**Comment by AlisaFmla** [comment]
And other new tools compiled by msvc don't seem to work either! I checked AOMEnc v3.8.0-178-ge065e0fead-x64-msvc 1938 with default options, it also gives an error: exit code: -1073741795

**Comment by Dendraspis** [comment]
Thanks for the information, appreciate it.
So I guess the next release is coming soon..  🙄

**Comment by kuzon3** [comment]
> > Starting with preset 9 (Very fast) and slower, the encoder throws the most confusing exception and that's it: Error Video encoding ------------------------
> 
> > 
> 
> > Video encoding returned exit code: -1073741795 (0xC000001D)
> 
> 
> 
> That means that the tool is crashing/stopping without an error message or so, we just get an exit code.
> 
> 
> 
> > download the official 1.8.0 svt-av1 encoder from gitlab.
> 
> 
> 
> As far as I know there is no official `SvtAv1EncApp` binary available. Do you have build one on your own? 

Sorry for the late reply to find the build you need to go to the artifacts page and find Win64(MSVC, Test): [Release] inside the zip you'll need to copy SvtAv1Enc.dll and .exe to the SvtAv1EncApp folder in staxrip

**Comment by Dendraspis** [comment]
Yeah, thanks, it looks like Microsoft has to deal with a bug that makes several builds unusable. 

For the moment you can use the one you've mentioned or the `GCC` version provided by Patman86. The next release will hopefully have working builds only.
