### ISSUE TITLE
Need help solving the error

### ISSUE THREAD

**Issue by rohitghali** [staxrip/staxrip#1178]
Here's the error log:

   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 353
   at StaxRip.SvtAv1Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Code\Github\staxrip\staxrip\Source\Encoding\SvtAv1Enc.vb:line 74
   at StaxRip.SvtAv1Enc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\SvtAv1Enc.vb:line 40
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 379

**Comment by Dendraspis** [comment]
Sorry, but that's as helpful as saying *"I have a problem"* without any further information.

And that's just the bottom part of the error message, above is more. Providing the whole log file would be helpful. Additionally:
Source file?
Filters?
Encoder settings?
When does it appear?
How to reproduce?

**Comment by rohitghali** [comment]
> Sorry, but that's as helpful as saying _"I have a problem"_ without any further information.
> 
> And that's just the bottom part of the error message, above is more. Providing the whole log file would be helpful. Additionally: Source file? Filters? Encoder settings? When does it appear? How to reproduce?

Sorry. My bad. Here's the full log:

`
------------------------- System Environment -------------------------

StaxRip    : v2.31.0
Windows    : Windows 10 Home 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : English (United States)
CPU        : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
RAM        : 20GB
GPU        : Intel(R) UHD Graphics 620, NVIDIA GeForce MX150, DisplayLink USB Device, DisplayLink USB Device
Resolution : 1920 x 1080
DPI        : 96
Code Page  : 1252

----------------------- Media Info Source File -----------------------

C:\Users\user\Desktop\mkvgui\filename.mkv

General
Complete name             : C:\Users\user\Desktop\mkvgui\filename.mkv
Format                    : Matroska
Format version            : Version 4
File size                 : 5.40 GiB
Duration                  : 2 h 14 min
Overall bit rate mode     : Variable
Overall bit rate          : 5 735 kb/s
Frame rate                : 24.000 FPS
Movie name                : filename
Encoded date              : 2024-01-05 18:15:55 UTC
Writing application       : mkvmerge v81.0 ('Milliontown') 64-bit
Writing library           : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : Main@L4
Format settings           : CABAC / 3 Ref Frames
Format, CABAC             : Yes
Format, Reference frames  : 3 frames
Codec ID                  : V_MPEG4/ISO/AVC
Duration                  : 2 h 14 min
Bit rate mode             : Variable
Bit rate                  : 5 000 kb/s
Maximum bit rate          : 7 500 kb/s
Width                     : 1 920 pixels
Height                    : 1 080 pixels
Display aspect ratio      : 16:9
Frame rate mode           : Constant
Frame rate                : 24.000 FPS
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.100
Stream size               : 4.68 GiB (87%)
Writing library           : x264 core 148 r2727 7d026e8
Default                   : Yes
Forced                    : No

Audio
ID                        : 2
Format                    : E-AC-3 JOC
Format/Info               : Enhanced AC-3 with Joint Object Coding
Commercial name           : Dolby Digital Plus with Dolby Atmos
Codec ID                  : A_EAC3
Duration                  : 2 h 14 min
Bit rate mode             : Constant
Bit rate                  : 768 kb/s
Channel(s)                : 6 channels
Channel layout            : L R C LFE Ls Rs
Sampling rate             : 48.0 kHz
Frame rate                : 31.250 FPS (1536 SPF)
Compression mode          : Lossy
Stream size               : 741 MiB (13%)
Language                  : Lang1
Service kind              : Complete Main
Default                   : No
Forced                    : No
Complexity index          : 16
Number of dynamic objects : 15
Bed channel count         : 1 channel
Bed channel configuration : LFE

Text #1
ID                        : 3
Format                    : UTF-8
Codec ID                  : S_TEXT/UTF8
Codec ID/Info             : UTF-8 Plain Text
Duration                  : 2 h 8 min
Bit rate                  : 62 b/s
Frame rate                : 0.228 FPS
Count of elements         : 1756
Stream size               : 59.3 KiB (0%)
Language                  : English
Default                   : No
Forced                    : No

Text #2
ID                        : 4
Format                    : UTF-8
Codec ID                  : S_TEXT/UTF8
Codec ID/Info             : UTF-8 Plain Text
Duration                  : 2 h 8 min
Bit rate                  : 83 b/s
Frame rate                : 0.284 FPS
Count of elements         : 2201
Stream size               : 78.5 KiB (0%)
Language                  : English
Default                   : No
Forced                    : No

Menu
00                        : 00:00.000                             : en:Part 01
02                        : 10:03.450                             : en:Credits

------------------------------ Demux MKV ------------------------------

mkvextract 81.0

C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Support\MKVToolNix\mkvextract.exe --ui-language en "C:\Users\user\Desktop\mkvgui\filename.mkv" tracks 2:"C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1_en.srt" 3:"C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID2_en.srt" 1:"C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi].eac3"

Extracting track 1 with the CodecID 'A_EAC3' to the file 'C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi].eac3'. Container format: Dolby Digital Plus (E-AC-3)
Extracting track 2 with the CodecID 'S_TEXT/UTF8' to the file 'C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1_en.srt'. Container format: SRT text subtitles
Extracting track 3 with the CodecID 'S_TEXT/UTF8' to the file 'C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID2_en.srt'. Container format: SRT text subtitles

Start:    1:33:45 PM
End:      1:33:52 PM
Duration: 00:00:06

General
Complete name             : C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi].eac3
Format                    : E-AC-3 JOC
Format/Info               : Enhanced AC-3 with Joint Object Coding
Commercial name           : Dolby Digital Plus with Dolby Atmos
File size                 : 741 MiB
Duration                  : 2 h 14 min
Overall bit rate mode     : Constant
Overall bit rate          : 768 kb/s

Audio
Format                    : E-AC-3 JOC
Format/Info               : Enhanced AC-3 with Joint Object Coding
Commercial name           : Dolby Digital Plus with Dolby Atmos
Duration                  : 2 h 14 min
Bit rate mode             : Constant
Bit rate                  : 768 kb/s
Channel(s)                : 6 channels
Channel layout            : L R C LFE Ls Rs
Sampling rate             : 48.0 kHz
Frame rate                : 31.250 FPS (1536 SPF)
Compression mode          : Lossy
Stream size               : 741 MiB (100%)
Service kind              : Complete Main
Complexity index          : 16
Number of dynamic objects : 15
Bed channel count         : 1 channel
Bed channel configuration : LFE

------------------------- Demux xml chapters -------------------------

mkvextract 81.0

C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Support\MKVToolNix\mkvextract.exe "C:\Users\user\Desktop\mkvgui\filename.mkv" --ui-language en chapters "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\filename_chapters.xml"

File 'C:\Users\user\Desktop\mkvgui\filename.mkv': container: Matroska
Track ID 0: video (AVC/H.264/MPEG-4p10)
Track ID 1: audio (E-AC-3)
Track ID 2: subtitles (SubRip/SRT)
Track ID 3: subtitles (SubRip/SRT)
Chapters: 2 entries

Start:    1:33:52 PM
End:      1:33:52 PM
Duration: 00:00:00

------------------------- Demux ogg chapters -------------------------

mkvextract 81.0

C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Support\MKVToolNix\mkvextract.exe "C:\Users\user\Desktop\mkvgui\filename.mkv" --ui-language en chapters "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\filename_chapters.txt" --simple

File 'C:\Users\user\Desktop\mkvgui\filename.mkv': container: Matroska
Track ID 0: video (AVC/H.264/MPEG-4p10)
Track ID 1: audio (E-AC-3)
Track ID 2: subtitles (SubRip/SRT)
Track ID 3: subtitles (SubRip/SRT)
Chapters: 2 entries

Start:    1:33:52 PM
End:      1:33:52 PM
Duration: 00:00:00

---------------------- Indexing using ffmsindex ----------------------

C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Plugins\Dual\ffms2\ffmsindex.exe "C:\Users\user\Desktop\mkvgui\filename.mkv" "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\temp.ffindex"

Writing index... done.

Start:    1:33:53 PM
End:      1:33:58 PM
Duration: 00:00:05

---------------------------- Configuration ----------------------------

Template                : av1 stream quality
Video Encoder           : SvtAv1Enc
Video Encoder Profile   : AV1 | SvtAv1EncApp
Container/Muxer Profile : MKV (mkvmerge)

----------------------- Media Info Source File -----------------------

C:\Users\user\Desktop\mkvgui\filename.mkv

General
Complete name             : C:\Users\user\Desktop\mkvgui\filename.mkv
Format                    : Matroska
Format version            : Version 4
File size                 : 5.40 GiB
Duration                  : 2 h 14 min
Overall bit rate mode     : Variable
Overall bit rate          : 5 735 kb/s
Frame rate                : 24.000 FPS
Movie name                : filename
Encoded date              : 2024-01-05 18:15:55 UTC
Writing application       : mkvmerge v81.0 ('Milliontown') 64-bit
Writing library           : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : Main@L4
Format settings           : CABAC / 3 Ref Frames
Format, CABAC             : Yes
Format, Reference frames  : 3 frames
Codec ID                  : V_MPEG4/ISO/AVC
Duration                  : 2 h 14 min
Bit rate mode             : Variable
Bit rate                  : 5 000 kb/s
Maximum bit rate          : 7 500 kb/s
Width                     : 1 920 pixels
Height                    : 1 080 pixels
Display aspect ratio      : 16:9
Frame rate mode           : Constant
Frame rate                : 24.000 FPS
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.100
Stream size               : 4.68 GiB (87%)
Writing library           : x264 core 148 r2727 7d026e8
Default                   : Yes
Forced                    : No

Audio
ID                        : 2
Format                    : E-AC-3 JOC
Format/Info               : Enhanced AC-3 with Joint Object Coding
Commercial name           : Dolby Digital Plus with Dolby Atmos
Codec ID                  : A_EAC3
Duration                  : 2 h 14 min
Bit rate mode             : Constant
Bit rate                  : 768 kb/s
Channel(s)                : 6 channels
Channel layout            : L R C LFE Ls Rs
Sampling rate             : 48.0 kHz
Frame rate                : 31.250 FPS (1536 SPF)
Compression mode          : Lossy
Stream size               : 741 MiB (13%)
Language                  : Hindi
Service kind              : Complete Main
Default                   : No
Forced                    : No
Complexity index          : 16
Number of dynamic objects : 15
Bed channel count         : 1 channel
Bed channel configuration : LFE

Text #1
ID                        : 3
Format                    : UTF-8
Codec ID                  : S_TEXT/UTF8
Codec ID/Info             : UTF-8 Plain Text
Duration                  : 2 h 8 min
Bit rate                  : 62 b/s
Frame rate                : 0.228 FPS
Count of elements         : 1756
Stream size               : 59.3 KiB (0%)
Language                  : English
Default                   : No
Forced                    : No

Text #2
ID                        : 4
Format                    : UTF-8
Codec ID                  : S_TEXT/UTF8
Codec ID/Info             : UTF-8 Plain Text
Duration                  : 2 h 8 min
Bit rate                  : 83 b/s
Frame rate                : 0.284 FPS
Count of elements         : 2201
Stream size               : 78.5 KiB (0%)
Language                  : English
Default                   : No
Forced                    : No

Menu
00                        : 00:00.000                             : en:Part 01
02                        : 10:03.450                             : en:Credits

--------------------------- AviSynth Script ---------------------------

AddAutoloadDir("C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\plugins")

LoadPlugin("C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Plugins\Dual\ffms2\ffms2.dll")
tcFile = "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\filename_timestamps.txt" # timestamps file path
Exist(tcFile) ? FFVideoSource("C:\Users\user\Desktop\mkvgui\filename.mkv", cachefile="C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("C:\Users\user\Desktop\mkvgui\filename.mkv", cachefile="C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\temp.ffindex")

------------------------- Source Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 194289
Time      : 02:14:55.375
Framerate : 24 (24/1)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 194289
Time      : 02:14:55.375
Framerate : 24 (24/1)
Format    : YUV420P8

---------------------- Media Info Audio Source 1 ----------------------

General
Complete name             : C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi].eac3
Format                    : E-AC-3 JOC
Format/Info               : Enhanced AC-3 with Joint Object Coding
Commercial name           : Dolby Digital Plus with Dolby Atmos
File size                 : 741 MiB
Duration                  : 2 h 14 min
Overall bit rate mode     : Constant
Overall bit rate          : 768 kb/s

Audio
Format                    : E-AC-3 JOC
Format/Info               : Enhanced AC-3 with Joint Object Coding
Commercial name           : Dolby Digital Plus with Dolby Atmos
Duration                  : 2 h 14 min
Bit rate mode             : Constant
Bit rate                  : 768 kb/s
Channel(s)                : 6 channels
Channel layout            : L R C LFE Ls Rs
Sampling rate             : 48.0 kHz
Frame rate                : 31.250 FPS (1536 SPF)
Compression mode          : Lossy
Stream size               : 741 MiB (100%)
Service kind              : Complete Main
Complexity index          : 16
Number of dynamic objects : 15
Bed channel count         : 1 channel
Bed channel configuration : LFE

------------------------ Error Video encoding ------------------------

Video encoding returned exit code: -1073741795 (0xC000001D)


--------------------------- Video encoding ---------------------------

SvtAv1EncApp 1.8.0-1+3-43997134-[Mod-by-Patman]-x64-msvc1938

C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll -y4mp "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\filename.avs" | C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --input - --width 1920 --height 1080 --output "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\filename_out.ivf" --frames 194289 --rc 0 --progress 2 --preset 8 --level 4.0 --aq-mode 1 --scd 1 --enable-overlays 1 --tune 0 --film-grain 5 --film-grain-denoise 0 --superres-mode 0

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.8.0-1+3-43997134 [Mod by Patman]
Svt[info]: SVT [build]  :	Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Dec 27 2023 17:06:37
Svt[info]: -------------------------------------------
avs2pipemod[info]: writing 194289 frames of 24/1 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
Svt[warn]: Instance 1: The adaptive quantization mode using segmentation is at a support level only to be available for demos, experimentation, and further development uses and should not be used for benchmarking until fully implemented.
Svt[warn]: Instance 1: It is recommended to not use Film Grain for presets greater than 6 as it produces a significant compute overhead. This combination should only be used for debug purposes.
Svt[warn]: SVT-AV1 has an integrated mode decision mechanism to handle scene changes and will not insert a key frame at scene changes
Svt[info]: Number of logical cores available: 8
Svt[info]: Number of PPCS 148
Svt[info]: [asm level on system : up to avx2]
Svt[info]: [asm level selected : up to avx2]
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: main profile	tier (auto)	level 4.0
Svt[info]: SVT [config]: width / height / fps numerator / fps denominator 		: 1920 / 1080 / 24 / 1
Svt[info]: SVT [config]: bit-depth / color format 					: 8 / YUV420
Svt[info]: SVT [config]: preset / tune / pred struct 					: 8 / VQ / random access
Svt[info]: SVT [config]: gop size / mini-gop size / key-frame type 			: 161 / 32 / key frame
Svt[info]: SVT [config]: BRC mode / rate factor 					: CRF / 35 
Svt[info]: SVT [config]: film grain synth / denoising / level 				: 1 / 0 / 5
Svt[info]: -------------------------------------------
Encoding          avs2pipemod[info]: finished, wrote 108 frames [0%].
avs2pipemod[info]: total elapsed time is 29.284 sec.
avs2pipemod[error]: only wrote 108 of 194289 frames.

--------------------------- Video encoding ---------------------------

SvtAv1EncApp 1.8.0-1+3-43997134-[Mod-by-Patman]-x64-msvc1938

C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll -y4mp "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\filename.avs" | C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --input - --width 1920 --height 1080 --output "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\filename_out.ivf" --frames 194289 --rc 0 --progress 2 --preset 8 --level 4.0 --aq-mode 1 --scd 1 --enable-overlays 1 --tune 0 --film-grain 5 --film-grain-denoise 0 --superres-mode 0

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.8.0-1+3-43997134 [Mod by Patman]
Svt[info]: SVT [build]  :	Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Dec 27 2023 17:06:37
Svt[info]: -------------------------------------------
avs2pipemod[info]: writing 194289 frames of 24/1 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
Svt[warn]: Instance 1: The adaptive quantization mode using segmentation is at a support level only to be available for demos, experimentation, and further development uses and should not be used for benchmarking until fully implemented.
Svt[warn]: Instance 1: It is recommended to not use Film Grain for presets greater than 6 as it produces a significant compute overhead. This combination should only be used for debug purposes.
Svt[warn]: SVT-AV1 has an integrated mode decision mechanism to handle scene changes and will not insert a key frame at scene changes
Svt[info]: Number of logical cores available: 8
Svt[info]: Number of PPCS 148
Svt[info]: [asm level on system : up to avx2]
Svt[info]: [asm level selected : up to avx2]
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: main profile	tier (auto)	level 4.0
Svt[info]: SVT [config]: width / height / fps numerator / fps denominator 		: 1920 / 1080 / 24 / 1
Svt[info]: SVT [config]: bit-depth / color format 					: 8 / YUV420
Svt[info]: SVT [config]: preset / tune / pred struct 					: 8 / VQ / random access
Svt[info]: SVT [config]: gop size / mini-gop size / key-frame type 			: 161 / 32 / key frame
Svt[info]: SVT [config]: BRC mode / rate factor 					: CRF / 35 
Svt[info]: SVT [config]: film grain synth / denoising / level 				: 1 / 0 / 5
Svt[info]: -------------------------------------------
Encoding          avs2pipemod[info]: finished, wrote 108 frames [0%].
avs2pipemod[info]: total elapsed time is 29.284 sec.
avs2pipemod[error]: only wrote 108 of 194289 frames.

Start:    1:41:03 PM
End:      1:41:34 PM
Duration: 00:00:30

----------------------- Convert EAC3 to FLAC 1 -----------------------

ffmpeg N-113112-gf5f414d9c4-x64-gcc13.2.0

C:\CustomPrograms\Encoders\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -i "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi].eac3" -y -hide_banner -ac 6 "C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi]_2061246812.flac"

[eac3 @ 00000189ca399f80] Estimating duration from bitrate, this may be inaccurate
Input #0, eac3, from 'C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi].eac3':
  Duration: 02:14:55.39, start: 0.000000, bitrate: 768 kb/s
  Stream #0:0: Audio: eac3 (Dolby Digital Plus + Dolby Atmos), 48000 Hz, 5.1(side), fltp, 768 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (eac3 (native) -> flac (native))
Press [q] to stop, [?] for help
[flac @ 00000189cbbdbf40] encoding as 24 bits-per-sample, more is considered experimental. Add -strict experimental if you want to encode more than 24 bits-per-sample
Output #0, flac, to 'C:\Users\user\Desktop\mkvgui\Staxrip\temp\filename_temp\ID1 Hindi [hi]_2061246812.flac':
  Metadata:
    encoder         : Lavf60.20.100
    WAVEFORMATEXTENSIBLE_CHANNEL_MASK: 0x3f
  Stream #0:0: Audio: flac, 48000 Hz, 5.1, s32 (24 bit), 128 kb/s
      Metadata:
        encoder         : Lavc60.36.100 flac

Start:    1:41:03 PM
End:      1:41:34 PM
Duration: 00:00:30

`

**Comment by Dendraspis** [comment]
Please head over to [Patman86's SvtAv1EncApp Mod](https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases/tag/v1.8.0-1%2B3) and download the ***GCC*** version, extract it and replace  `.\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe` with this one. 

Direct link:
https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases/download/v1.8.0-1%2B3/SvtAv1EncApp-v1.8.0-1+3-43997134-.Mod-by-Patman.-x64-gcc13.2.0.7z

This could/should solve the issue.

**Comment by rohitghali** [comment]
> Please head over to [Patman86's SvtAv1EncApp Mod](https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases/tag/v1.8.0-1%2B3) and download the _**GCC**_ version, extract it and replace `.\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe` with this one.
> 
> Direct link: https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases/download/v1.8.0-1%2B3/SvtAv1EncApp-v1.8.0-1+3-43997134-.Mod-by-Patman.-x64-gcc13.2.0.7z
> 
> This could/should solve the issue.

Yep. That worked. What was the issue?

**Comment by Dendraspis** [comment]
It was discussed in #1173 , basically Microsoft seems to have a bug in their latest compilers.
