### ISSUE TITLE
No audio streams in Container Options after file demuxing

### ISSUE THREAD

**Issue by Omegaplexx** [staxrip/staxrip#1180]
**Describe the bug**
After importing a file and demuxing its streams, all subtitle tracks, attachments, chapters and other information are automatically substituted into the empty fields of Container Options screen except for audio tracks.

Example: I open a file with 5 audio tracks with StaxRip. After demuxing all streams in temp folder I can see 2 first audios in main screen and empty list in Container Options.
![stax main](https://github.com/staxrip/staxrip/assets/95503207/20bf0c2d-2755-4912-8679-823e34ba9865)
![stax container](https://github.com/staxrip/staxrip/assets/95503207/2daf25bd-6b96-47d2-bdf6-1273683d63d3)
If I manually add all 5 tracks again and start processing, I'll get a video with 2 first and 5 manually added tracks. Is this how it's supposed to work? I don't think so.

**Expected behavior**
I would like Container Options menu to display all audio tracks by default, with the ability to quickly rename them and customize their language (as in the Subtitles tab). The current implementation doesn't save audio track names, which slows down work with streams. I don't see any use for the Audio section on the main screen, because it gets in the way if a video with >2 audio tracks has been imported into the app. Have a list of all audio tracks in Container Options, and have the Audio section duplicate the first two tracks, which will automatically change if I change the order or names of the tracks via the Container menu.

**How to reproduce the issue**
1. Open any source file with StaxRip
2. Go to "Container Options -> Audio"

It will be always empty even with "Demux Audio" option is set to "All" in Project Options (can be found by clicking "Options" button in upper part of main screen). Tested on StaxRip 2.32, 2.29 and older versions. Thank you for reading and sorry for my English mistakes :)

**Comment by Dendraspis** [comment]
Thanks for the detailed report.

To be precise StaxRip does exactly what it is supposed to do. It demuxes the audio tracks, adds the suiting ones to the audio panel at the bottom of the main window and that's it. 
The "problem" is when you want to have more than 2 audio tracks, then you have to add them manually.

I will have a look at how I can improve it....

> The current implementation doesn't save audio track names

Reminder for myself.  😁

**Comment by Omegaplexx** [comment]
> The "problem" is when you want to have more than 2 audio tracks, then you have to add them manually.

Hm, I don't get it then. If I have, for example, a video with 5 audios and 5 subtitle tracks, StaxRip will demux and automatically attach all subs (along with covers, chapters, attachments, etc.) except for audio tracks, because an Audio panel contains only 2 slots? There's no point to cut off already demuxed audios and force user to re-attach them manually just to rename, change order or don't touch at all.

> I will have a look at how I can improve it....

I think that displaying all audio tracks in Container Options and duplicating the first two on the main screen doesn't conflict with behaviour of anything. Users still can use Audio panel as before even if there's more than 2 audios in total. They also can quickly add, delete, rename or reorder audio tracks through Container Options.

Adding to "Project Options" → "Audio" → "Demux Audio" an option "Demux all and attach to project" is basically what I mean.

> The track name is saved in the file name.

Yeah, but only in filename. I'll still have to manually attach and name every audio stream to project because if I open a source file with 5 audios in StaxRip and start processing without any changes, I'll get the file with only 2 audio tracks named "Track 1" and "Track 2" in video player, so track names don't save after remuxing.

Thank you for your answer and interest! 😄

**Comment by Dendraspis** [comment]
Yeah, that's basically the idea/reason. StaxRip was first released over 20 years ago - back then there were different focuses, nobody wanted to just copy the big audio files and also nobody wanted to keep 10 of them as.  😉 
I'm already thinking of extending the number of audio track panels, but that's not easy nor quick to do.
But in the meantime I'll see if I can add a new mode to include demuxed files as well ... maybe I'm gonna make a poll on Discord for that...

> I think that displaying all audio tracks in Container Options and duplicating the first two on the main screen doesn't conflict with behaviour of anything. Users still can use Audio panel as before even if there's more than 2 audios in total. They also can quickly add, delete, rename or reorder audio tracks through Container Options.

Totally depends on your need and workflow. To proper implement it, I have to check if the files are already used for the audio track panel, which can be truely difficult, because both parts are separated.

> Adding to "Project Options" → "Audio" → "Demux Audio" an option "Demux all and attach to project" is basically what I mean.

Yeah, already got it.  👍 

> Yeah, but only in filename. I'll still have to manually attach and name every audio stream to project because if I open a source file with 5 audios in StaxRip and start processing without any changes, I'll get the file with only 2 audio tracks named "Track 1" and "Track 2" in video player, so track names don't save after remuxing.

So we have another improvement here, that is also necessary for the other improvement to work.  😕 
Just by writing it down it feels pretty time consuming. 😅 

Btw:  Are 5 audio tracks (in total) the maximum or do you deal sometimes with even more?

**Comment by Omegaplexx** [comment]
> StaxRip was first released over 20 years ago

It's amazing that a program that's older than myself, after many years, is still improving and doesn't require paid subscriptions or watching ads. Thank you for your responsiveness and willingness to develop this long-standing project. It's really amaze me!

> I'm already thinking of extending the number of audio track panels, but that's not easy nor quick to do.

Personally, I rarely use audio panel on main screen, as I use StaxRip quite often for muxing bunch of subtitles and audios to output files. I understand that many users don't need to merge that many tracks into containers, so two slots of the bottom audio panel are enough for them. That's why I suggest to change only its logic to duplicate the first two tracks displayed in Container Options, rather than adding new audio panels or expanding the number of slots in the existing one.

> I'll still have to manually attach and name every audio stream to project because if I open a source file with 5 audios in StaxRip and start processing without any changes, I'll get the file with only 2 audio tracks named "Track 1" and "Track 2" in video player, so track names don't save after remuxing.

Oops, I'm really sorry. Just tested it. if I open a file with 5 audios and start processing without changes, I'll get a video with 2 properly named audios, but there's still a problem. If I try to attach the other 3 demuxed but cut tracks via Container Options, StaxRip doesn't keep their names and they end up being named as "Track 3", "Track 4" and "Track 5" in the output file.

> Btw: Are 5 audio tracks (in total) the maximum or do you deal sometimes with even more?

Of course! I once even muxed 22 different Russian dubs of The Terminator to MKV. Yeah, sounds stupid, but I needed to get all the voiceovers in one place xD

**Comment by Dendraspis** [comment]
Should have been fixed/done with `v2.42.0`, so I close this now...
