### ISSUE TITLE
Impossible AV1 Encoding: Video encoding pass 1 returned exit code: -1073741795 (0xC000001D)

### ISSUE THREAD

**Issue by rafpigna** [staxrip/staxrip#1181]
**Describe the bug**
Tried AV1 encoding with StaxRip 2.31 and AOMEnc (but had the same problem both with Rav1e and SvtAv1EncApp).
Tried both with single pass or two pass
Tried both with all default settings or tweaking some settings.
Tried with different video sources (h264, h265) and containers (mp4, mkv)
Tried also with the StaxRip 2.32, same error.
I can't encode any video in AV1, never.
**Please note: encoding Av1 in Handbrake from the same sources on the same system, works totally fine.**

Error received after a couple of seconds from the encoding starts (after about 50 frames):

Video encoding pass 1 returned exit code: -1073741795 (0xC000001D)

Just tweaking the settings I discovered that changing Bit Depth to 8 instead of 10 (--bit-depth=8) with TWO PASS, execute the first passa corretcly without errors, but after 30/50 frames in the second pass, the error appears and the encoding crashes.
If used --bit-depth=8 in ONE PASS, the error shows immediately (after about 50 frames)

In the error window there is an "odd" part at the end that refers to source files used to compile the encoder.. maybe is a good hint...
```
   in StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:riga 353
   in StaxRip.AOMEnc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Code\Github\staxrip\staxrip\Source\Encoding\AOMEnc.vb:riga 75
   in StaxRip.AOMEnc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\AOMEnc.vb:riga 52
   in System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:riga 379
```
My system specs:
Ryzen 9 5900X 12 cores - 24 Threads (stock, not overclocked)
64GB DDR4 3200Mhz
NVIDIA RTX 3080 10G

**Expected behavior**
Expected to be able to encode in AV1

**How to reproduce the issue**
Just try to encode any x265/x265 mp4/mkv video in AV1 with any of the three encoders shipped with StaxRip

**Provide information**
This is the log of one of my tries, done with AOMEnc and ALL DEFAULT SETTINGS.
But I can provide as many as you want with different conditions.

I provide you with the full text from the error window and the encoding job log.

[full_error_log.txt](https://github.com/staxrip/staxrip/files/13889099/full_error_log.txt)

[Star Trek_ Enterprise_S01E01_Prima missione_ Parti 1 e 2 [1080p][H264 - AAC]_staxrip.log](https://github.com/staxrip/staxrip/files/13889102/Star.Trek_.Enterprise_S01E01_Prima.missione_.Parti.1.e.2.1080p.H264.-.AAC._staxrip.log)

**Comment by Dendraspis** [comment]
Can you also share the log file from the `v2.32.0` version?  There should be a difference...

**Comment by rafpigna** [comment]
> Can you also share the log file from the `v2.32.0` version? There should be a difference...

Well, I feel so stupid.
Unpacked the 2.32 zip I just forgot to change the link on my desktop to the new version, so when I was testing the 2.32 I was still using 2.31 and didnt noticed that! 
2.32 works fine!
Sorry for this, lesson learned: stop having more than one version "installed" in different folders... :)

**Comment by rafpigna** [comment]
> Can you also share the log file from the `v2.32.0` version? There should be a difference...

Anyway, just for my understanding, and of course only if you know, what is the difference between 2.31 and 2.32 about this error? What was causing it?

**Comment by Dendraspis** [comment]
The problem was a Microsoft compiler bug that broke the builds it has created. In `v2.32` the tools were compiled with an older version.

Glad it works for you, I just wish you had noticed it before putting that much time into the report.  😕 
But also glad you've found the problem and it works now.  👍
