### ISSUE TITLE
Error Extract Dolby Vision metadata

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1183]
**Describe the bug**
When demuxing remux with DV layer profile 7 getting Error Extract Dolby Vision metadata.
In project options in Video tab I have selected
- Extract HDR metadata set to Dolby Vision only
- RPU conversion mode set to 2: Convert RPU to be 8.1 compatible
Log attached to issue.

**Expected behavior**
No error and DV layer processed correctly

**Provide information**
StaxRip    : v2.32.0

[Weathering With You (2019) UHD BDRemux 2160p Dolby Vision, HDR_staxrip.log](https://github.com/staxrip/staxrip/files/13902874/Weathering.With.You.2019.UHD.BDRemux.2160p.Dolby.Vision.HDR_staxrip.log)

**Comment by Dendraspis** [comment]
Thanks for the report and the log file.
On some systems .NET Code is interpreted differently, don't know why, but it seems to be not OS version related.  🙄

The issue is already fixed and will be available with the next release - probably in a few days.
