### ISSUE TITLE
Preserve audio track name if added through container options

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1184]
**Is your feature request related to a problem? Please describe.**
When adding additional audio tracks through container options, their original names that were demuxed from remux are not preserved

**Describe the solution you'd like**
Do the same way as 2 main audio tracks from main GUI.

**Explain why the feature matters to you**
When you have a bunch of audio tracks(there might be few commentary tracks) it is not clear what tracks corresponds to which file if there is no original track name.

**Comment by Dendraspis** [comment]
Thanks for separating the topics even it was not necessary. 😊👍

**Comment by Dendraspis** [comment]
Will be integrated in the next release....
