### ISSUE TITLE
(EAC3) Demux audio returned exit code: 1 when opening MP4 file

### ISSUE THREAD

**Issue by rafpigna** [staxrip/staxrip#1185]
**Describe the bug**
StaxRip version 2.32 (tried with 2.31 and 2.30, same error)
Not happens with all .mp4 files, but only with some (seems only on videos that contains all audio in EAC3, not videos that contains mixed audio format like one track EAC3 and one AAC or DTS and so...), I dont understand why: if it's a bug or a file problem.
As soon the mp4 source file is loaded, it starts to demux it and the error message shows. 
The app force closes itself after clicking on "ok" in the error message window.

Only way to avoid the error is to set "Demux audio" to "none" in the options panel.
Tried to select DirectShow and NicAudio as Cutting Method (dont know if it's needed) but same error.

Mediainfo and logfile attached below

**Expected behavior**
That I'm able to load the source file without errors :)
[log_file.log](https://github.com/staxrip/staxrip/files/13908358/log_file.log)
[mediainfo.txt](https://github.com/staxrip/staxrip/files/13908360/mediainfo.txt)

**Comment by Dendraspis** [comment]
Okay, the file is definitely not *"normal"*.`MP4Box` struggles to deal with it, so you have to choose `ffmpeg` instead.

Go to `Settings » Preprocessing`, disable `MP4Box` and click on `Edit` for `ffmpeg: Demux` and add `mp4` to the field:
![image](https://github.com/staxrip/staxrip/assets/50659978/03eb9ef5-9b42-4eb0-a927-bb35a7085d33)

Then everything should work again including demuxing.

**Comment by rafpigna** [comment]
Thanks for the "solution", I will test it asap.
Anyway the file was downloaded from the most famous streaming site and encoded by "StreamFab" software. 
I downloaded other movies and tvshows, but this is the only one that had this issue, I really dont know why!
I'm sorry to had bothered you with this, but because I used StaxRip with thousands of files and never had this issue, I was quite sure there was some bug, somewhere, but now I'm happpy that the bug was the file itself! :-)
Thanks for your help!

**Comment by rafpigna** [comment]
Tested your suggested solution: it works, but the subtitles are not demuxed so in the next encoding will be impossible to add them. I dont know if it's normal that ffmpeg demux can't extract subtitles (.srt files) or it's another bug caused from the "strange" file.
Am I missing something about subtitles demux? There is a way to let's ffmpeg do it or do it automatically after the source is fully loaded and demuxed, but with no subs? 

Only solution that I found is to firstly demux the source file via mp4box with no audio demuxing, then demux it via ffmpeg to obtain also audio. Anyway this will be necessary only if I need to cut/split the original video, because if I have to encode or remux the full video, mp4 box will work fine with this strange buggy file type.

**Comment by Dendraspis** [comment]
No problem, just glad we could solve the problem so easy.  😅 

In case of the `ffmpeg` demuxer, the subtitles are used directly from the source file as you have already found out:
![image](https://github.com/staxrip/staxrip/assets/50659978/e18720a8-66f0-40aa-aff8-9d4553854e88)


>  if the target file container is set to "mp4" there are no subtitles. If I change the container to MKV, immediately all subtitles appears. If I change it back to mp4, all the subs disappears again.

StaxRip copies the subtitles from the source file to the new container, but only for `MKV`, not for `MP4`. I guess this is because of the limited supported subtitle types and it was never split in StaxRip.  🤔

**Comment by Dendraspis** [comment]
The next release will will also extract all subtitles when using the `ffmpeg` demuxer, this should also solve your issue.

I close this one as the original issue is sort of solved.....
