### ISSUE TITLE
DoVi Extraction does not work on demuxed x265 files

### ISSUE THREAD

**Issue by FlorianGamper** [staxrip/staxrip#1187]
**Describe the bug**
When Extracting HDR MetaData of DolbyVision formats it does not work on demuxed streams (tested with .x265 Streams)
Mediainfo also does not detect DoVi Data in them. But if dovi_tool is used directly on the demuxed streams, it extracts the rpu data properly. 

**Expected behavior**

**How to reproduce the issue**
use Extract HDR MetaData with Demux Video and encode a video

If you can't (or don't) share your log file, give us at least this information:
- 2.32.1

**Comment by Dendraspis** [comment]
Can you post the MediaInfo data of the source file?

**Comment by FlorianGamper** [comment]
Media Info of the mkv

`Video
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
`

and of the extracted x265
'Video
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : SMPTE ST 2086, HDR10 compatible
'

This happens with all mediainfo queries on extracted "x.x265" files
but dovi_tool extracts >10 MB rpu data out of the file

**Comment by Dendraspis** [comment]
The next release should already solve this issue, so please check that later in `v2.33`....

**Comment by FlorianGamper** [comment]
Regression in 2.35 
Extraction only happens on Muxed video files, not on demuxed x265
May be, as mediainfo does not recognize DV Metadata in extracted video streams.

**Comment by Dendraspis** [comment]
Already fixed for the release...
