### ISSUE TITLE
HDR10plus issue

### ISSUE THREAD

**Issue by Wursti87** [staxrip/staxrip#1188]
Every HDR/Dovi file won't work since HDR10plus tool added in vers. 2.32 (2.31 and older works fine)

If file added and hdr10plus tool running, there is an failure msg after collecting informations
Also tried two older versions of hdr10 plus tool (1.5.2 + 1.5.1) same issue

` Error Extract HDR10+ metadata (v2.33.0)

Extract HDR10+ metadata returned exit code: 1 (0x1)

----------------------- Extract HDR10+ metadata -----------------------

HDR10Plus_Tool 1.6.0

C:\ProgramData\StaxRip-v2.33.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -hide_banner -probesize 50M -i "E:\HDR\2160p.DV.HDR.mkv" -an -sn -dn -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | C:\ProgramData\StaxRip-v2.33.0-x64\Apps\Support\HDR10Plus_Tool\hdr10plus_tool.exe extract -o "E:\HDR\2160p.DV.HDR_temp\HDRmetadata.json" -

Input #0, matroska,webm, from 'E:\HDR\2160p.DV.HDR.mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
    creation_time   : 2024-01-18T10:08:07.000000Z
  Duration: 01:30:28.96, start: 0.000000, bitrate: 24215 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 662.375000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 662.375000, end 1221.583000
      ....cutted.....
      Metadata:
        title           : Chapter 09
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1608 [SAR 1:1 DAR 160:67], 24 fps, 24 tbr, 1k tbn (default)
      Metadata:
        BPS             : 23444353
        DURATION        : 01:30:28.959000000
        NUMBER_OF_FRAMES: 130295
        NUMBER_OF_BYTES : 15909804287
        _STATISTICS_WRITING_APP: mkvmerge v77.0.11 ('Elemental') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-01-18 10:08:07
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1
  Stream #0:1(ger): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
      Metadata:
        title           : German
        BPS             : 384000
        DURATION        : 01:30:28.960000000
        NUMBER_OF_FRAMES: 169655
        NUMBER_OF_BYTES : 260590080
        _STATISTICS_WRITING_APP: mkvmerge v77.0.11 ('Elemental') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-01-18 10:08:07
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(ger): Subtitle: subrip (default) (forced)
      Metadata:
        title           : German (Forced)
        BPS             : 0
        DURATION        : 00:56:12.375000000
        NUMBER_OF_FRAMES: 13
        NUMBER_OF_BYTES : 384
        _STATISTICS_WRITING_APP: mkvmerge v77.0.11 ('Elemental') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-01-18 10:08:07
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
 Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Output #0, hevc, to 'pipe:':
  Metadata:
    encoder         : Lavf60.20.100
  Chapters:
    Chapter #0:0: start 0.000000, end 662.375000
      Metadata:
        title           : Chapter 01
    ....cutted.....
      Metadata:
        title           : Chapter 09
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1608 [SAR 1:1 DAR 160:67], q=2-31, 24 fps, 24 tbr, 1k tbn (default)
      Metadata:
        BPS             : 23444353
        DURATION        : 01:30:28.959000000
        NUMBER_OF_FRAMES: 130295
        NUMBER_OF_BYTES : 15909804287
        _STATISTICS_WRITING_APP: mkvmerge v77.0.11 ('Elemental') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-01-18 10:08:07
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1
Press [q] to stop, [?] for help
size=  398545kB time=00:03:25.99 bitrate=15849.0kbits/s speed= 393x    
...cutted....
size=15063404kB time=01:26:15.37 bitrate=23843.6kbits/s speed= 335x    
[out#0/hevc @ 0000020682f6ed40] video:15537154kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
size=15537154kB time=01:30:28.79 bitrate=23445.4kbits/s speed= 340x    
Error: Condition failed: `self.hdr10plus_sei_list.len() == frames.len()` (130296 vs 130295)

StaxRip.ErrorAbortException: Extract HDR10+ metadata returned exit code: 1 (0x1)

----------------------- Extract HDR10+ metadata -----------------------

HDR10Plus_Tool 1.6.0

C:\ProgramData\StaxRip-v2.33.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -hide_banner -probesize 50M -i "E:\HDR\2160p.DV.HDR.mkv" -an -sn -dn -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | C:\ProgramData\StaxRip-v2.33.0-x64\Apps\Support\HDR10Plus_Tool\hdr10plus_tool.exe extract -o "E:\HDR\2160p.DV.HDR_temp\HDRmetadata.json" -

Input #0, matroska,webm, from 'E:\HDR\2160p.DV.HDR.mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
    creation_time   : 2024-01-18T10:08:07.000000Z
  Duration: 01:30:28.96, start: 0.000000, bitrate: 24215 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 662.375000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 662.375000, end 1221.583000
      ......cutted......
      Metadata:
        title           : Chapter 09
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1608 [SAR 1:1 DAR 160:67], 24 fps, 24 tbr, 1k tbn (default)
      Metadata:
        BPS             : 23444353
        DURATION        : 01:30:28.959000000
        NUMBER_OF_FRAMES: 130295
        NUMBER_OF_BYTES : 15909804287
        _STATISTICS_WRITING_APP: mkvmerge v77.0.11 ('Elemental') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-01-18 10:08:07
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1
  Stream #0:1(ger): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
      Metadata:
        title           : German
        BPS             : 384000
        DURATION        : 01:30:28.960000000
        NUMBER_OF_FRAMES: 169655
        NUMBER_OF_BYTES : 260590080
        _STATISTICS_WRITING_APP: mkvmerge v77.0.11 ('Elemental') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-01-18 10:08:07
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
 Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Output #0, hevc, to 'pipe:':
  Metadata:
    encoder         : Lavf60.20.100
  Chapters:
    Chapter #0:0: start 0.000000, end 662.375000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 662.375000, end 1221.583000
      Metadata:
.....cutted.......
      Metadata:
        title           : Chapter 09
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1608 [SAR 1:1 DAR 160:67], q=2-31, 24 fps, 24 tbr, 1k tbn (default)
      Metadata:
        BPS             : 23444353
        DURATION        : 01:30:28.959000000
        NUMBER_OF_FRAMES: 130295
        NUMBER_OF_BYTES : 15909804287
        _STATISTICS_WRITING_APP: mkvmerge v77.0.11 ('Elemental') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-01-18 10:08:07
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1
Press [q] to stop, [?] for help
size=  398545kB time=00:03:25.99 bitrate=15849.0kbits/s speed= 393x    
.......cutted...... 
size=15063404kB time=01:26:15.37 bitrate=23843.6kbits/s speed= 335x    
[out#0/hevc @ 0000020682f6ed40] video:15537154kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
size=15537154kB time=01:30:28.79 bitrate=23445.4kbits/s speed= 340x    
Error: Condition failed: self.hdr10plus_sei_list.len() == frames.len() (130296 vs 130295)

   bei StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:Zeile 353.
   bei StaxRip.MainForm.ExtractHdr10PlusMetadata(Project proj) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:Zeile 3446.`

Also don't know why there is 
`   bei StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:Zeile 353.
   bei StaxRip.MainForm.ExtractHdr10PlusMetadata(Project proj) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:Zeile 3446.`
there are no files (or my directory)

**Comment by Dendraspis** [comment]
So this should be definitely a tool or broken source file issue. `ffmpeg` reports `130295` frames, no clue where the additional frame comes from, but from StaxRips side everything looks good.

**Comment by Wursti87** [comment]
I don't think that the source file is broken (because in 2.31 it is working - and tried serveral HDR / Dovi files)
Could it be the implamentation of the hdr tool is not correct? Because the link to wrong directories ( everytime ´d:\code\github.....´ is in log)

**Comment by Dendraspis** [comment]
Open the `Command Prompt` and paste the command line, that StaxRip executes, in and run it:
`C:\ProgramData\StaxRip-v2.33.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -hide_banner -probesize 50M -i "E:\HDR\2160p.DV.HDR.mkv" -an -sn -dn -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | C:\ProgramData\StaxRip-v2.33.0-x64\Apps\Support\HDR10Plus_Tool\hdr10plus_tool.exe extract -o "E:\HDR\2160p.DV.HDR_temp\HDRmetadata.json" -`

What is the result?

**Comment by Wursti87** [comment]
`[out#0/hevc @ 0000019f42087e40] video:15537154kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
size=15537154kB time=01:30:28.79 bitrate=23445.4kbits/s speed= 327x
Error: Condition failed: self.hdr10plus_sei_list.len() == frames.len() (130296 vs 130295)`

And no temp file (or the temp folder) was created (or saved)
One frame difference between ffmpeg and hdr10plus. This is at all files i tested
Seems to be that the tools a a different frame counting method

**Comment by Dendraspis** [comment]
So it has to be a tool issue, assuming that your files are okay and your system does not interfere. I have checked several files and have never seen such a frame difference. 🤔
