### ISSUE TITLE
StaxRip v2.33.0 Dolby Vision RPU crop

### ISSUE THREAD

**Issue by legosoff** [staxrip/staxrip#1190]
Hello, Dendroaspis. Dolby Vision 3840 x 2160p there is nothing to crop 3840x1600p RPU. I have an LG OLED 1C, Dolby Vision screen is narrow, incorrectly expanded due to 3840 x 2160p, you need to crop 3840x1600p, which you do not have.

I'm through Dolby_Vision_Tool, СROP YES,  the screen is perfectly smooth. https://radikal.host/i/czbhcX

https://radikal.host/i/czbNrO

**Comment by Dendraspis** [comment]
Sorry, don't understand your issue.

Why don't you crop the video to `2160x1600`? The result should be fine...

**Comment by legosoff** [comment]
Yes, the video should be cropped 3840x1600, and you also need to crop the RPU 3840x1600, but you don't have it. The RPU costs 3840x2160 is not correct.

**Comment by legosoff** [comment]
You thought it was just a video, trimming one and rpa without trimming and encoding to mp4 is not easy. If you crop a 3840x1600 video, you will also need to trim the 3840x1600 frame and the screen exactly. If the video is 3840x2160 without cropping, then without cropping the rpu it will be the entire screen 3840x2160.

**Comment by legosoff** [comment]
https://radikal.host/i/c3KuCe   You've seen it, the screen is narrow.
Crop video 3840x1600 and rpu without crop 3840x2160 Dolby Vision the screen is not correct.

**Comment by Dendraspis** [comment]
But the RPU is always cropped in StaxRip  🫤

**Comment by legosoff** [comment]
I'm through Dolby_Vision_Tool.exe rpu crop, everything is OK.  
You StaxRip crop rpu does not work.

**Comment by Dendraspis** [comment]
Can you post the log file?

**Comment by Dendraspis** [comment]
The crop issue should be gone in the next version that will be released on Saturday.

Btw: The `Cropped Encode` function should produce the same RPU file that `v2.33` produces because the `-c` parameter is used on `dovi_tool`.
