### ISSUE TITLE
Crop Bug

### ISSUE THREAD

**Issue by nnnnnnnbow** [staxrip/staxrip#1191]
When you crop manually with QTGMC, a bug appears between frames with color distortion. And when you choose autocrop, the problem disappears. This happens on different videos
![Auto Crop](https://github.com/staxrip/staxrip/assets/83091567/5ed4c523-0212-4da5-801f-940ac4151400)
![Hand Cut](https://github.com/staxrip/staxrip/assets/83091567/44423bde-fdf9-4fd9-94fa-c50ae1ddd089)

**Comment by Dendraspis** [comment]
log file? Preferably of both encodes.

**Comment by nnnnnnnbow** [comment]
I played with it and it can disappear even with manual cropping, but you need to trim the corners and check preview each time whether it disappears on the same frame on which it tends to appear

**Comment by nnnnnnnbow** [comment]
There are no errors in the log file, it encodes both with and without color distortion. The main thing is to fix the bug before the start

**Comment by Dendraspis** [comment]
I don't want to see if there is an error, I want to see the scripts.

**Comment by nnnnnnnbow** [comment]
Log File
[Outkast - So Fresh, So Clean_staxrip.log](https://github.com/staxrip/staxrip/files/14057606/Outkast.-.So.Fresh.So.Clean_staxrip.log)

**Comment by Dendraspis** [comment]
This is definitely a issue with the used filters and not StaxRip.

You should try to re-order the filters
```
Crop(6, 126, -8, -126)
QTGMC(preset="Medium")
BicubicResize(944, 408)
ChangeFPS(25)
```

to something like

```
QTGMC(preset="Medium")
Crop(6, 126, -8, -126)
BicubicResize(944, 408)
ChangeFPS(25)
```
as the cropped size is not `Mod 8` it could make problems. Adjust the cropping, making it `Mod 8`, could also work.

You could also try to use `QTGMC()` with the `sourceMatch = x` parameter and see if it makes any difference, like
`QTGMC(preset="Medium", InputType=0, sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8)`

Sadly I can't give more advices.
