### ISSUE TITLE
AOMEnc / SVT-AV1 - Encoder settings are not displayed in finished file

### ISSUE THREAD

**Issue by Flyk3** [staxrip/staxrip#1192]
If I encode with x264 or x265, the encoder options are automatically transferred to the mkv. MediaInfo thus displays the encoder settings:
![x265s](https://github.com/staxrip/staxrip/assets/145803606/d8cef2b5-d5af-41c3-b2c2-548455b95896)

This is not the case with AV1 (AOMEnc and SVT1):
![AV1](https://github.com/staxrip/staxrip/assets/145803606/d419c377-d9c6-416a-97cc-46f9bbf95717)

**Comment by Dendraspis** [comment]
This tag is optional, I don't know why AOMedia don't include it, but they don't do it.  😕
