### ISSUE TITLE
Automatic RPU generation (and HDR metadata if possible) 

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1194]
v 2.33
**What are the settings / entries / criteria to have the Dolby Vision RPU.BIN file automatically generated by StaxRip?**

Occasionally happens automatically, but I cannot figure out how to make it happen on demand.

Re-encoding using NVEncC (Nvidia) H.265 to MP4 to enable DV playback on my Amazon QLED Fire TV. See my discussion about issues/settings: https://github.com/staxrip/staxrip/discussions/1179

I generally use **HDR Muti** Tool to extract the **RPU.bin** but it would be more convenient to let StaxRip generate the file automatically.  https://github.com/jlw4049/HDR-Multi-Tool

Also, is there a way to have the HDR10(+) metadata file extracted automatically?

**Comment by Dendraspis** [comment]
The extraction is based on the settings in `Options » Video` regarding the HDR metadata extraction and then on the media info of the source file.

So if you have a source file, where the RPU data is not extracted, then please post the media info of that file.

**Comment by noblemd00** [comment]
Is there any restriction or requirement for the text entered in the VUI HDR10 Info File and Dolby Vision RPU input boxes

If these are blank does the extraction still occur? If they contain text what happens (are the entries disregarded-ignored)? 

<img width="148" alt="240125 102234" src="https://github.com/staxrip/staxrip/assets/16325865/a0e4a7fb-7088-4fcd-ba23-f61629293f27">

These entries (Options-Video) have worked for recent re-encodes (auto extract):
<img width="297" alt="240125 094253" src="https://github.com/staxrip/staxrip/assets/16325865/2a3e02cf-f643-4d52-b404-66cace74efb9">

**Comment by Dendraspis** [comment]
So after your *Update* it looks like everything works as intended. 🤔 

> HDR10 Info remains blank after extract - shouldn't this be filled with "copy" or the .json file path/name (like the RPU entry)?

Yes, that's an issue I have already solved for the next release that is coming out within the next few days. So in `v2.34` the `HDR10 Info File` field will also be set when a `Dolby Vision RPU` is set.
