### ISSUE TITLE
Attempting to use NvencC upsize nvvfx-superres fails

### ISSUE THREAD

**Issue by chowderhead** [staxrip/staxrip#1196]
attempting to upscale from 720p to 1080p with nvvfx-superres.
Ive followed all the instructions listed in NvencC 7.31 instructions.
but staxrip still produces an error as follows when trying to use nvvfx-superres function call.
Ive searched everywhere t find out what file is missing but cannot.
Ive attempted to query rigaya about this problem to which he replied.

"If you ran the installers then everything should work fine....if it doesn't work what do you want me to do about it, Im not the staxrip developer."

And then ghosted me everywhere afterwards.  So he/she is an asshole who wont help me in any way despite being the bloody author of NvencC rigaya clearly could care less whether it actually works or not.

Maybe you can get some useful info from rigaya, I sure couldnt.

Heres the error.

```
Error Video encoding (v2.29.0)

Video encoding returned exit code: 1 (0x1)


--------------------------- Video encoding ---------------------------

NVEncC 7.31

"F:\Downloads\APPS and INSTALLERS\StaxRip-v2.29.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe" --avsdll "F:\Downloads\APPS and INSTALLERS\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --vbr 1500 --codec h265 --preset P7 --output-depth 10 --level 5.1 --multipass 2pass-full --qp-init 18 --qp-max 20 --qp-min 18 --max-bitrate 8000 --aq --aq-strength 1 --bframes 4 --ref 8 --lookahead 12 --gop-len 120 --cu-min 8 --vpp-resize algo=nvvfx-superres --vpp-convolution3d ythresh=10,cthresh=11,t_ythresh=10,t_cthresh=11 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange full --output-buf 128 --perf-monitor-interval 2000 --vbr-quality 18 --output-res 1920x1080 --mv-precision q-pel -i "C:\AADownloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004.avs" -o "C:\AADownloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_out.h265"

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
C:\AADownloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_out.h265
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
nvvfx-superres: Failed load library for nvvfx.
nvvfx-superres: Please make sure you have downloaded and installed Video Effect models and runtime dependencies.
resize: Failed to init nvvfx-superres with ratio 2.0, retrying with other ratios...
nvvfx-superres: Failed load library for nvvfx.
nvvfx-superres: Please make sure you have downloaded and installed Video Effect models and runtime dependencies.
resize: Failed to init nvvfx-superres with ratio 3.0, retrying with other ratios...
nvvfx-superres: Failed load library for nvvfx.
nvvfx-superres: Please make sure you have downloaded and installed Video Effect models and runtime dependencies.
resize: Failed to init nvvfx-superres with ratio 4.0, retrying with other ratios...
resize: Suitable ratio for nvvfx-superres not found.
resize: Failed to init nvvfx filter.

StaxRip.ErrorAbortException: Video encoding returned exit code: 1 (0x1)


--------------------------- Video encoding ---------------------------

NVEncC 7.31

"F:\Downloads\APPS and INSTALLERS\StaxRip-v2.29.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe" --avsdll "F:\Downloads\APPS and INSTALLERS\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --vbr 1500 --codec h265 --preset P7 --output-depth 10 --level 5.1 --multipass 2pass-full --qp-init 18 --qp-max 20 --qp-min 18 --max-bitrate 8000 --aq --aq-strength 1 --bframes 4 --ref 8 --lookahead 12 --gop-len 120 --cu-min 8 --vpp-resize algo=nvvfx-superres --vpp-convolution3d ythresh=10,cthresh=11,t_ythresh=10,t_cthresh=11 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange full --output-buf 128 --perf-monitor-interval 2000 --vbr-quality 18 --output-res 1920x1080 --mv-precision q-pel -i "C:\AADownloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004.avs" -o "C:\AADownloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_out.h265"

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
C:\AADownloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988..S01E004_out.h265
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
nvvfx-superres: Failed load library for nvvfx.
nvvfx-superres: Please make sure you have downloaded and installed Video Effect models and runtime dependencies.
resize: Failed to init nvvfx-superres with ratio 2.0, retrying with other ratios...
nvvfx-superres: Failed load library for nvvfx.
nvvfx-superres: Please make sure you have downloaded and installed Video Effect models and runtime dependencies.
resize: Failed to init nvvfx-superres with ratio 3.0, retrying with other ratios...
nvvfx-superres: Failed load library for nvvfx.
nvvfx-superres: Please make sure you have downloaded and installed Video Effect models and runtime dependencies.
resize: Failed to init nvvfx-superres with ratio 4.0, retrying with other ratios...
resize: Suitable ratio for nvvfx-superres not found.
resize: Failed to init nvvfx filter.


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 353
   at StaxRip.NVEnc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\NVEnc.vb:line 107
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 373
```

**Comment by rigaya** [comment]
The actual log is very useful, it is failing to load NVVideoEffects.dll.

1. There might be a case that Maxine installer requires VC++ redistributable package, but not installed. VC++ redistributable package can be downloaded from link below.
  https://aka.ms/vs/17/release/vc_redist.x64.exe

2. Please make sure environment variables which should be set by the installer is set to the correct path.
  NVVFX_MODEL_DIR should be set at: C:\Program Files\NVIDIA Corporation\NVIDIA Video Effects\models

**Comment by Dendraspis** [comment]
1. I can understand that sometimes it's pretty frustrating to get help on a pretty rare error message, especially when the answers are not of the kind you would expected, but the next time you call him or anybody else an "asshole" you will be blocked.
2. rigaya answered already and it looks like I would also go into the requirements, dependencies and the used driver.
3. It should not be StaxRip related, but yeah ... please check those two points and tell us the outcome.

**Comment by chowderhead** [comment]
Rigaya,
I just got back from a short trip and was pleasantly surprised to find this email.
Thanks so much for trying to help me.

Ill follow your instructions and see if this helps the script finally work.

I was surprised that you responded to a staxrip issue tag.
Naturally I want to ask, are you aquainted with staxrip developer since you saw the issue when I posted it?
You said you weren’t the staxrip developer in a previous email.
But you responded to the staxrip issue which kinda surprised me.

Anyway, thanks for responding and trying to help me.
I would think you would be acquainted since staxrip makes such strong use of NvencC.
Ive been using staxrip since version 1.4 stable no idea how long that is but probably 10 years or more and I love the program and all the variety of Avisynth plugins and the power of NvencC that do every imaginable thing to video at stunning speeds.

Later today Ill have time to see if this gets things running and Ill send you some feedback.

Cheers,
Randy Kuehn

**Comment by chowderhead** [comment]
I followed rigayas instructions but still same error message.  Maxine installer did NOT set the  system variable which I set manually.  Ive had a 300GB 720p upscale project sitting on idle trying to at least SEE what the superres upscale looks like.  If its anything like the NPP high res downscale module its worth the wait.  The downscales Ive done from 4K to 1080 with that plugin are shockingly good.  _ hope we can get to the bottom of the mystery.  Clearly when rigaya wrote NvencC the module surely must have worked in beta and release but something got lost from rigayas desk to nvidia to us something got whacked.  If a simple system variable fix would be awesome but weve gone down that road.  Im willing to do whatever testing to help.  Staxrip users should realize if the upscale rivals the down module everyone is in for a real treat.  

my_ apologies for the language, I guess I had hit my limit and  pressure from the project etc etc...but still no excuse.  Thanks rigaya for overlooking my crappy attitude.  If theres anything else to try please let me know.  Ive nearly given up hope for getting this working....And have to start the project within a few days.  Since everything is buried inside DLL's theres probably no quick fix like with VBscript or python java etc.

Anything else I can try??  Rigaya??  should I just give up for now?  I cant even file a ticket w nvidia since their system keeps erroring when creating my acccount.  Oh well, if theres any hope let me know otherwise its probably spline36 ...........again.

Cheers, Randy

**Comment by rigaya** [comment]
I think we can check two more for extra hints.

1. As I was able to know from the log exactly where it is causing error, I've created a test build which might be able to show better error logs. Although this will still cause error, the error message is designed to show more information.
  https://nightly.link/rigaya/NVEnc/actions/runs/7677168703/NVEncC_release_r2683_x64.zip
  Please extract the zip file, and then the internal 7z file, and then run the command line below in the extracted directory which NVEncC64 exists. Afterwards, please share (attach) the "log.txt" generated, which might help.
  ```NVEncC64.exe -i "<path to any 720p input file>" -o test.mp4 --vpp-resize nvvfx-superres --output-res 1920x1080 --log-level debug --log log.txt```

2. Please check ```C:\Program Files\NVIDIA Corporation\NVIDIA Video Effects\NVVideoEffects.dll``` in your system by using DependenciesGui.exe (x64) in [Dependencies](https://github.com/lucasg/Dependencies). It might be able to show error when loading it's submodules.
  Below is the example of ```nppig64_11.dll``` load error, which I removed ```nppig64_11.dll``` on purpose to just show example of error. There should not be a module shown in red like this. 
  ![image](https://github.com/staxrip/staxrip/assets/815947/3f3ea7ea-c5c9-408c-80a0-b799473e46c8)

**Comment by chowderhead** [comment]
ill try this and report back.  sorry for the delay.  my PC acted up a little and not so quick repair delayed my attempting these instructions.

**Comment by chowderhead** [comment]
well certainly a surprise.  It appears to have worked.  (I think) when done this way But I tested with staxrip as well as this method and still got the error message in staxrip.  Heres the 1080 output file test.mp4 and the log file.

cheers Randy 


https://github.com/staxrip/staxrip/assets/22981743/c8bf8fb9-8ec1-4e0c-9ad2-c07aa9595cf8

[log.txt](https://github.com/staxrip/staxrip/files/14111252/log.txt)

**Comment by chowderhead** [comment]
I made a really small test file.  heres the specs on the test input file from media info if it helps you further.

General 
Unique ID : 315397171673380699633705896602451411468 (0xED4749259B4779CA54383A3BB669820C) 
Complete name : C:\AADownloads\REMUX3\TEST.720P.SMALL-001.mkv 
Format : Matroska 
Format version : Version 4 
File size : 12.0 MiB 
Duration : 11 s 797 ms 
Overall bit rate mode : Variable 
Overall bit rate : 8 559 kb/s 
Frame rate : 24.262 FPS 
Encoded date : 2024-01-31 11:48:16 UTC 
Writing application : mkvmerge v78.0 ('Running') 64-bit 
Writing library : libebml v1.4.4 + libmatroska v1.7.1 
Attachments : aaaiight.ttf / ARIAL.TTF / cosmic2n.ttf / georgiab.TTF / L_10646.TTF / lsans.ttf / Maian.TTF / QlassikBold_TB.otf / tt0448m_.ttf 

Video 
ID : 1 
Format : AVC 
Format/Info : Advanced Video Codec 
Format profile : High 10@L4 
Format settings : CABAC / 12 Ref Frames 
Format settings, CABAC : Yes 
Format settings, Reference frames : 12 frames 
Codec ID : V_MPEG4/ISO/AVC 
Duration : 9 s 768 ms 
Bit rate : 7 048 kb/s 
Width : 960 pixels 
Height : 720 pixels 
Display aspect ratio : 4:3 
Frame rate mode : Variable 
Frame rate : 24.262 FPS 
Original frame rate : 23.976 (24000/1001) FPS 
Color space : YUV 
Chroma subsampling : 4:2:0 
Bit depth : 10 bits 
Scan type : Progressive 
Bits/(Pixel*Frame) : 0.420 
Stream size : 8.21 MiB (68%) 
Language : English 
Default : Yes 
Forced : No 
Color range : Limited 
Color primaries : BT.709 
Transfer characteristics : BT.709 
Matrix coefficients : BT.709 

Audio #1 
ID : 2 
Format : FLAC 
Format/Info : Free Lossless Audio Codec 
Codec ID : A_FLAC 
Duration : 9 s 813 ms 
Bit rate mode : Variable 
Bit rate : 624 kb/s 
Channel(s) : 2 channels 
Channel layout : L R 
Sampling rate : 48.0 kHz 
Frame rate : 11.719 FPS (4096 SPF) 
Bit depth : 16 bits 
Compression mode : Lossless 
Delay relative to video : 15 ms 
Stream size : 748 KiB (6%) 
Writing library : libFLAC 1.2.1 (2007-09-17) 
Language : Japanese 
Default : Yes 
Forced : No 
MD5 of the unencoded content : EFAFAAB87C2BC7607BAD339B32C6A0ED 

Audio #2 
ID : 3 
Format : MLP FBA 
Format/Info : Meridian Lossless Packing FBA 
Commercial name : Dolby TrueHD 
Codec ID : A_TRUEHD 
Duration : 9 s 768 ms 
Bit rate mode : Variable 
Bit rate : 1 624 kb/s 
Maximum bit rate : 2 673 kb/s 
Channel(s) : 6 channels 
Channel layout : L R C LFE Ls Rs 
Sampling rate : 48.0 kHz 
Frame rate : 1 200.000 FPS (40 SPF) 
Compression mode : Lossless 
Stream size : 1.89 MiB (16%) 
Language : Japanese 
Default : No 
Forced : No 

Text 
ID : 4 
Format : ASS 
Codec ID : S_TEXT/ASS 
Codec ID/Info : Advanced Sub Station Alpha 
Duration : 9 s 200 ms 
Bit rate : 174 b/s 
Frame rate : 0.217 FPS 
Count of elements : 2 
Compression mode : Lossless 
Stream size : 201 Bytes (0%) 
Language : English 
Default : Yes 
Forced : No 

Menu 
00:00:00.000 : en:Chapter 01

**Comment by chowderhead** [comment]
The person im doing this 720 convert for is also very interested to see the output of the nvvfx-superres upsize option compared to spline36.  so I have a little more time to see if this can be fixed in staxrip.  Since Im also using several AVIsynth plugins for this and theres nearly 200 files doing this by command line would be quite difficult along with audio file conversions and muxing subtitles etc etc.  Thats a tall order for command line ripping.  I could write a FOR /R script that "Might" work but being a coder is not my strong suit and it likely would NOT work imho given my skill set.

Randy

**Comment by chowderhead** [comment]
Out of curiosity I plugged your 2683 build in staxrip 2.34.  Great news - works properly in staxrip 2.34.  whatever its doing it has pegged my GPU and slowed ripping to 90fps down from 130fps.  Its really thinking hard about this.  AMAZING.
After all this effort it appears nvvfx-superres only handles symmetrical 2X 3X 4X upscales.  but the program handles the upscale downscale process to get to 1080 wo any additional input.
ITS CLEAN.  WOW.  BEAUTIFUL UPSCALE.  LACK OF UPSCALE ARTIFACTS IS AMAZING!!

--------------------------- Video encoding ---------------------------

NVEncC 7.42

C:\AADownloads\REMUX3\StaxRip-v2.34.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe --avsdll C:\AADownloads\REMUX3\StaxRip-v2.34.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --qvbr 28 --codec h265 --preset P7 --output-depth 10 --level 5.1 --multipass 2pass-full --qp-init 19 --qp-max 21 --qp-min 19 --max-bitrate 8000 --aq --aq-strength 1 --bframes 4 --ref 8 --lookahead 12 --gop-len 120 --cu-min 8 --vpp-resize algo=nvvfx-superres --vpp-convolution3d matrix=standard,ythresh=30,cthresh=31,t_ythresh=30,t_cthresh=31 --vpp-warpsharp depth=25 --sar 32:27 --videoformat component --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange full --cuda-schedule spin --output-buf 128 --perf-monitor-interval 2000 --vbr-quality 19 --output-res 1920x1080 --mv-precision q-pel -i "F:\Downloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988.S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988.S01E004.avs" -o "F:\Downloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988.S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988.S01E004_out.h265"

----------------------------------------------------------------------------------------------------------------------------------------------------------------
F:\Downloads\STAXRIP CACHE\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988.S01E004_temp\LOGH.(Ginga.Eiyuu.Densetsu).Main.Series.1080p.1988.S01E004_out.h265
----------------------------------------------------------------------------------------------------------------------------------------------------------------
NVEncC (x64) 7.42beta1 (r2683) by rigaya, Jan 27 2024 07:27:38 (VC 1929/Win)
OS Version     Windows 10 x64 (17763) [CP1252]
CPU            Intel Core i7-10750H @ 2.60GHz [TB: 4.43GHz] (6C/12T)
GPU            #0: NVIDIA GeForce RTX 2070 (2304 cores, 1455 MHz)[PCIe3x16][546.29]
NVENC / CUDA   NVENC API 12.1, CUDA 12.3, schedule mode: spin
Input Buffers  CUDA, 32 frames
Input Info     AviSynth+ 3.7.3 r4003(yv12)->nv12 [AVX2], 960x720, 60/1 fps
Vpp Filters    copyHtoD
               cspconv(nv12 -> yv12(16bit))
               convolution3d: matrix standard, mode normal
                       threshold spatial luma 30, chroma 31, temporal luma 30, chroma 31
               resize: nvvfx-superres 960x720 -> 1920x1440
                           nvvfx-superres: cspconv(yv12(16bit) -> bgr(fp32))
                                           nvvfx-superres: mode: 1 (aggressive), strength 0.40
                                           cspconv(bgr(fp32) -> yv12(16bit))
                       spline36 1920x1440 -> 1920x1080
               warpsharp: threshold 128.0, blur 2, type 0, depth 25.0, chroma 0
               cspconv(yv12(16bit) -> p010)
Output Info    H.265/HEVC main10 @ Level 5.1
               1920x1080p 569:480 60.000fps (60/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        0 kbps (Max: 8000 kbps)
Target Quality 19.00
Initial QP     I:19  P:19  B:19
QP range       I:19-21  P:19-21  B:19-21
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 12 frames, Adaptive I, B Insert
GOP length     120 frames
B frames       4 frames [ref mode: middle]
Ref frames     8 frames, MultiRef L0:auto L1:auto
AQ             on (spatial, strength 1)
CU max / min   auto / 8
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,videoformat:component,range:full
Others         mv:Q-pel 
encoded 74541 frames, 83.59 fps, 6673.87 kbps, 988.40 MB
encode time 0:14:51, CPU: 11.8, GPU: 96.1, VE: 75.2, GPUClock: 1638MHz, VEClock: 1518MHz
frame type IDR   720
frame type I     720,  total size   60.62 MB
frame type P   15875,  total size  464.47 MB
frame type B   57946,  total size  463.31 MB

Start:    8:14:24 AM
End:      8:29:18 AM
Duration: 00:14:54
__________________________________________________________
SPLINE36 VS NVVFX-SUPERRES SEE THIS EXAMPLE.

![SPLINE36 720-1980](https://github.com/staxrip/staxrip/assets/22981743/daf8da90-6ea6-4209-a5f9-dcc562e7c8aa)

![NVVFX-SUPERRES 720-1980](https://github.com/staxrip/staxrip/assets/22981743/444a573d-e4e1-49e2-a1a9-88d7bb2ef5d6)

**Comment by rigaya** [comment]
I'm glad to hear that now nvvfx-superres is working. It's kind of a bit weird it previously didn't work, as the Video Effect installer should have been working, and also the functionality of build 2683 is completely the same as NVEnc 7.41 (the difference between release 7.41 and build 2683 is only in the error log messages). But it's fine as it now works anyway.

> should I continue to use your quick build 2683. Im sure NvencC 7.42 release will come eventually. But is it Ok to just use this for now since it works.

Sure of course, please continue to use build 2683.

**Comment by Dendraspis** [comment]
> It's kind of a bit weird it previously didn't work, as the Video Effect installer should have been working, and also the functionality of build 2683 is completely the same as NVEnc 7.41 (the difference between release 7.41 and build 2683 is only in the error log messages). But it's fine as it now works anyway.

Maybe because he used `v7.31` and not `v7.41`? 
At least's what he said and what the log file is telling use. 🤔

So I guess we can close this issue now?  😅

**Comment by Dendraspis** [comment]
Thank you, too.  🙂
