### ISSUE TITLE
How to change "Add hardcoded subtitle" default browse location?

### ISSUE THREAD

**Issue by hani-yassine** [staxrip/staxrip#1199]
Hello i was using Staxrip version 2.1.8.0 in this version when i press ctrl + H to add hardcoded subtitles it open the file browser to where the video is located 
now i downloaded version 2.33.0 and when i press ctlr+h it always open the temp folder of the video (created by staxrip) and in my case im not trying to add the embeded subtitle im trying to add the  subtitle file that is in the same folder of the video so how to change the behavior of ctrl + h to open the folder of the video instead of the temp file like the old version of staxrip? thanks!

**Comment by Dendraspis** [comment]
Just navigate to it:

![image](https://github.com/staxrip/staxrip/assets/50659978/7b558d91-900e-4017-8f3e-0ec2d8b9e00f)

...or click on the folder in the address bar.

**Comment by hani-yassine** [comment]
> Just navigate to it:
> 
> ![image](https://private-user-images.githubusercontent.com/50659978/299831169-7b558d91-900e-4017-8f3e-0ec2d8b9e00f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDI5MjIsIm5iZiI6MTcwNjMwMjYyMiwicGF0aCI6Ii81MDY1OTk3OC8yOTk4MzExNjktN2I1NThkOTEtOTAwZS00MDE3LThmM2UtMGVjMmQ4YjllMDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIwNTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0OWZkNzRkYzg2Yjg5MjVmZDM2MmMyMzQwNWQyNGFlZWI5MWRjZWVjODk5ZDU0M2EyM2NkZjcxZTRjMDA0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Spc87QsxLiWRj0KH8UPOd-hOKQm0bGVCvaTya74NfYo)
> 
> ...or click on the folder in the address bar.

yeah i know i can do that but im doing a lot of videos so i use shortcut to open a video and another shortcut to add a sub file fast so i want to skip the step if possible like the older version

**Comment by hani-yassine** [comment]
> The behavior was changed 3 years ago in `v2.1.8.3` and I don't think I will change it, but I will let this issue open, maybe I get an idea...

i'm using a ctrl + G with the command "ShowOpenSourceSingleFileDialog" to open the video this command remember the folder where i selected the last video and open the same location so if you can add a similar command for subs that can remember the last location for previous selected sub that would be grate :) and you can keep the current behavior for people that like to quickly add embedded  subs so we have 2 options to choose, that would be great ! something like 
"ShowHardcodedSubtitleDialog" that can remember the last open location 
"ShowEmbededHardcodedSubtitleDialog" that open the temp folder of the video to select the embedded  subs

**Comment by Dendraspis** [comment]
I have split the command into two new commands, so you can open it from both locations which should satisfy your needs.

Will be available in the next release...
