### ISSUE TITLE
Preview and crop windows display problem with 1080x1920 videos

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#120]
Hi Stax, Hi everyone.
When loading a vertical video 1080x1920, the display in the the previw and crop windows are not ok.
Here is what I get:
![SNAG-0003](https://user-images.githubusercontent.com/17828567/75826321-f2a85700-5daf-11ea-8b8f-2019654837bd.jpg)

Here is a link to a samplevideo that you can try (1080x1920 hevc 10bits):
Click [here](http://zafer.kantar.free.fr/sample1080x1920_HEVC10.mkv) to download the tiny video sample.

**Comment by stax76** [comment]
So far I found out that it happens when the resize width is not mod 16 and it happens only with AviSynth and not with VapourSynth and only in StaxRip because mpv and mpc render the same script correctly.

**Comment by 44vince44** [comment]
However it dit work fine in beta 2.0.6.2

**Comment by stax76** [comment]
Hello, I'll upload a fix today.

**Comment by 44vince44** [comment]
Thanks, it seems fixed indeed !!
