### ISSUE TITLE
add Job error can't save srip file

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#1201]
SerializationException (v2.34.0)

'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' 어셈블리의 'System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[StaxRip.DolbyVisionMetadataFile, StaxRip, Version=2.34.0.0, Culture=neutral, PublicKeyToken=null]]' 형식이 serializable로 표시되어 있지 않습니다.

System.Runtime.Serialization.SerializationException: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' 어셈블리의 'System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[StaxRip.DolbyVisionMetadataFile, StaxRip, Version=2.34.0.0, Culture=neutral, PublicKeyToken=null]]' 형식이 serializable로 표시되어 있지 않습니다.
   위치: System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   위치: System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   위치: System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   위치: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   위치: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   위치: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   위치: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   위치: System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   위치: System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   위치: StaxRip.SafeSerialization.GetObjectData(Object o) 파일 D:\Code\Github\staxrip\staxrip\Source\General\General.vb:줄 367
   위치: StaxRip.SafeSerialization.Serialize(Object o, String path) 파일 D:\Code\Github\staxrip\staxrip\Source\General\General.vb:줄 282
   위치: StaxRip.MainForm.SaveProjectPath(String path) 파일 D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:줄 4203

so i replace staxrip 2.33 exe file

**Comment by Dendraspis** [comment]
Reproducible, working on a fix.  Sorry for the inconvenience...

**Comment by Dendraspis** [comment]
Here is the hotfix, replace the `StaxRip.exe` and you should be fine:

[StaxRip_v2.34.0_Hotfix.zip](https://github.com/staxrip/staxrip/files/14066736/StaxRip_v2.34.0_Hotfix.zip)

Sorry for the inconvenience...
