### ISSUE TITLE
DisplayHistogram error (staxrip 2.34)

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#1202]
Script Error

Python exception: No attribute with the name hist exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
  File "C:\EncodingSSD\TEST_temp\TEST.vpy", line 46, in <module>
    clip = muvsfunc.DisplayHistogram(clip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\StaxRip\Apps\Plugins\VS\Scripts\muvsfunc.py", line 2971, in DisplayHistogram
    histogram_v = core.hist.Classic(clip)
                  ^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 2639, in vapoursynth._CoreProxy.__getattr__
  File "src\\cython\\vapoursynth.pyx", line 2494, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name hist exists. Did you mistype a plugin namespace?

i try use vapoursynth installed directly 

it's setting is fine work.

import os, sys
  2: import vapoursynth as vs
  3: core = vs.core
  4: 
  5: sys.path.append(r"C:\StaxRip\Apps\Plugins\VS\Scripts")
  6: import importlib.machinery
  7: mvsfunc = importlib.machinery.SourceFileLoader('mvsfunc', r"C:\StaxRip\Apps\Plugins\VS\Scripts\mvsfunc.py").load_module()
  8: adjust = importlib.machinery.SourceFileLoader('adjust', r"C:\StaxRip\Apps\Plugins\VS\Scripts\adjust.py").load_module()
  9: havsfunc = importlib.machinery.SourceFileLoader('havsfunc', r"C:\StaxRip\Apps\Plugins\VS\Scripts\havsfunc.py").load_module()
 10: muvsfunc = importlib.machinery.SourceFileLoader('muvsfunc', r"C:\StaxRip\Apps\Plugins\VS\Scripts\muvsfunc.py").load_module()
 11: tcFile = r"C:\EncodingSSD\TEST_temp\TEST_timestamps.txt" # timestamps file path
 12: clip = core.ffms2.Source(r"C:\EncodingSSD\TEST.mkv", cachefile=r"C:\EncodingSSD\TEST_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"C:\EncodingSSD\TEST.mkv", cachefile=r"C:\EncodingSSD\TEST_temp\temp.ffindex")
 13: tcFile = r"C:\EncodingSSD\TEST_temp\TEST_timestamps.txt" # timestamps file path
 14: try:
 15:     clip = core.vfrtocfr.VFRToCFR(clip, timecodes=tcFile, fpsnum=60, fpsden=1)
 16: except:
 17:     raise vs.Error("Timestamps extraction from MKV must be turned on in Options. Remux your input to MKV if it is not an MKV file.")
 18: # Don't forget to mux the timestamps file in the output mkv
 19: clip = core.std.Crop(clip, 18, 18, 10, 10)
 20: clip = clip[::2]
 21: clip = muvsfunc.DisplayHistogram(clip)
 22: clip.set_output()

**Comment by Dendraspis** [comment]
Seems like a dependency does not work with `VapourSynth R55+` anymore.   😕

**Comment by DandyClubs** [comment]
use vapoursynth x64 r64 and r65 work.

use python 3.11.6

**Comment by Dendraspis** [comment]
Ehm ... what?
