### ISSUE TITLE
got an error i can't figure out

### ISSUE THREAD

**Issue by hjason78121** [staxrip/staxrip#1203]
Hello i am trying to make my uhd movies work on emby currently they don't play dolby vision even though they have dv in them..
I stubled accross this wonderful program and everything was easy and greaty until i got this error see screenshot.
i have no idea what to do here i found the settongs for vbv but i have no idea what the settings should be for anything thats why i loved this program it was all automatic except clicking the source file.. could someone please help me?
thanks

![Screenshot 2024-01-26 170330](https://github.com/staxrip/staxrip/assets/157432604/99a35b43-abfd-4f18-9e27-7de65f069c65)

**Comment by Dendraspis** [comment]
Hello,
here you can find some hints:
https://en.m.wikipedia.org/wiki/High_Efficiency_Video_Coding_tiers_and_levels
...you want to check out the column `Max bit rate for Main and Main 10 profiles (1000bit/s)`

For a normal `Level 5.1 @ High Tier` just set both values to `160000` and you're fine.
Both values are required when you use Dolby Vision metadata.

**Comment by hjason78121** [comment]
Thank you
