### ISSUE TITLE
QTGMC Repair causes encoding to stop with error at some point on versions 2.31+ 

### ISSUE THREAD

**Issue by OleksiiMatiash** [staxrip/staxrip#1205]
Starting from 2.31 it is impossible to use QTGMC Repair, encoding is starting and at some point stops with error. 2.30 works without any issue. It happens with every (long?) file, tried ~10 files 30 min+ each, no one succeeded. Tried all versions from 2.28 to 2.34. Also tried 4 different encoders in lossless mode:

- nvenc 264
- x264
- ffmpeg x64
- ffv1

Nothing helped, so it is not an encoder issue, especially because all they work nice when not using QTGMC Repair.

Typical log is attached.

[filename.log](https://github.com/staxrip/staxrip/files/14071542/filename.log)

Upd: The same with interlaced videos and usual QTGMC, btw.

**Comment by Dendraspis** [comment]
You could try to take `v2.31` and replace these file with the ones from `v2.30` and see if that makes any difference for you:
`.\Apps\Plugins\Dual\ffms2\ffms2.dll`
`\Apps\Encoders\x264.x264.exe`
...and of course use `x264` for testing.

Apart from that there is no real reason why there should be an issue, whereas `v2.30` worked.

If that also doesn't work, try the latest `v2.34`.

**Comment by OleksiiMatiash** [comment]
> .\Apps\Plugins\Dual\ffms2\ffms2.dll

That was the reason, thank you! 2.34 release with ffms2.dll from 2.30 works perfect.

**Comment by Dendraspis** [comment]
Thanks for your feedback. So I guess their latest changes fixed something, but broke something else.  🥴 

So I close this one...
