### ISSUE TITLE
why AV1 encoding output only 25 frame rate?

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#1207]
i input 30 or 60 video

use encoding nvencc av1 or svtav1encapp 

only output 25 frame rate.. and slow motion...

**Comment by Dendraspis** [comment]
What shall I do with that insufficient information?
It's like saying *"My printer does not print. What's wrong?"*  🙄

**Comment by DandyClubs** [comment]
------------------------- System Environment -------------------------

StaxRip    : v2.34.0
Windows    : Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : Korean (Korea)
CPU        : AMD Ryzen 9 7950X3D 16-Core Processor
RAM        : 64GB
GPU        : NVIDIA GeForce RTX 4090
Resolution : 3840 x 2160
DPI        : 144
Code Page  : 949

---------------------- Indexing using ffmsindex ----------------------

C:\StaxRip\Apps\Plugins\Dual\ffms2\ffmsindex.exe C:\EncodingSSD\TEST.mov C:\EncodingSSD\TEST_temp\temp.ffindex

Writing index... done.

Start:    오전 3:27:08
End:      오전 3:28:59
Duration: 00:01:50

----------------------- Media Info Source File -----------------------

C:\EncodingSSD\TEST.mov

General
Complete name            : C:\EncodingSSD\TEST.mov
Format                   : MPEG-4
Commercial name          : DNxHR HQ
Format profile           : QuickTime
Codec ID                 : qt   0000.02 (qt  )
File size                : 247 GiB
Duration                 : 1 h 19 min
Overall bit rate         : 443 Mb/s
Frame rate               : 60.000 FPS
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC
Writing application      : Blackmagic Design DaVinci Resolve Studio

Video
ID                       : 1
Format                   : VC-3
Commercial name          : DNxHR HQ
Format version           : Version 3
Format profile           : RI@HQ
Codec ID                 : AVdh
Codec ID/Info            : Avid DNxHR
Duration                 : 1 h 19 min
Bit rate mode            : Constant
Bit rate                 : 440 Mb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 60.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:2
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 3.540
Stream size              : 246 GiB (99%)
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : PCM
Format settings          : Little / Signed
Codec ID                 : lpcm
Duration                 : 1 h 19 min
Bit rate mode            : Constant
Bit rate                 : 2 304 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Bit depth                : 24 bits
Stream size              : 1.29 GiB (0%)
Default                  : Yes
Alternate group          : 1
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC

Other
ID                       : 3
Type                     : Time code
Format                   : QuickTime TC
Duration                 : 1 h 19 min
Frame rate               : 60.000 FPS
Time code of first frame : 01:00:00:00
Time code of last frame  : 02:19:56:07
Time code, stripped      : Yes
Language                 : English
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC

----------------------------- Demux Audio -----------------------------

ffmpeg N-113112-gf5f414d9c4-x64-gcc13.2.0

C:\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i C:\EncodingSSD\TEST.mov -vn -sn -c:a pcm_s16le C:\EncodingSSD\TEST_temp\ID1.wav

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\EncodingSSD\TEST.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    creation_time   : 2024-01-28T16:56:38.000000Z
    encoder         : Blackmagic Design DaVinci Resolve Studio
  Duration: 01:19:56.13, start: 0.000000, bitrate: 442707 kb/s
  Stream #0:0[0x1]: Video: dnxhd (DNXHR HQ) (AVdh / 0x68645641), yuv422p(tv, bt709), 1920x1080, 440401 kb/s, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 15360 tbn (default)
      Metadata:
        creation_time   : 2024-01-28T16:56:38.000000Z
        handler_name    : VideoHandler
        vendor_id       :     
        encoder         : DNxHR HQ
        timecode        : 01:00:00:00
  Stream #0:1[0x2]: Audio: pcm_s24le (lpcm / 0x6D63706C), 48000 Hz, stereo, s32 (24 bit), 2304 kb/s (default)
      Metadata:
        creation_time   : 2024-01-28T16:56:38.000000Z
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74) (default)
      Metadata:
        creation_time   : 2024-01-28T16:56:38.000000Z
        handler_name    : TimeCodeHandler
        timecode        : 01:00:00:00
Stream mapping:
  Stream #0:1 -> #0:0 (pcm_s24le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\EncodingSSD\TEST_temp\ID1.wav':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    ISFT            : Lavf60.20.100
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, stereo, s16, 1536 kb/s (default)
      Metadata:
        creation_time   : 2024-01-28T16:56:38.000000Z
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc60.36.100 pcm_s16le
[out#0/wav @ 0000019eb868e940] video:0kB audio:899275kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000008%

Start:    오전 3:30:56
End:      오전 3:31:06
Duration: 00:00:10

General
Complete name         : C:\EncodingSSD\TEST_temp\ID1.wav
Format                : Wave
Format settings       : PcmWaveformat
File size             : 878 MiB
Duration              : 1 h 19 min
Overall bit rate mode : Constant
Overall bit rate      : 1 536 kb/s
Writing application   : Lavf60.20.100

Audio
Format                : PCM
Format settings       : Little / Signed
Codec ID              : 1
Duration              : 1 h 19 min
Bit rate mode         : Constant
Bit rate              : 1 536 kb/s
Channel(s)            : 2 channels
Sampling rate         : 48.0 kHz
Bit depth             : 16 bits
Stream size           : 878 MiB (100%)

---------------------------- Configuration ----------------------------

Template                : Automatic Workflow
Video Encoder           : NVEnc
Video Encoder Profile   : NVEncC (Nvidia) | AV1
Container/Muxer Profile : ffmpeg | MP4
+++++
Process Priority        : BelowNormal
Delete Temp Files       : Disabled

----------------------- Media Info Source File -----------------------

C:\EncodingSSD\TEST.mov

General
Complete name            : C:\EncodingSSD\TEST.mov
Format                   : MPEG-4
Commercial name          : DNxHR HQ
Format profile           : QuickTime
Codec ID                 : qt   0000.02 (qt  )
File size                : 247 GiB
Duration                 : 1 h 19 min
Overall bit rate         : 443 Mb/s
Frame rate               : 60.000 FPS
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC
Writing application      : Blackmagic Design DaVinci Resolve Studio

Video
ID                       : 1
Format                   : VC-3
Commercial name          : DNxHR HQ
Format version           : Version 3
Format profile           : RI@HQ
Codec ID                 : AVdh
Codec ID/Info            : Avid DNxHR
Duration                 : 1 h 19 min
Bit rate mode            : Constant
Bit rate                 : 440 Mb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 60.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:2
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 3.540
Stream size              : 246 GiB (99%)
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : PCM
Format settings          : Little / Signed
Codec ID                 : lpcm
Duration                 : 1 h 19 min
Bit rate mode            : Constant
Bit rate                 : 2 304 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Bit depth                : 24 bits
Stream size              : 1.29 GiB (0%)
Default                  : Yes
Alternate group          : 1
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC

Other
ID                       : 3
Type                     : Time code
Format                   : QuickTime TC
Duration                 : 1 h 19 min
Frame rate               : 60.000 FPS
Time code of first frame : 01:00:00:00
Time code of last frame  : 02:19:56:07
Time code, stripped      : Yes
Language                 : English
Encoded date             : 2024-01-28 16:56:38 UTC
Tagged date              : 2024-01-28 16:56:38 UTC

------------------------- VapourSynth Script -------------------------

import os, sys
import vapoursynth as vs
core = vs.core

sys.path.append(r"C:\StaxRip\Apps\Plugins\VS\Scripts")
tcFile = r"C:\EncodingSSD\TEST_temp\TEST_timestamps.txt" # timestamps file path
clip = core.ffms2.Source(r"C:\EncodingSSD\TEST.mov", cachefile=r"C:\EncodingSSD\TEST_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"C:\EncodingSSD\TEST.mov", cachefile=r"C:\EncodingSSD\TEST_temp\temp.ffindex")
clip = clip.resize.Bicubic(format = vs.YUV420P8)
clip = clip[131148:131961]
clip.set_output()

------------------------- Source Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 287768
Time      : 01:19:56.133
Framerate : 60 (60/1)
Format    : YUV422P8

------------------------- Target Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 813
Time      : 00:13.550
Framerate : 60 (60/1)
Format    : YUV420P8

---------------------- Media Info Audio Source 1 ----------------------

General
Complete name         : C:\EncodingSSD\TEST_temp\ID1.wav
Format                : Wave
Format settings       : PcmWaveformat
File size             : 878 MiB
Duration              : 1 h 19 min
Overall bit rate mode : Constant
Overall bit rate      : 1 536 kb/s
Writing application   : Lavf60.20.100

Audio
Format                : PCM
Format settings       : Little / Signed
Codec ID              : 1
Duration              : 1 h 19 min
Bit rate mode         : Constant
Bit rate              : 1 536 kb/s
Channel(s)            : 2 channels
Sampling rate         : 48.0 kHz
Bit depth             : 16 bits
Stream size           : 878 MiB (100%)

----------------- Create avi file for audio cutting 1 -----------------

ffmpeg N-113112-gf5f414d9c4-x64-gcc13.2.0

C:\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -f lavfi -i color=c=black:s=16x16:d=4796.133333333:r=60.000000000 -y -hide_banner -c:v ffv1 -g 1 C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.avi

mkvmerge cannot cut audio without video so an avi file has to be created

Input #0, lavfi, from 'color=c=black:s=16x16:d=4796.133333333:r=60.000000000':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 16x16 [SAR 1:1 DAR 1:1], 60 fps, 60 tbr, 60 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> ffv1 (native))
Press [q] to stop, [?] for help
Output #0, avi, to 'C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.avi':
  Metadata:
    ISFT            : Lavf60.20.100
  Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), yuv420p(progressive), 16x16 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 60 fps, 60 tbn
      Metadata:
        encoder         : Lavc60.36.100 ffv1
[out#0/avi @ 000001ff209b2580] video:10679kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 63.210587%

Start:    오전 3:47:37
End:      오전 3:47:44
Duration: 00:00:06

General
Complete name         : C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.avi
Format                : AVI
Format/Info           : Audio Video Interleave
Format settings       : BitmapInfoHeader
File size             : 17.0 MiB
Duration              : 1 h 19 min
Overall bit rate mode : Variable
Overall bit rate      : 29.8 kb/s
Frame rate            : 60.000 FPS
Writing application   : Lavf60.20.100

Video
ID                    : 0
Format                : FFV1
Format version        : Version 0
Codec ID              : FFV1
Duration              : 1 h 19 min
Bit rate mode         : Variable
Bit rate              : 18.2 kb/s
Width                 : 16 pixels
Height                : 16 pixels
Display aspect ratio  : 1.000
Frame rate            : 60.000 FPS
Color space           : YUV
Chroma subsampling    : 4:2:0
Bit depth             : 8 bits
Scan type             : Progressive
Compression mode      : Lossless
Bits/(Pixel*Frame)    : 1.188
Stream size           : 10.4 MiB (61%)
coder_type            : Golomb Rice

----------------------------- Cut Audio 1 -----------------------------

mkvmerge 82.0

C:\StaxRip\Apps\Support\MKVToolNix\mkvmerge.exe -o C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.mkv C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.avi C:\EncodingSSD\TEST_temp\ID1.wav --split parts-frames:131148-131961 --ui-language en

mkvmerge v82.0 ('I'm The President') 64-bit
'C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.avi': Using the demultiplexer for the format 'AVI'.
'C:\EncodingSSD\TEST_temp\ID1.wav': Using the demultiplexer for the format 'WAV'.
'C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.avi' track 0: Using the output module for the format 'VfW compatible video'.
'C:\EncodingSSD\TEST_temp\ID1.wav' track 0: Using the output module for the format 'PCM'.
Timestamp used in split decision: 00:36:25.783000000
The file 'C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.mkv' has been opened for writing.
The cue entries (the index) are being written...
Timestamp used in split decision: 00:36:39.333000000
Multiplexing took 1 second.

Start:    오전 3:47:44
End:      오전 3:47:44
Duration: 00:00:00

General
Complete name           : C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.mkv
Format                  : Matroska
Format version          : Version 4
File size               : 2.55 MiB
Duration                : 13 s 577 ms
Overall bit rate mode   : Variable
Overall bit rate        : 1 574 kb/s
Frame rate              : 60.000 FPS
Encoded date            : 2024-01-28 18:47:44 UTC
Writing application     : mkvmerge v82.0 ('I'm The President') 64-bit
Writing library         : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                      : 1
Format                  : FFV1
Format version          : Version 0
Codec ID                : V_MS/VFW/FOURCC / FFV1
Duration                : 13 s 551 ms
Bit rate mode           : Variable
Bit rate                : 18.2 kb/s
Width                   : 16 pixels
Height                  : 16 pixels
Display aspect ratio    : 1.000
Frame rate mode         : Constant
Frame rate              : 60.000 FPS
Color space             : YUV
Chroma subsampling      : 4:2:0
Bit depth               : 8 bits
Compression mode        : Lossless
Bits/(Pixel*Frame)      : 1.187
Stream size             : 30.2 KiB (1%)
Default                 : Yes
Forced                  : No
coder_type              : Golomb Rice

Audio
ID                      : 2
Format                  : PCM
Format settings         : Little / Signed
Codec ID                : A_PCM/INT/LIT
Duration                : 13 s 560 ms
Bit rate mode           : Constant
Bit rate                : 1 536 kb/s
Channel(s)              : 2 channels
Sampling rate           : 48.0 kHz
Frame rate              : 25.000 FPS (1920 SPF)
Bit depth               : 16 bits
Delay relative to video : 17 ms
Stream size             : 2.48 MiB (97%)
Default                 : Yes
Forced                  : No

------------------------- Demux cutted MKV 1 -------------------------

mkvextract 82.0

C:\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe --ui-language en C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.mkv tracks 1:C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.wav

Extracting track 1 with the CodecID 'A_PCM/INT/LIT' to the file 'C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.wav'. Container format: WAV

Start:    오전 3:47:44
End:      오전 3:47:45
Duration: 00:00:00

General
Complete name         : C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.wav
Format                : Wave
Format settings       : PcmWaveformat
File size             : 2.48 MiB
Duration              : 13 s 560 ms
Overall bit rate mode : Constant
Overall bit rate      : 1 536 kb/s

Audio
Format                : PCM
Format settings       : Little / Signed
Codec ID              : 1
Duration              : 13 s 560 ms
Bit rate mode         : Constant
Bit rate              : 1 536 kb/s
Channel(s)            : 2 channels
Sampling rate         : 48.0 kHz
Bit depth             : 16 bits
Stream size           : 2.48 MiB (100%)

-------------------------- Audio Encoding 1 --------------------------

qaac 2.81

C:\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -i C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.wav -loglevel fatal -hide_banner -f wav - | C:\StaxRip\Apps\Audio\qaac\qaac64.exe --cvbr 192 - -o C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.m4a

qaac 2.81, CoreAudioToolbox 7.10.9.0
ID1_2375604581_cut_.m4a
AAC-LC Encoder, CVBR 192kbps, Quality 96
650880/-1 samples processed in 0:00.172
Overall bitrate: 194.196kbps

Start:    오전 3:47:45
End:      오전 3:47:47
Duration: 00:00:02

General
Complete name         : C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (M4A /mp42/isom)
File size             : 327 KiB
Duration              : 13 s 611 ms
Overall bit rate mode : Variable
Overall bit rate      : 197 kb/s
Encoded date          : 2024-01-28 18:47:47 UTC
Tagged date           : 2024-01-28 18:47:47 UTC
Writing application   : qaac 2.81, CoreAudioToolbox 7.10.9.0, AAC-LC Encoder, CVBR 192kbps, Quality 96
Encoding Params       : (Binary)

Audio
ID                    : 1
Format                : AAC LC
Format/Info           : Advanced Audio Codec Low Complexity
Codec ID              : mp4a-40-2
Duration              : 13 s 611 ms
Bit rate mode         : Variable
Bit rate              : 192 kb/s
Maximum bit rate      : 207 kb/s
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 46.875 FPS (1024 SPF)
Compression mode      : Lossy
Stream size           : 323 KiB (99%)
Encoded date          : 2024-01-28 18:47:47 UTC
Tagged date           : 2024-01-28 18:47:47 UTC

--------------------------- Video encoding ---------------------------

NVEncC 7.41

C:\StaxRip\Apps\Encoders\NVEncC\NVEncC64.exe --qvbr 16 --codec av1 --preset P7 --max-bitrate 10000 --vbv-bufsize 20000 --aq --aq-strength 1 --aq-temporal --lookahead 8 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange limited --cuda-schedule auto -i C:\EncodingSSD\TEST_temp\TEST-muxed.vpy -o C:\EncodingSSD\TEST_temp\TEST-muxed_out.av1

--------------------------------------------------------------------------------
C:\EncodingSSD\TEST_temp\TEST-muxed_out.av1
--------------------------------------------------------------------------------
NVEncC (x64) 7.41 (r2681) by rigaya, Jan 22 2024 13:02:15 (VC 1929/Win)
OS Version     Windows 11 x64 (22631) [UTF-8]
CPU            AMD Ryzen 9 7950X3D 16-Core Processor [5.18GHz] (16C/32T)
GPU            #0: NVIDIA GeForce RTX 4090 (16384 cores, 2520 MHz)[PCIe4x16][551.23]
NVENC / CUDA   NVENC API 12.1, CUDA 12.4, schedule mode: auto
Input Buffers  CUDA, 28 frames
Input Info     VapourSynthMT r65(yv12)->nv12 [AVX2], 1920x1080, 60/1 fps
Vpp Filters    copyHtoD
Output Info    AV1 main @ Level auto
               1920x1080p 1:1 60.000fps (60/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      none
Bitrate        0 kbps (Max: 10000 kbps)
Target Quality 16.00
Initial QP     I:20  P:23  B:25
QP range       I:0-255  P:0-255  B:0-255
QP Offset      cb:0  cr:0
VBV buf size   20000 kbit
Split Enc Mode auto
Lookahead      on, 8 frames, Adaptive I, B Insert
GOP length     600 frames
B frames       3 frames [ref mode: middle]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             on (spatial, temporal, strength 1)
Part size      max auto / min auto
Tile num       columns auto / rows auto
TemporalLayers max 1
Refs           forward auto, backward auto
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,range:limited
Others         mv:auto 
encoded 813 frames, 177.24 fps, 10229.14 kbps, 16.52 MB
encode time 0:00:04, CPU: 0.2, GPU: 92.0, VD: 6.0, GPUClock: 2710MHz, VEClock: 2090MHz
frame type IDR   2
frame type I     2,  total size   0.23 MB
frame type P   203,  total size   0.00 MB
frame type B   608,  total size  16.29 MB

Start:    오전 3:47:47
End:      오전 3:48:01
Duration: 00:00:14

General
Complete name : C:\EncodingSSD\TEST_temp\TEST-muxed_out.av1
File size     : 16.5 MiB

---------------------------- Muxing to MP4 ----------------------------

ffmpeg N-113112-gf5f414d9c4-x64-gcc13.2.0

C:\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i C:\EncodingSSD\TEST_temp\TEST-muxed_out.av1 -i C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.m4a -map 0:v -map 1 -c:v copy -c:a copy -strict -2 C:\EncodingSSD\TEST-muxed.mp4

[libdav1d @ 0000026d4090af40] libdav1d 1.3.0-22-g746ab8b
Input #0, obu, from 'C:\EncodingSSD\TEST_temp\TEST-muxed_out.av1':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: av1 (Main), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1200k tbn
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\EncodingSSD\TEST_temp\ID1_2375604581_cut_.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2024-01-28T18:47:47.000000Z
    encoder         : qaac 2.81, CoreAudioToolbox 7.10.9.0, AAC-LC Encoder, CVBR 192kbps, Quality 96
    Encoding Params : vers
    iTunSMPB        :  00000000 00000840 00000140 000000000009EE80 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
  Duration: 00:00:13.61, start: 0.044000, bitrate: 196 kb/s
  Stream #1:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 194 kb/s (default)
      Metadata:
        creation_time   : 2024-01-28T18:47:47.000000Z
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Output #0, mp4, to 'C:\EncodingSSD\TEST-muxed.mp4':
  Metadata:
    encoder         : Lavf60.20.100
  Stream #0:0: Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1200k tbn
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 194 kb/s (default)
      Metadata:
        creation_time   : 2024-01-28T18:47:47.000000Z
        vendor_id       : [0][0][0][0]
Press [q] to stop, [?] for help
[out#0/mp4 @ 0000026d427f2b00] video:16920kB audio:323kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.053625%

Start:    오전 3:48:01
End:      오전 3:48:01
Duration: 00:00:00

---------------------------- Job Complete ----------------------------

Start:    오전 3:47:37
End:      오전 3:48:01
Duration: 00:00:24


source 60 fps 

but av1 encoding result 25 fps

**Comment by Dendraspis** [comment]
Can you try to mux the files into an `MKV` container instead of `MP4` ?
Just to see if that works, because everything looks good except the `MP4` mux.

**Comment by DandyClubs** [comment]
mkv is work...

maybe mp4box 60fps to 25fps 

so slow motion

**Comment by DandyClubs** [comment]
mkv is work...

maybe mp4box 60fps to 25fps 

so slow motion

**Comment by Dendraspis** [comment]
The problem is that `ffmpeg` is used and it interprets the AV1 file with `25fps`  😕
I don't know why, should be a tool issue and probably fixed with one of the next versions.
