### ISSUE TITLE
Bug with audio cutting when preview window opened from Edit code window 

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#121]
Hi Stax, Patman, All Contributors,
This is an old bug, and took time for me to find how to reproduce it. It created files where video is cutted properly while audio is not cutted:

1. open a mp4 file (with no chapters because the txt chapter bug is still there!), one video stream, one audio stream.
2. set compression for video and audio as you wish (i used x265, aac auto encoder select)
3. open the preview, select a small range in the middle so we don't waste time encoding, close preview
4. open the Edit Code window
5. from the Edit Code window, open the Preview window, close it
6. Press OK in the Edit Code window, and immediately press next to save the job, and launch the job.

The resulting file will have video cutted to the desired range, but full audio, not cutted to the desired range.

**Comment by Patman86** [comment]
Have you tested the procedure with other fileformats?
What's your final file format? mkv, mp4 etc.?

**Comment by 44vince44** [comment]
It's mkv.
The bug only happens when the LAST preview window that you have opened, has been opened from inside the Edit Code Window, by pressing F5. (step 5).
If after step 5, you open a preview window from the main window and close it, and you create the job and execute it, the resulting video and audio streams will be cutted accordingly.

**Comment by stax76** [comment]
I've committed a fix now and upload a build tomorrow.

**Comment by 44vince44** [comment]
Thanks Stax, I'll test as soon as I see the new build in your folder!

**Comment by stax76** [comment]
Hello Vince, I've uploaded the new build.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS
