### ISSUE TITLE
StaxRip extract DV RPU.bin of UHD on main video stream

### ISSUE THREAD

**Issue by Morku** [staxrip/staxrip#1210]
**Describe the bug**
When extract a Blu-ray folder, Staxrip tries to extract RPU.bin on the first videostream, even if no DV exist on the Disc.

![Screenshot 2024-01-30 131632](https://github.com/staxrip/staxrip/assets/6276915/064cc5d7-db47-4a6d-95aa-93fb55a66c45)

Without surprise, the RPU.bin is empty

![grafik](https://github.com/staxrip/staxrip/assets/6276915/8e712f8b-0a0b-41a3-80d6-5ea3c5da583c)

At least, no RPU.bin was loaded into the Bitstream. However, this is a waste of time and ressources.

**Expected behavior**

When select a Blu-ray folder to start for extraction, there should no automation to extract the RPU.bin on the main movie stream.
Instead, when extract a Blu-ray, always extract the second Videostream as well -> perform dovi tool extraction here

If Staxrip is unable to find a second video stream (like the example above) -> there is no DV information to extract, skip it

**How to reproduce the issue**

1. Click Source, Open, Blu-ray Folder (in my case an UHD with HDR10+, but no DV)
2. Select Playlist
3. Extract Movie and stuff with eac3to
4. Extraction starts fine, then hdr10+.json extracts
5. Suddenly the extraction of dovi tool starts on the extracted first video

An UHD Blu-ray movie never ever has DV information in the main movie stream (not so far I have seen). It is always used as a second video stream like this:

![grafik](https://github.com/staxrip/staxrip/assets/6276915/a720eb7f-9022-4952-a318-a10c7be752f8)

**Provide information**

StaxRip 2.34

**Comment by Dendraspis** [comment]
Will be fixed in the next release.
