### ISSUE TITLE
Overriding profile on DolbyVision extraction

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1212]
Hello,

why does dolbyvision profile 5 is changed to profile 8 during extraction?

i would like to be asked what would like to do with it, or leave it like it is from source...

**Comment by Dendraspis** [comment]
As far as I know `Dolby Vision Profile 8.1` is the only one, that works inside containers or MKV.

Even if you select `Untouched` for the RPU metadata file, the encoder setting is set to `--dolby-vision-profile 8.4`, which of course is going to change the preset value.  🤔   I will change that at least for `Untouched` for a future release...

**Comment by madey83** [comment]
i use profile 5 in mp4 container for my LG oled TV.
if my source movie does not have HDR and it has only DoVi profile 5 what is the reason to convert to 8.1...?

**Comment by Dendraspis** [comment]
Like I said, as far as I know profile `8.1` is the only one that is really supported in mp4/mkv. But if you want to use `5` it's okay. I have already changed the handling so that `Untouched` won't overwrite the setting anymore.
