### ISSUE TITLE
Extract Dolby Vision, Version 1.0, dvhe.08.06 RPU

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1214]
**Is your feature request related to a problem? Please describe.**
There are a lot of Hybrid Remuxes with 
`Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible`
Currently, StaxRip doesn't extract RPU from them.

**Describe the solution you'd like**
RPU should be extracted from Hybrid Remuxes

**Explain why the feature matters to you**
I wish to do DV encodes from such sources without using other tools to extract RPU

**Additional context**
Maybe I'm wrong and there is way to do that. But I have tried different options for RPU Conversion Mode and neither seems to helps

**Comment by IevgenSobko** [comment]
Encoding by default involves cropping so yes.
I have seen some issue was opened for 2.33 and there were some changes regarding DV extraction cropping in 2.34.

**Comment by Dendraspis** [comment]
Yeah, but `v2.35` fixes even more issues ... and it's out now.  😅 
I advice you to read the release notes and changelog.

So I close this one. If you still have issues with your extractions, feel free to re-open it.
