### ISSUE TITLE
black backgrounds always become gray with this filter.  All else color clarity etc improves while black backgrounds get hammered.

### ISSUE THREAD

**Issue by chowderhead** [staxrip/staxrip#1216]
This is an issue with the AI part of the filter that Nvidia needs to be aware of.
They need to retrain the AI about black backgrounds I guess.  

I've successfully used nvvfx-superres on 100 files that don't have black backgrounds but the other 150GB of this project is all drawn as interstellar battles in deep dark recesses of NOT BLACK - GRAY outer space.  (at least with this plugin outer space is gray.

Comments??? See photo tells everythig.  Ive produced same effect on 10 seperate files.  Tried to override it with other extensins and scripts.  not happeing.  GRAY OUTER SPACE .  ALL OF THEM.

![blacksbackgroundissue](https://github.com/staxrip/staxrip/assets/22981743/9ab4f3ee-74f7-444f-b173-0f03b9c03849)

Randy

Not complaining.  Just passing along important info thru the only channel I've successfully used t solve some problems.

**Comment by chowderhead** [comment]
Ive tested this up sideways and down the AI doesnt like large black backgrounds.  I made a film of 10 seconds of black and the ai turned it gray.  But still AMAZING improvements in colors and detail.  so for now Im just avoiding videos with lots of dark backgrounds until I can examine this further and maybe NVIDIA can come out with version 2.0 or whatever number comes next.

**Comment by Dendraspis** [comment]
This is, again, the issue tracker of StaxRip.
If you want to share (useful) information, please do so in a forum of your choice, but not here.

> This is an issue with the AI part of the filter that Nvidia needs to be aware of.
They need to retrain the AI about black backgrounds I guess.

Then head over to www.nvidia.com and tell them.
But I guess this is caused because you use `--colorrange full` on a source with limited color range.

Nevertheless I will close this here.
