### ISSUE TITLE
muvsfunc.DisplayHistogram need libhistogram.dll

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#1218]
https://github.com/dubhater/vapoursynth-histogram

download v2 and extra to C:\StaxRip\Apps\Plugins\VS\Histogram\

i test 

core.std.LoadPlugin(r"C:\StaxRip\Apps\Plugins\VS\Histogram\libhistogram.dll", altsearchpath=True)
clip = muvsfunc.DisplayHistogram(clip)

DisplayHistogram is fine work.

**Comment by Dendraspis** [comment]
Duplicate to: #1202 

Thanks for the info, I have already added `libhistogram`, so with the next release it will be included.
