### ISSUE TITLE
Bug with txt files still there

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#122]
The path to the text file is not *.txt, but *.log !!!! See image and error report below please:
![SNAG-0005](https://user-images.githubusercontent.com/17828567/76065428-58553880-5f94-11ea-80b5-c40eeca619e2.jpg)

Link to the [small video](http://zafer.kantar.free.fr/TEST_of_failing_txtchapters_files.mp4)

-----------------------------------------------------------------------------------------------------
Error Muxing using mkvmerge 43.0.0 (2.0.7.4)

Muxing using mkvmerge 43.0.0 failed with exit code: 2 (0x2)

The exit code might be a system error code: STATUS_WAIT_2

The exit code might be a system error code: The system cannot find the file specified.

--------------------- Muxing using mkvmerge 43.0.0 ---------------------

"D:\Downloads\_IDM Downloads\StaxRip-x64-2.0.7.4-beta\Apps\Support\MKVToolNix\mkvmerge.exe" -o D:\Desktop\reproo\TEST_of_failing_txtchapters_files.mkv D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files_out.hevc --no-chapters --audio-tracks 0 --language 0:eng --track-name "0:IsoMedia File Produced by Google, 5-11-2011" --default-track 0:0 --forced-track 0:0 "D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files ID1 {IsoMedia File Produced by Google, 5-11-2011}_a1.m4a" --no-audio --no-video --no-chapters --no-attachments --no-track-tags --no-global-tags --subtitle-tracks 2 --forced-track 2:0 --default-track 2:0 --language 2:und --track-name "2:" D:\Desktop\reproo\TEST_of_failing_txtchapters_files.mp4 --chapters D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files_staxrip.log --ui-language en

mkvmerge v43.0.0 ('The Quartermaster') 64-bit
Error: Unknown chapter file format in 'D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files_staxrip.log'. It does not contain a supported chapter format.

StaxRip.ErrorAbortException: Muxing using mkvmerge 43.0.0 failed with exit code: 2 (0x2)

The exit code might be a system error code: STATUS_WAIT_2

The exit code might be a system error code: The system cannot find the file specified.

--------------------- Muxing using mkvmerge 43.0.0 ---------------------

"D:\Downloads\_IDM Downloads\StaxRip-x64-2.0.7.4-beta\Apps\Support\MKVToolNix\mkvmerge.exe" -o D:\Desktop\reproo\TEST_of_failing_txtchapters_files.mkv D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files_out.hevc --no-chapters --audio-tracks 0 --language 0:eng --track-name "0:IsoMedia File Produced by Google, 5-11-2011" --default-track 0:0 --forced-track 0:0 "D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files ID1 {IsoMedia File Produced by Google, 5-11-2011}_a1.m4a" --no-audio --no-video --no-chapters --no-attachments --no-track-tags --no-global-tags --subtitle-tracks 2 --forced-track 2:0 --default-track 2:0 --language 2:und --track-name "2:" D:\Desktop\reproo\TEST_of_failing_txtchapters_files.mp4 --chapters D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files_staxrip.log --ui-language en

mkvmerge v43.0.0 ('The Quartermaster') 64-bit
Error: Unknown chapter file format in 'D:\Desktop\reproo\TEST_of_failing_txtchapters_files_temp\TEST_of_failing_txtchapters_files_staxrip.log'. It does not contain a supported chapter format.

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 342
   at StaxRip.MkvMuxer.Mux() in D:\Projekte\VB\staxrip\General\Muxer.vb:line 558
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 136

**Comment by stax76** [comment]
Did you open this file manually or was it detected by staxrip?

**Comment by stax76** [comment]
Next build will only detect txt and xml containing 'chapters'.

**Comment by 44vince44** [comment]
Mediainfo says it is a timed text format. Isn't that the same as txt ?


Text
--
ID : | 3
Format : | Timed Text
Codec ID : | text
Duration : | 1 s 0 ms
Bit rate : | 184 b/s
Stream size : | 23.0 Bytes (0%)
Default : | No
Forced : | No
Encoded date : | UTC 2018-08-31 04:06:09
Tagged date : | UTC 2020-03-05 07:43:36

**Comment by 44vince44** [comment]
Thank you, this has been fixed indeed in 2.0.7.5
