### ISSUE TITLE
VCEEncC x.265 combined QP setting has no effect

### ISSUE THREAD

**Issue by MrExplode** [staxrip/staxrip#1222]
**Describe the bug**
The VCEEnc x.265 QP field is not changing the command line value when used in combined mode. If the `Show advanced QP settings` field is selected, the individual `I`, `P`, `B` fields correctly modify the command line.

**Expected behavior**
When the `Show advanced QP settings` is not selected, the command line should use the `--cqp <int>` format instead of the advanced `--cqp <int>:<int>:<int>` formatting.

**How to reproduce the issue**

- Select VCEEncC with x.265
- Open `Encoding Options`
- Navigate to the `Basic` tab
- Try to change the QP field

**Used StaxRip version**
`v2.35.0`

**Comment by Dendraspis** [comment]
Yeah, definitely missed to set it when I changed the other two modes.  🙄 

Thanks for the report. It will be fixed in the next version.
