### ISSUE TITLE
Extracted DV is not cropped when it needs to be

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1223]
**Describe the bug**
First of all I started with completely new setting for 2.35.0 as was mentioned in release notes.
Configured `Auto Crop` after opening to be `Always`.
To not touch default `x265` profile I have custom `x256` profile saved with with name like `x265-TaurohtaR`. The same applies to Autoloading project template with some custom filters.
When I open Remux with DV I see DV RPU is extracted without crop command line parameter
```
C:\ToolS\StaxRip-v2.35.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -hide_banner -probesize 20M -i "Z:\RippinG\World.War.Z.2013.BDRemux.2160p.DV.HDR-UTOPIA.mkv" -an -sn -dn -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | C:\ToolS\StaxRip-v2.35.0-x64\Apps\Support\DoVi_Tool\dovi_tool.exe -m 2 extract-rpu - -o "C:\RippinG\World.War.Z.2013.BDRemux.2160p.DV.HDR-UTOPIA_temp\HDRDVmetadata.rpu"
```
Then when I start encoding there is some incentive to get croped RPU but log shows that JSON config has `0` values set to all of parameters:
```
C:\ToolS\StaxRip-v2.35.0-x64\Apps\Support\DoVi_Tool\dovi_tool.exe editor -i "C:\RippinG\World.War.Z.2013.BDRemux.2160p.DV.HDR-UTOPIA_temp\HDRDVmetadata.rpu" -j "C:\RippinG\World.War.Z.2013.BDRemux.2160p.DV.HDR-UTOPIA_temp\HDRDVmetadata_Config.json" -o "C:\RippinG\World.War.Z.2013.BDRemux.2160p.DV.HDR-UTOPIA_temp\HDRDVmetadata_Cropped.rpu"

EditConfig {
  "mode": 0,
  "remove_cmv4": false,
  "remove_mapping": false,
  "active_area": {
    "crop": false,
    "presets": [
      {
        "id": 0,
        "left": 0,
        "right": 0,
        "top": 0,
        "bottom": 0
      }
    ],
    "edits": {
      "0-166796": 0
    }
  }
}
```

The same behavior on 3 of my encoding machines.
I also attached log files for you to look into.

[2024-02-05 - 21.25.39 - World.War.Z.2013.1080p.UHD.BluRay.DD+.7.1.DV.HDR.x265-TaurohtaR_staxrip.log](https://github.com/staxrip/staxrip/files/14208030/2024-02-05.-.21.25.39.-.World.War.Z.2013.1080p.UHD.BluRay.DD%2B.7.1.DV.HDR.x265-TaurohtaR_staxrip.log)
[Jerry.Maguire.1996.1080p.UHD.BluRay.DD+.7.1.DV.HDR.x265-TaurohtaR_staxrip.log](https://github.com/staxrip/staxrip/files/14207903/Jerry.Maguire.1996.1080p.UHD.BluRay.DD%2B.7.1.DV.HDR.x265-TaurohtaR_staxrip.log)

**Comment by Dendraspis** [comment]
I have checked both log files and as far as I can see all looks good and as intended.  👍

**Comment by IevgenSobko** [comment]
After some digging around now I see how it works.
First, full RPU is extracted.
Then L5 extraction to see crop values and length of DV stream.
And finally before encode there is another edit that sets crops to 0(actually there is some math behind this I guess you comparing autocrop values with L5 and do some calculation so it is not always 0) meaning crop was made.

**Comment by Dendraspis** [comment]
In addition I started overhauling the [guide](https://github.com/staxrip/staxrip/wiki/Home#guides) about handling sources with Dolby Vision metadata. In case you want to check it out:
[Encoding Dolby Vision with StaxRip using x265, NVEncC, QSVEncC, VCEEncC](https://github.com/staxrip/staxrip/wiki/Encoding-Dolby-Vision-with-StaxRip-using-x265%2C-NVEncC%2C-QSVEncC%2C-VCEEncC)

The *Cropping* section will be continued soon...
