### ISSUE TITLE
Dolby Vision Crop - auto filling non-Mod 2 numbers - Crop: YUV must be Mod 2

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1224]
v.2.35
Why does StaxRip auto fill with non-Mod 2 numbers if the Crop function requires Mod 2 numbers? Are there circumstances where non-Mod 2 numbers can be used in cropping?

**Describe the bug**
Auto Crop after opening: "Always" setting auto filling non-Mod 2 - Crop: YUV must be Mod 2.

**Expected behavior**

**If a MOD 2 number is always REQUIRED by the crop function, StaxRip should automatically prevent (in any circumstance) non-Mod 2 numbers from being filled irregardless of Auto correct crop value settings - this Auto correct should be executed by default.** This includes the Dolby auto and the Crop menu visual crop function, which should only select Mod 2 values when moving sliders and when executing auto cropping. This should be done without other user intervention (such as failing to check Auto correct).

**How to reproduce the issue**

Set Auto Crop after opening to Always.
Do not set Auto correct crop values.
Load Dolby Vision video (Mediainfo attached) that needs cropping.

**Provide information**

Script Error (Main user interface)
Crop: YUV image can only be cropped by Mod 2 (top).

[CropProblem.txt](https://github.com/staxrip/staxrip/files/14214642/CropProblem.txt)

**Comment by Dendraspis** [comment]
`Auto correct crop values` is enabled by default which prevents such issues.
If you want it always to be `mod 2`, so why do you disable this feature?  

Honestly, I don't get it. It's like turning the *Auto Rotate* feature off to complain, that nobody needs videos with wrong orientation and *Auto Rotate* should always be applied.

**Comment by noblemd00** [comment]
Logically, why even have the Auto crop switch IF A MOD 2 NUMBER IS ALWAYS REQUIRED. StaxRip should use the proper setting to prevent the user receiving an ERROR message or having improper crop values filled.

StaxRip = calculates Crop not equal to Mod 2 = ERROR, ERROR, ERROR = UNNECESSARY

StaxRip = calculates Crop = Mod 2 = GOOD = NO ERROR

Its like your car mechanic disconnecting the battery then telling you your car won't start because you did not connect the battery.

The battery ALWAYS needs to be connected! Why is it disconnected?

Why force the user to set an Auto Crop switch when Auto cropping is ALWAYS REQUIRED? The Auto crop setting is superfluous.

**Comment by noblemd00** [comment]
Logically, why even have the Auto correct crop value switch IF A MOD 2 NUMBER IS ALWAYS REQUIRED. StaxRip should use the proper value to prevent the user receiving an ERROR message or having improper crop values filled.

Its like installing a light switch in your house that if turned off, it may explode a bomb. Why install such a switch?

StaxRip = (unselected option) calculates Crop not equal to Mod 2 = ERROR, ERROR, ERROR = UNNECESSARY

StaxRip = (auto corrects) Crop (all the time) = Mod 2 = GOOD = NO ERROR

Why have an Auto correct Crop value switch when a proper Auto correct cropping value is ALWAYS REQUIRED? The Auto correct crop selection setting is superfluous - should be on all the time.

Yes, I know the switch is on by default - BUT - Why allow a user to create a situation where an error could occur - if the Mod 2 value is ALWAYS required, do not allow the user to change an item that will create an error. Proper programming prevents the possibility of user errors.

**Comment by Dendraspis** [comment]
You have a pretty annoying opinion about what StaxRip should do....

> Its like installing a light switch in your house that if turned off, it may explode a bomb.

There is no bomb that explodes. You get a message, that the number of turned off lights does not match your settings/expectations, so you can adjust/fix that.
At first you should make sure, that what you do is correct. On top of that there are some features that can help you and the Assistant, that warns you at last.

> Why install such a switch?

Because you can turn off that particular light ?!

> StaxRip = (unselected option) calculates Crop not equal to Mod 2 = ERROR, ERROR, ERROR = UNNECESSARY
> StaxRip = (auto corrects) Crop (all the time) = Mod 2 = GOOD = NO ERROR

What makes you believe, that there are no circumstances that allow odd crop values?

> Why have an Auto correct Crop value switch when a proper Auto correct cropping value is ALWAYS REQUIRED?

Because it depends on the source, filters and settings.
Better question:  Why do you turn it off when you want it to be enabled?

> The Auto correct crop selection setting is superfluous - should be on all the time.

Therefore it is enabled by default. 

> if the Mod 2 value is ALWAYS required

That's the point:  It is not.

> Proper programming prevents the possibility of user errors.

Indeed, but the definition of *proper* is a bit wanky when it comes to hundreds of use cases, video formats, limitations, exceptions, ...

> At the very least there should be a warning when the Auto correct crop value is unselected - Warning: unselecting may cause Crop to calculate incorrect values!

As stated in the *README*, StaxRip has a lot to offer, but it is designed to be your tool, not vice versa.  When you disable a feature, you should know what you do. You also don't get a warning when you select a high CRF value for the encoder, that the result may look a bit clonky.
Harming users who know what they to cannot be the solution. 

At first the feature is there because it helps most users. Therefore it is enabled by default. To let the users decide, if they want to use it or not, it is possible to disable it.

**Comment by noblemd00** [comment]
> What makes you believe, that there are no circumstances that allow odd crop values?

My original question:
>Are there circumstances where non-Mod 2 numbers can be used in cropping?

Mod 2 numbers are always even numbers (re: Benoit Mandelbrot) 

This is the right click item (help) message (see my original question-above):
<img width="283" alt="240212 173836" src="https://github.com/staxrip/staxrip/assets/16325865/62e59ad2-d172-4830-82bb-aede906374e6">


I have tried every value of the Options/Image/Output Mod value (2, 4, 8, 16) and the Error message persists (or does the "forced output mod value" refer to something else?):
<img width="339" alt="240212 152156" src="https://github.com/staxrip/staxrip/assets/16325865/7d61d635-4a01-4654-b1f9-b8bad64df556">


1. If you'll read my original post you'll see I specifically ask that question as part of the first paragraph. "Why" and "Are there circumstances"

> Why does StaxRip auto fill with non-Mod 2 numbers if the Crop function requires Mod 2 numbers?  Are there circumstances where non-Mod 2 numbers can be used in cropping?

AND... (note the "IF" at the beginning)

> If a MOD 2 number is always REQUIRED by the crop function, StaxRip should automatically prevent (in any circumstance) non-Mod 2 numbers from being filled irregardless of Auto correct crop value settings - this Auto correct should be executed by default. This includes the Dolby auto and the Crop menu visual crop function, which should only select Mod 2 values when moving sliders and when executing auto cropping. This should be done without other user intervention (such as failing to check Auto correct).

2. I was trying to illicit a reason for the existence of the Auto correct crop switch. Only after I asked those questions did I put forward my reasons for wondering about the Auto correct crop setting. 
 
3. If StaxRip can determine there is an error with the crop number, then wouldn't it be better for StaxRip to correct the value (add or subtract 1) and notify the user of the value change? 

----------------------------------
> Better question: Why do you turn it off when you want it to be enabled? 

Better Question yet: Why can it be turned off when it should always be enabled? (if true - the gist of my original inquiry - and still not answered).

StaxRip should auto correct improper values automatically? (Auto crop after opening, Auto crop boarders until proper aspect ratio is found, and Crop menu Auto crop - all should result with proper corrected values).


Auto crop screen with non Mod 2 (ODD) result:
<img width="474" alt="240212 144641" src="https://github.com/staxrip/staxrip/assets/16325865/8e18a6c7-7eec-4d51-8b59-6c901012e05e">
----------------------------------
The proper (and need I say it polite) way to answer my original inquiry would have been to explain (if true) that non-Mod 2 numbers can be used in some circumstances, SUCH AS... (I still don't know if this is true - never answered).

If you read my original question it was presented in a very polite manner answering the form questions.
1. the question - my inquiry - Description
2. Expected behavior - why I was inquiring
3. What caused the issue
Not in any way shape or form confrontational or argumentative - simply answering the form questions.

I did not ridicule you or the StaxRip program - I inquired about what I thought was an issue - an unneeded Auto correct crop checkbox - an item that should always be enabled and should not be capable of being disabled because, disablement results in an error. 

Please note: I think StaxRip is a great program - my only purpose for inquiries and feature requests is to improve the program.

Your response to my original inquiry:
> Auto correct crop values is enabled by default which prevents such issues.
If you want it always to be mod 2, so why do you disable this feature?

> Honestly, I don't get it. It's like turning the Auto Rotate feature off to complain, that nobody needs videos with wrong orientation and Auto Rotate should always be applied.
