### ISSUE TITLE
Version 2.35 crashes

### ISSUE THREAD

**Issue by Victory61** [staxrip/staxrip#1225]
Good morning.
In my configuration with version 2.35 it happened to me 2 times with the x265 encodind during processing crashes.
Also since I set the pc has work at night, I always select the hibernate command for the end of the processes, well even in this case I end up the next morning with a warning message that the processing is terminated at 98.5% and that some frames have not been processed.
Which in the previous version never happened to me, the operating system and the various software did not change.
Today I downgraded to version 2.34 and so far everything is running smoothly
I can't give an explanation and I have no idea why this is happening, this is the first time it has happened with the latest release.

**Comment by Dendraspis** [comment]
Interestingly there were absolutely no changes made in `v2.35` that could explain that. Demuxers, encoders, muxers, all the same.

A log file would be nice to see if there is something that could help identifying the issue.

**Comment by Victory61** [comment]
You are right it is happening even with version 2.34. I don't understand what is happening.
The ..staxrip.log file how lop I attach it?

**Comment by Dendraspis** [comment]
Let's see if the log file can help us a bit...

> how lop I attach it?

Maybe this could help:  😅 
![image](https://github.com/staxrip/staxrip/assets/50659978/35fe62d8-7e6a-404f-8a70-26d0986915ae)

**Comment by Victory61** [comment]
CIao I attach the file of my x265 encoding process, with my Ryzen 9 7950x processor I use 3 Chunks.
[Indy 5 Regrade_staxrip.log](https://github.com/staxrip/staxrip/files/14224044/Indy.5.Regrade_staxrip.log)

**Comment by Dendraspis** [comment]
Are you using the `x265.exe` that is delivered with StaxRip or did you replace it?

**Comment by Victory61** [comment]
I use the version contained in StaxRip "3.5+153+15-813ccbff0-.Mod-by-Patman.-x64-avx2-msvc1937"

**Comment by Victory61** [comment]
I restored the operating system image and installed version 2.35 again and started a new encoding process let it go overnight, and entered the "Hibernate" command for the end of the process.
Let's see what happens tomorrow.

**Comment by Dendraspis** [comment]
You use `--asm avx512` with a `x265.exe` version, that is just build for `AVX2`. That could be the culprit.

So you could try to remove this parameter or you can try another build from here: https://github.com/Patman86/x265-Mod-by-Patman/releases/tag/3.5%2B153%2B15

Regarding your `Hibernate`  command:
The error message seems to prevent the system from hibernating, so if you want to turn off your PC, you could also disable the error message in `Options`, so there will be just a warning in the log file.

**Comment by Victory61** [comment]
Thank you very much for the advice.
Although I find it very strange that this problem has emerged only a few days ago, and I have never deselected the AVX512 parameter and have always used the x265 encoder embedded in StaxRip.

**Comment by Dendraspis** [comment]
If your CPU supports `AVX512` then you should at least try it out. There should also be a very small speed up of about 1-3%.

Nevertheless it would be interesting if that replacing or the removing of `--asm avx512` solves your issues.

In case it worked for a longer time period and now starts to make issues, I suggest checking your hardware. 
Maybe one or more fans and/or your CPU cooler is/are cloaked up and can't provide the little amount of air your CPU needs for the hard job. Especially when the problem occurs always after/at different times/progresses. 
There are many reasons possible. But when you run one encode multiple times and it stops always at different frames, it's probably a hardware issue.

**Comment by Victory61** [comment]
Hello.
In StaxRip I left the selection on avx512 and replaced the default installed .exe encoder with "3.5+153+15-813ccbff0-.Mod-by-Patman.-x64-avx512-msvc1937" and set the hibernate command as I often do overnight.
You were right about the advice you gave me and I thank you. 
In fact for the same file it was faster, about 2% and completed without any problem. 
At this point I don't know if I should uncheck avx512 and leave the encoder by Patman avx2
I will do more processing to test the stability, however I use a CPU cooler with ARCTIC Liquid Freezer II 280 A-RGB

**Comment by Dendraspis** [comment]
> I left the selection on avx512 and replaced the default installed .exe encoder with "3.5+153+15-813ccbff0-.Mod-by-Patman.-x64-avx512-msvc1937"

This would be my solution No. 1.  😅 

> In fact for the same file it was faster, about 2% and completed without any problem.

So I guess the issue was the combination you had before. So that means for the next releases you give up the `AVX512` advantage or you have to (download and) replace the encoder with every StaxRip version you download. It's up to you, the important part is that your encodes finish without issues.

> however I use a CPU cooler with ARCTIC Liquid Freezer II 280 A-RGB

And it seems to do a good job. Just thought because of the report, that it could be cloaked up, but that does not seem to be the case.

So I guess we can close this....

**Comment by Victory61** [comment]
yes. I thank you for your help, however I still reserve the right to perform a test with the default encoder (avx2) by deselecting from the settiung avx521 (solution2).
