### ISSUE TITLE
indexing progress for video comparison window

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#1226]
currently when loading videos into the video comparison window, the window freezes while video indexing takes place. this probably isn't a problem for small videos, but if you have large files it can take a very long time to index these, during which we just have a frozen window with no idea of how long this will take. some kind of progress indicator instead of simply letting the window freeze would be nice here, like we get in the regular encode windows

**Comment by Victory61** [comment]
This would be very helpful, so as not to incur the misinterpretation of crashes.
Thank you

**Comment by Dendraspis** [comment]
Took me a while, but it should be available with the next main release `v2.40`. Hope my testing was enough...
