### ISSUE TITLE
Let Staxrip see that a *.MKS is an regular subtitle file.

### ISSUE THREAD

**Issue by AdPatat** [staxrip/staxrip#1227]
As the title says it all, there is not much to say here.
The \*.mks subtitle files are a part of my DVB recordings.
Fore now I can add them by clicking "add" and then "all files (\*.\*)" in the container configuration, so its not a "big issue".

P.S. \*.mks is a picture based subtitle file...

Thanks for your attention.

**Comment by Dendraspis** [comment]
Funny, that it wasn't there yet.  🥴 

I added it to the valid subtitle file types and you should be able to select it directly with the next version.
