### ISSUE TITLE
Request a "Project Load as Startup" or "Template Load as Startup" Menu item

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1229]
**Is your feature request related to a problem? Please describe.**
See issue  https://github.com/staxrip/staxrip/issues/1228

**Describe the solution you'd like**
Add a button that allows quick and easily loading a Project template as the Startup template

**Describe alternatives you've considered**
See issue [1228](https://github.com/staxrip/staxrip/issues/1228) - still needed - would keep from having to constantly load template as startup for re-encoding multiple files

**Explain why the feature matters to you**
Currently, to set a Template as the Startup template numerous multiple steps are needed
1. Click the File menu
2. Select the Project template menu item
3. Select/Load the template
4. Click the File menu
5. Click the Save Project as template menu item
6. Click the Load Template as startup
7. Click the OK button

or...

1. Click the Tools menu 
2. Click Settings menu item
3. Click the Startup Template dropdown
4. Select/Click the Project template
5. Click the OK button
6. Click the File menu
7. Select the Project template menu item
9. Select/Load the template

With a USER FRIENDLY "Project Templates Load as Startup" menu item the steps are significantly simplified...

1. Click the File menu
2. Select the "Project Load as Startup" (or "Template Load as Startup") menu item
3. Select/Load the template

**_THREE steps versus SEVEN or EIGHT steps._**

**Comment by Dendraspis** [comment]
`v2.38.x` will have an extension where the new selected Startup Template is loaded after closing the Settings.
