### ISSUE TITLE
small preview issue with MPV preview when cutting range(s) selected

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#123]
Hi Stax, thanks for this beta 2.0.7.5, this is the first results of testing:

1) cutting work very well now, the previous cutting issue is **fixed** ! Video and audio are cutted 
 accordingly now, even if preview window is opened from the Edit code window. Thanks !

2) new feature of mpv preview, the preview plays from the exact current cursor position of the F5 preview: this is very useful and highly appreciated and works well when no cutting range selected. Thousand thanks!

3) small issue when a cutting range is selected with mpv preview:

- 1. Open a source video, open preview (F5).
- 2. Select a small cutting range in the middle of the timeline
- 3. Press F9 from INSIDE the preview window. MPV starts up. **Problem:** the playback position is out of range, so all you see is black, and if you want to see the actual range, you have to seek back.

This happens when:
  Main Window -> F5 preview -> select (small) range -> Press F9
or
  Edit Code Window -> F5 preview -> select (small) range -> Press F9 

Again, many thanks, I'll be testing on several videos this evening and tomorrow, and I'll post anything I find.

**Comment by 44vince44** [comment]
Actually this is a very silly bug, here is a clearer explanation:

When you select a range from preview window, and press F9 to open mpv.net, mpv.net will start playing at an out-of-range position, giving you an all black image.

This is because the cursor in the preview window is set exactly at the end of the range.

Workaround:
Select a range, then just move the cursor to anywhere, and press F9, then mpv.net will show you the video from a position inside the range.

**Comment by stax76** [comment]
Unfortunately I'm not able to reproduce it, maybe it's a rounding error. I tried with only one section like you write but also with two sections at section1start, section1end and section2start. How many sections are there? On which section is the current position and where exactly at the section, start or end?

You write **a** range which is one, in that case if the current position is at the start of the section mpv received pos 0, if you are at the end of the section you are at the end and mpv received that.

**Comment by 44vince44** [comment]
Hi Stax, that's exactly what happens : when you are at the exact end of the range, mpv receives the position of the end of the range,  so it must receive the last frame of the range, and show it still while it continues playback (it continues because the audio now is longer than video, which is normal). But the problem is that it does not show the last frame of the range, it shows black.

I made a screen capture with a sample video. The capture can be seen [HERE](http://zafer.kantar.free.fr/screencaptvid.mkv). (small 640 k file).
In this example, I open a timecode video (each frame shows time index), I select a range. The last frame of selection shows 00:00:22:02. When I press F9, I have a black video. But I should see the last frame playing still.

**Comment by stax76** [comment]
I've changed it to add audio only if there are null sections, then in my test with my mpv settings the last frame is shown.

**Comment by 44vince44** [comment]
Stax, I am testing with the 2.0.8.0 release, untouched, unmodified, I just extract it to a new folder, ask to set settings folder inside this new folder, so I have a fresh setup, no mods, no personal settings.

The problem is still there when cursor is at the end of range, but now mpv just shows nothing (logo).
[screencap2080.zip](https://github.com/staxrip/staxrip/files/4332374/screencap2080.zip)

I think I know what's happening:
When you select a range, let's say begin position of cursor is "b", end position of cursor is "e".
The actual range that will be processed is (b ; e-1)
The trim function parameters will be Trim( b , e-1 ).
When cursor is at end of range position, cursor position is "e". When you send position to mpv, it should be treated as what you send when cursor is out of the range.

**Comment by 44vince44** [comment]
Line 1132 of PreviewForm.vb:

                    If current.End < Renderer.Position

Shouldn't it be 

                    If current.End **<=** Renderer.Position
??

**Comment by 44vince44** [comment]
@Patman86, Thank you for compiling and sharing the test build. Here is what I get with this fix:

**Before fix:**
- no range selected => no problem
- one range selected => problem if cursor is at end of range, otherwise no problem
- two or more ranges selected => problem if cursor is at end of last range, otherwise all ok.

**After fix:**
- no range selected => no problem
- one range selected => no problem
- two or more ranges selected => problem if cursor is at the end of any range except last range
       (e.g: three ranges, problem only if cursor is at end of range1 or end of range2).

In all cases, when "problem" happens, just move the cursor.

So what do you think, which is better?

**Comment by Patman86** [comment]
I will invest some time tomorrow and hope i can fix all issues 😉

**Comment by 44vince44** [comment]
Thanks again, I'll look into the code now but I guess tomorrow would be more productive! Good night !

**Comment by 44vince44** [comment]
Well, I'm no real coder, but if this means something, it allows last range only (or unique range) to be treated with " <=":
So instead of the modded line:
If current.End <= Renderer.Position
We would have
If current.End < Renderer.Position OR (  x=(p.Ranges.Count - 1) AND  current.End=Renderer.Position )

Sorry my coding skill haven't been updated since 1998...

**Comment by Patman86** [comment]
> 
> 
> Oops, before continuing further, there is a Dim without setting an initial value for someting that is later incremented:
> 
> line 1127
> Dim frames As Integer
> 
> Shouldn't be followed by:
> frames = 0

The function after that part describes the frames. I think mpv.net is little bugy. Pls test with mpc-hc or mpc-be. I' ve uploaded new fix...

**Comment by stax76** [comment]
vince, please try 2.0.8.11, the problem was caused by loading audio, now audio is disabled if there is a cut section and with that mpv showed the last frame correctly in my test using the original position calculation.

**Comment by 44vince44** [comment]
Stax, the problem is still there.
Indeed now the logic of audio is better, but it didn't fix the problem, not in 2.0.8.0 and not in 2.0.8.11.
I made a small video screen capture, in the fifth post of this thread, and the problem is the same today with 2.0.8.11.

But yesterday, Patman did a build changing line 1132 to   If current.End <= Renderer.Position
and the result was better, meaning that the problem didn't happen anymore at the end of last range.

@Patman86  Thank you Patman, but unfortunately the build that you made today didn't work, there is an error stating an exception.

**Comment by stax76** [comment]
In the next build it will check if the current position is at the very end (the end of the last section) and then go back two frames, I tried one frame but MPC did not work with that. I also tried MPC and VapourSynth and the results were not identical to AviSynth. I did not try different source filters. Issue should now be closed.
