### ISSUE TITLE
Loading Dolby Vision only for re-encode = no VUI Dolby Vision RPU: entry (blank)

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1230]
v.2.35
**Describe the bug**
NVENC API 12.1 CUDA 12.3 Windows 11
Loading Dolby Vision only (Purple/Green tint) for re-encode = no VUI Dolby Vision RPU: entry (blank)
Re-encode to enable playback on Dolby Vision QLED TV - Works if RPU entered manually.
MediaInfo attached at bottom

<img width="234" alt="240210 131430" src="https://github.com/staxrip/staxrip/assets/16325865/28389bc0-72e2-4d2d-8899-102d88eae024">

![240210 105130 copy](https://github.com/staxrip/staxrip/assets/16325865/5c8857f9-4226-4a44-bad0-149b42ae5cdb)

[noEntry.txt](https://github.com/staxrip/staxrip/files/14230106/noEntry.txt)

**Comment by Dendraspis** [comment]
This should be a duplicate to #1198

`NVEncC` was not implemented as mentioned in the release notes of `v2.35`, but the next version will support it.
