### ISSUE TITLE
Attachments don't added to final encode file

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1233]
**Describe the bug**
Attachments missing in container options and in final mkv container.
Project option to add attachments is enabled and attachment exists in temp demux folder.
StaxRip 2.35.0

**Comment by Dendraspis** [comment]
I would need "some" more information like the file names and if the attachments were demuxed by StaxRip or added manually...

**Comment by IevgenSobko** [comment]
Sure thing.
The name of the file was `cover.jpg`. It was demuxed from Remux into temp folder.
When I opened container options in Attachments tab, there were no files.
If I add them manually, everything is OK.

**Comment by IevgenSobko** [comment]
So based on latest encodes, I can say that attachments actually added in the final file.
There is some issue with displaying them on Source|Attachments tab when configuring encode.
Sometimes there is no any attachment displayed there, but final file actually contains them.
I don't know what to do with the issue in this case.

**Comment by IevgenSobko** [comment]
Here is log with one of the latest encodes.
As you can see, attachment was demuxed but not included in the final mkv file
[The.Ring.2002.1080p.UHD.BluRay.DD+.7.1.DV.HDR.x265-TaurohtaR_staxrip.log](https://github.com/staxrip/staxrip/files/14723911/The.Ring.2002.1080p.UHD.BluRay.DD%2B.7.1.DV.HDR.x265-TaurohtaR_staxrip.log)

**Comment by Dendraspis** [comment]
I will take a look at it the next days...

**Comment by Dendraspis** [comment]
Looks like this is finally solved in `v2.42` .... we will see.  😅
