### ISSUE TITLE
Trim HDR 4K source

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1234]
when i have tried cut/trim 4k HDR source i have got this:

Frame Mismatch (v2.35.113)

Target file has 81927 frames, but should have 82047 frames!

StaxRip.ErrorAbortException: Target file has 81927 frames, but should have 82047 frames!
   at StaxRip.GlobalClass.ProcessJob(String jobPath)

[log.txt](https://github.com/staxrip/staxrip/files/14279449/log.txt)

**Comment by Dendraspis** [comment]
And I guess you have cut out those exact 120 frames?

**Comment by madey83** [comment]
i've tried cut exactly 716 frames...

**Comment by Dendraspis** [comment]
716 frames at the beginning, got it.
Might take a while, but I will come to it when I have more information....

**Comment by Dendraspis** [comment]
Ok, had to check it now...  😅 

The warning is because there is a frame mismatch and the frame mismatch is because of the fact, that those non-re-encoded cuts are only possible when cut at key frames. So if you want to have those exact 716 frames cut out, you have to re-encode.

For now you can disable the warning in `Options » Misc`. In one of the next versions the `Frame Mismatch` check will ignore the `Copy/Mux` runs.

**Comment by madey83** [comment]
![image](https://github.com/staxrip/staxrip/assets/34553588/a372f043-8fa7-4ae4-9822-121142ed412d)

on the left hand side you have key frame found by this command
.\ffprobe.exe -select_streams v -show_entries packet=pts_time,flags -of compact -read_intervals 700%800 E:\HDR.mkv | findstr K

on the right hand side you have shown information how many frames were selected. Cutted was in this approach 715 frames.

**Comment by madey83** [comment]
i have done cutting by using avidemux in two steps...
in second step i have cut only 24 frames as you can see on below screenshot

![image](https://github.com/staxrip/staxrip/assets/34553588/bc4bbbac-1b6c-4bb7-a46c-77cf358a8c97)

**Comment by madey83** [comment]
Avidemux was able to cut some frames and left only 24... which i could not cut further...

**Comment by Dendraspis** [comment]
Will be fixed with `v2.37`....
