### ISSUE TITLE
Assertion Failed written whenever any video is opened

### ISSUE THREAD

**Issue by rahatbracu** [staxrip/staxrip#1237]
![Screenshot_11](https://github.com/staxrip/staxrip/assets/146360339/0f9a0248-8947-4847-bc40-5436a119cc4e)

I've facing this  problem while opening any source on Staxrip.What could be the problem and solution? Installed every ms redistributable using vcredist, but no luck. 
When I click Retry , everything just closes down

**Comment by Dendraspis** [comment]
The *README* has a *Prerequirements* section with a link to an All-In-One package that should solve your issue:

https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by rahatbracu** [comment]
> The _README_ has a _Prerequirements_ section with a link to an All-In-One package that should solve your issue:
> 
> https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

still same problem

**Comment by Dendraspis** [comment]
Ah, I just see that you have set StaxRip to use your installed AviSynth+ instead of the portable one that comes with StaxRip.

So in that case I can't really help you as it's your local installation.

![image](https://github.com/staxrip/staxrip/assets/50659978/08f561ac-b56a-47ff-a480-2438c76d24aa)
