### ISSUE TITLE
Container settings not taking the chapters files automaticall although it is there

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#124]
Hi Stax, after having fixed the issue with chapters causing problems, now there is a new issue, the chapters are not taken automatically. I have tested with both a mp4 source and a mkv source, both with chapters.

1) chapters are demuxed ok, they are in the temp folder:
source file: Blade (1998) x265 AC3 Subs Chapters.mp4
listing of demuxed files
Blade (1998) x265 AC3 Subs Chapters ID1 English.ac3
Blade (1998) x265 AC3 Subs Chapters.avs
Blade (1998) x265 AC3 Subs Chapters_chapters.txt
Blade (1998) x265 AC3 Subs Chapters_source.avs
Blade (1998) x265 AC3 Subs Chapters_staxrip.log

I checked the txt file, it is good.

2) When opening the "container options" window (mkv or mp4): here is what I get:
![SNAG-0000](https://user-images.githubusercontent.com/17828567/76146957-76a85a80-60a0-11ea-9877-cc232968e0c7.jpg)

The field for the chapters is empty.
If I browse and select manually the txt file, it will take it OK, but if I don't, the output will not have chapters.

**Comment by 44vince44** [comment]
Here is the mediainfo of the source file

General
Complete name                            : D:\Desktop\Blade (1998) x265 AC3 Subs Chapters.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : iso4 (iso4/iso6)
File size                                : 1.89 GiB
Duration                                 : 2 h 0 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 253 kb/s
Encoded date                             : UTC 2020-03-07 16:05:20
Tagged date                              : UTC 2020-03-07 16:05:20

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L3.1@Main
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 2 h 0 min
Bit rate                                 : 1 803 kb/s
Maximum bit rate                         : 9 741 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.082
Stream size                              : 1.51 GiB (80%)
Writing library                          : x265 2.0+5-98a948623fdc:[Windows][GCC 5.4.0][64 bit] 8bit+10bit+12bit
Encoding settings                        : wpp / ctu=64 / min-cu-size=8 / max-tu-size=32 / tu-intra-depth=1 / tu-inter-depth=1 / me=3 / subme=3 / merange=57 / rect / no-amp / max-merge=3 / temporal-mvp / no-early-skip / rskip / rdpenalty=0 / no-tskip / no-tskip-fast / strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / no-fast-intra / open-gop / no-temporal-layers / interlace=0 / keyint=250 / min-keyint=23 / scenecut=40 / rc-lookahead=25 / lookahead-slices=4 / bframes=4 / bframe-bias=0 / b-adapt=2 / ref=4 / limit-refs=3 / limit-modes / weightp / no-weightb / aq-mode=1 / qg-size=32 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=4 / psy-rd=2.00 / rdoq-level=2 / psy-rdoq=1.00 / no-rd-refine / signhide / deblock=0:0 / sao / no-sao-non-deblock / b-pyramid / cutree / no-intra-refresh / rc=crf / crf=20.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ipratio=1.40 / pbratio=1.30
Encoded date                             : UTC 2020-03-07 16:05:20
Tagged date                              : UTC 2020-03-07 16:05:40
Codec configuration box                  : hvcC

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : ac-3
Duration                                 : 2 h 0 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Maximum bit rate                         : 473 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 385 MiB (20%)
Language                                 : English
Service kind                             : Complete Main
Encoded date                             : UTC 2020-03-07 16:05:36
Tagged date                              : UTC 2020-03-07 16:05:40

Text
ID                                       : 3
Format                                   : Timed Text
Codec ID                                 : tx3g
Duration                                 : 1 h 53 min
Bit rate mode                            : Variable
Bit rate                                 : 43 b/s
Stream size                              : 36.1 KiB (0%)
Title                                    : Sub EN SRT
Language                                 : English
Forced                                   : No
Encoded date                             : UTC 2020-03-07 16:05:40
Tagged date                              : UTC 2020-03-07 16:05:40

Menu
00:00:00.000                             : Chapter 1
00:10:45.644                             : Chapter 2
00:19:32.211                             : Chapter 3
00:30:40.086                             : Chapter 4
00:38:17.253                             : Chapter 5
00:50:09.840                             : Chapter 6
01:01:26.974                             : Chapter 7
01:08:51.627                             : Chapter 8
01:18:57.064                             : Chapter 9
01:28:29.386                             : Chapter 10
01:38:50.172                             : Chapter 11
01:55:12.863                             : Chapter 12

**Comment by stax76** [comment]
Yes, sorry, I have to admit that I could have avoided some of these bugs easily, I have to break soon for rest before I continue (with mpv.net then) (I'm missing much sleep due to fibromyalgia pain 🙁).

I tried to write you a PS script to download and compile the code so you don't have to wait for an upload but it's not working because the compiler is too old, .NET framework ships a compiler but it's older than the one shipped with Visual Studio 2019, sorry.

```PowerShell
curl.exe https://github.com/staxrip/staxrip/archive/master.zip --location --output staxrip.zip
Expand-Archive staxrip.zip staxrip
$msbuild = 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe'
$projectFile = '.\staxrip\staxrip-master\StaxRip.vbproj'
& $msbuild $projectFile /p:Configuration=Debug /p:Platform=x64
# explorer.exe '/n,' '/select,'
```
I have probably enough PC for today, see you.

**Comment by stax76** [comment]
Those two too small dropdown buttons must be a Win 7 only bug btw., I cannot reproduce it.

**Comment by 44vince44** [comment]
Stax, I am aware of your fibromyalgia because you already told us, and I suggest you code only as long as you have the pleasure to do it. You rest when you need, code when you feel like coding, and we wait, there is no rush :-*  and thanks for everything.

**Comment by Patman86** [comment]
The last commits/changes from stax work!

**Comment by 44vince44** [comment]
Thank you Patman for compiling and sharing! I tested, and indeed, it fixes the issue!
