### ISSUE TITLE
additional NVENCC denoise filters

### ISSUE THREAD

**Issue by cartman0208** [staxrip/staxrip#1240]
Is there a way to get all the current denoise filters of nvencc in StaxRip?
From 6 available 3 seem implemented.
    **knn (K-nearest neighbor)**
    **pmd (modified pmd method)**
    gauss (npp library, x64 version only)
    **convolution3d**
    nvvfx-artifact-reduction
    nvvfx-denoise

Or did I just miss the others?
Thanks

**Comment by Dendraspis** [comment]
`--vpp-nvvfx-denoise` and `--vpp-nvvfx-artifact-reduction` are indeed missing, wheras they are sort of special and pretty simple and thus easy to add by hand. 
I will implement them for one of the next releases.

For the others it seems like a new rearrangement of the settings could be useful:  😅 

- KNN
- Convolution3D
- PMD

![image](https://github.com/staxrip/staxrip/assets/50659978/83dd0950-8b85-494a-a27e-91810a47edfe)

- Gauss

![image](https://github.com/staxrip/staxrip/assets/50659978/8dcca8a2-7471-4c96-9416-c86908820735)

- Denoise DCT

![image](https://github.com/staxrip/staxrip/assets/50659978/df712533-a925-47b2-989a-3e60a44c8bd3)

**Comment by Dendraspis** [comment]
Both parameters should be available in the next release...
