### ISSUE TITLE
x265 --auto-aq support

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1241]
I'd like to try the --auto-aq parameter from jpsdr x265 build but StaxRip wants to always add an aq-mode from 0 to 5.

Could you make the aq-mode selection to support --auto-aq too? AFAIK it uses boolean values converted to decimal units.

**Comment by Dendraspis** [comment]
I would at least need some info about the parameter. Is there a description available?

**Comment by tormento** [comment]
I have asked Patman to build the next release with [--auto-aq patch](https://mailman.videolan.org/pipermail/x265-devel/2020-February/012882.html).

In the meantime you can try [jpsdr x265](https://github.com/jpsdr/x265/releases), that already has it.

**Comment by Dendraspis** [comment]
Interestingly this is not an official patch.  😕 

But when Patman is going to implement it, I'm pretty sure StaxRip will support it soon...

**Comment by Dendraspis** [comment]
I highly doubt that, because it is nowhere in the code, just on a mailing list. But we will see and I can only support parameters, that exist....

**Comment by tormento** [comment]
Look [here](https://forum.doom9.org/showthread.php?p=1981371#post1981371).

**Comment by Dendraspis** [comment]
This post is over a year old and already interpreted, I need something more specific like the source code. We will wait till it's implemented officially or by Patman86...

**Comment by tormento** [comment]
[Today](https://forum.doom9.org/showthread.php?p=1998152#post1998152).

**Comment by tormento** [comment]
Annuntio vobis gaudium magnum: habemus Papam!

[Here](https://github.com/Patman86/x265-Mod-by-Patman/releases/tag/3.5%2B155%2B16) :)

**Comment by Dendraspis** [comment]
I know.  😁 

We decided to use the official patch without those extra parameter settings. So when you want to use them, you have to replace `x265` and use the `Custom` field to set them.

Will be available in the next release....

**Comment by Dendraspis** [comment]
@tormento 
Be aware that there is a bug in that `x265` build, which causes the normal `--aq-mode` not to work as intended when `--auto-aq` is disabled. A new release is on its way...

**Comment by tormento** [comment]
@Dendraspis perhaps you should summon @Patman86 :)

**Comment by Dendraspis** [comment]
He already fixes it, a fix will be released soon. Just wanted you to know that.

**Comment by tormento** [comment]
@Dendraspis very kind.

Is that bug so bad to ruin encodes? I did some in the mean time.

Visually I can't perceive nothing different.

**Comment by Dendraspis** [comment]
No, but the `aq-mode` setting does not work as intended, means the value is not used. So it *could* be always set to `2` or `0` or so.

The fixed version should be release soon, so better wait with further encodes, downgrade or always use `--auto-aq`.

**Comment by tormento** [comment]
@Dendraspis the problem, with the current version, is that you can't use --auto-aq alone, as StaxRip always inserts some --aq-mode, from 0 to 5. It's impossible to disable it.

**Comment by Dendraspis** [comment]
Oh yeah, you're right.  😕 

I guess the next release is coming within the next few hours. If you can't wait:  better downgrade.

**Comment by IevgenSobko** [comment]
Glad I jumped in this thread 😀
Wanted to upgrade to 37th version

**Comment by Dendraspis** [comment]
Why?  Of course `v2.37` has the fix already included.  🤔

**Comment by IevgenSobko** [comment]
oh... I thought we should expect 37.1 or 38...
Thanks for update

**Comment by tormento** [comment]
> I guess the next release is coming within the next few hours.

I'd prefer to wait some more time and have a proper auto-aq "binary selection", without having to remember what each bit does.

**Comment by Dendraspis** [comment]
I have roughly checked the implementation and decided to go with the unofficial official one.  😅 
Beside the fact that the doc/explanation about the parameter value is a bit wrong, there are some questions left about the implementation of those additional features. We will see....

Once Issue No.6 is done, I can implement both features, even "our" main `x265` version sticks to the "official" implementation.
