### ISSUE TITLE
Incorrect command line when using VCEEnc (VCE) Decoder with CQP and advanced QP settings - missing space between --avhw and --cqp parameters.

### ISSUE THREAD

**Issue by Klaus-B** [staxrip/staxrip#1247]
**Describe the bug**
When selecting **VCEEnc (VCE)** for Decoder, **CQP - Constant QP** for Mode, and checking the **Show advanced QP settings** checkbox, the command line assembled by StaxRip v2.36 is invalid. The command line starts with --avhw--cqp xx:yy:zz instead of --avhw --cqp xx:yy:zz. Note the missing space between --avhw and the following hyphen.
As a result the job will fail.
 

**Expected behavior**
The command line should have a space between **--avhw** and **--cqp xx:yy:zz** parameters.

**How to reproduce the issue**
1. Navigate to Encoder options -> Basic
2. Select VCEnc (VCE) for the Decoder
3. Select CQP - Constant QP for the Mode
4. Check the Show advanced QP settings checkbox
5. Watch the assembled command line at the bottom of the dialog.  There is no space between **--avhw** and **--cqp xx:yy:zz** parameters.

![image](https://github.com/staxrip/staxrip/assets/161223216/8c97205c-33bf-41a2-97da-a5517e292133)

**Comment by Dendraspis** [comment]
Thank you for the report.

I have a hotfix for you, just replace the files and you're good to go:
[StaxRip_v2.36.1.zip](https://github.com/staxrip/staxrip/files/14397097/StaxRip_v2.36.1.zip)

The fix will also be implemented in the next release....
