### ISSUE TITLE
Options-Image-Crop not retaining/saving entered values - No source loaded

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1249]
v2.36
**Describe the bug**
With no source loaded (attempting to create a new template)...
Options-Image-Crop not retaining/saving Custom Crop user entered values.

When manually entering Custom Crop values and clicking OK to exit the Options dialog the Crop values are not saved.
Re-opening the Options dialog the Custom crop values are back to 0

**Expected behavior**
The Custom Crop values should be retained for use in a new template.

**How to reproduce the issue**
With no source loaded attempting to create a new template with Custom Crop values ...
It does not matter what options are checked (active) or how Auto Crop after opening is set.

<img width="398" alt="240225 173621" src="https://github.com/staxrip/staxrip/assets/16325865/905834a7-8eff-4a56-8fe7-f5ee82d03b8b">

1. Click OK then
2. Click Options menu item to reopen options
<img width="396" alt="240225 173636" src="https://github.com/staxrip/staxrip/assets/16325865/f58446c1-5003-45b9-9241-65bc72c33c7f">

**Comment by Dendraspis** [comment]
Thank you for the report. Sadly introduced it with `v2.36` while changing some logic in the background.

It will be fixed with the next release.

I will see if I can make a hotfix for that....

**Comment by Dendraspis** [comment]
Here is a hotfix for this issue:
[StaxRip_v2.36.2.zip](https://github.com/staxrip/staxrip/files/14403582/StaxRip_v2.36.2.zip)

It might interfere under some circumstances, but it's just a hotfix, so...
