### ISSUE TITLE
QTGMC doesen't work

### ISSUE THREAD

**Issue by frenksisco** [staxrip/staxrip#125]
Hi, I really appreciate this program and your work. Unfortunately my beloved QTGMC filter no longer seems to work after Staxrip 1.9.0.0.
Currently I have just tested it on the stable version 2.0.6.0 and I get this error message:
"Cannot load file '.../dfttst.dll'. Plattform returned code 1114"
After that I also tested the latest 2.0.7.6-beta but in this case Staxrip crashes completely as soon as I select QTGMC.
Hope it can be fixed, until then I will continue to use version 1.9.0.0.
Thanks

**Comment by stax76** [comment]
# for decimal 1114 / hex 0x45a
  ERROR_DLL_INIT_FAILED                                          winerror.h
# A dynamic link library (DLL) initialization routine failed.

There has been a change regarding this, see here:

https://forum.doom9.org/showthread.php?p=1902529#post1902529

Find a beta here:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/u/s!ArwKS_ZUR01g0kH4d4eT_6a3GaKe?e=qbOfGS

**Comment by frenksisco** [comment]
Same problem with beta 2.0.7.7. Staxrip crashes completely as soon as I select QTGMC.
Windows 10 x64 Intel Core i7-3770K

**Comment by stax76** [comment]
Besides the source file there should be a temp folder, I need to know the content of the files with extension avs, vpy and log.

**Comment by frenksisco** [comment]
[test_temp.zip](https://github.com/staxrip/staxrip/files/4321835/test_temp.zip)

**Comment by stax76** [comment]
Thank you, to be sure it's not source file specific please try an ordinary avc/hevc/mkv/mp4 source file.

**Comment by frenksisco** [comment]
Same problem with a mp4 file.
[test_temp.zip](https://github.com/staxrip/staxrip/files/4325168/test_temp.zip)

**Comment by stax76** [comment]
Is your auto load folder containing anything? A dfttst.dll for instance? Maybe try to request help here:

https://forum.doom9.org/showthread.php?t=174544

**Comment by 44vince44** [comment]
I tested QTGMC on my input files, and it works perfectly!

**Comment by frenksisco** [comment]
Sorry but I don't even know what this "auto load folder" is...

**Comment by stax76** [comment]
You can find it in the main menu under Tools > Folder > Plugins

If you are running anti malware software then please try it with temporarily disabled ant malware software.

**Comment by frenksisco** [comment]
No anti malware present except the one included in windows. 
Anyway I completely deactivated it and I repeated the procedure ... same problem; Staxrip crashes.
I am attaching a screenshot of the content of the folder you ask
No dfttst.dll founded.

![2020-03-14 00_35_23-plugins64+](https://user-images.githubusercontent.com/1014756/76669576-96ea8480-658c-11ea-9fff-ce45198f4c1b.jpg)
.

**Comment by 44vince44** [comment]
Using AviSynth or Vapoursynth ??

**Comment by frenksisco** [comment]
If i remember correctly, the first time I started Staxrip it told me to install avisynth+.  If the program had asked me to install Vapoursynth I would have installed that. So I guess staxrip is using avisynth.
It must be said that I am totally ignorant of programming and I only know how to use staxrip.  I don't know how it works and what it needs to work.  I believed that as a portable program it included everything it needed to function.
Now I will try to completely uninstall avisynth and install vapoursynth

**Comment by 44vince44** [comment]
I guess you are using Avisynth indeed.
I suggest: uninstall AVISynth,  uninstall Vapoursynth and anything related, uninstall Python.
Then open staxrip (i suggest you download latest stable version 2.0.8.0)
Then browse in the app manager and install the missing things, that is:

Go to menu -> Apps ->Manage

1. This opens a window, click on the left side "Apps", and install the following Avisynth+
2. Then on the left side, click on "Runtimes" and install all the runtimes under it
  Note that for Python (needed for Vapoursynth) you must select install for all users
3. Then back to the "Apps" on the left, and install Vapoursynth.

Those are what you need. I hope it helps!

**Comment by frenksisco** [comment]
I'm going crazy .. Python 3.7 suggests to be installed "for all users" and so I did. But when I go to install Vapoursynth it gives an error saying that Python is installed for "for the current user only" ... But that's not true! Now I uninstall and reinstall everything for the second time .................... 
If it doesn't work I will install the latest version of python instead of the old one asked by staxrip.....
![2020-03-14 15_47_47-CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US](https://user-images.githubusercontent.com/1014756/76684350-993ff380-660b-11ea-8365-1365d71badea.jpg)

**Comment by frenksisco** [comment]
Ok I finally managed to reinstall everything.
I used python 3.7.7 instead of 3.7.6.
Now QTGMC works at least with vapousynth. Instead it still doesn't work with Avisynth. As I said, as soon as I select QTGMC filter, Staxrip suddenly turns off.
Anyway, it can be perfectly fine for me to use vapoursynth If I can't use avisynth .. Thanks a lot for the help

**Comment by 44vince44** [comment]
You're welcome!
at least you have a solution working!

**Comment by 44vince44** [comment]
You're welcome!
at least you have a solution working!

**Comment by 44vince44** [comment]
@frenksisco I need you to do the following very quick test, please.
Can you please use Avisynth again, and change the following filter:
-Right click on Resize (which is by default set to Bicubic),
-Select Resize > Advanced > ResizeMT > BicubicResizeMT (or anyone in this list of ResizeMT
Note that it is important that it iis a Resize**MT** filter.
Tell me if it crashed (and you'll have helped find a bad bug ;-))

**Comment by stax76** [comment]
@frenksisco 

It sometimes happens that a developer cannot reproduce an issue and nobody knows what could be wrong, if it happens on only one machine than it's especially difficult to find. Please try to get help at doom9.

**Comment by 44vince44** [comment]
@frenksisco  @stax76 I think I know what is causing that: maybe frencisco's machine has an older processor with no AVX2 instruction set, and the dll of JPSDR that is released with Staxrip is the AVX2 build.
So this is why I am waiting to know if ResizeMT filters crash on his machine.
If they crash, then he has simply to replace the JPSDR with a proper one for his processor.

**Comment by stax76** [comment]
@frenksisco

In the Apps dialog what is the status for FFTW ?

**Comment by stax76** [comment]
@44vince44 

Great find, that fixes it at least for somebody at doom9, it will be replaced in the next build.

**Comment by 44vince44** [comment]
@stax76 thanks ;-) but maybe it shouldn't be replaced because most people who care about processing video update their hardware. AVX2 is in the processors since 2013. So it's better to keep AVX2 and standard, and put a zipped copy of the AVX build in the forlder and put a note somewhere... no?

**Comment by frenksisco** [comment]
@44vince44
Sorry for the delay, I did the test you asked: yes it crashes as soon as I select BicubicResizeMT
But I didn't understand what I need to do to fix it

**Comment by 44vince44** [comment]
It's OK, we found that there is a plugin that is called JPSDR that crashes on your setup because it is not supported by some processors made before 2016. So Stax changed the version of this plugin to another one that works on all processors since 2011! Just download last full beta from Stax's dropbox 2.0.9.1 and it is fixed there!
links for Stax's dropbox: you can find them here #110 
And you can close this thread now because it's fixed!

**Comment by frenksisco** [comment]
Wow thank you very much! The 2.0.9.1 beta works perfectly now! I really have never received such serious and effective support. Thanks a lot again!

**Comment by coralhl** [comment]
@44vince44> 
>  replace the JPSDR with a proper build for his processor (AVX).

You are the best!

**Comment by 44vince44** [comment]
@coralhl (blush) thanks ;-)))
