### ISSUE TITLE
Main Screen VBR file size estimate is off - DoVi/HDR10(+)

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1254]
v. 2.36
**Describe the bug**
File size estimate of DoVi/HDR10(+) finished file size is off by 100+ MB (estimated 730Mb / finished 630MB) - used to be a closer estimate of the finished size.

Approximately 15% smaller than estimate. SDR and DV only file size estimate seems to be more accurate (same file in DV only - estimated 730MB finished 700MB). 

**Expected behavior**
Dolby Vision / HDR video size estimate should be closer to finish re-encoded video size. Previously, this estimate was within 5% (+/-).

**How to reproduce the issue**
Load a Dolby Vision / HDR video 
1. Note the estimated VBR size vs. bitrate on the main screen and re-encode.
2. Compare the size of the file after encode.

**Provide information**
<img width="234" alt="240229 132817" src="https://github.com/staxrip/staxrip/assets/16325865/6955078f-4125-4f99-bbcc-a0d37f8e40e2">
<img width="215" alt="240229 132833" src="https://github.com/staxrip/staxrip/assets/16325865/f2932a0e-e903-488b-8a1e-b80a6275aecf">

EDIT
Bit Rate comparison re-encoded files (DV only top / DV HDR10+ bottom) - Note StaxRip VBR bitrate setting same for both

![240229 142016](https://github.com/staxrip/staxrip/assets/16325865/99b70b96-5c71-49f4-b153-83c47ce8da4a)

**Comment by Dendraspis** [comment]
Metadata should definitely be added to the calculation, which is currently missing.  🤔 

I will see what I can do....
