### ISSUE TITLE
QTGMC no longer works; crashes StaxRip

### ISSUE THREAD

**Issue by THGhost** [staxrip/staxrip#1256]
**Describe the bug**
Enabling QTGMC causes StaxRip to crash either partway through an encode or instantly when using the Preview window.

**Expected behavior**
QTGMC should successfully deinterlace the source file and result in a complete encode.

**How to reproduce the issue**

Method 1:
Input a source file.
Enable the QTGMC filter and input the following settings: `QTGMC(preset="Slow", inputType=0, FPSDivisor=2, matchpreset="Slow", Lossless=2, matchpreset2="Slow", sourcematch=3)`
Open the Preview window and try moving to a specific timecode/frame number.
StaxRip instantly crashes. No error message.

Method 2:
Input a source file.
Enable the QTGMC filter and input the following settings: `QTGMC(preset="Slow", inputType=0, FPSDivisor=2, matchpreset="Slow", Lossless=2, matchpreset2="Slow", sourcematch=3)`
Start the encode.
QTGMC will eventually crash. When exactly appears to be random, most likely depending on the source. Error message below.

**Provide information**
Screenshots of the the error message that occurs when QTGMC crashes after attempting an encode:

![dfjdfjdfhj](https://github.com/staxrip/staxrip/assets/32550606/5f14609c-3540-435b-9d45-16eefe6bc939)

(Source file name has been hidden. Gotta have some secrets now, eh?)

Used StaxRip version: v2.36.0

**Additional context**
I believe it's the following settings that are causing QTGMC to crash:
`Lossless=2` & `sourcematch=3`
If these are set to anything other than 0, QTGMC will crash.

v2.28.0 appears to be the most recent version of StaxRip that works with these specific QTGMC settings. Every version since results in the same crash scenario. I've tried pointing v2.36.0 to the QTGMC files in v2.28.0 but it didn't work. So I need both versions installed until this is fixed.

**Comment by Dendraspis** [comment]
Thanks for the report.

Interestingly the preview works for me, but I had to peek at least 10 or 15 frames till StaxRip crashed. But at least reproducible...

I'll be back when I have a solution for that issue.

**Comment by Ding-adong** [comment]
I haven't used QTGMC for a while and did some comparison and I got the same experience as @THGhost.
