### ISSUE TITLE
Since V2.35 Resizing would interfere with the DV Metadata, Disable Resize or the DV RPU File.! OTHER DV requires VBV to enlable HRD 

### ISSUE THREAD

**Issue by Wayne-interrssierts** [staxrip/staxrip#1259]
Since V2.35 only Resize & DV VBV problems that I can't get solved, I switch off Resize as requested, then the problem comes with DV VBV, then I can't re-encode anything anymore, I often do UHD HDR to FHD HDR and This has always worked so far.

I still have an older V2.13, NO problems or I have to switch to Handbrake, no problems either..

If it always worked before, something must have been programmed incorrectly or not?

In any case, if I turn off resize, which I don't want to do, I use the program EXTRA for resize, the stupid VBV error comes up...

**Comment by Dendraspis** [comment]
> Since V2.35 only Resize & DV VBV problems that I can't get solved

Why not?

> I switch off Resize as requested

Then you better switch to `v2.36`, restricted resizing is allowed now.

> then the problem comes with DV VBV

So why don't you click on the error message and fill out the necessary data? The data is required, because the encoder will crash otherwise.
You could also use the search and find a closed issue like #1203 where you get even more information.

> I still have an older V2.13, NO problems or I have to switch to Handbrake, no problems either..

Then you probably produced broken encodes....  😕 

> If it always worked before, something must have been programmed incorrectly or not?

Until `v2.32` the handling of Dolby Vision metadata was completely up to the user. Meanwhile StaxRip checks also for needed settings and also if you're going to break the result, for example by wrong cropping, resizing, ...

> In any case, if I turn off resize, which I don't want to do, I use the program EXTRA for resize, the stupid VBV error comes up...

I think I have already answered these questions.
Just for your information:  Depending on your workflow, the metadata could not fit the encode anymore.

**Comment by Wayne-interrssierts** [comment]
""Then you better switch to v2.36, restricted resizing is allowed now.""

2.36 has the same problem...

""So why don't you click on the error message and fill out the necessary data? The data is required, because the encoder will crash otherwise.
You could also use the search and find a closed issue like https://github.com/staxrip/staxrip/issues/1203 where you get even more information.""

If I knew WHERE I would have to enter WHAT exactly in which row so that the sh.. message would go away..
I read something about entering 16000 in issue 1203... that means that I have such a high bit rate, which I don't want either, I encode some 100GB films down to under 10GB with HDR and they look the same in FHD Looks good, like the original, I don't see any difference on my 65" TV at a distance of 3m.

""Then you probably produced broken encodes.... 😕""

NOPE, I didn't create any incorrect encodings because ALL encodings looked GREAT on my TV.
I NEVER needed DV data because my TV can only do HDR anyway.

I've already answered that, my coding was always GREAT until Staxrip was rewritten up to 2.32 and now these annoying messages come up..

Well, whatever, I'll just use Handbrake or Megui again, no annoying messages, no Problems, great encodings as every time..

**Comment by Dendraspis** [comment]
> 2.36 has the same problem...

Then you need to resize properly, meaning even. 

> If I knew WHERE I would have to enter WHAT exactly in which row so that the sh.. message would go away..

The Assistant opens the encoder settings for you where you can find the VBV settings. You could also use the search inside the encoder settings....

> I read something about entering 16000 in issue 1203... that means that I have such a high bit rate, which I don't want either

That's not what VBV is there for.

> I've already answered that, my coding was always GREAT until Staxrip was rewritten up to 2.32 and now these annoying messages come up..

These warnings only appear when you use Dolby Vision metadata. So either you have to deal with the necessary limitations or just get rid of Dolby Vision.

> Well, whatever, I'll just use Handbrake or Megui again, no annoying messages, no Problems, great encodings as every time..

Yeah, definitely the better option for you.  😅 
I close this one.....

**Comment by Wayne-interrssierts** [comment]
LOL and how can i DISABLE DV Metadata? 
Well, i use, if i use Staxrip, then older Versions until 2.31, than do this Tool what i want, not what the tool want..

**Comment by Dendraspis** [comment]
The extraction can be set up in `Options » Video`.

> then older Versions until 2.31, than do this Tool what i want, not what the tool want..

StaxRip just prevents you from destroying the result and that would have happened with the Dolby Vision metadata that was set.
