### ISSUE TITLE
hardcoded subs not working

### ISSUE THREAD

**Issue by hani-yassine** [staxrip/staxrip#126]
hey i tried staxrip 2.6.0 (stable) and all the later beta all of them i open staxrip add a video then press ctrl+h to add a .ass file select default x264 profile and select MP4 box and after encoding the resulting video have no hard-coded subtitles at all, so i tried an old version (2.0.0.0) i did the same streps and the hard-coded subs worked as an extra investigation i went into apps >subtitles > vsrip and the 2.0.0 version where it's working it's modified in 2019 meanwhile the 2.0.6 where it's not working modified in 2011, hopefully this can be fixed thanks :)
![2 0](https://user-images.githubusercontent.com/39760468/76503177-0efe6080-644e-11ea-983a-c294f9d40072.PNG)

**Comment by 44vince44** [comment]
I made some tests, and I found a problem with 10bit sources.
Try putting, in the code, the command ConvertBits(8) before the command TextSubMod(......)
resulting in something like that:
ConvertBits(8)
TextSubMod("D:\Desktop\myvideosubs.ass")

Tell me if it works

**Comment by hani-yassine** [comment]
@44vince44  interesting that worked going to vsfilter > add > color > convert > bitdepth and then selecting 8bit did the trick, thanks! the subs now show up but hopefully this can be fixed in the next version :)
![Capture](https://user-images.githubusercontent.com/39760468/76564428-228ee300-64b1-11ea-84d1-cf67714333ee.PNG)

**Comment by 44vince44** [comment]
Hani-Yassine, that's strange because the Vapoursynth implementation of this filter is supposed to work with 10+bits !

**Comment by hani-yassine** [comment]
@44vince44 yeah it does that is why i was confused when you told me to do that and it worked :D

**Comment by 44vince44** [comment]
@hani-yassine : I was able to make it works, even with 10 bits.
Please do try the following: go to windows settings > Apps and Features
Remove ALL Python version as well as all Vapoursynth.
Once all are removed, install Python 3.7.6 (be careful: use CUSTOM install so you can install for ALL USERS), then install VapoursythR48.
Then you should be able to make it work, without converting to 8 bit.

**Comment by stax76** [comment]
Is there anything I can do? Otherwise the issue can be closed.

**Comment by 44vince44** [comment]
I was waiting a reply from hani-yassine, because if two users have same issue due to same problem (a problem that is external to staxrip), maybe it's worth putting a note in the app manager on the Python page, a note that says something like "Note: if too many versions of Python are installed on your system, than they could cause malfunction of Vapoursynth filters, so it is recommended you uninstall all Python versions and install only the required one". That's only a suggestion Stax...

**Comment by hani-yassine** [comment]
i see i already had an older version of python when i installed staxrip and when i installed the latest version i just did a "repair version" maybe it needed a fresh install to avoid malfunction @stax76 (in my case i i already have python and installed staxrip and did a "repair current python version" before using aviSynth it can cause malfunction (it's a rare and only will happens to poeple that already have an older version of python and want to use 10bit source to hardcore subs), thanks @44vince44  for your help :)

**Comment by 44vince44** [comment]
You're welcome Hani!
