### ISSUE TITLE
ffmpeg -hwaccel cuda -hwaccel_output_format cuda

### ISSUE THREAD

**Issue by staxrip727** [staxrip/staxrip#1260]
Where is `-hwaccel cuda` ? NVDEC HW decoding does not work.
![nvdec](https://github.com/staxrip/staxrip/assets/161551111/a292bb00-80d4-45cd-b30e-a2fb4eb38956)

https://trac.ffmpeg.org/wiki/HWAccelIntro#NVDECCUVID

Sample decode using CUDA:

`ffmpeg -hwaccel cuda -i input output`

Full hardware transcode with NVDEC and NVENC:

`ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i input -c:v h264_nvenc -preset slow output`

**Comment by Dendraspis** [comment]
I will add it for the next release, so that `-hwaccel cuda -hwaccel_output_format cuda` will be added.

Meanwhile you can add it manually via the `Custom` field...

**Comment by staxrip727** [comment]
Custom addition also does not work.
Error:
`ffmpeg.exe -hwaccel_output_format cuda -i "E:\Badminton\CCTV Olympics 4K 2023 Sudirman Cup Badminton China VS Japan 20230520 HEVC 2160p HLG AAC-WWSL.mp4" -c:v hevc_nvenc -cq 25 

> -hwaccel cuda

 -an -y -hide_banner "E:\Badminton\CCTV Olympics 4K 2023 Sudirman Cup Badminton China VS Japan 20230520 HEVC 2160p HLG AAC-WWSL_temp\CCTV Olympics 4K 2023 Sudirman Cup Badminton China VS Japan 20230520 HEVC 2160p HLG AAC-WWSL_new 34 cuda_out.mkv"`

Correct:
`ffmpeg.exe 

> -hwaccel cuda

 -hwaccel_output_format cuda -i "E:\Badminton\CCTV Olympics 4K 2023 Sudirman Cup Badminton China VS Japan 20230520 HEVC 2160p HLG AAC-WWSL.mp4" -c:v hevc_nvenc -cq 25 -an -y -hide_banner "E:\Badminton\CCTV Olympics 4K 2023 Sudirman Cup Badminton China VS Japan 20230520 HEVC 2160p HLG AAC-WWSL_temp\CCTV Olympics 4K 2023 Sudirman Cup Badminton China VS Japan 20230520 HEVC 2160p HLG AAC-WWSL_new 34 cuda_out.mkv"`

**Comment by Dendraspis** [comment]
Okay, sorry, forgot about the `ffmpeg` parameter syntax order.  🙄 

So instead, can you try this hotfix and tell me if it works for you:
[StaxRip_v2.36.3.zip](https://github.com/staxrip/staxrip/files/14478208/StaxRip_v2.36.3.zip)

A short feedback would be nice....

**Comment by staxrip727** [comment]
> Okay, sorry, forgot about the `ffmpeg` parameter syntax order. 🙄
> 
> So instead, can you try this hotfix and tell me if it works for you: [StaxRip_v2.36.3.zip](https://github.com/staxrip/staxrip/files/14478208/StaxRip_v2.36.3.zip)
> 
> A short feedback would be nice....

YES!

**Comment by Dendraspis** [comment]
Thanks, so it will be available in the next release...
