### ISSUE TITLE
is it posssible to use fuctions like MAXINE API artifact reduction in staxrip.

### ISSUE THREAD

**Issue by chowderhead** [staxrip/staxrip#1263]
artifact reduction works without increasing size..
Id ike to use it but I simply cant figure out how.
thanks Randy Kuehn

**Comment by Dendraspis** [comment]
You can call every filter/plugin for `AviSynth` or `VapourSynth`. You just have to find one that you can use - that should be the biggest problem.  😅 

On the other side `NVEncC` supports it meanwhile with the `--vpp-nvvfx-artifact-reduction` parameter, so you just have to update it and set the values by hand. Or you just wait for the next release as that will have all you need included.

**Comment by chowderhead** [comment]
I finally found the MOST recent NvencC instructions .md file that contains all the flags and variables including the latest MAXINE CALLS.  Its in NvencC 7.44.zip  file named NvencC.options.en.md

**Comment by Dendraspis** [comment]
You can also find the most updated version online:
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md


So I close this one....
