### ISSUE TITLE
QSVenc 

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1264]
Hello! Spanish ver. 2.36
When I select the QSVenc codec, then after processing, when finished, it saves the changes, but reports an error.

**Comment by Dendraspis** [comment]
Can you share the log file?

**Comment by Andrasolin** [comment]
Frame Mismatch (v2.38.0)

Target file has 19848 frames, but should have 9924 frames!

StaxRip.ErrorAbortException: Target file has 19848 frames, but should have 9924 frames!
   в StaxRip.GlobalClass.ProcessJob(String jobPath) в D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:строка 464

**Comment by Andrasolin** [comment]
[2024-05-03 - 22.26.44 - IVE_new2_new_new_new_staxrip.log](https://github.com/staxrip/staxrip/files/15200646/2024-05-03.-.22.26.44.-.IVE_new2_new_new_new_staxrip.log)

**Comment by Dendraspis** [comment]
Should be already fixed in the latest release...

**Comment by Andrasolin** [comment]
ok, I'll wait

**Comment by Dendraspis** [comment]
No, I meant the one that is already out. 😅

**Comment by Andrasolin** [comment]
Is it fixed in version 2.38.7 ???

**Comment by Dendraspis** [comment]
Test it and tell me...

**Comment by Andrasolin** [comment]
This "error" is not critical
I'll stay in version 2.38.0

**Comment by Andrasolin** [comment]
in this new version 2.39.1, this "bug" is present

I choose QSVenc H.265 CQP balanced 8-bit Main 
VPP: deinterlace-x2(bob)
VUY: tff
