### ISSUE TITLE
Auto Crop not working

### ISSUE THREAD

**Issue by bdlegend** [staxrip/staxrip#1265]
Auto Crop not working in latest version. Back to v2.34 where auto crop working.

**Comment by Dendraspis** [comment]
That doesn't help at all.
Log file?
`HDRDVmetadata_L5.json` existing in Temp folder? Share the file or content.

**Comment by Andrasolin** [comment]
This function resets the settings and returns the menu interface to the default. QSVenc is also buggy. I’ll probably install 2.34 too
