### ISSUE TITLE
SVT-AV1 2-Pass Bug

### ISSUE THREAD

**Issue by kuzon3** [staxrip/staxrip#1267]
If you set variable bitrate and 2-pass encoding everything works fine. The bug happens when you switch back to quality/crf encoding. If you forget to set 2-pass back to 1-pass before switching to quality. Staxrip will re-encode the video and call it a second pass. (lol)

Bug Fix: Make sure you set 2-pass back to 1-pass

**Comment by Dendraspis** [comment]
Good catch, thanks for the report.

Will be fixed in the next release...
