### ISSUE TITLE
Show frame type

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1268]
On preview screen would be good to see frame type: I, P, B to be able to identify where would be possible cut off

![image](https://github.com/staxrip/staxrip/assets/34553588/481bbc23-a6f9-46ed-813e-2ce8eda8607a)

**Comment by Dendraspis** [comment]
This is not possible. The frame type is an information that is only included in the source file. The Preview shows the result after opening the source file and handing it over to VapourSynth, and potentially after applying other filters.
