### ISSUE TITLE
Tune and preset selection not working properly

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1269]
Open x265 options and switch from none to `animation `and back to `none`.

It will leave some "residues" from the animation tune.

Now, restart staxrip.

My switches for x265 are `--crf 20 --preset slow --output-depth 10 --amp --tskip --aq-mode 5 --keyint 24 --fades --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --selective-sao 2`.

Change the preset from slow to medium.

The switches will be changed to `--crf 20 --output-depth 10 --aq-mode 2 --keyint 24 --fades --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --selective-sao 2`.

It seems a sort of duplicate of a [previous issue](https://github.com/staxrip/staxrip/issues/894#issue-1267919975) I posted.

**Comment by Dendraspis** [comment]
It does not look like there is something wrong, this happens by design.

When you select a different tune or preset, those values are applied - that's it.

**Comment by tormento** [comment]
I can understand your point of view, but it would be nicer to give precedence to the parameters set in Staxrip, when things are set back to the original values.

**Comment by Dendraspis** [comment]
There is no *back to the original values*. The preset/tune sets multiple parameters and values and those are set when you change the preset/tune and then one more time when you set them back. Values, that are not set by the preset/tune are not harmed in any way.
