### ISSUE TITLE
Extract audio from DTS-HD.MA and Dolby Atmos

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1270]
Could it be possible to add an option to extract audio stream from DTS-HD.MA.5.1 and Dolby Atmos without encode it?

![image](https://github.com/staxrip/staxrip/assets/34553588/075e27f4-96eb-487d-b2d7-d3bf50ce0e4e)

**Comment by Dendraspis** [comment]
The last one already exists, not sure about the others, have to check that....

<img src=https://github.com/staxrip/staxrip/assets/50659978/97302d44-3581-454c-a439-1471abe86707 width=500>

**Comment by madey83** [comment]
hi,

but i do not have access to version 2.39 ;)

**Comment by Dendraspis** [comment]
Since DTS Core can already be extracted and the latest versions of `eac3to` separate the AC3 stream from the TrueHD stream, I can close this one...
