### ISSUE TITLE
StaxRip v2.37 Default Encoder Profile for SvtAv1EncApp missing changes in v2.0.0

### ISSUE THREAD

**Issue by BillyBob1354** [staxrip/staxrip#1273]
**Describe the bug**
There where some changes to the parameters in SVT-AV1 v2.0.0

**Changes to multi pass:**
https://gitlab.com/AOMediaCodec/SVT-AV1/-/releases/v2.0.0
3-pass VBR was removed
(checked and only one pass CBR work in Stax)

![image](https://github.com/staxrip/staxrip/assets/46253676/babed7c8-c4eb-455f-ab85-a3120c2c7efe) ![image](https://github.com/staxrip/staxrip/assets/46253676/2c47615f-b692-4875-b2b1-7a3d854073a1)

**Film grain changes:**
https://gitlab.com/AOMediaCodec/SVT-AV1/-/compare/v1.8.0...v2.0.0

Film grain denoise is now [disabled by default](https://gitlab.com/AOMediaCodec/SVT-AV1/-/commit/8b39b41df9e07bbcdbd19ea618762c5db3353c03).
New parameter "[--fgs-table](https://gitlab.com/AOMediaCodec/SVT-AV1/-/commit/ae7ce1abc5f3f7913624f728ae123f8b8c1e30de)"

![image](https://github.com/staxrip/staxrip/assets/46253676/b7911ad0-fb9b-402f-ae67-b6f7a7f9b5d9)

**Comment by Dendraspis** [comment]
Looks like there were more changes in this and/or earlier versions, that are not covered.

I will go through the [Parameters list](https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md) and adjust the implementation....

**Comment by Dendraspis** [comment]
Updates will be available in `v2.38`....

**Comment by Dendraspis** [comment]
Actually it's available with [v2.37.5](https://github.com/staxrip/staxrip/releases/tag/v2.37.5)...
