### ISSUE TITLE
Show current time on crop/preview window

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1274]
Hello,

I wanted to ask you to kindly please implant a feature that shows the current time of the video(where the slider is) on crop and preview window. There is a frame number on the crop window but that's not as good.
That's all 🙂

**Comment by LazyNCoder** [comment]
Sorry about that. Just updated to the last version. closed.

**Comment by Dendraspis** [comment]
### Crop window

I will add the `Time` information for one of the next releases.

### Preview window

There is already a `Time` information implemented via the `Info` screen. Enable it via `Menu » View » Info` or just hit `i` on your keyboard.

**Comment by Dendraspis** [comment]
Available in the latest release....
