### ISSUE TITLE
Unsupported Compression Method Extracting v2.37 from 7zip

### ISSUE THREAD

**Issue by ddelella** [staxrip/staxrip#1278]
**Describe the bug**
Extracting the zip file for 2.37.0 using 7zip 22.01 produces 4 "unsupported compression method" messages.

**Expected behavior**
Extracting without issue.

**How to reproduce the issue**

Use the listed version of 7zip in Window, download the zip for 2.37.0 and trying to right click on it and extract.

**Provide information**

![image](https://github.com/staxrip/staxrip/assets/548747/31734d37-5d24-4257-a1a6-f3af96e137c1)

If you can't (or don't) share your log file, give us at least this information:
StaxRip 2.37.0
7zip 22.01
Windows 11 23H2

**Comment by Dendraspis** [comment]
Just update 7-zip and/or download `v2.37.1`. I suggest doing both. 😅
