### ISSUE TITLE
x264 chroma_qp_offset bug

### ISSUE THREAD

**Issue by kuzon3** [staxrip/staxrip#1279]
Might be bug I don't know. What I do know is if you set -chroma_qp_offset=-1 it always gives it a -3. Meaning it goes from -1 to -4. To counteract it I have to set -chroma_qp_offset=2 to get -chroma_qp_offset=-1. Don't know if it's a staxrip bug or encoder bug.

**Comment by Dendraspis** [comment]
`--chroma-qp-offset` is just a value that is passed to the encoder. So in case it is changed in the output, the encoder changes it.
