### ISSUE TITLE
Event Command - After Video Encoded - Error

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#128]
2.0.7.6 Beta (and others)

If an Event Command is created with the event After Video Encoded and part of the event changes the name of the TARGET file an error occurs because StaxRip tries to access the temporary files using the new (changed) name - cannot find file error occurs.

Example: I have the following event commands which rename the target file based on standard/nonstandard video with: 
****************************************************************************************

Name: WidthStandard
Event: Before Job Processed

Criteria Match Any
Target Image Width		Is		1920
Target Image Width		Is		1280
Target Image Width		Is		720

Command: SetTargetFile
Parameters: Target File Path
%target_dir%%source_name%.%target_height%p.%encoder_ext%.%muxer_ext%

*****************************************************************************************

Name: WidthxHeight
Event: Before Job Processed

Criteria: Match All 
Target Image Width	Is Not	1920
Target Image Width	Is Not	1280
Target Image Width	Is Not	720

Command: SetTargetFile
Parameters: Target File Path
%target_dir%%source_name%.%target_width%x%target_height%.%encoder_ext%.%muxer_ext%

******************************************************************************************
Example output: xyzvideofile.720p.h265.mkv or xyzvideofile.2160x1280.h265.mkv
******************************************************************************************

if I change the event to After Video Encoded (which should still work) - a not able to find file error occurs.

The event command currently works using Before Job Processed, so it's not a major issue. However, StaxRip should not use event command altered target filenames to attempt access of temporary processing files.

**Comment by noblemd00** [comment]
v2.0.8.0 

The above Event Commands are no longer working properly in v2.0.8.0 using any event designation.

**Comment by noblemd00** [comment]
Event Commands are no longer changing target file names in v2.0.8.0

**Comment by stax76** [comment]
Please try if 'Before Job Processed' works with 2.0.8.11

https://github.com/staxrip/staxrip/blob/master/Changelog.md

https://staxrip.readthedocs.io/intro.html#download

**Comment by noblemd00** [comment]
Hi,

 

Tried 2.0.8.12 since it was the latest and it worked – Thanks!

 

Test.Sub.mkv (original)

Test.Sub.960p.h265.mkv

Test.Sub.2160x1080.h265.mkv

 

 

Also created this event command:

 

Creates a log entry with the DESTINATION file/path explicitly logged. Can we get this (or something similar) included in the log without needing an event command and preferably at the end of the log (Job Complete section). 

 

Note: the stars are there to make the entry is easy to spot (not needed if in Job Complete section).

 

Also why is the Event command text written in the log? (following). 

A Command text Log entry is confusing and redundant since they are in the Event Command dialog if needed: 

 

Event: Before Job Processed

Command: WriteLog

Parameter Header: 

Parameter Message: 

**********************************************************************

************************     DESTINATION     *************************

**********************************************************************

 

%target_dir%

%target_file%

 

**********************************************************************

**********************************************************************

 

Actual output:

 

**********************************************************************

************************     DESTINATION     *************************

**********************************************************************

 

F:\-CNV\_TV\Test\

F:\-CNV\_TV\Test\Test.Sub.960p.h265.mkv

 

**********************************************************************

**********************************************************************

 

 

Mike

**Comment by noblemd00** [comment]
Hi (again)

 

One other request while I have your attention…

 

Could you include a “Make Current Template as Startup” (or something similar) in the FILE menu?

 

Yes, it is available as a multi-step process in settings or when saving a Template, but a single click FILE menu item would be very useful and much more convenient.

**Comment by noblemd00** [comment]
HI, (one more time)

 

See the problem with Network Paths  ignoring first “\” in path (\\TMSY\T8.Movies <file://TMSY/T8.Movies> ).

 

https://github.com/staxrip/staxrip/issues/132

 

Mike

**Comment by stax76** [comment]
> If an Event Command is created with the event After Video Encoded and part of the event changes the name of the TARGET file an error occurs because StaxRip tries to access the temporary files using the new (changed) name - cannot find file error occurs.

It changes just the variable of the target file and at this time of the processing it is something that cannot be done.

> Creates a log entry with the DESTINATION file/path explicitly logged. Can we get this (or something similar) included in the log without needing an event command and preferably at the end of the log (Job Complete section).

Answer is still no, but it's a good use case for Event Commands, next build has a 'After Job Muxed' event which is suitable for logging the destination path

> Also why is the Event command text written in the log?

Nobody yet requested to hide it. ;-)

Also next build:

- new: when a Event Command executes it writes a log entry,
       this is now disabled by default but there is a new setting:
       'Write Event Commands to log file'

> Could you include a “Make Current Template as Startup” (or something similar) in the FILE menu?

Maybe not a good idea because you can use 'File > Save Project as Template' which has a startup checkbox or change it in the settings dialog which allows to choose the startup template too. StaxRip has design principles that aim to avoid cognitive overload, people like me that are prone to it have bad experience with overloaded apps like PotPlayer or Hybrid. If you really want to have this you can request a new command so you can customize the main menu. It's probably already possible since staxrip can be automated via powershell and there is a command to run powershell code. I don't have time to explain how to do it because StaxRip is now paused for me for a longer time as I made the transition working on mpv.net and other projects again.

In the future please don't make multiple unrelated requests in a single issue but rather create dedicated issues for each request.
