### ISSUE TITLE
dovi_tool -c switch

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1280]
Hello,

After a while, I decided to check the latest version (2.37.1) to see how it handles metadata. I noticed, it doesn't use -c switch that is needed to crop a video with DV metadata. Is that OK?
The output RPU is totally different if you use -c switch 
I don't know how it doesn't make a problem, not using the switch and still cropping the image. Please somebody let me know. Thanks

Also, shouldn't --dhdr10-opt be used when encoding HDR10+ in x265?

**Comment by Dendraspis** [comment]
>  I noticed, it doesn't use -c switch that is needed to crop a video with DV metadata. Is that OK?

Yes. Using `--crop`/`-c` is the wrong way and it can destroy the output, even when it works for many videos.
I made multiple overhauls to create a workflow that ensures a proper outcome for ***all*** sources.

You did not mention from which version you came, but when StaxRip used `-c` it should be `v2.34`.
I recommend reading the notes on the latest [Releases](https://github.com/staxrip/staxrip/releases) I made, especially `v2.35` and `v2.36`, including the linked guide.

**Comment by LazyNCoder** [comment]
I have a video, the black bars are 264px on top and the same on the bottom. Staxrip crops only 56px of it. When I manually crop the image, it says it's over cropped. I don't know what to do. Is there any way to fix this?
If I use dovi_tool with -c switch and an older Staxrip(like 2.31) would it ruin the results? There's too much difference there between 56px and 264. 
Maybe I shouldn't crop it at all.

**Comment by Dendraspis** [comment]
You haven't read the guide. 😅

**Comment by LazyNCoder** [comment]
Thank you. I just read it.
So, manual threshold didn't help.
I opened the HDRDVmetadata_L5.json with notepad and it's like this:
```
{
  "crop": true,
  "presets": [
    {
      "id": 0,
      "left": 0,
      "right": 0,
      "top": 52,
      "bottom": 52
    }
  ],
  "edits": {
    "0-87155": 0
  }
}
```

I changed them to 264 and it worked. I just don't know if this is right or not 😅😅

**Comment by Dendraspis** [comment]
In that case `Manual Threshold` really cannot help.  😅 

Without destroying the outcome you can't crop the video more than `52px`.  Cropping it more would harm the result, same with the adjustment you've made by editing those values.

**Comment by LazyNCoder** [comment]
Thank you. What exactly do you mean by "destroying the outcome"? would it ruin the colors and DV metadata? at the moment I don't have a DV device available to check the result.

**Comment by Dendraspis** [comment]
The metadata won't fit the video anymore, many of the pixels would be shifted. How *dramatic* the difference would look like depends on the video and the metadata.

**Comment by LazyNCoder** [comment]
I can still go uncropped without any issues right?
I wish there was tools to check and correct these things.

**Comment by Dendraspis** [comment]
Uncropped is what always works, yes.

Why correct? StaxRips allows you to do everything you like without harming the outcome. Basically there is nothing more needed. 🤔

**Comment by LazyNCoder** [comment]
I understand. But encoding something which has 264px black bars with only 52px of them cropped is kinda ugly.

Nevertheless, Thank you for everything you do.

**Comment by Dendraspis** [comment]
> But encoding something which has 264px black bars with only 52px of them cropped is kinda ugly.

I absolutely agree. I guess somebody was pretty lazy.  😕 

You're welcome.

**Comment by Dendraspis** [comment]
Little addition:
Of course this restriction is only valid when the Dolby Vision metadata is applied. You can remove it from the encode and crop whatever you want.
