### ISSUE TITLE
Hardcoded Subtitle function no longer available since v2.36

### ISSUE THREAD

**Issue by mcmighty7** [staxrip/staxrip#1281]
Since v2.36, hardcoded subtitles no longer work. If i click CTRL+H, oder select "Tools > Advanced > Add Hardcoded Subtilte, nothing happens anymore. No Function anymore. 

Otherwise the dialog window always appeared where you could select the .srt File. Unfortunately that is no longer possible. 

For now, I Use as Workarround with using another AVS-Filter for example "Field" and entering "TextSub("D:\Video\_temp\forcedsub.srt")" there as Function to Burn in Subtitle.  Please bring back the normal function for burned-in subtitles. Thanx. Keep it up. Great tool

**Comment by Dendraspis** [comment]
This is why I wrote down:

> Please check out the Changelog as always to know what has changed and start with fresh settings to avoid side effects.

You use the new version(s) with pre-`v2.36` settings, simple as that, check out the Changelog. 😅
So in order to solve that, you have to reset the settings, the whole Main menu or re-assign the menu entry for that function in case you made already adjustments.

**Comment by mcmighty7** [comment]
Okay, Thanx for the Info. After Reset Settings, CTRL+H works fine ;)
