### ISSUE TITLE
Ctrl + H does not work. Add hardcoded subtitle does not work.

### ISSUE THREAD

**Issue by viktorz3008** [staxrip/staxrip#1282]
**Describe the bug**
Ctrl + H does not work. Add hardcoded subtitle does not work.

**Expected behavior**
It should work. Has happened since 2.36.0

**How to reproduce the issue**

Just try and see. Had to go back to 2.35.0

**Provide information**

No error, it just does not work.

**Additional context**
Nothing

**Please be as clear and as detailed as possible**

**Comment by Dendraspis** [comment]
Duplicate to the last issue #1281
