### ISSUE TITLE
Missing parameters in command with new nvenc filters

### ISSUE THREAD

**Issue by cartman0208** [staxrip/staxrip#1283]
**Describe the bug**
Thanks for adding the new denoise filters in #1240
Now, when activating those, the acutal parameter is missing in the resulting command, only the options are added

**Expected behavior**
activating filters should add 
--vpp-nvvfx-denoise strength=0
and
--vpp-nvvfx-artifact-reduction mode=0

**How to reproduce the issue**
Enable the new filters, check if only strength=0 and/or mode=0 is added
Running the job fails

**Provide information**
![grafik](https://github.com/staxrip/staxrip/assets/69698996/d19475e4-6bb3-4ec6-bc8f-d8825e3dc055)

- Used StaxRip version
2.37.2

**Comment by Dendraspis** [comment]
Yeah, stupid bug, will be fixed tomorrow with a new release.

Thanks for the report!
