### ISSUE TITLE
Skipable output mod

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1285]
Hi,

I know in recent versions the default output mod changed from 8 to 2. But I'm old school and I prefer it on good old 8.

In older versions, if the output mod wasn't matched, it would throw an unskippable error, but today I simply pressed 'next' without realizing it, which bypassed the modulus error.
![sshot-2024-03-27- 13-21-00](https://github.com/staxrip/staxrip/assets/54937979/a39ddada-8fe4-41e3-80dc-98e2a1310aa0)

Is there any way to force it to be unskippable? Otherwise it doesn't make any sense.

**Comment by LazyNCoder** [comment]
That's correct, I disabled the "auto correct" because sometimes it changes way too much. Like, rounds 137 to 140.
I have to say, disabling this option is problematic. It crashes if the values are not mod 2 when you're using crop tool. Python doesn't accept it, and so on.

I still think it should be sensitive about what mod we chose. Especially now that mod 2 is default.

Anyway, Mr. Dendraspis sir, thank you for answering my basic questions with such a great attitude. I really appreciate it.

**Comment by Dendraspis** [comment]
I will have a look at when we can do about it...

**Comment by Dendraspis** [comment]
This could help to make everybody happy I guess:

<img width=500 src=https://github.com/staxrip/staxrip/assets/50659978/24c94c1c-dabc-401a-b674-6a17001446f9>

**Comment by LazyNCoder** [comment]
I can't thank you enough.

**Comment by LazyNCoder** [comment]
Hi,

I got two problems with this new option.

1- It doesn't work on batch encodes I guess. I have "auto crop" on always. cropped 138px top and bottom (=804) and went on. Didn't care about output mod which was 8.

2- If you check the new option, ignore the warning by clicking on the accept button, uncheck it, it doesn't warn you anymore. 

I enabled "Auto correct crop values" and it changed 138 to 140. Which I think is over-cropping.

**Comment by Dendraspis** [comment]
This option is just made to make the warning ignorable - the mechanism behind has not changed at all.

1. This is probably because you've disabled `Auto Correct Crop Values`. Auto Crop values are adjusted when this option is selected only.
2. That is something that could be improved, indeed. 🤔 

> I enabled "Auto correct crop values" and it changed 138 to 140. Which I think is over-cropping.

But it should match `Mod 8` then. So what would be your solution?

**Comment by LazyNCoder** [comment]
> But it should match Mod 8 then. So what would be your solution? Keeping a bit of the black bar?

Well yeah, 2px black bar is better than 2px of the image removed IMO

**Comment by Dendraspis** [comment]
I could add an option to decrease the crop rather than increase it.  🤔

**Comment by LazyNCoder** [comment]
Well, it's awesome to have an option to choose whatever the user wants. But I still think if it crops more than it should, it would make the result invalid. Either way, any fix for this is appreciated 🙂

**Comment by Dendraspis** [comment]
> Well yeah, 2px black bar is better than 2px of the image removed IMO

In your case 6px black bar vs 2px into the image.

> But I still think if it crops more than it should, it would make the result invalid

It somehow feels like we're talking about different things.  🤔 

You run `Auto Crop` and the outcome is odd or doesn't match the `Output Mod`, then `Auto Correct Crop Values` kicks in to match the `Output Mod` you have set. This means that the crop has to be extended.

I guess this is one reason why the very most users prefer using `Mod 2` as this makes you loose max. 1px while not keeping any black bars.

**Comment by Dendraspis** [comment]
> 2- If you check the new option, ignore the warning by clicking on the accept button, uncheck it, it doesn't warn you anymore.

This was changed in `v2.37.5`.

**Comment by Dendraspis** [comment]
As far I can everything should be solved with `v2.38.0`, so I close this now....
