### ISSUE TITLE
Log file - Media Info Target File

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1286]
There is a new bug. At the end of the log file, Media Info Target File is all on 1 line

----------------------- Media Info Target File -----------------------

Matroska : 1.93 GiB, 1 h 41 min2 132 kb/s, 1920*1040 (1.85:1), .............................. all on 1 line

---------------------------- Job Complete ----------------------------

**Comment by Dendraspis** [comment]
Please post the log file so I can see and verify the result.

**Comment by Zodler** [comment]
I don't understand, that's from the log file. I don't think the log file is going to give any information about why new lines are not inserted in that section.

Please just check any new log file you have created yourself, you don't see that?

**Comment by Dendraspis** [comment]
Yes, it does, because the received data is just written to the log file. So I need to know more.

Here is a test I ran:

![image](https://github.com/staxrip/staxrip/assets/50659978/8eb40fcc-cb12-4975-b618-a4d114c7c58c)
