### ISSUE TITLE
Options layout in Advanced Audio Options are displayed in a misleading way

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#129]
Hi again, Stax.
After following the issue #119 with user Vegax265, it appeared that the window "Advanced Audio Options" that you get when clicking on (Audio) Edit -> More, shows information in a confusing way:

![current](https://user-images.githubusercontent.com/17828567/76678527-70a30400-65e1-11ea-8673-1944edf67f2b.jpg)
Because the options for "loudnorm" mode are shown for ffmeg directly. They should be shown for ffmpeg -> loudnorm
Please consider this layout:

![whatshouldbe](https://user-images.githubusercontent.com/17828567/76678585-f2932d00-65e1-11ea-978f-75df8443b3d5.jpg)

And the dynaudionorm section remains unchanged:

![dynaudnorm](https://user-images.githubusercontent.com/17828567/76678772-4a7e6380-65e3-11ea-8f0e-cbc5b4bf7a80.jpg)

**Comment by Patman86** [comment]
Like that?

![grafik](https://user-images.githubusercontent.com/54327252/76689353-4f6c0300-6635-11ea-90f6-70efde648e7a.png)

![grafik](https://user-images.githubusercontent.com/54327252/76689358-5dba1f00-6635-11ea-8c4b-c90176e924e9.png)

![grafik](https://user-images.githubusercontent.com/54327252/76689366-71658580-6635-11ea-8731-34a969a8a76a.png)

**Comment by 44vince44** [comment]
Yes !!! beautiful ! thanks

**Comment by Patman86** [comment]
Uploaded a [fix](http://www.mediafire.com/file/fmpsdsqbf7dw64b/StaxRip_fix.7z/file)

**Comment by 44vince44** [comment]
Thank you very much Patman, I have tested this new options form, it is perfect!
I have also tested the commit from issue #123 and it seems good for me. I'll give my detailed results in the corresponding thread #123.

**Comment by stax76** [comment]
Thanks vince and Patman, I've merged it and updated the Changelog.

**Comment by 44vince44** [comment]
Thanks Stax!! and Patman!!
