### ISSUE TITLE
AviSynthShader Shader-x64.dll is not loading

### ISSUE THREAD

**Issue by AlFmla** [staxrip/staxrip#1299]
Many AVS filters, such as SMDegrain, SuperRes, require LoadPlugin("...\StaxRip\Apps\Plugins\AVS\AviSynthShader\Shader-x64.dll")
which is not loading! Error:
> Script Error
> 
> Cannot load file '.../StaxRip/Apps/Plugins/AVS/AviSynthShader/Shader-x64.dll'. Platform returned code 126:
> The specified module was not found.

**Comment by Dendraspis** [comment]
`Shader-x64.dll` seems to have issues when there is an underscope `_` in the path. Maybe it's also the reason for your issue?

**Comment by AlFmla** [comment]
No:
> Script Error
> 
> Cannot load file 'D:/StaxRip/Apps/Plugins/AVS/AviSynthShader/Shader-x64.dll'. Platform returned code 126:
> The specified module was not found.
> 
> (D:\StaxRip\temp\temp\bikenew.avs, line 22)
[bikenew.zip](https://github.com/staxrip/staxrip/files/14871928/bikenew.zip)
Don't you have such a problem? I have Win: 23H2 22631.3007

**Comment by Dendraspis** [comment]
The only issues regarding `Sharder-x64.dll` are those with the path and underscopes, but your paths are short and look good.

> I also had this problem on previous versions of StaxRip.

StaxRip itself has nothing to do with that problem, it's the tools.

> Nvidia RTX 3060 driver 31.0.15.5123

The graphics card is definitely enough to handle all scripts, but the driver version doesn't make sense as almost new NVidia drivers have versioning like `5xx.xx`. Maybe you should check and update this one.

**Comment by AlFmla** [comment]
Nvidia driver 551.23. So no one else has this problem?

**Comment by Dendraspis** [comment]
> So no one else has any problems with this tool?

The last time someone had problems was last year. Sadly most people don't give any feedback, so I can't tell you if there are some solutions or workarounds.

I have tried your call of `SMDegrain` and sadly I get no warnings.

Do you have the [Microsoft Visual C++ Redistributable Runtimes](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/) installed as some dependencies require them?
Do you use the latest StaxRip version?
In case you have updated, I hope that you didn't overwrite the existing StaxRip folder with another one...

I guess it has something to do with your environment. Maybe Anti-Virus protection, not enough execution or write permissions, missing OpenCL driver, ...

**Comment by AlFmla** [comment]
The main thing is that you have checked and you have no problems, thank you.
So I'm the only one with a problem, I'm closing the problem.

**Comment by Dendraspis** [comment]
I hope you can get it running.

You could try if VapourSynth works for you .... my last idea for now.  😕
