### ISSUE TITLE
NVEncC framerate halving option needs to be added

### ISSUE THREAD

**Issue by gnucian** [staxrip/staxrip#13]
Starting NVEncC 4.23, rigaya added the following framerate reducing option, but StaxRip doesn't seem to support it.

```
--vpp-select-every 2
--vpp-select-every 2,offset=1
```

Please see [here](https://github.com/rigaya/NVEnc/issues/89#issuecomment-437001206).

**Comment by stax76** [comment]
I've added it, I hope it's correct, don't have hardware to test it.

--vpp-select-every 5,offset=1,offset=2,offset=3
