### ISSUE TITLE
Wiki updates

### ISSUE THREAD

**Issue by trolleyboy** [staxrip/staxrip#1300]
Hi there,
Long time user, first time contributor. As requested on the [Usage](https://github.com/staxrip/staxrip/wiki/Usage) wiki page, I've volunteered to convert it to Markdown. I've forked the Wiki Repo. The converted Usage page is available here: https://github.com/trolleyboy/staxrip/wiki/Usage for review. You'll see I've made some minor formatting changes to keep some consistencies with other Wiki pages and make things a little clearer (e.g. menu buttons highlighted as code, block quotes as notes). 

I also was getting an error after initially cloning locally because the current wiki page https://github.com/staxrip/staxrip/wiki/Subtitles:-how-to-hardcode-them contains `:` in the name - which Windows doesn't like. So, I've renamed/moved the page to https://github.com/trolleyboy/staxrip/wiki/How-to-hardcode-subtitles.

I'm certainly no expert at using Staxrip, so I'm not "qualified" to write actual documentation. But, am happy to help out with formatting Wiki pages etc whenever I have time. I hope this first contribution is helpful. 

Cheers!

**Comment by trolleyboy** [comment]
Noticed that Home has a link to the "Subtitles: How to hardcode them" page, so updated that to the new page name too.

**Comment by Dendraspis** [comment]
Thank you very much.  I appreciate your help., it looks pretty good.  ❤️ 

As far as I remember you should be able to edit the Wiki directly without cloning it. In that case your name would appear as *Editor* of those pages which would be better than me copy&pasting your results.

Would you like to try it?

Just a little typo I found:
`Usage` :  `Video Encooding`  😁

**Comment by trolleyboy** [comment]
Ha ha, thanks @Dendraspis for the typo. I have installed a spell-checker 🕵️. I'm happy to edit the wiki directly. I'd assumed the wiki is closed for direct contributions. If you don't mind, could you please merge the wiki git repo from my fork to bring over these initial changes, like described [here](https://gist.github.com/omaraboumrad/35654da0a376c57a2e0ab4d92ad0c339#core-contributors). Seems we can't raise PRs for the wiki repo, so going forward I'll just edit directly.

**Comment by Dendraspis** [comment]
Finally the changes are merged.  😅 

Again, thank you for the help, I appreciate it!  ❤️
