### ISSUE TITLE
Hardcoded Subtitles - Python Exception using VapourSynth

### ISSUE THREAD

**Issue by Skin80** [staxrip/staxrip#1307]
**Describe the bug**

Staxrip is not loading the SubText.dll plugin for VapourSynth, when choosing to hardcode subtitles. Following error message occurs, after trying to add the Subtitle filter - "Python exception: No attribute with the name sub exists. Did you mistype a plugin namespace or forget to install a plugin?"
The bug can be circumvented by manually adding in the relevant code to load the plugin.

**Expected behavior**

Staxrip should load the relevant plugin, in this case SubText.dll, when choosing to add hardcoded subtitles.

**How to reproduce the issue**

1. Using a fresh/clean copy of Staxrip, switch from AVS filters to VapourSynth (VS) Filters.
2. Add a video Source file. In my case, I added in an MKV containing an HEVC video and EAC3 audio.
3. Click on Tools > Advanced > Add hardcoded subtitle (or use shortcut Ctrl + H).
4. Select relevant subtitle file. I added in an SRT file.
5. Wait for Staxrip to show error.
6. Open code editor. I usually double click one of the filters, in this case the Subtitle filter.
7. Add in the necessary code to load the SubText.dll plugin. In my case, I added in "core.std.LoadPlugin(r"D:\StaxRip-v2.37.5-x64\Apps\Plugins\VS\SubText\SubText.dll", altsearchpath=True)".
8. Profit!

**Provide information**

Error Message: "Python exception: No attribute with the name sub exists. Did you mistype a plugin namespace or forget to install a plugin?"

Staxrip version: v2.37.5

**Additional context**
Opening Apps > Manage shows all relevant apps and plugins with "Status: OK".

**Comment by Dendraspis** [comment]
Thanks for the detailled report, so I was able to find the reason very quickly.  

It will be fixed with the next release...
