### ISSUE TITLE
Error on Add Job (v2.37.6)

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1308]
**Describe the bug**
ArgumentException (v2.37.6)

Object must be a root directory ("C:\") or a drive letter ("C").

System.ArgumentException: Object must be a root directory ("C:\") or a drive letter ("C").
   at StaxRip.JobManager.SaveJobs(List`1 jobs)
   at StaxRip.JobManager.AddJob(String name, String path, Int32 position)
   at StaxRip.MainForm.AddJob(Boolean showConfirmation, String templateName, Boolean showAssistant, Int32 position)
   at StaxRip.MainForm.AddJob(Boolean showConfirmation, String templateName, Int32 position)
   at StaxRip.MainForm.AddJob(Boolean showJobsDialog, Int32 position)
   at StaxRip.MainForm.bnNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at StaxRip.UI.ButtonEx.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Dendraspis** [comment]
Do you use StaxRip on a network share or something like that ?

**Comment by noblemd00** [comment]
StaxRip program folder is on my LOCAL Samsung 980 PRO 1TB U: drive (4500/5000 MB/sec read/write). 
Temp files path for all templates is LOCAL "S:\VidTemp\%source_name%_temp\" (also a 1TB 980 PRO).
C: Drive is reserved for the operating system. 
StaxRip has been configured this way for a long time.
It has always worked properly before and worked before 2.37.6. 
What has changed? 

"Do you use StaxRip on a network share" 
Just curiosity - why restrict use of a network share drive?

**Comment by Dendraspis** [comment]
`U:` is mostly used for network drives, but ok.  🤔

I'll try to implement a more robust method for the next version...

> It has always worked properly before and worked before 2.37.6. What has changed?

A kind of a safety feature as written in the Changelog.

**Comment by noblemd00** [comment]
Okay, I guess you mean this "UI: Improve saving of Jobs List to avoid data loss on full disk" 

Did not equate that to this problem.

The drive problem actually started me thinking - I have 3 computers and would like to share the same Settings folder across all three. The 2.37.6 version DOES NOT work with an "Add Network Location" drive, but DOES work with a Mapped Network drive - No ADD JOB drive error. 

BTW: 

"U:" was used as the drive letter because I reserve X,Y, and Z for temporary mapped network drives and "S:" was chosen because "S"taxRip was the reason I added the high speed NVME data drive. I was going to put the StaxRip program folder on the "S" drive, but then decided to separate the TEMP drive from the PROGRAM drive to get any speed advantage. 

My in-house network storage consists of three Synology NAS connected to a 10GbE switch.
DS1823XS+/DX517 expansion (8 x 12TB drives and 5 x 8TB drives in 2 RAID 6 volumes),
DS1621XS+/DX517 expansion (Backup unit - 6 x 14TB drives and 5 x 8TB drives in 2 RAID 5 volumes),
and my original DS1520+ with DSM modified to use a 5GbE USB NIC (5 x 6TB drives in a RAID 5).

Average is 500 to 800 MB/sec read/write speeds to/from the 10G NASs.

**Comment by Dendraspis** [comment]
Indeed, there were not many changes in that version.


> The 2.37.6 version DOES NOT work with an "Add Network Location" drive, but DOES work with a Mapped Network drive - No ADD JOB drive error.

This is right, I haven't thought about the possibility using a network share to run StaxRip. I would prefer running separated instances, but it's up to you.
The next release will have a fix for that, so the new feature will also work on other drive types like network shares. In my test it worked, but feel free to complain if it's not working for you by re-opening this issue. 

Btw:  Very nice setup.  👍
