### ISSUE TITLE
Auto crop for Dolby Vision does not work

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1311]
i have latest version of app and try to do auto crop. When i hit on keyboard "A" nothing has happened.
when i do manaul crop i have got this warning:

![image](https://github.com/staxrip/staxrip/assets/34553588/9731598b-831f-49bf-a2c8-ff288f56d328)

BTW: Auto crop for the same file works fine in app version 3.34 without any warning..

**Comment by Dendraspis** [comment]
In your `_temp`-subfolder there should be a file named `HDRDVmetadata_L5.json`. Please post its content and the file itself.

> BTW: Auto crop for the same file works fine in app version 3.34 without any warning..

Indeed, therefore the result was broken.  😕

**Comment by madey83** [comment]
[HDRDVmetadata_L5.json](https://github.com/staxrip/staxrip/files/14987683/HDRDVmetadata_L5.json)

**Comment by Dendraspis** [comment]
Everything is working properly, you just have to decide what to do with the last ~5000 frames.

I suggest reading [this guide](https://github.com/staxrip/staxrip/wiki/Encoding-Dolby-Vision-with-StaxRip#cropping) I was linking before with various releases.

**Comment by madey83** [comment]
is it mean that i need to crop in StaxRip every time DV metada when i crop it by other soft.?

**Comment by Dendraspis** [comment]
Seems you haven't read the guide?!

You have to make a choice:
Do not crop or crop the video and potentially destroy the visual experience of the last 5000 frames. In case you want to crop, the guide tells you how to do that.

**Comment by madey83** [comment]
thx.... issue solved
