### ISSUE TITLE
Network Path as default Target

### ISSUE THREAD

**Issue by netleader** [staxrip/staxrip#132]
With 2.0.6.0 I could set my default target path to \\Server\Path since version 2.0.8.0 it replaces the two \\ with one \ and I always have to add an additional one, even though it shows two in the settings.

**Comment by stax76** [comment]
I don't know git good enough to find out which commits contain \\, maybe you can describe the issue more detailed or maybe show me how to reproduce it. I don't have access to a network, I used to know how to create such a path on my PC but I've forgotten it.

**Comment by noblemd00** [comment]
v 2.0.8.0
Not a problem for me:

Just created new option entry: "\\\TMSY\T8.TVActive" without a problem

**Comment by stax76** [comment]
It's fixed in the newest build:

2.0.9.10

https://github.com/staxrip/staxrip/blob/master/Changelog.md

https://staxrip.readthedocs.io/intro.html#download
