### ISSUE TITLE
error at saving after trim 

### ISSUE THREAD

**Issue by MasY30** [staxrip/staxrip#1323]
Frame Mismatch (v2.38.0)

Target file has 28948 frames, but should have 34321 frames!

StaxRip.ErrorAbortException: Target file has 28948 frames, but should have 34321 frames!
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 464

D:\Code\Github\staxrip\staxrip\Source\General\ this is not my pc path...

**Comment by Dendraspis** [comment]
Duplicate to #1315  and partly #1322.

Please note, that the encode should be fine, it's just the error message that assumes wrong target data.
The `Frame Mismatch` can be disabled in the project options.

A fix will be released soon....
