### ISSUE TITLE
From StaxRip v2.38.2 til the latest (v2.38.5) DGDecNV is not working anymore...

### ISSUE THREAD

**Issue by AdPatat** [staxrip/staxrip#1326]
Its giving me a path error and StaxRip stop working.
In StaxRip v2.38.0 everyting works fine. I'm still hope that you will DGDecNV intergrate in StaxRip again because its free now...

GrTz
Ad

**Comment by Dendraspis** [comment]
First question:  You know, that you can edit your posts?  😉 
I have deleted your first issue...

So where and how did you define the path as `DGDecNV` is not included anymore.
Also can you show a screenshot of the error message?

**Comment by AdPatat** [comment]
The path is oke for v2.38.0 and works fine, but in v2.38.2 I get this...

![StaxRipv2 38 2](https://github.com/staxrip/staxrip/assets/32195020/0c8a11ba-b582-48d6-ae01-1f8060438948)

**Comment by AdPatat** [comment]
Watch the missing \ between Settings and Plugins

**Comment by Dendraspis** [comment]
Yes, and the path itself is wrong.

I will check that...

**Comment by Dendraspis** [comment]
So I guess you're using it as Command Line Demuxer?  Can you show me the command?

Or did you already fix it?

**Comment by AdPatat** [comment]
[staxrip_2.38.0.log](https://github.com/staxrip/staxrip/files/15113238/staxrip_2.38.0.log)
[staxrip_2.38.2.log](https://github.com/staxrip/staxrip/files/15113239/staxrip_2.38.2.log)

The two logfiles, first went oke, second wrong

**Comment by Dendraspis** [comment]
Okay, so you had to set up `DGIndexNV` in `Settings » Preprocessing`. Can you post a screenshot of that settings? ..meaning after you selected the entry and clicked on `Edit`.

**Comment by AdPatat** [comment]
![Settings_v2 38 0](https://github.com/staxrip/staxrip/assets/32195020/14fb9015-2b59-48ac-b384-81f7d2124358)
![Settings_v2 38 2](https://github.com/staxrip/staxrip/assets/32195020/f987f715-08ed-40c3-acf1-32d69f60a429)

Here you go

**Comment by Dendraspis** [comment]
Okay, here we go...

There is the command consisting of `%settings_dir%Plugins`. You have to change it into `%settings_dir%\Plugins`.

This is something that has changed in `v2.38.1`, that I was not aware in terms of its dimensions.  🫤

**Comment by AdPatat** [comment]
Let's round up...

IT WORKS... Thanks for the quick response 🥇

**Comment by AdPatat** [comment]
Please don't forget to adjust (y)our manual at:
[https://github.com/staxrip/staxrip/wiki/How-to-register-DGDecNV%28DGSource-and-DGIndexNV%29-in-StaxRip](url)

**Comment by Dendraspis** [comment]
Thanks for the feedback!

Wiki page is updated.  😁
