### ISSUE TITLE
Overflow Exception

### ISSUE THREAD

**Issue by kliffgomel** [staxrip/staxrip#1327]
An overflow error occurs when opening a file (Source - Single File) for video sample awaken-girl.4K.HDR.DV.mkv :

System.OverflowException: Overflow resulting from an arithmetic operation.
    at StaxRip.GlobalClass.CorrectCropMod(ForceOutputModDirection direction, Boolean force) at D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 1592
    at StaxRip.GlobalClass.SetCrop(Int32 left, Int32 top, Int32 right, Int32 bottom, ForceOutputModDirection direction, Boolean force) at D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 1429
    at StaxRip.MainForm.AutoCrop() at D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2642
    at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) at D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2392
[awaken-girl.4K.HDR.DV_new_staxrip.log](https://github.com/staxrip/staxrip/files/15109955/awaken-girl.4K.HDR.DV_new_staxrip.log)

**Comment by Dendraspis** [comment]
Can you also share the content of the `HDRDVmetadata_L5.json` file in the `_temp` folder?

**Comment by kliffgomel** [comment]
[HDRDVmetadata_L5.json](https://github.com/staxrip/staxrip/files/15111234/HDRDVmetadata_L5.json)

**Comment by Dendraspis** [comment]
As the source is pretty small, is there a chance you can share that file with me?

There is no crop to be set and code-wise I can't find any reason for an OverflowException, even when I force a cropping that is not allowed.  😕

**Comment by kliffgomel** [comment]
https://mega.nz/file/DGJU1BzL#4jtSK9Kvx2N6WuNdnQXyOi4NFEqLIymLrmSK5R8WilY
from https://kodi.wiki/view/Samples

**Comment by Dendraspis** [comment]
Thanks a lot, with this sample I was able to find the culprit finally.  👍 

To fix this issue temporarily, disable the `Automatic` Threshold mode in the Project Options .

The next release is coming in a few days...

**Comment by kliffgomel** [comment]
In the new version of staxrip v2.38.6 the error still occurs.
[awaken-girl.4K.HDR.DV_new_staxrip.log](https://github.com/staxrip/staxrip/files/15148803/awaken-girl.4K.HDR.DV_new_staxrip.log)

**Comment by Dendraspis** [comment]
I know, it is already fixed in `v2.38.7`, but because many users complained about the quick fixes and frequent releases, you have to wait a few days.  😕 

In the meantime you can turn off `AutoCrop` at opening in the Project Options and/or switch the method from `Automatic` to `Manual`.
