### ISSUE TITLE
v2.38.5 Not asking where to put Settings

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1328]
First copied v2.38.5 exe only to v2.38 and it erased all my settings.

Then I deleted everything and did a clean install of StaxRip-v2.38.5-x64.7z (extracted to an empty folder)

Running StaxRip.exe is not asking me where to put the settings.

**Comment by Dendraspis** [comment]
I guess you have replaced `StaxRip.exe` and also renamed the folder it's in?

**Comment by Zodler** [comment]
No I didn't rename the folder. Why should I rename the folder when updating.

**Comment by Dendraspis** [comment]
I have tested it and also let another user test it:  no issues.
When you replace the exe file and start StaxRip, you definitely get asked about your settings path.

Not sure what happened, but most likely you accidentally hit `Enter` oder clicked on a button.
You can check the used `Settings` folder location by

1. Open `RegEdit` and check out `HKEY_CURRENT_USER\SOFTWARE\StaxRip\SettingsLocation`
2. Open `StaxRip` and go to `Tools » Folders » Settings`

**Comment by Zodler** [comment]
When you replace the exe file and start StaxRip, you should not get asked about your settings path.
That is not the default behavior and it was never like this before. When I replaced the exe in the past,
it did not ask and used the proper settings location.

So I went to
HKEY_CURRENT_USER\SOFTWARE\StaxRip\SettingsLocation
and cleaned it

There where 3 different entries. Interestingly, not only you put the location of settings there but also the location of the staxrip.
So in theory you could have several staxrips with different settings.

It had changed the folder to C:\ProgramData\Staxrip.

But I cleaned it and now it is pointing to the correct location.

**Comment by Zodler** [comment]
I'm going to do more tests to cause this again because what happened today should not happen. Losing all the settings.

**Comment by Dendraspis** [comment]
> When you replace the exe file and start StaxRip, you should not get asked about your settings path.

Basically yes, but in that case you're overwriting one version with another one. It's the shortcut to downloading and extracting the whole package and then copying the settings over to the new version. 

> That is not the default behavior and it was never like this before. When I replaced the exe in the past, it did not ask and used the proper settings location.

That's right, sadly a part of an improvement that *interferes*, but StaxRip won't ask anymore.

> So in theory you could have several staxrips with different settings.

Yes, that's the idea. You can also run different versions in parallel at the same time, they just have to have different `Settings` folders.

> because what happened today should not happen. Losing all the settings.

Definitely, but this is also not what should and would happen normally. Something must have happened...
Btw:  In case you still have the `Settings` folder, you should check out the `Backup` subfolder.

**Comment by Dendraspis** [comment]
It's not that important, because the locations are cleaned up automatically by StaxRip on each startup.

> So maybe put a link in the software to open it by the user, the same way you can open the settings folder.

In general a very nice idea, but not easy to implement, because `RegEdit` does not provide that possibility. But I will think about that...

**Comment by Zodler** [comment]
> It's not that important, because the locations are cleaned up automatically by StaxRip on each startup.

What does that mean, it's not clear. What is cleaned up exactly and when? Are you saying that when you run a staxrip it will also cleanup the locations of other staxrips?

> In general a very nice idea, but not easy to implement, because `RegEdit` does not provide that possibility. But I will think about that...

Maybe just show the path on screen, copy it to clipboard.

**Comment by Dendraspis** [comment]
Yes.

Nah. You have dozens of apps installed that don't inform you and on top leave registry entries and files behind after deinstallation. 

Did you update to `v2.38.6` ? Did StaxRip ask you about the location?

**Comment by Zodler** [comment]
Yes, but you want to be better than other apps I suppose. I personally would aspire to be better. Without that address I couldn't have solved the problem. Or maybe add an entry to clean staxrip data from registry.

I did a test with v2.38.5 to v2.38.6. It did not ask as it has always been.

**Comment by Dendraspis** [comment]
I keep that idea in mind, but I will close this issue for now as the problem should be done...
