### ISSUE TITLE
Event Command macro %target_dir% missing "\" at the end.

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1329]
**Describe the bug**
v.2.38.5  

NOTE:
See Event command info below.
Is the Event Command macro change an error or a permanent (purposeful) change?

Encoded file with TARGET (example) location of: \\10.15.1.47\TV\Active\W\Show.Folder.Name\0107.Episode.Name.mp4

This file ended up in with the name  ...\W\Folder.Names0107.VideofileName.mp4 - NOTE: missing "\" subfolder separator between "Folder.Name" and "0107".

I verified that the Target file location/path was correct.

*********************************************************

I have an Event command active that changes the target file name to add "HDV" to the target name if the Template name contains "HDV" (see picture). "HDV" is my designation for HDR+DoVi encoded video.

%target_dir%%target_name%.%target_height%p.HDV.%encoder_ext%.%muxer_ext%

This Event command has always worked properly before. Now it seems %target_dir%   does not contain the final backslash

Previously %target_dir% had a final backslash at the end.

I have temporarily changed the Event Command (added a backslash between %target_dir% and %target_name% )

%target_dir%(backslash)%target_name%.%target_height%p.HDV.%encoder_ext%.%muxer_ext%

<img width="441" alt="240425 111418" src="https://github.com/staxrip/staxrip/assets/16325865/983c6d17-70b7-4b63-a002-8b4b4d07a80b">

********************************************************
**Expected behavior**
The finished file should end up in the proper folder with the proper name regardless of the file or path name complexity.

**How to reproduce the issue**

Encode a file and use the following Event command:

• Match All 
Before Processing
Template Name Contains HDV

%target_dir%%target_name%.%target_height%p.HDV.%encoder_ext%.%muxer_ext%

**Comment by Dendraspis** [comment]
Indeed that is something I didn't have in mind when I released it, meaning without any notes about the missing backslash.  🙄 
But this is now the way to go, so as you've already found out, the backslash has to be there since `v2.38.1`. 

To be honest this is also better for reading and makes it easier to use in different approaches where the backslash at the end is not wanted.

Thanks to point that out, as it caused already problems like in #1326 .

**Comment by wrzlpete** [comment]
Ah great, I wasn't the only one getting old script errors thrown into my face when going from 2.38.0 to 2.38.5 :D
So this stays, it's "safe" to adjust the templates to include the backlash from now on?

**Comment by Dendraspis** [comment]
It is. No matter what happens next, the ending backslash won't be included anymore in the directory name.

**Comment by wrzlpete** [comment]
Great, thx for the info!
