### ISSUE TITLE
2.38.6 error messages

### ISSUE THREAD

**Issue by johnvick** [staxrip/staxrip#1331]
Open a file as usual and get the following error message: 

Illegal characters in path.
File: C:\Staxrip\Apps\Support\MKVToolNix\mkvextract.exe
Arguments: --ui-language en \\192.168.2.1\storage\Episode.S01E04.720p.mkv tracks 2:d:\temp\Episode.S01E04.720p_temp\ID1_[en].srt 3:"d:\temp\Episode.S01E04.720p_temp\ID2_[en] {SDH}.srt" 1:"d:\temp\Episode.S01E04.720p_temp\ID1 English [en].eac3"

File does not encode - this is the log:

```
------------------------- System Environment -------------------------

StaxRip    : v2.38.6
Settings   : v2.36
Windows    : Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : English (New Zealand)
CPU        : AMD Ryzen 9 5900X 12-Core Processor
RAM        : 32GB
GPU        : NVIDIA GeForce RTX 3070 Ti
Resolution : 2560 x 1440
DPI        : 96
Code Page  : 1252

----------------------- Media Info Source File -----------------------

\\192.168.2.1\storage\Episode.S01E04.720p.mkv

General
Complete name            : \\192.168.2.1\storage\Episode.S01E04.720p.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 601 MiB
Duration                 : 26 min 21 s
Overall bit rate mode    : Variable
Overall bit rate         : 3 185 kb/s
Frame rate               : 25.000 FPS
Writing application      : mkvmerge v83.0 ('Circle Of Friends') 64-bit
Writing library          : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L3.1
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 26 min 21 s
Bit rate mode            : Variable
Bit rate                 : 2 926 kb/s
Maximum bit rate         : 6 375 kb/s
Width                    : 1 280 pixels
Height                   : 720 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.127
Time code of first frame : 00:00:00;00
Stream size              : 552 MiB (92%)
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : E-AC-3
Format/Info              : Enhanced AC-3
Commercial name          : Dolby Digital Plus
Codec ID                 : A_EAC3
Duration                 : 26 min 21 s
Bit rate mode            : Constant
Bit rate                 : 256 kb/s
Channel(s)               : 6 channels
Channel layout           : L R C LFE Ls Rs
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 48.3 MiB (8%)
Language                 : English
Service kind             : Complete Main
Default                  : Yes
Forced                   : No

Text #1
ID                       : 3
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Duration                 : 26 min 16 s
Bit rate                 : 79 b/s
Frame rate               : 0.363 FPS
Count of elements        : 572
Stream size              : 15.2 KiB (0%)
Language                 : English
Default                  : No
Forced                   : No

Text #2
ID                       : 4
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Duration                 : 26 min 16 s
Bit rate                 : 90 b/s
Frame rate               : 0.389 FPS
Count of elements        : 613
Stream size              : 17.4 KiB (0%)
Title                    : SDH
Language                 : English
Default                  : No
Forced                   : No

Menu
00                       : 00:00.000                             : en:Main
00                       : 25:49.280                             : en:Credits

------------------------------ Demux MKV ------------------------------

mkvextract 83.0

C:\Staxrip\Apps\Support\MKVToolNix\mkvextract.exe --ui-language en \\192.168.2.1\storage\Episode.S01E04.720p.mkv tracks 2:d:\temp\Episode.S01E04.720p_temp\ID1_[en].srt 3:"d:\temp\Episode.S01E04.720p_temp\ID2_[en] {SDH}.srt" 1:"d:\temp\Episode.S01E04.720p_temp\ID1 English [en].eac3"

Start:    7:41:39 am
End:      7:41:49 am
Duration: 00:00:09

------------------------------ Exception ------------------------------

System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 315
   at StaxRip.mkvDemuxer.Demux(String sourcefile, IEnumerable`1 audioStreams, IEnumerable`1 subtitles, AudioProfile ap, Project proj, Boolean onlyEnabled, Boolean videoDemuxing, Boolean overrideExisting, String title, Boolean useStreamName) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 959
   at StaxRip.mkvDemuxer.Run(Project proj) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 752
   at StaxRip.MainForm.Demux() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 3681
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2241
```

**Comment by Dendraspis** [comment]
Please try using fresh settings as this should be no problem anymore in v`2.38.6` - at least I can't reproduce it.

**Comment by johnvick** [comment]
Thanks - I tried deleting the settings.dat file and restarting - is that what you mean? I still got the errors as above.

**Comment by Dendraspis** [comment]
No, you should delete the whole `Settings` folder.

Best approach:
Extract the new version, start it, choose the first Settings option (which creates a `Settings` subfolder) and set it up manually while you run the old version, so you can check the old settings.

StaxRip is very flexible with a lot of advantages, sadly this causes issues when you use a new version with old settings.
Exceptions:
`v2.38.x` is compatible to `v2.38.0`
`v2.37.x` is compatible to `v2.37.0`
...and so on.

**Comment by johnvick** [comment]
Thanks for your help. I extracted new version, set the settings location. did nothing more. I add a video file and get "Illegal characters in path" as above. I set up a new encoding profile, load the video file and again same error.

v2.38 is running fine, I am a happy to continue with it.

**Comment by Dendraspis** [comment]
Please do me a favor:
You're using `v2.38.0` now, right?  So please start StaxRip, open the same file again and after opening, please share the log file with me.

For me everything works fine, so where is the problem?

<img width=700 src=https://github.com/staxrip/staxrip/assets/50659978/cd26a478-643d-4502-bae5-8098dbef91f2>

**Comment by johnvick** [comment]
------------------------- System Environment -------------------------

StaxRip    : v2.38.0
Settings   : v2.36
Windows    : Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : English (New Zealand)
CPU        : AMD Ryzen 9 5900X 12-Core Processor
RAM        : 32GB
GPU        : NVIDIA GeForce RTX 3070 Ti
Resolution : 2560 x 1440
DPI        : 96
Code Page  : 1252

----------------------- Media Info Source File -----------------------

D:\temp\Episode.S01E04.mkv

General
Complete name            : D:\temp\Episode.S01E04.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 601 MiB
Duration                 : 26 min 21 s
Overall bit rate mode    : Variable
Overall bit rate         : 3 185 kb/s
Frame rate               : 25.000 FPS
Writing application      : mkvmerge v83.0 ('Circle Of Friends') 64-bit
Writing library          : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L3.1
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 26 min 21 s
Bit rate mode            : Variable
Bit rate                 : 2 926 kb/s
Maximum bit rate         : 6 375 kb/s
Width                    : 1 280 pixels
Height                   : 720 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.127
Time code of first frame : 00:00:00;00
Stream size              : 552 MiB (92%)
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : E-AC-3
Format/Info              : Enhanced AC-3
Commercial name          : Dolby Digital Plus
Codec ID                 : A_EAC3
Duration                 : 26 min 21 s
Bit rate mode            : Constant
Bit rate                 : 256 kb/s
Channel(s)               : 6 channels
Channel layout           : L R C LFE Ls Rs
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 48.3 MiB (8%)
Language                 : English
Service kind             : Complete Main
Default                  : Yes
Forced                   : No

Text #1
ID                       : 3
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Duration                 : 26 min 16 s
Bit rate                 : 79 b/s
Frame rate               : 0.363 FPS
Count of elements        : 572
Stream size              : 15.2 KiB (0%)
Language                 : English
Default                  : No
Forced                   : No

Text #2
ID                       : 4
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Duration                 : 26 min 16 s
Bit rate                 : 90 b/s
Frame rate               : 0.389 FPS
Count of elements        : 613
Stream size              : 17.4 KiB (0%)
Title                    : SDH
Language                 : English
Default                  : No
Forced                   : No

Menu
00                       : 00:00.000                             : en:Main
00                       : 25:49.280                             : en:Credits

------------------------------ Demux MKV ------------------------------

mkvextract 83.0

C:\Staxrip\Apps\Support\MKVToolNix\mkvextract.exe --ui-language en D:\temp\Episode.S01E04.mkv tracks 2:d:\temp\Episode.S01E04_temp\ID1_[en].srt 3:"d:\temp\Episode.S01E04_temp\ID2_[en] {SDH}.srt" 1:"d:\temp\Episode.S01E04_temp\ID1 English [en].eac3"

Extracting track 1 with the CodecID 'A_EAC3' to the file 'd:\temp\Episode.S01E04_temp\ID1 English [en].eac3'. Container format: Dolby Digital Plus (E-AC-3)
Extracting track 2 with the CodecID 'S_TEXT/UTF8' to the file 'd:\temp\Episode.S01E04_temp\ID1_[en].srt'. Container format: SRT text subtitles
Extracting track 3 with the CodecID 'S_TEXT/UTF8' to the file 'd:\temp\Episode.S01E04_temp\ID2_[en] {SDH}.srt'. Container format: SRT text subtitles

Start:    5:52:57 pm
End:      5:53:04 pm
Duration: 00:00:06

General
Complete name         : d:\temp\Episode.S01E04_temp\ID1 English [en].eac3
Format                : E-AC-3
Format/Info           : Enhanced AC-3
Commercial name       : Dolby Digital Plus
File size             : 48.3 MiB
Duration              : 26 min 21 s
Overall bit rate mode : Constant
Overall bit rate      : 256 kb/s

Audio
Format                : E-AC-3
Format/Info           : Enhanced AC-3
Commercial name       : Dolby Digital Plus
Duration              : 26 min 21 s
Bit rate mode         : Constant
Bit rate              : 256 kb/s
Channel(s)            : 6 channels
Channel layout        : L R C LFE Ls Rs
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 SPF)
Compression mode      : Lossy
Stream size           : 48.3 MiB (100%)
Service kind          : Complete Main

------------------------- Demux xml chapters -------------------------

mkvextract 83.0

C:\Staxrip\Apps\Support\MKVToolNix\mkvextract.exe D:\temp\Episode.S01E04.mkv --ui-language en chapters d:\temp\Episode.S01E04_temp\Episode.S01E04_chapters.xml

File 'D:\temp\Episode.S01E04.mkv': container: Matroska
Track ID 0: video (AVC/H.264/MPEG-4p10)
Track ID 1: audio (E-AC-3)
Track ID 2: subtitles (SubRip/SRT)
Track ID 3: subtitles (SubRip/SRT)
Chapters: 2 entries

Start:    5:53:04 pm
End:      5:53:10 pm
Duration: 00:00:06

------------------------- Demux ogg chapters -------------------------

mkvextract 83.0

C:\Staxrip\Apps\Support\MKVToolNix\mkvextract.exe D:\temp\Episode.S01E04.mkv --ui-language en chapters d:\temp\Episode.S01E04_temp\Episode.S01E04_chapters.txt --simple

File 'D:\temp\Episode.S01E04.mkv': container: Matroska
Track ID 0: video (AVC/H.264/MPEG-4p10)
Track ID 1: audio (E-AC-3)
Track ID 2: subtitles (SubRip/SRT)
Track ID 3: subtitles (SubRip/SRT)
Chapters: 2 entries

Start:    5:53:10 pm
End:      5:53:16 pm
Duration: 00:00:06

---------------------- Indexing using ffmsindex ----------------------

C:\Staxrip\Apps\Plugins\Dual\ffms2\ffmsindex.exe D:\temp\Episode.S01E04.mkv d:\temp\Episode.S01E04_temp\temp.ffindex

Writing index... done.

Start:    5:53:16 pm
End:      5:53:23 pm
Duration: 00:00:06

---------------------------- Configuration ----------------------------

Template                : JV 265 - AAC
Video Encoder           : NVEnc
Video Encoder Profile   : NVEncC (Nvidia) | H.265
Container/Muxer Profile : MKV (mkvmerge)
+++++
Process Priority        : Idle
Delete Temp Files       : Permanent

--------------------------- AviSynth Script ---------------------------

AddAutoloadDir("C:\Staxrip\Apps\FrameServer\AviSynth\plugins")

LoadPlugin("C:\Staxrip\Apps\Plugins\Dual\ffms2\ffms2.dll")
tcFile = "d:\temp\Episode.S01E04_temp\Episode.S01E04_timestamps.txt" # timestamps file path
Exist(tcFile) ? FFVideoSource("D:\temp\Episode.S01E04.mkv", cachefile="d:\temp\Episode.S01E04_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("D:\temp\Episode.S01E04.mkv", cachefile="d:\temp\Episode.S01E04_temp\temp.ffindex")

------------------------- Source Script Info -------------------------

Width     : 1280
Height    : 720
Frames    : 39544
Time      : 26:21.760
Framerate : 25 (25/1)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 1280
Height    : 720
Frames    : 39544
Time      : 26:21.760
Framerate : 25 (25/1)
Format    : YUV420P8

---------------------- Media Info Audio Source 1 ----------------------

General
Complete name         : d:\temp\Episode.S01E04_temp\ID1 English [en].eac3
Format                : E-AC-3
Format/Info           : Enhanced AC-3
Commercial name       : Dolby Digital Plus
File size             : 48.3 MiB
Duration              : 26 min 21 s
Overall bit rate mode : Constant
Overall bit rate      : 256 kb/s

Audio
Format                : E-AC-3
Format/Info           : Enhanced AC-3
Commercial name       : Dolby Digital Plus
Duration              : 26 min 21 s
Bit rate mode         : Constant
Bit rate              : 256 kb/s
Channel(s)            : 6 channels
Channel layout        : L R C LFE Ls Rs
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 SPF)
Compression mode      : Lossy
Stream size           : 48.3 MiB (100%)
Service kind          : Complete Main

----------------------------- Find Gain 1 -----------------------------

ffmpeg N-113112-gf5f414d9c4-x64-gcc13.2.0

C:\Staxrip\Apps\FrameServer\AviSynth\ffmpeg.exe -i "d:\temp\Episode.S01E04_temp\ID1 English [en].eac3" -sn -vn -hide_banner -af volumedetect -f null NUL

[eac3 @ 00000193e5549640] Estimating duration from bitrate, this may be inaccurate
Input #0, eac3, from 'd:\temp\Episode.S01E04_temp\ID1 English [en].eac3':
  Duration: 00:26:21.73, start: 0.000000, bitrate: 256 kb/s
  Stream #0:0: Audio: eac3, 48000 Hz, 5.1(side), fltp, 256 kb/s
[Parsed_volumedetect_0 @ 00000193e6ec40c0] n_samples: 0
Stream mapping:
  Stream #0:0 -> #0:0 (eac3 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf60.20.100
  Stream #0:0: Audio: pcm_s16le, 48000 Hz, 5.1(side), s16, 4608 kb/s
      Metadata:
        encoder         : Lavc60.36.100 pcm_s16le
[Parsed_volumedetect_0 @ 00000193e6f0a900] n_samples: 455537664
[Parsed_volumedetect_0 @ 00000193e6f0a900] mean_volume: -32.3 dB
[Parsed_volumedetect_0 @ 00000193e6f0a900] max_volume: -2.9 dB
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_2db: 1
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_3db: 51
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_4db: 322
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_5db: 2449
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_6db: 15853
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_7db: 28784
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_8db: 44132
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_9db: 64028
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_10db: 99696
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_11db: 152786
[Parsed_volumedetect_0 @ 00000193e6f0a900] histogram_12db: 227147
[out#0/null @ 00000193e6e7e440] video:0kB audio:889722kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

Start:    5:53:42 pm
End:      5:53:51 pm
Duration: 00:00:09

----------------------- Convert EAC3 to FLAC 1 -----------------------

ffmpeg N-113112-gf5f414d9c4-x64-gcc13.2.0

C:\Staxrip\Apps\FrameServer\AviSynth\ffmpeg.exe -i "d:\temp\Episode.S01E04_temp\ID1 English [en].eac3" -af volume=2.9dB -y -hide_banner -ac 6 "d:\temp\Episode.S01E04_temp\ID1 English [en]_1368249155.flac"

[eac3 @ 00000241322296c0] Estimating duration from bitrate, this may be inaccurate
Input #0, eac3, from 'd:\temp\Episode.S01E04_temp\ID1 English [en].eac3':
  Duration: 00:26:21.73, start: 0.000000, bitrate: 256 kb/s
  Stream #0:0: Audio: eac3, 48000 Hz, 5.1(side), fltp, 256 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (eac3 (native) -> flac (native))
Press [q] to stop, [?] for help
[flac @ 0000024133c16c40] encoding as 24 bits-per-sample, more is considered experimental. Add -strict experimental if you want to encode more than 24 bits-per-sample
Output #0, flac, to 'd:\temp\Episode.S01E04_temp\ID1 English [en]_1368249155.flac':
  Metadata:
    encoder         : Lavf60.20.100
    WAVEFORMATEXTENSIBLE_CHANNEL_MASK: 0x3f
  Stream #0:0: Audio: flac, 48000 Hz, 5.1, s32 (24 bit), 128 kb/s
      Metadata:
        encoder         : Lavc60.36.100 flac
[out#0/flac @ 0000024133c5fe00] video:0kB audio:580724kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001401%

Start:    5:53:51 pm
End:      5:54:03 pm
Duration: 00:00:11

**Comment by Dendraspis** [comment]
Thanks, but that's not fair.  😅 

In the new version you've used `\\192.168.2.1\storage` whereas the working old version opens a file in `D:\temp`.
Then you've also removed the `.720p` from the file name.

Sadly this makes it impossible to find the difference.  😕

**Comment by johnvick** [comment]
Sorry, it is the same file, the locations have changed as I have spent the half the day trying to work this out. And earlier testing eliminated the file as the source of error.

**Comment by Dendraspis** [comment]
No problem, sadly that was what I would have needed. But I guess I found the culprit anyway....

**Comment by Dendraspis** [comment]
Yes, I guess I have found the problem.  Thanks for your help!  ❤️ 

The fix comes with the next release. Please feel free to report back if you still encounter such issues....
