### ISSUE TITLE
Error message after encoding a project that has been cut / trimmed

### ISSUE THREAD

**Issue by Flyk3** [staxrip/staxrip#1334]
Hi,
I currently often get the following error message when I have trimmed video:

> --------------------------- Frame Mismatch ---------------------------
> WARNING: Target file has 79953 frames, but should have 80004 frames!
> Encoding was probably terminated at 99,9% with a mismatch of 51 frames!

I am still using v.2.38.0, but I think the problem already existed in 2.37. I encode from HEVC to AV1 with the AOMEnc encoder and use the cut function in the preview window.

So far I have not noticed any errors in the finished video. The video is in sync with the sound and I can't find any errors at the beginning or end.

As an example, here is the log from one of the projects:
[test_new_staxrip.log](https://github.com/staxrip/staxrip/files/15162963/test_new_staxrip.log)

Greetings

**Comment by Dendraspis** [comment]
This was already solved in `v2.38.2`, please update and the problem should be gone.
