### ISSUE TITLE
HDR to SDR using Placebo, HDRTools

### ISSUE THREAD

**Issue by ShubhamVimal** [staxrip/staxrip#1335]
I'm trying to convert 4K HDR video to SDR using libplacebo, HDRTools, but I'm not getting the desired result.
(SVT-AV1 Encoder)

Using Placebo, getting the following error -:

![image](https://github.com/staxrip/staxrip/assets/51742764/e68a60fd-315d-4dbb-9166-4254353b285e)

Using HDRTools, getting following pop up -:

![image](https://github.com/staxrip/staxrip/assets/51742764/d2742438-2902-48f7-9c47-5e1d5b02af5f)
 
What is HDR max luminance level ? How to decide what value to put ?
In the metadata of the file, there is a line which says ---> Mastering display luminance : min: 0.0200 cd/m2, max: 1200 cd/m2 , so I've tried to put 1200 cd/m2 as max luminance level, but after encoding the video is full of brightness.

![image](https://github.com/staxrip/staxrip/assets/51742764/16a1a340-3966-452c-8bb4-bea04c38765f)

Source file-: https://mega.nz/file/Sfw1hDpK#ErxCOpQDVjcI1gq6ZbX3vIfdtXZompkFe0jq47EhR2o

I hope you can help me solve this issue, I'm not an expert in scripting etc.

**Comment by Dendraspis** [comment]
How does you `Placebo` script looks like?

**Comment by ShubhamVimal** [comment]
Where to find Placebo script ? I don't know anything related to AVS or VS. Don't mind I'm a noob.

**Comment by Dendraspis** [comment]
I meant the filter call, double-click on the filter lists on the left or right-click and select `Edit Code`:
<img width=300 src=https://github.com/staxrip/staxrip/assets/50659978/f6ca4424-7442-48bd-a2c7-535f717bca3e>

**Comment by ShubhamVimal** [comment]
Ohh Ok sorry here you go -: 
![image](https://github.com/staxrip/staxrip/assets/51742764/22cae1fc-f1ed-4ef6-a084-be650d7f2369)

**Comment by Dendraspis** [comment]
Your edited post was absolutely okay - and I can see you have already removed the unnecessary `ConvertBits(10)`.

Seems the template is outdated/wrong. I will try to update the template for the next major release.
To proper set up the filter, please refer to the doc for valid parameters:
https://github.com/Asd-g/avslibplacebo?tab=readme-ov-file#tone-mapping

**Comment by ShubhamVimal** [comment]
Thanks, but what about HDRTools question? HDR max luminance level ?

**Comment by Dendraspis** [comment]
That has to be set manually, you can get the exact value from the Media Info of the source. There you find something like this:

```
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant
Mastering display color primar : BT.2020
Mastering display luminance    : min: 0.0000 cd/m2, max: 1000 cd/m2
Maximum Content Light Level    : 2279 cd/m2
Maximum Frame-Average Light Le : 256 cd/m2
```

**Comment by ShubhamVimal** [comment]
In the metadata of the file, there is a line which says ---> Mastering display luminance : min: 0.0200 cd/m2, max: 1200 cd/m2 , so I've tried to put 1200 cd/m2 as max luminance level, but after encoding the video is full of brightness.

**Comment by Dendraspis** [comment]
For detailed info about the parameter settings please head over to the plugin docs, which you can find here:
https://github.com/jpsdr/HDRTools/blob/master/HDRTools%20-%20ReadMe.txt

Looks like when using a `PQ` source, you have to multiply the value by 10, so in this case using `12000`.

The preset is adjusted for the next major release, so I close this now...

**Comment by xzpyth** [comment]
hello i know i am late to the party but this very simple way to convert HDR to SDR as of now:
___
ConvertBits(16)
libplacebo_Tonemap(src_csp=1, dst_csp=0, dynamic_peak_detection=True, tone_mapping_function="spline")
ConvertBits(8)
ConvertToYUV420()
___
