### ISSUE TITLE
Show full filename in Video Comparison

### ISSUE THREAD

**Issue by Elgohan2** [staxrip/staxrip#1336]
I work with pretty long file name and since a release of StaxRip where tabs on Video Comparison stop flashing when too many tabs are open makes tabs too small to show entire filenames.
The current behaviour is good enough but I can't show full name of a file.
It is possible to show full filename somewhere on the Video Comparison window? Maybe on the bottom, next to Position, Time ans Size? Or in a tooltip when hovering the tab?

**Comment by Dendraspis** [comment]
I have added a ToolTip, so you can see the path of any opened tab you like.  Was a bit odd that it wasn't there yet.  🥴 
Will be implemented in `v2.39`...


<img width=300 src=https://github.com/staxrip/staxrip/assets/50659978/3f827fdd-b600-47c7-87e0-3fd9abf028a9>

**Comment by Elgohan2** [comment]
Really appreciate your work, thanks ❤️
