### ISSUE TITLE
Custom paths within the startup folder are not permitted

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1337]
v2.38.6

So I was setting up staxrip and for AAC encoding
Apple Application Support
CoreAudioToolbox.dll
Edit Path and I use the same path I used before and I get an error.

Custom paths within the startup folder are not permitted because it would prevent a simple update process.
Please put the file somewhere else outside the startup folder.

What startup folder? What that means? It is not in the staxrip folder. This did not happen before.

**Comment by Dendraspis** [comment]
> What startup folder?

That's the folder `StaxRip.exe` is in.

> What that means?

That you can only select files, that are not inside the startup folder including subfolders, except the `Settings` folder.

> It is not in the staxrip folder.

You didn't mention the paths of StaxRip and the file you want to select, so....

**Comment by Zodler** [comment]
Staxrip is in
Z:\My Data\Portable Apps\Video\StaxRip

CoreAudioToolbox.dll in
Z:\My Data\Portable Apps\Video\StaxRip Aux\Apple
