### ISSUE TITLE
Why EncoderBitDepth was removed from SvtAv1Enc?

### ISSUE THREAD

**Issue by flesnuk** [staxrip/staxrip#1338]
On this commit https://github.com/staxrip/staxrip/commit/497195e17bd8d2f966f6066c8e7f960b2141b5bb

Strange thing is that if even I add it on the custom box `--input-depth 10` it still doesn't work 
`Svt[info]: SVT [config]: bit-depth / color format                               : 8 / YUV420` 

```
D:\code\StaxRip-v2.38.6-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe -dll=D:\code\StaxRip-v2.38.6-x64\Apps\FrameServer\AviSynth\AviSynth.dll -y4mp C:\Users\flesn\Videos\00000-720_temp\00000-720.avs | D:\code\StaxRip-v2.38.6-x64\Apps\Encoders\SvtAv1EncApp\SvtAv1EncApp.exe --input - --width 1280 --height 720 --output C:\Users\flesn\Videos\00000-720_temp\00000-720_out.ivf --frames 1261 --rc 0 --progress 2 --input-depth 10

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:       SVT-AV1 Encoder Lib v2.0.0-7+6-62325458 [Mod by Patman]
Svt[info]: SVT [build]  :       Visual Studio 2022 64 bit
Svt[info]: LIB Build date: Apr 14 2024 00:36:07
Svt[info]: -------------------------------------------
avs2pipemod[info]: writing 1261 frames of 25/1 fps, 1280x720,
                   sar 0:0, YUV-420-planar-8bit progressive video.
Svt[warn]: Film grain denoise apply signal is going to be ignored when film grain is off.
Svt[info]: Number of logical cores available: 12
Svt[info]: Number of PPCS 140
Svt[info]: [asm level on system : up to avx2]
Svt[info]: [asm level selected : up to avx2]
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: profile / tier / level                                 : main / auto / auto
Svt[info]: SVT [config]: width / height / fps numerator / fps denominator       : 1280 / 720 / 25 / 1
Svt[info]: SVT [config]: bit-depth / color format                               : 8 / YUV420
Svt[info]: SVT [config]: preset / tune / pred struct                            : 10 / PSNR / random access
Svt[info]: SVT [config]: gop size / mini-gop size / key-frame type              : 161 / 32 / key frame
Svt[info]: SVT [config]: BRC mode / rate factor                                 : CRF / 35 
Svt[info]: -------------------------------------------
Encoding          
```

So I don't know what's happening there. With a 10bit source it works and shows the output bit-depth is 10.

**Comment by flesnuk** [comment]
Even on 2.37 this wasn't working, so maybe that's why it was removed..
Is there a way we could output yuv420p10le with AV1 (when input is yuv420p)?

**Comment by Dendraspis** [comment]
That's the reason why it was removed.  😉 

In oder to understand what's going on you have to check out the docs where it states:

<table>
<tr>
<td>

\--input-depth
</td>
<td>

\[8, 10\]
</td>
<td>8</td>
<td>Input video file and output bitstream bit-depth</td>
</tr>
</table>

...including fallback/correction. 

That means a 8bit source will always end up in a 8bit encode. To get a 10bit encode, you have to add a filter to convert the source to 10bit first before sending it to the encoder.

**Comment by flesnuk** [comment]
I see, I was reading the SVT-Av1 docs and saw that aswell. I thought --input-depth 10 outputs 10bit even if source is 8bit.
Then I saw how in x265 for example there is a --output-depth which does that, as expected. 
When adding ConvertBits(10) to the filters, it works as expected, thanks!

**Comment by Dendraspis** [comment]
That was the reason why I implemented it at first, because that's what almost every other encoder does, but...

You're welcome.
