### ISSUE TITLE
Python MAJOR installer confusion making Vapoursynth fail to initialize, please read my suggestion.

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#134]
There is a MAJOR problem with Python installer (3.7.6 and 3.7.7) that makes Vapoursynth not be able to function.

1. Vapoursynth expects **python.exe to be in Program Files folder** (regardless of path env. variable)
2. Python installs python.exe in Appdata folder when selecting "Install **launcher** for all users" from main installer screen
3. Python installs python.exe in Program Files folder ONLY when selecting "Install for all users" in the CUSTOMIZE -> ADVANCED OPTIONS (that most users will not use)

So, this problem is external to staxrip, and users will blame staxrip, because they get confused between "install **launcher** for all users" and "Customize / Advanced/ Install for all users".

**Suggested action 1:**
In the Apps Manager, Runtimes/Python page, Just under the description, place a note like:
Please carefully select "Customize Installation", and in the "Advanced Options" page, select "Install for all users". If this options is not available, you will need to uninstall previous version first.

OR

**Suggested action 2:**
Simply put the following options for the installer 
python-3.7.6-amd64-webinstall.exe InstallAllUsers=1 PrependPath=1 Include_exe=1 Include_launcher=1
This will ensure that when the user clicks on install, the defaults will be set properly for Vapoursynth requirements, without needing to go in the custom install options.
However, this solution does not work when updating from a previous version (if the previous version was installed with the wrong parameters, the new version will keep those wrong parameters)

OR

**Suggested action 3:**
make a page for troubleshooting Staxrip with this kind on information in the Wiki. I don't have access to creating such page, otherwise I would have done it myself (to help).
And place a link on home page to the wiki so people are reminded that there is a troubleshooting section in the wiki.

And please don't forget to update to 3.7.7

**Comment by stax76** [comment]
I always use custom options, so I can disable things like TK and docs. It's probably important to let the installer put it to the path env var, after all it's a console interpreter, I'm the only user on my PC and never install it for all users, I install Python always here:

C:\Users\frank\AppData\Local\Programs\Python\Python37\python.exe

Normally that should be no problem. Usability wise that's probably easier and hopefully not insecure.

I've created a Troubleshooting page here:

https://github.com/staxrip/staxrip/wiki/Troubleshooting

**Comment by 44vince44** [comment]
@stax76 I believe you have no problems because you installed it with proper options long time ago, and now you're updating it.
I think that if you uninstall all your pythons from your system and install it again with this path, you'll get some issues. Can I ask you please a very simple thing: please tell me if there is a "python.exe" in your C:\Program Files\Python37 folder.

**Comment by stax76** [comment]
According to Everything I have:

```
C:\Users\frank\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\frank\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\python.exe
C:\Users\frank\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\frank\AppData\Local\Programs\Python\Python37\Lib\venv\scripts\nt\python.exe
C:\Windows\Prefetch\PYTHON.EXE-C396A723.pf
```

**Comment by 44vince44** [comment]
Oh that means that you've installed the Windows store Python app, and also you've installed the desktop version. I'm checking things relating to the path definitions now.

**Comment by 44vince44** [comment]
Ok, here is to put down clearly, after I made a thorough clean up of my paths:

1. If you install Python using Customize -> advanced options -> install for all users
    then you must install VapourSynth for all users, and everything works fine.

2. If you install Python with defaults installer option, NO customize, i.e Python will be installed for current user only.  In this case you must install Vapoursynth for current user only.
But you may bump into an error that it fails to create a registry key. So in this case, cancel the installation of Vapoursynth and relaunch Vapoustynth installer with admin priviedges, and install for current user only. and everything works fine.

Strange, but definitely external to Staxrip. I'm closing this...

**Comment by stax76** [comment]
> Oh that means that you've installed the Windows store Python app

I think it's in Windows by default in recent versions.

> But you may bump into an error that it fails to create a registry key.

I think I saw something like this too and will report it if it happens again.
