### ISSUE TITLE
(another) NVEncC denoise filter

### ISSUE THREAD

**Issue by cartman0208** [staxrip/staxrip#1342]
I see there's some space left in the "NVEncC - VPP - Denoise 2" section, hopefully the newest denoise filter can be squeezed in there ;)
[https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-nlmeans-param1value1param2value2](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-nlmeans-param1value1param2value2)

**Comment by Dendraspis** [comment]
Will be included in the next main release, but might take a while, sorry.
