### ISSUE TITLE
Move by KeyFrames

### ISSUE THREAD

**Issue by Jay123210599** [staxrip/staxrip#1343]
I want to copy/mux my videos when cutting/splitting videos, but I don't know which frame is a keyframe/I-frame. I would appreciate it if you could add buttons to the tool that allow me to go forward and backward by keyframe. Or, at the very least, make it so that the tool tells us whether we are at a I, P, or B frame in Preview. I saw many other video editors/cutters already having these features and I'm sure much more people will use StaxRip if you add them to it.

Thanks!

**Comment by Dendraspis** [comment]
Already answered on Discord 3 weeks ago!

Quote:
*This is not possible as Keyframe is an encoder-based interpretation of a frame. Once loaded for further processing this doesn't work anymore.*
