### ISSUE TITLE
Cannot load file nnedi3cl.dll

### ISSUE THREAD

**Issue by bdlegend** [staxrip/staxrip#1345]
Hi,

While using QTGMC I got this error message 

Cannot load file '..../StaxRip-v2.38.6-x64/Apps/Plugins/AVS/NNEDI3CL/nnedi3cl.dll'. Platform returned code 126:
The specified module could not be found.

I am using RDP with Windows Server 2019.

Any Solution ?

Thanks

**Comment by Dendraspis** [comment]
Does the server have a (dedicated) GPU?

**Comment by bdlegend** [comment]
> Does the server have a (dedicated) GPU?

No dedicated GPU..
