### ISSUE TITLE
Video Comparison screenshots saved in wrong location due to backslash stripping

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1348]
**Describe the bug**
I have 2 videos to compare in `Z:\RippinG` folder.
In previous versions when taking comparison screenshots they would be saved into the same folder as videos are.
But now due to some issue with slashes it is saved in the root directory of `Z:\` disk with strange name like `RippinG148337 Goodfellas (1990) BDRip 1080p H.265 [2xUKR_ENG] [Hurtom].png`

StaxRip v2.38.7

**Comment by Dendraspis** [comment]
Thanks for the report, will be fixed in the next release.  🤝
