### ISSUE TITLE
Event Commands not working with Batch Jobs

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#135]
Event Commands are not working with Batch scheduled Jobs.

**Comment by noblemd00** [comment]
Also batch scheduled jobs are only creating 1 log file (2 are normally created - a small one and a larger one). 

Log output when batch scheduled (partial at beginning of log file):

**********************************************************************
************************     DESTINATION     *************************
**********************************************************************

.1080p.h265.mkv
.1080p.h265.mkv

**********************************************************************
**********************************************************************

-------------------------- System Environment --------------------------

StaxRip    : 2.0.9.10
Windows    : Windows 10 Pro 1909
Language   : English (United States)
CPU        : AMD Ryzen 9 3900X 12-Core Processor
GPU        : NVIDIA GeForce GTX 1660 Ti
Resolution : 1920 x 1080
DPI        : 96

------------------------ MediaInfo Source File ------------------------




Log output when job individually created (partial - in middle of log file):

----------------------- Event Command W.Standard -----------------------

Event: Before Job Processed
Command: SetTargetFile
Parameter Target File Path: %target_dir%%source_name%.%target_height%p.%encoder_ext%.%muxer_ext%

-------------------- Event Command Destination AVE --------------------

----------------------- Indexing using ffmsindex -----------------------

X:\StaxRip-x64\Apps\Plugins\Dual\ffms2\ffmsindex.exe F:\-CNV\_TV\Westworld\S01.1080p.Edited\104.Dissonance.Theory.mkv X:\VidTemp\104.Dissonance.Theory_temp\104.Dissonance.Theory.ffindex

Writing index... done.

Start:    14:27:30
End:      14:27:31
Duration: 00:00:01

----------------------- Event Command W.Standard -----------------------

Event: Before Job Processed
Command: SetTargetFile
Parameter Target File Path: %target_dir%%source_name%.%target_height%p.%encoder_ext%.%muxer_ext%

-------------------- Event Command Destination AVE --------------------

Event: Before Job Processed
Command: WriteLog
Parameter Header: 
Parameter Message: **********************************************************************
************************     DESTINATION     *************************
**********************************************************************

%target_dir%
%target_file%

**********************************************************************
**********************************************************************
**********************************************************************
************************     DESTINATION     *************************
**********************************************************************

\\TMSY\T8.TVActive\W\Westworld\
\\TMSY\T8.TVActive\W\Westworld\104.Dissonance.Theory.1080p.h265.mkv

**********************************************************************
**********************************************************************

--------------------------- AviSynth Script ---------------------------

LoadPlugin("X:\StaxRip-x64\Apps\Plugins\Dual\ffms2\ffms2.dll")
FFVideoSource("F:\-CNV\_TV\Westworld\S01.1080p.Edited\104.Dissonance.Theory.mkv", cachefile="X:\VidTemp\104.Dissonance.Theory_temp\104.Dissonance.Theory.ffindex")
#AssumeFPS(25)

**Comment by stax76** [comment]
I think the problem is at the time the event command executes, the source file isn't yet opened.

There is not much I can do apart from a major rewrite which is not an option.

For your task I think you can use the event 'After Source Loaded'.

**Comment by noblemd00** [comment]
Ok…

 

The question is why did the Event Command work using Before Job Processed with batch files in 2.0.6.0, but does not work in 2.0.9+?

 

What changed?

 

Mike

**Comment by stax76** [comment]
I don't know and don't have time to investigate it.

Please don't post this email metadata every time!

**Comment by noblemd00** [comment]
Don’t know what you are talking about “Please don't post this email metadata every time!”, I am just replying to your email (Microsoft Outlook 2019).

 

I deleted your text – hopefully it does not “post this email metadata.”

 

Also I just tried 2.0.6 and I am wrong, the Before Job Processed Event commands do not work with batch files in that version – I may have been using my old Event Commands to accomplish the auto name change.

 

The thing is, this is a problem with the program which should be addressed – Eventually.

 

Batch File processing should work the same as manually adding multiple jobs to queue – all functions should work properly in both instances.

 

I use your program, usually daily, and am very impressed with its operation, my bug reports/suggestions are not meant to offend, but only to advise you of a problem or improve the program. 

 

A programmer should consider suggestions from users to improve a program – it is one of the main ways to improve the program and make it more user friendly.

 

With that in mind, I would like to suggest that you add a “Load Project Template as Startup” (or similar) to the File menu – a duplicate of the Project Templates menu that loads the Template and assigns it as the startup template.

 

The reason for this is that many times I have loaded a template, drag-n-dropped and processed a video file then drag-n-drop another video file to process and the template for the second file reverts to the startup template.

 

Having this “Load Template as Startup” would prevent the program from reverting to a different template when the next file is drag-n-dropped.

 

Or, this could be prevent this by warning the user that the template is going to revert – “Use current Template or Startup” with buttons <Current> and <Startup>.

 

The first choice of a “Load Template as Startup” is better because no further user action is required. 

 

Hopefully, you will consider my suggestion to improve the program and recognize the spirit in which they are made.

 

Mike

mnoble24@cfl.rr.com

**Comment by stax76** [comment]
Please don't post Email metadata.

Please don't post 4 newlines for each paragraph.

And please create a separate issue for each request.

**Comment by noblemd00** [comment]
In case you did not realize - I was using an email program to reply to an email I received from email sender StaxRip - Your constant comment in your email reply of "Please don't post Email metadata" made absolutely no sense what so ever. I thought I was receiving an email from the programmer for further comment and was replying to the email - NOT to a comment or issue in Github. 

YOUR SYSTEM added the "4 newlines for each paragraph" my original email reply is properly formatted. YOUR SYSTEM sent me the original email and I replied to that email in a conversational friendly manner even when I received an email which says 

"I don't know and don't have time to investigate it."

YOUR "Issue" system should make it clear that the email is sent by YOUR system automatically and it is sending copies of replies to posted ISSUES. YOUR system should NOT send emails that appear to come from a person that is requesting comments via a reply.

It was only when I looked at the Issue here (in GitHub) that I realized the emails I received were automated. Once again NOTHING in the emails I received indicated they were automated notifications.

**Comment by stax76** [comment]
Sorry, I didn't know and expect that it's possible to reply to github notification mails, forums and similar sites typically don't have such functionality.
