### ISSUE TITLE
Order of languages from project options is ignored and I always getting English track first

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1350]
**Describe the bug**
Order of languages from project options is ignored and I always getting English audio track first despite that my list looks  following `ukr eng und`. So I expect Ukrainians audio tracks to be first included.

**Comment by Dendraspis** [comment]
Do you have a sample file for me?

**Comment by IevgenSobko** [comment]
> Do you have a sample file for me?

Let me do some short extraction by mkvtoolnix

**Comment by IevgenSobko** [comment]
Here you can download short 10 seconds extraction from my encode with a few audio tracks
https://drive.proton.me/urls/9J4ANT1B1G#XRQM1vMBQ0aR

**Comment by IevgenSobko** [comment]
Hmm... Strange it was not reproduced by video I made. Let leave this for some time for me to reproduce.

**Comment by IevgenSobko** [comment]
Yep, here it is again.
This remux has Ukrainian track in itself but it is not selected as first during initialization/demuxing
<img width="732" alt="Screenshot 2024-05-08 at 09 34 28" src="https://github.com/staxrip/staxrip/assets/14232100/8a4d54dd-5493-40d7-a7c5-9f7796928611">

**Comment by Dendraspis** [comment]
Currently the `preferred languages` are there primary to demux the tracks. For the selection, the set language in the audio profile is also considered. So when you click on `Edit` and set `Ukranian [uk]` as language for the first audio track, an Ukrainian audio track will be loaded.

> Also Target has slashes removed

How did you achieve that? I'm not able to reproduce it...

**Comment by IevgenSobko** [comment]
> How did you achieve that? I'm not able to reproduce it...
Don't know. Its just woks this way for me.
Maybe I need setting reset. But I will wait new version to do that and check again

And thanks for pointing me out to language in Edit for the first track. It was really set to English on this instance - that was causing selection English for first track. I leaned something new about StaxRip

**Comment by Dendraspis** [comment]
You can also run a copy without `Settings` folder from a new location and test if that solves your issue...

**Comment by Dendraspis** [comment]
No problem, glad it works now.  👍
