### ISSUE TITLE
Video encoding returned exit code: -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1351]
SDR source during encode has crushed. Log below
[new_staxrip.log](https://github.com/staxrip/staxrip/files/15245610/new_staxrip.log)

**Comment by Dendraspis** [comment]
Should be related to a filter issue or system related. Hard to tell because of so many possibilities, especially because you overload existing script, probably with a different version.

Most likely there is an issue with the memory.

**Comment by madey83** [comment]
yes, this could be with lack of memory... After i opened case i realized that my virtual machine is turned on.

after shut it down i have started encode and it's still progressing...
