### ISSUE TITLE
auto-crop

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1355]
I downloaded the “full version” of version 2.38.7 - when starting the software, the auto-analysis of function updates produced a message about the new version of auto-crop and then suggested changing the Name by pressing f12. - produces an error when saving. and every time you launch the software it displays a message about a new auto-crop and saves with an error

**Comment by Andrasolin** [comment]
![изображение](https://github.com/staxrip/staxrip/assets/150133906/b2aa9d52-2709-4907-8141-046a64a041a3)

**Comment by Andrasolin** [comment]
How to disable the auto-check for updates feature?

**Comment by Dendraspis** [comment]
Yeah, I accidentally updated `AutoCrop`.
Just enter `2.3` and hit `OK`.

If there is any error after that, you might need write permissons.
