### ISSUE TITLE
VS ResampleHQ error with some resizers

### ISSUE THREAD

**Issue by Elgohan2** [staxrip/staxrip#1359]
**Describe the bug**
When choosing some resizer in ResampleHQ on VapourSynth filter, an error message is shown and we can't encode with that resizer.

**Expected behavior**
Encoding with chosen resizer.

**How to reproduce the issue**

1. Open a source file
2. Choose "VS Filters"
3. On "Resize" filter, choose one of them: "Rect", "Blackman", "Blackmanminlobe", "Spline64", "Gauss" or "Sinc"
4. Error message appear at the bottom of the windows and we can't click on "Accept / Next" button

**Provide information**

The error message is:
```
Script Error

Python exception: cannot access local variable 'scaler' where it is not associated with a value

Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
  File "E:\dir_temp\movie.vpy", line 13, in <module>
    clip = resamplehq.resample_hq(clip, 1280, 720, kernel='Sinc')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StaxRip-v2.39.1-x64\Apps\Plugins\VS\Scripts\resamplehq.py", line 152, in resample_hq
    clip = scaler(clip, **scaler_opts)
           ^^^^^^
UnboundLocalError: cannot access local variable 'scaler' where it is not associated with a value
```

Used StaxRip version: 2.39.1

**Comment by Dendraspis** [comment]
Thanks for the catch, I'll remove them.
