### ISSUE TITLE
Error when trying to use tonemapping placebo

### ISSUE THREAD

**Issue by githubbabby** [staxrip/staxrip#1360]
**Describe the bug**
When trying to add tonemapping to an HDR file, I get this error:

Script Error

Python exception: No attribute with the name placebo exists. Did you mistype a plugin namespace or forget to install a plugin?

Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
  File "C:\Users\ayybased\Videos\staxrip\Godzilla.Minus.One.2023.UHD.Bluray.2160p.TrueHD.7.1.Atmos.DV.HEVC.REMUX-GojiraDidNothingWrong_temp\Godzilla.Minus.One.2023.UHD.Bluray.2160p.TrueHD.7.1.Atmos.DV.HEVC.REMUX-GojiraDidNothingWrong_staxrip.vpy", line 15, in <module>
    clip = core.placebo.Tonemap(clip, src_csp=1, dst_csp=0, dynamic_peak_detection=1, tone_mapping_function=5, tone_mapping_mode=0)
           ^^^^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 2741, in vapoursynth._CoreProxy.__getattr__
  File "src\\cython\\vapoursynth.pyx", line 2564, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name placebo exists. Did you mistype a plugin namespace or forget to install a plugin?

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version: 2.39.1

**Comment by Dendraspis** [comment]
Which GPU is installed?

**Comment by githubbabby** [comment]
Only integrated graphics from intel cpu is used.

**Comment by Dendraspis** [comment]
Load your project, right-click on the filters, click on `Preview Code` and share the resulting script with me.

The loading of the DLL should be prevented because of not fulfilling the requirements, meaning a Vulkan compatible GPU that is needed.

**Comment by githubbabby** [comment]
1: import os, sys
  2: import vapoursynth as vs
  3: core = vs.core
  4: 
  5: sys.path.append(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\VS\Scripts")
  6: core.std.LoadPlugin(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\VS\fmtconv\fmtconv.dll", altsearchpath=True)
  7: # !! The following line is commented out by StaxRip, because the system does not fulfill all requirements to execute it !!
  8: #core.std.LoadPlugin(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\VS\libvs_placebo\libvs_placebo.dll", altsearchpath=True)
  9: core.std.LoadPlugin(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll", altsearchpath=True)
 10: 
 11: clip = core.lsmas.LWLibavSource(r"C:\Users\ayybased\Videos\staxrip\Godzilla.x.Kong.The.New.Empire.2024.HDR.2160P.WEB.H265-POKE_temp\Godzilla.x.Kong.The.New.Empire.2024.HDR.2160P.WEB.H265-POKE.h265", cachefile=r"C:\Users\ayybased\Videos\staxrip\Godzilla.x.Kong.The.New.Empire.2024.HDR.2160P.WEB.H265-POKE_temp\temp.lwi")
 12: clip = core.fmtc.bitdepth(clip, bits=16)
 13: clip = core.placebo.Tonemap(clip, src_csp=1, dst_csp=0, dynamic_peak_detection=1, tone_mapping_function=0, tone_mapping_mode=0)
 14: # clip = clip.resize.Bicubic(format = vs.YUV420P10)
 15: 
 16: clip.set_output()

**Comment by githubbabby** [comment]
sorry for the wait, here it is: 
  1: import os, sys
  2: import vapoursynth as vs
  3: core = vs.core
  4: 
  5: sys.path.append(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\VS\Scripts")
  6: core.std.LoadPlugin(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\VS\fmtconv\fmtconv.dll", altsearchpath=True)
  7: # !! The following line is commented out by StaxRip, because the system does not fulfill all requirements to execute it !!
  8: #core.std.LoadPlugin(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\VS\libvs_placebo\libvs_placebo.dll", altsearchpath=True)
  9: core.std.LoadPlugin(r"C:\Users\ayybased\scoop\apps\staxrip\current\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll", altsearchpath=True)
 10: 
 11: clip = core.lsmas.LWLibavSource(r"C:\Users\ayybased\Videos\staxrip\Godzilla.Minus.One.2023.UHD.Bluray.2160p.TrueHD.7.1.Atmos.DV.HEVC.REMUX-GojiraDidNothingWrong_temp\Godzilla.Minus.One.2023.UHD.Bluray.2160p.TrueHD.7.1.Atmos.DV.HEVC.REMUX-GojiraDidNothingWrong.h265", cachefile=r"C:\Users\ayybased\Videos\staxrip\Godzilla.Minus.One.2023.UHD.Bluray.2160p.TrueHD.7.1.Atmos.DV.HEVC.REMUX-GojiraDidNothingWrong_temp\temp.lwi")
 12: clip = core.resize.Bicubic(clip, 1920, 1080)
 13: clip = core.fmtc.bitdepth(clip, bits=16)
 14: clip = core.placebo.Tonemap(clip, src_csp=1, dst_csp=0, dynamic_peak_detection=1, tone_mapping_function=0, tone_mapping_mode=0)
 15: # clip = clip.resize.Bicubic(format = vs.YUV420P10)
 16: 
 17: clip.set_output()

**Comment by Dendraspis** [comment]
Look at line 7 and you will know why this happens.

Just to check what happens anyway, you can copy line 8 and insert it without hashtag at the top of your filter, so it gets loaded before the call.
