### ISSUE TITLE
Error demuxing subtitles from TS container

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1361]
v.2.39.1

Problem with reading the .TS container with subtitles, reports an error due to subtitles and closes the software

converted it to .MTS, then it read and processed without problems

**Comment by Dendraspis** [comment]
Should be implemented with the next release...

**Comment by Andrasolin** [comment]
and changing the FPS using a "deinterlacing" (x2)bob inside QSVenc - reports an error - but processes "Good"

**Comment by Dendraspis** [comment]
1. New problem => new issue
2. More info!
