### ISSUE TITLE
HDR metadata not imported for SVT-AV1

### ISSUE THREAD

**Issue by shodan5000** [staxrip/staxrip#1362]
**Describe the bug**
When a UHD with HDR info file is loaded the HDR metadata is not automatically populated in the Color Description tab of the SvtAv1EncApp encoder. Everything has to be manually chosen/populated.

**Expected behavior**
HDR metadata should automatically populate in the Color Description tab when an appropriate file is loaded.

**Comment by Dendraspis** [comment]
Will be implemented with the next release...
