### ISSUE TITLE
QSVenc+FPS

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1363]
Launched StaxRip v.2.39.1

uploaded a video file 123mb.mp4 1080p29.97fps

selected and configured QSVenc = ICQ H.265 main(8-bit) / DoubleFrameRate(Bob) / TFF

I pressed Start and after processing it showed an error message with FPS, but the video file itself was changed to what I wanted

FPS analysis when using QSVenc is incorrect

**Comment by Dendraspis** [comment]
Exact error message?

Log file?

I guess you mean the `Frame Mismatch` ?

**Comment by Andrasolin** [comment]
![изображение](https://github.com/staxrip/staxrip/assets/150133906/f59e4404-a433-499c-b2f4-9f3bbe7549ea)

Frame Mismatch (v2.39.1)

Target file has 12128 frames, but should have 6064 frames!

StaxRip.ErrorAbortException: Target file has 12128 frames, but should have 6064 frames!
   в StaxRip.GlobalClass.ProcessJob(String jobPath) в D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:строка 458

[2024-05-21 - 19.19.46 - THE SHOW 240521_new_staxrip.log](https://github.com/staxrip/staxrip/files/15398605/2024-05-21.-.19.19.46.-.THE.SHOW.240521_new_staxrip.log)

**Comment by Andrasolin** [comment]
1.the function of creating a "Log file" is broken...
2.in the interface - you ask to open the folder with Logs - it gives an error and cannot be found and opened
3. go manually and find the folder with Logs and it’s empty

**Comment by Dendraspis** [comment]
1. No, it's definitely not.  😄 
2. Just hit `F8` after the run or loading the project or look in the `_temp` folder for the log file. You can also use `Project » Folders » Temp` to get there.
3. You might use (very) old settings and/or you don't have write permissions or so.

**Comment by Dendraspis** [comment]
Keep in mind, that this is Project based, so you have to re-add existing jobs.

If you have disabled `Abort on Frame Mismatch`, there is ***no way*** you get an error message.
