### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1364]
v.2.39.1

"Log file" creation function is broken

launched StaxRip, pressed Tools-Folders-LogFiles
It gave me an error saying it couldn’t find and open.

and if you find and open the folder yourself, then there is a folder with the same name, but it is empty

**Comment by Dendraspis** [comment]
This was already fixed in `v2.38.7`.

Start with fresh/new settings, reset the main menu or at least fix the menu item's command line to solve your problem.
