### ISSUE TITLE
staxrip 2.39.1 crop

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1367]
Hi,

is there any option to force staxrip 2.39.1 to crop video to match RPU information?

![staxrip 2 39 1](https://github.com/staxrip/staxrip/assets/34553588/18cfc2af-5219-4ddd-b587-4ae4fdb06322)

**Comment by Dendraspis** [comment]
This is by definition of a YUV420 color model not possible, so StaxRip doesn't support it out of the box.
Mod 2 is the way to go.

The only way to try it anyway is to bypass StaxRip's logic, for example by settings the RPUs offset to `0` and then crop manually.

**Comment by madey83** [comment]
![staxrip 2 39 1_2](https://github.com/staxrip/staxrip/assets/34553588/cfde32c0-ffad-44fa-bf81-c68a9ffb371b)
![staxrip 2 39 1_3](https://github.com/staxrip/staxrip/assets/34553588/055a634b-53c7-47ca-8eba-722633f83b81)

how can i move forward?

**Comment by Dendraspis** [comment]
You can only crop `YUV444` videos with uneven values as far as I remember, so you need to convert it before cropping.

**Comment by madey83** [comment]
MeGui autocrop detect the same file like that
![megui](https://github.com/staxrip/staxrip/assets/34553588/917f41cd-d6d3-48a5-9b96-7e341efc2e72)

Staxrip with manual crop shows this

![staxrip 2 39 1_5](https://github.com/staxrip/staxrip/assets/34553588/7aa0f503-efa7-43bb-8065-e81340280349)

i can accept loosing 1px even if i know that resolution 1920x816 is good.

**Comment by madey83** [comment]
resolution 1920x818 has additional 1px black bar...

**Comment by madey83** [comment]
Is it possible to add option to skip assistanse warning?

**Comment by Dendraspis** [comment]
No as that will break the metadata.

**Comment by madey83** [comment]
Hi Dendraspis,

could you please take a look on this:

https://forum.doom9.org/showthread.php?p=2002203#post2002203

**Comment by Dendraspis** [comment]
Ok, I did, and now?

**Comment by madey83** [comment]
and now i think leave one pixel extra in video resolution and 0px in RPU cause missmatch.
maybe allowing manual crop could be an easy solution when video and rpu are cropped. if not maybe more checks should be added...

**Comment by Dendraspis** [comment]
> leave one pixel extra in video resolution and 0px in RPU cause missmatch

Indeed that would lead to a mismatch.

> maybe allowing manual crop could be an easier solution when video and rpu are cropped

You can manually crop it to the maximum, in your case up to 263px whereas you're limited to 262px.

> if not maybe more checks should be added

Cropping of Dolby Vision material works as intended, nothing has to be added.

**Comment by madey83** [comment]
sorry for be boring in this matter, but if there is additional 1/1 pixel in resolution it means cropping RPU to 0/0/0/0 is not proper way of handling this workflow. In my opinion additional check on RPU should be implemented when crop is enabled. In my case RPU shows 263 pixel which is not possible to divide by 2 that is why when i cropped it i left 1 pixel on top and bottom in RPU as you see below.

https://imgur.com/a/U0DZ02M

**Comment by Dendraspis** [comment]
> if there is additional 1/1 pixel in resolution it means cropping RPU to 0/0/0/0 is not proper way of handling this workflow

Exactly.

> In my opinion additional check on RPU should be implemented when cropping is enabled

One is not enough?

> In my case RPU shows 263 pixel which is not possible to divide by 2 that is why when i cropped it i left 1 pixel on top and bottom in RPU as you see below and this is - i think - way to go with DoVi cropping...

Nice to see that my proper solution finally gets implemented by others.

**Comment by madey83** [comment]
is this setup should crop RPU?
![1](https://github.com/staxrip/staxrip/assets/34553588/0a7ca1eb-0b69-4745-a546-e511e7e99abc)

If yes, i can see that is not do that:
![2](https://github.com/staxrip/staxrip/assets/34553588/5778a063-2656-4c68-94f0-85bc5d20fa83)

log:
[test.txt](https://github.com/staxrip/staxrip/files/15468905/test.txt)
[HDRDVmetadata_L5.json](https://github.com/staxrip/staxrip/files/15468908/HDRDVmetadata_L5.json)

**Comment by Dendraspis** [comment]
> is this setup should crop RPU?

Yes.

> If yes, i can see that is not do that:

Of course the adjustments are made after everything is being set and needed, meaning when the encode starts.

**Comment by madey83** [comment]
would it be possible as well to get from RPU MaxCLL and MaxFALL and put it to encode settings?
 
![4](https://github.com/staxrip/staxrip/assets/34553588/252b94d9-1ef4-45cf-a67f-3ba6c33277e0)

**Comment by Dendraspis** [comment]
Why messing things up? That data is only relevant for the Dolby Vision metadata...

**Comment by madey83** [comment]
> Why messing things up? That data is only relevant for the Dolby Vision metadata...

so it is not needed for x265 encoder? ok. then. no more queston. 

thank you for all answers and clarifications. :)
