### ISSUE TITLE
Update ManagedCuda.dll

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1369]
I saw that a very old version of ManagedCuda.dll is included in StaxRip.

What does StaxRip use that dll for? I know the purpose of ManagedCuda.dll but not its job with StaxRip.

Anyway, there are way newer versions, you can find as a [nupkg package](https://www.nuget.org/packages/ManagedCuda-12) that you can easily unzip.

**Comment by Dendraspis** [comment]
This is part of a package and used internally only for a check, so unless there are any issues with that, there is no need to update it.
