### ISSUE TITLE
Buttons to install required runtimes disappeared!!

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#137]
This is how App Manager handles missing runtimes:
![SNAG-0000](https://user-images.githubusercontent.com/17828567/76824513-09bf5e00-6820-11ea-9238-43c2e3c78e2b.jpg)
![SNAG-0001](https://user-images.githubusercontent.com/17828567/76824516-0c21b800-6820-11ea-8877-cab638d00b30.jpg)

No button, and link is in the "Web" menu.
Is this intentional?

**Comment by stax76** [comment]
It's OK here, I think it's because the latest beta does not include tools and I updated the tools meanwhile with:

Installers\python-3.7.7-amd64-webinstall.exe

```
    Shared Property Python As Package = Add(New Package With {
        .Name = "Python",
        .Filename = "python.exe",
        .TreePath = "Runtimes",
        .WebURL = "http://www.python.org",
        .HelpSwitch = "-h",
        .Description = "Python is required by VapourSynth.",
        .SetupFilename = "Installers\python-3.7.7-amd64-webinstall.exe",
        .RequiredFunc = Function() p.Script.Engine = ScriptEngine.VapourSynth,
        .HintDirectories = {GetPythonHintDir()}})
```

**Comment by 44vince44** [comment]
@stax76 ok! sorry for this false alert!!

**Comment by stax76** [comment]
No problem, I appreciate your feedback.

**Comment by 44vince44** [comment]
And we all appreciate the huge work and the excellent piece of software this is becoming! Did I tell you that when I began customizing the UI and the filters and filters profiles I was amazed of what we could do with staxrip !!! (same thing about mpv.net)
