### ISSUE TITLE
Custom audio filter issue (-af) with ffmpeg while Normalize is enabled. And Audio sync (delay) issues.

### ISSUE THREAD

**Issue by fa1rid** [staxrip/staxrip#1370]
**Describe the bug**
In Audio Settings, custom audio parameter `-af` overrides the "Normalize" option (that is ticked [☑](https://www.alt-codes.net/check-mark-symbols.php)in the UI) while encoding audio using ffmpeg.
Example, when encoding to AC3 while removing encoder delay 5.33ms : `-af atrim=0.00533`

![image](https://github.com/staxrip/staxrip/assets/6115961/1499a880-52e9-4680-bbba-4084b6acf67a)

**ffmpeg log:**
```
ffmpeg .... -c:a ac3 -b:a 640k -af volume=2.9dB -af atrim=0.00533  ....
Multiple -filter/-af/-vf options specified for stream 0, only the last option '-filter:a atrim=0.00533' will be used.
```

**Expected behavior**
To merge the custom audio filter with the normalize filter.

**Additional context**
Also, audio encoders add silent delay at the beginning of audio stream. For AC3 at 48 kHz, it's 5.33ms.
For qaac, you can just add `--no-delay`  to fix the added delay.

--no-delay     
Compensate encoder delay by prepending 960 samples
                       of scilence, then trimming 3 AAC frames from
                       the beginning (and also tweak iTunSMPB).
                       This option is mainly intended for resolving
                       A/V sync issue of video.
                       
                       
 **I suggest settings these as default. Imagine you encode an audio multiple times, you will end up with big delay and A/V going out of sync.**
 
Here is a waveform comparison between the original audio (up) and encoded ac3 (down).
Notice how the waveform is shifted.
 
 
![Audio Sync issue](https://github.com/staxrip/staxrip/assets/6115961/4eba655a-c209-450c-aa60-e3fe5debefe0)

 
**Lastly, is there a way to add more than 2 audio tracks, and encoding audio only without having video?**

**Comment by fa1rid** [comment]
Also when using qaac, why do you convert the audio to `FLAC `first (which uses disk space) rather than just decoding it using ffmpeg and pipe it to qaac like this:

`ffmpeg -i "INPUT.ac3" -acodec pcm_f32le -f wav - | qaac64 -q 2 -v384 --no-delay --verbose --threading --ignorelength - -o "OUTPUT.m4a" --log "qaac.log"`

-i, --ignorelength     Assume WAV input and ignore the data chunk length.

**Comment by fa1rid** [comment]
> Also when using qaac, why do you convert the audio to `FLAC `first (which uses disk space) rather than just decoding it using ffmpeg and pipe it to qaac like this:
> 
> `ffmpeg -i "INPUT.ac3" -acodec pcm_f32le -f wav - | qaac64 -q 2 -v384 --no-delay --verbose --threading --ignorelength - -o "OUTPUT.m4a" --log "qaac.log"`
> 
> -i, --ignorelength Assume WAV input and ignore the data chunk length.

I actually noticed the option to set it to pipe instead of using FLAC. I'm wondering why it's not the default. I haven't tried yet though.

**Comment by Dendraspis** [comment]
As far as I remember the step using FLAC prevented some rare issues, but I don't remember what they were.
But please: One issue per issue.  😉 

The issue should be done with the next release as far as I could test it out. 
Feel free to re-open this issue if you still have some problems related to this one.
