### ISSUE TITLE
SvtAv1EncApp: Add VUI metadata import defaulting to incorrect option

### ISSUE THREAD

**Issue by shodan5000** [staxrip/staxrip#1371]
**Describe the bug**
The add VUI metadata import for SvtAv1EncApp appears to be defaulting/choosing the incorrect Transfer Characteristics of SMPTE TE 428. This causes HDR video colors to appear incorrectly.

**Expected behavior**
The defaulting Transfer Characteristics should be SMPTE TE 2084, ITU BT.2100 PQ to have color reproduced correctly.

**Comment by Dendraspis** [comment]
Indeed, a stupid typo.  🤕 

Will be fixed in the next release coming soon...
