### ISSUE TITLE
Adding Multiple Files fails, if any of the source files have a comma in its name.

### ISSUE THREAD

**Issue by Skin80** [staxrip/staxrip#1372]
**Describe the bug**
When adding multiple files, Staxrip stops and reports an error if more than one file being added has a comma in the file name. through the 

**Expected behavior**
Source files should be added to each of their own Staxrip instance, with relevant demuxing/indexing/etc to occur, ready to be worked on.

**How to reproduce the issue**

Source file type is currently MKV, will test other file types when I get the opportunity to do so.

If the issue happens only under special conditions then please describe how this conditions can be reproduced:

1. Go to: File -> Open Video Source File(s)... -> Multiple Files
2. Add video source files, with at least one containing a comma (,) in its name.
3. Encoder not relevant as it never gets that far.
4. Tested on both AviSynth and VapourSynth being used (both result in the error).
5. Filter(s) being used not relevant, as error occurs during source file import.
6. Hardware specs, if relevant:

Windows    : Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
CPU        : AMD Ryzen 5 5600X 6-Core Processor
RAM        : 48GB
GPU        : NVIDIA GeForce RTX 3070

**Provide information**

Error message below, as copied from the message window:

```
FileNotFoundException (v2.39.2)

Could not find file 'D:\Media\MLPFiM\Season 4\MLP_FiM - S04E21 - Testing'.

System.IO.FileNotFoundException: Could not find file 'D:\Media\MLPFiM\Season 4\MLP_FiM - S04E21 - Testing'.
File name: 'D:\Media\MLPFiM\Season 4\MLP_FiM - S04E21 - Testing'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2174
```

The full name of the file should be: 'D:\Media\MLPFiM\Season 4\MLP_FiM - S04E21 - Testing, Testing, 1, 2, 3.mp4'

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version is v2.39.2

**Additional context**
If the first file in the list has a comma, it does not error. Only stops/errors when the 2nd or greater has a comma.

**Comment by Dendraspis** [comment]
Thanks for the detailed report.

> If the first file in the list has a comma, it does not error. Only stops/errors when the 2nd or greater has a comma.

That was very helpful to reproduce the problem!  👍 

It should be fixed with the next release...
