### ISSUE TITLE
Use the same file naming template for Video Comparison as for Preview 

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1373]
**Describe the bug**
Currently, VIdeo Comparison tool uses screenshot name in format that starts with frame number. It is very inconvenient when you need to find matching screenshots if a folder contains more than one unique movie name.
It would be great to use the same file naming template preview feature uses, where screenshot name starts with movie name.

**Comment by Dendraspis** [comment]
Interestingly I think `0000 Filename.png` is a better option at least for Video Comparison as you get all screenshots bundled together, independent of their original file name and without having x files in between.  🤔

**Comment by Dendraspis** [comment]
It definitely depends on what your needs are. In your situation for example sorting the file by date instead of name should solve your issue.

But I will see if I can do anything about that...

**Comment by Dendraspis** [comment]
Something like this maybe?

<img width=600 src=https://github.com/staxrip/staxrip/assets/50659978/add9307d-4f1c-4893-a6bb-ec626bccb593>

**Comment by IevgenSobko** [comment]
That would be the best way to satisfy everyone 👍

**Comment by Dendraspis** [comment]
Should be available in the next release, so I close this one.  Have fun...

**Comment by IevgenSobko** [comment]
Oh, you couldn't imagine how much easier is now to do comparison upload of 2-5 rips at the same time to find out better encode. 👏
