### ISSUE TITLE
PSY-SVT-AV1 Weird bug

### ISSUE THREAD

**Issue by ojetepelon** [staxrip/staxrip#1376]
**Describe the bug**
The preset wanted change.

**Expected behavior**
Get the preset wanted.

[Sony Swordsmith HDR UHD 4K Demo_staxrip.log](https://github.com/user-attachments/files/15521526/Sony.Swordsmith.HDR.UHD.4K.Demo_staxrip.log)

**Comment by Dendraspis** [comment]
This is normal behavior of the official `SvtAv1EncApp`.
