### ISSUE TITLE
V2.39.3 Error loading Template by double clicking .srip file  yields "System Exception"

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1377]
**Describe the bug**
Associate ".srip" with StaxRip program and load a template by double clicking the template.

<img width="351" alt="240602 103314" src="https://github.com/staxrip/staxrip/assets/16325865/eeae004f-7259-4c56-a888-eae042f230f3">

**Expected behavior**

Simple Template loading by double clicking Template .srip file

Previously, Templates could easily be selected/loaded (and run) StaxRip by double clicking the Template .srip file. Additionally, the Job (.srip file) in the StaxRip temp folder could reload the Job by double clicking the Temp folder .srip file. 

As of v. 2.39.3 double clicking any .srip file results in a "System Exception"

After clearing the error message, the SAVED Template appears to be properly loaded.

After clearing the error message, the Temp folder .srip file does not RELOAD the JOB.

Associating files with a program and double clicking to open the program/load is a standardized Windows function which previously worked properly in StaxRip.

**How to reproduce the issue**
Associate ".srip" extension with the StaxRip program and attempt to load a template by double clicking the Template/Temp Folder .srip file.

**Comment by Dendraspis** [comment]
Thanks for the detailed report, but it was already reported ... and fixed:
#1375 

This also happens when video files are passed to StaxRip. But it was already fixed for the next release, probably next week.

So right now you can use the main menu to open the file, drag it onto StaxRip or you downgrade to `v2.39.2` which is not affected by this problem.

**Comment by noblemd00** [comment]
Ok, thanks for replying - checked open issues but forgot to check the closed issues. I'll try to remember to do that next time.
