### ISSUE TITLE
Opening a .srip file from file explorer (file association) fails in staxrip 2.39.3 was working in 2.39.2

### ISSUE THREAD

**Issue by BillyBob1354** [staxrip/staxrip#1378]
**Describe the bug**
Trying to open a .srip file from file explorer after associating the .srip file type with staxrip fails with this error message (image).
![image](https://github.com/staxrip/staxrip/assets/46253676/b4bcee74-5103-488f-bb04-37f33bb30a55)

Dragging and dropping the .srip file into staxrip still works.

Was working correctly in 2.39.2 but fails in 2.39.3.

**Comment by Dendraspis** [comment]
This is a duplicate to #1375 and #1377 and will be fixed with the next release.
