### ISSUE TITLE
Preview in MPV very BROKEN !!!

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#138]
Beta 2.0.9.11:

- case 1: press F5 for Preview, don't select range. leave cursor at frame 0, press F9, you get an error (see below), press OK, MPV opens, video plays OK.
- case 2: press F5 for preview. Select range(s). move cursor to somewhere outside range. Press F9. You get the same error (see below), press OK, mpv open and plays.

Please tell me why didn't you accept the commit proposal  #123   If current.End <= Renderer.Position  it gave perfect behaviour in 99.9999999999% of cases, and in 0.0000000001% of cases (very unlikely to happen unintentionally) , just requires to move cursor.

--------------------------------
Exception

start: MPV_ERROR_PROPERTY_FORMAT

System.Exception: start: MPV_ERROR_PROPERTY_FORMAT
   at mpvnet.mp.set_property_string(String name, String value, Boolean throwOnException) in D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 501
   at mpvnet.mp.ProcessCommandLine(Boolean preInit) in D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 639

**Comment by stax76** [comment]
`current.End <= Renderer.Position` does not work, I just tried a second time!

That issue with the start was unrelated to the 2 frame back solution which is solid, nobody knows why you can't hit the exact frame with every player every frame server every source filter combination and nobody has time to find out, why is it important?

2.0.9.12

https://github.com/staxrip/staxrip/blob/master/Changelog.md

https://staxrip.readthedocs.io/intro.html#download

**Comment by 44vince44** [comment]
It's working !!! no issues, no errors, no black screen, no....
It's working !!!!! Thanks !!!!!!!!!!!!!!!!!! :-D
