### ISSUE TITLE
Shortcut to Log Files cannot find the folder

### ISSUE THREAD

**Issue by inter5tella** [staxrip/staxrip#1380]
**Describe the bug**
Using the shortcut "Tools>Folders>Log Files" is trying to open the local log file folder but is missing a backslash at the last folder name.

**Expected behavior**
Using the shortcut "Tools>Folders>Log Files" is opening the Log Files folder in the Staxrip appdata folder structure.

**How to reproduce the issue**
1. Click on 'Tools' in the application's menu bar
2. Select 'Folders'
3. Select 'Log Files'

**Provide information**
The error message says, that the folder/file can not be found.
![grafik](https://github.com/staxrip/staxrip/assets/12923644/f01e2be1-3816-4b76-824d-3a915e748ecf)

Actually, a backslash character is missing before the very last folder name.
![grafik](https://github.com/staxrip/staxrip/assets/12923644/d7c90773-3aad-4184-95ce-fbf247b0c33d)

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version 2.39.3

**Comment by Dendraspis** [comment]
This was already fixed in `v2.38.7` and it seems you're still using old settings.

Start with fresh/new settings, reset the main menu or at least fix the menu item's command line to solve your problem.
