### ISSUE TITLE
L5 metadata has multiple presets

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1381]
Hi,

I opened a bluray in Staxrip. I immediately noticed the crop values are incorrect. 

I checked the "HDRDVmetadata_L5.json" and I noticed:
```
  "crop": true,
  "presets": [
    {
      "id": 0,
      "left": 0,
      "right": 0,
      "top": 277,
      "bottom": 277
    },
    {
      "id": 1,
      "left": 0,
      "right": 0,
      "top": 44,
      "bottom": 45
    }
  ],
```

The first one is the correct one, but for whatever reason Stax chose the latter. 

Also, it corrected the values to 44px top and 44px bottom. Is that possible when encoding with DV metadata?

Because the correct crop values are also 277x277 which should be corrected to either 276x276 or 278x278

**Comment by Dendraspis** [comment]
In order to give you an answer I need to see the whole content of the file.

**Comment by LazyNCoder** [comment]
Oh I got it now. Thanks.
There's a section called "edits" and it assigns different crop presets to different frames. It's like this:
```
  "edits": {
    "0-58112": 0,
    "58113-58237": 1,
    "58238-58327": 0,
    "58328-58439": 1,
    "58440-68491": 0,
    "68492-68534": 1,
    "68535-107339": 0,
    "107340-107425": 1,
    "107426-107532": 0,
    "107533-107611": 1,
    "107612-107640": 0,
    "107641-107684": 1,
    "107685-107734": 0,
    "107735-107828": 1,
    "107829-109035": 0,
    "109036-109104": 1,
    "109105-164964": 0
  }
```

It's strange because we don't have anything changing on the video. It's not like it's imax or anything. I don't know why this would happen.

I guess encoding without cropping is the way to go here. Am I right?

**Comment by Dendraspis** [comment]
So StaxRip handles it the right way.  🙂 

> It's strange because we don't have anything changing on the video.

Happens sometimes. I suggest checking multiple frame sections, that are listed there and check, if there is a change in aspect ratio or not. Often there is one.

> I don't know why this would happen.

You have to ask the publisher or creator of the video.  😁 

> I guess encoding without cropping is the way to go here. Am I right?

The maximum crop is `44px` at the top and bottom, so you can let StaxRip handle it as intended or you can disable the `Crop` filter and continue without cropping. The third solution is to remove the Dolby Vision metadata and set the cropping values you like - it's your choice.
