### ISSUE TITLE
Auto Crop doesn't allow option only when crop is enabled

### ISSUE THREAD

**Issue by pianistrevor** [staxrip/staxrip#1382]
**Describe the bug**
Before in StaxRip, auto-cropping would only happen if I had "Crop" enabled in the filters. Now, it's tied to the value in Project > Options > Crop > Auto Crop after opening, which overrides whether I have the Crop option enabled in the workflow.

**Expected behavior**
Auto-cropping only happens if "Crop" is enabled in the filters

**How to reproduce the issue**

1. Project > Options > Crop > Auto Crop, set to Always
2. Disable the Crop filter in the workflow
3. Open a source file
4. Observe that auto-cropping happens anyway and Crop becomes enabled

**Provide information**
StaxRip 2.39.2

**Comment by Dendraspis** [comment]
This is not a bug, the behavior has changed in `v2.35.0` and it works as intended.

If you don't want cropping after opening, simply set it to `Disabled`.

**Comment by pianistrevor** [comment]
I’m not saying I don’t want auto cropping. I’m saying I want it if I toggle Crop, and don’t want it if I don’t toggle Crop.

It’s not the end of the world but if I want to run a batch of files and crop them, I now have to manually change the setting from Disabled to Always beforehand. Just feels unnecessary.

**Comment by Dendraspis** [comment]
But there had to be a possibility to add the `Dolby Vision only` mode, so there is no going back.

Either you go to the Options to change the mode or you create another template and work with that when needed/wanted.
