### ISSUE TITLE
Using new Progress Highlighting colors on System Colors theme

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1383]
Hi, I'm using system colors. After upgrading to the latest version, the text is not that readable. 
![sshot-2024-06-08- 19-31-11](https://github.com/staxrip/staxrip/assets/54937979/5da4ebee-eb2a-47de-b509-7bfb45a9e089)

**Comment by Dendraspis** [comment]
1. Who on earth uses System Colors?  😱 
2. Try the other colors as the yellowish colors are meant for the default theme.

**Comment by LazyNCoder** [comment]
1- I'm old school. I love system colors 😅
2- I tried changing colors in Windows settings. But it didn't change the color of the what I wanted to change. I think I'm gonna switch to "Light Gray" theme for now. But it's still very dark for my taste. I hope you could add more bright themes in the future. 

Is there any other setting I can mess with in order to use the system color theme?

**Comment by Dendraspis** [comment]
Did you ever click on that menu icon on the `Processing...` window?  🤔 

![image](https://github.com/staxrip/staxrip/assets/50659978/631f05d5-401a-4e19-a19f-ab5eced20ee4)


>  I hope you could add more bright themes in the future.

To be honest I thought about removing `Light Gray` and `Gray`.  🥴

**Comment by LazyNCoder** [comment]
> Did you ever click on that menu icon on the `Processing...` window? 🤔
> 
> ![image](https://private-user-images.githubusercontent.com/50659978/337925894-631f05d5-401a-4e19-a19f-ab5eced20ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NzI4OTksIm5iZiI6MTcxNzg3MjU5OSwicGF0aCI6Ii81MDY1OTk3OC8zMzc5MjU4OTQtNjMxZjA1ZDUtNDAxYS00ZTE5LWExOWYtYWI1ZWNlZDIwZWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDE4NDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMWY4MDFkMmRkNzM0YWMwZmJlYzJjY2ZmOTBjNmFmMzAwNzA5ODRiYTNlMzEzYWE4ZmFjYmNkOWUwODZiNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kXvaPdcOfbfd2mvpMehY9LDTEd_18ADWX8gRfHKF37s)
> 
> > I hope you could add more bright themes in the future.
> 
> To be honest I thought about removing `Light Gray` and `Gray`. 🥴

There it is... 🤣
I looked everywhere for it. 

Thanks. I never had problem with it before. 
You learn something from the great Dendraspis everyday.

Sorry, please close it.

**Comment by LazyNCoder** [comment]
-
