### ISSUE TITLE
Getting: Script Error: There is no function named  'FFT3dFilter'

### ISSUE THREAD

**Issue by craposoup** [staxrip/staxrip#1384]
I did a clean extract of version c:\StaxRip-v2.40.0-x64 on OS: Win10 Pro, 22H2, AVX

Launched as admin, and tried to deinterlace a .VOB as always, version StaxRip-v2.40.0-x64 is throwing the following error:

Script error: There is no function named 'FFT3DFilter'.
(C:\StaxRip-v2.40.0-x64\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 1631)
(C:\StaxRip-v2.40.0-x64\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 1631)
(C:\StaxRip-v2.40.0-x64\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 805)
(C:\VOB\VTS_01_1_temp\VTS_01_1.avs, line 23)

I do not face this issue with the previous StaxRip-v2.39.3-x64
Although Crop is selected, I did not select it, looks like a crash.

![image](https://github.com/staxrip/staxrip/assets/49623148/280f7a1b-3edb-4f7f-a588-98ac20bb170d)

**Comment by Dendraspis** [comment]
Try to import also
`.\Apps\Plugins\AVS\FFT3DFilter\fft3dfilter.dll`
`.\Apps\Plugins\Dual\f3kdb Neo\neo-f3kdb.dll`
right before your call of `QTGMC`. That should solve the problem.

This will be fixed for the next release...

**Comment by Dendraspis** [comment]
Can you check if this one works for you without adding imports?

[StaxRip v2.40.1 (EXE ONLY)](https://ufile.io/ew5qqvcb)

**Comment by craposoup** [comment]
I tested using the 2.40.1.exe, the errors did not appear however crop is getting selected.
![image](https://github.com/staxrip/staxrip/assets/49623148/5be5db66-30a5-4e9d-8334-38e8cd25f09d)

In v2.39.3, Crop does not automatically selected after selecting a .Vob file
![image](https://github.com/staxrip/staxrip/assets/49623148/8faecdef-951d-4e6d-ac74-af7370bacf72)

**Comment by Dendraspis** [comment]
https://github.com/staxrip/staxrip/issues/1391#issuecomment-2160013334

**Comment by craposoup** [comment]
Yep, that took care of the autocrop, thankyou!
