### ISSUE TITLE
AV1-SVT Preset Changes at Run Time

### ISSUE THREAD

**Issue by xazoo** [staxrip/staxrip#1385]
Using AvtAv1EncApp, preset 6 executes as preset 7.
Presets 5, 7, 8 are not affected
Verified with VMAF scores that 6 is encoding as 7.
Using v2.40

**Expected behavior**
Preset 6 should be used in encoding

**How to reproduce the issue**
When preset 6 is selected in the "Encoder Options" > "Basic" > "Preset:", the encoder sets it to 7 when encoding.

**Provide information**
From the log:

Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1-PSY Encoder Lib v2.1.0-1+1-8ba1c70f [Mod by Patman]
Svt[info]: SVT [build]  :	Visual Studio 2022 64 bit
Svt[info]: LIB Build date: May 20 2024 18:05:51
Svt[info]: -------------------------------------------
avs2pipemod[info]: writing 7553 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
Svt[warn]: Preset M6 is mapped to M7.
Svt[info]: Number of logical cores available: 32
Svt[info]: Number of PPCS 173
Svt[info]: [asm level on system : up to avx512]
Svt[info]: [asm level selected : up to avx2]
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: profile / tier / level 				: main / auto / auto
Svt[info]: SVT [config]: width / height / fps numerator / fps denominator 	: 1920 / 1080 / 24000 / 1001
Svt[info]: SVT [config]: bit-depth / color format 				: 8 / YUV420
Svt[info]: SVT [config]: preset / tune / pred struct 				: 7 / SSIM / random access
Svt[info]: SVT [config]: gop size / mini-gop size / key-frame type 		: 120 / 32 / key frame
Svt[info]: SVT [config]: BRC mode / rate factor 					: CRF / 27.00 
Svt[info]: SVT [config]: AQ mode / variance boost strength / octile / curve 		: 2 / 2 / 6 / regular
Svt[info]: SVT [config]: Sharpness / QP scale compress strength / Frame low-luma bias 	: 0 / 1 / 0
Svt[info]: -------------------------------------------

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version
v2.40

[Hellsing Ultimate 1-4 Disc 1_t02_new27.6.0_staxrip.log](https://github.com/user-attachments/files/15750487/Hellsing.Ultimate.1-4.Disc.1_t02_new27.6.0_staxrip.log)

**Comment by Dendraspis** [comment]
This is normal behavior of the official `SvtAv1EncApp`, I guess since `v2.1.0`.
