### ISSUE TITLE
Ignoring frames when cropping

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1386]
Hi,

Now that cropping is improving, I have something in mind for the next update maybe.

Sometimes there are irrelevant frames on the beginning or  the end of the video, like company logo or something similar. They often don't have the black bar on them and because of that, crop tool ignores the black bar completely for the whole video. 

Maybe you can put something built-in, like ignoring the first and last 30 seconds of the video. Or put a setting for users to choose. 

I'm thinking something with in/out buttons on the crop window. to select a range or something. 

Thanks ❤️

**Comment by Dendraspis** [comment]
So basically we could use the `Threshold`, that is used currently for `Dolby Vision` only, to make it work for all sources. Do you think that would also suit your needs?

Sadly there is no way I can make a better integration into the Crop window.

**Comment by LazyNCoder** [comment]
That would get the job done. What I had in mind was, an "in" and "out" button on the crop window to set the starting and ending points. But if it's not possible, we can do that manually when needed. 

Thank you very much.

**Comment by Dendraspis** [comment]
In your case, in hope you still have the video file that brought you here, can you tell me...

1. how long is the video?
2. how many frames or seconds have to be skipped in order to crop the video itself correctly?

**Comment by LazyNCoder** [comment]
Well I wouldn't bother you for a single video. The feature I'm asking is applicable to many cases. 
Like imaging a BluRay movie with 140px top/bottom black bars. And then at the end of the video a 1920x1080 WB logo without the blackbars for 5 seconds appear.  Autocrop sets the crop values to 0px because of that WB stupid logo that has no use. 

If we could set a range to ignore that would be good. Like in project options. two values ignore 0 second from the beginning and 0 second from the end. Or else you can just set a default value like 30 seconds or 1 minute for both of them and just place a checkbox for user to choose. 

OR an in and out button on the slider bar on the crop window the choose the duration of where we want the video to be cropped.

**Comment by Dendraspis** [comment]
That's the problem:
How many percent of the whole video are ignored at the beginning?  Is it just 30s of a 2h video and 15s of a 1h video?
But it looks like there is no automatic way to go as there might be also important data.  😕 

Thanks, so it looks like a manual threshold has to be implemented...  😩

**Comment by LazyNCoder** [comment]
I have something else in mind too. Maybe instead of the whole thing we talked about. autocrop can show the report of the scans to users.
Like, 98% of the video has 140px 140px black bar. Do you want to crop or not.

Of course there's a catch. Imaging a case, like an imax movie, which has different AR throughout the video. a detailed report would be needed here. with all the changes.
ex:
frames: 0-200 0px
frames: 201 to 1000 140px 140px
frames: 1001 to 2000 80px 80px

Something like that. And user can choose the lowest one. three options gives to user. which one do you want:
0px
140 px
80px 

I'm sure you got the idea. And you have far better idea in your mind.

**Comment by Dendraspis** [comment]
> Like, 98% of the video has 140px 140px black bar. Do you want to crop or not.

That is actually a very interesting approach.  🤔 
At least for the AutoCrop process not my favorite as it should be done without any user interactions, so that when the opening is done StaxRip is ready.

Personally I tend to adjust AutoCrop to ignore the first and last ~30s for videos that are longer than 1h.  🤔

**Comment by LazyNCoder** [comment]
Well... you're the boss here. But at least can you lower the time from 1 hour to like 15 minutes?

I'm not on stax's Discord server yet.(I don't use Discord often) 😅

**Comment by Dendraspis** [comment]
Indeed  😅

Yeah, should be okay to do so. That's why I asked those 2 questions about your video file.

Hmm, okay. In case you join tell me.

**Comment by Dendraspis** [comment]
Nevermind, so I will keep the solution I have implemented now. Will be available in the next main release `v2.42`.
