### ISSUE TITLE
SvtAvtEncApp AVX512 disabled in bundled Windows binary

### ISSUE THREAD

**Issue by gitoss** [staxrip/staxrip#1387]
**Describe the bug**
The bundled SvtAv1EncApp.exe seems to be built only for AVX2, and doesn't enable AVX512.

```
Svt[info]: SVT [version]:       SVT-AV1-PSY Encoder Lib v2.1.0-1+1-8ba1c70f [Mod by Patman]
Svt[info]: [asm level on system : up to avx512]
Svt[info]: [asm level selected : up to avx2]

```

**Expected behavior**
The 'asm level selected' should be avx512 if 'asm level on system" is avx512. 

**How to reproduce the issue**
Using a cpu supporting AVX512 (like AMD Zen4 or Intel Tiger Lake) and run SvtAv1EncApp.exe with either --asm avx512 or --asm max

**Provide information**
The svt encoder has --asm max and should auto-select to best asm level for each system, so as far as I understand it it's not necessary to build a binary limited to AVX2?

**Additional context**
Other SvtAv1EncApp Windows binaries available on github seem to be limited to AVX2, too - but have binaries supporting AVX512 for Linux: https://github.com/gianni-rosato/svt-av1-psy/releases

**Comment by Dendraspis** [comment]
Sadly I can't verify that because of no suitable CPU. 
As this is obviously an issue related to that tool, please open an issue on its issue tracker:
https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases

I have already messaged Patman86 and he will try to make such a binary for the next release.

**Comment by gitoss** [comment]
Thanks! I didn't know where the binary originated from, otherwises I'd have opened the issue over there.

**Comment by gitoss** [comment]
I'm closing the issue over here because I've opened a ticket in the original repo.
