### ISSUE TITLE
Warning "Dolby vision requires VBV settings to enable HRD"

### ISSUE THREAD

**Issue by Bdraft** [staxrip/staxrip#1389]
Hi, I got this warning when I try to encode a video with HDR.
![1](https://github.com/staxrip/staxrip/assets/7032941/1eaa9a9f-183d-4a60-8c2a-5ed70141fb5c)
![2](https://github.com/staxrip/staxrip/assets/7032941/8d1acc95-20bc-4107-bb29-6ef888999daf)
![3](https://github.com/staxrip/staxrip/assets/7032941/ea52b2e1-3ccf-4607-8f58-02e18cf91dae)

Any idea what should I do in order to be able to encode the video?

**Comment by Dendraspis** [comment]
Please check out #1203 for the answer.
