### ISSUE TITLE
Cutting is currently not supported for dolby vision encodes

### ISSUE THREAD

**Issue by Bdraft** [staxrip/staxrip#1394]
"Cutting is currently not supported for dolby vision encodes"

This is the warning that appear when I select a fragment of a video with DoVi (I'm using staxrip 2.40), the message say it all but what get me curious is that if I load the same project with Staxrip 2.12 DoVi data is recognized and I can make selection with no problem. So my question is if this feature already was in staxrip and was removed or something is wrong with v2.40.

**Comment by Dendraspis** [comment]
In `v2.12` there was no real *Dolby Vision support*, meaning StaxRip didn't care about it in terms of making sure that the result becomes valid and correct - it was all up to the user. This changed with `v2.32`.

**Comment by Bdraft** [comment]
Thanks for your reply **Dendraspis**, I just tried v2.38 that according to what you said it support DoVi and I get no warnings when I cut or made a selection in the video neither if I leave the VBV Buffer size and VBV maxrate by default (which is 0).
The output seems to play fine. Why are these warnings really needed?

**Comment by Dendraspis** [comment]
Cutting was added later on along with many other improvements.

The videos always play fine, but that doesn't mean they are proper. So yes, these warnings are necessary.
