### ISSUE TITLE
Set 10bit by default for AV1 encoders

### ISSUE THREAD

**Issue by JND94** [staxrip/staxrip#1397]
https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/CommonQuestions.md#8-or-10-bit-encoding

**Comment by Dendraspis** [comment]
StaxRip uses native encoders primarily, even `ffmpeg` is also usable.
So there is no such parameter that can be set and encoders like `SvtAv1EncApp` don't support such parameters.

Additionally:
Feature request could only be worse without providing a link.  🙄

**Comment by Crypto-Spartan** [comment]
To anyone wondering how to enable 10bit for AV1:

> It's a filter added in "VS filters". Rclick -> Add -> Color -> Convert -> Convertbits -> 10 (this should be the default path

Source: https://discord.com/channels/1163724583472472138/1163724584311345154/1252019471732834456

Screenshot:
![image](https://github.com/staxrip/staxrip/assets/29098151/d0be1369-357e-4fe8-872a-db04ed021e5d)
