### ISSUE TITLE
v2.40.0 - Output

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1399]
ignores Information about FPS and Video Resolution. During processing, it shows correctly, but at the end it reports an error stating that the FPS and Resolution are different

![изображение](https://github.com/staxrip/staxrip/assets/150133906/9d356b57-ecd5-435f-8c60-79c41b1ec68c)

**Comment by Dendraspis** [comment]
Duplicate to #1363

**Comment by Andrasolin** [comment]
💯 This error message is annoying.

**Comment by Dendraspis** [comment]
As stated at least 1 million times:  Turn it off for such purposes as there is no way to determine what happens to the video when you pass it to the encoder.

That's it!

**Comment by Dendraspis** [comment]
Look into #1363 and check out my second post.

And again keep in mind, that those are project based settings, means you have to save them as a template in order to make it sort of permanent.

**Comment by Andrasolin** [comment]
This is the 2nd time I say/report - It doesn’t work!

![изображение](https://github.com/staxrip/staxrip/assets/150133906/7ef49519-947d-445d-a759-920c4fc364b9)

**Comment by Dendraspis** [comment]
Of course it works. But your screenshot shows, that `Frame Mismatch` is still enabled, so turn it off as I said multiple times.

**Comment by Andrasolin** [comment]
![изображение](https://github.com/staxrip/staxrip/assets/150133906/e446d971-8700-4dce-9446-f15103a660ec)

I poked these on/off switches and it works

Thanks!
