### ISSUE TITLE
Batch Framerate Subtitles

### ISSUE THREAD

**Issue by 21jump** [staxrip/staxrip#140]
Hello, first of all, thank you very much for this piece of software, I have only been using this for several months!

I would have a request to make, you made so that the software can modify the framerate from 25 to 23.976 and vice versa for video and audio, and it works wonderfully! But, would it be possible to have the same possibility for batch subtitles? I know that the software includes tools allowing to do it manually, but it would be good if we could do this operation in batch like the other two! I've searched everywhere, and it doesn't seem possible right now ...

Thank you and good day!

**Comment by stax76** [comment]
It's too specialized for me to spend time with it, there is advanced feature called Event Commands that allow some advanced tasks and there is PowerShell scripting support, which can at least help experienced programmers.
