### ISSUE TITLE
StaxRip v2.41.2 - incorrect default for SVT-AV1-PSY ( --enable-variance-boost)

### ISSUE THREAD

**Issue by BillyBob1354** [staxrip/staxrip#1405]
"--enable-variance-boost" is enabled by default in SVT-AV1-PSY (--enable-variance-boost 1).
![image](https://github.com/staxrip/staxrip/assets/46253676/2f202b7e-1f7f-4ad5-8fd6-da1ea5c24aee)

https://github.com/gianni-rosato/svt-av1-psy/blob/37a5609bcc20bbf40203b8c4736d906af1a259d3/Docs/Parameters.md?plain=1#L99
https://github.com/gianni-rosato/svt-av1-psy/blob/37a5609bcc20bbf40203b8c4736d906af1a259d3/README.md?plain=1#L84

**Comment by Dendraspis** [comment]
The documentations drive me crazy...

`--enable-variance-boost` is not a PSY-only parameter anymore, but they changed the default value to `1`.  🙄

**Comment by Dendraspis** [comment]
Here is the fix:
[StaxRip v2.41.4 (EXE-only)](https://ufile.io/eirp2ma1)
