### ISSUE TITLE
NVEnc problems with ProRes 4444/4444XQ files.

### ISSUE THREAD

**Issue by Victory61** [staxrip/staxrip#1406]
Good morning.
I have a problem with the NVEnc encoder, the installed version is 7.54.
The problem occurs with files encoded in ProRes especially only with profiles 4444 and 4444 XQ, profile 422 HQ is handled without problems.
These are the error messages when I import the files:
![ProRes 4444](https://github.com/staxrip/staxrip/assets/97799367/3ac0348b-a8d2-4904-ac54-914586c541c0)
![ProRes 4444 XQ](https://github.com/staxrip/staxrip/assets/97799367/a9aff9fb-06f4-4e8d-aab9-5c6104debbf0)

**Comment by Dendraspis** [comment]
Hello.
How does you script looks like?

**Comment by Victory61** [comment]
Questi sono i 2 log.
[Sample ProRes 4444_staxrip.log](https://github.com/user-attachments/files/15944603/Sample.ProRes.4444_staxrip.log)
[Sample ProRes 4444 XQ_staxrip.log](https://github.com/user-attachments/files/15944606/Sample.ProRes.4444.XQ_staxrip.log)

**Comment by Dendraspis** [comment]
1. Would it be possible to share a short 2s sample of that file with me?
2. Please try `VapourSynth` instead of `AviSynth+` as the reported color format seems to be somehow off.  🤔

**Comment by Victory61** [comment]
I attach the sample ProRes 4444 XQ.
https://www.mediafire.com/file/noecrjrp4rb7tip/Sample_ProRes_4444_XQ.mov/file

**Comment by Joet73** [comment]
@Dendraspis
I confirm that Vapoursynth works with YUVA prores file.
Using nvenc file reader (either hardware or software) doesn't work.
There is the exact same issue with QSVEnc.
If i use avsresize plugin to modify color format instead of the regular convertto avisynth internal.plugin, no issue with the encoder.
Looks like an avisynth issue to me with alpha channel handling.

**Comment by Dendraspis** [comment]
Oh yeah, it seems to be an `AviSynth+` issue. Further `NVEncC` seems also to have a problem with the alpha channel.  🥴 

So I would also suggest using `VapourSynth` as there is no issue with such video formats. In case you have to use `AviSynth+`, you have to convert the color space first.

@Joet73 
Thanks for you expertise.  👍

**Comment by Victory61** [comment]
Thank you all.
I ask if VapourSynth can be set up for 4444 and 4444 XQ profiles in the next versions.

**Comment by Dendraspis** [comment]
You can use `VapourSynth` already as it supports that format. No need to add or modify anything.

**Comment by Victory61** [comment]
OK. Thank you.

**Comment by Victory61** [comment]
Excuse me one last question.
In the interface of NVEnc I have to is this option okay?
![Immagine 2024-06-24 151701](https://github.com/staxrip/staxrip/assets/97799367/5c040d75-5d39-4774-95c4-17e214099d04)

**Comment by Dendraspis** [comment]
It's not `Interface`, it's `Interlace` with an *L*.
Because this file is progressive, setting it to `Disabled` is the right setting.
