### ISSUE TITLE
File Batch processing not running Event Commands

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1407]
v. 2.41.5 (recent previous also)

**Describe the bug**
File Batch processing not executing Event Commands

**Expected behavior**
Event commands should be executed during File Batch processing

**How to reproduce the issue**
Create an event command, run Batch processing on multiple files.

Event Commands that work for single file conversion are not executing during Batch File processing.

Searched for "Event" and "Batch" in Open and Closed issues.

![240623 101404](https://github.com/staxrip/staxrip/assets/16325865/eb922ea1-611e-4c76-becd-c1b06827e391)

Event Command 

![240623 103115](https://github.com/staxrip/staxrip/assets/16325865/1f91090d-be48-40fe-a385-6bb84bf6d582)

NOT BATCH 
0103.Boom.1080p.HLG.h265.mp4

BATCH 
0103.Boom.mp4

**Comment by Dendraspis** [comment]
Currently the event is only triggered when you press the `Add Job` button. I will see what I can do....

**Comment by Dendraspis** [comment]
Will be added with the next release...
