### ISSUE TITLE
mov faststart flag option

### ISSUE THREAD

**Issue by BuyMyMojo** [staxrip/staxrip#1408]
**Is your feature request related to a problem? Please describe.**
Creating mp4 or mov files for the web you sould enable "faststart" to improve streaming the content and having this option built into staxrip would be useful.

**Describe the solution you'd like**
A simple check box for the ffmpeg container options or check box with an int value for mp4box.

ffmpeg just required this added to the commandline: `-movflags +faststart`

for the mp4 box option you add this flag to the commandline: `-inter 500`, I don't have much experince with other values but I've been told 500 is a good default value for this.

**Describe alternatives you've considered**
I've previously just used ffmpeg to add this after the fact as it doesn't require reencoding
`ffmpeg -i in.mp4 -c:v copy -c:a copy -movflags +faststart out.mp4`

**Explain why the feature matters to you**
I like to use staxrip to compress videos for sharing on my website or on discord and for larger videos, such as any nearing the 500mb discord nitro limit) greatly benifit from this option so the viewer doesn't need to load the entire video before hitting play

**Additional context**
- [mp4box fragmentation docs](https://github.com/gpac/gpac/wiki/Fragmentation,-segmentation,-splitting-and-interleaving)
- [ffmpeg fragmentation docs](https://ffmpeg.org/ffmpeg-formats.html#Fragmentation)

**Comment by Dendraspis** [comment]
For `mp4box` I have added the `Streaming` command line menu preset, so it becomes easily editable.

For `ffmpeg` I have added it permanently - not interested in wasting time on that as it seems pretty good to have those data at the beginning instead of the end. We will see...

So `v2.42` will have it implemented.
