### ISSUE TITLE
Audio encoding error

### ISSUE THREAD

**Issue by nero1st** [staxrip/staxrip#141]
Hi,
today when I tried to cut a small part of a video using the qaac encoder for the audio, I got an error:
```
ERROR: m_module.stream_decoder_seek_absolute(m_decoder.get(), count)

StaxRip.ErrorAbortException: Audio encoding 2 using qaac 2.68 failed with exit code: 2 (0x2)

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 328
   at StaxRip.GUIAudioProfile.Encode() in D:\Projekte\VB\staxrip\General\AudioProfile.vb:line 677
   at StaxRip.GlobalClass._Closure$__._Lambda$__31-1() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 109
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 132
```
I did several tests and everything goes well using any other encoder or in case I don't use cut filter.

It would be great to be able to fix that. Thanks.

OS: Win10 x64
StaxRip Ver.: 2.0.8.0

**Comment by 44vince44** [comment]
I'm surprised because I use the qaac encoder all the time and cut audio with it, and it works perfectly !
Please check that in your Staxrip\Apps\Audio\qaac folder, you've got the QTFiles64 folder and inside it there is usually 10 files.

**Comment by stax76** [comment]
I don't have time to examine every tool issues in detail and report it to the tool author, if possible please report it to the tool author.

As workaround, you can try another encoder.

**Comment by 44vince44** [comment]
Stax, I think it isn't an issue, I think he's missing the QTFiles64 folder that has to be put manually.

**Comment by nero1st** [comment]
Hi 44vince44, thanks for your answer. Yes, I have the QTFiles64 folder and there is no warning in the apps manager. Have you tried to encode any video using qaac for audio while using the cut filter in the process with no issues? If so, which version are you using?

Stax, I'll take a look at that, thanks.

**Comment by 44vince44** [comment]
@nero1st yes I confirm that: all the videos I encode are video=x265 audio=qaac. And everytime I cut at least a few frames from the beginning and a few from the end. Try the latest beta in Stax's dropbox, and make a test.
The download links are there [https://staxrip.readthedocs.io/intro.html#download](https://staxrip.readthedocs.io/intro.html#download) (Drobpox and OneDrive), latest beta is 2.1.0.1

**Comment by nero1st** [comment]
Weird... I tried your suggestion, but I got the same error. However, if I don't use the cut filter everything works fine, no issues. Maybe it's something on my side because I tried to use the cut filter on another tool with the same encoders/parameters and everything went well. I also tried to do that on a clean virtual machine and the same error occurs. Sadly.

What is your OS and its build?

**Comment by 44vince44** [comment]
Windows 10 home x64 18363.720

But I'm pretty sure it is not related to the OS.  Are you sure the file name isn't problematic? because when you cut, there are several processes involved that are not used when you don't cut (intermediate avi file for cutting etc). Maybe one of those processes cannot take special characters in the file name or long file names. NOTE: the file names of the cutting intermediate files use the stream name of audio. 

=> suggestion : do this test: before processing with staxrip, remux the file with mkvtoolnix, make sure you remove the stream names.
Use the remuxed file in staxrip instead of your original file. And try cutting.

**Comment by nero1st** [comment]
Closing because I found a way to make it work.

I'd like to thank 44vince44 for his tips and for his immense kindness in trying to help me. I really appreciate that.

**Comment by 44vince44** [comment]
You're welcome, I'm glad to know i could help!

**Comment by stax76** [comment]
But what was it? Maybe staxrip could work around it or show a warning or do something else.

**Comment by nero1st** [comment]
In my particular case, for some reason, the error was due to choosing a specific decoder. Leaving it on automatic makes it work.

But if you ask me why, I don't know. Maybe you can explain it to me... because when I tried using another video encoding tool, there was no error.

**Comment by stax76** [comment]
You did not post the log file, so I don't know which decoder and which source file type.

If the involved tools are still maintained by somebody then a bug report could be made.

**Comment by nero1st** [comment]
It was an mkv file. I've tried every available decoder without success. However, leaving it on automatic everything goes well for some reason. 

If you wish, I can do the process again and send you the log file. But I wouldn't worry too much about it for now, since apparently it only happened to me.

**Comment by 44vince44** [comment]
@nero1st you can still find saved log files in your staxrip settings folder!

**Comment by nero1st** [comment]
Here's the log file:
https://pastebin.com/raw/FHhkj0d2

**Comment by stax76** [comment]
I can reproduce it and try to find out which app is causing it.

**Comment by nero1st** [comment]
Alright, thanks.

**Comment by stax76** [comment]
It was a mkvtoolnix bug:

https://forum.doom9.org/showthread.php?p=1905464#post1905464

**Comment by nero1st** [comment]
I see. So I guess we'll have to wait for the next release for a possible fix.

**Comment by stax76** [comment]
It will not be fixed but there will be meaningful error messages:

https://forum.doom9.org/showthread.php?p=1905709#post1905709

And staxrip will block this particular setup with following message:

> Audio decoding is enabled with FLAC as output format which mkvmerge cannot cut. Either disable decoding or set the decoding format from FLAC to W64.

**Comment by nero1st** [comment]
Good call. Thanks.
