### ISSUE TITLE
Exception when skip AutoCrop

### ISSUE THREAD

**Issue by FangLeeway** [staxrip/staxrip#1411]
**Describe the bug**
When I ripped an IMAX source, I wanted to skip autocrop because the crop was unnecessary. But the StaxRip give me an exception.

**Expected behavior**
Enter StaxRip GUI to do further things.

**Provide information**

```
------------------------------ Exception ------------------------------

StaxRip.SkipException: 应用程序中的错误。
   在 StaxRip.Proc.Start() 位置 D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:行号 332
   在 StaxRip.MainForm.AutoCrop() 位置 D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:行号 2653
   在 StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding, Int32 timeout) 位置 D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:行号 2392
```

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version v2.41.5

[Batman.v.Superman.Dawn.of.Justice.2016.Remastered.UHD.BluRay.2160p_staxrip.log](https://github.com/user-attachments/files/16026989/Batman.v.Superman.Dawn.of.Justice.2016.Remastered.UHD.BluRay.2160p_staxrip.log)

**Comment by Dendraspis** [comment]
Currently when you abort the process it will abort the whole opening of the video file.
In order to skip the AutoCrop process you have to disable it in the project options beforehand.

**Comment by FangLeeway** [comment]
> Currently when you abort the process it will abort the whole opening of the video file. In order to skip the AutoCrop process you have to disable it in the project options beforehand.

Love the AutoCrop function and the default output mode, they really saved my time.

**Comment by Dendraspis** [comment]
In the next release it is or should be able to abort/skip `AutoCrop` so no crop is applied, but the source file will still be opened.
