### ISSUE TITLE
Set Project Options > open multiple source files, only the first file respects the options as set

### ISSUE THREAD

**Issue by thepsyborg** [staxrip/staxrip#1416]
**Describe the bug**
Adding multiple files to a project only respects project settings for the first file; all others revert to defaults.

**Expected behavior**
Setting project options and then clicking Open Multiple Files will open those source files _with those options._

**How to reproduce the issue**
For the example in question, I am using three short, low-res .mp4 (MPEG-4 AAC-LC) files located in //TRUENAS/smb0/TestSource/

1. Open StaxRip, ensure there is no preexisting project open.
2. Click `Project` on the menubar. Click `Options`. The Project Options dialog opens.
3. Click `Paths` on the left side, and configure the Paths as follows:
   - Default Project Target: `C:\recoding\TestTarget\`
   - Default Target Name: `%source_name%`
   - Temp Files Folder: `C:\recoding\TestTemp\%source_name%_temp`
   - Default Thumbnails Path without extension: `%target_dir%\%target_name%_Thumbnail`
4. Click 'OK'.
5. Configure other project options, filters, and encoder options as desired. (They don't actually _matter,_ as we never actually reach the point of encoding, but I'll list what I selected just in case.)
6. Using '...' encoder. `SvtAv1EncApp`; `MP3 ~165kbps`
7. 'AviSynth or VapourSynth' being used. `Source: Automatic`
8. Filter(s) x is being used. `Color: ConvertBits 10`
9. If it's tied to a hardware encoder then post your hardware specs. `no hardware issue`
10. Click `File` on the menubar. Click `Open Video Source File(s)` on the menu. The "Select a method for opening a source:" dialog opens. Click `Multiple Files`. The `Open` dialog opens. 
11. Select the three files in //TRUENAS/smb0/TestSource/ and click `Open`
12. The StaxRip window closes, it does its opening/demuxing/creation of temp files, and three StaxRip windows open.
13. The first one shows a source of `C:\recoding\TestTemp\File1.h264`, target of `C:\recoding\TestTarget\File1.mkv`, and all encoding options as specified; the `Color:ConvertBits 10` filter is retained, and the `Source:Automatic` filter has become `Source:LWLibavVideoSource`
14. The second and third show Source: `\\TRUENAS\smb0\TestSource\File2.mp4` / `...\File3.mp4`, Target of \\TRUENAS\smb0\TestSource\File[2,3].mkv`, default x265/18/Medium encoder, `Source:LSMASHVideoSource` filter, and no color conversion filter.
15. Checking the locations confirms that there is one temp folder at `C:\recoding\TestTemp\File1_temp` and two folders at `\\TRUENAS\smb0\TestSource\File2_temp` and `...\File3_Temp`

**Provide information**

No error message is generated, and no recoding is actually done, so I don't think the log files are relevant, though I can provide them if really needed.

- Used StaxRip version
v2.41.5 

**Additional context**
Windows 11, Ryzen 9 7940HS.

**Please be as clear and as detailed as possible**

**Comment by Dendraspis** [comment]
This is because the first file is opened in the current instance, using the project, that is currently set. Every further file is opened in a new instance that, of course, does not know about any unsaved changes you have made.

You have two possibilities:
1. Create a new template with your settings and set it as startup template, then you can open all those files like you have already done.
2. You use the *File Batch* opening. That will not open any instances, but add those files directly to the Jobs List. In case you don't need to alter the jobs this methods can be considered over the first one.

**Comment by thepsyborg** [comment]
Ohhhhhhhhhkkay, that explains it.

I mean, I figured I had to be doing _something_ wrong, but darned if I could figure out _what._ Appreciate you laying it out for me.
