### ISSUE TITLE
Add Save n Resume support during encoding.

### ISSUE THREAD

**Issue by ShubhamVimal** [staxrip/staxrip#1417]
Hey there, just wondering if you can add pause/save current/ongoing encoding and resume it at later (say next day). Sometimes (for me it always due to very old PC) encoding takes a lot time to complete. 

If Staxrip can provide a feature to save/pause current encoding (for ex say 5% is done) and resume the rest next day or even after PC restarts from same point it was paused and not from the beginning ? I don't think there are any software available providing pause/resume support.

Anyway thanks for this amazing piece of software. KEEP UP THE GREAT WORK. PEACE CHEERS.

**Comment by Dendraspis** [comment]
Hello,
that would be a great feature, but sadly this is not possible by design as StaxRip just calls the native encoders and they don't support such processes. 

Thanks you.
