### ISSUE TITLE
Statusbar

### ISSUE THREAD

**Issue by filyse** [staxrip/staxrip#1419]
Is it possible to add a time countdown to the status bar?
<img width="603" alt="Screenshot_2" src="https://github.com/staxrip/staxrip/assets/52866885/fa612bbb-8703-4d6f-b9a3-a78d7604c3cb">
When rendering on nvenc it is there, but not on encrow.
<img width="641" alt="Screenshot_3" src="https://github.com/staxrip/staxrip/assets/52866885/3a5bc40f-327c-442f-b7ec-7baf01501692">

**Comment by Dendraspis** [comment]
When the encoder does not provide such information, there is nothing I can do about it, sorry.
