### ISSUE TITLE
"Go to time" (T) key on Crop window like Preview Window

### ISSUE THREAD

**Issue by Hackerpcs** [staxrip/staxrip#1421]
**Describe the solution you'd like**
Crop window lacks the "T" key feature "Go to time", it can work the same way. Crop Window does feature 100/1000 frames navigation with PgUp/Down

**Explain why the feature matters to you**
On big length sources that need to be trimmed as different videos with different crop values, there isn't something else aside from going up and down with the slider to find the part of the video you want the crop for, navigating via time would be very useful

**Comment by Andrasolin** [comment]
You didn’t write clearly, this function exists - 'Go to time'

**Comment by Dendraspis** [comment]
Yes, but only in `Preview`, not `Crop`.

**Comment by Dendraspis** [comment]
The new menu items come with few minor changes, but makes it necessary to bring them to the next major version change which is `v2.42` ... which will take a while.

So I close it now...


PS: Beta Testers have access to release candidates.  😉

**Comment by Andrasolin** [comment]
This function "Go to time" works great in "Preview" :)
