### ISSUE TITLE
TP-container

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1429]
1920*1080i 29.97fps tff 8.91gb.tp
staxrip v.2.41.0

Staxrip does not see the TP-container, I had to change it to MTS, then I saw it and read for a long time

**Comment by Dendraspis** [comment]
What is a TP-Container? Did you mean TS?

**Comment by Andrasolin** [comment]
no. TP-container

**Comment by Dendraspis** [comment]
Please provide some information about that container.

**Comment by Andrasolin** [comment]
O_O ? mmm...
