### ISSUE TITLE
Can't find the Bitrate selection box

### ISSUE THREAD

**Issue by mehenuf** [staxrip/staxrip#143]
![image](https://user-images.githubusercontent.com/40866680/77346367-59da7b00-6d60-11ea-9c5d-3376bc6ce218.png)
The v2.0.6.0  have this feature but in v 2.0.8.0 is missing this. Have this been relocated or permanently omitted?
![image](https://user-images.githubusercontent.com/40866680/77346762-f7ce4580-6d60-11ea-8279-7fe386056bcc.png)

And have another suggestion : you guys should add to select custom bitrate for AAC audio if i select quality the output gets different bitrate then predicted so adding custom bitrate selection will help a lot.

**Comment by tnatiuk17piano** [comment]
Which encoder are you using? If you set the encoder mode to "bitrate" mode that box should show up.

**Comment by nero1st** [comment]
If you take a look at the changelog, specifically at https://github.com/staxrip/staxrip/blob/master/Changelog.md#2075-beta you'll notice that some default settings were changed in v2.0.7.5.

To be able to choose the bitrate, just select one of the encoder modes that use them: bitrate, two pass or three pass.

For AAC or another audio codec, if you wish an exact bitrate simply choose an encoder that offers CBR rate mode (ffmpeg for example) and set the bitrate you want.

**Comment by stax76** [comment]
This is explained in the FAQ btw. 🙂

https://staxrip.readthedocs.io/faq.html#how-can-i-encode-with-a-fixed-bitrate
