### ISSUE TITLE
Jobs crashing but ONLY when i minimize the jobs window

### ISSUE THREAD

**Issue by chowderhead** [staxrip/staxrip#1432]
just to be clear this could easily be totally the result of windows but nevertheless it occurs.

when running jobs if i just click away and let them run it naturally pops up a window when demuxing a new job in queue which means i gotta click away AGAIN and again etc.  Id like to minimize to avoid all these interruptions but then jobs will start to error.  but not all of them probably every 2nd or 3rd job.  

whats the best way to debug something like this.  I run a VERY clean LTSC of win 10 and have very very few issues but this one is REPEATABLE so I thot id try and debug it since i use staxrip quite a bit.

whats your suggestion to start debugging something that behaves like this repeatably no matter the filters or NVIDIA or otherwise.  it feels system related like a memory thing or something regedit related to some system caching to ONLY surface when minimized.

thanks always
RK

**Comment by chowderhead** [comment]
a typical errror gives few clues

Video encoding returned exit code: -1073741819 (0xC0000005)

nothing else

**Comment by Dendraspis** [comment]
The nature of your issue and `0xC0000005` indicate more likely a system issue. Start running StaxRip with admin privileges and make sure the right .NET Framework is installed properly. 
Otherwise I don't think I can help. It must be a system issue.  😕

**Comment by chowderhead** [comment]
ill .NET is soid jusst got latest so i just wish i could tweak something in rezedit to allocate more ram to the process.  is there any way to do this.  I also wondered if its a communication thing between the nvenc and staxrip.  Would raising the priority of the process help at all.

**Comment by chowderhead** [comment]
I changed the priority to High and parallel processes to 12 to match my cores and its stopped crashing so for now ill claim success but some miracle of intuition.  well see if it actually fixed it or im just lucky lately that it stopped.  im  hoping its the intuition that is correct.  I think that with the process as Normal the high process of potplayer  is causing an interruption of the communication stream between AVS plugins scripts and NvenC process which must always be in sync with frameserver..  Potplayer has a setting that is set to high by default and always watch video while ripping.  When i run multiple ripping sessions i tried running 3 at once and got the same errors at random so i backed off to 2 and  problem goes away.  

its just a blind theory but maybe im correct cuz its working.  ill update progress after this 200 episodes finishes hopefully with no 0x00000005 errors.

**Comment by chowderhead** [comment]
oh and i set staxrip to run as administrator if that had an effect as well maybe.
