### ISSUE TITLE
No SDH tag for subtitles in the player

### ISSUE THREAD

**Issue by FangLeeway** [staxrip/staxrip#1433]
**Describe the bug**
The subtitle didn't get the SDH tag in the PotPlayer, since the subtitle was tagged  Hearingimpaired in the container setting of StaxRip.

**Expected behavior**
The Tagged subtitle should be shown the SDH tag like the default-tagged subtitle.

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version: v2.41.5
- Used PotPlayer version: 240618(1.7.22260)

**Notes before posting**
- Please also try the latest release of StaxRip.
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. 
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is especially true on the VapourSynth side, which will crash if your CPU don't support it.
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet.

**Please be as clear and as detailed as possible**

**Comment by Dendraspis** [comment]
When `Hearing Impaired` is set, the subtitle in the mkv container will be set properly. Players like `MPC` do recognize those subtitles as `hearing impaired`, so everything works.

So either it is an issue with `PotPlayer`, that I don't know, or you have to be more precise and present a log and/or sample.
