### ISSUE TITLE
Wrong source file loaded

### ISSUE THREAD

**Issue by Elgohan2** [staxrip/staxrip#1434]
**Describe the bug**
When I open a source file (mkv), a wrong source file is put in the source field if I have remnant video file (hevc) in temp folder.

**Expected behavior**
Having the opened file in source field.

**How to reproduce the issue**

1. Open a source file (mkv)
2. Choose `x265` video preset
3. In Options window, choose `Two Pass` or `Three Pass`
4. Click on `Run Compressibility Check`
5. Wait for compressibility check is done
6. Restart StaxRip or load/reload a template
7. __Open the same source file (mkv) as the first__
8. __In Source field, the file is not the source file opened but the encoded video file from compressibility check (`video_CompCheck.hevc`)__

**Provide information**

I use StaxRip v2.41.7 and that's happen too from previous versions. 
The same behavior occurs when encoding the same file with chunks in `x265` and don't remove the temp video files. After opening the same source file, a random chunk file is put in source field.

**Comment by Dendraspis** [comment]
Indeed, those file were never ignored. Will be changed in `v2.42`....
