### ISSUE TITLE
AutoCrop function not working

### ISSUE THREAD

**Issue by kliffgomel** [staxrip/staxrip#1435]
StaxRip 2.41.7
Source video file 4K with Dolby Vision 8.1 rpu. I want to crop by 280px top/bottom.
I cant crop in manual mode, get assistant warning "You have cropped the top side by 280px too much". Auto crop not working.
[ZV.ep2_staxrip.log](https://github.com/user-attachments/files/16336816/ZV.ep2_staxrip.log)
[HDRDVmetadata.zip](https://github.com/user-attachments/files/16336828/HDRDVmetadata.zip)

**Comment by Dendraspis** [comment]
Auto Crop is working actually, but the Dolby Vision metadata cannot be *cropped*, so this is the reason why you always get the error message from the Assistant.

You have only those solutions:
1. Don't crop the video
2. Remove the Dolby Vision data from the encoding options and then crop the video as usual.

Every other solution would lead to a broken alignment.

**Comment by kliffgomel** [comment]
> Auto Crop is working actually, but the Dolby Vision metadata cannot be _cropped_, so this is the reason why you always get the error message from the Assistant.
> 
> You have only those solutions:
> 
>     1. Don't crop the video
> 
>     2. Remove the Dolby Vision data from the encoding options and then crop the video as usual.
> 
> 
> Every other solution would lead to a broken alignment.

This is strange because in this script https://github.com/R3S3t9999/DoVi_Scripts, margin cropping works for this video.

**Comment by Dendraspis** [comment]
Sure, but the result would be different/wrong. The metadata clearly indicates, that cropping is not possible.
