### ISSUE TITLE
Error Demux audio eac3

### ISSUE THREAD

**Issue by MasY30** [staxrip/staxrip#1436]
Error Demux audio (v2.41.7)

MP4Box 2.5-DEV-rev273-gf2ce8bf1d-x64-msvc1940

D:\Sistem\StaxRip\StaxRip\Apps\Support\MP4Box\MP4Box.exe -raw 3 -out "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(3)_temp\ID1 Japanese [ja] {japoneză [originală]}.eac3" "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(3).mp4"

Filter mp4dmx failed to setup: BitStream Not Compliant
[Exporter] Cannot load filter for input file "(null)": BitStream Not Compliant
	Error: BitStream Not Compliant

Demux audio returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

StaxRip.ErrorAbortException: MP4Box 2.5-DEV-rev273-gf2ce8bf1d-x64-msvc1940

D:\Sistem\StaxRip\StaxRip\Apps\Support\MP4Box\MP4Box.exe -raw 3 -out "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(3)_temp\ID1 Japanese [ja] {japoneză [originală]}.eac3" "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(3).mp4"

Filter mp4dmx failed to setup: BitStream Not Compliant
[Exporter] Cannot load filter for input file "(null)": BitStream Not Compliant
	Error: BitStream Not Compliant


Demux audio returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 366
   at StaxRip.MP4BoxDemuxer.DemuxAudio(String sourcefile, AudioStream stream, AudioProfile ap, Project proj, Boolean overrideExisting) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 675
   at StaxRip.MP4BoxDemuxer.Run(Project proj) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 503
   at StaxRip.MainForm.Demux() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 3695
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding, Int32 timeout) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2245

**Comment by Dendraspis** [comment]
Does it also happen with other `eac3` files from another source?

**Comment by MasY30** [comment]
------------------------- System Environment -------------------------

StaxRip    : v2.41.7
Settings   : v2.38.2
Windows    : Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : English (United States)
CPU        : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
RAM        : 16GB
GPU        : NVIDIA GeForce GTX 1060
Resolution : 1920 x 1080
DPI        : 96
Code Page  : 1252

----------------------- Media Info Source File -----------------------

E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(7).mp4

General
Complete name            : E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(7).mp4
Format                   : MPEG-4
Format profile           : Base Media
Codec ID                 : isom (isom/dby1/iso2/avc1/mp41)
File size                : 272 MiB
Duration                 : 25 min 25 s
Overall bit rate mode    : Variable
Overall bit rate         : 1 496 kb/s
Frame rate               : 23.976 FPS
Collection               : Kakegurui
Season                   : 1
Track name               : Refuzul
Description              : Prinse în jocul lor de cărți ESP mortal, Midari îi povestește lui Yumeko despre meciul ei dur cu președinta consiliului elevilor, Kirari.
Recorded date            : 2017
Writing application      : Lavf60.3.100
Cover                    : Yes
Part_ID                  : 7

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Codec ID                 : avc1
Codec ID/Info            : Advanced Video Coding
Duration                 : 25 min 25 s
Bit rate mode            : Variable
Bit rate                 : 1 363 kb/s
Maximum bit rate         : 20.0 Mb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 23.976 (24000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.027
Stream size              : 248 MiB (91%)
Title                    : ?@GPAC2.3-DEV-rev7249-gb5923a16f-HEAD
Writing library          : x264 core 148 r2727 7d026e8
Codec configuration box  : avcC

Audio
ID                       : 3
Format                   : E-AC-3
Format/Info              : Enhanced AC-3
Commercial name          : Dolby Digital Plus
Codec ID                 : ec-3
Duration                 : 25 min 25 s
Bit rate mode            : Constant
Bit rate                 : 128 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 23.3 MiB (9%)
Title                    : japoneză [originală]
Language                 : Japanese
Service kind             : Complete Main
Default                  : Yes
Alternate group          : 1
Dialog Normalization     : -19 dB
compr                    : -0.28 dB
dialnorm_Average         : -19 dB
dialnorm_Minimum         : -19 dB
dialnorm_Maximum         : -19 dB

-------------------------- Error Demux audio --------------------------

MP4Box 2.5-DEV-rev273-gf2ce8bf1d-x64-msvc1940

D:\Sistem\StaxRip\StaxRip\Apps\Support\MP4Box\MP4Box.exe -raw 3 -out "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(7)_temp\ID1 Japanese [ja] {japoneză [originală]}.eac3" "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(7).mp4"

Filter mp4dmx failed to setup: BitStream Not Compliant
[Exporter] Cannot load filter for input file "(null)": BitStream Not Compliant
	Error: BitStream Not Compliant


Demux audio returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Start:    20:55:58
End:      20:56:00
Duration: 00:00:02

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: MP4Box 2.5-DEV-rev273-gf2ce8bf1d-x64-msvc1940

D:\Sistem\StaxRip\StaxRip\Apps\Support\MP4Box\MP4Box.exe -raw 3 -out "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(7)_temp\ID1 Japanese [ja] {japoneză [originală]}.eac3" "E:\Anime\Kakegurui\1\kakegurui_a-nolimit_(7).mp4"

Filter mp4dmx failed to setup: BitStream Not Compliant
[Exporter] Cannot load filter for input file "(null)": BitStream Not Compliant
	Error: BitStream Not Compliant


Demux audio returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 366
   at StaxRip.MP4BoxDemuxer.DemuxAudio(String sourcefile, AudioStream stream, AudioProfile ap, Project proj, Boolean overrideExisting) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 675
   at StaxRip.MP4BoxDemuxer.Run(Project proj) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 503
   at StaxRip.MainForm.Demux() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 3695
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding, Int32 timeout) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2245

**Comment by MasY30** [comment]
> Does it also happen with other `eac3` files from another source?
> 
> Please provide the log file or the Media Info data.

yes

**Comment by Dendraspis** [comment]
After testing also with some official versions, I can confirm that there seems to be an issue with `mp4box` and `eac3`.  😕 

So I order to solve your issue, you just have to let `ffmpeg` do the demuxing for `mp4`:

<img width=800 src=https://github.com/user-attachments/assets/bbfcb582-0971-4211-a8fb-83392c5fa7b9>

**Comment by Dendraspis** [comment]
Were you able to solve your issue with that setting?
