### ISSUE TITLE
Un-default audio streams

### ISSUE THREAD

**Issue by cartman0208** [staxrip/staxrip#1437]
I'm editing multiple sources with a template.
Some of the audio streams in those sources (mkv) have the "default" flag set.
Is there a way to unset that in a template?
Currently the flag is taken over to the resulting (mkv) file even though the checkbox is not set in the template.
I don't want any default flags at all ... usually the player language sets the output language.

**Comment by cartman0208** [comment]
Just an addition:
I noticed when the source is MP4 with default-flagged audio, the flag is not carried over to the resulting MKV

**Comment by Dendraspis** [comment]
Basically the `Default` flag should be possible to (not) set via the Audio Settings. No checkbox on `Default` should mean, that it doesn't get this flag in to resulting container. Doesn't it work for you?

**Comment by cartman0208** [comment]
Uhm, it's a bit embarassing, but I can't reproduce it today ... I changed several options, I don't even remember all of them, and now it works as expected.
I tried multiple times yesterday and eventually gave up ... now all is fine *facepalm*

**Comment by Dendraspis** [comment]
All good, just glad it works for you now.  😅

So I will close this one now. In case you can reproduce it, feel free to re-open it.
