### ISSUE TITLE
auto crop not working

### ISSUE THREAD

**Issue by zeal-ch** [staxrip/staxrip#1438]
I tested with multiple 1080p videos but it doesn't work

**Comment by Dendraspis** [comment]
Do you want to provide some more information and/or a sample file or shall I close this issue directly?

**Comment by zeal-ch** [comment]
Blu-ray Remux is too large to provide a sample
https://www.mediafire.com/file/o4tcsqds1n2pss5/Video_2024-07-28_180130_1.mp4/file
The other video is currently working fine
So I tested it with the handbrake encoder and it works 100%.
I'll have to do it manually for videos that don't work

**Comment by Dendraspis** [comment]
The only reason, that should be possible, is when there is at least one frame with brighter areas at the top and/or bottom - probably at the beginning or end. But "brighter" can also mean, that the black bar is not completely black, but dark gray, which is also brighter than the tolerance. Would be nice to have that source file though.

The next AutoCrop version will include some improvements, which could help in that case. In this case it seems you have to crop by hand.  😕 
But it's always better and less annoying to crop too less than crop too much.

**Comment by Andrasolin** [comment]
....... иy the way, the auto-analysis for crop works well. and colored or patterned stripes must be measured and indicated manually

1. https://youtu.be/yzNY2lLqw6k

2. https://youtu.be/StEkpxsf9m4

**Comment by Andrasolin** [comment]
TS: take a screenshot or use this software or Shutter Encoder and trim the video to 11 seconds

https://www.shutterencoder.com/
