### ISSUE TITLE
Muxing using mkvmerge 44.0.0 failed with exit code: 2 (0x2)

### ISSUE THREAD

**Issue by YinnVI** [staxrip/staxrip#144]
-------------------------- System Environment --------------------------

StaxRip    : 2.0.8.0
Windows    : Windows 10 Pro 1909
Language   : Indonesian (Indonesia)
CPU        : Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
GPU        : Intel(R) HD Graphics 610, NVIDIA GeForce GTX 1050
Resolution : 1920 x 1080
DPI        : 96

------------------------ MediaInfo Source File ------------------------

D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv

General
Complete name            : D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 27.1 GiB
Duration                 : 1 h 31 min
Overall bit rate mode    : Variable
Overall bit rate         : 42.6 Mb/s
Encoded date             : UTC 2020-03-18 17:54:07
Writing application      : mkvmerge v34.0.0 ('Sight and Seen') 64-bit
Writing library          : libebml v1.3.7 + libmatroska v1.5.0

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4.1
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Format, GOP              : M=1, N=12
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 1 h 31 min
Bit rate mode            : Variable
Bit rate                 : 31.2 Mb/s
Maximum bit rate         : 34.0 Mb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 23.976 (24000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.628
Stream size              : 19.9 GiB (73%)
Language                 : Japanese
Default                  : Yes
Forced                   : No

Audio #1
ID                       : 2
Format                   : DTS XLL
Format/Info              : Digital Theater Systems
Commercial name          : DTS-HD Master Audio
Codec ID                 : A_DTS
Duration                 : 1 h 31 min
Bit rate mode            : Variable
Bit rate                 : 1 509 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 93.750 FPS (512 SPF)
Bit depth                : 24 bits
Compression mode         : Lossless
Stream size              : 983 MiB (4%)
Language                 : Japanese
Default                  : Yes
Forced                   : No

Audio #2
ID                       : 3
Format                   : PCM
Format settings          : Little / Signed
Codec ID                 : A_PCM/INT/LIT
Duration                 : 1 h 31 min
Bit rate mode            : Constant
Bit rate                 : 6 912 kb/s
Channel(s)               : 6 channels
Sampling rate            : 48.0 kHz
Frame rate               : 200.000 FPS (240 SPF)
Bit depth                : 24 bits
Stream size              : 4.40 GiB (16%)
Language                 : Japanese
Default                  : No
Forced                   : No

Audio #3
ID                       : 4
Format                   : DTS XLL
Format/Info              : Digital Theater Systems
Commercial name          : DTS-HD Master Audio
Codec ID                 : A_DTS
Duration                 : 1 h 31 min
Bit rate mode            : Variable
Bit rate                 : 1 351 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 93.750 FPS (512 SPF)
Bit depth                : 24 bits
Compression mode         : Lossless
Stream size              : 880 MiB (3%)
Language                 : Japanese
Default                  : No
Forced                   : No

Audio #4
ID                       : 5
Format                   : DTS XLL
Format/Info              : Digital Theater Systems
Commercial name          : DTS-HD Master Audio
Codec ID                 : A_DTS
Duration                 : 1 h 31 min
Bit rate mode            : Variable
Bit rate                 : 1 562 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 93.750 FPS (512 SPF)
Bit depth                : 24 bits
Compression mode         : Lossless
Stream size              : 1 017 MiB (4%)
Language                 : Japanese
Default                  : No
Forced                   : No

Text
ID                       : 6
Format                   : PGS
Muxing mode              : zlib
Codec ID                 : S_HDMV/PGS
Codec ID/Info            : Picture based subtitle format used on BDs/HD-DVDs
Duration                 : 1 h 30 min
Bit rate                 : 167 kb/s
Count of elements        : 6550
Stream size              : 108 MiB (0%)
Language                 : Japanese
Default                  : Yes
Forced                   : No

Menu
00                       : 00:00.000                             : :Chapter 01
00                       : 09:55.761                             : :Chapter 02
00                       : 19:59.656                             : :Chapter 03
00                       : 29:55.418                             : :Chapter 04
00                       : 43:28.814                             : :Chapter 05
00                       : 53:38.840                             : :Chapter 06
01                       : 03:20.713                             : :Chapter 07
01                       : 13:29.780                             : :Chapter 08
01                       : 25:44.514                             : :Chapter 09

------------------ Demux MKV using mkvextract 44.0.0 ------------------

"D:\Srip\New folder - Copy\Apps\Support\MKVToolNix\mkvextract.exe" "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv" tracks 5:"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID6 Japanese.sup" 1:"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID1 Japanese.dtshd" 2:"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav" 3:"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID3 Japanese.dtshd" 4:"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID4 Japanese.dtshd" --ui-language en

Extracting track 1 with the CodecID 'A_DTS' to the file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID1 Japanese.dtshd'. Container format: Digital Theater System (DTS)
Extracting track 2 with the CodecID 'A_PCM/INT/LIT' to the file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav'. Container format: WAV
Extracting track 3 with the CodecID 'A_DTS' to the file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID3 Japanese.dtshd'. Container format: Digital Theater System (DTS)
Extracting track 4 with the CodecID 'A_DTS' to the file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID4 Japanese.dtshd'. Container format: Digital Theater System (DTS)
Extracting track 5 with the CodecID 'S_HDMV/PGS' to the file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID6 Japanese.sup'. Container format: SUP
The file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav' was written as a W64 file instead of WAV as it is bigger than 4 GB and therefore too big to fit into the WAV container.

Start:    23.31.49
End:      23.41.55
Duration: 00:10:06

General
Complete name         : D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID1 Japanese.dtshd
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
File size             : 983 MiB
Overall bit rate mode : Variable

Audio
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless
General
Complete name         : D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav
Format                : Wave64
File size             : 4.40 GiB
Duration              : 1 h 31 min
Overall bit rate mode : Constant
Overall bit rate      : 6 912 kb/s
FileExtension_Invalid : w64

Audio
Format                : PCM
Format settings       : Little / Signed
Codec ID              : 1
Duration              : 1 h 31 min
Bit rate mode         : Constant
Bit rate              : 6 912 kb/s
Channel(s)            : 6 channels
Sampling rate         : 48.0 kHz
Bit depth             : 24 bits
Stream size           : 4.40 GiB (100%)
General
Complete name         : D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID3 Japanese.dtshd
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
File size             : 880 MiB
Overall bit rate mode : Variable

Audio
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless
General
Complete name         : D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID4 Japanese.dtshd
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
File size             : 1 017 MiB
Overall bit rate mode : Variable

Audio
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless

-------------- Demux xml chapters using mkvextract 44.0.0 --------------

"D:\Srip\New folder - Copy\Apps\Support\MKVToolNix\mkvextract.exe" "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv" chapters "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_chapters.xml"

File 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv': container: Matroska
Track ID 0: video (MPEG-4p10/AVC/H.264)
Track ID 1: audio (DTS-HD Master Audio)
Track ID 2: audio (PCM)
Track ID 3: audio (DTS-HD Master Audio)
Track ID 4: audio (DTS-HD Master Audio)
Track ID 5: subtitles (HDMV PGS)
Chapters: 9 entries

Start:    23.41.55
End:      23.41.56
Duration: 00:00:00

-------------- Demux ogg chapters using mkvextract 44.0.0 --------------

"D:\Srip\New folder - Copy\Apps\Support\MKVToolNix\mkvextract.exe" "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv" chapters "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_chapters.txt" --simple

File 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv': container: Matroska
Track ID 0: video (MPEG-4p10/AVC/H.264)
Track ID 1: audio (DTS-HD Master Audio)
Track ID 2: audio (PCM)
Track ID 3: audio (DTS-HD Master Audio)
Track ID 4: audio (DTS-HD Master Audio)
Track ID 5: subtitles (HDMV PGS)
Chapters: 9 entries

Start:    23.41.56
End:      23.41.56
Duration: 00:00:00

----------------------- Indexing using ffmsindex -----------------------

"D:\Srip\New folder - Copy\Apps\Plugins\Dual\ffms2\ffmsindex.exe" "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv" "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.ffindex"

Writing index... done.

Start:    23.41.56
End:      23.45.29
Duration: 00:03:32

-------------------------- VapourSynth Script --------------------------

import os, sys
import vapoursynth as vs
core = vs.get_core()
sys.path.append(r"D:\Srip\New folder - Copy\Apps\Plugins\VS\Scripts")
core.std.LoadPlugin(r"D:\Srip\New folder - Copy\Apps\Plugins\Dual\ffms2\ffms2.dll")
core.std.LoadPlugin(r"D:\Srip\New folder - Copy\Apps\Plugins\VS\SVPFlow\svpflow1_vs64.dll")
core.std.LoadPlugin(r"D:\Srip\New folder - Copy\Apps\Plugins\VS\SVPFlow\svpflow2_vs64.dll")
clip = core.ffms2.Source(r"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv", cachefile = r"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.ffindex")
core = vs.get_core(threads=7)

clip = clip.resize.Bicubic(format=vs.YUV420P8)

crop_string  = ""
resize_string = "core.resize.Bicubic(input,1280,720)"
super_params     = "{pel:1,scale:{up:0},gpu:0,full:false,rc:true}"
analyse_params   = "{block:{w:32,overlap:0},main:{search:{coarse:{distance:-8,bad:{sad:2000}},type:2}},refine:[{thsad:250}]}"
smoothfps_params = "{gpuid:21,rate:{num:5,den:2},algo:13,mask:{area:25},scene:{mode:1}}"

def interpolate(clip):
    input = clip
    if crop_string!='':
        input = eval(crop_string)
    if resize_string!='':
        input = eval(resize_string)

    super   = core.svp1.Super(input,super_params)
    vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
    smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
    smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
    return smooth

smooth =  interpolate(clip)

smooth.set_output()

---------------------- Source Script Information ----------------------

Width     : 1920
Height    : 1080
Frames    : 131016
Time      : 01.31.04.459
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

---------------------- Target Script Information ----------------------

Width     : 1280
Height    : 720
Frames    : 327538
Time      : 01.31.04.426
Framerate : 59.940059 (60000/1001)
Format    : YUV420P8

-------------------------- VapourSynth Script --------------------------

import os, sys
import vapoursynth as vs
core = vs.get_core()
sys.path.append(r"D:\Srip\New folder - Copy\Apps\Plugins\VS\Scripts")
core.std.LoadPlugin(r"D:\Srip\New folder - Copy\Apps\Plugins\Dual\ffms2\ffms2.dll")
core.std.LoadPlugin(r"D:\Srip\New folder - Copy\Apps\Plugins\VS\SVPFlow\svpflow1_vs64.dll")
core.std.LoadPlugin(r"D:\Srip\New folder - Copy\Apps\Plugins\VS\SVPFlow\svpflow2_vs64.dll")
clip = core.ffms2.Source(r"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.mkv", cachefile = r"D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou.ffindex")
core = vs.get_core(threads=7)

clip = clip.resize.Bicubic(format=vs.YUV420P8)

crop_string  = ""
resize_string = ""
super_params     = "{pel:1,scale:{up:0},gpu:0,full:false,rc:true}"
analyse_params   = "{block:{w:32,overlap:0},main:{search:{coarse:{distance:-8,bad:{sad:2000}},type:2}},refine:[{thsad:250}]}"
smoothfps_params = "{gpuid:21,rate:{num:5,den:2},algo:13,mask:{area:25},scene:{mode:1}}"

def interpolate(clip):
    input = clip
    if crop_string!='':
        input = eval(crop_string)
    if resize_string!='':
        input = eval(resize_string)

    super   = core.svp1.Super(input,super_params)
    vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
    smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
    smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
    return smooth

smooth =  interpolate(clip)

smooth.set_output()

---------------------- Source Script Information ----------------------

Width     : 1920
Height    : 1080
Frames    : 131016
Time      : 01.31.04.459
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

---------------------- Target Script Information ----------------------

Width     : 1920
Height    : 1080
Frames    : 327538
Time      : 01.31.04.426
Framerate : 59.940059 (60000/1001)
Format    : YUV420P8

----------------------- MediaInfo Audio Source 1 -----------------------

General
Complete name : D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav
File size     : 555 MiB

------------------- Video encoding using QSVEnc 3.33 -------------------

"D:\Srip\New folder - Copy\Apps\Encoders\QSVEnc\QSVEncC64.exe" --codec hevc --profile main10 --ref 5 --b-adapt --direct-bias-adjust --mbbrc --output-buf 128 --input-buf 3 --output-thread 1 --fullrange --sao all --ctu 64 --icq 18 -i "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new.vpy" -o "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new_out.hevc"

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new_out.hevc
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Adaptve B-frame insert is not supported on current platform, disabled.
Direct Bias Adjust is not supported on current platform, disabled.
HEVC CTU is not supported on current platform, disabled.
HEVC SAO is not supported on current platform, disabled.
cop3.DirectBiasAdjustment value changed off -> auto by driver
cop3.GlobalMotionBiasAdjustment value changed off -> auto by driver
QSVEncC (x64) 3.33 (r1761) by rigaya, Mar  7 2020 13:22:22 (VC 1916/Win/avx2)
OS             Windows 10 x64 (18363)
CPU Info       Intel Pentium(R) G4560 @ 3.50GHz (2C/4T) <Kabylake>
GPU Info       Intel HD Graphics 610 (12EU) 1050MHz (26.20.100.7262)
Media SDK      QuickSyncVideo (hardware encoder) PG, 2nd GPU, API v1.30
Async Depth    4 frames
Buffer Memory  d3d11, 3 input buffer, 14 work buffer
Input Info     VapourSynthMT r48(yv12)->p010 [SSE2], 1920x1080, 60000/1001 fps
AVSync         cfr
Output         HEVC main10 @ Level 4.1 (high tier)
1920x1080p 1:1 59.940fps (60000/1001fps)
Target usage   4 - balanced
Encode Mode    ICQ (Intelligent Const. Quality)
ICQ Quality    18
QP Limit       min: none, max: none
Trellis        Auto
Ref frames     5 frames
Bframes        3 frames, B-pyramid: on
Max GOP Length 600 frames
VUI            range:full
Ext. Features  PerMBRC WeightP WeightB ctu:32 sao:none
encoded 327538 frames, 44.22 fps, 2503.58 kbps, 1630.86 MB
encode time 2:03:27, CPU: 73.4, GPU: 89.2, VD: 7.9
frame type IDR      1
frame type I      547,  total size    37.35 MB
frame type P    81885,  total size  1144.54 MB
frame type B   245107,  total size   448.98 MB

Start:    01.02.36
End:      03.06.10
Duration: 02:03:34

General
Complete name        : D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new_out.hevc
Format               : HEVC
Format/Info          : High Efficiency Video Coding
File size            : 1.59 GiB

Video
Format               : HEVC
Format/Info          : High Efficiency Video Coding
Format profile       : Main 10@L4.1@High
Width                : 1 920 pixels
Height               : 1 080 pixels
Display aspect ratio : 16:9
Frame rate           : 59.940 (60000/1001) FPS
Color space          : YUV
Chroma subsampling   : 4:2:0
Bit depth            : 10 bits
Color range          : Full

------------------ Error Muxing using mkvmerge 44.0.0 ------------------

Muxing using mkvmerge 44.0.0 failed with exit code: 2 (0x2)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

The system cannot find the file specified

--------------------- Muxing using mkvmerge 44.0.0 ---------------------

"D:\Program Files\MKVToolNix\mkvmerge.exe" -o "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new.mkv" "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new_out.hevc" --audio-tracks 0 --language 0:jpn --default-track 0:0 --forced-track 0:0 "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav" --chapters "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_chapters.xml" --ui-language en

mkvmerge v44.0.0 ('Domino') 64-bit
'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new_out.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
Error: The demultiplexer for the file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav' failed to initialize:
The file headers could not be parsed, e.g. because they're incomplete, invalid or damaged.

--------------------- Muxing using mkvmerge 44.0.0 ---------------------

"D:\Program Files\MKVToolNix\mkvmerge.exe" -o "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new.mkv" "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new_out.hevc" --audio-tracks 0 --language 0:jpn --default-track 0:0 --forced-track 0:0 "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav" --chapters "D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_chapters.xml" --ui-language en

mkvmerge v44.0.0 ('Domino') 64-bit
'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou 1080_new_out.hevc': Using the demultiplexer for the format 'HEVC/H.265'.
Error: The demultiplexer for the file 'D:\Torrent\New folder\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp\[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav' failed to initialize:
The file headers could not be parsed, e.g. because they're incomplete, invalid or damaged.

Start:    03.06.10
End:      03.06.10
Duration: 00:00:00

**Comment by Patman86** [comment]
I've had the problem before and for me it was due to the length of the file name. Shorten the file name and then it should work (less than 255 characters).

**Comment by stax76** [comment]
Exit code 2:

> 2 -- This exit code is used after an error occurred. mkvmerge(1) aborts right after outputting the error message. Error messages range from wrong command line arguments over read/write errors to broken files.

> Error: The demultiplexer for the file '**D:\Torrent\New folder[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou_temp[BDREMUX] Violet Evergarden Gaiden Eien To Jidou Shuki Ningyou ID2 Japanese.wav**' failed to initialize:
> **The file headers could not be parsed, e.g. because they're incomplete, invalid or damaged**.

I've pasted the path to VS Code and it says 168 characters, probably something is wrong with the wave file, maybe convert to FLAC or let ffmpeg re-create the WAV file, staxrip should be able to do both.

This possibly could be a mkvtoolnix bug so if you have time maybe report it to the mkvtoolnix author, in this case you need to upload a sample and post simple command lines so the author can reproduce it easily, it is some work, your decision.
