### ISSUE TITLE
The named argument "tone_mapping_function" to libplacebo_Tonemap had the wrong type

### ISSUE THREAD

**Issue by Elgohan2** [staxrip/staxrip#1440]
**Describe the bug**
Unable to use "Auto" tone mapping in Libplacebo.

**Expected behavior**
Use "Auto" value whatever it's realy.

**How to reproduce the issue**

1. Choose "AVS Filters"
2. Right click to add "Color>Tonemap>Placebo"
3. Choose a source color space ("HDR10" for example), a target color space ("SDR" for example), a dynamic peak detection ("Yes (default)" for example, a Tonemapping Function ("Auto (default)" for example) and a Tonemapping Mode ("Auto (default)" for example)

An error message appear:
```
Script error: the named argument "tone_mapping_function" to libplacebo_Tonemap had the wrong type
(D:\video.mkv, line 8)
```

**Provide information**
StaxRip v2.41.7 is used.

**Additional context**

The code generated in my example is:
```
ConvertBits(16)
libplacebo_Tonemap(src_csp=1, dst_csp=0, dynamic_peak_detection=True, tone_mapping_function=0, tone_mapping_mode=0)
# ConvertBits(8)
# ConvertToYUV420()
```

According to the official [documentation](https://github.com/Asd-g/avslibplacebo#tone-mapping), the possibles values for `tone_mapping_function` are:
- `clip`
- `st2094-40`
- `st2094-10`
- `bt2390`
- `bt2446a`
- `spline`
- `reinhard`
- `mobius`
- `hable`
- `gamma`
- `linear`
- `linearlight`

There is no numeric values. If a put by myself `tone_mapping_function="bt2390"` instead of `tone_mapping_function=0` in the code editor, the error message become:
```
Script error: libplacebo_Tonemap does not have a named argument "tone_mapping_mode"
(D:\video.mkv, line 8)
```

There is no help for "tone_mapping_mode" argument in the official documentation.

**Comment by Elgohan2** [comment]
Yes, you're right, after restoring defaults in `Profiles`, no error message appears.

But if I want to preview my encoding, an error message appears in a pop-up:
```
Script Error

System exception - Access Violation
(D:\Video_HDR\video_view.avs, line 13)
```

I tried with a brand new template from "Automatic Workflow".

**Comment by Dendraspis** [comment]
Can you post the content of the mentioned file?

**Comment by Elgohan2** [comment]
It's a very big file, I'll try to cut it and make sure the error still appear with the cutted file.

**Comment by Elgohan2** [comment]
Here's a 20 seconds sample of the file I want to convert from HDR to SDR using libplacebo: https://mega.nz/file/CYY20QKB#8pee0E70EgUzYBeI0nMy6VySNHgGNmzonBExIg9KPOU

**Comment by Dendraspis** [comment]
Sorry, little misunderstanding: I meant the content of this file:  `D:\Video_HDR\video_view.avs`   😅

**Comment by Elgohan2** [comment]
Here it is: https://mega.nz/file/idAW3QTJ#34aXeptPa3egm8klfvApXEsr7mNAIW9C6GJtWsLacGA
😄

**Comment by Dendraspis** [comment]
Does it also happen when you disable the Resize filter ?

**Comment by Elgohan2** [comment]
I will try that but not now, and I will be away from home for about 10 days.

**Comment by Dendraspis** [comment]
Damn.  😅 
Have a nice holiday/trip, see you in ~2 weeks.

**Comment by Elgohan2** [comment]
Hi, I'm back! :)

I have the same error when I disable Resize filter. But I opened the automaticaly created `recovery.srip` project on a different computer and I can preview the encoding without error!

There is the specs of my computers:
1. (the one with the error): AMD Ryzen 5 5600X 6-Core / 16 Go / Nvidia GT 710 2 Go (without connected screen, accessing to it only by RDP/VNC)
2. (the one without error): AMD Ryzen 5 5900X 12-Core / 32 Go / AMD Radeon RX 6900 XT 16 Go

On both I have Windows 11 LTSC 24H2, same StaxRip version.

Maybe the GPU is the culprit?

**Comment by Dendraspis** [comment]
That GPU, maybe combined with using RDP/VNC only, should be the reason as those filters use the GPU for such jobs.
Maybe it can help installing new drivers, especially Vulkan drivers, but who knows. It definitely has something to do twith the GPU, sadly that's all I can tell.

**Comment by Elgohan2** [comment]
I installed latest NVIDIA drivers for that GPU and I keep a screen plugged to the computer, and I have the same error. So, I don't think now that the lack of drivers and/or RDP/VNC is the culprit. :(

**Comment by Dendraspis** [comment]
So it should be an issue with your GPU itself.  🫤
