### ISSUE TITLE
Crash after opening a source file

### ISSUE THREAD

**Issue by KelvinSoh8** [staxrip/staxrip#1441]
------------------------- System Environment -------------------------

StaxRip    : v2.41.7
Settings   : v2.41.7
Windows    : Windows 10 Pro for Workstations 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : English (United States)
CPU        : AMD Ryzen 7 3700X 8-Core Processor
RAM        : 40GB
GPU        : NVIDIA GeForce GTX 1660
Resolution : 3840 x 2160
DPI        : 144
Code Page  : 936

----------------------- Media Info Source File -----------------------

E:\Suzume 4K HDR10 DTS-HD.mkv

General
Complete name                     : E:\Suzume 4K HDR10 DTS-HD.mkv
Format                            : Matroska
Format version                    : Version 4
File size                         : 27.5 GiB
Duration                          : 2 h 1 min
Overall bit rate mode             : Variable
Overall bit rate                  : 32.5 Mb/s
Frame rate                        : 23.976 FPS
Encoded date                      : 2024-02-10 10:36:10 UTC
Writing application               : mkvmerge v82.0 ('I'm The President') 64-bit
Writing library                   : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                                : 1
Format                            : HEVC
Format/Info                       : High Efficiency Video Coding
Format profile                    : Main 10@L5.1@High
HDR format                        : SMPTE ST 2086, HDR10 compatible
Codec ID                          : V_MPEGH/ISO/HEVC
Duration                          : 2 h 1 min
Bit rate                          : 28.4 Mb/s
Width                             : 3 840 pixels
Height                            : 2 160 pixels
Display aspect ratio              : 16:9
Frame rate mode                   : Constant
Frame rate                        : 23.976 (24000/1001) FPS
Color space                       : YUV
Chroma subsampling                : 4:2:0 (Type 2)
Bit depth                         : 10 bits
Bits/(Pixel*Frame)                : 0.143
Stream size                       : 24.1 GiB (88%)
Default                           : Yes
Forced                            : No
Color range                       : Limited
Color primaries                   : BT.2020
Transfer characteristics          : PQ
Matrix coefficients               : BT.2020 non-constant
Mastering display color primaries : BT.2020
Mastering display luminance       : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level       : 996 cd/m2
Maximum Frame-Average Light Level : 817 cd/m2

Audio
ID                                : 2
Format                            : DTS XLL
Format/Info                       : Digital Theater Systems
Commercial name                   : DTS-HD Master Audio
Codec ID                          : A_DTS
Duration                          : 2 h 1 min
Bit rate mode                     : Variable
Bit rate                          : 3 848 kb/s
Channel(s)                        : 6 channels
Channel layout                    : C L R Ls Rs LFE
Sampling rate                     : 48.0 kHz
Frame rate                        : 93.750 FPS (512 SPF)
Bit depth                         : 24 bits
Compression mode                  : Lossless
Stream size                       : 3.26 GiB (12%)
Language                          : Japanese
Default                           : Yes
Forced                            : No

Text #1
ID                                : 3
Format                            : PGS
Muxing mode                       : zlib
Codec ID                          : S_HDMV/PGS
Codec ID/Info                     : Picture based subtitle format used on BDs/HD-DVDs
Duration                          : 2 h 0 min
Bit rate                          : 207 kb/s
Frame rate                        : 1.463 FPS
Count of elements                 : 10600
Stream size                       : 179 MiB (1%)
Language                          : Japanese
Default                           : Yes
Forced                            : No

Text #2
ID                                : 4
Format                            : PGS
Muxing mode                       : zlib
Codec ID                          : S_HDMV/PGS
Codec ID/Info                     : Picture based subtitle format used on BDs/HD-DVDs
Duration                          : 2 h 0 min
Bit rate                          : 131 kb/s
Frame rate                        : 1.161 FPS
Count of elements                 : 8366
Stream size                       : 112 MiB (0%)
Language                          : English
Default                           : Yes
Forced                            : No

Text #3
ID                                : 5
Format                            : PGS
Muxing mode                       : zlib
Codec ID                          : S_HDMV/PGS
Codec ID/Info                     : Picture based subtitle format used on BDs/HD-DVDs
Duration                          : 2 h 0 min
Bit rate                          : 130 kb/s
Frame rate                        : 1.137 FPS
Count of elements                 : 8191
Stream size                       : 112 MiB (0%)
Language                          : Chinese
Default                           : Yes
Forced                            : No

------------------------------ Demux MKV ------------------------------

mkvextract 85.0

"A:\Green Program\StaxRip-v2.41.7-x64\Apps\Support\MKVToolNix\mkvextract.exe" --ui-language en "E:\Suzume 4K HDR10 DTS-HD.mkv" tracks 3:"E:\Suzume 4K HDR10 DTS-HD_temp\ID2_[en]_default.sup" 1:"E:\Suzume 4K HDR10 DTS-HD_temp\ID1 Japanese [ja].dtshd"

Extracting track 1 with the CodecID 'A_DTS' to the file 'E:\Suzume 4K HDR10 DTS-HD_temp\ID1 Japanese [ja].dtshd'. Container format: Digital Theater System (DTS)
Extracting track 3 with the CodecID 'S_HDMV/PGS' to the file 'E:\Suzume 4K HDR10 DTS-HD_temp\ID2_[en]_default.sup'. Container format: SUP

Start:    5:28:33 PM
End:      5:33:42 PM
Duration: 00:05:08

General
Complete name         : E:\Suzume 4K HDR10 DTS-HD_temp\ID1 Japanese [ja].dtshd
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
File size             : 3.26 GiB
Overall bit rate mode : Variable

Audio
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
Bit rate mode         : Variable
Channel(s)            : 6 channels
Channel layout        : C L R Ls Rs LFE
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless

---------------------- Indexing using ffmsindex ----------------------

"A:\Green Program\StaxRip-v2.41.7-x64\Apps\Plugins\Dual\ffms2\ffmsindex.exe" "E:\Suzume 4K HDR10 DTS-HD.mkv" "E:\Suzume 4K HDR10 DTS-HD_temp\temp.ffindex"

Writing index... done.

Start:    5:33:42 PM
End:      5:37:39 PM
Duration: 00:03:57

------------------------------ Auto Crop ------------------------------

AutoCrop 2.4

"A:\Green Program\StaxRip-v2.41.7-x64\Apps\Support\AutoCrop\AutoCrop.exe" "E:\Suzume 4K HDR10 DTS-HD_temp\Suzume 4K HDR10 DTS-HD_new_source.avs" 1 15 0

0,277,0,276

Start:    5:37:41 PM
End:      5:40:19 PM
Duration: 00:02:38

------------------------------ Exception ------------------------------

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at StaxRip.Startup.Main() in D:\Code\Github\staxrip\staxrip\Source\General\Misc.vb:line 1006

**Comment by Dendraspis** [comment]
Are you able to create a short and small sample, that can reproduce this issue?
