### ISSUE TITLE
StaxRip SHIM Icon NOT Launching App

### ISSUE THREAD

**Issue by AYColumbia** [staxrip/staxrip#1443]
**Describe the bug**
The SHIM desktop shortcut is not working as expected.  After double clicking it, it briefly displays what looks like a command/dos window and disappears.

**Expected behavior**
When the SHIM shortcut is used I expect StaxRip to be launched.

**How to reproduce the issue**
- Use Windows 11 OS
- Install or upgrade StaxRip with Chocolatey until it puts the SHIM shortcut icon on the desktop
- Try to launch the app with the shortcut

Current SR version: StaxRip-v2.41.7-x64

**Additional context**
The shortcut points to: C:\ProgramData\chocolatey\bin\staxrip.exe

![2024-08-02 21_48_45-StaxRip SHIM shortcut](https://github.com/user-attachments/assets/9009729a-bf92-4310-bc97-31bdd4996138)

Please let me know if you need any other info.  Thank you.

**Comment by Dendraspis** [comment]
StaxRip is published as Win64 EXE file only. Every packaging with Chocolatey, Docker or so is not supported officially, so I can't tell what was done to that one and why it doesn't work the way it maybe should work.

**Comment by AYColumbia** [comment]
Hi, okay thanks.  I hadn't realized that so I'll point the Chocolatey packaging author to this issue to see if they can do anything.  Thank you.
