### ISSUE TITLE
Improper VCEEnc parameters being passed through. Also number of parameters are lacking 

### ISSUE THREAD

**Issue by DimkaTsv** [staxrip/staxrip#1444]
**Describe the bug**
Some parameters that StaxRip passes as VCEEnc options are improper and error out.
And some parameters are very far from being up-to-date. 

For example:
1. HEVC and AV1 for quite some time also support QVBR, HQVBR and HQCBR, not just AVC. (But that one can be understood, it can only be seen by AMF TranscodeHW tool, which shows all options available, and Rigaya doesn't update parameters file very often)
2. There are no options to enable `--dhdr10-info copy`
3. There are also missing options for basic options to copy/encode more colorspace parameters (not through `--vpp-colorspace` option), aka `--colorrange` `--chromaloc` `--max-cll` `--master-display` `--atc-sei`. (And plenty of other options)
4. (non-critical) `--quality` option technically doesn't exist, but for some reason VCEEnc still accepts it, heh. Instead by documentation it is called `--preset` (which is also called "Preset" in GUI, but when changed it writes parameter as --quality in command line prompt)

**Expected behavior**
`--pa ltr=` boolean state is not true boolean, so it accepts worded "true" as parameter when enabled. (aka `--pa ltr=true`)
`--pa motion-quality`, as written in error message below can only take "none" or "auto" as parameters, while StaxRip tried to set it to 1 instead

**How to reproduce the issue**

1. Use AMD GPU (For VCEEnc to work)
2. Import file
3. Use VCEEnc encoder
5. Go to "Encoder Options"
6. Go to "Preanalysis" and toggle "Pre-Analysis to enhance quality"
7. 2 options that are broken are "Enable automatic LTR frame management" when set to "True", and "High motion quality boost mode", when set to "Auto"

Which is kinda amusing, as in interface they actually provide you switches as proper argument to pass, but in command line it becomes "nothing" if False, or "1" if True.

**Provide information**

Thrown errors:

`Error: Invalid value "1" for "--pa ltr=" `

```
Error: Invalid value "1" for "--pa motion-quality="
  Option value should be one of below...
    none, auto
```

Used StaxRip version - v2.41.7

**Additional context**

Not that there can be much of additional context, but if any question appears, i will try my best to answer.

**Comment by Dendraspis** [comment]
Thanks for the report.
`VCEEncC` is one of those encoders, that nobody seems to use. The issues were never reported before and my poll on Discord always indicates no users - at least within the small group of participants.

1. The support seems to be proper:  
<img width=300 src=https://github.com/user-attachments/assets/496295d5-9519-422e-b955-26ae9c626bea>

2. Just type `copy` in and you should be fine:
<img width=600 src=https://github.com/user-attachments/assets/7ef6e2eb-29a9-4166-b655-2e00603ab2ee>


3. VUI parameters are copied over by default, unless you disable the option. But you're right, there are options missing, that will be  added with `v2.42` - at least the few you mentioned and I could find.
4. Oh yeah, will be fixed for `v2.42`.
5. The `--pa` parameter values will be fixed in `v2.42`:
<img width=600 src=https://github.com/user-attachments/assets/3a389698-523d-4543-ac08-ad3da7f27fca>

**Comment by DimkaTsv** [comment]
>VCEEncC is one of those encoders, that nobody seems to use. The issues were never reported before and my poll on Discord always indicates no users - at least within the small group of participants.

Well, tbh most of AMD users don't usually do transcodes or do it on basic software like Handbrake (even though VCEEnc is SOO MUCH BETTER!). And others are already using command line version of VCEEnc so there was no reason to try GUI (i was one of them, and when tried to do a comparison for someone on internet i decided to use StaxRip for first time). 

1. Rigaya didn't update this part of a page (and i reminded him few times, _sigh_). AMF developers added support for these modes for HEVC at some point. 
Here is from AMF documentation (https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_HEVC_API.md):
![image](https://github.com/user-attachments/assets/d74ae539-916a-4ec3-9b18-062ae02677b2)

And as i personally used HEVC QVBR and HQVBR on VCEEnc, can confirm that these methods work. 
Here is proof that it works: (also yeah, HQVBR may generate with bitrate below set average due to how it works and is like 3 times slower than normal VBR. But it does help quite a lot with 1% and even 5% lows in comparison, even if slightly sacrifices average benchmarking scores)
```
C:\Users\DimkaTsv\Videos\test sample>C:\Users\DimkaTsv\Desktop\Utilites\VCE_Encoder\VCEEncC_x64\\VCEEncC64.exe -i "C:\Users\DimkaTsv\Videos\test sample\Test_softer.mkv" -o "Test_softer_processed.mkv" --codec hevc --profile main --level 6.2 --tier high --preset slow --vbrhq 10000 --max-bitrate 40000 --pa
--------------------------------------------------------------------------------
Test_softer_processed.mkv
--------------------------------------------------------------------------------
Pre-analysis will be enabled for VBR-HQ mode.
VCEEnc (x64) 8.23 (r1710) by rigaya, Jul 18 2024 12:57:57 (VC 1940/Win)
OS:            Windows 11 x64 (22631) [UTF-8]
CPU:           AMD Ryzen 7 5800X3D 8-Core Processor [4.46GHz] (8C/16T)
GPU:           AMD Radeon RX 7800 XT [32.0.11029.1008]
AMF:           Runtime 1.4.34 / SDK 1.4.34
Input Info:    avvce: H.265/HEVC, 3840x2160, 24000/1001 fps
VPP            cspconv(p010 -> yv12)
               cspconv(yv12 -> nv12)
Output:        H.265/HEVC  main @ Level 6.2 (high tier)
               3840x2160p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc => matroska
Quality:       slow
VBR-HQ:           10000 kbps
Max bitrate:   40000 kbps
QP:            Min: 0:0, Max: 51:51
VBV Bufsize:   10000 kb
Bframes:       0 frames
Pre Analysis:  sc medium, ss high, activity y
               lookahead 0, caq medium, paq none, taq 0, motion-qual none, ltr off
Ref frames:    2 frames
LTR frames:    0 frames
Motion Est:    Q-pel
Slices:        1
GOP Len:       240 frames
Others:        skipframe:on deblock
Terminating internal PA thread , 7777 kb/s, remain 0:00:00, GPU 4%, VE 96%, est out size 148.4MB

encoded 3861 frames, 22.76 fps, 7790.36 kbps, 149.55 MB
encode time 0:02:49, CPU: 0.1%, GPU: 4.4%, VE: 99.0%
frame type IDR   87
frame type I     87,  avgQP  22.59,  total size    5.68 MB
frame type P   3774,  avgQP  22.56,  total size  143.87 MB

C:\Users\DimkaTsv\Videos\test sample>pause
Для продолжения нажмите любую клавишу . . .
```

2. Oh! I see, yeah that wasn't obvious for me, but i can see why it was done like that (i know that this parameter can accept both  "copy" and path to metadata file), thanks. Maybe some UI hint would help, though. Maybe some checkbox next to it that will allow user to set it to copy, and lock out path field?

3-5.  Super, will test it out when it will be released. (AMF also updated to 8.23 since last StaxRip update)

I will also note that currently i don't see a way to use scalar functionality with HW encoder specific parameters. But maybe i am just blind? (which is partially true, ngl) 
In case of AMF and VCEEnc scalar can be called as `--vpp-resize` with many options from which there are several specific to AMF.  `amf_point` (broken for quite a while and will produce green screen, that is why was removed out of documentation. But functionality still exists. Who knows, maybe AMF devs will manage to fix it some day), `amf_bilinear`, `amf_bicubic` and `amf_fsr` (There is also amf_fsr2 within AMF documentation, but it is quite restricted and almost never applicable). In addition to that amf_fsr scaler can take on additional unique parameter called `--vpp-scaler-sharpness` with range of 0.0-2.0 and default value of 0.5 (Again, specific to amf_fsr. It won't work for any other scalar)

**Comment by Dendraspis** [comment]
Very interesting. Seems like `VCEEncC` is not just not used by StaxRip users.  😅 

1. Thanks for the proof, I have enabled all modes for all codecs now, which will be available in `v2.42`.
2. I will add a hint to the help text, but nothing more I guess.


> I will also note that currently i don't see a way to use scalar functionality with HW encoder specific parameters.

I guess you mean this one, which is already implemented without those not documented values:
<img width=600 src=https://github.com/user-attachments/assets/a957b4de-a720-4cc3-9def-532173e212f6>

**Comment by DimkaTsv** [comment]
>Very interesting. Seems like VCEEncC is not just not used by StaxRip users. 😅
>1. Thanks for the proof, I have enabled all modes for all codecs now, which will be available in v2.42.
>2. I will add a hint to the help text, but nothing more I guess.

Well, i am not even sure if VCEEnc is that popular compared to NVEnc and QSVEnc. Nvidia has much larger market share, Intel has it's QSV embedded in iGPU's, which are quite common. AMD mainsteam CPU's (except Ryzen 7000), on other hand do not have iGPU's with VCN support, afaik. And users with specific needs compile their own applications using AMF framework directly. 

>I guess you mean this one, which is already implemented without those not documented values:

Oh, yeah then it's me being blind. Oops. 
And as non-experienced user... How does it interact with this part of StaxRip? 
![image](https://github.com/user-attachments/assets/7af19221-82a2-44cc-90bb-8998f3a771a9)

Or does this resize option do not apply if you use HW encoder?

**Comment by Dendraspis** [comment]
> Well, i am not even sure if VCEEnc is that popular compared to NVEnc and QSVEnc.

Definitely not, I can tell you.  😁 

> And as non-experienced user... How does it interact with this part of StaxRip?

The Resize function on the main window normally just sets/affects the scripts, but there is a small exception or help:
You can select the `Hardware Encoder` Resizer so the value is set to the encoder command line using `--output-res` in that case:

<img width=500 src=https://github.com/user-attachments/assets/4d631e4f-ee59-4c64-bc08-488168bd683f>
<img width=500 src=https://github.com/user-attachments/assets/c1b8292b-a439-4f88-97ec-8268526e14ea>

**Comment by DimkaTsv** [comment]
>You can select the Hardware Encoder
Welp, i definitely was blind, it seems... Hadn't thought to properly look for RMB options and checked only what double-click does. 

Thanks. You were of a great help. Will wait for v2.42. 

Tbh, i feel kinda overwhelmed with options for now, as, for now, i don't quite understand what most of them do. But time, experience gain and a lot of googling will definitely help me out with this. 
I did note importing times, though. It can take quite a bit more time compared to other tools (due to autocrop step), which i was caught off guard with on my first time.

**Comment by Dendraspis** [comment]
You're welcome.
`v2.42` will take a while and because there were already various changes made to `VCEEncC` I won't put that much time to make a hotfix.

> Tbh, i feel kinda overwhelmed with options

Yeah, it is. Depending on how you want to use such an encoder you have to study a lot of parameters and also try different settings to see what they do.

>  It can take quite a bit more time compared to other tools (due to autocrop step), which i was caught off guard with on my first time.

Depending on your source file and settings:  Yes. Demuxing takes a while, AutoCrop, HDR metadata extraction and especially indexing also need their time to prepare the source. It has its pros and cons.
