### ISSUE TITLE
Tool Errors on Win7 in 2.41.7:  AVI (DV) / MPEG VOB content.

### ISSUE THREAD

**Issue by tascani11** [staxrip/staxrip#1445]
Hi, been using Staxrip for years. In the lastest 2.41 version I now get a couple of errors:
- I'm on Win 7.
- Because of my system, on a new version I always replace the JPSDR AVX2 default dll with the appropiate Win7 AVX dll.

1 - Opening an AVI source (DV capture):
a - I get this error: 

![Error](https://github.com/user-attachments/assets/c5b2e756-2823-4a96-90ad-8ba1920242e3)

b - After simply dismissing that error, I then get this other one:

![AVI Demux Error](https://github.com/user-attachments/assets/4bd8e399-bcc7-4d20-b4d4-da214c0fe9f4)

2 - Encoding MOV Prores from DVD source file (MPEG/VOB), I get this error:

![Encode DVD mpeg Error](https://github.com/user-attachments/assets/037c2ddd-dd80-4f31-8a9d-47a04ffddda6)

My workflow's been fine up to Staxrip 2.40. The test files are exactly the same ones I've used for years.
It probably has something to do with the major FFMPEG update for this new version.

I appreciate any help with this.

**Comment by Dendraspis** [comment]
Windows 7 is not supported anymore for a decent amount of time and it looks like some tools are build with newer compilers, that also don't support Windows 7 anymore.

The only thing you can do is try to find a working and compatible binaries of `SvtAv1EncApp` and `ffmpeg` and replace them.

**Comment by tascani11** [comment]
Good enough, I understand.
Thanks a lot for your explanation.

**Comment by Ding-adong** [comment]
Try this as it worked on Window 7 for me.

https://github.com/kusaanko/FFmpeg-Auto-Build/releases
