### ISSUE TITLE
Unwanted trim at the beginning of a video which has ?blank? in its start (not an actual problem)

### ISSUE THREAD

**Issue by gkalemis** [staxrip/staxrip#1446]
**Describe the bug**
Reencoding videos trim them for a second or so in the beginning when they are blank 

**Expected behavior**
Original and reencoded video should have the same length

**How to reproduce the issue**
I am reencoding a lot of videos. I have some settings and I am very happy with them. But I decided to compare some videos and realized that there is one second or so trim in the begging of the reencoded videos. The reencoded video is also 1 second short. It is happening ONLY in videos that have a delayed (maybe blank) start.

I have reencoded the videos with different settings H265 NVe or x265 with the same results.

It is not an actual problem but sometimes hinders the comparing of the videos

**Provide information**

Staxrip version v2.41.7

**Comment by Andrasolin** [comment]
and this is a bug in codec 265/HEVC when processing HD and SD content. when processing HD/SD video content with the 265 codec, their fps should be more than 30fps-1080 and 60fps-720 and lower resolution

1080p and lower resolution = 264/AVC

1440p AND HIGHER = 265/HEVC

**Comment by Andrasolin** [comment]
Staxrip software is becoming popular, people with poor knowledge about codecs and filters use it more often and complain that it doesn’t work with 1 click

**Comment by gkalemis** [comment]
FIle is here https://file.io/BOZBsxFghjrg Sorry for the delay.

**Comment by gkalemis** [comment]
Also, as I already said, it is not a real issue. Probably the original videos, like the sample that I have posted, have an issue themselves. Take care and thank you again. The delay was because I wasn't at home and didn't have a way to crop the original video.

**Comment by gkalemis** [comment]
> Do you have a small file that you can share with me?

https://file.io/BOZBsxFghjrg
