### ISSUE TITLE
x265 hdr option error

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#145]
Hi,
[As stated in x265 documents for v3.3](https://x265.readthedocs.io/en/default/releasenotes.html#version-3-3):
```
Renamed --hdr to --hdr10
Renamed --hdr-opt to --hdr10-opt
```

Now, there are two options in StaRip on tab VUI
"`Add luma and chroma offsets for HDR/WCG content`" which adds command `--hdr-opt`
"`Block-level QP optimization for HDR10 content`" which adds command `--hdr10-opt`

Both of these commands are the same. One of them are enough either -`-hdr-opt` or `--hdr10-opt` and it should be `--hdr10-opt` because the other one will be removed in the next updates.

Thanks

**Comment by stax76** [comment]
Hi,
I've updated it locally, thanks.
