### ISSUE TITLE
Can't cut HDR > SDR video

### ISSUE THREAD

**Issue by fa1rid** [staxrip/staxrip#1454]
![image](https://github.com/user-attachments/assets/4200e006-021e-492b-8fbb-1eda74513041)

**Comment by Dendraspis** [comment]
Oh yeah, nasty bug.  Thanks for the report, will be fixed in `v2.42`.

For now the only workaround is to make sure the Dolby Vision metadata extraction is disabled in the project options before opening the source file.   😕

**Comment by fa1rid** [comment]
I already disabled metadata extraction (before opening the source file) as shown below.

![image](https://github.com/user-attachments/assets/ec1ab92b-9f55-4cef-b369-dc68292cc771)

I don't understand, why can't the video?

**Comment by Dendraspis** [comment]
No, you have not. You have to set `Extract HDR metadata` to `HDR10+ only` or turn it off completely.

**Comment by fa1rid** [comment]
In this guide here it only says to Disable "Import VUI metadata"

![image](https://github.com/user-attachments/assets/2df547ae-909c-4e96-972c-61acbe66a77b)

I will try to turn off "Extract HDR metadata", but what's the difference than "Import VUI metadata"?

Thanks!

**Comment by Dendraspis** [comment]
Like I said there is a bug and what I have mentioned was a workaround to get the encode running without waiting a few weeks for the next release.
