### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1458]
I checked the "Log files" folder - there are records and saves of only 100% processing without errors. And the “Log files” with errors are not recorded and saved. The separately displayed Message about "Info window with error" is not recorded and saved.

![001](https://github.com/user-attachments/assets/af97f0c0-b557-4bad-9ed8-dd2f774dfceb)

**Comment by Dendraspis** [comment]
All log files are saved next to the project in the temp folder and only the succeeded encodes log files are copied over to have them after the source might be deleted.
Why should anyone want to keep log files of failed encodes?
