### ISSUE TITLE
--input now needed

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1459]
Now --input is needed to have the last version of x265 to work.

Please have a look at Patman's last build and post [here](https://github.com/Patman86/x265-Mod-by-Patman/issues/27#issuecomment-2323413067).

**Comment by tormento** [comment]
I see just now that's already planned. Sorry.

**Comment by Dendraspis** [comment]
Duplicate to #1457.

> I see just now that's already planned. Sorry.

No problem.  😁
