### ISSUE TITLE
x265 GCC 9.3 vs MSVC encodings benchmarks (NOT AN ISSUE)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#146]
@Patman86 ; @stax76 
I did some tests on small source mp4 videos (FHD, all between 2-3 minutes) encoding x265 (no filtering, no audio nothing excepting decoding->encoding), and I was satisfied with the result that GCC 9.3 gives slightly better performance than MSVC (less than 2% better, but better!)
Tests made with latest x265 3.3+10 builds "M" by Patman.

**Comment by Patman86** [comment]
Thx for your feedback. I made some little code improvements for compiling and the switch to gcc 9.3.0. Now, I'm testing compiling with gcc 10.0.1 😉

**Comment by 44vince44** [comment]
Ah ! as soon as they're available, i'll test them ! Thanks Patman.

**Comment by Patman86** [comment]
x265 compiled with gcc 10.0.1 is online ;)

**Comment by 44vince44** [comment]
@Patman86 ah ! let's play ;-)

**Comment by 44vince44** [comment]
@Patman86 : impressive !!. I got an average of 8.5% better for your gcc 10.0.1 build compared to the msvc build !
I wasn't expecting such a difference!!!
