### ISSUE TITLE
view encode results without ending process...

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1461]
Hello,

i have question: is it possible to pause encoding process and view all already encoded frames and resume it if encode result looks ok?

if not possible in this version could it be implemented or its not possible?

**Comment by Dendraspis** [comment]
Nope, that's no possible, by design. We have no control over standalone applications/encoders, so there is way to realize that.

**Comment by Ding-adong** [comment]
Just make a 5 second clip using cutting features and then encode it and then see if the result looks ok.
