### ISSUE TITLE
Crop crashes with DivideByZeroException

### ISSUE THREAD

**Issue by legosoff** [staxrip/staxrip#1462]
DivideByZeroException (v2.41.7)

Попытка деления на нуль.

System.DivideByZeroException: Попытка деления на нуль.
   в System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   в System.Decimal.Divide(Decimal d1, Decimal d2)
   в StaxRip.CropForm.UpdateAll() в D:\Code\Github\staxrip\staxrip\Source\Forms\CropForm.vb:строка 486
   в StaxRip.CropForm.OnLoad(EventArgs args) в D:\Code\Github\staxrip\staxrip\Source\Forms\CropForm.vb:строка 293
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Dendraspis** [comment]
On the main window, right-click on the filter section on the left side, click on `Preview Code...` and post the code here.

**Comment by legosoff** [comment]
I can't find it, send me a screenshot.

**Comment by Dendraspis** [comment]
<img width=400 src=https://github.com/user-attachments/assets/1e22ab01-0051-4f89-9808-60091dfbaff8>

**Comment by legosoff** [comment]
1: AddAutoloadDir("C:\Encoder\StaxRip-v2.41.7-x64\Apps\FrameServer\AviSynth\plugins\")
  2: 
  3: LoadPlugin("C:\Encoder\StaxRip-v2.41.7-x64\Apps\Plugins\Dual\ffms2\ffms2.dll")
  4: tcFile = "D:\Harry.Potter.and.the.Goblet.of.Fire.2005.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_temp\Harry.Potter.and.the.Goblet.of.Fire.2005.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_timestamps.txt" # timestamps file path
  5: Exist(tcFile) ? FFVideoSource("D:\Harry.Potter.and.the.Goblet.of.Fire.2005.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT.mkv", cachefile="D:\Harry.Potter.and.the.Goblet.of.Fire.2005.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("D:\Harry.Potter.and.the.Goblet.of.Fire.2005.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT.mkv", cachefile="D:\Harry.Potter.and.the.Goblet.of.Fire.2005.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_temp\temp.ffindex")

**Comment by Dendraspis** [comment]
Okay, because there is no cropping included, I'm pretty sure you're using an old/outdated/broken template. I guess the issue is not reproducible when you start with new settings. Can you verify that?

**Comment by legosoff** [comment]
That's right, you're right. The beginning is to install everything ok and then not how many times about 3-4 times already break, delete and install everything ok again.

**Comment by Dendraspis** [comment]
So you should have used settings from `v.2.40` or even prior. That can cause such issues, sadly.
But I'm glad it works now for you.

Btw: `v2.42` is coming soon...

**Comment by legosoff** [comment]
Aah, I get it, name.strip is the setting from was v.2.40. yes exactly.  Thanks for everything. I will be waiting for v2.42.
