### ISSUE TITLE
SelectEvery sometimes doesn't work correctly 

### ISSUE THREAD

**Issue by bobdig** [staxrip/staxrip#1463]
**Describe the bug**
SelectEvery doesn't work correctly anymore since some versions. 

**Expected behavior**
Video should not have double frames if SelectEvery is set up correctly and video has doubled frames evenly

**How to reproduce the issue**

If the issue happens only under special conditions then please describe how this conditions can be reproduced:

2. Click on '...'
3. Using '...' encoder.
4. 'VapourSynth' being used.
5. Filter(s) x is being used: SelectEvery
7. If it's tied to a hardware encoder then post your hardware specs.

**Provide information**

No error message

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version 2.41.7

**Notes before posting**
- Please also try the latest release of StaxRip.
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. 
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is especially true on the VapourSynth side, which will crash if your CPU don't support it.
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet.

**Additional context**
I switched to another app called hybrid and it is working there like it used to in StaxRip

**Please be as clear and as detailed as possible**

**Comment by Dendraspis** [comment]
Sounds like an handling issue, because the filter itself works fine.

Do you have a log file for me, preferably from such an encode?

**Comment by Dendraspis** [comment]
> I only can say that it worked before and isn't anymore, for several times now.

Tested with several files and always:

<img width=800 src=https://github.com/user-attachments/assets/1a49e644-eda5-4472-b845-d1b77f029610>

**Comment by Dendraspis** [comment]
Which encoder did/do you use when the issue occurred? Do you remember?

**Comment by Dendraspis** [comment]
Okay, feel free to re-open this issue in case you have something that is reproducible...
