### ISSUE TITLE
Project templates bug with imported old settings

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1464]
![image](https://github.com/user-attachments/assets/5eb37278-5ab3-4626-b860-704bac9381df)

Just copied 2.41 ./Settings/ into 2.42.

My templates are now in recent projects:

![image](https://github.com/user-attachments/assets/54f5c30a-32e9-4436-a835-f3c3c496ec8b)

I think there is something wrong.

**Comment by Dendraspis** [comment]
I just quote myself from the release page:

![image](https://github.com/user-attachments/assets/5a083d84-358a-4691-a989-21c8da41607d)

I definitely do not support any usage of old settings, especially this time.
