### ISSUE TITLE
Crash while demuxing and avoiding ARIB subtitle

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1466]
Error Demux subtitles (v2.42.0)

ffmpeg N-116758-x64-gcc14.2.0

E:\Pro321\StaxRip-v2.42.0-x64\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i "E:\COOKIE 111\CDTV.ts" -c:s copy -vn -an "E:\COOKIE 111\CDTV_temp\ID1_[ja]."

[mpeg2video @ 00000000027ba700] Invalid frame dimensions 0x0.
    Last message repeated 3 times
[aac @ 00000000027bb300] channel element 1.14 is not allocated
[aac @ 00000000027bb300] channel element 3.13 is not allocated
[mpeg2video @ 00000000027ba700] Invalid frame dimensions 0x0.
    Last message repeated 6 times
[mpegts @ 00000000027b1080] start time for stream 3 is not set in estimate_timings_from_pts
[mpegts @ 00000000027b1080] PES packet size mismatch
[mpegts @ 00000000027b1080] Packet corrupt (stream = 1, dts = 4145159600).
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 4 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 5 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 6 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 7 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 8 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 9 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 10 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 11 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 12 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
Input #0, mpegts, from 'E:\COOKIE 111\CDTV.ts':
  Duration: 02:00:58.10, start: 38799.686222, bitrate: 14341 kb/s
  Program 1048 
  Stream #0:0[0x111]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, top first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
      Side data:
        cpb: bitrate max/min/avg: 20000000/0/0 buffer size: 9781248 vbv_delay: N/A
  Stream #0:1[0x112]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 189 kb/s
  Stream #0:2[0x114]: Subtitle: arib_caption (Profile A) ([6][0][0][0] / 0x0006)
  Stream #0:3[0x115]: Data: bin_data ([6][0][0][0] / 0x0006)
  Stream #0:4[0x840]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:5[0x850]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:6[0x857]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:7[0x858]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:8[0x859]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:9[0x85e]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:10[0x85f]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:11[0x860]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:12[0x86e]: Unknown: none ([13][0][0][0] / 0x000D)
[AVFormatContext @ 0000000002dabe40] Unable to choose an output format for 'E:\COOKIE 111\CDTV_temp\ID1_[ja].'; use a standard extension for the filename or specify the format manually.
[out#0 @ 0000000002e7eec0] Error initializing the muxer for E:\COOKIE 111\CDTV_temp\ID1_[ja].: Invalid argument
Error opening output file E:\COOKIE 111\CDTV_temp\ID1_[ja]..
Error opening output files: Invalid argument

Demux subtitles returned exit code: -22 (0xFFFFFFEA)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

StaxRip.ErrorAbortException: ffmpeg N-116758-x64-gcc14.2.0

E:\Pro321\StaxRip-v2.42.0-x64\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i "E:\COOKIE 111\CDTV.ts" -c:s copy -vn -an "E:\COOKIE 111\CDTV_temp\ID1_[ja]."

[mpeg2video @ 00000000027ba700] Invalid frame dimensions 0x0.
    Last message repeated 3 times
[aac @ 00000000027bb300] channel element 1.14 is not allocated
[aac @ 00000000027bb300] channel element 3.13 is not allocated
[mpeg2video @ 00000000027ba700] Invalid frame dimensions 0x0.
    Last message repeated 6 times
[mpegts @ 00000000027b1080] start time for stream 3 is not set in estimate_timings_from_pts
[mpegts @ 00000000027b1080] PES packet size mismatch
[mpegts @ 00000000027b1080] Packet corrupt (stream = 1, dts = 4145159600).
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 4 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 5 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 6 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 7 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 8 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 9 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 10 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 11 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 00000000027b1080] Could not find codec parameters for stream 12 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
Input #0, mpegts, from 'E:\COOKIE 111\CDTV.ts':
  Duration: 02:00:58.10, start: 38799.686222, bitrate: 14341 kb/s
  Program 1048 
  Stream #0:0[0x111]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, top first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
      Side data:
        cpb: bitrate max/min/avg: 20000000/0/0 buffer size: 9781248 vbv_delay: N/A
  Stream #0:1[0x112]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 189 kb/s
  Stream #0:2[0x114]: Subtitle: arib_caption (Profile A) ([6][0][0][0] / 0x0006)
  Stream #0:3[0x115]: Data: bin_data ([6][0][0][0] / 0x0006)
  Stream #0:4[0x840]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:5[0x850]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:6[0x857]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:7[0x858]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:8[0x859]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:9[0x85e]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:10[0x85f]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:11[0x860]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:12[0x86e]: Unknown: none ([13][0][0][0] / 0x000D)
[AVFormatContext @ 0000000002dabe40] Unable to choose an output format for 'E:\COOKIE 111\CDTV_temp\ID1_[ja].'; use a standard extension for the filename or specify the format manually.
[out#0 @ 0000000002e7eec0] Error initializing the muxer for E:\COOKIE 111\CDTV_temp\ID1_[ja].: Invalid argument
Error opening output file E:\COOKIE 111\CDTV_temp\ID1_[ja]..
Error opening output files: Invalid argument


Demux subtitles returned exit code: -22 (0xFFFFFFEA)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   в StaxRip.Proc.Start() в D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:строка 366
   в StaxRip.ffmpegDemuxer.DemuxSubtitles(List`1 subtitles, Project proj, Boolean overrideExisting) в D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:строка 428
   в StaxRip.ffmpegDemuxer.Run(Project proj) в D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:строка 301
   в StaxRip.MainForm.Demux() в D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:строка 3839
   в StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding, Int32 timeout) в D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:строка 2446

![изображение](https://github.com/user-attachments/assets/c5df9b70-0b85-4934-8113-6ff37f2656fd)

**Comment by Andrasolin** [comment]
mediaInfo

General
ID                                       : 32739 (0x7FE3)
Complete name                            : E:\COOKIE 111\CDTV.ts
Format                                   : MPEG-TS
File size                                : 12.1 GiB
Duration                                 : 2 h 0 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 14.3 Mb/s
Frame rate                               : 29.970 FPS

Video
ID                                       : 273 (0x111)
Menu ID                                  : 1048 (0x418)
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@High
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=15
Format settings, picture structure       : Frame
Codec ID                                 : 2
Duration                                 : 2 h 0 min
Bit rate mode                            : Variable
Maximum bit rate                         : 20.0 Mb/s
Width                                    : 1 440 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan order                               : Top Field First
Compression mode                         : Lossy
Time code of first frame                 : 12:26:38:10
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Open
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 274 (0x112)
Menu ID                                  : 1048 (0x418)
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Format version                           : Version 2
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 2 h 0 min
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -279 ms

Text
ID                                       : 276 (0x114)-1
Menu ID                                  : 1048 (0x418)
Format                                   : ARIB STD B24/B37
Format profile                           : HD side panel
Muxing mode                              : CCIS
Codec ID                                 : 6
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)
Language                                 : Japanese

**Comment by Andrasolin** [comment]
![004](https://github.com/user-attachments/assets/e6eda7be-deb4-489a-9ee9-3fd70b29d2db)

Made these settings - saved and closed the software.
then I launched it and input this file, read it for a long time, then the interface display disappeared as if the software had been turned off, and after 5 seconds the interface window appeared. normal, no mistakes

**Comment by Dendraspis** [comment]
Duplicate to #1447

**Comment by Dendraspis** [comment]
Do you use fresh/new settings or the ones from `v2.41.x `?

**Comment by Andrasolin** [comment]
> Do you use fresh/new settings or the ones from `v2.41.x `?

I made preliminary settings in StaxRip 2.42.0 from 0. 
I did not transfer the ready-made saves of the settings

=========================================
> And do you know how to create a sample file with `ffmpeg` out of your source file? Would be very helpful to have one.

Absolutely not, I can only “1-click”

**Comment by Andrasolin** [comment]
I'm a good merchant. that's why I know how to communicate

**Comment by Andrasolin** [comment]
torrent - https://drive.google.com/file/d/1OuFdi2_TN13WtpMNJPZCGrr2ZfGysHN5/view?usp=sharing

**Comment by Dendraspis** [comment]
Is it possible that you still use your old templates from `v2.41.x` ?

This is what happens when I open your video with a fresh new instance of StaxRip `v2.42` - absolutely no issues:
<img width=700 src=https://github.com/user-attachments/assets/5d5b0831-c5be-49d6-a0b1-fb4c2790e331>

**Comment by Andrasolin** [comment]
Weird/strange situation...all settings are 'new', without transfer. MB the reason is in the codec and in the container? (mine)Starting x264-8bit .mp4
and your x265-10bit and .mkv...

By the way: the sound track is 2 channels, but yours displays 8

**Comment by Andrasolin** [comment]
Changing the codec and container didn't help

![364995928-e6eda7be-deb4-489a-9ee9-3fd70b29d2db](https://github.com/user-attachments/assets/fd75fc1b-9ca8-4f7d-9461-497978ff5e31)
this is the only thing that helped and the sound track shows 8 but should be 2

**Comment by Dendraspis** [comment]
> Changing the codec and container didn't help

They have nothing to do with the subtitle extraction.

> this is the only thing that helped and the sound track shows 8 but should be 2

It's the file you have given me!

**Comment by Andrasolin** [comment]
I am becoming more and more convinced that the 'Input' has suffered due to compression and therefore transmits the 'info-bd' of the audio track and subtitles with an error

![Uploading 003.jpg…]()

**Comment by Dendraspis** [comment]
The archive is okay. It's more likely you having issues with old setting, templates or so.
