### ISSUE TITLE
Log file not complete in v2.42

### ISSUE THREAD

**Issue by Victory61** [staxrip/staxrip#1467]
Version 2.42 log file not complete
Good morning in encodind x265 processing, I noticed that in the new log file of version 2.42 the sections no longer appear: 
Configuration
AviSynth Script
Source Script Info
Target Script Info
Media Info Audio Source
Video Encoding
Muxing to MKV
Media Info Target File
Job Complete

Is it possible to restore them?
Thank you

**Comment by Dendraspis** [comment]
For me everything works normal along many, many test encodes.

Did you use new settings or old settings from `v2.41.x` ?

**Comment by Victory61** [comment]
I had imported the settings from 2.41.7, now I test again with new settings.

**Comment by Victory61** [comment]
I deleted the previous file “Settings.dat” I made the settings and line commands for x265 encoder again.
this are the sections I get from the log file.
1- System Environment
2- Media Info Source File
3- Auto Crop

https://justpaste.it/drfmo

**Comment by Dendraspis** [comment]
Did you start the encoder or did you just prepare the job ?!

**Comment by Victory61** [comment]
Here are 2 tests with a 10-second sample file, first with version 2.42 and then with version 2.41.7
I don't understand where I'm going wrong.
https://www.youtube.com/watch?v=7W6WEU84BRo

**Comment by Dendraspis** [comment]
Very interesting. Thanks for the video.  Bug confirmed.

**Comment by Victory61** [comment]
Thank you.
I hope it can be restored in the next version.

**Comment by Dendraspis** [comment]
Issues should be solved....

Here you can test `v2.42.1-RC1`:
https://ufile.io/njcxbirz

**Comment by Victory61** [comment]
I thank you for the release, but I can't download from the server.

**Comment by Dendraspis** [comment]
So I hope that means, that the log file is complete again with this fix.  😅 

If not, please tell me, otherwise this can be closed...

**Comment by Victory61** [comment]
I have run tests and the log file is generated perfectly as in previous versions.
It can be closed.
Thank you
