### ISSUE TITLE
Character limit produces error

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#147]
**Issue:**
Limit on file path/characters

**Example**:
(X = replaced character)
1. Open source (H:\XXXXX the XXXXXXX XXXXXX S01 1080p XXXXXX XXXXXX XX+ 5.1 x264\XXXXX the XXXXXXX XXXXXX S01E01 1080p XXXXXX XXXXXX XX+ 5.1 x264 - XXXX.mkv)
2. Generic error is displayed about x265 (even though I'm using x264) and the batch list moves onto the next job
3. A text file is opened for an error log to be written to, but is left blank

**Resolution**
In this instance, changing "H:\XXXXX the XXXXXXX XXXXXX S01 1080p XXXXXX XXXXXX XX+ 5.1 x264\" to "H:\S1\" entirely resolves the issue and the file is encoded.

**Versions Affected**
2.0.6.0 and 2.0.8.0 (and possibly previous versions)

**Screenshot**
![image](https://user-images.githubusercontent.com/10042301/77840066-e4651500-717a-11ea-91e6-0157d9316aed.png)

Regarding the screenshot:
1. I am not using x265, but x264. 
2. I am using profiles I have created - all with x264.
3. Staxrip handles the file without an issue when changing the path as explained above (replacing "XXXXX the XXXXXXX XXXXXX S01 1080p XXXXXX XXXXXX XX+ 5.1 x264" to "S1".
4. There is no issue with the audio file either (mentioned in the error screenshot).
5. The same error is shown in 2.0.8.0 and can produce a screenshot if absolutely required (it says exactly the same thing)

**Notes**
Using Avisynth (Staxrip default) and no internal or external filters (incl. resizing).

_PS: Is there any way to change the the log file limit from 50 to something else (Settings/Log Files/)? I would like to change it to 150 or even remove the limit._

**Desktop**
- Windows    : Windows 10 Pro 1909
- Language   : English (United Kingdom)
- CPU        : Intel(R) Xeon(R) CPU E3-1220 v5 @ 3.00GHz
- GPU        : Microsoft Remote Display Adapter, ASPEED Graphics Family(WDDM)
- Resolution : 3840 x 2160
- DPI        : 96
^ using rdp to encode

**Comment by stax76** [comment]
I would need a full log file.

There is a setting for the log file history.

**Comment by tnatiuk17piano** [comment]
MAX_PATH on Windows 10 is 256 characters by default, so if StaxRip tries to create the "<file>_temp" directory and place files in it that have a PATH over 256 characters, it probably errors out. You can change the default MAX_PATH in the Windows Registry

**Comment by stax76** [comment]
MAX_PATH is 260 defined at:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\minwindef.h

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

It's highly unlikely that more than 260 chars can ever be used in staxrip because it depends on too many apps written in C/C++ and they very often use MAX_PATH to define buffer sizes. Last time I tried it was mkvtoolnix that failed and Mosu did not reply when I reported it.

Windows has thousands of legacy API functions and structures that deal with paths and only the fewest will ever get fixed and .NET 4.8 will also never get fixed and staxrip will very unlikely be ported to .NET Core because it's too much work without any benefit, in fact staxrip will never run on Core because it's very unlike the form designer will ever be stable because MS had to do a major rewrite and staxrip has like 40 forms with many being complex. StaxRip uses WinForms since .NET 1.0 in 2002 and the designer was often very unstable in the past. WinForms is one of the worst products MS ever created because the designer is not High DPI agnostic.

> For developers the .NET Core Windows Forms Designer (when we will release the GA version) will look and feel the same as the .NET Framework Windows Forms Designer. But for us it is a huge technical challenge to bring the designer to .NET Core because it requires the design surface that hosts the live .NET Core form to run outside the Visual Studio process. That means we need to re-architect the way the designer surface “communicates” with Visual Studio. You can watch these communications in the Output Window, where we track each request sent when the Visual Studio components are accessing properties or executing methods on the live controls in the design surface. The engineering team is still working on this technical challenge, and we will be releasing the Preview versions on regular basis to give you the early glance at the .NET Core Designer.

**Comment by vonH** [comment]
Thank you both for your replies. @stax76  No log file is created at all (that's part of the issue reported) but now I understand the char limit is not something that can easily be fixed. Perhaps adding a function in later releases that checks the path length before trying to encode might be an idea? 

As for the 50 encode log file limit, I looked through all the options but can't seem to see it. Sorry. Am I being blind?

**Comment by vonH** [comment]
Sorry, I've now found the option for log file limits. I'll close this issue, but would appreciate consideration being given to introducing a check on character limits when creating a project (maybe a warning saying the encode may not work, or something like that?). Thank you both for your help and input.

**Comment by stax76** [comment]
I've added a verification that will block too long paths and filenames.

```
If file.Length > 150 OrElse file.FileName.Length > 75 Then
    MsgError("Source file path or filename is too long",
        "In theory Windows 10 supports long paths, there are technical reasons why this will never work in StaxRip.")

    Return True
End If
```

**Comment by vonH** [comment]
> I've added a verification that will block too long paths and filenames.
> 
> ```
> If file.Length > 150 OrElse file.FileName.Length > 75 Then
>     MsgError("Source file path or filename is too long",
>         "In theory Windows supports long paths, in reality neither Windows, the .NET Framework or the used tools have full long path support.")
> 
>     Return True
> End If
> ```

Thank you. I've seen the warning in 2.1.3.0 and increased the limit to 180. So far, I've only experienced issued with paths longer than ~200. I even tested one file that wouldn't work in 2.0.x.0 and it works in 2.1.x
