### ISSUE TITLE
Demux preferred languages but don't include them does not demux subs in 2.42.0

### ISSUE THREAD

**Issue by wrzlpete** [staxrip/staxrip#1471]
**Describe the bug**
Project Options -> Subtitles -> Demux preferred languages but don't include them
- this setting does not demux the preferred langauges (= create the subtitle files in the temp folder) anymore since 2.42.0

**Expected behavior**
Demuxing should work the same as in 2.41.x

**How to reproduce the issue**
Activate Project Options -> Subtitles -> Demux preferred languages but don't include them
Open a file that includes subtitles of the preferred languages

**Provide information**
The temp folder for the file does not include any subtitle files. First I thought this was related to some kind of bad import of settings (which I didn't actually do really), but I when I made sure and recreated all relevant settings from complete scracth with 2.42.0 the issue remained.

**Comment by Andrasolin** [comment]
try this

![003](https://github.com/user-attachments/assets/2adce90f-7f4a-452b-a0e7-eada0800b23d)

**Comment by Dendraspis** [comment]
The only problem that I can confirm is that too many subtitles are demuxed.  🥴 

<img width=600 src=https://github.com/user-attachments/assets/52350633-1437-4244-84ab-007f0c5e66b2>

<img width=600 src=https://github.com/user-attachments/assets/20883204-5bb0-4c94-a681-72d449d2694c>

**Comment by Andrasolin** [comment]
mb - is the compression to 402 mb too strong? try to share without compression, and with compression up to 999MB

![003](https://github.com/user-attachments/assets/cdaf86ce-97cd-4c70-a8cc-67e48ed93691)

**Comment by Andrasolin** [comment]
I forgot about these error messages. there are probably more errors - the compression is strong

! F:\bank\COOKIE 000\StaxRip-v2.42.0-x64.7z: Неизвестный метод в StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
! F:\bank\COOKIE 000\StaxRip-v2.42.0-x64.7z: Неизвестный метод в StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
! F:\bank\COOKIE 000\StaxRip-v2.42.0-x64.7z: Неизвестный метод в StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\setuptools\gui-arm64.exe
! F:\bank\COOKIE 000\StaxRip-v2.42.0-x64.7z: Неизвестный метод в StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\setuptools\cli-arm64.exe

**Comment by Dendraspis** [comment]
Use [7-zip](https://7-zip.org) or another almost up to date extractor to avoid issues while extracting.

**Comment by wrzlpete** [comment]
I'm not talking about the subs inside the container (menu), but the extracted subtitle files that had been inside the default temp folder before the change to 2.42.0.

The reason for this is that I use a script to hardcode the demuxed subtitle files into the video, and this does not work anymore since there are no subtitle files in the temp folder when using "Demux preferred languages but don't include them".

The files are being created when using "Demux preferred languages and include them", but I do not want to include them when hardcoding the subs into the video stream. 

I don't think the source file matters much since the options do not handle demuxing consistently, but for reference, the streams of the source file are as shown on the screenshot of a mkvmerge output.
![sample](https://github.com/user-attachments/assets/ed43c8ce-1227-4181-b1fa-d75b5c768b5d)

**Comment by Dendraspis** [comment]
Okay, got you. I will check that....

**Comment by Dendraspis** [comment]
Please try `v2.42.1-RC2` and tell me, if that fixes your issues:
https://ufile.io/njcxbirz

**Comment by wrzlpete** [comment]
Yep, everything now works as it should. Cheers! :)
