### ISSUE TITLE
CROP error

### ISSUE THREAD

**Issue by legosoff** [staxrip/staxrip#1472]
CROP

libplacebo_Tonemap: [error] Allocation of size   63M failed: VK_ERROR_OUT_OF_DEVICE_MEMORY!
[error] Memory heaps supported by device:
[error]     0: flags 0x1 size   11G
[error]     1: flags 0x0 size   15G
[error]     2: flags 0x1 size  214M
[error] Memory pool 0:
[error]     Compatible types: 0x3
[error]     Optimal flags: 0x1
[error]     Slab  0:        e x   15M:   15M used   15M res   63M alloc from heap 0, efficiency 100.00%  [../src/utils/upload.c:252]
[error]     Pool summary:   15M used   15M res   63M alloc, efficiency 100.00%, utilization 25.00%
[error] Memory pool 1:
[error]     Compatible types: 0xffffffff
[error]     Optimal flags: 0x3
[error]     Buffer flags: 0x3
[error]     Pool summary:     0 used     0 res     0 alloc, efficiency 100.00%, utilization 100.00%
[error] Memory summary:   15M used   15M res   63M alloc, efficiency 100.00%, utilization 25.00%, max page:  758M
[error]   Backtrace:
[error]     #0  0x7ffdc2796204 in pl_rect2df_rotate+0xdb64 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0x76204) (0x180076204)
[error]     #1  0x7ffdc2795189 in pl_rect2df_rotate+0xcae9 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0x75189) (0x180075189)
[error]     #2  0x7ffdc27c557b in pl_vulkan_release+0xb0b (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0xa557b) (0x1800a557b)
[error]     #3  0x7ffdc275c6ba in pl_buf_create+0x4aa (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0x3c6ba) (0x18003c6ba)
[error]     #4  0x7ffdc2799fec in pl_rect2df_rotate+0x1194c (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0x79fec) (0x180079fec)
[error]     #5  0x7ffdc275bab9 in pl_tex_upload+0x89 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0x3bab9) (0x18003bab9)
[error]     #6  0x7ffdc275f531 in pl_upload_plane+0x481 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0x3f531) (0x18003f531)
[error]     #7  0x7ffdc273db20 in avisynth_c_plugin_init+0x17360 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\AVS_LibPlacebo\avs_libplacebo.dll+0x1db20) (0x18001db20)
[error]     #8  0x7ffdbe6431dc in avs_is_rgb48+0xdb26f (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xe31dc) (0x1800e31dc)
[error]     #9  0x7ffdbe605f58 in avs_is_rgb48+0x9dfeb (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xa5f58) (0x1800a5f58)
[error]     #10 0x7ffdbe6472f4 in avs_is_rgb48+0xdf387 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xe72f4) (0x1800e72f4)
[error]     #11 0x7ffdbe647645 in avs_is_rgb48+0xdf6d8 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xe7645) (0x1800e7645)
[error]     #12 0x7ffdbe5e3974 in avs_is_rgb48+0x7ba07 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x83974) (0x180083974)
[error]     #13 0x7ffdbe6472f4 in avs_is_rgb48+0xdf387 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xe72f4) (0x1800e72f4)
[error]     #14 0x7ffdbe647645 in avs_is_rgb48+0xdf6d8 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xe7645) (0x1800e7645)
[error]     #15 0x7ffdbe5d5e8d in avs_is_rgb48+0x6df20 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x75e8d) (0x180075e8d)
[error]     #16 0x7ffdbe5f750e in avs_is_rgb48+0x8f5a1 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x9750e) (0x18009750e)
[error]     #17 0x7ffdbe62ec96 in avs_is_rgb48+0xc6d29 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xcec96) (0x1800cec96)
[error]     #18 0x7ffdbe630050 in avs_is_rgb48+0xc80e3 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xd0050) (0x1800d0050)
[error]     #19 0x7ffdbe67b859 in avs_is_rgb48+0x1138ec (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x11b859) (0x18011b859)
[error]     #20 0x7ffdbe67b0fa in avs_is_rgb48+0x11318d (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x11b0fa) (0x18011b0fa)
[error]     #21 0x7ffdbe67c413 in avs_is_rgb48+0x1144a6 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x11c413) (0x18011c413)
[error]     #22 0x7ffdbe67cf62 in avs_is_rgb48+0x114ff5 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x11cf62) (0x18011cf62)
[error]     #23 0x7ffdbe67cf62 in avs_is_rgb48+0x114ff5 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x11cf62) (0x18011cf62)
[error]     #24 0x7ffdbe67cf95 in avs_is_rgb48+0x115028 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x11cf95) (0x18011cf95)
[error]     #25 0x7ffdbe67cec5 in avs_is_rgb48+0x114f58 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x11cec5) (0x18011cec5)
[error]     #26 0x7ffdbe6839fe in avs_is_rgb48+0x11ba91 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x1239fe) (0x1801239fe)
[error]     #27 0x7ffdbe5f750e in avs_is_rgb48+0x8f5a1 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x9750e) (0x18009750e)
[error]     #28 0x7ffdbe62ebb6 in avs_is_rgb48+0xc6c49 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xcebb6) (0x1800cebb6)
[error]     #29 0x7ffdbe62d2d1 in avs_is_rgb48+0xc5364 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xcd2d1) (0x1800cd2d1)
[error]     #30 0x7ffdbe688211 in avs_is_rgb48+0x1202a4 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x128211) (0x180128211)
[error]     #31 0x7ffdbe5f750e in avs_is_rgb48+0x8f5a1 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0x9750e) (0x18009750e)
[error]     #32 0x7ffdbe62ebb6 in avs_is_rgb48+0xc6c49 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xcebb6) (0x1800cebb6)
[error]     #33 0x7ffdbe62d2d1 in avs_is_rgb48+0xc5364 (C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll+0xcd2d1) (0x1800cd2d1)
[error]     #34 0x7ffe074c1e16 (C:\Encoder\StaxRip-v2.42.0-x64\FrameServer.dll+0x1e16) (0x180001e16)
[error]     #35 0x7ffd918e7a63 (+0x57a63) (0x57a63)
[error]   for malloc: ../src/gpu/utils.c:533
[error] No slab to serve request for   15M bytes (with alignment 0xc00) in pool 1!

(C:\Users\info\Downloads\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_temp\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_new_crop.avs, line 10)

  1: AddAutoloadDir("C:\Encoder\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\plugins\")
  2: 
  3: LoadPlugin("C:\Encoder\StaxRip-v2.42.0-x64\Apps\Plugins\Dual\ffms2\ffms2.dll")
  4: tcFile = "C:\Users\info\Downloads\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_temp\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_timestamps.txt" # timestamps file path
  5: Exist(tcFile) ? FFVideoSource("C:\Users\info\Downloads\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT.mkv", cachefile="C:\Users\info\Downloads\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("C:\Users\info\Downloads\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT.mkv", cachefile="C:\Users\info\Downloads\Harry.Potter.and.the.Half-Blood.Prince.2009.2160p.UHD.BDRemux.DTSX.7.1.P8.HYBRID.DoVi-DVT_temp\temp.ffindex")
  6: loadPlugin("C:\Encoder\StaxRip-v2.41.7-x64\Apps\DGHDRtoSDR_1.15\DGHDRtoSDR.dll")

**Comment by Dendraspis** [comment]
Seems your GPU is incompatible or has not enough memory to offer. You can turn Tonemapping for cropping off here:

<img width=600 src=https://github.com/user-attachments/assets/135db32b-4ee3-48c2-8e8e-563c7b8338bb>

**Comment by legosoff** [comment]
Thanks, everything is OK. I want to make a donation to you, where is the transfer?

**Comment by Dendraspis** [comment]
Glad to read that it works now for you.

For support you can find all information here:
https://github.com/staxrip/staxrip?tab=readme-ov-file#contribution--support
...or at the bottom of the last release (Tip-section):
https://github.com/staxrip/staxrip/releases/tag/v2.42.0
