### ISSUE TITLE
v2.42 - logs are broken

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1473]
Major bug with this new version v2.42

log files are no longer written for the encode.
They stop after
---------------------- Indexing using ffmsindex ----------------------

------------------------------ Auto Crop ------------------------------

after Auto Crop, log file ends.

**Comment by Zodler** [comment]
Update:
I have another new encode where the log file is complete. I don't know where is the problem.

**Comment by Zodler** [comment]
Ok I know more. It's not good. The encode I said it had the complete log has no longer the complete log!

As soon as staxrip finished its jobs, it went and over-wrote that good log file with a broken one!

It seems at the end of the jobs, it goes and overwrites the logs with an earlier version.

**Comment by Dendraspis** [comment]
Duplicate to #1467
