### ISSUE TITLE
v2.42.0 on Win 10 File Drop-downs messed up.

### ISSUE THREAD

**Issue by Theli93** [staxrip/staxrip#1474]
Interface seems to have messed up "Project Templates" & "Recent Projects" in the "File" drop-down.

File-->Project Templates: provides a list of apha categorized filters instead of Projects.
File-->Recent Projects provides my actual list of Project Templates

Actual "Recent Projects" seems to be lost altogether.

I reverted to v2.41.7 after the disovery so I don't know what else may be off. 
 
[Screenshots attached]

![v2_42_0_Project_Templates](https://github.com/user-attachments/assets/dba1d56a-8d13-4956-b6a8-ddec68551fb3)
![v2_42_0_Recent_Projects](https://github.com/user-attachments/assets/3111c864-c6a0-4d1b-87d5-0e530b0d3a53)

**Comment by Dendraspis** [comment]
Duplicate to #1464 

![image](https://github.com/user-attachments/assets/498e240f-7c08-4bd9-8643-fef5ea3fd13f)

**Comment by Theli93** [comment]
Sorry, but thanks!
