### ISSUE TITLE
Handling of broken source files leads to wrong audio track information

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1476]
incorrectly analyzes and displays the audio track

and when
you change the name of the audio track, then automatically resets the name immediately returns the original name

![002](https://github.com/user-attachments/assets/e37e3c42-8897-41ff-8026-25be7faa4013)

[CDTV_staxrip.log](https://github.com/user-attachments/files/16926119/CDTV_staxrip.log)

----------------------------- Demux Audio -----------------------------

ffmpeg N-116758-x64-gcc14.2.0

E:\Pro321\StaxRip-v2.42.0-x64\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -y -hide_banner -probesize 10M -i "E:\COOKIE 111\CDTV.ts" -vn -sn -c:a copy "E:\COOKIE 111\CDTV_temp\ID1 -279ms.m4a"

[mpeg2video @ 000000000348a700] Invalid frame dimensions 0x0.
    Last message repeated 3 times
[aac @ 000000000348b300] channel element 1.14 is not allocated
[aac @ 000000000348b300] channel element 3.13 is not allocated
[mpeg2video @ 000000000348a700] Invalid frame dimensions 0x0.
    Last message repeated 6 times
[mpegts @ 0000000003481080] start time for stream 3 is not set in estimate_timings_from_pts
[mpegts @ 0000000003481080] PES packet size mismatch
[mpegts @ 0000000003481080] Packet corrupt (stream = 1, dts = 4145159600).
[mpegts @ 0000000003481080] Could not find codec parameters for stream 4 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 5 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 6 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 7 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 8 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 9 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 10 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 11 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
[mpegts @ 0000000003481080] Could not find codec parameters for stream 12 (Unknown: none ([13][0][0][0] / 0x000D)): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (10000000) options
Input #0, mpegts, from 'E:\COOKIE 111\CDTV.ts':
  Duration: 02:00:58.10, start: 38799.686222, bitrate: 14341 kb/s
  Program 1048 
  Stream #0:0[0x111]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, bt709, top first), 1440x1080 [SAR 4:3 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
      Side data:
        cpb: bitrate max/min/avg: 20000000/0/0 buffer size: 9781248 vbv_delay: N/A
  Stream #0:1[0x112]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 189 kb/s
  Stream #0:2[0x114]: Subtitle: arib_caption (Profile A) ([6][0][0][0] / 0x0006)
  Stream #0:3[0x115]: Data: bin_data ([6][0][0][0] / 0x0006)
  Stream #0:4[0x840]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:5[0x850]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:6[0x857]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:7[0x858]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:8[0x859]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:9[0x85e]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:10[0x85f]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:11[0x860]: Unknown: none ([13][0][0][0] / 0x000D)
  Stream #0:12[0x86e]: Unknown: none ([13][0][0][0] / 0x000D)
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Output #0, ipod, to 'E:\COOKIE 111\CDTV_temp\ID1 -279ms.m4a':
  Metadata:
    encoder         : Lavf61.5.101
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
Press [q] to stop, [?] for help
[ipod @ 0000000003a7be40] aac bitstream error
    Last message repeated 17185 times
[ipod @ 0000000003a7be40] aac bitstream error
    Last message repeated 23130 times
[ipod @ 0000000003a7be40] aac bitstream error
    Last message repeated 22637 times
[ipod @ 0000000003a7be40] aac bitstream error
    Last message repeated 13365 times
[ipod @ 0000000003a7be40] aac bitstream error
    Last message repeated 13434 times
[ipod @ 0000000003a7be40] aac bitstream error
    Last message repeated 13425 times
[ipod @ 0000000003a7be40] aac bitstream error

**Comment by Dendraspis** [comment]
Notice how many times these messages are repeated over and over again:
```
[ipod @ 0000000003a7be40] aac bitstream error
Last message repeated 17185 times
[ipod @ 0000000003a7be40] aac bitstream error
Last message repeated 23130 times
[ipod @ 0000000003a7be40] aac bitstream error
Last message repeated 22637 times
[ipod @ 0000000003a7be40] aac bitstream error
Last message repeated 13365 times
[ipod @ 0000000003a7be40] aac bitstream error
Last message repeated 13434 times
```

Obviously your source file is broken or at least incorrectly coded, so when you extract the audio file it cannot be identified properly anymore. Instead of demuxing the audio track, you can try to use the audio stream from the source file instead - maybe that can help.
