### ISSUE TITLE
SvtAv1EncApp Dolby Vision Profile

### ISSUE THREAD

**Issue by legosoff** [staxrip/staxrip#1479]
SvtAv1EncApp Dolby Vision RPU Profile 8 and 5 she's not there.

**Comment by Dendraspis** [comment]
Do you provide more information or do you expect me to guess what you mean?

**Comment by legosoff** [comment]
I was wrong about Profile 8 and 5, it has A V1 Profile 10.1, dav1.10.06 everything is correct. Unfortunately, Bento 4 HLS generation does not support Dolby Vision Profile 10. The topic is closed.

**Comment by legosoff** [comment]
I want can you create your own generation of HLS Staxrip?

**Comment by legosoff** [comment]
#EXTM3U
#GENERATOR CINEMAHD VERSION=0.0.8-HLSF+
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-SESSION-DATA

#--Audio--
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a.40.2",LANGUAGE="ru",NAME="Русский | AAC | 2.0 | Superbit",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="audio/ru/mp4a.40.2/1/media.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a.40.2",LANGUAGE="en",NAME="English | AAC | 2.0 | Blu-ray",AUTOSELECT=YES,DEFAULT=NO,CHANNELS="2",URI="audio/en/mp4a.40.2/1/media.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a.40.2",LANGUAGE="ru",NAME="Русский | AAC-HD | 7.1 | Superbit",AUTOSELECT=YES,DEFAULT=NO,CHANNELS="8",URI="audio/ru/mp4a.40.2/2/media.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio/mp4a.40.2",LANGUAGE="en",NAME="English | AAC-HD | 7.1 | Blu-ray",AUTOSELECT=YES,DEFAULT=NO,CHANNELS="8",URI="audio/en/mp4a.40.2/2/media.m3u8"

#--Video--
#EXT-X-STREAM-INF:SUBTITLES="subtitles",AUDIO="audio/mp4a.40.2",AVERAGE-BANDWIDTH=4058847,BANDWIDTH=15572062,VIDEO-RANGE=SDR,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1152x488,FRAME-RATE=23.976
video/avc1/media.m3u8
#EXT-X-STREAM-INF:SUBTITLES="subtitles",AUDIO="audio/mp4a.40.2",AVERAGE-BANDWIDTH=35279151,BANDWIDTH=43931658,VIDEO-RANGE=PQ,CODECS="hvc1.2.4.H150.90,mp4a.40.2",RESOLUTION=3840x1632,FRAME-RATE=23.976
video/hvc1/media-hdr.m3u8
#EXT-X-STREAM-INF:SUBTITLES="subtitles",AUDIO="audio/mp4a.40.2",AVERAGE-BANDWIDTH=35279151,BANDWIDTH=43931658,VIDEO-RANGE=PQ,CODECS="hvc1.2.4.H150.90,mp4a.40.2",RESOLUTION=3840x1632,FRAME-RATE=23.976,SUPPLEMENTAL-CODECS="dvh1.08.06/db1p"
video/hvc1/media.m3u8
#EXT-X-STREAM-INF:SUBTITLES="subtitles",AUDIO="audio/mp4a.40.2",AVERAGE-BANDWIDTH=35279151,BANDWIDTH=43931658,VIDEO-RANGE=PQ,CODECS="dvh1.08.06,mp4a.40.2",RESOLUTION=3840x1632,FRAME-RATE=23.976
video/hvc1/media.m3u8
#EXT-X-STREAM-INF:SUBTITLES="subtitles",AUDIO="audio/mp4a.40.2",AVERAGE-BANDWIDTH=35279151,BANDWIDTH=43931658,VIDEO-RANGE=PQ,CODECS="dvh1.05.06,mp4a.40.2",RESOLUTION=3840x1632,FRAME-RATE=23.976
video/hvc1/media-dv.m3u8

#--I-Frame--
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=275981,BANDWIDTH=937546,VIDEO-RANGE=SDR,CODECS="avc1.640028",RESOLUTION=1152x488,URI="video/avc1/fragment.m3u8"
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=1145052,BANDWIDTH=3268892,VIDEO-RANGE=PQ,CODECS="hvc1.2.4.H150.90",RESOLUTION=3840x1632,URI="video/hvc1/fragment-hdr.m3u8"
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=1145052,BANDWIDTH=3268892,VIDEO-RANGE=PQ,CODECS="hvc1.2.4.H150.90",RESOLUTION=3840x1632,URI="video/hvc1/fragment.m3u8",SUPPLEMENTAL-CODECS="dvh1.08.06/db1p"
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=1145052,BANDWIDTH=3268892,VIDEO-RANGE=PQ,CODECS="dvh1.08.06",RESOLUTION=3840x1632,URI="video/hvc1/fragment.m3u8"
#EXT-X-I-FRAME-STREAM-INF:AVERAGE-BANDWIDTH=1145052,BANDWIDTH=3268892,VIDEO-RANGE=PQ,CODECS="dvh1.05.06",RESOLUTION=3840x1632,URI="video/hvc1/fragment-dv.m3u8"

#--Subtitles--
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles",NAME="Русский | Полный | Blu-ray CEE",AUTOSELECT=YES,DEFAULT=NO,LANGUAGE="ru",URI="subtitles/ru/media.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles",NAME="Український | Повен | Blu-ray CEE",AUTOSELECT=YES,DEFAULT=NO,LANGUAGE="uk",URI="subtitles/uk/media.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles",NAME="English | Full | Blu-ray",AUTOSELECT=YES,DEFAULT=NO,LANGUAGE="en",URI="subtitles/en/media.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitles",NAME="English | SDH | Blu-ray",AUTOSELECT=YES,DEFAULT=NO,LANGUAGE="en2",URI="subtitles/en2/media.m3u8"

**Comment by legosoff** [comment]
https://radikal.host/i/gNjYCE
