### ISSUE TITLE
2.1.0.2 beta fails to import Vapoursynth module

### ISSUE THREAD

**Issue by tnatiuk17piano** [staxrip/staxrip#148]
StaxRip Version: 2.1.0.2 beta
Python Version: 3.8.2 (3.7.7 used to test)
Windows 10 Home
Vapoursynth R49

When I run a job in StaxRip, the source script fails to load due to an inability to load Vapoursynth as a module. This is most likely due to line 2, "import vapoursynth as vs".

Running these commands in Python 3.7.7 produces this error; however, running the same commands in Python 3.8.2 does not produce the error. I deduce this is because StaxRip is not using python38 to execute the commands.

**Comment by stax76** [comment]
StaxRip isn't using Python directly, it only verifies that it is installed, what staxrip does is using the vapoursynth API.

You can try if mpc-be and VirtualDub2 can open vapoursynth scripts, if not then your setup don't work.

Here all apps work with python 3.8.2 and vapoursynth r49, I always install things only for one user and don't install multiple python version side by side if that is possible.

**Comment by tnatiuk17piano** [comment]
I got it to work by uninstalling and reinstalling both. Thanks!

**Comment by stax76** [comment]
No  Problem.
