### ISSUE TITLE
YUV420 height must be multiple of 4

### ISSUE THREAD

**Issue by craposoup** [staxrip/staxrip#1480]
After applying the v2.42.1 update, app launches however after loading a .vob file it throws the below errors:

SeparateFields: YUV420 height must be multiple of 4
(C:\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 1607)
(C:\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 517)
(C:\VOB\VTS_01_1_temp\VTS_01_1.avs, line 25)

**Comment by Dendraspis** [comment]
So just do what `SeparateFields` tells you:
The height of the frame, that you pass to `SeparateFields`, *must be multiple of 4*.
