### ISSUE TITLE
Audio is not demuxed and/or inserted

### ISSUE THREAD

**Issue by Andrasolin** [staxrip/staxrip#1482]
What happens to the audio track display? When re-encoding, it doesn't show audio, why?

![изображение](https://github.com/user-attachments/assets/5fbc5c5a-bb3d-4e62-887c-58ef52090c30)

**Comment by Dendraspis** [comment]
Go to `Project » Options » Audio` and have look at your settings.

In case you cannot find the problem, send me a screenshot of the window.

**Comment by Andrasolin** [comment]
selected, saved, relaunched. Everything's good

![001](https://github.com/user-attachments/assets/9afb2026-c2a0-4831-8788-959a32cb344a)
