### ISSUE TITLE
VCEEnc configuration bug and questions (or wishes) about interaction with options. 

### ISSUE THREAD

**Issue by DimkaTsv** [staxrip/staxrip#1486]
Sorry for bothering, i returned with new pack of tinkering. 

1. **[bug]** When you select Preanalysis -> Perceptual AQ mode = CAQ, StaxRip will submit `paq=1` ... Should be `paq=caq` (or paq=none when disabled). And selector shows correct values, only passed option is wrong. 

------------

2. **[feature request?]** `--avsw` and `--avi` flags for VCEEnc decoder? Currently there are only options of `--y4m`, `--avhw` and `--avsdll` utilisation. ~~Same command line arguments that VCEEnc can use, also are applicable for NVEnc and QSVEnc from rigaya.~~ Checked... You already have `--avsw` for NVEnc and QSVEnc (no `--avi`, but it's use case way narrower compared to `--avsw`, so understandable. It was more like fallback option.)
3. **[feature request?]** AV1 codec level selector for VCEEnc... Currently RX 7000 can support up to AV1 6.0, but there are more options (up to 7.3, i believe). There is no selector for this in VCEEnc AV1 encoder options right now.

------------

4. **[UI ineraction (optional)]** b-frames (and b-pyramid option) do not exist for anything besides H.264 on AMF (at least for now). As well as Non-ref Bframe and Ref Bframe QP offsets. Maybe making them hidden when HEVC or AV1 is selected would be nice? Or mark that it is only AVC specific option?
5. **[UI ineraction (optional)]** Slices do not exist for AV1. Those are only valid for AVC and HEVC. So, maybe making it only visible for when AV1 is selected? Setting `--slices X` doesn't break anything with AV1 (it is ignored), so it's just to avoid confusion. Or mark that it is AV1 specific option?

6. **[UI interaction (optional)]** defaults of max-bitrate and VBV Bufsize being "set" to 20000 kbps are confusing and not representative of truth, as these numbers adjust dynamically based on target bitrate. Maybe make them be default at 0? This will represent tool behaviour properly. [if you set argument to 0 (aka `--max-bitrate 0`, for example), it will actually use default value based on target bitrate]
7. **[UI ineraction (optional)]** --tiles 1 is default, not necessary to show it in command line. Default value in UI can also be a 0. (if you use --tiles 0, it will default to 1 on AV1 encode) 

8. **[UI ineraction (optional)]** You cannot use preencode and preanalysis simultaneously. Not critical, if --pa flag is enabled, --pe will just be ignored with notification. Is it possible to lock preanalysis to "disabled" state when you enable preencode? Or vice verse (probably locking preencode would be simpler)
9. **[UI ineraction (optional)]** Preanalysis is currently limited to 8-bit encode without any timeline for 10-bit functionality (preencode does not have such limitation). Trying to encode with 10 bit and --pa flag enabled will cause VCEEnc to stop and throw an error. Can there be a way to warn anyone that tries to set 10 bit encode with preanalysis? 

------------

10. **[questionable UI moment]** QP min/max for VCEEnc AVC/HEVC are 51 (default), and for AV1 it should be up to 255 (default). Currently StaxRip shows 100 as default value for QP Max, which does not align to any encoder.

**Comment by Dendraspis** [comment]
No problem, I'm happy about your report, so I can fix some issues.

1. ✅ 
2. According to the docs these options are valid/available:  https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--avsw-string
3. ✅ 
4. According to the docs and code `--bframes` is also used for at least AV1
5. ✅ 
6. ✅  with a default value of `0`
7. ✅ 
8. ❌  I keep it the way it is ... too time consuming
9. ✅ / ❌   To keep the code readable I decided to use the same logic like for `NVEncC`, so for `AV1` the limit is `255` and for the other codecs it's `63` as this is the max value when using 10-bit output. No clue what happens for 8-bit when using a value above `51`.
10. 〰️ As these parameters should be rarely used, I use the same logic as for `NVEncC`: Default is `0` and there is sort of no upper limit, means you have to take care of the right values.

**Comment by DimkaTsv** [comment]
2 - They are, but you still cannot currenrly access --avsw flag for VCEEnc, while you can for NVEnc and QSVEnc, so i wrote is as feature request

4 - According to the docs and code --bframes is also used for at least AV1... 
Oh, hmm, i hadn't actually checked rigaya code before (and you may be right), so you may be technically correct, as it parses b-frames with AV1 and even warns if you set --bframes>3. He also did respond to similar issue for NVEnc by mentioning mini-GOP's. 

But there are no options for b-frames for AV1 in AMF documentation. Not that there can probably be, as AV1 does not support conventional b-frames by spec, afaik. Maybe difference is that AV1 produces own b-frame analog by default? But it will never be reported as b-frame as they technically are not ones  (AV1 encodes as Intra/Inter frames instead of I/P/B).  

Right now setting --bframes 3 --b-pyramid produces result that has frame by frame 0 differences (up to checksum of output) from one that is skipping these parameters. So i kinda assume that they these options don't do anything when used on AV1. But, on other hand, they also don't break anything, so leaving them be won't affect anything. 

I probably need to ask rigaya directly about this one (i have few more questions pending, and wrote few of those yesterday, so it's probably a good time). 

>10. 〰️ As these parameters should be rarely used, I use the same logic as for NVEncC: Default is 0 and there is sort of no upper limit, means you have to take care of the right values.

Really? NVEnc does not have upper limit for QP level? That's something new. QP level range is enforced by encoder afaik. (not to say that default 0 should only be a default for minQP... Otherwise nothing will be compressed).
But ok, i can see your position. These are really ones that only touched if user MUST do something manually. 

---------
1. ❌ Welp, for some reason --pa (preanalysis) now is completely gone from options. Only --pe is left Oops.
![image](https://github.com/user-attachments/assets/818410fb-560b-4929-8a54-7bd01a1d642e)

2. ❌ `--avsw` is still unaccessible. VCEEnc option in list forces HW variant (aka `--avhw`). If issue is in this <string> parameter, you may ignore it. Just passing --avsw is enough to make it work as he provides. If anything NVEnc option.md list also mentions --avsw <string> as argument. 
![image](https://github.com/user-attachments/assets/af0ecb46-144a-4c2c-8ba2-e96d52e4ceee)

3. ✅ Confirmed change. AV1 encoder level selector is now available.
4. 〰️ Currently suspended, until more data.
5. ✅ Confirmed change. Option for slices is now hidden when AV1 encoder is selected.
6. ✅ Confirmed change. Max bitrate and VBV buffer size now show value 0 in GUI by default.
7. ✅/〰️ Confirmed change. GUI now shows Tiles = 1,  but it now counts as default and isn't written in command line, unless changed. Based on AMF docs tile size is limited to 4096 width and 4096*2304 area, so if you do 8k encode, it will default to 4 tile encode instead of 1 (tbh, if you manually set --tiles 1 in mentioned case,  it will still force 4 tiles, though). Idk if setting default number of tiles in UI to 0 for better representation is a good choise though, but --tiles 0 definitely does not break "auto" behaviour based on quick testing i had with different resolutions. 
8. ❌ Look at 1. Now broken, as preanalysis hidden for some reason without clear way how to make it appear.
9. 〰️ Reasonable. Revoked. 
10. ✅/〰️ Confirmed change. Now max QP value in UI is set to 0 by default (without command line impact). Understandable. Personal opinion is that, maybe, 255 is better middle ground for Max QP default value in UI to be more reflective of it's meaning? In this case it will be aligned to AV1 encoder range, which is largest for now (1-255). But i guess 0 is also fine for defaults, as smallest possible QP in reality is 1. (At least on VCE? Because from what i see NVEnc reports that QP 0 is possible for AV1 [their range is 0-255], so i assume that it is same for NVEnc AVC/HEVC?)

**Comment by Dendraspis** [comment]
1. I'm on the road, but I'm sure it's correct now as `--pa` is not available for 8-bit - I have checked the code for all params.
2. Hmm, so you are sure both of them can be removed?
3. -
4. `--bframes` is not used directtly, but used to set other values by comparison.

....

**Comment by DimkaTsv** [comment]
>1. I'm on the road, but I'm sure it's correct now as --pa is not available for 8-bit - I have checked the code for all params.

Not quite. PA is not available for 10 bits, not for 8 bits. Currently AMF devs hadn't release 10 bit version of preanalysis (and there are people that wait for this day).
It was designed for 8 bits, and, for example, is forcefully enabled if you use QVBR/HQVBR/HQCBR encodes. [That is also reason why these rate control methods won't actually work if you do 10 bit encode]

>2. Hmm, so you are sure both of them can be removed?

Better say that both of them (`--avhw` and `--avsw`) can just be used without additional hoops. Maybe because AMF uses ffmpeg libraries in sources, or he just bundles them anyway? For example VCEEnc uses `--avsw` fallback as default when source is encoded in AV1, unless `--avhw` is specified. (in this case it throws error and closes. Rigaya had some issues with HW AV1 decode, so he decided do it by locking it from `--avhw` opton)

Tbh, i don't quite know what behaviour is for --avsw in NVEnc and QSVEnc. But for VCEEnc it is like second "native" mode. Just with SW instead of HW. More reliable, though.

`C:\Users\-----\Videos\test sample>C:\Users\-----\Desktop\Utilites\VCE_Encoder\VCEEncC_x64\\VCEEncC64.exe -i "C:\Users\-----\Videos\test sample\[4k]fast_sample.mkv" -o "[4k]fast_sample_processed.mkv" --avsw --codec av1 --preset slower --vbr 20000 --tiles 0 --audio-copy`

```
Input Info:    avsw: hevc(yv12)->nv12 [AVX2], 3840x2160, 60/1 fps
Output:        AV1  main @ Level 5.2
               3840x2160p 0:0 60.000fps (60/1fps)
               avwriter: av1, aac => matroska
```

>--bframes is not used directtly, but used to set other values by comparison.

Oh, i see. I will still ask him just in case. Because AMF always had very limited support of b-frames.  If anything they only returned them back to AVC, like, 2 years ago.

**Comment by Dendraspis** [comment]
1. Indeed, I recalled it wrong: 8-bit is supported, 10-bit not, so `--pa` is limited to "8-bit" and "not --cqp" and this is currently being depicted by StaxRip. At the bottom are the related `VCEEncC` code snippet:
2. So I thing it cannot be wrong to leave it as it is. As long as it does not lead to a crash, it seems to be good for me.
3. -
4. 👍 
5. 👍 
6. 👍 
7. Okay, that wan't mentioned before. So I set the default to `0` which does not show up in the parameter list, so it works like an *automatic/default*  value.
8. See (1). I guess you where in *CQP* mode when you tested it.
9. 👍 
10. I leave it at `0` as this is a so-called standard value for *Automatic* - see (7). I know, that it is not great, but I would blow up the code and make it more complicate for 2 parameters, that are extremely rarely used. And yes, technically speaking it is currently not possible to set `--qp-max 0` via that control as it will fall back to the default value of `51`/`63`/`255` - you have to use the Custom box.



----------

https://github.com/rigaya/VCEEnc/blob/8be39483b2cffad392ff9c50d83a636b2584a49a/VCECore/vce_core.cpp#L2051-L2060
```cpp
if (prm->pa.enable) {
    if (GetEncoderBitdepth(prm) > 8) {
        PrintMes(RGY_LOG_ERROR, _T("Pre analysis is limited to 8bit encoding, disabled.\n"));
        return RGY_ERR_UNSUPPORTED;
    }
}
```

https://github.com/rigaya/VCEEnc/blob/8be39483b2cffad392ff9c50d83a636b2584a49a/VCECore/vce_core.cpp#L2268-L2279
```cpp
    if (prm->pa.enable) {
        if (   prm->rateControl != get_codec_vbr(prm->codec)
            && prm->rateControl != get_codec_hqvbr(prm->codec)
            && prm->rateControl != get_codec_vbr_lat(prm->codec)
            && prm->rateControl != get_codec_cbr(prm->codec)
            && prm->rateControl != get_codec_hqcbr(prm->codec)
            && prm->rateControl != get_codec_qvbr(prm->codec)) {
                PrintMes(RGY_LOG_WARN, _T("Pre analysis is currently supported only with CBR/VBR/QVBR mode.\n"));
                PrintMes(RGY_LOG_WARN, _T("Currenlty %s mode is selected, so pre analysis will be disabled.\n"), get_cx_desc(get_rc_method(prm->codec), prm->rateControl));
                prm->pa.enable = false;
        }
    }
```

**Comment by Dendraspis** [comment]
Here is another RC for you:
https://ufile.io/ovtial5h

**Comment by DimkaTsv** [comment]
1. ✅
2. ❌
3. ✅
4. 〰️(Suspended)
5. ✅
6. ✅
7. ✅
8. ✅
9. 〰️(Retracted)
10. ✅✅

>https://github.com/rigaya/VCEEnc/blob/8be39483b2cffad392ff9c50d83a636b2584a49a/VCECore/vce_core.cpp#L2268-L2279
 PrintMes(RGY_LOG_WARN, _T("Pre analysis is currently supported only with CBR/VBR/QVBR mode.\n"));

1. Well, technically by AMF spec it is forcefullt enabled for QVBR, HQCBR and HQVBR modes, so he probably didn't update this particular line. But yes, you are right, it doesn't work with CQP and it was reason why i missed point 8. Retracted statement. 

2. Well i wanted option to simply enable  `--avsw`. Not to disable `--avhw`. Sorry for bothering too much. 
Like what you have for NVEnc and QSVEnc already:
![image](https://github.com/user-attachments/assets/73cfeba2-cb30-4d66-be1b-71b6a8d1f4ee)
![image](https://github.com/user-attachments/assets/fbd6fa59-6352-4a9b-9d87-3ee5a4e8eb35)
![image](https://github.com/user-attachments/assets/b1299d62-d20b-4f75-a897-f7ed3f8242c0)

Where NVEnc Hardware = `--avhw` and NVEnc Software = `--avsw`. 
And QSVEnc Hardware = `--avhw` and QSVEnc Software = `--avsw`
But for VCEEnc only VCEEnc = `--avhw` is available. 
Even though it supports exact same `--avsw` flag as other two.

>7. Okay, that wan't mentioned before. So I set the default to 0 which does not show up in the parameter list, so it works like an automatic/default value.  
7. Confirmed change. To be fair, i only took a deeper dive at that afterwards myself (after reading AMF docs bit more closely).  

10. Confirmed change. Great. Now it is even dynamic based on selected encoder!

**Comment by Dendraspis** [comment]
😂   Oh boy .... sorry, my bad, I really thought `VCEEncC` would already behave like the others without double-checking it.  🤦‍♂️ 
The screenshots would have been enough, but thanks for also explaining it.

> To be fair, i only took a deeper dive at that afterwards myself (after reading AMF docs bit more closely).

No problem.  😄 

So hopefully the last RC for this issue .... RC4:
https://ufile.io/xfcy355c

**Comment by DimkaTsv** [comment]
>So hopefully the last RC for this issue .... RC4:

Can confirm all fixes, so it seems it indeed will be last for this issue):
1. ✅
2. ✅
3. ✅
4. 〰️(Suspended)
5. ✅
6. ✅
7. ✅
8. ✅
9. 〰️(Retracted)
10. ✅✅

But besides that:
There is also `--interlace auto` option (besides tff/bff), for all 3 of rigaya tools (aka NVEnc/QSVEnc/VCEEnc), but that can be on hold... It is just for information.

**Comment by Dendraspis** [comment]
I have changes some minor things, so in case you wanna try out - let's say it had something to do with interlacing:  🤭 
RC5:
https://ufile.io/7869cx12


So I'm closing this issue now. Thanks for your reports.
