### ISSUE TITLE
I'm stuck with Batch encode function

### ISSUE THREAD

**Issue by art2work4** [staxrip/staxrip#1488]
So I have a folder with files that I want to batch encode. But each time I get the following error:

```
IOException (v2.42.1)

The filename, directory name, or volume label syntax is incorrect.

System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at StaxRip.SafeSerialization.Serialize(Object o, String path) in D:\Code\Github\staxrip\staxrip\Source\General\General.vb:line 297
```

Now I understand that there's something not right in the path/folder/file names, but I have no clue what is really wrong.

Here's an example of a path:
`E:\DaVinci Resolve  CAPTURE\ADCV captures\Hi8 tapes\Macedonie 1997 Illendenski Denovi\Macedonie 1997 29_30-07 001\ohrid 1997 29_30-07 0001.avi`

All the other avi files have the same naming convention, so ending with 0002.avi, 0003.avi etc.

I hope someone can guide me on how to use the Batch encode option in StaxRip

**Comment by Dendraspis** [comment]
I guess you can open each file separately without any issues?

**Comment by art2work4** [comment]
yes, individually they all open fine and Staxrip also converts them according to my settings

**Comment by Dendraspis** [comment]
Then it looks like you don't have (enough) writing permissions in your chosen `Settings` folder. Try starting StaxRip `As Administrator` to see if that solves your issue.

**Comment by art2work4** [comment]
Hi Dendraspis, you were right. At first the program folder with Staxrip was on my Synology NAS. This NAS OS is Linux based and I've noticed on other occasions that the rights management is complex. So I copied the Staxrip folder to a local NVME drive, changed the project to be a local files on the NVME as well and started Staxrip as Admin. Now that error message is gone.

However I do get another error message:
AviSynth Script Error (v2.42.1)

SeparateFields: YUV420 height must be multiple of 4
(E:\DaVinci Resolve  CAPTURE\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 1607)
(E:\DaVinci Resolve  CAPTURE\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 517)
(E:\DaVinci Resolve  CAPTURE\ADCV captures\Hi8 tapes\Macedonie 1997 Illendenski Denovi etc met Caroline\Macedonie 1997 29_30-07 001\ohrid 1997 29_30-07 0002_temp\ohrid 1997 29_30-07 0002.avs, line 30)

StaxRip.ErrorAbortException: SeparateFields: YUV420 height must be multiple of 4
(E:\DaVinci Resolve  CAPTURE\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 1607)
(E:\DaVinci Resolve  CAPTURE\StaxRip-v2.42.0-x64\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 517)
(E:\DaVinci Resolve  CAPTURE\ADCV captures\Hi8 tapes\Macedonie 1997 Illendenski Denovi etc met Caroline\Macedonie 1997 29_30-07 001\ohrid 1997 29_30-07 0002_temp\ohrid 1997 29_30-07 0002.avs, line 30)
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 315
[ohrid 1997 29_30-07 0002_staxrip.log](https://github.com/user-attachments/files/17006400/ohrid.1997.29_30-07.0002_staxrip.log)


(attached the log file)

I am quite a novice in this stuff, so I have no idea why this error pops up and neither do I know how to fix it.
But the weird thing is that Staxrip is encoding the files just fine. I can play the resulting *.mov files without any (to my eyes at least) visible issues.

Should I be concerned about this error and is there a way to fix this?

**Comment by art2work4** [comment]
another thing I notices is that the first AVI renders as fast as when I render is separately (render speed +/- 4x). However the subsequent files in the Batch are rendering really slow (speed 0,584) and only one core is slightly used.
I guess this is not how it's supposed to be?

**Comment by Dendraspis** [comment]
At first:  One ticket per issue.

> Now that error message is gone.

Very good!

> However I do get another error message
> [..] so I have no idea why this error pops up [..]
> Should I be concerned about this error and is there a way to fix this?

This was already answered a few days ago:  #1480
You just have to do what the script tells you:  `YUV420 height must be multiple of 4`
The Mod values can be seen/checked/set on the Crop window:
<img width=500 src=https://github.com/user-attachments/assets/40865399-3785-48c7-9910-cdd5b84db315>

> But the weird thing is that Staxrip is encoding the files just fine.

I somehow doubt that. Normally the error message will block the encode and your log file also does not show any encoding.

> another thing I notices is that the first AVI renders as fast as when I render is separately (render speed +/- 4x). 

Again:  One ticket per issue, whereas this is a handling/using question which is better asked on a forum or our Discord server.
Nevertheless it's more likely that the error at `SeparateFields` which is called by `QTGMC` leads to a deactivation of `QTGMC` and maybe all following filters, which then could speed up the entire encode. But like I said: You log file does not show any encoding.

**Comment by art2work4** [comment]
sorry for the late response. I changed the size to match Mod 4. I do however notice issue with batch encoding, but as you rightfully pointed out, I will raise this as a separate question.
