### ISSUE TITLE
demux chapters

### ISSUE THREAD

**Issue by fransalas71** [staxrip/staxrip#1489]
I am ripping my fulls and when I do them the chapters do not appear automatically. I always have to put them in manually. Is there a way to put them in automatically? That is to say, I have the demultiplexing chapters option checked.

**Comment by Dendraspis** [comment]
You could tell me more about the source or even better post the log file.  😅

**Comment by fransalas71** [comment]
------------------------- System Environment -------------------------

StaxRip    : v2.42.1
Settings   : v2.42.1
Windows    : Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)
Language   : Spanish (Spain, International Sort)
CPU        : 13th Gen Intel(R) Core(TM) i9-13900KF
RAM        : 128GB
GPU        : NVIDIA GeForce RTX 4090
Resolution : 3840 x 2160
DPI        : 168
Code Page  : 1252

----------------------- Media Info Source File -----------------------

C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv

General
Complete name            : C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv
Format                   : Matroska
Format version           : Version 4
File size                : 7.59 GiB
Duration                 : 1 h 20 min
Overall bit rate         : 13.5 Mb/s
Frame rate               : 25.000 FPS
Encoded date             : 2023-11-18 04:14:18 UTC
Writing application      : mkvmerge v66.0.0 ('Josie') 64-bit
Writing library          : libebml v1.4.2 + libmatroska v1.6.4

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 1 h 20 min
Bit rate                 : 13.0 Mb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.250
Stream size              : 7.31 GiB (96%)
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : E-AC-3
Format/Info              : Enhanced AC-3
Commercial name          : Dolby Digital Plus
Codec ID                 : A_EAC3
Duration                 : 1 h 20 min
Bit rate mode            : Constant
Bit rate                 : 224 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 129 MiB (2%)
Title                    : Castellano DD+ 2.0 @ 224 kbps
Language                 : Spanish
Service kind             : Complete Main
Default                  : Yes
Forced                   : No
Dialog Normalization     : -31 dB
compr                    : -0.28 dB
dsurmod                  : Not Dolby Surround encoded
dialnorm_Average         : -31 dB
dialnorm_Minimum         : -31 dB
dialnorm_Maximum         : -31 dB

Text
ID                       : 3
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Title                    : Castellano Completos [Planos]
Language                 : Spanish
Default                  : No
Forced                   : No

Menu
00                       : 00:00.000                             : en:Scene 1
00                       : 05:45.000                             : en:Scene 2
00                       : 10:05.000                             : en:Scene 3
00                       : 15:08.000                             : en:Scene 4
00                       : 21:19.000                             : en:Scene 5
00                       : 26:44.000                             : en:Scene 6
00                       : 31:46.000                             : en:Scene 7
00                       : 37:14.000                             : en:Scene 8
00                       : 42:54.000                             : en:Scene 9
00                       : 48:13.000                             : en:Scene 10
00                       : 53:40.000                             : en:Scene 11
00                       : 59:33.000                             : en:Scene 12
01                       : 04:37.000                             : en:Scene 13
01                       : 09:59.000                             : en:Scene 14
01                       : 14:54.000                             : en:Scene 15
01                       : 19:20.000                             : en:16. End Credits

---------------------- Indexing using ffmsindex ----------------------

C:\Users\FranSalas\Desktop\StaxRip-v2.42.0-x64\Apps\Plugins\Dual\ffms2\ffmsindex.exe "C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv" "D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\temp.ffindex"

Writing index... done.

Start:    11:52:28
End:      11:52:34
Duration: 00:00:05

---------------------------- Configuration ----------------------------

Template                    : NVEncC_SDR_Series
Video Encoder               : NVEnc
Video Encoder Profile       : NVEncC (Nvidia) | H.265
Container/Muxer Profile     : MKV (mkvmerge)
+++++
Process Priority            : Idle
Delete Temp Files           : Disabled
Delete Temp Files Selection : Include

------------------------- VapourSynth Script -------------------------

import os, sys
import vapoursynth as vs
core = vs.core

sys.path.append(r"C:\Users\FranSalas\Desktop\StaxRip-v2.42.0-x64\Apps\Plugins\VS\Scripts")
core.std.LoadPlugin(r"C:\Users\FranSalas\Desktop\StaxRip-v2.42.0-x64\Apps\Plugins\Dual\ffms2\ffms2.dll", altsearchpath=True)

tcFile = r"D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_timestamps.txt" # timestamps file path
clip = core.ffms2.Source(r"C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv", cachefile=r"D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv", cachefile=r"D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\temp.ffindex")
clip = core.resize.Bicubic(clip, format=vs.YUV420P10)

clip.set_output()

------------------------- Source Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 120867
Time      : 01:20:34.680
Framerate : 25 (25/1)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 120867
Time      : 01:20:34.680
Framerate : 25 (25/1)
Format    : YUV420P10

--------------------------- Video encoding ---------------------------

NVEncC 7.66

C:\Users\FranSalas\Desktop\StaxRip-v2.42.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe --avsdll C:\Users\FranSalas\Desktop\StaxRip-v2.42.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --vbr 3000 --codec h265 --preset P7 --output-depth 10 --profile main10 --tier high --level 5.1 --multipass 2pass-full --qp-init 4 --qp-max 69 --bframes 4 --ref 4 --lookahead 3 --cu-min 8 --cu-max 64 --colormatrix bt709 --colorprim bt709 --transfer bt709 --atc-sei bt709 --colorrange limited --chromaloc 2 -i "D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01.vpy" -o "D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01_out.h265"

------------------------------------------------------------------------------------------------------------------------
D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01_out.h265
------------------------------------------------------------------------------------------------------------------------
NVEncC (x64) 7.66 (r2994) by rigaya, Sep  2 2024 12:52:18 (VC 1929/Win)
OS Version     Windows 11 x64 (22631) [UTF-8]
CPU            13th Gen Intel Core i9-13900KF [5.52GHz] (8P+16E,24C/32T)
GPU            #0: NVIDIA GeForce RTX 4090 (16384 cores, 2520 MHz)[PCIe4x16][560.81]
NVENC / CUDA   NVENC API 12.2, CUDA 12.6, schedule mode: auto
Input Buffers  CUDA, 24 frames
Input Info     VapourSynthMT r66(yv12(10bit))->p010 [AVX2], 1920x1080, 25/1 fps
Vpp Filters    copyHtoD
Output Info    H.265/HEVC main10 @ Level 5.1
               1920x1080p 0:0 25.000fps (25/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        3000 kbps (Max: 153600 kbps)
Target Quality auto
Initial QP     I:4  P:4  B:4
QP range       I:0-63  P:0-63  B:0-63
QP Offset      cb:0  cr:0
VBV buf size   auto
Split Enc Mode auto
Lookahead      on, 3 frames, Level 0, Adaptive I, B Insert
GOP length     250 frames
B frames       4 frames [ref mode: middle]
Ref frames     4 frames, MultiRef L0:auto L1:auto
AQ             off
CU max / min   64 / 8
VUI            matrix:bt709,colorprim:bt709,transfer:bt709,range:limited,chromaloc:topleft
Others         mv:auto repeat-headers 
encoded 120867 frames, 145.77 fps, 3094.97 kbps, 1783.75 MB
encode time 0:13:49, CPU: 0.5, GPU: 45.0, VE: 51.6, VD: 0.0, GPUClock: 2716MHz, VEClock: 2100MHz
frame type IDR  1226
frame type I    1226,  total size    88.03 MB
frame type P   37080,  total size  1153.22 MB
frame type B   82561,  total size   542.50 MB

Start:    11:53:08
End:      12:07:01
Duration: 00:13:52

General
Complete name            : D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01_out.h265
Format                   : HEVC
Format/Info              : High Efficiency Video Coding
File size                : 1.74 GiB
Frame rate               : 25.000 FPS

Video
Format                   : HEVC
Format/Info              : High Efficiency Video Coding
Format profile           : Main 10@L5.1@High
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0 (Type 2)
Bit depth                : 10 bits
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709 / BT.709
Matrix coefficients      : BT.709

---------------------------- Muxing to MKV ----------------------------

mkvmerge 86.0

C:\Users\FranSalas\Desktop\StaxRip-v2.42.0-x64\Apps\Support\MKVToolNix\mkvmerge.exe -o "C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01.mkv" "D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01_out.h265" --no-video --no-subs --no-chapters --no-attachments --no-track-tags --no-global-tags --audio-tracks 1 --language 1:es --track-name "1:Castellano DD+ 2.0 @ 224 kbps" --default-track-flag 1:1 --forced-display-flag 1:0 --commentary-flag 1:0 "C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv" --no-audio --no-video --no-chapters --no-attachments --no-track-tags --no-global-tags --subtitle-tracks 2 --language 2:es --default-track-flag 2:0 --forced-display-flag 2:0 --commentary-flag 2:0 --hearing-impaired-flag 2:0 --track-name "2:Castellano Completos [Planos]" "C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv" --ui-language en

mkvmerge v86.0 ('Winter') 64-bit
'D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01_out.h265': Using the demultiplexer for the format 'HEVC/H.265'.
'C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv': Using the demultiplexer for the format 'Matroska'.
'C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv': Using the demultiplexer for the format 'Matroska'.
'D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01_out.h265' track 0: Using the output module for the format 'HEVC/H.265 (unframed)'.
'C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv' track 1: Using the output module for the format 'AC-3'.
'C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO].mkv' track 2: Using the output module for the format 'text subtitles'.
The file 'C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01.mkv' has been opened for writing.
'D:\other\staxrip.temp\Aguila Roja S01E01 [AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]_temp\Aguila Roja S01E01_out.h265' track 0: Extracted the aspect ratio information from the video bitstream and set the display dimensions to 1920/1080.
The cue entries (the index) are being written...
Multiplexing took 6 seconds.

Start:    12:07:01
End:      12:07:08
Duration: 00:00:06

----------------------- Media Info Target File -----------------------

General
Complete name            : C:\Users\FranSalas\Desktop\Aguila Roja (2009) S01 [PACK][AMZN WEB-DL 1080p AVC ES DD+ 2.0 Subs][HDO]\Aguila Roja S01E01.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 1.87 GiB
Duration                 : 1 h 20 min
Overall bit rate         : 3 321 kb/s
Frame rate               : 25.000 FPS
Encoded date             : 2024-09-15 10:07:01 UTC
Writing application      : mkvmerge v86.0 ('Winter') 64-bit
Writing library          : libebml v1.4.5 + libmatroska v1.7.1

Video
ID                       : 1
Format                   : HEVC
Format/Info              : High Efficiency Video Coding
Format profile           : Main 10@L5.1@High
Codec ID                 : V_MPEGH/ISO/HEVC
Duration                 : 1 h 20 min
Bit rate                 : 3 095 kb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0 (Type 2)
Bit depth                : 10 bits
Bits/(Pixel*Frame)       : 0.060
Stream size              : 1.74 GiB (93%)
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709 / BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : E-AC-3
Format/Info              : Enhanced AC-3
Commercial name          : Dolby Digital Plus
Codec ID                 : A_EAC3
Duration                 : 1 h 20 min
Bit rate mode            : Constant
Bit rate                 : 224 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 129 MiB (7%)
Title                    : Castellano DD+ 2.0 @ 224 kbps
Language                 : Spanish
Service kind             : Complete Main
Default                  : Yes
Forced                   : No
Dialog Normalization     : -31 dB
compr                    : -0.28 dB
dsurmod                  : Not Dolby Surround encoded
dialnorm_Average         : -31 dB
dialnorm_Minimum         : -31 dB
dialnorm_Maximum         : -31 dB

Text
ID                       : 3
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Duration                 : 1 h 18 min
Bit rate                 : 70 b/s
Frame rate               : 0.244 FPS
Count of elements        : 1150
Stream size              : 40.8 KiB (0%)
Title                    : Castellano Completos [Planos]
Language                 : Spanish
Default                  : No
Forced                   : No

---------------------------- Job Complete ----------------------------

Start:    11:53:06
End:      12:07:08
Duration: 00:14:01

**Comment by Dendraspis** [comment]
I guess you have changed the `Preprocessing` in the `Settings`...

When you use new settings, it should work again. You can try it out by temporarily renaming your `Settings` folder.

**Comment by fransalas71** [comment]
ok, solved.... thanks a lot

**Comment by fransalas71** [comment]
ok, solved.... thanks a lot
