### ISSUE TITLE
x265-4.0

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1490]
Hi, 

Well, my baby is a grown up now 🥹

I tried using patman's builds of v4.0 with Stax2.42.1 but it didn't work. I don't know if patman has to do something about it. Or you should add support. I wanted to PM patman about it on doom9 but seems like he's busy these days. So, I decided to ask here. 

I get this error when I run stax with x265 v4.0:
```
x265.exe - System Error
---------------------------
The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem. 
```

I know this is related to MinGW/gcc compiler and maybe downloading and putting the dll in the stax directory fixes the issue. But before I do all that, I wanted to know if you guys checked it and if v4 is already compatible with Stax

/////

before I post this, I decided to check the msvc version. It seems to be working just fine. No error of anything. But I rather have the gcc version. 

So, I wanted to know your opinion. Should I grab libstdc++-6.dll and use it as is, should I wait for patman to do something about it(I think using -static-libgcc and -static-libstdc++ would solve this)  or should I wait for Stax to support it?
Thank you

**Comment by Dendraspis** [comment]
Hello,

the `x265 v4.0` release is made exactly like the previous ones, except the compiler version. I guess you are just missing some C++ Runtimes. You can download and install them from here:  [Microsoft Visual C++ Redistributable Runtimes All-in-One](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/)

StaxRip is compatible with that version since. `v2.42.0`.

**Comment by LazyNCoder** [comment]
> Hello,
> 
> the `x265 v4.0` release is made exactly like the previous ones, except the compiler version. I guess you are just missing some C++ Runtimes. You can download and install them from here: [Microsoft Visual C++ Redistributable Runtimes All-in-One](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/)
> 
> StaxRip is compatible with that version since. `v2.42.0`.

Unfortunately, that didn't help. I had already installed all the VC++ files. But knowing that there's no issue with the v4.0 I will try to install the dll for gcc version, if I find it anywhere.

![sshot-2024-09-16- 21-36-43](https://github.com/user-attachments/assets/9ab848a2-2b8f-4272-95e3-e9a4c2724f2a)

**Comment by LazyNCoder** [comment]
update:
I found the needed dlls in Filezilla installation folder. 
libgcc_s_seh-1.dll
libstdc++-6.dll

copied both of these files in Stax's folder and it started working. Hopefully that's the end of it. 
There wouldn't be any glitches or anything bad.

**Comment by LazyNCoder** [comment]
![sshot-2024-09-17- 01-17-44](https://github.com/user-attachments/assets/637b02b1-346a-42eb-84d2-aab8df44fe7c)

**Comment by Dendraspis** [comment]
There should not be any issues once it started running.

Btw:  You can also use the `msvc` version, which should not have such issues, like:
`x265 v4.0+4+2-c591f33d4-.Mod-by-Patman.-x64-avx2-msvc1940`

**Comment by Dendraspis** [comment]
It looks like you were right - there is something different with this release.  I had tested `v3.6.85` which was compiled with the same compiler which worked (and works), but `v4.0` also gives me the error message you were faced with.  😕 

Patman86 will take a look at that issue when he has some time...

**Comment by Dendraspis** [comment]
@LazyNCoder 
Patman has updated his GCC-Releases, now they work without issues.  👍
