### ISSUE TITLE
Custom output path not working

### ISSUE THREAD

**Issue by R3S3t9999** [staxrip/staxrip#1491]
I set a custom output path for my template but when I load any file, the path is missing the backslash \ and the file is saved in the staxrip folder instead of the path I added.

```
custom path:  D:\
got D:
```

![Capture d’écran 2024-09-16 142752](https://github.com/user-attachments/assets/ef61e087-6f3d-4aff-8149-28053a1dbe72)

**Comment by Dendraspis** [comment]
Thanks for the report.

Until the fix will be released, you can type in `D:\\` which should fix your issue.

**Comment by Dendraspis** [comment]
Will be fixed in `v2.42.2`, that will be released within the next days...
