### ISSUE TITLE
Change Crop Keyboard shortcut from numpad +/- to just +/-

### ISSUE THREAD

**Issue by mokahless** [staxrip/staxrip#1492]
**Is your feature request related to a problem? Please describe.**
Any laptop without a numpad and anyone who prefers a smaller keyboard doesn't have a keyboard shortcut available to crop in the crop interface, resulting in an incredulous amount of "right click>increase active side" clicks.

**Describe the solution you'd like**
Ideally, a way to customize keyboard shortcuts would be best but a faster solution might be to change the accepted keypress to be just the regular +/- meaning numpad users will be unaffected while small keyboard users can just use the normal "-" and "shift =" (+)

**Describe alternatives you've considered**
autohotkey, if devs don't have time to consider this and anyone find this via a google search. Be a bit to set up and you'd have to run it on each device but once you've got it going, it'll keep working. Just find an example keypress replacement script to get you going.

**Explain why the feature matters to you**
Productivity speed.

**Comment by Dendraspis** [comment]
In the bottom right of the Crop window you can find a `Menu` button. When you click on it, you get a menu where you can find all actions as well as `Edit Menu` where you can customize the keys:

<img width=300 src=https://github.com/user-attachments/assets/0a63434b-1b98-4f6b-a6c8-98ec046735c5> 
<img width=500 src=https://github.com/user-attachments/assets/90ca4b56-d3f1-4d66-909d-461608441007>
