### ISSUE TITLE
Allow adding job if there is any source filter

### ISSUE THREAD

**Issue by Didas-git** [staxrip/staxrip#1498]
**Is your feature request related to a problem? Please describe.**
I was testing adding multiple sources into just 1 script profile so its easier to switch between the source type i want, however if i disable the source script at the top StaxRip errors saying `The first filter must have the category Source` even if it is the source script is the first **enabled** one (see screenshot bellow for my specific case)

![image](https://github.com/user-attachments/assets/f3eed5fb-d159-4c2b-aa7a-b32c7d899708)

**Describe the solution you'd like**
I would like for StaxRip to only require to have 1 source type no matter the location in the filters.

**Describe alternatives you've considered**
Another option its to at least require it to be the first enabled script, so if all the filters above are disabled it would still be counted as the first.

**Explain why the feature matters to you**
I just see it as a nice QoL improvement, its fairly inconvenient to have to move the filter up and down.

**Comment by Dendraspis** [comment]
But you still have to open it, so I guess the difference are (just) some additions after the source filter?

**Comment by Didas-git** [comment]
i dont quite understand what you mean with opening it, do you mean opening the filter code or like importing the source file? 
Sorry if im missing something here...

**Comment by Dendraspis** [comment]
The first filter in your screenshot is a `Source` filter called `FFVideoSource`with the purpose to open the source file ( using `FFVideoSource`. The second one is activated and is called `With logo overlay`. So isn't it just the same filter but with added lines?

The thing is that you won't be happy with the change, because it's not just the Assistant message you get. Underneath there is a lot more going on with the (selected) `Source` filter and on top it gets overwritten by StaxRip.

**Comment by Didas-git** [comment]
Its not just added lines, due to how `Overlay` works the actual final source ends up being the result of `AlignedSplice`.

I did not know that StaxRip modified filters that much, do you an example or somewhere i could read what it does to the `Source` filter? Because other than it adding the import for `ffms2`  and other plugins the `preview code` doesnt really show anything else.

**Comment by Dendraspis** [comment]
StaxRip uses it for example for cropping and multiple other scenarios and may overwrite it with one of the given profiles.
Altered filter categories are for example `Source`, `Crop`, `Resize`, `Cutting` and `Rotation`.

When you just add some lines, you should create an extra category for it and enable it if needed.

But for me it sounds like you want to add your own `Source` profiles. This way you can select them via rightclick on `Source` and `Replace`. You can find and edit the profiles here - the content should be self-explaining as there are some existing profiles in single- and multirow-style:

<img width=400 src=https://github.com/user-attachments/assets/32efc6f4-ae1a-4ae6-98e5-ba2168968b16>

**Comment by Didas-git** [comment]
Adding a new profile does solve the inconvenience to some extent, however now when i share my `srip` file it does not include those new profiles, is there any way to export/share this profile settings?

**Comment by Dendraspis** [comment]
That would be another feature request.  😅 

Currently you can only copy/paste the profiles.

**Comment by Didas-git** [comment]
Well... i'd argue that both are valid feature requests but from a technical standpoint i can see my initial one being way more complicated to implement and just flat out just break a lot of things, so, maybe the issue should be renamed to adding profile exports to other features like filters.

**Comment by Dendraspis** [comment]
After some thinking and checking I would have to change too much of StaxRip logic and handling regarding the first source filter. And I'm not going to do that.

If you want to use different source filters, you should use different templates or you can change them via right-click and the source filter selection. Alternatively you can remove the first unused source filters or move the active one to the top.
