### ISSUE TITLE
Suggestion: Add container tab for attachments

### ISSUE THREAD

**Issue by Ch0kehold** [staxrip/staxrip#15]
Hello,

Is there a possibility in a future build to include an attachment tab in the Container Options?
More often than not I use styled softsubs for multiple videos at a time that tend to use the same settings and it would be great to be able to attach the font files directly via Staxrip as part of the project.

As things are now I have to attach fonts separately via MKVToolNix after each project so I know it is possible with MKV container, not so sure about MP4.

**Comment by stax76** [comment]
Hi, maybe as I think it will be a couple hours of work.

**Comment by stax76** [comment]
The new beta has support for this.
