### ISSUE TITLE
Why ffmpeg volumedetect is used instead of qaac --normalize?

### ISSUE THREAD

**Issue by ArturAlekseev** [staxrip/staxrip#1500]
2.42.1 version
When encoding dtshd to aac it does:
1) ffmpeg.exe -i "A:\x.dtshd" -sn -vn -hide_banner -af volumedetect -f null NUL
2) ffmpeg.exe -i "A:\x.dtshd" -y -hide_banner -ac 6 "out.flac"
3) qaac64.exe --tvbr 50 "A:\out.flac" -o "A:\out.m4a"

If normalize is checked then ffmpeg makes audio gain when converting to flac.
Why it is used instead of qaac normalize option?
In my case ffmpeg first pass stress CPU much higher than qaac (fan is going crazy).

**Comment by Dendraspis** [comment]
The conversion has to be done nevertheless and `ffmpeg` offers some choices and advantages. There is no really need for the build-in normalization - maybe except your CPU fan.  😅
