### ISSUE TITLE
New TEMPLATE Audio Track Number Selection should default to 1 and have ability for only 1 Track (1-6 ) selectable

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1502]
New Template number of Audio Tracks.

The ability to select number of tracks a good addition.

When selecting Automatic WorkFlow Template as a basis to create a new Template...

Defaulting to a single audio track would be best.
The user should also be able to select 1 track only - 1 audio track is probably the number most videos use. 

The default for tracks is "Copy/Mux".
The default should be "No Audio" if empty or until auto filled when a source file is added.

<img width="617" alt="241006 175122" src="https://github.com/user-attachments/assets/135220d6-ed07-4a82-979a-531cd8f6c0e7">

**Comment by Dendraspis** [comment]
> Defaulting to a single audio track would be best.

For your workflow, maybe, but most users would need 2+ tracks. Even so, unused fields are just empty, better than discarding existing audio tracks.

> The user should also be able to select 1 track only - 1 audio track is probably the number most videos use.

You can adjust it down to 2 if you need/want it. In case your videos have only 1 audio track, only one will be filled, depending on your settings. So no problem in that side.

> The default should be "No Audio" if empty or until auto filled when a source file is added.

`No audio` prohibits any insertion, so `Copy/Mux` is the right default setting. Feel free to customize and create your own template(s).

**Comment by noblemd00** [comment]
I have had .avs files inserted as the #1 track. and the proper audio track put in the #2 slot. 

The user should be able to pick the Audio tracks inserted - since this multi track went into effect I have had multiple audio tracks inserted and cannot select the one I want to be the #1 track - when I try to delete the first track or select the single audio track as track #1 it highlights in red and says duplicate track with no way to delete the same track in the #2 position - if I delete the audio track text it just reinserts the text.

There should be an option for the user to select 1 audio track and be able to specify which trac should the #1 track.

**Comment by Dendraspis** [comment]
> The user should be able to pick the Audio tracks inserted

You are able to do that in multiple ways. Seems you think too complicated...

> when I try to delete the first track or select the single audio track as track `#1` it highlights in red and says duplicate track with no way to delete the same track in the `#2` position

Right-click, then select another stream or file or click on `Remove` to delete the audio track at that position.

> if I delete the audio track text it just reinserts the text.

Yeah, a bit misleading...

> If I set the first improper track to no audio does the second track then become the `#1` track?

Yes, as this is just an ordered list of available audio tracks that is later used for muxing.

> There should be an option for the user to select 1 audio track and be able to specify which track should the `#1` track.

Just use `No Audio` for the second track and you get what you want.

> 1 audio track is the standard - 99% of the videos only need/use 1 audio track

Depends on your source files.  😅  But you seem to have also multiple audio tracks, otherwise I would not get why you have such problems.  😅

**Comment by noblemd00** [comment]
Very occasional multi tracks are present (1 out of 100) when re-encoding TV shows and movies for archiving. 

I believe I did try remove the improper first track (avs) but StaxRip did not move the 2nd Track up so I did not think it would work.

As I said I will keep eye out for the error when .avs files are loaded as audio tracks - unless this has already been reported as a problem.

---

Unrelated Side subject - I checked to see if already reported- nothing found - When Show dialog to choose Subtitles is selected and then in the selection dialog click NONE (unselecting all) - Subtitles are still loaded and selected for inclusion in target. Choosing NONE (no selected subtitles) seems to have no effect. 

Works ok if there is at least 1 subtitle selected but not if all unselected. 

Has this been reported as an issue?

I'll report this as an issue if not already known.

**Comment by Dendraspis** [comment]
> Choosing NONE (no selected subtitles) seems to have no effect.

Which demuxer and/or source file type?

**Comment by noblemd00** [comment]
NVEnc h265
Subtitles: Show dialog = None

Selected video has multiple subtitles (see MediaInfo)
<img width="500" alt="241015 100008" src="https://github.com/user-attachments/assets/da4236ea-5008-4241-8ee0-f1a0fcc03349">
<img width="620" alt="241015 100328" src="https://github.com/user-attachments/assets/8dd9077b-a282-418e-a2c3-0e200b492422">
<img width="868" alt="241015 100657" src="https://github.com/user-attachments/assets/7b0626ed-f9f0-46d4-b74e-ae919284b7c1">

[MediaInfo.txt](https://github.com/user-attachments/files/17379535/MediaInfo.txt)

**Comment by Dendraspis** [comment]
Okay, now I got it. I confirm, that all subtitles are extracted and included if *none* is selected....

**Comment by Dendraspis** [comment]
Will be fixed in `v2.42.2`, that will be released the next days...
