### ISSUE TITLE
Xvid not coded

### ISSUE THREAD

**Issue by filyse** [staxrip/staxrip#1504]
Error Video encoding command line encoder: XviD (v2.42.1)

"C:\Users\filys\Desktop\x_v_i_d_encraw-1.3.7\xvid_encraw.exe" -bitrate 1500 -progress -max_key_interval 100 -kboost 100 -ostrength 10 -oimprove 10 -odegrade 10 -chigh 30 -clow 15 -turbo -vhqmode 4 -bvhq -nopacked -masking 2 -imin 1 -bmin 1 -pmin 1 -threads 1 -par %target_sar% -pass1 "C:\Stax\Temp\XviD\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb_temp\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb.stats" -i "C:\Stax\Temp\XviD\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb_temp\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb.avs" || exit

xvid_encraw - raw mpeg4 bitstream encoder written by Christoph Lampert
Trying to retrieve width and height from input header
Can't open avi/avs file C:\Stax\Temp\XviD\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb_temp\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb.avs

Video encoding command line encoder: XviD returned exit code: -1 (0xFFFFFFFF)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

StaxRip.ErrorAbortException: "C:\Users\filys\Desktop\x_v_i_d_encraw-1.3.7\xvid_encraw.exe" -bitrate 1500 -progress -max_key_interval 100 -kboost 100 -ostrength 10 -oimprove 10 -odegrade 10 -chigh 30 -clow 15 -turbo -vhqmode 4 -bvhq -nopacked -masking 2 -imin 1 -bmin 1 -pmin 1 -threads 1 -par %target_sar% -pass1 "C:\Stax\Temp\XviD\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb_temp\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb.stats" -i "C:\Stax\Temp\XviD\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb_temp\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb.avs" || exit

xvid_encraw - raw mpeg4 bitstream encoder written by Christoph Lampert
Trying to retrieve width and height from input header
Can't open avi/avs file C:\Stax\Temp\XviD\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb_temp\The Simpsons S36E01 Barts Birthday 1080p DSNP WEB-DL DDP5 1 H 264-NTb.avs


Video encoding command line encoder: XviD returned exit code: -1 (0xFFFFFFFF)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   в StaxRip.Proc.Start() в D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:строка 366
   в StaxRip.BatchEncoder.Encode() в D:\Code\Github\staxrip\staxrip\Source\Encoding\VideoEncoder.vb:строка 570

**Comment by Dendraspis** [comment]
Sorry, I can't really help with this one. I have not used XviD for at least 15 years I guess. You should really think about using AV1 for such videos in 2024.

But it seems like XviD should get the source file as input file instead of the AviSynth script which it surely cannot read.
