### ISSUE TITLE
Unicode filenames are not supported by AviSynth unless Windows 10 is used.

### ISSUE THREAD

**Issue by chowderhead** [staxrip/staxrip#1506]
i am using win 10. Enterprise LTSC build 17763rs5 release 180914-1434

but it doesnt seem to understand that giving me the error:
```
Unicode filenames are not supported by AviSynth unless Windows 10 is used.

Rename the file or enable VapourSynth:

Filters > Filter Setup > VapourSynth
```
I dont want to use vapoursynth because the script im using is avisynth.

the files are named as follows. 
Soul Land - S01E01 - 第001集.mkv  002 etc all the way thru 14 seasons
Soul Land - S14E13 - 第234集

what should i do??
Thanks.  RK

**Comment by chowderhead** [comment]
the system seems to want to enhance the text I typed. 
 I didnt make those lines 60 or 70   \\point type or whatever size that is

"but it doesnt seem to understand that giving me the error:" and
"Filters > Filter Setup > VapourSynth "

  became super large font size all by itself FYI.

**Comment by Dendraspis** [comment]
Nothing I can do about it I guess. The verification is done by StaxRip to make sure everything works as intended.
Maybe it will help to make sure the path is short enough, no Unicode characters are used and that the script file is saved in UTF-8.

> became super large font size all by itself FYI.

It's the markdown language.  😉

**Comment by chowderhead** [comment]
> Nothing I can do about it I guess. The verification is done by StaxRip to make sure everything works as intended. Maybe it will help to make sure the path is short enough, no Unicode characters are used and that the script file is saved in UTF-8.
> 
> > became super large font size all by itself FYI.
> 
> It's the markdown language. 😉

Why would you say "nothing I can do."
yu wrote the code.  \
why is it saying itt wont work with unixode unless win 10 and it is win 10.  
When I rename the files by removing pinyin it works but why is the other incorrect  error being produced

mkvtoolix works fine i tested it with pinyin.

**Comment by chowderhead** [comment]
> Because your system seems to not support it. As far as I can see your Windows build came out before the `1903`(?) build,

pinyin unicode 
wrks in mkvtoolnix
works with nkvmerge
works w potplayer
works with VLC 
works with outlook email
as a test I renamed it adding at leaast 59 more letters.
![LONGPATHS](https://github.com/user-attachments/assets/62fe7edf-7e6d-46e5-af3e-c4115a81d9e1)
from my regedit iImage attached.  This LTSC has long paths enabled,

 Your acting like this error is VALID.  its not valid its AT ALL..
Its gouldnt say anything abour long paths.  

are you sure there isnt a actual reason this incorrect error was thrownn by ONLY sttaxeip.  
It just seems like there should be ANOTHER **just as irritated program by the unicode** if it was a global machine OS thing.\\

Im not being stubborn, This could happen to anyone.

**Comment by chowderhead** [comment]
thanks for the detailed explanation., I truly appreciate it.  **It helped me in my thinking**
I even tried it sitting at the root of C drive where the path us C://fiilename, FAIL
its odd that all other apps ARENT bothered but they dont use avisynth+
which tells me avistnth is possibly the root issue.

so i got the latest avisynth removed old made sure all bits pieces are removed and 
installed                           AviSynthPlus_3.7.3_20230715
my installed version was AviSynthPlus_3.4.0_20191020
doesn't seem like much until you read everything that was fixed between these versions.
pages and pages and pages AND MORE pages of fixes.  100s of things fixed.

GOOD NEWS.  error is gone files go to completion in staxRIP.
When I set up this machine I made the mistake of just using an AVIsynth+ installer from a
quickinstall folder of installers i had in archive.
due to age of avisynth+ I didnt expect such dramatic update between the versions.

naturally when setting up a machine you want to use the latest or dam close so auto updaters can handle rest.
most things auto update once connected to the net as well.  avisynth doesnt.
anyway i found the real issue.  avisynth+ must be latest.
cheers.

**Comment by chowderhead** [comment]
Thanks man.  Your comments helped steer me to the solution.
Kudos to the guys that are carrying water on the programming of avisynth.
Man what a massive list of bug fixes.  Just crazy.

Im very happy because Ive got 100s of files sitting in queue all with names like  Soul Land - S07E03 - 第133集.mkv
Or much worse.
