### ISSUE TITLE
Typo: "TDent" should be "TDeint"

### ISSUE THREAD

**Issue by Binjohn** [staxrip/staxrip#151]
This typo appears in AviSynth filter profiles and the changelog. I updated from StaxRip 1.5.0.0 to 2.0.8.0 recently and saw it.

PS. Thank you for this software! I have used this for several years.

![Filter Profiles](https://user-images.githubusercontent.com/43265566/78285565-362ee600-7553-11ea-8649-3907d30ff8ea.png)

**Comment by stax76** [comment]
Thanks for reporting, will be fixed in the next build.
