### ISSUE TITLE
qaac encoder normalization issue: normalization is applied two times

### ISSUE THREAD

**Issue by eremichyura** [staxrip/staxrip#1510]
**BUG**

When trying to use audio ffmpeg dynaudnorm normalization we need to check `Normalize` checkbox to proceed. 
But this aslo adds `--normalize` to qaac encoder witch make doble normalizations: 
first one: `ffmpeg dynaudnorm`
second one: `qaac --normalize`

**Expected behavior**
Should be checkboxes to select: to normalize with ffmpeg or to normalaize with qaac (and they should be excluding each other).

**REPRODUCE**
1. Select `Normalize` for codec AAC and encoder qaac :
![image](https://github.com/user-attachments/assets/34b71151-2372-4717-84d7-1be311b4e44a)

2. GoTo More...:
![image](https://github.com/user-attachments/assets/5ff8ee76-539f-4107-b5f8-d31e64f73f36)

-> Then GoTo `General` and select `Pipe` (with wave normalizations didn't work at all):
![image](https://github.com/user-attachments/assets/b1a95bd5-7c5c-401a-84ab-1565bba51dd7)

3. GoTo More...:
![image](https://github.com/user-attachments/assets/94299576-1427-4d76-bbd2-2caa4aad85e7)

-> Then goto `ffmpeg` and select `dynaundnorm`

4. Than in `Show comand lline` you can see that normalizations will be apply 2 tumes:
![image](https://github.com/user-attachments/assets/19ae2b5a-583b-46f5-93e6-5948762c68fb)

Here My example:
`C:\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe -i "F:\VideoEncodingTests\sets. film_original_low_bitrate_tests\film_original_low_bitrate_temp\***.ac3" -af dynaudnorm=f=700:g=51:p=0.9:m=4:r=0.3:c=true -loglevel fatal -hide_banner -f wav - | C:\StaxRip\Apps\Audio\qaac\qaac64.exe --tvbr 45 --normalize --no-delay - -o "***.m4a"`

And this is incorrect because when applying such normalization like ffmpeg dynaudnorm it's defenetly no need is such pure simple  normalization like qaac --normalize. It's make results unpredicrable and low quality.

#######
- Used StaxRip version 2.42.1

- logs when encoding using `pipe` method: [mando_original qaac-703-n-a290.log](https://github.com/user-attachments/files/17386735/mando_original.qaac-703-n-a290.log)

from logs is not clear if `dynaudnorm` was applied (looks like yes), but `qaac --normalize` was applyed in 100%

- logs when encoding using `wave` method: [mando_original qaac-704-n-wave.log](https://github.com/user-attachments/files/17386780/mando_original.qaac-704-n-wave.log)

Here in loggs we see that `dynaudnorm normalization` wasn't applyed at all when extracting to wave, but was applyed `qaac --normalize` when encoding

**Comment by Dendraspis** [comment]
Difficult...

Meanwhile the normalization process has been altered (and is available for supporters). `Pipe` can not really work as multiple steps are needed. But for the intermediate files, the current workflow is to apply `dynaudnorm` and then perform another normalization with `volumedetect` and `volume=x` because `dynaudnorm` does not perform an overall normalization.

So in this case applying `dynaudnorm` and the encoder `--normalize` seems also legit for me.  🤔

**Comment by eremichyura** [comment]
Thanks for reply, currently i have a workaround - using fdkaac encoder. A bit bigger file but sound is also very good.

And it's good to here about it's implemented in RC.

Related to problem (my point of view):
it's very depends on for what you are applying normalization. If it's a multichannel audio track from action moovie and your already aplyed dynanorm than applying over this "simpe" volumedetect normalizations can lead to distortions and clipping. 

Maybe for some music audio it's ok, don't know. But for video, espacially with multichannel...and big dynamic range audio it risky, because:
1. Dynaudnorm is specifically designed for processing dynamic rande - it makes quiet dialogue clearer while maintaining the impact of loud scenes (explosions, gunfire or some else loud sounds). This is important for keeping the emotional and dynamic flow of an action movie intact. 
2. And when you applying volumedetect and volume=x after dynaudnorm this could  push the already dynamically balanced audio to levels that exceed what your system can handle, causing clipping and distortion—especially during the loud peaks. 

Also, I think, that if audio "global loudnes" is still very low after dynanorm then it's a bad audio candidate for normalization at all  - you will increase not only "good sound" but also all "hidden trash" like noises... and maybe will get distortions, clips, metallic voices and other cool stuff.

I did a plenty tests on this with double normalization (qaac normalize after dynanorm) and always I got unpredictable results... metall voice, clipping, distortion, or any combinations of.

It's  significant risk to get all problems ( just metioned before) when you've already applied dynamic normalization and trying to apply any other normalizations for problems when you are working with good original. 

yes, it's "legit" but in rare cases, so, it's good  to have only dynaudnorm normalizations in automatic mode for qaac  encoder without --normalize (now thay are strictly connected). 

As a side note: 
I tried to do dynanorm using fdkaac  - and all is good, just because there is no such param like --normalize for fdkaac: ffmpeg correctly aplying dynanorm and then pyping  result to fdkaac encoder witch doesn't have built-in normalization and just encode.

But anyway, thanks, great tool!

**Comment by Dendraspis** [comment]
> and your already aplyed dynanorm than applying over this "simpe" volumedetect normalizations can lead to distortions and clipping.

By definition and implementation it will not - as long as it works correctly.
`dynaudnorm` does change the channels compared to each other, but it does not change the overall peak. If you have a max peak of `-30dB` it might change to `-28dB` or so, but it stays low/silent. With `volumedetect`/`--af volume` you raise the volume of all channels towards `0dB`, till the loudest channel reaches `~0dB`, whereas their characteristics keep the same - just louder.

> Also, I think, that if audio "global loudnes" is still very low after dynanorm then it's a bad audio candidate for normalization at all - you will increase not only "good sound" but also all "hidden trash" like noises... and maybe will get distortions, clips, metallic voices and other cool stuff.

Maybe, but normalization is normalization.  😅   And depending on the source it should be okay to normalize `-50dB` files.

> I did a plenty tests on this with double normalization (qaac normalize after dynanorm) and always I got unpredictable results... metall voice, clipping, distortion, or any combinations of.

It's definitely over - meanwhile it is done via `ffmpeg` only.

> It's significant risk to get all problems ( just metioned before) when you've already applied dynamic normalization and trying to apply any other normalizations for problems when you are working with good original.

So far no issues with the new implementation after a lot of tests.  😁 

We will see....

**Comment by eremichyura** [comment]
hm, agree, almost)

dynaudnorm works by normalizing each audio channel independently. It ensuring that quieter sections are boosted while louder sections are not. But yest it can change the balance between the channels, particularly if one channel is quieter than the others. (but not must - if I'm correct it's setvia some parameter - coupling I think but not to much)
and dyna normalization is applied per channel which may slightly alter their relative volumes, but yes it doesn't significantly change the overall peak unless specified through parameters like target peak.

and here is what I'm talking about: 

Channels in audio could be inbalanced!. When you apply dynaudnorm to audio with channel imbalances, for example:
    One channel at +5 dB
    Another channel at -10 dB

dynaudnorm will try to normalize both channels independently, adjusting each channel's dynamic range. The goal is to bring quieter parts up and louder parts down, making the overall dynamic range more consistent within each channel.
So, after dynaudnorm, you we should see:

    The channel originally at +5 dB will be  +3 dB
    The channel originally at -10 dB will be  -7 dB or -6 dB.

And yes we  can expect relative adjustments of about ±2-3 dB per channel, depending on settings like frame length, max gain factor, and target RMS. Yes ther is coupling mode but again - +-3-2 dB

After dynaudnorm, applying volume normalization (e.g., using the volume x after volumedetect) as I understand this typу ща normalisation:

-  volumedetect will measure the peak level of the entire mix (not individual channels).
- Result will be highest peak across all channels (regardless of their individual levels). 
- When we applying a volume normalization filter using volume, thene filter will  adjust all channels by the same amount. It won't apply different gain values to different channels. Instead, it will increase (or decrease) the gain for the entire mix so that the loudest peak hits 0 dB (or othert we set)

For my example:
- If volumedetect reports a peak of -5 dB, and we apply volume to boost everything by 5 dB, every channel will be raised by 5 dB.
- The channel that was at +3 dB (after dynaudnorm) will now be at +8 dB.
- The channel that was at -7 dB (after dynaudnorm) will now be at -2 dB.

something like) if i'm correct. 

...lot of tests with issues for qacc with simple normalization after dyna:)
for fdkaac WITHOUT after simple voluem normalization - no issues 😁

yep) waiting new version)

**Comment by Dendraspis** [comment]
> The channel that was at +3 dB (after dynaudnorm) will now be at +8 dB

That should be not possible as `dynaudnorm` should take care of clipping and prevent channels from ending louder than 0dB. Secondly `volumedetect` would recognize at least those +3dB so min -3dB would be applied.

**Comment by eremichyura** [comment]
ok, this was bad example...

last try to explaing my point of view:

I was talking about what could be - IMBALANCED channels and then applying normilize after dynanorm will lead to audio problems
It could be such case:
- channel 1: -4 db; 
- channel 2: -12 db;
- channel 3: -10 db;
- channel 4: -17 db;
- channel 5: -15 db;
- 6 channel: -17 db

1. no issues for dynanorm, yes?. and it will apply max +- 1-2-3 db (espacialy for channel 1)
2. volumedetect will NOT get peak volumes from channels separetly and apply difefrent values to different channels - it will anylyze mixed result for all channel, and it will be smaller value than -4 db.
3. Then, appling this one value to ALL channels -  channel 1 will get result > 0 dB.

And this is exactly what I mean under imbalanced channels, which in multichannel movie audio could be.

**Comment by eremichyura** [comment]
and just a siide note: 
with bad params for dynanorm it could be that channel volume peaks will be >0... if you set big increasing of silence part (Max Gain Factor) without limiting high peaks (Target Peak) plus small Frame Length andf high Target RMS... and ...you can get >0
:)

**Comment by eremichyura** [comment]
ok, if this is that way, than looks like i'm wwrong.

**Comment by Dendraspis** [comment]
Will be fixed/changed in `v2.44.0`...
