### ISSUE TITLE
QTGMC - Illegal instruction

### ISSUE THREAD

**Issue by John3d** [staxrip/staxrip#1519]
**Describe the bug**
Script Error

System exception - Illegal Instruction
(D:\Estudio de grabacion\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 1053)
(D:\Estudio de grabacion\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 847)
(E:\video_temp\video.avs, line 25)

**Expected behavior**
Use QTGMC for deinterlaced

**How to reproduce the issue**

AVS filter :   Field - deinterlace - QTGMC - QTGMC... or QTGMC with repair

**Provide information**

Script Error

System exception - Illegal Instruction
(D:\Estudio de grabacion\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 1053)
(D:\Estudio de grabacion\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 847)
(E:\Navidad_temp\Navidad_new.avs, line 25)

If you can't (or don't) share your log file, give us at least this information:

- Used StaxRip version v2.42.1

**Notes before posting**

System:

Procesador	AMD FX(tm)-8300 Eight-Core Processor              3.30 GHz
RAM instalada	16,0 GB
Tipo de sistema	Sistema operativo de 64 bits, procesador basado en x64
Edición	Windows 10 Pro
Versión	22H2
Compilación del sistema operativo	19045.5011
Experiencia	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by Dendraspis** [comment]
I would need the log file to check some things - QTGMC itself seems to works fine:

<img width=700 src=https://github.com/user-attachments/assets/9b11a10d-832c-4c39-83cb-a37fbf67df2f>

**Comment by John3d** [comment]
Ok. It´s log file

[Navidad_staxrip.log](https://github.com/user-attachments/files/17544664/Navidad_staxrip.log)

**Comment by Dendraspis** [comment]
🤔   Interestingly the log file does not contain the needed information.

Can you right-click on the filters on the left side, click on `Preview Code` and copy&paste the code here?

**Comment by John3d** [comment]
yes

  1: AddAutoloadDir("D:\Estudio_grabacion\StaxRip\Apps\FrameServer\AviSynth\plugins\")
  2: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\AddGrainC\AddGrainC.dll")
  3: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\Bwdif\BWDIF.dll")
  4: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\DFTTest\dfttest.dll")
  5: Import("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\Dither\dither.avsi")
  6: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\Dither\dither.dll")
  7: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\EEDI2\EEDI2.dll")
  8: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\EEDI3\eedi3.dll")
  9: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\JPSDR\Plugins_JPSDR.dll")
 10: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\masktools2\masktools2.dll")
 11: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\mvtools2\mvtools2.dll")
 12: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\RgTools\RgTools.dll")
 13: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\TDeint\TDeint.dll")
 14: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\vinverse\vinverse.dll")
 15: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\yadifmod2\yadifmod2.dll")
 16: Import("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi")
 17: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\FFT3DFilter\fft3dfilter.dll")
 18: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\Dual\FFT3D Neo\neo-fft3d.dll")
 19: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\TMM2\TMM2.dll")
 20: LoadPlugin("D:\Estudio_grabacion\StaxRip\Apps\Plugins\Dual\ffms2\ffms2.dll")
 21: Import("D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi")
 22: tcFile = "E:\Navidad_temp\Navidad_timestamps.txt" # timestamps file path
 23: Exist(tcFile) ? FFVideoSource("E:\Navidad.avi", cachefile="E:\Navidad_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("E:\Navidad.avi", cachefile="E:\Navidad_temp\temp.ffindex")
 24: ConvertToYUV420()
 25: QTGMC(preset="Placebo", InputType=0, sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8, AssumeBFF())

**Comment by Dendraspis** [comment]
I got almost the same code, but for me `.\Apps\Plugins\AVS\NNEDI3CL\nnedi3cl.dll` is also included.
Not sure why, could also be source file or system related.

**Comment by John3d** [comment]
Is there anything else I can do to help find the problem?

**Comment by Dendraspis** [comment]
1. What GPU is installed ?
2. Did you update any scripts/plugins/tools by your own?

**Comment by Dendraspis** [comment]
You have to put the "original" one back - the one that came with StaxRip. 
And what error message do you get then?

**Comment by John3d** [comment]
> You have to put the "original" one back - the one that came with StaxRip. And what error message do you get then?

I have started from 0
- Downloaded and unzipped StaxRip v2.42.0
- Upgraded to StaxRip v2.42.1 [Update] (only replaced StaxRip.exe and StaxRip.pdb)
- I have configured : Field - Deinterlace - QTGMC - QTGMD... - Placebo - Interlaced
- I have opened the video file and the same error appears:
Script Error

System exception - Illegal Instruction
(D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 1056)
(D:\Estudio_grabacion\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi, line 850)
(D:\Estudio_grabacion\How to Capture SD Video in VirtualDub2, Deinterlace in StaxRip, and Upscale to HD in Topaz Video AI.f136_temp\How to Capture SD Video in VirtualDub2, Deinterlace in StaxRip, and Upscale to HD in Topaz Video AI.f136.avs, line 24)

![Sin título](https://github.com/user-attachments/assets/d742dd2b-f9b5-4540-9642-7cf991dc521e)

**Comment by Dendraspis** [comment]
Okay, no wonder: your source is already progressive, not interlaced! No need to use QTGMC on that source file...

**Comment by John3d** [comment]
> Okay, no wonder: your source is already progressive, not interlaced! No need to use QTGMC on that source file...

You're right, I had taken another video to test...

Now with the interlaced video:

![Sin título](https://github.com/user-attachments/assets/8fdfde4b-87a0-491e-b1bc-772e54590dd0)

[Navidad_staxrip.log](https://github.com/user-attachments/files/17555038/Navidad_staxrip.log)

**Comment by Dendraspis** [comment]
It must have something to do with the missing loading of `.\Apps\Plugins\AVS\NNEDI3CL\nnedi3cl.dll`. Don't know why it does not work for you, maybe a source, driver or runtime file issue. You can try to import to load it manually and see what happens.

I don't think I can give you more help than that.  😕

**Comment by John3d** [comment]
I notice that unlike yesterday, today it loads the plugin but the error still appears:
![Sin título](https://github.com/user-attachments/assets/267c4afa-6b0c-4b27-b3b5-ee26ae590491)

I have made another test that I don't know if it will be useful, I have chosen this plugin:
Field - Deinterlace - NNEDI3
and another error appears:
![Sin título-2](https://github.com/user-attachments/assets/55aaf2b7-9c63-459f-8026-4c6b57981d6c)

I have tried other plugins for deinterlace and no errors (although I have not processed the video).

**Comment by Dendraspis** [comment]
It should have something to do with your source file.
Can you create a ~10s short sample out of your source file and share it with me?

**Comment by Dendraspis** [comment]
So it has to be your system.

You may want to check if *OpenCL* is activated/available on your system/GPU and the right drivers are installed. It could also help to read and install this one:
https://github.com/staxrip/staxrip/wiki/Intel-OpenCL-drivers-could-be-required-for-some-processors-(Xeon%2C-...)-to-run-some-filters-(KNLMeansCL%2C-QTGMC%2C-...)


<img width=600 src=https://github.com/user-attachments/assets/1ccb15ee-f21f-40fe-8f75-a3dc23df4eea>

```
 ....
 22: Import("D:\Code\Github\staxrip\staxrip\Source\bin\Apps\Plugins\AVS\QTGMC\QTGMC.avsi")
 23: tcFile = "A:\_StaxRip-Test\Test.avi_temp\Test_timestamps.txt" # timestamps file path
 24: Exist(tcFile) ? FFVideoSource("A:\_StaxRip-Test\Test.avi", cachefile="A:\_StaxRip-Test\Test.avi_temp\temp.ffindex", timecodes=tcFile) : FFVideoSource("A:\_StaxRip-Test\Test.avi", cachefile="A:\_StaxRip-Test\Test.avi_temp\temp.ffindex")
 25: ConvertToYUV420()
 26: QTGMC(preset="Placebo", InputType=0, sourceMatch=3, sharpness=0.2, tr2=2, ediThreads=8)
```

**Comment by tascani11** [comment]
Hi, sorry to jump in here but I think I know what's your issue..
It has to do with the JPSDR plugin pack and your AMD FX series chip which can handle AVX but not AVX2.

Therefore:
- Download the latest plugins_JPSDR_v3_3_5.7z  from:  https://github.com/jpsdr/plugins_JPSDR/releases/tag/3.3.5
- Unzip and look in x64 folder for the "Release_W7_AVX" version.
(that's the one you need, as StaxRip comes default with AVX2 version).
- Replace that in StaxRip > Apps > Plugins > AVS > JPSDR

That should do it!!

**Comment by Dendraspis** [comment]
Ohhh, soooo obvious! 🤦‍♂️
Haven't noticed the old CPU and yes, that should be checked first. 

Thanks for pointing on that and also for the instruction to fix it!

**Comment by John3d** [comment]
That's right, I have done it and it doesn't seem to be an error anymore.
Thank you both for your help and sorry for the inconvenience.

**Comment by tascani11** [comment]
You're welcome, Dendraspis & John3d.. Glad it's working now..
Keep up the good work with this great App!!
