### ISSUE TITLE
Filters for adjusting TV/PC levels

### ISSUE THREAD

**Issue by Binjohn** [staxrip/staxrip#152]
In AviSynth filter profiles, the filter chosen for adjusting TV/PC level is `Levels()`, but I think we should use `ColorYUV(levels="<type>")` for correctness.

According to [AviSynth wiki of Levels function](http://avisynth.nl/index.php/Levels), the two methods have some difference in chroma scaling. Is there any reason for StaxRip to use `Levels()` instead?

> \# scales a [16,235] clip to [0,255]:
> Levels(16, 1, 235, 0, 255, coring=false)  
> \# note both luma and chroma components are scaled by the same amount,
> \# so it's not exactly the same as ColorYUV(levels="TV->PC")

![Filter Profiles](https://user-images.githubusercontent.com/43265566/78289762-421ba780-7555-11ea-9dc8-cdfa22af296b.png)

**Comment by stax76** [comment]
Revan added most of the filters, I've rather limited experience and interest in filters, maybe somebody else can confirm that it should rather be changed.

**Comment by Patman86** [comment]
I think, you are right. Setting must be ColorYUV(levels="type"). 
I've changed it for myself. There are two more settings available for param levels... AviSynth wiki of ColorYUV Levels

**Comment by stax76** [comment]
Thanks guys, it's changed in version 2.1.0.4 Beta.
