### ISSUE TITLE
Macro to get the used encoder codec

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1520]
**Describe the bug**
The macro value %encoder_ext% for NVEnc AV1 = "mkv" (example source file "myvideo.mkv") but...
For NVEnc H265 the %encoder_ext% value equals "h265"

The value should be consistent either the target extension or the codec - what does the macro value %encoder_ext% represent?

If %encoder_ext% is the target extension then both should = "mkv" (example in this case) - if %encoder_ext% is the Video CODEC then all values should equal the proper codec text ("AV1", "h265",  "h264", etc..).

If %encoder_ext% is the target extension, then there should be a CODEC macro (that equals the codec text) such as %source_codec% and %target_codec% or an added %target_video_format% equivalent to the macro %source_video_format%, which seems to equal the source codec.

Or, are there existing macros that return the source and target codec values?

NVEnc AV1 
![241029 105313](https://github.com/user-attachments/assets/c3f42034-359f-4861-b359-8928690d5242)

NVEnc H265 
![241029 105214](https://github.com/user-attachments/assets/19bbf9ec-0307-4862-bd75-077218d73e49)

**Comment by Dendraspis** [comment]
`%encoder_ext%` gives you the extension of the output file, that the encoder writes. In case of `NVEncC` and H264 it's `.h264`, for H265 it's `.h265` and for AV1 it's `.mkv`.

**Comment by noblemd00** [comment]
What macro/variable gives the value (i.e. "h265, AV1, h264) of the target codec or target video format? RE: like %source_video_format% 

or how would I access a variable that will return the target codec?

**Comment by noblemd00** [comment]
I deleted my previous because I think the explanation is that "ext" is referring to the file extension of the file in the temp folder: 
i.e. "myvideo_out.h265" not the finished encoded video file: i.e. "myvideo_new.mkv"

**Comment by Dendraspis** [comment]
Yes, that is what I have written/answered.  😁 

I will add a new macro for you:   `%encoder_codec%`

**Comment by noblemd00** [comment]
> I will add a new macro for you: %encoder_codec%

Excellent thanks!

> Yes, that is what I have written/answered. 😁
> gives you the extension of the output file, that the encoder writes

Thanks for the confirmation. Wasn't sure from the reply what output file you were referring to. Only confirmed by checking the codec used versus the extensions of various output files and determining what matched the %encoder_ext% text.

**Comment by Dendraspis** [comment]
The new macro `$encoder_codec%` will be added in `v2.42.2`, that will be released within the next days...
