### ISSUE TITLE
Audio cutting fails

### ISSUE THREAD

**Issue by dustsigns** [staxrip/staxrip#1525]
**Describe the bug**
Cutting FLAC fails with the new version of mkvmerge

**Expected behavior**
Cutting should succeed (see workaround below) or use a different intermediate format. Alternatively, it should give a visible error message instead of silently falling back to the uncut audio file.

**How to reproduce the issue**

Encoding AC3 (and other!) audio tracks using eac3to, StaxRip converts it to FLAC, then creates an AVI and finally performs the cutting (see log file below). I tried it with different input files and formats and the result is always the following error message:

> Error: The track ID 0 from the file 'D:\temp\x\A1_t00_temp\ID1_[de] (German) {Stereo}.flac' cannot be split. Splitting tracks of this type is not supported.

Log file snippet: https://pastebin.com/wzeaCVz5

It seems that this is no longer supported in newer mkvmerge versions as per their [FAQs](https://gitlab.com/mbunkus/mkvtoolnix/-/wikis/Appending-&-splitting-FLAC-audio-tracks-not-supported). A potential workaround would be to use the `--engage append_and_split_flac` flag as indicated in their FAQs.

*Version*: v2.42.1 [Update]

**Comment by Dendraspis** [comment]
As far as I know `mkvmerge` was never able to cut FLACs.

In your case to solve the issue the `Decoder` should be set to `Automatic` - I guess you have set it to `eac3to` as that was the only way I could reproduce it.

![image](https://github.com/user-attachments/assets/f808f009-f701-4025-9efd-f1b1f87f0a79)

**Comment by dustsigns** [comment]
Yes, I set the decoder and encoder to eac3to. Thank you for pointing out the workaround using the "Automatic" decoder.

However, I still consider it a bug that StaxRip silently ignores the error of eac3to and - without even a warning - continues to encode and mux the uncut audio. It would be nice to let the user know that the cutting failed - otherwise, they might be surprised (like me) to find an hours-long audio track in a minutes-long video in the end result.

**Comment by Dendraspis** [comment]
This is why I have added the bug label.  😁

Haven't checked it in detail yet but it will definitely take some time to modify it.

**Comment by Dendraspis** [comment]
Should be done with `v2.44.1`. If there is still an issue, please re-open this issue....
