### ISSUE TITLE
StaxRip crashes when x264 warns on `VBV underflow`

### ISSUE THREAD

**Issue by Didas-git** [staxrip/staxrip#1527]
**Describe the bug**
When using x264 to encode video and explicitly setting vbv buffer sizes, if x264 throws underflow warnings about staxrip just becomes unresponsive and ends up crashing, the "worst" part about this is that after crashing the x264 encoder keeps running in the background (to some extend i guess thats expected because vbv underflow is not a critical error)

**Expected behavior**
I would expect StaxRip to just keep working instead of becoming unresponsive.

**How to reproduce the issue**

Set a high vbv bufsize with a high crf (high compression with high buffer)

**Provide information**

- Used StaxRip version: v2.42.1

**Comment by Dendraspis** [comment]
Please provide the log file from a failed encode. I cannot force any issues and the description "high" is way to imprecise and subjective.

**Comment by Didas-git** [comment]
I tried to find a log file but due to the way staxrip crashed (or should i say, forced to close by windows) it did not generate any log files.
On the other hand i have been trying to reproduce the error but even using the exact same video and config as before i simply do not get vbv underflow errors anymore which to me is weird to say the least
