### ISSUE TITLE
Problem with playing video iOS device 

### ISSUE THREAD

**Issue by neptune84x** [staxrip/staxrip#1530]
Hello everyone. I get iPod video output with mp4box. There is more than one track of audio and subtitles in my video. My problem is that my iOS device starts playing on two sounds at the same time. (English and German). This is because one of the sounds of iOS must be marked as the default "Yes" and the others must be marked with the default "No". Marking all tracks as default causes the same problem. In ffmpeg, this problem can be solved with "-disposition 0". Can an improvement be made for this in mp4box? Or I wonder if there is a command similar to this command for mp4box. Thank you.

**Comment by Dendraspis** [comment]
Basically this should be doable via the `Default Track` option:

<img width=600 src=https://github.com/user-attachments/assets/4d57030c-ee12-4c3e-af04-1c00bda06190>

**Comment by neptune84x** [comment]
As I said, this doesn't solve the problem. An audio track should be marked as Default "Yes" and the others must be marked as "No". This option only says “Yes”. How should I mark the rest as the default "No". I can share more information if necessary. Marking all audio tracks as "Yes" causes the same problem.

**Comment by neptune84x** [comment]
The “Default Track” option can only be checked as “Yes”.

**Comment by Dendraspis** [comment]
Which target container?  MKV or MP4?

**Comment by neptune84x** [comment]
MP4 sir

**Comment by neptune84x** [comment]
I can share mediainfo output. Working examples and non-working examples.

**Comment by Dendraspis** [comment]
From the log file you can take the whole MP4Box command line and try to copy&paste it into a PowerShell or Command Line window, then check for the audio files in form of `filename.m4a#audio:lang=eng:name=English` and add a `:tkhd=0` to all the audio files that should **not** be *default*. Result would then be:
`filename.m4a#audio:tkhd=0:lang=eng:name=English`

MP4 as well as MP4Box behave pretty strange when it comes to default tracks as there seems to be no standard, also how default tracks are interpreted is player-related.  🙄

**Comment by neptune84x** [comment]
`C:\Apps\StaxRip\Apps\Support\MP4Box\MP4Box.exe -fps 23.976024 -add "D:\tempy\2004.mkv_temp\2004.h265#video:name=" -add "D:\tempy\2004.mkv_temp\ID1_[en] (English) SBR.aac#audio:sbr:lang=eng:name=:group=1" -add "D:\tempy\2004.mkv_temp\ID2_[tr] (Turkish) SBR.aac#audio:sbr:tkhd=0:lang=tur:name=:group=1" -add "D:\tempy\2004.mkv_temp\ID1_[en]_default.srt:lang=eng:name=:group=2" -new D:\tempy\2004_new.mp4`

**Comment by Dendraspis** [comment]
Instead of posting it here it would be great if you could execute it and check, if the result is okay.  😅

**Comment by neptune84x** [comment]
This works also without using "tkhd" command. And all Default "Yes" 

`C:\Apps\StaxRip\Apps\Support\MP4Box\MP4Box.exe -fps 23.976024 -add "D:\tempy\2004.mkv_temp\2004.h265#video:name=" -add "D:\tempy\2004.mkv_temp\ID1_[en] (English) SBR.aac#audio:sbr:lang=eng:name=:group=1" -add "D:\tempy\2004.mkv_temp\ID2_[tr] (Turkish) SBR.aac#audio:sbr:lang=tur:name=:group=1" -add "D:\tempy\2004.mkv_temp\ID1_[en]_default.srt:lang=eng:name=:group=2" -new D:\tempy\2004_new.mp4` 

I tested both my ios device and works perfectly both. 

I think it's very interesting that the default flag is not the issue. In the code above I made the subtitle group 1 while it was 2.

Results problem are group flag

**Comment by neptune84x** [comment]
My problem is solved only if I do not mark subtitles as default, thank you very much.

**Comment by neptune84x** [comment]
I think Subtitles must be  `:group=2"`
I will wait the next  release :)

**Comment by Dendraspis** [comment]
Sadly I cannot test it the way you can do.
Are you able to verify if it also works for subtitles and if `group=1` is enough or `group=2` has to be used?

**Comment by neptune84x** [comment]
There is an application I use on macOS. Its name is Subler.app In all mp4 files I created before switching to Windows, subtitle tracks are `group=2 (Alternate group : 2 in mediainfo NET)`. When I edit the command line of mp4box to `group=2` for subtitle tracks as above, they work fine again. In the default player of iphone, all audio and subtitle tracks are selectable and work fine. My iOS device iPhone SE (2022). and iOS 18.1 I tested it with multiple instances and it works.

**Comment by Dendraspis** [comment]
Here is a hotfix for you if you wanna test it:
https://ufile.io/cl05j9um
Link expires soon...

**Comment by neptune84x** [comment]
You're fantastic. Everything works perfectly. Thank you so much.


<a href="https://ibb.co/6ZKrZCr"><img src="https://i.ibb.co/FWQmWTm/image0.jpg" alt="image0" border="0"></a>
<a href="https://ibb.co/myNMDBq"><img src="https://i.ibb.co/xgFRCsj/image1.jpg" alt="image1" border="0"></a>
<a href="https://ibb.co/QF2B2fr"><img src="https://i.ibb.co/XZhBhbS/image2.jpg" alt="image2" border="0"></a>

**Comment by Dendraspis** [comment]
That's great, thanks for the feedback.

Fix will be available in `v2.42.4`...
