### ISSUE TITLE
Subtitle disappears during jump when playing mp4 file in LG webOS

### ISSUE THREAD

**Issue by neptune84x** [staxrip/staxrip#1535]
Hello it's me again :)

I play the mp4 video I muxed with mp4box on lg tv webos. When I fast skip or skip to a certain part of the video while playing, the subtitles disappear.

After some research, I discovered a command that solves the problem. 

`-tight` command

I would really like to see this added to StaxRip (or as an optional option). Thank you:

**Comment by Dendraspis** [comment]
And why don't you add it via the `Additional custom switches` ?

**Comment by Dendraspis** [comment]
But you know, that you can add it for yourself to the list, right?

**Comment by neptune84x** [comment]
> But you know, that you can add it for yourself to the list,

I know that yes :) But the last piece.

**Comment by Dendraspis** [comment]
Sure, I will add that preset as `Better Seeking" to the general presets. I was just asking because you can add it for yourself and don't hat to wait that long.

**Comment by neptune84x** [comment]
Thank you. You're the best. :)
