### ISSUE TITLE
preferred subtite

### ISSUE THREAD

**Issue by tuktukcima** [staxrip/staxrip#1537]
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).
The preferred languages is extracted in %working_dir% 
Is there a way to add it automatically?
 i try use this but not work
```
[Subs]
ASS/SSA/SRT =
    for file in os.listdir(r"%working_dir%\"):
        if file.endswith((".ass", ".ssa", ".srt")):
            ass = os.path.join(r"%working_dir%\", file)
    clip = core.assrender.TextSub(clip, ass, fontdir=r"%working_dir%\")
```

**Comment by Dendraspis** [comment]
No need to ask in multiple issues....

You can put this code to the filter profiles, so you can use it as preset.
Or you can simple put/paste it into a filter, but without `[Subs]`.

If you have problems doing that I would recommend giving more/enough details about your problem.

**Comment by tuktukcima** [comment]
![image](https://github.com/user-attachments/assets/6e18025d-2a89-40f1-8f67-c74fa0293681)
The translation is extracted into the file "%working_dir%\"

![image](https://github.com/user-attachments/assets/ff4a30cb-4822-4c61-8e44-beac17185084)
I put it like this
Nothing happens and no translation is added.

**Comment by tuktukcima** [comment]
Sorry, I think if you reach a solution, we will use another method to add the translation automatically.
![image](https://github.com/user-attachments/assets/7242f706-20db-4d92-ba6c-ad6290254daa)
How do I change the name of the extracted translation to a fixed name, for example, the file name?

**Comment by Dendraspis** [comment]
Just to make it clear:
You want to hardcode / burn-in the subtitle, right ?

**Comment by Dendraspis** [comment]
Ah, my bad:
You're in the profiles for `AviSynth`, but the code is for `VapourSynth`, so you have to switch over to `VapourSynth` first and then paste the code there.

Afterwards you can add the filter via:
<img width=400 src=https://github.com/user-attachments/assets/841747c1-ddbf-4d98-80a1-2907251dd90b>

...or you paste it directly in via the Code Editor like mentioned before.

> Can you tell me how to change the name of the extracted translation to the name of the file?

Not even sure what you mean.  But you can preview the code via right-click.

**Comment by tuktukcima** [comment]
![image](https://github.com/user-attachments/assets/397d1762-4ade-4888-ba94-f6c9162c5f1c)
When extracting subtitle by mkvextract 
![image](https://github.com/user-attachments/assets/8717ce3f-689d-4f3e-8edf-4b312264ba4c)
This is the name of the translation. Can it be extracted with a custom name? like english.srt no id7_[ar}

**Comment by Dendraspis** [comment]
No, those are specific file names so StaxRip can use them for further usage.
Whatever you want to do, you have to do it by hand or with help of a self-written script that you call after file opening.
