### ISSUE TITLE
Setting 'High Tier' to 'Yes' or 'No' in x265 profiles overwrites VBV values when source loaded

### ISSUE THREAD

**Issue by yammes08** [staxrip/staxrip#1539]
**Describe the bug**
When using an x265 video encoder profile with 'High Tier' set to 'Yes' or 'No', allowable VBV rate limits are overwritten with the tier's maximum values instead.

**Expected behavior**
Manually entered VBV rate limits are respected so long as they are within limits.

**How to reproduce the issue**
1. Create a test x265 profile in 2-pass mode, level 5.1, and High Tier set to No
2. Set the bitrate to eg 18000
3. Set VBV-maxrate to eg 32000
4. Set VBV-bufsize to eg 40000
5. Save the profile, and activate it
6. Open a source file
7. Click 'Options' for your test x265 profile
8. Observe that the VBV settings are both set to 40000, the max value for a non-High tier file

You can repeat this with High Tier set to Yes and observe the values are overwritten to 160000 instead.

**Provide information**
- Used StaxRip version: 2.41.7 and 2.42.2

**Comment by Dendraspis** [comment]
Is it possible you're using old settings from `v2.41.7` or prior?
