### ISSUE TITLE
HELP light problem at nvenc

### ISSUE THREAD

**Issue by YinnVI** [staxrip/staxrip#154]
When i try to encode with NVENC the results of the light are different from QSVENC it appears darker in NVENC, 

How do i make it as bright as in QSVENC? PLEASE HELP

![ASLI](https://user-images.githubusercontent.com/26527969/78537894-61972680-781a-11ea-916b-11b0e34bc51e.jpg)
Original file without being encoded
-----------
![NORMAL](https://user-images.githubusercontent.com/26527969/78537293-7626ef00-7819-11ea-9891-13423feb4b16.jpg)
This QSVENC
-----------
![NOUK](https://user-images.githubusercontent.com/26527969/78537368-9a82cb80-7819-11ea-88f8-1ccb36ea5ae9.jpg)
And THis NVENC
-----------
How do i make it as bright as in QSVENC? PLEASE HELP

Sorry my english bad

**Comment by Patman86** [comment]
Have you found a solution?
