### ISSUE TITLE
Dolby Vision VBV Warning Message

### ISSUE THREAD

**Issue by neptune84x** [staxrip/staxrip#1541]
StaxRip
Hi, I get the following error when encoding Dolby Vision with StaxRip. 

I did vbv 160000 as in #1203 but I got the following error.

I wish StaxRip would fill in these settings for us.

The video I used for the test: 
https://www.demolandia.ovh/downloads/dolby-vision/dolby-vision-amaze-(dolby-vision)-(www.demolandia.net).mp4

```
x265 4.0+4+4-b267772b2-[Mod-by-Patman]-x64-avx2-msvc1940

C:\Applications\StaxRip\Apps\Encoders\x265\x265.exe --reader-options library=C:\Applications\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll --crf 20 --output-depth 10 --vbv-bufsize 160000 --vbv-maxrate 160000 --dolby-vision-profile 8.1 --dolby-vision-rpu C:\Users\neptu\Desktop\Db.mp4_temp\HDRDVmetadata.rpu --output C:\Users\neptu\Desktop\Db.mp4_temp\Db_out.hevc --input C:\Users\neptu\Desktop\Db.mp4_temp\Db.avs

avs+ [INFO]: using external Avisynth library from: "C:\Applications\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll" 
avs+ [INFO]: AviSynth+ 3.7.3 (r4003, 3.7, x86_64)
avs+ [INFO]: 3840x2160 fps 60/1 i420p10 frames 0 - 3371 of 3372
raw  [INFO]: output file: C:\Users\neptu\Desktop\Db.mp4_temp\Db_out.hevc
x265 [INFO]: HEVC encoder version 4.0+4+4-b267772b2 [Mod by Patman]
x265 [INFO]: build info [Windows][MSVC 1940][64 bit] 10bit
x265 [INFO]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [FLAW]: Dolby Vision profile - 8.1 requires Mastering display color volume information
x265 [FLAW]: x265_encoder_open() failed for Enc, 
x265 [FLAW]: Failure generating stream headers in x265

```

**Comment by Dendraspis** [comment]
This has nothing to do with VBV settings at all.

Your source file is an SDR video with Dolby Vision Profile 5 metadata, so there is actually nothing to use for the Profile 8.1 you have selected and you have to fill in everything by hand.

If you want to try to preserve the original *type* with Profile 5, you have to use Profile 5 instead and that should be enough as far as I remember.  🤔

**Comment by Dendraspis** [comment]
Did it help in any way to solve your issue?  😅

**Comment by neptune84x** [comment]
Yes, my problem is solved, thank you.

**Comment by Dendraspis** [comment]
Great!  
Would be nice if you could give me a short feedback and/or close the issue next time when it's completed.  😊 

So I'm closing it now...
