### ISSUE TITLE
Project file failed to load

### ISSUE THREAD

**Issue by filyse** [staxrip/staxrip#1542]
Project file failed to load

Отказано в доступе по пути "C:\Users\filys\Desktop\StaxRip-v2.42.0-x64\Templates\720p.srip".

It will be reset to defaults.

C:\Users\filys\Desktop\StaxRip-v2.42.0-x64\Templates\720p.srip

System.UnauthorizedAccessException: Отказано в доступе по пути "C:\Users\filys\Desktop\StaxRip-v2.42.0-x64\Templates\720p.srip".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   в System.IO.FileStream..ctor(String path, FileMode mode)
   в StaxRip.SafeSerialization.Deserialize[T](T instance, String path) в D:\Code\Github\staxrip\staxrip\Source\General\General.vb:строка 312
   в StaxRip.MainForm.OpenProject(String path, Boolean saveCurrent) в D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:строка 1608

**Comment by Dendraspis** [comment]
Either you have not enough permissions or it's not the right file. The location is also not the default location, so I guess you have copied it over from an old version which is not a good thing to do, especially with this release.  🤔

**Comment by filyse** [comment]
he writes the same thing in the old version now after the update.

**Comment by Dendraspis** [comment]
Make sure you have the permissions to read and write that file and that you have chosen the right file - the locations says that something is wrong.

Otherwise I can't help because of missing information.

**Comment by filyse** [comment]
so as not to create new topics. I'll ask a question right here. I can open it directly via a .bat template. But how can I drag and drop a file there and have it open?

```
@echo off
cd "C:\Users\filys\Desktop\Reaper\StaxRip"
start StaxRip.exe "C:\Users\filys\Desktop\Reaper\StaxRip\Settings\Templates\400p.srip"
```

I tried it this way but it gives me an error "-i"

```
set inputFile=%~1
start "" "C:\Users\filys\Desktop\Reaper\StaxRip\StaxRip.exe" -i "%inputFile%" "C:\Users\filys\Desktop\Reaper\StaxRip\Settings\Templates\720p.srip"
```

**Comment by Dendraspis** [comment]
Take a look at https://github.com/staxrip/staxrip/wiki/Command-Line-Interface
