### ISSUE TITLE
New x265 v4.1 encoder does not support “--pme”

### ISSUE THREAD

**Issue by Victory61** [staxrip/staxrip#1544]
Good morning.
In the new StaxRip encoder “x265-4.1+54+9-0c07fe364-.Mod-by-Patman.-x64-avx512-msvc1942”
Parallel motion estimation is no longer supported. Do I need to set some other parameter or is it sufficient to simply disable it?
Thanks 

![Screenshot (1372)](https://github.com/user-attachments/assets/e322ec53-4d02-47ab-bdee-d935f64f0e42)

![Immagine 2024-12-05 072816](https://github.com/user-attachments/assets/4383c43c-bd76-4aa9-bcb0-8962676de348)

**Comment by Dendraspis** [comment]
First it's not a *StaxRip encoder*, but a modified native encoder, that is used by StaxRip.

Thanks for pointing that out. The Release Notes don't mention that and even the CLI help still shows them without any annotation.  🙄 

I will remove it for the next release.

And yes, it's just enough for you to disable that option so the parameter will be removed from the command line argument.

**Comment by Victory61** [comment]
Thanks for the confirmation, possibly I can use the native version for StaxRip and wait for future updates.

**Comment by Dendraspis** [comment]
v4.1 feels even more buggy/incomplete, but apart from that there is no reason to use the old version. Use the latest one and just don't set that parameter.

**Comment by Victory61** [comment]
Thank you for the confirmation.

**Comment by Dendraspis** [comment]
Will be implemented in `v2.44.0`...

**Comment by Victory61** [comment]
Great, I will wait for the release.
Thank you

**Comment by Dendraspis** [comment]
Not sure exactly when, but definitely this year.  😅 

Nevertheless a very minor fix as it also works without issues as long as you don't change those two parameters.
Way worse:  there are other issues with `x265` .... but they will also be fixed.
