### ISSUE TITLE
Ability to set temporary folder location

### ISSUE THREAD

**Issue by igorbaryshev** [staxrip/staxrip#1545]
Could be very useful to be able to set a custom path for temporary files.
Would speed things up when, say, the source files are located on an HDD or a slow SSD, and the temp folder is on a separate faster SSD or even some large RAMDisk (for reduced SSD wear).

**Comment by igorbaryshev** [comment]
Found out that I can set temp folder for the project, even though can't set it by default.
So, I just made a template project that with custom folder set.

**Comment by Dendraspis** [comment]
Of course you can, you just have to set it for the startup template. So if you're still using the default `Automatic Workflow`, set the temp dir you want to use, save it as a new template and set it as startup template.
