### ISSUE TITLE
can i transfer a file from mp4 to mp3 using StaxRip ?

### ISSUE THREAD

**Issue by LouayHanouche** [staxrip/staxrip#1547]
seems that ffmpeg can do that but didnt find an option , is there an option for this ?

**Comment by Dendraspis** [comment]
MP4 is usually a video container, but MP3 is an audio file, so what do you want to be?

**Comment by LouayHanouche** [comment]
i want to be able to either convert it to mp3 or extract the audio from the mp4 , so at the end ill have an mp3 file with the mp4 audio :)

**Comment by Dendraspis** [comment]
Yes, you can do it. But in case you just want the audio tracks to be extracted and/or converted to mp3, I would think about using an ffmpeg GUI or so, which might be better for your needs. StaxRip is primary a video encoding GUI. But when you already use it and just want to create the mp3's from time to time or while the video file is already open, why not...

**Comment by LouayHanouche** [comment]
Hmm i see soo how can i do it?

**Comment by Dendraspis** [comment]
Just open the video file as usual and choose the audio track you want and the corresponding mp3 profile and finally right-click on the text field (with the audio file path) and click on `Execute`.
