### ISSUE TITLE
QTGMC At Parallel Desktop

### ISSUE THREAD

**Issue by Sincere4f** [staxrip/staxrip#1550]
**Describe the bug**
Platform Error

**Expected behavior**
Plugin dll Library.

Hi Sir
at the first thank you very very much for this software

i use this app with no problem on windows pc
but my pc is very slow and old
i have mac mini m1 with macos 15.0.1
i use parallel desktop to run windows 11 ARM on macos
StaxRip 2.42.2 has error when use QTGMC Filter
and this is the error message

```
Script Error

Cannot load file 'C:/StaxRip-v2.42.2-x64_SF/Apps/Plugins/AVS/JPSDR/Plugins_JPSDR.dll'. Platform returned code 1114:
A dynamic link library (DLL) initialization routine failed.

(W:\00-Familiary 2023\00-To Crop\Lamyiaa.mp4_temp\Lamyiaa_new.avs, line 8)
```

Please help me to fix this error
![Screenshot 2024-12-11 at 1 01 24 PM](https://github.com/user-attachments/assets/9191c068-766e-4b00-868f-9b5cf0bd44fc)

**Comment by Dendraspis** [comment]
The solution would be to check all dependencies and check, if they work on ARM and if there is an alternative - in most cases there is not an alternative. Some plugins like QTGMC have so many dependencies, that also have many dependencies, that it could be pretty difficult to found out the culprit.

But there is also a high chance, that it's GPU driver related or you're missing DirectX, VS runtimes, or something like that. I would start with that first, if you haven't checked it yet.
