### ISSUE TITLE
Staxrip v2.44  crash (Script Error : Core plugin autoloading failed)

### ISSUE THREAD

**Issue by strati64** [staxrip/staxrip#1554]
**Describe the bug**
I have update my staxrip to the last version : StaxRip v2.44
When I launch an encoding, this message appears and removes the encoding phase.

```
Script Error

Core plugin autoloading failed. Installation is broken?
```
Downgrade to 2.42.2 backup work !

deezy.exe seems to have a problem while replacing a file for downgrade: (Error 0x8007007A ). A reboot of computer is necessary to erase this file.

**Expected behavior**
A bug fix ?

**How to reproduce the issue**

With all video file source.

When I launch an encoding, this message appears and removes the encoding phase.

**Provide information**

```
Script Error

Core plugin autoloading failed. Installation is broken?
```

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version :  v2.44

**Comment by Dendraspis** [comment]
Looks like theog file is necessary.

**Comment by strati64** [comment]
> Looks like the log file is necessary.

[Wistoria Wand and Sword S01E01 MULTi 1080p WEB x264 AAC -Tsundere-Raws (CR) [H.265 AAC]_staxrip.log](https://github.com/user-attachments/files/18213003/Wistoria.Wand.and.Sword.S01E01.MULTi.1080p.WEB.x264.AAC.-Tsundere-Raws.CR.H.265.AAC._staxrip.log)

**Comment by Dendraspis** [comment]
Is it possible you have extracted the archive into the existing folder while overwriting the existing files?

This is also why there is a big box at the very top of the release that reminds you to start with fresh settings and templates.  😉
