### ISSUE TITLE
Cutting

### ISSUE THREAD

**Issue by legosoff** [staxrip/staxrip#1558]
https://radikal.host/i/oqClM1

Have you not fixed it again?

**Comment by legosoff** [comment]
CAST
We don't need

**Comment by legosoff** [comment]
I'm using the reverse version StaxRip-v2.36.0-x64

**Comment by Dendraspis** [comment]
There is nothing to fix. If you want a broken result, then use the old version.

**Comment by legosoff** [comment]
It's not a big deal StaxRip-v2.36.0 everything is working fine. I just replaced the codecs version and that's it.

**Comment by Dendraspis** [comment]
You simply don't understand what's going on, but when you're happy with your broken result....

**Comment by legosoff** [comment]
The translator must have made some kind of mistake. 
When RPU to put, нe cannot continue the special cut because of the RPU interference.

**Comment by legosoff** [comment]
StaxRip-v2.36.0 rpu+h265, audio and subtitles сut everything is fine.
 StaxRip-v2.44.0 rpu+h265, audio and subtitles сut error

**Comment by Dendraspis** [comment]
"everything is fine" is wrong! StaxRip lets you do it, but the result is broken! You cannot cut Dolby Vision metadata.

**Comment by legosoff** [comment]
I've already checked, RPU He didn't touch anything cut, it's a full whole size 22,3 MB, there are no losses. I have already extracted it to save the Dolby Vision metadata.
New version why would you touch RPU cut?
New version don't touch anything cut RPU. Then you can touch cut  h265, aac and subtitles.

**Comment by legosoff** [comment]
This is the first time you cut RPU why? Do not touch PRU.

**Comment by Dendraspis** [comment]
You should maybe find a better translator or find somebody, who can better explain what you mean.  😕 

So at the end:
When you have a source file with Dolby Vision metadata and you want the encode to keep it => you cannot cut the video.

**Comment by legosoff** [comment]
RPU 2 hour 36 minutes 55 second leave save and do not cut anything
H265 You can cut out 2 hour 30 second 21 second
Audio You can cut out  2 hour 30 second 21 second
Subtitles You can cut out  2 hour 30 second 21 second

**Comment by legosoff** [comment]
https://radikal.host/i/oqPfFK

Since I cut out the video, audio, and subtitles + rpu to create an mp4, I extracted it again, checked how the processor was working, and everything is fine now. I've already checked many times, I have an LG C4 and iOS Dolby Vision, no problems, Dolby Vision is working fine.

**Comment by legosoff** [comment]
Now you already understand. Now the next version is fixed. RPU does not touch anything cut.

**Comment by Dendraspis** [comment]
This may work, when you cut the video at the end, but otherwise it won't work.
MediaInfo showing `Dolby Vision` means nothing because it can be shifted, stretched or so.

**Comment by legosoff** [comment]
No. I have already tested everything ok many times, there is no problem. 
Video + RPU both just started reading 0:00:00 start, and at the end of the video, for example, 1:30:00, both RPU 1:30:00 also stop, there is 1:36:00 left, it will not continue.

**Comment by legosoff** [comment]
You try to test yourself to make sure that I was right.

**Comment by legosoff** [comment]
If the video has started to crop, then yes, the problem is Dolby Vision does not work correctly, blinking light and dark. 
You can сut it at the end.

**Comment by legosoff** [comment]
Mkvtoolnix allows Dolby Vision video cut.
And then there's the Blu-ray M2TS split a lot of the file,  Dolby Vision  works.
Apple TV+  split fragment  m4s  Dolby Vision.
