### ISSUE TITLE
Script Error after update

### ISSUE THREAD

**Issue by ttplayer** [staxrip/staxrip#1559]
**Describe the bug**
After unzipping the new Version into my Staxrip installation, I get an error message after opening any video file.
Working ist not possible anymore.....

Script Error

Core plugin autoloading failed. Installation is broken?

![picture](https://github.com/user-attachments/assets/3e6d758b-3328-4f5f-b010-dc297fc5778c)

**Comment by Dendraspis** [comment]
Please check out #1554 

**TL;DR**: Never overwrite existing instances.

**Comment by ttplayer** [comment]
Sorry, it was my fault.
After a clean installation, all seems fine. -(

**Comment by Dendraspis** [comment]
Great, so I can close this issue.  Have fun.
