### ISSUE TITLE
StaxRip crash with DSS2 Source Filter and QTGMC

### ISSUE THREAD

**Issue by dchmayer** [staxrip/staxrip#1563]
**Describe the bug**
When I am using DSS2 source filter and add QTGMC with preset "very slow" or "placebo" and interlanced input, StaxRip crashes when opening my AVI file. However, it is possible to disable QTGMC load the AVI file first and activate QTGMC when loaded, which also results in the same crash. 
It works if I convert to YV12 color before using QTGMC filter though.

I attached the StaxRip preset, Windows Event logs of the crash, MediaInfo of the input AVI file and systeminformation.

I am trying to use DSS2 in the first place because the AVI file contains dropped frames (indicated by VirtualDub) and indexing with FFVideoSource seems to ignore those frames when indexing, resulting in a shorter video file and audio constantly being out of sync by around 2 seconds (video ahead of audio).
DSS2 does however duplicate the frame before the dropped ones and the output file has exactly the same count of frames as the input file (I tested this with no filters, just decode and encode).

I hope I included all necessary information and would appreciate any help.
Sorry for my english, I am german native speaker...

**Expected behavior**
Should not crash.

**How to reproduce the issue**
1. Open StaxRip
2. Select DSS2
3. Select QTGMC Placebo Interlanced
4. Open AVI file

OR

1. Open StaxRip
2. Load provided preset
3. Open AVI file

**Provide information**
StaxRip Version 2.44.0
LAVFilters Version 0.79.2
Windows 10 Pro 23H2 2009 (22621.1.amd64fre.ni_release.220506-1250)

Input AVI file:
VHS capture generated by VirtualDub v2.1.3.667 with Hauppauge USB-Live2 capture card.
MediaInfo of the file attached.
Side Note: The Input AVI file reads "progressive" in MediaInfo but is actually interlanced.

Output encoder: ffmpeg FFV1 with custom flag "-level 3"
Output container: ffmpeg mkv

Hardware:
Intel(R) Core(TM) i9-14900K
NVIDIA GeForce RTX 4070 SUPER
32GB RAM

Windows Event Log, StaxRip preset, MediaInfo AVI file, System information by Windows: 
[Debug.zip](https://github.com/user-attachments/files/18231485/Debug.zip)

I already tried running these commands to fix the dll file:
sfc /scannow
dism /Online /Cleanup-Image /ScanHealth
chkdsk /f

I also tried re-downloading and decompressing StaxRip.

**Comment by Dendraspis** [comment]
I don't have experience with DSS2 , but let's try to find the culprit.
The project log file would also be helpful, but regarding the issue I guess it won't be complete.

First: What do you mean by "crash"? Does it close itself, is the an error message or is it a freeze, where you get a "not responding" message?

Are you able to create a 10s sample file out of your source file to test it and maybe share it with me?
Your source file is huge, especially for an AVI file...

> Sorry for my english, I am german native speaker...

Better than mine / me too.  😅

**Comment by dchmayer** [comment]
Here I have uploaded the logfile: 
[Sample_staxrip.log](https://github.com/user-attachments/files/18242618/Sample_staxrip.log)

Due to the size even of s sample it is uploaded to my GDrive: https://drive.google.com/file/d/1bAygicb97JLmmL-KTHpz1g4QIrnRhMs8/view?usp=sharing

With crash I mean the program loads for five seconds and then closes without anything.
The only trace of a problem is the windows event log indicating the ntdll.dll file is the faulty module causing StaxRip.exe to terminate.
![grafik](https://github.com/user-attachments/assets/b32bc264-59a5-4713-ac7b-3a22dc8b0835)

**Comment by Dendraspis** [comment]
First, let's note, that `LWLibavVideoSource` seems to handle the source file very well:
<img width=300 src=https://github.com/user-attachments/assets/d58694d0-83bf-4fb3-8d81-120bc1fc9fdc>

...and it should be definitely preferred over `DSS2`, which is about 10 years old and not maintained anymore.

The preview is very smooth and I guess this will solve your issues.

**Comment by dchmayer** [comment]
I tested LWLibavVideoSource and it also went out of sync with the audio, however I found the configuration for FFVideoSource to output constant 25 fps to stay in sync with the audio...it was simply adding "fpsnum=25, fpsden=1" to the options of the filter.
So this seems to work for my situation and I will probably use FFVideoSource if there are no problems with it?

Regarding the DSS2 source I guess there is something wrong with the output which leads to crashing QTGMC, but this belongs into other issues, not here...

Thank you for all your work @Dendraspis !

**Comment by Dendraspis** [comment]
> it was simply adding "fpsnum=25, fpsden=1"

Totally forgot that this is also an option.  😂  🤦‍♂️  
Glad you have figured it out by yourself.  👍 

> So this seems to work for my situation and I will probably use FFVideoSource if there are no problems with it?

Definitely! I guess it works so good because the frame rate of the video file is `Variable` without having timestamps, so that might confuse the source filters. So fixing the frame rate to `25` is a good solution.

You're welcome, have fun and thanks for the feedback!
