### ISSUE TITLE
Crash with ffmpeg encoders and Vapoursynth

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [staxrip/staxrip#1566]
**Describe the bug**
As the title suggests, using any ffmpeg encoder (be it x265, vp9 or ffv1 etc.) alongside vs filters crashes staxrip, even with only the source filter on.

**Expected behavior**
Not crash I guess haha

**How to reproduce the issue**
- Using VS filter setup
- Source filter on Auto
- Encoder ffmpeg -> FFV1

**Provide information**
Using Staxrip v2.44 w/ a fresh profile
Had previously 0 issues with v2.42.2

I did basic troubleshooting of course; from downgrading to an older vapoursynth version, to trying a different [ffmpeg](https://jeremylee.sh/bins/) binary, but unfortunately the issue still persists..

Here's the relevant part of the error code:

```
[vapoursynth @ 000002405a3775c0] Could not open VSScript.dll. Check VapourSynth installation.
[in#0 @ 000002405a351c80] Error opening input: Generic error in an external library
Error opening input file **redacted**
Error opening input files: Generic error in an external library

Video encoding FFV1 returned exit code: -542398533 (0xDFABA7BB)
```

Thank you!

**Comment by Dendraspis** [comment]
You could try to download the old [v2.42.0](https://github.com/staxrip/staxrip/releases/tag/v2.42.0) and replace `.\Apps\FrameServer\AviSynth\ffmpeg.exe` with the old one which should solve the issue.
Can you confirm, that it works?

**Comment by DestroyTargetNonBasicLand** [comment]
Yep, works like a charm! Can't believe I didn't think of that lol

**Comment by Dendraspis** [comment]
Great, thanks for the feedback, so I will fix that for the next release.  😊👍
