### ISSUE TITLE
hardcoding an .ass sub doesn't work

### ISSUE THREAD

**Issue by ahmedflix25** [staxrip/staxrip#159]
i Ctrl+H to add ass file to hardcode it into the video but after it finish no thing change in the video

**How to reproduce the issue**
```
Format                      : Matroska
Format version              : Version 4
File size                   : 141 MiB
Duration                    : 25 min 7 s
Overall bit rate            : 787 kb/s
Encoded date                : UTC 2020-04-09 15:58:30
Writing application         : mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
Writing library             : libebml v1.3.10 + libmatroska v1.5.2 / Lavf57.83.100

Video
ID                          : 1
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main 10@L4.1@Main
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 25 min 7 s
Bit rate                    : 658 kb/s
Width                       : 1 888 pixels
Height                      : 1 056 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.014
Stream size                 : 118 MiB (84%)
Writing library             : Lavc57.107.100 hevc_nvenc
Default                     : Yes
Forced                      : No

Audio
ID                          : 2
Format                      : Opus
Codec ID                    : A_OPUS
Duration                    : 25 min 7 s
Bit rate                    : 126 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 48.0 kHz
Frame rate                  : 50.001 FPS (960 SPF)
Compression mode            : Lossy
Stream size                 : 22.6 MiB (16%)
Writing library             : Lavc57.107.100 libopus
Language                    : Japanese
Default                     : Yes
Forced                      : No

Text
ID                          : 3
Format                      : ASS
Codec ID                    : S_TEXT/ASS
Codec ID/Info               : Advanced Sub Station Alpha
Duration                    : 25 min 0 s
Bit rate                    : 704 b/s
Count of elements           : 497
Compression mode            : Lossless
Stream size                 : 129 KiB (0%)
Language                    : Arabic
Default                     : Yes
Forced                      : No

Menu
00:00:00.000                : en:Prologue
00:01:22.040                : en:OP
00:02:52.130                : en:Part A
00:11:56.090                : en:Part B
00:23:24.820                : en:ED
00:24:55.057                : en:Preview
```

If the issue happens only under special conditions then please describe how this conditions can be reproduced:

1- Using encoder nvidia x265 and x264 normal x265 and x264
2- AviSynth and VapourSynth being used.
3- Using MKV and MP4 as containers

Hardware specs.
```
NVEncC (x64) 4.68 (r1402) by rigaya, Mar  7 2020 13:54:44 (VC 1916/Win/avx2)
OS Version     Windows 10 x64 (19603)
CPU            Intel Core i7-4790 @ 3.60GHz [TB: 3.79GHz] (4C/8T)
GPU            #0: MSI GeForce GTX 1660 (1408 cores, 1860 MHz)[PCIe2x16][445.75]
```

![Annotation 2020-04-16 062657](https://user-images.githubusercontent.com/7858946/79414586-50cd7a00-7fab-11ea-8482-d57c14561f50.png)
![Annotation 2020-04-16 062429](https://user-images.githubusercontent.com/7858946/79414593-54610100-7fab-11ea-8d2e-4fe1b712dd63.png)
![Annotation 2020-04-16 062445](https://user-images.githubusercontent.com/7858946/79414594-56c35b00-7fab-11ea-949b-8fdd5439d845.png)
![Annotation 2020-04-16 062504](https://user-images.githubusercontent.com/7858946/79414596-575bf180-7fab-11ea-88ee-14bce2e127a6.png)
![Annotation 2020-04-16 062511](https://user-images.githubusercontent.com/7858946/79414598-588d1e80-7fab-11ea-9ace-16cc153ab273.png)
![Annotation 2020-04-16 062641](https://user-images.githubusercontent.com/7858946/79414600-59be4b80-7fab-11ea-9d02-cddfa16384d3.png)
![Annotation 2020-04-16 062650](https://user-images.githubusercontent.com/7858946/79414606-5aef7880-7fab-11ea-834e-1964df7e14f9.png)

**Comment by ahmedflix25** [comment]
also there is no audio by default i had to add it manually from the container window

**Comment by 44vince44** [comment]
For the subtitles issue, did you read thread #126  ?
It was due to Python. Must uninstall all Python than clean reinstall only the one you need.

**Comment by ahmedflix25** [comment]
yes i took a look but what i got from it that i have to install python to all users which i did i will uninstall all now and reinstall 3.7.6 only

**Comment by ahmedflix25** [comment]
still the same problem

**Comment by 44vince44** [comment]
Ahmed can you please zip the .ass file and drag and drop it here.

**Comment by ahmedflix25** [comment]
sure 
[01 ID3 Arabic.zip](https://github.com/staxrip/staxrip/files/4490759/01.ID3.Arabic.zip)

https://subscene.com/subtitles/tiger-x-dragon-toradora/arabic/1244421

**Comment by 44vince44** [comment]
I checked your subtitles, and it worked, i can render, preview and hardcode those subs.
Your video is a 10bits depth video, so you have the following options:

1. use Avisynth but you need to insert a convert to 8bits filter just BEFORE the subtitles filter, because Avisynth subtitle filter only works with 8 bit depth.

2. use VapourSynth, and if you have Python and Vapoursynth properly installed after clean up all previous versions, it will work. If it stilll doesn't then something is wrong with your setup, and you can work around it by converting to 8 bits, just before the subtitle filter.

**Comment by ahmedflix25** [comment]
trying it right now

**Comment by ahmedflix25** [comment]
adding the 8bit converter filter before the subtitle one does make it work with Avisynth/VapourSynth but hardware encoders doesn't

thanks

**Comment by Patman86** [comment]
If you want to use the hardware decoder, you need to add the --vpp-subburn option

![grafik](https://user-images.githubusercontent.com/54327252/79630101-e05f5e00-814e-11ea-86b5-1dfde25c0aa6.png)

Read how to use it in help file ;)

**Comment by 44vince44** [comment]
Thanks @Patman86 Patman for showing the solution !

@ahmedflix25 The decoding encoding scheme you are applying, is an almost direct link between HW decoder and encoder. So Almost all filters of AviSynth and Vapoursynth will not work, like color correction, noise filtering, and the subtitle filter. This is why it is recommended to use AviSynth/VapourSynth decoder.

Besides, the HW decoder cannot decode all the formats that the Avisynth/Vapoursynth decoders do.
And I am surprised it can decode 10 bits... You must have a very recent nvidia chip.

**Comment by ahmedflix25** [comment]
yes, i do have gtx1660

**Comment by Patman86** [comment]
Which staxrip version do you use?

**Comment by ahmedflix25** [comment]
2.0.8.0

**Comment by Patman86** [comment]
It is caused by MP4Box 0.8.0, there is no Opus support. I created MP4Box 0.9.0 and Opus worked there, but you need to demux the audio file. Copy / Mux doesn't work, but it can be a problem with Staxrip. [Here is the link](http://www.mediafire.com/folder/vkt2ckzjvt0qf/StaxRip-Tools_by_Patman) to MP4Box 0.9.0

**Comment by Patman86** [comment]
I tested it again, demux is not necessary.
