### ISSUE TITLE
[Question] How to run 2.0.2.4 - x64 without error

### ISSUE THREAD

**Issue by samkatakouzinos** [staxrip/staxrip#16]
**Describe the bug or Issue**
Starting StaxRip from their unpacked locations gives an error of not finding the Versions.txt file under the Apps folder from where they run.

**Step To Reproduce the Problem**
1. Go to unpacked 'Staxrip.2.0.2.4.x64' folder
1. Go to either v4.7 / v4.8 folder.
1. Start StaxRip.exe
1. Main window opens.
1. Error message opens.

**Screenshots**
If possible, add screenshots to help explain your problem.

![StaxRip_2019-06-28_18-28-07](https://user-images.githubusercontent.com/1305871/60328964-b3309c00-99d2-11e9-8fb9-9961b966f698.png)

![StaxRip_2019-06-28_18-28-40](https://user-images.githubusercontent.com/1305871/60328973-b9267d00-99d2-11e9-9903-67b47ecf448d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1809 17763.592
- StaxRip Version: 2.0.2.4 - x64
- Post your Logs, There Tell contain Allot of Information that Could Help.

**Question**
Am I meant to choose one version and copy the exe and config file to the folder above?

**Comment by stax76** [comment]
Thanks for the detailed report.

> Am I meant to choose one version and copy the exe and config file to the folder above?

Yes

@Revan654 

Maybe it's better if we use 4.8 in the next build.

**Comment by Revan654** [comment]
Yes, Pick you version and Then move it to base directory next to the App folder. if you have 4.8 installed use 4.8.

4.7.2 is the standard default now, However most PC's now use 4.8 as the default Framework. Even though that will be killed off early next year with Net5.

I wonder If We could just move the Code to .NetCore and do away with all Framework. .NetCore 3 is Suppose to be Faster 5x faster then Framework now.

**Comment by stax76** [comment]
@Revan654 

I think this should be planned carefully, what if MS drops Win 7 support in .NET 5?

**Comment by Revan654** [comment]
>  this should be planned carefully, what if MS drops Win 7 support in .NET 5?

Windows 7 is already on life support. I doubt There going drop Win7 Support and go with One OS Setup for .Net5. That would be more .Net 6 or 7.

**Comment by stax76** [comment]
For now, we should stick to 4.8 I guess. I can't think of any real benefit in a port though. We don't have scaling issues, we don't have performance issues, there aren't any upcoming interesting language features or framework features. Using new tech is always exciting, I agree with that. If you want to do all the work I have no problem with a port but you should probably ask the users before.

**Comment by Revan654** [comment]
> 
> 
> For now, we should stick to 4.8 I guess. I can't think of any real benefit in a port though. We don't have scaling issues, we don't have performance issues, there aren't any upcoming interesting language features or framework features. Using new tech is always exciting, I agree with that. If you want to do all the work I have no problem with a port but you should probably ask the users before.

Might be worth look at this: https://github.com/onovotny/MSBuildSdkExtras

I came across this the other day, I usually don't may much attention to the sdk code inside the project file. This allows multi target from .netcore to .netFramework 4.8.

FYI, might consider moving to reference package from normal package file. Since Package file setup is no longer under development and being dropped in future releases.

**Comment by samkatakouzinos** [comment]
I'm happy for you to change the title to better reflect the direction of this issues conversation.
