### ISSUE TITLE
Has encoding issues with .ts files from twitter

### ISSUE THREAD

**Issue by grich99** [staxrip/staxrip#160]
**Describe the bug**
---- Error ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman ----

ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

**Expected behavior**
encode without issues

**How to reproduce the issue**
Download a .ts file with audio and try it.

**Provide information**

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

**Notes before posting**
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. 
- If you require help with one of the frame servers, tools or scripting then post in the forums rather then opening a ticket here:
  https://forum.videohelp.com
  https://forum.doom9.org
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is espeically true on the VapourSynth side, which will crash if your CPU don't support it.
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet.

**Additional context**
Add any other information or additional context that can be helpful.

**Please be as clear and as detailed as possible**

**Comment by stax76** [comment]
Maybe post the full log to pastebin or post a download link to the file. TS was always the most troublesome format.

**Comment by Patman86** [comment]
Pls switch to a more recent ffmpeg build. [Here is the link](http://www.mediafire.com/folder/vkt2ckzjvt0qf/StaxRip-Tools_by_Patman) and test remux again. I tested it with Staxrip 2.1.0.8 without problems. Or as stax mentions, share the download link / file.

**Comment by grich99** [comment]
Thanks for the reply!

.TS has not worked (for 70%) for any version of staxrip,so it isnt likely a ffmpeg build issue since this is across all builds of staxrip.

Here's the log:

-------------------------- System Environment --------------------------

StaxRip    : 2.0.6.0
Windows    : Windows 10 Pro 1903
Language   : English (Canada)
CPU        : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
GPU        : Radeon RX 570 Series
Resolution : 1680 x 1050
DPI        : 96

------------------------ MediaInfo Source File ------------------------

C:\dl\t\a.ts

General
ID                       : 1 (0x1)
Complete name            : C:\dl\t\a.ts
Format                   : MPEG-TS
File size                : 377 MiB
Duration                 : 59 min 41 s
Overall bit rate mode    : Variable
Overall bit rate         : 884 kb/s

Video
ID                       : 256 (0x100)
Menu ID                  : 1 (0x1)
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L3.1
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Codec ID                 : 27
Duration                 : 59 min 41 s
Width                    : 1 280 pixels
Height                   : 720 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Variable
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Writing library          : x264 core 159 r2991 1771b55

Audio
ID                       : 257 (0x101)
Menu ID                  : 1 (0x1)
Format                   : AAC LC
Format/Info              : Advanced Audio Codec Low Complexity
Format version           : Version 4
Muxing mode              : ADTS
Codec ID                 : 15-2
Duration                 : 59 min 41 s
Bit rate mode            : Variable
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 44.1 kHz
Frame rate               : 43.066 FPS (1024 SPF)
Compression mode         : Lossy
Delay relative to video  : -16 ms

Menu
ID                       : 4095 (0xFFF)
Menu ID                  : 1 (0x1)
Duration                 : 59 min 41 s
List                     : 258 (0x102) () / 256 (0x100) (AVC) / 257 (0x101) (AAC)

---- Error ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman ----

ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


------- ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman -------

"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "C:\dl\t\a.ts" -c copy -map 0 -ignore_unknown -sn -y -hide_banner "C:\dl\t\a_temp\a.mkv"

Input #0, mpegts, from 'C:\dl\t\a.ts':
Duration: 00:59:41.53, start: 3503.966000, bitrate: 883 kb/s
Program 1
Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720, 10 tbr, 90k tbn, 2k tbc
Stream #0:2[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 123 kb/s
[matroska @ 0000028ab5090540] Only audio, video, and subtitles are supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Last message repeated 1 times

------- ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman -------

"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "C:\dl\t\a.ts" -c copy -map 0 -ignore_unknown -sn -y -hide_banner "C:\dl\t\a_temp\a.mkv"

Input #0, mpegts, from 'C:\dl\t\a.ts':
Duration: 00:59:41.53, start: 3503.966000, bitrate: 883 kb/s
Program 1
Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720, 10 tbr, 90k tbn, 2k tbc
Stream #0:2[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 123 kb/s
[matroska @ 0000028ab5090540] Only audio, video, and subtitles are supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Last message repeated 1 times

Start:    8:07:52 PM
End:      8:07:54 PM
Duration: 00:00:02

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


------- ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman -------

"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "C:\dl\t\a.ts" -c copy -map 0 -ignore_unknown -sn -y -hide_banner "C:\dl\t\a_temp\a.mkv"

Input #0, mpegts, from 'C:\dl\t\a.ts':
Duration: 00:59:41.53, start: 3503.966000, bitrate: 883 kb/s
Program 1
Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720, 10 tbr, 90k tbn, 2k tbc
Stream #0:2[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 123 kb/s
[matroska @ 0000028ab5090540] Only audio, video, and subtitles are supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Last message repeated 1 times


   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 340
   at StaxRip.CommandLineDemuxer.Run(Project proj) in D:\Projekte\VB\staxrip\General\Demux.vb:line 195
   at StaxRip.MainForm.Demux() in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 3113
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 1967

**Comment by grich99** [comment]
I can also give you the .ts file if u need

**Comment by Patman86** [comment]
It would be great if I could do some tests on your file! I think the command line is wrong for ffmpeg. I use dsmux for ts files, so I asked if the MatroskaSplitter was installed.

**Comment by grich99** [comment]
It's going to take a long while to upload the 2 files to you, using a free
file hoster.  I cannot give you a link unless you have Internet Download
Manager and a facebook account to like a certain page.  It would be faster
than the 4-5 hours it takes for me to upload the 2 files to the file host

**Comment by grich99** [comment]
Thank you for the quick replies!
First part 2 shows links to both files using a faster file host
Second part shows my attempt to encode using the ffmpeg link provided and
subsequent error log

1)
ok nm found a faster file host:
First file:
http://www.mediafire.com/file/em9uwx1dxcvtegm/c.rar/file

SEcond file:
http://www.mediafire.com/file/3d5j7z07cvut6if/a.rar/file


2)Using the new ffmpeg you gave me in link i got an error even dragging the
file onto staxrip.  Here is the copy of the error message:
Error ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman (2.0.6.0)

ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman failed with exit
code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


------- ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman -------

"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i
"C:\dl\t\a.ts" -c copy -map 0 -ignore_unknown -sn -y -hide_banner
"C:\dl\t\a_temp\a.mkv"

Input #0, mpegts, from 'C:\dl\t\a.ts':
Duration: 00:59:41.53, start: 3503.966000, bitrate: 883 kb/s
Program 1
Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B),
yuv420p(progressive), 1280x720, 10 tbr, 90k tbn, 2k tbc
Stream #0:2[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz,
stereo, fltp, 123 kb/s
[matroska @ 0000018e233622c0] Only audio, video, and subtitles are
supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?):
Invalid argument
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Last message repeated 1 times

StaxRip.ErrorAbortException: ffmpeg: Re-mux TS to MKV using ffmpeg
2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


------- ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman -------

"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i
"C:\dl\t\a.ts" -c copy -map 0 -ignore_unknown -sn -y -hide_banner
"C:\dl\t\a_temp\a.mkv"

Input #0, mpegts, from 'C:\dl\t\a.ts':
Duration: 00:59:41.53, start: 3503.966000, bitrate: 883 kb/s
Program 1
Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B),
yuv420p(progressive), 1280x720, 10 tbr, 90k tbn, 2k tbc
Stream #0:2[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz,
stereo, fltp, 123 kb/s
[matroska @ 0000018e233622c0] Only audio, video, and subtitles are
supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?):
Invalid argument
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Last message repeated 1 times


   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line
340
   at StaxRip.CommandLineDemuxer.Run(Project proj) in
D:\Projekte\VB\staxrip\General\Demux.vb:line 195
   at StaxRip.MainForm.Demux() in
D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 3113
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean
isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 1967

**Comment by Patman86** [comment]
Re-muxing the files with LWLibavVideoSource Filter and dsmux works without problems. Your files contain a menu and the ffmpeg re-mux command line cannot handle this. The option -map 0 then brings the error. Correct command line shoud be:

`ffmpeg -i "SourceFolder\Sourcefile.ts" -c copy -ignore_unknown -sn -y -hide_banner "OutputFolder\Finalfile.mkv"`

**Comment by grich99** [comment]
Hello!  Where do i put this command line in staxrip interface, for ffmpeg?

**Comment by Patman86** [comment]
Open Staxrip -> Tools -> Advanced -> Command Prompt and select Powershell or Command Prompt and copy this command line:

`"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i
"C:\dl\t\a.ts" -c copy -ignore_unknown -sn -y -hide_banner
"C:\dl\t\a_temp\a.mkv"`

Check if all folders exist. If the a_temp folder does not exist, add this command line:

`"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i
"C:\dl\t\a.ts" -c copy -ignore_unknown -sn -y -hide_banner
"C:\dl\t\a.mkv"`

**Comment by grich99** [comment]
Ok so I put in one of the 2 lines (tried both), then added the a.ts to
Staxrip and got an error window pop up.  If i disabled the audio it starts
encoding without errors.

The error log:

Error ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman (2.0.6.0)

ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman failed with exit
code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


------- ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman -------

"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i
"C:\dl\t\a.ts" -c copy -map 0 -ignore_unknown -sn -y -hide_banner
"C:\dl\t\a_temp\a.mkv"

Input #0, mpegts, from 'C:\dl\t\a.ts':
Duration: 00:59:41.53, start: 3503.966000, bitrate: 883 kb/s
Program 1
Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B),
yuv420p(progressive), 1280x720, 10 tbr, 90k tbn, 2k tbc
Stream #0:2[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz,
stereo, fltp, 123 kb/s
[matroska @ 000002233d3122c0] Only audio, video, and subtitles are
supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?):
Invalid argument
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Last message repeated 1 times

StaxRip.ErrorAbortException: ffmpeg: Re-mux TS to MKV using ffmpeg
2019-09-27 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


------- ffmpeg: Re-mux TS to MKV using ffmpeg 2019-09-27 Patman -------

"C:\Program Files\StaxRip-x64\Apps\Encoders\ffmpeg\ffmpeg.exe" -i
"C:\dl\t\a.ts" -c copy -map 0 -ignore_unknown -sn -y -hide_banner
"C:\dl\t\a_temp\a.mkv"

Input #0, mpegts, from 'C:\dl\t\a.ts':
Duration: 00:59:41.53, start: 3503.966000, bitrate: 883 kb/s
Program 1
Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B),
yuv420p(progressive), 1280x720, 10 tbr, 90k tbn, 2k tbc
Stream #0:2[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz,
stereo, fltp, 123 kb/s
[matroska @ 000002233d3122c0] Only audio, video, and subtitles are
supported for Matroska.
Could not write header for output file #0 (incorrect codec parameters ?):
Invalid argument
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Stream #0:2 -> #0:2 (copy)
Last message repeated 1 times


   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line
340
   at StaxRip.CommandLineDemuxer.Run(Project proj) in
D:\Projekte\VB\staxrip\General\Demux.vb:line 195
   at StaxRip.MainForm.Demux() in
D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 3113
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean
isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 1967

**Comment by Patman86** [comment]
It is not necessary to add the a.ts file again. Start the command prompt as described, then copy and paste the second command line. Press Enter to see what happened. I had an error when entering the command line, this has now been corrected.

**Comment by grich99** [comment]
ah ok so fffmepg will create a new ile, that file then i fed into staxrip
for the actual encoding.  The resulting encoded file has audio and is much
smaller as expected!

Ok thanks.  That solves a mystery of why things werent working for years
:D  Thank you for your explanation and workarounds!

**Comment by Patman86** [comment]
You're welcome!

**Comment by stax76** [comment]
What was the problem?
