### ISSUE TITLE
Elapsed time on 'Job Processing'

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#161]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open the _Job Processing_ window and can't see how much time the current encode takes. Regarding the percentage/frames and the remaining time I have to guess how long it takes overall.

**Describe the solution you'd like**
I would like to have an information how long the current encode is running - for example next to ETA.

**Describe alternatives you've considered**
. / .

**Explain why the feature matters to you**
For me it is sort of important to check and compare encoding settings and simply to know how long a particular encode takes. At 42% and remaining 11:07:44 hours any calculation without 3rd party tools is sort of inaccurate and/or takes ages - at least for me. It may be important to know, that the tv series, which consists of 8 files, will end in approx. 5, 6, 7 or 8 days.

**Additional context**
. / .

**Comment by stax76** [comment]
The current process prints status output and staxrip catches this output and writes it to the status bar, if that process writes insufficient info than it's not a staxrip issue but an issue of the tool, it's too difficult to analyze and modify the status output.

**Comment by Dendraspis** [comment]
I think we have to live with this issue. Would be great, but...

Thanks for the fast answer. Let's move on to the next requests. ;-)

**Comment by Dendraspis** [comment]
I don't want to open a new request because this is very similar and related.

Would it be possible and useful for you and the others to and the start time of a process in its header or whatever position you prefer?
I mean something like:

```
----- Video encoding using x265 3.3+2-gbe2d82093 GCC 9.2.0 Patman -----
------------------------- 2020-04-22 17:50:12 -------------------------
```

With this information it would be possible to calculate it by yourself.
