### ISSUE TITLE
Stop processing after current job

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#165]
**Is your feature request related to a problem? Please describe.**
Usually I use one instance for processing while having other instances opened to fill the job list. This works without issues. But often I'm not sure if my settings are set right so I create a short sample, set the parameters and queue it. After moving it to the top I can start a new instance of StaxRip encoding this sample (while my normal encodes are still running). What drives me crazy is: I have to wait till the encode ends, which means that the next job starts. Then I have to stop this one and reactivate it on the job list. If I wait too long I lose time.

**Describe the solution you'd like**
_Job Processing_ has an option called *When finished do:* and it would be nice if it could handle one more option to stop after the current job - this would be fantastic.
For example *When finished do* could be renamed to *After this job* with options:
- *Go to next job* or *Move on*
- *Do nothing* or *Stop*
- *Close window if last job*
- *Start Hibernate if last job*
- *Start Hybrid if last job*
- *Start Standby if last job*
- *Shutdown computer if last job*

...just an idea to illustrate one possible solution.

**Describe alternatives you've considered**
- An additional checkbox called '*After current job*' could also be a good solution to extend the possibilities.
- An additional DropDown/Textfield to set the number of jobs after those the action should be performed, which would give even more possibilities than the checkbox.
- Extension to the job list to assign jobs on the job list to instances. (But I doubt this will be an interesting alternative)

**Explain why the feature matters to you**
It's so important that it can't be explained by words. It would be a lifetime saver and let me/us work faster and better with StaxRip.

**Additional context**
. / .

**Comment by vonH** [comment]
I would also love to see an 'Ignore job queue after current job' option as I've found I've needed it more often than I would have though.

**Comment by stax76** [comment]
> Job Processing has an option called When finished do: and it would be nice if it could handle one more option to stop after the current job - this would be fantastic.
> For example When finished do could be renamed to After this job with options:

I would like to keep it one word in this drip down because that is a general design rule in staxrip, it helps to reduce cognitive load. And it fits well into the current layout.

You could just uncheck all remaining jobs, the menu has many features for selecting and checking.

**Comment by Dendraspis** [comment]
One main goal of the requested feature is to be able to start an additional instance/encode and set it on "*stop after this encode*". This would be awesome when you have a job with higher (personal) priority.

Example:
One encode is running and meanwhile I decide to run an encode of a sample to check my parameters or a private record I want to share with a friend *now*. With this possibility I could run it and set it up without thinking of stopping the instance when the job is done and resetting the job's checkbox. 
This would be very powerful when used with process priority - weather used in StaxRip or TaskManager.

So at this point the *Uncheck All* feature is a nice one, but it doesn't help.  🙂   But thanks. 

It's up to you to close this request or leave it open if you think it could be implemented one day.

**Comment by stax76** [comment]
A relative easy way to support it would be putting a menu item into the Jobs dialog, it's probably not the most intuitive way but the only solution I can image me implementing this.

**Comment by Dendraspis** [comment]
But the job list is shared with all instances, which means there is no (good) way to identify an particular instance.

Okay, I close it - makes me a bit sad but it's not the end of the world.
Thanks for reading and discussing.

**Comment by Dendraspis** [comment]
Okay, I've tested it with 2 instances now and it's **AWESOME !!!**
I don't know if many users are going to use it, but at least for me it is an absolute game changer. It allows me to run test encodes in between without loosing time because of all those steps that were needed before.

**Thank you for this feature!**

But I think I found a minor but irritating bug in this new feature:
Instance A is running, Instance B is started and runs. When you tell B to **Stop after current job** everything works as expected for B. Then I looked into A and its menu said **Continue after current job** - which is obvisiously wrong. Because I thought it will stop after the job, I clicked it and when I reopened the menu it still said **Continue after current job**. So I clicked it again and next time I opened the menu it said **Stop after current job**.
It seems like the menu item/text is shared with all instances, but not its current instance setting.

Hope that was understandable.  🙄

**Comment by stax76** [comment]
It's not designed to be shared, that would have required inter process communication which is way too much work for such a specialized feature.

**Comment by Dendraspis** [comment]
Okay, I'll try to reproduce it - maybe I checked the wrong instance?!?  😕 

But one (more) little confusing bug that I've been able to reproduce two times:
When I set a process to *Stop after current job*, the menu text correctly says *Continue after current job* and it stops after the current job ... and everything is fine.  😄 
But when the same instance starts a new run, its menu item says *Continue after current job*, indicating that it will stop. But after it finished the job, it starts the next one. So the behavior is as far as I see 100% correct, but the menu items text is indicating wrong settings.

**Comment by Dendraspis** [comment]
> 
> It's not designed to be shared, that would have required inter process communication which is way too much work for such a specialized feature.

Sorry, my bad. I've confused myself with two those instances.  You are right, there is **no** interfering with other instances! So it is just the little cosmetic bug I've described in my last post. Sorry.

**Comment by stax76** [comment]
Thanks for testing. I changed it to show a check box instead of changing the caption, the implementation for that checkbox is not ideal but since it's the only checkbox I use anywhere it's not worth the effort improving the implementation, normally custom drawing must be done as the WinForms UI toolkit has shitty High DPI support but since there is a checkbox symbol I just set/unset the symbol. And have fixed the issue of showing the wrong check state after a restart.

**Comment by Dendraspis** [comment]
Thanks for implementing.

Meanwhile I have another problem with this feature:  I use it too often.   😄   Despite the little bug it works great and makes everything for me soooo much easier and faster. Now I can start an encode of a sample without watching and waiting till it ends.  

Good idea, a checkbox should be easier to handle and to understand.  👍 
One more time:  thank you!
