### ISSUE TITLE
Selective Process Priority

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#166]
**Is your feature request related to a problem? Please describe.**
I have set *Process Priority* to *Below Normal* to be able to do other stuff while encoding in the background.
My problem is that this setting influences also processes like *ffmsindex*, which is a 'helping' process to be able to create a new job. The natural purpose should be run processes like *ffmsindex* as fast as possible, but it can take an hour instead of minutes if the process priority is not set to normal or higher.

**Describe the solution you'd like**
Possible solution no1: Exclude these processes from being set.
Possible solution no2: Create second setting for those type of processes.

**Describe alternatives you've considered**
. / .

**Explain why the feature matters to you**
Because it takes ages to index source files if I don't open the task manager, search the given process (most times *ffmsindex*) and set it to *Normal* or *Higher than Normal* by hand.

**Additional context**
. / .

**Comment by stax76** [comment]
I changed ffmsindex to use normal priority.

**Comment by Dendraspis** [comment]
Thanks, this will help alot!  😄
