### ISSUE TITLE
DGIndex missing on latest beta

### ISSUE THREAD

**Issue by Cyberavater** [staxrip/staxrip#169]

**Comment by Dendraspis** [comment]
DGIndex is not allowed to be delivered with StaxRip anymore, so you have to keep it up to date by yourself.

Quote from v2.1.0.8 BETA changelog:
> DG* tools binaries and urls removed according to author request

**Comment by Cyberavater** [comment]
So, why not link it to the website as we get for VS?

**Comment by Dendraspis** [comment]
> So, why not link it to the website as we get for VS?

> DG* tools binaries and urls removed according to author request

**Comment by Cyberavater** [comment]
Then how about using another better open-source alternative?

**Comment by PhoO3nX** [comment]
> Then how about using another better open-source alternative?

Just keep DGIndex from an old Staxrip version and use it

**Comment by Patman86** [comment]
It's not an issue. You can follow the discussion [here](http://forum.doom9.org/showthread.php?p=1908682)

**Comment by Cyberavater** [comment]
It's not an issue in that sense, but Staxrip needs a 'REAL' FOSS alternative for mpeg2, vob.

[Seems like DGIndex isn't FOSS but falsely claims to be one].

**Comment by Patman86** [comment]
I think there is no real alternative. All the tools I found are based on DGIndex. In the doom9 forum you will find the download link for DGIndex in my signature.

**Comment by stax76** [comment]
To manually create a d2v file there is a tool called _d2v witch_.
