### ISSUE TITLE
Plan to allow users to edit & run command line within StaxRip?

### ISSUE THREAD

**Issue by gnucian** [staxrip/staxrip#17]
I know I can _import_ command line options from the clipboard but StaxRip seems to _ignore/cut_ some options it does not recognize.

For example, I want to adopt a constant quality mode for NVEncC and try to import the options including '`--vbrhq 0 --vbr-quality 30`'. But StaxRip completely ignores the '`--vbr-quality 30`' option and leaves '`--vbrhq 0`' part only.

Likewise, the framerate halving option '`--vpp-select-every 2,offset=1`' is completely ignored as well, so I have to separately run the command line in the Command Prompt.

Can you please let users edit and run the command line **within** StaxRip, not switching to the Command Prompt instead? Thanks.

**Comment by Revan654** [comment]
Patience, Those Flags will be added in the Next Release from me unless Stax already added it. Not everything is listed in ths doc from the Encoder.

**Comment by stax76** [comment]
@gnucian 

The next build has some nvenc command line import fixes.

nvenc though has many complex parameters that have more than one argument, it's too much work to add import support of such complex parameters.

> Can you please let users edit and run the command line within StaxRip, not switching to the Command Prompt instead? Thanks.

Not sure how exactly this is supposed to work, maybe try the 'Custom' field on the 'Other' tab?
