### ISSUE TITLE
Cropping in Batch Mode

### ISSUE THREAD

**Issue by cfelicio** [staxrip/staxrip#173]
Not sure if this is normal behavior, but I'm trying to setup a static crop for all my video encodes. I configured it and saved as a template:

![image](https://user-images.githubusercontent.com/7227683/80318831-a848c280-87c1-11ea-9c35-77bc11e4a285.png)

This works fine if I open each file manually and add to the job list. On the other hand, if I try to batch process, the crop will not be selected. Is there a way to do it?

Thanks! :-)

**Comment by PhoO3nX** [comment]
It's a issue ticket here, not a forum. Ask your question on the videohelp staxrip forum

**Comment by cfelicio** [comment]
Sorry if it wasn't clear, I am reporting what I believe to be an issue. If that's not the case, and the tool is working as expected, I can close it.

**Comment by 44vince44** [comment]
@cfelicio try putting the filter "crop (4,4,-12,-12)" in a filter slot other than the "crop" slot.

**Comment by cfelicio** [comment]
Worked! Thanks for the workaround! :-)

**Comment by 44vince44** [comment]
You're welcome!!
