### ISSUE TITLE
Wrong RC-Lookahead default value using Slower preset on x265

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#176]
**Describe the bug**
When **Slower** preset is selected, the value of *RC Lookahead* is set to **30 instead of 40**. It is not passed to the encoder, which is using its 40, but this makes it **impossible to set the value to 30**.
This happens with **StaxRip v2.0.8.0** as well as **v2.1.0.9 beta**.

**Expected behavior**
The *RC Lookahead* edit field should be set to **40** when **Slower preset** is set - like **Veryslow**.

**How to reproduce the issue**
Select *x265*, change the preset to *Slower* and check the value.

**Screenshots**
![StaxRip_Bug1](https://user-images.githubusercontent.com/50659978/80789194-85d0f380-8b8b-11ea-83c0-61277255d7ed.JPG)

**Value 40 set by hand:**
![StaxRip_Bug2](https://user-images.githubusercontent.com/50659978/80789195-86698a00-8b8b-11ea-9dc5-aaa0f445f2c3.JPG)

**Comment by Patman86** [comment]
I am currently reviewing and adjusting the default settings for x264 and x265.

**Comment by Dendraspis** [comment]
Found the lines where the parameters are set:
https://github.com/staxrip/staxrip/blob/08eed29429ba9cb9a2d05350d18af36d34e2b036/Encoding/x265Enc.vb#L1395

... and it seems there are a few values out of spec, for example:

- This should be =1:
https://github.com/staxrip/staxrip/blob/08eed29429ba9cb9a2d05350d18af36d34e2b036/Encoding/x265Enc.vb#L1389

- `LimitRefs.Value = 0` should be applied to *VerySlow*

- This should be =4:
https://github.com/staxrip/staxrip/blob/08eed29429ba9cb9a2d05350d18af36d34e2b036/Encoding/x265Enc.vb#L1392

- This should be =5:
https://github.com/staxrip/staxrip/blob/08eed29429ba9cb9a2d05350d18af36d34e2b036/Encoding/x265Enc.vb#L1421

- ...

At least *Slow* seems to be okay.  🙏

**Comment by stax76** [comment]
@Dendraspis 

It's possible to make a pull request entirely in the browser, go to page:

https://github.com/staxrip/staxrip/blob/master/Encoding/x265Enc.vb

Click on the pencil symbol to edit the file, just found this out today making my first pull request adding staxrip and mpv.net to the list of applications supporting vapoursynth in the docs section of the vapoursynth repo.

The change log file can be changed the same way:

- fix incorrect x265 preset values (Patman86)

It's a huge help.

**Comment by Dendraspis** [comment]
Did my first PR.  😀   Interesting, I didn't know this you also be done by hand.
But I'm sure @Patman86 is going to do a better job on that.

**Comment by Dendraspis** [comment]
> I am currently reviewing and adjusting the default settings for x264 and x265.

@Patman86 
Don't wanna hurry, but are you still on it? Haven't seen a commit and I just would like to know, if we can trust the current values.
