### ISSUE TITLE
Open Blu-ray Folder missing playlist

### ISSUE THREAD

**Issue by proper88** [staxrip/staxrip#178]
When i try to open a Blu-ray folder i get an empty playlist window(tried also differnet blu-ray folders with differents sources)
I am using Beta 2.1.0.9
![picture](https://user-images.githubusercontent.com/17383867/80863603-cf9a0680-8c7d-11ea-8a36-b1addce36771.jpg)

**Comment by Patman86** [comment]
I can't reproduce that. More Infos pls, like settings.

**Comment by proper88** [comment]
Copy staxrip to a folder. Run staxrip(settings dialog appers, no template loeded, no script loaded).
Maybe i need some additional software to install ?

**Comment by Patman86** [comment]
This function works very well for me. Please check all apps, runtimes and plugins under Tab Apps, Manage

![grafik](https://user-images.githubusercontent.com/54327252/80964771-bde96800-8e11-11ea-9eb8-9d15c4a9f865.png)

StaxRip searches for the PLAYLIST subfolder in the BDMV folder

**Comment by proper88** [comment]
When i open the playlist file *,mlps directly,  i get this error
![picture_1](https://user-images.githubusercontent.com/17383867/80984978-df0c8180-8e2e-11ea-9556-d1cc58a77262.jpg)

**Comment by Dendraspis** [comment]
@proper88 
Start StaxRip, then **File » Open Video » Blu-ray Folder** and enter **E:\** - what happens?

**Comment by proper88** [comment]
Hi Dendraspis,
thank you for your help.
A window "Please select a playlist" but there are no playlists to select
When i open a music or data disc
same windows with "No playlist directory found"
whick apps i need, because all other stuff is working fine

**Comment by stax76** [comment]
How did you rip the discs? Are this new releases?

**Comment by Patman86** [comment]
> 
> 
> How did you rip the discs? Are this new releases?

maybe copyprotection :-P

**Comment by Dendraspis** [comment]
Regarding the screenshot I would say (s)he did not rip the disc. 🙊 
Possible reasons: copyprotection (already mentioned by @Patman86) broken source/archives, incomplete folder structure, issues with extraction, ...

@proper88 
Open command prompt in *E:\\* and start **eac3to** (without parameters). When it gives you a list with playlists, there could be an issue with StaxRip. If you get error messages, you have to check your source.

<details>
<summary>@proper88</summary>
Ich würde dringend empfehlen den Screenshot zu entfernen oder besser noch ihn zu bearbeiten und die beiden verräterischen Pfadangaben schwärzen.  😉  🤝 
</details>

**Comment by proper88** [comment]
no copyprotection, when i start eac3to from staxrip  i get this window
![picture](https://user-images.githubusercontent.com/17383867/81007224-23a91480-8e51-11ea-8656-04a37c9c6e4b.jpg)

**Comment by Patman86** [comment]
That helps a lot 👍 pls install [that package](https://github.com/abbodi1406/vcredist/releases/download/v0.29.0/VisualCppRedist_AIO_x86_x64_29.zip)
