### ISSUE TITLE
Taskbar-Progress always shown when process is running

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#179]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have multiple instances running and I try to locate the one that is currently running - or to be more precise: the one that started running a moment before. 
The taskbar progress ability is used, but when the progress is below the 1% mark the taskbar "item" looks like every other (sleeping) instance.

**Describe the solution you'd like**
https://github.com/staxrip/staxrip/blob/bd9cfdd84b7788d94b2f2841e3908465dc1e8c81/General/Native.vb#L250

It would be awesome if the TaskbarProgress **always** would indicate a running process - resulting in setting a progress value greater that 0. There are multiple solutions for that, my favorites are:

1. `.., CULng(Math.Max( 1, Math.Truncate(progressValue) )), ..`
2. `.., CULng(Math.Min( 1 + Math.Truncate(progressValue), progressMax) ), ..`

**Describe alternatives you've considered**
. / .

**Explain why the feature matters to you**
Find the running instance at 0.5% when you have 15+ (sleeping) instances open. 😠 

**Additional context**
. / .

**Comment by stax76** [comment]
Thanks for the pull request, merged.

**Comment by Dendraspis** [comment]
Thanks for accepting my request.
