### ISSUE TITLE
NotImplementedException when dragging jobs

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#182]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I (accidently) drag a job up/down and I get a *NotImplementedException*, which is okay by default, **but it also crashes StaxRip ~~and the running encode~~!** 😡 
*__EDIT__: The encoder is still running in the background, but obviously without control and information. At least the encode is able to finish.* 🙄 

**Describe the solution you'd like**
It would be nice, if a message box would pop up **without** crashing the whole app.

**Describe alternatives you've considered**
Disable this feature until it's fully implemented.

**Explain why the feature matters to you**
Start an encode, wait 10 hours and then forget, that you should not drag jobs while reorganizing them. 🤕  This is unpleasant in so many ways!

**Additional context**
. / .

**Comment by stax76** [comment]
I can try to reproduce it but at the moment I'm taking a break..., working on mpv.net instead and I have an unreleased up I want to release (not video related).

**Comment by Dendraspis** [comment]
No problem, I've already noticed your break.  😁  Just hope you are successfull very soon.  😉 

This should help:

https://github.com/staxrip/staxrip/blob/bd9cfdd84b7788d94b2f2841e3908465dc1e8c81/UI/Controls/ListViewEx.vb#L345-L353

In principle it should be enough to *Exit Sub* at the beginning or write a log entry instead of throwing the error.

**Comment by stax76** [comment]
yes, fixed in next build

**Comment by Dendraspis** [comment]
Thanks!
