### ISSUE TITLE
Staxrip is unable to encode audio when vapoursynth script is used

### ISSUE THREAD

**Issue by dragonballz4** [staxrip/staxrip#184]
**Describe the bug**
staxrip crashes when i try to encode using vapoursynth filters. This does does not happen when i encode only the video using the no audio options. Encoding using avisynth filters is fine, this happens only when using vapoursynth filters. I think the issue is because the vapoursynth filters are being copied into the audio avisynth file as you can see that i have attached in the two avisynth files generated using the both filters. I have also attached the log.

**Expected behavior**
Audio encoding should proceed as expected and vapoursynth filters should not be copied.

**How to reproduce the issue**

This happens with any audio file. Just switch to vapoursynth filters and activate one of them and try encoding the audio. for reference my decoder was ffaudiosource, my encoder was qaac and my decoding method was wav.

**Provide information**

I have attached all the relevant files including both avisynth files generated, stax log and 2 screenshots with my audio and profile settings
![audio](https://user-images.githubusercontent.com/54824571/80950507-a0b59900-8e13-11ea-921e-fd60076e2f95.png)
[avisynth files.zip](https://github.com/staxrip/staxrip/files/4573687/avisynth.files.zip)
[test_staxrip.log](https://github.com/staxrip/staxrip/files/4573688/test_staxrip.log)
![Untitled](https://user-images.githubusercontent.com/54824571/80950517-a4492000-8e13-11ea-94f8-3eb5b3935287.png)

**Comment by Patman86** [comment]
If you want to use vapoursynth for audio encoding, open the audio settings and click the 'more' button
![grafik](https://user-images.githubusercontent.com/54327252/80959839-ee2c0900-8e07-11ea-8236-8b478f66991b.png)

in the following window set the decoding method to pipe

![grafik](https://user-images.githubusercontent.com/54327252/80959957-26cbe280-8e08-11ea-9c79-466727a66cc0.png)

**Comment by stax76** [comment]
StaxRip first appeared 2002, there are some very old features still present, this FFAudioSource Decoder feature was probably designed before VapourSynth even existed, it works only when avisynth is used for video processing. It's a flaw that the assistant don't prevent this not supported combination.
