### ISSUE TITLE
DGIndex disabled by default, but still required?!

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#189]
**Describe the bug**
Since v2.1.0.9 BETA *DGIndex* is not delivered and disabled by default. But when you go under apps and click on *Tools » check status of all required apps*, DGIndex is listed as required/not found. This might be confusing to some (new) users.  Or is this intentional?!

**Expected behavior**
DGIndex won't be listed or - in case of intention - maybe give a better/different message?!

![StaxRip-Bug](https://user-images.githubusercontent.com/50659978/81212549-52e88e80-8fd5-11ea-9cf9-24fabbd97bf8.JPG)

![StaxRip-Bug2](https://user-images.githubusercontent.com/50659978/81212760-a529af80-8fd5-11ea-85a6-f695d676e28b.JPG)

**Comment by 44vince44** [comment]
@Dendraspis I read that the author of DGIndex explicitly asked to remove it from Staxrip package. And all the mess got from there. The proper way is now to ignore it and handle it like DGIndexNV, so I guess you're right, this is optional, so the message shouldn't appear.

**Comment by 44vince44** [comment]
@Dendraspis , I tested with beta 2.1.1.1:
- if DGIndex is checked YES in Settings > Preprocessing , then DGIndex is listed as required/not found
- if DGIndex in unchecked in Settings > Preprocessing, then DGIndex is not listed as required.

Can you please confirm and close this thread if OK, because that would be the right behaviour!

**Comment by Dendraspis** [comment]
🤦‍♂️    Doohh!

Don't know how I dismanaged it. When I start StaxRip on a PC without previous versions it works as you described - meaning the right way / as intended. Seems like I forgot to doublecheck if DXIndex is really disabled or I selected to wrong settings path on startup.

**Sorry!** I think I should try to get more sleep before posting more...  🙄

**Comment by 44vince44** [comment]
@stax76 resolved it I just tested :-)))))

**Comment by Dendraspis** [comment]
@44vince44 
😋   I meant not only you pointed out that I made a huge mistake, you also verified it and gave me a step-by-step instruction to self-proof it.  👍

**Comment by 44vince44** [comment]
Ah ;-)))) it's ok, you're welcome !
