### ISSUE TITLE
--limit-modes switch doesn't work on slow presets using x265

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#193]
**Describe the bug**
On *Medium* the `--limit-modes` switch and checkbox work as expected.
But when you use *Slow*, *Slower* or *Veryslow* `--limit-modes` is always enabled and can't be disabled via its checkbox, which is without function on these presets.

**Expected behavior**
It should work.  😬 

**How to reproduce the issue**

## MEDIUM with (un-)checked `--limit-modes`
![StaxRip_Bug0](https://user-images.githubusercontent.com/50659978/81504270-a2d29880-92e8-11ea-9ab4-861a54980def.JPG)
![StaxRip_Bug1](https://user-images.githubusercontent.com/50659978/81504273-a36b2f00-92e8-11ea-8d02-bbfa40f62bee.JPG)

## SLOW with (un-)checked `--limit-modes`
![StaxRip_Bug2](https://user-images.githubusercontent.com/50659978/81504275-a403c580-92e8-11ea-8998-698f9158e374.JPG)
![StaxRip_Bug3](https://user-images.githubusercontent.com/50659978/81504276-a403c580-92e8-11ea-9118-c0c692768ec0.JPG)

## Running encode with unchecked `--limit-modes`
![StaxRip_Bug4](https://user-images.githubusercontent.com/50659978/81504277-a403c580-92e8-11ea-9286-af1fe847c50b.JPG)

**Comment by stax76** [comment]
Thanks for reporting, will be fixed in the next beta build.
