### ISSUE TITLE
 d2v(Vapoursynth) + m2ts + cutting = Frozen/Unresponsive Program

### ISSUE THREAD

**Issue by looppoo** [staxrip/staxrip#197]
**Describe the bug**
StaxRip freezes when cutting ads from most, but not all, **MPEG2 .m2ts** files using **d2v** as automatic source. 
_Recording is split by DVR at 500mb. 1st part usually works._

Seeking to the end of the preview bar (last 1% of frames) freezes all of StaxRip. Remains unresponsive indefinitely but with ~30% continuous CPU usage.

**Expected behavior**
Clear, responsive seek to the final frames so I can finish cutting.

**How to reproduce the issue**
Vapoursynth+d2v+MPEG2 .m2ts

MediaInfo on source that doesn't freeze StaxRip:
[OK Source.txt](https://github.com/staxrip/staxrip/files/4640717/OK.Source.txt)

MediaInfo on "Unresponsive Program" Source:
[Freeze Source.txt](https://github.com/staxrip/staxrip/files/4640718/Freeze.Source.txt)

**Comment by stax76** [comment]
It's much likely a source filter issue, not much I can do other than suggesting an alternative route.
