### ISSUE TITLE
Reduce DTS-HDMA / DTS-HD to DTS core

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#198]
I'd like to have the options in the GUI to reduce these types of tracks to core. 
DTS-HDMA / DTS_HD (both have the same process/commands to reduce to core, also channels do not matter. As a DTS-HD file with a 2 channel layout, when reduced to core will still have a 2 channel layout automatically / same goes for a 6 channel layout. Both commands provided below correctly do this automatically)

Here is the media info for the larger file before reducing to core
https://pastebin.com/ECJWgUs1

Here is what it should look like after it's reduced. 
https://pastebin.com/LSR8pfnm

You can do this 2 ways that I know of. 
With FFMPEG you can reduce to core with this command 
"-bsf:a dca_core -c:a copy"

With mkvmerge 
"--reduce-to-core"

(Both have the same outcome. I would like both options in the GUI if possible)

**Comment by jlw4049** [comment]
I was able to do it via FFMPEG with this setup. 

https://i.imgur.com/oY4Z0gC.png

**Comment by 44vince44** [comment]
I add my "vote" here, to create a new audio profile called "Extract DTS-Core" and have it among the default audio profiles. This could be used by many people (many people still want DTS-core and don't want the extra layer the HD has added)

**Comment by Dendraspis** [comment]
...or better add an additional checkbox "*Only Core*" to the *Copy/Mux* profile.

**Comment by 44vince44** [comment]
if you add it as an option inside "Copy/Mux" then you'll have to handle several cases, in the code, depending on what muxer is being used (because copy/mux only envolves muxer). So the code will have to include a case for all muxers (i.e containers), and in some cases it even won't be possible.
It is easier and cleaner to consider it as a new profile of the "command line" type.
imho...

**Comment by stax76** [comment]
I've been working in this today:

The audio encoder has an option to extract core using eac3to, next build has also an option for ffmpeg, when enabled the generated name is _Extract DTS Core_.

The audio muxer profile has an extract core feature to extract it with mkvmerge.

**Comment by 44vince44** [comment]
@stax76, please, just so there is no confusion, this is a checkbox that overrides all other settings (bitrate etc), Those other settings are not greyed out but have no meaning if the checkbox is selected, so maybe if we put :

Extract DTS Core (Overrides other settings) 

Just for people not getting confused (for ffmpeg and the existing eac3to, which i hadn't noticed ;-))

**Comment by stax76** [comment]
I've changed it to disable bitrate/quality, changing all controls is too much work, hope this didn't add new bugs.

And I greatly simplified the DTS extract core implementation but it leads to discarded settings.

New beta is now online.

https://staxrip.readthedocs.io/introduction.html#beta
