### ISSUE TITLE
MISSING options in Audio Profiles > Command Line

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#199]
**Describe the bug**
In the Audio Profile "Command Line" Editor:
1) There is no checkbox for Default Track
2) There is no checkbox for Forced Track

**Expected behavior**
These options are needed, for the same reason that they are in the Encode/Decode Audio Settings, and in the Copy/Mux Settings too.

Current Editor
![SNAG-0003](https://user-images.githubusercontent.com/17828567/82217781-98854f80-9923-11ea-901f-76827821da48.jpg)

What should be:
![SNAG-0003b](https://user-images.githubusercontent.com/17828567/82217833-a89d2f00-9923-11ea-9f65-c930d6eff673.jpg)

**Comment by 44vince44** [comment]
@Patman86 maybe you can help?

**Comment by stax76** [comment]
Dealing with WinForms layout is tricky, so I've added it at the bottom.

**Comment by 44vince44** [comment]
@stax76 Thanks the options checkboxes are working BUT PLEASE FIX this:
the command line used ffmpeg before, it worked
now you changed to %app:ffmpeg%  : THAT DOESN'T WORK, it must be **"**%app:ffmpeg%**"** with the quotation marks **""**.

**Comment by 44vince44** [comment]
@stax76 and please don't close the posts before testing, you know that I always test the changes in less than 24 hours and I give you the testing results...

**Comment by stax76** [comment]
Sorry I thought it was solved.

**Comment by 44vince44** [comment]
@stax76 it is solved, but a new silly error was introduced due to the change of default command.

Instead of ffmpeg, you now use %app:ffmpeg%. This doesn't work for paths with spaces. So you should put instead "%app:ffmpeg%" (very simply)

**Comment by stax76** [comment]
I've changed it now to:

"%app:ffmpeg%" -i "%input%" -b:a %bitrate%k -y -hide_banner "%output%"

"%app:xvid_encraw%" -cq 2 -smoother 0 -max_key_interval 250 -nopacked -vhqmode 4 -qpel -notrellis -max_bframes 1 -bvhq -bquant_ratio 162 -bquant_offset 0 -threads 1 -i "%script_file%" -avi "%encoder_out_file%" -par %target_par_x%:%target_par_y%

Problem with the second command line is I cannot test it because I don't have the xvid_encraw binary, I hope it works.

**Comment by 44vince44** [comment]
@stax76 it's all ok, 

> Problem with the second command line is I cannot test it because I don't have the xvid_encraw binary, I hope it works.

I tested xvid_encraw, and it worked :
here is the command line generated
------------ Video encoding command line encoder: Command Line ------------

"D:\Downloads\_IDM Downloads\StaxRip-x64-2.1.1.4-beta\Apps\Encoders\xvid_encraw\xvid_encraw.exe" -cq 2 -smoother 0 -max_key_interval 250 -nopacked -vhqmode 4 -qpel -notrellis -max_bframes 1 -bvhq -bquant_ratio 162 -bquant_offset 0 -threads 4 -i "D:\Downloads\_IDM Downloads\DTS HD Living World Of Audio sample_temp\DTS HD Living World Of Audio sample_new.avs" -avi "D:\Downloads\_IDM Downloads\DTS HD Living World Of Audio sample_temp\DTS HD Living World Of Audio sample_new_out.avi" -par 1:1

Command line is correct, and result file is ok !

**Comment by stax76** [comment]
Ok, thanks for testing.

**Comment by 44vince44** [comment]
ALL OK here in new beta 2.1.1.5
