### ISSUE TITLE
Job processing not showing estimated stream size

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#20]
Correct me if I'm wrong, but it seemed to me that version 2.0.2 did show the estimated stream size while encoding, just after the ETA.
In 2.0.2.4 this is not happening!!

**Comment by stax76** [comment]
I don't know which x265 build Revan used, I prefer Wolfberry because it supports avs input.

The feature you are talking about is not official, it's called asuki build I think built by MeteorRain I think.
