### ISSUE TITLE
Please change Avisynth Filter profile DFTTest to this one (better)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#200]
Since a few month, DFTTest has a new version (by pinterf) 1.9.6, and it's in Staxrip all right.
Major change is that it handles natively 10+ bit depths without the stack16 hack.
The Filter options are not adapted.
I suggest you use this one instead (replace the DFTTEST line):

DFTTest = dfttest($select:msg:Select Strength;Light|sigma=6, tbsize=3;Moderate|sigma=16, tbsize=5;Strong Static|sigma=64, tbsize=1;Strong Temporal|sigma=64, tbsize=3$,$select:msg:Reduce Banding?;No Deband| dither=0;Deband| dither=1;Add Noise| dither=2;More Noise| dither=3$)

This gives a better choice of denoising options, and better deband and dither options, and removes the now useless lsb_in and lsb.

**Comment by stax76** [comment]
New beta is now online.

https://staxrip.readthedocs.io/introduction.html#beta

**Comment by 44vince44** [comment]
seems all ok! thanks @stax76
