### ISSUE TITLE
DGDecNV support return

### ISSUE THREAD

**Issue by kliffgomel** [staxrip/staxrip#201]
Please return DGDecNV support! Staxrip supports a huge number of different filters, this makes it unique. It makes no sense to remove the support of the time-tested DGDecNV, it is too early to write off this tool.

**Comment by 44vince44** [comment]
@kliffgomel  are you aware that LSmashVideoSource and LWLiBavVideoSource have the switch
prefer_hw=3, which makes decoding with the nvidia gpu?

**Comment by kliffgomel** [comment]
Yes it is. These filters can replace many more other tools in the kit. But everyone uses the tool to which he is accustomed and trusts. DGDecNV is constantly evolving and in my opinion has the best implementation of hardware decoding on NVIDIA cards among other filters. In any case, this filter does its job as it should, it would be great to keep its support along with other filters.

**Comment by stax76** [comment]
I can't really recommend this tool any longer, it's still usable through configuration, most features were  only settings and all this can still be used by adding the configuration. There are different settings, here is an example:

To customize the Automatic source filter you can first create a source filter profile (right-click filters -> Profiles) and after that associate a file extension to this source filter profile at:

Main Menu > Tools > Setting > Source Filters

StaxRip supports side by side execution of different staxrip versions, each version using their own settings, with that you can easily run an old staxrip version and get the needed configuration from it, it's easy like that!

**Comment by kliffgomel** [comment]
According to the instructions, I can configure the DGDecodeNV.dll decoder plugin, and the index will have to be created manually?

**Comment by stax76** [comment]
Here is a guide:

https://forum.doom9.org/showthread.php?p=1913597#post1913597
