### ISSUE TITLE
Container Options Window Improvements! :) 

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#202]
This request is some suggestions on improving the "container options" window. 

https://i.imgur.com/D2Myedc.png

1. I'd like to be able to resize the window. Maximize/manual resize would be nice. 

2. I'd like to be able to drag and drop audio/subtitle files if it's not to hard. If this is difficult/problematic ignore it. 

Thanks for reading this!

**Comment by stax76** [comment]
I made it resizable and remember it and look at drag & drop tomorrow.

Something is wrong with the font scaling, what is your resolution, your DPI value and your OS?

**Comment by jlw4049** [comment]
I use custom scaling on Windows 10 at 115%. At 1080p and on Windows 10!

**Comment by stax76** [comment]
It's not reproducible here.

**Comment by jlw4049** [comment]
So you are saying that you are able to resize the container window? 

I do use a custom scale because my vision is not perfect unfortunately. 

I will install Stax on my 2nd pc and try it there too.

**Comment by jlw4049** [comment]
Wanted to update, latest BETA on my second rig, no resize options. 

https://i.imgur.com/tJ9LHaT.png

**Comment by stax76** [comment]
It's not yet online.

**Comment by Dendraspis** [comment]
@jlw4049 
Meanwhile/Additionally you could play with this setting:
![StaxRipSettings](https://user-images.githubusercontent.com/50659978/82732154-bed43200-9d0b-11ea-92d4-32c3261fd3ad.JPG)

**Comment by stax76** [comment]
New beta is now online.

https://staxrip.readthedocs.io/introduction.html#beta

**Comment by jlw4049** [comment]
Works perfectly now! Thank you!
