### ISSUE TITLE
chunks increased to 64, but max number of parallel processes still 4

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#203]
Hi Stax, I think you saw how excited we are to discover the effect of setting chunks > 1 with x265.
But is it normal that we can set chunks to 64, while max **number of parallel processes is still max =4** ?

**Comment by stax76** [comment]
Hello Vince, personally I think 4 is enough for common hardware, in the next build the max value for both will be 16.

**Comment by 44vince44** [comment]
@stax76 Thanks Stax !!
