### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by Sibbs** [staxrip/staxrip#204]
Error Find Gain 1 using ffmpeg N-96788 GCC 9.2.0 Patman (2.1.0.2)

Find Gain 1 using ffmpeg N-96788 GCC 9.2.0 Patman returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function

---------- Find Gain 1 using ffmpeg N-96788 GCC 9.2.0 Patman ----------

"O:\Installed Programs\StaxRip v2.1.0.2 Beta\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "O:\Fifty Shades Freed (2018) Unrated_temp\Fifty Shades Freed (2018) Unrated ID1 20ms English.m4a" -sn -vn -hide_banner -af volumedetect -f null NUL

[aac @ 00000000005bbf80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 00000000005bbf80] decode_pce: Input buffer exhausted before END element found
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000000005aa8c0] Failed to open codec in avformat_find_stream_info
[aac @ 00000000005bbf80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 00000000005bbf80] decode_pce: Input buffer exhausted before END element found
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000000005aa8c0] Could not find codec parameters for stream 0 (Audio: aac (mp4a / 0x6134706D), 48000 Hz, 0 channels, fltp, 539 kb/s): unspecified number of channels
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'O:\Fifty Shades Freed (2018) Unrated_temp\Fifty Shades Freed (2018) Unrated ID1 20ms English.m4a':
Metadata:
major_brand     : M4A
minor_version   : 1
compatible_brands: isomM4A mp42
creation_time   : 2020-05-19T01:33:38.000000Z
Duration: 01:50:18.15, start: 0.000000, bitrate: 540 kb/s
Stream #0:0(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 0 channels, fltp, 539 kb/s (default)
Metadata:
creation_time   : 2020-05-19T01:33:38.000000Z
handler_name    :
[aac @ 0000000000606200] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0000000000606200] decode_pce: Input buffer exhausted before END element found
Stream mapping:
Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Error while opening decoder for input stream #0:0 : Operation not permitted

StaxRip.ErrorAbortException: Find Gain 1 using ffmpeg N-96788 GCC 9.2.0 Patman returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function

---------- Find Gain 1 using ffmpeg N-96788 GCC 9.2.0 Patman ----------

"O:\Installed Programs\StaxRip v2.1.0.2 Beta\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "O:\Fifty Shades Freed (2018) Unrated_temp\Fifty Shades Freed (2018) Unrated ID1 20ms English.m4a" -sn -vn -hide_banner -af volumedetect -f null NUL

[aac @ 00000000005bbf80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 00000000005bbf80] decode_pce: Input buffer exhausted before END element found
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000000005aa8c0] Failed to open codec in avformat_find_stream_info
[aac @ 00000000005bbf80] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 00000000005bbf80] decode_pce: Input buffer exhausted before END element found
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000000005aa8c0] Could not find codec parameters for stream 0 (Audio: aac (mp4a / 0x6134706D), 48000 Hz, 0 channels, fltp, 539 kb/s): unspecified number of channels
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'O:\Fifty Shades Freed (2018) Unrated_temp\Fifty Shades Freed (2018) Unrated ID1 20ms English.m4a':
Metadata:
major_brand     : M4A
minor_version   : 1
compatible_brands: isomM4A mp42
creation_time   : 2020-05-19T01:33:38.000000Z
Duration: 01:50:18.15, start: 0.000000, bitrate: 540 kb/s
Stream #0:0(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 0 channels, fltp, 539 kb/s (default)
Metadata:
creation_time   : 2020-05-19T01:33:38.000000Z
handler_name    :
[aac @ 0000000000606200] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0000000000606200] decode_pce: Input buffer exhausted before END element found
Stream mapping:
Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Error while opening decoder for input stream #0:0 : Operation not permitted

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 331
   at StaxRip.GUIAudioProfile.NormalizeFF() in D:\Projekte\VB\staxrip\General\AudioProfile.vb:line 724
   at StaxRip.Audio.ConvertFF(AudioProfile ap) in D:\Projekte\VB\staxrip\General\Audio.vb:line 260
   at StaxRip.Audio.Convert(AudioProfile ap) in D:\Projekte\VB\staxrip\General\Audio.vb:line 88
   at StaxRip.Audio.Process(AudioProfile ap) in D:\Projekte\VB\staxrip\General\Audio.vb:line 48
   at StaxRip.GlobalClass._Closure$__._Lambda$__31-0() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 100
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 133

**Comment by Sibbs** [comment]
tried latest beta, and it crashes when it gets to mp4box, which is worse than 2.1.0.4, that got to the very beginning of encoding, must be just a bad mkv, but it plays fine, just tried handbrake 1.3.1 and it encodes it just fine

**Comment by stax76** [comment]
I'm not sure it's an issue in staxrip, maybe you can upload this m4a file?
