### ISSUE TITLE
Adding VapourSynth-Waifu2x-caffe

### ISSUE THREAD

**Issue by bakamosokyo** [staxrip/staxrip#205]
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe
Would be nice to see this in Staxrip.

**Comment by stax76** [comment]
Did you notice it's 300 MB? You can use it in staxrip via customization.

**Comment by Dendraspis** [comment]
@bakamosokyo 
Could you please summarize the usage and/or benefit of this filter? Can't find a short text that explains what this filter does.  😞

**Comment by bakamosokyo** [comment]
> @bakamosokyo
> Could you please summarize the usage and/or benefit of this filter? Can't find a short (understandable) text that explains what this filter is about. 😞

It's a resize tool based on Deep Learning, It have excellent quality when up-scaling anime/2D content.

**Comment by bakamosokyo** [comment]
For those who want use this in staxrip, 
1.Download and unzip this : https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe/releases
2. Download and put cudnn64_7.dll in same folder
3. Move everything to C:\Program Files\VapourSynth\core\plugins, 
make sure Waifu2x-caffe.dll and cudnn64_7.dll are here.
4. Click VS filters and edit Profile, add Waifu2x-caffe = clip = core.caffe.Waifu2x(clip, noise=1, scale=2, block_w=240, block_h=240, model=1, cudnn=True, processor=0, tta=False, batch=1) to [Resize].

**Comment by bakamosokyo** [comment]
> For those who want use this in staxrip,
> 1.Download and unzip this : https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe/releases
> 2. Download and put cudnn64_7.dll in same folder
> 3. Move everything to C:\Program Files\VapourSynth\core\plugins,
> make sure Waifu2x-caffe.dll and cudnn64_7.dll are here.
> 4. Click VS filters and edit Profile, add Waifu2x-caffe = clip = core.caffe.Waifu2x(clip, noise=1, scale=2, block_w=240, block_h=240, model=1, cudnn=True, processor=0, tta=False, batch=1) to [Resize].

Here is how to use it in VapourSynth @Dendraspis
I suggest you try out original waifu2x-caffe before you use this plugin.
https://github.com/lltcggie/waifu2x-caffe/releases

**Comment by Dendraspis** [comment]
@bakamosokyo 
Thank you. I'll give it a try next time I resize a bunch of videos. My sources are mostly 1080p or 2160p, so no need to resize yet. Thanks also for the short instructions.  🙂
