### ISSUE TITLE
DGINDEX path just to keep things tidy

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#207]
Hi again @stax76, this is a small detail, just to keep things conform to global logic:

Default path for DGIndex (which is not included anymore) is Apps\DGIndex\DGIndex.exe
Shouldn't it be Apps\Support\DGIndex\DGIndex.exe  ??

**Comment by Dendraspis** [comment]
Indead, this leads to the problem you have to browse for DGIndex.exe, because StaxRip can't find it even it's in its old default location.

**Comment by stax76** [comment]
StaxRip is still searching for apps at Apps\AppName\FileName.exe but it's dead code no longer used by any included app, so I just removed this code.

Not included apps are searched in some locations like this:

`Registry.ClassesRoot.OpenSubKey("Local Settings\Software\Microsoft\Windows\Shell\MuiCache")`

Or in the path env var and that's it.

I don't recommend making any changes to the StaxRip folder, it's not making much sense, instead put your settings and custom apps outside. If browsing is a hassle maybe the folder structure needs simplification, or use voidtools Everything.

**Comment by 44vince44** [comment]
Ok, it was not important at all, i thought it would be an easy thing.
So don't make any change indeed!!!
