### ISSUE TITLE
Finished jobs have still open handles in StaxRip

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#21]
Another thing I noticed in StaxRip 2.0.2.4 - 4.8.

When you have several jobs in StaxRip and one ends, the handles inside StaxRip to that finished job are not closed.

When a job is finished and I want to move or rename the folder, I can not. It says it's still open in StaxRip. This did not happen before.

**Comment by stax76** [comment]
It's either ffms2 or l-smash or even both. If you open the preview, seek for a while and close the preview, then the memory is not released by many builds and file handles might not be closed, memory consumption can be seen in task manager. Every build needs to be tested for this.

https://forum.doom9.org/showthread.php?p=1879043#post1879043

https://forum.doom9.org/showthread.php?p=1879044#post1879044

**Comment by stax76** [comment]
It's probably fixed in the last build:

https://forum.doom9.org/showthread.php?p=1882197#post1882197
