### ISSUE TITLE
This program does not work

### ISSUE THREAD

**Issue by Adramelramalech** [staxrip/staxrip#211]
I have said this before and I am saying this again, how is any one using this? It does not work at all. No matter what you do you will always get an error screen, it always crashes, it refuses to accept any user made settings and discards user settings and uses it's own crappy settings. I have no idea how any one is using this, I can not even encode one movie, do a batch? Forgot about it, not possible. This has to be the worse program ever built by man, seriously. And Then finally after fighting with this program to batch encode it finally ran but then it decided to crash and quit on me because one file name was too long. Okay who cares, move on, do the next one, why crash and burn over it? 
Features request? Remove the stupid 1 pass at 7,000 default settings. Why is it there? stupid. If a file name is too long, move on and lastly, make this program work, just for once.

**Comment by Adramelramalech** [comment]
Just restarted the whole thing over, it gave a dumb error and it just quit and crashed on me, waste of time.

**Comment by Dendraspis** [comment]
> I have no idea how any one is using this, I can not even encode one movie,...

Seems like you've figured out what's the reason.  😄 
I would recommend you use one of those two forums to get support/help instead of spamming the issue tracker.  🤔

**Comment by Adramelramalech** [comment]
What? what ever, you make no sense. Worlds worst program and i will spam where the fuck i want

**Comment by Dendraspis** [comment]
At least we can now be sure why it doesn't work for you.  😄

**Comment by 44vince44** [comment]
@Dendraspis don't bother, this user has already made the same input a few months ago, now he returned. Same content, same language.

@Adramelramalech there are many users using this program. So stop spamming, and get OUT.

@stax76 Please report this user or block him. He is the same author of the threads https://github.com/staxrip/staxrip/issues/109 and https://github.com/staxrip/staxrip/issues/101 .
He has already insulted this software and you before.

**Comment by stax76** [comment]
I've blocked this user, hopeless case, whatever his talent is, it's not technical or social, unbelievable.
