### ISSUE TITLE
cutting impossible with QTGMC slow enabled

### ISSUE THREAD

**Issue by bobdig** [staxrip/staxrip#212]
It would be nice to do cutting before the filters so that it is fast and more usable.

**Comment by stax76** [comment]
The Preview dialog is designed to show the full script, I don't think there is an easy way to change anything in this regard.

**Comment by bobdig** [comment]
>You could just disable slow filters before you open the preview.

The problem with that is, that if you have interlaced material and you use QTGMC-slow there is a framerate change or something similar and then the file in the end is async. There is a warning which also is stating that and at least I never had a pleasant result.

**Comment by JonathonSunshine** [comment]
save it as videowithfiltersapplied.AVS and then open that AVS in Staxrip as your source?

I do a lot of qtgmc, i've never noticed anything like that. I don't tend to mess with "slow" setting though.

Try switching to Vapoursynth instead of AviSynth as welll.... just out of the box, so much better. You're limited in the other filters you can use, but i dont normally use any so...



> 
> 
> The Preview dialog is designed to show the full script, I'm not sure it's easy to change something in this regard. You could just disable slow filters before you open the preview.

Preview dialog is wicked just the way it is :D   open preview, turn off a filter, open preview again, and you can seek both at the same time with the slider to see a comparisons, you can do it over and over as well, 5 or 6 previews going at the same time... all syncing to each other. PLEASE DONT MESS WITH IT :|

**Comment by bobdig** [comment]
@JonathonSunshine I can't find that option to save as avs in the GUI.
If the source is i50, I want it to be p50. But to be honest, with full HD i50 as source I also get a somewhat messy end-product... but this is for another discussion.

**Comment by JonathonSunshine** [comment]
> 
> 
> @JonathonSunshine I can't find that option to save as avs in the GUI.
Right click inside your filters, (qtgmc, source, resize etc), > preview code > copy paste is all into notepad manually.

I live in a PAL country, you probs have ntsc interlaced into 50i. Theres actually a routine for getting it back to 30 or 24  but i've never come across a source like that in the age of qtgmc. Even DVDs, I still sort of just trust DGIndex is doing a good job etc. (where i expect them to be well mastered dvds)

**Comment by JonathonSunshine** [comment]
@bobdig try VapourSynth, its way faster, its well multithreaded. I only mtthreads() or whatever helps a lot but VapourSynth, you can watch them in realtime in MPC-BE (it has built in avs and vs support)

**Comment by bobdig** [comment]
@JonathonSunshine I am from Germany, i50 does exist there. And copying stuff to notepad is not the right way of doing it and also I am no expert, but I like the options ans possibilities staxrip offers in a gui. But thanks for your input.

**Comment by 44vince44** [comment]
@bobdig 
This is a "by design" unavoidable problem. You can't do the cutting without the QTGMC slow because the frame rate is changed. And you can't do the cutting with QTGMC slow because the interface will react too slowly.

WORKAROUND: 
change QTGMC from slow to fast or faster, do your cutting, close preview, change QTGMC back to slow, encode.

**Comment by bobdig** [comment]
@44vince44 I cant judge this, if this is a unavoidable problem. problem with the workaround is, that "fast" is not "changing" the framerate.

**Comment by stax76** [comment]
Try to cut first and after that put slow fps changing filters at last filter at the end of the script.

Remember:

You can always disable and enable filters at any time.

You can always reorder filters at any time.

You don't have to use the preview but can use mpv instead from the main dialog, with playback or for slow filters with pause.

**Comment by bobdig** [comment]
> Try to cut first and after that put slow fps changing filters at last filter at the end of the script.
But how to do this? Moving the filter in the AVS Filters "window" never worked for me. The target always get flawed.

**Comment by stax76** [comment]
In the filters context menu there are menu items:

Move Up
Move Down

**Comment by bobdig** [comment]
yes, for me that never solved it..

**Comment by 44vince44** [comment]
@bobdig 

> Problem with the workaround is, that "fast" is not "changing" the framerate.

Did you select option interlaced ? when you select option interlaced, it does double the frame rate (just checked it)

**Comment by bobdig** [comment]
You are right, last time I tried that it wasn't the case, only for the slower profiles. 
So the workaround probably works. But still it will have some impact on cutting with a high def source I think.

**Comment by 44vince44** [comment]
You have to find ways to workaround the performance issues. There is hardware that allows to work comfortably with those kind of sources but it's expensive. I would do this, if i wanted to work with cutting and very slow filters:
1. setup all the filters, check them on a few frames, make sure QTGMC is working ok (be patient)
2. put a temporary fast resize filter at the beginning (that i'll remove later), resize to a smaller size like 480p. Now I can do my cutting, color adjustment etc
3. when everything is ok, just remove the fast resize filter
4. encode

**Comment by bobdig** [comment]
> 
> 
> @bobdig try VapourSynth, its way faster, its well multithreaded. I know mtthreads() or prefetch() or whatever helps a lot but VapourSynth, you can watch them in realtime in MPC-BE (it has built in avs and vs support)

Where to change between the two? Can't find any option/dialog for that.

**Comment by bobdig** [comment]
Ok found it... it is a lot faster!! Thank you.
