### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by utcutr** [staxrip/staxrip#213]
It does not work. It is a useless worthless app.
All it is error after error.
Guess ill make videos to prove it.
Keep on blocking me, ill come back

**Comment by Dendraspis** [comment]
> Keep on blocking me, ill come back

Please do so!  😄 
I'm sort of torn back and forth: It's fun looking at somebody who has to express himself/herself multiple times as "*not that intelligent*", on the other side: What sort of human being is wasting his/her (and others) life time in such a stupid and unnecessary way on purpose?  😧

**Comment by 44vince44** [comment]
I think he believes it's a game or something....
