### ISSUE TITLE
ImageSource() as Input Type

### ISSUE THREAD

**Issue by JonathonSunshine** [staxrip/staxrip#214]
**Is your feature request related to a problem? Please describe.**
I am encoding from numeric image sequences, 000.tif, 001.tif, 002..etc .etc

Currently, I have to (manually) create an AVS, with the image sequence and then import that. It's hard to automate as well, because you have to specify the first and last images. Currently I write  a script that looks lllike
`ImageSource("M:\folder with image sequence\%d.tif",0,10814)
AssumeFPS(30000, 1001)
ConvertToYV16()
Prefetch(12)`
 (where 10814.tif is the last in the sequence and 0.tif is the first)

And then open that AVS in Staxrip.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/27830114/83232611-ce9ebb00-a1d0-11ea-8e77-ef56d5d97fe2.png)
5th option, "open image sequence", and then in the filechooser, show jpg and tif bmp etc, png, maybe throw an error if the filename isn't numeric? then count to the end of that numeric filesequence and create the input "ImageSource()" as in the example above. All the other stuff (in the script) doesn't matter. ImageSource(0,5789) will work just fine without framerate, it just uses a default fps (that escapes me).

Another important thing to know if you are not familiar with ImageSource(), if you specify an image sequence 0 to 100, and images are missing, ImageSource() will insert blankframes, even if it is  missing everything from 2-99. So, hayhaps, you would do this by opening a folder as source instead, enter first image in sequenc, and then the last, do not check for missing frames, just go straight from first to last. I think it is safe to assume people would only have one video in each folder.

I presume there is away to open filename0001.tif, filename0002.tif, but i haven't found it :(

**Describe alternatives you've considered**
A batch file that will create AVS scripts for me

**Explain why the feature matters to you**
AI enhancement softwares best quality output is tif or png image sequences, it uses a really ugly, really shitty avc encoder at a superhighbitrate. But it still doesn't look as good as the tif, and is too big to use without reencoding. And when i encoded it myself in HEVC, it looks way better than the default avc output and a quarter the size.

Thank you for your consideration.

**Comment by stax76** [comment]
There are possibilities like powershell or vapoursynth and python. I don't have a lot of time for special requests and I think it does not fit well into the current design, maybe somebody else can help. The vapoursynth filter seem to be more convenient:

https://forum.doom9.org/showthread.php?t=170981

**Comment by JonathonSunshine** [comment]
That's ok. VS solution looks great if I don't have to specify the last frame. Am I the _only_ one that can close a thread that I start?

**Comment by stax76** [comment]
There is now ImageSource for sequences support in the last beta, just open the first image like it would be a video file.
