### ISSUE TITLE
Opus bitrate doesn't change automatically

### ISSUE THREAD

**Issue by Cyberavater** [staxrip/staxrip#215]
It seems if I change the channel (5.1 to 2 or whatever) it automatically doesn't change the bitrate as it does for AAC

**Comment by stax76** [comment]
I think bitrate change happens only when you have quality based encoding settings and not with bitrate based encoding settings.

**Comment by Cyberavater** [comment]
But, it changes in that condition if it's AAC. So maybe that is the bug?

**Comment by Cyberavater** [comment]
https://wiki.xiph.org/index.php?title=Opus_Recommended_Settings&mobileaction=toggle_view_desktop

**Comment by stax76** [comment]
AAC uses typically a quality mode where you don't define a bitrate but rather some rate factor.

Opus uses a fixed bitrate setting.

It does change only in quality mode and not in fixed bitrate mode, it's doubtful and also difficult to change something here.

**Comment by Cyberavater** [comment]
Is it not possible to use rate factor in Opus?

Also, how about setting a default bitrate (which can be manually changed tho) value channel-wise from here?;
https://wiki.xiph.org/index.php?title=Opus_Recommended_Settings&mobileaction=toggle_view_desktop

**Comment by stax76** [comment]
> Is it not possible to use rate factor in Opus?

I don't know.

> Also, how about setting a default bitrate (which can be manually changed tho) value channel-wise from here?;

The audio dialog is rather complex because it mixes all audio formats and audio tools, so I typically avoid changes unless they are very important.
