### ISSUE TITLE
Add 'SelectRangeEvery' to filter options 

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#216]
**Is your feature request related to a problem? Please describe.**
N/A This is not an issue with Staxrip.

**Describe the solution you'd like**
When creating a script, I would use #SelectRangeEvery(1500,50) (depending on source) to get a reasonable idea of the end results, but without having to encode the entire file. I know this can be added by editing the script in Staxrip, but it's hard to work out where to place it (I'm not used to the UI and editing the script brings up this box:

![image](https://user-images.githubusercontent.com/10042301/83400597-09843700-a3fb-11ea-8f12-d022d46a5a56.png)

Where should I add the SelectRangeEvery()?

**Describe alternatives you've considered**
I've considered trying to load a pre-written script into Staxrip, but then it seems pointless to use Staxrip in the first place if I go back to writing the script.

**Explain why the feature matters to you**
It's a really useful tool and would be an excellent add-on to the program. I can't imagine it would be hard to implement. I would suggest adding it to 'AVS Filters -> Misc -> SelectRangeEvery' or perhaps 'AVS Filters -> Testing -> SelectRangeEvery()' (new category) and let the user decide.

**Additional context**
I can't think of any. I have read through the documentation and [this forum post](https://forum.doom9.org/showthread.php?t=175845&page=41) but can't seem to work out exactly where to place it and really believe there would be a benefit of adding it.

**Comment by vonH** [comment]
I should add that this can be done by going to Profiles -> Misc -> and adding 'SelectRangeEvery() = #SelectRangeEvery(1500,50)' without the ' , but it would be nice to see this added as a standard option in the next release, if possible.

**Comment by stax76** [comment]
I've added it to the presets.

> Where should I add the SelectRangeEvery()?

In the Code Editor menu:

Add... > Empty Filter

**Comment by stax76** [comment]
New beta is online.

**Comment by vonH** [comment]
> I've added it to the presets.
> 
> > Where should I add the SelectRangeEvery()?
> 
> In the Code Editor menu:
> 
> Add... > Empty Filter

Only just seen this. Not sure how I missed the notification as I added it then saw you'd added in. Just wanted to say thank you.
