### ISSUE TITLE
What happened to DGDecNV?

### ISSUE THREAD

**Issue by OnbekendHH** [staxrip/staxrip#217]
Hello Everyone!

What happened to DGDecNV?

I was trying out the newest BETA and was quite astonished to find out that DGDecNV is not longer listed in the Apps?

Was it removed on purpose? If so, why so?

Many thanks in advance!

**Comment by Dendraspis** [comment]
Info can be found here:
https://github.com/staxrip/staxrip/blob/master/Changelog.md#2113-beta
https://github.com/staxrip/staxrip/blob/master/Changelog.md#new

**Comment by stax76** [comment]
It was removed because of too many arguments with the author. I suggest to use L-Smash-Works instead.

[Here is a guide.](https://forum.doom9.org/showthread.php?p=1913597#post1913597)
