### ISSUE TITLE
Tiny, messed up fonts in Windows 7 x64

### ISSUE THREAD

**Issue by Beliathal** [staxrip/staxrip#218]
Tiny, messed up fonts in Windows 7 x64, running in classic mode (dwm off), DPI 96 (default)

Attaching comparison screen between v1.5.0.0 and v2.0.8.0
![issue](https://user-images.githubusercontent.com/19905041/84007021-64c4a500-a978-11ea-833c-bb51b7640c6d.png)

**Comment by stax76** [comment]
What is the display resolution and what does it look like in a default Win 7 setup. If it works in a default  Win 7 environment then Classic mode is not a supported scenario any longer unless somebody sends a patch or it's possible to reproduce in Windows 10, I can try that but don't think Win 10 supports it.

**Comment by stax76** [comment]
I wasn't able to reproduce it WMWare, please try v2.1.1.9.
