### ISSUE TITLE
filtering for batch processing

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#219]
I would find it very useful if there were a way to filter e.g by wildcard or filetype, when adding files via batch processing 

In my project I have hundreds of episodes ripped from DVD to encode, and they are not all the same so I have had to manually check and index each episode in DGIndex and produce d2v files accordingly (I can't leave this to automation or it goes wrong). In my workflow I have a folder for each episode containing the VOB, the d2v, the extracted audio, and the chapters file

I then "add folder including sub-folders" to add these into staxrip for encoding, but of course this adds the d2vs and the vobs as well, which means I then need to go through the list and remove every vob file added (this is still the quickest way of doing this). It would be great if I could simply filter the selection after adding it, perhaps with a filter button next to the add and remove buttons in the batch importer

I've tried working around this by putting all the vobs in one location and the d2vs etc in another but it just makes the workflow a mess. And this can't be the only case where someone would find filtering the selection useful! It would be a great addition I'm sure

**Comment by Dendraspis** [comment]
Just a sidenote:

As a workaround you could use a Powershell script for example to rename each VOB, use StaxRip and rename them back afterwards - should be a lot faster then moving them:

```Powershell
# BEFORE StaxRip
Get-ChildItem *.vob -Recurse | Foreach-Object{ Rename-Item $_.FullName ($_.BaseName + '.vobstax') }
```

```Powershell
# AFTER StaxRip
Get-ChildItem *.vobstax -Recurse | Foreach-Object{ Rename-Item $_.FullName ($_.BaseName + '.vob') }
```

**Comment by Statick** [comment]
that's not a bad idea actually, I have a batch file rename tool already so I can use that
cheers

**Comment by stax76** [comment]
The easiest way here is using the search feature of Windows File Explorer.

Search for:

*.d2v

Then drag and drop the result on the File Batch window.

In the next build there is a new command called AddBatchJob, like all commands its available on the CLI:

https://staxrip.readthedocs.io/cli.html#cmdoption-addbatchjob-sourcefile
