### ISSUE TITLE
Quality not shown in Main Windows

### ISSUE THREAD

**Issue by Stofferl** [staxrip/staxrip#22]
Hello!
I don't get the quality setting in the main window.
The last version where it works is 2.0.0.0.
If i use the settings folder from the 2.0.0.0 version in a newer version it works, but if i use a fresh settings folder in a newer version it is not shown.
![sr1](https://user-images.githubusercontent.com/48128281/60802539-69d21080-a179-11e9-92ad-9e179191c667.png)

**Comment by stax76** [comment]
Hi,
in the codec options go to the basic tab and change mode from two pass to quality.
