### ISSUE TITLE
CRASH - Re-encode any x265 using x265 NVIDIA Hardware

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#227]
![20061300](https://user-images.githubusercontent.com/16325865/84572124-fad84100-ad65-11ea-9c42-e1be427aee2c.png)

All other settings default.

Error Muxing (2.1.3.0)

Muxing returned error exit code: 2 (0x2)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

The system cannot find the file specified

------------------------------- Muxing -------------------------------

mkvmerge 47

X:\StaxRip-x64.Org4\Apps\Support\MKVToolNix\mkvmerge.exe -o "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _new.mkv" --default-duration 0:23.976024fps "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _new_out.h265" --no-chapters --audio-tracks 0 --language 0:eng --default-track 0:0 --forced-track 0:0 "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta  ID1 English {English}_a1.m4a" --forced-track 0:0 --default-track 0:0 --language 0:eng --track-name "0:English (SDH)" "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta  ID3 English {English (SDH)}.ass" --ui-language en

mkvmerge v47.0.0 ('Black Flag') 64-bit
Error: The file 'F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _new_out.h265' could not be opened for reading: end of file error.

StaxRip.ErrorAbortException: Muxing returned error exit code: 2 (0x2)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

The system cannot find the file specified

------------------------------- Muxing -------------------------------

mkvmerge 47

X:\StaxRip-x64.Org4\Apps\Support\MKVToolNix\mkvmerge.exe -o "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _new.mkv" --default-duration 0:23.976024fps "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _new_out.h265" --no-chapters --audio-tracks 0 --language 0:eng --default-track 0:0 --forced-track 0:0 "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta  ID1 English {English}_a1.m4a" --forced-track 0:0 --default-track 0:0 --language 0:eng --track-name "0:English (SDH)" "F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta  ID3 English {English (SDH)}.ass" --ui-language en

mkvmerge v47.0.0 ('Black Flag') 64-bit
Error: The file 'F:\-CNV\_TV\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _temp\Trackers.S01E02.PROPER.720p.HEVC.x265-MeGusta _new_out.h265' could not be opened for reading: end of file error.

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 372
   at StaxRip.MkvMuxer.Mux() in D:\Projekte\VB\staxrip\General\Muxer.vb:line 569
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 309

**Comment by stax76** [comment]
It's much likely a nvenc issue, I don't have hardware/driver to reproduce it, so there is not much I can do, but somebody should report it to the nvenc author.

https://github.com/rigaya/NVEnc/issues

**Comment by 44vince44** [comment]
good news: nvenc has been updated (twice) since this post
