### ISSUE TITLE
Display info of >2 audio tracks in main UI

### ISSUE THREAD

**Issue by Druhl** [staxrip/staxrip#228]
First, thank you for all your work on a great program!

Second - possible very dumb question - for a few versions StaxRip supports selecting >2 audio channels during import but is there a way to expand the UI to display them and their options at the bottom in addition to the default 2?

If there is somewhere to enable or customise this I've never found it.

Thanks!

**Comment by stax76** [comment]
You can add more audio files/tracks/streams in the container/muxer dialog, the main dialog can only show 2 and it's very unlikely that it will change because it's way too much work, it would take weeks to build.

**Comment by Druhl** [comment]
OK. Thank you for the reply, and again for all the work on this program.
