### ISSUE TITLE
MkvExtract Demux does not honor "extract Video" on Batch Encodes

### ISSUE THREAD

**Issue by FlorianGamper** [staxrip/staxrip#229]
**Describe the bug**
If you have set Video Demuxing to true on MKVExtract Demux in  Preprocessing, it does not demux the video and ffindex indexes the original mkv (Source ffms2 / Vapoursynth)

**Expected behavior**
demux the video into the TempDirectory and use it

**Comment by stax76** [comment]
There is a new Beta which fixes it.

**Comment by FlorianGamper** [comment]
Wow that was fast :) 
I will try it tomorrow

**Comment by FlorianGamper** [comment]
It does "work"

it demuxes and uses the h264 file. Unfortunately at the end it tells me, that it cannot delete the file because it's still in use by Staxrip ?

cheers

**Comment by FlorianGamper** [comment]
The File seems to be locked until the next one starts encoding !
So it's still locked during the whole demuxing ffindex phase of the next file

**Comment by stax76** [comment]
> Unfortunately at the end it tells me, that it cannot delete the file because it's still in use by Staxrip ?

At the end of what? End of encoding or end of preprocessing? Who wants to delete the file for what reason? Do mean the feature _Delete Temp Files_? I tried this feature and it did not cause an error.

Please post log files to pastebin.com using auto expire.

**Comment by FlorianGamper** [comment]
The File that is locked is the demuxed .h264 file after the encoding. its locked until the next encoding has finished its preprocessing phase and started encoding.

I will post logs tomorrow

**Comment by stax76** [comment]
Please reopen after providing logs.
