### ISSUE TITLE
Source filter issue

### ISSUE THREAD

**Issue by Cyberavater** [staxrip/staxrip#23]
The system cannot find the file specified

File: ffmsindex.exe

Arguments: H:\z\a.mkv H:\z\a_temp\a.ffindex

InvalidOperationException (2.0.2.4)

No process is associated with this object.

System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at StaxRip.Proc.Start()
   at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Project proj)
   at StaxRip.MainForm.Indexing()
   at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath)
   at StaxRip.MainForm.ModifyFilters()
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding)

[a_new_staxrip.log](https://github.com/staxrip/staxrip/files/3370096/a_new_staxrip.log)

**Comment by 44vince44** [comment]
This is the consequence of the issue 18:
[https://github.com/staxrip/staxrip/issues/18](url)
Open the app manager in staxrip (Apps>Manage), and locate file ffms2.dll under Avisynth and Vapoursynth.
Set path (using F11) to C:\Program Files\StaxRip\Apps\Plugins\Both\FFMS2

**Comment by Cyberavater** [comment]
Okay, thanks! Further discussion can continue there.

**Comment by stax76** [comment]
Better use ffms2 of 2023, the one in 2024 is broken.

**Comment by stax76** [comment]
Issue can stay open until there is a new release.

**Comment by Revan654** [comment]
> 
> 
> Better use ffms2 of 2023, the one in 2024 is broken.

Nothing Wrong with the version in 2.0.2.4 version(Like I said, this is due to Staxrip looking in the wrong place for the files). Plus I supply two different versions. The main problem with ffms2 is the ffmsindex which hasn't been updated for awhile last time I checked. Wish there were more Source filters, since some of them are a bit dated and can struggle with certain formats.

**Comment by stax76** [comment]
@Revan654 

I made another test with the ffms2 in 2023, after the preview is closed the memory is not released and it's also using much more memory, please try with a 4K source and observe in task manager.

**Comment by Cyberavater** [comment]
@stax76 Try this version,
https://forum.doom9.org/showthread.php?p=1881331#post1881331

**Comment by stax76** [comment]
I used that one in the last build, it seem to work fine.
