### ISSUE TITLE
How can update right

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#235]
**Is your feature request related to a problem? Please describe.**
I don't know how can update right StaxRip

**Describe the solution you'd like**
I unrar the new version, and can I re-write on the old version?
How about my personal issues and my personal presets?

Sorry, but I'm new user of StaxRip, and I can't get find it.

**Comment by stax76** [comment]
You can find some guide in the link below, I hope it's clear.

https://forum.doom9.org/showthread.php?p=1915875#post1915875

**Comment by papa-pitufo** [comment]
If I understand right, 

To make an update right:
Unrar the new version
Copy the Settings folder of the old version into the new version folder, and re-write if ask about it.

It's that Ok?

**Comment by Dendraspis** [comment]
Yes - or you use the user profile to store the settings, so you never have to copy and/or overwrite them.

**Comment by papa-pitufo** [comment]
Ok, thank you very much.

**Comment by papa-pitufo** [comment]
> 
> 
> Yes - or you use the user profile to store the settings, so you never have to copy and/or overwrite them.

Hi, again.

I try to find user profile, but I don't find it.

Could you help me?

**Comment by Dendraspis** [comment]
Short answer:
`%appdata%\StaxRip`

But what was meant was, that StaxRip asks you for the storage location when it is started the first time from a (new) location - there you can say "User profile".

**Comment by papa-pitufo** [comment]
Ok, I understand right,

Thanks a lot
