### ISSUE TITLE
I don't know how can I do crop right

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#236]
Hi, again

In the past I used Handbrake, and use crop in automatic mode and his crop modify anything.

Here, with StaxRip, I'm sure that I do it anything wrong, because I pick up crop, select automatic and doesn't do anything.

How can I find any tutorial about this crop?

Best regards

**Comment by stax76** [comment]
How did you pick up crop, in the filter list in the main dialog or in the menu of the crop dialog?

For auto crop to work you have to check the checkbox in the main dialog filter list before you open a source file.

Afterwards you still can trigger auto crop by opening the crop dialog and choose auto crop in the menu.

StaxRip is complex application and encoding is a difficult field, it takes time and patience to learn everything.

**Comment by papa-pitufo** [comment]
Ooooh, thanks

I do it **after open** and it must doi t **before open**

With handbrake or Hybrid is after, then I getting crazy because I want to do like these. jajajajaja

Thanks a lot
