### ISSUE TITLE
This video conversion is not supported

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#237]
Hi, 

I select a UHD BD folder, and StaxRip, well, specify Demux M2TS tell me this message.

I know there is a new tsRemux that it can do it with UHD folder, but I don't know if I can redirect demux funtion to tsRemux or I need to make a BDRemux or extract with tsremux and then use the video to make an encode.

Best regards

Notice, the last version do it, I did it with another UHD folder, but this version don't do it, I tested with the same folder.

**Comment by papa-pitufo** [comment]
Error Demux M2TS (2.1.3.0)

Demux M2TS returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Función incorrecta


----------------------------- Demux M2TS -----------------------------

eac3to 3.34

C:\Users\JAVIG\Downloads\StaxRip-x64-2.1.3.0-stable\Apps\Audio\eac3to\eac3to.exe "G:\DESCARGAR TORRENT\MYLENE_FARMER_LE_FILM_2019_UHD_HDR\BDMV\PLAYLIST\" 1) 2: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR_temp\MYLENE_FARMER_LE_FILM_2019_UHD_HDR." 1: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR_temp\MYLENE_FARMER_LE_FILM_2019_UHD_HDR_chapters.txt" -progressnumbers

M2TS, 1 video track, 2 audio tracks, 2:08:01, 12.500p
1: Chapters, 23 chapters
2: h265/HEVC, 2160p25 (16:9), 10 bits
3: RAW/PCM, French, 2.0 channels, 24 bits, 96kHz
4: TrueHD/AC3 (Atmos), French, 7.1 channels, 48kHz, dialnorm: -27dB
(embedded: AC3 EX, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB)
This video conversion is not supported.

StaxRip.ErrorAbortException: Demux M2TS returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Función incorrecta


----------------------------- Demux M2TS -----------------------------

eac3to 3.34

C:\Users\JAVIG\Downloads\StaxRip-x64-2.1.3.0-stable\Apps\Audio\eac3to\eac3to.exe "G:\DESCARGAR TORRENT\MYLENE_FARMER_LE_FILM_2019_UHD_HDR\BDMV\PLAYLIST\" 1) 2: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR_temp\MYLENE_FARMER_LE_FILM_2019_UHD_HDR." 1: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR_temp\MYLENE_FARMER_LE_FILM_2019_UHD_HDR_chapters.txt" -progressnumbers

M2TS, 1 video track, 2 audio tracks, 2:08:01, 12.500p
1: Chapters, 23 chapters
2: h265/HEVC, 2160p25 (16:9), 10 bits
3: RAW/PCM, French, 2.0 channels, 24 bits, 96kHz
4: TrueHD/AC3 (Atmos), French, 7.1 channels, 48kHz, dialnorm: -27dB
(embedded: AC3 EX, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB)
This video conversion is not supported.


   en StaxRip.Proc.Start() en D:\Projekte\VB\staxrip\General\Proc.vb:línea 372
   en StaxRip.MainForm.OpenEac3toDemuxForm(String playlistFolder, Int32 playlistID) en D:\Projekte\VB\staxrip\Forms\MainForm.vb:línea 5221

**Comment by papa-pitufo** [comment]
I hope I'm doing well

I apologize for my bad english, it's not my mother tongue

**Comment by Dendraspis** [comment]
The problem seems to be:
`2: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR_temp\MYLENE_FARMER_LE_FILM_2019_UHD_HDR."`
where the extension is missing.

**Comment by papa-pitufo** [comment]
I name the extension .mkv.

 Do the same: (What extension I have to write?)  I only want to demux to make a encode.

Error Demux M2TS (2.1.3.0)

Demux M2TS returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Función incorrecta


----------------------------- Demux M2TS -----------------------------

eac3to 3.34

C:\Users\JAVIG\Downloads\StaxRip-x64-2.1.3.0-stable\Apps\Audio\eac3to\eac3to.exe "G:\DESCARGAR TORRENT\MYLENE_FARMER_LE_FILM_2019_UHD_HDR\BDMV\PLAYLIST\" 1) 2: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR.mkv." 1: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR.mkv_chapters.txt" -progressnumbers

M2TS, 1 video track, 2 audio tracks, 2:08:01, 12.500p
1: Chapters, 23 chapters
2: h265/HEVC, 2160p25 (16:9), 10 bits
3: RAW/PCM, French, 2.0 channels, 24 bits, 96kHz
4: TrueHD/AC3 (Atmos), French, 7.1 channels, 48kHz, dialnorm: -27dB
(embedded: AC3 EX, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB)
This video conversion is not supported.

StaxRip.ErrorAbortException: Demux M2TS returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Función incorrecta


----------------------------- Demux M2TS -----------------------------

eac3to 3.34

C:\Users\JAVIG\Downloads\StaxRip-x64-2.1.3.0-stable\Apps\Audio\eac3to\eac3to.exe "G:\DESCARGAR TORRENT\MYLENE_FARMER_LE_FILM_2019_UHD_HDR\BDMV\PLAYLIST\" 1) 2: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR.mkv." 1: "C:\Users\JAVIG\Documents\Trabajos MKV\Temporal de StaxRip\MYLENE_FARMER_LE_FILM_2019_UHD_HDR.mkv_chapters.txt" -progressnumbers

M2TS, 1 video track, 2 audio tracks, 2:08:01, 12.500p
1: Chapters, 23 chapters
2: h265/HEVC, 2160p25 (16:9), 10 bits
3: RAW/PCM, French, 2.0 channels, 24 bits, 96kHz
4: TrueHD/AC3 (Atmos), French, 7.1 channels, 48kHz, dialnorm: -27dB
(embedded: AC3 EX, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB)
This video conversion is not supported.


   en StaxRip.Proc.Start() en D:\Projekte\VB\staxrip\General\Proc.vb:línea 372
   en StaxRip.MainForm.OpenEac3toDemuxForm(String playlistFolder, Int32 playlistID) en D:\Projekte\VB\staxrip\Forms\MainForm.vb:línea 5221

**Comment by Dendraspis** [comment]
Instead of `.mkv` it should be `.hevc` or `.h265` because eac3to can't mux HEVC into a mkv container.

Maybe someone else has to help you with the settings - I prepare my sources always outside of StaxRip.

**Comment by papa-pitufo** [comment]
ok, tomorrow I'll do it and tell you.

Good night

**Comment by papa-pitufo** [comment]
It does the same.
[MYLENE_FARMER_LE_FILM_2019.h265 - Log.txt](https://github.com/staxrip/staxrip/files/4798020/MYLENE_FARMER_LE_FILM_2019.h265.-.Log.txt)

When the program ask me about file name, it not the name of the file, is the name of the folder temp. Then then program do it automatically.

The problem is eac3to don't demux an UHD video file, but it doesn't in this version.
The old version it do it, I'm sure, I did it without problem with this same folder.

Is there any way to change the Demux program? By default is eac3to, but  could you (the user) change the program? by example tsMuxer or whatever?

**Comment by Dendraspis** [comment]
Have you ensured to set the output to **H265**?:
![StaxRip1](https://user-images.githubusercontent.com/50659978/85018453-7c1c4300-b16d-11ea-8080-21cf48f41f16.JPG)

**Comment by Dendraspis** [comment]
@stax76 
There seems to be a bug in or around here:

https://github.com/staxrip/staxrip/blob/e92619989a91b1b775cb7f98411edd603210150d/Forms/eac3toForm.vb#L1001-L1025

When you import a Bluray, the eac3to dialogs' Output is set to **"H264"**, but when you open a UHD Bluray (with a H265 video track) the selection is empty and you have to select an option - or the above described problem appears, where the extracted video tracks should have an empty extension.


![StaxRip2](https://user-images.githubusercontent.com/50659978/85019479-2fd20280-b16f-11ea-90fb-987ff8d4003c.JPG)
![StaxRip3](https://user-images.githubusercontent.com/50659978/85019481-306a9900-b16f-11ea-89e3-d5a7de4a7af0.JPG)

**Comment by papa-pitufo** [comment]
Yeah!!!

That's right.

Now it's demuxing without any problems.

Thanks a lot

Best regards

**Comment by Dendraspis** [comment]
You're welcome.  🙂 

Don't forget to close this issue.  😉

**Comment by papa-pitufo** [comment]
ok.
