### ISSUE TITLE
Wrong Image size with internal filter "Addborders" of AVS

### ISSUE THREAD

**Issue by Globefishp** [staxrip/staxrip#239]
When I use Addborders filter, it fail to update the image size in the main window.
When it was used after crop, the image size should be added and it can be divisible by 8. But since the size increased by Addborders is not calculated, a warn was shown in the bottom says "Image width is not divisible by 8. Click here to correct the crop value......." Though I can change the output mod settings to bypass the warn, I wasn't a good resolution.

**Comment by 44vince44** [comment]
@Globefishp Staxrip doesn't track the changes of filters like Addborder, and all the filters that are not linked to a command of the user interface:
- the crop filter that works with the menu CROP is tracked
- the resize fliter that works with the resize slider is tracked
any other size or geometry filter can not be tracked.
The only way you can know of the video size you'll get is: 
-opening the preview window
-if no information is displayed, press "i"
there you get in the upper-left corner the real video size that will be processed

**Comment by Globefishp** [comment]
Thanks!

**Comment by 44vince44** [comment]
You're welcome!

@stax76 there should be a way to track the all the changes in geometry (crop, addborders, turnleft, turnright, flip etc), and display the final resolution in the TARGET section, next to the fps which BTW is tracked properly!

**Comment by stax76** [comment]
@44vince44 

The main dialog has only a limited amount of room to display such info, if there is too much info then it's also a problem in regard of usablity. In Quality mode there is some room but not in two pass mode. Where exactly would you display this?

Additional to the Preview dialog, script info is also available in the filter list, there is a menu item called _Info_.

**Comment by 44vince44** [comment]
@stax76 yes indeed I forgot that there are other encoding mode that display much more information.
Well until now, only one user has complained, so I guess the workaround will have to be enough !
