### ISSUE TITLE
No audio option is not working

### ISSUE THREAD

**Issue by hani-yassine** [staxrip/staxrip#240]
![Capture](https://user-images.githubusercontent.com/39760468/85233921-b5c1a800-b412-11ea-8ef6-820d14967fe4.PNG)
hello, i'm using StaxRip 2.1.2 and the No audio option is not working the original video have 2 audio i copy one and select No audio for the other (to remove it) but after the encoding both audios are in the resulting video
(i know i can remove it using mkvtoolnix but it would be cool if fixed to skip a step)
Thanks for your great work :)

**Comment by stax76** [comment]
I'll fix it, but why did you use ffmpeg for MKV muxing?

**Comment by stax76** [comment]
New beta which fixes it is online.

**Comment by hani-yassine** [comment]
> I'll fix it, but why did you use ffmpeg for MKV muxing?
> 
> With mkvmerge I cannot reproduce it, I can only reproduce it with the ffmpeg muxer.

thanks for fixing it :) im using ffmpeg to use a custom command "-aspect 16/9" to specify the aspect ration since my tv only play that and there no option in the GUI

**Comment by stax76** [comment]
I still don't understand, the ffmpeg muxer of staxrip does not support custom commands.

**Comment by hani-yassine** [comment]
> I still don't understand, the ffmpeg muxer of staxrip does not support custom commands.

[template.zip](https://github.com/staxrip/staxrip/files/4818383/template.zip)
i dont know the details but here is the template if you want to see i had a 4:3 ratio video and when i put the custom command  "-aspect 16/9" in the encoder option it made them 16:9
