### ISSUE TITLE
Staxrip 2.1.3.0 errors at launch

### ISSUE THREAD

**Issue by mikaljan** [staxrip/staxrip#241]
**Describe the bug**
After upgrading to StaxRip 2.1.3.0 I'm experiencing 4 error messages at launch of StaxRip:
![Annotation 2020-06-22 071145](https://user-images.githubusercontent.com/13774116/85237262-0dcecd80-b458-11ea-9ed5-6765be5ebc03.jpg)
![Annotation 2020-06-22 071209](https://user-images.githubusercontent.com/13774116/85237263-0f989100-b458-11ea-99da-5d3abec423f7.jpg)
![Annotation 2020-06-22 071229](https://user-images.githubusercontent.com/13774116/85237264-10c9be00-b458-11ea-849f-a1280cde5d1e.jpg)
![Annotation 2020-06-22 071247](https://user-images.githubusercontent.com/13774116/85237265-11625480-b458-11ea-8e6b-dc3b31154c53.jpg)

If I revert back to StaxRip 2.0.8.0 then the errors are gone.
I tried reinstalling StaxRip 2.1.3.0 again, and the problem comes back, so I'm sure this is a new issue with the v.2.1.3.0.

**Expected behavior**
Should launch without problem/errors like StaxRip 2.0.8.0

**How to reproduce the issue**
I have Windows 10 Pro on AMD Ryzen 3900x with 32GB RAM & nVidia RTX2080Ti
I have Python 3.8.315.1013
Avisynth v3.6.1
Vapoursynth r50

Just launch and error will occur.

**Provide information**

Please refer to the above pictures.

**Comment by stax76** [comment]
It's because a new version was copied over an old version, staxrip generally does not support this scenario and it also does not try to detect this and warn about it. It's generally not a good idea for any complex app.
