### ISSUE TITLE
A Flash when toggle between tabs of the Video Comparison Tool 

### ISSUE THREAD

**Issue by Globefishp** [staxrip/staxrip#242]
I noticed the Comparison Tool in ver.2.1.3.0 has changed. When I select another tab, the image area will turn white to refresh (maybe) and then show the selected tab. The question is if the two images are not shown continuously, I can't easily tell the difference of them. So it's not convenience for comparison. In old version the tool scan the image progressively, not having this kind of flash. I think that way may be a better solution, though the visible scanning process sometimes annoying.

BTW, the new Comparison Tool don't show OPEN FILEs window when it opens. I need to right click to open files. Could you rollback this behavior to ver.2.0.8.0 which is more simple to use?

Thanks.

**Comment by stax76** [comment]
It took a while to find out how to get it, but yes, both fixed in the next build.
