### ISSUE TITLE
Pipe RAW data using avs2pipemod

### ISSUE THREAD

**Issue by Globefishp** [staxrip/staxrip#243]
**Is your feature request related to a problem? Please describe.**
I try encoding video using Debugmode FrameServer from Adobe Premiere Pro. I find though the data from Frameserver is RGB24, the output data of avs2pipemod sent to x264 is still y4mp, which cannot pipe RGB correctly and throw an error like this:

> avs2pipemod[info]: invoking ConvertToYV24 ...
> avs2pipemod[info]: writing 3063 frames of 24/1 fps, 1920x1080,
>                    sar 0:0, YUV-444-planar-8bit progressive video.
> y4m [info]: 1920x1080p 0:0 @ 24/1 fps (cfr)
> x264 [warning]: --ssim used with psy on: results will be invalid!
> x264 [warning]: --tune ssim should be used if attempting to benchmark ssim!
> x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> x264 [info]: profile High 4:4:4 Predictive, level 5.0, 4:4:4, 8-bit
> y4m [error]: bad frame header magic
> y4m [error]: bad frame header length
> avs2pipemod[info]: total elapsed time is 0.263 sec.
> x264 [info]: frame I:1     Avg QP:23.00  size:  1261
> x264 [info]: mb I  I16..4:  0.0% 100.0%  0.0%
> x264 [info]: 8x8 transform intra:100.0%
> x264 [info]: coded y,u,v intra: 0.0% 0.0% 0.0%
> x264 [info]: i16 v,h,dc,p: 50%  0% 50%  0%
> x264 [info]: i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  0%  0% 100%  0%  0%  0%  0%  0%  0%
> x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu:  0% 44% 56%  0%  0%  0%  0%  0%  0%
> x264 [info]: SSIM Mean Y:1.0000000 (100.000db)
> x264 [info]: kb/s:242.11
> encoded 1 frames, 7.25 fps, 242.11 kb/s
> avs2pipemod[error]: only wrote 3 of 3063 frames.

It seem like the avs2pipemod convert the data to YV24, but then something goes wrong. If ConvertToYV24(matrix="Rec709") added in AVS, avs2pipemod can work well. 

I wonder whether avs2pipemod can pipe RGB24 data to x264 so that the final output can be real RGB. I'm not sure if piping RAW data to x264 is fesible, since there's an --rawvideo option in the pipe tool. But I didn't find where to tweak this setting. 

Will an option be added or a way to customize the command line?

Thanks.

**Comment by stax76** [comment]
At the left bottom in the x264 dialog there is a search field, enter _pipe_ there, this will show you the piping tool option located in the tab Other, there you can use the option None because x264 supports direct avs input, I've tried this with RGB and it works but x264 shows a warning:

resize [warning]: converting from bgra to yuv420p

You can also try the piping tool option ffmpeg.

**Comment by stax76** [comment]
> Will an option be added or a way to customize the command line?

I'll think about it if you post a working avs script and a working encoding command line and the full console output it generates.

**Comment by Globefishp** [comment]
AVS is really simple:
> AviSource("%source_file%", audio=false)

Encoding Command Line:

> avs2pipemod64.exe -y4mp "#Path#\1.avs" | #Path#\x264.exe --crf 19 --preset slower --psy-rd 0.95:0 --aq-mode 2 --aq-strength 0.9 --qcomp 0.7 --qpstep 6 --chroma-qp-offset -1 --cplxblur 5 --merange 40 --bframes 5 --rc-lookahead 48 --colorprim bt709 --colormatrix bt709 --transfer bt709 --output-csp rgb --ssim --deblock 1:-1 --demuxer y4m --frames 3063 --output "#Path#\1_out.h264"

Note: The mentioned warning can be solved by using option in x264 "--output-csp rgb", which allow the encoded video to be in RGB format instead of YUV.

Full Log is here:
[1_staxrip.log](https://github.com/staxrip/staxrip/files/4818987/1_staxrip.log)

Note that the avi is a so-called "signpost" file generated by the FrameServer attached to Premiere Pro, and can't be preprocessed like a normal file(but AviSource can process it correctly, maybe frame by frame). In this case maybe I should manually specify a data format(in x264 and Staxrip can detect the chosen "input-csp" or "output-csp"?), or let Staxrip detect the format of output data by avs?

**Comment by stax76** [comment]
I'm not really understanding what's the problem.

With direct avs input and manual settings you can get what you want?

**Comment by Globefishp** [comment]
Thanks. direct AVS input work perfectly. My original problem is if you use RGB format as AVS output and use avs2pipemod to pass data to x264, Staxrip don't handle it correctlly because the default (and can't be modified) command line of avs2pipemod use "--y4mp" option. I think in this case this option should be disable and be replaced by "--raw". 
It's better to have a way to customize command line of the pipe tool.
But since the direct AVS input work well, you may not add that :).
Thanks.

**Comment by stax76** [comment]
I've uploaded a new beta you can try, by default it uses avs input now for x264 and it has pipe options for raw format. I think there is a bug in avs2pipemod, image was upside down using raw RGB, it works with ffmpeg.
