### ISSUE TITLE
Import error on job after encoding abort and restart

### ISSUE THREAD

**Issue by stgmihnea** [staxrip/staxrip#245]
Hi again, I've noticed a curious issue. I'll often start encoding something and then midway through I'll change my mind and abort the encoding, maybe tweak a couple of settings such as CRF value and then requeue the job with the same name and start again. 

When doing this in Staxrip 2.1.3.0 I get an import error (Staxrip log attached).

In this example I started encoding LST.mp4 at CRF 22 and then it seemed like too much bitrate was being used so I aborted, put CRF 24 instead and requeued. That's when the import error happened:

[LST_staxrip.log](https://github.com/staxrip/staxrip/files/4826428/LST_staxrip.log)

**Comment by stax76** [comment]
What do you mean with import error?

There is something wrong with avisynth and piping, if the script is OK and has worked before then it's difficult to find the reason for this error. I don't see how this is connected to job processing.

```
avs2pipemod[info]: writing 48802 frames of 2997/125 fps, 1280x720,
                   sar 0:0, YUV-420-planar-8bit progressive video.
x265 [error]: unable to open input file <->
```

**Comment by stgmihnea** [comment]
I get many of these "unable to open input file" errors and I have no idea why. I know that if I abort the encode, change a setting and then try to run it again with the same job name I get the error. I sometimes get them from the first try.

What solves them is deleting the temporary folder and starting from scratch. The avisynth filters I use work in the end but they often require more than one try before they do. I'm not sure if this is specifically an avisynth bug of some kind or if something is happening behind the scenes in stax that I don't know about.

**Comment by stax76** [comment]
When you get the error you can open the script with an editor and see if the script is OK.

You can copy the command line in the log file and then start a command prompt from Tools > Advanced and run it there.

In the encoder dialog you can search for pipe and change the piping tool, for that you need the last beta because there were changes lately.

Or you can try vapoursynth at:

Filters > Filter Setup > VapourSynth

**Comment by stgmihnea** [comment]
I've done what you suggested and once I switched the piping tool from avs2pipemod to ffmpeg I stopped having this issue. I'm still testing but even with longer filenames I don't seem to be getting this error now.

Looks like it was avs2pipemod all along.

**Comment by stax76** [comment]
I can report it on the avs2pipemod issue tracker if you are sure that avs2pipmod is causing it.

I assume it only happens under special conditions like with certain avisynth filters because avs2pipimod is used by default in staxrip since a very long time without people reporting issues with it.

**Comment by stgmihnea** [comment]
After more extensive testing it happens with ffmpeg as well but definitely less than with avs2pipemod. 
I'm just confused as to what be the cause, it just looks like Stax does the demuxing and preparation but fails on opening the video file for encoding.

**Comment by Dendraspis** [comment]
Seems to be sort of identical with #397.

Please try the latest beta where this problem could/should be solved.  😃
