### ISSUE TITLE
I don't know how can I test by chapter

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#246]
Hi again

Usually I make mkv 4k or 1080 encoder from BD movies.

Therefore I use a preset h264 o h265 and modify it.  I need to test the film, in other programs I used chapter, I pick up 3 o 4 chapter and test it.

Stax demux my chapter and use to the final file, but I don't find how can I select "all chapter or X chapter"

I usually make a film and when it spend 15 o 20% abort it.  Buy even so I can't or I don' know how to get this file, because when I put to encode again it show me 2 option re-use or recode and I don't know how can record this file.

Apologize for my bad english it's not my mother tongue

**Comment by iAM261917** [comment]
When you abort an encoding task and want to get the encoded file, you can find them in temp folder. Use mkvmergegui (mkvtoolnix) to mux them into .mkv file, or just open it with players, note that pure video streams (.h264 or .hevc) can be buggy sometimes.

Furthermore, staxrip has a feature names "Compressibility Check" that might fit your need, you can find it when toggle to n-pass mode, and the output of this feature can also be found in temp folder.

**Comment by papa-pitufo** [comment]
Many thanks for your answer.

I see the temp folder and find it the file.

But I don' find how to run "n-pass mode" and in x265 option I don't have Comp. check.
Other question, the number of comp check, what does it mean? Chapter? I don't think so, but I ask it.

Best regards and many thanks for your patient

**Comment by iAM261917** [comment]
"Compressibility Check" periodically picks some segments of video and then encode them with **CRF = "Comp. Check" value**, and gives a compressibility value that I'm not understand yet.

I just use it to estimate the bitrate of my result, then I toggle back to CRF mode for the actual encoding.

"N-pass mode" means these two rate control mode here:
![](https://user-images.githubusercontent.com/42721712/85928940-7fd56580-b8e3-11ea-97b6-5d72b5f483f3.png)
And "Comp. Check" option is here:
![](https://user-images.githubusercontent.com/42721712/85928942-819f2900-b8e3-11ea-859a-70488639cd10.png)

**Comment by papa-pitufo** [comment]
Ok, I understand right.

Thank you very much.

Close it.

Tnaks a lot.
