### ISSUE TITLE
The edge enlarging feature in crop window is missing? (since 2.0.8.0)

### ISSUE THREAD

**Issue by iAM261917** [staxrip/staxrip#247]
When do cropping in older versions, there is a small enlarged area in the edge, it's helpful.
![](https://user-images.githubusercontent.com/42721712/85636580-84b3d280-b6b3-11ea-83f0-ca39c3e5428a.jpg)
But since ver. 2.0.8.0, it missing.
![](https://user-images.githubusercontent.com/42721712/85636772-f5f38580-b6b3-11ea-86ed-97d3fd4bf4be.jpg)

Is this a bug? Or is it just be removed for some reason?

**Comment by stax76** [comment]
The renderer was replaced, it's 50 times faster now due to hardware acceleration.

I don't know if it could be done with the new renderer, it's probably difficult.

**Comment by vonH** [comment]
Hmm. That was a really useful feature for the niche case of using RDP (no HW acceleration on remote system) on a 2160p display to crop mostly 720p, 1080p content with dirty borders. Guess I can always import the avs into Staxrip.

**Comment by 44vince44** [comment]
Still there is the possibility to use the keyboard. Maybe @stax76 you should decide whether this is gonna happen one day. If not, then forget about it ?

**Comment by Dendraspis** [comment]
If it should be re-implemented, I would complain if it can't be hidden.   😁

**Comment by JJKylee** [comment]
I believe the newly implemented dark themes by @Dendraspis will make this issue irrelevant.

![StaxRip v2 1 8 2D_DarkMode16_Crop-Window_20210222](https://user-images.githubusercontent.com/3157518/108751397-ff5d1800-74f6-11eb-83a1-9e6c5cb2f0d0.gif)

Expect the grand debut coming soon~! 😆

**Comment by 44vince44** [comment]
I don't remember the old markers. I don't remember if you could grab them and move them with the mouse pointer.
If not, then indeed the new implementation of @Dendraspis should immediately close this thread 😁

**Comment by JJKylee** [comment]
Like I said, I don't think this 'feature' is relevant any more.

**Comment by 44vince44** [comment]
YEPP, and I couldn't agree more... so... who will FINALLY close this 🤣

**Comment by 44vince44** [comment]
I see this is standing ... 🤣

**Comment by Dendraspis** [comment]
I would close it, but @stax76 decides.  😉

**Comment by Dendraspis** [comment]
...and closed!  😁
