### ISSUE TITLE
Staxrip v2.1.3.0 stop using Multithreading?

### ISSUE THREAD

**Issue by mikaljan** [staxrip/staxrip#248]
**Describe the bug**
Staxrip v2.1.3.0 stop using Multithreading?
I switched back to v2.0.8.0 and multithreading is working again, but switching back to v.2.1.3.0 again, and it stop using multithreading.

all the settings were the same, and nothing else was changed except rip versions.

![v2 0 8 0](https://user-images.githubusercontent.com/13774116/85836107-b2d70680-b7c8-11ea-81fa-5d7bd3b0dc7c.jpg)

![v2 1 3 0](https://user-images.githubusercontent.com/13774116/85836134-bf5b5f00-b7c8-11ea-8e9a-c9e0dc460bcc.jpg)

**Comment by stax76** [comment]
staxrip usually only executes console tools, so it's unlike that the issue is caused by staxrip, if there is a problem then it's much likely a console tool that executes it.

**Comment by mikaljan** [comment]
If you look at the output console, you can see under "Input info: " v2.0.8.0 shows "VapourSynthMT r50" while the v2.1.3.0 shows "VapourSynth r50"

Seems like v2.1.3.0 is not using VapourSynth in Multithreading mode

**Comment by stax76** [comment]
Is that NVEnc output? I think there was an MT issue lately in NVEnc. Please see the NVEnc changelog, find the link to the NVEnc website in the apps dialog.

**Comment by mikaljan** [comment]
yes, it seems like that's the NVEnc64 output, maybe I can switch out the NVEnc64.exe from v.2.0.8.0 to v.2.1.3.0 and redo the same encode.

**Comment by Dendraspis** [comment]
> Put default vpy reader back to multi-thread version, the default was accidentaly changed to single thread in NVEnc 5.01 - 5.05.

So you would need one of the latest Beta versions to get MT back. This problem was fixed 2 weeks ago - so after v2.1.3.0 came out.

**Comment by mikaljan** [comment]
> > Put default vpy reader back to multi-thread version, the default was accidentaly changed to single thread in NVEnc 5.01 - 5.05.
> 
> So you would need one of the latest Beta versions to get MT back. This problem was fixed 2 weeks ago - so after v2.1.3.0 came out.

Thanks Dendraspis for the info!
