### ISSUE TITLE
Staxrip Bug on incilization

### ISSUE THREAD

**Issue by MGuimaraesUS** [staxrip/staxrip#249]
Every time when starting staxrip, it starts giving this error, could someone help me?

![image](https://user-images.githubusercontent.com/58942696/85913087-10d70e80-b808-11ea-8ef6-55a12e9a294a.png)

![image](https://user-images.githubusercontent.com/58942696/85913108-395f0880-b808-11ea-80de-5c95ffc09995.png)

![image](https://user-images.githubusercontent.com/58942696/85913109-3ebc5300-b808-11ea-9edb-f7856e45cd52.png)

**Comment by stax76** [comment]
It was reported several times before. It's a user error, avoid copying a new portable app over an old one.
