### ISSUE TITLE
l-smash update

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#25]
l-smash supports now native high bit depth and has a memory issue fixed.

https://forum.doom9.org/showthread.php?p=1879043#post1879043

Should `format = "YUV420P8"` be removed from the l-smash defaults?

**Comment by ofek** [comment]
Any progress on this?

**Comment by stax76** [comment]
yes :-)

https://forum.doom9.org/showthread.php?p=1882197#post1882197
