### ISSUE TITLE
Calling Neo filters unnecessarily invokes non-Neo plugin dlls

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#250]
**Describe the bug**
Currently (as of 2.1.3.7 Beta), calling **Neo f3kdb** and **DFTTest Neo** filters invokes old dlls unnecessarily. (_flash3kyuu_deband.dll_ in AVS for **Neo f3kdb**, _DFTTest.dll_ in VS for **DFTTest Neo**).

**Expected behavior**
These dlls shouldn't be included in the avs/vs code.

**How to reproduce the issue**
AVS/VS filters ⇒ add corresponding filters ⇒ Preview Code...

**Comment by stax76** [comment]
The related code is complex and ugly, it would probably not be easy to fix.

**Comment by stax76** [comment]
There is now a new hotfix online trying to solve it. I hope it works.
