### ISSUE TITLE
Consistency in naming Neo filters family

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#251]
**Is your feature request related to a problem? Please describe.**
Not a problem, but for managing purposes.

**Describe the solution you'd like**
Currently (2.1.3.7 Beta) **Neo f3kdb** and **DFTTest Neo** follow different naming rules: **Neo ...** vs **... Neo**. Unifying the rules will be helpful in managing/adding Neo filters family in the future.

**Comment by stax76** [comment]
It will be _f3kdb Neo_ in the next build, I prefer it this way.

**Comment by JJKylee** [comment]
Sounds good.
