### ISSUE TITLE
Typo in NVEnc generated option string

### ISSUE THREAD

**Issue by softrockstar** [staxrip/staxrip#252]
**Describe the bug**
StaxRip 2.1.3.6
Select Encoder: Nvidia - H.265. Encoder Options -> Deinterlace -> "N Size"
In the window below,  "nszie=[option]" is shown as the option to be passed.

**Expected behavior**
it should be 'nsize' (as part of eg. --vpp-nnedi nsize=32x6)

**How to reproduce the issue**
As above.

**Additional context**
W10 build 18363, GTX 1070, Stax 2.1.3.6

**Please be as clear and as detailed as possible**

**Comment by stax76** [comment]
Will be fixed in the next build.
