### ISSUE TITLE
Add .ec3 audio files support

### ISSUE THREAD

**Issue by koolkunz** [staxrip/staxrip#253]
**Is your feature request related to a problem? Please describe.**
.ec3 files do not show up in the audio selection box when using mkvmerge as the muxer and also if you manually select any .ec3 file a 'Audio format conflicts with container' warning shows up saying mkvmerge does not support .ec3

**Describe the solution you'd like**
mkvmerge works just fine with .ec3 files (.ec3 is same as .eac3 for dolby digital plus files) so you can just add it to the list of supported file types so that we can select the files manually and also make them show up automatically in the audio selection box

**Describe alternatives you've considered**
Currently I just rename the .ec3 file to .eac3 and that works fine. Also if I select ffmpeg as the muxer then .ec3 files can be selected manually without warning although they still do not show up in the audio selection box.

**Explain why the feature matters to you**
It will just remove one unnecessary/extra step from many people's workflow.

**Additional context**
Was unable to attach images here directly so I have uploaded them to extraimage.com
No Warning with FFMPEG: https://extraimage.com/image/L2NlJP
Warning with MKVMERGE: https://extraimage.com/image/L2NdXN
No .ec3 file in selection box: https://extraimage.com/image/L2Nh1m
.eac3 shows up in selection box: https://extraimage.com/image/L2NfNS

**Comment by stax76** [comment]
OK, available in the next build.

**Comment by koolkunz** [comment]
Thanks that was fast!
