### ISSUE TITLE
Attempting to deinterlace using Nvidia - H.265

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#256]
**Describe the bug**
Error attempting to deinterlace and encode Nvidia - H.265 using either nnedi or Yadif (similar error occurs with either)

**Expected behavior**
Should deinterlace without error

**How to reproduce the issue**

Attempt to deinterlace an interlaced video encode with Nvidia - H.265 using either nnedi or Yadif

Error info:

Error Video encoding (2.1.3.7)

Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function

--------------------------- Video encoding ---------------------------

NVEnc 0.5.6.0

X:\StaxRip-x64\Apps\Encoders\NVEnc\NVEncC64.exe --cqp 28:30:32 --codec h265 --output-depth 10 --qp-init 31 --qp-max 33 --qp-min 28 --aq --aq-temporal --bref-mode each --bframes 4 --ref 4 --gop-len 240 --lookahead 16 --slices 2 --multiref-l0 4 --multiref-l1 2 --strict-gop --output-buf 64 --vpp-yadif mode=tff --output-res 984x720 -i X:\VidTemp\Miniseries.to.Series_temp\Miniseries.to.Series.984x720.h265.avs -o X:\VidTemp\Miniseries.to.Series_temp\Miniseries.to.Series.984x720.h265_out.h265

--------------------------------------------------------------------------------
X:\VidTemp\Miniseries.to.Series_temp\Miniseries.to.Series.984x720.h265_out.h265
--------------------------------------------------------------------------------
Please set input interlace field order (--interlace tff/bff) for vpp-yadif.

StaxRip.ErrorAbortException: Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function

--------------------------- Video encoding ---------------------------

NVEnc 0.5.6.0

X:\StaxRip-x64\Apps\Encoders\NVEnc\NVEncC64.exe --cqp 28:30:32 --codec h265 --output-depth 10 --qp-init 31 --qp-max 33 --qp-min 28 --aq --aq-temporal --bref-mode each --bframes 4 --ref 4 --gop-len 240 --lookahead 16 --slices 2 --multiref-l0 4 --multiref-l1 2 --strict-gop --output-buf 64 --vpp-yadif mode=tff --output-res 984x720 -i X:\VidTemp\Miniseries.to.Series_temp\Miniseries.to.Series.984x720.h265.avs -o X:\VidTemp\Miniseries.to.Series_temp\Miniseries.to.Series.984x720.h265_out.h265

--------------------------------------------------------------------------------
X:\VidTemp\Miniseries.to.Series_temp\Miniseries.to.Series.984x720.h265_out.h265
--------------------------------------------------------------------------------
Please set input interlace field order (--interlace tff/bff) for vpp-yadif.

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 372
   at StaxRip.NVEnc.Encode() in D:\Projekte\VB\staxrip\Encoding\NVEnc.vb:line 90
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 312

**Comment by stax76** [comment]
> Please set input interlace field order (--interlace tff/bff) for vpp-yadif.

The error tells you exactly what's wrong.

In the search field in the left bottom of the dialog enter:

` --interlace`

**Comment by noblemd00** [comment]
Done that - The setting has to be set in order to activate Yadif (Auto, TFF, BFF, etc.) does not work no matter how deinterlace options are set. Same error occurs regardless of settings - have tried all.  It is as if the setting is not being passed to the function.

Similar error occurs with nnedi regardless of settings.

**Comment by Dendraspis** [comment]
Indeed, you set up a DEINTERLACE filter to work before the encoding, but then you have to tell the encoder, that the input differs and in which way.

But I would also need a few attempts to figure out where this setting is.  😄  Especially "*for vpp-yadif*" would lead me in the wrong direction. Maybe it could be a good idea to extend the message to push the user in the right direction:
*Please set the input interlace field order (--interlace tff/bff) for vpp-yadif **in the encoder settings**.*

**Comment by crisc2000** [comment]
> OK - That is a totally different setting - In a totally different location from Deinterlace - A NOTIFICATION should warn the user that this setting must ALSO be set - An ERROR should not occur. Perhaps even a duplicate of this setting in the DEINTERLACE section is appropriate.
> 
> Perhaps you as the programmer understood the warning, but I, as a user, thought the warning was referring to DEINTERLACE settings not a separate setting elsewhere in the program. After all, I was setting up DEINTERLACE.

I had the same problem, and fixed by googling and finding this page. I totally agree with @Dendraspis is saying. That interlace setting in a different place then Deinterlace is counter intuitive.
