### ISSUE TITLE
The character "+" is no longer supported

### ISSUE THREAD

**Issue by D0LLYNH0** [staxrip/staxrip#257]
**Describe the bug**
Whenever the character "+" is used, I get an error of "Incorrect function"

_Input file:_
![Input file](https://user-images.githubusercontent.com/67797325/86488395-39df2e00-bd37-11ea-9e2e-004cb14d0de9.png)

_Output file:_
![Output file](https://user-images.githubusercontent.com/67797325/86488397-3b105b00-bd37-11ea-8b75-fc813c0e6775.png)

_Tag video:name in the container:_
![Tags in the container](https://user-images.githubusercontent.com/67797325/86488399-3b105b00-bd37-11ea-9bb1-5fb8e5c18e40.png)

_Track name:_
![Track name](https://user-images.githubusercontent.com/67797325/86488401-3ba8f180-bd37-11ea-92b3-1e3b10124e71.png)

**Expected behavior**
Should accept the "+" character as in the penultimate published stable version (2.0.8.0).

**Note**
- Until the penultimate stable version this problem does not occur. (2.0.8.0)
- I don't know in which specific version this problem started, because I don't follow the beta versions. So for me the problem occurs from the latest stable version (2.1.3.0)
- To reproduce the prints, I used the last beta version released (2.1.3.7)

**Comment by stax76** [comment]
Likely a MP4Box issue, try replacing it.

**Comment by D0LLYNH0** [comment]
Perfect, you got it right!
As of version "**1.0.0-rev16-g10dd6533a**", the character "+" is no longer accepted.

The last version that worked was "**0.8.0-rev178-g44c48d630**".

**Comment by stax76** [comment]
Maybe you can also report it on the MP4Box tracker, I'm currently trying to have a break.

**Comment by Patman86** [comment]
I'll upload a new version of MP4Box tonight. The issue should be solved.

**Comment by Patman86** [comment]
@Dendraspis pls close #270 too, it's not possible for me ^^

**Comment by Dendraspis** [comment]
@Patman86  Sure, it's done.  🙂
