### ISSUE TITLE
Warning Message Typo

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#259]
**Describe the bug**
There's a typo in the pop-up warning message for trying to re-encode a video stream. (2.1.3.7)

![StaxRip_2 1 3 7_warning_message_typo_20200705](https://user-images.githubusercontent.com/3157518/86548985-21b40e00-bef3-11ea-8b0a-d933b456e4f8.jpg)

**Expected behavior**
It should be '**A**', not '**An**'.

**Comment by Dendraspis** [comment]
Fixed - can be closed.  🔐
