### ISSUE TITLE
Indexing using ffmsindex failed with exit code: -1073741701 (0xC000007B)

### ISSUE THREAD

**Issue by ENunn** [staxrip/staxrip#26]
trying to get this amarec file working with staxrip and it throws me an error

> Error Indexing using ffmsindex (2.0.2.4)
> 
> Indexing using ffmsindex failed with exit code: -1073741701 (0xC000007B)
> 
> The exit code might be a system error code: {Bad Image}
> hs is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0x
> 
> 
> ----------------------- Indexing using ffmsindex -----------------------
> 
> "C:\Program Files (x86)\AviSynth+\plugins64+\ffmsindex.exe" "D:\amarec\amarec(20190711-1259).avi" "D:\amarec\amarec(20190711-1259)_temp\amarec(20190711-1259).ffindex"
> 
> 
> 
> 
> StaxRip.ErrorAbortException: Indexing using ffmsindex failed with exit code: -1073741701 (0xC000007B)
> 
> The exit code might be a system error code: {Bad Image}
> hs is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0x
> 
> 
> ----------------------- Indexing using ffmsindex -----------------------
> 
> "C:\Program Files (x86)\AviSynth+\plugins64+\ffmsindex.exe" "D:\amarec\amarec(20190711-1259).avi" "D:\amarec\amarec(20190711-1259)_temp\amarec(20190711-1259).ffindex"
> 
> 
> 
>    at StaxRip.Proc.Start()
>    at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Project proj)
>    at StaxRip.MainForm.Indexing()
>    at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath)
>    at StaxRip.MainForm.ModifyFilters()
>    at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding)

Not  sure what the deal is. Log is attached.  Any help? Thanks!

[amarec(20190711-1259)_staxrip.log](https://github.com/staxrip/staxrip/files/3388278/amarec.20190711-1259._staxrip.log)

**Comment by 44vince44** [comment]
Check this issue number 18:
[issue number 18](https://github.com/staxrip/staxrip/issues/18)

**Comment by YinnVI** [comment]
> Error Indexing using ffmsindex (2.0.2.4)

Indexing using ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


----------------------- Indexing using ffmsindex -----------------------

D:\Staxrip.2.0.2.4.x64\v4.8\Apps\Plugins\Both\FFMS2\ffmsindex.exe "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv" "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).ffindex"

Writing index... Error writing index: Failed to open 'D:\Torrent\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01ï½ž02è©± (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC).ffindex'



StaxRip.ErrorAbortException: Indexing using ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


----------------------- Indexing using ffmsindex -----------------------

D:\Staxrip.2.0.2.4.x64\v4.8\Apps\Plugins\Both\FFMS2\ffmsindex.exe "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv" "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).ffindex"

Writing index... Error writing index: Failed to open 'D:\Torrent\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01ï½ž02è©± (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC).ffindex'


   at StaxRip.Proc.Start()
   at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Project proj)
   at StaxRip.MainForm.Indexing()
   at StaxRip.MainForm.Demux()
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding)

**Comment by stax76** [comment]
There is a new build, maybe it works better, if ffms2 fails you can also try l-smash.

https://forum.doom9.org/showthread.php?p=1882197#post1882197
