### ISSUE TITLE
Strongly suggest to set DGIndex as default

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#263]
Hi Stax, I know you're getting some rest now.
Just to leave this suggestion here: D2V Witch is causing many issues (usually with fps), and DGIndex works better.
Maybe you should consider putting DGIndex back as default ?
I know we can set it in the settings, but just suggesting to put it as default in order to avoid users having problems ....

**Comment by Dendraspis** [comment]
> I know we can set it in the settings, but just suggesting to put it as default in order to avoid users having problems ....

Don't forget there are some circumstances where you (or StaxRip) have to reset your settings - so you have to keep in mind change the setting after such situation to not run into potential issues.

I would support your suggestion. :slightly_smiling_face:

**Comment by Dendraspis** [comment]
Yepp, I can confirm via code, that D2VWITCH is disabled by default whereas DGIndex is enabled.
So I think everything is OK except the documentation.  😄

**Comment by 44vince44** [comment]
Ah! thanks for checking with 2.1.3.7 @Dendraspis !!! I didn't have much time to test 2.1.3.7 yet (working on a PE Boot project for 10 days, which leaves me not much time).
So I may close this thread once you've read my answer.

**Comment by Dendraspis** [comment]
No worry, I'm *watching* this repository.  😁 

Let's see if stax76 (not mentioned on purpose!) will merge my PR to extend the update checker - could make it easier to stay up to date for some (or even many) users. ⁉️ 

> PE Boot project

..sounds interesting.  😮

**Comment by 44vince44** [comment]
Ok so I wil close it ;-)

> ..sounds interesting. 😮

Ih yeas it is, every 3-4 years a do a new build with things updated. The possibility to have your windows booting from a USB key, so you can work on any computer with it, without having to install anything on the computer. Of course I have Stax's mpv.net running on it and obviously staxrip ;-)
