### ISSUE TITLE
use ffmpeg to convert ,notice an error

### ISSUE THREAD

**Issue by thisisjin** [staxrip/staxrip#270]
![image](https://user-images.githubusercontent.com/22115417/86861901-b9377d80-c0fa-11ea-9452-44a43fc18ac6.png)
![image](https://user-images.githubusercontent.com/22115417/86861911-bdfc3180-c0fa-11ea-9eae-e487a503a215.png)

**Comment by 44vince44** [comment]
I confirm the bug. 
At first glance it seems that quality and threads are not specified, so I tried:

ffmpeg N-98276-g1d5d8a30b4-g842bc312ad-gcc10.1.0 Patman

"C:\Program Files\StaxRip\Apps\Encoders\ffmpeg\ffmpeg.exe" -i C:\Temp\_StaxRip\Ute_temp\Ute.avs -c:v libx264 -crf 26 -threads 8 -an -y -hide_banner C:\Temp\_StaxRip\Ute_temp\Ute_out.h264

C:\Temp\_StaxRip\Ute_temp\Ute.avs: Unknown error occurred

StaxRip.ErrorAbortException: Video encoding x264 returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function


------------------------- Video encoding x264 -------------------------

ffmpeg N-98276-g1d5d8a30b4-g842bc312ad-gcc10.1.0 Patman

"C:\Program Files\StaxRip\Apps\Encoders\ffmpeg\ffmpeg.exe" -i C:\Temp\_StaxRip\Ute_temp\Ute.avs -c:v libx264 -crf 26 -threads 8 -an -y -hide_banner C:\Temp\_StaxRip\Ute_temp\Ute_out.h264

C:\Temp\_StaxRip\Ute_temp\Ute.avs: Unknown error occurred


   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 372
   at StaxRip.ffmpegEnc.Encode(String args) in D:\Projekte\VB\staxrip\Encoding\ffmpegEnc.vb:line 138
   at StaxRip.ffmpegEnc.Encode() in D:\Projekte\VB\staxrip\Encoding\ffmpegEnc.vb:line 123
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 309

**Comment by 44vince44** [comment]
I think maybe @Patman86 didn't have the x264 libraries when you compiled ffmeg ?

@thisisjin in the mean time use x264 codex, it's superior to ffmpeg x264 !

**Comment by Patman86** [comment]
I always compile ffmpeg with x264 libraries! I uploaded a [new version](https://www.mediafire.com/folder/9gxbsrup4j872/StaxRip_Universe#vkt2ckzjvt0qf) and tested it with x264 settings, everything is fine.

**Comment by 44vince44** [comment]
@Patman86  Yes indeed I confirm everything works fine! Thank you very much Patman!

@thisisjin you can update the FFMPEG version in staxrip, but first, before doing anything, you MUST install Avisynth on your system because this version of Staxrip you are using does not support completely portable Avisynth.

**Comment by thisisjin** [comment]
@

> @Patman86 Yes indeed I confirm everything works fine! Thank you very much Patman!
> 
> @thisisjin you can update the FFMPEG version in staxrip, but first, before doing anything, you MUST install Avisynth on your system because this version of Staxrip you are using does not support completely portable Avisynth.

thanks

**Comment by Patman86** [comment]
closed

**Comment by Patman86** [comment]
closes #270

**Comment by Patman86** [comment]
close #270
