### ISSUE TITLE
Add "open single file" command to the menu editor (shortcut to open single file)

### ISSUE THREAD

**Issue by hani-yassine** [staxrip/staxrip#275]
hello the default behavior for open video file is opening a menu like this:
![Capture2](https://user-images.githubusercontent.com/39760468/87550213-799f0180-c6b7-11ea-9eb1-dd9ec423d2a2.PNG)
i always select single file so it would be very useful if you can add a "OpenSingleFile" command in the menu editor here:
![Capture](https://user-images.githubusercontent.com/39760468/87550294-94717600-c6b7-11ea-8dc0-14b85430e31f.PNG)
instead of the  "ShowOpenSourceDialog", or make a tick box "remember my choice" that will be very useful so i use the keyboard shortcut to immediately open a video file, Thanks for your hard work!

**Comment by Dendraspis** [comment]
Pull Request is waiting to be merged.

But wouldn't it be faster for you to create a context menu entry for media files to open them directly with StaxRip?

**Comment by hani-yassine** [comment]
> Pull Request is waiting to be merged.
> 
> But wouldn't it be faster for you to create a context menu entry for media files to open them directly with StaxRip or use Drag&Drop?

not sure what is this context menu but what i would like a shortcut to open explorer browser and select a file like all programs with open file

**Comment by Dendraspis** [comment]
I mean the context menu (right click) on a file on Desktop or in Explorer. 

The feature is waiting to be included - maybe in the next beta version.

**Comment by 44vince44** [comment]
@hani-yassine it seems that Stax is on a break now for some time, so this request could take some time. In the meanwhile, why don't you use drag and drop as @Dendraspis suggests?

**Comment by hani-yassine** [comment]
> @hani-yassine it seems that Stax is on a break now, so this request could take some time. In the meanwhile, why don't you use drag and drop as @Dendraspis suggests?

well hopefully he add this feature when he is back :) im opening 1 file and 1 subtitle at a time (because im burning in subs) so using ctrl+g for dialog menu then selecting single file and sub file with ctrl+h is faster then drag and drop (because selecting a video file and subs and dragging them only open the video)
