### ISSUE TITLE
fail to Index dvd vob

### ISSUE THREAD

**Issue by hintlou** [staxrip/staxrip#278]
Some vobs failed to be indexed after I updated to v2.1.3.0.
Now I used v2.1.3.7. Some vobs failed to be indexed,too.

I have to remux the vob to mkv for indexing to staxrip.

the  log:

------------------------- System Environment -------------------------

StaxRip    : 2.1.3.7
Windows    : Windows 7 Ultimate
Language   : Chinese (Simplified, PRC)
CPU        : Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
GPU        : Intel(R) HD Graphics Family, Oray Display Mirror Driver, NVIDIA GeForce GT 720M
Resolution : 1366 x 768
DPI        : 96

----------------------- Media Info Source File -----------------------

E:\Downloads\ybrq.VOB

General
Complete name             : E:\Downloads\ybrq.VOB
Format                    : MPEG-PS
File size                 : 301 MiB
Duration                  : 4 min 14 s
Overall bit rate mode     : Variable
Overall bit rate          : 9 908 kb/s

Video
ID                        : 224 (0xE0)
Format                    : MPEG Video
Format version            : Version 2
Format profile            : Main@Main
Format settings           : CustomMatrix / BVOP
Format, BVOP              : Yes
Format, Matrix            : Custom
Format, GOP               : Variable
Format, picture structure : Frame
Duration                  : 4 min 14 s
Bit rate mode             : Variable
Bit rate                  : 8 175 kb/s
Maximum bit rate          : 9 800 kb/s
Width                     : 720 pixels
Height                    : 480 pixels
Display aspect ratio      : 4:3
Frame rate                : 29.970 (30000/1001) FPS
Standard                  : NTSC
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Interlaced
Scan order                : Top Field First
Compression mode          : Lossy
Bits/(Pixel*Frame)        : 0.789
Time code of first frame  : 01:18:48:17
Time code source          : Group of pictures header
Stream size               : 248 MiB (83%)

Audio
ID                        : 189 (0xBD)-160 (0xA0)
Format                    : PCM
Format settings           : Big / Signed
Muxing mode               : DVD-Video
Duration                  : 4 min 14 s
Bit rate mode             : Constant
Bit rate                  : 1 536 kb/s
Channel(s)                : 2 channels
Sampling rate             : 48.0 kHz
Bit depth                 : 16 bits
Delay relative to video   : -204 ms
Stream size               : 46.7 MiB (16%)

Menu

---------------- Error D2V Witch: Demux & Index MPEG-2 ----------------

D2V Witch: Demux & Index MPEG-2 returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

函数不正确。

------------------- D2V Witch: Demux & Index MPEG-2 -------------------

D2V Witch v4

"E:\KKBOX\StaxRip-x64-2.1.3.7-beta\Apps\Support\D2V Witch\d2vwitch.exe" --audio-ids all --output "E:\Downloads\ybrq_temp\ybrq.d2v" "E:\Downloads\ybrq.VOB"

------------------- D2V Witch: Demux & Index MPEG-2 -------------------

D2V Witch v4

"E:\KKBOX\StaxRip-x64-2.1.3.7-beta\Apps\Support\D2V Witch\d2vwitch.exe" --audio-ids all --output "E:\Downloads\ybrq_temp\ybrq.d2v" "E:\Downloads\ybrq.VOB"

Start:    22:56:50
End:      22:56:56
Duration: 00:00:06

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: D2V Witch: Demux & Index MPEG-2 returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

函数不正确。

------------------- D2V Witch: Demux & Index MPEG-2 -------------------

D2V Witch v4

"E:\KKBOX\StaxRip-x64-2.1.3.7-beta\Apps\Support\D2V Witch\d2vwitch.exe" --audio-ids all --output "E:\Downloads\ybrq_temp\ybrq.d2v" "E:\Downloads\ybrq.VOB"

   在 StaxRip.Proc.Start() 位置 D:\Projekte\VB\staxrip\General\Proc.vb:行号 372
   在 StaxRip.CommandLineDemuxer.Run(Project proj) 位置 D:\Projekte\VB\staxrip\General\Demux.vb:行号 154
   在 StaxRip.MainForm.Demux() 位置 D:\Projekte\VB\staxrip\Forms\MainForm.vb:行号 3268
   在 StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) 位置 D:\Projekte\VB\staxrip\Forms\MainForm.vb:行号 2108

**Comment by Dendraspis** [comment]
Have you already tried **DGIndex** instead of **D2V Witch** ?

![StaxRipVOB](https://user-images.githubusercontent.com/50659978/87806759-a9850b00-c857-11ea-93cb-4eaec9977322.JPG)

**Comment by hintlou** [comment]
Solved.Thanks!

**Comment by 44vince44** [comment]
The same issue again. It seems that people who don't use FRESH settings still have D2V Witch enabled...

**Comment by stax76** [comment]
I changed the default back to DGIndex, this was missing in the changelog but now it's also in changelog due to pull request by Dendraspis.
