### ISSUE TITLE
Failed to initialize VapourSynth, but the .vpy plays fine

### ISSUE THREAD

**Issue by Vrael0n** [staxrip/staxrip#281]
After successfully demuxing and indexing StaxRip presents the error "Script Error   Failed to initialize VapourSynth". I believe this is a StaxRip bug and not Vapoursynth bug as I can play the .vpy script in the video's _temp folder with MPC-BE without issues (showing Python and Vapoursynth are functioning). I've enabled "Enable debug logging" and "Write Event Commands to log file" but StaxRip is not writing logs for this error in StaxRip-2.1.3.0\Settings\Log Files and the log in the _temp folder of input media does not define the error and ends with the contents of the .vpy file being written to it.

System software:
Staxrip: 2.1.3.0 and 2.1.3.7-beta tested
Vapoursynth: R50 (internal and external tested)
Python: 3.8.4-64bit and 3.7.8-64bit tested
Windows 10 Pro 1909 (build 18363.959)

System hardware:
CPU: R9 3950X (AVX2)
RAM: 32GB 3200MHz
GPU: GTX 1080Ti

staxrip.log:
------------------------ Error opening source ------------------------

Failed to initialize VapourSynth

import os, sys
import vapoursynth as vs
core = vs.get_core()
sys.path.append(r"C:\Users\User\Desktop\Random\Util\StaxRip-2.1.3.0\Apps\Plugins\VS\Scripts")
core.std.LoadPlugin(r"C:\Users\User\Desktop\Random\Util\StaxRip-2.1.3.0\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll", altsearchpath=True)
clip = core.lsmas.LWLibavSource(r"E:\OBS Capture\2020-07-24 12-22-22.mkv", cachefile=r"E:\OBS Capture\2020-07-24 12-22-22_temp\2020-07-24 12-22-22.lwi", prefer_hw=3)
#clip = core.std.AssumeFPS(clip, None, 25, 1)
clip.set_output()

**Comment by stax76** [comment]
This will very likely be very difficult to debug since it only happens on your system and nobody really knows what to do about it. Errors that are not reproducible on a developer machine are typically very hard to find.

The best thing to do here is adding back VFW/avifile support as alternative way to access avisynth and vapoursynth so staxrip supports two methods for accessing avisynth and vapoursynth.

So you can try if staxrip 2.0.6.0 works with installed VapourSynth, this was the last VFW/avifile based version.

**Comment by Vrael0n** [comment]
I did some further digging and installed Staxrip on another PC. Eventually I found what causes this bug, just not how. Uninstalling Vapoursynth/Python and reinstalling their latest stable releases, even if reversed, will cause Staxrip to be unable to use Vapoursynth. Even re-enabling "Use included portable VapourSynth" (which uses an internal Python as well) does not fix the problem.

Perhaps newer Python versions changed something that leaves a permanent effect on the system or install directory structure? Also, MPC-BE can play the .vpy script on that system as well, so whatever change was made does not break other applications like it does to Staxrip.

For reference these are the Installers I used:
https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64.exe
https://github.com/vapoursynth/vapoursynth/releases/download/R50/VapourSynth64-R50.exe

**Comment by stax76** [comment]
OK, I will try to reproduce it, tomorrow if I have time.

**Comment by stax76** [comment]
I've installed python-3.8.5, it's still working here.

What you can try is staxrip 2.0.6.0.

And you can try mpv and mpv.net with following config:

https://github.com/stax76/mpv.net/blob/master/Manual.md#playback-of-vapoursynth-scripts

**Comment by Vrael0n** [comment]
I've downloaded your MPV (mpv.net-portable-x64-5.4.8.0) and when I copy the contents of Staxrip's .\Apps\FrameServer\VapourSynth (Python and Vapoursynth) folder into mpv.net's folder it plays Staxrip's .vpy perfectly. Whatever is going on here appears to be exclusive to Staxrip.

**Comment by stax76** [comment]
I'm working on VFW support.

**Comment by Vrael0n** [comment]
I have confirmed that 2.0.6.0 works, but what exactly is VFW? All I can find is this http://www.vapoursynth.com/2012/09/r10-vfw-enters-the-scene-from-the-left/ which references AviSynth a lot. Dose this mean I will lose the benefits of Vapoursynth? (proper native 10bit support and better multi-threading)

**Comment by stax76** [comment]
There shouldn't be a disadvantage except staxrip not knowing what color space is used and portable mode not being available. There are only 3 info features that use the color space:

1. The info in the preview
2. The info dialog in the context menu of the filters
3. Script info in the log file

When VFW is used in these 3 locations staxrip just shows Unknown as color space but you can still find out the color space at:

Code Editor > Context Menu > Advanced Info

This will show the color space via external tool, in case of VapourSynth via vspipe.

So it's only a minor disadvantage.

There will be two new settings:

Main Menu > Tools > Settings > Frameserver > AviSynth > Use installed AviSynth via VFW

Main Menu > Tools > Settings > Frameserver > VapourSynth > Use installed VapourSynth via VFW

We still can create an issue on the VapourSynth tracker, maybe the VapourSynth author has some ideas how the cause can be found.

I finished it today but before I commit and upload it I want to test it some more. It should be online tomorrow.

**Comment by stax76** [comment]
The new beta is online now, I did 2 things to address your issue.

1. Add a VFW mode (requires avisynth being installed), there is no color space display limitation, I found out how to support it for VFW.

2. In case the problem was a missing VC++ DLL I added a VC++ all in one package under Apps/Support/VC, staxrip adds this folder as process wide env var so the OS can find it.

I hope it works.

**Comment by Vrael0n** [comment]
I have good and bad news, VFW works perfectly, but I have found out why Vapoursynth was not working. The problem was a workaround for an old NVENC bug (now fixed) that required vsscript.dll to be copied to System32. I had forgotten about it as I did it over a year ago and it fixed a bug. This is why both machines I tried to debug with had the same problem. Not sure why this would effect the included Vapoursynth with its own vsscript.dll but it did. Apologies for potentially wasted time.

**Comment by stax76** [comment]
OK, no problem. I think a better workaround would have been to modify the path env var, this is somehow advanced.

I think my implementation does not load vsscript.dll with full path but only with filename and the OS finds it because staxrip modifies the path env var.
