### ISSUE TITLE
FFmpeg nvenc no working

### ISSUE THREAD

**Issue by kebinzhi** [staxrip/staxrip#285]
version 2.1.3.7
![Snipaste_13-06-23](https://user-images.githubusercontent.com/20044735/88621868-1019ec80-d0d4-11ea-8c8b-ed47610db7a7.png)

**Comment by Dendraspis** [comment]
Why don't you use NVENC directly?

**Comment by kebinzhi** [comment]
> Why don't you use NVENC directly?

1、for transcoding speed,ffmpeg nvenc is faster.
2、for variable frame rate video, there is a problem that the audio and video are not synchronized.

**Comment by Dendraspis** [comment]
1. When it's faster, than just because of a lower resulting quality.
2. Okay, that's a reason.

***I would strongly suggest using constant FPS and native NvEnc.***
Variable framerate will save just a few MB, but on the other side it gives you a bunch of issues and problems and it prevents many post production possibilties, like swapping audio, add/change subtitles, re-encoding video, ... 

Let's see if anybody else can help you with this problem.

**Comment by kebinzhi** [comment]
> 1. When it's faster, than just because of a lower resulting quality.
> 2. Okay, that's a reason.
> 
> _**I would strongly suggest using constant FPS and native NvEnc.**_
> Variable framerate will save just a few MB, but on the other side it gives you a bunch of issues and problems and it prevents many post production possibilties, like swapping audio, add/change subtitles, re-encoding video, ...
> 
> Let's see if anybody else can help you with this problem.

I use ffmpeg nvenc just for speed, I don’t care about the picture quality.Because I just use these videos for preview in premiere.
I like constant FPS,but some videos that I downloaded is vfr by default.
Thank you for the reply.

**Comment by kebinzhi** [comment]
> 1. When it's faster, than just because of a lower resulting quality.
> 2. Okay, that's a reason.
> 
> _**I would strongly suggest using constant FPS and native NvEnc.**_
> Variable framerate will save just a few MB, but on the other side it gives you a bunch of issues and problems and it prevents many post production possibilties, like swapping audio, add/change subtitles, re-encoding video, ...
> 
> Let's see if anybody else can help you with this problem.

![image](https://user-images.githubusercontent.com/20044735/88657481-94846380-d104-11ea-91a5-6c849cb6b824.png)
I set -q:v to a negative number,the problem is solved.

**Comment by 44vince44** [comment]
Confirmed: I made three tests with the same file: quality 7, 20, and 28.
They all have the same output video Kbps. It confirms that quality is not working.

From the log file:
WARNING: defaulting hwaccel_output_format to cuda for compatibility with old commandlines. This behaviour is DEPRECATED and will be removed in the future. Please explicitly set "-hwaccel_output_format cuda".

I'm afraid the command line is deprecated. It need updating...

**Comment by stax76** [comment]
For me it's difficult because I don't have nvenc compatible hardware.

There is currently a thread at doom9 where people use h264_nvenc:

https://forum.doom9.org/showthread.php?t=181550

**Comment by Dendraspis** [comment]
@44vince44 
Could you try to add a custom parameter `-cq:v 10` and tell us if the result changes?  I think the quality parameter is wrong.

**Comment by kebinzhi** [comment]
> -cq:v 10

![image](https://user-images.githubusercontent.com/20044735/88680969-a6293380-d123-11ea-8eda-7d46a7235349.png)

nothing changed,the q value is always 50.

**Comment by Dendraspis** [comment]
So maybe more parameters are needed to enable non-default-settings.  🤔 

Could you also check this: `-rc:v vbr_hq -cq:v 10`

**Comment by 44vince44** [comment]
OK here is the answer to @Dendraspis and @kebinzhi 

![SNAG-0008](https://user-images.githubusercontent.com/17828567/88682599-854ce800-d0fb-11ea-99d0-4cce120c167c.jpg)

@kebinzhi  use this method and it will work!

**Comment by Dendraspis** [comment]
@44vince44 
Oh boy, looks like a nightmare to realize - but 100 points for the illustration.  😄 
Yes, `:v` is just a stream specifier to affect video only.

**Comment by kebinzhi** [comment]
> OK here is the answer to @Dendraspis and @kebinzhi
> 
> ![SNAG-0008](https://user-images.githubusercontent.com/17828567/88682599-854ce800-d0fb-11ea-99d0-4cce120c167c.jpg)
> 
> @kebinzhi use this method and it will work!
> 
> @Dendraspis I guess cq and cq:v are the same. But you still need to remore the -rc constqp

it works, thank you very much.

**Comment by 44vince44** [comment]
@Dendraspis LOL ;-) an illustration is worth pages of exxplanations !

I got the information from [nvidia dev](https://developer.nvidia.com/ffmpeg) 

But I'm always surprised of how difficult it is to get documentation.
For instance the -bf and g parameters, what are they ?

**Comment by Dendraspis** [comment]
@44vince44 
You used 4 arrows/pointers and technical expressions - so it fits.  😄  But good work!
It is - and how often solved problems don't work anymore because of (slightly) changed parameters or so.

I'm curious if @stax76 is going to extend/improve to UI.  🙂  🍻

**Comment by 44vince44** [comment]
@Dendraspis 
Don't think it takes time to do the illustrations. I use a tool from Techsmith (Snagit, Snagit studio), it allows screen captures and easy annotations. And there are many other tools for that. In that case it took me less than 1 minute. Maybe if i spent more time, it would look less messy ;-)
@stax76 is enjoying summer right now (i think so). But he did agree it has to be fixed ! Right Stax?

**Comment by Dendraspis** [comment]
@44vince44   Just take it!  😛 
I know he is on a break - that I'm disturbing continuously 🙄 , but I meant in the (far) future.  At least it has *Priority Low*.  😁 


Sorry, but because I will never use ffmpeg for encodes, I'm not gonne try to fix it by myself.

**Comment by stax76** [comment]
I hope this was it:

https://github.com/staxrip/staxrip/commit/2b4ab460c32c8abf811ca964bbce812eae1e1738

**Comment by Dendraspis** [comment]
@stax76 
It could be helpful to release a new official beta version - also regarding some past fixes.

**Comment by kebinzhi** [comment]
> I hope this was it:
> 
> [2b4ab46](https://github.com/staxrip/staxrip/commit/2b4ab460c32c8abf811ca964bbce812eae1e1738)

@stax76 @44vince44 @Dendraspis  if the rate control is constqp, -qp worked.
![image](https://user-images.githubusercontent.com/20044735/88705369-04650f00-d142-11ea-84f6-51f728f30296.png)

**Comment by Dendraspis** [comment]
@kebinzhi 
`qp` if different from `cq`

**Comment by kebinzhi** [comment]
> @kebinzhi
> `-qp` if different from `-cq`
> 
> `-qp` = Constant QP [therefore you need `-rc constqp`]
> `-cq` = Constant Quality (CRF)

![Snipaste_03-37-15](https://user-images.githubusercontent.com/20044735/88714414-611af680-d14f-11ea-8b27-3ebbea247002.png)

is there a bug with this value?I used this value in another ffmpeg converter,it works.
but,it can not change the vfr to cfr in staxrip ffmpeg.

**Comment by kebinzhi** [comment]
> > @kebinzhi
> > `-qp` if different from `-cq`
> > `-qp` = Constant QP [therefore you need `-rc constqp`]
> > `-cq` = Constant Quality (CRF)
> 
> ![Snipaste_03-37-15](https://user-images.githubusercontent.com/20044735/88714414-611af680-d14f-11ea-8b27-3ebbea247002.png)
> 
> is there a bug with this value?I used this value in another ffmpeg converter,it works.
> but,it can not change the vfr to cfr in staxrip ffmpeg.

**Comment by stax76** [comment]
Is it solved by the last beta?

**Comment by 44vince44** [comment]
According to what @kebinzhi and @Dendraspis found, it isn't!
you must create 2 cases:
if rate control =Const qp use -qp for quality value
else use -cq for quality value

am I right guys?

**Comment by Dendraspis** [comment]
I would say ***yes***.   👍   

The big questio is:  how many cases are necessary to get all correct parameters in line?!  😆

**Comment by kebinzhi** [comment]
> @stax76
> 
> According to what @kebinzhi and @Dendraspis found, it isn't!
> you must create 2 cases:
> 
> * if rate control =Constqp then use -qp for quality value
> * else use -cq for quality value
> 
> am I right guys?

![image](https://user-images.githubusercontent.com/20044735/88761126-11651b00-d1a1-11ea-96f7-769af274a214.png)
@stax76 my test.

**Comment by kebinzhi** [comment]
@stax76 
2.1.3.8 version.
missing ffmpeg nvidia.
![image](https://user-images.githubusercontent.com/20044735/88766336-6eb19a00-d1aa-11ea-91e7-2152f0d4c9be.png)

**Comment by 44vince44** [comment]
> 
> 
> I would say _**yes**_. 👍
> 
> The big questio is: how many cases are necessary to get all correct parameters in line?! 😆

How about REMOVING options that are not interesting. The user can always use the CUSTOM switches.
That would leave only 2 or 3 selectable options. More than enough, don't you agree?

About the "error" pointed out by @kebinzhi, the deprecated syntax:
This error is related to DECODING with NVIDIA. It doesn't appear when decoding is set to AviSynth/Vapoursynth.
So syntax must be changed from **-hwaccel cuvid** to **-hwaccel_output_format cuda**,   of course when ffmpeg/nvidia selected as decoder.
Also I guess it should be the same with Nvidia/h265

**Comment by 44vince44** [comment]
CONFIRMATION: I just made a command line test: replace  "-hwaccel cuvid" with "-hwaccel_output_format cuda", error is gone, and the process is successfull.

**Comment by Dendraspis** [comment]
Depends on the target group.
At least settings like *Quality* are so basic, that I would try to keep them.

Very nice @44vince44 ! 👍   Aaaaaaaaaand another condition.  😄

**Comment by 44vince44** [comment]
LOL, @Dendraspis 

Sorry we have to remove NOTHING. those other options work fine when the MODE is set to ONE PASS or TWO PASS. 
@kebinzhi 's tests were made all in MODE=QUALITY.

So please @stax76, here is the mod:
1) replace syntax  "-hwaccel cuvid" with "-hwaccel_output_format cuda"  for both Nvidia/h264 and Nvidia/h265
2) -cq and -qp stuff:

-    Quality = Preset => -cq
-    Quality = VBR  => -cq
-    Quality = VBR_MinQP => -cq
-    Quality = ConstQP => -qp

**Comment by 44vince44** [comment]
@stax76 This is labelled as fixed, but I don't think is it fixed ? The fix is:

  1.  replace syntax "-hwaccel cuvid" with "-hwaccel_output_format cuda" for both Nvidia/h264 and Nvidia/h265
  2. choosing between -cq and -qp, 2 cases
-     Quality = Preset or VBR or VBR_MinQP => -cq
-     Quality = ConstQP => -qp

**Comment by stax76** [comment]
v2.1.4.8 fixed _-hwaccel_output_format cuda_ and
v2.1.4.9 will fix _ConstQP => -qp_

Is that all?

**Comment by 44vince44** [comment]
@stax76 , yes it should be all, indeed! thank you!  I can only test stuff related to h264 because my nvidia doesn't have h265.

**Comment by Dendraspis** [comment]
> When beta 2.1.4.9 is out i'll test all syntaxes !

@44vince44 
In order to close old issues:  Could you test all syntaxes so far?  😁

**Comment by 44vince44** [comment]
Yes sure, I've forgotten this one, thanks for reminding me. I'm on it now!

**Comment by 44vince44** [comment]
@Dendraspis
Checked the commands generated
Made 5 combinations of decode/encode
All seems OK. Please close !! Thanks!!

**Comment by Dendraspis** [comment]
@44vince44 
Thank you, too!
