### ISSUE TITLE
cfr video have a wrong info.

### ISSUE THREAD

**Issue by kebinzhi** [staxrip/staxrip#287]
![image](https://user-images.githubusercontent.com/20044735/88717195-bb698680-d152-11ea-91bf-b15faa3f585f.png)
i use ffmpeg change a vfr video to a cfr video. everything is ok but the info is vfr.
wrong info.

**Comment by vonH** [comment]
Can you provide more information? The first part is correct (24000/1001=23.976...) and this is a normal way to display frame rate. How did you "change" the VFR to CFR (e.g. settings or arguments used)?
