### ISSUE TITLE
BUG: Autocrop feature in Crop Window creates Mod 1 trims both sides

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#289]
**Describe the bug**
When using Autocrop in window Crop (press "A") the crop values respect MOD globally, but do not respect Mod2 on every edge

**Expected behavior**
Mod2 must be respected on every edge

**How to reproduce the issue**

Open the sample (zipped mkv) file provided below. Open crop window, press A. See crop values, they are ODD!!! they must be even (Mod2). Close the crop window, you have an error.

**Comment by Dendraspis** [comment]
Sorry, I can't see any problem. What am I missing?

AutoCrop Result:
![StaxRipAutoCrop1](https://user-images.githubusercontent.com/50659978/88786501-e378da00-d192-11ea-893e-0ab5e102c81f.JPG)

**Comment by 44vince44** [comment]
it works on your setup! i guess it needs more investigating. Doing further tests now

**Comment by 44vince44** [comment]
![SNAG-0001](https://user-images.githubusercontent.com/17828567/88810112-978f5a80-d1bd-11ea-842c-b6c886ae397c.jpg)

Well, I guess I didn't know the meaning of that one until now!
@Dendraspis  Thanks for testing

**Comment by Dendraspis** [comment]
Ah, you disabled this default setting long time ago just to run into potentional issues - very clever!   😄 

Why waiting a few hours? Let's pin it to the top and add some funky labels.  😆 

Sorry, I need sleep.... but till now I also didn't know what this checkbox really does.  😄   I never use AutoCrop, because it's too dangerous for me.

**Comment by 44vince44** [comment]
LOOOOOOOOOOOOOOLLLL

I disabled it long time ago (how did you guess?) because i misunderstood the meaning ;-)))))))))))
And I see you didn't know as well ! ALSO  " I never use AutoCrop, because it's too dangerous for me." Same exact thing here !
Go to sleep ;-)))))))))))))

**Comment by Dendraspis** [comment]
> I disabled it long time ago (how did you guess?) 

I stood behind you.  👀
