### ISSUE TITLE
Links to support modifications requested by Stax76 regarding avisynth.dll

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#296]
Hi all, Hi @Dendraspis 

Most of you who don't check the forums need to know that @stax76  is currently asking for some changes in external dlls in order to make portable avisynth work without hacks and softlinks.

Please find the links to three projects [here](https://forum.doom9.org/showthread.php?p=1920012#post1920012) post number 3628 and please add your support after visiting the links presented in that post.

Know also that @Rigaya has reacted in favor of  Stax's request, and **thank you very much Rigaya**

**Comment by JJKylee** [comment]
Guys,

For ffmpeg, don't forget to up-vote the post by clicking the up arrow above the post.
I'm the only up-voter as of now.

**Comment by 44vince44** [comment]
OMG thanks for pointing that out! indeed, I had added my support as a written comment. This up-vote is really hidden !

**Comment by stax76** [comment]
> For ffmpeg, don't forget to up-vote the post by clicking the up arrow above the post.
> I'm the only up-voter as of now.

It's easy to overlook this feature.

Maybe program it on our own and submit a pull request or finding somebody willing to donate for it. For the donation option a platform like Kickstarter could be used.

**Comment by 44vince44** [comment]
I am closing this thread because I don't think it will change any more things...
