### ISSUE TITLE
Some encodes fails around the ffmsindex point if project uses multiple drives

### ISSUE THREAD

**Issue by SnorreSelmer** [staxrip/staxrip#30]
My setup:
Drive A - MKV remuxes of my media
Drive B - Temp-files
Drive C - Completed encodes

I run a lot of batch jobs, and about 1 in 8 files silently crashes StaxRip at the end of the ffmsindex step. (It's the same movies every time, and repeated processing always failed.)

What happens:
I start the demux, ffmsindex gets to 100%, and one of two things happen (with a "fail-file"):
1: The ffmsindex window closes and the encode never starts (nor does the StaxRip UI load up)
2: The "Processing Jobs" window is left open (and blank) for several minutes while in the Resource Monitor I can see StaxRip saturate the read capacity of my temp-drive (while my HDD LED does _not_ reflect this activity) for several minutes, and then back to the above point.

Why is this a bug:
I consolidated the files and folders on one drive, and now the "fail-files" are encoding as if nothing was wrong in the first place.

**Comment by Revan654** [comment]
This is tied to ffindex, Which has problems to start with(There hasn't been an update for awhile(atlease last time I checked)). Once you introduce more then one drive it's introducing a whole batch of problems that could appear and you have to take into account speed of the drives and if a drive is in standby mode. Some software will not wait for the drive to Bootup. 

Don't use HDD LED as activity on different drives, If I remember correctly it only reports activity from the OS drive, the rest gets ignored. Some Motherboards this function is very limited.

**Comment by stax76** [comment]
Maybe try l-smash instead. Such kind of issue is extremely hard to reproduce and fix.

New build:

https://forum.doom9.org/showthread.php?p=1882197#post1882197
