### ISSUE TITLE
Vapoursynth R51 included in Staxrip 2.1.4.2-Beta contains a bug that causes video aliasing, it was fixed in the unreleased R52

### ISSUE THREAD

**Issue by mikaljan** [staxrip/staxrip#300]
A bug managed to sneak into Vapoursynth R51 included in Staxrip 2.1.4.2-Beta, which causes a lot of video aliasing as pointed out here:

https://github.com/vapoursynth/vapoursynth/issues/625

the bug is fixed now in the unreleased R52, please consider updating Vapoursynth dlls in the next official release of Staxrip!

**Comment by JJKylee** [comment]
2.1.4.3 Beta ships with R52.

**Comment by stax76** [comment]
OK, closing.
