### ISSUE TITLE
ffv1 display aspect ratio not working

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#301]
encode a video using FFV1 with whatever display aspect ratio you want
use mkv container

play the video in any compatible player - it displays using a pixel aspect ratio of 1:1

e.g take a DVD rip in 720x576 and a display aspect ratio of 1.77777, a very common format for that era
encode it in FFV1
play it back in something
it displays in 720x576 and looks squished

it looks like ffmpeg is being passed the -aspect command correctly so perhaps the problem is in ffmpeg?
I'm encoding to mkv so my workaround has been to use mkvmerge to remux the file with a new DAR specified in mkv headers

**Comment by Statick** [comment]
here's my encoding settings and the result I get when loaded in mediainfo. as you can see it says display ratio 5:4 which is the same as a pixel ratio of 1:1 at 720x576, obviously this looks incorrect when opened in any media player. this happens to me every time. could it be because of using d2v source? regardless, the DAR setting is correct, and I've set that manually as well (it defaults to the PAL ITU ratio when I open the d2v, but the video actually wants straight 16:9 not the PAL ratio), and the aspect setting is being passed to ffmpeg

I'm always indexing dvds manually in dgindex and producing d2v files which is what I load into staxrip, I've only recently started using ffv1 output so I can export lossless into another software for processing, and this has happened every time I've gone d2v > ffv1 which is maybe 10 times

settings : https://i.ibb.co/wCJQVNk/Srip1.png
settings : https://i.ibb.co/D7x7Xph/Srip2.png
output : https://i.ibb.co/q0JLNbr/Minfo.png

**Comment by Statick** [comment]
confirmed this is an MKV container issue. the avi output file in the temp folder shows the correct aspect ratio when opened in mediainfo, and displays correctly when opened in a player. it's the final MKV that is muxed at the end which shows 5:4 aspect ratio

**Comment by stax76** [comment]
Please report it here:

https://mkvtoolnix.download/bugreports.html

**Comment by stax76** [comment]
https://gitlab.com/mbunkus/mkvtoolnix/-/issues/2993
