### ISSUE TITLE
Color Debanding Filters issues

### ISSUE THREAD

**Issue by inter5tella** [staxrip/staxrip#304]
Hi,

when I'm trying to add f3kdb/neo-f3kdb I'm getting this error:

```
Error Video encoding (2.1.4.2)

Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion


--------------------------- Video encoding ---------------------------

x265 M-3.4+6-g73f96ff39-gcc11.0.0 Patman

"C:\Program Files\StaxRip\Apps\Support\avs2pipemod\avs2pipemod64.exe" -dll="C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll" -y4mp "D:\Video\Monster Mädchen BD 1\01_temp\01_new.avs" | "C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 18 --preset slower --tune animation --profile main10 --level-idc 4.1 --output-depth 10 --rskip 0 --max-merge 5 --bframes 6 --lookahead-slices 4 --ref 4 --high-tier --no-sao --frames 34111 --y4m --output "D:\Video\Monster Mädchen BD 1\01_temp\01_new_out.hevc" -

avs2pipemod[info]: writing 34111 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
x265 [error]: unable to open input file <->

StaxRip.ErrorAbortException: Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion


--------------------------- Video encoding ---------------------------

x265 M-3.4+6-g73f96ff39-gcc11.0.0 Patman

"C:\Program Files\StaxRip\Apps\Support\avs2pipemod\avs2pipemod64.exe" -dll="C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll" -y4mp "D:\Video\Monster Mädchen BD 1\01_temp\01_new.avs" | "C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 18 --preset slower --tune animation --profile main10 --level-idc 4.1 --output-depth 10 --rskip 0 --max-merge 5 --bframes 6 --lookahead-slices 4 --ref 4 --high-tier --no-sao --frames 34111 --y4m --output "D:\Video\Monster Mädchen BD 1\01_temp\01_new_out.hevc" -

avs2pipemod[info]: writing 34111 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
x265 [error]: unable to open input file <->


   bei StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:Zeile 377.
   bei StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:Zeile 120.
   bei StaxRip.x265Enc.Encode() in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:Zeile 43.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 310.
```

The same error appears with stable 2.1.3.0
When I'm adding GradFun3 it seems to work, but it would be nice to have an option to change threshold value, etc.

**Comment by inter5tella** [comment]
Hi Vince,

attached you will find the log for my test.
I’ve copied the dlls to my system folder and renamed the project’s folder name.

I’ve found out that f3kdb is working if the source file has been demuxed freshly. As soon as you close Staxrip or try another encode just after you’ve aborted the 1st try, it’s crashing. Only deleting the temp folder and demuxing again makes it working.

Btw, thanks for the example usage of GradFun3.

Regards.

Von: 44vince44
Gesendet: Sonntag, 23. August 2020 08:30
An: staxrip/staxrip
Cc: inter5tella; Mention
Betreff: Re: [staxrip/staxrip] Color Debanding Filters issues (#304)

@inter5tella
First, please copy the Avisynth script that fails here. You can get it from the log. You may zip and attach the log here.
Maybe I can see what's wrong...
Then, before further testing, we need to clear this (possible reasons):
• Install avisynth on your system, or manually copy the files Avisynth.dll and DevIL.dll from C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\ to C:\Windows\System32\ (this is currently required because there are still problems with portable Avisynth.
• Use files and paths with standard characters, like Madchen instead of Mädchen (and keep them short)
Finally, you can use Gradfun3 very easily by editing the parameters. Here is a gradfun3 simplified recommended syntax:
GradFun3(thr=0.5, radius=12, mode=6, smode=1)
Only change values of thr and radius
The higher thr is, the more areas will be included in the process, (threshold)
The higher radius is, the more "blur" it will do, it usually depends on the resolution.
Mode=6 and smode=1 are the best quality available, leave as is.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



------------------------- System Environment -------------------------

StaxRip    : 2.1.4.2
Windows    : Windows 10 Pro 2004
Language   : German (Germany)
CPU        : AMD Ryzen 7 3800X 8-Core Processor
GPU        : NVIDIA GeForce GTX 1070 Ti
Resolution : 2560 x 1440
DPI        : 96

----------------------- Media Info Source File -----------------------

D:\Video\MonsterMusume\01.mkv

General
Complete name                    : D:\Video\MonsterMusume\01.mkv
Format                           : Matroska
Format version                   : Version 2
File size                        : 6.20 GiB
Duration                         : 23 min 42 s
Overall bit rate mode            : Variable
Overall bit rate                 : 37.4 Mb/s
Movie name                       : Monster Mädchen BD 1
Encoded date                     : UTC 2020-08-16 10:06:14
Writing application              : MakeMKV v1.15.2 win(x64-release)
Writing library                  : libmakemkv v1.15.2 (1.3.10/1.5.2) win(x64-release)

Video
ID                               : 1
ID in the original source medium : 4113 (0x1011)
Format                           : AVC
Format/Info                      : Advanced Video Codec
Format profile                   : High@L4.1
Format settings                  : CABAC / 4 Ref Frames
Format, CABAC                    : Yes
Format, Reference frames         : 4 frames
Codec ID                         : V_MPEG4/ISO/AVC
Duration                         : 23 min 42 s
Bit rate mode                    : Variable
Bit rate                         : 33.1 Mb/s
Maximum bit rate                 : 39.5 Mb/s
Width                            : 1 920 pixels
Height                           : 1 080 pixels
Display aspect ratio             : 16:9
Frame rate mode                  : Constant
Frame rate                       : 23.976 (24000/1001) FPS
Color space                      : YUV
Chroma subsampling               : 4:2:0
Bit depth                        : 8 bits
Scan type                        : Progressive
Bits/(Pixel*Frame)               : 0.666
Stream size                      : 5.48 GiB (88%)
Language                         : English
Default                          : No
Forced                           : No
Original source medium           : Blu-ray

Audio #1
ID                               : 2
ID in the original source medium : 4352 (0x1100)
Format                           : DTS XLL
Format/Info                      : Digital Theater Systems
Commercial name                  : DTS-HD Master Audio
Codec ID                         : A_DTS
Duration                         : 23 min 42 s
Bit rate mode                    : Variable
Bit rate                         : 2 136 kb/s
Channel(s)                       : 2 channels
Channel layout                   : L R
Sampling rate                    : 48.0 kHz
Frame rate                       : 93.750 FPS (512 SPF)
Bit depth                        : 24 bits
Compression mode                 : Lossless
Stream size                      : 362 MiB (6%)
Title                            : Stereo
Language                         : Japanese
Default                          : Yes
Forced                           : No
Original source medium           : Blu-ray

Audio #2
ID                               : 3
ID in the original source medium : 4353 (0x1101)
Format                           : DTS XLL
Format/Info                      : Digital Theater Systems
Commercial name                  : DTS-HD Master Audio
Codec ID                         : A_DTS
Duration                         : 23 min 42 s
Bit rate mode                    : Variable
Bit rate                         : 2 131 kb/s
Channel(s)                       : 2 channels
Channel layout                   : L R
Sampling rate                    : 48.0 kHz
Frame rate                       : 93.750 FPS (512 SPF)
Bit depth                        : 24 bits
Compression mode                 : Lossless
Stream size                      : 361 MiB (6%)
Title                            : Stereo
Language                         : German
Default                          : No
Forced                           : No
Original source medium           : Blu-ray

Text #1
ID                               : 4
ID in the original source medium : 4608 (0x1200)
Format                           : PGS
Codec ID                         : S_HDMV/PGS
Codec ID/Info                    : Picture based subtitle format used on BDs/HD-DVDs
Duration                         : 23 min 23 s
Bit rate                         : 40.1 kb/s
Count of elements                : 804
Stream size                      : 6.70 MiB (0%)
Language                         : German
Default                          : No
Forced                           : No
Original source medium           : Blu-ray

Text #2
ID                               : 6
ID in the original source medium : 4609 (0x1201)
Format                           : PGS
Codec ID                         : S_HDMV/PGS
Codec ID/Info                    : Picture based subtitle format used on BDs/HD-DVDs
Duration                         : 21 min 14 s
Bit rate                         : 7 503 b/s
Count of elements                : 146
Stream size                      : 1.14 MiB (0%)
Language                         : German
Default                          : No
Forced                           : No
Original source medium           : Blu-ray

Menu
00                               : 00:00.000                             : en:Chapter 01
00                               : 04:09.999                             : en:Chapter 02
00                               : 12:16.026                             : en:Chapter 03
00                               : 21:50.809                             : en:Chapter 04
00                               : 23:21.024                             : en:Chapter 05
00                               : 23:41.044                             : en:Chapter 06

------------------------------ Demux MKV ------------------------------

mkvextract 49

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" D:\Video\MonsterMusume\01.mkv tracks 3:"D:\Video\MonsterMusume\01_temp\01 ID4 German.sup" 4:"D:\Video\MonsterMusume\01_temp\01 ID5 German.sup" 1:"D:\Video\MonsterMusume\01_temp\01 ID1 Japanese {Stereo}.dtshd" 2:"D:\Video\MonsterMusume\01_temp\01 ID2 German {Stereo}.dtshd" --ui-language en

Extracting track 1 with the CodecID 'A_DTS' to the file 'D:\Video\MonsterMusume\01_temp\01 ID1 Japanese {Stereo}.dtshd'. Container format: Digital Theater System (DTS)
Extracting track 2 with the CodecID 'A_DTS' to the file 'D:\Video\MonsterMusume\01_temp\01 ID2 German {Stereo}.dtshd'. Container format: Digital Theater System (DTS)
Extracting track 3 with the CodecID 'S_HDMV/PGS' to the file 'D:\Video\MonsterMusume\01_temp\01 ID4 German.sup'. Container format: SUP
Extracting track 4 with the CodecID 'S_HDMV/PGS' to the file 'D:\Video\MonsterMusume\01_temp\01 ID5 German.sup'. Container format: SUP

Start:    12:29:16
End:      12:29:18
Duration: 00:00:02

General
Complete name         : D:\Video\MonsterMusume\01_temp\01 ID1 Japanese {Stereo}.dtshd
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
File size             : 362 MiB
Overall bit rate mode : Variable

Audio
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless
General
Complete name         : D:\Video\MonsterMusume\01_temp\01 ID2 German {Stereo}.dtshd
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
File size             : 361 MiB
Overall bit rate mode : Variable

Audio
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless

------------------------- Demux xml chapters -------------------------

mkvextract 49

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" D:\Video\MonsterMusume\01.mkv chapters D:\Video\MonsterMusume\01_temp\01_chapters.xml

File 'D:\Video\MonsterMusume\01.mkv': container: Matroska
Track ID 0: video (MPEG-4p10/AVC/H.264)
Track ID 1: audio (DTS-HD Master Audio)
Track ID 2: audio (DTS-HD Master Audio)
Track ID 3: subtitles (HDMV PGS)
Track ID 4: subtitles (HDMV PGS)
Chapters: 6 entries

Start:    12:29:18
End:      12:29:18
Duration: 00:00:00

------------------------- Demux ogg chapters -------------------------

mkvextract 49

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" D:\Video\MonsterMusume\01.mkv chapters D:\Video\MonsterMusume\01_temp\01_chapters.txt --simple

File 'D:\Video\MonsterMusume\01.mkv': container: Matroska
Track ID 0: video (MPEG-4p10/AVC/H.264)
Track ID 1: audio (DTS-HD Master Audio)
Track ID 2: audio (DTS-HD Master Audio)
Track ID 3: subtitles (HDMV PGS)
Track ID 4: subtitles (HDMV PGS)
Chapters: 6 entries

Start:    12:29:18
End:      12:29:19
Duration: 00:00:00

---------------------- Indexing using ffmsindex ----------------------

"C:\Program Files\StaxRip\Apps\Plugins\Dual\ffms2\ffmsindex.exe" D:\Video\MonsterMusume\01.mkv D:\Video\MonsterMusume\01_temp\01.ffindex

Writing index... done.

Start:    12:29:19
End:      12:29:21
Duration: 00:00:02

--------------------------- AviSynth Script ---------------------------

AddAutoloadDir("C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\plugins")
AddAutoloadDir("C:\Users\micha\AppData\Roaming\StaxRip\Plugins\AviSynth")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\Dual\ffms2\ffms2.dll")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\Dual\flash3kyuu_deband\flash3kyuu_deband.dll")
FFVideoSource("D:\Video\MonsterMusume\01.mkv", cachefile="D:\Video\MonsterMusume\01_temp\01.ffindex")
#AssumeFPS(25)
f3kdb()

------------------------- Source Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 34111
Time      : 23:42.713
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 34111
Time      : 23:42.713
Framerate : 23.976023 (24000/1001)
Format    : YUV420P8

------------------------ Error Video encoding ------------------------

Video encoding returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion


--------------------------- Video encoding ---------------------------

x265 M-3.4+6-g73f96ff39-gcc11.0.0 Patman

"C:\Program Files\StaxRip\Apps\Support\avs2pipemod\avs2pipemod64.exe" -dll="C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll" -y4mp D:\Video\MonsterMusume\01_temp\01_new.avs | "C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 18 --preset slower --tune animation --profile main10 --level-idc 4.1 --output-depth 10 --rskip 0 --max-merge 5 --bframes 6 --lookahead-slices 4 --ref 4 --high-tier --no-sao --frames 34111 --y4m --output D:\Video\MonsterMusume\01_temp\01_new_out.hevc -

avs2pipemod[info]: writing 34111 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
x265 [error]: unable to open input file <->

--------------------------- Video encoding ---------------------------

x265 M-3.4+6-g73f96ff39-gcc11.0.0 Patman

"C:\Program Files\StaxRip\Apps\Support\avs2pipemod\avs2pipemod64.exe" -dll="C:\Program Files\StaxRip\Apps\FrameServer\AviSynth\AviSynth.dll" -y4mp D:\Video\MonsterMusume\01_temp\01_new.avs | "C:\Program Files\StaxRip\Apps\Encoders\x265\x265.exe" --crf 18 --preset slower --tune animation --profile main10 --level-idc 4.1 --output-depth 10 --rskip 0 --max-merge 5 --bframes 6 --lookahead-slices 4 --ref 4 --high-tier --no-sao --frames 34111 --y4m --output D:\Video\MonsterMusume\01_temp\01_new_out.hevc -

avs2pipemod[info]: writing 34111 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-8bit progressive video.
x265 [error]: unable to open input file <->

Start:    12:31:36
End:      12:31:36
Duration: 00:00:00

**Comment by SimplisticGH** [comment]
I'm having basically the same issue

I can't exactly get it to work predictably either, sometimes it works and sometimes it doesn't (which makes batch jobs impossible).

Video Example: https://streamable.com/jmjytt
[log.txt](https://github.com/staxrip/staxrip/files/5119081/log.txt)

**Comment by 44vince44** [comment]
I have crashes with f3kdb, even when I open the preview window. This is why I decided to ever use it. Instead, I use:

Gradfun3 (note that with 10+ bit sources you need to use stack16 mode)
DFTTest with deband option

And I removed f3kdb a long time ago from my filter profiles.

**Comment by Dendraspis** [comment]
I'll close it for now. @stax76  couldn't reproduce this issue and we haven't heard something after @44vince44 gave his excellent expertise and workaround/alternative about 4 monts ago.
