### ISSUE TITLE
How can I use AVISynth and VapourSynth scripts in other software?

### ISSUE THREAD

**Issue by JonathonSunshine** [staxrip/staxrip#305]
This template is meant for usage questions of StaxRip.

Hello!!   At some point, StaxRip has become a fully portable installation, when running it for the first time, it doesn't try to install VS or AVS anymore.

Can you please nominate the correct external versions of AVISynth, VS and Python, and whether to install them for "current user only" or "all users (requires admin privileges)".

The end goal being to be able to run those scripts in MPC or VirtualDub, MeGUI, make gifs with FFMPeg etc

Thank you

**Comment by JonathonSunshine** [comment]
Hello, back again, I'm trying to open a QTGMC Vapoursynth script in VirtualDub x64 and getting errors, any ideas?

![vapoursyntherror](https://user-images.githubusercontent.com/27830114/103178243-d2accb80-48cc-11eb-9d9e-6ea15d8338e4.jpg)

**Comment by JonathonSunshine** [comment]
Hello, I'm trying to open a VapourSynth Script in VirtualDub

I'm using StaxRip-x64-2.1.5.3-Beta, Python x64 3.8.7  and VapourSynth64-R52
In staxrip, I have both VS and AVS set to "use installed directly".

If I try using AVS, the script will work with VirtualDub if I select "medium" quality, if I select "very slow". I get the following error.
![aviSynth Error](https://user-images.githubusercontent.com/27830114/103178417-5fa45480-48ce-11eb-80f1-4aac577d45d6.jpg)

In VapourSynth scripts I get this error

![vapoursyntherror](https://user-images.githubusercontent.com/27830114/103178289-291a0a00-48cd-11eb-83a9-7491f1b523bb.jpg)

**Comment by stax76** [comment]
It works in staxrip and tools started by staxrip because staxrip adds the fftw3 directory to the user path environment variable.

rundll32.exe sysdm.cpl,EditEnvironmentVariables

**Comment by JonathonSunshine** [comment]
Hmmm, am I doing this right, because I'm getting the same errors?

![added to path](https://user-images.githubusercontent.com/27830114/103197373-a37c7580-4931-11eb-9bf6-0650f4e50d95.jpg)

**Comment by JonathonSunshine** [comment]
got it going, "C:\StaxRip-x64-2.1.5.3-Beta\Apps\Support\FFTW"

had to add that to path, now works with VS and AVS.

I'd suggest that if you select "use installed %%frameserver%% directly" it should add the appropriate path to PATH.

Thanks

**Comment by stax76** [comment]
In the next build there is a new feature:

- The apps dialog has a feature to edit the user PATH environment variable.

And the problem is now described in the docs:

https://staxrip.readthedocs.io/usage.html#opening-scripts-externally

I think this is sufficient, such critical system settings should only be changed with great care, and it's too advanced for asking all users about it with a dialog.
