### ISSUE TITLE
Error Muxing

### ISSUE THREAD

**Issue by PixelatedFloppy** [staxrip/staxrip#307]
**Describe the bug**

Error message "Muxing returned error exit code: -1073740940 (0xC0000374)" is given when trying to create an mp4 encode from a mkv file.

**Expected behavior**

Create a 720p encode and mux into a mp4 container from a 1080p remux mkv.

I was able to create a 1080p encode muxed into MP4 container from same 1080p remux mkv without issue

If I DO NOT do any audio I do not have have this issue

(removed)

**Additional context**
I delete the temp folder every time I try to encode it
I have tried;
creating even shorter file path and file name
using a different 720p profile
changing the "." to "_"
using both "." & "_"
using the 2nd audio path option in the Staxrip GUI
running ONLY the encode with nothing else running
Upgraded from StaxRip-x64-2.1.3.7-beta to StaxRip-x64-2.1.4.2-Beta
Updated Windows
Rebooted

Others have said they get the same error and have to use something else like MEGUI to get the encode they want

**Comment by 44vince44** [comment]
So you mean:

- Encoding audio track + Encoding video (2 pass) to x264 then muxing mp4 -> mux error
- No audio track + Encoding video (2pass) to x264 then muxing mp4 - > No mux error
- Encoding audio track + Copy/mux video then muxing mp4 -> No mux error

Right ?

It would help much to know what happens if you use mkv container for destination, if you get muxing error. Please can you do this test?

**Comment by PixelatedFloppy** [comment]
- **"Encoding audio track + Encoding video (2 pass) to x264 then muxing mp4 -> mux error"**  - That is correct.

- **"No audio track + Encoding video (2pass) to x264 then muxing mp4 - > No mux error"**  - I only just tried this last night and this DID NOT give me the mux error. So that is correct.

- **"Encoding audio track + Copy/mux video then muxing mp4 - > No mux error"**  - Did not try this yet

- **How could you generate a mediainfo file of destination?** - I have no idea...I am just as confused and that is why i posed the media info for that file

**Comment by 44vince44** [comment]
This is very strange.... I tried to reproduce this here and I couldn't !

>     * **How could you generate a mediainfo file of destination?** - I have no idea...I am just as confused and that is why i posed the media info for that file

You mean the destination file was generated in spite of the error ?

**Comment by PixelatedFloppy** [comment]
**You mean the destination file was generated in spite of the error ? -** Yes! but the log stays in the temp folder it its NOT placed with the other logs for encodes that completed without issue. The log also does not contain the normal media info at the end

**Comment by 44vince44** [comment]
This is strange!! Did it ever happened to you with another file before ?

**Comment by PixelatedFloppy** [comment]
Yes, this is probably the 4th or 5th time it has happend. I have another file that I can post those 3 logs for, if it would be helpful.

**Comment by 44vince44** [comment]
At that point, what would be helpful is to post a link to the original file so I can test it myself!

**Comment by PixelatedFloppy** [comment]
44vince44 the file is 17GB is that alright?

**Comment by 44vince44** [comment]
LOOOL ;-)) noo it's too much !!!

Maybe @Patman86 knows something about that, because he works on Mp4box!

@Patman86: please, in case you are available, there is a problem with projects to be muxed as mp4 at the last step, an error message error is thrown, but the file is muxed all right, and is generated! Any idea? seems related to Mp4box muxing.
There is a full log in the first post. 
I couldn't reproduce it, and the source file is huge so I couldn't get it.

**Comment by Patman86** [comment]
@PixelatedFloppy pls share/link the file. 17 GB is no problem and I want to reproduce it.

**Comment by PixelatedFloppy** [comment]
I am not going to post a link publicly, but the source is "Harry.Potter.And.The.Order.of.The.Phoenix.2007.BluRay.1080p.DTS-HD.MA.5.1.VC-1.REMUX-FraMeSToR"

**Comment by stax76** [comment]
@PixelatedFloppy 

I can't reproduce it either.

```
Dev> .\Err.exe 0xC0000374
# for hex 0xc0000374 / decimal -1073740940
  STATUS_HEAP_CORRUPTION                                         ntstatus.h
# A heap has been corrupted.
# 1 matches found for "0xC0000374"
```

**Comment by 44vince44** [comment]
@Patman86 were you able to get the file for testing ?

**Comment by PixelatedFloppy** [comment]
here is the audio settings that I am using

eac3to -448 -resampleTo48000 -downDpl

**Comment by 44vince44** [comment]
Try using FFMPEG to recode/resample your streams, I always prefer ffmpeg to eac3to.

**Comment by PixelatedFloppy** [comment]
"Encoding audio track + Copy/mux video then muxing mp4 - > No mux error" - I got an error

Staxrip Log - https://pastebin.com/5qMJitfW

"Try using FFMPEG"  - will try

**Comment by Patman86** [comment]
@PixelatedFloppy

I can't reproduce it either.

**Comment by PixelatedFloppy** [comment]
FFMPEG - Got an error using it as well

Staxrip Log - https://pastebin.com/d8XmR1Mw

**Comment by 44vince44** [comment]
> 
> 
> @PixelatedFloppy
> I have a similar file from Harry and i can't reproduce your error either.

@Patman86 by "similar" you mean that it is NOT a "REMUX-FraMeSToR" release, right ?

**Comment by Patman86** [comment]
With similar I mean it's a Remux but not from FraMeSToR.

**Comment by 44vince44** [comment]
So I guess it is a problem relating to the release FraMeSTor. Never happenned before.

- not a known release ("private" type)
- file processing completes, error is thrown but output is generated correctly.

I would advise to close the thread and delete from it any reference to illegal things

**Comment by PixelatedFloppy** [comment]
[anything.zip](https://github.com/staxrip/staxrip/files/5147317/anything.zip)

**Comment by 44vince44** [comment]
@PixelatedFloppy I'm sorry I looked the settings of the project and I really found nothing strange !! I really don't know :-(

**Comment by PixelatedFloppy** [comment]
strange, thanks for looking into it
