### ISSUE TITLE
How to automatically convert specific characters in a file name to other characters in the output filename?

### ISSUE THREAD

**Issue by stemcc** [staxrip/staxrip#308]
Specifically, how to convert spaces in the input filename into underscores or dashes in the output filename.

**Comment by 44vince44** [comment]
Use a file renamer. there are very good free ones out there (just search for them on the web) ! Staxrip's role is not to format file names !

**Comment by Dendraspis** [comment]
...or write your own script for console or Powershell, that you can run before or afterwards and that you can also run automatically via ***Tools » Advanced » Event Command***.  😊

**Comment by stax76** [comment]
A few more details:

event command method 1 renames the target file with powershell after the job is finished:

```
Event: After Job Processed
Command: ExecutePowerShellScript
    Script Code: Rename-Item "$env:target_file" (("$env:target_name" -replace " ", "_") + ".$env:muxer_ext")
    Use External Shell: Yes
```

Downside is an external shell pops up and stays open.


ExecutePowerShellScript does not expand macros but when we use an external shell then it's a child process and all child processes staxrip creates should have all macros available as environment variables.


event command method 2 uses the command SetTargetFile, powershell is used here too using the eval macro:

```
Event: Before Processing
Command: SetTargetFile
    Path: %target_dir%%eval:'%target_name%' -replace ' ', '_'%.%muxer_ext%
```


In the next build the command ExecutePowerShellScript expands macros:

```
Event: After Job Processed
Command: ExecutePowerShellScript
    Script Code: Rename-Item "%target_file%" (("%target_name%" -replace " ", "_") + ".%muxer_ext%")
    Use External Shell: no
```
