### ISSUE TITLE
Plugin loaded error when opening video with vapoursynth

### ISSUE THREAD

**Issue by Snylonue** [staxrip/staxrip#31]
It reported 'Failed to open source,try another source filter'(`Plugin already loaded`),with automatic,ffms2:
![Snipaste_2019-07-30_14-48-50](https://user-images.githubusercontent.com/48825598/62107806-0439f580-b2db-11e9-9ddd-bba7d09cdf9d.png)
then I chose LWLibavSource,and it reported 'Failed to load script'(`name 'core' is not defined`):
![Snipaste_2019-07-30_14-51-43](https://user-images.githubusercontent.com/48825598/62108103-bec9f800-b2db-11e9-9ebe-c93e0ce24bfd.png)

environment:cpu:i5-7300hq,gpu:gtx1050,win10 1809 x64,staxrip 2.0.2.4 beta,ffms2 2.27.0

**Comment by Revan654** [comment]
this is python issue, Your loading the same file twice.

VS first will load anything in the dll folders, then StaxRip will load it's only dll files. Any files that appear in StaxRip Plugins should be removed from VS folder.

**Comment by Snylonue** [comment]
Thank you,the problem has been sloved.But I need to use VS alone sometimes that I have to load plugins manually or put the plugin back to the folder.What should I do to make them(the same plugin) coexist ?
(~~I'm sorry that I can't express my mind in English clearly~~)

**Comment by Revan654** [comment]
StaxRip has it's own Loading System, Best advise would be to create an autoloader that points to StaxRip Plugin Directory. There should be tutorial on VS website on how to do that.

or create a simple script that auto creates .py file with the loaded plugins already added.

**Comment by Snylonue** [comment]
Thank you for your help.The problem is completely solved.
