### ISSUE TITLE
Chapters files from some mp4s are not handled properly, Staxrip throws ERROR when muxing

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#310]
**Describe the bug**

Some mp4s have chapters that Staxrip does not handle correctly. It seems like xml, but the chapter file is demuxed as txt.
When muxing the project, staxrip throws this error:

Error: The XML chapter file 'C:\Temp\_StaxRip\TimecodeSample25FpsWithChapts_temp\TimecodeSample25FpsWithChapts_chapters.txt' contains an error: The root element must be Chapters.

This same file is played perfectly in players, and is handled flawlessly by MKVToolNix !

**Expected behavior**
The chapter file must be demuxed correctly...

**How to reproduce the issue**

Use the sample file attached below, inside the archive. (Very small file)
Drag and drop the extracted file in Staxrip. Copy/Mux Video and Audio, then run job. =>You'll get the error.

You can also use any file with chapters produced by Handbrake. You'll get the same error.

**SAMPLE FILE**

[TimecodeSample25FpsWithChapts.zip](https://github.com/staxrip/staxrip/files/5132444/TimecodeSample25FpsWithChapts.zip)

**Comment by stax76** [comment]
staxrip uses the mp4box option -dump-chap-ogg, the ogg chapter format is not xml based but the output is a xml based format that mkvmerge don't understand, so it looks like a mp4box bug and I don't know how to workaround it.

**Comment by 44vince44** [comment]
@stax76 Thank you very much for checking, I can always remux it to mkv with Mkvtoolnix before processing it in Staxrip as workaround.
@Patman86 can you please check that as well, maybe you could have an idea?

**Comment by Patman86** [comment]
If the '-dump-chap' option is used to extract chapters, the chapter file must be 'someting.ttxt' and you can add the chapter with the following command `-add 'something.ttxt:chap'`. Staxrip uses -chap and it's wrong because of the structure of the chapter files.

**Comment by stax76** [comment]
With ttxt extension mkvmerge still don't except it.

Maybe it could be extracted with ffmpeg to a mkvmerge compatible chapter format?

**Comment by 44vince44** [comment]
Thanks for the link @Patman86, it explains it all. So this is the 3gpp ttxt format by apple :-( 

@stax76 there is already some fix required:
1) re-muxing with Mp4BOX: 
With syntax correction pointed out by @Patman86, when using MP4Box to mux to mp4 format, instead of -chap, staxrip has to use -add filename.ttxt:chap and in WORKS!  (extension must be .ttxt for this format, so must be careful when demuxing with mp4box)

2) re-muxing with Mkvmerge.
You can't remux this format (either with txt or ttxt extension) with mkvmerge. However mkvmerge accepts the stream when it is inside of an mp4 file, not when it has been extracted as ttxt.

So I guess we're stuck here, unless we convert ttxt to xml or basic txt. I found no converters for that.
FFMPEG can handle it and converts it internally to standard text format, but only when it is in an MP4 source, and NOT from a ttxt source. And FFMPEG can't handle it when the output is mkv !!!!

**Comment by 44vince44** [comment]
@Patman86 just one more question:
The problem is when extracting the chapters. Staxrip uses switch "-dump-chap-ogg".
In mp4box documentation, it says : extract chapter file as OGG format.
Isn't that supposed to convert to ogg format instead of ttxt ?

**Comment by Patman86** [comment]
The chapter file in your sample is an apple chapters file

```
<?xml version="1.0" encoding="UTF-8" ?>
<!-- GPAC 3GPP Text Stream -->
<TextStream version="1.1">
<TextStreamHeader width="0" height="0" layer="0" translation_x="0" translation_y="0">
<TextSampleDescription horizontalJustification="left" backColor="0 0 0" scroll="None">
<TextBox top="0" left="0" bottom="0" right="0"/>
</TextSampleDescription>
</TextStreamHeader>
<TextSample sampleTime="00:00:00.000" sampleDescriptionIndex="1" xml:space="preserve">Chapter 1</TextSample>
<TextSample sampleTime="00:01:00.000" sampleDescriptionIndex="1" xml:space="preserve">Chapter 2</TextSample>
<TextSample sampleTime="00:01:18.360" text="" />
</TextStream>
```

so you need the ttxt extention.

chapeters in the OGG file format looks like

```
CHAPTER01=00:00:00.000
CHAPTER01NAME=The Invaders (Main Titles)
CHAPTER02=00:04:04.286
CHAPTER02NAME=The Professionals

```
the txt extention is correct.

MP4Box recognize this during the demux process

```
Chapter track found, dumping to ttxt
[iso file] Unknown box type encd
[iso file] Unknown box type encd
Conversion done
```

**Comment by 44vince44** [comment]
@Patman86 thanks !

>  This file cann't be automatically converted to the OGG file format.
I guess that's the problem. It means we won't be able to mux it into mkv (except if it is converted).

However, @stax76 there is still something that can be fixed in the mp4 muxing case: the `-add 'something.ttxt:chap'` syntax instead of `-chap`.

So I'm leaving this open.

**Comment by 44vince44** [comment]
@stax76 @Patman86 
I posted a bug report on the gpac page, and it turned out that THERE WAS A BUG IN MP4BOX.
So they fixed it. The -dump-chap-ogg was not functioning correctly, now it's fixed.
Link to the bug report and reply [HERE](https://github.com/gpac/gpac/issues/1584)

@Patman86 the changes are committed, but I don't know if you can access or build yet. Anyway, I'll keep checking your builds ;-))

**Comment by 44vince44** [comment]
@Patman86 : I just tested their nightly build gpac-1.0.0-rev211-g71f1d75e-master-x64, the problem is fixed !

**Comment by Patman86** [comment]
I made a new version and yes the problem is fixed. I will upload it in the evening / tonight

**Comment by 44vince44** [comment]
@Patman86  1000000000 thanks!

**Comment by 44vince44** [comment]
@Patman, @stax76 
Got Patman's Mp4Box-1.0.0-rev211-g71f1d75ea-x64-gcc10.2.0 build and tested, OK!
This whole issue is now **FIXED**.
Thanks Patman!

**Comment by patman** [comment]
(@Patman86 )

**Comment by 44vince44** [comment]
@Patman86 : thanks!!!!!!
@patman : sorry ;-)))))))))))))
