### ISSUE TITLE
encoding speed get slower by the time

### ISSUE THREAD

**Issue by ruixingchen** [staxrip/staxrip#311]
I encoded some 1080p videos with AMD 5300M(MacBook 16 bootcamp), the GPU video encode usage was about 80% at the very beginning, but it got lower and lower by the time, 80->70->60->50...., after some time, it went to 25% usage, the encoding speed is really slow.
is this a bug with Staxrip or my hardware ?

**Comment by stax76** [comment]
Please use the bug issue template.

https://github.com/staxrip/staxrip/issues/new?assignees=&labels=&template=report-a-bug.md&title=

**Comment by 44vince44** [comment]
It is definitely **NOT a bug in Staxrip.**
it could be hardware (overheating resulting in throttling)
it could be NOT hardware, but a problem of how you use the filters. You could do a small test on a range and send us the log so we can see the filters that you are using

**Comment by Dendraspis** [comment]
Could also be your source drive that can't keep up, your OS, overheating GPU, other running apps, ...

**Comment by vonH** [comment]
I've finished encoding over 600 programmes (the entire 20 years of Law & Order ;) and the fps and time taken per encode remained ~5% of one another (picking random log files). That was on Staxrip 2.0.6.0 and then 2.0.8.0.

Are you sure there's not an OS issue?

**Comment by 44vince44** [comment]
He's using GPU encoding, not CPU. I asked him for a log file to see if he's using all hardware or software/hardware, but he didn't reply.
I think it's definitely an overheating problem of the GPU (typically due to thermal paste degradation, it always happens under the GPU before it happens under the CPU).

**Comment by vonH** [comment]
> He's using GPU encoding, not CPU. I asked him for a log file to see if he's using hardware/hardware or software/hardware encoding/decoding, but he didn't reply.
> I think it's definitely an overheating problem of the GPU (typically due to thermal paste degradation, it always happens under the GPU before it happens under the CPU).

Ah, I read Nvidia instead of AMD. Sorry. I've encoded thousands of files with Nvenc and, again, there's been ~5% difference between files (based on sources with the same length and characteristics). With AMD though, I imagine it's related to drivers. A simple request would be to ask him to test X files using an alternative GUI/toolset and see if the problem persists.

**Comment by ruixingchen** [comment]
> > He's using GPU encoding, not CPU. I asked him for a log file to see if he's using hardware/hardware or software/hardware encoding/decoding, but he didn't reply.
> > I think it's definitely an overheating problem of the GPU (typically due to thermal paste degradation, it always happens under the GPU before it happens under the CPU).
> 
> Ah, I read Nvidia instead of AMD. Sorry. I've encoded thousands of files with Nvenc and, again, there's been ~5% difference between files (based on sources with the same length and characteristics). With AMD though, I imagine it's related to drivers. A simple request would be to ask him to test X files using an alternative GUI/toolset and see if the problem persists.

sorry for my late response, it looks like really an overheating problem, works fine on my desktop 😄

**Comment by warior456** [comment]
I've also had this happen after a while with my nvidia gtx 1050ti
![fast](https://user-images.githubusercontent.com/66562258/209432254-29ca2802-d189-4af9-a7d3-5f3bb913a0cb.png)
![slow](https://user-images.githubusercontent.com/66562258/209432207-1da67101-adca-4a23-9c99-69d8768f6edf.png)

**Comment by warior456** [comment]
@Dendraspis
