### ISSUE TITLE
How to configure so no errors when OpenCL not supported?

### ISSUE THREAD

**Issue by sharygin** [staxrip/staxrip#313]
This line: LoadPlugin("C:\Programs\StaxRip-x64-2.1.3.0\Apps\Plugins\Dual\KNLMeansCL\KNLMeansCL.dll") causes an error. My research suggests that it is because the laptop I'm using doesn't have OpenCL drivers available (gen 1 core i5-520M). When I manually went in to remove that line in the script, it was added again automatically. The only solution I found was to create a dummy file with the same name as the dll. I expected that if I am not using the plugin, that it should not be loaded. Or if they didn't load, alternative/fallback could be selected. What would be the correct way to address this?

**Comment by stax76** [comment]
A creative workaround is taking another plugin like ffms2.dll and rename it to KNLMeansCL.dll and put it in the location of KNLMeansCL.dll.

**Comment by sharygin** [comment]
thanks, that works but... why does it try to load the plugins if they aren't needed, and overwrite if I edit the script?

**Comment by stax76** [comment]
Building a better detection is either not possible or too difficult.
