### ISSUE TITLE
2.1.4.3 mp4box demux missing audio filename and missing ffms index filename

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#314]
I:\Encoder\StaxRip\Apps\Support\MP4Box\MP4Box.exe -single 2 -out "E:\WORK\TestFile_temp\ID1 {simple_aac_recording}.m4a" TestFile.mp4

clip = core.ffms2.Source(r"TestFile.mp4", cachefile=r"E:\WORK\TestFile_temp\temp.ffindex")

**Comment by stax76** [comment]
It's by design to get shorter temp file names to avoid getting too long paths, many tools support only 260 characters in paths.

I also find that in certain situations it increases usability, in other situations like using external tools it might decrease usability.
