### ISSUE TITLE
x265 chunk encoding issue

### ISSUE THREAD

**Issue by xx005fs** [staxrip/staxrip#316]
It seems that when chunk encoding is enabled, the output video file will only contain the video for chunk one, which has the same filename as the usual output [videoname]_out.hevc. The other encoded chunks generated by x265 doesn't make its way to the final video. Any workarounds for that? I followed the instructions from the documentations and everything else seems to work. I'm currently using Staxrip 2.1.4.3 beta.

**Comment by Dendraspis** [comment]
A log file would be very welcome.
Do you had problems with earlier versions?

I don't use this feature, but when it came out some guys (including me) did some tests and they were all successful.  🤔

**Comment by xx005fs** [comment]
Maybe my description of the problem is poor, but what I mean is that it only took one out of the 4 (number of chunks I'm working with) video clips and putting it in the output. In my case, say the video is 4000 frames long, in the output the first 1000 frames will show up just normally, but then after that, the video freezes and it keeps displaying the last frames of the 1000th frame. At the same time, the video filesize is totally different from what it would've been if encoded without using this feature. 

I have attached the log file down here. from my understanding, it seems that when it is on the final video construction step, it only added the "Top Gear - 07x01 - _out.hevc" clip into the final video, but the "Top Gear - 07x01 - _out_chunk[n].hevc" where n is 2, 3, and 4, are ignored:
[Uploading 2020-09-02 - 18.27.32 - Top Gear - 07x01 -_staxrip.log…]()
The video output size that is problematic is only 62.3MB.

**Comment by Dendraspis** [comment]
Had just a quick look, but it seems to be a bug when muxing into MP4 with MP4BOX - only the first chunk is used for muxing.

**Comment by stax76** [comment]
Fixed in the next build.
