### ISSUE TITLE
Japanese Audio not selected

### ISSUE THREAD

**Issue by kurim** [staxrip/staxrip#318]
**Describe the bug**
Japanese Audio not selected, even if i set audio to "all"

**Expected behavior**
If set to all or to ja / jpn it should selected.
![image](https://user-images.githubusercontent.com/1880220/92214974-6a0c8f80-ee94-11ea-9002-1efb4911168f.png)
![image](https://user-images.githubusercontent.com/1880220/92215038-83154080-ee94-11ea-9056-c3df1b55bf15.png)

**How to reproduce the issue**

1. Open a br-disk with japanese audio
2. Select playlist
![image](https://user-images.githubusercontent.com/1880220/92214497-477a7680-ee94-11ea-9c78-74c163b705fb.png)
3. Check eac3to Muxing:
![image](https://user-images.githubusercontent.com/1880220/92214767-57925600-ee94-11ea-901e-839e34787763.png)

Happens in 2.1 and all other betas.

**Comment by Dendraspis** [comment]
As far as I remember you should use ISO 639-2B letters that are 3 chars long. In your case try using `ger, jap` - I don't know what `iv`should be because it's not a valid 2-letter language code.

**Comment by kurim** [comment]
Hi Dendraspis,

thanks for feedback since help for this entry this is allowed:
![image](https://user-images.githubusercontent.com/1880220/92239820-e49cd580-eebb-11ea-9c06-08cd6029ebef.png)

- de, jp, iv
- ger, jpn, und
- all

non of this options work

**Comment by Dendraspis** [comment]
Now you know I sat in front of my smartphone answering you and that I don't use those demux possibilities.  😄 
Thanks for this additional infos!

🤔  I'll try to check this weekend why Japanese isn't working properly.

**Comment by 44vince44** [comment]
This seems to be specific to br-disc source. Because there is no problem with mp4s and mkvs as source.

**Comment by Dendraspis** [comment]
@44vince44 
Thanks for setting the bar even higher!

**Comment by kurim** [comment]
Just a part of the log file, there it looks fine.

```
staxrip2.1.4.3-Beta\Apps\Audio\eac3to\eac3to.exe "Z:\BDMV\PLAYLIST\" 2) -progressnumbers

M2TS, 1 video track, 2 audio tracks, 2 subtitle tracks, 0:50:25, 24p /1.001    
1: h264/AVC, 1080p24 /1.001 (16:9)                                             
2: DTS Master Audio, German, 2.0 channels, 16 bits, 48kHz, dialnorm: -4dB      
   (core: DTS, 2.0 channels, 768kbps, 48kHz, dialnorm: -4dB)                   
3: DTS Master Audio, Japanese, 2.0 channels, 16 bits, 48kHz, dialnorm: -4dB    
   (core: DTS, 2.0 channels, 768kbps, 48kHz, dialnorm: -4dB)                   
4: Subtitle (PGS), German                                                      
5: Subtitle (PGS), German 
```

**Comment by Dendraspis** [comment]
@kurim 
Thanks, but the whole log file would be better to see the parameters for all commands. :wink:

**Comment by 44vince44** [comment]
@Dendraspis when handling m2ts (br) files, the eac3to muxer is used. This is the only situation where eac3to muxer is called.
The problem is apparently with the code related to eac3to preprocessing only!

**Comment by kurim** [comment]
@Dendraspis,
here is the complete log
[Re_ Zero - Vol#1 (h265)_staxrip.log](https://github.com/staxrip/staxrip/files/5177635/Re_.Zero.-.Vol.1.h265._staxrip.log)

**Comment by Dendraspis** [comment]
@44vince44 
...and I'm curious to find out why Japanese is so special.  😎
Of course you're right - but now I have to find a source that fits and I'm pretty sure that is the really hard part.  😁

@kurim 
Thanks, so now we know demuxing works as intended, so it's really the selection of the audio track. That also helps.


Thanks!

**Comment by 44vince44** [comment]
> ...and I'm curious to find out why Japanese is so special. 😎

Haha, however in this case, it's as special as any non-english language, lol. To make tests, use the sample file I attached in my previous post! I guess the content of the sample file explains why Japanese is so special ;-)))

> Thanks, so now we know demuxing works as intended, so it's really the selection of the audio track. That also helps.

Yes it seems the syntax with eac3to.exe is not the problem. Staxrip simply forgets to select the tracks.

**Comment by kurim** [comment]
Fun fact, I test a disc with:
EN, DE, FR Audio - and it selects not "all" but EN, DE make it more confusing
![image](https://user-images.githubusercontent.com/1880220/92300136-bd481600-ef58-11ea-93e6-b0b2735a87bb.png)

**Comment by 44vince44** [comment]
@kurim, not confusing actually: those are the personal preferences of @Stax76 ;-)))))))))))

**Comment by stax76** [comment]
> I don't know what iv should be because it's not a valid 2-letter language code.

It stands for **i**n**v**ariant.

The issue should be fixed by the last commit.

**Comment by Dendraspis** [comment]
@stax76 
Indeed, but nevertheless it's not a valid ISO 639-1 code.  So I'm still right. 😋

Thanks for fixing - I'm glad I saw this before I started. 😄


@kurim 
Let's wait for the next beta version. 😃

**Comment by 44vince44** [comment]
@kurim please try beta 2.1.4.4, it's available since yesterday.

i tested with a m2ts file, it seems ok.

**Comment by kurim** [comment]
Hi,
is set to en,de,ja and works fine.
![image](https://user-images.githubusercontent.com/1880220/92412286-a3225980-f14b-11ea-8c69-bd0903c92b3d.png)

Thanks for fast fixing.
