### ISSUE TITLE
eac3to 3rd party lib upate request.

### ISSUE THREAD

**Issue by fuchanghao** [staxrip/staxrip#32]
the libdcadec.dll and libFLAC.dll in eac3to are too old.

the FLAC still stay in v1.2.1 and dcadec have bugs in DTS-HD XLL and not support DTS Express.

My build with Visual Studio 2019.

https://mega.nz/#!dFAmEC4Y!WMTQvzLkfTDHPfhTXURSLaFWbmDMVaq3dKfk4ucjYrI

Source

FLAC 1.3.3 release 
https://github.com/xiph/flac

dcadec latest git
https://github.com/withmorten/dcadec/

test

> 
> eac3to v3.34
> command line: "E:\StaxRip\Apps\Audio\eac3to\eac3to.exe" G:\CHARS_COUNTERATTACK_UHDBD\BDMV\STREAM\00003.m2ts 2: "F:\[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID2 Japanese.flac" 3: "F:\[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID3 Japanese.flac" 4: "F:\[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID4 Japanese.sup" -progressnumbers
> ------------------------------------------------------------------------------
> M2TS, 1 video track, 2 audio tracks, 1 subtitle track, 1:59:54, 11.988p
> 1: h265/HEVC, 2160p24 /1.001 (16:9), 10 bits
> 2: RAW/PCM, Japanese, 2.0 channels, 24 bits, 48kHz
> 3: DTS Master Audio, Japanese, 3/1.1 channels, 24 bits, 48kHz
>    (core: DTS, 3/1.1 channels, 1509kbps, 48kHz)
> 4: Subtitle (PGS), Japanese
> [a02] Extracting audio track number 2...
> [a03] Extracting audio track number 3...
> [s04] Extracting subtitle track number 4...
> [a02] Reading RAW/PCM...
> [a02] Swapping endian...
> [a02] Encoding FLAC with libFlac...
> [a03] Decoding with libDcaDec DTS Decoder...
> [a03] Encoding FLAC with libFlac...
> [a03] Creating file "F:\[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID3 Japanese.flac"...
> [a02] Creating file "F:\[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID2 Japanese.flac"...
> [s04] Creating file "F:\[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID4 Japanese.sup"...
> [a02] The original audio track has a constant bit depth of 24 bits.
> [a03] The original audio track has a constant bit depth of 24 bits.
> Video track 1 contains 172464 frames.
> Subtitle track 4 contains 1811 captions.
> eac3to processing took 7 minutes, 59 seconds.
> Done.
> 

FLAC mediainfo

> General
> Complete name                            : F:\[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID3 Japanese.flac
> Format                                   : FLAC
> Format/Info                              : Free Lossless Audio Codec
> File size                                : 2.17 GiB
> Duration                                 : 1 h 59 min
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 2 591 kb/s
> 
> Audio
> Format                                   : FLAC
> Format/Info                              : Free Lossless Audio Codec
> Duration                                 : 1 h 59 min
> Bit rate mode                            : Variable
> Bit rate                                 : 2 591 kb/s
> Channel(s)                               : 5 channels
> Channel layout                           : L R C LFE Cb
> Sampling rate                            : 48.0 kHz
> Bit depth                                : 24 bits
> Compression mode                         : Lossless
> Stream size                              : 2.17 GiB (100%)
> Writing library                          : libFLAC 1.3.3 (UTC 2019-08-04)

**Comment by stax76** [comment]
Using builds of random users is a security risk, do you have an account on doom9 or videohelp?

**Comment by pemaaaw** [comment]
> the libdcadec.dll and libFLAC.dll in eac3to are too old.
> 
> the FLAC still stay in v1.2.1 and dcadec have bugs in DTS-HD XLL and not support DTS Express.
> 
> My build with Visual Studio 2019.
> 
> https://mega.nz/#!dFAmEC4Y!WMTQvzLkfTDHPfhTXURSLaFWbmDMVaq3dKfk4ucjYrI
> 
> Source
> 
> FLAC 1.3.3 release https://github.com/xiph/flac
> 
> dcadec latest git https://github.com/withmorten/dcadec/
> 
> test
> 
> > ## eac3to v3.34
> > command line: "E:\StaxRip\Apps\Audio\eac3to\eac3to.exe" G:\CHARS_COUNTERATTACK_UHDBD\BDMV\STREAM\00003.m2ts 2: "F:[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID2 Japanese.flac" 3: "F:[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID3 Japanese.flac" 4: "F:[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID4 Japanese.sup" -progressnumbers
> > M2TS, 1 video track, 2 audio tracks, 1 subtitle track, 1:59:54, 11.988p
> > 1: h265/HEVC, 2160p24 /1.001 (16:9), 10 bits
> > 2: RAW/PCM, Japanese, 2.0 channels, 24 bits, 48kHz
> > 3: DTS Master Audio, Japanese, 3/1.1 channels, 24 bits, 48kHz
> > (core: DTS, 3/1.1 channels, 1509kbps, 48kHz)
> > 4: Subtitle (PGS), Japanese
> > [a02] Extracting audio track number 2...
> > [a03] Extracting audio track number 3...
> > [s04] Extracting subtitle track number 4...
> > [a02] Reading RAW/PCM...
> > [a02] Swapping endian...
> > [a02] Encoding FLAC with libFlac...
> > [a03] Decoding with libDcaDec DTS Decoder...
> > [a03] Encoding FLAC with libFlac...
> > [a03] Creating file "F:[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID3 Japanese.flac"...
> > [a02] Creating file "F:[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID2 Japanese.flac"...
> > [s04] Creating file "F:[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID4 Japanese.sup"...
> > [a02] The original audio track has a constant bit depth of 24 bits.
> > [a03] The original audio track has a constant bit depth of 24 bits.
> > Video track 1 contains 172464 frames.
> > Subtitle track 4 contains 1811 captions.
> > eac3to processing took 7 minutes, 59 seconds.
> > Done.
> 
> FLAC mediainfo
> 
> > General
> > Complete name                            : F:[philosophy-raws][Mobile Suit Gundam The Movie Char's Counterattack]\00003 ID3 Japanese.flac
> > Format                                   : FLAC
> > Format/Info                              : Free Lossless Audio Codec
> > File size                                : 2.17 GiB
> > Duration                                 : 1 h 59 min
> > Overall bit rate mode                    : Variable
> > Overall bit rate                         : 2 591 kb/s
> > Audio
> > Format                                   : FLAC
> > Format/Info                              : Free Lossless Audio Codec
> > Duration                                 : 1 h 59 min
> > Bit rate mode                            : Variable
> > Bit rate                                 : 2 591 kb/s
> > Channel(s)                               : 5 channels
> > Channel layout                           : L R C LFE Cb
> > Sampling rate                            : 48.0 kHz
> > Bit depth                                : 24 bits
> > Compression mode                         : Lossless
> > Stream size                              : 2.17 GiB (100%)
> > Writing library                          : libFLAC 1.3.3 (UTC 2019-08-04)

Hei, i'm confuse how to make libflac.dll like you do, is there any guide how to do it? i've been looking the guid but didn't really found it

**Comment by gonzalojp76** [comment]
Any chance for libFLAC v1.4.3 Release 2023-06-23?
https://github.com/xiph/flac
Thank you very much!

**Comment by Dendraspis** [comment]
Yes, it's already updated for the next release.  👍 

Please consider using our [Discord server](https://discord.gg/uz8pVR79Bd) or the [Tool Update Requests](https://github.com/staxrip/staxrip/wiki/Tool-Update-Requests) page for update requests.
