### ISSUE TITLE
Optional menu for deleting an item in Source Filters setting

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#322]
**Version info**
2.1.4.4 Beta x64

**Describe the situation**
Since there is no way to remove an existing item in Tools > Settings > **Source Filters** > AviSynth/VapourSynth, the only way to do it is deleting the File Type field. But if you confirm the deletion by clicking OK in the Settings window, an error message pops up as follows:

[Error message](https://pastebin.com/6J03CQEd)

Despite the pop-up error message, however, the entry is successfully removed if you click OK in the pop-up window.

**Expected behavior/suggestion**
The error message itself is a good signal, but it can give a false impression that your setting failed.
An item removal option in the Source Filters setting would be more appropriate.

**How to reproduce the issue**

1. Go to 'Tools > Settings > Source Filters > AviSynth or VapourSynth'
2. Create any item with any source filter, and then delete the File Type field.
3. Click 'OK'

**Comment by stax76** [comment]
Hello JJKylee,

in the next build the crash/error is fixed.

There will be two ways to delete a row:

1. click row header for row selection and then delete key.

2. clear the left cell.
