### ISSUE TITLE
Forked plugin: AddGrainC 1.8.2

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#325]
It's a simple request: I've tested the forked AddGrainC 1.8.2 from @pinterf on Staxrip 2.1.3.0 and it works. It seems to fix a few issues the 2013 release had. It would be nice to see this included in the next release.

I should add: it's comes compiled and available in both 64 and 32-bit. That should make any internal Staxrip development validation easier, if it's decided to add this.

https://github.com/pinterf/AddGrainC/releases/tag/v1.8.2

**Comment by stax76** [comment]
Available in the latest build.
