### ISSUE TITLE
Wrong value for Eac3to quality

### ISSUE THREAD

**Issue by inter5tella** [staxrip/staxrip#328]
**Describe the bug**
An invalid value for quality is chosen if eac3to is picked as encoder.

**Expected behavior**
After switching to Beta 2.1.4.4, I wasn't very comfortable with the low bitrate of qaac tvbr. So I edited the profile to always use Eac3to again. Unfortunately a quality value of '3,00' is selected as a default, which will bring eac3to to an error as the value has to be like '0,3'.

**How to reproduce the issue**
1. Go to audio lines and click on output format
2. Chose AAC
3. Click on 'Edit'
4. Select 'Eac3to' from Encoder and notice the command line 'eac3to -quality=3 -normalize'
5. Apply and start a encode

**Provide information**
Error log:

Error Audio Encoding 1 (2.1.4.4)

Audio Encoding 1 returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion

-------------------------- Audio Encoding 1 --------------------------

eac3to 3.34

"C:\Program Files\StaxRip\Apps\Audio\eac3to\eac3to.exe" "E:\Downloads\***\***_temp\ID1 German.dtshd" "E:\Downloads\***\***_temp\ID1 German_a1.m4a" -quality=3 -normalize -progressnumbers

Command line parameter "quality=3" is unknown.

StaxRip.ErrorAbortException: Audio Encoding 1 returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Unzulässige Funktion

-------------------------- Audio Encoding 1 --------------------------

eac3to 3.34

"C:\Program Files\StaxRip\Apps\Audio\eac3to\eac3to.exe" "E:\Downloads\***\***_temp\ID1 German.dtshd" "E:\Downloads\***\***_temp\ID1 German_a1.m4a" -quality=3 -normalize -progressnumbers

Command line parameter "quality=3" is unknown.

   bei StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:Zeile 377.
   bei StaxRip.GUIAudioProfile.Encode() in D:\Projekte\VB\staxrip\General\AudioProfile.vb:Zeile 751.
   bei StaxRip.GlobalClass._Closure$__._Lambda$__113-0() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 271.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 312.

**Comment by Dendraspis** [comment]
This seems to be correct, because `-quality=3` is an invalid parameter.

**Comment by JJKylee** [comment]
I confirm this on the _[eac2to documentation](https://en.wikibooks.org/wiki/Eac3to/How_to_Use#Command_Line_Syntax)_.
The value for _-quality_ should be 0.00~1.00.

> Nero AAC encoding quality (0.00=lowest; 1.00=highest) (default: 0.5)

**Comment by Dendraspis** [comment]
I'll have a look at it.

**Comment by Patman86** [comment]
I've fixed it...
see pull request #329
