### ISSUE TITLE
Disordered playlist selection

### ISSUE THREAD

**Issue by kurim** [staxrip/staxrip#332]
**Describe the bug**
"Please select a playlist" shows disorderd which may end up in wrong numbering the episodes

**Expected behavior**
Each playlist should be in correct order.

**How to reproduce the issue**
Open Bluray image, which includes not a move just a TVseries
![image](https://user-images.githubusercontent.com/1880220/92478353-550c6500-f1e2-11ea-93d5-7ac32c3d7e08.png)

I don't know if it's belong to staxrip or to eac3to.
[VALKYRIE DRIVE MERMAID VOL1_1 (h265)_staxrip.log](https://github.com/staxrip/staxrip/files/5188354/VALKYRIE.DRIVE.MERMAID.VOL1_1.h265._staxrip.log)

**Comment by Dendraspis** [comment]
This is the default behaviour of eac3to which sorts the playlists ascending by length. This is very welcome for movies, but indeed not ideal for tv series.

**Comment by kurim** [comment]
Hi Dendraspis,

thanks for fast feedback, when it's intended, than we can close it here.
