### ISSUE TITLE
New stable version for StaxRip

### ISSUE THREAD

**Issue by borgCubeSector009** [staxrip/staxrip#335]
Hello. Is there going to be a new stable version of StaxRip? It's been almost 3 months since the last release (v2.1.3.0 June 12).
I think it would be nice to have a stable version every 3 months. 
I avoid the beta versions, especially since I heard of the aliasing issue in the last version using VapourSynth R51.

**Comment by Dendraspis** [comment]
> I avoid the beta versions, especially since I heard of the aliasing issue in the last version using VapourSynth R51.

Such issues can also occur to stable versions. Nobody is going to check each tool line by line for bugs before they are included. 😉

**Comment by borgCubeSector009** [comment]
So, what would you recommend? Should I continue using the latest stable version or is it safe to use a beta version? Is the latest beta going to be ok?

**Comment by Dendraspis** [comment]
Hard to say. Depending on what's new and how you use StaxRip it is not necessary to update every time - currently I'm still using v2.1.3.8.
Everytime I update I check if every setting is working and I also check my first encode - just to be sure everything works. If something is dramatically wrong, someone is going to create an issue for that. But if a *Stable* is having this problem, it might take weeks till the next *Stable* appears, so there is no *best practice*.

I would stick to the latest (or one of the latest) *Beta*s. 

Tip: In the setting you can enable the update checker - and let it include beta versions.

**Comment by JJKylee** [comment]
Since StaxRip supports multiple instances simultaneously as long as you keep settings locally, I guess it's not a bad idea to keep different versions at the same time if you have enough space in the hard drive. 😄
