### ISSUE TITLE
BUG: v.2.1.4.4 asks for ffmpeg non-free path.

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#337]
**Describe the bug**
v.2.1.4.4 asks for ffmpeg non-free path. If I use the path to ffmpeg.exe (C:\Program Files\ffmpeg\bin) conversion starts, but stops before conversion completes.

**Expected behavior**
Should not ask for ffmpeg non-free path and should convert properly

![20091003](https://user-images.githubusercontent.com/16325865/92770376-e48f5080-f367-11ea-870b-32fbc6535d4c.png)
.
**How to reproduce the issue**

Convert file with Nvidia - H.265 or other encoder and AAC (at least that is how it happens for me).

If the issue happens only under special conditions then please describe how this conditions can be reproduced:

1. Load Project with AAC as audio profile
ffmpeg -c:a libfdk_aac -b:a 128k -ac 2

2. Load Source File - ASKS FOR PATH TO: ffmeg non-free

3. Using 'Nvidia - H.265 encoder (in my specific case).

![20091004](https://user-images.githubusercontent.com/16325865/92771057-90d13700-f368-11ea-9c6b-f0029fb26a7f.png)

![20091005](https://user-images.githubusercontent.com/16325865/92771906-4308fe80-f369-11ea-84b2-a3cf212537fd.png)

--avhw --cqp 25:32:34 --codec h265 --preset quality --output-depth 10 --aq --aq-temporal --bref-mode middle --gop-len 240 --lookahead 16 --multiref-l0 3 --multiref-l1 2 --strict-gop --output-buf 64

5. No Filters
6. Asks for ffmpeg non-free path with x264 encoder as well.

**Additional context**
Don't know what ffmeg non-free is, but App page should lead to a site that actually points to ffmpeg non-free info NOT general ffmpeg download site.

**Comment by JJKylee** [comment]
Choose **fdkaac**, not ffmpeg as the audio encoder.

This happens because your ffmpeg executable does not support **libfdk_aac** as an audio encoder. The ffmpeg executable you assigned as a non-free ffmpeg does not seem to be an actual non-free ffmpeg that support FDK-AAC.

**Comment by stax76** [comment]
I think it's more by design or lack of documentation instead of a bug. The default AAC encoder is not very good so it makes sense to use libfdk_aac.

**Comment by JJKylee** [comment]
> The default AAC encoder is not very good so it makes sense to use libfdk_aac.

True. But the issue here is that 2.1.4.4 **force**s users to use non-free ffmpeg whenever they choose ffmpeg for AAC. I think it's more desirable to let users _**choose** between _libfdk_aac_ and _aac_ depending on whether or not non-free ffmpeg is set up in Apps Management.

**Comment by stax76** [comment]
In the next build there is:

ffmpeg fdk-aac has an option and is disabled by default

![Untitled](https://user-images.githubusercontent.com/11410540/93014552-522ebd00-f5b2-11ea-8195-bc51def32894.png)

**Comment by JJKylee** [comment]
This looks reasonable.
