### ISSUE TITLE
Windows 10 long path support

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#338]
**Content was moved to the wiki:**

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by 44vince44** [comment]
@stax76 is there a way to pin this post on top? it seems like an important "dashboard"

**Comment by Dendraspis** [comment]
@44vince44 & @stax76 
I've pinned it. It makes sense because it is an information/overview.

**Comment by stax76** [comment]
Didn't know there is a pin feature, nice.

**Comment by stax76** [comment]
Merge request for x264:
https://code.videolan.org/videolan/x264/-/merge_requests/37

**Comment by stax76** [comment]
Maybe it's better using the wiki for tracking progress and also to describe the problems:

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by stax76** [comment]
@Patman86 

There has been a long path commit for MP4Box:

https://github.com/gpac/gpac/commit/1c6f924f054706abb448ff87b1a2e14f5d8d3a96

**Comment by Patman86** [comment]
I'll update some tools tomorrow in the evening.

**Comment by Statick** [comment]
what's the status of long path support for NVEnc / QSVEnc?

**Comment by Patman86** [comment]
Now I updated my builds.

**Comment by stax76** [comment]
Thanks for the new builds @Patman86 . I'll pause work on StaxRip for this year however to have some time for other software projects. Bye for now!

**Comment by 44vince44** [comment]
@stax76 thanks for all, have nice rest, and fun on other projects, however can't we have a last beta build with the last tools and commits, so in this time we can do testing?

**Comment by stax76** [comment]
@44vince44 thanks. There was only a small commit in an area that is not particular important (ffmpeg nvenc). I can upload new builds if @Dendraspis or somebody else contributes code.

There was a discussion about screenshot making lately, maybe you remember where it was, my current way for posting screenshots is not very productive.

**Comment by Squall-Leonhart** [comment]
So amusingly, you've broken paths that aren't even close to 200 characters in the latest builds, but older ones supported them just fine - except older builds (2.0.8.0 in this case) are unable to work with recent msvcp140, claiming them to be "old"

**Comment by Squall-Leonhart** [comment]
and the beta also throws the too old issue with the version of avisynth you recommended to be used in another bug, workaround - replace the system32 avisynth with the one included with staxrip beta.

**Comment by stax76** [comment]
@msg7086
@DJATOM
@Patman86
@richardpl
@Nevcairiel

I've updated our wiki page about long path support in Windows 10 today, it tracks the tool status and provides all resources tool authors may need to implement long path support in Windows 10. I can also provide guidance.

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by stax76** [comment]
Also @myrsloik

**Comment by stax76** [comment]
There is a new request on the nvenc tracker, it was forgotten to request before. 🙂

https://github.com/rigaya/NVEnc/issues/309

Wiki was updated:

https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support
