### ISSUE TITLE
Apps & some filters that need to be updated in 2.1.4.6

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#339]
### [Apps]
**NVEnc** is updated to [5.15](https://github.com/rigaya/NVEnc/releases/tag/5.15).
**AVSMeter** is updated to [3.0.3.0](https://forum.doom9.org/showthread.php?t=174797).
**VCEEnc** is now [6.03](https://github.com/rigaya/VCEEnc/releases/tag/6.03).
**Subtitle Edit** is now [3.5.16](https://github.com/SubtitleEdit/subtitleedit/releases/tag/3.5.16).
**chapterEditor** is now [1.24](https://forum.doom9.org/showthread.php?t=169984).
@Patman86 's **ffmpeg** is now N-98942.
@Patman86 's **x264** is now 0.161.3018.

### [Filters]
**L-SMASH-Works** is updated to [20200728](https://github.com/HolyWu/L-SMASH-Works/releases/tag/20200728).
**MPEG2DecPlus** is renamed to [D2VSource](https://github.com/Asd-g/MPEG2DecPlus/releases/tag/1.0.0).

The above filters list is not exhaustive. Guys, please complement it by adding what you know about.

**Comment by Sledge-Hammer** [comment]
**MKVMerge** is now [50.0](https://mkvtoolnix.download/doc/NEWS.md)

**Comment by JJKylee** [comment]
> **MKVMerge** is now [50.0](https://mkvtoolnix.download/doc/NEWS.md)

2.1.4.6 ships with mkvmerge/mkvextract/mkvinfo 50.

BTW, **qaac** is updated to [2.70](https://www.videohelp.com/software/qaac).
**AVSMeter** is updated to [3.0.4.0](https://forum.doom9.org/showthread.php?t=174797).

**Comment by vonH** [comment]
https://github.com/staxrip/staxrip/issues/325

**Comment by stax76** [comment]
@JJKylee 

On the long run it's too much of a burden for the maintainer to update all tools manually. Here is an idea on how to make it collaborative:

In the apps dialog there would be a submit feature to upload the tool to a ftp folder, only contributors can see and use the feature.

Download, extraction, integration etc. would be automated so the project maintainer has much less manual work.

It's the simplest idea I have and I'm not sure if it's a good idea. I don't have much experience with web related and security topics however.

**Comment by JJKylee** [comment]
> On the long run it's too much of a burden for the maintainer to update all tools manually.

I agree. You're totally right on it.

> Here is an idea on how to make it collaborative:
> 
> In the apps dialog there would be a submit feature to upload the tool to a ftp folder, only contributors can see and use the feature.
> 
> Download, extraction, integration etc. would be automated so the project maintainer has much less manual work.
>
> It's the simplest idea I have and I'm not sure if it's a good idea. I don't have much experience with web related and security topics however.

Sounds like a good idea as long as it's implemented. Food for thought.

**Comment by Dendraspis** [comment]
> In the apps dialog there would be a submit feature to upload the tool to a ftp folder, only contributors can see and use the feature.

..but the function and login data would be available for everyone via source code, right?  :thinking:

**Comment by Patman86** [comment]
You can sync the ftp with my mediafire folder if you want.

**Comment by stax76** [comment]
> ..but the function and login data would be available for everyone via source code, right?

Not via source code but configuration.

The alternative would be trying to write a tool that finds and updates new versions automatically, it's more ambitious but maybe quite possible for most tools.

**Comment by therealt3nzin** [comment]
Closest thing to what you're describing is probably a combination of [scoop](https://github.com/lukesampson/scoop) and [0install](https://github.com/0install/0install-win)

**Comment by stax76** [comment]
0install is new to me, thanks.

**Comment by stax76** [comment]
I've a local branch with an auto update feature ready, it works with GitHub releases, but with MediaFire it cannot even extract the download URLs. 🤔

**Comment by Patman86** [comment]
Based on what source?

**Comment by stax76** [comment]
https://github.com/staxrip/staxrip/blob/master/General/ToolUpdate.vb#L24

**Comment by therealt3nzin** [comment]
[mediafire-dl](https://github.com/Juvenal-Yescas/mediafire-dl) might be a solution to that

**Comment by stax76** [comment]
Looks promising.
