### ISSUE TITLE
2.1.4.6: Setting AAC codec Decoding Method to Pipe causes error

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#340]
**Describe the bug**
In audio profile, choosing **AAC** and setting its Decoding Method to **Pipe** causes an error and pops up an error message window.

**How to reproduce the issue**
1. In any template or project, go to 'Audio'
2. Choose 'AAC' and click 'Edit'
3. Click 'More...'
4. In General, choose 'Pipe' as 'Decoding Method'

**Error Log**
The error log is [here](https://pastebin.com/UegwTr2g).

**Additional Information**
Only AAC has this problem. Other audio codecs are OK.

**Question**
Whether I choose to report the bug or not, the main window just closes and the program ends.
(report ⇒ opens the log, the browser goes to the issue tracker page, and the program exits,
not report ⇒ the program just exits.)
Is this intended?

**Comment by Mister-XY** [comment]
Same problem here. if i choose qaac i get also error message. If i use ffmpeg, all is fine.
![qaac](https://user-images.githubusercontent.com/10309056/93045581-ccfde380-f657-11ea-928f-a9080c47745d.png)
![qaac2](https://user-images.githubusercontent.com/10309056/93045583-cd967a00-f657-11ea-9e52-fe54b8ac46c0.png)

**Comment by JJKylee** [comment]
Yes. I verified that among the five AAC encoders,

Automatic, qaac, fdkaac ⇨ error
eac3to, ffmpeg ⇨ OK.

Please take a look.

**Comment by VEGAX265** [comment]
Same here updated from beta 2.1.4.4 to beta 2.1.4.6 as well as clean install of beta 2.1.4.6  Hope this gets fixxed! thanks guys

**Comment by GregoryL77** [comment]
I think here is the culprit in audioprofile.vb, in the last stringbuilder commit, (btw  makes audio dialog more responsive, for sure): https://github.com/GregoryL77/staxrip/commit/f227161cd112c493eb23496d50a86d7ff695094a , this works for me
