### ISSUE TITLE
2.1.4.6: AAC ffmpeg setting lacks a critical parameter and bitrate selection is always disabled

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#341]
**Describe the bug**
In Audio Settings, selecting **ffmpeg** for AAC misses an indispensable parameter: `-c:a aac`

See this screenshot:
![StaxRip-2 1 4 6_aac_ffmpeg_bug](https://user-images.githubusercontent.com/3157518/93045552-4e2f8900-f60c-11ea-877e-816e0c590797.gif)

And I cannot choose a bitrate instead of a quality no matter what.
Even in "Use fdk-aac", I cannot choose a bitrate.

**Expected behavior**
`-c:a aac` should be in the command line in place of `-c:a libfdk_aac` if "Use fdk-aac" is _not_ checked.
And the user should be able to choose between bitrate and quality. It'd be good if this option is put in the **Advanced** section.

**Comment by vonH** [comment]
Is the output correct if you use a command line (Staxrip -> Audio -> Command Line -> Edit)?

Here's a screenshot of the UI I see. Yours appears to be different
![image](https://user-images.githubusercontent.com/10042301/93259618-063d6d00-f798-11ea-95f2-f63781fa2df1.png)

**Comment by JJKylee** [comment]
Of course you can _always_ add a custom command line profile and avoid this issue.
But I'm talking about the **default** AAC/ffmpeg profile settings in StaxRip.

**Comment by Dendraspis** [comment]
Still to do:

> And I cannot choose a bitrate instead of a quality no matter what.
Even in "Use fdk-aac", I cannot choose a bitrate.

**Comment by Patman86** [comment]
my changes fixed that issue, see pull request

**Comment by stax76** [comment]
Not sure if it's finished now, I'll take another look tomorrow (at home).

**Comment by stax76** [comment]
Is it OK now with the newest build?

**Comment by JJKylee** [comment]
> Is it OK now with the newest build?

It looks fine in 2.1.4.7. Good job! 😃
