### ISSUE TITLE
What do this app exactly do?? Download streaming videos?

### ISSUE THREAD

**Issue by Notorious2Beat** [staxrip/staxrip#343]
This template is meant for usage questions of StaxRip.

**Comment by Dendraspis** [comment]
### Short answer
It changes your life! 

### Long answer
Check the ...
-  [repository start page](https://github.com/staxrip/staxrip) and/or ...
- [Readme](https://github.com/staxrip/staxrip/blob/master/README.md) and/or ...
- [Docs](https://staxrip.readthedocs.io/)
