### ISSUE TITLE
2.1.4.6: Folder for user added DUAL mode plugins is needed

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#349]
**Is your feature request related to a problem? Please describe.**
Currently, only _AviSynth_ and _VapourSynth_ folders are created in _%settings_dir%Plugins_ folder at the first launch of StaxRip. Therefore, when users want to add their own filters supporting **dual** mode, such as DFTTest Neo, DGDecNV, DGHDRtoSDR, FFT3D Neo, etc., they are forced to put them in either of these two folders and make use of the autoload function in the portable frameserver mode, giving up one of the two ― AviSynth and VapourSynth ― modes. Otherwise, they need to create another folder for those filters under _%settings_dir%Plugins_ and customize both AVS and VS profiles to include the corresponding folder (_LoadPlugin_) when the dual mode filter is called, even in the portable frameserver mode.

**Describe the solution you'd like**
Another folder named, for example, **_Dual_** needs to be created in _%settings_dir%Plugins_ folder along with the other two at the time of first launch, and it should be autoloaded in both AVS and VS (_AddAutoloadDir_). This way, users can always put their own dual mode filters there and make use of the autoload function in the portable frameserver mode.

**Additional issue**
Users of _installed_ frameserver mode still need to customize the AVS and VS profiles to load the filter folders manually. I'm wondering if autoload does not work in the installed frameserver mode.

**Comment by stax76** [comment]
Please try with the latest beta build.

**Comment by JJKylee** [comment]
OK. I admit that I was mistaken in understanding how _AddAutoloadDir_ works. It does NOT **recursively** search for plugins in the subfolders. That means, simply putting a filter **folder** in an Autoloaded folder does not activate the filter: we need to put _dll_'s and _avsi_'s in the Autoloaded folder, but this messes up the folder structure of some filters like DGDecNV. So, I guess we still need to put _LoadPlugin_ or _Import_ functions in order to preserve the folder structure and call filters put in subfolders of _%settings_dir%Plugins_ folder even if they are Autoloaded no matter whether the frameservers are portable or installed.

What makes things more complicated is that we can put simple filters composed of _dll_'s or _avsi_'s only in the Autoloaded folder and omit _LoadPlugin_ or _Import_ functions regardless of the frameserver's mode. But well, in 2.1.4.7, Autoload of subfolders of _%settings_dir%Plugins_ folder is not written in the app itself. (It's up to users to put the code.)

Anyway, creation of _%settings_dir%Plugins\Dual_ along with _AviSynth_ and _VapourSynth_ is successful in 2.1.4.7. I think we'd better leave it at that for the time being until recursive search in Autoloaded folder is supported in AviSynth+ or so.

**Comment by stax76** [comment]
In mpv.net the DLL name must be identical to the folder name:

https://github.com/stax76/mpv.net/blob/master/Manual.md#extensions

That pattern could also make sense for avisynth and vapoursynth.
