### ISSUE TITLE
Incorrect commandline args for nVidia Encoder

### ISSUE THREAD

**Issue by fecheva** [staxrip/staxrip#350]
When trying to encode with nVidia H265 and deinterlacing:

if I try to use nnedi Deinterlacer, it generates commandline arguments:

--cqp 18 --codec h265 --sar 16:11 --vpp-nnedi field=top

if I try to use Yadif Deinterlacer, it generates commandline arguments:
--cqp 18 --codec h265 --sar 16:11 --vpp-yadif mode=tff

In any case, or if I just set field to "AUTO", I get the error message:

"Please set input interlace field order (--interlace tff/bff) for <vpp-nnedi|vpp-yadif>".

So I suspect, or there is a bug building the commandline args or I have some non-compatible API in my codec. Anyway, I uptated nVidia CUDA yesterday.

**Comment by JJKylee** [comment]
This is not a bug. It's a matter of how you build the options setting.

You just need to follow the error message and search for "**interlace**" in the NVEnc options search field.

![StaxRip-2 1 4 6-Beta_NVEnc-options_Interlace_20200925](https://user-images.githubusercontent.com/3157518/94327589-da24a780-ff60-11ea-9722-892f26b8943f.jpg)

Click enter until you find the proper option, then choose the appropriate value.

**Comment by fecheva** [comment]
Oh! Thanks! :-)
