### ISSUE TITLE
makes stax work right for once

### ISSUE THREAD

**Issue by dchgjhcchdjcdlhilcudh** [staxrip/staxrip#351]
all it is one giant error. It does not work at all. It is poorly developed. Everything i touch in the UI or everything I attempt to do results in some error or when there is no error the program will disregard all my settings and use it's own crappy stock settings. I have no idea how any one is using this. I can not simply add one video and add settings and get it to encode with out having to fight with it. I only use this crap software twice, maybe three times a year and everytime it is a nightmare.

Add file
add setting
press start

Not that hard. one more time

add file
add setting
press start

Why does this not apply? Seriously? Why

**Comment by 44vince44** [comment]
Guess who.. it's our old friend again...
