### ISSUE TITLE
Gain Error

### ISSUE THREAD

**Issue by MrOctober77** [staxrip/staxrip#352]
Encoding a video, it got to 100 but when finishing up Staxrip crashed.
[2020-10-02 20-12-00_new_staxrip.log](https://github.com/staxrip/staxrip/files/5321867/2020-10-02.20-12-00_new_staxrip.log)

**Comment by stax76** [comment]
```
----------------------------- Find Gain 1 -----------------------------

ffmpeg N-97868-gaa6f38c298-g38490cbeb3-gcc10.1.0 Patman

C:\Users\Don\Documents\Staxrip2.1.3\Apps\Encoders\ffmpeg\ffmpeg.exe -i "D:\Media\MyVideos\2020-10-02 20-12-00_temp\2020-10-02 20-12-00 ID1.mka" -sn -vn -hide_banner -af volumedetect -f null NUL

[matroska,webm @ 000001d082312b00] Format matroska,webm detected only with low score of 1, misdetection possible!
[matroska,webm @ 000001d082312b00] EBML header parsing failed
D:\Media\MyVideos\2020-10-02 20-12-00_temp\2020-10-02 20-12-00 ID1.mka: Invalid data found when processing input
```

There might be something wrong with the source mka file or with ffmpeg.

**Comment by JJKylee** [comment]
Looking at the log, you can see that the audio track was not properly extracted in the first place.

```
Error: Track 1 with the CodecID 'A_AAC' is missing the "codec private" element and cannot be extracted.

General
Complete name : D:\Media\MyVideos\2020-10-02 20-12-00_temp\2020-10-02 20-12-00 ID1.mka
File size     : 0.00 Byte
```

You need to check if your source file is playable. According to [this post](https://forum.doom9.org/showthread.php?p=1695495#post1695495), mkvmerge mistakes a raw pcm file as an mpeg4 part10/avc stream and muxes into a non-playable mkv file. I'm not sure if this still holds, but at least it seems that you need to check the integrity of your source file.
