### ISSUE TITLE
Create default filter profiles for all included filters 

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#355]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but I see no point in including filters but not having a basic default included in the UI. AddGrainC is a good example - it's included but there's no option in the Filters downdrop.

**Describe the solution you'd like**
Rework the default Filters. Take AddGrainC, for example:

>[Noise]
Remove Noise | DeGrainMedian = DeGrainMedian(limitY=4, limitUV=6, mode=1, interlaced=false, norow=false)
Remove Noise | DeNoise | Denoise MD = DeNoiseMD1(sigma=4, overlap=2, thcomp=80, str=0.8)DitherPost(mode=7, ampo=1, ampn=0)
Remove Noise | DeNoise | Denoise MF = DenoiseMF2(s1=2.0, s2=2.5, s3=3.0, s4=2.0, overlap=4, thcomp=80, str=0.8, gpu=$select:msg:Use GPU Enabled Feature?;True;False$)
Remove Noise | DFTTest = dfttest($select:msg:Select Strength;Light|sigma=6, tbsize=3;Moderate|sigma=16, tbsize=5;Strong Static|sigma=64, tbsize=1;Strong Temporal|sigma=64, tbsize=3$,$select:msg:Reduce Banding?;No Deband| dither=0;Deband| dither=1;Add Noise| dither=2;More Noise| dither=3$)
Remove Noise | FFT3DFilter | FFT3DFilter = FFT3DFilter()
Remove Noise | FFT3DFilter | FFT3DGPU = FFT3DGPU(sigma=1.5, bt=5, bw=32, bh=32, ow=16, oh=16, sharpen=0.4, NVPerf=$select:msg:Enable Nvidia Function;True;False$)
Remove Noise | HQDN3D = HQDN3D(ls=4.0, cs=3.0, lt=6.0, ct=4.5, restart=7)
Remove Noise | mClean = mClean()
Remove Noise | MCTemporalDenoise | MCTemporalDenoise = MCTemporalDenoise(settings="medium")
Remove Noise | MCTemporalDenoise | MCTemporalDenoisePP =
    source=last
    denoised=FFT3Dfilter()
    MCTemporalDenoisePP(denoised)
Remove Noise | MiniDeen = MiniDeen(radius=1, thrY=10, thrUV=12, Y=3, U=3, V=3)
Remove Noise | NLMeans | KNLMeansCL = KNLMeansCL(D=1, A=1, h=$select:msg:Select Strength;Light|2;Medium|4;Strong|4$, device_type="auto")
Remove Noise | NLMeans | TNLMeans = TNLMeans(Ax=4, Ay=4, Az=0, Sx=2, Sy=2, Bx=1, By=1, ms=false, rm=4, a=1.0, h=1.8, sse=true)
Remove Noise | NLMeans | xNLMeans = xnlmeans(a=4,h=2.2,vcomp=0.5,s=1)
Remove Noise | RemoveGrain | RemoveGrain = RemoveGrain(mode=2, modeU=2, modeV=2, planar=false)
Remove Noise | RemoveGrain | RemoveGrain | RemoveGrain16 with Repair16 =
    Processed = Dither_removegrain16(mode=2, modeU=2, modeV=2)
    Dither_repair16(Processed, mode=2, modeU=2, modeV=2)
Remove Noise | RemoveGrain | RemoveGrain With Repair =
    Processed = RemoveGrain(mode=2, modeU=2, modeV=2, planar=false)
    Repair(Processed, mode=2, modeU=2, modeV=2, planar=false)
Remove Noise | SMDegrain | SMDGrain = SMDegrain(tr=2, thSAD=250, contrasharp=false, refinemotion=true, lsb=false)
Remove Noise | SMDegrain | SMDGrain 16Bit =
    sharp=last
    dfttest(tbsize=1, sigma=10, lsb=True)
    SMDegrain(tr=3, thSAD=300, CClip=sharp, lsb_in=True, lsb_out=True)
Remove Noise | SMDegrain | SMDGrain With Motion Vectors =
    super_search = Dither_Luma_Rebuild(S0=1.0, c=0.0625).MSuper(rfilter=4)
    bv2 = super_search.MAnalyse(isb=true,  delta=2, overlap=4)
    bv1 = super_search.MAnalyse(isb=true,  delta=1, overlap=4)
    fv1 = super_search.MAnalyse(isb=false, delta=1, overlap=4)
    fv2 = super_search.MAnalyse(isb=false, delta=2, overlap=4)
    MDegrain2(MSuper(levels=1), bv1, fv1, bv2, fv2, thSAD=300, thSADC=150)
Remove Noise | VagueDenoiser = VagueDenoiser(threshold=0.8, method=1, nsteps=6, chromaT=0.8)

>Add Noise | AddGrainC = AddGrainC(var=1.0, uvar=0.0, hcorr=0.0, vcorr=0.0, seed=6, constant=false, sse2=true)

This is only one example, but it instantly tells the user that there are options to remove noise/grain, or add noise/grain and what those options are. I believe the new versions will not use tooltips, instead opting to take a user to the wiki or docs where these filters are explained in more detail. This would compliment that (and make it worth including the many filters without default profiles).

**Describe alternatives you've considered**
Adding Undot and AddGrainC myself, but why include them at all if they don't have profiles?

**Explain why the feature matters to you**
It makes sense.

**Comment by vonH** [comment]
That's a fair point. I wouldn't mind going through the filters included and created a restructured menu, if that helps?

**Comment by JJKylee** [comment]
> That's a fair point. I wouldn't mind going through the filters included and created a restructured menu, if that helps?

Sounds good. You can be a collaborator in this matter if you want to, @vonH . Composing AVS/VS filter profiles is not that hard, and IMHO, the learning curve is pretty flat. I guess sharing your profiles code for specific filters on the Wiki section of this repo will be pretty helpful for other users.

As for me, I personally think that **not** all default filter profiles are necessary. To be frank, I don't use many filters except for some several essential filters, so I think the current filters menu is kind of excessive. I just think of the collection of default filters as an _inventory_ so that I can invoke any of them by composing a code snippet when I need it. The help system in StaxRip is pretty good, and Avisynth Wiki is always there to help us.

I know. Lots of users may find this process uncomfortable. But Wiki does not exist for nothing. People like you can help by putting your own code there for sharing. I think this is much more efficient than putting all the profiles in the program by default.  😄

**Comment by vonH** [comment]
> I know. Lots of users may find this process uncomfortable. But Wiki does not exist for nothing. People like you can help by putting your own code there for sharing. I think this is much more efficient than putting all the profiles in the program by default. 😄

That wasn't the suggestion I was making. Either way, I took a more in depth look at the included filters and it seems this request is not workable. I'll close it.
