### ISSUE TITLE
Aomenc CDEF option is backwards. Off is On.

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#358]
**Staxrip Version:**
StaxRip-x64-2.1.3.0-stable

**Describe the bug**
Enable CDEF option is backwards.  On is Off.

**Expected behavior**
If user sets Misc 1 > Enable CDEF to "On", then the parameter should be omitted since 1 (On) is default.

If user sets Misc 1 > Enable CDEF to "Off", then the parameter should become `--enable-cdef=0`

**How to reproduce the issue**

1. set video encoder to AV1 - aomenc
2. go to encoder options
3. go down to "Misc 1" in the left sidebar menu
4. change "Enable CDEF" to "On"
5. notice below, `--enable-cdef=1`.  (This is wrong.)  It should be omitted since 1 (On) is default
6. change "Enable CDEF" to "Off"
7. notice below, `--enable-cdef` has been removed.  (This is wrong.) It should be ADDED as `--enable-cdef=0`

From AV1 Parameters:
`--enable-cdef=<arg>         Enable the constrained directional enhancement filter (0: false, 1: true (default))`

**Comment by JJKylee** [comment]
This issue still exists in 2.1.4.7.

![StaxRip_2 1 4 7_aomenc_settings_bug_CDEF_20201006](https://user-images.githubusercontent.com/3157518/95260232-3a2b1180-07dd-11eb-9071-64a0f44c5441.gif)

**Comment by stax76** [comment]
I've fixed it but users need to reset it manually.

**Comment by JJKylee** [comment]
> I've fixed it but users need to reset settings manually.

You mean, Video Encoder Profiles?

**Comment by stax76** [comment]
Yes, but it's not necessary to reset all video encoder profiles but rather use `Add` and `Remove` in the profile editor.

**Comment by JJKylee** [comment]
Yes, I was thinking about that. Thanks. 😄

**Comment by stax76** [comment]
New beta is out, I hope it's fixed.
