### ISSUE TITLE
Add missing "Frame Boost" option to AOMENC

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#359]
**Is your feature request related to a problem? Please describe.**
Missing feature from AOMENC

**Describe the solution you'd like**
Add a dropdown menu option for "Frame Boost"
0 (Off) Default <-- StaxRip Prefer
1 (On)

**Describe alternatives you've considered**
It can be added as a custom parameter from the "Misc 1" > "Custom" input field.  `--frame-boost=1`

**Explain why the feature matters to you**

Frame boost 1 (On) might be beneficial if you're doing higher quality encodes with encoded grain (not synthetic grain).  I haven't tested this yet to confirm, but I'm sure there's a usage case for this somewhere.

When I asked what this was in the AV1 Discord channel:
``what is frame periodic boost?``

This is the answer I received:
``IIRC it's not helpful, and might be harmful
I think it lowers the QP for every so-many frames``

So, based on that limited conversation, I'd recommend in StaxRip, setting it to 0 (Off), simply because having it off is better than having it on (I guess).

Based on this logic, having periodic frame boost ON, might cause the final filesize to be larger than having it Off, since lowered CQ = more bits = bigger file.  AV1 community seems like they know what they're doing, and they recommend it 0 (OFF), so I guess we should just stick with what they've figured out.  Right now, AV1 is most useful for very small filesizes (default is `--cq-level=30`), so, might as well accept that smaller filesize at expense of a bit of lost quality = preferred behavior.

**Additional context**
From the AV1 (AOMENC) Parameter List:
`--frame-boost=<arg>         Enable frame periodic boost (0: off (default), 1: on)`

**Comment by JJKylee** [comment]
I confirm that it's still missing in 2.1.4.7.

**Comment by stax76** [comment]
Should it be a dropdown or a checkbox?

**Comment by JJKylee** [comment]
It's Boolean, so I think a checkbox will be enough.

**Comment by Neltulz** [comment]
Agree, checkbox is probably fine.

**Comment by stax76** [comment]
I hope it's fine in the last beta.
