### ISSUE TITLE
ArgumentOutOfRangeException (2.1.3.0) - Transcoding 1080p h.264 to 720p XviD

### ISSUE THREAD

**Issue by JK98062** [staxrip/staxrip#360]
**Describe the bug**
When attempting to Transcode a 1080p h.264 file to 720p XviD, an ArgumentOutOfRangeException error occurs and StaxRip force quits.

**Expected behavior**
It probably goes without saying, but I expected the File to be converted successfully.

**How to reproduce the issue**
My workflow was as follows: load File > select template > demux > index > select output location > submit job to job list > commence transcoding > error occurs.

**Provide information**
I've attached the StaxRip Log as well as the .srip File.
[The Cannonball Run.srip.log](https://github.com/staxrip/staxrip/files/5336172/The.Cannonball.Run.srip.log)
[The Cannonball Run_staxrip.log](https://github.com/staxrip/staxrip/files/5336162/The.Cannonball.Run_staxrip.log)

MediaInfo for the File: [MediaInfo.NET Information - Pastebin](https://pastebin.com/ec4YGLvq)
I also uploaded a ~1 Minute Clip of the Video in it's native format to Streamable, these are the Direct Links to the Hosted File and a Viewer Link: [Streamable Hosted File Direct Link](https://cdn-cf-east.streamable.com/video/mp4/9cxyr5.mp4?Expires=1602272820&Signature=PmFqRyTH7MoTzGev7mL80b1fJobp4nKNn-WhMVcrdld-2jCtp1Dfj4NtokuPp~-x6q~zslHHP7~ykBeiT9B-pN0vesBrNdl-LPOrTk2St19fQ5kO5lXYGLOo25hQBjYNJHtE0cN322wB~IuJXVjvOmNnaSDVb1DolU0VuC2x5QCfFxvU9pMZODF3-NB2PoU49YGIksx2kpwVQiT37gh1SR9lbhDxxKV1wqNqhQ0-ckVI8~QCUrLFKW-MUwzb2Kf3Wij9EV-5A9U0nseo3tmwv-Oyl7I-aq8YZLvRDm3uBy1F4p8G-fXejbZna4CWav3-zP6n~s-9ktp-b6k8ywc~sA__&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ) or [Viewer Link](https://streamable.com/9cxyr5)

Any suggestions on what to do next?
Let me know if you need me to provide the Template I used, or any further info.

**Comment by stax76** [comment]
It's unusual that the log file does not contain debug info about the exception. It could mean that there is a problem with the error handling. Without that info it's difficult to understand what the problem is. From where do you know that it is a ArgumentOutOfRangeException?

**Comment by JK98062** [comment]
> It's unusual that the log file does not contain debug info about the exception. It could mean that there is a problem with the error handling. Without that info it's difficult to understand what the problem is. From where do you know that it is a ArgumentOutOfRangeException?
> 
> I think there was a ArgumentOutOfRangeException recently fixed so with the last beta this error is probably fixed:
> 
> https://staxrip.readthedocs.io/introduction.html#beta
> 
> https://github.com/staxrip/staxrip/issues?q=is%3Aissue+ArgumentOutOfRangeException

I know it’s an ArgumentOutOfRangeException due to that being the Title of the Error Pop-Up Window that’s shown upon commencing Transcode.
It’s quite easily reproducible if you want to see for yourself, simply download the video I linked (Direct Link) which is a 1 minute clip in the Native Format of the Source, and follow the same workflow I listed above. Re-Sizing to 720p XviD at 2304MB Output File Size, with 320kbps MP3.

**Comment by stax76** [comment]
Please try if it happens with the last beta. It should not because it was fixed before.

**Comment by vonH** [comment]
> When attempting to Transcode a 1080p h.264 file to 720p XviD, an ArgumentOutOfRangeException error occurs and StaxRip force quits.

Out of curiousity, why re-encode H.264 to XviD? The only reason I can think of is hardware limitation.

**Comment by JK98062** [comment]
@stax76  Transcode completes successfully on v2.1.4.8 Beta.

@vonH  Basically, I’m stuck living in the past thanks to my compulsion to have my entire library encoded using the exact same Codec combination which is XviD + MP3 because that’s what I started collecting in 2003/4.
When you’ve got OCD about everything being the same format and you’ve got a library consisting of 1800 movies; at least 500 of which being extremely rare; 14100 episodes of TV; ~3400 rare ones; and over 1000 stand up comedy specials;  nearly half of which can’t be found online; you might be able to understand my reluctance to try and switch from XviD to H.264. Would consider it more seriously if I had a Compute Farm to help Transcode all ~13TB of my library. Haha
