### ISSUE TITLE
Default Subtitle choice in Project Options

### ISSUE THREAD

**Issue by nitz-tech** [staxrip/staxrip#362]
Hello, 

I'm trying to use the "Native" subtitle feature in "Project Options", but it doesn't seem to work as suggested or it's misunderstanding on my part. 

For me, "Native" should select in my opinion the subtitle track which was by default in the base file before conversion, but it seems to choose the first "preferred" language. 

Would it be possible to have everything muxed with the initial default track of the file? 

If everything is currently working as you wish, would it be possible to add an option in this direction please, it would be really easier, especially in the case of "forced" tracks which are not necessarily in the correct order in the file basic please? 

Thank you very much for this practical software!

**Comment by stax76** [comment]
For the _Default Subtitle_ dropdown in the project options the next build has a new _Default_ option.

If tested this with a MKV source containing text subtitles.
