### ISSUE TITLE
-hwaccel cuvid depreciated command in ffmpeg Options

### ISSUE THREAD

**Issue by nitz-tech** [staxrip/staxrip#363]
Hello, when we try to use the hardware decoder of the NVidia card with the ffmpeg encoder and not the nvenc.c one, we get an error that the command is deprecated and the encoding stops immediately. 

Would it be possible to make the necessary adjustment please, this is indicated in the error message below. 

Thank you!

`
---------------- Video encoding Nvidia | Nvidia H.265 ----------------

ffmpeg N-98647-gffa6072fc7-x64-gcc10.2.0 Patman

C:\Users\XYZ\Desktop\StaxRip\StaxRip-x64-2.1.4.7-Beta\Apps\Encoders\ffmpeg\ffmpeg.exe -hwaccel cuvid -i C:\Remux\Web\Web-DL-Test.mkv -c:v hevc_nvenc -threads 4 -profile:v main10 -pix_fmt p010le -preset p7 -b:v 2500k -an -y -hide_banner C:\Remux\Web\Web-DL-Test_Temp\Web-DL-Test_new_test_out.mkv

WARNING: defaulting hwaccel_output_format to cuda for compatibility with old commandlines. This behaviour is DEPRECATED and will be removed in the future. Please explicitly set "-hwaccel_output_format cuda".
Guessed Channel Layout for Input Stream #0.1 : 5.1
Guessed Channel Layout for Input Stream #0.2 : 5.1
Input #0, matroska,webm, from 'C:\Remux\Web\Web-DL-Test.mkv':
  Metadata:
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-04-03T04:51:45.000000Z
  Duration: 00:48:48.03, start: 0.000000, bitrate: 11429 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x960 [SAR 1:1 DAR 2:1], 23.98 fps, 23.98 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      BPS-eng         : 9890810
      DURATION-eng    : 00:48:48.009000000
      NUMBER_OF_FRAMES-eng: 70202
      NUMBER_OF_BYTES-eng: 3620047742
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(fre): Audio: eac3, 48000 Hz, 5.1, fltp (default)
    Metadata:
      title           : French
      BPS-eng         : 768000
      DURATION-eng    : 00:48:48.032000000
      NUMBER_OF_FRAMES-eng: 91501
      NUMBER_OF_BYTES-eng: 281091072
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: eac3, 48000 Hz, 5.1, fltp
    Metadata:
      title           : English
      BPS-eng         : 768000
      DURATION-eng    : 00:48:48.032000000
      NUMBER_OF_FRAMES-eng: 91501
      NUMBER_OF_BYTES-eng: 281091072
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(fre): Subtitle: subrip (default) (forced)
    Metadata:
      title           : French (Forced)
      BPS-eng         : 0
      DURATION-eng    : 00:47:29.057000000
      NUMBER_OF_FRAMES-eng: 6
      NUMBER_OF_BYTES-eng: 133
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(fre): Subtitle: subrip
    Metadata:
      title           : French
      BPS-eng         : 52
      DURATION-eng    : 00:47:29.057000000
      NUMBER_OF_FRAMES-eng: 622
      NUMBER_OF_BYTES-eng: 18839
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(fre): Subtitle: subrip
    Metadata:
      title           : French (SDH)
      BPS-eng         : 67
      DURATION-eng    : 00:47:29.057000000
      NUMBER_OF_FRAMES-eng: 717
      NUMBER_OF_BYTES-eng: 23974
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS-eng         : 66
      DURATION-eng    : 00:44:30.880000000
      NUMBER_OF_FRAMES-eng: 666
      NUMBER_OF_BYTES-eng: 22139
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:7(eng): Subtitle: subrip
    Metadata:
      title           : English (SDH)
      BPS-eng         : 71
      DURATION-eng    : 00:45:34.151000000
      NUMBER_OF_FRAMES-eng: 743
      NUMBER_OF_BYTES-eng: 24398
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 04:51:45
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc))
  Stream #0:3 -> #0:1 (subrip (srt) -> ass (ssa))
Press [q] to stop, [?] for help
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
Conversion failed!`

**Comment by 44vince44** [comment]
@stax76 this has been brought up in that thread (still open) : https://github.com/staxrip/staxrip/issues/285

quote:
**replace syntax "-hwaccel cuvid" with "-hwaccel_output_format cuda" for both Nvidia/h264 and Nvidia/h265**
(of course, it's about ffmpeg/Nvidia)
etc..

**Comment by stax76** [comment]
@44vince44 OK thanks, should be fine in the last beta, so closing.
