### ISSUE TITLE
Include AOMENC 2.0.0-892 (or newer) with StaxRip

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#364]
**Is your feature request related to a problem? Please describe.**
I noticed StaxRip does not include AOMENC, therefore it must be either compiled yourself, or a precompiled build must be downloaded from the net.

**Describe the solution you'd like**
Include version 2.0.0-892 or newer from this source:

https://ci.appveyor.com/project/marcomsousa/build-aom/build/artifacts  <-- I recommend this version

**Explain why the feature matters to you**
1. According to AV1 User BlueSwordM, this version has faster first-pass encoding capability as mentioned here:
> However, make sure to provide the latest master builds compiled in ffmpeg, and not the 2.0.0 release to make sure you have fast 1-pass.

2. It will make StaxRip better / easier to recommend for users looking to get into AV1 encoding.

**Edit: I originally had a bunch of stuff in here written about an alternate version with tune-vmaf capability, but that was a bag of complicated, so I removed it and I just recommend the appveyor version since that should have fewer issues.**

**Comment by JJKylee** [comment]
Thanks for the info. I'll be giving it a try. 😃 

BTW, I think it'd be great if StaxRip could support _chunk encoding_ a la Av1an.

I tested @Neltulz 's aomenc settings in **StaxRip** (with @Patman86 's most recent aomenc build) on my system (i5-7300HQ) and it took really really long: 0.027x for a 1080p24 8 bit source. And the CPU usage was only around 42%.

On the other hand, **neav1e** did almost the same job three times faster with 25 seconds chunks, making full use of the CPU.

I know there was a little discrepancy b/w aomenc builds used by the two apps, but the gap was too noticeable in spite of that fact.

I wish I could run aomenc with chunk encoding in StaxRip just as I can with x265. 😄

**Comment by Neltulz** [comment]
> Thanks for the info. I'll be giving it a try. 😃

BTW, I think it'd be great if StaxRip could support chunk encoding a la Av1an.

I tested @Neltulz 's aomenc settings in StaxRip (with @Patman86 's most recent aomenc build) on my system (i5-7300HQ) and it took really really long: 0.027x for a 1080p24 8 bit source. And the CPU usage was only around 42%.

On the other hand, neav1e did almost the same job three times faster with 25 seconds chunks, making full use of the CPU.

I know there was a little discrepancy b/w aomenc builds used by the two apps, but the gap was too noticeable in spite of that fact.

I wish I could run aomenc with chunk encoding in StaxRip just as I can with x265. 😄

I don't think this is the right place for that kind of discussion.  This is a feature request for the inclusion of a prebuilt aomenc encoder.  If you wanna have this discussion, the best way to have this discussion would be to create your own feature request here on github regarding chunk encoding, and then offer up your reasons for it there.  Please do not hijack other issues for the purpose of starting discussion on unrelated things.

**Comment by JJKylee** [comment]
> Please do not hijack other issues for the purpose of starting discussion on unrelated things.

Oh, I didn't mean to. I was just chatting. If it makes you inconvenient, my apologies.
I was about to open an issue regarding that matter sooner or later.

**Comment by Neltulz** [comment]
> > Please do not hijack other issues for the purpose of starting discussion on unrelated things.
> 
> Oh, I didn't mean to. I was just chatting. If it makes you inconvenient, my apologies.
> I was about to open an issue regarding that matter sooner or later.

Cool.  I'd be happy to respond there too if you do it.

**Comment by stax76** [comment]
Where can the latest build be found?

**Comment by Dendraspis** [comment]
> Where can the latest build be found?

In ths first post @Neltulz writes:
> https://ci.appveyor.com/project/marcomsousa/build-aom/build/artifacts <-- I recommend this version

v2.0.0-1113 seems to be the newest version.  😁 

...or as an overview:
https://github.com/marcomsousa/build_aom
