### ISSUE TITLE
2.1.4.8: aomenc - wrong option names and weird context help call

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#365]
**Describe the bug & expected behavior**
1. There are three **Chroma Sample Pos** options in aomenc Options > Misc 1.
The last two should be renamed correctly as follows:

![StaxRip_2 1 4 8_aomenc_settings_bug_wrong_option_names_20201007](https://user-images.githubusercontent.com/3157518/95427173-fc70da80-08fb-11eb-9d14-dd1ba213ebb7.jpg)

2. Context help (right-click help) call in aomenc does not work at first. It works **only after** the user opens the local help file.

See this:

![StaxRip_2 1 4 8_aomenc_settings_bug_context-help_issue_20201007](https://user-images.githubusercontent.com/3157518/95427282-25916b00-08fc-11eb-92fe-de39b09d9713.gif)

The same phenomenon happens again after relaunch.

**Comment by Neltulz** [comment]
I have the same issues with StaxRip v2.1.3.0.  Good finds.  I guess I need to update my StaxRip, I'm falling behind!

**Comment by Dendraspis** [comment]
> 1. There are three **Chroma Sample Pos** options in aomenc Options > Misc 1.
>    The last two should be renamed correctly as follows:

Fixed through remake of all options.  ✔️ 

> 2. Context help (right-click help) call in aomenc does not work at first. It works **only after** the user opens the local help file.

Fixed! ✔️
