### ISSUE TITLE
Dealing with orphaned .ivf files in _temp folders

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#366]
**Is your feature request related to a problem? Please describe.**
Rav1e creates .ivf files inside the temp folder.  Staxrip produces an error if you try to encode a file with the same filename as the .ivf file that still resides inside of the _temp folder from a previous job.

**Describe the solution you'd like**
1. On successful encoding & muxing of .ivf file, delete the .ivf file since it is no longer needed.
2. On **unsuccessful** encoding or aborting of job, do **NOT** delete the .ivf file.
3. If the user attempts to encode a video with the same filename as the .ivf file, rename the existing .ivf file to ``filename_BAK.ivf`` to prevent overwriting and/or program error.
4. or just overwrite the .ivf file without error/prompting user...

**Describe alternatives you've considered**
Deleting the .ivf file prevents errors, but is annoying because you have to remember do it.

**Explain why the feature matters to you**
Improve program stability, prevent errors, etc.

**Additional context**
Tested on StaxRip version 2.1.3.0 and rav1e version 0.4.0-beta

**Comment by stax76** [comment]
Thanks for reporting, this was fixed recently.
