### ISSUE TITLE
Write Encoder Settings as a tag in the container or video stream

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#367]
**Is your feature request related to a problem? Please describe.**
I noticed AV1 for Aomenc and Rav1e (I am also assuming SVT-AV1) does not write the encoder settings as a tag in the container or video stream of the file.

For example, this information:
```Encoder: aomenc v2.0.0-898```

```Encoder Settings: --passes=2 --pass=1 --end-usage=q --bit-depth=10 --cpu-used=4 --cq-level=20 --tile-columns=2 --tile-rows=1 --kf-max-dist=240 --lag-in-frames=30 --i420 --threads=8 --row-mt=1 "--frame-boost=1" --tune-content=screen --auto-alt-ref=1 --arnr-maxframes=15 --arnr-strength=2```

**Describe the solution you'd like**
It would be nice if it could be added to the mkv container as a tag, or added directly to the video stream so that it can be viewed whenever a user tries to view the MediaInfo of the mkv file.

**Describe alternatives you've considered**
I can manually copy paste the encoder settings into the container settings > tags

**Explain why the feature matters to you**
I am a forgetful person, and if the program can take care of this for me automatically, that would be great. :)

**Additional context**
N/A

**Comment by stax76** [comment]
It's available in the next build.

![image](https://user-images.githubusercontent.com/11410540/102724739-1f633600-4312-11eb-8c0a-1c871440f63d.png)

**Comment by stax76** [comment]
Also in the next build a new `AddTags` command that can be used with the _Event Commands_ feature (Tools > Advanced > Event Commands).

![image](https://user-images.githubusercontent.com/11410540/102773722-00a08600-438a-11eb-9b12-6f7dc7800820.png)

**Comment by stax76** [comment]
Closing since the new build is online.
