### ISSUE TITLE
2.1.4.8: Tone Mapping menu in default AVS Profiles

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#369]
**Describe the bug**

The AVS filter menu _Tone Mapping_ is meaningful only when **DGTonemap** filter is installed.
Since DGTonemap is removed and does not ship with StaxRip any more, the menu should be removed as well.

**How to reproduce the issue**

1. After a source file is opened, go to _Tone Mapping_ menu in _AVS Filters_ as follows:

![StaxRip_2 1 4 8_missing_filter_menu_in_AVS_1_20201008](https://user-images.githubusercontent.com/3157518/95540232-2df1b080-09a5-11eb-93ab-3f493a88c67c.jpg)

2. You will see this _Script Error_ message in the main window as follows:

![StaxRip_2 1 4 8_missing_filter_menu_in_AVS_2_20201008](https://user-images.githubusercontent.com/3157518/95540370-7d37e100-09a5-11eb-8975-a936686d956f.jpg)

> Script error: There is no function named 'DGHable'/'DGReinhard'.

3. You cannot proceed any more at this stage.

**Provide information**

The following code in AVS Profiles should be removed.

```
HDRCore | Tone Mapping = $select:msg:Select the Map Tone You Wish to Use;DGReinhard|DGReinhard();DGHable|DGHable()$
```

**Additional context**

Users can install and register DGTonemap filter by themselves referring to this [Wiki document](https://github.com/staxrip/staxrip/wiki/How-to-register-DGTonemap-&-DGHDRtoSDR-filters-in-StaxRip).

**Comment by 44vince44** [comment]
I agree @JJKylee , and and at the same time I regret that "claims" of Donald Graft have lead to remove DGToneMap and DGHDRtoSDR.
Especially DGHDRtoSDR which is a very easy to use and efficient and hardware accelerated HDR to SDR filter.

**Comment by 44vince44** [comment]
@stax76 @Dendraspis, this is very easy to fix:

in Filter Profiles (AVS), **remove line**
`HDRCore | Tone Mapping = $select:msg:Select the Map Tone You Wish to Use;DGReinhard|DGReinhard();DGHable|DGHable()$`

Because this is a call to a plugin that has been removed and that will not be back, because it's closed source, and not free to distribute (thanks JJKylee for pointing this out)
