### ISSUE TITLE
NVEnc Error (2.0.3.0) Unknown option: "cuda"

### ISSUE THREAD

**Issue by coxinator138** [staxrip/staxrip#37]
I'm having trouble encoding at all with NVenc x264 with NVenc Cuda selected.

1. Add any file to encode
2. Use settings NVenc x264 with NVenc Cuda decoding selected
3. Try to encode the file

Here's the error I'm getting

Error Video encoding using NVEnc 4.44 (2.0.3.0)

Video encoding using NVEnc 4.44 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 4.44 -------------------

C:\Users\jdcox215\Downloads\Compressed\StaxRip-x64-2.0.3.0-stable\Apps\Encoders\NVEnc\NVEncC64.exe --avhw cuda --vbr 8000 --preset quality --level 4.1 --bframes 8 --ref 4 --cabac -i "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!.mkv" -o "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_temp\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_new_out.h264"

Error: Unknown option: "cuda"

StaxRip.ErrorAbortException: Video encoding using NVEnc 4.44 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 4.44 -------------------

C:\Users\jdcox215\Downloads\Compressed\StaxRip-x64-2.0.3.0-stable\Apps\Encoders\NVEnc\NVEncC64.exe --avhw cuda --vbr 8000 --preset quality --level 4.1 --bframes 8 --ref 4 --cabac -i "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!.mkv" -o "F:\Blu Ray\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_temp\Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_new_out.h264"

Error: Unknown option: "cuda"

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 339
   at StaxRip.NVEnc.Encode() in D:\Projekte\VB\staxrip\Encoding\NVEnc.vb:line 82
   at StaxRip.GlobalClass.ProcessVideo() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 227
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 137

  Desktop:
 - OS: Windows 10 Pro Insider Preview Build 18963
- NVEnc 4.44
- Logs attached in files

I had been using the exact same settings as I am for this encode for a lot of the other encodes I did today and it worked..... I updated to Staxrip 2.0.3.0 and it stopped working.... so then I continued using 2.0.2.4 and it still wouldn't work...
[Dragon Ball Z Kai - S01E01 - Prologue to Battle! The Return of Goku!_new_staxrip.log](https://github.com/staxrip/staxrip/files/3523058/Dragon.Ball.Z.Kai.-.S01E01.-.Prologue.to.Battle.The.Return.of.Goku._new_staxrip.log)

**Comment by stax76** [comment]
Please report it here:

https://github.com/rigaya/NVEnc/issues

**Comment by Patman86** [comment]
Code customization for NVEnc is needed because the cuda option has been removed since version 4.44. The new option is only --avhw or totally remove cuda option.

[https://github.com/rigaya/NVEnc/issues/139#issuecomment-523931111](url)

**Comment by stax76** [comment]
@Patman86 

I've merged the pull request and made few more minor changes. Unfortunately I don't have compatible hardware at this time, so I cannot test anything.

https://github.com/staxrip/staxrip/commit/8e95552477ca1818fe2eabb64c87696bd20da6ea

**Comment by Patman86** [comment]
I saw your minor changes. 
I've tested the command and it worked well.
Issue can be closed.

**Comment by stax76** [comment]
I'll close it when there is a new build. Thanks for the help.
