### ISSUE TITLE
I have received this error 19 times in a row

### ISSUE THREAD

**Issue by YOURMOMMYFACE** [staxrip/staxrip#370]
ArgumentOutOfRangeException (2.1.3.0)

Value to add was out of range.
Parameter name: value

System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at StaxRip.ServerInfo.GetInfoText(Int32 position) in D:\Projekte\VB\staxrip\General\FrameServer.vb:line 71
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 250
   at StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 192

**Comment by YOURMOMMYFACE** [comment]
And not tell me to use some other version please.

Just tell me what is wrong

**Comment by JJKylee** [comment]
You keep ignoring template guideline in reporting an issue.
And the title is not appropriate either.
There's no way others can understand what's going on.

**Comment by YOURMOMMYFACE** [comment]
I don't see no template.

Win 10 and yes and yes.

4 different versions of stax and all 4 version gives me a unique error each, encode quits half way through or will not even start or it will start and finish but be a busted file.

**Comment by JJKylee** [comment]
> I don't see no template.

![StaxRip_Github_repo_issue_template](https://user-images.githubusercontent.com/3157518/95671295-14d63480-0b4a-11eb-970a-c0ea3381d731.gif)

By template, I mean the auto filled body content when you start writing an issue.
You need to modify it appropriately.
You don't see this at all?

**Comment by YOURMOMMYFACE** [comment]
![image](https://user-images.githubusercontent.com/72358404/95681288-ea699300-0bac-11eb-8279-c34fbdc53cbd.png)

**Comment by YOURMOMMYFACE** [comment]
this template will not even help

4 different versions all recieving different errors
I do batch and it will not run batch
It will quit half way through
or
it will finished and totally be ruined, i.e. a solid grey frame with the remaing frames appearing in that frame as blue or red. Encoded over 10,000 items. I have never seen this before.

**Comment by JJKylee** [comment]
You're just saying "My StaxRip stops working halfway." **without providing any information on your side**. (An error message is not enough.)

If a job/project starts in StaxRip, at least there should be a log. You should provide the log file, and **describe** what steps you were taking when the error occurred.
If StaxRip doesn't launch, there's something wrong with your system.

> stax is literally the only option, literally, no other option so I am forced to use it.

No, that's not true. There are other apps that can handle AviSynth/VapourSynth in a similar way as StaxRip. Hybrid is an example. Although it's really heavy for some users like me, you can give it a try if you cannot find the reason of errors with StaxRip.

**Comment by jlw4049** [comment]
You have to have more information for someone to go on then this. You'll never receive help otherwise.

**Comment by YOURMOMMYFACE** [comment]
------------------------------ Exception ------------------------------

System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at StaxRip.ServerInfo.GetInfoText(Int32 position) in D:\Projekte\VB\staxrip\General\FrameServer.vb:line 71
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 250
   at StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 192

**Comment by YOURMOMMYFACE** [comment]
I am utterly not allowed to open stax and simply have it encode something like every one else can. Why?

**Comment by YOURMOMMYFACE** [comment]
> You have to have more information for someone to go on then this. You'll never receive help otherwise.

What info. What more info do you need other than every one can open stax, every one can apply settings, everyone can press start and every one can encode something. I can not open stax, I can not apply settings, get it to run or even encode anything.

What are you people possibly doing that so different from what I am doing?

**Comment by YOURMOMMYFACE** [comment]
> This is about a bug (on your side), so you're supposed to **report a bug**, not just ask a question.
> 
> And you're just complaining by saying "My StaxRip stops working halfway." **without providing any information on your side**. (An error message is not enough.)
> 
> If a job/project starts in StaxRip, at least there should be a log. You should provide the log file, and **describe** what steps you were taking when the error occurred.
> If StaxRip doesn't launch, there's something wrong with your system.
> And at least you should avoid UAC folders for installing StaxRip such as `C:\Program Files\` or `C:\Users\<User Name>\Documents`, etc.
> 
> > stax is literally the only option, literally, no other option so I am forced to use it.
> 
> No, that's not true. There are other apps that can handle AviSynth/VapourSynth in a similar way as StaxRip. Hybrid is an example. Although it's really heavy for some users like me, you can give it a try if you cannot find the reason for errors with StaxRip.

For one no one person said anything about a bug. I am asking a question

what is this?

------------------------------ Exception ------------------------------

System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at StaxRip.ServerInfo.GetInfoText(Int32 position) in D:\Projekte\VB\staxrip\General\FrameServer.vb:line 71
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 250
   at StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 192

Complaining? I have said this so many times. I CAN NOT OPEN STAX AND USE IT LIKE EVERYONE ELSE!!!

there are so many issues and I truly can not get any help or I can not for the life of me get stax to even work right?


Maybe I need a step by step guide, maybe a stax for dummies so to speak.

Becasue apprently you can not open stax, add settings, add a file and press start. There is some other trick invovlved. Like templates. For the longest stax would take my settings and totally ignore them and use its own crappy default settings. I don't want to use templates but you have to for some reason or it will not work. So there one trick I found out. Now I trying to figure out the rest of the tricks.

Every other encoder out there, add settings, add a file press start. But I am trying to figure out why this process does not apply with the encoder stax. That is my true question.

**Comment by YOURMOMMYFACE** [comment]
And again

ArgumentOutOfRangeException (2.1.3.0)

Value to add was out of range.
Parameter name: value

System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at StaxRip.ServerInfo.GetInfoText(Int32 position) in D:\Projekte\VB\staxrip\General\FrameServer.vb:line 71
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 250
   at StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 192

**Comment by YOURMOMMYFACE** [comment]
33 times now. I open stax, it encodes one or two files and then I get this, each and every time.

**Comment by jlw4049** [comment]
> 33 times now. I open stax, it encodes one or two files and then I get this, each and every time.

You have to be doing something wrong. I encode 1000s of files with it.

**Comment by YOURMOMMYFACE** [comment]
now I get a stuck one grey frame and all the remainder frames play over that stuck frame in red and blue colors while the file size being 16x larger than the rest of the files

**Comment by YOURMOMMYFACE** [comment]
> > 33 times now. I open stax, it encodes one or two files and then I get this, each and every time.
> 
> You have to be doing something wrong. I encode 1000s of files with it.

And what could I be doing wrong is what I have been trying to figure out. You and every one else on the planet claim to use stax millions of times. I have only needed to use it a total 5x a year and I can not complete that 5x or so without a true battle. I have to physically fight with stax, literally. Before I found out you are forced to use a template I was not using templates. And it would randomly and periodically disregard my settings and use its own crappy settings one pass at 7,000kbps. Things gotten better with templates but I have recieved a total of 7 different error messages amongst other things, like batch. It does one, then finishes, won't touch any of the other files. This new error being the more frequently appearing one. But unfortunately no one cares at all. And now I am getting new errors. Look at post above.

**Comment by jlw4049** [comment]
> > > 33 times now. I open stax, it encodes one or two files and then I get this, each and every time.
> > 
> > 
> > You have to be doing something wrong. I encode 1000s of files with it.
> 
> And what could I be doing wrong is what I have been trying to figure out. You and every one else on the planet claim to use stax millions of times. I have only needed to use it a total 5x a year and I can not complete that 5x or so without a true battle. I have to physically fight with stax, literally. Before I found out you are forced to use a template I was not using templates. And it would randomly and periodically disregard my settings and use its own crappy settings one pass at 7,000kbps. Things gotten better with templates but I have recieved a total of 7 different error messages amongst other things, like batch. It does one, then finishes, won't touch any of the other files. This new error being the more frequently appearing one. But unfortunately no one cares at all. And now I am getting new errors. Look at post above.

I've read all of your messages, this is free software, this is def a user error because I've used the program on now 6 different machines for a long time. 

Have you tried reading the docs?

**Comment by Dendraspis** [comment]
Sorry, but we can't help if there is nothing we can look into. As far as I can see you don't even tell us what you are trying to do or when the error message appears. A log file would be the least.
From what I can see I would say there could be a problem with the framerate or its recognition.

Feel free to  re-open this issue or even better start a new **bug template issue**.
