### ISSUE TITLE
Mp4box

### ISSUE THREAD

**Issue by Rozin14** [staxrip/staxrip#371]
Mp4Box not responding and using cpu resources dangerously when demuxing a file with 7 channel audio
It also has long path error even if the file name is small.
2.1.3.0 is not stable.☹️

**Comment by JJKylee** [comment]
Please keep template guideline when you report an issue.
Otherwise, there's no way others can understand what's going on.

**Comment by vonH** [comment]
> Mp4Box not responding and using cpu resources dangerously when demuxing a file with 7 channel audio
> It also has long path error even if the file name is small.
> 2.1.3.0 is not stable.☹️

Can you post the log?
