### ISSUE TITLE
please add a way to automatically remux mkv vfr timestamps if extracted

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#373]
I have a large number of VFR MKV files I need to adjust and transcode
I have the option selected to extract the MKV timestamps, but once extracted there is no way to automatically remux these back into the output. if I don't remux them back in then I end up with a CFR file, audio out of sync, video wrong duration, etc

I can manually go to container options and browse to select the timestamps file, and this works to produce a VFR file, but I can't use this for batch processing and I have 100+ files to process. I cannot use a macro here - if I type "%temp_dir%%source_name%_timestamps.txt" here then the resulting mkvmerge command contains that exact text and not the filename (also this same thing is true for adding a custom chapters file as well, you cannot use a macro here). so I cannot target the timestamps file automatically, I have to browse and select it manually, so I cannot use batch processing - enabling macros to be used here would be very helpful

I can add the --timestamps switch manually using a macro in the command line tab (this is how I am also adding a custom chapters file with batch processing), but this adds the switch to the end of the mkvmerge command line, and for timestamps to work it needs to come before the video input. at least, I think that's what the problem is. it doesn't produce an error, but it doesn't produce the correct output (I still end up with a cfr file and problems). I'm adding --timestamps 0:"%temp_dir%%source_name%_timestamps.txt" and it produces the same command as if I select the timestamps file manually, only with the switch at the end of the command line, and it doesn't work

if we could use macros in the options tab to add a timestamps file or a chapters file then that would help

but really I think there should simply be a checkbox option alongside the "extract VFR MKV timestamps" to "remux VFR MKV timestamps" back into the output

meanwhile I have hundreds of files to process and either I do these one-by-one or I can't do them...

**Comment by Statick** [comment]
also - just remembered - when manually adding a timestamps file you have the option to use .txt or .mkv (presumably selecting .mkv should extract the timestamps from the mkv). selecting .mkv does not work, it just passes the mkv file to mkvmerge as if it were a timestamps file and results in an error (not a valid timestamps file)

**Comment by Dendraspis** [comment]
> I cannot use a macro here - if I type "%temp_dir%%source_name%_timestamps.txt" here then the resulting mkvmerge command contains that exact text and not the filename (also this same thing is true for adding a custom chapters file as well, you cannot use a macro here). so I cannot target the timestamps file automatically, I have to browse and select it manually, so I cannot use batch processing - enabling macros to be used here would be very helpful

How does your command exactly look like?

**Comment by stax76** [comment]
Has anybody VFR sample file?

**Comment by 44vince44** [comment]
@Statick please provide us with a sample file, we would appreciate it very much and we should be able to work on this, or else we'll close this thread.

**Comment by Statick** [comment]
thanks, this was a while ago and I don't think I have the files anymore. I ended up converting to CFR
