### ISSUE TITLE
"there is no function named MPEG2Source" on 2.1.4.8, works fine on 2.1.3.0

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#374]
**Describe the bug**
Unable to use MPEG2Source on 2.1.4.8 beta, was working fine on stable 2.1.3.0 release. Produces script error "there is no function named MPEG2Source" which prevents me from adding the job to the queue

**Expected behavior**
I expect the MPEG2Source filter to load and work as normal, which it does on stable release. I have rolled back to stable release and it's working again.

**How to reproduce the issue**
Use the MPEG2Source filter and open a d2v file

**Provide information**
I cannot produce a log while there is a script warning about the missing filter

**Comment by JJKylee** [comment]
_MPEG2Source_ is renamed to [_D2VSource_](https://github.com/Asd-g/MPEG2DecPlus), and starting 2.1.4.7 new AVS Profiles and the AviSynth Source Filter setup for d2v are applied.
If you just overwrote the files, check those out and update your AVS Profiles and AviSynth Source Filters in Settings.

**Comment by Statick** [comment]
ahh thank you - I had continued my same templates saved from earlier versions

**Comment by Statick** [comment]
coming back to this - it would seem that MPEG2Source isn't just "renamed" to D2Vsource, as parameters have changed as well

my existing source filter looks like this
MPEG2Source("%source_file%", CPU2="ooooxx")

the dering filter activated by CPU2 is useful for DVD rips which are often poorly encoded (I prefer to use other deblock filters so I only activate the dering filter here). is there an equivalent in D2Vsource? as CPU2 is not a recognised parameter for D2Vsource

**Comment by stax76** [comment]
We could re-add the old plugin so that both old and new are included, the advantage would be backward compatibility. How large is the file size of the old plugin?

And we could ask on the issue tracker why the option was removed.

**Comment by stax76** [comment]
I don't want to put it back because it's 300 KB.

It can be manually integrated by the user.
