### ISSUE TITLE
MAJOR regression regarding audio processing since shortening temp file name: output rewrites original demuxed stream

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#380]
Hi @stax76 @Dendraspis , and hi everyone! 

**Describe the bug**
When output audio is processed in same codec than original audio, then the original audio demuxed stream is overwritten with the output. This is due to the naming of audio elements that does not include something that distinguishes output from input.
Consequence: when reprocessing audio a second time (for instance, if you need to redo the processing due to something not satisfactory), the resulting audio will be impacted twice.

Example: use the sample provided below.
1. open sample.mkv in staxrip,
   => this generates the temp files required for processing, among them
        ID1 English.m4a
  edit: make sure you use FFVideoSource, and not DSS2 !

2. Set the processing to:
    Container = MKV 
    Video = copy/mux
    AUDIO = qaac encode, normalize=no, gain = +6dB

3. process, keep the temp files (do not delete)
   ID1 English.flac is created from ID1 English.m4a, with +6dB.
   ID1 English.flac is reencoded to ID1 English.m4a SAME NAME AS ORIGINAL !
  => the output audio is +6db louder than original, OK this is what is expected.

4. reopen the sample.srip file, and process again.
  => the ouput audio is **+12db** louder than original, NOT WHAT EXPECTED.

In the the second process, the output must still be +6dB louder and not +12dB.
This error happens because the process is using output audio stream name = input stream name.
 
[Sample.zip](https://github.com/staxrip/staxrip/files/5456297/Sample.zip)

Kind Regards for all !!

Note (Edit): this can be fixed, along with another issue relating to audio mess up when doing multiple staxrip simultaneous processing on the same input file https://github.com/staxrip/staxrip/issues/297 , by including in the processed file name the target name or something like a crc of the target name. example: 
ID1 English.m4a -> this is the extracted original stream, keep name as is.
ID1 English.flac -> this is the first step in processing, should be named ID1 English<CRC_of_target>.flac 
                                 (this method keeps file name short)
ID1 English.m4a (converted from the flac above) -> should be named ID1 English<CRC_of_target>.m4a

**Comment by 44vince44** [comment]
Adding that this test was made with source = FFVideoSource.
Some other sources like DSS2 work fine, in the case of DDS2 the audio is demuxed from scratch!

**Comment by stax76** [comment]
Very good bug report, thank you.

Next build checks if the output file exists, if yes then _new is added to the output filename.

**Comment by 44vince44** [comment]
@stax76 in this case why not just add _new or _out **without checking.**
So, for instance, the output will be current_name_out.ext

Simpler, and doesn't lead to the possibility of having something like name_new_new if process has been repeated 4 times

**Comment by stax76** [comment]
The new beta is online.

Adding _new only if strictly necessary seems simpler, I think most tools do it this way.

Let's also not forget the annoying 260 character limitation.

**Comment by 44vince44** [comment]
I'll download it now then test this evening because I'll have a busy day!

@stax76 the reason I ask you that is because I am thinking of the way to fix the issue with internal confusion between audio output when having several jobs on the same video running simultaneously. Video stream doesn't get confused because video output is called "[destination_file_name]_out.hevc"
I know for audio it's different because there are already items (ID number, delay etc) in the name, so it cannot be named like the video, using the destination name. I was thinking, if you can easily add "_new", then you could perhaps easily add "_[CRC32 of destination name]", and since the CRC32 is only 8 character, no problem with the 260 limit. So you see where I'm trying to get ?

**Comment by stax76** [comment]
Yes I remember it, a proper fix for this could maybe look like so:

Try to open the file in readwrite mode, if a process is currently writing to this file then this requests will fail, in that case staxrip could wait until the file is unlocked. Sounds good?

**Comment by 44vince44** [comment]
It won't work because the audio is processed at the beginning and then the muxing happens after video is finished processing.
Here is an example, encoding simultaneously two ranges of a source video, into two different outputs:

I am working on video_source.mp4
I create first job:            Job1 = encode audio and video from Range 1   to destination file video1.mkv
I create second job:       Job2 = encode audio and video from Range 2   to destination file video2.mkv

I run the batch in two instances of staxrip, so Job1 and Job2 are being encoded same time.
Here is what happens :
Job1 creates intermediate cut files (for audio of Range1), and then encodes Range1 to ID1_cut.m4a
Job1 begins encoding video on Range1 (long process pending) [Stax76, continue to next step (we're multitasking)]
Job2 creates intermediate cut files (for audio of Range2), if any file locked wait, then encode Range2 to **same** ID1_cut.m4a
Job2 begins encoding video on Range 2

Result: when all encoding finished, you get:
video1_out.hevc
video2_out.hevc
ID1_cut.m4a

The resulting file from from Job1 is a file with video stream video1_out.hevc and audio stream ID1_cut.m4a, which has been OVERWRITTEN with **audio from RANGE2 !!!!!!**.

The only way to avoid that is to put in the audio intermediate and final names a unique identifier. Putting the name of the destination file is maybe a long file name, but putting an intelligent sum like CRC32 of the destination name can work.

**Comment by stax76** [comment]
OK, didn't think about that. What about this:

When job processing is started, check if there is already another instance processing, if so then check if the target file already exists, if so then append CRC32 of the destination mkv filename.

**Comment by 44vince44** [comment]
Seems good, but why not doing it without checking?  CRC32 is only 8 chars....

**Comment by Dendraspis** [comment]
Sorry for throwing that in without being 100% into it, but wouldn't it be better to just add something like ***_#*** where *#* is a continuous number?

CRC32 is okay, but for identifying not that easy as long the source doesn't contain it, too.

**Comment by stax76** [comment]
@Dendraspis 

Right now in most places files get overwritten or reused or there is a question offering overwrite or reuse. It's simple, short and consistent.

When there are two instances and the file already exists then we need something else.

CRC32 has 8 characters and is slightly cryptic, I have CRC32 code, 38 lines.

A counter would create a new file every time but I don't think it matters because we do it only when there are two instances and the file already exists, it's unlikely it would result in many files.

I think both ways are fine but like the counter method slightly more, not cryptic, no need adding the CRC32 code and less chance hitting the 260-character limit.

**Comment by Dendraspis** [comment]
@stax76 
Okay, so that's a point for the Checksum/Hash.

The only other possibility I see at the moment is to add (all needed) identifiers (maybe criptic) to the filename to be sure duplicates can be prohibited.

**Comment by 44vince44** [comment]
@stax76, @Dendraspis 
There is a current naming pattern which is ok when targeting a single destination for the same source file.

Using what you've both said, there would be two options:

option 1: new_naming_pattern = current_naming_pattern + COUNTER
option 2: new_naming_pattern = current_naming_pattern + CRC32 of destination file name

options 1 and 2 will respect the file name length limit.  COUNTER is 1 or 2 characters,  CRC32 is 8 characters.
option 1 has a problem: increasing number of files uselessly if operation aborted/repeated
option 2 does not have that problem, CRC32 is the same as long as destination file name is the same.
But option 2 requires 32 lines of CRC32 code.

Your decision ?

**Comment by Dendraspis** [comment]
I had a nice idea:  Create a short random sequence for every job and use it as prefix for every temporary filename. So there is no lost time through checksum calculations and it's secure. On the other hand there might be duplicates temporary wasting disk space.

For my selected prefix pattern ('HHmmssff_') the result for @44vince44 's example would be:

- 00590143_video1_out.hevc
- 00590143_ID1_cut.m4a
- 00591612_video2_out.hevc
- 00591612_ID1_cut.m4a

It's all about finding a compromise. Either you waste time and energy or temporary disk space.  🤔

**Comment by Dendraspis** [comment]
> options 1 and 2 will respect the file name length limit. COUNTER is 1 or 2 characters, CRC32 is 8 characters.
> option 1 has a problem: increasing number of files uselessly if operation aborted/repeated
> option 2 does not have that problem, CRC32 is the same as long as destination file name is the same. It is unique.
> But option 2 requires 32 lines of CRC32 code.

One of the biggest problems with option 2 is, that you have to create that file in order to find out, if it was necessary or if you've wasted your time, because it's already there. The only big benefit is, that you can delete the duplicate immediately after comparing (when they are equal).

The only way to prevent wasting time and disk space would be adding all parameters (like range, bitrate, codec, ..) to the filename or use meta files with all necessary informations so StaxRip could see if it has to create a new file or not. 🤔

**Comment by stax76** [comment]
@Dendraspis 

Working on it right now, there seem to be some complexity, so I hope to get everything right.

**Comment by Dendraspis** [comment]
@stax76 
If not, @44vince44 will find the bug(s).  😂 
Good succeed!

**Comment by 44vince44** [comment]
@stax76 @Dendraspis Count on me both of you! I'll do the most thorough checking ;-))))))

**Comment by stax76** [comment]
Let's see if you can find something. 😀

New beta is online.

**Comment by 44vince44** [comment]
OK i know what I'm gonna be doing this afternoon ;-)

**Comment by 44vince44** [comment]
So far, so good! impressive CRC generation ;-) 
all seems flawless. I must push the tests further ...

**Comment by stax76** [comment]
Great, I had to rewrite it like 10 times, you have seen it coming a long time before. 👍

**Comment by 44vince44** [comment]
Thanks 10x10 times I'll close this issue because this is fixed, and we're way beyond "fixed", it's like a new feature!
