### ISSUE TITLE
KNLMeansCL/QTGMC for Xeon users (error 126)

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#383]
**Describe the niche issue**
The included KNLMeansCL is not supported on Xeon platforms without GPUs, despite an OpenCL runtime for CPU existing.

**Expected behaviour**
I expected Staxrip to have noted this in documentation, or for the runtime to be included (I know this is a very niche scenario).

**How to reproduce the issue**
Try using QTGMC on a Xeon without a dGPU, or any CPU without an iGPU (tested on old consumer AMD CPU without iGPU and GPU and found the same issue).

**Provide information**
This is more of a record for those who have the same issue, and a fix for it. If you find Staxrip produces a '126' error when trying to use 'QTGMC with Repair', and have a Xeon, you need to download the **Intel® CPU Runtime for OpenCL™ Applications for Windows OS**

1. Older versions of KNLMeansCL designed for CPU-only will not work.
2. You will need to create an account on Intel's website.

Windows 64bit: 
```
https://registrationcenter.intel.com/en/forms/?productid=3207
```
Linux 64bit (for emulation): 
```
https://registrationcenter.intel.com/en/forms/?productid=3206
```
You may need to use an older binary as well. The specific version can be found here: 
```
https://github.com/Khanattila/KNLMeansCL/releases/tag/v0.6.11
```
Replace the x64 .dll from
```
\Staxrip\Apps\Plugins\Dual\KNLMeansCL
```
with the one from the zip.

You may also need a new runtime:
```
https://aka.ms/vs/16/release/vc_redist.x64.exe
```

I have tested and confirmed this resolves the issue with Staxrip and, I imagine, similar software that using QTGMC.

**Notes**
Please feel free to mark this as Resolved and close. I would post and close, but interested if any of the team have anything to add.

**Comment by 44vince44** [comment]
@vonH may I suggest you copy this information (as you are the author of the first post) to the Wiki section and close this thread, please ?

**Comment by 44vince44** [comment]
@vonH I think you misunderstood me, I was asking you to copy this to the wiki, so we can close this non-bug thread.
Well I'll do it myself.
@Dendraspis or Vonh can you close this thread.
I have put on the wiki information with the corrected links as they should be in a new wiki page.
