### ISSUE TITLE
Unknown Error Occurred with ffmpeg

### ISSUE THREAD

**Issue by nbetcher** [staxrip/staxrip#384]
**Describe the bug**
Attempting to use FFMpeg to encode any file results in 'Unknown Error Occurred' (from ffmpeg). I've tried changing, removing, adding items into the .avs file that is being loaded, but nothing changes.

Testing the command manually from the command line with "-v trace" reveals nothing useful.

I've checked that my CPU supports AVX2 using CPU-Z and it reports that AVX2 is present.

I'm guessing this is a 32-bit vs 64-bit issue, but everything that is being used is from the StaxRip 64-bit 2.1.3.0 package.

NOTE: I need ffmpeg in order to properly convert VFR to CFR. The origin file (VOB from the DVD) is VFR. Other utilities do not sync the audio properly.

**Expected behavior**
File begins being encoded.

**How to reproduce the issue**
Load an MKV file, change encoder to, 'ffmpeg - x264' and click, 'Start' -- error is produced.

**Provide information**
------------------------- System Environment -------------------------

StaxRip    : 2.1.3.0
Windows    : Windows 10 Pro 2009
Language   : English (United States)
CPU        : Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
GPU        : NVIDIA GeForce RTX 2060 SUPER
Resolution : 2560 x 1440
DPI        : 96

----------------------- Media Info Source File -----------------------

D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv

General
Complete name            : D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv
Format                   : Matroska
Format version           : Version 4
File size                : 1.85 GiB
Duration                 : 45 min 28 s
Overall bit rate mode    : Variable
Overall bit rate         : 5 815 kb/s
Movie name               : Star Trek Deep Space 9 Season 1 Episode 3
Encoded date             : UTC 2020-11-06 18:36:52
Writing application      : mkvmerge v51.0.0 ('I Wish') 64-bit
Writing library          : libebml v1.4.0 + libmatroska v1.6.2

Video
ID                       : 1
Format                   : MPEG Video
Format version           : Version 2
Format profile           : Main@Main
Format settings          : CustomMatrix / BVOP
Format, BVOP             : Yes
Format, Matrix           : Custom
Format, GOP              : Variable
Codec ID                 : V_MPEG2
Codec ID/Info            : MPEG 1 or 2 Video
Duration                 : 45 min 27 s
Bit rate mode            : Variable
Bit rate                 : 5 165 kb/s
Maximum bit rate         : 9 800 kb/s
Width                    : 720 pixels
Height                   : 480 pixels
Display aspect ratio     : 4:3
Frame rate mode          : Variable
Frame rate               : 24.029 FPS
Original frame rate      : 29.970 (30000/1001) FPS
Standard                 : Component
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Compression mode         : Lossy
Bits/(Pixel*Frame)       : 0.622
Time code of first frame : 00:59:58;00
Time code source         : Group of pictures header
Stream size              : 1.64 GiB (89%)
Language                 : English
Default                  : Yes
Forced                   : No
Color primaries          : BT.601 NTSC
Transfer characteristics : BT.601
Matrix coefficients      : BT.601

Audio #1
ID                       : 2
Format                   : AC-3
Format/Info              : Audio Coding 3
Commercial name          : Dolby Digital
Codec ID                 : A_AC3
Duration                 : 45 min 28 s
Bit rate mode            : Constant
Bit rate                 : 448 kb/s
Channel(s)               : 6 channels
Channel layout           : L R C LFE Ls Rs
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 146 MiB (8%)
Language                 : English
Service kind             : Complete Main
Default                  : Yes
Forced                   : No

Audio #2
ID                       : 3
Format                   : AC-3
Format/Info              : Audio Coding 3
Commercial name          : Dolby Digital
Codec ID                 : A_AC3
Duration                 : 45 min 28 s
Bit rate mode            : Constant
Bit rate                 : 192 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 62.4 MiB (3%)
Language                 : English
Service kind             : Complete Main
Default                  : No
Forced                   : No

Text
ID                       : 4
Format                   : VobSub
Codec ID                 : S_VOBSUB
Codec ID/Info            : Picture based subtitle format used on DVDs
Duration                 : 43 min 57 s
Bit rate                 : 5 099 b/s
Count of elements        : 822
Stream size              : 1.60 MiB (0%)
Language                 : English
Default                  : No
Forced                   : No

Menu
00                       : 00:00.000                             : en:Chapter 1
00                       : 06:25.933                             : en:Chapter 2
00                       : 12:13.200                             : en:Chapter 3
00                       : 17:24.033                             : en:Chapter 4
00                       : 21:56.400                             : en:Chapter 5
00                       : 27:27.466                             : en:Chapter 6
00                       : 35:35.866                             : en:Chapter 7
00                       : 41:15.966                             : en:Chapter 8

------------------------------ Demux MKV ------------------------------

mkvextract 47

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv" tracks 3:"D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID4 English.idx" 1:"D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID1 English.ac3" 2:"D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID2 English.ac3" --ui-language en

Extracting track 1 with the CodecID 'A_AC3' to the file 'D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID1 English.ac3'. Container format: Dolby Digital (AC-3)
Extracting track 2 with the CodecID 'A_AC3' to the file 'D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID2 English.ac3'. Container format: Dolby Digital (AC-3)
Extracting track 3 with the CodecID 'S_VOBSUB' to the file 'D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID4 English.sub'. Container format: VobSubs
Writing the VobSub index file 'D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID4 English.idx'.

Start:    6:07:00 PM
End:      6:07:02 PM
Duration: 00:00:02

General
Complete name         : D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID1 English.ac3
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
File size             : 146 MiB
Duration              : 45 min 28 s
Overall bit rate mode : Constant
Overall bit rate      : 448 kb/s

Audio
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
Duration              : 45 min 28 s
Bit rate mode         : Constant
Bit rate              : 448 kb/s
Channel(s)            : 6 channels
Channel layout        : L R C LFE Ls Rs
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 SPF)
Compression mode      : Lossy
Stream size           : 146 MiB (100%)
Service kind          : Complete Main
General
Complete name         : D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID2 English.ac3
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
File size             : 62.4 MiB
Duration              : 45 min 28 s
Overall bit rate mode : Constant
Overall bit rate      : 192 kb/s

Audio
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
Duration              : 45 min 28 s
Bit rate mode         : Constant
Bit rate              : 192 kb/s
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 SPF)
Compression mode      : Lossy
Stream size           : 62.4 MiB (100%)
Service kind          : Complete Main

------------------------- Demux xml chapters -------------------------

mkvextract 47

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv" chapters "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_chapters.xml"

File 'D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv': container: Matroska
Track ID 0: video (MPEG-1/2)
Track ID 1: audio (AC-3)
Track ID 2: audio (AC-3)
Track ID 3: subtitles (VobSub)
Chapters: 8 entries

Start:    6:07:02 PM
End:      6:07:02 PM
Duration: 00:00:00

------------------------- Demux ogg chapters -------------------------

mkvextract 47

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv" chapters "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_chapters.txt" --simple

File 'D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv': container: Matroska
Track ID 0: video (MPEG-1/2)
Track ID 1: audio (AC-3)
Track ID 2: audio (AC-3)
Track ID 3: subtitles (VobSub)
Chapters: 8 entries

Start:    6:07:02 PM
End:      6:07:02 PM
Duration: 00:00:00

-------------------------- Demux timestamps --------------------------

mkvextract 47

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" timestamps_v2 "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv" 0:"D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_timestamps.txt"

Start:    6:07:02 PM
End:      6:07:03 PM
Duration: 00:00:01

---------------- Extract forced subtitles if existing ----------------

"C:\Program Files\StaxRip\Apps\Subtitles\BDSup2Sub++\bdsup2sub++.exe" --forced-only -o "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID4 English_forced.idx" "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID4 English.idx"

Star Trek Deep Space 9 Season 1 Episode 3 ID4 English.idx

BDSup2Sub++ 1.0.3
OPTION: Exporting only forced subtitles.
Converting SUB/IDX
Loading D:/DVD Rips/Star Trek Deep Space 9/Season 1/Star Trek Deep Space 9 Season 1 Disc 1/VIDEO_TS/I2_T2/Star Trek Deep Space 9 Season 1 Episode 3_temp/Star Trek Deep Space 9 Season 1 Episode 3 ID4 English.idx
No forced subtitles found.
WARNING: Invisible caption due to zero alpha (not fixed due to user setting).
Detected 0 forced captions.

Start:    6:07:04 PM
End:      6:07:04 PM
Duration: 00:00:00

--------------------------- AviSynth Script ---------------------------

LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\Dual\ffms2\ffms2.dll")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\AVS\TDeint\TDeint.dll")
FFVideoSource("D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3.mkv", cachefile="D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3.ffindex")
#AssumeFPS(25)
TDeint()

------------------------- Source Script Info -------------------------

Width     : 720
Height    : 480
Frames    : 65551
Time      : 45:27.970
Framerate : 24.029219 (62500/2601)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 720
Height    : 480
Frames    : 65551
Time      : 45:27.970
Framerate : 24.029219 (62500/2601)
Format    : YUV420P8

---------------------- Media Info Audio Source 2 ----------------------

General
Complete name         : D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID2 English.ac3
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
File size             : 62.4 MiB
Duration              : 45 min 28 s
Overall bit rate mode : Constant
Overall bit rate      : 192 kb/s

Audio
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
Duration              : 45 min 28 s
Bit rate mode         : Constant
Bit rate              : 192 kb/s
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 SPF)
Compression mode      : Lossy
Stream size           : 62.4 MiB (100%)
Service kind          : Complete Main

---------------------- Media Info Audio Source 1 ----------------------

General
Complete name         : D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3 ID1 English.ac3
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
File size             : 146 MiB
Duration              : 45 min 28 s
Overall bit rate mode : Constant
Overall bit rate      : 448 kb/s

Audio
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
Duration              : 45 min 28 s
Bit rate mode         : Constant
Bit rate              : 448 kb/s
Channel(s)            : 6 channels
Channel layout        : L R C LFE Ls Rs
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 SPF)
Compression mode      : Lossy
Stream size           : 146 MiB (100%)
Service kind          : Complete Main

---------------------- Error Video encoding x264 ----------------------

Video encoding x264 returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function

------------------------- Video encoding x264 -------------------------

ffmpeg N-97868-gaa6f38c298-g38490cbeb3-gcc10.1.0 Patman

"C:\Program Files\StaxRip\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_new.avs" -c:v libx264 -aspect 1.367521 -an -y -hide_banner "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_new_out.mkv"

D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_new.avs: Unknown error occurred

------------------------- Video encoding x264 -------------------------

ffmpeg N-97868-gaa6f38c298-g38490cbeb3-gcc10.1.0 Patman

"C:\Program Files\StaxRip\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_new.avs" -c:v libx264 -aspect 1.367521 -an -y -hide_banner "D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_new_out.mkv"

D:\DVD Rips\Star Trek Deep Space 9\Season 1\Star Trek Deep Space 9 Season 1 Disc 1\VIDEO_TS\I2_T2\Star Trek Deep Space 9 Season 1 Episode 3_temp\Star Trek Deep Space 9 Season 1 Episode 3_new.avs: Unknown error occurred

Start:    6:29:22 PM
End:      6:29:23 PM
Duration: 00:00:00

**Comment by nbetcher** [comment]
Update: I've managed to fix this after several hours of trying different things. For those who have this issue, install AviSynth from https://github.com/AviSynth/AviSynthPlus/releases (I installed 3.6.1 w/VCRE). Once you're in StaxRip, go to Apps, Manage..., find AviSynth, click Version, and change it to 3.6.1.0. After this, the encoder works properly and streams data from AviSynth as expected.

It appears there's some kind of compatibility issue with the newly-bundled DLL of AviSynth into StaxRip. Leaving this issue open so that the maintainer may fix this for next release.

Processors Information
-------------------------------------------------------------------------

Socket 1			ID = 0
	Number of cores		6 (max 6)
	Number of threads	12 (max 12)
	Manufacturer		GenuineIntel
	Name			Intel Core i7 5820K
	Codename		Haswell-E/EP
	Specification		Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
	Package (platform ID)	Socket 2011 LGA (0x2)
	CPUID			6.F.2
	Extended CPUID		6.3F
	Core Stepping		R2
	Technology		22 nm
	TDP Limit		140.0 Watts
	Tjmax			95.0 °C
	Core Speed		1511.6 MHz
	Multiplier x Bus Speed	12.0 x 126.0 MHz
	Base frequency (cores)	126.0 MHz
	Base frequency (ext.)	126.0 MHz
	Stock frequency		3300 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, AES, AVX, AVX2, FMA3
	Microcode Revision	0x43
	L1 Data cache		6 x 32 KBytes, 8-way set associative, 64-byte line size
	L1 Instruction cache	6 x 32 KBytes, 8-way set associative, 64-byte line size
	L2 cache		6 x 256 KBytes, 8-way set associative, 64-byte line size
	L3 cache		15 MBytes, 20-way set associative, 64-byte line size
	Max CPUID level		0000000Fh
	Max CPUID ext. level	80000008h
	Cache descriptor	Level 1, D, 32 KB, 2 thread(s)
	Cache descriptor	Level 1, I, 32 KB, 2 thread(s)
	Cache descriptor	Level 2, U, 256 KB, 2 thread(s)
	Cache descriptor	Level 3, U, 15 MB, 16 thread(s)
	FID/VID Control		yes

**Comment by Dendraspis** [comment]
@nbetcher 
Please try the latest beta. A lot of things have changed since v2.1.3.0, including ffmpeg and AviSynth. **If the problem still occurs, please feel free to re-open this issue and let us know** - it's easier to analyze problems from an actual viewing point.
I'm also pretty sure we've had such a similar issue that could be solved.  🤔 

Nevertheless thanks for your solution - that will help others and us, if the problem should still occur. 👍
