### ISSUE TITLE
Setting the default VapourSynch Choice for subtitle renderer for batch processing hardcoded subs

### ISSUE THREAD

**Issue by wrzlpete** [staxrip/staxrip#385]
I cannot find a way to set the default subtitle renderer for hardcoding subs when using vapoursynch so when doing a batch process I have to manually pick one of the 2 given options (2.1.4.8 beta): core.sub.Textfile or core.vsfm.TextSubMod, meaning I cannot leave the process run unattended. How can I set one of the 2 as the default choice? Can I remove one of them just to have the other automatically as default somehow?
I have to use vapoursynch because the source is 10bit and only the vapoursynch plugin version can handle the subtitle rendering on that source color type.

**Comment by wrzlpete** [comment]
Ok, my workaround has become to ignore the staxrip internal setting of "Add hardcoded subtitle" in the Project Options "Subtitles" and use my own profile paragraph for Subtitles and simply enter the command StaxRip creates with the corresponding path macros for my template. Added benefit of this solution was that I could also add a parameter for scaling to the subtitle filter without any hassle. Not sure if this warrants closing this thread, as the issue itself still persists... so I'll refrain from doing that for now. Have a nice day everyone.

**Comment by stax76** [comment]
Sorry for not being able to reply earlier. Good to hear that you found a creative workaround.

**Comment by fidelix** [comment]
@wrzlpete can you explain how you achieved this?

Specifically, this?
> use my own profile paragraph for Subtitles and simply enter the command StaxRip creates with the corresponding path macros for my template

Thanks,

**Comment by wrzlpete** [comment]
I right clicked on the filter window pane (on the left) and selected "Profiles" and then added the following paragraph to the whole list of options in the edit window:
```
[Subtitle]
Sub_resize = clip = core.sub.TextFile(clip, file = r"%temp_dir%ID1 English_default.ass", scale=0.75)
```
The part `ID1 English_default.ass` is the name of the subtitle that StaxRip autocreates in the corresponding temp folder when demuxing the file you want to work with. Then just save the template as usual and as long as the filename of the demuxed subtitle stays the same it works without changes. If not, adjust it to the filename you find after demuxing. 

The scale-part is only for resizing, you can omit that to use the subs without changes.

**Comment by fidelix** [comment]
@wrzlpete thanks.

I did this instead (Basically gets the last subtitle in the folder):

```
[Subs]
ASS/SSA/SRT =
    for file in os.listdir(r"%working_dir%\"):
        if file.endswith((".ass", ".ssa", ".srt")):
            ass = os.path.join(r"%working_dir%\", file)
    clip = core.assrender.TextSub(clip, ass, fontdir=r"%working_dir%\")
```

A bit more fool-proof for cases where the source didn't set the language properly.

Thanks a ton!

**Comment by wrzlpete** [comment]
Wow, thanks a lot for that! I always wanted to dive in deeper to figure out a way to not have to deal with different filenames, but so far always chose the lazy route and just changed the config when needed.

I wasn't aware there's actual scripting possible inside the profile setup, nice to know! I'll change my setup right away.

Thanks @fidelix !

**Comment by tuktukcima** [comment]
> ```
>     clip = core.assrender.TextSub(clip, ass, fontdir=r"%working_dir%\")
> ```

hello how use this code

**Comment by tuktukcima** [comment]
> @wrzlpete thanks.
> 
> I did this instead (Basically gets the last subtitle in the folder):
> 
> ```
> [Subs]
> ASS/SSA/SRT =
>     for file in os.listdir(r"%working_dir%\"):
>         if file.endswith((".ass", ".ssa", ".srt")):
>             ass = os.path.join(r"%working_dir%\", file)
>     clip = core.assrender.TextSub(clip, ass, fontdir=r"%working_dir%\")
> ```
> 
> A bit more fool-proof for cases where the source didn't set the language properly.
> 
> Thanks a ton!


hello how use this code
