### ISSUE TITLE
Audio Naming

### ISSUE THREAD

**Issue by STiCKYFiNGAZZ** [staxrip/staxrip#386]
**Describe the bug**
Starting with Beta 2.1.4.3 the default naming of audio 1 to a1 and audio 2 to a2 seems to be removed. Now it names them both the same as source with only the extension added. In return will overwrite the first created audio with the second and cannot run concurrent audio jobs from the same source.

**Expected behavior**
Transcoded audio files have unique names, al/a2 was not ideal but it worked, maybe use the audio profile name instead? or revert back to a1/a2?

**How to reproduce the issue**

For example: Use source.audio.dts and choose ac3 5.1, it auto names it source.audio.dts.ac3. Then use the same source for second encode with a different audio codec and it also names it the same. Deletes the first encoded audio and cannot run 2 concurrent jobs.

**Comment by 44vince44** [comment]
@STiCKYFiNGAZZ
this is almost same issue described in posts https://github.com/staxrip/staxrip/issues/380 and https://github.com/staxrip/staxrip/issues/297. Audio naming since latest modifications has issues indeed.

**Comment by stax76** [comment]
It still uses a1, a2 etc. but only if there is actually more than one track, so I don't understand what's the problem here.

**Comment by 44vince44** [comment]
I think it's related to the audio modifications you're doing now:

> cannot run 2 concurrent jobs.

maybe whatever the issue is, it will be "fixed" with the new naming patterns

**Comment by stax76** [comment]
I hope things are better in the last build, there are many features and much complexity.
