### ISSUE TITLE
FFMPEG multipass video encoding fails due to pass log file improper location 

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#388]
**Describe the bug**
ffmpeg multipass operation attempts to create a log file called ffmpeg2pass-0.log in the **root of Staxrip program**.
This must not be allowed because if Staxrip program folder is in C:\Program Files\ then it is a Write Protected location.
(Found by Mister XY in Staxrip forum on Doom9)

**Expected behavior**
The pass log file of ffmpeg should be in the **temp folder**, not in the root of Staxrip program, which is normally semi-forbidden for Write operations.

**How to reproduce the issue**

Simply open a video file, set encoder to FFMPEG>x265 (or any supporting multipass) in TWO PASS mode. 
-If your Staxrip program files files folder is protected (which is the normal status), encoding will file due to incapacity of writing in that location
-If your Staxrip program files folder is not protected for R/W operations, then you'll see the file ffmpeg2pass-0.log appear in the root.

**Provide information ABOUT HOW TO FIX**

There is an option called -passlogfile in ffmpeg. You should use it in maybe all ffmpeg calls.
It works by adding custom switch **-passlogfile "%temp_dir%\ffmpeg2passlog"**
_EDIT: doesn't work **in custom line** because it seems that custom line does NOT pass macro values, unfortunately (read posts below)_
Note: the file name must not include the extension .log (ffmpeg adds it).

**Comment by Mister-XY** [comment]
I have no chance with the macro -passlogfile "%temp_dir%\ffmpeg2passlog" in custom switch in ffmpeg windows.
i get allways this message.
`Cannot write log file '%temp_dir%\ffmpeg2passlog-0.log' for pass-1 encoding: No such file or directory `

**Comment by 44vince44** [comment]
> 
> 
> I have no chance with the macro -passlogfile "%temp_dir%\ffmpeg2passlog" in custom switch in ffmpeg windows.
> i get allways this message.
> `Cannot write log file '%temp_dir%\ffmpeg2passlog-0.log' for pass-1 encoding: No such file or directory `

You're right, the macros are not passed in the custom window, but will be passed in the fix (that is, when @stax76 or @Patman86 or @Dendraspis fix it, and I'm really wondering why there is no sign of any of them at all).
The command line already uses macros for ffmpeg.exe, for the input file, etc.. So it will be very simple to add in the code the switch-passlogfile "%temp_dir%\ffmpeg2passlog".
Unfortunately, as we got to know now, the custom line does not pass macro values, so the only thing you can do in the custom line is:
-passlogfile "%temp%\ffmpeg2passlog"
This is not a staxrip macro, this is the user temp folder as defined in your Windows system (a global environment variable).

**Comment by Dendraspis** [comment]
@44vince44 
I'm sorry. Wanted to answer your last mentioning, but here we are. :(
There were some changes in my life and almost every aspect brought a lot of time consuming problems and questions about the present and the future. Additionally my Windows crashed and I lost a lot of data, including my few enhancements of StaxRip I worked on. I had no time yet to check what I could recover so far.
I'm still interested in StaxRip and hope I can re-join the development soon, but I doubt it will take a few more weeks.

**Comment by 44vince44** [comment]
@Dendraspis I'm happy to hear from you! But I'm so sorry about what happened to you, I wish you'll sort out the problems, and that you'll be fine soon, far away from any problems! Good luck my Friend !

**Comment by stax76** [comment]
@Dendraspis I'm also happy to hear from you and hope everything will be fine.

**Comment by 44vince44** [comment]
@stax76 Hey where have you been ;-)

**Comment by stax76** [comment]
@44vince44 Hi, I needed a break, still do. 🤔

**Comment by 44vince44** [comment]
Enjoy it @Stax76 !!  ;-)))

**Comment by stax76** [comment]
@44vince44

Thx, so I was at therapy, for quite a while, I was very lucky and had a great time and therapy greatly helped, after therapy it was difficult for a while, now I'm fine again.

I'll create an issue and pin it (or a discussion with this new discussion feature...) to tell you guys about my outlook on the project. 

Next build 2.1.4.9 Beta addresses this issue with:

- Set the current directory of the StaxRip process to the temp/working
  directory of the current project.

ffmpeg as child process will automatically inherit the directory and use it for temp files.

- ffmpeg encoder expands macros of custom options.

This should probably be done for all encoders but there might be many more important tasks.

**Comment by Mister-XY** [comment]
Nice to hear that you’re fine.

**Comment by 44vince44** [comment]
Welcome back @stax76 ! I'm so relieved that you're fine !!

**Comment by Dendraspis** [comment]
@stax76 
Nice to read you're fine!  😊 
The dream team is complete, again.  🎉

**Comment by 44vince44** [comment]
still need  to hear from @Patman86  !hope he's fine too !

**Comment by Patman86** [comment]
Hello everybody.  I became a father for the second time, so my focus was and is currently another.  I will get back to you more often now.

**Comment by 44vince44** [comment]
@Patman86 Congratulations !!!!!!!!!

**Comment by stax76** [comment]
@Patman86 Congratulations and Best Wishes!

**Comment by 44vince44** [comment]
This is fixed, just tested OK!
Thanks!
Closing the thread.
