### ISSUE TITLE
long path support need to be investigated

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#39]
long path support need to be investigated

**Comment by Revan654** [comment]
> 
> 
> long path support need to be investigated

Windows 10 => Not sure what needs to Investigated(There an Option to Enable it).  Even Python after install it. Will ask you if you want to Enable long path support.

Long path is only really an Issue on Windows 7. All support for Windows 7 ends in 5 months.

**Comment by stax76** [comment]
@Revan654 

You mean you successfully used long paths in staxrip? I've never really tried.

**Comment by Revan654** [comment]
> 
> 
> @Revan654
> 
> You mean you successfully used long paths in staxrip? I've never really tried.

There isn't really a path length any more on Windows 10.

**Comment by stax76** [comment]
I know there is a switch to enable it, by default it's disabled. Even when it's enabled I'm sure many apps will not support long paths for various reasons, I know one of my .net utilities failed recently but when it happened I didn't have time to investigate it.

**Comment by Revan654** [comment]
- If any Harddrive still uses FAT, It will not work on due to limitations it has.

The Other is likely due to the Framework, Anything above 4.6.2 has Long Path support by default. The Max Limit is now (32,767), from the previous 260.

**Comment by stax76** [comment]
https://forum.doom9.org/showthread.php?p=1885092#post1885092

**Comment by Revan654** [comment]
> 
> 
> https://forum.doom9.org/showthread.php?p=1885092#post1885092

Info was pulled directly from MS docs. Could be an issue when using external processes that is not native to the app.

**Comment by stax76** [comment]
It would be nice to support it but if tools like mkvtoolnix don't support it there is not much we can do.
