### ISSUE TITLE
IMPORTANT REGRESSION in 3-pass mode (x265)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#391]
@Dendraspis:  the bug concerns at what stage the output video is generated in the --pass steps

First-pass : the output video is NUL   => GOOD
Nth-pass : the output video is the output video file  => **NO ! it must be NUL**
Last-pass : the output  video is NUL   => **NO! it must be the output video file.** because it must be generated here.

Only affects x265 in 3 pass mode (and 3-pass mode with chunks)! 

Note: x264 works fine.

**Comment by Dendraspis** [comment]
@44vince44 
Very good job! Shame on me, the confusion about those passes let me forget to check that.  🙄   But it's fixed now. 
Side note:  I knew you prefer 3-pass mode over CRF.  😄  😏

**Comment by 44vince44** [comment]
> Side note: I knew you prefer 3-pass mode over CRF. 😄 😏

Indeed, you've got me, and EXACTLY same reason why you fixed it so quickly 😄😄😄😄😄

**Comment by 44vince44** [comment]
@Dendraspis this is fixed indeed. tested 3-pass an 3-pass chunk with 2 chunks. all ok !
Thanks!!!

**Comment by Dendraspis** [comment]
@44vince44 
No problem, but thanks for testing ... I knew I would make you very happy when 3-pass mode would work properly.  😄 😜 😄
