### ISSUE TITLE
Can someone please close all fixed / tool issue / question threads ?

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#392]
Looking at the open issues, one will think that staxrip is veeeery buggy .....

**Comment by stax76** [comment]
Sometimes it is buggy. 🤔

But yes, I'll have a look and close as many as possible.

**Comment by Dendraspis** [comment]
> But yes, I'll have a look and close as many as possible.

😁  I found another one ....

**Comment by 44vince44** [comment]
well done 🤣
