### ISSUE TITLE
BUG : warning "Invalid Cutting Settings" does not appear always when it should appear.

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#395]
**Describe the bug**
There are two ways of defining a range:
1) open preview from main program window
2) open preview from EDIT CODE window

When you define a range from the EDIT CODE window, the range will applied correctly on audio, but INCORRECTLY on video.
So you get a file with correct audio, but incorrect video.

**Expected behavior**
Either:

- put back the WARNING message that can not be skipped, and that asks to open the preview (like it was before)
or
- fix for video, and check other streams as well (subtitles and menu)

**Comment by stax76** [comment]
Are you sure there was a warning about this?

I don't remember anything about it.

**Comment by 44vince44** [comment]
Yes there was:

![SNAG-0000](https://user-images.githubusercontent.com/17828567/102307390-0dc60b00-3f6d-11eb-9d26-cef7e4f26d34.jpg)


And it's not a feature request with priority low, it's a REGRESSION with priority HIGHT !!!!
this this was working all right in 2.1.4.8

**Comment by 44vince44** [comment]
@stax76 
It's worse than I thought.
The message works if Main window preview has never been opened. Once it is opened (only once) the message is disabled.

Here is how to reproduce:
open the file
open Code Editor (using Edit Code command, under AVS filter drop list)
press F5 from inside code editor, it opens preview, define a range, close preview
close code editor
MESSAGE "Invalid cutting settings" appears  ===> THIS IS GOOD, expected behavior
Open Preview from MAIN PROGRAM window (not from code editor), CLOSE preview
MESSAGE "Invalid cutting settings" is GONE ===> THIS IS GOOD, expected behavior
open Code Editor again
open preview from Code Editor (F5), clear range, define new, different range
Close preview, close Code Editor
MESSAGE "Invalid Cutting Settings" **DOES NOT APPEAR** ===> **NOT GOOD**, and the encode proves it.

**Comment by stax76** [comment]
I changed it to refresh the cut code after the code editor closes.

**Comment by stax76** [comment]
@44vince44

I wonder how you got the UI themed like in your screenshot?

**Comment by 44vince44** [comment]
@stax76 Windows themes still use (for all colors except one or two) the very old color definitions. You can still tweak them, That's what I did ;-)

BTW I need to test this fix, because I must see how multiple preview windows is being handled, since you can open as many preview windows as you want from the Code Editor (and that is a very powerful feature, when you apply correction to the image)

**Comment by stax76** [comment]
> Request: can this be fixed easily so pressing F9 from an active preview shows only ONE mpv, with the avs of the active preview?

It was already implemented for Close and was relative easy to expand for Play. I verified that it actually uses the script of the active preview. And I removed the main dialog being the owner, it's now possible to put the main dialog in the foreground.

**Comment by 44vince44** [comment]
Wow thanks !!! can't wait for next beta 🤣
