### ISSUE TITLE
ffmpeg CRF value

### ISSUE THREAD

**Issue by Mister-XY** [staxrip/staxrip#396]
Hello, a little question. With ffmpeg I can only specify the crf area in the two-digit range. ffmpeg allows me to change the crf area after a point. Say crf 20.2 instead of just 20. I can change it myself with the command -crf 18.2 in the command line, but why not in the selection?

![Screenshot 2020-12-15 190726](https://user-images.githubusercontent.com/10309056/102254378-d291f080-3f08-11eb-8964-83c67b49f076.jpg)

![Screenshot 2020-12-15 191306](https://user-images.githubusercontent.com/10309056/102254909-9743f180-3f09-11eb-9996-7d27a0dc8a89.jpg)

**Comment by Dendraspis** [comment]
Because nobody use ffmpeg as encoder - especially when there is a good one from the developers like x265 that is fully supported in StaxRip.

I think I can change it the next days.

**Comment by stax76** [comment]
I've changed it now.

**Comment by Dendraspis** [comment]
...and I've set the step to 0.5 instead of 1.0 to be compliant with x264 and x265 settings.  😬 

@stax76 
> I've changed it now.

Spoilsport!  😋
