### ISSUE TITLE
File not found exception when converting mp4 to mkv

### ISSUE THREAD

**Issue by asheroto** [staxrip/staxrip#397]
**Describe the bug**
I converted some mp4 files to mkv and then deleted the mkv files.  I tried to convert the mp4 files again (using a different profile) and now the program just errors out with the following:

```
System.IO.FileNotFoundException: Could not find file 'C:\hold\17. 01-030-030 AWS Architecture and Compliance.mkv'.
File name: 'C:\hold\17. 01-030-030 AWS Architecture and Compliance.mkv'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 1981
```

**Expected behavior**
I expected the mp4 file to convert to mkv.  There is no "mkv" file because I deleted it (because I wanted to use a different profile).  But now it won't convert anything in this folder.

It's like Staxrip "remembers" the file or something.

**How to reproduce the issue**

Convert an mp4 file to mkv using one profile, then delete the mkv, then convert the same mp4 file to mkv using a different profile.

**Comment by Dendraspis** [comment]
- Which version are you using?
- Have you updated StaxRip between those encodes?

**Comment by asheroto** [comment]
Hello @Dendraspis,

- Version 2.1.3.0
- I have had the same version
- Both single and batch produce the same problem
- There was only one instance of StaxRip

Here's something weird...

If I delete `%AppData%\StaxRip` and launch it again, it works correctly.

I tried building the project in Visual Studio but got a ton of errors...

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'VSScript.h': No such file or directory	FrameServer	C:\data\GitHub\staxrip\FrameServer\VapourSynthServer.h	10	
Error (active)	E0018	expected a ')'	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0018	expected a ')'	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	20	
Error (active)	E0018	expected a ')'	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	23	
Error (active)	E0018	expected a ')'	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	24	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0020	identifier "handle" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0020	identifier "script" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0020	identifier "errorFilename" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	20	
Error (active)	E0020	identifier "handle" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	20	
Error (active)	E0020	identifier "scriptFilename" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	20	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	21	
Error (active)	E0020	identifier "handle" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	21	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	22	
Error (active)	E0020	identifier "handle" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	22	
Error (active)	E0020	identifier "VSNodeRef" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	23	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	23	
Error (active)	E0020	identifier "handle" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	23	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	24	
Error (active)	E0020	identifier "handle" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	24	
Error (active)	E0020	identifier "VSCore" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	25	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	25	
Error (active)	E0020	identifier "handle" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	25	
Error (active)	E0020	identifier "VSAPI" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	26	
Error (active)	E0020	identifier "VSAPI" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	39	
Error (active)	E0020	identifier "VSScript" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	40	
Error (active)	E0020	identifier "VSNodeRef" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	41	
Error (active)	E0020	identifier "VSFrameRef" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	42	
Error (active)	E0020	identifier "VSVideoInfo" is undefined	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	43	
Error (active)	E0254	type name is not allowed	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0254	type name is not allowed	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0254	type name is not allowed	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	19	
Error (active)	E0254	type name is not allowed	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	20	
Error (active)	E0254	type name is not allowed	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	20	
Error (active)	E0254	type name is not allowed	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	23	
Error (active)	E0254	type name is not allowed	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	24	
Error (active)	E1696	cannot open source file "VSScript.h"	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	10	
Error (active)	E1696	cannot open source file "VSHelper.h"	FrameServer	C:\Data\GitHub\staxrip\FrameServer\VapourSynthServer.h	11	

```

**Comment by asheroto** [comment]
Here's an error from trying to convert a h264 mkv to a h265 mkv

![image](https://user-images.githubusercontent.com/49938263/102447441-97212000-3ff5-11eb-86ba-57b22dea0ba8.png)

**Comment by asheroto** [comment]
That file exists

![image](https://user-images.githubusercontent.com/49938263/102447508-b029d100-3ff5-11eb-835d-8c594d6544d9.png)

**Comment by asheroto** [comment]
Here is the log file using a sample video
[video_staxrip.log](https://github.com/staxrip/staxrip/files/5707568/video_staxrip.log)

**Comment by Dendraspis** [comment]
> Here's something weird...
> If I delete `%AppData%\StaxRip` and launch it again, it works correctly.

Interesting. 🤔  Good observation!

> I tried building the project in Visual Studio but got a ton of errors...

It's a bit easier than that:
https://staxrip.readthedocs.io/introduction.html#beta

**Comment by 44vince44** [comment]
@Dendraspis @asheroto careful, this is version 2.1.3.0, lots of things have changed. Why not use latest beta for the tests ?

**Comment by Dendraspis** [comment]
@44vince44 
Because he/she/it tried to build StaxRip with VS, I would guess he/she/it didn't know, that there is an official beta and/or where to find it.

**Comment by asheroto** [comment]
> > Here's something weird...
> > If I delete `%AppData%\StaxRip` and launch it again, it works correctly.
> 
> Interesting. 🤔 Good observation!
> 
> > I tried building the project in Visual Studio but got a ton of errors...
> 
> It's a bit easier than that: 😁
> https://staxrip.readthedocs.io/introduction.html#beta
> 
> Please try also this:
> Move the source from `C:\` to another drive and subfolder or a folder with full access like 'Documents', 'Downloads' or similar inside your profile.
> Then open it and start the process as you did before. Error gone?

Unfortunately, no.  I even assigned "everyone" full control on a test folder and file and it didn't help.

If I delete %AppData%\StaxRip and then open up StaxRip and open a file, it does the "ISO extraction" right away.  But deleting the _temp folder it creates and then re-adding the file fails to do the "ISO extraction" again.  Does that make sense?

1. Clear appdata folder
2. Open mp4 and it does ISO extraction
3. Delete _tmp folder it created
4. Open mp4 again - this time it does NOT do ISO extraction and it fails with an error message



> @asheroto careful, this is version 2.1.3.0, lots of things have changed since then. Why not use latest beta for the tests ?
> I'm afraid you maybe didn't see Dendraspis suggestion.
> 
> Note: I do tons of mp4 to mkv conversions and tons of re-running same job. Never had this problem.
> I have questions, please provide the answers, they are needed to try to reproduce:
> 
> 1. What happens to the temp folder, is it deleted or still there (deletion of temp folder options are in the settings)
> 2. How do you reprocess the file, do you drag and drop the mp4 again, or open the mp4 again in staxrip, or do you open the previous .srip file (found in the temp folder) in Staxrip and modify the parameters?

1. See above (or if I set it to Recycle Bin / Permanent in settings)
2. I usually right-click on the source textbox, go to Open, Single File, OR I will drag in there (either way it has the same issue)

I will try the beta, I didn't see the compiled links before, so thanks!

Pronoun for me is a "he".  :-)

**Comment by asheroto** [comment]
Happy to report that beta version 2.1.5.2 is working without this bug.  👍 

Thanks all for the quick response and help.

**Comment by asheroto** [comment]
FYI I originally found StaxRip on Chocolatey's website. That's how I ended up with the non-beta.

**Comment by stax76** [comment]
> Cannot open include file: 'VSScript.h': No such file or directory

You need to put the apps in the output folder:

\Apps\FrameServer\VapourSynth\sdk\include\VSScript.h
