### ISSUE TITLE
How do I solve Script Error?

### ISSUE THREAD

**Issue by AlucardSama04** [staxrip/staxrip#399]
`Script Error

Python exception: Plugin C:\Users\George\Desktop\[A-Evolution] StaxRip\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll already loaded (systems.innocent.lsmas) from C:/Users/George/AppData/Roaming/VapourSynth/plugins64/LSMASHSource.dll

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
  File "D:\Downloads\[SubsPlease] Rail Romanesque - 01 (1080p) [3B5B2354]_temp\[SubsPlease] Rail Romanesque - 01 (1080p) [3B5B2354]_source.vpy", line 5, in <module>
    core.std.LoadPlugin(r"C:\Users\George\Desktop\[A-Evolution] StaxRip\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll", altsearchpath=True)
  File "src\cython\vapoursynth.pyx", line 2069, in vapoursynth.Function.__call__
vapoursynth.Error: Plugin C:\Users\George\Desktop\[A-Evolution] StaxRip\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll already loaded (systems.innocent.lsmas) from C:/Users/George/AppData/Roaming/VapourSynth/plugins64/LSMASHSource.dll

`
What should I do?

**Comment by stax76** [comment]
What's happening here is probably l-smash is located in a plugin autoload folder and vapoursynth loads it from there, and then staxrip tries to load it again manually from the plugins that are included by staxrip, which is the normal operation mode of staxrip. Staxrip has already a protection against this built-in, but it's apparently not working here.

Do you have staxrip configured to use portable or installed vapoursynth? You can see that in the staxrip settings on the Frameserver tab.

Staxrip has a feature to disable manual plugin loading altogether, but then you would need all plugins to be available in the plugin autoload folder, I don't know if that's suitable for you.

I'll try to reproduce it.

**Comment by stax76** [comment]
Yes, I can reproduce it when staxrip is configured to use installed vapoursynth. I'll investigate it.

**Comment by stax76** [comment]
It will be fixed in the next beta version, meanwhile you can workaround it by using portable mode.

**Comment by stax76** [comment]
You can try now the new Beta version.
