### ISSUE TITLE
Doesn't support filenames with ampersands

### ISSUE THREAD

**Issue by dhry** [staxrip/staxrip#4]
Tried to encode a file with an & in the name, got a failure. Staxrip 2.0.2.0. I had manually updated Nvencc to 4.40 if that makes a difference. All my other encodes worked fine.

------------------- Video encoding using NVEnc 4.38 -------------------

"C:\Program Files\StaxRip\Apps\Encoders\NVEnc\NVEncC64.exe" --avhw cuda --vbrhq 2 --codec h265 --preset quality --vpp-unsharp --lookahead 32 --qp-init 28 --qp-max 24 --qp-min 28 --max-bitrate 0 --vbr-quality 24 --aq --colormatrix bt709 --cabac -i K:\TBD\Ben&Jamie.mkv -o K:\TBD\Ben&Jamie_temp\Ben&Jamie_new_out.h265

Output file is not specified.
'Jamie.mkv' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
Jamie_new_out.h265' is not recognized as an internal or external command,
operable program or batch file.

Start:    8:32:48 AM
End:      8:32:48 AM
Duration: 00:00:00

**Comment by stax76** [comment]
Thanks for the feedback, it will be fixed in the next build/release.

**Comment by dhry** [comment]
Nice work Frank, thanks!

**Comment by stax76** [comment]
You're welcome, the new release is out.
