### ISSUE TITLE
New Patman86 builds (formerly-Attention Patman86: your builds are missed !)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#400]
@Patman86 i really miss your builds of x265 and x264.... Hope you'll find some time to update them...

**Describe alternatives you've considered**
there are no other builds (that i know of) that provide the estimate size of the stream... And besides, your gcc builds have better performance...

**Comment by Patman86** [comment]
I want to upload my updates tonight ^^

**Comment by 44vince44** [comment]
that's real great news !!! 🎉

**Comment by Patman86** [comment]
I've updated most of my builds. Only with x265 do I have some problems. The version is wrong with the query (both builds) and with the mod trying to find out why the direct * .vpy support doesn't work properly with the 3.4 branch (the direct * .avs support works). Branch 3.3 works fine with both changes (avs + vpy).

**Comment by 44vince44** [comment]
Strange... why should the behavior change. did they do some undocumented changes ?

**Comment by Patman86** [comment]
I don't think so, but maybe the routine or phylosophy has changed. I'll stay tuned ...

**Comment by 44vince44** [comment]
New builds by Patman86 available right now (builds 2020-12-20) clickable links:

[ffmpeg-N-100448-gab6a56773f-x64-gcc10.2.0](https://www.mediafire.com/file/usnteo0pds69bpw/ffmpeg-N-100448-gab6a56773f-x64-gcc10.2.0.7z/file)
[x264M-0.161.3027-4121277-x64-gcc10.2.0](https://www.mediafire.com/file/5fn34ezqq124x4o/x264M-0.161.3027-4121277-x64-gcc10.2.0.7z/file)
[SvtAv1EncApp-v0.8.6-27-g3105898d7-x64-gcc10.2.0](https://www.mediafire.com/file/10ogogacdsepc3s/SvtAv1EncApp-v0.8.6-27-g3105898d7-x64-gcc10.2.0.7z/file)
[rav1e-0.4.0-alpha (p20201215)-x64-gcc10.2.0](https://www.mediafire.com/file/2sr28sxzgajjg10/rav1e-0.4.0-alpha_%2528p20201215%2529-x64-gcc10.2.0.7z/file)
[aomenc-2.0.1-1114-g7ddc21b28-x64-gcc10.2.0](https://www.mediafire.com/file/01v36grpzhvw9ov/aomenc-2.0.1-1114-g7ddc21b28-x64-gcc10.2.0.7z/file)
[Mp4Box-1.1.0-DEV-rev384-gf9e004333-x64-gcc10.2.0](https://www.mediafire.com/file/jcaoaqtxw5yztp0/Mp4Box-1.1.0-DEV-rev384-gf9e004333-x64-gcc10.2.0.7z/file)

Still waiting for x265M release (the most important one 🤣).

**Comment by Patman86** [comment]
I'll fix aomenc today

**Comment by 44vince44** [comment]
@Patman86 please check also Mp4Box there's an error with liblzma-5.dll missing !

FFMPEG and x264M are apparently OK!

**Comment by Patman86** [comment]
Thx for your feedback, I'll check it.

**Comment by Patman86** [comment]
I've recompiled all of my builds and hope the bugs are fixed!

**Comment by Dendraspis** [comment]
Today I switched to StaxRip v2.1.5.3 and damn, I'm so f*§x1#$ missing your x265 estimated file size addition.  😭  😁 

Hope to see you succeed very soon.  ☺️

**Comment by Patman86** [comment]
I hope so too.

**Comment by 44vince44** [comment]
I'll be testing later ;-)

**Comment by Patman86** [comment]
I ran the files on my laptop and got no errors. It would be great if you can confirm that @44vince44

**Comment by 44vince44** [comment]
@Patman86 
I tested both the apps  that were failing:

Mp4Box => now works, no more requests for dll 🆗 
aomenc => now works, no more requests for 🆗 BUT there is no output showing the progress in terms of frames processed

**Comment by Patman86** [comment]
> aomenc => now works, no more requests for dlls 🆗 BUT there is no output showing the progress in terms of frames processed

The included version (staxrip zip) was compiled with msvc (Visual Studio). It's the same problem we had with SVT-AV1!
@ stax76, you know?

**Comment by Dendraspis** [comment]
Erm ... where can I find those new builds?  😥 

> Thanks! Can't wait for the new x265!

Oh yes!! Agreed!! 😎 

> it seems that version checking for aomenc is not detecting different version (specific aomenc), Is there any thing forgotten in the process?

🤔  Nothing special found.

**Comment by 44vince44** [comment]
@Dendraspis the version detection for aomenc did work with last aomenc update. Thanks @Patman86 ?
BTW Did you find Patman's repository ?

**Comment by 44vince44** [comment]
> x265 and x265M are online. At the moment only the direct AVS input works on x265M. Don't be confused about the version tag (is up to date), something is wrong with the latest commit on x265_git. I opened an issue for it.

@Patman86  thanks for everything ! I'm enjoying x265 verbosity as I'm used to it, finally!

**Comment by Patman86** [comment]
>Thanks @Patman86 ?

I've reorder my scripts for compiling and now it's no problem to update the tools 4 times a month (minimum) 😁

**Comment by 44vince44** [comment]
Ah! that's good to know 😃

**Comment by 44vince44** [comment]
@Patman86 new aomenc is displaying info all right now 👍 

@Dendraspis Warning my friend, setting threads of aomenc to 128 gives an out of range error. I tried value 32 it passed ok. Please change the initial setting !!!!

**Comment by Dendraspis** [comment]
@Patman86 
Thanks.  😀 

@44vince44 
Wrong issue ... and I hate you.  😏  😁  😂  ... and aomenc, but this time I'm not lying.  💢 
I've answered in #375.  😜

**Comment by 44vince44** [comment]
Since this is an ALL FIXED, EVERYTHING OK event, I'm closing!
Thanks @Patman86 
@stax76 don't forget to update !

**Comment by stax76** [comment]
@Patman86

Great to see you back. I've tried updating x265 M-3.4+28-419182243-x64-gcc10.2.0 (2020-12-22) and tested avs input, it seems to be broken, output is distorted, with avs2pipemod it's fine.

**Comment by stax76** [comment]
@Patman86 

> The included version (staxrip zip) was compiled with msvc (Visual Studio). It's the same problem we had with SVT-AV1!

I've fixed the progress for aomenc, it probably was never implemented, but you are right, it looks like we have the same flush issue we had with SVT-AV1.

**Comment by stax76** [comment]
Made a bug report:

https://bugs.chromium.org/p/aomedia/issues/detail?id=2909

**Comment by Dendraspis** [comment]
@Patman86 
Just a question: Why is your build about 20x smaller than the one from Yuuki-Asuna?  😲

**Comment by Patman86** [comment]
> @Patman86 
> Just a question: Why is your build about 20x smaller than the one from Yuuki-Asuna?  😲 

Packed with upx 😉

**Comment by Dendraspis** [comment]
> I've tried updating x265 M-3.4+28-419182243-x64-gcc10.2.0 (2020-12-22) and tested avs input, it seems to be broken, output is distorted, with avs2pipemod it's fine.

> EDIT: x265 and x265M are online. At the moment only the direct AVS input works on x265M. Don't be confused about the version tag (is up to date), something is wrong with the latest commit on x265_git. I opened an issue for it.

😄 


> Packed / compressed with upx 😉

🤔  I hope there are no issues because of compression - I had really bad experience with such tools years ago.
But it explains the huuuuuuuuge difference in size.  😁

**Comment by Patman86** [comment]
> > I've tried updating x265 M-3.4+28-419182243-x64-gcc10.2.0 (2020-12-22) and tested avs input, it seems to be broken, output is distorted, with avs2pipemod it's fine.

> 🤔 I hope there are no issues because of compression - I had really bad experience with such tools years ago.
> But it explains the huuuuuuuuge difference in size. 😁 Thanks!

I made a mistake while putting the data together for compilation, it should work now. x265M files have been updated.

**Comment by Dendraspis** [comment]
@Patman86 
I meant other issues, but it seems to help there either.   😁

**Comment by Patman86** [comment]
> I've fixed the progress for aomenc, it probably was never implemented, but you are right, it looks like we have the same flush issue we had with SVT-AV1, so I use the [marco sousa](https://ci.appveyor.com/project/marcomsousa/build-aom/build/artifacts) build, file size is too large. 🤔

I've uploaded a msvc version too.

**Comment by stax76** [comment]
> x264 is generally broken because the long path patch did break ANSI support..., I will not update it until it's fixed, I made a request on the x264 tracker.

I take this back.

> I've tried updating x265 M-3.4+28-419182243-x64-gcc10.2.0 (2020-12-22) and tested avs input, it seems to be broken, output is distorted

Added this now to the wiki:

https://github.com/staxrip/staxrip/wiki/x265#patman

**Comment by Patman86** [comment]
I updated some tools again. x265 now also supports direct avs and vpy input (thx @msg7086 and @DJATOM for source code)

**Comment by 44vince44** [comment]
I promise I will test, just after the following 2 or 3 days.

**Comment by Patman86** [comment]
Updated tools again and add msvc builds for some tools.

**Comment by Patman86** [comment]
Updated tools ...
@ stax76
MP4Box should now support a long path when compiling with gcc
aomenc, the progress bar should now be displayed correctly

**Comment by stax76** [comment]
@Patman86 
I confirm the freeze, apparently only happens with long path and within staxrip, it works using cmd directly, I'm afraid it will not be easy to find the reason.

**Comment by stax76** [comment]
Fortunately I already found it, here is the code that was causing it:

proc.Process.StartInfo.EnvironmentVariables("TEMP") = proj.TempDir
proc.Process.StartInfo.EnvironmentVariables("TMP") = proj.TempDir

This was added because MP4box did trash the temp folder with huge files.

**Comment by Patman86** [comment]
I've updated x264 and integrates some of the DJATOM- and msg7086 commits. Give it a try 😉
x265 will follow tomorrow.

**Comment by JJKylee** [comment]
So, have you included the custom progress header for your x264 like @DJATOM?

**Comment by Patman86** [comment]
No, I use my custom progress bar.
[See from here ...](https://github.com/Patman86/x264-Mod-by-Patman/commit/2fcf143a0bbb42ab2d027905bdddfdcb7d795ed9#diff-8c56d435884632afd2d52637bfc692c57c9308fb7883611cab40e21471e7a09eR1898)

**Comment by JJKylee** [comment]
Looks good to me. 😄

![StaxRip_2 1 8 0_Patman_x264_default_progress-text_20210212](https://user-images.githubusercontent.com/3157518/107838714-0009e780-6d5c-11eb-9865-efeb87e1c933.jpg)

But I'm afraid @Dendraspis will have a headache building a separate rule for parsing your custom progress text. 🤣

BTW, although I haven't tested thoroughly, your x264 build seems to be working pretty well so far.
Good job, @Patman86! 👏👏👏👏

**Comment by Patman86** [comment]
THX for your fast feedback.

> But I'm afraid @Dendraspis will have a headache building a separate rule for parsing your custom progress text. 🤣

he can do it... 😂 I've stored everything directly in the progress bar 😎

**Comment by stax76** [comment]
@Patman86 

If you are interested I can create repos under github.com/staxrip

**Comment by stax76** [comment]
@Patman86

I wanted to patch ffmpeg with long path and UTF-8 support, it can be done with a command line tool that ships with Visual Studio, it's described here:

https://docs.microsoft.com/de-de/cpp/build/how-to-embed-a-manifest-inside-a-c-cpp-application?view=msvc-160

It works, but only with an unpacked ffmpeg.

I tried to unpack your build, but it fails to unpack correctly.

Maybe you can upload it unpacked, so I can patch and pack it.

**Comment by Patman86** [comment]
Tonight I'll upload an unpacked version of ffmpeg and the finished x265 binary

**Comment by stax76** [comment]
I've uploaded a new Beta with your new ffmpeg build.

The new x264 build isn't yet included and integrated but should be in the next Beta.

**Comment by 44vince44** [comment]
@stax76 I tested v2.1.8.2 ffmpeg encoding with non-ascii characters, all working fine!

**Comment by Patman86** [comment]
My x265 version is online 😉

**Comment by 44vince44** [comment]
I'll test it this evening !!!

**Comment by Patman86** [comment]
I want to integrate mkv and mp4 support for output file but there are two issues... Are you interested in this support?

**Comment by JJKylee** [comment]
IMHO, _elementary streams_ are more than enough for an output format. If we need an `mkv` or `mp4` output, we can always use `MP4Box` or `mkvmerge` along with the _No Audio_ option. You don't have to waste your precious time. 😅

**Comment by DJATOM** [comment]
I want to add mkv support for my mod (and extend VS reader to support VFR clips), but have more urgent tasks next month, so it will wait.

**Comment by Patman86** [comment]
> I want to add mkv support for my mod (and extend VS reader to support VFR clips), but have more urgent tasks next month, so it will wait.

As input or output support?

**Comment by DJATOM** [comment]
Output.

**Comment by 44vince44** [comment]
As a user of Staxrip, imho : 

- output mkv,mp4 : Staxrip does the muxing with mkvmerge, so as @JJKylee  said, we can use the muxer. Current h265 stream is more than enough and can be used directly in mp4 and mkv containers.
- VFR clips supported in VS reader : @DJATOM  this could be really interesting, as long as cutting is supported ! What will be the output in that case, a VFR or a CFR ?

**Comment by Dendraspis** [comment]
Personally I would ***LOVE*** to have the option to create MKVs directly. 🤗

**Comment by 44vince44** [comment]
What for, you would create a mkv with only the video stream. I fail to understand why. I'm surely missing the point ....

**Comment by DJATOM** [comment]
Vapoursynth produces vfr by stuffing different _DurationNum/_DurationDen, so trimming should work fine.

**Comment by Dendraspis** [comment]
That's what StaxRip does for me at the moment. I only encode the source using x265 and StaxRip muxes the encoded file into an MKV file.

With x265 supporting MKV as output file, I could save time and also a lot of IO activity.

**Comment by DJATOM** [comment]
@44vince44 the point is to provide muxed stream with timecodes, no need to mux from text file.

**Comment by msg7086** [comment]
I just want to add some context.

The only reason I left MKV support in the patch list, is because a friend of mine wanted to play the output file during encoding (to examine the quality and restart if needed). It serves absolutely no purpose in encoding if you don't watch the video during encoding. MP4 output is always in a better support than its MKV.

The MKV muxer is an ancient one, and is not in production grade for modern codecs. It MUST be re-muxed by a modern muxer such as mkvmerge to properly re-construct a few things.

**Comment by Dendraspis** [comment]
> The MKV muxer is an ancient one, and is not in production grade for modern codecs. It MUST be re-muxed by a modern muxer such as mkvmerge to properly re-construct a few things.

That's right and at least what I would do. The biggest difference are the timestamps as already mentioned by @DJATOM. With a normal player you can't check the result when it's an h265 file. An MKV would let us check check the whole output ***and*** save a good amount of minutes for muxing - maybe multiple times.

**Comment by msg7086** [comment]
> With a normal player you can't check the result when it's an h265 file.

Now I almost only use GOP output as it works best with my needs, and I can chunk encode or check the result easily.

**Comment by stax76** [comment]
@Dendraspis If you want you can disable muxing by choosing the _No Muxing_ muxer profile.

**Comment by Dendraspis** [comment]
@stax76  I know, but an ***.h265*** file is useless for me, because I need to check the result before the next steps. So as long there is no direct MKV output, I'm very happy, that StaxRip can do this for me - without big adjustments.  😊

**Comment by 44vince44** [comment]
@stax76 this makes sense, i sometimes would like to test a file in the middle of the encoding. The file "xxxxx_out.hevc" can play in mpv.net but you can't seek inside it. But if it was a "xxxx_out.mkv" it would be readable and seekable in mpv,net.
And you would be able to check the encoding without stopping the encoding...
It requires the encoder to output directly to mkv or mp4.

**Comment by Dendraspis** [comment]
Allow me to ask:
What's the difference between the *gcc* and *msvc* version? 🤔

**Comment by Patman86** [comment]
Just the compiler and the file size 😉
maybe a little speed difference

**Comment by Dendraspis** [comment]
The question is: which is or might be faster? 🤔

Just wanted to ask if there are parameter-wise differences or supported inputs. 😊
But it seems we have the choice just for fun. 😁

**Comment by Patman86** [comment]
There are no differences between the versions. Some people prefer certain compilers. Pick your favorite.

**Comment by Dendraspis** [comment]
Belongs to the category *black zebra with white stripes or white zebra with black stripes*.  😁

Thanks for explanation/confirmation.

**Comment by 44vince44** [comment]
@Dendraspis @Patman86 @JJKylee Some time ago, we made tests comparing builds between msvc and gcc.
Test results were reported here and on doom9.
**ALL USERS found that gcc version gives you a few percent better performance.**

This is why we choose to prefer gcc over msvc.
The only case where we don't use gcc is aomenc because there is a bug in their gcc code. (bug that affects progress text i think, that @stax76 reported in last december, but I don't know if something has changed yet)

**Comment by Dendraspis** [comment]
@Patman86 
I have a request.  😊
Would it be possible to display the file sizes in MB instead of GB as highest unit?
Somehow I miss to see even small(er) progress steps. 😕

**Comment by Patman86** [comment]
> @Patman86 
> I have a request.  😊
> Would it be possible to display the file sizes in MB instead of GB as highest unit?
> Somehow I miss to see even small(er) progress steps. 😕

Will do that with the next version.

**Comment by Dendraspis** [comment]
Thanks.  😃

**Comment by Patman86** [comment]
Is it enough if I display everything in MB up to 10 GB and then in GB?

**Comment by Dendraspis** [comment]
To be honest I would prefer MB up to 1000 GB.  😁  😥 

Very often I check the est. size to see whether it goes up or down. If I look the third time on it and it's climbing a few MB every second, I know, that I have to adjust my settings, because it will climb even further.
Sometimes it's very useful, sometimes it doesn't matter. But if you like the GB format and/or you wanna save the 2 characters .... it's your build. 😊

**Comment by DJATOM** [comment]
@Dendraspis dMod when? 😄

**Comment by Dendraspis** [comment]
@DJATOM 
First I would wait (and/or ask) for your 3.5 update.  😁

**Comment by DJATOM** [comment]
Probably will wait until April (if Aruna releases it in March).

**Comment by Dendraspis** [comment]
@Patman86 
I have another request.  😁   
Would it be possible to align these colons `:` properly?   😗 

<img src="https://user-images.githubusercontent.com/50659978/109289538-a0650f00-7826-11eb-8928-d56f093eabb8.PNG">

**Comment by Patman86** [comment]
It's possible 😉

**Comment by Dendraspis** [comment]
@Patman86 
Guess what .... once again I have another request.  😁 
Even not absolutely necessary, it would be nice, if the output file could be printed with quotation marks, al least if spaces are included. 
For example: `output file: "A:\XXX_temp\XXX YYY UUU VVV ZZZ VERY long Path to Nowhere_out.hevc"`

<img src="https://user-images.githubusercontent.com/50659978/109305538-2a6ca200-783e-11eb-88ab-0d4a144321ac.PNG">

**Comment by Patman86** [comment]
So roughly? 

![image](https://user-images.githubusercontent.com/54327252/109348027-4b4fea00-7874-11eb-886b-4483ea82c21e.png)

**Comment by Dendraspis** [comment]
BEAUTIFUL!
Thanks!

This is going to look superb within my next new feature. 🤓👍

**Comment by Patman86** [comment]
update online

**Comment by Dendraspis** [comment]
I think to know why they made those colons like they did ... now.  😁 

It seems in the original code there was a specific width hardcoded, that is used unless the left part is wider.  🤔  Wouldn't it be possible to just increase this value by 2 to match the "bias"-line?
Especially without VBV this looks a bit strange.  😞 

<img src="https://user-images.githubusercontent.com/50659978/109363363-b1486b80-788c-11eb-944d-dede307da3be.PNG">

**Comment by Patman86** [comment]
that's not a problem, but as soon as someone uses the option vbv, it looks weird again 😜

**Comment by Dendraspis** [comment]
***Man(n) kann nur einen Tod sterben.***  😁 

Yeah, every solution has it's downside. But I think it might be more useful to keep the values as near as possible to the description due to readability reasons.  🤔

**Comment by JJKylee** [comment]
As a user who rarely uses the VBV/HRD option in x265, I agree with @Dendraspis. 😝😆

**Comment by Dendraspis** [comment]
But the discussion made me do this:  😁  😎 

<img src="https://user-images.githubusercontent.com/50659978/109367324-0ccb2700-7896-11eb-98d1-312fc2a3f2df.PNG">

**Comment by JJKylee** [comment]
Stripes? 😆
It's getting more and more colorful and varietal. 😄
Then maybe you can try making the progress text scroll within the progress bar, @Dendraspis. 🤣

**Comment by Patman86** [comment]
I optimized the info texts and the distances.

**Comment by Dendraspis** [comment]
@Patman86 
What have you changed/optimized?  🤔

**Comment by Dendraspis** [comment]
Hey @Patman86 ,
believe it or not:  I have a request.  😁  This time for x264.  😎 

Would it be possible to the *output source* `text.PadRight(4)`, so `[Info]` will be aligned for all outputs:

```
avs  [Info]: ...
x264 [Info]: ...

             ...instead of...

avs [Info]: ...
x264 [Info]: ...
```

<img src=https://user-images.githubusercontent.com/3157518/109372420-4e3fe000-785e-11eb-9dfe-d903bbe7935f.jpg>

**Comment by Dendraspis** [comment]
> There are now 40 characters between the semicolon and the colon. Text was adjusted so that all options fit in the 40 characters. The info with bias contained 38 characters, there are now 2 characters more 🙄

So meanwhile it seems you can lower it again after changing the descriptions.  😁 

May I suggest changing the two (remaining) `, ` for ` / ` as separator.  This looks a bit weird. 😉 

<img src=https://user-images.githubusercontent.com/3157518/109372387-1c2e7e00-785e-11eb-9dde-46cd709ea15c.jpg>

**Comment by Dendraspis** [comment]
Meanwhile this is the current look with `+2+27` and I can't believe how gigantic the difference is:

<img src="https://user-images.githubusercontent.com/50659978/109396246-fc1bbf00-7930-11eb-877d-bea390591b1c.PNG">

<img src="https://user-images.githubusercontent.com/50659978/109396136-66802f80-7930-11eb-9f74-9efb495ed7fb.PNG">

**Comment by Patman86** [comment]
updated x264 and x265
