### ISSUE TITLE
(Minor bug) Info overlay can't toggle when several Preview windows opened (either with key I or menu item select)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#401]
**Describe the bug**
When several preview windows are open, toggle "Info" overlay does not work. You need to close all previews and leave only one open so you can toggle it.
This is not a new bug, it's been for a while...

**Expected behavior**
Toggle "Info" overlay should work no matter how many open previews there are!

**Comment by stax76** [comment]
This and toggle buttons will be fixed in the next build.
