### ISSUE TITLE
Error GPU encoding Nvidia ffmpeg

### ISSUE THREAD

**Issue by Steinadler177** [staxrip/staxrip#403]
Hello, I'm new to GPU video encoding. I tried to encode an H265 video on ffmpeg with Staxrip, but it doesn't work.
If I use Nvidia H.265 (not ffmpeg) then it works perfectly. 
I tried to adjust Bitrate or other options, the result is same. I have installed ffmpeg on my computer and it's full functional when I run it by Powershell.

Here I provided my error log, please let me know if there is further information needed. Thanks guys!

>------------------------- System Environment -------------------------
>
>StaxRip    : 2.1.3.0
>Windows    : Windows 10 Pro 2004
>Language   : Chinese (Simplified, China)
>CPU        : Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
>GPU        : Intel(R) UHD Graphics 630, NVIDIA GeForce GTX 1650 with Max-Q Design
>Resolution : 3840 x 2160
>DPI        : 144

> ----------------------- Media Info Source File -----------------------
> 
> C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306.mp4
> 
> General
> Complete name            : C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306.mp4
> Format                   : MPEG-4
> Format profile           : Base Media / Version 2
> Codec ID                 : mp42 (isom/mp42)
> File size                : 111 MiB
> Duration                 : 1 min 9 s
> Overall bit rate         : 13.4 Mb/s
> Encoded date             : UTC 2019-02-10 08:43:06
> Tagged date              : UTC 2019-02-10 08:43:06

> com.android.version      : 9
> 
> Video
> ID                       : 1
> Format                   : AVC
> Format/Info              : Advanced Video Codec
> Format profile           : High@L4
> Format settings          : CABAC / 1 Ref Frames
> Format, CABAC            : Yes
> Format, Reference frames : 1 frame
> Format, GOP              : M=1, N=30
> Codec ID                 : avc1
> Codec ID/Info            : Advanced Video Coding
> Duration                 : 1 min 9 s
> Source duration          : 1 min 9 s
> Bit rate                 : 13.1 Mb/s
> Width                    : 1 920 pixels
> Height                   : 1 080 pixels
> Display aspect ratio     : 16:9
> Frame rate mode          : Variable
> Frame rate               : 29.235 FPS
> Minimum frame rate       : 6.897 FPS
> Maximum frame rate       : 43.562 FPS
> Color space              : YUV
> Chroma subsampling       : 4:2:0
> Bit depth                : 8 bits
> Scan type                : Progressive
> Bits/(Pixel*Frame)       : 0.216
> Stream size              : 108 MiB (98%)
> Source stream size       : 108 MiB (98%)
> Title                    : VideoHandle
> Language                 : English
> Encoded date             : UTC 2019-02-10 08:43:06
> Tagged date              : UTC 2019-02-10 08:43:06
> Color range              : Limited
> Color primaries          : BT.709
> Transfer characteristics : BT.709
> Matrix coefficients      : BT.709
> mdhd_Duration            : 69166
> Codec configuration box  : avcC
> 
> Audio
> ID                       : 2
> Format                   : AAC LC
> Format/Info              : Advanced Audio Codec Low Complexity
> Codec ID                 : mp4a-40-2
> Duration                 : 1 min 9 s
> Bit rate mode            : Constant
> Bit rate                 : 192 kb/s
> Channel(s)               : 2 channels
> Channel layout           : L R
> Sampling rate            : 48.0 kHz
> Frame rate               : 46.875 FPS (1024 SPF)
> Compression mode         : Lossy
> Stream size              : 1.58 MiB (1%)
> Title                    : SoundHandle
> Language                 : English
> Encoded date             : UTC 2019-02-10 08:43:06
> Tagged date              : UTC 2019-02-10 08:43:06
> mdhd_Duration            : 69120

> ----------------------------- Demux audio -----------------------------
> 
> MP4Box 0.9.0-DEV-rev0-g81b4481e1-gcc10.0.1 Patman
> 
> "D:\Green Software\StaxRip_x64_2.1.3.0\Apps\Support\MP4Box\MP4Box.exe" -single 2 -out "C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306 ID1 English {SoundHandle}.m4a" C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306.mp4
> 
> Start:    15:08:40
> End:      15:08:40
> Duration: 00:00:00
> 
> General
> Complete name         : C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306 ID1 English {SoundHandle}.m4a
> Format                : MPEG-4
> Format profile        : Base Media
> Codec ID              : isom (isom)
> File size             : 1.60 MiB
> Duration              : 1 min 9 s
> Overall bit rate mode : Variable
> Overall bit rate      : 194 kb/s
> Encoded date          : UTC 2020-12-23 14:08:40
> Tagged date           : UTC 2020-12-23 14:08:40
> 
> Audio
> ID                    : 2
> Format                : AAC LC
> Format/Info           : Advanced Audio Codec Low Complexity
> Format profile        : AAC@L2
> Codec ID              : mp4a-40-2
> Duration              : 1 min 9 s
> Bit rate mode         : Variable
> Bit rate              : 192 kb/s
> Nominal bit rate      : 446 b/s
> Maximum bit rate      : 198 kb/s
> Channel(s)            : 2 channels
> Channel layout        : L R
> Sampling rate         : 48.0 kHz
> Frame rate            : 46.875 FPS (1024 SPF)
> Compression mode      : Lossy
> Stream size           : 1.58 MiB (99%)
> Encoded date          : UTC 2020-12-23 14:08:40
> Tagged date           : UTC 2020-12-23 14:08:40
> 

> --------------------------- AviSynth Script ---------------------------
> 
> LoadPlugin("D:\Green Software\StaxRip_x64_2.1.3.0\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll")
> LSMASHVideoSource("C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306.mp4")
> #AssumeFPS(25)
> 
> ------------------------- Source Script Info -------------------------
> 
> Width     : 1920
> Height    : 1080
> Frames    : 2022
> Time      : 01:09.166
> Framerate : 29.234099 (87790/3003)
> Format    : YUV420P8
> 
> ------------------------- Target Script Info -------------------------
> 
> Width     : 1920
> Height    : 1080
> Frames    : 2022
> Time      : 01:09.166
> Framerate : 29.234099 (87790/3003)
> Format    : YUV420P8
> 
> ---------------------- Media Info Audio Source 2 ----------------------
> 
> General
> Complete name         : C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306 ID1 English {SoundHandle}.m4a
> Format                : MPEG-4
> Format profile        : Base Media
> Codec ID              : isom (isom)
> File size             : 1.60 MiB
> Duration              : 1 min 9 s
> Overall bit rate mode : Variable
> Overall bit rate      : 194 kb/s
> Encoded date          : UTC 2020-12-23 14:08:40
> Tagged date           : UTC 2020-12-23 14:08:40
> 
> Audio
> ID                    : 2
> Format                : AAC LC
> Format/Info           : Advanced Audio Codec Low Complexity
> Format profile        : AAC@L2
> Codec ID              : mp4a-40-2
> Duration              : 1 min 9 s
> Bit rate mode         : Variable
> Bit rate              : 192 kb/s
> Nominal bit rate      : 446 b/s
> Maximum bit rate      : 198 kb/s
> Channel(s)            : 2 channels
> Channel layout        : L R
> Sampling rate         : 48.0 kHz
> Frame rate            : 46.875 FPS (1024 SPF)
> Compression mode      : Lossy
> Stream size           : 1.58 MiB (99%)
> Encoded date          : UTC 2020-12-23 14:08:40
> Tagged date           : UTC 2020-12-23 14:08:40
> 
> ----------------------------- Find Gain 2 -----------------------------
> 
> ffmpeg N-97868-gaa6f38c298-g38490cbeb3-gcc10.1.0 Patman
> 
> "D:\Green Software\StaxRip_x64_2.1.3.0\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306 ID1 English {SoundHandle}.m4a" -sn -vn -hide_banner -af volumedetect -f null NUL
> 
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306 ID1 English {SoundHandle}.m4a':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 1
>     compatible_brands: isom
>     creation_time   : 2020-12-23T14:08:40.000000Z
>   Duration: 00:01:09.12, start: 0.000000, bitrate: 193 kb/s
>     Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
>     Metadata:
>       creation_time   : 2020-12-23T14:08:40.000000Z
>       handler_name    : GPAC ISO Audio Handler
> Stream mapping:
>   Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
> Press [q] to stop, [?] for help
> Output #0, null, to 'NUL':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 1
>     compatible_brands: isom
>     encoder         : Lavf58.43.100
>     Stream #0:0(und): Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s (default)
>     Metadata:
>       creation_time   : 2020-12-23T14:08:40.000000Z
>       handler_name    : GPAC ISO Audio Handler
>       encoder         : Lavc58.86.101 pcm_s16le
> video:0kB audio:12960kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> [Parsed_volumedetect_0 @ 00000155de4cbb80] n_samples: 6635520
> [Parsed_volumedetect_0 @ 00000155de4cbb80] mean_volume: -26.6 dB
> [Parsed_volumedetect_0 @ 00000155de4cbb80] max_volume: 0.0 dB
> [Parsed_volumedetect_0 @ 00000155de4cbb80] histogram_0db: 48
> [Parsed_volumedetect_0 @ 00000155de4cbb80] histogram_1db: 101
> [Parsed_volumedetect_0 @ 00000155de4cbb80] histogram_2db: 202
> [Parsed_volumedetect_0 @ 00000155de4cbb80] histogram_3db: 571
> [Parsed_volumedetect_0 @ 00000155de4cbb80] histogram_4db: 1091
> [Parsed_volumedetect_0 @ 00000155de4cbb80] histogram_5db: 1815
> [Parsed_volumedetect_0 @ 00000155de4cbb80] histogram_6db: 2900
> 
> Start:    15:09:49
> End:      15:09:50
> Duration: 00:00:00
> 
> ------------- Error Video encoding Nvidia | Nvidia H.265 -------------
> 
> Video encoding Nvidia | Nvidia H.265 returned error exit code: 1 (0x1)
> 
> It's unclear what the exit code means, in case it's a Windows system error then it possibly means:
> 
> Incorrect function.
> 
> 
> ---------------- Video encoding Nvidia | Nvidia H.265 ----------------
> 
> ffmpeg N-97868-gaa6f38c298-g38490cbeb3-gcc10.1.0 Patman
> 
> "D:\Green Software\StaxRip_x64_2.1.3.0\Apps\Encoders\ffmpeg\ffmpeg.exe" -i C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306.avs -c:v hevc_nvenc -pass 1 -b:v 607617k -f rawvideo -an -y -hide_banner NUL
> 
> Input #0, avisynth, from 'C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306.avs':
>   Duration: 00:01:09.17, start: 0.000000, bitrate: 0 kb/s
>     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 29.23 fps, 29.23 tbr, 29.23 tbn, 29.23 tbc
> Stream mapping:
>   Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_nvenc))
> Press [q] to stop, [?] for help
> [hevc_nvenc @ 000001b8f4efc180] InitializeEncoder failed: invalid param (8): 
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> Conversion failed!
> 
> ---------------- Video encoding Nvidia | Nvidia H.265 ----------------
> 
> ffmpeg N-97868-gaa6f38c298-g38490cbeb3-gcc10.1.0 Patman
> 
> "D:\Green Software\StaxRip_x64_2.1.3.0\Apps\Encoders\ffmpeg\ffmpeg.exe" -i C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306.avs -c:v hevc_nvenc -pass 1 -b:v 607617k -f rawvideo -an -y -hide_banner NUL
> 
> Input #0, avisynth, from 'C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306.avs':
>   Duration: 00:01:09.17, start: 0.000000, bitrate: 0 kb/s
>     Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 29.23 fps, 29.23 tbr, 29.23 tbn, 29.23 tbc
> Stream mapping:
>   Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_nvenc))
> Press [q] to stop, [?] for help
> [hevc_nvenc @ 000001b8f4efc180] InitializeEncoder failed: invalid param (8): 
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> Conversion failed!
> 
> Start:    15:09:49
> End:      15:09:50
> Duration: 00:00:00
> 
> -------------------------- Audio encoding 2 --------------------------
> 
> ffmpeg N-97868-gaa6f38c298-g38490cbeb3-gcc10.1.0 Patman
> 
> "D:\Green Software\StaxRip_x64_2.1.3.0\Apps\Encoders\ffmpeg\ffmpeg.exe" -i "C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306 ID1 English {SoundHandle}.m4a" -c:a libopus -vbr on -b:a 250k -ac 2 -y -hide_banner "C:\Users\lvtin\Desktop\新建文件夹\VID_20190210_164306_temp\VID_20190210_164306 ID1 English {SoundHandle}_a2.opus"
> 
> Start:    15:09:50
> End:      15:09:50
> Duration: 00:00:00

**Comment by Dendraspis** [comment]
> If I use Nvidia H.265 (not ffmpeg) then it works perfectly.

So why not using the better and native encoder?  🤔

**Comment by Dendraspis** [comment]
> [hevc_nvenc @ 000001b8f4efc180] InitializeEncoder failed: invalid param (8):
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

I guess this is because of the very high target bitrate: `-b:v 607617k`
600MBit/s seems to be a little bit too much for me.  😉

**Comment by Steinadler177** [comment]
> > If I use Nvidia H.265 (not ffmpeg) then it works perfectly.
> 
> So why not using the better and native encoder? 🤔

I'm not sure if native encoder is better in quality than ffmpeg.

I also tried to adjusted the bitrate for common setup like 20MBit/s. But the same issue appeared. I'm showing this log since it's "default" configuration.

**Comment by Steinadler177** [comment]
> If `NUL` is part of the command line, this could/should be the problem. So the destination filename seems to be missing. 🤔

Ok I removed the Chinese folder name in the target direction, then it worked.

Interesting, I can have Chinese character in resource path or target path when using native encoder, so I never thought that can be a problem. So many thanks to you!

**Comment by Dendraspis** [comment]
> I'm not sure if native encoder is better in quality than ffmpeg.

It is ... for sure!

> I also tried to adjusted the bitrate for common setup like 20MBit/s. But the same issue appeared. I'm showing this log since it's "default" configuration.

Yeah, it seems to be the empty destination. :thinking:

**Comment by stax76** [comment]
I tried the Asian characters with avisynth and ffmpeg x264, and it worked fine. I don't have nvenc hardware unfortunately, PC is too small to fit such a card...

If you have Win 10 I recommend going to the administrative language settings and change the default code page to UTF8. This will give full Unicode support to AviSynth and Windows Terminal... 🚀

NUL is probably there because two pass mode was used but that is not really supported by nvenc. StaxRip should hide two pass mode for nvenc. I've looked at the code, it seems it's too difficult to fix.

**Comment by Steinadler177** [comment]
> I tried the Asian characters with avisynth and ffmpeg x264, and it worked fine. I don't have nvenc hardware unfortunately, PC is too small to fit such a card...
> 
> If you have Win 10 I recommend going to the administrative language settings and change the default code page to UTF8. This will give full Unicode support to AviSynth and Windows Terminal... 🚀
> 
> NUL is probably there because two pass mode was used but that is not really supported by nvenc. StaxRip should hide two pass mode for nvenc. I've looked at the code, it seems it's too difficult to fix.

I also tried with Asian characters with ffmpeg x264 and it's fine, it only happens with nvenc. But I think you are right that I should not using two-pass for nvenc.

UTF8... That's always an issue for Simplified Chinese users cause the system would default in GBK.  I don't know too much about this part but it's usually better in Win10 than the older windows system. Mac is another issue and I only use English in Linux.
