### ISSUE TITLE
Cannot convert with NVIDIA H.265 (feature not implemented)

### ISSUE THREAD

**Issue by asheroto** [staxrip/staxrip#404]
**Describe the bug**
When trying to convert a video file using the NVIDIA H.265 method, it fails, saying "NVENC Feature has not been implemented yet." However, converting using ffmpeg NVIDIA H.265 works fine (even through StaxRip).

**Expected behavior**
Successful conversion

**How to reproduce the issue**
Convert video using NVIDIA H.265

**Provide information**
Using StaxRip 2.1.5.3 beta
[log.txt](https://github.com/staxrip/staxrip/files/5739571/log.txt)

Graphics Adapter:
NVIDIA Tesla V100

**Comment by Dendraspis** [comment]
It should be necessary to view the whole log file, not only some stripped parts. Some of the interesting parts are missing, especially your NVenc settings.

**Comment by stax76** [comment]
I would guess it's a tool issue:

https://github.com/rigaya/NVEnc/issues
