### ISSUE TITLE
Merry Christmas to you all

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#405]
@stax76 @Dendraspis @Patman86 and all contributors and users, Merry Christmas!

**Comment by Patman86** [comment]
So to you too!  I also wish you a Merry Christmas.🎅🎄

**Comment by stax76** [comment]
Merry Christmas guys!

mpv.net users please update, it's having a new [Santa hat logo](https://github.com/stax76/mpv.net/blob/master/img/mpvnet-santa.png). 🎅😀

**Comment by Dendraspis** [comment]
***Merry Christmas***

![Xmas](https://user-images.githubusercontent.com/50659978/103103409-2a270f00-4621-11eb-8f82-02603232e487.jpg)

**Comment by 44vince44** [comment]
> mpv.net users please update (Beta), it's having a new [Santa hat logo](https://github.com/stax76/mpv.net/blob/master/img/mpvnet-santa.png). 🎅😀

@stax76 I updated it yesterday, it looks very nice 😄 Thanks !!

**Comment by gkalemis** [comment]
Merry COVID-free Christmas.

Thanks @stax76
