### ISSUE TITLE
New beta please

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#407]
@stax,76 @Dendraspis can we please have a new beta, there have been many commits since last beta, small things that need to be checked.
Thanks ;-)

**Comment by Dendraspis** [comment]
That's something only @stax76 can do - but I'm pretty sure he will do it this year. :smile:

**Comment by 44vince44** [comment]
Yes I hope he'll give it to us as a present for the New Year ;-)

**Comment by stax76** [comment]
Here you go! 😉

https://github.com/staxrip/staxrip/blob/master/Changelog.md

https://staxrip.readthedocs.io/introduction.html#beta

**Comment by 44vince44** [comment]
now that was fast ! thanks !!!!!!

**Comment by Dendraspis** [comment]
...just because he forgot the red bow! :joy:

**Comment by 44vince44** [comment]
Okay, I'll write down here the thing that could be done in order to make this a possible release, because I'm confident things are good in this beta. Of course more will come with the progress of the tests:

These are obvious, probably forgotten by Stax76
- Audio qaac\QTFiles64 must be removed for legal stuff
- Avisynth symlinks have been converted to real dlls. Please delete links from folders before creating archive.
  Encoders/FFMpeg, x264, x265 (delete as well the "unpacked x265.exe" that was left behind

Now I'm doing some serious testing (more coming soon)

**Comment by Dendraspis** [comment]
> So far, so good, trying many possible encoding scenarios, only with x265.

Don't forget the 3-pass mode.  :grin:

But you're right - it's time for a new stable. :+1:

**Comment by stax76** [comment]
@44vince44 

I've removed the qt files, it's handled now by the apps dialog.

mpv.net is updated.

[The release script](https://github.com/staxrip/staxrip/blob/master/Release.ps1#L96) deletes the symlinks, so when you unpack staxrip there should not be any symlinks.

Probably you moved the staxrip location after you have created the links. Copy and move operations cause Windows to replace symlinks with real files.

StaxRip will detect this though and ask to re-create the symlink, it's probably fine.

**Comment by 44vince44** [comment]
@stax76 what triggers the symlink creation ?

I have manually deleted the copies of Avisynth.dll that were put in the folders FFMPEG, x264, x265, but when I run staxrip again, I don't get the dialog to create symlinks. How can I force the dialog to appear so i can create new symlinks ?

**Comment by 44vince44** [comment]
@Dendraspis I have something very unfortunate for you :-(    -sorry 😢 

This has not been adressed in aomenc:

> **V- BUG: Rate modes Q and CQ must remove the target bitrate and grey out the Size and target bitrate in the interface**
> ===> When Rate modes Q and CQ are selected, **The --target-bitrate=xxx** switch MUST BE removed, and the interface items "Size" and "Video Bitrate" must disappear from the interface (as they do in other encoders when selecting qualiby based modes)

Well at least remove the --target-bitrate=xxx switch when q and cq modes selected

**Comment by stax76** [comment]
@44vince44 

There was a bug in the release script which is fixed in the next build.

The current build should detect any problem with symlinks and automatically re-create the links, but this happens only when symlinks are actually needed, that is using avisynth portable mode and ffmpeg video encoder.

**Comment by 44vince44** [comment]
yes indeed ! using ffmpeg as encoder immediately asked for creating symlinks! Thanks!

**Comment by Dendraspis** [comment]
@stax76 
It would be nice if you could publish v2.1.7.6 Beta with its improvements in the next days.
According to https://github.com/staxrip/staxrip/issues/470#issuecomment-766871520 please make sure, that you include the latest x265 version, ***which was silently rebuilt 2 days ago after your changelog entry***:
https://github.com/DJATOM/x265-aMod/releases/tag/3.4%2B65

...and maybe his new x264 build, too, that also includes a parameter for the used lib (`--synth-lib`):
https://github.com/DJATOM/x264-aMod/releases

**Comment by 44vince44** [comment]
and maybe use the --synth-lib instead of symlink in x264 folder.

**Comment by stax76** [comment]
> According to #470 (comment) please make sure, that you include the latest x265 version, which was silently rebuilt 2 days ago after your changelog entry:

OK, I've updated it.

> ...and maybe his new x264 build, too, that also includes a parameter for the used lib (--synth-lib)

Oh, that is good news, making ffmpeg the last tool that needs a soft link.
