### ISSUE TITLE
GitHub Discussion feature ready for use

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#408]
GitHub has a new Discussion feature, it's ready for use.

Please let us know what you think about it.

Should we use it for questions and topics that are not a bug or feature request?

https://github.com/staxrip/staxrip/discussions

**Comment by JJKylee** [comment]
Good. Seems like it can be a good replacement/supplement for current forum threads (Doom9, VideoHelp, etc.).
IMHO, the forum format doesn't do well when it comes to discussing a specific topic.

**Comment by Dendraspis** [comment]
Personally I don't like ***Discussions*** at the moment. Via browser you get and see notifications for discussions, but you can't see nor access them via the GitHub App. So the usage is limited by GitHub itself. 

Starting discussions is okay, but we should not expect many participations.

**Comment by JJKylee** [comment]
@Dendraspis
I didn't know about it cuz I almost always access GitHub from PC. Hope the GitHub app is updated soon to be more functional. 😃

**Comment by JJKylee** [comment]
> Via browser you get and see notifications for discussions, but you can't see nor access them via the GitHub App. So the usage is limited by GitHub itself.

The GitHub app on iOS is updated today to support Discussions. 😃

**Comment by Dendraspis** [comment]
Since discussions are not in beta stage anymore and we already have a few discussions, .....
