### ISSUE TITLE
In search of testers for a x265 build with direct AviSynth and VapourSynth support

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#409]
Please test and report.

https://github.com/msg7086/x265-Yuuki-Asuna/issues/11#issuecomment-751929687

**Comment by 44vince44** [comment]
I could never use or understand Vapoursynth (and I swore I'll never use it 😞 )
But I could do tests for AVS.
For VS it means having time to understand it. Maybe after a few days, I'll have time...

**Comment by Dendraspis** [comment]
What's special about *Yuuki Asuna Mod* ?  🤔

**Comment by msg7086** [comment]
I ported lots of patches from x264 to x265, so you get ffmpeg, avisynth input, and mp4 output. Now we have vapoursynth input support from DJATOM

**Comment by stax76** [comment]
It's now in the latest Beta and credits everybody involved. Next beta will use direct avs/vpy input by default.

Issues we hope can be addressed in the future:

- UTF-8 manifest like x264, this will give full Unicode support on Win 10
- Long path support like x264
- AviSynth custom DLL path, goal is to eliminate the need for symlinks

I can help if there is a Visual Studio project.

**Comment by msg7086** [comment]
I uploaded some code to support specifying DLL path in file name, like this:

```
x265 [d:\avs361\AviSynth.dll]://test.avs
x265 [d:\vs52\vsscript]://test.vpy
```

Does that meet your demands?

**Comment by stax76** [comment]
Probably not, or I don't understand it. In nvenc and avs2pipemod it's straightforward:

nvenc/qsvenc:

--avsdll <path>

avs2pipemod:

-dll=<path>

In mpv.net I've not yet implemented it as command line option but only as env var so far, the avs/vpy wrapper frameserver.dll of staxrip uses this env var too, name is AviSynthDLL, that would be sufficient, but command line option is generally better.

https://github.com/rigaya/NVEnc

https://github.com/chikuzen/avs2pipemod

**Comment by msg7086** [comment]
OK, never mind then.

**Comment by 44vince44** [comment]
I'll begin shortly to test.
I guess that would mean testing BOTH Yuuki-Asuna and Patman86 builds ?

**Comment by Dendraspis** [comment]
@44vince44 
> I guess that would mean testing BOTH Yuuki-Asuna and Patman86 builds ?

The latest beta uses `x265 M-3.4+28 gcc10.2.0 Yuuki-Asuna/msg7086/DJATOM/Patman` so I would guess everything is baked together.  😁

**Comment by 44vince44** [comment]
@Dendraspis @stax76 

> so I would guess everything is baked together. 😁

Yes it seems that way! I was surprised the build I downloaded fro Yuuki-Asuna displays the estimated file size, which was a feature only available in Patman's builds.
Now that makes perfect sense, and I salute all people involved in that "all baking together" decision.

Now, I am happy to report since I made 2 tests with the following builds:

@Patman86 : x265M-3.4+29-4e3bb4354-x64-gcc10.2.0  this passed the vpy direct (no pipe) test describes two posts above
@msg7086 : x265-Asuna-3.4+13-g729a838d3+38 passed the vpy test as well.
@DJATOM wishing you a full recovery!

**Comment by Patman86** [comment]
The builds of DJATOM and Msg7086 have supported the display of the estimated file size for a while. I've been using the Yuuki-(Asuna) build for a long time, but I was too packed.  So I started making my own builds.

**Comment by 44vince44** [comment]
@Patman86 
Ah thanks for the explanation. Then I guess i'll still be testing both for a short while, before getting back to my old habits ( = your builds) 😄

**Comment by stax76** [comment]
> @DJATOM wishing you a full recovery!

Yes, wishing 100 % recovery. 💯

**Comment by 44vince44** [comment]
OK I made several tests, they ALL PASS, but there is one case that pass ok BUT gave a log file with a repeating message for every frame:

`Avisynth Compat: requested frame 648 not prefetched, using slow method`

@msg7086, @stax76 why do we get Avisynth Compat things here ?

The full log is here:
[2021-01-01 - 20.59.51 - LG OLED Art HDR UHD 4K Demo_staxrip.log.zip](https://github.com/staxrip/staxrip/files/5759321/2021-01-01.-.20.59.51.-.LG.OLED.Art.HDR.UHD.4K.Demo_staxrip.log.zip)

Note that this case is quite complex (color conversion, frame rate conversion, resize, bit conversion, color processing HDR to SDR, resizing...)
The line repeats for every frame, so if the video is very long  you'll end up with huge log file.

**Comment by Patman86** [comment]
Hi vince44,
are you sure this is a problem with x265?  You use a lot of filters/plug-ins, not that it is one of the dual plug-ins 😁

**Comment by msg7086** [comment]
> I was surprised the build I downloaded from Yuuki-Asuna displays the estimated file size, which was a feature only available in Patman's builds.

If you ever wonder why, that's because the patch is ported by me from x264 in the year 2015. Yuuki Asuna mod was probably the first mod to support that feature.

**Comment by 44vince44** [comment]
@Patman86 yes it does indeed do the same thing with x264. So it's a plugin message. I believe it's the HSRtoSDR plugin (the only one which is dual)

I believe it is safe to say the vpy no-pipe support seems OK !

@msg7086 Ah! So 1000 thanks for having had that very clever idea !!!!

**Comment by Patman86** [comment]
> @Patman86 yes it does indeed do the same thing with x264. So it's a plugin message. I believe it's the HSRtoSDR plugin (the only one which is dual)

Be so kind and test the procedure with vspipe instead of direct input.  If the message still occurs, maybe narrow it down to the filter.

**Comment by 44vince44** [comment]
I did, our messages got crossed (see above): with vspipe, the same messages appear. So it's the plugin's fault.

**Comment by Patman86** [comment]
> I did, our messages got crossed (see above): with vspipe, the same messages appear. So it's the plugin's fault.

Which version of HDRtoSDR do you use?

**Comment by 44vince44** [comment]
We're doing the same thing at the same time 🤣 
The same idea has crossed my mind, I have removed HDRtoSDR (it's version 1.14) and I still get the same error. By isolating properly the filters, I could reveal the one causing the message. here it is:
clip = core.avs.z_ConvertFormat(clip, pixel_type='YV12',colorspace_op='709:2020:2020:l=>2020ncl:2020:2020:l', dither_type='None')

**Comment by Patman86** [comment]
> We're doing the same thing at the same time 🤣 
> The same idea has crossed my mind, I have removed HDRtoSDR (it's version 1.14) and I still get the same error. By isolating properly the filters, I could reveal the one causing the message. here it is:
> clip = core.avs.z_ConvertFormat(clip, pixel_type='YV12',colorspace_op='709:2020:2020:l=>2020ncl:2020:2020:l', dither_type='None')
> 

Congrats, you found a bug 😂 these option is not supported by Vapoursynth for now (no filter available)

**Comment by 44vince44** [comment]
🤣 🤣 🤣 I'm speechless!
See, that's one of the reasons I prefer AVS...

**Comment by 44vince44** [comment]
We can close this, right ?

**Comment by Dendraspis** [comment]
Yes, we can ... I think 😁

**Comment by msg7086** [comment]
I added a quick fix to the VPY support under Linux. If your builds will ever get a chance to run under Linux/macOS you should apply that patch. If it'll be Windows only then you can leave it there.
