### ISSUE TITLE
aomenc - Disable "target bitrate" when using "CQ" or "Q" Rate Mode

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#410]
**Describe the bug**
Staxrip v2.1.5.4 Beta
When setting "Rate Mode" to "Q" or "CQ", "--target-bitrate" still remains in the parameter list

**Expected behavior**
"--target-bitrate" should be removed

**Comment by stax76** [comment]
Changelog

https://github.com/staxrip/staxrip/blob/master/Changelog.md


Download

https://staxrip.readthedocs.io/introduction.html#beta
