### ISSUE TITLE
aomenc - Move "CQ Level" option to "Rate Control 1"

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#411]
StaxRip v2.1.5.4 Beta
Since "CQ Level" is only used when "Rate Mode" is set to "Q" or "CQ", it should be placed directly below "Rate Mode".

**Comment by Dendraspis** [comment]
@Neltulz 
Sorry, due to lack of contributers interested in aomenc we stick to the CLI help order for better and faster maintenance if something should change.
But yes, it should be there.  😞 

@stax76 
Regarding the labels:  do you have a different point of view meanwhile?

**Comment by stax76** [comment]
> Regarding the labels: do you have a different point of view meanwhile?

Which labels do you mean?

**Comment by Dendraspis** [comment]
@stax76 
Especially *Priority Medium* . :grin:
Just wanted to be sure we are still looking in the same direction. :wink:

**Comment by 44vince44** [comment]
@Dendraspis 👍 🤣 
Indeed this is not a blocking issue, it seems very medium to me... imho

**Comment by stax76** [comment]
I choose medium because it's probably very easy to do. 😉

**Comment by Dendraspis** [comment]
@stax76 
It is, indeed. 

:thinking: Okay, because the `--cq-level` is the only param that it so off and aomenc won't be touched for the next time, let's do it commented.

I'll move it later while fixing some other stuff.

**Comment by Dendraspis** [comment]
@Neltulz 
It's moved.  You will see it in the next beta.  😄
