### ISSUE TITLE
please release 2.1.5.6 because there is a bug fix halfway done in 2.1.5.5

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#413]
Aomenc is really a pain in the ***. Please let me do a final checking with latest @Dendraspis commit. This one impacts the command line and is important. So I need 2.1.5.6 !!

I really want to finish this and to ensure that @Dendraspis will be relieved for some time with aomenc suff.

**Comment by stax76** [comment]
I've uploaded just the staxrip binary.

**Comment by 44vince44** [comment]
Thanks I'll work on it now.
In the meantime, I checked that the items that  must be removed from the release are indeed removed:
-the apple quicktime files
-the symlinks
All removed OK

**Comment by Dendraspis** [comment]
> Aomenc is really a pain in the ***.

More than that - by far! :grin:
But these point are my mistakes - I should have done it more accurately. :disappointed:

> I really want to finish this and to ensure that @Dendraspis will be relieved for some time with aomenc suff.

Indeed, let's wait till aomenc introduces 3-pass mode.  :grin:

@stax76 
Be aware of the version date in the changelog that I already set to 2021.

**Comment by 44vince44** [comment]
> Indeed, let's wait till aomenc introduces 3-pass mode. 😁

NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
