### ISSUE TITLE
Happy New Year

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#414]
For some around the Globe, we're already 2021!

Happy New Year for all!

@stax76 , @Dendraspis, @Patman86 , and all Contributors and Users!

**Comment by Dendraspis** [comment]
🚀  ***HAPPY NEW YEAR*** 🚀 

Because *New Year* sucks this year, you get an older photo this time:

![NEWYEAR3](https://user-images.githubusercontent.com/50659978/103418986-5991ca80-4b91-11eb-986c-cc26c7a01d15.jpg)

**Comment by stax76** [comment]
Happy new year everybody, especially to friends of video encoding and people affected by Covid-19.
