### ISSUE TITLE
qaac requires this library for AAC encoding

### ISSUE THREAD

**Issue by gkalemis** [staxrip/staxrip#415]
**Describe the bug**
The folder with the CoreAudioToolbox.dll is missing

**Expected behavior**
It works properly in beta version 2.1.5.4

**How to reproduce the issue**
Try to encode anything using AAC

**Provide information**
Version beta 2.1.5.5

**Comment by Dendraspis** [comment]
The quicktime files were removed due to license reasons.
You have to use the ones from Apple directly - or take them from the last beta. :smile:

**Comment by gkalemis** [comment]
Good to know, thank you. After putting the files in the position were they where from the previous beta version and pointing the path to their position, I get a message that the .dll file cannot be inside the settings folder. Is there  a workaround or should I put them outside as I did?

**Comment by stax76** [comment]
Save it outside.

**Comment by gkalemis** [comment]
Ok then, outside it is. Thanks.

**Comment by stax76** [comment]
I've improved this message now:

```
Custom paths within the startup folder are not permitted because it would prevent a simple update process.

Please put the file somewhere else outside the startup folder.
```
