### ISSUE TITLE
progress bar support for ffmpeg audio processing

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#42]
Maybe progress bar support for ffmpeg audio processing can be added.

**Comment by Revan654** [comment]
Not sure how audio gets feed back (Never paid attention).

with ffmpeg Video it's much simpler to get the % and feed it back:

This is for Video, with some tweaking it might work for audio as well.
Only Need the Base(This was written Ages ago for Gif Encoder that was Created in VB).

Also use Background worker for the call back through DoWorkEventArgs.

Also might need to add in Thread.Sleep(500) as well.

ProcRate = FrameRate (Pull if from ffprobe or MediaInfo)
ProcDuration = Length (Pull if from ffprobe or MediaInfo)

 Results = ProcRate * ProcDuration

` Do
            Export = Proc.StandardError.ReadLineAsync().ConfigureAwait(false)

            Try
                If Export.Contains("frame=") Then
                    CurrentFrame = Mid(Export, 7, 6)
                    CurrentFrameInt = CurrentFrame.ToInt()
                    EncodingStatus.Text = "Encoding Status: " & CurrentFrameInt
                End If

                EncodingPB.Maximum = Results
                EncodingPB.Value = CurrentFrame

            Catch ex As Exception
            End Try


        Loop Until Proc.HasExited Or Export = Nothing

        If EncodingPB.Value <> EncodingPB.Maximum Then
            EncodingPB.Value = EncodingPB.Maximum
        End If`

**Comment by Patman86** [comment]
I've found sometthing in VB-Paradise forum, it helps maybe:

[https://www.vb-paradise.de/index.php/Thread/93305-FFMPEG-Fortschritt-anzeigen-lassen-Problem/](url)

**Comment by stax76** [comment]
I've made commit to support it.

**Comment by Patman86** [comment]
The process displays the current file size during audio encoding, not in percent.

**Comment by stax76** [comment]
The progress output is always the unchanged output of the application.
