### ISSUE TITLE
Can the HDR Ingest option be removed?

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#421]
This feature was implemented by Revan who is inactive.

I don't really understand much of the HDR topic.

What the code does is following, for every output file staxrip creates, the HDR ingest function creates an additional second output file that adds several hard coded HDR values via mkvmerge.

```VB.NET
    Shared Sub MetadataHDR(inputFile As String, proj As Project)
        If Not File.Exists(inputFile) Then
            Exit Sub
        End If

        Dim hdr = MediaInfo.GetVideo(inputFile, "transfer_characteristics")

        If hdr = "PQ" Then
            Using Proc As New Proc
                Proc.Header = "Adding HDR Metadata"
                Proc.SkipStrings = {"Progress", "The file", "The cue", "Multiplexing"}
                Proc.Encoding = Encoding.UTF8
                Proc.Package = Package.mkvmerge
                Proc.Arguments = "-o " + (inputFile + "_HDR10.mkv").Escape + " --colour-matrix 0:9 " +
                    "--colour-range 0:1 --colour-transfer-characteristics 0:16 --colour-primaries 0:9 " +
                    "--max-content-light 0:1000 --max-frame-light 0:300 --max-luminance 0:1000 " +
                    "--min-luminance 0:0.01 --chromaticity-coordinates 0:0.68,0.32,0.265,0.690,0.15,0.06" +
                    "--white-colour-coordinates 0:0.3127,0.3290 " + inputFile.Escape
                Proc.Start()
            End Using
        ElseIf hdr = "HLG" Then
            Using Proc As New Proc
                Proc.Header = "Adding HDR Metadata"
                Proc.SkipStrings = {"Progress", "The file", "The cue", "Multiplexing"}
                Proc.Encoding = Encoding.UTF8
                Proc.Package = Package.mkvmerge
                Proc.Arguments = "-o " + (inputFile + "_HLG.mkv").Escape + " --colour-matrix 0:9 " +
                    "--colour-range 0:1 --colour-transfer-characteristics 0:18 --colour-primaries 0:9 " +
                    "--max-content-light 0:1000 --max-frame-light 0:300 --max-luminance 0:1000 " +
                    "--min-luminance 0:0.01 --chromaticity-coordinates 0:0.68,0.32,0.265,0.690,0.15,0.06 " +
                    "--white-colour-coordinates 0:0.3127,0.3290 " + (inputFile).Escape
                Proc.Start()
            End Using
        Else
            MsgInfo("No HDR Metadata Key was Found")
        End If
    End Sub
```

**Comment by Dendraspis** [comment]
@stax76 
I would say ***YES***, if you want to shrink the code.  😊   But nothing wrong keeping it yet.

**Comment by stax76** [comment]
Maybe it would be better to write these properties in the regular muxing process instead of doing an additional muxing process with an additional output file.

Do think the options are correct? We could ask at doom9.

**Comment by Dendraspis** [comment]
My problem with this is, that they are set with mkvmerge, the container. So the video file may have incorrect/different settings. I have not investigated this issue, because I felt inconfident with this situation.

Without this function StaxRip is able to convert HDR10 and HDR10+ videos directly without issues. For HLG only one parameter setting should be changed in x265 to make it work, so this is also no problem.

**Comment by stax76** [comment]
I can try to contact the author Revan, he has admin privileges for this repo, but he is inactive for a long time.

**Comment by Dendraspis** [comment]
Whatever you want.  😎

As long as x265 is able to do everything it should do, I don't care about code relicts. 😁

**Comment by Patman86** [comment]
@Dendraspis 
I agree with you. All of this can be stored with x265, there is no need for a separate process. I think can be removed.

**Comment by stax76** [comment]
I've removed it from the options. It's still available in the menu:

Apps > Media Info > Ingest HDR

But maybe it should be moved to:

Apps > Other > Ingest HDR

**Comment by stax76** [comment]
I've moved this to:

Tools > Advanced > Ingest HDR

**Comment by stax76** [comment]
@Dendraspis 

It's HDR related, so your decision.

**Comment by Dendraspis** [comment]
> Tools > Advanced > Ingest HDR

Sounds like a good decision.  😊
