### ISSUE TITLE
Editing "Command Line" audio profile crashes the app

### ISSUE THREAD

**Issue by DavidRodriguezSoaresCUI** [staxrip/staxrip#423]
**Describe the bug**
I switched from 2.1.3.0 to 2.1.6.0 today and when I try to edit an audio settings profile like "Vorbis ~252 Kbps", the editing window shows up as expected, but when I try to edit the "Command Line" profile or any custom profile based on it, the app crashes.

Note : It might be the case that the profiles on my computer got corrupted (unlikely) or that something changed between 2.1.3.0 and 2.1.6.0 to make them incompatible.

**Expected behavior**
An editing window should pop up. Instead StaxRip crashes.

**How to reproduce the issue**

1.Run StaxRip 2.1.6.0
2.On the bottom right, select "Command Line" for audio settings profile
3.Click on the "edit" button immediately right to it
4.StaxRip crashes

**staxrip.log**

------------------------- System Environment -------------------------

StaxRip    : 2.1.6.0
Windows    : Windows 10 Home 2009
Language   : French (Switzerland)
CPU        : AMD Ryzen 7 1700 Eight-Core Processor
GPU        : NVIDIA GeForce GTX 970
Resolution : 1920 x 1080
DPI        : 96

------------------------------ Exception ------------------------------

System.ArgumentNullException: La référence de chaîne n'est pas définie à une instance d'une chaîne.
Nom du paramètre : s
   à System.Text.Encoding.GetBytes(String s)
   à StaxRip.CRC32.GetChecksum(String str) dans D:\Projekte\VB\staxrip\General\General.vb:ligne 1525
   à StaxRip.AudioProfile.GetTrackID() dans D:\Projekte\VB\staxrip\General\AudioProfile.vb:ligne 283
   à StaxRip.AudioProfile.GetOutputFile() dans D:\Projekte\VB\staxrip\General\AudioProfile.vb:ligne 301
   à StaxRip.AudioProfile.ExpandMacros(String value, Boolean silent) dans D:\Projekte\VB\staxrip\General\AudioProfile.vb:ligne 348
   à StaxRip.AudioProfile.ExpandMacros(String value) dans D:\Projekte\VB\staxrip\General\AudioProfile.vb:ligne 341
   à StaxRip.MacroEditorControl.UpdatePreview() dans D:\Projekte\VB\staxrip\Controls\MacroEditorControl.vb:ligne 310
   à StaxRip.CommandLineAudioEncoderForm.tbBitrate_TextChanged() dans D:\Projekte\VB\staxrip\Forms\CommandLineAudioEncoderForm.vb:ligne 540
   à StaxRip.CommandLineAudioEncoderForm._Lambda$__R105-5(Object a0, EventArgs a1)
   à System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   à System.Windows.Forms.Control.set_Text(String value)
   à System.Windows.Forms.TextBoxBase.set_Text(String value)
   à System.Windows.Forms.TextBox.set_Text(String value)
   à StaxRip.CommandLineAudioEncoderForm..ctor(BatchAudioProfile profile) dans D:\Projekte\VB\staxrip\Forms\CommandLineAudioEncoderForm.vb:ligne 469
   à StaxRip.BatchAudioProfile.EditProject() dans D:\Projekte\VB\staxrip\General\AudioProfile.vb:ligne 457
   à StaxRip.MainForm.AudioEdit1ToolStripMenuItemClick() dans D:\Projekte\VB\staxrip\Forms\MainForm.vb:ligne 5587
   à StaxRip.ControlExtension._Closure$__3-0._Lambda$__0() dans D:\Projekte\VB\staxrip\General\Extensions.vb:ligne 1018
   à StaxRip.ControlExtension._Closure$__3-0._Lambda$__R1(Object a0, EventArgs a1)
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.Label.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by 44vince44** [comment]
Bug reproduced and confirmed also with latest beta 2.1.6.1

**Comment by Dendraspis** [comment]
@stax76 
Just a little help:  The problem is here in lines 348 and 349:

https://github.com/staxrip/staxrip/blob/7f59694496a70aa0031fae7e7ae55e5e8741414d/General/AudioProfile.vb#L344-L357

Side note:  When a source file is selected, `GetOutputFile.Escape()` works as intended.

**Comment by stax76** [comment]
Thanks, I added a null check here:

```
    Shared Function GetChecksum(str As String) As UInteger
        If str <> "" Then
            Return GetChecksum(Encoding.Unicode.GetBytes(str))
        End If
    End Function
```

Uploading the next stable version now.

**Comment by Dendraspis** [comment]
> Thanks, I added a null check here:

Saw it already.  😁

**Comment by stax76** [comment]
I've uploaded it now since there were two severe bugs. I hope it will last this time.

**Comment by 44vince44** [comment]
Thanks @stax76 @Dendraspis for the quick response and actions ;-)))

**Comment by DavidRodriguezSoaresCUI** [comment]
Woah, I'm impressed ! Didn't think it would be this quick, bravo @stax76 and thanks !
