### ISSUE TITLE
Register MPEG2Source from DGMPGDec 2.0.00 to AVS and VS as Additional Source Filters

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#424]
**DGDecode.dll**(MPEG2Source) in [DGMPGDec 2.0.00](http://rationalqm.us/dgmpgdec/dgmpgdec.html) (released on Dec 23, 2020) now supports _64 bit_ and is **_dual_**.

Please register **MPEG2Source** in Apps Management so that users can make use of them in place of D2Vsource(AVS) and d2vsource(VS) natively in StaxRip.

**How**

1. Put the 64 bit `DGDecode.dll` file in `%startup_dir%Apps\Plugins\Dual\DGDecode`.
2. Create items for `MPEG2Source` in Apps Management AviSynth and VapourSynth sections.
3. Add `MPEG2Source` items in AVS Profiles and VS Profiles respectively.

AVS:
`MPEG2Source = MPEG2Source("%source_file%")`

VS:
`MPEG2Source = clip = core.dgdecode.MPEG2Source(r"%source_file%")`
(Plz, refer to [this](http://rationalqm.us/board/viewtopic.php?f=7&t=982))

Of course `LoadPlugin` should be automatically put when `MPEG2Source` filter is activated.

4. Add `MPEG2Source` to DGIndex and D2V Witch preprocessors (in Settings) as an additional source filter.
5. (Optional) Set `MPEG2Source` as the default source filter for `d2v`.

**Comment by JJKylee** [comment]
Meanwhile, **DGMPGDec** is updated to 2.0.01:

> *Fixed decode crash with 64-bit DLL in Vapoursynth mode when stream has RFF flags. The UV pitch was getting set wrong.

It's [here](http://rationalqm.us/board/viewtopic.php?f=5&t=463&start=250#p12920) or [here](https://www.videohelp.com/software/DGMPGDec)(VideoHelp).

**Comment by stax76** [comment]
I've worked on it and there is a problem with the staxrip preview using vapoursynth, it shows blackness, encoding with x265 works.

**Comment by stax76** [comment]
mpv and mpv.net cannot open the _view.vpy script either.

**Comment by stax76** [comment]
It's caused by the resize line:

`clip = clip.resize.Bicubic(format = vs.COMPATBGR32)`

I would guess a DGDecode or VapourSynth issue, problem is both the vapoursynth author and me have not a good relationship with DG.

**Comment by JJKylee** [comment]
I found some critical bugs in DGMPGDec 2.0.01 while testing it with the 2.1.7.0 fresh version.
(Decoder does not start in VS MPEG2Source, and DGIndex/DGDecode mismatch in AVS.)
I think we should wait until they are fixed.
I'm going to report the bugs on the DG Tools forum for this.

Sorry about my hastiness. 😓

**Comment by stax76** [comment]
I'm not getting this error, only problem is dgdecode.MPEG2Source does not define Primaries and Transfer clip info, that's what was causing the problem, it should be possible to workaround it.

**Comment by JJKylee** [comment]
Pretty weird.
I'm really curious what caused these errors in my case.
Maybe a different source video/d2v file?
Then what about the version mismatch b/w DGIndex and DGDecode?
Food for thought. ☹️

**Comment by JJKylee** [comment]
I figured out the cause of my errors.

It was due to the _text encoding (UTF8 **with BOM**) of the **d2v** file_ generated by the DGIndex preprocessor in StaxRip (when the system codepage is UTF-8).

DGIndex.exe (the GUI app) and DGDecode.dll do not recognize this as a valid d2v file although it was generated by DGIndex.exe itself via CLI in StaxRip.

But on the other hand, the d2v file generated by DGIndex in GUI is saved in the correct text encoding (UTF-8 **without BOM**).

Only after I correct the text encoding to UTF-8 **_without BOM_** can I see no errors - both in StaxRip (AVS and VS) and DGIndex.exe. And preview works OK with my sample video.

![DGMPEGDec_2 0 01_VS_preview_in_StaxRip_2 1 7 0_20210109](https://user-images.githubusercontent.com/3157518/104112067-0ad5e600-529f-11eb-9857-829688c37fe6.jpg)

But like you said, there may be other bugs. So we'd better wait until they are fixed.

**Comment by JJKylee** [comment]
And **D2VSource**(AVS) and **d2vsource**(VS) also fail to read the BOM-prefixed d2v file.
No wonder considering they are mod versions of MPEG2Source.

**Comment by videoh** [comment]
I cannot get a BOM using either GUI or CLI. Maybe staxrip edits the D2V file and saves it with a BOM? Please follow up at DG forum.

**Comment by JJKylee** [comment]
You're right about it, @videoh.
It was a bug with StaxRip.

I posted an issue(#435) about this bug.

I admit that I made a hasty conclusion about it.
It didn't occur to me at first that an external `exe` call from StaxRip could make this kind of text encoding problem. 😢

**Comment by stax76** [comment]
@JJKylee 

It took a while but the blackness/color issue is solved. I can now investigate the text encoding issue.

**Comment by JJKylee** [comment]
For your reference, _DGIndexNV_ preprocessors created from an empty Command Line Demuxer template (as mentioned in the [Wiki document](https://github.com/staxrip/staxrip/wiki/How-to-register-DGDecNV(DGSource-and-DGIndexNV)-in-StaxRip)) do not have this BOM issue with the output `dgi` file. Hope it helps when you look into it.

**Comment by stax76** [comment]
I think there is code in staxrip that changes the d2v file depending on if it's something like film or not, maybe that's what added the BOM.

**Comment by stax76** [comment]
Yes, it was staxrip writing the file with BOM. The code was changed just days ago as part of a major text encoding rewrite.
