### ISSUE TITLE
Hardware decode with LWLibavSource outputs 8bit video

### ISSUE THREAD

**Issue by Vrael0n** [staxrip/staxrip#425]
Indexer successfully detects 10bit source video but LWLibavSource interprets it as 8bit.

![image](https://user-images.githubusercontent.com/61518774/103979825-74d17c80-5133-11eb-99da-ba8bea86f479.png)
![image](https://user-images.githubusercontent.com/61518774/103979604-f8d73480-5132-11eb-97a4-41afd1c299d0.png)

**Comment by Dendraspis** [comment]
I tried to reproduce it and Sources ***ffms2*** and ***LWLibavSource*** produce the same (correct) result using SDR and HDR content: 

![SR0](https://user-images.githubusercontent.com/50659978/103999466-353f7a80-519d-11eb-845d-bf0943219f1e.JPG)
![SR1](https://user-images.githubusercontent.com/50659978/103999468-35d81100-519d-11eb-990b-89713b58b005.JPG)

**Comment by Vrael0n** [comment]
You are correct, the problem appears to be LWLibavSource's hardware decoding feature **clip = core.lsmas.LWLibavSource(r"%source_file%", cachefile=r"%source_temp_file%.lwi", prefer_hw=3)** Removing ", prefer_hw=3" resolves the issue, but this is unfortunate as software decoding 4K HEVC is compute intensive and should be done with hardware. After the removal of DGdecNV support #274 this was the alternative. I will likely have to revert to an older StaxRip version.

**Comment by Dendraspis** [comment]
If it works without `prefer_hw=3` then the hardware part detects the wrong bit depth. So I doubt an older StaxRip version would fix it - having in mind that you can still use a pipe to feed x265.  🤔 

> I will likely have to revert to an older StaxRip version.

You can still use a pipe via settings to produce the old behaviour.

![SR3](https://user-images.githubusercontent.com/50659978/104006442-ca933c80-51a6-11eb-9b1e-a2728b29073d.JPG)

**Comment by Vrael0n** [comment]
Changing the pipe has no effect, only disabling hardware decode fixes the problem. I will attempt to add DGDecNV back to 2.1.7.0 myself. I have confirmed it decodes 10bit properly with StaxRip 2.0.8.0 using DGDecNV with its "fulldepth=True" flag.

**Comment by Dendraspis** [comment]
Okay, so it's definitely a tool issue.  👍 

Here is an instruction, that should still work - good luck!
https://forum.doom9.org/showthread.php?p=1913597#post1913597

**Comment by stax76** [comment]
It's also in the wiki:

https://github.com/staxrip/staxrip/wiki/How-to-register-DGDecNV(DGSource-and-DGIndexNV)-in-StaxRip

Here using GT 1030 I get 10-bit output, so it must be GPU/driver specific.

**Comment by Vrael0n** [comment]
Thanks for the guide, its working perfectly, no color banding on output.
![image](https://user-images.githubusercontent.com/61518774/104071041-2072df00-51bd-11eb-97f9-91a62b29aaba.png)
