### ISSUE TITLE
Register DFTTest Neo for AVS as well as for VS

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#426]
Although [DFTTest Neo](https://github.com/HomeOfAviSynthPlusEvolution/neo_DFTTest) is **_dual_**, StaxRip has it registered only for VS as of 2.1.7.0.

![StaxRip_2 1 7 0_missing_DFTTest_Neo_in_AVS_20210107](https://user-images.githubusercontent.com/3157518/103979838-78fd9a00-5133-11eb-856f-9b5758705094.jpg)

**Describe the solution you'd like**

1. Move `DFTTest Neo` folder from the current location to under `Dual` folder and change the default location for VS to the new one.
2. Create an item for `DFTTest Neo` in Apps Management AviSynth section.
3. Add `DFTTest Neo` item in AVS Profiles.

`DFTTest Neo = neo_dfttest(ftype=0, sigma=2.0, y=3, u=3, v=3)`

Of course `LoadPlugin` should be automatically put when `DFTTest Neo` filter is activated.

**Comment by stax76** [comment]
I've changed it.

y=3, u=3, v=3 gave a type error here however, so I removed it, I tried float and string without success, seems to be bool.

**Comment by 44vince44** [comment]
@stax76 there is now a minor problem.
When using DFTTEST ( NOT neo), the two lines appear in the code:
`LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\AVS\DFTTest\dfttest.dll")
LoadPlugin("C:\Program Files\Staxrip\Apps\Plugins\Dual\DFTTest Neo\neo-dfttest.dll")
`

the line concerning neo-dfttest.dll shouldn't appear!

**Comment by JJKylee** [comment]
@44vince44,
This issue was already reported and is still unresolved.
See #250.

**Comment by Dendraspis** [comment]
> y=3, u=3, v=3 gave a type error here however, so I removed it, I tried float and string without success, seems to be bool.

y, u and v are AviSynth+ only, for VapourSynth (only) `planes` is used

**Comment by 44vince44** [comment]
@JJKylee thanks for pointing that out !
Well, in the other post, @stax76 mentions that it won't be easy to fix.
There is no real problem, except only UI performance: when opening the Code Editor window, the more dlls are loaded, the more it takes time to open.

**Comment by JJKylee** [comment]
@44vince44 Agreed.

I guess the issue is related to the same character string that is included in the function names for neo and non-neo filters. Can’t we distinguish them by the ‘neo’ string in the function name using Regular Expression? Well, just a rough idea. 😄

**Comment by stax76** [comment]
There is now a new beta + hotfix online trying to solve it. I hope it works.
