### ISSUE TITLE
x265 direct AVS (no-pipe): possible tool performance issue (Patman86)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#429]
@Patman86 

I have been doing some performance tests on direct AVS input in x265. I was obviously expecting that this input method will be faster than the pipe.
Unfortunately, I noticed the opposite: the encoding time on a 4 minutes process would require a few seconds more when using direct AVS input. This result has repeadtedly shown on my 8 logical cores i7. 
Only a few seconds is not a big deal.

However, a processor with much more cores would reveal a bigger difference. This should be known by the end of the day by user MrBrownCow who already spotted huge performance issues (discussion on doom9's staxrip thread).

As I know you own a Ryzen with many logical cores, could you please do the following tests on a 4-5 minutes process:
-process a video, only a crop of the image, no other filters, no audio with **avs2pipemod**, monitor average CPU usage
-process same video with same parameters but  **no pipe**, monitor average CPU usage
And compare encoding times and average CPU usage.

If I'm right, CPU usage will be almost the same in both cases, but encoding time will be up to 40%  longer without pipe.

Thanks in advance!

**Comment by Dendraspis** [comment]
Seems like I should do some testing, too.  😲

**Comment by Patman86** [comment]
Only direct avs input or vs too?

**Comment by 44vince44** [comment]
@Dendraspis oh i forgot you had a ryzen too !! 

I'll test VS now!  I'm finishing another test first with the chunks

**Comment by Dendraspis** [comment]
> @Dendraspis oh i forgot you had a ryzen too !!

Psssst!  🤫  🤐 

Okay, the first test is running now. Will take a while till I come back with the results. 
I use a HDR file [video stream only] with a length of 150s and I have 4 jobs queued now:
1. AVS only using Crop via AVS2PIPEMOD
2. AVS only using Crop via DIRECT INPUT
3. AVS only using Crop via AVS2PIPEMOD
4. AVS only using Crop via DIRECT INPUT

I don't monitor the CPU usage, I'm only interested in the comparision of the fps (and duration).

**Comment by 44vince44** [comment]
3 and 4 are probably VS ;-)

**Comment by Dendraspis** [comment]
Nope - AVS only. I want to prevent caching or any other advantage for the second run, so I repeat them for better results.

**Comment by 44vince44** [comment]
My mistake ! you're right !!!

**Comment by Patman86** [comment]
Here are my results:

AVS_pipe
`avs2pipemod[info]: writing 7194 frames of 24000/1001 fps, 1920x800,
                   sar 0:0, YUV-420-planar-8bit progressive video.
y4m  [info]: 1920x800 fps 24000/1001 i420p8 unknown frame count
raw  [info]: output file: D:\xxx.hevc
x265 [info]: HEVC encoder version x265M 3.4+35-772bb4c84
x265 [info]: build info [Windows][MSVC 1928][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(13 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-18.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=5 deblock sao
avs2pipemod[info]: finished, wrote 7194 frames [100%].
avs2pipemod[info]: total elapsed time is 265.114 sec.
x265 [info]: frame I:    129, Avg QP:16.92  kb/s: 32020.60
x265 [info]: frame P:   1780, Avg QP:19.26  kb/s: 11345.96
x265 [info]: frame B:   5285, Avg QP:23.48  kb/s: 2885.13 
x265 [info]: Weighted P-Frames: Y:3.4% UV:2.0%
x265 [info]: consecutive B-frames: 15.3% 6.1% 8.0% 27.5% 43.1% 
encoded 7194 frames in 266.29s (27.02 fps), 5501.03 kb/s, Avg QP:22.32

Start:    13:55:05
End:      13:59:32
Duration: 00:04:26`

AVS_nopipe
`avs+ [info]: AviSynth+ 3.6.1 (r3300, 3.6, x86_64)
avs+ [info]: Video colorspace: YUV420 (YV12)
avs+ [info]: Video depth: 8
avs+ [info]: Video resolution: 1920x800
avs+ [info]: Video framerate: 24000/1001
avs+ [info]: Video framecount: 7194
avs+ [info]: 1920x800 fps 24000/1001 i420p8 frames 0 - 7193 of 7194
raw  [info]: output file: D:\xxx.hevc
x265 [info]: HEVC encoder version x265M 3.4+35-772bb4c84
x265 [info]: build info [Windows][MSVC 1928][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(13 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-18.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=5 deblock sao
x265 [info]: frame I:    129, Avg QP:16.92  kb/s: 32020.60
x265 [info]: frame P:   1780, Avg QP:19.26  kb/s: 11345.96
x265 [info]: frame B:   5285, Avg QP:23.48  kb/s: 2885.13 
x265 [info]: Weighted P-Frames: Y:3.4% UV:2.0%
x265 [info]: consecutive B-frames: 15.3% 6.1% 8.0% 27.5% 43.1% 
encoded 7194 frames in 266.60s (26.98 fps), 5501.03 kb/s, Avg QP:22.32

Start:    14:02:42
End:      14:07:09
Duration: 00:04:26`

VS_pipe
`y4m  [info]: 1920x800 fps 24000/1001 i420p8 unknown frame count
raw  [info]: output file: D:\xxx.hevc
x265 [info]: HEVC encoder version x265M 3.4+35-772bb4c84
x265 [info]: build info [Windows][MSVC 1928][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(13 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-18.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=5 deblock sao
Output 7194 frames in 269.42 seconds (26.70 fps)
x265 [info]: frame I:    129, Avg QP:16.92  kb/s: 32020.60
x265 [info]: frame P:   1780, Avg QP:19.26  kb/s: 11345.96
x265 [info]: frame B:   5285, Avg QP:23.48  kb/s: 2885.13 
x265 [info]: Weighted P-Frames: Y:3.4% UV:2.0%
x265 [info]: consecutive B-frames: 15.3% 6.1% 8.0% 27.5% 43.1% 
encoded 7194 frames in 270.53s (26.59 fps), 5501.03 kb/s, Avg QP:22.32

Start:    14:09:21
End:      14:13:52
Duration: 00:04:30`

VS_nopipe
`vpy  [info]: VapourSynth Video Processing Library Core R52
vpy  [info]: Video colorspace: YUV420 (YV12)
vpy  [info]: Video depth: 8
vpy  [info]: Video resolution: 1920x800
vpy  [info]: Video framerate: 24000/1001
vpy  [info]: Video framecount: 7194
vpy  [info]: 1920x800 fps 24000/1001 i420p8 sar 1:1 frames 0 - 7193 of 7194
vpy  [info]: using 16 parallel requests
raw  [info]: output file: D:\xxx.hevc
x265 [info]: HEVC encoder version x265M 3.4+35-772bb4c84
x265 [info]: build info [Windows][MSVC 1928][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(13 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 23 / 250 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-18.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=5 deblock sao
x265 [info]: frame I:    129, Avg QP:16.92  kb/s: 32020.60
x265 [info]: frame P:   1780, Avg QP:19.26  kb/s: 11345.96
x265 [info]: frame B:   5285, Avg QP:23.48  kb/s: 2885.13 
x265 [info]: Weighted P-Frames: Y:3.4% UV:2.0%
x265 [info]: consecutive B-frames: 15.3% 6.1% 8.0% 27.5% 43.1% 
encoded 7194 frames in 268.26s (26.82 fps), 5501.03 kb/s, Avg QP:22.32

Start:    14:14:41
End:      14:19:09
Duration: 00:04:28`

**Comment by Dendraspis** [comment]
@Patman86 
Sorry for misusing this issue, but while looking at you logs I have to ask, if this info is made on purpose in such "ugly" way:
`avs+ [info]: 1920x800 fps 24000/1001 i420p8 frames 0 - 7193 of 7194`
Wouldn't it be better or more useful writing `frames 1 - 7194 of 7194` ?

**Comment by 44vince44** [comment]
@Dendraspis I have noticed that same thing in the preview window. frames counter starts at 0.
I'm really afraid if something was to be changed, it could mess up other things.

**Comment by Patman86** [comment]
> @Patman86
> Sorry for misusing this issue, but while looking at you logs I have to ask, if this info is made on purpose in such "ugly" way:
> `avs+ [info]: 1920x800 fps 24000/1001 i420p8 frames 0 - 7193 of 7194`
> Wouldn't it be better or at least less annoying writing `frames 1 - 7194 of 7194` ?

This is a part of x265cli.cpp that does not come from the avs support implementation

```
        if (param->logLevel >= X265_LOG_INFO)
        {
            char buf[128];
            int p = sprintf(buf, "%dx%d fps %d/%d %sp%d", param->sourceWidth, param->sourceHeight,
                param->fpsNum, param->fpsDenom, x265_source_csp_names[param->internalCsp], info.depth);

            int width, height;
            getParamAspectRatio(param, width, height);
            if (width && height)
                p += sprintf(buf + p, " sar %d:%d", width, height);

            if (framesToBeEncoded <= 0 || info.frameCount <= 0)
                strcpy(buf + p, " unknown frame count");
            else
                sprintf(buf + p, " frames %u - %d of %d", this->seek, this->seek + this->framesToBeEncoded - 1, info.frameCount);

            general_log(param, input->getName(), X265_LOG_INFO, "%s\n", buf);
        }
```

**Comment by Dendraspis** [comment]
@Patman86 
Thanks for this information - I suspected that. 😞 
Maybe you could think of fixing it, too? - if you want. 😉  I don't know if this would create other issues or problems while patching/modding/merging, but it would be nice to have correct numbers. 🤔 

```C++
sprintf(buf + p, " frames %u - %d of %d", this->seek + 1, this->seek + this->framesToBeEncoded, info.frameCount);
```

-------------

Okay, here are my results:

1. `Duration: 00:22:13` AVS only using Crop via AVS2PIPEMOD
2. `Duration: 00:21:56` AVS only using Crop via DIRECT INPUT
3. `Duration: 00:22:02` AVS only using Crop via AVS2PIPEMOD
4. `Duration: 00:22:02` AVS only using Crop via DIRECT INPUT


### ***Seems like there is almost no difference other than caching advantages or similar!***

@44vince44 
So starting with Direct Input followed by a pipe job should result in ***PIPE is faster*** or vice versa if you start with the pipe configuration.

But here is something I also noticed when I starred at the resulting logs:

1. `Video Bit rate: 31.2 Mb/s` AVS only using Crop via AVS2PIPEMOD
2. `Video Bit rate: 31.3 Mb/s` AVS only using Crop via DIRECT INPUT
3. `Video Bit rate: 31.2 Mb/s` AVS only using Crop via AVS2PIPEMOD
4. `Video Bit rate: 31.3 Mb/s` AVS only using Crop via DIRECT INPUT

... with the interesting resulting file sizes:

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        09.01.2021     14:08      588002226 #1_PIPE_out.hevc
-a----        09.01.2021     14:30      588008511 #2_NoPIPE_out.hevc
-a----        09.01.2021     14:52      588008511 #3_PIPE_out.hevc
-a----        09.01.2021     15:14      588002226 #4_NoPIPE_out.hevc
```

### This is very annoying!

**Comment by 44vince44** [comment]
> ... with the interesting resulting file sizes (..)
yes indeed, why are the file sizes not correlated ? very strange!

Well thanks for the test. So we know that direct input support is not problematic....

**Comment by Dendraspis** [comment]
> yes indeed, why are the file sizes not correlated ? very strange!

...and the (shown) bitrate!
@Patman86  Do you have an explaination for those different results?  🤔 

> So we know that direct input support is not problematic....

Veni, vidi, vici .... we read it, we tested it scientifically, we refuted it!  😎  🚀

**Comment by JJKylee** [comment]
Very funny result. 😄

Well, I envy you high-end CPU owners.
My system is pretty mediocre, so I'm kind'a sad that my participation would not produce any significant results.
i5-7300... Sigh... 😭

**Comment by Patman86** [comment]
> yes indeed, why are the file sizes not correlated ? very strange!
> 
> ...and the (shown) bitrate!
> @Patman86 Do you have an explaination for those different results? 🤔

I can't confirm. I've done some tests with multiple files and I always get the same file size and bitrate.

> avs+ [info]: 1920x800 fps 24000/1001 i420p8 frames 0 - 7193 of 7194

This information is correct. The start frame is often frame 0 and in this case the end frame is 7193, the counter with 7194 frames is also correct. I don't want to change the information output.

[Look here](https://www.quora.com/In-video-production-why-is-the-first-frame-0-instead-of-1#:~:text=VFX%20shots%20often%20start%20their,motion%20blur%20is%20calculated%20correctly.)

**Comment by 44vince44** [comment]
@Patman86 @Dendraspis can I please ask you do do the following test, it requires you download an older version of staxrip: version 2.1.3.0.  And after that I'll close this issue:

- download v 2.1.3.0, deflate somewhere as is, no mod, keep settings as they are
- download v 2.1.7.0 deflate somewhere as is, no mod, keep settings as they are

process a small video with a basic **crop** only to make sure avs is really working, no audio stream. 
use **x265 --crf 24 --output-depth 10** as ONLY parameters. Encode same file, only one encode is enough.
Please see if there is a significant difference in encoding times

**Comment by Dendraspis** [comment]
@Patman86 
> I can't confirm. I've done some tests with multiple files and I always get the same file size and bitrate.

Interesting.  🤔 

> I don't want to change the information output.

Okay, thanks.  ☺️ 

--------

@JJKylee 
> My system is pretty mediocre, so I'm kind'a sad that my participation would not produce any significant results.
i5-7300... Sigh... 😭

Maybe your CPU would produce more significant results due to higher CPU usage - who knows. But it seems we have enough test made to say there is no disadvantage using DirectInput.  👍 

---------

@44vince44 
> can I please ask you do do the following test, [..]

What do you expect? Do you think the whole patching made x265 slower?  🤔 

> [..] it requires you download an older version of staxrip:

😂  😂  😂      
 👇 

![SRlist](https://user-images.githubusercontent.com/50659978/104104350-bd11ab80-52a7-11eb-902f-f249af46565a.JPG)

**Comment by 44vince44** [comment]
@Dendraspis i only wish you do this test because of our conversation with MrBrownCow at doom9 forum.
When he compares encode times between 2.1.3.0 and 2.1.7.0 he has version 2.1.7.0 40% slower 😞.

On my laptop there is a difference, maybe 2%, not 40%. But I have a 8 logical system, he has 24 ! So this is why I ask you to do that, because you have many cores, you too... Unlike JJkyle and I 🤣

**Comment by Dendraspis** [comment]
> Come on, it's only a couple of encodes.... 

I'll do it, don't worry. 
Might be coincidence or based on different sources, but I also had the feeling ***some***  encodes would take a little bit longer. 

But I think it would be more useful to test the latest version of StaxRip with the 'built-in' x265 encoder as well as with an unmodded version. :thinking: 
Because it is possible that x265 itself had a change or fix that causes it to be slower than before.

**Comment by 44vince44** [comment]
@Dendraspis I'm asking for that test, and really believe that you won't get a big difference. It's only to make sure.
Indeed, x265 changes between sub-versions explain speed and size changes. But i really have the feeling you'll get very small difference in this test.

**Comment by Patman86** [comment]
I ran tests with StaxRip 2.1.7.0, 2.1.4.9 and 2.1.4.6. Always the same x265 version (original and mod), only Avisynth is always from the corresponding StaxRip version. My results cannot confirm that something has changed for the worse, rather for the better or at the same level.

[Alpha Centauri - S04E13 - Woher kommt unser Wissen uebers All_staxrip2.1.7.0.log](https://github.com/staxrip/staxrip/files/5791742/Alpha.Centauri.-.S04E13.-.Woher.kommt.unser.Wissen.uebers.All_staxrip2.1.7.0.log)
[Alpha Centauri - S04E13 - Woher kommt unser Wissen uebers All_staxrip2.1.7.0mod.log](https://github.com/staxrip/staxrip/files/5791743/Alpha.Centauri.-.S04E13.-.Woher.kommt.unser.Wissen.uebers.All_staxrip2.1.7.0mod.log)
[Alpha Centauri - S04E13 - Woher kommt unser Wissen uebers All_staxrip2.1.4.6.log](https://github.com/staxrip/staxrip/files/5791744/Alpha.Centauri.-.S04E13.-.Woher.kommt.unser.Wissen.uebers.All_staxrip2.1.4.6.log)
[Alpha Centauri - S04E13 - Woher kommt unser Wissen uebers All_staxrip2.1.4.6mod.log](https://github.com/staxrip/staxrip/files/5791745/Alpha.Centauri.-.S04E13.-.Woher.kommt.unser.Wissen.uebers.All_staxrip2.1.4.6mod.log)
[Alpha Centauri - S04E13 - Woher kommt unser Wissen uebers All_staxrip2.1.4.9.log](https://github.com/staxrip/staxrip/files/5791746/Alpha.Centauri.-.S04E13.-.Woher.kommt.unser.Wissen.uebers.All_staxrip2.1.4.9.log)
[Alpha Centauri - S04E13 - Woher kommt unser Wissen uebers All_staxrip2.1.4.9mod.log](https://github.com/staxrip/staxrip/files/5791747/Alpha.Centauri.-.S04E13.-.Woher.kommt.unser.Wissen.uebers.All_staxrip2.1.4.9mod.log)

**Comment by JJKylee** [comment]
> My results cannot confirm that something has changed for the worse, rather for the better or at the same level.

Well, isn't this normal?

I'm very doubtful about the report that the encoding speed for the **same x265 binary** became _significantly_ different _only by employing different StaxRip versions_. Technically speaking, StaxRip is just a GUI with some convenient automation functions, and thus in theory it should not affect the actual encoding job itself. ☹️

**Comment by 44vince44** [comment]
totally agreed, however this is the statement of MrBrownCow

> 2.1.3.0 Duration: 00:08:15 uses AviSynth 3.6.0
> 2.1.3.7 Duration: 00:08:23 uses AviSynth 3.6.1
> 2.1.4.8 Duration: 00:13:31 uses AviSynth 3.6.2 test 2
> 2.1.4.9 Duration: 00:13:37 uses AviSynth 3.6.2 test 2
> 2.1.5.2 Duration: 00:14:04 uses AviSynth 3.6.2 test 2
> 2.1.5.5 Duration: 00:13:19 uses AviSynth 3.6.2 test 6
> 2.1.6.0 Duration: 00:12:58 uses AviSynth 3.6.2 test 6
> 2.1.6.1 Duration: 00:13:04 uses AviSynth 3.6.2 test 6
> 2.1.7.0 Duration: 00:13:01 uses AviSynth 3.6.2 test 6

the test made by @Patman86 does not allow me to prove my point, because the versions there are not problematic. That's why I mentioned 2.1.3.0 and 2.1.7.0, both specifically.
On my 8 logical core setup, i proved that 2.1.3.0 and 2.1.7.0 are similar in encoding times. I just wished we had the same test made on a Ryzen other then MrBrownCow's...

**Comment by Dendraspis** [comment]
Technically this _could_ be possible, of course - a wrong setting of a parameter, a buggy portable AVS/VPS build, a buggy filter, a wrong process priority, ...

And just as reminder:

> When he compares encode times between 2.1.3.0 and 2.1.7.0 he has version 2.1.7.0 40% slower 😞.

I haven't read the original posts, but nobody said *StaxRip itself is to blame* - for example it could also be AVS/VPS, a filter or x265.

>  I just wished we had the same test made on a Ryzen machine other then MrBrownCow's...

![Donkey](https://user-images.githubusercontent.com/50659978/104108716-27861400-52c7-11eb-99bf-a23d907b8617.jpg)

...but you have to wait till tomorrow.

**Comment by Patman86** [comment]
@JJKylee
I agree with you.  Only AviSynth / VapourSynth and x265 themselves influence the result if no other filters are activated.

**Comment by 44vince44** [comment]
> ...but you have to wait till tomorrow.

do it at your convenience my dear friend !

**Comment by Dendraspis** [comment]
@44vince44 
Testing is not necessary anymore. MrBrownCow was right - at least partially. Do you need more infos? :grin:

**Comment by Dendraspis** [comment]
@44vince44 
No more testing needed ... I have the reason!
Do you need more informations? :grin:

**Comment by Patman86** [comment]
@Dendraspis 
share with us!!!

**Comment by 44vince44** [comment]
yeeessssssssss please !

**Comment by JJKylee** [comment]
Maybe it's @Dendraspis's secret recipe. 😄

**Comment by Dendraspis** [comment]
No magic - it's very simple, but I don't feel like typing the whole story on my smartphone.

**Comment by JJKylee** [comment]
Sounds very much like Fermat... 😆

**Comment by Dendraspis** [comment]
> Sounds very much like Fermat... 😆

😂 😁 😂 

Ok, I'll try to shorten it a bit:

When I saw @44vince44 's quote from MrBrownCow with the durations, I remembered something:

> #### v2.1.3.8 Beta
> - x265 Presets and Tunes fixes (Dendraspis)

I remember, that this was one of my first and very heavy fixes and changes in StaxRip. Presets, Tunes and also some default settings were partly wrong, so that the encoded results should differ a lot between v2.1.3.8 and those before. ***They can only be compared with attention, because the encode may be completely different!***

So MrBrownCow could be right, that StaxRip v2.1.3.0 was faster, because it partially set wrong values.

Then we had another change:

> #### v2.1.4.5 Beta
> - Fixed x265 Preset default value for LookaheadSlices (Dendraspis, (112e150))

Both fixes were between his last fast and first slow experiances, so they possibly affect the results.

But then I wanted to investigate the source of the problem and searched doom9 for that discussion.
As it turned out, MrBrownCow has not used minimalistic x265 parameters for his tests and he also posted the log files from both encodes using v2.1.3.0 and v2.1.7.0 [in that thread](https://forum.doom9.org/showthread.php?p=1932785#post1932785).
I'll post the interesting parts so you can compare them:

```
x265.exe --pass 2 --bitrate 1000 --preset slow --profile main10 --output-depth 10 --refine-mv 1 --aq-mode 3 --qcomp 0.75 --aq-motion --bframes 8 --rc-lookahead 50 --multi-pass-opt-rps --selective-sao 0
```

```
x265.exe --pass 2 --bitrate 1000 --preset slow --profile main10 --output-depth 10 --rskip 0 --refine-mv 1 --aq-mode 3 --qcomp 0.75 --aq-motion --bframes 8 --rc-lookahead 50 --multi-pass-opt-rps --selective-sao 0
```

And we remember:
> This option determines early exit from CU depth recursion in modes 1 and 2. When a skip CU is found, additional heuristics (depending on the RD level and rskip mode) are used to decide whether to terminate recursion. 
> Provides minimal quality degradation at good performance gains for non-zero modes. --rskip mode 0 means disabled. Default: 1,

In other words: this comparison is ***not fair*** whether this parameter alone has such an huge impact or not. I guess his profile was corrupted or so with v2.1.3.8 where many settings changed for x265 (see above).
After one quick shot with `--rskip 0` my encode duration went up to `00:23:32` (+7%). But I think this setting is very dependant on the given source.

Another difference in x265 is this:
v2.1.3.0 uses `x265 M-3.4+6-g73f96ff39-gcc11.0.0 Patman`
v2.1.7.0 uses `x265 M-3.4+28 gcc10.2.0 Yuuki-Asuna/msg7086/DJATOM/Patman`
...newer version built with an older gcc version. That might also impact the speed (a bit).

I guess it's a combination of everything - different settings and different/changed tools.

Oh, meanwhile my encode using StaxRip v2.1.3.0 with `--rskip 0` finished: `00:23:48` (+1% compared to v2.1.7.0)

So I'm very sure that MrBrownCow has a problem with his system (configuration), because nobody here can verify his duration differences. About possible 15% goes to `--rskip 0`, but another 25% seems like x265 would be harmed from the outside.


Sorry for typos - it's late - tooooooooo late!
Good night.

**Comment by JJKylee** [comment]
> I guess it's a combination of everything - different settings and different/changed tools.
> 
> So I'm very sure that MrBrownCow has a problem with his system (configuration), because nobody here can verify his duration differences. About possible 15% goes to `--rskip 0`, gcc and changed tool behaviour, but another 25% seems like x265 would be harmed from the outside.

Yeah, no wonder. 😄
Thanks for the findings. You must be having a big magnifier. 😆

**Comment by 44vince44** [comment]
Well guys, I know all about that. Yes @Dendraspis it has occurred to me.
That's why **TWO days ago**, I made a test with **exact same command line switches** that the ones used by MrBrownCow.
The results logs of my test are here: https://forum.doom9.org/showthread.php?p=1932827#post1932827

Where MrBrownCow finds 40% slower, I find less than 3% slower.
So I am guessing that there is something wrong in MrBrownCow steup.

I'm only asking to so a simple encode on a Ryzen (no need to test with those complex switches), comparing 2.1.3.0 and 2.1.7.0. If the results are 3% like in my case, then we can answer MrBrownCow that his issue is not reproducible.

**Comment by Patman86** [comment]
Can someone share v2.1.3.0 with me 😁

**Comment by Dendraspis** [comment]
> If the results are 3% like in my case, then we can answer MrBrownCow that his issue is not reproducible

Yes, they are. And yes, they don't. :grin:

> And please this time if anyone was to perform a test, do v.2.1.3.0 vs 2.1.7.0,

I did. :thinking: 

And I won't do any more. I already lost enough time already and even not scientifically, we have proven that there is no more difference than maybe 2% when using ***same settings*** on such small test files which sometimes can be explained through caching advantages.

So the only thing that would let me do more test would be his source file and his template so we could compare the results.
Sorry, but every other test seems to be useless.

**Comment by 44vince44** [comment]
OMG LOOOOOL  🤣 
https://github.com/staxrip/staxrip/releases/tag/2.1.3.0

**Comment by 44vince44** [comment]
@Dendraspis The test you shared with us was pipe vs no-pipe.
But I don't remember you sharing any test relating to v2.1.3.0 vs v2.1.7.0.

**Comment by Patman86** [comment]
> OMG LOOOOOL  🤣 
> https://github.com/staxrip/staxrip/releases/tag/2.1.3.0
> 

OMG not enough sleep! 🤦‍♂️

**Comment by Dendraspis** [comment]
@44vince44 
No big comparison chart this time, right. It was too late.  😁  But I compared both versions with same settings:

> After one quick shot with `--rskip 0` my encode duration went up to `00:23:32` (+7%).  

> Oh, meanwhile my encode using StaxRip v2.1.3.0 with `--rskip 0` finished: `00:23:48` (+1% compared to v2.1.7.0)

So my difference between v2.1.3.0 and v2.1.7.0 was about 1.13% - v2.1.7.0 being faster!

I've done a few more tests before that I didn't mention and on my PC with my test file and settings there is absolutely no significant difference using old and new versions.

@Patman86 
Thanks for that! 🤣

**Comment by 44vince44** [comment]
@Dendraspis sorry for not having inderstood that

> Oh, meanwhile my encode using StaxRip v2.1.3.0 with --rskip 0 finished: 00:23:48 (+1% compared to v2.1.7.0)

So you compared v2.1.3.0 with v2.1.7.0 **both using --rskip 0**
And you got +1% time longer for v2.1.3.0. **right ?**

This is all I needed to know! thanks

**Comment by Dendraspis** [comment]
@44vince44 
No problem. But it explains why there is no *thumbs up* for my long text from you.  😂  You haven't read it.  😂 

> So you compared v2.1.3.0 with v2.1.7.0 **both using --rskip 0** 
> And you got +1% time longer for v2.1.3.0. **right ?**

💯   Right!

> This is all I needed to know! **thanks** 🤣

😅

**Comment by 44vince44** [comment]
@Dendraspis 

> 
No problem. But it explains why there is no thumbs up for my long text from you. 😂 You haven't read it. 😂

it was late, i stupidly skipped it ! :(((( sorryy!!!

**Comment by Patman86** [comment]
I have now also carried out a test, only the Staxrip version differs (x265, ffms, avisynth same version) and I used the parameters of MrBrownCow, but with one of my files. It turns out that version 2.1.7.0 is slightly faster than 2.1.3.0 (about 1%). So I come to a similar result as Dendraspis.

**Comment by 44vince44** [comment]
@Dendraspis @Patman86 @JJKylee Thanks all for your participation !!

I'm closing this now !
