### ISSUE TITLE
ffmpeg build Wolfberry doesn't support dxva2

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#43]
The Wolfberry build don't have dxva2 as decoder, was removed by Wolfberry. Version from ffmpeg homepage support avs import too and have dxva2 decoder enabled.

**Comment by Revan654** [comment]
Just delete the included version and use the default or Custom build. There are licensing issues based on what codecs you include inside of ffmpeg during the build process.

**Comment by Patman86** [comment]
I've done that. I noticed that during the test with qsvenc and nvenc. There you can select the option to decode the file with ffmpeg dxva2.

**Comment by stax76** [comment]
@Patman86 

I used Wolfberry's build because it supports vpy input.

Maybe try to ask Wolfberry to support dxva2.

**Comment by Patman86** [comment]
I've build my own version and still test it now.

**Comment by Patman86** [comment]
Here are my builds of 
x264.exe (0.158.2984 with l-smash and ffms)
x265.exe (3.1+19 / 8-bit, 10-bit, 12-bit)
ffmpeg.exe (from 16.09.19 like zeranoe builds + openal, opencl, opengl, vapoursynth and cuda-nvcc)
MP4Box.exe (0.8.0-rev69)

I've tested a lot but not everything. Maybe some one is interested.

http://www.mediafire.com/folder/t8wli9je1n54apx,ke1hf4ouus5xpcw,ov5lpil8k4kk9rb,cq7y2mqgyryc029/shared
