### ISSUE TITLE
Cannot remove files after ADD Folder

### ISSUE THREAD

**Issue by SergePD** [staxrip/staxrip#433]
**BUG***
Cannot remove files in a list.

**Expected behavior**
In previous version individual files can be removed.

**How to reproduce the issue**
Right click "OPEN", "FILE BATCH" "+ADD" "Add Folder" "Include subfolders - YES"
Now, the option to remove files is dimmed.

**Comment by 44vince44** [comment]
BUG CONFIRMED.

And neither the Arrows are available!

**Comment by Dendraspis** [comment]
A nice bug that should exist for a very long time.  😁 
But it's fixed now.
