### ISSUE TITLE
Can I load only an audio file in StaxRip

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#437]
I need to change an audio file, change AC3 to EAC3, and StaxRip with ffmpeg does it.

Usually I load my video file and StaxRip check all and divide them to video, audio and subs.  Right.

But I need to load only the audio file.
If I select sigle file or megue files, trhe program load but when it finish tell me about which program use to create the script, and in this moment when I select one of them, the program crush because it waits a video file.

Is there any way to load only an audio file?  Only audio file.

Thanks in advantage

**Comment by Dendraspis** [comment]
1. Why don't you use ffmpeg to convert the audio file?
2. Why converting an AC3 to EAC3?

StaxRip is a ***video encoding tool***, so this is not possible.
Seems like you have to use ffmpeg directly or another GUI or audio encoding tool.

**Comment by Patman86** [comment]
look at [that](https://forum.doom9.org/showthread.php?t=181616)

**Comment by papa-pitufo** [comment]
> 1. Why don't you use ffmpeg to convert the audio file?
> 2. Why converting an AC3 to EAC3?
> 
> StaxRip is a _**video encoding tool**_, so this is not possible.
> Seems like you have to use ffmpeg directly or another GUI or audio encoding tool.

Because I prefer to use a GUI

And, 2, I'm sorry, I use ffmpeg to convert DTS or DTSHD to EAC3

**Comment by papa-pitufo** [comment]
> look at [that](https://forum.doom9.org/showthread.php?t=181616)
> easy to use and supports many codecs

Thank you very much, I see it

**Comment by Dendraspis** [comment]
Ok, DTS to EAC3 makes more sense. 😊

**Comment by papa-pitufo** [comment]
Yes, of course.

Thank you very much guys.

**Comment by stax76** [comment]
It's a supported use case.

1. Start staxrip, no video is loaded.
2. Drop audio file.
3. Right-click audio track, choose _Execute_.

**Comment by Dendraspis** [comment]
😲   Didn't know that yet.

**Comment by Patman86** [comment]
Can be closed, or?

**Comment by papa-pitufo** [comment]
> It's a supported use case.
> 
> 1. Start staxrip, no video is loaded.
> 2. Drop audio file.
> 3. Right-click audio track, choose _Execute_.

Ohhh, it's so easy,

Thank you very much for your help

Best regards, and yes, it's can be closed.

**Comment by AkashKhan2020** [comment]
> It's a supported use case.
> 
> 1. Start staxrip, no video is loaded.
> 2. Drop audio file.
> 3. Right-click audio track, choose _Execute_.

I don't understand...
Then what?
