### ISSUE TITLE
Shortcuts for filter composition related jobs

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#444]
**Is your feature request related to a problem? Please describe.**

Most users move back and forth between filter script composition and preview to get the best result they want.
But mouse clicking a relevant menu each time is sometimes very inconvenient and time-consuming.

**Describe the solution you'd like**

It would be convenient if there were _shortcuts_ to menus for filter composition related jobs where applicable.
![StaxRip_2 1 7 1_script-composition-related-shortcuts_missing_20210112](https://user-images.githubusercontent.com/3157518/104406277-c7d07880-5513-11eb-80a1-ee4378215e0d.jpg)

Currently users are not allowed to set/change shortcuts for them.

**Comment by 44vince44** [comment]
**You want a shortcut for Edit Code ?** Use your creativity

1) Edit MAIN WINDOW menu and create a MENU called Edit Code

![SNAG-0001](https://user-images.githubusercontent.com/17828567/104567189-2e11e400-5657-11eb-8800-d47b46b882c0.jpg)

Give it a shortcut, Select the command Show/ShowFilterEditor

2) Look how beautiful
![SNAG-0000](https://user-images.githubusercontent.com/17828567/104567330-5699de00-5657-11eb-95b3-c31b99a65fdb.jpg)


3) I vote AGAINST the request. The current state of the software allows this, it needs 30 seconds to be done.
 The shortcuts of the MAIN window are those of the MAIN MENU. This is a logic that must be respected. The area that @JJKylee points to is not the main window.
**Don't have an item in main menu ? You can put it yourself as a user !**

**Comment by JJKylee** [comment]
Shoot... I feel ashamed I was not even thinking about this.
I was so reckless. 😢
@44vince44, thanks for reminding me. 😄

BTW, why don't you put this in Wiki or others?
I'm pretty sure most users don't know about this.

(BTW, what's the command for `Preview Code`? This is the one I need a shortcut for desperately, but I can't find it.)

**Comment by Dendraspis** [comment]
> BTW, what's the command for `Preview Code`? This is the one I need a shortcut for desperately, but I can't find it.

It's called `ShowCodePreview`  and it will be available in the next beta.  😁

**Comment by JJKylee** [comment]
> It's called `ShowCodePreview` and it will be available in the next beta. 😁

Super! 👏
So then I wasn't that stupid, was I? 😓
