### ISSUE TITLE
Error in subtitles with accented characters and others

### ISSUE THREAD

**Issue by rg6304** [staxrip/staxrip#446]
I am using staxrip version 2.1.7.0.
When hardcoded subtitles of type .ass are added, accented characters and some punctuation marks appear as small rectangles.
I give you screenshots of the subtitles before pasting them into the video and after pasting. See how they look.

Before:

![image](https://user-images.githubusercontent.com/77389573/104447633-d0a86500-557a-11eb-9715-5f00a2ffdb9e.png)

After:
![image](https://user-images.githubusercontent.com/77389573/104447945-46143580-557b-11eb-9f09-74bb2f712683.png)
![image](https://user-images.githubusercontent.com/77389573/104448050-6d6b0280-557b-11eb-962e-6fba8e6ee9d2.png)

I also attach the log of the process.

[Tehran.S01E01_staxrip.log](https://github.com/staxrip/staxrip/files/5808372/Tehran.S01E01_staxrip.log)

I also did tests with another movie and another .ass file with the same result.

It had never happened to me before. I've been using the app for years.

If you could tell me how to solve it, I would appreciate it.

Best regards.

Ruben

**Comment by 44vince44** [comment]
@rg6304 
Can you please send to me the file F:\Tehran S01 [2020]\Tehran.S01E01.ass  (you'll need to zip it)

I have tested with a file will french characters and they were OK. So I need to test your subtitile file.

**Comment by rg6304** [comment]
Hi 44vince44!

Thank you for your help.

I send you the compressed file.
[Tehran.S01E01.zip](https://github.com/staxrip/staxrip/files/5809478/Tehran.S01E01.zip)

I await your comments.

Best regards.

Ruben

**Comment by 44vince44** [comment]
Hi again @rg6304 Ruben, this is because your *.ass subtitles are in "1252 Western European Encoding". If you open the subtitle in Subtitle Edit, change the encoding to Unicode (the first in the list) and save the subtitle, it will work and show the characters as they should be.
It is not an error with staxrip I think, it's a tool issue.

**Comment by rg6304** [comment]
Hi Vince,

I have been using SubtitleWorkshop 6.0e for a long time.

I changed the subtitle output record parameter to UTF-8.

I pass the screenshot, in case the same thing happens to someone.

I really appreciate your help.

Best regards.

Ruben.
![Screenshot_1](https://user-images.githubusercontent.com/77389573/104490085-2b5bb400-55af-11eb-8357-b3c4974be27a.png)

**Comment by stax76** [comment]
@rg6304 

Do you use Windows 10, if so which version of Windows 10?

What is your code page? You can get with powershell:

`[Text.Encoding]::Default | select EncodingName,CodePage`
