### ISSUE TITLE
Do you have another name for "Chunks"

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#447]
![SNAG-0000](https://user-images.githubusercontent.com/17828567/104592951-ac7e7e00-5677-11eb-90ec-9a4040b98c3d.jpg)

So it is only a UI design small change, or a rename.
Well because put like that, it really looks like Chunks and Chunk-start, Chunk-end are related, ans as we know for a long time they are not!

**Comment by Patman86** [comment]
Partitions maybe 😆

**Comment by DJATOM** [comment]
"Segment" perhaps?

**Comment by Dendraspis** [comment]
I'm curious who renames all internals to avoid readability/coding problems.  😁 

@44vince44 
No participation until you stop [ignoring me](https://github.com/staxrip/staxrip/discussions/443#discussioncomment-279536)!!  😝

**Comment by 44vince44** [comment]
@Dendraspis Since when I'm ignoring you ???? ❤️ 
AHHH lol i didn't see that 🤣 

I find @DJATOM 's suggestion "Segments" very adequate!

> I'm curious who renames all internals to avoid readability/coding problems. 😁

I hope that's not too much work ...

**Comment by JJKylee** [comment]
Partitions vs segments.
Both look good, but I also think '**segments**' is more appropriate in this case.
To add my personal impression, 'partition' makes me imagine a 2 dimensional space, while 'segment' makes me think about a line.

**Comment by Dendraspis** [comment]
> 'partition' makes me imagine a 2 dimensional space

Funny,, it lets me think of a new HDD.  😁 

My suggestions are a little bit simpler:   **Parts** or **Fragments**

**Comment by 44vince44** [comment]
Why not segments, I already saw it in similar things ? Fragments implies something messy.

**Comment by stax76** [comment]
I like Chunks or Parts, or maybe Split Parts.

In case the feature is very popular it could be moved to the basic tab however.

**Comment by JJKylee** [comment]
> I like Chunks or Parts, or maybe Split Parts.

Oh, that makes me think about another term: '**splits**'.

Now I'm indifferent b/w 'segments' vs 'splits'.

**Comment by Dendraspis** [comment]
@44vince44 
Just to have fun.  🤣 

But **Fragments** doesn't imply something messy, it implies something **incomplete**.

To be honest it doesn't bother me that much. Yes, it is confusing for everybody who looks onto these options, but there are more complex situations/options than that - in my opinion.
Nevertheless it's a little bit inappropriately placed.

**Comment by JJKylee** [comment]
> > 'partition' makes me imagine a 2 dimensional space
> 
> Funny,, it lets me think of a new HDD. 😁

Wow, you're really a techie. When I was mentioning it, I was thinking about an office room. 😋

**Comment by 44vince44** [comment]
> But Fragments doesn't imply something messy, it implies something incomplete.

Indeed, incomplete is implied. But messy, like the overall view of a fragmented HDD ;-)

**Comment by 44vince44** [comment]
I'm gonna remove this, since it appears that "chunks" has become a common way to call those... If people get confused, we'll explain...

**Comment by Dendraspis** [comment]
> since it appears that "chunks" has become a common way to call this feature...

Where? 
I wanted to rename it to ***Segments*** after I finish the aomenc improvements.  🤔

**Comment by JJKylee** [comment]
For your reference, Av1an and NotEnoughAV1Encodes call it '**worker**' while Ripbot264 calls it 'chunk'.

[Av1an](https://github.com/master-of-zen/Av1an)

![NEAV1E_1 6_splitting_setting_20210210](https://user-images.githubusercontent.com/3157518/107526674-f2423f80-6b6c-11eb-9165-08bd1a0cdcba.jpg)

**Comment by Dendraspis** [comment]
I like ***Workers***.  😊

**Comment by 44vince44** [comment]
I really believe that Segments is perfect, but Chunks is also good. 

I'm afraid it would take your time for nothing really important. And I could do a Wiki page explaining how to speed up encoding.

**Comment by 44vince44** [comment]
> But I like scene detecting splitting even more. 😲

You know it won't do much difference on HQ encodes.... You would see a difference on crappy encodes, where crf is more than 35 maybe..
