### ISSUE TITLE
FFMS2 AVS filter is missing for ffms2.dll in Apps Manager

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#448]
**Describe the bug**

`FFMS2` filter was introduced in **ffms2** ver 2.22, and this is an alias for `FFmpegSource2` which _combines_ the functionality of `FFVideoSource` and `FFAudioSource`. ([FFmpegSource2 Avisynth User Manual](https://github.com/FFMS/ffms2/blob/master/doc/ffms2-avisynth.md))
But as of 2.1.7.1, it's missing from the _Apps Manager_.

![StaxRip_2 1 7 1_FFMS2_filter_missing_in_ffms2_AVS_20210114](https://user-images.githubusercontent.com/3157518/104690794-eff9dc00-56b9-11eb-9867-d4b52e45084b.jpg)

Therefore, users should _manually_ add `LoadPlugin` call to `ffms2.dll` that's already in the program tree in order to use this filter(`FFMS2`) in AVS, because they run into an error without the call.

![StaxRip_2 1 7 1_FFMS2_filter_with_LoadPlugin_AVS_20210114](https://user-images.githubusercontent.com/3157518/104690989-49620b00-56ba-11eb-99fd-e249bfdb8b3c.jpg)

**Expected behavior**

`FFMS2` needs to be registered as a filter embedded in `ffms2.dll`.

**How to reproduce the issue**

1. Go to AVS _Filter Profiles_.

2. Add `FFMS2` item under [Source] category.

```
FFMS2 = FFMS2("%source_file%", atrack=-1, cachefile="%source_temp_file%.ffindex")
```

3. Register `FFMS2` as the source filter for `*`, and uncheck all the preprocessors so that `FFMS2` can handle the source file.

4. Load any source file, and you'll see this error message.

![StaxRip_2 1 7 1_FFMS2_filter_without_LoadPlugin_AVS_error_20210114](https://user-images.githubusercontent.com/3157518/104691925-f2f5cc00-56bb-11eb-8f90-399f77c76455.jpg)

**Additional info**

The error is gone if you add the `LoadPlugin` call to `ffms2.dll` additionally as follows:

```
FFMS2 =
    LoadPlugin("%startup_dir%Apps\Plugins\Dual\FFMS2\ffms2.dll")
    FFMS2("%source_file%", atrack=-1, cachefile="%source_temp_file%.ffindex")
```

But since `ffms2.dll` is already in the program tree, we can avoid this hassle by registering `FFMS2` as an AVS filter provided by the library.

**Extra**

I would also like to request that `FFMS2` be added in the default AVS _Filter Profiles_. It's more versatile than `FFVideoSource` and enables other audio related jobs that cannot be easily done by `FFVideoSource` alone.

**Comment by stax76** [comment]
It will be available in the next build.
