### ISSUE TITLE
Only one pass command is visible in two pass encoding

### ISSUE THREAD

**Issue by lifta19** [staxrip/staxrip#454]
https://funkyimg.com/i/3a4JA.jpg

I'm sorry I didn't speak English well

In 2-pass encoding, commands can only be checked for 1 pass
Please let me see the 2-pass command
Sometimes you can encode one pass first and two passes a few days later

To encode two passes, you must complete all one pass two passes
2 pass can be encoded independently based on the file generated in 1 pass encoding
I request

**Comment by stax76** [comment]
I've added it for the command line preview of x265.
