### ISSUE TITLE
ec3/eac3  - Dolby Digtial Plus dont' Mux in mp4 container

### ISSUE THREAD

**Issue by Xperia** [staxrip/staxrip#455]
When I try to mux ec3/eac3  - Dolby Digital Plus to a mp4 container staxrip says mp4box doesn't support it when Mp4box actually do.

**Comment by JJKylee** [comment]
Well, the report itself is too concise but a good find. I can confirm it.

Currently in 2.1.7.1, AC3 muxing by MP4Box has no problem, but E-AC3 is refused.
MP4Box muxes E-AC3 too, so this outdated warning should be removed. 

![StaxRip_2 1 7 1_false-warning_MP4Box_E-AC3_muxing_20210116](https://user-images.githubusercontent.com/3157518/104822572-45d49e00-57f8-11eb-8b69-7c67af2d7d2d.jpg)

**Comment by stax76** [comment]
I will be fixed in the next build.

**Comment by JJKylee** [comment]
I confirm this issue is fixed in 2.1.7.2 released today.
We can close this issue now. 😃
