### ISSUE TITLE
Soft Links must be created for DevIL.dll also

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#458]
**Is your feature request related to a problem? Please describe.**
This is not a problem unless user decides to call DevIL.dll for processing video to image conversion with AVS.
DevIL.dll is one of the two dlls of Avisynth provided with the Avisynth package, and is included in Staxrip.

Currently, when you encode with Staxrip set to use INTERNAL Avisynth,  if there exists C:\Windows\System32\DevIL.dll, it will be locked because "used by the process x265".

This proves that the encoding process looks for DevIL.dll, and in the wrong place.

**Describe the solution you'd like**
There should be a softlink to internal DevIL.dll exactly the same way there is for Avisynth.dll.

**Comment by stax76** [comment]
It would mean for every avisynth soft link also a DevIL soft link. The related code is rather complex and also important, I don't want to invest a lot of time, risk new bugs etc. unless it's absolutely necessary, what would be benefit? It would also be interesting to know when avisynth needs DevIL. Does avisynth work if DevIL is missing, I ask because for native code different link methods exist, that is:

load-time dynamic linking and
run-time dynamic linking

But there is also a hybrid form.

Did you try the new install.ps1? Normally I do not install avisynth, only for things like testing and development.

install.ps1 does not copy files to system32, instead it adds the directory to PATH (per-user), so that client apps that load avisynth (via LoadLibrary call) will find it.

**Comment by 44vince44** [comment]
I didn't try it but I checked the the registry entries (for {E6D6B700-124D-11D4-86F3-DB80AFD98778}) are OK.
I'll try it later but I have some encodes running, and have to finish them first (I have been aborting them for all these tests)

>  It would also be interesting to know when avisynth needs DevIL

In my understanding DevIL is the dll that allows to create an image sequence from a source video.
I do NOT use that feature, however, when I do an encode, DevIL.dll  gets locked because it's "in use", so I cannot delete it.
It seems whenever Avisynth is in use, it locks DevIL.
I will complete the info a bit later when my encode is finished.

**Comment by JJKylee** [comment]
I'm not sure about this matter either, but just in case, maybe [this post on a Doom9's thread by Groucho2004](https://forum.doom9.org/showthread.php?p=1846513#post1846513) can be of help.

**Comment by Dendraspis** [comment]
> [..] I have some encodes running, and have to finish them first (I have been aborting them for all these tests)

Why don't you just start another instance with higher process priority, so that it's test encodes are processed faster?  
Even with shared settings you could add the job to the top (Shift + NEXT) and start it with ***Stop After Current***.  🤔

**Comment by 44vince44** [comment]
@Dendraspis it's a very long single file. It just finished. I can do tests now.

The test is: when I use internal Avisynth, and begin an encode: which devil.dll will be locked ? the one in the internal folder, or the one in System32 ? And then what happens if there is no one in system32. 
I'll use imagesource filter to see what happens also. My answers here in 1/2 an hour.

**Comment by 44vince44** [comment]
@stax76 Here is the result of the testing with DevIL.
Context: Staxrip Settings set to use internal Avisynth. In all tests below, files Avisynth.dll and DevIL.dll are present in Staxrip internal tree.

1) if DevIL.dll not present in System32, then the file DevIL.dll of Staxrip's internal tree will be used.
2) if DevIL.dll is present in System32, then the file DevIL.dll of the system32 folder will be used and be locked while processing,
regardless of if there is a avisynth.dll file in system32, and regardless of the registry entries (installing the ps changes nothing to the behavior).
3)If DevIL.dll is present in System32, BUT i create a softlink next to the encoder's exe, pointing to the DevIL.dll inside the internal tree, then the file in System32 will NOT be used.

So it's the same observation that was made maybe one year ago on Avisynth when beginning the creation of the whole Softlink logic for Avisynth.

If we want to be consistent, the same logic must be implemented for DevIL.dll

**HOWEVER:** The only video processing that will really use DevIL.dll is ImageSource() filter.

So maybe 1/10000 users will complain, only in the case they have an old DevIL.dll in System32.
And the solution is : copy DevIL.dll to system32. Or Install global Avisynth.  

So if it's too complex, it can be left as it is now.

**Comment by stax76** [comment]
Thanks for testing. I'm not an expert here, but I think normally the OS DLL search order is this:

1. Folder where the application is in
2. System32
3. PATH

**Comment by 44vince44** [comment]
@stax76 yes it confirms my tests! I didn't know it was a general rule! Thanks for the information !
