### ISSUE TITLE
Windows 10 StartUp programs do not load after StaxRip shutdown

### ISSUE THREAD

**Issue by WIGGER-BG** [staxrip/staxrip#459]
Hello,

First I'd like to thank for the continuous improvement and your dedicated work on this great software!

Here is what I use:

StaxRip    : 2.1.7.0
Windows    : Windows 10 Pro 2009
CPU        : AMD Ryzen 7 1700X Eight-Core Processor
GPU        : NVIDIA GeForce GTX 1050 Ti
Resolution : 1920 x 1080
DPI        : 96

I already got this issue twice: After finishing x264 encoding I choose automatic shutdown from the menu. Everything goes fine, computer is shut down as expected. But when I start it again, my start-up programs do not load. I have lock screen with password and normally all programs are loaded on the back. I tried normal shutdown and new start and all programs were loaded.

I hope this information is useful for future versions.

**Comment by 44vince44** [comment]
Could not reproduce it (made 3 tests). How can Staxrip's shutdown command have an impact on next system start up ? 
However I tested beta 2.1.7.2 and not 2.1.7.0.

**Comment by 44vince44** [comment]
@WIGGER-BG you should get the latest beta 2.1.7.3 and test it. It has many fixes sinces 2.1.7.0.

**Comment by stax76** [comment]
The shutdown is done with the following command line:

`shutdown.exe /f /s /t 0`

Docs:

https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/shutdown

**Comment by Dendraspis** [comment]
Using `/f` is too aggressive in most cases and can cause some issues with other apps.

I made the force switch optional - will be available in the next version. Maybe this helps.

**Comment by stax76** [comment]
I hope it helps. Made also a small change.

**Comment by WIGGER-BG** [comment]
Thanks both to @Dendraspis and @stax76 for the quick reaction. I'll test it again on the next stable version.
