### ISSUE TITLE
How to customize the loadplugin code in vapoursynth script generated automatically?

### ISSUE THREAD

**Issue by wzunknown** [staxrip/staxrip#46]
**Notes Before Posting**
- Only Open an issue if it's tied to Staxrip, If issues is tied to external program or filter. Head to Resp page for that project and open an issue there. 
- Beta Releases are Not Covered, Beta Are Pre-Releases and Could Contain Bugs. This is the Risk Your Willing to Take When using Beta releases. Beta Concerns should be posted in the forums.
- If you Require Help with one of the FrameServers, Programs or Scripting Post in the Forums, Rather then opening a ticket here.
  Link: https://forum.doom9.org/showthread.php?t=175845
- Check your CPU Specs as Well. Many newer Filters are AVX2 Enabled with no AVX1 support(This is espeically True on VapourSynth side. Which will crash the software if your CPU doesn't support it.
- Lastly, Only Files that are Released with StaxRip are fully supported, This is done to make debugging easier. Also since all filters have been tested before release. Newer versions can have changes which have not been added to StaxRip yet.

**Describe the bug or Issue**
I met the same problem as https://github.com/staxrip/staxrip/issues/31. And I think the autoloading clash can be solved by add "try...except..." in the code. So how can I do it? Thanks a lot. (~~my English is poor...~~)

**Add The Proper Label**

**Step To Reproduce the Problem**

3. Using '...' Encoder
4. 'Avisynth or VapourSynth' Being Used 
6. Filter(s) x is being Used.
7. Any Major External Files tied to the Error.
8. Post Both your Log file & AVS/VS Script.
9. It it's Tied to Hardware Encoder Post your Hardware Specs along with the Following.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1803]
- Version [e.g. 1.9]
- FrameServer Being Used [e.g. Avisynth]
- Version of External Application / Filter Being Used [e.g. 2.9+10]
- List of Filters Being Used [e.g. QTGMC]
- Post your Logs, There Tell contain Allot of Information that Could Help.
- The More Information Posted, The Easier it will be to Debug.

**Additional context**
Add any other Information or additional context that can be Helpful.

**Please be Clear and as Detailed as Possible**

**Any Issues left unattended to for Length of Time will automatically be Closed Due and or Locked to inactivity**

**Comment by Revan654** [comment]
> I met the same problem as #31. And I think the autoloading clash can be solved by add "try...except..." in the code. So how can I do it? Thanks a lot. (my English is poor...)

Try catch will not safe guard you from everything, you also need to know how to work your self out of the catch statements or it's pointless to even have. 

Many of the issues are tied to directly to python (External) sources are very hard to impossible to at times to guard against to there runtime errors.
