### ISSUE TITLE
batch processing crash to desktop if source file not found

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#460]
if you have a queue of jobs lined up, and accidentally delete or move one of the source files in that queue before staxrip goes to process it, it will crash to desktop when that job starts and the file is not found. be good if this could be handled more gracefully (error message then skip over the job, like with other errors) as this can sometimes happen when working with large numbers of files if you're not careful, leading to the queue being interrupted until staxrip is manually reloaded and the queue restarted

**Comment by 44vince44** [comment]
Yes I guess a simple test of file exist, if fails, untick job, error message with counter, resume jobs processing.... right ?

**Comment by Statick** [comment]
yeah a simple test and error message is fine! just enough to keep the queue moving if you're not sat there watching it :)

**Comment by Dendraspis** [comment]
Would be nice if anybody could test this:
[StaxRip v2.1.7.3D_JobStop.zip](https://github.com/staxrip/staxrip/files/5843130/StaxRip.v2.1.7.3D_JobStop.zip)

**Comment by 44vince44** [comment]
OK I'm on it!

**Comment by 44vince44** [comment]
OK, I made some tests including several source files missing, it seems to work OK.
The message is left there, but the batch keeps running (no need to validate/close the error message).
If several sources missing, several messages are left on the screen, so at the end, the user has to validate them.
Well I think it's a good solution! Thanks @Dendraspis  👍

**Comment by Dendraspis** [comment]
@44vince44 
Thanks a lot! 

I've implemented it now, so it's available in the next beta.  😄
