### ISSUE TITLE
Please add NvEnc --vpp-colorspace options.

### ISSUE THREAD

**Issue by anthony75smith75** [staxrip/staxrip#461]
HDR looks terrible on my TVs with washed out blacks and faded color. Both TVs support HDR and show it as enabled when HDR content is present. However, the colors and blacks still look terrible compared to normal SDR which looks great. This HDR issue is well confirmed on the internet and Tone mapping HDR to SDR has become the current best solution. 

I use Staxrip with the Nvidia H265 encoder as this is much faster than x265 and retains excellent quality. Nvidia encoder supports fast hardware tone mapping using "--vpp-colorspace hdr2sdr=reinhard" command line option.  Currently we have to add this option manually in Encoder Options/Other/Custom. Works well with excellent results.

Can we have a "Colorspace Conversion" option added to the VPP GUI section of the NvEnc Encoder Options? Should include Reinhard, Hable and Mobius conversion options as a selection box. NvEnc supports a heap of manual options for Colorspace Conversions as well. These could be added too, perhaps at a later stage as I think most people will be happy with the 3 Auto selections listed above. 

Will be great to have the Colorspace options available in their proper easy place in the GUI so they can be used by the many and not have to be manually added by the very determined few.

**Comment by stax76** [comment]
I had added this to the list of ignored switches (so the test tool will not nag to implement it) because it's quite a bit work.

**Comment by Dendraspis** [comment]
@anthony75smith75 
Do you know how the options are combined?  
From the doc:

```
example1: convert from BT.601 -> BT.709
--vpp-colorspace matrix=smpte170m:bt709

example2: using hdr2sdr (hable tone-mapping)
--vpp-colorspace hdr2sdr=hable,source_peak=1000.0,ldr_nits=100.0
```

How does the command looks like, if `matrix` and `hdr2sdr` are both set at the same time? Or is one parameter only allowed? 🤔

**Comment by Dendraspis** [comment]
Okay, `--vpp-colorspace` is basically implemented and seems to work. Only ***hdr2sdr*** is missing yet, which I'm going to implement the next days.

**Comment by JJKylee** [comment]
Since HDR and SDR are acronyms, maybe it'd be better to put them in uppercase.

**Comment by JJKylee** [comment]
Will do when I get back to my place/pc after work in like 5 hours. I'm sure @44vince44 will join in the meantime. 😃

**Comment by 44vince44** [comment]
@JJKylee I never used nvenc (and i'm not willing to use it for many reasons), so i won't be a good tester for this particular matter.... and it's 11:30 pm :-(
Maybe i'll help you with it tomorrow.... need to be very fresh for the unknown things....

**Comment by Dendraspis** [comment]
We can also wait for @anthony75smith75 to test it.  🤓 

But I think it only needs little adjustments. 

@44vince44 
I'm curious what those reasons are. 😁

**Comment by 44vince44** [comment]
@Dendraspis you probably know them as well as i do:
1) there is no match to software encoding, especially when software encoder is being improved almost month !
2) how can I adjust or tweak color values if I don' have a preview !?

So I always go for x265, and Donald Graft's HDRtoSDR. In my opinion, the only proper way to use the nvidia card is to use CUDA, but not decoding, not encoding.
.

**Comment by anthony75smith75** [comment]
Thanks everyone. Will be happy to test new NvEnc colorspace options. Will do shortly. 44vince44 x265 is no doubt better than NvEnc but like 10 fold slower. Have found NvEnc quality to be excellent. As you know Nvidia have added dedicated hardware to the GPU die to handle the encoding and decoding processes. This hardware is light years ahead of older GPU implementations. Agree with you on point two though. A preview on tweak options would be terrific! However, I only occasionally need tweak and usually only have to move one of the options one notch, so not a deal breaker for me.

**Comment by anthony75smith75** [comment]
Loving this new Colorspace option within NvEnc options. Have done some testing and here are my findings.

Colorspaces tap needs to be broken down into two modes. Auto OR Manual. When Auto is selected we should be able to only select the HDR2SDR mode and options associated with HDR2SDR. Reinhart, hable, brightness, curves etc. Do not give the option of none. (Useless) The manual section and all of it’s settings at this stage should be shown as unset and greyed out so they cannot be changed or selected. If ALL manual settings are set to auto we actually get an encode error.

When Manual is selected. Start all manual settings on auto to auto unless we have VUI data indicating otherwise. (Source Matrix, Colorprim etc.) Default “To” sections to auto. Show another HDR2SDR section perhaps defaulted to BT2390 since “none” with all manual settings set to auto gives encode error. (Nothing to do?) Don’t allow this scenario or the option of “unset” in any manual modes. Unset returns encode failure errors. 

HDR enabled players read the VUI file data to mange HDR modes. This data needs to be updated in the file encode to match the HDR2SDR settings that were encoded. HDR2SDR on Auto always uses BT709 as it’s output formats. Auto mode does not change the
 video range.

The conversion speed and quality are excellent for HDR2SDR. Indeed a very useful and valuable feature addition to the NvEnc settings section. Much thanks to all who have helped.

**Comment by JJKylee** [comment]
1. Not bad, but some options are cropped at my UI scale factor.

![StaxRip_2 1 7 3_NVEnc_vpp-colorspace_20210119](https://user-images.githubusercontent.com/3157518/105138846-5318b380-5aaa-11eb-8d45-71fe9651b51f.jpg)

2. Why are encoder options windows not resizeable or scrollable?

3. Sometime the command line pane occupies too much space with empty lines below, but the pane itself is not resizeable, either.

![StaxRip_2 1 7 3_NVEnc_vpp-colorspace_NG_20210119](https://user-images.githubusercontent.com/3157518/105139912-c838b880-5aab-11eb-86ce-5d906c6b727a.jpg)

The size of the pane becomes different only after I disable some options. ☹️

And about @anthony75smith75's comment: HDR2SDR _none_ option is sometimes **necessary** when only colorspace features need to be corrected without tonemapping. 601 vs 709 is a good case. They have the same transfer characteristic but different color matrices and primaries. See [this post by poisondeathray](https://forum.doom9.org/showthread.php?p=1905737#post1905737) (and other related posts) on Doom9's thread.

**Comment by anthony75smith75** [comment]
Have observed the scaling issue on my system as well. Wonder why Windows can't provide a scroll bar on the side to deal with this issue? My suggestion relative to removing the "none" option was only in Auto mode as it does nothing in this scenario. Agree, it is still needed and should be available in Manual mode.

**Comment by Dendraspis** [comment]
> Not bad, but some options are cropped at my UI scale factor.
> Why are encoder options windows not resizeable or scrollable?

> Wonder why Windows can't provide a scroll bar on the side to deal with this issue?
 
Yeah, this is due to Windows and how StaxRip was designed many years ago. Would need a lot of work to change the UI.

> Sometime the command line pane occupies too much space with empty lines below, but the pane itself is not resizeable, either.

Interesting, I've never seen such a big and empty command line panel. 

> And about @anthony75smith75's comment: HDR2SDR _none_ option is sometimes **necessary** when only colorspace features need to be corrected without tonemapping. 601 vs 709 is a good case. They have the same transfer characteristic but different color matrices and primaries. See [this post by poisondeathray](https://forum.doom9.org/showthread.php?p=1905737#post1905737) (and other related posts) on Doom9's thread. So even if it's gone in the 'Auto' mode, it's definitely necessary in the 'Manual' mode.

I know, therefore it is there - and I'm not willed to remove possible settings.

I've rearranged the settings and it should be okay now. If anybody wants to test it before the next beta is released:
[StaxRip v2.1.7.3Dnvenc2.zip](https://github.com/staxrip/staxrip/files/5841640/StaxRip.v2.1.7.3Dnvenc2.zip)

Thanks for helping.  😊

**Comment by JJKylee** [comment]
> Yeah, this is due to Windows and how StaxRip was designed many years ago. Would need a lot of work to change the UI.

😭😭😭😭😭😭😭😭😭😭 

> Interesting, I've never seen such a big and empty command line panel. 😲

I'm truly surprised. 😮

> I've rearranged the settings and it should be okay now. If anybody wants to test it before the next beta is released:
> [StaxRip v2.1.7.3Dnvenc2.zip](https://github.com/staxrip/staxrip/files/5841640/StaxRip.v2.1.7.3Dnvenc2.zip)

![StaxRip_2 1 7 3_NVEnc_vpp-colorspace_20210120](https://user-images.githubusercontent.com/3157518/105177289-52e4dc00-5adb-11eb-8fcb-12e4433ad335.jpg)

I like this a LOT better. Thanks. 😄

**Comment by Dendraspis** [comment]
@44vince44 
> [..] and i'm not willing to use it for many reasons

> @Dendraspis you probably know them as well as i do:
>     1. there is no match to software encoding, especially when software encoder is being improved almost month !
>     2. how can I adjust or tweak color values if I don' have a preview !?

I asked, because I've expected a lot more than just 2 reasons.  🤣 

-------------
@JJKylee 
> I like this a LOT better. Thanks. 😄

Was the only solution - and it looks a lot better.  😁   Thanks for testing!

**Comment by 44vince44** [comment]
I'll test this evening, because i haven't had time yet, but the screenshots made by Jjkylee show a clean implementation!!
Nicely done @Dendraspis !
and yes you're right, "2" would translate better as "a couple of" instead of "many" 🤣

**Comment by 44vince44** [comment]
Well it seems OK, but @anthony75smith75 :

> HDR enabled players read the VUI file data to mange HDR modes. This data needs to be updated in the file encode to match the HDR2SDR settings that were encoded. 

Well, the (relevant) VUI data looks like this

```
HDR format : | SMPTE ST 2086, HDR10 compatible
Color primaries : | BT.2020
Transfer characteristics : | PQ
Matrix coefficients : | BT.2020 non-constant
Mastering display color primaries : | Display P3
Mastering display luminance : | min: 0.0500 cd/m2, max: 1200 cd/m2
```

How is it possible to derive from those all the HDR2SDR parameters (upto 11 parameters with Hable) ????
