### ISSUE TITLE
Request for AvsResize update

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#462]
https://forum.doom9.org/showthread.php?p=1933800#post1933800

Update AvsResize to the most recent version r5 by StvG. The current one(r1d) is kind of outdated.

See this Wiki page about AvsResize:

http://avisynth.nl/index.php/Avsresize

(I think it's more appropriate for the Website link on Apps Manager.)

The most noticeable changes are as follows:
Many pixel types are added.
z_BlackmanResize(), z_GaussResize(), and z_SincResize() compatibility aliases have been removed.
zimg(z.lib) is updated.

But since we only have z_ConvertFormat filter in AVS/VS Profiles, we just need to add additional option values as follows:

[AviSynth]

Convert | Format = z_ConvertFormat(pixel_type="$enter_text:Enter the Format You Wish to Convert to$", colorspace_op="$select:msg:Select Input Color Matrix;rgb;709;unspec;fcc;470bg;170m;240;ycgco;2020ncl;2020cl;chromancl;chromacl;ictcp$:$select:msg:Select Input Color Transfer;709;unspec;470m;470bg;601;240m;linear;log100;log316;xvycc;srgb;2020_10;2020_12;st2084;std-b67$:$select:msg:Select Input Color Primaries;709;unspec;470m;470bg;170m;240m;film;2020;st428;st431-2;st432-1;jedec-p22$:$select:msg:Select Pixel Range;limited;l;full;f$=>$select:msg:Select Output Color Matrix;rgb;709;unspec;fcc;470bg;170m;240;ycgco;2020ncl;2020cl;chromancl;chromacl;ictcp$:$select:msg:Select Output Color Transfer;709;unspec;470m;470bg;601;240m;linear;log100;log316;xvycc;srgb;2020_10;2020_12;st2084;std-b67$:$select:msg:Select Output Color Primaries;709;unspec;470m;470bg;170m;240m;film;2020;st428;st431-2;st432-1;jedec-p22$:$select:msg:Select Pixel Range;limited;l;full;f$", dither_type="$select:msg:Select Dither Type;none;ordered;random;error_diffusion$")

[VapourSynth]

Convert | Format = clip = core.avs.z_ConvertFormat(clip, pixel_type='$enter_text:Enter the Format You Wish to Convert to$', colorspace_op='$select:msg:Select Input Color Matrix;rgb;709;unspec;fcc;470bg;170m;240;ycgco;2020ncl;2020cl;chromancl;chromacl;ictcp$:$select:msg:Select Input Color Transfer;709;unspec;470m;470bg;601;240m;linear;log100;log316;xvycc;srgb;2020_10;2020_12;st2084;std-b67$:$select:msg:Select Input Color Primaries;709;unspec;470m;470bg;170m;240m;film;2020;st428;st431-2;st432-1;jedec-p22$:$select:msg:Select Pixel Range;limited;l;full;f$=>$select:msg:Select Output Color Matrix;rgb;709;unspec;fcc;470bg;170m;240;ycgco;2020ncl;2020cl;chromancl;chromacl;ictcp$:$select:msg:Select Output Color Transfer;709;unspec;470m;470bg;601;240m;linear;log100;log316;xvycc;srgb;2020_10;2020_12;st2084;std-b67$:$select:msg:Select Output Color Primaries;709;unspec;470m;470bg;170m;240m;film;2020;st428;st431-2;st432-1;jedec-p22$:$select:msg:Select Pixel Range;limited;l;full;f$', dither_type='$select:msg:Select Dither Type;none;ordered;random;error_diffusion$')
Since I incorporated all available values here, we can omit some values depending on use case.

z_ConvertFormat is indispensable in tonemapping, so this needs to be taken care of appropriately.

And don't forget to delete the three filters(z_BlackmanResize, z_GaussResize, z_SincResize) from Apps Manager.

**Comment by JJKylee** [comment]
Well, I thought this was not such a big issue to post here. 😄
But anyway, thanks for this though.

**Comment by 44vince44** [comment]
I think @stax76 copied it here because here is a better place to follow up bug corrections and feature requests. I think @JJKylee you should always post here !

**Comment by JJKylee** [comment]
I see. So I'm not gonna bug others in the forum with this kind of loooong source codes again. 😆
