### ISSUE TITLE
No persistent saved option menu

### ISSUE THREAD

**Issue by cacafuti8888** [staxrip/staxrip#467]
Hi, i select, Options, Audio or Subtitles, Preferred Laguages to All, and it doesn't do anithing, stays checked that way but when i load a file o restart the program it backs to the default

**Comment by 44vince44** [comment]
you have to **save the template** so the options are kept!

**Comment by cacafuti8888** [comment]
> Not a bug: you have to **save the template** so the options are kept!

My bad.....new in your program....Testing it and for now very happy.
