### ISSUE TITLE
Nvidia NvEnc Deinterlace Layout Improvements

### ISSUE THREAD

**Issue by anthony75smith75** [staxrip/staxrip#468]
Hi all. I use the Nvidia NvEnc encoder mostly and have found the current layout of Deinterlacing Options to be quite disjoint and confusing. Let me explain.

The situation is compounded by the fact that NvEnc supports 4 different Deinterlacing types: 
1: Basic Adaptive/Bob. Currently found under VPP/Misc.
2: Nedi Deinterlacer. Currently found under VPP/Field
3: Yadif. Currently found under VPP/Field.
4: AFS. Currently found under VPP/AFS.

In addition we have another important Field order flag found under “Other.” This must be set for options 2,3 and 4 above, otherwise we get encode error.

Could we rename ‘Field’ to ‘Deinterlace’. List important “Other” Deinterlace field order option here and then list the 4 different Deinterlace types, each in its own section.

To avoid encode error we also should only allow one type of Deinterlacer to be enabled at any one time. These simple layout changes will make management of the Deinterlace options much easier. Especially relative to the very easy missed and important option currently hidden under 'Other'.

Much thanks for your time and attention to detail on this one.

**Comment by JJKylee** [comment]
I agree.

And I think `AFS 2` should be combined with `AFS 1` as a submenu.

**Comment by JJKylee** [comment]
Too sad that @Dendraspis's Nvidia graphics card is broken at this time. 😭

**Comment by Dendraspis** [comment]
@JJKylee 
First I had no NVidea card. 😁 And I already answered this question: https://github.com/staxrip/staxrip/issues/456#issuecomment-766723750

I don't know when I'm willed to do those changes. At the moment I have too much to do, so when I have a few minutes left I spend them on things I use. 😟

**Comment by JJKylee** [comment]
> First I had no NVidea card. 😁 And I already answered this question: [#456 (comment)](https://github.com/staxrip/staxrip/issues/456#issuecomment-766723750)

Yeah, I already saw it. I'm sorry to hear that.

Maybe I was confused because we talked about NVEnc H.265 parameter settings in Discussions and then I read that your graphics card was broken. I thought you were not using NVEnc even though you were owning an Nvidia. 😝

Anyway... As for me, I'll be happy as long as this matter is taken care of sometime in the future. Not a big deal for now. 😄

**Comment by anthony75smith75** [comment]
Agree. This improvement can wait until certain Nvidia graphics cards are working again. Changes always need testing. I can and am happy to help on this front if needed. My Nvidia rig is up and go!

**Comment by Dendraspis** [comment]
Feel free to test this one - a good start?:
[StaxRip v2.1.7.5D_NVEnc.zip](https://github.com/staxrip/staxrip/files/5876786/StaxRip.v2.1.7.5D_NVEnc.zip)

> In addition we have another important Field order flag found under “Other.” This must be set for options 2,3 and 4 above, otherwise we get encode error.

Because it doesn't belong to *VPP* I can't move it there.  ***Other*** doesn't seem to be wrong, but any suggestions?

> To avoid encode error we also should only allow one type of Deinterlacer to be enabled at any one time. These simple layout changes will make management of the Deinterlace options much easier. Especially relative to the very easy missed and important option currently hidden under 'Other'.

Nice task, especially because the UI doesn't support such combinations yet.  🤔   And the docs doesn't tell that multiple sets are not allowed.  🙄

**Comment by JJKylee** [comment]
> Feel free to test this one - a good start?:
> [StaxRip v2.1.7.5D_NVEnc.zip](https://github.com/staxrip/staxrip/files/5876786/StaxRip.v2.1.7.5D_NVEnc.zip)

Looks good to me. 👍

> Because it doesn't belong to _VPP_ I can't move it there. _**Other**_ doesn't seem to be wrong, but any suggestions?

Well, then we can't help it. 🤷‍♂️
Maybe we better make a profile or template for this matter. 😅

**Comment by JJKylee** [comment]
> Feel free to test this one - a good start?:
> [StaxRip v2.1.7.5D_NVEnc.zip](https://github.com/staxrip/staxrip/files/5876786/StaxRip.v2.1.7.5D_NVEnc.zip)

Well, while trying this executable with NVEnc and qaac, I ran into this error in audio conversion from (cut) w64 to aac (by qaac):

```
System.ObjectDisposedException: cannot access a deleted object.
Object name: 'LabelProgressBar'
   Location: System.Windows.Forms.Control.CreateHandle()
   Location: System.Windows.Forms.Control.get_Handle()
   Location: System.Windows.Forms.Control.get_WindowText()
   Location: StaxRip.UI.LabelProgressBar.get_Text()
   Location: System.Windows.Forms.Control.set_Text(String value)
   Location: StaxRip.UI.LabelProgressBar.set_Text(String Value)
   Location: StaxRip.ProcController._Closure$__44-0._Lambda$__0()
   Location: System.Threading.Tasks.Task.Execute()
--- End of previous stack location trace where exception was thrown ---
   Location: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   Location: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   Location: System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   Location: StaxRip.ProcController.VB$StateMachine_44_SetText.MoveNext()
--- End of previous stack location trace where exception was thrown ---
   Location: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

The progress window for qaac dies but NVEnc still goes on as a zombie process.
Where does this error come from? A new progress status bar?
Can you please look into this?

**Comment by anthony75smith75** [comment]
Just had a look at the new layout changes. An improvement. If the layout interface can't restrict more than one option being ticked then presentation and labeling are very important. "Deinterlace" tab needs overall deinterlace field order setting listed first. Then we could show 4 Tick boxes with OR between them. 

[ ] 1: Standard Deinterlacer (Bob/Adaptive selection box) 
OR
[ ] 2: Yadif Deinterlacer (Options selection box) 
OR 
[ ] 3: Nnedi Deinterlacer
OR
[ ] 4: AFS (Auto Field Shift) Deinterlacer

The extra options could be left under their labeled sections. (Nnedi, AFS) But will Nnedi be greyed out in extra section if it's not ticked on first Interlace tab? 

Will test for the process window death bug shortly.

**Comment by Dendraspis** [comment]
@JJKylee 
Please stop double posting - it's totally confusing. 😁


Are you really sure, that you cannot set both  Yadif and AFS at the same time? 🤔

**Comment by anthony75smith75** [comment]
Yes we get a specific error stating that more than one deinterlace method is not supported.

**Comment by Dendraspis** [comment]
[StaxRip v2.1.7.5D_NVEnc2.zip](https://github.com/staxrip/staxrip/files/5879580/StaxRip.v2.1.7.5D_NVEnc2.zip)

The only solution. But there are 2 issues:
1. ***AFS 2*** is always shown
2. ***Standard Deinterlacer*** can always be selected, but its option and parameter will only be visible if the right decoder is set

**Comment by JJKylee** [comment]
For me, this couldn't be better. 👍
Right click help also works for each deinterlacing method if clicked a little below. 😄

**Comment by anthony75smith75** [comment]
Huge improvement! Much thanks. Sorry to keep harping. Can we please make a very small note to global deinterlace setting under 'other'? Couldn't get deinterlacing to work for months until I finally found that hidden setting.

**Comment by Dendraspis** [comment]
Okay, I think this is the way to go:
[StaxRip v2.1.7.5D_NVEnc3.zip](https://github.com/staxrip/staxrip/files/5880644/StaxRip.v2.1.7.5D_NVEnc3.zip)

**Comment by anthony75smith75** [comment]
Even better. Love the labels. Yadif (Yet Another DeInterlacing Filter) Not sure about nnedi. Have tested all options on previous enc2 version and found no problems. All layout changes working without any errors. Where have you moved global deinterlace field order option?

**Comment by Dendraspis** [comment]
....to ***Basic***, together with ***Input Colorspace***.

**Comment by anthony75smith75** [comment]
Yes much better spot than 'other' area. Well done. Thanks so much.

**Comment by Dendraspis** [comment]
The changes are commited for the next version, so I'll close this...
