### ISSUE TITLE
HDR Settings (Mastering display luminance) value is wrong

### ISSUE THREAD

**Issue by AlDocTHorXJ** [staxrip/staxrip#47]
**Notes Before Posting**
- Only Open an issue if it's tied to Staxrip, If issues is tied to external program or filter. Head to Resp page for that project and open an issue there. 
- Beta Releases are Not Covered, Beta Are Pre-Releases and Could Contain Bugs. This is the Risk Your Willing to Take When using Beta releases. Beta Concerns should be posted in the forums.
- If you Require Help with one of the FrameServers, Programs or Scripting Post in the Forums, Rather then opening a ticket here.
  Link: https://forum.doom9.org/showthread.php?t=175845
- Check your CPU Specs as Well. Many newer Filters are AVX2 Enabled with no AVX1 support(This is espeically True on VapourSynth side. Which will crash the software if your CPU doesn't support it.
- Lastly, Only Files that are Released with StaxRip are fully supported, This is done to make debugging easier. Also since all filters have been tested before release. Newer versions can have changes which have not been added to StaxRip yet.

**Describe the bug or Issue**
This is simple. Staxrip gets HDR meta tags from Mediainfo I think. 
I had this problem with HDR settings on Stax 2 (upto 2.0.4.0), but not in Stax 1.7

I have an HDR video with this info:
Mastering display luminance: min: 0.0050 cd/m2, max: 4000 cd/m2

Stax2.0 gives me(auto):
G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)

Stax1.7 gives me:
G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)
Which is the correct values.

**Add The Proper Label**

**Step To Reproduce the Problem**
Any HDR content that is not 0.001 / 1000
Just drag and drop it. Go to settings(x265)/vapoursynth

3. Using '...' Encoder
4. 'Avisynth or VapourSynth' Being Used 
6. Filter(s) x is being Used.
7. Any Major External Files tied to the Error.
8. Post Both your Log file & AVS/VS Script.
9. It it's Tied to Hardware Encoder Post your Hardware Specs along with the Following.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1803]
- Version [e.g. 1.9]
- FrameServer Being Used [e.g. Avisynth]
- Version of External Application / Filter Being Used [e.g. 2.9+10]
- List of Filters Being Used [e.g. QTGMC]
- Post your Logs, There Tell contain Allot of Information that Could Help.
- The More Information Posted, The Easier it will be to Debug.

**Additional context**
Also, There are other switches of x265 is enabled. are they really necessary?
--repeat-headers 
--hrd
--aud

I don't think these are related to HDR. correct me if I'm wrong.
on the other hands, --hdr is enabled which is a good thing but --hdr-opt is not enabled by default which I think it should. 

Anything else? I'm there for you

**Please be Clear and as Detailed as Possible**

**Any Issues left unattended to for Length of Time will automatically be Closed Due and or Locked to inactivity**

**Comment by Revan654** [comment]
1.7 used MediaInfo when used with Color coordinate system, Which no longer exists in MediaInfo. 

Plus, HDR Mastering display Changes based on the colorgrading, If it targets P3, BT 2020, DCI, etc...

Masterdisplay of G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) is wrong.

I have no idea where 40000000 came from but it was wrong. It's way beyond the scope of BT.2020 Luminous.

and yes these switches are tied to HDR to correctly inject the right Metadata into the container.

Not all the switches are automatic enabled. Still need to the settings like GOP and such.

if you need Proof this is directly from Studio Encoded Sample Video.

![HDR+Metadata+Key-Value+Pairs+Text+File](https://user-images.githubusercontent.com/38091898/64367449-fff1ae00-cfe5-11e9-994c-1d27b312967d.png)
