### ISSUE TITLE
2.1.7.3: x265 Profile field width becomes different b/w 8-bit and 10-bit

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#472]
**Describe the bug**
See this screen capture.

![StaxRip_2 1 7 3_x265_Options-window_profile-field_size_20210122](https://user-images.githubusercontent.com/3157518/105473831-6a92a080-5c52-11eb-8578-b880f2e4f484.gif)

**Expected behavior**
The width is supposed to remain the same. 😄

I know this is trivial, but... you know. 😓

**Comment by Dendraspis** [comment]
This is not a bug .... it's a feature!

😋  I'll fix it if I'm able to fix my PC first. 😟

**Comment by 44vince44** [comment]
What happened to your PC @Dendraspis ???

**Comment by Dendraspis** [comment]
@44vince44 
Right before posting this I wanted to check an encode. The player opened, started loading and then: black screen.
Seems like my video card is in heaven. Can't boot anymore. And the best: you can't buy video cards at the moment .. almost all sold out. 😟

**Comment by JJKylee** [comment]
OMG!!!! At this time???
My deepest condolences, @Dendraspis. 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭

**Comment by 44vince44** [comment]
Oh my :-(( bad timing... I'm so sorry !!! Sometimes video cards do fail like this, but most often it doesn't behave like this. It could be the power supply box inside the desktop. It could be ANY connector or card on your motherboard, Please check that they are properly inserted. it could be the motherboard itself. (I used to assemble many machines between 2000 and 2007, maybe I assembled more than 500 ! And I remember how painful it used to be).
You can do the following test to be sure that the fault comes from the graphic card
- if your motherboard has a basic embedded graphic card, then try removing your graphic card and use the embedded one
- if your motherboard does not have an embedded graphic card, then if you remove your graphic card, and boot, you should get a different "bip" sound...

**Comment by stax76** [comment]
@Dendraspis 
I'm sorry about the PC defect.

There was a wrong definition, main444-mainstillpicture instead of main444-stillpicture, and because the text was long the option control did auto expand. The max length for the compact size was 23 characters, but I changed it now to 24 characters.

**Comment by Dendraspis** [comment]
Thanks for your kind words!

@44vince44 
Thanks, but I know what to do. 😊
Sadly it's 99% save that the videocard is causing it. 😟
