### ISSUE TITLE
Maybe there is a better solution than soft links

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#473]
Maybe the soft link solution can and should be replaced and should have never happened in the first place.

It could work like so:

All apps that use AviSynth and don't support using a custom AviSynth DLL path are located in the folder of AviSynth at:

Apps\FrameServer\AviSynth

Now if the user wants to use an installed AviSynth and enables it in the settings, staxrip will move the avisynth.dll file to another folder, for instance a sub folder of Apps\FrameServer\AviSynth

The only requirement for this to work is write access to move the file, I think and hope that this would work and be a better solution.

**Comment by DJATOM** [comment]
I have implemented custom library loading via `--reader-options library=...` for my mod and it will make into next build, but you still have to find someone interested to implement such feature for x264 and ffmpeg (probably it's not so hard for me to do that for x264 but ffmpeg has much more complex codebase and I don't have much experience implementing options there).

**Comment by stax76** [comment]
That will be very helpful, thank you, to my awareness this will be the last missed feature.

**Comment by 44vince44** [comment]
@stax76

> The only requirement for this to work is write access to move the file, I think and hope that this would work and be a better solution.

As long as you have file access permission requirements of any kind, the solution will not be perfect. You'll end up with the same issues.

**Comment by stax76** [comment]
It's also a permission problem, the question is how does it compare to the current permission problem, I think the current problem is worse.

**Comment by 44vince44** [comment]
I agree, But as long as there remains a problem, I really think you shouldn't waste your time. 
If you find a solution with 0 problems, then it could be worth to code.

**Comment by JJKylee** [comment]
But then the program tree structure becomes messed up. ☹️
And what about VapourSynth? Is there not any problem with moving app binaries to AviSynth folder?

**Comment by stax76** [comment]
It should not make a difference for vapoursynth, program structure would be OK I think, it's only ffmpeg, x264 and vceenc where only vceenc has multiple files, but since nvenc and qsvenc already support a custom avisynth dll path, it's probably realistic to get it for vceenc too. I don't mind spending a few hours if the result is better.

**Comment by JJKylee** [comment]
I see.

**Comment by 44vince44** [comment]
I vote for changing nothing !!! 😁

**Comment by JJKylee** [comment]
Personally, I second with @44vince44 in this matter.
But if @stax76 thinks the change is more desirable and inevitable, then... you know... 😅

**Comment by Dendraspis** [comment]
> BTW, I didn't know that so many people would have a hard time setting up a soft link in their system in the first place. 😮

It should be easy, if you place StaxRip where you have all rights - or (better) if you have control over your own system!

Nonetheless it's interesting following this whole topic. 😋

**Comment by JJKylee** [comment]
> > BTW, I didn't know that so many people would have a hard time setting up a soft link in their system in the first place. 😮
> 
> It should be easy, if you place StaxRip where you have all rights - or (better) if you have control over your own system!

I know. I'm just saying I'm curious what kind of situation makes them use a system they don't have control over. Putting StaxRip on a PC that's not accessible except via a network? Or on a PC they're not allowed to modify at all? Hmm... Interesting... 🤔

**Comment by 44vince44** [comment]
@JJKylee actually putting the staxrip folder inside Program Files as is (that location is user write protected) is enough to cause problems.
The fact is that some people must understand that Staxrip is a **portable software**.
Either you disable the portable features, or put it in a place where you have full control as user, or start Staxrip once as admin. 
Easy.

**Comment by stax76** [comment]
> actually putting the staxrip folder inside Program Files as is (that location is user write protected) is enough to cause problems.

If a normal user with an admin account copies a folder into Program Files then everything inside the folder is not protected.

**Comment by stax76** [comment]
I checked the vceenc console help, --avsdll is already supported, so it's only ffmpeg and x264.

**Comment by 44vince44** [comment]
> If a normal user with an admin account copies a folder into Program Files then everything inside the folder is not protected.

Yes indeed, and if not, he can do the other easy things...

> I checked the vceenc console help, --avsdll is already supported, so it's only ffmpeg and x264.

Thumbs up Rigaya ;=)

**Comment by stax76** [comment]
I've removed the soft link solution now, it was difficult to maintain due to high complexity.

Since I made a small change after the beta release I uploaded a hotfix.

**Comment by JJKylee** [comment]
While launching 2.1.7.8 Beta (with `StaxRip.exe` replaced with the _hotfix_) the **first time**, I ran into this error pop-up.

```
------------------------- System Environment -------------------------

StaxRip    : 2.1.7.8
Windows    : Windows 10 Home 2009
Language   : English (United States)
CPU        : Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
GPU        : NVIDIA GeForce GTX 1060 with Max-Q Design, Intel(R) HD Graphics 630
Resolution : 2560 x 1080
DPI        : 120
Code Page  : 65001

------------------------------ Exception ------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.FrameServerHelp.IsAviSynth()
   at StaxRip.FrameServerHelp.AviSynthToolPath()
   at StaxRip.Package.LoadConfAll()
   at StaxRip.Package._Closure$__._Lambda$__489-98()
   at StaxRip.GlobalClass._Closure$__188-0._Lambda$__0()
```

If I force close the main window ingoring the errors and relaunch it, the error disappears and does not pop up again.

IMHO, this is because `Settings.dat` is missing on the first launch. By contrast, overwriting binaries (except for Apps folder) on the existing ones does not raise this issue on the first launch of this new version.

For your reference, I have an installed AviSynth 3.7.0 on `C:\WINDOWS\system32\AviSynth.dll`.

**Comment by JJKylee** [comment]
And I've found that even if I change the setting to _Use installed directly_ for AviSynth Frameserver, `ffmpeg.exe` remains in the same folder as the portable `AviSynth.dll`. (I have a _full_ write access in the corresponding StaxRip folder.)

If so, wouldn't `ffmpeg.exe` be still using the **portable** _dll_ instead of the installed one in the system? 🤔

**Comment by JJKylee** [comment]
OK.
Let me just report separate issues regarding the two matters mentioned above so that we can easily keep track of them.

**Comment by stax76** [comment]
I've uploaded a new hotfix.

I don't know why the exception happened, but the code wasn't important, so I removed it.

> And I've found that even if I change the setting to Use installed directly for AviSynth Frameserver, ffmpeg.exe remains in the same folder as the portable AviSynth.dll. (I have a full write access in the corresponding StaxRip folder.)

This is probably because ffmpeg is not in use, files are only moved if absolutely necessary.

> I'm not sure if this feature is implemented, but... if a user without any installed frameserver in the system tries to change the setting to use it, shouldn't he be warned about it? (Correct me if I'm wrong.)

There is now a warning and correction.
