### ISSUE TITLE
Unable to produce x265 Main10 4:4:4 video

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#474]
**Describe the bug**
H264 input video with 4:4:4 chroma subsampling does not convert with x265 to 4:4:4.  The video is being converted to 4:2:0.

**Expected behavior**
4:4:4 output video.

**How to reproduce the issue**

Choose a source video with 4:4:4 chroma subsampling
Change x265 profile to Main 4:4:4 10
(Optional) - Force Input CSP to I444
Add job and encode the video.
Check resulting video with MediaInfo - You will notice that Chroma subsampling is being reported as 4:2:0

**Additional Notes**
I used OBS to create an H264 Lossless video using NVENC (New), with Full color range, and 4:4:4 chroma subsampling.  This is the video I used for my source in StaxRip.

**StaxRip Version:**
v2.1.7.3-beta

**x265 version:**
3.4+62-aMod-gcc10.2.1-hdr10-info

**Comment by 44vince44** [comment]
@Neltulz 
In settings>video, is the option "Add filter to convert chroma to 4:2:0" selected? you should remove it and try.

**Comment by Neltulz** [comment]
> @Neltulz
> In settings>video, is the option "Add filter to convert chroma to 4:2:0" selected? you should remove it and try.

That's probably it!  I will give it a try.  Thank you.
