### ISSUE TITLE
Vapoursynth VSSCript.dll is called in x265 command but not Avisynth.dll...

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#475]
**Describe the bug**
The following switch is added IN A Avisynth mode encode;
--reader-options library="D:\Downloads\_IDM Downloads\StaxRip-x64-2.1.7.4-Beta\Apps\FrameServer\VapourSynth\VSScript.dll"

**Expected behavior**
No call should be made to anything related to Vapoursynth when using Avisynth !!!!

**Comment by stax76** [comment]
Oh sorry, there should **now** be a hotfix, and a new beta build in a few minutes.

**Comment by 44vince44** [comment]
Testing hotfix now

**Comment by 44vince44** [comment]
It appears fixed indeed! (thanks for the immediate response :smile. I will do some more tests tomorrow!

**Comment by 44vince44** [comment]
@stax76 I closed this maybe too early, Shouldn't this be used to locate the internal avisynth.dll file, when in AVS mode ?

**Comment by Patman86** [comment]
> @stax76 I closed this maybe too early, Shouldn't this be used to locate the internal avisynth.dll file, when in AVS mode ?

At least that's the rationale behind this option ...

**Comment by stax76** [comment]
I think it was announced, but not yet released.

**Comment by 44vince44** [comment]
ok i'm closing this.. for now...
