### ISSUE TITLE
FFT3dGPU update and parameter change

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#477]
Hi you guys doing great work thanks.

I see new version FFT3dGPU can you implement to staxrip its now support 10bit videos.

https://github.com/pinterf/FFT3dGPU

Also im currently using staxrip v2130 i asume this parameter not change for new version of staxrip default parameters of fft3dgpu in stax like this

FFT3DGPU(sigma=1.5, bt=5, bw=32, bh=32, ow=16, oh=16, sharpen=0.4, NVPerf=False)

but bt=5 only supported by FFT3DFilter for FFT3DGPU maximum bt=4 but bt=3 run more stably and fast this should be change other parameters all good.

**Comment by JJKylee** [comment]
Wow! Thanks for the info, @darkcity87.

BTW, the website info is also missing for FFT3DGPU as of now. Please add it as well. 😉

**Comment by darkcity87** [comment]
It was fast thanks.
