### ISSUE TITLE
How to load a .vpy file as a script?

### ISSUE THREAD

**Issue by wzunknown** [staxrip/staxrip#48]
**Notes Before Posting**
- Only Open an issue if it's tied to Staxrip, If issues is tied to external program or filter. Head to Resp page for that project and open an issue there. 
- Beta Releases are Not Covered, Beta Are Pre-Releases and Could Contain Bugs. This is the Risk Your Willing to Take When using Beta releases. Beta Concerns should be posted in the forums.
- If you Require Help with one of the FrameServers, Programs or Scripting Post in the Forums, Rather then opening a ticket here.
  Link: https://forum.doom9.org/showthread.php?t=175845
- Check your CPU Specs as Well. Many newer Filters are AVX2 Enabled with no AVX1 support(This is espeically True on VapourSynth side. Which will crash the software if your CPU doesn't support it.
- Lastly, Only Files that are Released with StaxRip are fully supported, This is done to make debugging easier. Also since all filters have been tested before release. Newer versions can have changes which have not been added to StaxRip yet.

**Describe the bug or Issue**
I load the .vpy file as a source file. But it failed and gives messages,
```
Failed to load script.

Python exception: name 'core' is not defined

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
  File "D:\else\BDrip\ngnl0_00003\00003_temp\00003_source.vpy", line 5, in <module>
    core.std.LoadPlugin(r"D:\software\BD tools\StaxRip\Apps\Plugins\vs\fmtconv\fmtconv.dll")
NameError: name 'core' is not defined
```
And I check the file staxrip generated called "%filename%_source.vpy", it added some code before my own script.
```
import importlib.machinery
mvsfunc = importlib.machinery.SourceFileLoader('mvsfunc', r"D:\software\BD tools\StaxRip\Apps\Plugins\VS\Scripts\mvsfunc.py").load_module()
adjust = importlib.machinery.SourceFileLoader('adjust', r"D:\software\BD tools\StaxRip\Apps\Plugins\VS\Scripts\adjust.py").load_module()
havsfunc = importlib.machinery.SourceFileLoader('havsfunc', r"D:\software\BD tools\StaxRip\Apps\Plugins\VS\Scripts\havsfunc.py").load_module()
core.std.LoadPlugin(r"D:\software\BD tools\StaxRip\Apps\Plugins\vs\fmtconv\fmtconv.dll")
...(contiinue to load a lot of plugins)
```
I think the problem is that it didn't define variable "core" before using "core.std.LoadPlugin(...)". So how can I load a .vpy script correctly? Thanks a lot!

**Add The Proper Label**

**Step To Reproduce the Problem**

3. Using '...' Encoder
4. 'Avisynth or VapourSynth' Being Used 
6. Filter(s) x is being Used.
7. Any Major External Files tied to the Error.
8. Post Both your Log file & AVS/VS Script.
9. It it's Tied to Hardware Encoder Post your Hardware Specs along with the Following.

**Screenshots**
![Snipaste_2019-09-06_14-53-56](https://user-images.githubusercontent.com/32328286/64407238-70680000-d0b6-11e9-8e15-06cb937d41d6.png)
![Snipaste_2019-09-06_14-54-15](https://user-images.githubusercontent.com/32328286/64407247-778f0e00-d0b6-11e9-9fbe-b47038b84c1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1903
- Version 2.0.4.0 stable

**Additional context**
Add any other Information or additional context that can be Helpful.

**Please be Clear and as Detailed as Possible**

**Any Issues left unattended to for Length of Time will automatically be Closed Due and or Locked to inactivity**

**Comment by stax76** [comment]
Please post the code of the script you want to import but not as screenshot but in text format.

If possible, omit the code parts that are not relevant to reproduce it.

I tried to import a basic script and had no problem.

**Comment by wzunknown** [comment]
This is my script:
```
import vapoursynth as vs
import sys, os

import havsfunc as haf
import mvsfunc as mvf

core = vs.get_core(threads=8)
core.max_cache_size = 4000

src8 = core.lsmas.LWLibavSource(r"D:\else\BDrip\ngnl0_00003\00003.m2ts",format="yuv420p8",threads=1)
src16 = core.fmtc.bitdepth(src8, bits=16).std.Trim(605, 707)

dn = core.knlm.KNLMeansCL(src16, d=1, a=2, s=4, h=0.8, channels='Y', device_type="gpu")
dn = core.knlm.KNLMeansCL(dn, d=1, a=2, s=4, h=0.8, channels='UV', device_type="gpu")

db = core.f3kdb.Deband(dn, range=15, y=32, cb=64, cr=64, grainy=0, grainc=0, output_depth=16)
db = core.fmtc.bitdepth(db, bits=10)
db.set_output()
```

**Comment by stax76** [comment]
Only problem I found was showing the preview which is fixed in the last beta.

https://forum.doom9.org/showthread.php?p=1884662#post1884662
