### ISSUE TITLE
NVEnc: add a new vpp filter --vpp-warpsharp introduced in NVEnc 5.26

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#484]
**Describe the solution you'd like**

Please add this _new_ vpp filter in the NVEnc options menu.
For reference, see [this](https://github.com/rigaya/NVEnc/issues/294), or [this](https://github.com/dubhater/vapoursynth-awarpsharp2).

The inline help is as follows:

```
--vpp-warpsharp [<param1>=<value>][,<param2>=<value>][...]
    warpsharp filter to enhance edge.
params
    threshold=<float>         edge mask threshold (default=0.0, 0-255)
    blur=<int>                number of times to blur the edge mask.
                                (default=0, 0-)
    type=<int>                blur type, 0...13x13, 1...5x5 (default=2)
    depth=<float>             how far to warp (default=0.0, -128 - 128)
```
But I think `type` `default=2` is a typo: maybe it's `0`. This needs confirmation.
=> It's `0` according to the [online manual](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md).

**Explain why the feature matters to you**

It's a new edge sharpening CUDA filter added in this version.

**Comment by Dendraspis** [comment]
Check the changelog, it's already implemented since a few hours. 🤓 😁

But I took the parameter ranges and defaults from the docs, that are annoying different! For NVEnc I tend to stick to the docs, because they are really detailed and seem up to date.

@stax76 
Could you also update NVEnc for the next beta?
https://github.com/rigaya/NVEnc/releases

**Comment by JJKylee** [comment]
You're as fast as a rocket! 🚀😮😆😓

**Comment by Dendraspis** [comment]
@JJKylee 
If you wanna test the new feature: [StaxRip v2.1.7.5D_Warp.zip](https://github.com/staxrip/staxrip/files/5903783/StaxRip.v2.1.7.5D_Warp.zip)

**Comment by JJKylee** [comment]
> If you wanna test the new feature: [StaxRip v2.1.7.5D_Warp.zip](https://github.com/staxrip/staxrip/files/5903783/StaxRip.v2.1.7.5D_Warp.zip)

It seems to be well implemented. 👍

BTW, why is the NVEnc console help totally wrong about this option? 😖
I feel kind'a relieved to see that rigaya is also suffering from the same kind of hastiness as I am. 😝

**Comment by Dendraspis** [comment]
> BTW, why is the NVEnc console help totally wrong about this option? 😖

I couldn't resist to ask:
rigaya/NVEnc#304
Maybe just a forgotten build step, but I would guess the next release will be okay, because the source is okay.  ☺️
