### ISSUE TITLE
R9 5950X is not 100% used

### ISSUE THREAD

**Issue by Harybo** [staxrip/staxrip#485]
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).

Hello,

I am coming to you to find out if there would be a solution or a parameter changed so that my Ryzen 9 5950x is fully used at 100% when encoding 4k / x265

Thanks You

**Comment by DJATOM** [comment]
Put more frame threads and cores will be saturated higher. Also play with pme/pmode, that might give you additional core saturation.

**Comment by Dendraspis** [comment]
You can run multiple instances parallel encoding different files or you can use ***Chunks***:

<img src="https://user-images.githubusercontent.com/50659978/106601396-df6faf80-655b-11eb-928a-23926649d411.PNG">

**Comment by Harybo** [comment]
ok, nice thanks

**Comment by Harybo** [comment]
> Put more frame threads and cores will be saturated higher. Also play with pme/pmode, that might give you additional core saturation.

I tested pme, it doesn't change the processing time, but it uses all my processor.
For pmode it uses the whole processor but it doubles the processing time.
So for me for the moment not yet found a real good solution

**Comment by JJKylee** [comment]
So then what about chunks? Have you tried them?

**Comment by Harybo** [comment]
> Alors qu'en est-il des morceaux? Les avez-vous essayés?

I will try, I will tell you

**Comment by JJKylee** [comment]
Wow... I can speak French. 😮😓

**Comment by Harybo** [comment]
> Wow... I can speak French. 😮😓

ah ah merci alors pour les chunks, ça doit normalement rajouter un argument dans les lignes de sortie x265 ?

**Comment by Harybo** [comment]
ah je viens de comprendre, j'ai mit 4 chunks mais il m'en a fait que 2, bizarre mais ça à l'air de fonctionner. je vous tient au jus de la suite

**Comment by Harybo** [comment]
rectification, il prend juste son temps à lancer les autres chunks

**Comment by Dendraspis** [comment]
@JJKylee 
What have you done??  😂😝😂  Can't stop laughing.. 😂

**Comment by JJKylee** [comment]
IDK. Maybe @Harybo is using an auto-translation tool. 😓
Sorry, @Harybo, it was a joke that I can speak French. I said that because I found your quote of my reply was (automatically) translated into French. 😝 I can't speak French -- mostly. 😄

**Comment by Harybo** [comment]
I test all that or keep you up

**Comment by Dendraspis** [comment]
> IDK. Maybe @Harybo is using an auto-translation tool. 😓

Maybe??? 😂😂😂  It just keeps getting better! 😁

And don't let us forget running multiple instances at the same time - as already mentioned.

**Comment by 44vince44** [comment]
@Harybo 
Staxrip découpe en plusieurs morceaux ta video pour les traiter en parallele. A la fin du traitement, les chunks sont recollés.
Si tu veux qu'il fasse les 4 chunks en meme temps, tu peux aller dans SETTINGS > GENERAL> "Maximum Number of parallel processed" : mets 4.

Je te conseille de laisser 3. Si tu vois que t'es encore loin des 100% CPU, passe a 4.

**Comment by Harybo** [comment]
> @Harybo
> Staxrip découpe en plusieurs morceaux ta video pour les traiter en parallele. A la fin du traitement, les chunks sont recollés.
> Mettre chunks=4 ne suffit pas: si tu veux qu'il fasse vraiment les 4 chunks en meme temps, tu peux aller dans SETTINGS > GENERAL> "Maximum Number of parallel processed" : mets 4 ou 5.
> 
> Je te conseille de laisser 3. Si tu vois que t'es encore loin des 100% CPU, passe a 4.
> 
> Au debut, il fait le traitement de la piste audio, C'est pour ça qu'il y a toujours un chunk qui se lance apres les autres!

Merci pour les infos. Je vais test tout ça

**Comment by Harybo** [comment]
> @Harybo
> Staxrip découpe en plusieurs morceaux ta video pour les traiter en parallele. A la fin du traitement, les chunks sont recollés.
> Mettre chunks=4 ne suffit pas: si tu veux qu'il fasse vraiment les 4 chunks en meme temps, tu peux aller dans SETTINGS > GENERAL> "Maximum Number of parallel processed" : mets 4 ou 5.
> 
> Je te conseille de laisser 3. Si tu vois que t'es encore loin des 100% CPU, passe a 4.
> 
> Au debut, il fait le traitement de la piste audio, C'est pour ça qu'il y a toujours un chunk qui se lance apres les autres!

Nickel, super solution, tout fonctionne bien
