### ISSUE TITLE
Vapoursynth Script Import Error on System Installation

### ISSUE THREAD

**Issue by shirt-dev** [staxrip/staxrip#486]
**Describe the bug**
Vapoursynth script import fails when importing a script using the system Vapoursynth installation.

**Expected behavior**
The script should load and be encodable.

**How to reproduce the issue**
The issue occurs with any Vapoursynth script. I cannot reproduce the error on any other encoder.

**Provide information**

```
Script Error

Python exception: name 'vs' is not defined

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
  File "C:\Users\shirt\Downloads\thing_temp\thing_source.vpy", line 3, in <module>
    clip = vs.get_output()
NameError: name 'vs' is not defined
```

Tested on StaxRip-x64-2.1.7.0-Stable and StaxRip-x64-2.1.7.5-Beta.

**Additional context**
Occurs with an imported script.

**Comment by JJKylee** [comment]
`Python exception: name 'vs' is not defined` occurs since the following line does not work in the `vpy` script.

```
import vapoursynth as vs
```

Make sure your VapourSynth installation is working OK by testing the `vpy` script in other apps such as [VapourSynth Editor](https://bitbucket.org/mystery_keeper/vapoursynth-editor/), etc.

And just in case, don't forget that VapourSynth works with Python 3.8.x, but _not_ with Python 3.9.x.

**Comment by shirt-dev** [comment]
I mean that's what it says on the script that StaxRip generated on https://github.com/staxrip/staxrip/blob/56b81d2985007f9e2b00f26afd3e45e0bc126ed6/Forms/MainForm.vb#L2158

**Comment by JJKylee** [comment]
In `import vapoursynth as vs`, what matters here is `vapoursynth`. If Python cannot find a module named `vapoursynth` in the system, then the `import` step fails. That's what the error tells you. That's why I'm asking whether your VapourSynth installation is OK or not.

So, if 'your' script does not have the _problematic line_, is your script (aside from StaxRip) working OK on your system?

**Comment by shirt-dev** [comment]
Yes, it works on my system with VSPipe and python, my script is below.
```
import vapoursynth as vs
import havsfunc as hvs

core = vs.core

img_file = 'E:\\videos\\copyrightsucks.png'
src_file = 'E:\\videos\\video.mkv'

src = core.ffms2.Source(src_file)
copyrightsucks = core.ffms2.Source(img_file, alpha=True, format=vs.YUV420P8)

clip = hvs.Overlay(src, copyrightsucks[0], mask=copyrightsucks[1])
clip.set_output()
```

**Comment by shirt-dev** [comment]
Another thing that I noticed is that the generated script never imports vapoursynth, but then calls it.
```
from importlib.machinery import SourceFileLoader
SourceFileLoader('clip', r"C:\Users\shirt\Downloads\copyrightsucks.vpy").load_module()
clip = vs.get_output()
```

**Comment by shirt-dev** [comment]
I can reproduce the issue on this build as well.

Just to clarify, this happens when I try to encode an already existing VS script.

**Comment by JJKylee** [comment]
Let's clarify this: is there 'import existing VS script' feature in StaxRip? Or am I missing anything? ❓

**Comment by Dendraspis** [comment]
> Just to clarify, this happens when I try to encode an already existing VS script.

So you have overwritten the generated one?  🤔

**Comment by shirt-dev** [comment]
> > Just to clarify, this happens when I try to encode an already existing VS script.
> 
> ~So you have overwritten the generated one?~ 🤔
> 
> Okay, so you have opened _**"C:\Users\shirt\Downloads\copyrightsucks.vpy"**_ instead of a media file, is that correct?
> Because this is the only way to get the result you get.
> 
> @JJKylee
> _**File » Open Video File » Single File**_ and select a _**VPY**_ file and you'll get the message. 😉

Yes

**Comment by JJKylee** [comment]
> _**File » Open Video File » Single File**_ and select a _**VPY**_ file and you'll get the message. 😉

Wow... That's a very wild use case. 😓
I never imagined I could open a `vpy` file instead of a _video_ file. 😝
If I were in your shoes, I would use another VS editor, not StaxRip.

But anyway, IMHO, it's kind'a up to @stax76 whether this will be accepted as a _usual_ bug or not. 😄

**Comment by Dendraspis** [comment]
As far as I am concerned this is not possible.
After opening the source file you can copy your code into the Code Editor, but importing a script would break almost everything in StaxRip.

> I never imagined I could open a `vpy` file instead of a video file. 😝

Therefore it's called `Open Video File.  😁

**Comment by shirt-dev** [comment]
Gotcha, would be a cool feature addition but totally makes sense as to why you wouldn't want to support it LOL.

**Comment by shirt-dev** [comment]
I just assumed that it was supported as there's code for processing them as input scripts.

```
ElseIf p.SourceFile.Ext = "vpy" Then
                p.Script.Engine = ScriptEngine.VapourSynth
                p.Script.Filters.Clear()
                Dim code = "from importlib.machinery import SourceFileLoader" + BR +
                           $"SourceFileLoader('clip', r""{p.SourceFile}"").load_module()" + BR +
                           "clip = vs.get_output()"
                p.Script.Filters.Add(New VideoFilter("Source", "VS Script Import", code))
            End If
```

**Comment by Dendraspis** [comment]
Maybe it was planned or it has a different reason, but as you already saw it doesn't work as intended.

Regarding your ability to browse the code:  Implement the feature by yourself and create a pull request.  😉  😁

**Comment by shirt-dev** [comment]
Awesome, I'll try it!

**Comment by DJATOM** [comment]
I tried that first and it didn't work for me. So i had to open m2ts files directly for testing things eith staxrip 😅

**Comment by stax76** [comment]
> I just assumed that it was supported as there's code for processing them as input scripts.

I've worked on it but couldn't make it. For avisynth I believe it's supported. But for vapoursynth it's much more challenging.

**Comment by stax76** [comment]
Or maybe I just had a bad day or was drunk, hotfix is online.
