### ISSUE TITLE
It's normal?

### ISSUE THREAD

**Issue by ZeroCool22** [staxrip/staxrip#49]
First of all thx for this great program!

**PC Specs:**

I7 77OOK **|** CORSAIR 32 GB **|** MSI GTX 1080TI 11GB GAMING X.

**Nvidia Drivers:** 436.15 STANDARD - Game Ready.

**Version of the program:** StaxRip-x64-**2.0.3.0**-stable

I mostly was searching for a good video convertor for use H265 so i can take adavantage of the GPU.
And after trying a lot of convertors with CUDA capability, i just found StaxRip and seems to be really fast.

But the only way i could make the program to **use my GPU** is applying this setting:

![Screenshot_5](https://user-images.githubusercontent.com/13344308/64482293-87494800-d1c5-11e9-8944-a874bc825155.png)

If i let it with **"CPU will sleep when waiting for GPU task"** it only use CPU and not GPU.

And the **usage** of CPU & GPU is this:

![Screenshot_4](https://user-images.githubusercontent.com/13344308/64482304-c8415c80-d1c5-11e9-8358-f8595df48219.png)

If you look at the Task Manager it says the GPU usage if about **50%** but if you look at the bottom of the program screen console it says **9%**.

Is there a way i can make the program use **more the GPU and less CPU**?

Thx in advance!

**Comment by stax76** [comment]
I don't know, you can try asking on the NVEnc tracker:

https://github.com/rigaya/NVEnc/issues
