### ISSUE TITLE
2.1.7.8: 'Use installed directly' (for frameserver) does not move ffmpeg.exe to a separate folder

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#491]
**Describe the bug**
Even if I change the setting to `Use installed directly` for AviSynth Frameserver, `ffmpeg.exe` remains in the _same_ folder as the _portable_ `AviSynth.dll`. (I have a full write access in the corresponding StaxRip folder.)

![StaxRip_2 1 7 8_ffmpeg exe_does-not-move_20210206](https://user-images.githubusercontent.com/3157518/107130733-69ce5100-6885-11eb-9d60-cce8f2ff0f5b.jpg)

OTOH, the `AviSynth.dll` registered in _Apps Manager_ changes from the portable one to the one in the system.

![StaxRip_2 1 7 8_AviSynth dll_location_changes_20210206](https://user-images.githubusercontent.com/3157518/107130740-76eb4000-6885-11eb-9e91-fa32aecffe69.jpg)

I'm suspicious that `ffmpeg.exe` will _still_ be using the _portable_ dll in the same folder instead of the installed one in the system.

**Expected behavior**
`ffmpeg.exe` is supposed to move to a different folder so that it may use the system `AviSynth.dll`, not the portable one.

**How to reproduce the issue**
Just change the `Frameserver` > `AviSynth Mode` to `Use installed directly` and relaunch StaxRip.

**Comment by JJKylee** [comment]
Per @stax76's [reply](https://github.com/staxrip/staxrip/issues/473#issuecomment-774554483), I verify that this is **_not_** a bug.

`ffmpeg.exe` _does_ move when it is put to use with `AviSynth.dll`.

For example, if I select **`Pipe: ffmpeg`** along with `Decoder: AviSynth/VapourSynth`,
![StaxRip_2 1 7 8_ffmpeg-as-pipe-setting_does-move_ffmpeg exe_20210206](https://user-images.githubusercontent.com/3157518/107132036-9dfb3f00-6890-11eb-9cac-865560842ff4.jpg)

I can verify that `ffmpeg.exe` has moved to a new folder `%startup_dir%Apps\Encoders\ffmpeg\` in the _Processing_ windows as follows:
![StaxRip_2 1 7 8_ffmpeg-as-pipe-setting_does-move_ffmpeg exe_processing-log_20210206](https://user-images.githubusercontent.com/3157518/107132040-a784a700-6890-11eb-8608-ea49378cfa16.jpg)

I can double check this on _Apps Manager_:
![StaxRip_2 1 7 8_ffmpeg-as-pipe-setting_does-move_ffmpeg exe_apps-manager_20210206](https://user-images.githubusercontent.com/3157518/107132059-cdaa4700-6890-11eb-89f1-1fd7a8e1c92e.jpg)

If I revert the setting back to `Use portable directly`, `ffmpeg.exe` is again moved back to its original place: portable AviSynth Frameserver.

**Comment by 44vince44** [comment]
So this is only a problem of displayying the proper path to ffmpeg.exe in the apps manager ? it has to be fixed anyway and also an explanatory word should be put under description:

`Versatile and free audio video converter console app. **Staxrip uses two different paths for it according to the chosen Avisynth mode selected in settings.**`

**Comment by JJKylee** [comment]
I agree with @44vince44.

Although I put [some explanation in Doom9's thread](https://forum.doom9.org/showthread.php?p=1935412#post1935412) today, putting descriptions in _Apps Manager_ itself could be more desirable.

**Comment by stax76** [comment]
> So this was only a problem of displaying the proper path to FFMPEG.exe in the apps manager ?

Files are moved on 4 occasions:

1. Before the Apps dialog is shown (not strictly necessary)
2. After the settings dialog closes (not strictly necessary)
3. Before 'Execute Command line' (strictly necessary)
4. Before Jobs are started (strictly necessary)

The description isn't meant for documentation but rather the docs and the wiki, the wiki can be opened from the Apps dialog:

Help Button > Wiki

**Comment by JJKylee** [comment]
OK.

I just composed a [Wiki page on ffmpeg](https://github.com/staxrip/staxrip/wiki/ffmpeg) including an explanation about this as a start.

**Comment by 44vince44** [comment]
@stax76 @Dendraspis @JJKylee  May I comment this:

1) file should NOT be moved, instead, there should be two copies present, one in every location (**Frameserver** and **Encoders**) to avoid errors with users using C:\Program Files\ which is user write protected (which would make the file moving impossible, leading to an error. Only the path should be changed. NO one is gonna complain for 24MB more.

2) If there are two copies of FFMPEG.exe, then you only need to change the path and this can be done simply when pressing OK.

**Comment by stax76** [comment]
It's a new idea, it may however be extremely uncommon that there is no write access. Software installed with an installer does not have write access in C:\Program Files\ but if a user just copies the extracted staxrip folder to C:\Program Files\ using File Explorer, then the staxrip folder and all subfolders still have full write access, at least it works that way on my system. I would say let's wait for people reporting issues.

**Comment by 44vince44** [comment]
On my computer, Win10x64 HOME with **NO** developper mode, when you create a folder in Program Files, it has no write permissions to user. Any move/delete operation inside this folder requires administrator validation. I've just checked that!

Anyway, I think nobody will report anything since the default is "portable" and portable works for everyone (with no need to copy) !

**Comment by stax76** [comment]
> On my computer, Win10x64 HOME with NO developper mode, when you create a folder in Program Files, it has no write permissions to user. Any move/delete operation inside this folder requires administrator validation. I've just checked that!

Same here, but this is not as common as moving or copying an existing folder into Program Files, in that case there is still write access in the folder.
