### ISSUE TITLE
Bad behaviour (number 1) with PREVIEW windows

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#492]
**Describe the bug**
If a preview window is still open when the jobs are launched, it is impossible to close it (unless you abort the job and close it)

**Expected behavior**
When beginning the batch processing, the main form will close, **please close also any previews which are still open, automatically.**

**Comment by stax76** [comment]
It can be closed using the taskbar context menu.  😉

Fixed in the next build.

**Comment by 44vince44** [comment]
> It can be closed using the taskbar context menu. 😉

Good find 🤣

**Comment by Dendraspis** [comment]
> It can be closed using the taskbar context menu.  😉

🤔  And who's gonna add this to the wiki?

**Comment by 44vince44** [comment]
@stax76 this is fixed indeed: 1000000000 thanks !!
