### ISSUE TITLE
Shortcuts F5, F9, F10 from inside the Code Editor should use definitions in Preview

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#494]
**Describe the bug**
When you decide, in PREVIEW menu editor, to set F9 to play with mpv.net (default) and let's say, remove F10 which is supposed to open MPC-HC.

**Expected behavior**
I expect that using those shortcuts from inside the the Code Editor would do the same. Currently F10 would still attempt to open MPC-HC, or look at it in the default path

**Request**
please make F5, F9, F10 work in the Code Editor window as they are set to work in the Preview window. Only those three can be seen as common between Code Editor and Preview Window.

**Comment by stax76** [comment]
I think it's difficult to do something here, it could be tried to make the menu in the code editor customizable, but it's not something I'm interested at this time because it's like a full day work.

**Comment by 44vince44** [comment]
Ok, anyway it's not very important.... I thought it could be easy ...

**Comment by JJKylee** [comment]
As a side note, when there are two MPC players, MPC-BE and MPC-HC, `Play with mpc`(F10) defaults to _MPC-BE_ like there are no other **MPC** players.
It looks like _Preview_ and _Code Editor_ cannot distinguish b/w those two while _Apps Manager_ can. 😆

**Comment by 44vince44** [comment]
@JJKylee In preview, you can still define the shortcut and workaround the issue...

**Comment by JJKylee** [comment]
Yeah... There's only _one_ command in _Preview_ for MPC-XX players: `PlayWithMPC`. 😆

**Comment by 44vince44** [comment]
@stax76 @Dendraspis do I close this or is it hope it's gonna be done in 2021 ?

**Comment by Dendraspis** [comment]
@stax76  added the ***priority medium*** label, so he seems ambitious. 😁

**Comment by 44vince44** [comment]
That was before he admitted he had no interest in this ....

**Comment by Dendraspis** [comment]
His own fault. 😁

**Comment by stax76** [comment]
I hope it works.

There is a new beta because I made a breaking change, the name of the .conf files uses now dual instead of avs+vs, these names are now used in the help menu of the code editor context menu and in the main dialog main menu.

**Comment by 44vince44** [comment]
@stax76 , thanks the menu editor inside Code Editor works well, but I have to report this very minor thing: 
1) Open code Editor
2) Remove F10 from any definition there
3) press F10 : the mouse pointer changes, the window is not taking any shortcut commands untill you press F10 again, or click again inside.

ONLY HAPPENS WITH F10.

I know, very minor! but I had to report it. It seems there is still something hard coded with F10....

**Comment by stax76** [comment]
I would guess the reason would be too difficult to find out, keyboard things are tricky, very complex, there can be all kinds of quirks found.

Pressing Ctrl+I for instance will cause the OS to send tab, happens also in notepad, found that yesterday. In the code editor without source loaded this triggered like 3 issues, I'm investigating it currently.

**Comment by 44vince44** [comment]
@stax76 yes maybe an OS thing ! 

Well the important thing is this is working very well, and 100000s THANKS for all 👍 👍 😍

**Comment by stax76** [comment]
You're welcome.

I was thinking about a new feature, I'm not sure if it makes sense. It would be called _Edit Externally_, this would create a _external.avs or _external.vpy file and open it with AvsPmod or VapourSynth Editor 2, now if the staxrip window gets activation, staxrip will check if the file was modified meanwhile, if so it will ask if the code should be imported.

**Comment by 44vince44** [comment]
It seems really a powerful feature, but personally, i would never use it! I find Staxrip to give me all the editing i need !
