### ISSUE TITLE
x265 took a performance hit when upgraded Staxrip from 2.1.6.0 -> 2.1.7.0

### ISSUE THREAD

**Issue by Zcehtro** [staxrip/staxrip#495]
**Describe the bug**
x265 took a major performance hit when I upgraded Staxrip.
I am posting this here because I noticed that the encoding process is different: it used to be processed via avs2pipemod and after the upgrade it is processed directly via x265.

Before the upgrade a video file usually took 7h to reencode.
After the upgrade a similar video file took 12h to reencode.

Many more video files took much longer after the upgrade.

**Expected behavior**
I didn't expect x265 to take a performance hit.

**How to reproduce the issue**
I simply downgrade Staxrip and I can encode faster again.

**Provide information**
I am attaching log files of x265 encodes before Staxrip upgrade and after upgrade.
The log files belong to to very similar video files in order to make it easy to compare.

Before upgrade:
[2021-01-30 - 06.41.40 - [SubsPlease] Tensei Shitara Slime Datta Ken - 27 (1080p) [A3CBA8E7] _rcd-x265opus_staxrip.log](https://github.com/staxrip/staxrip/files/5940371/2021-01-30.-.06.41.40.-.SubsPlease.Tensei.Shitara.Slime.Datta.Ken.-.27.1080p.A3CBA8E7._rcd-x265opus_staxrip.log)

After upgrade:
[2021-02-04 - 10.39.00 - [SubsPlease] Tensei Shitara Slime Datta Ken - 28 (1080p) [72A59572] _rcd-x265opus_staxrip.log](https://github.com/staxrip/staxrip/files/5940374/2021-02-04.-.10.39.00.-.SubsPlease.Tensei.Shitara.Slime.Datta.Ken.-.28.1080p.72A59572._rcd-x265opus_staxrip.log)

**Comment by JJKylee** [comment]
Here comes `--rskip 0` again.

Please see [this issue](https://github.com/staxrip/staxrip/issues/463).
Well, so how much longer are we gonna see similar issues, @Dendraspis? 😓

**Comment by Dendraspis** [comment]
...and in the fast encode you used `bframes=10` rather that `6` in the slow encode.

**Comment by JJKylee** [comment]
Maybe we should post a **_notice_** about this somewhere. 😅

@Zcehtro, your parameters are different b/w the two jobs. Among the difference, `--rskip 0` is the main culprit that caused efficiency loss. (Other parameter settings as well, albeit slightly.)

When you report this sort of issue, please make sure that _all other conditions/parameter settings are equal_.

**Comment by JJKylee** [comment]
But don't get me wrong. I don't mean any offense.
There have been many, many people talking about this efficiency loss _issue_, which is actually **not** an issue.
Both in Doom9's forum and in the repo. There were two similar issues already. You're not alone in this. 😓

**Comment by 44vince44** [comment]
@Zcehtro you must reset your settings ! delete all the settings folder!

**Comment by Zcehtro** [comment]
Oh man thank you so much guys!
And I apologize for bringing this up as if it were something related to Staxrip when it was actually related to x265.

I have a many encoding templates and having to reset every one is a hassle... 😅
I know that Staxrip used to clear the templates after a major upgrade...
So what I did was move the template folder to my Dropbox and and the create a folder junction with MKLINK into the default Staxrip template dir.
This way I never lost a template... and I also got to have them in sync when using Staxrip on more than one computer...

However it seems that keeping old templates backfired on me this time...

![image](https://user-images.githubusercontent.com/10564090/107166885-54d8e700-6985-11eb-8dab-4c16bcce9441.png)

**Comment by Zcehtro** [comment]
Would there be a way in order to check template compatibility with current tools/apps?
Have Staxrip pop up a notification warning the user of potential incompatibility?

**Comment by JJKylee** [comment]
Let's clarify this: the efficiency loss problem we're talking about here did _not_ occur because of **template incompatibility**. It was because this additional option `--rskip 0` (introduced as a default option in the new version of StaxRip) was somehow _injected_ into your templates. My guess is that it is again because your template was composed _based on the default x265 profile_ provided by StaxRip.

As for me, I have no idea how anyone can check if _unintended_ options are injected in their templates _without_ opening/checking out parameter settings. I'd just recommend to check out _all_ your templates after StaxRip update, modify them as needed, and save them. Or you can follow @44vince44's recommendation of reset.

Having said that, I myself do not check up all templates every time I update StaxRip. I modify the templates _only after_ I find parameter changes in my templates. I guess that might be a more practical approach. 😅

**Comment by 44vince44** [comment]
@Zcehtro In your case, provided you only have 3 templates addected (the x265 ones), either you delete those 3 templates and re-create them, or do as @JJKylee suggested: modify those 3 templates so your command line gets rid of the --rskip 0 switch.

You get rid of the --rskip 0 switch by setting in x265  > Analysis > Recursion Skip = 1.
You'll have to do that for all you x265 templates.

As for this happening again, it is very rare, and we have to keep in mind to write an clear warning to users in changelog. md explicitly when such thing occur.

**Comment by Zcehtro** [comment]
I see that many other people had the same issue.

I've updates my staxrip templates and am running test encodes to see the difference in using the old vs new settings.

Thanks to everybody for clearing this up and explaining it to me.

**Comment by 44vince44** [comment]
Please close this thread, I've made an entry in the Wiki!
