### ISSUE TITLE
2.1.7.8: Add Decoder-Pipe option in aomenc

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#497]
**Please describe.**
This issue (lack of feature) was discovered while @44vince44, @Dendraspis, and @JJKylee were talking about #488 with the issuer: _aomenc lacks Decoder-Pipe options_. Instead, only `avs` reading by ffmpeg (thus, Decoder: AviSynth - Pipe: ffmpeg) is hard-wired.

**Describe the solution you'd like**
We need to see explicit Decoder-Pipe options just like x265.

**Additional context**
Although @Dendraspis is aware of this issue, I'm posting it for the record. 😃

**Comment by 44vince44** [comment]
This could also be done for the other AV1 encoders as well... Maybe could be needed one day 😁

**Comment by Dendraspis** [comment]
Already implemented in the next aomenc overhaul, so I'll close it now...
