### ISSUE TITLE
Please add filter ChangeFPS (AVS, internal), and modify currently existing ConvertFPS

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#499]
Hi there!

A) Currently Staxrip has AVS > Frame Rate > ConvertFPS as follows:
`ConvertFPS = ConvertFPS($select:msg:Select a frame rate;24;25;29.970;30;50;59.940;60;120;144;240;$)`

Please add the frame rate 23.976 which is the Traditional Cinema adapted to TV which is still a major standard today:
`ConvertFPS = ConvertFPS($select:msg:Select a frame rate;23.976;24;25;29.970;30;50;59.940;60;120;144;240;$)`

B) The filter ChangeFPS is a filter less sophisticated than ConvertFPS, but it works better for some cases.
I think it should be there, above ConvertFPS. This would be the filter profile:

`ChangeFPS = ChangeFPS($select:msg:Select a frame rate;23.976;24;25;29.970;30;50;59.940;60;120;144;240;$)`

Only a filter mod and a filter addition !

**Comment by 44vince44** [comment]
@Dendraspis this brings the question: do we keep format 24000/1001 or use 23.976 ?
The proper way is to keep 24000/1001, I don't know why this was recently changed... I would suggest to use this instead:


```
ChangeFPS = ChangeFPS($select:msg:Select a frame rate;24000/1001|24000, 1001;24;25;30000/1001|30000, 1001;30;50;60000/1001|60000, 1001;60;120;144;240$)
ConvertFPS = ConvertFPS($select:msg:Select a frame rate;24000/1001|24000, 1001;24;25;30000/1001|30000, 1001;30;50;60000/1001|60000, 1001;60;120;144;240$)
```

I also corrected removed the ";" before the $ sign.

**Comment by Dendraspis** [comment]
[StaxRip v2.1.7.9D_ChangeFps1.zip](https://github.com/staxrip/staxrip/files/5946443/StaxRip.v2.1.7.9D_ChangeFps1.zip)

> I also removed the ";" before the $ sign at the end.

Too late.  😂

**Comment by Dendraspis** [comment]
> I have no idea how that works (and I'm too old for that) 🤣

A very poor excuse, especially from you!  😝 
Here is the answer:

<img src="https://user-images.githubusercontent.com/50659978/107278919-ac935300-6a56-11eb-897f-7b5094d4645e.PNG">

**Comment by 44vince44** [comment]
> ![](https://user-images.githubusercontent.com/50659978/107278919-ac935300-6a56-11eb-897f-7b5094d4645e.PNG)

I must admit I'm not understanding.... is it a joke or it's really as simple as clicking on an Edit button ?

**Comment by 44vince44** [comment]
It's a png, nothing interesting will happen 🤣 

If you want to stick to 23.976, i can write a syntax that shows 23.976 in the selection list, but uses 24000/1001, which is the proper value to use.

**Comment by 44vince44** [comment]
OK I'm gonna try it. maybe I'm not too old for that after all...

**Comment by 44vince44** [comment]
@Dendraspis I could locate the file where the code appears because you did a commit previously and very recently. But how can I do a search across all the files ? Is there a way to search across files, or do you need to know what's inside every file (meaning to what it's related)

**Comment by Dendraspis** [comment]
> [..] that shows 23.976 in the selection list, but uses 24000/1001, which is the proper value to use.

I bet AviSynth is setting the value correctly by using 24000/1001 in the back.
But we can use 24000/1001 if it's okay for @stax76 ....

---------

> But how can I do a search across all the files ?

<img width="490" alt="SR" src="https://user-images.githubusercontent.com/50659978/107284166-a5237800-6a5d-11eb-94e9-1423d53bfaac.PNG">

**Comment by 44vince44** [comment]
> I bet AviSynth is setting the value correctly by using 24000/1001 in the back. 🤔

Nope, ChangeFPS(23.976) is not automatically "translated" to ChangeFPS(24000,1001). Be sure of that!

**Comment by Dendraspis** [comment]
Okay, so using this function with `23.976` would not create a full compatible TV signal ?   😲

**Comment by 44vince44** [comment]
Here check it yourself (I know you love those 😁 )

![SNAG-0000](https://user-images.githubusercontent.com/17828567/107285846-6cd56700-6a68-11eb-9bea-a262706a4c6c.jpg)

![SNAG-0001](https://user-images.githubusercontent.com/17828567/107285871-73fc7500-6a68-11eb-89e4-45de27a18353.jpg)

> Okay, so using this function with 23.976 would not create a full compatible TV signal ? 😲

Yes it's a matter of standards. 23.976 does not exist, it's a way of calling it. We can't replace 24000/1001 by 23.976. But we can still call it 23.976 and use 24000/1001. it's important!

**Comment by 44vince44** [comment]
So, my PR's gonna be merged or not 🤣 ?

**Comment by Dendraspis** [comment]
Is merged. There was a typo, that I saw too late, but it's fixed meanwhile.  😊 

Do you wanna close it now?  😉

**Comment by 44vince44** [comment]
Thanks ! haha ... my first PR 🚀

**Comment by Dendraspis** [comment]
> Thanks ! haha ... my first PR 🚀

You're welcome.  😊 
Just a pleasure for the next time:  Please give the commit a good name, not the default *"Update File.vb"*.  😉 

Ah, I totally forgot to append:
[StaxRip v2.1.7.9D_ChangeFps2.zip](https://github.com/staxrip/staxrip/files/5947140/StaxRip.v2.1.7.9D_ChangeFps2.zip)

**Comment by 44vince44** [comment]
> Just a pleasure for the next time: Please give the commit a good name, not the default "Update File.vb". 😉

at that time, I didn't even realize that is was a name for the commit, I though it was a confirmation for the filename i was working on🤣

**Comment by 44vince44** [comment]
@Dendraspis the file ChangeFPS2 does not include the commit.

it still has the names "24000/1001" and not "23.976"...
See:
`AssumeFPS = AssumeFPS($select:msg:Select a frame rate;24000/1001|24000, 1001;2 (...)`

**Comment by Dendraspis** [comment]
Nope, it looks okay.  Where are you looking at?  😁

**Comment by 44vince44** [comment]
![SNAG-0000](https://user-images.githubusercontent.com/17828567/107294787-c775bf80-6a76-11eb-861d-0fe802ed9dc7.jpg)

**Comment by Dendraspis** [comment]
Damn, seems like I took the wrong file.  😲
Sorry.  😟

**Comment by Dendraspis** [comment]
[StaxRip v2.1.7.9D_ChangeFps3.zip](https://github.com/staxrip/staxrip/files/5947570/StaxRip.v2.1.7.9D_ChangeFps3.zip)

**Comment by 44vince44** [comment]
Thanks, now it looks fine! I'll go to sleep and tomorrow do several encodes !

**Comment by Dendraspis** [comment]
@44vince44 
That's good ... old people need a lot of sleep.  😜

**Comment by 44vince44** [comment]
Nope we need less... I swear, it's we sleep less and we enjoy sleeping less...
