### ISSUE TITLE
Cutting and hard-coding subtitles don't work.

### ISSUE THREAD

**Issue by ls-milkyway** [staxrip/staxrip#50]
Using cutting/trimming by using preview and then selecting ssa/ass subtitle file from Tools>Advanced>Subtitles>Hardcoded Subtitle results in plain video (without burnt subtitles)...and sometimes gets stuck (plz check screenshot) and throws error on closing (plz check error log).

Tried ass file encoded in utf-8, utf-8 with bom and ansi ...but nothing works...Details:
Encoder: Nevnc x264 (Rigaya) 4.46 
Filetype: mkv with/without subtitle.
Staxrip Vrsion: 2.0.4.0 stable.
Even tried to place cutting before subtitle etc.
![staxrip_screen](https://user-images.githubusercontent.com/55090624/64531588-859a9400-d32d-11e9-80a7-fad58367f26e.jpg)
[staxrip-error.txt](https://github.com/staxrip/staxrip/files/3590512/staxrip-error.txt)

Although Nvenc 4.46 has inbuilt commands to add subtitles (vpp subburn) and trim but the subtitles are out of sync (change in video length due to trim is not reflected on ssa/ass subtitle....ts_offset doesn't work) ....reporting separately to nvenc. 
Thanks

**Comment by ls-milkyway** [comment]
Update-> please check the link below for the latest on the issue:
[https://github.com/rigaya/NVEnc/issues/146](url)

**Comment by stax76** [comment]
I tried to reproduce it and was getting a format exception which I fixed then, after that it was working:

https://pastebin.com/v5LArLzT

I watched the resulting video and everything was fine.

If it happens again please post the full log file and a sample file.
