### ISSUE TITLE
Minor bug : please remove default shortcut "M" in Code Editor that is assigned to Edit Menu

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#505]
**Describe the bug**
In Code Editor, you are supposed to select filters and also **type text** sometimes. When you write a word with "m", the menu editor pops up !

**Expected behavior**
As it is a text edit window the shortcuts that are simple letters must not exist

**Fix**
Simply remove the default shortcut M assigned to Edit menu IN THE CODE EDITOR only.
This is the only command with a simple letter shortcut. All other commands are OK.

**Comment by JJKylee** [comment]
You do have sharp eyes. 😮👍

**Comment by 44vince44** [comment]
I simply happened to type "DuplicateFram..." and there the mysterious window popped-up 🤣

**Comment by Dendraspis** [comment]
Nobody recognized it because everybody uses Copy&Paste. 😁

But typing 'm' is really annoying when a windows opens as soon as you press it.

**Comment by 44vince44** [comment]
Thanks @Stax76 !!
