### ISSUE TITLE
Please change --kf-max-dist and --kf-min-dist default and init for aomenc (they are currently wrong)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#506]
I think this is for @Dendraspis 

Currently the defaults are not correct
Default for --kf-max-dist is 9999 AND NOT 250
Default for --kf-min-dist is 0 AND NOT 23

## Please set the defaults (values that make the switch disappear) : 
- --kf-max-dist is 9999
- --kf-min-dist is 0

## THEN please, set the init values 
- --kf-max-dist = 9999 OR 150 (you decide whether to **stick to doc =9999** or help users encode with no problem as per known **usage habits = 150**, I would prefer 150)
- --kf-min-dist =0

## Additional request
Also PLEASE, set **--verbose** as selected in the init values. This only activates more information dispayed when encoder starts. This allowed me to know what the defaults are for kf-max-dist and kf-min-dist.

Thanks for all !

**Comment by Dendraspis** [comment]
And I thought you would create again a PR.  😁 

But I already implemented them for the next aomenc overhaul.  ☺️

**Comment by 44vince44** [comment]
> And I thought you would create again a PR. 😁

I thought about it but I was really too tired, I have been doing all imaginable tests with aomenc this morning that I am really exhausted!

**Comment by Dendraspis** [comment]
> I thought about it but I was really too tired

I meant about an hour ago when you've written the issue.  😜

**Comment by 44vince44** [comment]
🤣 One hour ago I was already exhausted. I had been testing for 5 hours. You can't imagine how many tests I did to begin understand what was happening. When I wrote the issue, it was after everything was finished, and I was doing a few additional tests just to confirm my latest find (and which did not require thinking)

**Comment by 44vince44** [comment]
@Dendraspis I forgot to check that one. Just did:

 - --kf-min-dist default is 0, init is 0 : **properly implemented** 🆗 
 - --kf-max-dist default is 9999, init is 120 : ERROR IN IMPLEMTATION ❌

**Comment by Dendraspis** [comment]
Yes, Sir!  🦾 
Is fixed - I can't get used to the UI configuration.  😁

**Comment by 44vince44** [comment]
I'm very sorry, I must have gotten you confused the the work "init" .
Apparently, init, in the code is the default value, the one which makes the switch disappear from command line.

**Comment by Dendraspis** [comment]
Exactly, but for me this is not intuitive enough.  😁 
Nevertheless it's fixed though ... now.  😄   Thanks for that.

**Comment by 44vince44** [comment]
Thanks to you @Dendraspis 
Well I git to do my PR after all 😁 Please check !!!
