### ISSUE TITLE
AAC TVBR quality

### ISSUE THREAD

**Issue by ArturAlekseev** [staxrip/staxrip#507]
Hello, I don't know why but in all profiles AAC TVBR quality is set to default 0 that causes lowerst bitrate and quality.
As I remember default should be 50. When 50 is set - 54 is used instead in command prompt.

**Comment by Dendraspis** [comment]
Template?
Screenshots?
Which StaxRip version?

I can't reproduce it - everything looks great with quality @ 50.

**Comment by ArturAlekseev** [comment]
Just checked again. Seems like this problem was because I have not made clean install (settings folder was from previous version).
I have not found this out right away and have some videos with lowerst bitrate audio now. Need to reencode them.
You can see its an often issue - some users don't realize it.
Check this thread: https://forum.doom9.org/showthread.php?t=175845&page=105
...
18 july 2020 post:
C:\Staxrip\Apps\Audio\qaac\qaac64.exe **--tvbr 0** --delay 1 --normalize "C:\Temp\[KH] After the Rain...

**Comment by JJKylee** [comment]
Me, neither.

![StaxRip_2 1 8 0_AAC-encoder_default-settings_20210210](https://user-images.githubusercontent.com/3157518/107518175-91623980-6b63-11eb-8fad-aacfbbfb208b.jpg)

⇐ 2.1.8.0 AAC _default_ settings

**Comment by Dendraspis** [comment]
Yeah, the big problem with StaxRip's settings...

***Tip:***  Always check or reset the settings when updating.

**Comment by JJKylee** [comment]
> Seems like this problem was because I have not made clean install (settings folder was from previous version).

First, you _**always**_ need to check out parameter settings _before_ running a job. This is a **must**.

Secondly, if you didn't do a clean install, you _**always**_ need to check out if there's any change in your settings, templates, profiles, custom menus, apps manager settings, etc. This is a very cumbersome job, and that's why clean install is recommended.
