### ISSUE TITLE
Update some tools

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#51]
- NVEncC  v4.47
- MediaInfo 19.09
- x265-3.1+15
- MP4Box 0.8.0-rev69
- ffmpeg 4.2.1
- mpv??

**Comment by stax76** [comment]
Thanks for posting, I'm currently working on a new beta build.

**Comment by stax76** [comment]
For x265 and ffmpeg I wait for Wolfberry making a new build.

For mp4box I did not find a trusted build.

**Comment by Patman86** [comment]
Hi Stax,

here is a link to Wolfberry's Google Drive
https://drive.google.com/drive/folders/1xZQABtoaSFgGu11YstmHKYLzO3elemlC

There are x265, ffmpeg and MP4Box included.
