### ISSUE TITLE
Support for Dark Mode?

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#510]
It looks like _dark mode_ is becoming a new trend.
Do you have any plan to support it in the near future?
Please help me protect my sore eyes with dark mode. 😅

**Comment by Dendraspis** [comment]
I tried it last year and it was a ton of work. While making good progress and being at about 70%, I lost everything due to a system failure. 😖

But I remember how difficult it was, because you have to adjust almost every single control and very often on each window separatly.

Maybe I'll try it again, but..... you know.

**Comment by 44vince44** [comment]
Staxrip uses the old color set. And some colors are not properly assigned. I made my own dark mode by modifying the registry OLD color settings, and I'm satisfied with this dark gray mode. This will impact only OLD ui style programs (which i use much).
The mod takes into consideration that many of the old UIs do not use the colors as they should be (including Staxrip).

Here is how I did it: 
1. set Windows to dark mode
2. then apply this registry mod: [Colors mod very old ui.zip](https://github.com/staxrip/staxrip/files/5970165/Colors.mod.very.old.ui.zip)

here's the result:
![SNAG-0007](https://user-images.githubusercontent.com/17828567/107739874-8d284e80-6d12-11eb-8786-1b7999e97324.jpg)

Just to help in the mean time 😄

**Comment by Dendraspis** [comment]
This is how my progress looked like:  

![SR1](https://user-images.githubusercontent.com/50659978/107740665-f5276680-6d0b-11eb-8036-2fe927fdd2ab.jpg)
![SR2](https://user-images.githubusercontent.com/50659978/107740666-f5bffd00-6d0b-11eb-9df3-cb00c25c4546.jpg)
![SR3](https://user-images.githubusercontent.com/50659978/107740667-f6589380-6d0b-11eb-87b3-41db080ed981.jpg)

**Comment by 44vince44** [comment]
Ah nice REAL Dark theme 👍🏼

**Comment by Dendraspis** [comment]
Haven't you read my first answer above?  🤔 

> And how come it shows staxrip 2.1.3.9???

Because this was the latest version when I started end of July.  😉

**Comment by 44vince44** [comment]
Of course I've read it:

> Maybe I'll try it **again**, but..... you know

I thought that "again" means that the previous attempt was failed. But the screenhots show something successful, not failed 😄 
This is why I was surprised. You should definitely do it again 🙏🏼

**Comment by Dendraspis** [comment]
I meant this part:   ***"I lost everything due to a system failure. 😖"***

**Comment by 44vince44** [comment]
O...o..... You're right, my brain completely censored it. Probably because it's something very, very sad .... all the work is gone. That's a shame 😢

**Comment by Dendraspis** [comment]
No worry, @JJKylee seemed to react with a laugh.  😲 

But every time I use StaxRip at night I think about my solution and if is worth to restart.  😁

**Comment by 44vince44** [comment]
> No worry, @JJKylee seemed to react with a laugh. 😲

Maybe there's a hidden pattern in your text that makes the brain skip it 🤣

**Comment by Dendraspis** [comment]
I think of restarting my attempt, somehow I manage to remember a lot of my solutions. But it'll still need many hours making such an revival.

Furthermore there seems to be almost no request for this feature.  🤔

**Comment by 44vince44** [comment]
You know, but in my own experience, there are some apps that don't look good in dark mode (and please don't get me wrong: it's my own experience, I'm not saying any thing bad about these apps)
-Windows, file explorer : looks good in dark mode
-browsers : look good in dark mode for almost all sites, but there is always a white flash when the browser is launched, that will probably cause more harm than the light mode itself (thank you Microsoft or whoever is responsible for such negligence)
- mkvtoolnix: I find dark mode very difficult to use, so I kept it light mode, and I reduce the screens brightness.
- staxrip: I made several tests before the result shown in my screenshot above. I prefered the grey/dark grey mode with screen brightness lowered down.

I don't know, you have to decide, you're doing all the hard work here ...

**Comment by Dendraspis** [comment]
Do you like the appearance on my early screenshots?

**Comment by 44vince44** [comment]
Yes I do. The appearance and colors chosen look relaxing to the eyes. if it's available, I really think I'd use it.

**Comment by JJKylee** [comment]
IMO, what about yellow or some other color instead of light blue? And the black menu icons need to be inverted in color. (They’re fonts, right? Hmm...)

**Comment by 44vince44** [comment]
ah @JJKylee you want Dark "Flashy" mode 🤣

**Comment by JJKylee** [comment]
Well, as long as the icons and menus stand out, I don’t mind about the details.
But I think I need to wait until I see the dark mode in reality. 😉

**Comment by Dendraspis** [comment]
But it would mean let StaxRip look like this in default mode:

<img width="700" alt="SR" src="https://user-images.githubusercontent.com/50659978/107773110-7519f480-6d3d-11eb-99d2-222d32b3de68.PNG">

**Comment by JJKylee** [comment]
Nope. I didn't propose any specific _color_.
I just wanted to point out that menus and icons don't stand out.

**Comment by Dendraspis** [comment]
@JJKylee 
This wasn't an answer to your comment. I wanted to point out, that implementing DarkMode would need some modification to the layout/style.

**Comment by JJKylee** [comment]
I was confused. 😓

Yes, I guess it would involve many changes at the code level. Sorry about the extra burden. 😅

BTW, the reason I thought about dark mode in StaxRip is because `Help` > `Info` is already in dark mode. It looked beautiful for me, so I thought dark mode would go well with StaxRip. 😃 (Or at least, @stax76 is thinking about adopting dark mode in StaxRip sometime...? 😄)

**Comment by Dendraspis** [comment]
@stax76 
If you would help fixing some UI glitches, I think I would re-start implementing it.  🤔

**Comment by stax76** [comment]
Yes but not right now since I'm having at least a small coding break.

**Comment by 44vince44** [comment]
>  I wanted to point out, that implementing DarkMode would need some modification to the layout/style.

Yes indeed the frames around the boxes are not very nice 😕 after the modification...
Those are the glitches you're refering to @Dendraspis ?

**Comment by HASJ** [comment]
I just use Windows with a modded theme:
![image](https://user-images.githubusercontent.com/9345660/107811327-bd8cde80-6d4c-11eb-8136-79299abdf526.png)

The only wrong thing is this:
![image](https://user-images.githubusercontent.com/9345660/107811366-caa9cd80-6d4c-11eb-9473-cc1a5f87fea6.png)

**Comment by Dendraspis** [comment]
That's just a design question. Even if we can't change it, it is okay.
I meant white borders around TextEdits, that disappear when you leave the control.

**Comment by anthony75smith75** [comment]
I love Dark Mode as well and would love to see a Dark Mode theme selection option in StaxRip. I will use it for sure but it needs to not have issues like the black text on dark grey above. I actually like the light grey over the darker one as well.

**Comment by stax76** [comment]
@Dendraspis 

This commit has a color change:

https://github.com/staxrip/staxrip/commit/4bd9bb1150f0984e27a5e5a7eb5967cb11b918f6

**Comment by Dendraspis** [comment]
@stax76 
Thanks, but the bigger problem is your new `Block()` and changed `Highlight` function, that I already implemented in an obvious other way. 🤔 
Merging them will be fun.  😁

**Comment by Dendraspis** [comment]
@stax76 
**Wow**, I would really appreciate if you could wait a bit with such changes, that are not really critical. 😁  I think I spent more time merging `MainForm` than you making the changes.

**Comment by Neltulz** [comment]
I managed to achieve an easy dark mode by using a program called WindowTop.  It turns any program dark by inverting it.

![2021-02-19_10-11-56](https://user-images.githubusercontent.com/7741742/108530242-fff97280-729a-11eb-9a9f-1b8a698d5b67.png)

**Comment by Dendraspis** [comment]
@stax76 
Would be nice if you could check out the [latest build](https://github.com/staxrip/staxrip/discussions/518) to see if ***Themes*** could make its way to the master branch soon.
The ***TaskDialog***s are OS made and can't be customized. So the only solution would be creating a new form and using it instead. But that's the point I would ask you to help. 😁

**Comment by stax76** [comment]
I tried the last, it's very impressive. Three issues I noticed:

1. On startup dark theme isn't applied directly.

2. The left and right border of menus is missing.

3. SimpleUI tab buttons don't have centered text.

Some of these issues might only happen with very high DPI, I'm using 288.

Feel free to merge it if you think it's ready, minor issues can be fixed later.

**Comment by 44vince44** [comment]
@stax76 I can only confirm "2"
Can you please screenshot for "3"

**Comment by Dendraspis** [comment]
@stax76 
1. That's right for the very first start, because the light theme is the default now. But after choosing a dark theme and restarting StaxRip it will load the chosen theme directly.
2. Yeah, needs to be improved later, because not trivial - maybe a border has to be drawn by hand
3. Yes, screenshot please.  🤔 

The high DPI setting might be the reason, but the drawing is made by the OS as far as I remember. 🤔 

Thanks.  👍   But it will take a few days to fix the already known issues and clean my code a bit because of all the trial and error.

**Comment by stax76** [comment]
3. can be seen here:

https://user-images.githubusercontent.com/17828567/108597456-ceaf9e00-7391-11eb-95fe-7a357d3bb539.jpg

Text is not vertically centered in the nav/tab button, I hope it can be fixed easily.

**Comment by stax76** [comment]
1. Happens on every start, some kind of flicker.

2. The dark mode of mpv.net has such border code.

https://raw.githubusercontent.com/stax76/mpv.net/master/img/Menu.jpg

It's C# but originally based on staxrip code.

https://github.com/stax76/mpv.net/blob/master/mpv.net/WinForms/Menu.cs#L131

**Comment by 44vince44** [comment]
Ah I understand now what "1." means:

@Dendraspis, @Stax76 is talking about something that happens instantly when you start Staxrip, if it was already set in dark mode, at start you'll see a light flash (flicker).
The problem is that I have this flicker with Staxrip, but also with Chrome, Firefox, even Windows file explorer. They are all in dark mode, and they all do a small white flash when I start them, as is the theme was not instantly applied when the start...

**Comment by stax76** [comment]
I have it with Chrome too, FireFox exactly the same, it's very short, did not notice before.

I'm not seeing it with File Explorer, unless my external HDD is sleeping, then it's very noticeable.

**Comment by 44vince44** [comment]
But one thing is sure, I never seen it in mpv.net (maybe because it's not an interface 🤣 )

Is it possible to set the theme somehow before the form is drawn ?

**Comment by Dendraspis** [comment]
> Is it possible to set the theme somehow before the form is drawn ?

It is!  It is set in the constructor, so there's no "before". Maybe it can be slightly optimized, but overall that's how WinForms works, which is by design not meant for such things like changing the appearance/colors of a button. 🙄

**Comment by 44vince44** [comment]
So the "flash" is by design.... no wonder it's also in Chrome, firefox, file explorer etc....

**Comment by 44vince44** [comment]
Really wondering how long this thread is still gonna be open  🤣

**Comment by JJKylee** [comment]
Like I mentioned in the [related discussion](https://github.com/staxrip/staxrip/discussions/518), I guess _[StaxRip v2.1.8.2D_DarkMode15.zip](https://github.com/staxrip/staxrip/files/6021452/StaxRip.v2.1.8.2D_DarkMode15.zip)_ is ready to roll out after some final polish. 😄
It was a loooooooong journey. Esp. for @Dendraspis. 😅
We owe him a really big time. 👏👏👏👏👏

**Comment by 44vince44** [comment]
Yes my comment was purely for fun.
And I agree that @Dendraspis did something really outstanding !

**Comment by Dendraspis** [comment]
@stax76 
Have a look at [v17 or above](https://github.com/staxrip/staxrip/discussions/518).  Almost done ... I guess 😁

**Comment by stax76** [comment]
It looks fantastic, people will love it. Next release will be a great one.

**Comment by 44vince44** [comment]
Next release will be a major one, it has Dark Theme, chunk encoding for aomenc, many bugfixes, Patman builds are back (but still DJATOM/msg must be mentionned and credited), am I forgetting something ?
So don't forget to tell the users : DELETE ALL PREVIOUS PROGRAM FOLDERS AND ALL PREVIOUS SETTINGS AND TEMPLATES!!!!

**Comment by stax76** [comment]
Also, AviSynth Unicode and Long Path on Windows 10 was completed.

> but still DJATOM/msg must be mentionned and credited

I think this is something Patman, DJATOM and MeteorRain can care about, for instance by writing it to the repo readme.md, repo links are in the docs:

https://github.com/staxrip/staxrip/wiki/x264

https://github.com/staxrip/staxrip/wiki/x265

> So don't forget to tell the users : DELETE ALL PREVIOUS PROGRAM FOLDERS AND ALL PREVIOUS SETTINGS AND TEMPLATES!!!!

Are there incompatible settings?

**Comment by Dendraspis** [comment]
Not as far I'm concerned. 🤔

**Comment by 44vince44** [comment]
Yes, there are new filter profiles needed to be updates, and the preview ability to create jobs from trim part, those need a settings refresh...
And as for templates, due to the switch to Patman86's build (2 options cancelled) and change of available options, it's better to refesh the templates as well.

**Comment by Dendraspis** [comment]
On the other side these are changes that happen all the way, probably one a week. 

But it could be a good advice for the next stable.  🤔

**Comment by Dendraspis** [comment]
Meanwhile 50 file changed.  😲 
I think I'll push it this evening...

**Comment by Dendraspis** [comment]
Okay, @stax76 , 😁  try to not directly alter/change my code in 
- `ThemeManager.vb`
- `Theme.vb`
- `ColorHSL.vb`

...at least for a (short) while.  😁   I know you like doing that.  😉

**Comment by JJKylee** [comment]
[This commit](https://github.com/staxrip/staxrip/commit/b14701cf8f9abd52fd24b0ca2a314c6ae6682239) finalizes my request for dark mode, so I believe I can happily close this thread. 😄

For those of you who are interested in what the dark mode themes look like, you can refer to [this discussion](https://github.com/staxrip/staxrip/discussions/518).

I'm using the final preview version and I'm really satisfied with its beauty. 👍👍👍👍👍

**Comment by stax76** [comment]
I fixed the flicker in the FormBase, disabled in preview due to freeze, committed and hot fixed, but needs testing since all forms are affected.

**Comment by Dendraspis** [comment]
Interesting, I've never seen flickering.  🤔
 😁 But maybe that's just me again.

**Comment by stax76** [comment]
It was very noticeable on my 4K setup.

Before this fix was needed in the Video Comparison, that's from where I knew it.

Works like so:

> The WS_EX_COMPOSITED extended style enables double-buffering on the window. This means that the control renders into an off-screen buffer, and only when rendering is complete is the result copied to the screen. This avoids flicker because only a completely-drawn control is put on the screen; you never see the control in a partially-drawn state.

**Comment by JJKylee** [comment]
I tried the hotfix `StaxRip.exe` on @stax76's Beta download archive, and here's what I experience.

### Pros
1. The small flickering with almost all new windows is gone.
2. Now there are the border lines b/w filter categories that @44vince44 has been wishing for so much. 😄

![StaxRip_2 1 8 2_stax76-hotfix1_Code-Editor_border-lines_20210223](https://user-images.githubusercontent.com/3157518/108908142-d496c080-75d7-11eb-9bc4-3dcef6b08381.jpg)

### Cons
1. My customized main menus (and shortcuts) are gone. 😭
2. In adding new custom main menus, I've found this new flickering issue in the _Menu Editor_.

![StaxRip_2 1 8 2_stax76-hotfix1_Menu-Editor_flickering_20210223](https://user-images.githubusercontent.com/3157518/108908604-5d156100-75d8-11eb-98a4-0440bfab84b0.gif)

This starts appearing when I click _Command Line_.

(BTW, I've found that the _Command Line_ title is hard to see in a dark theme. 😢)

![StaxRip_2 1 8 2_stax76-hotfix1_Menu-Editor_Command-Line_title_20210223](https://user-images.githubusercontent.com/3157518/108909047-e62c9800-75d8-11eb-9547-d534dda26007.jpg)

**Comment by Dendraspis** [comment]
Flickering ist strange - do you have the same problem with v23 ??

> BTW, I've found that the Command Line title is hard to see in a dark theme. 😢

Which menu is it ?

**Comment by JJKylee** [comment]
> Flickering ist strange - do you have the same problem with v23 ??

v23 does _not_ have this flickering issue. 

> Which menu is it ?

Main menu.
`Tools` > `Edit Menu...`

**Comment by Dendraspis** [comment]
@stax76 
If v23 is not flickering, it has something to do with your latest fix.  🤔 
I have ***Event Command Editor*** opened at the moment and the whole window is flickering as well as every control in it. 😲

**Comment by Dendraspis** [comment]
@JJKylee 
v24 is out.  😁
Sorry, this time I stopped reading before "new flickering issue in the *Menu Editor*."  🙄

**Comment by JJKylee** [comment]
> I have _**Event Command Editor**_ opened at the moment and the whole window is flickering as well as every control in it. 😲

I confirm this. Flickering starts when I click _Parameters:_ field.

And by 'the small flickering with almost all new windows' in v23, I mean this:

![StaxRip v2 1 8 2D_DarkMode23_window-flickering_20210223](https://user-images.githubusercontent.com/3157518/108912640-c3e94900-75dd-11eb-85b5-cc20709eb10d.gif)

I slow-motioned the field drawing part 10 times.

I'm not sure if this can even be called 'flickering'. It seems to be related to drawing window forms.
But this slow drawing issue is surely gone with @stax76's latest hotfix. 😅

**Comment by stax76** [comment]
There is now a new hotfix online, but you will need this new file:

Apps\Plugins\AVS\xy-VSFilter\VSFilter.dll

**Comment by JJKylee** [comment]
I put `xy-VSFilter` in the recommended place.
Downloaded the new hotfix.

The flickering issue in `Menu Editor` is gone.

But when I try to edit an `Event Command`, this error pops up.

```
MissingMethodException (2.1.8.2)

Method 'StaxRip.UI.PropertyGridEx.doccomment' not found.

System.MissingMethodException: Method 'StaxRip.UI.PropertyGridEx.doccomment' not found.
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   at StaxRip.Reflector.Invoke(String name, BindingFlags flags, Object[] args)
   at StaxRip.Reflector.Invoke(String name)
   at StaxRip.UI.PropertyGridEx.SetHelpHeight()
   at StaxRip.UI.PropertyGridEx.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
   at System.Windows.Forms.PropertyGrid.OnFontChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Font(Font value)
   at StaxRip.UI.FormBase.OnLoad(EventArgs args)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
😓

**Comment by Dendraspis** [comment]
I think this might be my fault.....

**Comment by JJKylee** [comment]
> Was it an existed event?

Yes.

**Comment by Dendraspis** [comment]
Got it - I can reproduce it.  👍 
Gimme a some time...

**Comment by stax76** [comment]
Maybe you need PropertyGrid instead of PropertyGridEx as type.

**Comment by JJKylee** [comment]
@Dendraspis, let me take this opportunity to point out the (hopefully) last issue I happened to find with the dark mode version.

![StaxRip_2 1 8 2_stax76-hotfix2_white_icons_in_Default_theme_20210223](https://user-images.githubusercontent.com/3157518/108916682-75d74400-75e3-11eb-9d7f-d8353052d054.jpg)

😅

**Comment by Dendraspis** [comment]
Yeah, seems like my fix was a culprit.  🙄 

@JJKylee 
v25 is online...

The white icon in Default theme is okay. It will be shown in the correct color after restarting StaxRip.

**Comment by stax76** [comment]
With 4K and 288 DPI there are two small menu issues:

1. The top and bottom border is thicker than the side borders.

2. For the menu separator there is an artifact on the left side and on the ride side.

Can you reproduce this?

![staxrip](https://user-images.githubusercontent.com/11410540/108918489-beb5e980-7631-11eb-8946-0c196cc51ab0.png)

![mpv net](https://user-images.githubusercontent.com/11410540/108918555-dc834e80-7631-11eb-8fbf-71aefedb6e44.png)

**Comment by JJKylee** [comment]
v25 and v26 have these issues.

![StaxRip v2 1 8 2D_DarkMode25_black-boxes_in_Default_theme_1_20210223](https://user-images.githubusercontent.com/3157518/108918487-4e35ab00-75e6-11eb-87fb-251dfa1cd3e7.jpg)

![StaxRip v2 1 8 2D_DarkMode25_black-boxes_in_Default_theme_2_20210223](https://user-images.githubusercontent.com/3157518/108918498-54c42280-75e6-11eb-939c-75910c81d375.jpg)

They look normal in a dark theme.

![StaxRip v2 1 8 2D_DarkMode25_black-boxes_in_Default_theme_1_dark-theme_20210223](https://user-images.githubusercontent.com/3157518/108918535-63123e80-75e6-11eb-9df6-796f82505489.jpg)

![StaxRip v2 1 8 2D_DarkMode25_black-boxes_in_Default_theme_2_dark-theme_20210223](https://user-images.githubusercontent.com/3157518/108918547-686f8900-75e6-11eb-99f1-f31721f1952c.jpg)

And this is a _very trivial_ thing.

![StaxRip v2 1 8 2D_DarkMode25_black-v-mark_in_dark-themes_20210223](https://user-images.githubusercontent.com/3157518/108918581-7a512c00-75e6-11eb-8cf4-ca54ae9799c8.jpg)

The `v` mark in a dark theme is not easily visible.

**Comment by JJKylee** [comment]
@stax76,

I can confirm those two, but wait. Weren't they intended? 🙄
I thought they were. 😁

**Comment by stax76** [comment]
It was probably not intended.

I'll try fixing the dropdown arrow now.

**Comment by stax76** [comment]
Dropdown arrow is hopefully fixed now in last commit and hotfix.

**Comment by Dendraspis** [comment]
@stax76 
1. For me it's okay, but if you wanna change it:  feel free. I had sooo much trouble with those borders ... 

Here at 400%:  [2160p, UIScale 1.00]
<img width="725" src="https://user-images.githubusercontent.com/50659978/108919967-2e2cd880-7634-11eb-94e0-fd43517a43c6.png">

2. Maybe you can find out why this happens.  I tried, but without success.
As far as I remember, there is a method that draws those separators, but if you remove the custom code from it and just let *MyBase* do the rendering, there is a tiny gap without content, but with both *lines* at the side - seemed to be system made, but I'm really no expert when it comes to UI. Maybe it's very easy, but I'm too stupid.

**Comment by Dendraspis** [comment]
> Dropdown arrow is hopefully fixed now in last commit and hotfix.

Thanks, seems to be forgotten.  😊

**Comment by Dendraspis** [comment]
@JJKylee 

> v25 and v26 have these issues.

Is fixed ... v27 is out

**Comment by JJKylee** [comment]
v27 looks perfect. 👍

And about the top/bottom border and separator issues, why don't we close this thread first and talk about them in a separate issue thread **_if_** anyone except @stax76 comes up with the same issues? 😁

As for me, I have no inconvenience with them. 😅

So now I'm closing this thread again.

**Comment by stax76** [comment]
I'll try to fix it.

**Comment by stax76** [comment]
I think I have it almost working but BorderColor doesn't give the right color?

```
     Protected Overrides Sub OnRenderToolStripBorder(e As ToolStripRenderEventArgs)
        If TypeOf e.ToolStrip IsNot MenuStrip Then
            Dim r = e.AffectedBounds
            r.Inflate(-1, -1)
            ControlPaint.DrawBorder(e.Graphics, r, DropdownBackgroundDefaultColor, ButtonBorderStyle.Solid)
            ControlPaint.DrawBorder(e.Graphics, e.AffectedBounds, BorderColor, ButtonBorderStyle.Solid)
        End If
    End Sub
```

**Comment by stax76** [comment]
I guess I can use MenuStripTextDefaultColor for the border and separator.

**Comment by Dendraspis** [comment]
Indeed - so it has the same color as the text, which is good.  👍

**Comment by stax76** [comment]
Hotfix and commit is online.

**Comment by Dendraspis** [comment]
I've changed the color of the first  method to `BorderColor` just to be compliant.  😊 

I'm curious if you try to fix the separators.  🍿 🍿

**Comment by JJKylee** [comment]
Wow... I think the fix works. 👍👍👍

![StaxRip_2 1 8 2_stax76-hotfix3_menu-top-bottom-borders_separator_20210223](https://user-images.githubusercontent.com/3157518/108928929-e25c3e00-75f7-11eb-9b61-3ae1dd1ef492.jpg)

**Comment by Dendraspis** [comment]
I've created separat colors for the border(s) and made them a bit darker, so the menu looks a bit more integrated.

» v29 is out...

**Comment by stax76** [comment]
Search field in apps dialog is fixed.

**Comment by stax76** [comment]
> I'm curious if you try to fix the separators.

What's wrong with them?

**Comment by Dendraspis** [comment]
😧  Ehm ..... 

> For the menu separator there is an artifact on the left side and on the ride side.

**Comment by stax76** [comment]
The separator is fine like shown in the last picture of JJKylee.

In the Default theme the apps dialog OK status green is too light I think, difficult to read.

**Comment by Dendraspis** [comment]
Oh, completely missed it. So it was the system renderer again ?!  🤢

Very nice!!  👏

**Comment by stax76** [comment]
Good Night

**Comment by Dendraspis** [comment]
......aaaand fixed.  😊
