### ISSUE TITLE
Automatically splitting of output files through multiple preview timings

### ISSUE THREAD

**Issue by HASJ** [staxrip/staxrip#512]
**Is your feature request related to a problem? Please describe.**
The current way to split the input file into small clips is repetitive and not efficient.

**Describe the solution you'd like**
After selecting the duration of the clips you want in the Preview window, a right click option to *Create separated jobs for each segment* would be simple and effective

**Describe alternatives you've considered**
- Manually creating segments, renaming the output file, adding them to the job list and repeating the process.
- A method devised by @44vince44, which can be found here: https://github.com/staxrip/staxrip/issues/511#issuecomment-778478681

**Explain why the feature matters to you**
StaxRip is the one application that does exactly what I want it do to. I like to cut small clips from my gameplay sessions and discard the larger files and StaxRip presents me with a nice GUI to do this, it is open source and what I can do with it is only limited by my knowledge of it's inner workings.
It is honestly baffling I didn't know about this.

**Comment by stax76** [comment]
@HASJ There is a hotfix build online, you need to reset the Preview menu:

- Preview dialog press m key
- Tools > Reset Everything > OK

Then you can find:

Cut > Create job for each selection

**Comment by 44vince44** [comment]
@stax76 i've just tested it: one test only (AVS) , a composite range of three sub-ranges.
Three jobs were created, each job made a video/audio of the correct subrange.

**THANKS !!!!**

@HASJ please take the hotfix executable and follow instructions that @stax76 layed above to make the new option appear.

**Comment by HASJ** [comment]
Got damn! @stax76 that's some quick work!
@44vince44 thanks for the ping
