### ISSUE TITLE
Hardcoded subs doesn't works.

### ISSUE THREAD

**Issue by ZeroCool22** [staxrip/staxrip#513]
**StaxRip 2.1.8.0-Stable**
I tried with the default settings and the result is the same, no subs.

![Screenshot_18](https://user-images.githubusercontent.com/13344308/107882541-ac68dc80-6ec8-11eb-9a12-cd471df9627e.png)

I converted the SRT subs to **ASS** (with Subtitle Edit), then Ctrl + H and add the ASS subtitles.

Then press start, the video (MKV) is processed without errors but the subs, aren't in the video.

**What could be the problem?**

**Comment by 44vince44** [comment]
Please send the log, I can help you with that. There are several know reasons.
If you're using Avisynth and your process is 10 or more bits, it won't work because the subs filter is only 8 bits in avisynth....

**Comment by ZeroCool22** [comment]
Thx for reply.

1. Never used the LOG, this is what i need to send you?
![Screenshot_18](https://user-images.githubusercontent.com/13344308/107883747-8266e880-6ecf-11eb-9329-eac639be6126.png)

2. When i use:
![Screenshot_19](https://user-images.githubusercontent.com/13344308/107883742-7549f980-6ecf-11eb-92a3-19d69adca409.jpg)

I get this error:
![Error](https://user-images.githubusercontent.com/13344308/107883774-b80bd180-6ecf-11eb-9cb3-27d4edf607ca.png)

**Comment by ZeroCool22** [comment]
Here is the LOG: http://www.pasteuf.store/paste.php?id=1448

**Comment by ZeroCool22** [comment]
If i just use **Tools** > **Advanced** > **Add Hardcoded Subs** i don't get any error, but the subs just doesn't get added to the video.

**Comment by 44vince44** [comment]
OK, so you have indeed a 10 bit source file.
So you can't use Avisynth because the subtitle filter of Avisynth is limited to 8 bits. But not Vapoursynth.

So you need to change the Filter Setup to Vapoursynth (where it says Avisynth on the Main Window, click on it, select "Filter Setup", select VapourSynth). and NOW use Ctrl+H. And of course remove the subtitles file from NVEnc. When you press Preview, you'll see the subtitles working.

Now that must work. Please zip the subtitles file and send drop it here, so I can see why it makes NVEnc crash...

**Comment by ZeroCool22** [comment]
**SRT:** http://www.mediafire.com/file/zc9fmw68dygyefb/Sub_SRT.rar/file

**ASS:** http://www.mediafire.com/file/oz9dctf7s2n3t5f/Sub_%2ASS.rar/file

Will try now what you told me...

**Comment by 44vince44** [comment]
@ZeroCool22 your srt and ass files are not correctly saved in UNICODE UTF-8.
Use your subtitles tool, and convert them to UTF-8. Otherwise the special characters will not be displayed correctly (ALWAYS check with preview)

**Comment by ZeroCool22** [comment]
@44vince44 

Awesome man!

Now it works, subs are working.

Very thanks! 👍

**PD:** It was my fault i didn't realize the video was 10 Bits.

**Comment by ZeroCool22** [comment]
> 
> 
> @ZeroCool22 your srt and ass files are not correctly saved in UNICODE UTF-8.
> Use your subtitles tool, and convert them to UTF-8. Otherwise the special characters will not be displayed correctly (ALWAYS check with preview)

Right!

And you know what means BOM?

![Screenshot_20](https://user-images.githubusercontent.com/13344308/107884612-b8f33200-6ed4-11eb-917c-48df856c345e.png)

I remember if i choose without BOOM i get some strange characters, but with BOM it goes well.

**Comment by Dendraspis** [comment]
> And you know what means BOM?

https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by 44vince44** [comment]
chose WITH BOM (it's a like a data header in the file)

**Comment by ZeroCool22** [comment]
Thank you, you were very kind.

**Comment by 44vince44** [comment]
You're welcome !
