### ISSUE TITLE
CRASH when closing two successive preview windows with the ESC key

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#515]
**Describe the bug**
When you have two or more previews open, closing first preview with ESC works, then closing second preview with ESC CRASHES

Version = 2.1.8.1 LATEST HOTFIX exe. Edit: also tested v 2.1.8.0, crashed.

```

NullReferenceException (2.1.8.1)

Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.UI.CustomMenu.OnKeyDown(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at StaxRip.PreviewForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Expected behavior**
It shouldn't crash.
When closing with the red cross at the corner, it doesn't crash.

**How to reproduce the issue**

1. Open a video
2. press PREVIEW once. if it's full screen, make it windowed
3. press PREVIEW again. Now you have two previews open.
4. Click inside latest preview one, press ESC, it closes.
5. Click inside second preview, press ESC, it crashes.

This is related to ESC only because closing with the cross at the upper-right corner does not crash.

**Comment by Dendraspis** [comment]
Just to be precise:
This happens with ***every*** shortcut after the first window was closed - via shortcut or not.

**Comment by Dendraspis** [comment]
@44vince44 
Here is a fix for you:
[StaxRip v2.1.8.1D_PreviewFix.zip](https://github.com/staxrip/staxrip/files/5980793/StaxRip.v2.1.8.1D_PreviewFix.zip)

**Comment by Dendraspis** [comment]
@stax76 
The fix is far away from being perfect, but the best without messing up your code. Some controls are not disposed as far as possible.

The problem is, that `CustomMenu.Items.MenuItem` seems to be shared with each instance of `PreviewForm`. So when `PreviewForm.Dispose()` is called, it disposes ***all*** `MenuItem`s.

**Comment by Dendraspis** [comment]
@44vince44 
Here is the fixed version:
[StaxRip v2.1.8.1D_PreviewFix2.zip](https://github.com/staxrip/staxrip/files/5981046/StaxRip.v2.1.8.1D_PreviewFix2.zip)

**Comment by stax76** [comment]
> So the solution was removing the shortcut handler from the closing form - great!

That didn't help at all.

Here is what fixed it:

https://github.com/staxrip/staxrip/commit/53884619a4f32d93dea034098621193a713c010c#diff-a840d2b8bc709ec5772a88dd11e404970460bb6475fee883ff8a17969e21f932L538

**Comment by Dendraspis** [comment]
Even better.  😁   Good catch!

**Comment by 44vince44** [comment]
lol do we have a final hotfixed exe to test ??

**Comment by Dendraspis** [comment]
Yes, the one I posted above.  🤔

**Comment by 44vince44** [comment]
i mean did you rebuild it so it has the latest hotfix ??

**Comment by Dendraspis** [comment]
it was the latest build/hotfix/whatsoever  😄

**Comment by 44vince44** [comment]
ok gonna try it 😁

**Comment by 44vince44** [comment]
@Dendraspis @stax76 thanks, it appears to be fixed. I'll continue working with it and try reproduce it of course, but I bet it's ok now!

**Comment by Dendraspis** [comment]
@44vince44 
Literally I have nothing done.  🙄 
But it ***must*** be okay now.  😊

**Comment by 44vince44** [comment]
@Dendraspis Thanks any for anybody who cared about the issue. They say it's the thought that counts 😁 😄 😍
