### ISSUE TITLE
Add another filters to StaxRip

### ISSUE THREAD

**Issue by AlucardSama04** [staxrip/staxrip#516]
Can you add another filters to StaxRip like placebo.Deband?

**Comment by stax76** [comment]
Please provide a project URL if you want a plugin to be included.

If it's not popular or the file size is too large, you can customize staxrip, there is some documentation, but it's still a somehow advanced task.

https://staxrip.readthedocs.io/usage.html#filter-profiles

https://github.com/staxrip/staxrip/wiki/How-to-register-DGTonemap-&-DGHDRtoSDR-filters-in-StaxRip

**Comment by AlucardSama04** [comment]
Ok
https://github.com/Lypheo/vs-placebo
https://github.com/AlucardSama04/faggotDb

**Comment by 44vince44** [comment]
@AlucardSama04 you can add vapoursynth filters yourself, by putting the filter files in your Settings\Plugins\VapourSynth.
They will be autoloaded, and you can edit the filters profile to integrate integrate it in your Staxrip.

However, in order to add it to Staxrip official releases, there must be:
- requests from several users
- at least a DECENT documentation of the filter available

**Comment by JJKylee** [comment]
I agree with @44vince44. At least their documentation seems to _lack sufficient info_.

I tried implementing `placebo.Deband` for example, but what the heck is this?

> planes: the planes to filter. **_The n-th plane is processed if the n-th lowest bit of planes is 1_**, so for example to filter all planes, pass `planes = 1 | 2 | 4`.

And if a user has to refer to the header files...

> For details on the debanding params and the dither methods, see the libplacebo header files.

it's not ready for use at the end user level.

I don't think they are ready to be natively available in StaxRip yet.

But you can go ahead and implement them on your own, @AlucardSama04.

**Comment by stax76** [comment]
libplacedo is a mpv component btw. I think, author is called haasn I think and works on vulkan support, that's how I remember it.

**Comment by DJATOM** [comment]
> 1 | 2 | 4

Evaluates to 7.
So, most useful modes:
Y only - 1
UV only - 6 
All planes - 7
Indeed obscure and should be handled inside filter's constructor/creator function, exposing more meaningful options to user.

**Comment by 44vince44** [comment]
IMHO, the placebo is very specific and too few users would see an interest in it.
I took a look at the debanding filter... I understood the parameters all right. It seems a powerful filter. However, setting that many parameters can only be suitable for people with strong interest in that (and who can understand them). Most people can't even handle the radius + threshold parameters...
Again, imho, if anyone wants to add this filter, and can understand it, I think they wouldn't mind adding it themselves.

**Comment by AlucardSama04** [comment]
If you can't handle the radius and threshold params, it means you aren't a good encoder.

**Comment by AlucardSama04** [comment]
If you can't handle the radius and threshold params, it means you aren't a good encoder.

**Comment by 44vince44** [comment]
> If you can't handle the radius and threshold params, it means you aren't a good encoder.

I think you didn't understand. I was talking about users. If you came to criticize, you're not welcome. Everything here is good, the only bad thing is you, for allowing yourself this kind of comment.

**Comment by DJATOM** [comment]
There's no good or bad encoders. People tends to put themselves on airs at some point. 
Good encoders aren't about handling options, but about ability to learn and aim for new methods of video processing and video compression techniques. Or at least that's what I believe in.
