### ISSUE TITLE
Please restore ALL the files that must be in the Avisynth folder of Frameserver (v2.1.8.x)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#517]
**Describe the bug**
In Frameserver\AviSynth\plugins  there should be 6 dlls that come with official release of AviSynth.
They are missing since v2.1.8.0

**Expected behavior**
Those files must be included because they are part of AviSynth release.

**Comment by stax76** [comment]
I've restored it. No clue what happened with those files...

**Comment by JJKylee** [comment]
Can't believe nobody has found out about this except @44vince44 till now. 🤣
As for me, I usually skip the portable part... 😅

**Comment by 44vince44** [comment]
Thanks @stax76 I'm surprised no one reacted 🤣 
Only a nerd like me could be affected by that ....

**Comment by Dendraspis** [comment]
> Can't believe nobody has found out about this except @44vince44 till now. 🤣
> As for me, I usually skip the portable part... 😅

I use portable apps/scripts only and meanwhile I switched to VPY.  🤣
