### ISSUE TITLE
Error exit code: 1 (0x1).

### ISSUE THREAD

**Issue by ZeroCool22** [staxrip/staxrip#519]
StaxRip-x64-2.1.8.0-Stable
NVEnc: 5.29

**Error:** http://www.pasteuf.store//paste.php?id=1452
**Log:** http://www.pasteuf.store//paste.php?id=1453

**Comment by JJKylee** [comment]
Your avs script is not correctly read by NVEnc in the legacy code page of your system.

```
avs: FFVideoSource: Can't open 'H:\El Se or De Los Anillos - El Retorno Del Rey (2003) BDRip 1080p Latino.mkv'
```

Try putting `--process-codepage os` in the NVEnc Options _custom_ field, as explained in the [NVEnc 5.29 release note](https://github.com/rigaya/NVEnc/releases/tag/5.29).

**Comment by stax76** [comment]
Or use the last StaxRip Beta, it writes the avs script used for nvenc with UTF-8 encoding as expected by nvenc 5.29 on Windows 10 1903 or later.

**Comment by ZeroCool22** [comment]
Thx you.
