### ISSUE TITLE
Support for importing information from .nfo files

### ISSUE THREAD

**Issue by Havokdan** [staxrip/staxrip#52]
Boa tarde, estou aqui para aditar um pedido que fiz no fórum doom9, que é a importação de tags para os arquivos mkv como tags próprias desse container, estou a propor que, vou dar um exemplo prático:

Exemplo 01 - Para filmes:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<movie>
  <title>60 Segundos</title>
  <originaltitle>Gone in Sixty Seconds</originaltitle>
  <sorttitle/>
  <epbookmark/>
  <year>2000</year>
  <ratings>
    <rating default="true" max="10" name="themoviedb">
      <value>6.2</value>
      <votes>2371</votes>
    </rating>
  </ratings>
  <userrating>0.0</userrating>
  <top250>0</top250>
  <set/>
  <outline/>
  <plot>Randall "Memphis" Raines (Nicolas Cage) um lend├írio ladr├úo de carros. Nenhuma fechadura ou alarme pode par├í-lo e ele consegue roubar seu carro em apenas 60 segundos. Durante anos, Memphis iludiu a pol├¡cia local, aplicando todo tipo de golpe imagin├ível. Mas quando o cerco ficou muito intenso, ele decidiu por largar a vida de crimes e partir para uma vida completamente diferente. Mas agora, quando seu irm├úo ca├ºula (Giovanni Ribisi) est├í tentando seguir seus passos no mundo do assalto a autom├│veis, Memphis volta a agir para tentar salvar a vida de seu irm├úo.</plot>
  <tagline>├ë s├│ o que precisa para seu carro sumir.</tagline>
  <runtime>118</runtime>
  <thumb aspect="poster">http://image.tmdb.org/t/p/w500/yzwyP9DIKxky986LjWI3FObAmOH.jpg</thumb>
  <fanart>
    <thumb>http://image.tmdb.org/t/p/original/8tlcHEUVw4pJgWUuV2GthbvJEhQ.jpg</thumb>
  </fanart>
  <mpaa>Rated PG-13</mpaa>
  <certification>US:PG-13 / US:Rated PG-13</certification>
  <id>tt0187078</id>
  <tmdbid>9679</tmdbid>
  <uniqueid default="false" type="tmdb">9679</uniqueid>
  <uniqueid default="true" type="imdb">tt0187078</uniqueid>
  <uniqueid default="false" type="trakt">4951</uniqueid>
  <country>Estados Unidos</country>
  <status/>
  <code/>
  <premiered>2000-06-09</premiered>
  <watched>true</watched>
  <playcount>1</playcount>
  <lastplayed/>
  <genre>A├º├úo</genre>
  <genre>Policial</genre>
  <genre>Thriller</genre>
  <studio>Jerry Bruckheimer Films</studio>
  <studio>Touchstone Pictures</studio>
  <credits>H.B. Halicki</credits>
  <credits>Scott Rosenberg</credits>
  <director>Dominic Sena</director>
  <tag>sibling relationship</tag>
  <tag>detective</tag>
  <tag>car race</tag>
  <tag>car thief</tag>
  <tag>blackmail</tag>
  <tag>brother</tag>
  <tag>remake</tag>
  <tag>heist</tag>
  <tag>betrayal</tag>
  <tag>organized crime</tag>
  <tag>shootout</tag>
  <tag>police chase</tag>
  <tag>explosion</tag>
  <tag>violence</tag>
  <tag>lock pick</tag>
  <tag>car chase</tag>
  <tag>stakeout</tag>
  <tag>illegal drugs</tag>
  <tag>stolen cars</tag>
  <tag>ford mustang</tag>
  <tag>blacklight</tag>
  <actor>
    <name>Nicolas Cage</name>
    <role>Randall 'Memphis' Raines</role>
    <thumb>http://image.tmdb.org/t/p/h632/kFULDrUeofwJg5kqCcNftmBcBZP.jpg</thumb>
    <profile>https://www.themoviedb.org/person/2963</profile>
  </actor>
  <actor>
    <name>Giovanni Ribisi</name>
    <role>Kip Raines</role>
    <thumb>http://image.tmdb.org/t/p/h632/mLQrEU7X7GD5V7i1clGRqpg8PVk.jpg</thumb>
    <profile>https://www.themoviedb.org/person/1771</profile>
  </actor>
  <actor>
    <name>Angelina Jolie</name>
    <role>Sara 'Sway' Wayland</role>
    <thumb>http://image.tmdb.org/t/p/h632/gD8jlGkQC8GBajulNlIzBK1YEO1.jpg</thumb>
    <profile>https://www.themoviedb.org/person/11701</profile>
  </actor>
  <actor>
    <name>T.J. Cross</name>
    <role>Mirror Man</role>
    <thumb>http://image.tmdb.org/t/p/h632/kYf4hL8UfzUhLuDwACJFWop6hrN.jpg</thumb>
    <profile>https://www.themoviedb.org/person/58497</profile>
  </actor>
  <actor>
    <name>William Lee Scott</name>
    <role>Toby</role>
    <thumb>http://image.tmdb.org/t/p/h632/dq4IWfaRLghUgkIUB7UVBlhWj8t.jpg</thumb>
    <profile>https://www.themoviedb.org/person/10128</profile>
  </actor>
  <actor>
    <name>Scott Caan</name>
    <role>Tumbler</role>
    <thumb>http://image.tmdb.org/t/p/h632/kvUKf9HCaqUtgj7XuKZOvN66MOT.jpg</thumb>
    <profile>https://www.themoviedb.org/person/1894</profile>
  </actor>
  <actor>
    <name>James Duval</name>
    <role>Freb</role>
    <thumb>http://image.tmdb.org/t/p/h632/psa8zYiaIeyUWH2cnZG0w11G3dW.jpg</thumb>
    <profile>https://www.themoviedb.org/person/1582</profile>
  </actor>
  <actor>
    <name>Will Patton</name>
    <role>Atlee Jackson</role>
    <thumb>http://image.tmdb.org/t/p/h632/qpycaaWP1oUx1Wd2lMBfQtR7qDO.jpg</thumb>
    <profile>https://www.themoviedb.org/person/883</profile>
  </actor>
  <actor>
    <name>Delroy Lindo</name>
    <role>(Det) Roland Castlebeck</role>
    <thumb>http://image.tmdb.org/t/p/h632/uhjdTemc2kYbQj47bVqRb7OdVjH.jpg</thumb>
    <profile>https://www.themoviedb.org/person/18792</profile>
  </actor>
  <actor>
    <name>Timothy Olyphant</name>
    <role>(Det) Drycoff</role>
    <thumb>http://image.tmdb.org/t/p/h632/qPqm3mx3xzROFjlSGvh5dqR0XtV.jpg</thumb>
    <profile>https://www.themoviedb.org/person/18082</profile>
  </actor>
  <actor>
    <name>Chi McBride</name>
    <role>Donny Astricky</role>
    <thumb>http://image.tmdb.org/t/p/h632/8SZovWxZzQ78uQp2rNzU9fKyYJS.jpg</thumb>
    <profile>https://www.themoviedb.org/person/8687</profile>
  </actor>
  <actor>
    <name>Robert Duvall</name>
    <role>Otto Halliwell</role>
    <thumb>http://image.tmdb.org/t/p/h632/1aBC7NxPy10ofng6HsJBecJ1vMZ.jpg</thumb>
    <profile>https://www.themoviedb.org/person/3087</profile>
  </actor>
  <actor>
    <name>Christopher Eccleston</name>
    <role>Raymond Calitri</role>
    <thumb>http://image.tmdb.org/t/p/h632/bx7RmVIxxuC1ZTGVIOuuvkP88OQ.jpg</thumb>
    <profile>https://www.themoviedb.org/person/2040</profile>
  </actor>
  <actor>
    <name>Vinnie Jones</name>
    <role>The Sphinx</role>
    <thumb>http://image.tmdb.org/t/p/h632/1QQea9t0JkRVVVbgVtpGAQuf0x5.jpg</thumb>
    <profile>https://www.themoviedb.org/person/980</profile>
  </actor>
  <actor>
    <name>Grace Zabriskie</name>
    <role>Helen Raines</role>
    <thumb>http://image.tmdb.org/t/p/h632/19tr5IbzCmv4x5B3WFlG1RQPwXu.jpg</thumb>
    <profile>https://www.themoviedb.org/person/6465</profile>
  </actor>
  <actor>
    <name>Frances Fisher</name>
    <role>Junie</role>
    <thumb>http://image.tmdb.org/t/p/h632/248IbuAi6RQG5l94a4hClUswbA5.jpg</thumb>
    <profile>https://www.themoviedb.org/person/3713</profile>
  </actor>
  <actor>
    <name>Jesse Corti</name>
    <role>Cop - At Quality Caf├⌐</role>
    <thumb>http://image.tmdb.org/t/p/h632/eiZnJIqQ6JTzusiMF1GnhDjVWdw.jpg</thumb>
    <profile>https://www.themoviedb.org/person/75599</profile>
  </actor>
  <actor>
    <name>Lois Hall</name>
    <role>Old Woman</role>
    <thumb>http://image.tmdb.org/t/p/h632/k6AR981Wne31IhGAGxrb7FSalV7.jpg</thumb>
    <profile>https://www.themoviedb.org/person/69642</profile>
  </actor>
  <actor>
    <name>Dean Rader Duval</name>
    <role>Hype</role>
    <thumb>http://image.tmdb.org/t/p/h632/dbvphLdVQwcW9JHIqufKhC3HtLx.jpg</thumb>
    <profile>https://www.themoviedb.org/person/1279744</profile>
  </actor>
  <actor>
    <name>Kevin Weisman</name>
    <role>Intern 2</role>
    <thumb>http://image.tmdb.org/t/p/h632/scVnbzhfefR0tp0p4X6LHiKIgQx.jpg</thumb>
    <profile>https://www.themoviedb.org/person/149670</profile>
  </actor>
  <actor>
    <name>Billy Devlin</name>
    <role>Detective Jurgens</role>
    <thumb>http://image.tmdb.org/t/p/h632/dnxo4BhdJk2LWYnhz7zLiuZZ9mt.jpg</thumb>
    <profile>https://www.themoviedb.org/person/1838353</profile>
  </actor>
  <actor>
    <name>Bodhi Elfman</name>
    <role>Frizzel</role>
    <thumb>http://image.tmdb.org/t/p/h632/8E88yatmj6bJywXqLmm1I0C3RWR.jpg</thumb>
    <profile>https://www.themoviedb.org/person/154883</profile>
  </actor>
  <actor>
    <name>Arye Gross</name>
    <role>James Lakewood</role>
    <thumb>http://image.tmdb.org/t/p/h632/ha4ziYlBSBBHs88ltnamOKLZ084.jpg</thumb>
    <profile>https://www.themoviedb.org/person/72028</profile>
  </actor>
  <actor>
    <name>Greg Collins</name>
    <role>San Pedro Cop</role>
    <thumb>http://image.tmdb.org/t/p/h632/42p7hsOck2OzIkr4b9Wtp0HckkG.jpg</thumb>
    <profile>https://www.themoviedb.org/person/58950</profile>
  </actor>
  <actor>
    <name>Joseph Patrick Kelly</name>
    <role>Snake G.R.A.B.</role>
    <thumb>http://image.tmdb.org/t/p/h632/FsyGOuH6AEbKf6VtTrhlaBnUs2.jpg</thumb>
    <profile>https://www.themoviedb.org/person/173886</profile>
  </actor>
  <actor>
    <name>Scott Burkholder</name>
    <role>Rent a Cop</role>
    <thumb>http://image.tmdb.org/t/p/h632/h77cldT88mrsvCr7Lw7sRvYMgoo.jpg</thumb>
    <profile>https://www.themoviedb.org/person/104503</profile>
  </actor>
  <actor>
    <name>Billy 'Sly' Williams</name>
    <role>Cop</role>
    <thumb>http://image.tmdb.org/t/p/h632/jhzsqj8kzuY72Dzl4wuwPcvz3IH.jpg</thumb>
    <profile>https://www.themoviedb.org/person/1088201</profile>
  </actor>
  <actor>
    <name>Carmen Argenziano</name>
    <role>Detective Mayhew</role>
    <thumb>http://image.tmdb.org/t/p/h632/8fi4xfPwYVHulKvmTTlwBx2nvLo.jpg</thumb>
    <profile>https://www.themoviedb.org/person/28413</profile>
  </actor>
  <actor>
    <name>Michael Pe├▒a</name>
    <role>Ignacio</role>
    <thumb>http://image.tmdb.org/t/p/h632/oqlIKSglghuX7kSTalODn71nlOd.jpg</thumb>
    <profile>https://www.themoviedb.org/person/454</profile>
  </actor>
  <actor>
    <name>John Carroll Lynch</name>
    <role>Impound Manager</role>
    <thumb>http://image.tmdb.org/t/p/h632/5eEGOANKnCCj7FLa3oV28gGYWkW.jpg</thumb>
    <profile>https://www.themoviedb.org/person/3911</profile>
  </actor>
  <actor>
    <name>Ken Jenkins</name>
    <role>Televangelist (uncredited)</role>
    <thumb>http://image.tmdb.org/t/p/h632/6w9OgC4nGUfYavC86a3FeeMgUJ4.jpg</thumb>
    <profile>https://www.themoviedb.org/person/38570</profile>
  </actor>
  <actor>
    <name>Master P</name>
    <role>Johnnie B. (uncredited)</role>
    <thumb>http://image.tmdb.org/t/p/h632/crshi8WF4eXvaumY5CLmPoTyMFB.jpg</thumb>
    <profile>https://www.themoviedb.org/person/65164</profile>
  </actor>
  <actor>
    <name>Brian McNamara</name>
    <role>Parking Garage Attendant (uncredited)</role>
    <thumb>http://image.tmdb.org/t/p/h632/aemVY13WmPKj3TOWSvtbWs7Vgzu.jpg</thumb>
    <profile>https://www.themoviedb.org/person/27238</profile>
  </actor>
  <producer>
    <name>Jerry Bruckheimer</name>
    <role>Producer</role>
    <thumb>http://image.tmdb.org/t/p/h632/lQu9eRzRX264j2LFQwvKC50wb9s.jpg</thumb>
  </producer>
  <producer>
    <name>Denice Shakarian Halicki</name>
    <role>Executive Producer</role>
    <thumb/>
  </producer>
  <producer>
    <name>Jonathan Hensleigh</name>
    <role>Executive Producer</role>
    <thumb>http://image.tmdb.org/t/p/h632/l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg</thumb>
  </producer>
  <producer>
    <name>Chad Oman</name>
    <role>Executive Producer</role>
    <thumb>http://image.tmdb.org/t/p/h632/l84amvUZOrpSU5GRTDYoEkvbh25.jpg</thumb>
  </producer>
  <producer>
    <name>Mike Stenson</name>
    <role>Producer</role>
    <thumb/>
  </producer>
  <producer>
    <name>Robert Stone</name>
    <role>Executive Producer</role>
    <thumb/>
  </producer>
  <producer>
    <name>Webster Stone</name>
    <role>Executive Producer</role>
    <thumb/>
  </producer>
  <producer>
    <name>Barry H. Waldman</name>
    <role>Executive Producer</role>
    <thumb/>
  </producer>
  <producer>
    <name>Aristides McGarry</name>
    <role>Associate Producer</role>
    <thumb/>
  </producer>
  <producer>
    <name>Pat Sandston</name>
    <role>Associate Producer</role>
    <thumb/>
  </producer>
  <producer>
    <name>Victoria Thomas</name>
    <role>Casting</role>
    <thumb>http://image.tmdb.org/t/p/h632/cdOR8cgySFsgxWtp6hGA3eMsVra.jpg</thumb>
  </producer>
  <producer>
    <name>Diane L. Sabatini</name>
    <role>Production Supervisor</role>
    <thumb/>
  </producer>
  <trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=cxCE9gDm1vo&amp;hd=1</trailer>
  <languages>ingl├¬s</languages>
  <dateadded>2017-04-07</dateadded>
  <fileinfo>
    <streamdetails>
      <video>
        <codec>h264</codec>
        <aspect>2.35</aspect>
        <width>1920</width>
        <height>816</height>
        <durationinseconds>7077</durationinseconds>
        <stereomode/>
      </video>
      <audio>
        <codec>AAC</codec>
        <language/>
        <channels>2</channels>
      </audio>
    </streamdetails>
  </fileinfo>
  
  <source>UNKNOWN</source>
  <edition>NONE</edition>
</movie>

In this case, you would import from this file, by way of example, since there are so many fields, that the file would import as a tag:

<plot> as a mkv tag title

> Randall "Memphis" Raines (Nicolas Cage) um lendário ladrão de carros. Nenhuma fechadura ou alarme pode pará-lo e ele consegue roubar seu carro em apenas 60 segundos. Durante anos, Memphis iludiu a polícia local, aplicando todo tipo de golpe imaginável. Mas quando o cerco ficou muito intenso, ele decidiu por largar a vida de crimes e partir para uma vida completamente diferente. Mas agora, quando seu irmão caçula (Giovanni Ribisi) está tentando seguir seus passos no mundo do assalto a automóveis, Memphis volta a agir para tentar salvar a vida de seu irmão.
And the text above as the content of the plot tag

In brief, summarized synthesis, all fields <field> text </field> were imported. Since <field> was imported as the name of the respective tag, the text as the content of the respective tag.

**Comment by stax76** [comment]
Which fields would you like to be imported?

Sugestion:

title
originaltitle
showtitle
studio
genre
director
season
episode
premiered
aired
outline
plot
tagline

Available fields:

```
<?xml version="1.0" encoding="utf-8"?>
<movie>
  <title></title>
  <originaltitle></originaltitle>
  <sorttitle></sorttitle>
  <set></set>
  <rating></rating>
  <top250></top250>
  <votes></votes>
  <outline></outline>
  <plot></plot>
  <tagline></tagline>
  <runtime></runtime>
  <thumb></thumb>
  <mpaa></mpaa>
  <playcount></playcount>
  <uniqueid type="imdb" default="true"></uniqueid>
  <studio></studio>
  <trailer></trailer>
  <genre></genre>
  <credits></credits>
  <director></director>
</movie>


<?xml version="1.0" encoding="utf-8"?>
<tvshow>
  <title></title>
  <showtitle></showtitle>
  <rating></rating>
  <votes></votes>
  <top250></top250>
  <season></season>
  <episode></episode>
  <uniqueid type="tmdb" default="true"></uniqueid>
  <displayseason></displayseason>
  <displayepisode></displayepisode>
  <outline></outline>
  <plot></plot>
  <tagline></tagline>
  <runtime></runtime>
  <mpaa></mpaa>
  <playcount></playcount>
  <lastplayed></lastplayed>
  <genre></genre>
  <premiered></premiered>
  <status></status>
  <code></code>
  <aired></aired>
  <studio></studio>
  <trailer></trailer>
  <set></set>
</tvshow>


<?xml version="1.0" encoding="utf-8"?>
<episodedetails>
  <title></title>
  <rating></rating>
  <season></season>
  <episode></episode>
  <plot></plot>
  <thumb></thumb>
  <playcount></playcount>
  <lastplayed></lastplayed>
  <credits></credits>
  <director></director>
  <aired></aired>
  <premiered></premiered>
  <studio></studio>
  <mpaa></mpaa>
  <displayseason></displayseason>
  <displayepisode></displayepisode>
</episodedetails>
```

**Comment by Havokdan** [comment]
I think your suggestion is great, I have nothing to add.

**Comment by stax76** [comment]
Find a new build here:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by Havokdan** [comment]
I will try

**Comment by stax76** [comment]
You are welcome.

The newest build fixes an exception that occurs when a nfo file does not contain xml content.

https://forum.doom9.org/showthread.php?p=1885113#post1885113
