### ISSUE TITLE
Missing BitRate selection - NvEnc VBR, & CBR modes

### ISSUE THREAD

**Issue by anthony75smith75** [staxrip/staxrip#520]
NvEnc Constant Quality Profile encode selection allows us to set the main rate control or Profile number on the first  Basic tab. More complicated and less used rate control options are then listed on the next Rate Control tab. This simple layout makes things easier and is great.

NvEnc VBR, VBRHQ, CBR, CBRHQ encode selections do not allow us to change the main important rate control option that I'm feeling should be listed on the Basic tab. I can see it in the command line but there is no way to change it. The more complicated and less used options under Rate Control tab are all present but they do not make up for this main missing item we currently can't change.

Command Line:
CBR:                --cbr 7767
CBRHQ:           --cbrhq 7767
VBR:                --vbr 7767
VBRHQ:          --vbrhq 7767

If we manually add --vbrhq 6000 to Other/Custom then the 7767 bit rate listed is replaced with the specified 6000. NvEnc indeed then encodes at 6000 just as it should. Seems we have a layout bug with a missing selection option that should have been a selection on the Basic tab.

**Comment by 44vince44** [comment]
![SNAG-0000](https://user-images.githubusercontent.com/17828567/108047382-63db2b80-704e-11eb-83b9-d73a0868f3c3.jpg)

**Comment by JJKylee** [comment]
Yeah, it's easy to forget. 😆
I used to be confused about it, too, @anthony75smith75. 😓

**Comment by stax76** [comment]
It would be possible to add a bitrate option like available for x265:

Setting the Bitrate option to 0 will use the bitrate defined in the project/template in the main dialog.

But it would be some work.

**Comment by 44vince44** [comment]
there's no rush.....

**Comment by Dendraspis** [comment]
Should be fixed:
[StaxRip v2.1.8.1D_NVEnc.zip](https://github.com/staxrip/staxrip/files/5988216/StaxRip.v2.1.8.1D_NVEnc.zip)

**Comment by stax76** [comment]
Good work.

Small problem I noticed:

x264/x265 allow defining 0 as bitrate in the encoder options, in that case the bitrate of the project and main dialog is used and can be edited in the main dialog, but this design is maybe too complex.

But I think all encoders should work the same for the sake of consistency.

I will make some experiments tomorrow.

**Comment by JJKylee** [comment]
Well, IMO, putting _Bitrate_ alongside _Constant Quality Mode_ in _Rate Control_ category seems more reasonable, because they are _**mutually exclusive**_ and theoretically 'bitrate' option belongs to 'rate control'.

And hiding _Bitrate_ option when _Constant Quality Mode_ is checked (`--vbr 0` or `--vbrhq 0`) seems more desirable.

Plus, `VBR Quality` should be hidden both in the menu and in the command line when _Constant Quality Mode_ is off since `VBR Quality` seems to always go with 'constant quality'. I experimented with `--vbr 2000` with `--vbr-quality 28` and without, and they produce _**different**_ bitrates.

`--vbr 2000` w/o `--vbr-quality 28`: 2,066 Kbps ⇨ hits target bitrate
`--vbr 2000` with `--vbr-quality 28`: 967 Kbps ⇨ misses target bitrate

**Comment by Dendraspis** [comment]
> Small problem I noticed:
> 
> x264/x265 allow defining 0 as bitrate in the encoder options, in that case the bitrate of the project and main dialog is used and can be edited in the main dialog, but this design is maybe too complex.
> 
> But I think all encoders should work the same for the sake of consistency.

🤔 NVEnc now behaves like x264/x265 like you've described it above. So I don't understand your "*but*".

**Comment by stax76** [comment]
> NVEnc now behaves like x264/x265 like you've described it above. So I don't understand your "but".

If you set the bitrate to 0 in the x265 encoder options and close the dialog with OK, you can set the bitrate in the main dialog, and this bitrate is then used, but I think this 0 concept was a mistake, I want to rewrite it tomorrow so the bitrate can be changed both in the encoder dialog and also in the main dialog, and it's kept in sync no matter where it was changed, I'm not sure if it will work out well, but I hope so.

**Comment by DJATOM** [comment]
In the web application we can define a "model" and alter it with setter. Probably such concept can be used with desktop application - you have an instance of settings and altering it's state forces all views where it referenced to re-draw contents (but I'm not familiar with net framework, can't say for sure).

**Comment by Dendraspis** [comment]
💡   Okay, this was not related to this issue or my solution itself, but to the concept they follow now.  The missing NVEnc in the listing confused me.  😁

**Comment by stax76** [comment]
@DJATOM 

It's not using any modern pattern like MVC or MVVM, I think there is zero data binding, it's an old app (since 2002) and certainly has its design flaws, many old apps have them, MPC is much similar in this regard, horrible design if you compare it to mpv, at least the way how I see it. But staxrip has also good parts that were constantly modernized.

**Comment by anthony75smith75** [comment]
Much thanks to all. I didn't know about the extra bit rate settings moved to the first page, completely outside of the NvEnc area. Wow! I think the sync idea listed above has merit then. These bit rate settings could be listed on the NvEnc Basic tab as is done with CQP and then also left on the first page as quick access but always in sync with each other. 

Also of note: When using Constant Quality Profile (CQP) in NvEnc the Max Bitrate option on the Rate Control tab has no effect. Seems like its exclusively using the Quality Number set on Basic Tab. This Max Bitrate option therefore should be removed for CQP. Does work well on CBR or VBR modes.

**Comment by 44vince44** [comment]
> This Max Bitrate option therefore should be removed for CQP

Remember, Staxrip can't handle ALL parameter dependencies... User must be aware of his favorite encoder's syntax.

**Comment by JJKylee** [comment]
@anthony75smith75: FYI, CQP is 'Constant QP(quantization parameter)', not 'Constant Quality Profile'.

**Comment by JJKylee** [comment]
> Remember, Staxrip can't handle ALL parameter dependencies... User must be aware of his favorite encoder's syntax.

You're right.
In the same vein, my note that
> `VBR Quality` should be hidden both in the menu and in the command line when `Constant Quality Mode` is off
can be revoked if needed. 😅

**Comment by stax76** [comment]
I've uploaded a hotfix:

If the bitrate can be changed in the options of x264, x265 or nvenc, then it can also be changed in the main dialog, the bitrate of the main dialog and the encoder dialog are kept in sync.

There is some complexity so it needs some testing. I hope it's not breaking anything.

**Comment by 44vince44** [comment]
In all software, there is a part that the user has to adapt himself to the software.
Here it was very obvious: the user merely has to close the encoder's window and set the value in the main window...
All the trouble you get into for one user who thinks this is too much asking (sorry, no offense intended to anyone).
You should have left the logic as it was, add bitrate inside the encoder window, and simply mention next to it "non zero value override size/bitrate setting in main window"

imho....

**Comment by 44vince44** [comment]
Can't we close this now 🤣

**Comment by stax76** [comment]
Yes, but the unfortunate behavior needs to be added to the wiki first. Started to move the docs to the wiki today, it's probably much better than readthedocs.io, everybody can edit it and markdown is extremely easy and popular. There are other projects that also use wiki for docs, for instance MP4Box, probably many more.

https://github.com/gpac/gpac/wiki
