### ISSUE TITLE
NVENC and QSVENS Subtitles file option must be removed

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#523]
**Describe the bug**
The option Other > Subtitle File must be removed from : 
- NVEnc : h264, h265
- QSVEnc : h264, h265 

because this options allows to **mux (not harcode!)** a subtitle file to the output of NVEnc and QSVEnc. Since in Staxrip the output of the encoder is *.h264 or *.h265, this option makes crash.

**Comment by JJKylee** [comment]
You've got a point.

The console help is not enough for this option `--sub-source`. In online help, it's about _**muxing**_ an external subtitle file.

> Read subtitle from the specified file and **_mux_** into the output file.

Since all we need is the encoded video elementary stream, this option is useless for us.

**Comment by 44vince44** [comment]
And also it leads to a crash !

> In online help, it's about muxing an external subtitle file.

I also had confirmation from Rigaya https://github.com/rigaya/NVEnc/issues/311

**Comment by JJKylee** [comment]
You're right. ES cannot contain subtitle streams. And subtitle hard-burning is available only via `--vpp-subburn`.

BTW, @Dendraspis and I once agreed that in NVEnc, **_online_** help is a must. (Console help is often wrong and insufficient.) 😆
