### ISSUE TITLE
Problem with ffmpeg encoding in staxrip 2.1.8.0

### ISSUE THREAD

**Issue by mr-qansuh** [staxrip/staxrip#525]
![2021-02-19_234337](https://user-images.githubusercontent.com/79289286/108564794-55ba3300-730c-11eb-9bb3-a697bf54dcf1.png)

**Comment by 44vince44** [comment]
@mr-qansuh this version of ffmpeg has a problem with asci non-standard characters (here Arabic names of the folders). @Patman86 and @stax76 are working on next ffmpeg build to remove this problem. The solution will work on all recent versions of Windows 10.


Why are you using ffmpeg to encode x264??  use x264 directly it's much better !

**Comment by mr-qansuh** [comment]
Thank you 

I was just trying to figure out the best way to convert.

> @mr-qansuh this version of ffmpeg has a problem with asci non-standard characters (here Arabic names of the folders). @Patman86 and @stax76 are working on next ffmpeg build to remove this problem. The solution will work on all recent versions of Windows 10.
> 
> Why are you using ffmpeg to encode x264?? use x264 directly it's much better ! and it works with Arabic characters.

**Comment by Patman86** [comment]
I've uploaded a new version, please test it.
[ffmpeg long path support (hope it works)](https://www.mediafire.com/file/q198mpqybeggwlg/ffmpeg-N-101189-g029e3c1c70-x64-gcc10.2.0.7z/file)

**Comment by 44vince44** [comment]
@Patman86 I could test in the conditions mentioned above that are: staxrip is in a path with Arabic characters. Now it works !

However I could not test with a file that has Arabic characters, because Staxrip forbids it saying that "The current AviSynth encoder does not support Unicode"

@stax76 we could remove that now, since Patman's new FFMPEG appears to work with unicode...

**Comment by stax76** [comment]
I confirm that AviSynth Unicode and Long Path support is fully working on Windows 10 1903.

It was the last important tool not supporting it. We've made it. 🙂

New hotfix is available, Wiki pages will be updated shortly.

**Comment by 44vince44** [comment]
I think we can expect a new beta soon with lots of improvements 😁
