### ISSUE TITLE
Is there any way to ONLY use STAXRIP for cutting and then leave the file NOT converted?

### ISSUE THREAD

**Issue by smallmagpie** [staxrip/staxrip#526]

**Comment by Dendraspis** [comment]
This is not possible. 
Think of it like a house where you want to remove the ground floor without rebuilding the house.

**Comment by 44vince44** [comment]
Yes there is, it's called COPY/MUX. You select this in the Video encoder section (instead of x265) and in the Audio encoder section (instead of Opus ~250 kpbs)

**Comment by smallmagpie** [comment]
> Yes there is, it's called COPY/MUX. You select this in the Video encoder section (instead of x265) and in the Audio encoder section (instead of Opus ~250 kpbs)

When i select COPY/MUX,the video will be copied instead of cutting.

**Comment by stax76** [comment]
Copy and cut is only supported with mkv output using mkvmerge.

This is documented in various locations.
