### ISSUE TITLE
MP4Box in 2.0.4.3 Beta leaves a Wolfberry metadata in the video stream

### ISSUE THREAD

**Issue by gnucian** [staxrip/staxrip#53]
I know that this is related to Wolfberry's MP4Box build, but I'm opening an issue here because I don't know where to go about this matter.

Like the title says, Wolfberry's MP4Box included in 2.0.4.3 Beta seems to leave a '**Title**' metadata in the **video** stream containing the version info of the MP4Box build.

![StaxRip-2 0 4 3-Beta_mp4box(Wolfberry)_video_stream_finger-print](https://user-images.githubusercontent.com/3157518/64918792-ee33a780-d757-11e9-8516-c7af7b601a36.jpg)

How can we deal with this?

**Comment by stax76** [comment]
Maybe send him a private message in the doom9 forum.

**Comment by gnucian** [comment]
Thanks for the pointer.
I did.
