### ISSUE TITLE
NvEnc - Move Decoder & Interlace from Other back to Basic 

### ISSUE THREAD

**Issue by anthony75smith75** [staxrip/staxrip#534]
NvEnc encoder options allow us to change the Decoder we use. It effects other plug ins like AviSynth so it is best left under Basic as it is very easy to change here. I noticed in Beta version 2.18.2 it has been moved and buried in Other. Same story with the global Interlace flag which is needed for the interlace settings tab under VPP. Where has Input Colorspace gone? Could it be moved to the other Colorspace options under VPP? 

Much thanks for your time and dedication to these suggestions.

**Comment by JJKylee** [comment]
Well, I can see the changes are reverted somehow in the course of the beta update.

That said, do we really need to stick to where the options are? As for me, I don't care as long as the option names and values are correct since I can always make use of the **_search box_** and **_encoder profiles_**.

![StaxRip_2 1 8 2_NVEnc_encoder-options_utilize-search-box_20210221](https://user-images.githubusercontent.com/3157518/108662185-a3f14280-7482-11eb-96a7-7e540dece39a.gif)

It'd be good if the options are placed where they used to be, but... you know... 😓

**Comment by 44vince44** [comment]
I suggest nothing is moved until @Dendraspis 's works on Dark Theme are completely finished!

**Comment by Dendraspis** [comment]
@44vince44 
No, that's absolutely no problem.  😄 

@stax76 changed the decoder position in cce11be3, maybe for a reason?!  🤔 

> please put option --input-csp (Input Colorspace) back, it has completely disappeared!

Seems like something went horribly wrong. 😲

**Comment by stax76** [comment]
--input-csp is only relevant for raw input I think, but that isn't supported anyway and maybe cannot be supported, at least not without also having raw input in avs/vs, there we should really add support:

https://forum.doom9.org/showthread.php?t=39798&page=8

https://forum.doom9.org/showthread.php?t=166075

From the nvenc docs:

--input-csp <string>           set input colorspace for **raw reader**

I think no encoder has the decoder option in the basic tab, it should probably be all or none, I think it's not basic but advanced.

**Comment by 44vince44** [comment]
Ok now it makes sense ! Sorry for this false alert :-)

**Comment by Dendraspis** [comment]
Maybe creating an Input/Output section for NVEnc, too?  🤔

**Comment by stax76** [comment]
Maybe I thought about it but couldn't find enough options for it.

**Comment by Dendraspis** [comment]
Maybe creating an ***Input/Output*** section for NVEnc decoder as well ?  🤔

**Comment by JJKylee** [comment]
That‘s a good idea. 👍

**Comment by stax76** [comment]
Which options would belong into _Input/Output_?

**Comment by JJKylee** [comment]
First of all, _Decoder_, _Interlace_, _Input Option_.

And _Pipe_ should be added with _avspipemod_ and _ffmpeg_.

As you may know, example code snippets are...

```
avs2pipemod -y4mp "<avsfile>" | NVEncC --y4m -i - -o "<outfilename.264>"
```

```
ffmpeg -y -i "<inputfile>" -an -pix_fmt yuv420p -f yuv4mpegpipe - | NVEncC --y4m -i - -o "<outfilename.264>"
```

> --input-csp set input colorspace for raw reader

> But I don't know what exactly raw reader means, raw file or raw pipe or maybe both.

I guess it's when NVencC reads a _raw YUV file_ only.

> `--input-csp` <string>
> Set input colorspace for `--raw` input. Default is yv12.

**Comment by JJKylee** [comment]
I deleted _Pipe_ option as a suggestion from the reply above since it makes `ffmpeg` portable issue complicated when `ffmpeg` is used as an `avs` reader.
Let's just put it away.

**Comment by stax76** [comment]
> I noticed in Beta version 2.18.2 it has been moved and buried in Other

As described by JJKylee it's easy to find using the search feature.


> I suggest nothing is moved until @Dendraspis 's works on Dark Theme are completely finished!

It should not matter as this code does not do anything color or control related.


> First of all, Decoder, Interlace, Input Option.

> And Input Option should be visible only when NVEnc Hardware or NVEnc Software is selected as the Decoder

Good work Dendraspis and JJKylee, it's fixed.

**Comment by JJKylee** [comment]
NVEnc 5.29 has this _ANSI fallback option_ for old systems.

`--process-codepage os`

Since we don't have `avs2pipemod` pipe option in NVEnc, this option is a must.

Is it already there but I can't see, or is it not implemented yet? 🙄❓

**Comment by stax76** [comment]
Old systems don't know the UTF-8 manifest and use the system code page.

This command creates a copy of the EXE with removed UTF-8 manifest, the newly created EXE no longer has a UTF-8 manifest and uses the system code like it was before.

So for staxrip the command isn't relevant.
