### ISSUE TITLE
Hardcoding subtitles does not work

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#536]
If I try to hardcode a subtitle it does nothing. I don't think this is just an issue with StaxRip as much as it is with VsFilterMod.

If I set the code from 'TextSubMod' to 'TextSub' it does work. 

```
AddAutoloadDir("C:\Encoding Tools\StaxRip 2.1.8.1 Beta\Apps\FrameServer\AviSynth\plugins")
LoadPlugin("C:\Encoding Tools\StaxRip 2.1.8.1 Beta\Apps\Plugins\Dual\ffms2\ffms2.dll")
FFVideoSource("examplesource.mkv", cachefile="examplesource_temp\temp.ffindex")
TextSubMod('example.srt')
```

The above code does not display burned in subtitles (This is at 2160p)

If I change TextSubMod to just TextSub, it does work fine however.

**Comment by 44vince44** [comment]
are you using a 10 bit source ?

**Comment by jlw4049** [comment]
Yes it's a 4K BluRay Remux

**Comment by 44vince44** [comment]
TextSubMod does not work in more than 8 bits.
But if you use Vapoursynth you'll have no problem
It's good to see that TextSub works!

**Comment by jlw4049** [comment]
> TextSubMod does not work in more than 8 bits.
> But if you use Vapoursynth you'll have no problem
> It's good to see that TextSub works!

Thanks for the information. Is there any downside to using the command 'TextSub' over the default?

**Comment by jlw4049** [comment]
Apparently TextSub uses the older Xy-VSfilter here http://avisynth.nl/index.php/Xy-VSFilter

As the newer TextSubMod is a more 'up to date' version of the former.

**Comment by 44vince44** [comment]
@jlw4049 EXCELLENT FIND !!! please close this thread so we can ask this as new feature.

**Comment by jlw4049** [comment]
It doesn't make since why an older version of the plugin would support 4K, but the newer up to date version doesn't? lol

Regardless, this isn't a problem with StaixRip. This is an issue with the plugin, maybe force StaxRip to use TextSub by default? 

Anyways, closed!

**Comment by 44vince44** [comment]
Actually, It makes sense because the latest coder of XY-VSFilter (it's pinterf) cares about 10+ filters, so he made many older filters compatible with 10+bit.
Whereas coders of VSFilterMod apparently don't care much about 10+ bit depths (but they will one day because 10+bit sources are more and more frequent)

**Comment by jlw4049** [comment]
I was going to put in issue on the tracker for added support, but I really see no way to contact them? 

https://github.com/sorayuki/VSFilterMod

**Comment by 44vince44** [comment]
This appears to be the VapourSynth version only. It's not the AviSynth.

**Comment by jlw4049** [comment]
> This appears to be the VapourSynth version only. It's not the AviSynth.

It's a dual-interface filter, supports AviSynth and VapourSynth.

**Comment by jlw4049** [comment]
> Yes I've edited my comment while you were typing. But it seems they really keep AviSynth as legacy, and don't care.
> Their page doesn't even mention Avisynth.

Yeah, it looks like a lot of the newer plugins are VapourSynth? Is this what the encoding scene is leading to now?

**Comment by jlw4049** [comment]
I messaged the main dev on twitter, let's see if I get a response haha.

**Comment by 44vince44** [comment]
At some point it looked like the whole scene was turning to VapourSynth, but then, some coders did an excellent work to bring AviSynth+ and many filters to a new standard. This saved AviSynth+ which will live long because it has a much bigger database than VapourSynth. i personally made the choice to stick to AviSynth....

**Comment by jlw4049** [comment]
I program in python myself, but prefer AviSynth to encode with.

**Comment by DJATOM** [comment]
I prefer Vapoursynth over Avisynth. With VS It's possible to access frames directly and manipulate that data with python modules. For example, I had to export image masks for further editing in image editor (mostly for clean-ups, since they caught more than I needed) 
```python3
import numpy, PIL
from PIL import Image

mtimes = [8365, 8377, 8387, 8402, 8421, 8430]
for i in mtimes:
    f = grayclip.get_frame(i)
    y = f.get_read_array(0)
    img = Image.fromarray(numpy.asarray(y, numpy.uint8), mode='L')
    img.save(rf'.\masks\EP{episode}\EP{episode}_{i:05d}.png', 'png')
```
Indeed that's an advanced usage, but I'm not sure if that's even doable with avisynth...

**Comment by jlw4049** [comment]
> I prefer Vapoursynth over Avisynth. With VS It's possible to access frames directly and manipulate that data with python modules. For example, I had to export image masks for further editing in image editor (mostly for clean-ups, since they caught more than I needed)
> 
> ```python
> import numpy, PIL
> from PIL import Image
> 
> mtimes = [8365, 8377, 8387, 8402, 8421, 8430]
> for i in mtimes:
>     f = grayclip.get_frame(i)
>     y = f.get_read_array(0)
>     img = Image.fromarray(numpy.asarray(y, numpy.uint8), mode='L')
>     img.save(rf'.\masks\EP{episode}\EP{episode}_{i:05d}.png', 'png')
> ```
> 
> Indeed that's an advanced usage, but I'm not sure if that's even doable with avisynth...

I might take a look at using this eventually haha
