### ISSUE TITLE
Please replace handling of AviSynth hardcoded subs with XY-VSFilter

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#537]
## Request

Following the great find of @jlw4049, please replace AviSynth filter VSFilterMod with:

XY-VsFilter pfmod (by Pinterf) version 3.2.0.802 31-oct-2018.
http://avisynth.nl/index.php/Xy-VSFilter

## Why we should do that

Although the latest version is dated 31-oct-2018, it is older than VSFilterMod, this filters INCLUDES NATIVE SUPPORT FOR 10 bit and 16bit YUV420 (AVS).
This is MORE than VSFilterMod provides, and will finally put an end to all the bug reports that "harcoded subs don't work (with 10bit sources)".

## Steps to implement that
I suggest:
- add VSFilter.dll in the standard AVS filters of staxrip (folder, app manager). Do **NOT** remove VSFilterMod, it's needed in Vapoursynth because it's dual, and some user could still want to use it in AviSynth. So keep it, in Dual.
- then make Ctrl+H create the filter TextSub(...) instead of TextSubMod(...)

Thanks @jlw4049 for bringing up this to us in this thread https://github.com/staxrip/staxrip/issues/536

**Comment by jlw4049** [comment]
Actually, it looks like you can still use the VSFilterMod and just change the command to TextSub and it will work fine.

**Comment by jlw4049** [comment]
![image](https://user-images.githubusercontent.com/48299282/108744850-6c2cde00-7508-11eb-9661-6c6e565d49cb.png)

**Comment by jlw4049** [comment]
Looks like HolyWu's xy-VSFilter works as well
https://github.com/HomeOfVapourSynthEvolution/xy-VSFilter/releases

**Comment by 44vince44** [comment]
In the documentation it says it does 8 bit and 16bit, but not 10bit.

**Comment by jlw4049** [comment]
I would assume if something supported all the way up to 16 bit, it should hit everything in between? However, I could be completely wrong to think that.

**Comment by 44vince44** [comment]
Not when it reads like that:
clip: Clip to process. Only YUV420P8, YUV420P16, and RGB24 are supported.

P10 and P12 are not included.
The XY-VSFilter says explicitly P10, and has more options for P8 (which can be useful because there are many 8bit sources that use YUY2)

**Comment by jlw4049** [comment]
I did test, it did work. however IDK if that means it fully supports it or not.

**Comment by 44vince44** [comment]
Maybe the doc is not correct 🤣 
I'll test it later, do you think it would be better than pinterf's ?

**Comment by jlw4049** [comment]
Well ironically, if you just leave the default 'VSFilterMod.dll' that StaxRip uses and simply use 'TextSub', it will work without changing the VSFilter.dll at all.

Because VSFilterMod is based off of Xy-VSFilter. So in a way I guess most of them are the same. I'm not sure if it would be better to swap to XY-VSFilter, HolyWu's XY-VSFilter, or stick with the VSFilterMod. All 3 of these work with the command TextSub.

**Comment by jlw4049** [comment]
To further show you. This is the filter that comes packed with staxrip. 

![image](https://user-images.githubusercontent.com/48299282/108775297-e3756880-752e-11eb-843a-01e69721cf8f.png)

This is HolyWu's filter (Font is slightly different)
![image](https://user-images.githubusercontent.com/48299282/108775393-03a52780-752f-11eb-9f6a-7dd531452e52.png)


This is pinterfs (Seems the same as HolyWu's, I think HolyWu has updated his since though)
![image](https://user-images.githubusercontent.com/48299282/108775545-34855c80-752f-11eb-9159-97dc9cebd864.png)

**Comment by 44vince44** [comment]
@jlw4049 the reason why TextSub works on your setup without adding any file, is because you have VSFilter.dll already in one of AviSynth autoload folders (probably in C:\Program Files\Avisynth+\plugin something like that.
On a fresh install of StaxRip with NO Avisynth folders elsewhere, using TextSub throws an error. Until I put VSFilter.dll in Staxrip internal Avisynth autoload folder.

**Comment by jlw4049** [comment]
**I'm an idiot lol**

You are right. In that case I would suggest using HolyWu's, as it's based off of pinterfs but has been updated a few times. I know he is active on the forums and he might potentially update further if requested/needed.

**Comment by 44vince44** [comment]
> I'm an idiot lol

not sure 🤣 

> You are right. In that case I would suggest using HolyWu's,

NOOOOOO. HolyWu is a page for Vapoursynth filters. The fact that their XY-VSFilter works dual with AviSynth is purely incidental.
They took an AviSynth plugin from Cyberbeing, and added Vapoursynth to it. Then they changed the source to the one from Pinterf. Any update they will do will obviously be to the Vapoursynth part, not the the Avisynth part.
So, on the contrary, **we must use PINTERF's version because PINTERF is the most likely to update it as AviSynth**!

And Staxrip will continue use VSFilterMod for Vapoursynth.

**Comment by jlw4049** [comment]
I did not know that. After further reading you are right. Well, I guess that only leaves 1 option then :P

**Comment by 44vince44** [comment]
@stax76 @Dendraspis this is a very easy change...

1) add new AVS filter (dll file and entry in staxrip)
2) Change AVS Ctrl+H behaviour : instead of TextSubMod(  , put TextSub(

so easy.... shouldn't stay more than 24 hours open 🤣

**Comment by JJKylee** [comment]
I confirm that this feature is added in [StaxRip.v2.1.8.2D_DarkMode27.zip](https://github.com/staxrip/staxrip/files/6032319/StaxRip.v2.1.8.2D_DarkMode27.zip) and works OK.

![StaxRip v2 1 8 2D_DarkMode27_TextSub_Code-Preview_20210223](https://user-images.githubusercontent.com/3157518/108924702-fb60f100-75ef-11eb-9c1d-6514bb882925.jpg)

(But I haven't tested a 10 bit source. 😅) 

Of course you need _xy-VSFilter_ in the program tree.

```
Apps\Plugins\AVS\xy-VSFilter\VSFilter.dll
```

Catch: Your _customized_ main menus and _shortcuts_ may be reset, just like me. 😢

**Comment by 44vince44** [comment]
@stax76 Thank you very much! forget to put the proper VSFilter.dll, the one by pinterf!

@JJKylee 🤣 You don't have a 10 bit source ? well type after the video source filter ConvertBits(10)

**Comment by JJKylee** [comment]
Sometimes I'm also surprised how easily I forget obvious things. 😁😅
Thanks for the reminder. 😄

**Comment by jlw4049** [comment]
Nice work!
