### ISSUE TITLE
Test tracking for x265 Patman's Mod  +  ACTION required

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#539]
This thread is to follow up the tests performed on @Patman86 's mod of x265.
Version used: x265-3.5_RC1+16-f19226e34-[Mod-by-Patman]-x64-gcc10.2.0

Please remind me of anything else i need to test.

Tests Performed and Results (I found nothing wrong yet, good work @Patman86 😄 ) :

- direct AVS / VS : pass 🆗 / 🆗 
- seek inside AVS / VS : pass 🆗 / 🆗 
- Unicode support (windows 1903+) AVS / VS : pass 🆗 / 🆗  
- --reader-options library=" ..... " AVS / VS : pass 🆗 / 🆗 but not automatically added to command
-  --dhdr10-info enabled AVS / VS : pass 🆗 / 🆗 

# Requirements from @stax76 or @Dendraspis :

- please make **--reader-options library**  be added automatically to Patman's build, same way it does with DJATOM's. Currently it doesn't, I had to put it manually in custom switches.
- No need to reformat output progress text, it is already correctly formatted !

**Comment by JJKylee** [comment]
So... what about whether there's memory leak for direct `vpy` input?
With my short 2 minute-ish sample, I couldn't see it, but maybe we need a longer sample for the test. 🙄

**Comment by 44vince44** [comment]
Maybe someone with a long video and a Ryzen, like @Patman86 himself can test it 😁 
please don't make me test any more VPY stuff, i hate it 🤣 
But you can have me test whatever avs things you want !

**Comment by Dendraspis** [comment]
> please make --reader-options library be added automatically to Patman's build, same way it does with DJATOM's.

Done  ✔️

**Comment by Patman86** [comment]
> > please make --reader-options library be added automatically to Patman's build, same way it does with DJATOM's.
> 
> Done ✔️
> [StaxRip v2.1.8.2D_x265.zip](https://github.com/staxrip/staxrip/files/6025253/StaxRip.v2.1.8.2D_x265.zip)

Your changes don't work for me... 😢

**Comment by Dendraspis** [comment]
What?  Gimme a second...

**Comment by Dendraspis** [comment]
🤣    @44vince44  requested `--reader-options library` , I've read `--progress-readframes`

Now `--reader-options library` is also enabled.  😁 

[StaxRip v2.1.8.2D_x2652.zip](https://github.com/staxrip/staxrip/files/6025592/StaxRip.v2.1.8.2D_x2652.zip)

**Comment by Patman86** [comment]
> 🤣 @44vince44 requested `--reader-options library` , I've read `--progress-readframes`
> 
> Now `--reader-options library` is also enabled. 😁
> 
> [StaxRip v2.1.8.2D_x2652.zip](https://github.com/staxrip/staxrip/files/6025592/StaxRip.v2.1.8.2D_x2652.zip)

copy & paste 🤔

**Comment by Dendraspis** [comment]
🤣   And I thought you were joking with *copy&paste*   🤣 

Of course it won't work when you check for DJATOM and for DJATOM.  So you were 100% right!  👍 

[StaxRip v2.1.8.2D_x2653.zip](https://github.com/staxrip/staxrip/files/6025698/StaxRip.v2.1.8.2D_x2653.zip)  *(tested!)*

**Comment by 44vince44** [comment]
--progress-readframes must be disabled for Patman's build !!!!!

**Comment by Dendraspis** [comment]
His CLI help tells another story.  😝 

But you're right, so it's reverted now. 👍

**Comment by Patman86** [comment]
FIXED 😁😁

**Comment by Dendraspis** [comment]
So after we have proven that this build is based on DJATOMs latest build, there is no need to check the memory seek issue and this issue can be closed, right?  🤓

**Comment by JJKylee** [comment]
I'm encoding a 2 hour-ish movie using @Patman86's new `x265` build (3.5_RC1+16 _MSVC1928_) via direct `vpy` input.
No memory leak issue is being watched up to now when 10% is processed. 👍

![StaxRip v2 1 8 2D_DarkMode17_Patman-Mod-x265_vpy_memory-usage_20210222](https://user-images.githubusercontent.com/3157518/108804931-8fc94600-7553-11eb-9b93-6919702f605a.jpg)

I think we can safely close this issue. 😄

**Comment by JJKylee** [comment]
But somehow while switching b/w windows, I see this weird _**negative processed time**_ in the progress text.

![StaxRip v2 1 8 2D_DarkMode17_Patman-Mod-x265_negative-processed-time_20210222](https://user-images.githubusercontent.com/3157518/108805394-cd7a9e80-7554-11eb-8314-252976a950e2.jpg)

I think @Patman86 should look into his code to fix this.

**Comment by 44vince44** [comment]
@JJKylee I tested both gcc and msvc builds, and the processed time shows OK.
😕

**Comment by JJKylee** [comment]
I'm gonna put the newest Dark-Mode build by @Dendraspis, [StaxRip v2.1.8.2D_DarkMode18.zip](https://github.com/staxrip/staxrip/files/6025310/StaxRip.v2.1.8.2D_DarkMode18.zip), reboot my Windows, and see if anything changes.

**Comment by 44vince44** [comment]
Well, for testing this, you should use the https://github.com/staxrip/staxrip/files/6025698/StaxRip.v2.1.8.2D_x2653.zip
because this one has the modification in command line to use the path to the frameserver.
(maybe you should follow up a bit what was said above 😁  😁 😁

**Comment by 44vince44** [comment]
And please remove manually --progress-readframe option (it's been removed in the commits, but not in the exes)

**Comment by JJKylee** [comment]
Oh, it's OK with me cuz I use _installed_ frameservers only. 😁

But I believe _StaxRip v2.1.8.2D_DarkMode18.zip_ already includes all the new commits, doesn't it? 🙄❓

If not, I'll try this weirdly named [StaxRip v2.1.8.2D_x2653.zip](https://github.com/staxrip/staxrip/files/6025698/StaxRip.v2.1.8.2D_x2653.zip). 😆

Well, anyway, it's really hard to let go of the dark themes. 😅

**Comment by Dendraspis** [comment]
Themes or customized progress text have nothing to do with this, because both don't alter this output.
So it must be caused inside x265. 🤔

**Comment by 44vince44** [comment]
@Dendraspis I'm only telling JJKylee to use the version with commits relating to x265 when testing x265. And not to use the version without the x265 commits. That's the correct way to debug.
It was a general idea, not specific to the text output (that, BTW, I could not reproduce, with either version)

**Comment by 44vince44** [comment]
And also I still need to check the latest commit to be sure that  --progress-readframe  works correctly 😁

**Comment by JJKylee** [comment]
I guess `0:35:47` is the turning point for @Patman86's `x265` build (3.5_RC1+16 **MSVC 1928**).
When it reaches `0:35:47`, it becomes `0:-35:-47` and moves towards `0:00:00` and then keeps increasing until it hits `0:35:47` again. And the same pattern repeats. I've seen it three times now. 😅 

But I'm not sure where this phenomenon comes from. Maybe it's my own problem like @44vince44 said.
I'm gonna replace the `exe` and reboot. But I don't think I'll repeat this test cuz it takes too loooooong. 😓 
But if I happen to run into the same issue though, I'll report it.

**Comment by DJATOM** [comment]
Set to easy preset and you will reproduce it faster.

**Comment by JJKylee** [comment]
But it doesn't change that I need to wait at least for about 36 minutes or so. Does it? 😝

**Comment by 44vince44** [comment]
Good find @JJKylee all my tests were short tests 10 minutes max. Now @Patman86 it seems there is a real bug here

**Comment by Dendraspis** [comment]
> And also I still need to check the latest commit to be sure that --progress-readframe works correctly 😁 But I don't have an exe with that commit 😕

Take v19 - It's fresh and still warm.  😁

**Comment by JJKylee** [comment]
On second thought, is there any possibility that this is an issue with `x265` 3.5_RC1 itself?

Although I said that `0:35:47` was the turning point, it looks like that the time itself was somewhat random around 35 minutes or so, to be precise. Considering that @Patman86 does not have any reason to design this intentionally, it may be an upstream issue, I guess. 🙄

**Comment by 44vince44** [comment]
@JJKylee , @Patman86 I confirm that 0:35:47 is the exact turning point !

![mpv-shot0001](https://user-images.githubusercontent.com/17828567/108822666-115abb80-75c8-11eb-9dda-60eafe40fd45.jpg)

![mpv-shot0002](https://user-images.githubusercontent.com/17828567/108822675-13bd1580-75c8-11eb-9b47-96444a4edaab.jpg)

There is a problem here, it could be as you say a problem with the RC1

**Comment by Patman86** [comment]
I think I found the reason, i upload a new build in the afternoon.

**Comment by 44vince44** [comment]
Ok @Patman86 , so I'm planning encodes of 36+minutes for this evening 😁

**Comment by Dendraspis** [comment]
@44vince44  Take your 2min test file and use *Placebo* preset.  😉

**Comment by 44vince44** [comment]
🤣  you mean my 2min UltraHD and use all the denoisers possible and upscale it to 8K, then put artificial noise to make it look like a GENUINE 8K film, and the placebo 😁

**Comment by Dendraspis** [comment]
Could could also use a *normal* preset and limit it to just one core.  😉   Advantage:  You can use your PC for other things and you save energy/heat/money.  😎

**Comment by Patman86** [comment]
DONE!!!

**Comment by JJKylee** [comment]
At this point, I can't help but ask this question out of curiosity.
So, @Patman86, what was so special about `0:35:47`? 😁😅

**Comment by Patman86** [comment]
I forgot the brackets 🙄

`(elapsed / 1000000);`

**Comment by 44vince44** [comment]
Well, important thing it works now (did a 1 hour encoding session, the bug is indeed fixed !
Congrats and thanks @Patman86 for this new x265 fully refreshed!

So next Staxrip release will have @Patman86 's x265 v3.5, right ?

**Comment by 44vince44** [comment]
@Patman86 did you change the way the FPS in the progress output is calculated ?

**Comment by Patman86** [comment]
No, it's the calculation I've always used.

**Comment by 44vince44** [comment]
@Patman86 Well wasn't it instant ??

**Comment by 44vince44** [comment]
Maybe I've entered in my age of senility... 😞

**Comment by Dendraspis** [comment]
Right, "maybe"   😆

**Comment by 44vince44** [comment]
OK I remember:
bitrate was instant
fps was average...
And it's still the same.

In DJAtom's build fps and bitrate are both average

and I'd like both instant 🤣

**Comment by Dendraspis** [comment]
Bitrate in kb/s is (and was) average, too  🤔

**Comment by 44vince44** [comment]
not in Patman's ....?

**Comment by Dendraspis** [comment]
Of course average.  🤔

**Comment by 44vince44** [comment]
Well then, definitely senile 🤣

**Comment by Patman86** [comment]
😂😂 DJATOM and I use the same code for fps and bitrate and now comes the surprise ... the original source code of x265 too 😂😂

**Comment by DJATOM** [comment]
Instant fps will be like jumping 0..50 per few ticks, I had that in avs2yuv for some time. Not really meaningful. 
As for bitrate thing, to measure instant bitrate we can a) update it 1 time per one second of encoded output b) track last "1 sec of output" and recalculate entire array (should be easy with c++, I think) c) display bitrate per frame, should be the same complexity as of global average bitrate.

**Comment by 44vince44** [comment]
what I mean by instant, is calculate the average on a range instead of from beginning. The range is sliding.
Like a buffer.

**Comment by DJATOM** [comment]
Then it's better to implement extra option to tune bitrate calculation window, so people can adjust what they want: 0.5 secs, 1 second, 10 seconds or default: average from beginning.

**Comment by 44vince44** [comment]
that we be a great idea... was afraid it's too much to ask ...

**Comment by DJATOM** [comment]
I should start a todo list of things I will have to implement after finishing my work project 😅
