### ISSUE TITLE
New Feature: Notification for a new stable release.

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#54]
It would be great to be notified inside the software if a new stable update has been released. The notification will include a link to the download page.

**Comment by stax76** [comment]
Sounds good, thanks for the feedback.

**Comment by Patman86** [comment]
I saw your commit that you linked website. I think, it is better to use these url:

https://github.com/staxrip/staxrip/releases

For future updates/releases, use only github and tag the beta releases as pre-releases.

**Comment by stax76** [comment]
Hello Patman,

the main page is the most important page, the releases page is only one click away.

The reason I use dropbox and onedrive is it can be automated very easily, I don't have time to do such things manually and I don't know if github releases can be automated.

https://github.com/staxrip/staxrip/blob/master/General/GlobalCommands.vb#L689

What's wrong with dropbox and onedrive? The links are in the forum announcements and on the main github page there is a download section with links to the docs section that has the links.

https://github.com/staxrip/staxrip#download

**Comment by Patman86** [comment]
Nothing is wrong with dropbox and onedrive, love these cloud storages! Was just an idea. It can like to stay the same :)

**Comment by stax76** [comment]
Feature is available in the next build.

https://github.com/staxrip/staxrip/commit/77a464bf467cf1f5124156c7b958307a1e3e0179

**Comment by Patman86** [comment]
Great!!! THX

**Comment by stax76** [comment]
new build:

https://forum.doom9.org/showthread.php?p=1885113#post1885113
