### ISSUE TITLE
APPS > MEDIAINFO FOLDER feature throws an error if characters [ ] are in one file's name

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#541]
**Describe the bug**

if running **Mediainfo Folder** feature on a folder where there is a file with "[ "character or "]" character or Turkish characters (probably the Turkish i) then Mediainfo Folder throws an error and stops reading files afterwards (but the windows doesn't crash)

However, if there are no such characters, but other Arabic, french special characters etc, there is NO PROBLEM.

Also Mediainfo FILE reads the same file with the problematic characters correctly.

Maybe similar to a recent issue found with Turkish i.

**Comment by stax76** [comment]
I usually start MediaInfo.NET from a media file in File Explorer and then start the folder view from MediaInfo.NET.

It's reproducible, yes.

**Comment by 44vince44** [comment]
Fixed indeed, thank you ! 👍🏼
