### ISSUE TITLE
"Delete temp files" setting won't delete temp files

### ISSUE THREAD

**Issue by Zcehtro** [staxrip/staxrip#542]
**Describe the bug**
The setting in Settings -> System -> Delete temp files, won't delete temp files to recycle bin or permanently if set to do so.
Setting operates as if "Disabled" was chosen.

**Expected behavior**
Encoding files should be treated as set in the setting.

**How to reproduce the issue**

Set any encode and set to "Permanent" or "Recycle Bin" and files will stay in temp folder.

**Provide information**

Got no way of proving it except submitting a log probably:
[[SubsPlease] Jujutsu Kaisen - 08 (1080p) [7CEEF59C] _rcd-x265opus_staxrip.log](https://github.com/staxrip/staxrip/files/6039738/SubsPlease.Jujutsu.Kaisen.-.08.1080p.7CEEF59C._rcd-x265opus_staxrip.log)

**Notes before posting**
Ok.

**Additional context**
Not off the top of my head.

**Please be as clear and as detailed as possible**
Done. Will answer any follow ups aqap.

**Comment by JJKylee** [comment]
1. _Settings_ apply **program-wise**. So once you change any options in _Settings_, close StaxRip and relaunch. The new settings will apply from then on.

2. I tried _Recycle Bin_ and restarted StaxRip. I see the _temp_ folder and all the temporary files in it are moved to the Recycle Bin and _Source_/_Target_ fields become empty _right after the encode succeeds_. If the encode fails, or if you close the project without doing a successful encode, the temp folder/files remain even after you close StaxRip.

**Comment by 44vince44** [comment]
I confirm that @JJKylee, I've been doing several encodes with delete temp files to Recycle Bin, and it is working properly.

**Comment by 44vince44** [comment]
I believe this is a possible solution:


![SNAG-0001](https://user-images.githubusercontent.com/17828567/109093556-3ca4ee00-7721-11eb-9b4c-1ab95b3c32ab.jpg)


AND don't forget this one as well:

![SNAG-0000](https://user-images.githubusercontent.com/17828567/109093595-4a5a7380-7721-11eb-8c3e-d30531c77874.jpg)

**Comment by Zcehtro** [comment]
I made a simple screen record of what happens on my computer. Log included.

[[SubsPlease] Jujutsu Kaisen - 01 (1080p) [4518EF4F] _rcd-x265opus_staxrip.log](https://github.com/staxrip/staxrip/files/6040191/SubsPlease.Jujutsu.Kaisen.-.01.1080p.4518EF4F._rcd-x265opus_staxrip.log)

https://user-images.githubusercontent.com/10564090/109094889-b79de280-76e8-11eb-9f64-75ab0538781a.mp4

**Comment by Zcehtro** [comment]
> 1. _Settings_ apply **program-wise**. So once you change any options in _Settings_, close StaxRip and relaunch. The new settings will apply from then on.
> 2. I tried _Recycle Bin_ and restarted StaxRip. I see the _temp_ folder and all the temporary files in it are moved to the Recycle Bin and _Source_/_Target_ fields become empty _right after the encode succeeds_. If the encode fails, or if you close the project without doing a successful encode, the temp folder/files remain even after you close StaxRip.

Ok, I just did this.
I started Staxrip, opened the template, set the option to recycle bin, exit.
Openend Staxrip again, set the option to permanent, exit again.
Opened Staxrip again, opened the template, cleared the temp files folder, added the same test video files again, ran the encode, finished...

...And temp files are still there.

😅

**Comment by 44vince44** [comment]
#THIS IS NO BUG

**The temp folder must finish with _temp.**

This is a KNOWN behaviour of StaxRip since ever, It is to ensure that no problem happens, Since deleting can be PERMANENT, this is a fail-safe precaution.

![SNAG-0002](https://user-images.githubusercontent.com/17828567/109096632-94922380-7726-11eb-8c5b-f8c997dfaed7.jpg)

**Comment by 44vince44** [comment]
@stax76 @Dendraspis please consider this solution

https://github.com/staxrip/staxrip/issues/542#issuecomment-785540860

**Comment by Zcehtro** [comment]
> # THIS IS NO BUG
> **The temp folder must finish with _temp.**
> 
> This is a KNOWN behaviour of StaxRip since ever, It is to ensure that no problem happens, Since deleting can be PERMANENT, this is a fail-safe precaution.
> 
> ![SNAG-0002](https://user-images.githubusercontent.com/17828567/109096632-94922380-7726-11eb-8c5b-f8c997dfaed7.jpg)
> 
> @Zcehtro, the _temp suffix is automatically added. Why tampering too much ?

Hot damn! That was it!!

You know, if somebody is tweaking lot's of things this little bit of info would be nice to have right there when tampering with the paths...

😁

**Comment by 44vince44** [comment]
@stax76 or @Dendraspis 

Please SIMPLY write under the `Project Options > Paths > Temp Files Folder` field:
"this path must end with _temp\ for correct operation of Staxrip"

Or something like that....

**Comment by stax76** [comment]
One setting is in the options dialog and the other is in the settings dialog, therefore I suggest showing a message box after closing the options and settings dialog.

**Comment by 44vince44** [comment]
@stax76 I thought message box would be more complicated to code... but it would cover more cases....

**Comment by Dendraspis** [comment]
I added just an extended description to "Temp Files Folder:" if Auto-Deletion is enabled. 

A warning message is prepared, but not activated. In case an experienced user does it on purpose, a warning message every time the options are changed, might be very annoying.
