### ISSUE TITLE
x265 wrong defaults + custom commands ordering

### ISSUE THREAD

**Issue by tkozybski** [staxrip/staxrip#546]
--selective-sao default is 0, not 4. 

--sar on auto correctly doesn't leaves the value unspecified, but setting 1:1 manually should do it, but it works the same as auto right now.

In Custom command textboxes, the "Custom" textbox will correctly apply the text to the end of the command, but on "Custom First Pass" etc. will apply them to the beginning, making them less useful as they won't overwrite the settings.

**Comment by stax76** [comment]
Hotfix is online.

**Comment by stax76** [comment]
**Please careful everybody with my last commit and hotfix:**

When a video encoder default value was changed, a compatibility issue with old settings was happening, this is finally fixed, **but could only be achieved by resetting all video encoder options**.

**Comment by stax76** [comment]
The fix doesn't seem to work correctly. 🙁

**Comment by stax76** [comment]
Second try is online. 🤞

**Comment by JJKylee** [comment]
The hotfix `StaxRip.exe` that reflects this commit resets my custom video encoder profiles and those in my custom templates.
See [this post](https://forum.doom9.org/showthread.php?p=1936812#post1936812) on Doom9.

So I guess a **_strong warning_** should be attached with this fix, not only with the hotfix, but with the new beta as well. 😅

**Comment by JJKylee** [comment]
This hotfix has a minor problem: the codec for **ffmpeg** _Intel_ and _Nvidia_ profiles is all set to `x264`, and cannot be changed in the _Profiles Editor_.
See this:

![StaxRip_2 1 8 4_hotfix2_ffmpeg_Intel_Nvidia_video-encoder-profiles_issue_20210226](https://user-images.githubusercontent.com/3157518/109362760-889a8480-7840-11eb-83d2-818c66bd8709.gif)

**Comment by stax76** [comment]
I was worried because the code everything is based on is very complex, and it might be a substantial problem, but it looks like this can be fixed easily, I found the problem. 🙂

**Comment by JJKylee** [comment]
Weren't you taking a rest? Maybe I woke you up. Sorry about that. 😅
No hurries. Just take your time. 😄

**Comment by stax76** [comment]
Hotfix is only.

Yes I will rest 1-2 weeks, this night was already better than the day before.

**Comment by JJKylee** [comment]
I confirm that the hotfix resolves the issue. 😃

I took this opportunity to check out all the video encoder profiles and found another minor issue.
But for @stax76's health, let me talk about this when he returns after a break. 😆😅

**Comment by 44vince44** [comment]
Well you should write it anyway, since @Dendraspis may feel like addressing it (as a change to his theme works) 😁

**Comment by JJKylee** [comment]
As a matter of fact, it's a very simple one: SVT-AV1 _Options Window_ does not have a command line pane.

![StaxRip_2 1 8 4_hotfix3_SVT-AV1_Options-Window_missing_command-line-options_20210226](https://user-images.githubusercontent.com/3157518/109375958-e72e2580-7875-11eb-8904-03a7da610e0d.jpg)

I'm wondering how many people are actively using SVT-AV1 on StaxRip, though. 😆

But if you feel like tackling this thing, you can go ahead, @Dendraspis. 😝😅

**Comment by Dendraspis** [comment]
@JJKylee 
This is no issue ... just change any value, so that the command line has something to show.  😉

**Comment by JJKylee** [comment]
![StaxRip v2 1 8 4D_OutputHighlighting9_SVT-AV1_Options-Window_20210301](https://user-images.githubusercontent.com/3157518/109550368-0a2e2480-7a84-11eb-9d84-b7cdf2e3b73a.jpg)

You're right.

I didn't even think about changing options. Hahaha... 😅😂😆🤣
