### ISSUE TITLE
x265 compressibility test - adjust frames amount variable

### ISSUE THREAD

**Issue by tkozybski** [staxrip/staxrip#547]
Currently the test will encode 14 frames every N seconds, based on the settings. But 14 frames is way too low to do any meaningful test, especially with high rc-lookahead and/or bframes. 

Would it be possible to make a variable for frames amount (with default of current 14) in addition to the percentage? For example SelectRangeEvery(3750, 210) would yield more accurate results compared to SelectRangeEvery(250, 14).

**Comment by Dendraspis** [comment]
I extended the range and made the block size configurable in ***seconds***.

Here is the current version:
[StaxRip v2.1.8.5D_CC.zip](https://github.com/staxrip/staxrip/files/6114582/StaxRip.v2.1.8.5D_CC.zip)
