### ISSUE TITLE
FFmpeg coding audio very slower

### ISSUE THREAD

**Issue by Creepercdn** [staxrip/staxrip#548]
**Describe the bug**
When using FFmpeg to coding audio stream, it was very slow.

**How to reproduce the issue**

3. Using 'FFmpeg' audio encoder.
4. 'AviSynth or VapourSynth' being used.
6. If it's tied to a hardware encoder then post your hardware specs.

**Provide information**

I cut some useful logs:
```
-------------------------- Audio Encoding 1 --------------------------

ffmpeg N-100448-gab6a56773f-x64-gcc10.2.0 Patman

ffmpeg.exe -i "xxx.mp4" -c:a aac -q:a 2 -af volume=4.3dB -ac 1 -ar 22050 -y -hide_banner "xxx.m4a"

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'xxx.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
    description     : Packed by Bilibili XCoder v2.0.2
  Duration: 00:03:32.32, start: 0.000000, bitrate: 4517 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 4440 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
```

Look at:
```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
```
This step only coding audio, but it coding audio and video.
Add custom argument `-vn` can fix this issue, but I think it should include in default argument.
However, file is correct.

Full log is in here: https://pastebin.ubuntu.com/p/wF5Kv5hjJN/

**Notes before posting**
- Please also try the latest version of StaxRip that can be found here: https://staxrip.readthedocs.io/introduction.html#download
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. 
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is espeically true on the VapourSynth side, which will crash if your CPU don't support it.
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet.

**Additional context**
Add any other information or additional context that can be helpful.

**Please be as clear and as detailed as possible**

**Comment by JJKylee** [comment]
Good find! I confirm this.

Never did it occur to me that an `m4a` file can contain a video stream as well. 😓
The encoded `m4a` file is actually a video file that has both video and audio streams.

So when the input has both video and audio, we need to _select only the exact audio stream_ for FFmpeg/AAC or FFmpeg/FDK-AAC encoding by employing the `-map` parameter, I guess.

**Comment by JJKylee** [comment]
Side note:

Well, on second thought, I did witness the same issue when I encoded an `avs` source served by FFMS2 via FFmpeg/FDK-AAC.
But I've been forgetting about it completely. Hahaha... 😅😅😅😅😅

**Comment by stax76** [comment]
I uploaded a hotfix that always sets map if the audio source file is a video file.

Before it was only setting map if there were more than one audio streams in the file.

I can add -vn in case of avs/vpy input, but isn't -vn deprecated?

**Comment by JJKylee** [comment]
> I can add -vn in case of avs/vpy input, but isn't -vn deprecated?

No. `-vn`, `-an`, `-sn` are valid options.

**Comment by stax76** [comment]
OK, thanks.

avs/vpy issue is fixed by using -vn before -i

Hotfix is online, but I didn't test it.

I need to take a break a couple of days because of difficulties with sleep, see you guys then. 👋

**Comment by JJKylee** [comment]
I’ll put it to test.
Take a good rest. 😃

**Comment by 44vince44** [comment]
@stax76 get some rest and some sleep! You really deserve it !

**Comment by 44vince44** [comment]
@JJKylee I remember that you already spotted the missing -vn some time ago :))

**Comment by JJKylee** [comment]
Yeah.

Just FYI, @44vince44, the hotfix `StaxRip.exe` resets all custom video encoder settings. See [my post](https://forum.doom9.org/showthread.php?p=1936812#post1936812) on Doom9.

I believe you already have a backup of your custom settings, so this is for 'just in case'. 😄

**Comment by JJKylee** [comment]
I confirm that this fix works correctly.

![StaxRip_2 1 8 4_hotfix2_stream-mapping_for_ffmpeg-aac_20210226](https://user-images.githubusercontent.com/3157518/109371511-23ec2380-785a-11eb-87ff-0964e88099ce.jpg)

(And `-vn` is applied for an `avs` input, as expected.)

**Comment by 44vince44** [comment]
@JJKylee why does my window show different options?

![SNAG-0001](https://user-images.githubusercontent.com/17828567/109377974-a961e900-78d7-11eb-856d-e8dc1b6a2b09.jpg)

**Comment by Dendraspis** [comment]
@44vince44 
Seems you used an older one.  🤔

**Comment by 44vince44** [comment]
No I downloaded hotfix file from stax76 beta repo

**Comment by 44vince44** [comment]
@JJKylee and @Dendraspis I really have a different thing without -map.

In what condition is -map supposed to appear now?

**Comment by JJKylee** [comment]
Is your input for audio encoding a video file?

**Comment by 44vince44** [comment]
OMG!! only now I've  understood what this is about 😬 Sorry for the inconvenience !!!
Of course, now it makes sense.
Disregard all my comments please 🙏🏼

**Comment by Dendraspis** [comment]
So we can close it?

**Comment by JJKylee** [comment]
Yes.

**Comment by Dendraspis** [comment]
That was really fast.  🤗
