### ISSUE TITLE
format exception and character limitation

### ISSUE THREAD

**Issue by just333** [staxrip/staxrip#55]
Hello,
since the titlename of each track is transmitted to the outputfile, there is an issue with cutting videos. 
When the audiotrack has a title set, the audiofile will not be processed and after the videoencode is finished you get this error:

FormatException (2.0.4.0)

Die Eingabezeichenfolge hat das falsche Format.

System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Text.StringBuilder.FormatError()
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.Format(String format, Object arg0, Object arg1)
   bei StaxRip.Audio.CutMkvmerge(AudioProfile ap) in D:\Projekte\VB\staxrip\General\Audio.vb:Zeile 467.
   bei StaxRip.Audio.Cut(AudioProfile ap) in D:\Projekte\VB\staxrip\General\Audio.vb:Zeile 188.
   bei StaxRip.Audio.Process(AudioProfile ap) in D:\Projekte\VB\staxrip\General\Audio.vb:Zeile 46.
   bei StaxRip.GlobalClass._Closure$__._Lambda$__31-1() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 114.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 138.
   bei StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:Zeile 37.

another issue i noticed is the symbol "/" is not transmitted correctly to the outputfile. It will be replaced with "_"
example: 
input "Deutsch (AC3 @384 kb/s)"
output "Deutsch (AC3 @384 kb_s)"

**Comment by stax76** [comment]
Hi,

I think it's fixed in 2.0.4.3 Beta

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by stax76** [comment]
next build has:

- fix: if subtitle and audio titles contained illegal
  file system characters then these characters were replaced
  with an underscore and thus being lost, now the characters
  are escaped/unescaped and thus preserved

**Comment by stax76** [comment]
new build:

https://forum.doom9.org/showthread.php?p=1885113#post1885113
