### ISSUE TITLE
Bug when typing values of resize (instead of moving slider) - newly introduced. used to work ok!

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#558]
**Describe the bug**
When typing a value of new height or new width in the resize boxes, instead of moving the slider, the display of the size under the Target field is not refreshed. 
- Opening the Info window and closing it will make the refresh happen (after closing it).
- Using the slider does not cause any problem.
- In order to reproduce this, you must disable option  Image > Aspect Ratio> "adjust height according to target display aspect ratio"

![SNAG-0005](https://user-images.githubusercontent.com/17828567/109708772-815ada00-7ba4-11eb-9f4e-4e9175cab4ca.jpg)

Sorry for the sloppy screenshots with corrections 🤣

**Comment by 44vince44** [comment]
To be more precise, the bug happens when typing in the HEIGHT box!

**Comment by Dendraspis** [comment]
Let's see if this fixes it for you - my tests were positive:
[StaxRip v2.1.8.4D_Size.zip](https://github.com/staxrip/staxrip/files/6082926/StaxRip.v2.1.8.4D_Size.zip)

**Comment by 44vince44** [comment]
Thanks! the problem is gone ! i'll close it :-)
😃
