### ISSUE TITLE
Increase number of frames used for auto crop limit

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#559]
Hi,

I want to ask to increase number of frames used for auto crop limit to like 40 or more, so it can be more precise. 
Also, if possible, make it more sensitive, some times the content has images wider or taller for a limited time(like IMAX) but the auto crop ignores them.

Thank you

**Comment by Dendraspis** [comment]
Please take a look at `Tools » Settings » Video » Number of frames used for auto crop`.  😉

**Comment by LazyNCoder** [comment]
> 
> 
> Please take a look at `Tools » Settings » Video » Number of frames used for auto crop`. 😉

I know. but the max is 20 frames. I wish it could be more like 40 or something.

**Comment by Dendraspis** [comment]
> Also, if possible, make it more sensitive, some times the content has images wider or taller for a limited time(like IMAX) but the auto crop ignores them.

That would mean scanning about 2% of all frames, so about 3500 frames, would take a very very long time to be that accurate.





> I know. but the max is 20 frames. I wish it could be more like 40 or something.

Ah, didn't even noticed, that the value changes back after pressing OK.  😁 

I've pushed the upper limit to **200**, which should be more than enough for most situations. If you doubt about the correctness you should use the slider to check the source with your eyes - that's what I do.  😁 

Here is the latest version:
https://github.com/staxrip/staxrip/files/6075042/StaxRip.v2.1.8.4D_OutputHighlighting13.zip

**Comment by LazyNCoder** [comment]
You're the best.
