### ISSUE TITLE
Adding Transparency, Brightness and Contrast to a 2K Sup so it gets updated to 4K HDR

### ISSUE THREAD

**Issue by pwacooijmans** [staxrip/staxrip#56]
Dear Stax76 and Revan654,

Is it possible to ask Rigaya from NVEncC64.exe how he did the transparency, brightness and contrast and make it possible to convert 2k.sup to 4k HDR.sup with these settings?....they work perfectly and he made it in less than 2 days. I just want to be able to make 2k sups into 4k HDR sups that's all.

Pretty please.

Many Thanks in advance,

Pieter Cooijmans

**Comment by stax76** [comment]
If I understand correctly then you convert:

pgs -> srt -> pgs

You do so with a new app called 'Blu-ray SUP', where can it be downloaded?

**Comment by pwacooijmans** [comment]
The point is I want to skip the srt part

Op di 17 sep. 2019 06:29 schreef stax76 <notifications@github.com>:

**Comment by stax76** [comment]
It's too difficult to build such tools.

**Comment by pwacooijmans** [comment]
Like bdsup2sub kan downgrade a 4k hdr sup to a 2k sup instantly however it
can't do it vica versa.

Op di 17 sep. 2019 08:40 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
That's a pity

Op di 17 sep. 2019 08:43 schreef stax76 <notifications@github.com>:

**Comment by pwacooijmans** [comment]
updated the question so it's what it should be.

**Comment by pwacooijmans** [comment]
![Transparency 0 15, Brightness -0 25, Contrast 0,67 Subtitle at 90% resize](https://user-images.githubusercontent.com/30800180/65182759-4de4c800-da62-11e9-90c6-73b83114e7b4.png)
--vpp-subburn filename="D:\Push the Tempo\La La Land (2016) Untouched sample_temp\La La Land (2016) Untouched sample ID4 Dutch.sup",shaping="complex",scale=2.0,transparency=0.15,brightness=-0.25,contrast=0.67
and a 90% resize with bdsup2sub++ to begin with

**Comment by pwacooijmans** [comment]
My favorite so far, any better ideas anyone?

**Comment by pwacooijmans** [comment]
https://drive.google.com/drive/folders/1gN7u1F1lp-ldLHQjXXTpDcMOlwoigQZU?usp=sharing
here a link with 2 samples....1 untouched and one with the burned in subtitle.

**Comment by pwacooijmans** [comment]
[BDSup2Sub512.zip](https://github.com/staxrip/staxrip/files/3628228/BDSup2Sub512.zip)
Java file so you need java to run it.

**Comment by pwacooijmans** [comment]
[Templates used.zip](https://github.com/staxrip/staxrip/files/3628346/Templates.used.zip)

**Comment by pwacooijmans** [comment]
[Versions.txt](https://github.com/staxrip/staxrip/files/3630229/Versions.txt)

**Comment by Patman86** [comment]
Here is BDSup2Sub512_x64.exe to download. You don't need Java.

http://www.mediafire.com/file/dyfhzlnnq72xqwo/BDSup2Sub512_x64.7z/file

**Comment by pwacooijmans** [comment]
however your version probably doesn't go till 16k sups resize

**Comment by pwacooijmans** [comment]
btw if you upscale a sup till 8k with bdsup2sub it's very easy to get the sup to srt since the programs make way less errors
