### ISSUE TITLE
StaxRip can no longer open a file after indexing on a NAS/remote location.

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#563]
StaxRip can no longer open a file after indexing on a NAS/remote location.

```
Script Error
Import: couldn't open "\\Jlwserver\e\Downloads\Blade.Runner.1982.The.Final.Cut.BluRay.1080p.TrueHD.5.1.VC-1.REMUX-FraMeSToR\Blade.Runner.1982.The.Final.Cut.BluRay.1080p.TrueHD.5.1.VC-1.REMUX-FraMeSToR_temp\Blade.Runner.1982.The.Final.Cut.BluRay.1080p.TrueHD.5.1.VC-1.REMUX-FraMeSToR_new_source.avs"
```

As far as I know the older versions of StaxRip had no issue doing this.

When I check the location of the avsfile, it is pretty out of wack

`\\?\UNC\Jlwserver\e\Downloads\Blade.Runner.1982.The.Final.Cut.BluRay.1080p.TrueHD.5.1.VC-1.REMUX-FraMeSToR\Blade.Runner.1982.The.Final.Cut.BluRay.1080p.TrueHD.5.1.VC-1.REMUX-FraMeSToR_temp`

**Comment by jlw4049** [comment]
Dropping the filename down to a much smaller size "Blade.Runner.1982.The.Final.Cut.BluRay.1080p" fixes the issue. So I'm assuming this is something to do with the long-path work.

**Comment by 44vince44** [comment]
@jlw4049 What's your windows version ?
you're using a recent version of staxrip ?

**Comment by jlw4049** [comment]
Mapping the drive on my 2nd computer, then dragging and dropping the file that way with the long file name fixed the issue. Actually manually navigating to my home servers drive like "\\Jlwserver\f" caused the error. Once I mapped the network drive to F: the error went away.

I also just now enabled long path. I'm going to close this as it was most likely my fault.

**Comment by stax76** [comment]
It's not reproducible with the desktop folder:

`\\localhost\c$\Users\JonDoe\Desktop`
