### ISSUE TITLE
AutoAdjust filter does not work properly after version 2.1.4.2

### ISSUE THREAD

**Issue by OnbekendHH** [staxrip/staxrip#564]
After Version 2.1.4.2, AutoAdjust (unfortunately) produces bright areas that are black instead. My AVS Code has not changed from one version to the next. Currently, I am using 2.1.8.0. No error message is produced. Encoding completes without error. 

**Expected behavior**
AutoAdjust produces smooth video output without artifacts. 

Here is the code:

```Python
LoadPlugin("C:\Other Apps\StaxRip\StaxRip-x64-2.1.8.0-Stable\Apps\Plugins\AVS\AutoAdjust\AutoAdjust.dll")
LoadPlugin("C:\Other Apps\StaxRip\StaxRip-x64-2.1.8.0-Stable\Apps\Plugins\AVS\FFT3DFilter\fft3dfilter.dll")
LoadPlugin("C:\Other Apps\StaxRip\StaxRip-x64-2.1.8.0-Stable\Apps\Plugins\Dual\KNLMeansCL\KNLMeansCL.dll")
LoadPlugin("C:\Other Apps\DGDecNV\DGDecNV_2053.0.0.223\DGDecodeNV.dll")
DGSource("D:\StaxRip_Temp\The Thing from Another World (1951)\The Thing from Another World (1951).dgi", i420=true)
ConvertBits(16)
Crop(240, 0, -240, -0)
Tweak(bright=-12, dither=true)
ConvertToStacked()
AutoAdjust(gamma_limit=1.0, gain_mode=1, auto_gain=true, auto_balance=false, scd_threshold=12, temporal_radius=120, avg_safety=0, use_interp=true, use_dither=true, Input_tv=true, output_tv=true, high_quality=true, high_bitdepth=true, chroma_process=20, asm_opt=3, debug_view=false)
ConvertFromStacked()
KNLMeansCL(D=3, A=2, h=10.725, wref=1.65, wmode=3, device_type="gpu")
FFT3DFilter(sigma=0.175135, bt=-1, bw=32, bh=32, ow=16, oh=16, sharpen=0.275135, interlaced=false, wintype=2, ncpu=16)
ConvertBits(10)
```

![2021-03-05 08_36_56-SpeedCommander 18](https://user-images.githubusercontent.com/7472445/110082804-24bb1300-7d8e-11eb-9a9a-7182b78dbf49.png)
![2021-03-05 08_39_10-New Issue · staxrip_staxrip - Brave](https://user-images.githubusercontent.com/7472445/110083006-6d72cc00-7d8e-11eb-9cbf-54ecf4897221.png)

**Comment by 44vince44** [comment]
Thanks for the bug reporting, and the code which will allow me investigate this now.

**Comment by Dendraspis** [comment]
@OnbekendHH 
Have you seen that @44vince44 has edited his post?  We're waiting.  😊

**Comment by 44vince44** [comment]
I think this must be labelled "could not reproduce" and "tool issue" then closed

**Comment by Dendraspis** [comment]
Feel free to re-open this issue when you have more information for us and think, that it is related to StaxRip.  😊
