### ISSUE TITLE
DD+ Encoding at higher bitrates fails

### ISSUE THREAD

**Issue by tkozybski** [staxrip/staxrip#566]
When encoding EAC3 to bitrates >= ~1 Mbps the ffmpeg will crash with this error at "Audio Encoding" phase:
> Internal error, put_bits buffer too small
>     Last message repeated 24 times
> Assertion s->buf_ptr < s->buf_end failed at src/libavcodec/put_bits.h:124

It's this error of ffmpeg: https://trac.ffmpeg.org/ticket/8513

I thought I'll use any other encoder in the "Encoding" option but StaxRip still uses ffmpeg no matter what I choose.

**Comment by Dendraspis** [comment]
You could share the log file with us, so we can see where it comes from.

**Comment by tkozybski** [comment]
There's nothing in the log file that I already said. The relevant part. No matter what I choose as an encoder, the log is the same. There's not even a mention of eac3to in the log file when I chose it.


---------------------- Media Info Audio Source 2 ----------------------

General
Complete name         : C:\AUDIOFILE.dtshd
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
File size             : 2.36 GiB
Overall bit rate mode : Variable

Audio
Format                : DTS XLL
Format/Info           : Digital Theater Systems
Commercial name       : DTS-HD Master Audio
Bit rate mode         : Variable
Channel(s)            : 6 channels
Channel layout        : C L R Ls Rs LFE
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : 24 bits
Compression mode      : Lossless

----------------------- Error Audio Encoding 2 -----------------------

Audio Encoding 2 returned error exit code: 3 (0x3)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

System nie może odnaleźć określonej ścieżki


-------------------------- Audio Encoding 2 --------------------------

ffmpeg N-100448-gab6a56773f-x64-gcc10.2.0 Patman

F:\Apps\StaxRip-x64-2.1.8.0-Stable\Apps\FrameServer\AviSynth\ffmpeg.exe -i "C:\AUDIOFILE.dtshd" -c:a eac3 -b:a 1024k -y -hide_banner "C:\AUDIOFILE_737501820.eac3"

Input #0, dts, from 'C:\AUDIOFILE.dtshd':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit)
Stream mapping:
  Stream #0:0 -> #0:0 (dts (dca) -> eac3 (native))
Press [q] to stop, [?] for help
Output #0, eac3, to 'C:\AUDIOFILE_737501820.eac3':
  Metadata:
    encoder         : Lavf58.65.100
    Stream #0:0: Audio: eac3, 48000 Hz, 5.1(side), fltp (24 bit), 1024 kb/s
    Metadata:
      encoder         : Lavc58.115.102 eac3
Internal error, put_bits buffer too small
    Last message repeated 24 times
Assertion s->buf_ptr < s->buf_end failed at src/libavcodec/put_bits.h:124

Start:    10:18:05
End:      10:18:08
Duration: 00:00:03

**Comment by 44vince44** [comment]
The title should be changed to "Cannot use other eac3 encoder than ffmpeg".
Changing encoder to eac3to will keep ffmpeg in command line...

To encode eac3, there is only ffmpeg and eac3to.

**Comment by tkozybski** [comment]
> 
> 
> The title should be changed to "Cannot use other eac3 encoder than ffmpeg".
> Changing encoder to eac3to will keep ffmpeg in command line...
> 
> To encode eac3, there is only ffmpeg. So you'll have to wait that they fix it.
> The bug in ffmpeg when encoding eac3 high rate is a tool issue, not Staxrip's.
> 
> **ANSWER: NOT A BUG**
> All other available encoders do NOT encode eac3. This is why ffmpeg REMAINS in the command line.

Never said that the crash is StaxRip's issue. I even linked the ffmpeg's ticket. Just that it doesn't use other encoders (eac3to included). 

Additionally, knowing there is an issue with ffmpeg, it could be hardcoded to use eac3to instead of ffmpeg for eac3 when bitrate > 900 (960 is the max based on my limited testing) as a workaround for the bug.

> **ANSWER: NOT A BUG**
It is a bug because it doesn't use eac3to when it should.

**Comment by 44vince44** [comment]
eac3to does not encode eac3. Nor the others.
The titles should be changed to be accurate. That's all I'm suggesting.

**Comment by tkozybski** [comment]
> 
> 
> eac3to does not encode eac3. Nor the others.
> If I'm wrong about eac3to please send me a link to the documentation that says otherwise...

Hmm, didn't know eac3to didn't support eac3 encoding, only decoding. A bit misleading to have it as a viable option in the encoder settings. Perhaps it could be improved.

I'm closing the issue then.

**Comment by Dendraspis** [comment]
Very sad that no encoder is able to do that and that *ffmpeg* struggles at higher bitrates.
But yes, a hack could help if it works under all conditions. I doubt that they are going to fix it after more than a year... 🙄 

Let's keep this issue open until it's decided if the hack should be applied or not.

@stax76 
Should be your part.  😁

**Comment by 44vince44** [comment]
If a hack is implemented to add .1 in the bitrate, then perhaps also a bug could be fixed:
when decreasing the bitrate to 1 kbps, then increasing it again, the bitrates are wrong (they are odd instead of even)...

**Comment by Dendraspis** [comment]
> then perhaps also a bug could be fixed:
> when decreasing the bitrate to 1 kbps, then increasing it again, the bitrates are wrong (they are odd instead of even)...

Done.  😃

**Comment by Dendraspis** [comment]
Here is a fix, that should work and I'm willed to implement:
[StaxRip v2.1.8.4D_DDPlus.zip](https://github.com/staxrip/staxrip/files/6090234/StaxRip.v2.1.8.4D_DDPlus.zip)

**Comment by 44vince44** [comment]
@Dendraspis the exe in StaxRip.v2.1.8.4D_DDPlus2.zip does not add 0.1, i've just tried it... with 1024...

**Comment by Dendraspis** [comment]
You were right!
But in my case it worked with `1152k` so when does this bug/issue occur?  😕 

[StaxRip v2.1.8.4D_DDPlus3.zip](https://github.com/staxrip/staxrip/files/6090708/StaxRip.v2.1.8.4D_DDPlus3.zip)

**Comment by 44vince44** [comment]
Well It's a workaround for a bug related to a buffer... so I don't know exactly 🤣 
In my previous test with 1024.0 it worked also. maybe it is only revealed with 5.1 sources ....

**Comment by Dendraspis** [comment]
I tested a 5.1 source and got this:  🤣 

```
Internal error, put_bits buffer too small
    Last message repeated 56 times
Assertion s->buf_ptr < s->buf_end failed at libavcodec/put_bits.h:108
```

**Comment by 44vince44** [comment]
LOL you mean it failed also with 1024.1 ?

**Comment by Dendraspis** [comment]
No, no. `1024k` works with Stereo, but fails with 5.1, the *hack* works with 5.1.
So it's not only related to high bitrates alone, but also to the number of channels.  🤣

**Comment by 44vince44** [comment]
AH LOL ok yes indeed.
But now it's working with the hack! right ? (maybe put a comment in the code so no one removes it accidentally 😁 )

**Comment by Dendraspis** [comment]
5.1, but maybe also 4.0, 7.1, ...  😁 

It's too obvious that it was made on purpose.  😁 

> Note: no one will ever encode stereo at 1024...

I did - and the resulting video was smaller than the stereo sound file.  😂 
But I agree - maybe that's the reason why it works.  🤣

**Comment by 44vince44** [comment]
> But I agree - maybe that's the reason why it works. 🤣
Yes it seems difficult to fill the target data with stereo (when flac, which is lossless usually goes around 700 kbps) 🤣 

> It's too obvious that it was made on purpose. 😁
Well it's possible... Anyway, as I saw you mention 7.1: I think ffmpeg does not allow it (yet... or on purpose also). Meaning there is currently no way to encode 7.1 except if you use commercial software to create the stream, then mux it.
