### ISSUE TITLE
option removed from x265: --mv-refine

### ISSUE THREAD

**Issue by sibylantonioforanna** [staxrip/staxrip#57]
Hi,
seems to me that this option's been removed (and x265 makes staxrip stop when it's used), but I've found there's the option --refine-mv <level 0..3> that looks like a replacement.
Could you look into it?

Thanks.

**Comment by stax76** [comment]
Fixed in the next build, thanks for reporting!

**Comment by stax76** [comment]
new build:

https://forum.doom9.org/showthread.php?p=1885113#post1885113
