### ISSUE TITLE
 Avs filter usage not loading cpu full.

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#575]
v2185 fresh install automatic workflow

Avs filter usage not loading cpu full.

I test few, some filters load more but always load less than no filter.

`AddAutoloadDir("C:\Portable\StaxRip2185\Apps\FrameServer\AviSynth\plugins")
LoadPlugin("C:\Portable\StaxRip2185\Apps\Plugins\Dual\ffms2\ffms2.dll")
LoadPlugin("C:\Portable\StaxRip2185\Apps\Plugins\AVS\TNLMeans\TNLMeans.dll")
FFVideoSource("D:\v\video.mkv", cachefile="D:\v\video_temp\temp.ffindex")
TNLMeans(Ax=4, Ay=4, Az=0, Sx=2, Sy=2, Bx=1, By=1, ms=false, rm=4, a=1.0, h=1.8, sse=true)`

![tnlmean](https://user-images.githubusercontent.com/12258051/110688715-f22c7280-81f2-11eb-9971-312df14c244a.PNG)

without filter

![no filter](https://user-images.githubusercontent.com/12258051/110688760-feb0cb00-81f2-11eb-908b-62731f1b57ad.PNG)

**Comment by jlw4049** [comment]
A lot of AVSFilters aren't multithreaded. This isn't an issue with StaxRip but the filter. 

Even filters that have multithreading support still won't fully load your CPU.

**Comment by DJATOM** [comment]
If you're using avs+, it has it's own MT, you just have to ensble it with `Prefetch(<number of cores>)`.

**Comment by darkcity87** [comment]
Im using build-in avs im not up to %100 but i thought 1080p should at least load %70
Can someone test smdegrain light so i can confirm its only me or not
this is smdegrain light only load %37

![smdgrain light](https://user-images.githubusercontent.com/12258051/110702679-e4cbb400-8203-11eb-87a5-290966869f07.PNG)

**Comment by 44vince44** [comment]
as @DJATOM said, you put at the end of your script:
Prefetch(8)

**Comment by darkcity87** [comment]
i thought MT enable all time.
Now load more than %90 thanks everyone. :-)
