### ISSUE TITLE
Setting for subtitles (ALL, NONE) is ignored in Project Options

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#577]
**Describe the bug**
When using batches, the setting:
Project Options > Subtitles > Demux Subtitles  

is ignored, meaning the subtitles will  be demuxed EVEN if you select NONE...

Moreover, here is a complete description of what happens: if you select DEMUX SUBTITLES = NONE

- In drag and drop mode, the subtitles ARE NOT EXTRACTED to a separate file, when loading the video. But when muxing the project, the muxer takes the subtiitles stream directly from the original video !!! so you end up with subtitles...
- In batch mode, it appears to do the same thing.

Both drag and drop and batch result in the same thing.

The syntax of the muxing command does not take the setting "NONE" into consideration.
I think also this has more repercussions, because when you select "NONE", there is no subtitle file extracted (which is ok), but in the container options, the subtitle checkbox appears and is checked.

Maybe the fix would be: if NONE is selected, make the subtitles UNSELECTED in the container options.

**Comment by 44vince44** [comment]
@stax76 according to what you said on doom9, this is no bug, but a feature.
So this should be closed!

**Comment by stax76** [comment]
Ok, then maybe leave open and check if usability can be improved somehow.

**Comment by 44vince44** [comment]
only needs an explanation note....
@stax76 your problem with discord: you have 2 accounts

**Comment by stax76** [comment]
It could be changed like so:

The option 'Demux Subtitles' has currently following options:

- Show Dialog
- Preferred Languages
- All
- None

This option could be renamed to just 'Subtitles' with the following options:

- Show dialog to choose subtitles to be included
- Demux and include preferred languages
- Don't include subtitles

This is much easier to use.

The capability to demux all but include only preferred will be lost however, I think it's not needed.

**Comment by 44vince44** [comment]
Well so much for a retirement 🤣

**Comment by stax76** [comment]
Unfortunately there was quite a bit of complexity, so I've programmed a little more than I wanted today, and due to the complexity it's possible that a bug slipped through. But I think it's a good usability improvement. Hotfix is online.

**Comment by 44vince44** [comment]
@stax76 I have tested this new feature,
- tested "Demux and Include Preferred Languages" with "all" => pass 🆗 
- tested "Demux and Include Preferred Languages" with specific languages available in files => pass 🆗 
- tested "Demux and Include Preferred Languages" with specific languages NOT available in files => pass 🆗 
- tested "Don't include subtitles" => pass 🆗 

-

**Comment by stax76** [comment]
@44vince44 Thanks for testing it.

**Comment by HakunaMatata47** [comment]
Hi @stax76   I still (or better again?) have this issue in  v2.30    with "don't include subtitles" - VSRip is started anyway.

It was fine with the old 1.1.9.0  but not with newer ones as far as I tested.
I even tested the version 2.1.9.0  where this issue is explicitly listed as an improved usability - but VSRip starts nevertheless with 
So selecting "no subtitles" in the options - in any spelling - does not skip this step of ripping subtitles.
Can you confirm that?

**Comment by Dendraspis** [comment]
I have fixed it for the next release....
