### ISSUE TITLE
Update tools, plugins

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#58]
x265-3.1+20 Wolfberry
https://doc-10-2s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/9rb5c5htr66v1nb92vmfocq1411m2a12/1568750400000/12366144845813295193/*/19cXGmLdl7qhSCIRHkCyMX8zRam2HFHGR?e=download

NVEncC 4.48
https://github.com/rigaya/NVEnc/releases/download/4.48/NVEncC_4.48_x64.7z

AVSMeter 2.9.6
http://www.iol.ie/~schubert/gas/AVSMeter296.7z

JPSDR Avisynth's plugins pack
https://github.com/jpsdr/plugins_JPSDR/releases/download/3.1.3/plugins_JPSDR_v3_1_3.7z

L-SMASH-Works
https://github.com/HolyWu/L-SMASH-Works/releases/download/20190917/L-SMASH-Works_20190917.7z

DGHDRtoSDR 1.12
http://rationalqm.us/hdr/DGHDRtoSDR_1.12.rar

MVTools 2.7.41
https://github.com/pinterf/mvtools/releases/download/2.7.41/mvtools-2.7.41-with-depans.7z

FFT3DFilter 2.6
https://github.com/pinterf/fft3dfilter/releases/download/v2.6/FFT3dFilter-v2.6.7z

TIVTC 1.0.14
https://github.com/pinterf/TIVTC/releases/download/v1.0.14/TIVTC-v1.0.14.7z

RGTools 0.98
https://github.com/pinterf/RgTools/releases/download/0.98/RgTools-0.98.7z

havsfunc r32
https://github.com/HomeOfVapourSynthEvolution/havsfunc/archive/r32.zip

DFTTest r6
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-DFTTest/releases/download/r6/DFTTest-r6.7z

TCanny r12
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-TCanny/releases/download/r12/TCanny-r12.7z

NNEDI3CL r7.3
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-NNEDI3CL/archive/r7.3.zip

BM3D r8
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D/releases/download/r8/BM3D-r8.7z

**Comment by stax76** [comment]
Thanks for all the links! I'm halfway through now of updating everything.

**Comment by Patman86** [comment]
[DGHDRtoSDR 1.13](http://rationalqm.us/hdr/DGHDRtoSDR_1.13.rar)

[NVEncC 4.51](https://github.com/rigaya/NVEnc/releases/download/4.51/NVEncC_4.51_x64.7z)

**Comment by stax76** [comment]
I've updated both, thanks for suggesting and posting the links.

**Comment by Patman86** [comment]
[NVEnc latest build](https://github.com/rigaya/NVEnc/releases/latest)
[QSVEnc latest build](https://github.com/rigaya/QSVEnc/releases/latest)
[VCEEnc latest build](https://github.com/rigaya/VCEEnc/releases/latest)
[Some other StaxRip-Tools](http://www.mediafire.com/folder/vkt2ckzjvt0qf/StaxRip_Tools)
[Plugins_JPSDR](https://github.com/jpsdr/plugins_JPSDR/releases/latest)
[VSFilterMod](https://github.com/sorayuki/VSFilterMod/releases/latest)

**Comment by 44vince44** [comment]
Thanks Patman86 for sharing the links with us (and the builds too)!!

**Comment by 44vince44** [comment]
@Patman86 What is the difference between the x264 release with letter M and the other? Is it to indicate it's a custom build ?

**Comment by Patman86** [comment]
> 
> 
> @Patman86 What is the difference between the x264 release with letter M and the other? Is it to indicate it's a custom build ?

yes, it is a custom build

[look here](https://forum.doom9.org/showthread.php?p=1897459#post1897459)

**Comment by 44vince44** [comment]
Ah, thanks again Patman86 !!!

**Comment by Patman86** [comment]
Thank you for your feedback. I want to remove the --bStylish option in my future versions. Only the revision of the progress bar remains.
