### ISSUE TITLE
Theming issue in demuxing dialog

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#581]
- The checkboxes in the screenshot aren't rendered correctly.
- The dialog background color is not correct.

**How to reproduce the issue**

Options > Subtitles > Show Dialog

![issue-demux-dialog](https://user-images.githubusercontent.com/11410540/110854268-ffaa3100-82b4-11eb-923f-de90f17768af.png)

**Comment by Dendraspis** [comment]
I'm already into it...

**Comment by stax76** [comment]
Great, otherwise we could have disabled custom drawing for this dialog meanwhile.

**Comment by Dendraspis** [comment]
Okay, there were a few things that slipped through my hands.  🙄  And if I had began Themes with this form, I would stop immediately. 

There are **two** things, that I cannot solve:
1. ListViews without content were disabled. But when they are disabled, they get the standard gray system color that you see in the picture above which looks awful.  So I let them enabled.
2. ListViews in `SmallIcon` view let the system draw the items as soon as the value is set. This means the system checkbox is used. 🙄

**Comment by stax76** [comment]
Good you've started not with this dialog. I've applied a workaround:

https://github.com/staxrip/staxrip/commit/9b6e9563d41fd4108df7a2052e22a037c9e58f9d

That should be fine, these two dialogs are not so important.
