### ISSUE TITLE
Theming issue in File Batch window

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#582]
**Describe the bug**
The file batch windows lacks theme, here is how it looks here (strange colors are due to customized OS color settings)
To open this window, just click on 
Open a Source File
-> File Batch

![SNAG-0002](https://user-images.githubusercontent.com/17828567/110906789-1f714180-8315-11eb-841d-48f192052431.jpg)

I hope this is not an impossible to do window that has already been mentioned and that I've forgotten about...

**Comment by Dendraspis** [comment]
No, this must be possible. I'll fix it today.

Interesting how many windows there are, that nobody has seen while testing and searching for several weeks.  😁

**Comment by 44vince44** [comment]
Well there were actually many different improvements at the same time. It explains some confusion 😁 ...
I am also very surprised that I skipped this window !!!

**Comment by Dendraspis** [comment]
Is fixed now:

<img width="500" src="https://user-images.githubusercontent.com/50659978/110917559-5564f480-831a-11eb-9168-9d80a39287eb.png">

**Comment by 44vince44** [comment]
Thanks 🎉
