### ISSUE TITLE
Error in demuxing audio

### ISSUE THREAD

**Issue by Basiswissen** [staxrip/staxrip#584]
With 2.1.8.4 and 2.1.8.5 I get an error with demuxing audio:

`MP4Box 1.1.0 rev506 gcc10.2 Patman

"C:\Program Files (x86)\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -single 2 -out "C:\Users\Michael\Desktop\DJI_0136_temp\ID1 English {DJI.AAC}.m4a" C:\Users\Michael\Desktop\DJI_0136.MP4

[isom] invalid tag size in Xtra !
[isom] not enough bytes in box Xtra: 177 left, reading 536576 (file isomedia/box_code_base.c, line 12503)
[iso file] Read Box "Xtra" (start 90900445) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "udta" (start 90900043) failed (Invalid IsoMedia File) - skipping
[iso file] Read Box "moov" (start 90899927) failed (Invalid IsoMedia File) - skipping
Error opening file C:\Users\Michael\Desktop\DJI_0136.MP4: Invalid IsoMedia File`

The video is directly from my DJI Osmo Pocket with 192 kb/s, 48KHz, 2 channel, AAC LC. 
The error happens even with fresh installed default settings.

With the last stable Staxrip 2.1.8.0 it works perfectly.

**Comment by Dendraspis** [comment]
@Basiswissen 
Can you share a short sample with us?

**Comment by Basiswissen** [comment]
Certainly:

https://drive.google.com/file/d/1HPwXkzwxPNVOWG_dfXRnsmP654wobo0x/view?usp=sharing

**Comment by 44vince44** [comment]
Seems a problem with mp4box ...
Meanwhile it is investigated:
@Basiswissen would could consider as a workaround to remux your file with mkxtoolnix so you can open it in Staxrip ?

**Comment by Basiswissen** [comment]
Thanks for you quick reply, btw.

I just dialed back to 2.1.8.0 for the time beeing. I'm in no hurry here ;)

**Comment by 44vince44** [comment]
Good ;-) I am checking if this is a problem with the original Mp4Box or a problem with Patman86's build...

**Comment by Dendraspis** [comment]
@Basiswissen 
You can use v2.1.8.5, you only have to replace MP4Box.exe.  😉 

I get the same error, so I can confirm it.  Replacing MP4Box with the one provided with v2.1.8.4 solves the problem.

**Comment by Basiswissen** [comment]
Thanks, will try that later!

**Comment by Dendraspis** [comment]
@Patman86 
This is a reproducible issue with the latest build of MP4Box.  Do you know the problem? Can you help??

`MP4Box 1.1.0-rev447-g8c190b551-gcc10.2.0 Patman`  🆗 
`MP4Box 1.1.0 rev506 gcc10.2 Patman`  🆗 
`MP4Box 1.1.0 DEV rev542 gcc10.2.0 Patman` 🛑

**Comment by 44vince44** [comment]
@Basiswissen @Dendraspis @Patman86 the problem described here is from original Mp4Box. The version used here is a DEV build, 1.1.0 rev542.  I have tried also 1.1.0 rev547 from Gpac releases, it does the same bug.
I am going to file that in Mp4Box tracker...
Maybe if this is not solved soon, we should include in next release of staxrip a stable version, not a dev version ?

**Comment by Dendraspis** [comment]
Yeah, of course - haven't seen the **DEV** until I pasted it here.   😂 

@44vince44 
Yeah, this is the way to go.  😁

**Comment by Patman86** [comment]
> `v2.1.7.2 -=- MP4Box 1.1.0-rev447-g8c190b551-gcc10.2.0 Patman` 🆗
> `v2.1.8.2 -=- MP4Box 1.1.0 rev506 gcc10.2 Patman` 🆗
> `v2.1.8.5 -=- MP4Box 1.1.0 DEV rev542 gcc10.2.0 Patman` 🛑

All versions are DEV versions!!!

![image](https://user-images.githubusercontent.com/54327252/110979074-6fc3c000-8364-11eb-86ad-fcc373786d33.png)

**Comment by Dendraspis** [comment]
I'm not using MP4Box at all, but good to know that.  😁 
Didn't know if there was such a bug modification like in x265.  😊 

Thanks, @44vince44  is going to report it.

**Comment by Basiswissen** [comment]
Just tested the MP4Box from 2.1.8.4, but still the same error. 

I initially tested 2.1.8.4 and 2.1.8.5 - both giving the same error. 

Using MP4Box from 2.1.8.0 and it's working good with 2.1.8.5.

**Comment by 44vince44** [comment]
yes, you need to use 2.1.8.2 for it to work.

**Comment by 44vince44** [comment]
Bug reported here:

https://github.com/gpac/gpac/issues/1707

you can all follow up ;-)

**Comment by Basiswissen** [comment]
> 
> 
> yes, you need to use 2.1.8.2 for it to work.

Same error with 2.1.8.2

The last working version is from 2.1.8.0

**Comment by 44vince44** [comment]
I can't confirm nothing of the exact latest version that works from their site because they keep less than 10 nightly builds

**Comment by Patman86** [comment]
Is fixed!

**Comment by stax76** [comment]
Express support. 🙂

Here is the download link:

https://www.mediafire.com/file/kcfa54k4f2hs14g/Mp4Box-1.1.0-DEV-rev589-gb2f344f5f-x64-gcc10.2.0.7z/file

**Comment by Basiswissen** [comment]
Fixed version works!

Thanks for the great support ;)
