### ISSUE TITLE
Possibility of changing ts/m2ts etc handling

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#588]
**Context**

A couple of years ago, there was no automatic preprocessing for ts/m2ts to remux them to mkv. And loading ts files did make Staxrip crash. So preprocessing was introduced to fix that.
But now, disabling the preprocessing does NOT make staxrip crash. I have just tested with 3 files (ts, ts, m2ts)

**Request**

Since ts and m2ts files preprocessing seems problematic (see this thread where to examples are discussed https://github.com/staxrip/staxrip/issues/585), and since it seems that NO preprocessing for ts and m2ts allows the file to be opened and encoded, can't we consider handling ts and m2ts directly without preprocessing ?

**Comment**
The stream list is not complete when loading directly ts/m2ts without preprocessing.

**Comment by stax76** [comment]
There can be different types of transport streams, ffms2 and L-Smash-Works were never good handling these files, often audio is asynchronous, only DGDecNV can process them reliably. In my experience it's more reliable remuxing ts to mkv with ffmpeg. Users might have to try different methods suitable for their type of file and configure staxrip which unfortunately might not many users know or understand, it's rather difficult for average people, and it's not yet even documented in the Wiki except JJKylee's [DGDecNV tutorial](https://github.com/staxrip/staxrip/wiki/How-to-register-DGDecNV%28DGSource-and-DGIndexNV%29-in-StaxRip).

**Comment by stax76** [comment]
If there are certain type of formats were eac3to or ffmpeg are known to fail, then it might be possible to address it in staxrip without too much effort. It should however also be reported on the ffmpeg tracker.

**Comment by 44vince44** [comment]
Ah, so that was the reason for remuxing... I see, I thought it was real crashes, but of course if there is AV sync problems, then it seems remixing is better.
I don't know if I have enough knowledge to continue with that. Maybe I should close, and we note that users having problems with ts/m2ts can try to change extension so they try another handler in staxrip...
What do you think ?

**Comment by stax76** [comment]
I don't know exactly the difference between the ts and m2ts container. If the extension is correct then I would not change the extension but rather change how staxrip handles the extension, this can be configured in the Preprocessing section of the settings.

**Comment by JJKylee** [comment]
I agree with @stax76. Users can always activate/de-activate `ts`/`m2ts` preprocessors by toggling their checkboxes in `Settings` > `Preprocessing`.

BTW, I got interested in testing if `DGDecNV` can handle those samples correctly _unlike_ `ffmpeg` and `eac3to`. @44vince44, can I get them if they're not too big? If it's inconvenient for you to get them ready, then forget about it. 😅

**Comment by 44vince44** [comment]
Here's the link to them:
http://thedigitaltheater.com/dolby-trailers/

There are all kinds of formats. I tested on the one called "chameleon", m2ts.
Then in order to test with ts, I've used tsMuxeR to create a ts file.

**Comment by JJKylee** [comment]
For a short test, I downloaded _Chameleon_, made a `ts` copy via _tsMuxeR_ (most recent nightly build).

In summary, `DGIndexNV` seems to _work well_ for both `m2ts` and `ts`. All audio tracks (including the embedded AC3 stream in trueHD) are demuxed correctly.

![StaxRip_2 1 8 5_DGDecNV_preprocessing_Dolby-Vision_m2ts_with_complex_audio_tracks_20210314](https://user-images.githubusercontent.com/3157518/111077854-f3d68e80-84af-11eb-9ad9-ce219d42e276.jpg)

Now I need @Bandid0's sample for comparison.

BTW, `DGIndex` is simply ignored since the video streams are not MPEG-2.

**Comment by 44vince44** [comment]
> BTW, DGIndex is simply ignored since the video streams are not MPEG-2.

thanks for the info !

Now for` DGIndexNV`, i believe it is not free software, right ?
And you had wrote the script manually... ?

**Comment by JJKylee** [comment]
`DGDecNV` is $15, one-time payment.

Once you set up StaxRip to use `DGDecNV`, it handles basically almost all most-often-used file types pretty nicely.

As you may know, refer to [this Wiki document](https://github.com/staxrip/staxrip/wiki/How-to-register-DGDecNV%28DGSource-and-DGIndexNV%29-in-StaxRip) for setup.

It may look a little complicated, but the workflow is pretty straightforward:

1. `DGIndexNV` takes the input file, generates a `dgi` index file for the video stream, (and demuxes audio tracks separately for some input file types according to the set up).
2. `DGSource` interprets the `dgi` index file and decodes the video stream (in the `avs` script).
3. Audio tracks are dealt with in the usual way.
4. The muxer of choice muxes the encoded video/audio streams into a container.

The `avs` script is automatically generated by the `DGSource` profile as introduced in the Wiki document. As you know, you can customize the profile to your taste referring to the `DGDecNV` manuals.

As simple as that. 😄

**Comment by Bandid0** [comment]
Chameleon
[Chameleon_staxrip.log](https://github.com/staxrip/staxrip/files/6139742/Chameleon_staxrip.log)

**Comment by 44vince44** [comment]
@Bandid0 🤣 If you read YOUR other thread https://github.com/staxrip/staxrip/issues/585, you'd know what to do...
CHANGE TO TS ! and it will work !

**Comment by 44vince44** [comment]
@stax76 If in the following days/weeks we get more information that proves that:

- ts is better handled with eac3to
- m2ts is better handled with ffmpeg

Then perhaps we could cross-exchange the default settings.

**Comment by Bandid0** [comment]
> @Bandid0 🤣 If you read YOUR other thread #585, you'd know what to do...
> CHANGE TO TS ! and it will work !

Sorry I thought you asked me to do the test

**Comment by 44vince44** [comment]
I was editing my post, just when you replied, when I read I thought it was rude, so sorry for that, no rudeness intended 😃

**Comment by Bandid0** [comment]
> @Bandid0 I was editing my post, just when you replied because when I read it again I thought it was rude, so I'm deeply sorry for that, no rudeness intended 😃

no problem

**Comment by JJKylee** [comment]
@Bandid0, can you share _your sample_ used in #585? I'd like to see if it demuxes OK with `DGIndexNV`.
But again, if it's inconvenient for you to get it ready, you can forget about it. 😅

**Comment by Bandid0** [comment]
I do not know if this type of content can be published here, due to the copyright issue

**Comment by 44vince44** [comment]
if you put it in a cloud, and put link then two hours later you delete the link, there is no problem

**Comment by JJKylee** [comment]
Good suggestion, @44vince44. But I will respect @Bandid0’s decision.
It’s up to you, @Bandid0, whether you will follow @44vince44’s idea or not. 😅

**Comment by Bandid0** [comment]
https://mega.nz/file/Fc8mmbJL#4vcJkr8F1s24Oyuhbk_LSQ0mNm3myVMT5g8W_LLBnYs

**Comment by 44vince44** [comment]
@JJKylee please take the file as soon as possible and let us know after a successful download !

**Comment by JJKylee** [comment]
@Bandid0, thanks. I've downloaded it and loaded it as is with `DGIndexNV` with _no problems_ at all.

#### [Main window after loading is finished]

![StaxRip_2 1 8 5_Bandid0_video ts_with_DGIndexNV_main-window_20210315](https://user-images.githubusercontent.com/3157518/111197891-3b2a5100-857c-11eb-9f83-4a682140827d.jpg)

#### [File list in the temp folder]

![StaxRip_2 1 8 5_Bandid0_video ts_with_DGIndexNV_file-list_20210315](https://user-images.githubusercontent.com/3157518/111198008-5ac17980-857c-11eb-9da3-d753238e251a.jpg)

#### [Log file]

[Bandid0_video_staxrip.log](https://github.com/staxrip/staxrip/files/6143458/Bandid0_video_staxrip.log)

*You can delete the file on Mega, @Bandid0.

**Comment by 44vince44** [comment]
So this should be closed, and replaced with a Wiki entry ?

**Comment by stax76** [comment]
> ts is better handled with eac3to

I think that is unlikely true for TS recorded from DVB.

**Comment by 44vince44** [comment]
I wrote a page in the wiki:
https://github.com/staxrip/staxrip/wiki/How-to-handle-.ts-and-.m2ts-files-in-StaxRip

@JJKylee (and @stax76 and @Dendraspis) please check it!

**Comment by stax76** [comment]
It's a very good guide, I've edited a little, hope it's OK.
