### ISSUE TITLE
2.1.8.5: System Theme Color destroys Dark Theme menus

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#589]
**Describe the bug**

Setting `Menu Style` to `System Theme Color` destroys dark theme menus.
See these screenshots:

![StaxRip_2 1 8 5_Dark-Mode_with_System-Theme-Color_1_20210314](https://user-images.githubusercontent.com/3157518/111076807-2cc03480-84ab-11eb-99eb-9e39e09397db.jpg)

![StaxRip_2 1 8 5_Dark-Mode_with_System-Theme-Color_2_20210314](https://user-images.githubusercontent.com/3157518/111076810-32b61580-84ab-11eb-88b0-612fd8e54326.jpg)

**How to reproduce the issue**

1. Go to `Tools` > `Settings` > `User Interface`.
2. Select any _**dark theme**_ and set `Menu Style` to `System Theme Color`.

**Additional Notes and Suggestion**

Since we already have a wide variety of themes, I believe _**we don't need system theme color menu styles any more**_.

**Comment by Dendraspis** [comment]
@stax76 
Since a dark theme is the default, it might be okay to remove this setting.  What do you think?

**Comment by stax76** [comment]
That feature don't appear important to me, I also think it's okay to remove it.

**Comment by Dendraspis** [comment]
And done.

I removed the whole related code and some old orphans.
