### ISSUE TITLE
JPSDR plugins

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#59]
I noticed that you are using some plugins from JPSDR, for example:

HDRTolls
aWarpSharp2 (aWarpSharpMT)
NNEDI3 [maybe]

and

JPSDR plugin pack (includes the three above)
https://forum.doom9.org/showthread.php?t=174248

Only use JPSDR plugin pack for all options and the other plugins can be deleted then.

**Comment by stax76** [comment]
I'll change it thanks.
