### ISSUE TITLE
2.1.8.5: Authors.html is missing

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#590]
**Describe the bug**

`Authors.html` seems to be missing/not generated.
(Not to mention `License.txt`. 😅)
See this:

![StaxRip_2 1 8 5_hotfix_Help-Info_20210313](https://user-images.githubusercontent.com/3157518/111078822-9db81a00-84b4-11eb-9503-707fe4c4ce89.gif)

**How to reproduce the issue**

1. Go to `Help` > `Info...`.
2. Click on 'StaxRip Authors'.

**Additional information**

See [this line](https://github.com/staxrip/staxrip/blob/469c9ade64c35d27476fb849d536343f492e4e22/Source/General/GlobalCommands.vb#L293).

**Comment by stax76** [comment]
It was added a day after the last beta, so will be included in the next build.
