### ISSUE TITLE
2.1.8.5: In Code Editor, shortcut Ctrl+I creates a tab character in the code

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#591]
In _Code Editor_, `Ctrl+I` (the default shortcut for `Info...`) creates an _unnecessary_ tab character in the code.

See this:

![StaxRip_2 1 8 5_Code-Editor_shortcut_Ctrl+I_20210314](https://user-images.githubusercontent.com/3157518/111086410-3c567200-84d9-11eb-9950-7265be5959b0.gif)

**Comment by stax76** [comment]
It happens also in notepad, here is an explanation:

https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode

With Ctrl+Shift+I it's also happening. 🙁

**Comment by JJKylee** [comment]
You're right.
So as an alternative, I've set `Ctrl+`` as the shortcut.

**Comment by Dendraspis** [comment]
🤔   For me it looks like a feature.   😁 

So why not just removing the shortcut? Or is anybody opening the Info window after each code line?!  😕

**Comment by 44vince44** [comment]
It's a bit annoying, but Ctrl+i seems intuitive for "information". It would be a pity to change it to something counter intuitive. But again, inserting a tab in the code is bad :-( so I really don't know....

**Comment by JJKylee** [comment]
> So why not just removing the shortcut? Or is anybody opening the Info window after each line of code?! 😕

I sometimes do. Esp. when I need to check out pixel formats/bit depths, I open the _Info_ window from within the _Code Editor_. 😝

Well, since this issue is related to something more fundamental and there's not much we can do on our side, I think we better close this thread at this point and leave the shortcut choice to the users. 😓

**Comment by Dendraspis** [comment]
But the default shortcut has to be changed in order to not break working code, because the cursor was placed unfortunate while using the shortcut.

**Comment by JJKylee** [comment]
OK. Then I'd like to recommend `` Ctrl+` `` as the _default_ shortcut like I mentioned above.

**Comment by Dendraspis** [comment]
The problem is, that this character is achieved differently depending the keyboard you use - regarding its language.
To get that particular character on a German keyboard you have to press and hold `SHIFT` + the character key, then release both and press space.
So that might cause issues and in order to prevent that, we should select another shortcut.  😞

**Comment by JJKylee** [comment]
Didn't know there's a problem with the `` ` ``(backtick) input for some keyboard layouts. 😆
`F2` looks simple and even better. 👍

**Comment by stax76** [comment]
> Well, since this issue is related to something more fundamental and there's not much we can do on our side.

It might be possible to workaround by dealing with Win32 window messages but spending an hour or two for this might not be well invested time, changing the default shortcut is much easier.

In mpv.net I was able to get rid of the annoying sound using the alt key but applying the very same fix in staxrip does not work. 🙁

I've changed it to F2.
