### ISSUE TITLE
x264 wrong preset defaults

### ISSUE THREAD

**Issue by tkozybski** [staxrip/staxrip#594]
https://dev.beandog.org/x264_preset_reference.html
Presets fast and higher set chroma-qp-offset to -2 by default. It's not happening right now.

Ultra Fast shouldn't have any partitions set. AQ-strength should be 0, but it's disabled anyway so it doesn't matter.

**Comment by JJKylee** [comment]
Well, the `x264` console help (`161-r3048+25(GCC10.2.0) Mod by Patman`) does _**not**_ have the related info.

```
--chroma-qp-offset <integer>  QP difference between chroma and luma [0]
```

And in the `--preset` part, `fast` and higher presets have the following modified parameter settings but `--chroma-qp-offset` is _**not**_ mentioned at all:

```
--preset <string>   Use a preset to select encoding settings [medium]
                    Overridden by user settings.
    - ultrafast:
        --no-8x8dct --aq-mode 0 --b-adapt 0 --bframes 0 --no-cabac --no-deblock --no-mbtree --me dia --no-mixed-refs --partitions none --rc-lookahead 0 --ref 1 --scenecut 0 --subme 0 --trellis 0 --no-weightb --weightp 0
    - superfast:
        --no-mbtree --me dia --no-mixed-refs --partitions i8x8,i4x4 --rc-lookahead 0 --ref 1 --subme 1 --trellis 0 --weightp 1
    - veryfast:
        --no-mixed-refs --rc-lookahead 10 --ref 1 --subme 2 --trellis 0 --weightp 1
    - faster:
        --no-mixed-refs --rc-lookahead 20 --ref 2 --subme 4 --weightp 1
    - fast:
        --rc-lookahead 30 --ref 2 --subme 6 --weightp 1
```

But I tried encoding with `--preset fast` and confirmed that `--chroma-qp-offset` is indeed set to `-2`.

[test_1-audio-track_staxrip.log](https://github.com/staxrip/staxrip/files/6143929/test_1-audio-track_staxrip.log)

Output file `Encoding settings` mediainfo:

```
Encoding settings:
[...] / chroma_qp_offset=-2 / [...]
```

So sad that the console help generated with the `--fullhelp` switch is not complete. 😢

**Comment by Dendraspis** [comment]
> https://dev.beandog.org/x264_preset_reference.html
> Presets fast and higher set chroma-qp-offset to -2 by default. It's not happening right now.

Because this parameter has nothing to do with presets, that are commited to x264. There is no preset that sets `chroma-qp-offset` to a specific value.

> Ultra Fast shouldn't have any partitions set. 

Which parameter(s) do you mean?

> AQ-strength should be 0, but it's disabled anyway so it doesn't matter.

Not *should*, because AQ-Strength is not set via presets. It is possible and valid disabling AQ-Mode and set AQ-Strength to maximum.

**Comment by JJKylee** [comment]
> > Presets fast and higher set chroma-qp-offset to -2 by default. It's not happening right now.
> 
> Because this parameter has nothing to do with presets, that are commited to x264. There is no preset that sets `chroma-qp-offset` to a specific value.

Agreed. This is not an issue.

`--chroma-qp-offset` is automatically set according to the preset choice. Since StaxRip does not _explicitly_ modify the parameter setting of a given preset with respect to `--chroma-qp-offset`, there's nothing to fix here.

**Comment by Dendraspis** [comment]
@JJKylee 
It's a cli help, not an encyclopedia.  😉   Of course internal procedures are not mentioned.
Check out the cli help of `aomenc`, afterwards you will love the x264 help.  😁

**Comment by JJKylee** [comment]
> Check out the cli help of `aomenc`, afterwards you will love the x264 help. 😁

...yuk! 😩😖😵🤪🤮😱

**Comment by tkozybski** [comment]
> > Ultra Fast shouldn't have any partitions set.
> 
> Which parameter(s) do you mean?

In GUI everything in Analysis->Partitions unchecked. 
param->analyse.intra = 0;
param->analyse.inter = 0;
In the x264 code: https://github.com/corecodec/x264/blob/master/common/base.c
Other presets also have different partitions settings (ultrafast, superfast, slower, veryslow, placebo strays from defaults).

> > https://dev.beandog.org/x264_preset_reference.html
> > Presets fast and higher set chroma-qp-offset to -2 by default. It's not happening right now.
> 
> Because this parameter has nothing to do with presets, that are commited to x264. There is no preset that sets `chroma-qp-offset` to a specific value.

I did some test encodes and you are right (partially?). if you set chroma-qp-offset to -2 on preset fast or above then it'll result as -4 in the encode so 0 in the app is good and I was wrong. What a great design decision from the x264 devs for it to have a hardcoded offset...

**Comment by JJKylee** [comment]
> In GUI everything in Analysis->Partitions unchecked.
> param->analyse.intra = 0;
> param->analyse.inter = 0;
> In the x264 code: https://github.com/corecodec/x264/blob/master/common/base.c
> Other presets also have different partitions settings (ultrafast, superfast, slower, veryslow, placebo strays from defaults).

Again, this is **_not a bug_** since StaxRip does not _explicitly_ modify any parameter settings related to the preset `ultrafast`. The command line (which is passed on to `x264`) is the final criterion for this.

![StaxRip_2 1 8 5_hotfix_x264_ultrafast_20210315](https://user-images.githubusercontent.com/3157518/111235766-9412dd00-85ae-11eb-94a5-d1cb3337ffe5.jpg)

If the output video stream lacks the said feature, then it's a tool issue with `x264`.

The GUI option values for `Partitions` in StaxRip are there for explicit customization of parameter settings. Users are responsible for their use, so there's nothing wrong about them.

---

Aside from this discussion, let me just point out a very minor issue regarding `--crf`. @Dendraspis, plz take a look at this:

![StaxRip_2 1 8 5_hotfix_x264_crf23_20210315](https://user-images.githubusercontent.com/3157518/111235962-fd92eb80-85ae-11eb-9886-b5d3efb54203.jpg)

**Comment by tkozybski** [comment]
> Again, this is **_not a bug_** since StaxRip does not _explicitly_ modify any parameter settings related to the preset `ultrafast`. The command line (which is passed on to `x264`) is the final criterion for this.

Right, I get all that but there is a mismatch between GUI and command line parameters because of that, we want to have the GUI match the parameters sent. Let's say someone would want to set preset ultrafast and enable the partitions that are currently enabled in GUI (but not sent to the encoder), you can't without passing custom command line, because the GUI doesn't match the parameters. It is a bug.

**Comment by JJKylee** [comment]
Makes sense. Yes, it is a bug _in that sense_.
In that case, we need to use the `Custom` section instead. But it's cumbersome, of course.

Maybe a similar topic was discussed in the past. IIRC, the required feature - a complete match between GUI and command line parameters - was left undone because its implementation is very hard and requires a lot of work. Is it right, @Dendraspis? 🙄

**Comment by Dendraspis** [comment]
Ok,  the easy thing first:   CRF23 is default now.  😁 

The *Partitions* are now all unchecked on *UltraFast*. That was indeed a bug.  😏 
Should be okay now.

> What a great design decision from the x264 devs for it to have a hardcoded offset...

It is not a hardcoded offset, it is more an internal re-calculation depending on all the other settings that were made. But indeed really confusing when the summary prints the different/calculated value only.  🙄 


Here is the hotfix:
[StaxRip v2.1.8.5D_x264.zip](https://github.com/staxrip/staxrip/files/6149898/StaxRip.v2.1.8.5D_x264.zip)

**Comment by JJKylee** [comment]
@Dendraspis,

I tested with the most recent hotfix on @stax76's beta archive, and it seems that `--crf 23` issue in `x264` has _not_ been properly fixed.

The `ultrafast` partitions mismatch b/w GUI and command line is fixed though.

![StaxRip_2 1 8 5_hotfix_x264_crf23_ultrafast_20210316](https://user-images.githubusercontent.com/3157518/111355641-cc64fa80-8644-11eb-99f7-32a9a276771c.jpg)

**Comment by Dendraspis** [comment]
You're right, there is even more to fix.  Don't know how I could miss this...  😲 

Now it's definitely fixed:
[StaxRip v2.1.8.5D_x2642.zip](https://github.com/staxrip/staxrip/files/6151537/StaxRip.v2.1.8.5D_x2642.zip)

**Comment by JJKylee** [comment]
I confirm it is fixed. Thanks. 😊
