### ISSUE TITLE
2.1.8.5: x264 console help window fails to read a particular portion of the help text file

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#595]
x264 _console help window_ fails to read the `Presets` section of the help text file, `x264 Help.txt`. To be precise, it's lines 41 through 143.

The following parameter options belong here:

> `--profile`, `--preset`, `--tune`, `--slow-firstpass`

As a result, the right click console help for the corresponding parameters either fails or finds a less relevant part on the help file.

See this:

![StaxRip_2 1 8 5_x264_console-help_missing_Presets_section_20210315](https://user-images.githubusercontent.com/3157518/111244913-0ab8d600-85c1-11eb-981e-c0a403a2e0bd.gif)

(By contrast, the help _text file_ itself is OK.)

**Comment by stax76** [comment]
I've uploaded a hotfix and hope it's working.
