### ISSUE TITLE
Thumbnailers: StaxRip Thumbnailer doesn't work & MTN Thumbnailer needs more custom fields

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#596]
As of 2.1.8.5,

### StaxRip Thumbnailer

Opening a video file succeeds.
But if I try to run it with a setting, it just dies and _kills the main window without any error messages at all_.

### MTN Thumbnailer

~~An extra field for a custom font path `-f fontfile` is desired in case the video name is localized(non-English).~~

Extra fields for other options are desired in the _Thumbnail Options_ window.
Ex) Fields for `-f`, `-F`, `-L`, `-g`, `-k`, etc. + `-Z`(always use non-seek mode)

The current _Thumbnail Options_ window:

![StaxRip_2 1 8 5_MTN_Thumbnail-Options-window_20210317](https://user-images.githubusercontent.com/3157518/111529989-07882c00-8720-11eb-87a9-cd5e3a53f749.jpg)

Only fields for `-c`, `-r`, `-j`, `-h`, `-w`, `-D`, `-O` exist.

### Extra note and suggestion

Considering that these tools are not closely associated with StaxRip and that there are many other excellent alternatives like the [standalone MTN](https://www.videohelp.com/software/movie-thumbnailer), [PotPlayer](https://www.videohelp.com/software/PotPlayer), [Video Thumbnails Maker](https://www.videohelp.com/software/Video-Thumbnails-Maker), etc., I believe we'd better remove these tools from StaxRip.

**Comment by 44vince44** [comment]
No, 😕  that should be easy to fix! is that right dear coders ?

**Comment by JJKylee** [comment]
Well, if fixing is possible, I will not stick with removal.

BTW, according to the explanation on the _Apps Manager_, _MTN Thumbnailer_ is a custom built version.

> StaxRip uses a custom built version with HEVC support added in and also includes the latest FFMPEG.

That means we need to modify the MTN sources and build it on our own.

I'm wondering if @stax76 or @Dendraspis is willing to go through this hassle. 😁

**Comment by 44vince44** [comment]
Yes you're right, Revan654 was the one who built it. We have an old build, I checked the latest version by Revan654 is 2.2 here https://github.com/Revan654/movie-thumbnailer-mtn

However, there are **more recent** forks that include hevc: https://gitlab.com/movie_thumbnailer/mtn/-/wikis/home
The latest version is 3.4.

**Comment by JJKylee** [comment]
I downloaded the [pre-built Windows executable (x86)](https://bitbucket.org/wahibre/mtn/downloads/mtn-3.4.0-win32.zip), extracted it to an arbitrary folder, and ran the following command line in that folder:

```
mtn -c 3 -r 5 -w 1024 -b 1 -f NanumSquareRegular.ttf -F ffffff:11:Daum_SemiBold.ttf:ffffff:222222:10 -L 4:2 -g 5 -k 171717 "D:\Downloads\한글 이름 테스트.mp4"
```

Here, `D:\Downloads\한글 이름 테스트.mp4` file is an HEVC/AAC-HE video file (in **_UTF-8 path_**), `NanumSquareRegular.ttf` is the font for the header info text, and `Daum_SemiBold.ttf` is the font for timestamps.

And I get the following snapshot file `D:\Downloads\한글 이름 테스트_s.jpg`.

![한글 이름 테스트_s](https://user-images.githubusercontent.com/3157518/111430961-61eda200-86b8-11eb-9f39-f9e2e49394ba.jpg)

It seems that the pre-built executable reads an HEVC video stream correctly. Here's the log.

```
File: D:\Downloads\í•œê¸€ ì´ë¦„ í…ŒìŠ¤íŠ¸.mp4
Size: 13449823 bytes (13 MiB), duration: 00:01:43, bitrate: 1039 kb/s
Audio: aac (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s (jpn)
Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 939 kb/s, 23.98 fps(r) (jpn)
  step: 6 s; # tiles: 3x5, tile size: 334x188; total size: 1024x1039
  step is less than 14 s; blank & blur evasion is turned off.
[swscaler @ 02f22f00] Warning: data is not aligned! This can lead to a speed loss
  *** seeking off target 9.04 s, increase time step or use non-seek mode.
  *** previous seek overshot target 00:00:36; switching to non-seek mode
  skipping non key packets for this file
  skipping shot at 00:00:36 because of previous seek or evasions
  skipping shot at 00:00:54 because of previous seek or evasions
  skipping shot at 00:01:18 because of previous seek or evasions
  changing # of tiles to 3x4 because of skipped shots; total size: 1024x851
  15.86 s, 0.76 shots/s; output: D:\Downloads\í•œê¸€ ì´ë¦„ í…ŒìŠ¤íŠ¸_s.jpg
```

Although the file names are shown broken in a UTF-8 codepage CMD console, I confirm that _input and output file names are correctly applied_.

So, I think we don't have to build a custom executable for MTN this time, but instead employ the pre-built binaries. 😄
But of course we seem to need additional fields in StaxRip for `mtn` command line input.

**Comment by 44vince44** [comment]
and if Staxrip's own thumbnailer is fixed, it could work maybe better ....

**Comment by JJKylee** [comment]
Well, unfortunately I've found a _critical_ issue with the [pre-built Windows executable 3.4.0](https://bitbucket.org/wahibre/mtn/downloads/mtn-3.4.0-win32.zip):

The executable returns **exit code 1** (ErrorLevel 1), and thus we encounter the `exit code: 1 (0x1)` pop-up window _whenever we run it_. The thumbnail file is successfully produced, though.

The current shipped version (2.0.1) does not have this problem, and I've confirmed that the same command line produces an equally nice output.

So, we need to either stick to the current version or build a correctly fixed executable. 😩

But it's true that either way we need to add extra fields in the `Thumbnail Options` window.

**Comment by 44vince44** [comment]
I think the reason for the exit code could be found and avoided, our coders can maybe investigate.
This is a  nice feature in staxrip, not much used, I agree, but it would be a pity to discard it !

**Comment by JJKylee** [comment]
Maybe @Patman86 has rich experience regarding this matter along with @DJATOM and @msg7086. 😄

**Comment by Patman86** [comment]
Hey guys, what do you think about [mpv-thumbnailer](https://github.com/otsaloma/mpv-thumbnailer)?

**Comment by 44vince44** [comment]
But that would imply maybe lots of new code, I don't know what the coders think ?

**Comment by Patman86** [comment]
Maybe a nice new feature of mpvnet...

**Comment by JJKylee** [comment]
> Hey guys, what do you think about [mpv-thumbnailer](https://github.com/otsaloma/mpv-thumbnailer)?

Looks like its command line syntax is pretty simple.

> Usage: mpv-thumbnailer VIDEO THUMBNAIL SIZE

Which means, there is not much to do for tweaks on the user's side.

It has cons and pros, but I'd like to go on with MTN instead. 😅

**Comment by 44vince44** [comment]
Maybe the exit code is only a problem with staxrip not expecting a proper return information ?

**Comment by JJKylee** [comment]
MTN 3.4.0 does issue exit code `1` but it's _ignored in the CMD console_. So it doesn't matter in CLI since we get the desired snapshot file.

But when MTN 3.4.0 is called from within StaxRip, this exit code `1` raises an issue, and StaxRip pops up an `exit code: 1 (0x1)` error window after the command line is executed.

**Comment by JJKylee** [comment]
This is the scrolling screenshot of an `exit code 0` pop-up error window when I run the pre-built 3.4.0 executable from within StaxRip.

![StaxRip_2 1 8 5_MTN-prebulit-3 4 0_exit-code-0_popup-error_20210317](https://user-images.githubusercontent.com/3157518/111520015-ea019500-8714-11eb-81a7-b7703fd15383.jpg)

Man... This `Err.exe` thingy makes the pop-up window really BIG. 😆

**Comment by JJKylee** [comment]
I've learned that @stax76 pushed [a commit fixing this `exit code 1` issue for MTN only](https://github.com/staxrip/staxrip/commit/042d83a12fc808346837dfa0eb378cd4b82ffaf4) just now.
So we can use the pre-built 3.4.0 executable from now on. 😝

**Comment by Patman86** [comment]
Here is mtn 3.4.0 bin compilied with gcc
[mtn-3.4.0-gcc10.2.0.zip](https://github.com/staxrip/staxrip/files/6159287/mtn-3.4.0-gcc10.2.0.zip)

**Comment by stax76** [comment]
> BTW, it seems like there's too much wasted space in the pop-up window. Is this fixable?

This is the TaskDialog, a native Windows component that cannot be themed, because of that it will be replaced, I started working on it today.

**Comment by JJKylee** [comment]
> Here is mtn 3.4.0 bin compilied with gcc
> [mtn-3.4.0-gcc10.2.0.zip](https://github.com/staxrip/staxrip/files/6159287/mtn-3.4.0-gcc10.2.0.zip)

mtn executable requires the following _shared_ libraries from `ffmpeg`:

```
avcodec-57.dll
avformat-57.dll
avutil-55.dll
liblibgd.dll
swresample-2.dll
swscale-4.dll
```

Your zip file has only the executable file `mtn.exe`, and thus returns exit code `-1073741515` when executed.

**Comment by Patman86** [comment]
Override the mtn.exe under `...\Apps\Thumbnails\MTN` and it works, so in my case.

**Comment by JJKylee** [comment]
Same issue.

It's because those `dll`s in the zip file are not the ones _used for building the executable_.
It works for you because you have those correct `dll`s somewhere in your system.
Plz include the correct `dll`s.

```
avcodec-xx.dll
avformat-xx.dll
avutil-xx.dll
liblibgd.dll
swresample-x.dll
swscale-x.dll
```

(I was wrong about the dll version numbers in the above reply. 😅)

**Comment by Patman86** [comment]
Hope new zip contains correct dll's

**Comment by JJKylee** [comment]
Unfortunately, I still have the same issue.

Maybe we can avoid this issue by making `mtn.exe` _static_, not shared (just like `ffmpeg.exe`).
My guess is it can be done by modifying the `%CFLAGS%` variable for `gcc` in `Make.MinGW.bat`.
Plz give it a try.

**Comment by Patman86** [comment]
Changes in the Make.MinGW.bat file do not produce the desired result. I take a closer look at the code and parameters. A static version would of course be better, so all dll's are omitted.

**Comment by 44vince44** [comment]
Hasn't this been fixed with the commit https://github.com/staxrip/staxrip/commit/042d83a12fc808346837dfa0eb378cd4b82ffaf4

**Comment by JJKylee** [comment]
Yeah, the `exit code 0` error is excepted for MTN, but it's not a fundamental solution to this problem.
We need a better working executable, and I believe @Patman86 will come up with one. 😅

**Comment by Patman86** [comment]
pls test
<a href="https://www.privfile.com/download.php?fid=605b9e65dec91-Njc0Mg==" title="Temporary File Hosting">Download mtn-3.4.0-gcc10.2.0.7z from privfile.com</a>

**Comment by JJKylee** [comment]
> [Download mtn-3.4.0-gcc10.2.0.7z from privfile.com](https://www.privfile.com/download.php?fid=605b9e65dec91-Njc0Mg==)

No more exit code `-1073741515`.
⇒ `dll` dependency issue is resolved. 👍

It runs OK in the CMD console, but this time the exit code is `1`. Same as the pre-built binaries.

This is the CMD code that I used for testing:

```DOS
@echo off
start /wait mtn -c 3 -r 5 -w 1280 -f <HEADER-FONT.ttf> -F ffffff:11:<TIMECODE-FONT.ttf>:ffffff:222222:10 -L 4:2 -g 5 -k 171717 "<INPUT-FILE>" -P
echo Errorlevel is %ERRORLEVEL%
```

Your MTN build produced `%ERRORLEVEL% = 1`, which is equivalent to `exit code 1`.

**Comment by Patman86** [comment]
I have now tested [this thumbnailer](https://github.com/mutschler/mt) and am very satisfied with it. Here is a packed 64bit version...
[mt-1.0.10-x86_64-w64-mingw32.zip](https://github.com/staxrip/staxrip/files/6208365/mt-1.0.10-x86_64-w64-mingw32.zip)

**Comment by JJKylee** [comment]
> [mt-1.0.10-x86_64-w64-mingw32.zip](https://github.com/staxrip/staxrip/files/6208365/mt-1.0.10-x86_64-w64-mingw32.zip)

I tested it out with a _local language(Korean)_ named `mkv` file as follows:

```
mt --numcaps=15 --columns=3 --width=420 --padding=5 --font="NanumSquareRegular.ttf" --font-size=11 --bg-content="23,23,23" --bg-header="23,23,23" --fg-header="255,255,255" --header-meta=true --comment="" --overwrite=true "D:\Downloads\한글 이름 테스트.mkv"
```

I tried to match MTN as closely as possible.

Here's the output snapshot file:

![한글 이름 테스트](https://user-images.githubusercontent.com/3157518/112574630-f2f50500-8dab-11eb-9b59-bdc275093b7c.jpg)

As you may be able to see, there's one _BIG problem_ with this app: Korean filename is broken (not displayed) although the designated font is basically a Korean font.

In more detail, there are obvious defects as follows compared to MTN:

- The comment in header should be explicitly set to an empty string in order to disable it (but can be configured in the `json` setting file)
- No options for a different font/size for timecode display
- Timecode background is not transparent
- No option for header/timecode locations

The only benefit I can find compared to MTN is that this app can generate the exact number of screenshots as directed by the option value(`15`).

Considering that the _correct display of a local filename_ was the original reason that I opened this issue thread, I'm afraid this app cannot be a better or even equivalent alternative to MTN. 🤔

**Comment by Patman86** [comment]
I agree with you, we should stay with mtn. I'm trying to find out why exit code 1 is reported.

**Comment by Patman86** [comment]
@JJKylee
```
MTN exits with

0 - OK
1 - Warning (some shots possibly missing)
2 - Error

Test on Windows:

mtn.exe <movie_file>
if ERRORLEVEL 2 echo Failed
if ERRORLEVEL 1 echo Failed or image is incomplete

or unix-like style

mtn.exe <movie_file> && echo OK || echo failed
```

It seems that error code 1 is a warning, not really an error. Maybe a config thing?

**Comment by JJKylee** [comment]
Oh, really? Then maybe excepting `Exit Code 1` error for MTN is right.

Configuration can be a cause, but it seems that MTN skips shots based on its own criteria.
Looking at my original test, MTN ignores some of my option settings based on the input file properties:

```
*** seeking off target 9.04 s, increase time step or use non-seek mode.
*** previous seek overshot target 00:00:36; switching to non-seek mode
skipping non key packets for this file
skipping shot at 00:00:36 because of previous seek or evasions
skipping shot at 00:00:54 because of previous seek or evasions
skipping shot at 00:01:18 because of previous seek or evasions
changing # of tiles to 3x4 because of skipped shots; total size: 1024x851
```

Then this is why my original test file ended up with `Exit Code 1`. But StaxRip took it as an _**error**_ and showed an error pop-up window accordingly.

Since @stax76 excepted MTN for `Exit Code 1` pop-up, he was right on this matter. 😁

Your build of 3.4.0, [mtn-3.4.0-gcc10.2.0.7z](https://www.privfile.com/download.php?fid=605b9e65dec91-Njc0Mg==), can be a good replacement then.

Thanks. 👍👍👍👍👍

**Comment by Patman86** [comment]
I'll share the MTN version on my mediafire folder. It's a 64 bit build.

**Comment by 44vince44** [comment]
@Dendraspis maybe you should include this build made by @Patman86 instead of the original...
(when it's uploaded)
@Patman86 many thanks !!

**Comment by JJKylee** [comment]
I replaced the pre-built version with @Patman86's build and tried to update the info in Apps Manager.
But I ran into this critical error there.

![StaxRip_2 1 32_Apps-Manager_Edit-Version_error_20210326](https://user-images.githubusercontent.com/3157518/112669449-f83e6800-8e1c-11eb-99a6-5013e658b406.jpg)

```
NullReferenceException (2.1.32)

Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.AppsForm.tsbVersion_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at StaxRip.AppsForm.miEditVersion_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at StaxRip.UI.MenuItemEx.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

@Dendraspis, I think you need to look at this before releasing a new build.

**Comment by 44vince44** [comment]
I confirm this crash with F12, not only mtn, but also mp4box

**Comment by stax76** [comment]
I'll take a look, TaskDialog width is also not optimal.

**Comment by stax76** [comment]
Hotfix is online.

**Comment by JJKylee** [comment]
> Hotfix is online.

This hotfix does fixes the issue. 👍👍👍

BTW, the hotfix build version is now 2.1._**15**_. 😅
I guess @stax76 and @Dendraspis need some agreement on versioning. 🤣

**Comment by 44vince44** [comment]
no they are simply working on their own local copy.... hence my remark some days ago about being careful in synchronizing their work...

**Comment by JJKylee** [comment]
> no they are simply working on their own local copy.... hence my remark some days ago about being careful in synchronizing their work...

That's what I meant.

Maybe there's a way to make versioning consistent b/w @stax76's local dev build and @Dendraspis's local dev build.
Perhaps a format like...
2.1.32D and 2.1.15S?

**Comment by Dendraspis** [comment]
@stax76 
Hotfix is nice, but I need the commit for the release.  😁 

@JJKylee 
Sadly there is no proper way to handle this. But we have to be careful when we release DEV builds officially.

**Comment by 44vince44** [comment]
The only proper way is to commit quickly...

**Comment by JJKylee** [comment]
Yeah, it'd be desirable ideally.
But let's not put too much stress on @stax76 and @Dendraspis's shoulders. 😁

**Comment by 44vince44** [comment]
No on the contrary, we're relieving them of the burden of future major errors ....

**Comment by JJKylee** [comment]
OK. Let's talk about this matter in another place like Discussions, etc.

Let me get back to the original issue here. 😁

@Patman86, I've found that putting a `-Z`(always use non-seek mode) option in MTN resolves the `Exit Code 1` issue in my case.
Now the exit code is `0` _although some shots are still skipped like before_.
Maybe we can include this extra option when we redesign the `Thumbnail Options` window. 🤔

**Comment by Patman86** [comment]
Good to know thanks @JJKylee!!! I think it's a good idea to redesign the thumbnail options window and include all of the options if possible. I think this issue is fixed, right?

**Comment by JJKylee** [comment]
Your build issue is fixed, IMHO. 👍

But this thread should remain open until all the thumbnailers related issues/feature requests are resolved. 😁

**Comment by stax76** [comment]
@Dendraspis 

I've fixed width and height issues in the task dialog. Switching between hide/show details produces some kind of flicker which I try to fix atm.

**Comment by Patman86** [comment]
Here is a little hint on my part. The StaxRip Thumbnailer is no longer included in the Staxrip or it does not work. Please check ...

**Comment by JJKylee** [comment]
Exactly.

Like I said in the original post, StaxRip _just dies without any error messages or logs_ when `StaxRip Thumbnailer` is run with a `Thumbnail Options` setting.

Since nobody notices this issue (except me and @Patman86 now), maybe people are not interested in generating thumbnails in StaxRip at all. 😁

**Comment by JJKylee** [comment]
MTN is updated to 3.4.1 just now. The pre-built _64-bit_ binary is [here](https://bitbucket.org/wahibre/mtn/downloads/mtn-3.4.1-win64.zip).

I tested it on the same (Korean named) file with almost the same command line options (`-Z` switch added this time to prevent the `exit code 1` warning) as follows:

```
mtn -c 3 -r 5 -w 1280 -f NanumSquareRegular.ttf -F ffffff:11:Daum_SemiBold.ttf:ffffff:222222:10 -L 4:2 -g 5 -k 171717 -Z "D:\Downloads\한글 이름 테스트.mkv" -P
```

This generated the following snapshot file:

![한글 이름 테스트_s](https://user-images.githubusercontent.com/3157518/112852872-30ce8380-9061-11eb-9f33-5cc0330e1299.jpg)

Can you see the difference? **_The number of shots is exactly the same as I configured in the options_** in this update.

There's a note in the changelog about this:

```
- improved decoding frames (less skipped pictures)
```

Yes, indeed.

Besides, the processing speed has improved _a lot_. Maybe employing 64 bits and recent ffmpeg codes (`compatibility with FFmpeg 4.4`) helped in this regard. 😊

**Comment by 44vince44** [comment]
@JJKylee @Dendraspis can't this -z parameter be added at once it the command generated by Staxrip ? so we can consider this matter "closed"?

**Comment by JJKylee** [comment]
Yes. Like I said in the original post, this whole issue is resolved if we redesign the `Thumbnail Options` form. 😉

And of course there should be some measure on the non-responsive `StaxRip Thumbnailer` as well.

**Comment by Patman86** [comment]
I'm going to see to what extent I can use the StaxRip Thumbnailer options dialog for MTN and then we should remove the Staxrip Thumbnailer.  The options are pretty similar.

**Comment by Dendraspis** [comment]
Okay, here was a lot of off-topic stuff going on and meanwhile MTN was updated and seems to fix issues.

So beside the missing parameters mentioned in the first post, can anybody summarize the current state and what's actual needed/wanted from StaxRip?

**Comment by 44vince44** [comment]
@JJKylee please state you request in a clear and concise way ! 🤣

**Comment by JJKylee** [comment]
### MTN Thumbnailer

There was an `Exit Code 1` pop-up error window issue. ⇒ fixed by @stax76: MTN is excepted for this 'warning'.

Extra fields for these options are needed for better customization.

`-f` ⇒ command line format: `-f <font-name-with-extension>`
(Default: `-f tahomabd.ttf`)
(Necessary to prevent broken non-European-language file names.)

`-F` ⇒ `-F <header-font-color-hex>:<header-font-size-point>[:<timecode-font-name-with-extension>:<timecode-font-color-hex>:<timecode-shadow-color-hex>:<timecode-font-size-point>]`
(Options in `[ ]` are optional.)
(Ex. `-F ffffff:11:Daum_SemiBold.ttf:ffffff:222222:10`)

`-L` ⇒ `-L <header-location>[:<timecode-location]`
(Options in `[ ]` are optional.) 
(`1`=lower left, `2`=lower right, `3`=upper right, `4`=upper left)
(Default: `-L 1:1`)

`-g` ⇒ `-g <gap-between-shots-in-pixel>`
(Default: `-g 0`)

`-k` ⇒ `-k <background-color-hex>`
(Default: `-k ffffff`)

`-Z` ⇒ `-Z`
(Single switch. Always use non-seek mode - slower but more accurate timing.)
(In order to not yield ERRORLEVEL `1` just in case.)

A console help file is attached.

[mtn Help.txt](https://github.com/staxrip/staxrip/files/6229787/mtn.Help.txt)


### StaxRip Thumbnailer

It just doesn't work after a thumbnail setting and kills the main window. No error messages, no logs.

**Comment by Dendraspis** [comment]
StaxRip Thumbnailer is fixed.  And while fixing I fixed other bugs, too, and I changed the font color to White, so a black background can be selected.  😁 
So now the main difference should be 10bit source file tonemapping only.  🤔 

![LG New York HDR UHD 4K Demo](https://user-images.githubusercontent.com/50659978/113045776-8741dc00-919f-11eb-852c-c48f8a3839c0.jpg)

**Comment by JJKylee** [comment]
For the same file, `LG New York HDR UHD 4K Demo.ts`, this is the **MTN result**:

![LG New York HDR UHD 4K Demo_s_-Z](https://user-images.githubusercontent.com/3157518/113050228-73738700-9159-11eb-843c-c702aab6ad77.jpg)

HDR colors are washed out as in `StaxRip Thumbnailer`.

But I find the following defects as well.

1. It takes _really long_ to get the output (in a matter of minutes, not seconds).
2. The typical FFmpeg warning in dealing with a transport stream file(`ts`, `m2ts`, etc.) appears: 'consider increasing `-analyzeduration` and `-probesize` value...'.

In an attempt to fix 1, I retried MTN _without_ the `-Z`(always use non-seek mode) switch.
It took much shorter (about 5 seconds), but the result is _**even worse**_.

![LG New York HDR UHD 4K Demo_s_no-Z](https://user-images.githubusercontent.com/3157518/113051046-66a36300-915a-11eb-8f24-3e619e2a3692.jpg)

For now, there's nothing we can do on our side.

I'm happy that `StaxRip Thumbnailer` is finally fixed, and shows at least the same or even better results compared to MTN. 😃

**Comment by JJKylee** [comment]
> ![LG New York HDR UHD 4K Demo](https://user-images.githubusercontent.com/50659978/113045776-8741dc00-919f-11eb-852c-c48f8a3839c0.jpg)

Wait. There's insufficient info about the video _pixel format_ here.
`yuv420p10le` is more proper instead of just `yuv420`.

`yuv420` ⇒ 4:2:0 chroma subsampling
`p` ⇒ planar
`10` ⇒ 10 bits per channel (=sample bit depth)
`le` ⇒ little endian

Plz fix it if possible.

**Comment by Dendraspis** [comment]
There is a lot to improve, but I'll wait till @Patman86 finishes his improvement, to not break his work.

> Is there any way to notify the user about this delayed process? 🙄

Sure, but see above.  😁 
And don't expect it to be fixed *tomorrow*.  😉

**Comment by JJKylee** [comment]
Got it.

And about the imprecise pixel format info, I guess it's because `StaxRip Thumbnailer` gets the info from MediaInfo.NET, not from ffmpeg like MTN. Let's forget about it if it's a matter of extra hard work. 😉

**Comment by Dendraspis** [comment]
I think we can close this, because the new Thumbnailer is finished and already tested. Fine tuning will follow, if necessary.

MTN was already removed from the package, which saves us about **60MB** (~10MB zipped).

**Comment by JJKylee** [comment]
Agreed. 😃
