### ISSUE TITLE
Bad Bitrate Calculation StaxRip Beta 2.1.8.5

### ISSUE THREAD

**Issue by PhoO3nX** [staxrip/staxrip#597]
**The bug**
From 2.8.1.5 (not 2.8.1.4) Bitrate Calculation is wrong for x265 (less than before)

**Exemple**
Exemple for a video 54m51s before Staxrip provide 1893 bitrate / 709 Mo (want 995 mo  2 pass with 2 audio EAC3 at 143 mo) target, now Staxrip provide 1805 bitrate / 709 Mo and the final size is less than +30 Mo (676 mo > 709 Mo)

**Comment by Dendraspis** [comment]
Please have a look at the Changelog.
Since v2.1.8.5 StaxRip uses SI prefixes for sizes. The next version lets you choose between SI and IEC prefix.

In the DropBox you can find the latest Hotfix, that includes the feature.

**Comment by PhoO3nX** [comment]
Excuse me but even with the last version [from StaxRip.v2.1.8.5D_Prefix2.zip or from exe file Dropbox] (tools > Settings > user Interface > Use binary prefix MiB the calculation is bad 
StaxRip 2.8.1.4 => 54m51s provide 1893 bitrate / 709 Mo
StaxRip 2.8.1.5 => 54m51s provide 1849 bitrate / 709 Mo so a false / bad size final

Could you explain me if it's this option ? Thanks

**Comment by JJKylee** [comment]
The bitrate unit for `x264` and `x265` is **kilo****_bits_** per second(_kbps_) while file sizes are measured in **_bytes_**.
It is _bytes_ that SI and IEC differ on, _not_ bits. For bits, the SI prefixes are unanimously used. That is, 1 kilobit is 1000 bits.

Therefore, for the same file, the bitrate remains _invariant_ while the file size can be different depending on whether it is denoted in _MB_(Megabytes, SI) or _MiB_(Mebibytes, IEC).

In the same logic, if the target is file size, 800MB and 800MiB can have _different bitrates_ although the nominal value may seem the same.

**Comment by PhoO3nX** [comment]
> The bitrate unit for `x264` and `x265` is **kilo _bits_** per second(_kbps_) while file sizes are measured in **_bytes_**.
> It is _bytes_ that SI and IEC differ on, _not_ bits. For bits, the SI prefixes are unanimously used. That is, 1 kilobit is 1000 bits.
> 
> Therefore, for the same file, the bitrate remains _invariant_ while the file size can be different depending on whether it is denoted in _GB_(Gigabytes, SI) or _GiB_(Gibibytes, IEC).
> 
> In the same logic, if the target is file size, 800MB and 800MiB can have _different bitrates_ although the nominal value may seem the same.

Thanks but i don't ask for the difference between GB/GIB or MB/MIB but i make a mention that the lastest build with "fix" not fixed properly the calculation even with applying the prefix setting. The good calculation & good size is only from 2.1.8.4 (1893 bitrate for a true file 709 when with the fix version 1849 are purposed and create a bad final size with a 2 pass encode. (~692/693Mo instead of 709 mo)

**Comment by 44vince44** [comment]
can you give me the size in bytes of the 693 Mo (Mo in French, MB in English). get that with the right click on the file > properties.

**Comment by PhoO3nX** [comment]
> can you give me the size in **bytes** of the 693 Mo resulting file (Mo in French, MB in English). get that with the right click on the file > properties.

No i have deleted the file. 

But it's not a problem, i will keep the 2.1.8.4.

**Comment by 44vince44** [comment]
OK I am doing some tests. Now you don't have the latest hotfixes. In the latest hotfix, you have Size (MB) and Size (MiB), the MB or MiB appears on the interface. So you don't have latest fixes. In a few minutes, I'll tell you the results of my test.

**Comment by Dendraspis** [comment]
Indeed, there is a problem.  😖

Seemed to be too obvious, but of course the displayed bitrate can not be passed to x265 in both cases. 🙄  

So in that case the displayed bitrate of 1849 is in **Kibps**, in **Kbps** it's about 1895.  

@PhoO3nX 
Good job! 👍

**Comment by 44vince44** [comment]
I took a look using tests, that said the same thing for all codecs tested (x265, x264, NVEnc_h264)

you must do the following:

- When the Binary prefix is selected (MiB): then you must correct the Video_Bitrate CALCULATED value with a factor of 1024
- When the MB mode is selected, then the current calculation is OK, you must change NOTHING!

**Comment by Dendraspis** [comment]
Okay, this one works - at least both settings come up with the same bitrate:
[StaxRip v2.1.8.5D_Prefix3.zip](https://github.com/staxrip/staxrip/files/6162778/StaxRip.v2.1.8.5D_Prefix3.zip)

Just kidding! I've calculated and tested it. If it doesn't work for you, there ***must*** be a conspiracy!  😧

**Comment by 44vince44** [comment]
well as we are investigation another bug introduced by Stax76 I was distracted... so couldn't test yet

**Comment by Dendraspis** [comment]
I have to rework the change - there are really strange things going on.  😕  But at the moment I don't have enough *Voodoo* to compensate.

**Comment by Dendraspis** [comment]
Okay, here is the final fix, sorry you had to wait:  😞 
[StaxRip v2.1.8.5D_Prefix4.zip](https://github.com/staxrip/staxrip/files/6164909/StaxRip.v2.1.8.5D_Prefix4.zip)

*Disclaimer:*
There was no conspiracy! Never! This word don't even exist! And I'm not forced to write that! You can believe me!

**Comment by Dendraspis** [comment]
Just for those who already downloaded my fix:
There was a part from another extension I test with included. So if you plan to use it, you should take **Prefix6** from above where I removed the code.

**Comment by PhoO3nX** [comment]
Good Job guys ! Fully working now :) 👍 

![staxrip2 1 8 5D_prefix6](https://user-images.githubusercontent.com/48757087/111671691-7bf2c600-8819-11eb-9dc6-5ea8bc96cb9a.jpg)

**Comment by 44vince44** [comment]
For future reference, some confusion happened due to the following standards:

- bit rates are always expressed in Kbps and NEVER Kibps (why, because this is how the encoders understand it)
- Size in Staxrip are expressed according to the setting MB or MiB
- Size of files in Windows are expressed in KiB MiB GiB although the "i" is not shown (thankfully the size in bytes is displayed)
