### ISSUE TITLE
Bug with new SAR auto/forced implementation

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#598]
**Describe the bug**

When you set in the main options "Target PAR" to 1, then the SAR "auto" mode does not work well, the switch --sar 1:1 is generated.
If you remove "Target PAR" setting then the sar auto mode works as expected.

**Expected behaviour**

in auto mode for SAR, value 1:1 should NOT generate the switch --sar 1:1, it should generate NO SAR switch at all (because it's auto, not forced) , even if target PAR is set to 1.

**Comment by stax76** [comment]
I designed it to behave like this. 😉 You pick 1:1 in the menu of main dialog or encoder dialog, you get 1:1 in the command line. I think it's fine!

**Comment by 44vince44** [comment]
@stax76 I understand what you did, but I think `auto` should write --sar only if different than 1.
Then why did you create the option `forced` ?

**Comment by stax76** [comment]
> Then why did you create the option forced ?

You have to remember the PAR menu is shared with main dialog and encoder dialog. If choose 1:1 then you get 1:1, what you get with force depends on the source PAR.

You need to choose auto in the main dialog as well and not 1:1

**Comment by 44vince44** [comment]
I understand now that `force` would force the switch --sar 1:1 when the calculated PAR is 1, without being set in the main options.
And when set explicitly to 1 in the main options, then --sar1:1 will be written in `auto` and `force` modes.

Then indeed not a bug.
For reference (anyone reading this): --sar in x265 options is PAR in staxrip's main options.
