### ISSUE TITLE
error while processing .ts file

### ISSUE THREAD

**Issue by egorks** [staxrip/staxrip#599]
see log below - erroring out while trying to convert .ts file. either audio or a container issue... option selected was to copy/mux audio stream, no conversion involved.

`
------------------------- System Environment -------------------------

StaxRip    : 2.1.8.0
Windows    : Windows 10 Enterprise 2004
Language   : English (Switzerland)
CPU        : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
GPU        : NVIDIA GeForce GTX 1080, Citrix Indirect Display Adapter
Resolution : 3840 x 2160
DPI        : 192
Code Page  : 1251

----------------------- Media Info Source File -----------------------

Y:\media\02enc\Police Academy\Police Academy-1.ts

General
ID                       : 1 (0x1)
Complete name            : Y:\media\02enc\Police Academy\Police Academy-1.ts
Format                   : MPEG-TS
File size                : 7.34 GiB
Duration                 : 1 h 32 min
Overall bit rate mode    : Variable
Overall bit rate         : 11.4 Mb/s
Maximum Overall bit rate : 35.5 Mb/s

Video
ID                       : 4113 (0x1011)
Menu ID                  : 1 (0x1)
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : Main@L4
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Format, GOP              : M=4, N=13
Codec ID                 : 27
Duration                 : 1 h 32 min
Bit rate mode            : Variable
Bit rate                 : 10.2 Mb/s
Maximum bit rate         : 40.0 Mb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Interlaced
Scan type, store method  : Separated fields
Scan order               : Top Field First
Bits/(Pixel*Frame)       : 0.197
Stream size              : 6.59 GiB (90%)
Color range              : Full
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio #1
ID                       : 4352 (0x1100)
Menu ID                  : 1 (0x1)
Format                   : AC-3
Format/Info              : Audio Coding 3
Commercial name          : Dolby Digital
Codec ID                 : 129
Duration                 : 1 h 32 min
Bit rate mode            : Constant
Bit rate                 : 192 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 127 MiB (2%)
Language                 : Russian
Service kind             : Complete Main

Audio #2
ID                       : 4353 (0x1101)
Menu ID                  : 1 (0x1)
Format                   : AC-3
Format/Info              : Audio Coding 3
Commercial name          : Dolby Digital
Codec ID                 : 129
Duration                 : 1 h 32 min
Bit rate mode            : Constant
Bit rate                 : 384 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Stream size              : 253 MiB (3%)
Language                 : English
Service kind             : Complete Main

------------------- Error ffmpeg: Re-mux TS to MKV -------------------

ffmpeg: Re-mux TS to MKV returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function

---------------------- ffmpeg: Re-mux TS to MKV ----------------------

C:\Programs\staxrip218\Apps\FrameServer\AviSynth\ffmpeg.exe -probesize 10M -i "Y:\media\02enc\Police Academy\Police Academy-1.ts" -c copy -ignore_unknown -sn -y -hide_banner "Y:\media\02enc\Police Academy\Police Academy-1_temp\Police Academy-1.mkv"

[h264 @ 0000018ac78256c0] Increasing reorder buffer to 2
Input #0, mpegts, from 'Y:\media\02enc\Police Academy\Police Academy-1.ts':
  Duration: 01:32:20.03, start: 600.000000, bitrate: 11376 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x1100](rus): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:2[0x1101](eng): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 384 kb/s
Output #0, matroska, to 'Y:\media\02enc\Police Academy\Police Academy-1_temp\Police Academy-1.mkv':
  Metadata:
    encoder         : Lavf58.65.100
    Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuvj420p(pc, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 90k tbc
    Stream #0:1(rus): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 0000018ac7fbf040] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0000018ac7fbf040] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
video:64kB audio:1kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

---------------------- ffmpeg: Re-mux TS to MKV ----------------------

C:\Programs\staxrip218\Apps\FrameServer\AviSynth\ffmpeg.exe -probesize 10M -i "Y:\media\02enc\Police Academy\Police Academy-1.ts" -c copy -ignore_unknown -sn -y -hide_banner "Y:\media\02enc\Police Academy\Police Academy-1_temp\Police Academy-1.mkv"

[h264 @ 0000018ac78256c0] Increasing reorder buffer to 2
Input #0, mpegts, from 'Y:\media\02enc\Police Academy\Police Academy-1.ts':
  Duration: 01:32:20.03, start: 600.000000, bitrate: 11376 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x1100](rus): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:2[0x1101](eng): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 384 kb/s
Output #0, matroska, to 'Y:\media\02enc\Police Academy\Police Academy-1_temp\Police Academy-1.mkv':
  Metadata:
    encoder         : Lavf58.65.100
    Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuvj420p(pc, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 90k tbc
    Stream #0:1(rus): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 0000018ac7fbf040] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0000018ac7fbf040] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
video:64kB audio:1kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Start:    01:05:04
End:      01:05:05
Duration: 00:00:00

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: ffmpeg: Re-mux TS to MKV returned error exit code: 1 (0x1)

It's unclear what the exit code means, in case it's a Windows system error then it possibly means:

Incorrect function

---------------------- ffmpeg: Re-mux TS to MKV ----------------------

C:\Programs\staxrip218\Apps\FrameServer\AviSynth\ffmpeg.exe -probesize 10M -i "Y:\media\02enc\Police Academy\Police Academy-1.ts" -c copy -ignore_unknown -sn -y -hide_banner "Y:\media\02enc\Police Academy\Police Academy-1_temp\Police Academy-1.mkv"

[h264 @ 0000018ac78256c0] Increasing reorder buffer to 2
Input #0, mpegts, from 'Y:\media\02enc\Police Academy\Police Academy-1.ts':
  Duration: 01:32:20.03, start: 600.000000, bitrate: 11376 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x1100](rus): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:2[0x1101](eng): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 384 kb/s
Output #0, matroska, to 'Y:\media\02enc\Police Academy\Police Academy-1_temp\Police Academy-1.mkv':
  Metadata:
    encoder         : Lavf58.65.100
    Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuvj420p(pc, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 90k tbc
    Stream #0:1(rus): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 0000018ac7fbf040] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0000018ac7fbf040] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
video:64kB audio:1kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 374
   at StaxRip.CommandLineDemuxer.Run(Project proj) in D:\Projekte\VB\staxrip\General\Demux.vb:line 161
   at StaxRip.MainForm.Demux() in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 3341
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 2148
`

**Comment by stax76** [comment]
It's a ffmpeg issue, not a staxrip issue, it happens only with certain types of TS files.

@44vince44 wrote a guide this week:

https://github.com/staxrip/staxrip/wiki/How-to-handle-.ts-and-.m2ts-files-in-StaxRip

**Comment by JJKylee** [comment]
You're using 2.1.8.0, @egorks.
Don't forget that it is always recommended to use the most recent beta when reporting an issue.
The current beta is 2.1.8.5.

**Comment by egorks** [comment]
thanks! 2 way it has been circumvented -  changing extension to .m2ts as well as ffmpeg preprocessing options.

thanks for quick reaction!
