### ISSUE TITLE
Update x265 options

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#60]
For the x265 encoder, the loop filters section requires a drop-down list for the --selective-sao option with the values 0-4. Or an alternative. See here:

https://forum.doom9.org/showthread.php?p=1885163#post1885163

https://x265.readthedocs.io/en/default/cli.html#cmdoption-selective-sao

**Comment by stax76** [comment]
I've added a numeric up down, there are no captions available for a dropdown.

**Comment by Patman86** [comment]
New x265 wolfberry build available

https://github.com/staxrip/staxrip/issues/58
