### ISSUE TITLE
Log in destination dir

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#601]
Sometimes I do runs of multiple scripts for the same video file, to compare final outcome, speed, etc.

I know that asking to rework the job and log window would be time consuming so, instead, would it be possible to save the individual log files into the destination file directory instead of the Logs directory in StaxRip settings?

**Comment by JJKylee** [comment]
You just need to adopt _different target file names_.

If you set `Tools` > `Settings` > `System` > `Delete temp files` to `Disabled`, you'll have respective log files in the `%temp_dir%` as long as the source file name remains the same.

IMO, this is a matter of usage, not something to be asked for.

**Comment by tormento** [comment]
> IMO, this is a matter of usage, not something to be asked for.

I know there is a copy in the %temp_dir% and it's a copy of the same log in the Logs dir.

I am simply asking to put that file in the same directory of the output video.

**Comment by 44vince44** [comment]
you have a copy of all the logs with a timestamped prefix in the settings\logs folder...

**Comment by JJKylee** [comment]
Do you scatter the output videos here and there to folders other than the `%target_dir%`? Your feature request of putting the log file alongside the output file may come in handy in that use case.

But in most cases where all the output files are put in the _same_ folder as the source file or the _same_ `%target_dir%`, you just need to copy the log files from `%temp_dir%` to its parent directory or to the `%target_dir%` if `%target_dir%` or `%temp_dir%` is customized in `Options` > `Paths` > `Default Target Folder`/`Temp Files Folder`.

As for me, I don't see any value in your request, but the decision is up to our coders as always. 😆

**Comment by 44vince44** [comment]
you can create an event command to automatically do so.
@stax76 knows how to do it. I dunno how to do it.
how do we write an event command that copies the log file to target_dir when job is finished ?

**Comment by JJKylee** [comment]
This _Event Command_ item seems to work OK:

![StaxRip_2 1 8 5_Event-Command_copy-target-file-log-to-target-folder_20210317](https://user-images.githubusercontent.com/3157518/111556853-b6406280-8748-11eb-82f9-2da682e958a7.jpg)

Script Code: `copy "%target_temp_file%_staxrip.log" "%target_dir%"`

**Comment by 44vince44** [comment]
that was quick!

**Comment by 44vince44** [comment]
@tormento has this answered your request ? please close the thread if so.

**Comment by JJKylee** [comment]
Due to internal code change, this _Event Command_ item should be modified as follows in v2.3.0.

![StaxRip_2 3 0_Event-Command_change_20210328](https://user-images.githubusercontent.com/3157518/112772641-c7119380-8fe6-11eb-8eb0-c59f5fccf9e2.jpg)

**Comment by stax76** [comment]
I've renamed several commands and implemented a much better method to ensure backward compatibility, it automatically corrects the settings structure. There is no action required from users, and it won't reset settings, it only corrects settings.

https://github.com/staxrip/staxrip/blob/master/Source/General/ApplicationSettings.vb#L340
