### ISSUE TITLE
Wrong shortcuts in Processing... window

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#602]
When you push the lower arrow on the right of the Processing... window, some shortcut appears.

The two, objects of the issue, are _Output Highlighting_ **O** and _Process Reformatting_ **P**.

Both work with lower **o** and **p** but not with upper **O** and **P**.

That is not only non functional but confusing too. Better to use **o** and **p** as showed shortcuts or accept both lower and upper cases for alphabetical shortcuts.

P.S: Perhaps that behaviour is for all the alphabetical shortcuts of StaxRip. I tried the only two I am using now as encoding.

**Comment by JJKylee** [comment]
Isn't it just a notational custom?

For example, the shortcut `Ctrl+V` doesn't mean that the user should press `Ctrl`, **`Shift`**, and `v` concurrently.

I don't think this is an issue. 🤔

**Comment by Dendraspis** [comment]
Indeed, this is a standard and is used by (almost?) every app. 😊
