### ISSUE TITLE
Nvenc VBR Quality comma bug

### ISSUE THREAD

**Issue by JibsouX** [staxrip/staxrip#604]
Hello, I come to report a bug in nvenc for the VBR Quality, namely: the parameter does not work with a comma but a point.

Not good : 26,0
Good : 26.0

this problem prevents to use the numbers after the comma because not understood by the encoder (26.5 for example)

Thanks in advance !

**Comment by JJKylee** [comment]
It's related to the system locale. Some European countries use `,` in place of `.`(decimal point).
Check out your locale and report with detailed info like log, your environment, StaxRip version, etc.

**Comment by Dendraspis** [comment]
And where is this value entered?  *VBR Quality* means Bitrate and *CQP* only offers numbers without comma/point, too.  🤨

**Comment by JibsouX** [comment]
> It's related to the system locale. Some European countries use `,` in place of `.`(decimal point).
> Check out your locale and report with detailed info like log, your system environment, StaxRip version, etc.

Indeed i'm on a french windows version..

**Comment by JibsouX** [comment]
> And where is this value entered? _VBR Quality_ means Bitrate and _CQP_ only offers numbers without comma/point, too. 🤨

Here :)
[](https://zupimages.net/up/21/11/es2z.png)

**Comment by Dendraspis** [comment]
Changing the system locale settings is the wrong way.

I'll fix it...

**Comment by Dendraspis** [comment]
@JJKylee 
You're right, that this is a locale setting, but StaxRip has to convert it for the command line. Otherwise almost nobody would use it.  😁 

Here is the fix:
[StaxRip v2.1.8.5D_NVEnc.zip](https://github.com/staxrip/staxrip/files/6167450/StaxRip.v2.1.8.5D_NVEnc.zip)

**Comment by JibsouX** [comment]
thanks it work i can change the default comma by a simple dot it's not replace by staxrip.
the only thing here with this fixed version is that staxrip is broken:
- no more saved settings, they are in a backup folder
- staxrip is black . MDR

[SCREENSHOT](https://zupimages.net/up/21/11/74ox.png)

**Comment by JJKylee** [comment]
> thanks it work i can change the default comma by a simple dot it's not replace by staxrip. (by default there is still a comma not a dot)

Plz show us where.

> * no more saved settings, they are in a backup folder

This is a major change in 2.1.8.5, and it was inevitable to fix a critical issue.

> When a video encoder default value was changed, a compatibility issue with old settings was happening, this is finally fixed, but could only be achieved by resetting all video encoder options (stax76, #546)

You need to restore your profiles _manually_ referring to the ones saved in the `Backup` category. It's annoying, but you can't help it. 😓

> * staxrip is black . MDR

This is a new change introduced in the _next_ release.

> Set "Dark | Blue" as default theme.

You're seeing it because your binary is a hotfix version. 😉

**Comment by Dendraspis** [comment]
> thanks it work i can change the default comma by a simple dot it's not replace by staxrip. (by default there is still a comma not a dot)

In the Edit Box this is intended and it has to be used, but in the command line below there is a dot now.


@JJKylee 
Thanks.  😊
