### ISSUE TITLE
2.1.8.5: In NVEnc --vbr-quality should be hidden in command line if Constant Quality Mode is off in VBR/VBRHQ

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#605]
In NVEnc, `--vbr-quality` is supposed to work only when `-vbr`(VBR mode) or `-vbrhq`(VBRHQ mode) is set to `0`. In the GUI, this is enabled by ticking `Constant Quality Mode` on.

But `--vbr-quality` option should be _hidden from the command line_ when the bitrate is _explicitly_ set by ticking `Constant Quality Mode` off.

(See [this part](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vbr-int) in NVEnc online help.)

Unfortunately, 2.1.8.5 fails to do so. See this screenshot:

![StaxRip_2 1 8 5_NVEnc_--vbr-quality_issue_20210318](https://user-images.githubusercontent.com/3157518/111732394-9ab18680-8832-11eb-8b2a-92a881fc1732.gif)

As a result, the final bitrate of the encoded video stream becomes _significantly different_ from the set value.

I believe we need to fix this.

**Comment by Dendraspis** [comment]
> I believe we need to fix this.

The best summary ever!  😂

I'll have a look at it and hope it's easy to fix.

**Comment by Dendraspis** [comment]
...and here it is:  🙂 
[StaxRip v2.1.8.5D_NVEnc2.zip](https://github.com/staxrip/staxrip/files/6169770/StaxRip.v2.1.8.5D_NVEnc2.zip)

**Comment by JJKylee** [comment]
![StaxRip v2 1 8 5D_NVEnc2 zip_virus_warning_2_20210319](https://user-images.githubusercontent.com/3157518/111762342-28ef3200-885e-11eb-992e-2640a01d09f8.jpg)

![StaxRip v2 1 8 5D_NVEnc2 zip_virus_warning_20210319](https://user-images.githubusercontent.com/3157518/111762367-2ee51300-885e-11eb-98b2-824a26d2f9d5.jpg)

Windows Defender DOES SUCK!!!

It forces me to restart. 😢 These MS guys should go to hell!!!!!!

**Comment by Dendraspis** [comment]
That's why my Windows Defender is turned off permanently.  😁 

But annoying why it pops up now.  🤨

**Comment by JJKylee** [comment]
What's even worse is that after the 20H2 update, users can't ignore Defender's false detection.
They MUST restart. Shoooooot!!!!

**Comment by JJKylee** [comment]
BTW, this issue is fixed in your hotfix.
Thanks. 👍

**Comment by Dendraspis** [comment]
> What's even worse is that after the 20H2 update, users can't ignore Defender's false detection.

**OMG!**  Another reason for me to let it disabled.   🤮  🤮  🤮

**Comment by 44vince44** [comment]
Create an exception.
Strange thing, my Windows Defender has never done this to me...

**Comment by JJKylee** [comment]
Maybe Windows Defender has an issue with [this anti-ransomware](https://www.checkmal.com/product/appcheck/?lang=en) installed in my system. I just registered its data folder in the exception list. Hope this problem does not occur again. 😞
