### ISSUE TITLE
Audio Bitrate not correct unless you open and close audio encoder settings

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#608]
**Context of the bug**
This bug happens when you are using an encoder like AAC (qaac), with channels settings to "original", set in template or before loading the source file.

**Description of the bug**
The Audio Bitrate that is displayed in the target section shows the estimate for a 6+ channel encode, REGARDLESS of source number of channels
But, it you open and close the Audio Encoder Settings, and press OK to close it, then the Audio Bitrate estimation is correct.

**Expected behavior**
The audio estimation should be correct without open and close the Audio Encoder Settings

**How to reproduce the issue**

Step 0: chose a file file a 2 channel audio track

Step 1: before dropping the file, set your AAC qaac encoder like this

![SNAG-0000](https://user-images.githubusercontent.com/17828567/111866451-2ed83680-8976-11eb-9304-b74acd6003ee.jpg)

At this stage it is NORMAL that audio bitrate is estimated 290, because no file has been dropped.
Close the Audio Encoder Settings by pressing button OK.

Step 2: drop your 2 channel audio file

![SNAG-0001](https://user-images.githubusercontent.com/17828567/111866491-7fe82a80-8976-11eb-9d1a-7d039e35c536.jpg)

The Audio Bitrate is still 290. This is NOT NORMAL because it should detect at this stage, without any further steps, that the channels number is 2 and that it is not a bitrate of 290.

Step 3: Open the Audio Settings

![SNAG-0002](https://user-images.githubusercontent.com/17828567/111866521-c178d580-8976-11eb-87ec-94c9c2f158b9.jpg)

Step 4: Press OK to close it

![SNAG-0003](https://user-images.githubusercontent.com/17828567/111866531-d2294b80-8976-11eb-84b3-2bf0c2e99c04.jpg)

NOW the audio bitrate is correct, but we had to open and close audio settings for that, which is acceptable for a drop operation, but leads to miscalculations is doing batch encodes with video encoding modes where video bitrate will be calculated for a requested file size.

**Comment by 44vince44** [comment]
This example shows the consequences for a 2 pass encode (same audio settings as the one before)

A) Here are the audio settings BEFORE dropping the file

![SNAG-0000](https://user-images.githubusercontent.com/17828567/111867163-0141bc00-897b-11eb-8a71-8ac8e82fe4f0.jpg)

Everything is normal at this stage

B) Here are the target values when we drop the files

![SNAG-0003](https://user-images.githubusercontent.com/17828567/111867182-16b6e600-897b-11eb-8f53-d6109c6bce31.jpg)

The value 290 for Audio Bitrate is NOT NORMAL !!!

C) here are the target values after open-close the Audio Settings

![SNAG-0005](https://user-images.githubusercontent.com/17828567/111867205-364e0e80-897b-11eb-8304-dff7682331e5.jpg)

Now the target Audio Bitrate is correct, but it required that the user open/closes Audio settings without modding anything. This is not good...

**Comment by JJKylee** [comment]
I thought it was normal thinking that bitrate calculation is always incorrect with quality encoding. But if the bitrate becomes different _by simply opening/closing the `Audio Settings` window_, then it must be an issue.

I couldn't find it because I never do a target size encoding. 🤣 Good find, @44vince44.

**Comment by 44vince44** [comment]
Thanks @JJKylee I never do target size encoding either, but lately we have been debugging those, with @Dendraspis ...

**Comment by Dendraspis** [comment]
@JJKylee 
 😡  Stop encouraging him!   😁 

@44vince44 
This was a tough one!  😒  

But here is the fix:
[StaxRip v2.1.8.5D_AudioBitrate.zip](https://github.com/staxrip/staxrip/files/6175703/StaxRip.v2.1.8.5D_AudioBitrate.zip)

**Comment by 44vince44** [comment]
small exception that leads to a crash, when there is an audio track selected, and you set to No Audio
😕 
sorry...

**Comment by JJKylee** [comment]
Well, I tried a target size encoding with [this sample](https://drive.google.com/file/d/1vTzpVTEojE0R0FeUOxK6iBYx7japf-7B/view?usp=sharing).

Size in MiB: 10
qaac 2 channels quality 62 (pipe) ⇨ calculated bitrate 128
The calculated video bitrate ⇨ 684
So I set NVEnc `--vbr 684` and `--preset P7 --multipass 2pass-full` with `H265`.

Result:
Size size: 6.16 MiB
Video bitrate: 408 kbps
Audio bitrate: 89.6 kbps

Hahaha... 🤣

I understand `qaac` can be incorrect in the output bitrate since `--tvbr` is a _quality_ mode per se.
But isn't `NVEnc` too much considering `--vbr 684` is a bitrate mode, not a quality mode? 😞

It seems that fixing this issue on StaxRip is meaningless unless the encoders themselves produce the expected results in target size encoding. 😅

> small exception that leads to a crash, when there is an audio track selected, and you set to No Audio

Yeah.

![StaxRipv2 1 8 5D_AudioBitrate_No-Audio_error_20210320](https://user-images.githubusercontent.com/3157518/111874141-038f2080-8951-11eb-8006-3bd81aee5353.jpg)

**Comment by Dendraspis** [comment]
I've tested it with multiple sources, but it seems professional beta testers have better test files.  😂 

Please check this version, it must work (even for you 😁  ):
[StaxRip v2.1.8.5D_AudioBitrate2.zip](https://github.com/staxrip/staxrip/files/6175842/StaxRip.v2.1.8.5D_AudioBitrate2.zip)

**Comment by Dendraspis** [comment]
> Size in MiB: 10
> qaac 2 channels quality 62 (pipe) ⇨ calculated bitrate 128
> The calculated video bitrate ⇨ 684
> So I set NVEnc `--vbr 684` and `--preset P7 --multipass 2pass-full` with `H265`.
> 
> Result:
> Size size: 6.16 MiB
> Video bitrate: 408 kbps
> Audio bitrate: 89.6 kbps
> 
> Hahaha... 🤣

But StaxRip should calculate a higher video bitrate:

<img src="https://user-images.githubusercontent.com/50659978/111875161-a4ed9500-8998-11eb-8f8e-e562b94daad2.PNG">

> I understand `qaac` can be incorrect in the output bitrate since `--tvbr` is a _quality_ mode per se.
> But isn't `NVEnc` too much considering `--vbr 684` is a bitrate mode, not a quality mode? 😞

Don't ask us, because the parameter was set properly.  😁 

> It seems that fixing this issue on StaxRip is meaningless unless the encoders themselves produce the expected results in target size encoding. 😅

😄 

> > small exception that leads to a crash, when there is an audio track selected, and you set to No Audio
> Yeah.

Thanks.  🙂

**Comment by JJKylee** [comment]
1. No crash with no audio. ⇨ ☑

To treat the original issue fairly, I re-encoded the one audio track sample to a _stereo_ version: [here](https://drive.google.com/file/d/1xqIx3eNNsqdEwnA-3jWKw1p0dN7I9Obo/view?usp=sharing).

2. The original issue of different bitrates for a stereo audio track before/after opening the `Audio Settings` window for `qaac` `--tvbr`.  ⇨ fixed. ☑

3. But still `NVEnc` does _not_ work as expected in the target size mode even with _**audio copy**_:

```
--vbr 724 --codec h265 --preset default
```

yields an output bitrate ⇨ 428 kbps 🤣

Yeah, this is absolutely a tool issue. 😂
