### ISSUE TITLE
SVT encoders

### ISSUE THREAD

**Issue by kleytr6s** [staxrip/staxrip#61]
Do you plan on adding the SVT-AV1, SVT-X265 encoders? They are Intel versions that are faster.

**Comment by stax76** [comment]
Only if it's a popular request.

**Comment by stax76** [comment]
Please note that staxrip still has full support for a generic command line encoder, the xvid encoder is based on that so you can clone and modify the xvid encoder to get your SVT encoder.

We will add an SVT GUI encoder only if few people request it, otherwise it would be a waste of time.

**Comment by zemanyak** [comment]
I'd love that too ! There are not many GUIs that support them so far. Staxrip is my favorite GUI because it's easy to use, very customable and supports many codecs. If you could add STV-AV1, SVT-HEVC, SVT-VP9 and libaom, it would be great : one GUI to command them all ! Also, this is certainly something that will be more and more used in the future so it will make Staxrip future-proof.

**Comment by stax76** [comment]
I wanted to start working on SVT-AV1 support but then I saw pipe input might not be stable, so I wait until that is solved.

https://github.com/OpenVisualCloud/SVT-AV1/issues/676

**Comment by Patman86** [comment]
I think SVT-AV1 is still in the test phase and still has some bugs / problems. If these are fixed, SVT-AV1 can also be included as a plugin in FFMPEG, but at the moment there are still some conflicts with other libs.

**Comment by stax76** [comment]
I already tried it and couldn't get pipe input working because undocumented and y4m not being supported.

**Comment by Patman86** [comment]
I've read something about using yuv to pipe files.

**Comment by Patman86** [comment]
Hello Stax,

I got it. Piping works fine with the following command line:

```
C:\WINDOWS\system32>F:\VideoProgz\Staxripx64\Apps\Encoders\ffmpeg\ffmpeg.exe -loglevel fatal -hide_banner -i E:\x264\test\00009_temp\00009.avs -nostdin -f rawvideo -pix_fmt yuv420p - | F:\VideoProgz\Staxripx64\Apps\Encoders\SVT-AV1\SvtAv1EncApp.exe -i stdin -n 2183 -w 720 -h 400 -q 21 -b E:\x264\test\00009_temp\00009_out.bin
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.7.0
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Sep 26 2019 23:51:25
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 72
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 720 / 400
SVT [config]: FrameRate / Gop Size                                              : 30 / 32
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 21 / 33 / 0
-------------------------------------------
Encoding      2000
Average System Encoding Speed:        50.80
     2183
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
        2183            30.00 fps                 12939418              1422.57 kbps


Channel 1
Average Speed:          53.045 fps
Total Encoding Time:    41154 ms
Total Execution Time:   41317 ms
Average Latency:        1378 ms
Max Latency:            2232 ms
Encoder finished
```

**Comment by stax76** [comment]
Hello Patman86,

nice find, at the moment I'm not working much on staxrip but this will probably be one of the first items when development continues.

**Comment by megapro17** [comment]
Any news about this? I found empty svt-av1 folder in staxrip 2.0.8.0
