### ISSUE TITLE
Three pass encodings, pass 3 before 2?

### ISSUE THREAD

**Issue by tkozybski** [staxrip/staxrip#611]
I was doing some test encodes and I noticed that --pass 3 is called before --pass 2 in the encoder(s). And I see this in the code:

```
ElseIf Params.Mode.Value = x264RateMode.ThreePass Then
    'Specific order 1 > 3 > 2 is correct!
    Encode("Video encoding Nth pass", GetArgs(3, p.Script), s.ProcessPriority)
    Encode("Video encoding last pass", GetArgs(2, p.Script), s.ProcessPriority)
End If
```

Why is it correct? It makes no sense to me to call it in that order. 2nd pass should be the Nth pass here.

**Comment by JJKylee** [comment]
Yeah, it's really confusing.
See here: #389.

**Comment by tkozybski** [comment]
I see it now. I'm closing the issue then. Man, the parameters for those encoders really confuse me sometimes.
