### ISSUE TITLE
ffmpeg_x265_quality-1

### ISSUE THREAD

**Issue by VEGAX265** [staxrip/staxrip#614]
What does the -1 quality when using ffmpeg profile with x265 encoder really mean quality wise compared to the regular x265 scale?
![ffmpeg_x265_quality-1](https://user-images.githubusercontent.com/44779244/111937716-bc16aa80-8a9e-11eb-8375-23766a1e881b.png)

**Comment by 44vince44** [comment]
I think it means the default quality. Maybe it is 28. If you do an encode you can know by comparing...
But you shouldn't use FFMPEG x265 because you have in staxrip direct x265 which is better, at all levels!

**Comment by Dendraspis** [comment]
**Quality** is used for multiple settings, depending on the selection above. So maybe there is one parameter that takes `-1`.  Using it with x265 in quality mode, `-crf -1` could cause an error.

**Comment by 44vince44** [comment]
No : when you select -1 it DOES NOT set `-crf -1`
**It simply doesn't set the switch -crf**
So the default quality is used, and the default, in x265 is 28.
