### ISSUE TITLE
Option to ignore chapters

### ISSUE THREAD

**Issue by dustsigns** [staxrip/staxrip#616]
**Is your feature request related to a problem? Please describe.**
I try to encode MKV files which have incorrect chapter information in them. I would like to ignore this chapter information, but StaxRip currently adds it automatically.

**Describe the solution you'd like**
I would like to have a template option or a setting allowing me to ignore chapters, i.e., that chapters are not added automatically.

**Describe alternatives you've considered**
I can remove the chapter (XML) file from the container options manually, but I need to do this manually for every file.

**Explain why the feature matters to you**
The manual removal of the chapter file from the options settings is tedious. I cannot use any batch processing for now because I need to remove the chapter (XML) file for every encoded file.

**Additional context**

![grafik](https://user-images.githubusercontent.com/11800082/111967768-b948a380-8af8-11eb-8b33-4f3c74fd90ae.png)

**Comment by stax76** [comment]
You can find this setting in the Preprocessing section of the settings dialog.

**Comment by 44vince44** [comment]
Maybe we should do a guide for that, it's a recurring question 🤣

**Comment by JJKylee** [comment]
@44vince44, I saw it. 👍

BTW, when you make another one regarding this matter, you may use this screenshot. 😁

![StaxRip_2 1 9 0_mkvextract_chapters-demuxing_20210322](https://user-images.githubusercontent.com/3157518/111989484-10d21980-8acf-11eb-96c0-9170a70d5e04.jpg)

**Comment by 44vince44** [comment]
I will, this evening!

**Comment by 44vince44** [comment]
@dustsigns next build will have option to demux chapters available in the projects options (exactly as demux subtitles and audio), and not the settings anymore.
