### ISSUE TITLE
Jump to option settings clicking on command line preview

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#617]
Would it be possible to jump to the correct Options window setting when clicking the corresponding switch in the command line preview? Sometimes StaxRip automatically changes encoder options according to source and not always I remember where they are.

**Comment by 44vince44** [comment]
type them in the search box

**Comment by Dendraspis** [comment]
...or use right-click and ***seach [parameter]***.

**Comment by stax76** [comment]
You can also right-click the switch in the command line preview, there is a menu item to find the corresponding page and control.

**Comment by tormento** [comment]
Thanks! Anyway clicking would be nice ;)

**Comment by 44vince44** [comment]
@stax76 the feature you implemented is nice, but causes problems when you want to select and copy part or all the command line options.
Could it be fixed but using a modifier like Ctrl+click instead of click ?

**Comment by JJKylee** [comment]
Ditto.

When I try selecting, the selection disappears right away.

I can still copy the _whole_ command line, but in lots of cases I just need only some part of it.
With the new feature, I can do that only by opening the right-click console help window. But still, selection of the set values is not possible.

**Comment by stax76** [comment]
I don't know if using a modifier key is more convenient than the context menu, but building that is likely simple, so I can do that. In the menu at the bottom this feature can be disabled. Selecting does not work because it looses focus to the search field, but it could certainly be implemented in a way that loosing focus will not happen and selecting text is possibly, I can do that tomorrow.

**Comment by stax76** [comment]
A fix for the focus issue is online.

**Comment by JJKylee** [comment]
[This fix](https://github.com/staxrip/staxrip/commit/932a920ac807c8171eca3eaf702a8feccce73e85) is what I desired.

Now selection _by drag_ does not lose focus, and I can still go to the UI part _with a single click_ on the parameter name.

I can see a new option `Preview Mouse-Up Search` in the bottom command line preview settings. 👍

**Comment by Dendraspis** [comment]
Oh yeah, a lot better now.  👍

**Comment by 44vince44** [comment]
Works perfectly !!! well done 👍🏼
