### ISSUE TITLE
Aspect ratio squished vertically

### ISSUE THREAD

**Issue by Xarano-GIT** [staxrip/staxrip#618]
Hi,

Im not sure if this is a problem with my source media, or with StaxRip.

I have a media file I am trying to encode into x265, but the aspect ratio is being squished slightly vertically.

Media Info reports below for the file:
```
Stored_Width                    : 720
Sampled_Width                   : 708
Sampled_Height                  : 480
Pixel aspect ratio              : 0.904
Display aspect ratio            : 1.333
Display aspect ratio            : 4:3
```

After encoding into x265, I'm getting the below:
```
Stored_Width                    : 712
Sampled_Width                   : 708
Sampled_Height                  : 480
Pixel aspect ratio              : 0.909
Display aspect ratio            : 1.341
Display aspect ratio            : 4:3
```

In the source box, I have set PAR 10:11, DAR 1.333333 as this is what it sets automatically.
I do not have the resize filter enabled, although the resize box is telling me i have a 10.63% error?
![image](https://user-images.githubusercontent.com/45671929/112043858-051f3b00-8b41-11eb-8cbe-dc0f1f20a904.png)

The strangest thing about this all however is when I take a screen capture using VLC of the videos.

```
Source image resolution: 708x531
Encoded image resolution: 708x528
```

I don't understand why both the source and encoded files have completely different vertical resolution to what Media Info reports.

If anyone can shed some light into what the problem is, and perhaps how I can fix it, that would be awesome!

Thanks!

**Comment by 44vince44** [comment]
OK I can help you with that.
- what version of Staxrip are you using ?
- if this is not the first  time you download staxrip, did you use settings from a previous version ?
- please check that the crop filter has not been activated. If it has, then untick it 
- in all cases, if you can give us the complete log of the operation, it could help understanding what happened...

**Comment by Dendraspis** [comment]
I guess it has to do something with the auto-crop-correction. 531px are unusual and not ***Mod 8*** (the default), but `528 / 8 = 66` is.

**Comment by Xarano-GIT** [comment]
> OK I can help you with that.
> 
> * what version of Staxrip are you using ?
> * if this is not the first  time you download staxrip, did you use settings from a previous version ?
> * please check that the crop filter has not been activated. If it has, then untick it
> * in all cases, if you can give us the complete log of the operation, it could help understanding what happened...

Heya!

I'm using the latest v2.1.9.0 Beta,
It is the first time I've ever used StaxRip, so no previous version.
Crop and resize filters are both disabled.
Log:
[2021-03-22 - 23.18.14 - Dragon Ball Z 001 stax 2.mkv_staxrip.log](https://github.com/staxrip/staxrip/files/6185831/2021-03-22.-.23.18.14.-.Dragon.Ball.Z.001.stax.2.mkv_staxrip.log)

**Comment by Xarano-GIT** [comment]
While waiting for the encode to finish and generate the log, I was reading a PDF made by the guys who made the original videos im trying to encode.

https://dombito.github.io/mergeproject/R1R2.pdf

They state in this that instead of using a PAR of 10:11, they use a PAR of 160:177.

I've tried typing a manual PAR of 160:177, but it changes back to 10:11

**Comment by Xarano-GIT** [comment]
Awesome, so I noticed that it was parsing the --sar 10:11 command into x265.

I replaced it with --sar 160:177 in the custom box and can see that the output file now correctly sets to 708x531!
