### ISSUE TITLE
update NVEncC options

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#62]
Hi,

based on these issues
http://forum.doom9.org/showthread.php?p=1885349#post1885349
http://forum.doom9.org/showthread.php?p=1885356#post1885356

for each encoding mode must be the possibility to change the bitrates. Look here

https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#encode-mode-options
or here
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vbr-quality-float

For CQP mode create a checkbox with titele "advanced settings". That activated checkbox will show us the three QP's (I, B, P) and without activated checkbox only QP is shown.

Default bitrate for all other modes is 7500 kbps. 

The --vbrhq 0 --vbr-quality <float> is a special case. Only with "0" after --vbrhq the additional option --vbr-quality <float> must be genertated.

Partially, really crazy options in NVEncC.

**Comment by stax76** [comment]
> for each encoding mode must be the possibility to change the bitrates. Look here

Right now the bitrate is always taken from the main dialog, it's difficult to tell if that is sufficient.

> For CQP mode create a checkbox with titele "advanced settings". That activated checkbox will show us the three QP's (I, B, P) and without activated checkbox only QP is shown.

I've added it.

> The --vbrhq 0 --vbr-quality is a special case. Only with "0" after --vbrhq the additional option --vbr-quality must be genertated.

I've added the possibility to choose 0 as bitrate in the main dialog and I've sent rigaya a mail to be sure there are no other use cases.

**Comment by ZeroCool22** [comment]
> 
> 
> > for each encoding mode must be the possibility to change the bitrates. Look here
> 
> Right now the bitrate is always taken from the main dialog, it's difficult to tell if that is sufficient.
> 
> > For CQP mode create a checkbox with titele "advanced settings". That activated checkbox will show us the three QP's (I, B, P) and without activated checkbox only QP is shown.
> 
> I've added it.

Where is the "Advanced Settings" in CQP? i don't see it...

![Screenshot_11](https://user-images.githubusercontent.com/13344308/65652480-52702a00-dfe8-11e9-9c9c-cff10494e539.png)

I'm using StaxRip-x64-**2.0.4.4-beta**

**Comment by Patman86** [comment]
The option will be released with next beta or final version.

**Comment by stax76** [comment]
@Patman86 

I've changed it now so --vbr-quality is only visibly for mode --vbr and mode --vbrhq, can you confirm that it works only with --vbrhq and not with --vbr ? I can't try myself because my GT 1030 don't support nvenc and I don't want to buy a new card, I'm not encoding nor gaming.

What I also did:

The default for --vbr-quality is -1 meaning it's disabled and the bitrate of the main dialog is used, if it's higher than -1 than the value is shown and the bitrate is set to 0.

If you have Visual Studio 2019.3 installed, maybe you can try if it's fine now.

**Comment by Patman86** [comment]
I'll have a look at it and give you feedback.

**Comment by Patman86** [comment]
_Update:_

I think it's not really useful to get the video bitrate from the main, because if you configure your encoding settings, it will help a lot if all the options are shown in the settings. If it's possible, add a checkbox for the modes cbr, cbrhq, vbr and vbrhq with title "Custom Bitrate". If the checkbox is disabled, just use the default settings. In the code then the following part: "& p.VideoBitrate" [Line](https://github.com/staxrip/staxrip/blob/ef70729001e7a1dc50e6c8652a07104d301e38db/Encoding/NVEnc.vb#L795) must be removed.

If the checkbox is activated, a field should appear in which you can enter the bitrate and this is used. For mode vbrhq add a second checkbox with title "Constant Quality Mode". If second box is activated the bitrate is set to 0. Only with bitrate like 0 the "Constant Quality Mode" works, with an other bitrate the option --vbr-quality set target quality when using VBR mode. So --vbr-quality works also with mode vbr but not as "Constant Quality Mode".

I'll test a little further and add more additions, if necessary :)

**Comment by Patman86** [comment]
I made some test with different settings in vbr and vbrhq. Here are my results:

[comparison.txt](https://github.com/staxrip/staxrip/files/3671967/comparison.txt)

**Comment by stax76** [comment]
I've added a new mode:

"VBR HQ - Variable Bitrate HQ - Quality Mode"

I don't know if it's better or worse than a checkbox.

I don't know if it's a good idea to allow to edit the bitrate in the encoder options, it could be but might be difficult to find out how exactly it's supposed to work. How does it interact with the bitrate in the main dialog and how does it interact with the profile settings. Will it be intuitive to use.

**Comment by Patman86** [comment]
All of that are ideas. No need 😉
The usage of the options in the right way is important.

**Comment by stax76** [comment]
I've just committed the change with the 'Constant Quality Mode' checkbox, I hope it's fine now.

**Comment by Patman86** [comment]
Your changes look good. I will test it later.

**Comment by ZeroCool22** [comment]
> 
> 
> I've just committed the change with the 'Constant Quality Mode' checkbox, I hope it's fine now.

I don't see it, it's on the last BETA **StaxRip-x64-2.0.4.6-beta**?

**Comment by Patman86** [comment]
> 
> 
> > I've just committed the change with the 'Constant Quality Mode' checkbox, I hope it's fine now.
> 
> I don't see it, it's on the last BETA **StaxRip-x64-2.0.4.6-beta**?

Is available in next release.
