### ISSUE TITLE
New font selector list : problem happens with scaling = 1.25 and when list is resized to see scrollbar

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#629]
**Describe the bug**
This has been pointed out some days ago, but I have new info
Please can anyone try to reproduce:

1) set settings **> scaling = 1.25,** close, restart staxrip
2) open settings, click on the font selector (...)
3) resize the list so the scrollbar appears
4) move scrollbar down

Can anyone confirm this happens ?
if not, try other scaling values, like 1.20 ; 1.30

**Comment by JJKylee** [comment]
This is very weird. At the same scale factor 1.25, I don't have this kind of issue.

![StaxRip_2 1 15_font-selector-window_20210326](https://user-images.githubusercontent.com/3157518/112680104-31310980-8e2a-11eb-9654-062f21b29774.gif)

**Comment by 44vince44** [comment]
can you try 1.20 and 1.30
please !

**Comment by JJKylee** [comment]
I tried 1.20 and 1.30 and they are OK too. Hmm... 🤔

**Comment by 44vince44** [comment]
Well if this can't be reproduced, then I'm closing it.
Thanks @JJKylee for testing !!!

**Comment by Dendraspis** [comment]
Mine looks like the sample above - no issues at all.  🤔

**Comment by 44vince44** [comment]
For the record, values of scaling under or equal to 1.12  make list function correctly, and values 1.13 and above make list malfunction.

**Comment by Dendraspis** [comment]
I tested with UIScale 1.60.   🤔
