### ISSUE TITLE
Error opening mpv via staxrip

### ISSUE THREAD

**Issue by Patman86** [staxrip/staxrip#63]
I've got these error:

KeyNotFoundException (2.0.4.4)

Der angegebene Schlüssel war nicht im Wörterbuch angegeben.

System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.ThrowHelper.ThrowKeyNotFoundException()
   bei System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   bei StaxRip.GlobalCommands.StartTool(String name) in D:\Projekte\VB\staxrip\General\GlobalCommands.vb:Zeile 261.

**Comment by stax76** [comment]
I've fixed it but it will remain until you edit or reset the menu.

wrong: mvpnet
correct: mpv.net
