### ISSUE TITLE
Option to increase the "Auto Force Film" threshold

### ISSUE THREAD

**Issue by sndtrack** [staxrip/staxrip#641]
Hello. I'm facing an issue with StaxRip regarding the "Auto Force Film" automation.

I want to convert a VOB file (decrypted from a NTSC DVD). It's mostly soft-telecined ("96.34% film" as reported by DGIndex) with a small portion of hard-telecined material.

I used DGIndex (2.0.0.5) to generate the d2v file honoring the pulldown flags, so the resulting d2v file has the parameters "Field_Operation=0" and "Frame_Rate=29970".

When I open this d2v file in StaxRip (via MPEG2Source), StaxRip automatically overwrites it and changes the parameters to "Field_Operation=1" and "Frame_Rate=23976". This automation prevents me from properly applying IVTC, since the framerate goes down from 23.976 to 19.180 fps. I also tried opening the VOB file directly in StaxRip (via MPEG2Source). Nevetheless, the resulting d2v file is also "forced film" (Field_Operation=1), despite the "-fo 0" (Field_Operation=0) argument in Tools > Settings > Preprocessing > DGIndex.

The solution: I edited the d2v file (changing the last line to "94.99% FILM") before opening it in StaxRip, and StaxRip preserved the "Field_Operation=0" and "Frame_Rate=29970" parameters.

I did this test because there's a setting in MeGUI 2913 where you can specify a threshold: Options > External Programs > DGIndex Tools > Auto Force Film at (percent): 95 (default value).

So if DGIndex reports "95% film" or higher, StaxRip automatically changes the parameters to "Field_Operation=1" and "Frame_Rate=23976".

The DGIndex user manual states: "If the clip is not PAL or MPEG1, and the Video Type field in the Information window indicates Film 95% or higher, it is likely that the clip can be treated as 3:2 pulldown material, and so the Force Film option should be selected for generation of the D2V file".

However, this it only a recommendation, not a rule.

The manual also adds: "...there are more advanced ways to handle hybrid, hard-telecined, field-blended, and other pathological video. These more advanced methods almost always require the video to be served with the Honor Pulldown Flags option".

This is my case: 96.34% film, but with a small portion of hard-telecined material. And it's not an isolated case in my collection. In order to apply IVTC and remove the stray combed frames of such videos, it would be great to have an option (like MeGUI 2913) to increase the "Auto Force Film" recommended threshold (95%), or to disable this automation for good.

Thank you.

**Comment by stax76** [comment]
I thought that such an option exists, maybe it was removed, there isn't anything in the changelog about it.

**Comment by 44vince44** [comment]
@stax76 it seems to have been removed, probably when DGIndex was removed then put back (due to license misunderstanding)...

**Comment by Dendraspis** [comment]
I checked v2.0.8.0 from before the license issues - it worked the same way.

**Comment by 44vince44** [comment]
Then I guess it was removed a very long time ago (like years ago)

**Comment by Dendraspis** [comment]
I'll try to implement a solution in the next couple of days.

@sndtrack 
Is a global setting via *Preprocessing* enough or is a project based solution necessary?

**Comment by sndtrack** [comment]
A global setting would be more than enough. Thank you.

**Comment by Dendraspis** [comment]
@sndtrack 
Can you test this solution and tell me if it works for you?
[StaxRip v2.3.40.zip](https://github.com/staxrip/staxrip/files/6270576/StaxRip.v2.3.40.zip)
Please use a new copy of ***StaxRip v2.3.0*** (or delete/rename the `settings.dat` file) and replace the exe file with this one. You'll find the setting in `Options » Video`.

**Comment by sndtrack** [comment]
By increasing the "Auto Force Film" threshold, StaxRip doesn't overwrite the d2v file anymore. It's perfect. Thank you very much!
