### ISSUE TITLE
Keep working template open after file batch is finished

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#645]
**Is your feature request related to a problem? Please describe.**

It's kind of _not easy_ to prepare a template fit for a specific file batch job because template editing can be done only _without a source file_ and thus users should _imagine_ the scenario in advance without a file.

Sometimes I find unwanted/need-to-be-modified settings only after watching batch processes in action. However, modified templates can be saved _only before_ a file batch job as of now because StaxRip reverts back to the `Startup Template` right after the file batch job is finished. Therefore, even if I happen to forget to save the working template or to find something to modify/update on the template while watching the batch processes, I have no other alternative but to start over.

**Describe the solution you'd like**

It'd be desirable if the main window remains the same as just before doing the file batch job, keeping the working template open.

That way, I can either save the unsaved template or start the batch job with modified/updated option settings.

**Comment by 44vince44** [comment]
Here is a different way of saying the same request:

Currently, when a batch is finished, Staxrip will reload the startup template (exactly as when you open staxrip, it loads the startup template).
*The request*: is it possible to make Staxrip NOT restore the startup template, but simply keep the options that were present before running the batch

**Comment by JJKylee** [comment]
I've confirmed this is implemented in v2.4.26.

**Comment by 44vince44** [comment]
@JJKylee @Dendraspis Unfortunaltely this has introduced a new problem: when "Delete temp folder" is enabled.

To reproduce the problem easily:

1) set "Delete temp folder" to Recycle Bin
2) drop a file, create job
3) process job

At the end, the project's temp folder is deleted, which is ok, BUT THEN a new project's temp folder is created with a few files only.
This is not ok. no new project temp folder should be created

**Comment by 44vince44** [comment]
@JJKylee since then many changes were made.
Now latest dev build 2.4.31 has 2 different ways of handling:
- if delete temp files disabled => you are returned to your startup template
- if delete temp files enabled => you are returned to the project's setting (which is possible since your temp folder is still there)

**Comment by JJKylee** [comment]
> * if delete temp files disabled => you are returned to your startup template
> * if delete temp files enabled => you are returned to the project's setting (which is possible since your temp folder is still there)

Seems like the explanation is wrongly paired... 🙄❓

**Comment by Dendraspis** [comment]
@JJKylee   
Doesn't matter - it's fixed.  😁

**Comment by 44vince44** [comment]
> Seems like the explanation is wrongly paired... 🙄❓


@JJKylee indeed they are.
this only proves how tiresome the testing is.... you have to test all situations, not only the one you use or care for...
