### ISSUE TITLE
NNEDI3 folder and included registered files need overhaul

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#649]
v2.3.0 ships with the following files in `<StaxRip-v2.3.0-x64>\Apps\Plugins\AVS\NNEDI3` folder, but none of them are used at all by the default AVS filter profiles.

Even `nnedi3` itself calls `JPSDR`, a merge of `NNEDI3` and other plugins.

![StaxRip_2 3 0_NNEDI3_20210403](https://user-images.githubusercontent.com/3157518/113493005-a3d85f80-9490-11eb-8063-bbfba7f7711e.jpg)

![StaxRip_2 3 0_NNEDI3_calls_JPSDR_20210403](https://user-images.githubusercontent.com/3157518/113493008-aa66d700-9490-11eb-9bc0-62dd5f1a8585.jpg)

Besides, most of them have wrong information on `Apps Manager`. Here's the list.

### `edi_rpow2.avsi`

Its filter name is `edi_rpow2`, not `nnedi3_rpow2`.

(`nnedi3_rpow2` is an _embedded_ function in `nnedi3.dll`, which is in turn merged in `JPSDR`.
Therefore, `nnedi3_rpow2` should be included in the filter list of `JPSDR`, too.)

![StaxRip_2 3 0_edi_rpow2_20210403](https://user-images.githubusercontent.com/3157518/113493570-25ca8780-9495-11eb-9497-6452deddf9ce.jpg)

And the correct Web address is: https://forum.doom9.org/showthread.php?p=1738351#post1738351

An updated version of `edi_rpow2.avsi` is [here](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.6%20and%20up/edi_rpow2.avsi).

The script has its own help in the header.

### `nnedi3_16.avsi`

Although its filter name is correct, its file name is wrong. It should be `nnedi3_resize16.avsi`.

The item name itself and Web/Help links are wrong, too.

Web/Help: http://avisynth.nl/index.php/Nnedi3_resize16

![StaxRip_2 3 0_nnedi3_resize16_20210403](https://user-images.githubusercontent.com/3157518/113493645-231c6200-9496-11eb-80af-44c0abf1f699.jpg)

Its updated version is [here](https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.6%20and%20up/nnedi3_resize16.avsi).

### `nnedi3x.avsi`

Its description and Web/Help links are wrong.

![StaxRip_2 3 0_nnedi3x_20210403](https://user-images.githubusercontent.com/3157518/113493659-3e876d00-9496-11eb-9ec3-e3a9285e0330.jpg)

Correct Web/Help link: http://avisynth.nl/index.php/Nnedi3ocl/nnedi3x

**Comment by Dendraspis** [comment]
I hope I took care of everything.  😁

**Comment by JJKylee** [comment]
I believe you didn't forget to include `nnedi3_rpow2` in the filter list of `JPSDR`. 😅

**Comment by Dendraspis** [comment]
Don't worry, I have deleted the whole folder.  😁
