### ISSUE TITLE
H.265/HEVC isn't supported by the graphics card. (I have a 1080 TI)

### ISSUE THREAD

**Issue by ZeroCool22** [staxrip/staxrip#65]
**PC Specs:**

I7 77OOK **|** CORSAIR 32 GB **|** MSI GTX 1080TI 11GB GAMING X.

**Nvidia Drivers:** 436.15 STANDARD - Game Ready.

**Version of the program:** StaxRip-x64-**x64-2.0.4.4-beta

**NVEnc Version:** 4.50_x64

![Screenshot_7](https://user-images.githubusercontent.com/13344308/65649921-ec32d980-dfde-11e9-8926-b592e5f6ac2a.png)

I only have this problem when use a version of NVEnc above of **4.48** x64, with 4.48 everything works fine:

![Screenshot_8](https://user-images.githubusercontent.com/13344308/65650291-99f2b800-dfe0-11e9-8406-c79637edd636.png)

Full Log: https://pastebin.com/0pip7jqi

**Comment by Patman86** [comment]
The option --codec h265 must be change to -- codec hevc. Pls test this in command line. I think Stax or Raven will change it.
