### ISSUE TITLE
AssumeBFF defaults to AssumeTFF

### ISSUE THREAD

**Issue by Eniff** [staxrip/staxrip#650]
When adding avisynth script -> field -> Assume, both settings AssumeBFF and AssumeTFF defaults to AssumeTFF.

I have found this in the default filter profiles:

`[Field] 
Assume = $select:TFF|AssumeTFF();BFF|AssumeTFF()$
`

**Comment by Dendraspis** [comment]
@Eniff 
Thanks for reporting.
