### ISSUE TITLE
VBRHQ/CBRHQ should be removed from NVEnc encode mode

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#652]
`NVEncC` does not have `VBRHQ` or `CBRHQ` as one of its encode modes (as of 5.29), but StaxRip `NVEnc Options` window still has them.

Check out [this post on Doom9's Forum](https://forum.doom9.org/showthread.php?p=1940164#post1940164) to see what kind of issue can arise in case this obsolete encode mode is put in the `NVEncC` command line.

These two _invalid_ encode mode options should be removed.

See the [corresponding part in `NVEncC Options` online manual](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#encode-mode-options).

**Comment by 44vince44** [comment]
It seems indeed the --vbrhq and --cbrhq are deprecated since they do the same as --vbr --multipass 2pass-full...

Is this correct @JJKylee ?

**Comment by Dendraspis** [comment]
The main problem is, that it was not announced/mentioned in the last release changelogs.  😕 

But it should be fixed without creating new issues due to interference.

**Comment by JJKylee** [comment]
As pointed out in Doom9's Forum, NVEnc started supporting multi NVENC SDK API versions depending on Nvidia driver versions in 5.10. See [here](https://github.com/rigaya/NVEnc/releases/tag/5.10).

I'm not sure if this still holds, but if so, it will make this issue a little more complicated. Should we keep `VBRHQ`/`CBRHQ` alive and make them contingent for OLD driver users? Hmm... 🤔

**Comment by Dendraspis** [comment]
> Should we keep `VBRHQ`/`CBRHQ` alive and make them contingent for OLD driver users? Hmm... 🤔

No ❗

**Comment by JJKylee** [comment]
😁😁😁😁😁
