### ISSUE TITLE
Staxrip crash when I use QTGMC

### ISSUE THREAD

**Issue by Bdraft** [staxrip/staxrip#654]
I tried Staxrip 2.4.0 with QTGMC on a .vob fileand it crash every time. No problems with v1.7.0

I'm using Staxrip on Win 7 64bits 16GB RAM
.Net Framework 4.8, Visual C++ packages  2008, 2010,2012, 2013, 2015-2019 and  JRE 8 installed.

Screenshots
![2021-04-09_145553](https://user-images.githubusercontent.com/7032941/114224279-438d6600-9947-11eb-8199-0f0781afca79.jpg)
![2021-04-09_145635](https://user-images.githubusercontent.com/7032941/114224300-48521a00-9947-11eb-82ad-31fb563169ef.jpg)

Thanks for any help, best regards.

**Comment by JJKylee** [comment]
Screenshots alone are not enough at all.
Please post an issue abiding by the directions in the template.

**Comment by DJATOM** [comment]
"Illegal instruction" means that your CPU doesn't support instruction in the plugin (for example, you tried to execute plugin with avx2 support in avx only CPU).

**Comment by JJKylee** [comment]
QTGMC line 923:

```
NNEDI3clp = EdiMode == "NNEDI3" || EdiMode == "EEDI3+NNEDI3" || EdiMode == "BWDIF+NNEDI3" || EdiMode == "BWDIF+EEDI3" ? Input.NNEDI3( field=-2, nsize=NNSize, nns=NNeurons, qual=EdiQual, threads=EdiThreads, U=CEed,V=CEed ) : undefined
```

QTGMC line 718:

```
QTGMC_Interpolate( ediInput, InputType, EdiMode, NNSize, NNeurons, EdiQual, EdiMaxD, EdiThreads, bobbed, ChromaEdi )
```

They both are related to `NNEDI3`.

But the default shipped `NNEDI3` plugin in StaxRip v2.4.0 is `JPSDR(plugins_JPSDR)` v3.2.4 x64 Clang W7 **_AVX_** build.

@Bdraft, check if you _mistakenly_ replaced the shipped `plugins_JPSDR.dll` file with an `AVX2` version referring to the [Wiki document](https://github.com/staxrip/staxrip/wiki/How-to-optimize-JPSDR-for-AVX2-supporting-CPU%3A-a-recommended-step-for-using-QTGMC-in-AviSynth).

If not, we need more info about this issue.

**Comment by Bdraft** [comment]
Could be that the new version of NNEDI3 does not support my 12 years old video card?
Logs

**Comment by Bdraft** [comment]
I don't know how but it seems like I closed the issue by mistake,sorry. Should I open a new issue?

**Comment by JJKylee** [comment]
> Could be that the new version of NNEDI3 does not support my 12 years old video card?
> As I said before no problem with QTGMC in Staxrip v1.7.0

It's not about the video card. It's about **CPU**.

Your CPU is `AMD Athlon II X2 250 Processor` and according to [this specs document](https://www.techpowerup.com/cpu-specs/athlon-ii-x2-250.c602), _it doesn't even support `AVX`_.

So go download [`plugins_JPSDR_v3_2_5.7z`](https://github.com/jpsdr/plugins_JPSDR/releases), unzip it, and replace the original `plugins_JPSDR.dll` in `<StaxRip-Folder>\Apps\Plugins\AVS\JPSDR\` with the one in `plugins_JPSDR_v3_2_5\x64\Release_clang_W7\`.

**Comment by Bdraft** [comment]
Perfect!!! Thank you so much! Best regards!
