### ISSUE TITLE
Crash when muxing with an empty SRT subtitle file

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#656]
### Describe the bug

THIS IS A TOOL ISSUE: Mkvmerge and Mp4box cannot mux exmpty srt.

When Staxrip attempts to mux with an empty srt file, the process crashes. This is SPECIFIC to SRT.

**Why would we have an empty srt file?** For one of those reasons:

- original srt file is not empty, but a trim filter was used, and the trimmed video corresponds to a range where there are no subs
- original srt file is empty, it is often done in series where sometimes there are forced subtitles, sometimes not. So in order to keep the structure the same for all episodes, the episodes with no forced subtitles will include an empty forced subtitles file.

Note that with other subtitle file types (ssa), there is no problem, the muxing works with the ssa file that has no subtitles inside it.

### Expected behavior

StaxRip should not crash when muxing the empty srt file, and it should **not** ignore it.

### Suggested fix

Writing to the authors of MKVMerge and MP4Box to ask this feature: please make your muxer accept empty srt files.

### How to reproduce the issue
Open your favorite video with srt subs. Of course make sure they will be extracted and included (options)
select a range with the preview, a range where there is no subs (short range is enough).
encode: success
mux: crash!!
error:
```
Error Muxing to MKV (v2.4.4)

Muxing to MKV returned exit code: 2 (0x2)

It's unclear what this exit code means, in case it's
a Windows system error then it possibly means:

# for hex 0x2 / decimal 2
  STATUS_WAIT_2                                                  ntstatus.h   
  ERROR_FILE_NOT_FOUND                                           winerror.h   
# The system cannot find the file specified.
# as an HRESULT: Severity: SUCCESS (0), FACILITY_NULL (0x0), Code 0x2
# for hex 0x2 / decimal 2
  ERROR_FILE_NOT_FOUND                                           winerror.h   
# The system cannot find the file specified.
```

```
"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvmerge.exe" -o "R:\Friends - S01E01 The One where Monica Gets a New Roomate.mkv" "C:\Temp\_StaxRip\Friends - S01E01 The One where Monica Gets a New Roomate_temp\Friends - S01E01 The One where Monica Gets a New Roomate_out.hevc" --no-chapters --audio-tracks 0 --language 0:eng --default-track 0:0 --forced-track 0:0 "C:\Temp\_StaxRip\Friends - S01E01 The One where Monica Gets a New Roomate_temp\ID1 English_1547878349_cut_.m4a" --forced-track 0:0 --default-track 0:0 --language 0:eng --track-name "0:English" "C:\Temp\_StaxRip\Friends - S01E01 The One where Monica Gets a New Roomate_temp\ID1 English {English} ID0_cut_.srt" --ui-language en --title ""

mkvmerge v56.0.0 ('Strasbourg / St. Denis') 64-bit
Error: The file 'C:\Temp\_StaxRip\Friends - S01E01 The One where Monica Gets a New Roomate_temp\ID1 English {English} ID0_cut_.srt' could not be opened for reading: end of file error.

```

### LOG and useful files 

Complete Log:
[Friends - S01E01 The One where Monica Gets a New Roomate_staxrip.log](https://github.com/staxrip/staxrip/files/6290763/Friends.-.S01E01.The.One.where.Monica.Gets.a.New.Roomate_staxrip.log)

Empty srt file:
[ID1 English {English} ID0_cut_.zip](https://github.com/staxrip/staxrip/files/6290772/ID1.English.English.ID0_cut_.zip)

**Comment by JJKylee** [comment]
Definitely `mkvmerge` seems to fail in muxing an _empty_ `srt` file. Interesting.
Isn't it supposed to issue a warning and _ignore_ the dummy `srt` file? 🤔
I guess this is something to be reported to `mkvmerge`.
But in the meantime, is there anything we can do on the StaxRip side to prevent a major crash? 🙄❓

BTW, can I point out two very minor things about the log format?

Look at lines 448-449.
They are different mediainfo for different files (demuxed cut audio and demuxed cut subtitle). We need an _**empty line**_ between them for readability!!! 😅😁

And the past participle for `cut` is `cut`, not `cutted`. Please fix this typo. 😝

**Comment by 44vince44** [comment]
> And the past participle for cut is cut, not cutted. Please fix this typo. 😝

Grammarly correct but I noticed that in the IT talks, people use `cutted` to make sure it is not confused with the simple present.

**Comment by Dendraspis** [comment]
> Suggested fix
> Writing to the authors of MKVMerge and MP4Box to ask this feature: please make your muxer accept empty srt files.

We won't stop you.  😉

**Comment by 44vince44** [comment]
Well, this is important, because it IS a tool issue, with two tools (MKVMerge and MP4Box) but it is an understandable bug (read below) and STAXRIP CAN WORKAROUND IT:

- the bug is understandable: since an `srt` file has NO HEADER (unlike `ssa` and others), mp4box and mkvmerge have to read the fist data in it to determine its format. When there is no data, then they fail to do so, and the bug occurs.
- Staxrip can workaround it with a script: if a srt file is found with less than 5 bytes of size, then type in the file:
`1
00:00:00,000 --> 00:00:00,000
           `    (this last line is a sequence a few space characters
This file will be structurally fine, and will display no subs

- the authors of the tools can perform a test: if file is less than 5 bytes then add is as empty, no need to know anything about it, since it's empty
-

**Comment by 44vince44** [comment]
I'll close this, since it is a tool feature request. When the tool is updated, Staxrip will require no change to integrate it.
