### ISSUE TITLE
Autocrop showing unrounded progress percentage 

### ISSUE THREAD

**Issue by TheMaskedOnion** [staxrip/staxrip#659]
**Describe the bug**
Autocrop progress percentage show unrounded values e.g. 3.33333333333333%

**Expected behavior**
It should be rounded to the nearest percent e.g 3%

**How to reproduce the issue**
Go to settings > video. change the number of frames used for auto crop to 30. Process a video with cropping enabled. tested with AVS but suspect is does the same thing with VS. 

**Provide information**
<a href="https://ibb.co/cTHxWNs"><img src="https://i.ibb.co/ys1Vz8x/Staxrip-autocrop-percent.png" alt="Staxrip-autocrop-percent" border="0"></a>

If you can't (or don't) share your log file, give us at least this information:
Used StaxRip version: 2.3 (clean settings)

**Comment by TheMaskedOnion** [comment]
just to add the same thing happens with v2.4.

**Comment by Dendraspis** [comment]
I'm pretty sure this *behavior* is there since the implementation of AutoCrop.  😁 
But I don't think it's worth spending time to make the progress nicer.

**Comment by TheMaskedOnion** [comment]
couldn't line 27 in Source/Tools/AutoCrop/Main.vb

go from
`Console.WriteLine("Progress: " & ((x - 1) / count * 100) & "%")`

to
`Console.WriteLine("Progress: " & Decimal.Round(((x - 1) / count * 100)) & "%")`

**Comment by Dendraspis** [comment]
Yeah, that is the fast part.  😁 
But instead of arguing and explaining and seeing you investing some time, I've made it.

The next release won't use decimal digits in progress output.

**Comment by 44vince44** [comment]
Thanks @TheMaskedOnion for your help!

Thanks @Dendraspis to have the wisdom to fix it 🤣
