### ISSUE TITLE
System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by megapro17** [staxrip/staxrip#66]
**Step To Reproduce the Problem**

Add new video, trim, convert using ffmpeg h265 intel crf 20. 
I tried mp4box and ffmpeg/mp4 muxers, same crash
I found out, that problem is because of audio is named: "Fallout - New Vegas 2019.09.27 - 23.33.32.02 ID1 {SoundHandle _ System sounds}.m4a", maybe it is { } symbols. If I rename audio, it converts normally

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
- Version 2.0.4.0
- FrameServer Being Used: Avisynth

[Fallout - New Vegas 2019.09.27 - 23.33.32.02_new_staxrip.log](https://github.com/staxrip/staxrip/files/3667886/Fallout.-.New.Vegas.2019.09.27.-.23.33.32.02_new_staxrip.log)
[recovery.zip](https://github.com/staxrip/staxrip/files/3667891/recovery.zip)

**Comment by stax76** [comment]
Hello,

it's a known issue that was already fixed:

https://github.com/staxrip/staxrip/issues/55
