### ISSUE TITLE
Need lighter Cropping Color

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#663]
Request:

When Cropping - It is very hard to see the difference in color between the DARK Blue (cropped) and  BLACK (not cropped) areas especially when close to the edge of the BLACK area making it difficult to tell when the final few pixel rows are selected/not selected. 

The Cropping color should be light (Light YELLOW, Light GREEN, or Pale PINK) - A light color would make it easier to differentiate (especially the final few pixel rows) between what will be cropped and what won't be cropped making the cropping process easier.

Bellow: are the last pixel rows cropped???

![210416 092658](https://user-images.githubusercontent.com/16325865/115031218-ea1cbe00-9e95-11eb-901d-da0dd61476a1.png)

This can be seen better when the cropped area is lighter (as below), but it is still not distinctively obvious.

![210416 092757](https://user-images.githubusercontent.com/16325865/115031573-539ccc80-9e96-11eb-9861-a1e38d0bcb4a.png)

**Comment by JJKylee** [comment]
My recommendation:

Apply auto crop (`A`) and _use the slider to change the frame_ to finetune the crops.

And you can change the feature **theme color** to change the cropping color:
`Tools` > `Settings` > `User Interface` > `Theme`.

**Comment by Dendraspis** [comment]
In Crop window you can also use the menu (bottom right) to choose a fix color (white, black).

**Comment by JJKylee** [comment]
> In Crop window you can also use the menu (bottom right) to choose a fix color (white, black).

This `Crop Color` menu would not be visible to users who copy-&-pasted old settings.
@noblemd00, _**reset**_ the right-click menus in `Crop` window:
Right click > `Edit Menu...` > `Tools` > `Reset everything`.

**Comment by noblemd00** [comment]
> In Crop window you can also use the menu (bottom right) to choose a fix color (white, black).
> 
> > The Cropping color should be light
> 

Thanks for pointing out the weird Menu position. Still and all, the DEFAULT crop color should be a LIGHT color not a DARK color (see my pictures). Users should not be forced to take action to correct a user interface issue. Don't you think a light color crop cursor is more user friendly.
-------------------------------------------------------------------------------------
> Definitely not. Seems you use it wrong. 😉

Oh, how am I using it wrong? I thought the purpose of the CROP menu was to CROP the video. I move the mouse to select the proper crop (top, bottom, left, right) then use a combination of mouse click (approximate amount of crop) and +/- (fine adjust) to position crop. How am I "using it wrong"?

**Comment by JJKylee** [comment]
![StaxRip_2 4 0_Crop-window_Crop-Color_20210416](https://user-images.githubusercontent.com/3157518/115048197-28ae7a80-9e8e-11eb-91a6-7de47d8bfb6a.jpg)

**Comment by JJKylee** [comment]
I don't understand why this can be something to complain about.
Like mentioned above, there are many easy alternatives.

Users have _different_ preferences depending on use case. Why do you claim that your case **_should_** be the _default_, @noblemd00?
What if someone else comes up with a bright frame and argues that a dark color should be the _default_ crop color? 😒
