### ISSUE TITLE
Make NVEnc, VCEEnc, QSVEnc optional, not required in Apps Manager

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#664]
**Is your feature request related to a problem? Please describe.**

As of v2.4.4, _**all**_ hardware encoders are _required_, not optional. This makes users carry along _unnecessary files_ even if they do not own the particular hardware.

For example, suppose you own an Intel CPU with an Nvidia graphics card that supports NVEnc, but do not have any AMD hardware. Even in that case, VCEEnc is _required_, and thus you cannot go without it. If you delete the files in `VCEEnc` to save the drive space (48 MiB or so), you will get this 'warning' in _Apps Manager_ and cannot proceed before you try to do anything in StaxRip.

![StaxRip_2 4 0_Apps-Manager_VCEEnc_required_20210416](https://user-images.githubusercontent.com/3157518/115098067-c2077c00-9ee2-11eb-9aa0-de3c640d6d8a.jpg)

The same applies to users who do not own related hardware in particular.

**Describe the solution you'd like**

These tools need to be made _**optional**_, not required, and the _Apps Manager_ warning needs to pop up _only_ when these tools are employed in reality.

**Comment by 44vince44** [comment]
By doing this, the user will freely be able to delete all or any hardware encoder, without staxrip blocking.

Good idea, and actually this is the proper way of handling it!

**Comment by JJKylee** [comment]
@Dendraspis,

I'm wondering.
Is adding a `.RequiredFunc` line to each item in _Package.vb_ gonna serve the purpose?

For example, in _VCEEnc_,

```
.RequiredFunc = Function() TypeOf p.VideoEncoder Is VCEEnc,
```

Will there be any unexpected but problematic outcome? 🙄❓

**Comment by 44vince44** [comment]
I think that's the whole point:
This simple change (or any other change at that level) can possibly break many things, and maybe @Dendraspis is not willing to take that risk, for something that is not preventing Staxrip from working.

**Comment by JJKylee** [comment]
That's exactly what I'm worried about.

**Comment by 44vince44** [comment]
Sometimes it's better to leave things working, as they are 🤣

**Comment by 44vince44** [comment]
Well, considering the "trouble" we could get into, I would recommend against this, finally... imho...

**Comment by 44vince44** [comment]
IMHO:
 
Do not change any code, because although this has some logic, StaxRip is not supposed to be crippled by the user.
But if the user is an advanced user, and he/SHE still wants to create a small release, he/she can put a DUMMY small exe in the place of those exes, and validates in the app manager with dummy data.

I really suggest this gets closed.

**Comment by Dendraspis** [comment]
Encoders are the basis of StaxRip and causing probable issues to save let's say 100(?) MB does not sound very attractive, especially some encoders are packed by @Patman86, so they need only ~3MB each.

In case you really need to save those few MB, use the technique provided by @44vince44 .
