### ISSUE TITLE
Add end of job queue sound

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#666]
When I leave my PC unattended, I'd like to have a sound for successful or aborted job queue.

Could be possible to add these two different sounds to StaxRip?

**Comment by Dendraspis** [comment]
You can set up an event command to play whatever you want.

**Comment by tormento** [comment]
@Dendraspis I am aware of actions but think to the average Joe user. A nice option would be preferred.

**Comment by 44vince44** [comment]
I don't recall anyone ever asking for this. Are there other users asking for this feature ?

**Comment by JJKylee** [comment]
Completion sound is really easy.

![StaxRip_2 4 0_Event-Command_completion-sound_20210417](https://user-images.githubusercontent.com/3157518/115120536-d7bc8600-9f62-11eb-8271-3105f36c9952.jpg)

And about the failure, how do we know (on what criteria) if any of the queued jobs has failed? 🙄❓

**Comment by Dendraspis** [comment]
@JJKylee 
You must be blind:  😜 

<img width=700 src="https://user-images.githubusercontent.com/50659978/115121659-33632f80-9fb4-11eb-8582-fbc181fcd39e.png">

Will be added in the next release....
