### ISSUE TITLE
Consistency in packaging releases

### ISSUE THREAD

**Issue by Zcehtro** [staxrip/staxrip#671]
**Is your feature request related to a problem? Please describe.**
I update Staxrip via Chocolatey, and I noticed that in some release versions the folder structure in the archive is different.
This presents an issue because my Windows shortcuts to Staxrip might point to missing executables because the archive extraction produced a different folder structure.

For example, here is the full path to StaxRip.exe in a few handpicked releases to show the inconsistency I request to be addressed, ordered by version number:

StaxRip-x64-2.0.2.0-stable.7z\StaxRip.exe
Staxrip.2.0.2.4.x64.rar\v4.7\StaxRip.exe
Staxrip.2.0.2.4.x64.rar\v4.8\StaxRip.exe
StaxRip-x64-2.0.6.0-stable.7z\StaxRip.exe
StaxRip-x64-2.0.8.0-stable.7z\StaxRip.exe
StaxRip-x64-2.1.3.0-stable.7z\StaxRip.exe
StaxRip-x64-2.1.6.0-Stable.7z\StaxRip.exe
StaxRip-x64-2.1.7.0-Stable.7z\StaxRip.exe
StaxRip-v2.2.0-x64.7z\StaxRip-v2.2.0-x64\StaxRip.exe
StaxRip-v2.4.0-x64.7z\StaxRip-v2.4.0-x64\StaxRip.exe

**Describe the solution you'd like**
Standardize the archive naming scheme, and packaging structure, for releases.

**Describe alternatives you've considered**
None.

**Explain why the feature matters to you**
More people are using Staxrip. So make it easier to install and handle.

**Additional context**
None.

**Comment by Dendraspis** [comment]
> Standardize the archive naming scheme, and packaging structure, for releases.
> For example, here is the full path to StaxRip.exe in a few handpicked releases to show the inconsistency I request to be addressed, ordered by version number: ...

That's what we already did with **v2.2.0**.
And when you eliminate the (non-official) hotfix versions, you end-up with:
 
- StaxRip-x64-2.0.2.0-stable.7z\StaxRip.exe
- StaxRip-x64-2.0.6.0-stable.7z\StaxRip.exe
- StaxRip-x64-2.0.8.0-stable.7z\StaxRip.exe
- StaxRip-x64-2.1.3.0-stable.7z\StaxRip.exe
- StaxRip-x64-2.1.6.0-Stable.7z\StaxRip.exe
- StaxRip-x64-2.1.7.0-Stable.7z\StaxRip.exe
- StaxRip-v2.2.0-x64.7z\StaxRip-v2.2.0-x64\StaxRip.exe
- StaxRip-v2.4.0-x64.7z\StaxRip-v2.4.0-x64\StaxRip.exe
