### ISSUE TITLE
Feature Request: let Stax76 give us some news even if he's not currently coding

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#678]
**Is your feature request related to a problem? Please describe.**
Yes we're worried about @stax76 , long time away, no news

**Describe the solution you'd like**
GIVE NEWS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by stax76** [comment]
Thanks, I don't feel particular well lately, not sure why.

I've been working on Everything.NET and mpv.net, code isn't yet pushed or released.

**Comment by 44vince44** [comment]
I'm really happy to hear from you, and hope you'll feel better soon !
We miss you much, can't wait to see what you've done in mpv.net 😁

**Comment by JJKylee** [comment]
@stax76, I wish you feel much better now. 💪
