### ISSUE TITLE
2.4.31: Still un-themed window - 'New From Defaults...'

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#681]
See this:

![StaxRip_2 4 31_unthemed_window_New-From-Defaults_20210430](https://user-images.githubusercontent.com/3157518/116727935-165a3380-a99a-11eb-9d99-d8ac6b5e9b06.png)

Can't believe I've found this. 😅🤣

**Comment by Dendraspis** [comment]
Will be fixed in next release...
