### ISSUE TITLE
Encode a dvd

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#685]
Hi guys,

StaxRip is an incredible program for me, I can encode from BD, Remux, other kind of mkv, other extensions, scalade from 720 up to 4k, use diferente codecs X265, Nvenc, etc.  Make HDR, use Dolby Vision, etc, etc

But I don' find anywhere if I can make a mkv from DVD folder.  Lower programs (for me) like Handbrake or VidCoder does do it.

It would be possible to introduce this option to further improve this incredible program?

There are many old film only in DVD and it would be very interesting to make transform to digital version (mkv)

Best regards, and apoligize for my bad english, it's not my mother tongue

**Comment by 44vince44** [comment]
You can do DVD to MKV !

Just drop the vob files. Take a look at that guide.
https://github.com/staxrip/staxrip/wiki/VOB-%28DVD%29-Processing-Tips

**Comment by papa-pitufo** [comment]
Thanks, I take an eye

But, if I understand well, I only transform a DVD to mkv, I don't up-scale to 720 or 1080, don't use filter of Avisynth, etc.  Isn't it?

Or I am wrong.

Best regards

**Comment by 44vince44** [comment]
Well, due to an imperfection in Staxrip, if you only convert DVD to MKV, without encoding, it won't work correctly.
But if you re-encode (x264, or x265 or any), it will work perfectly.

**Comment by papa-pitufo** [comment]
Ok, thanks a lot

**Comment by Mister-XY** [comment]
If you only want the DVD as a pure MKV file, then I recommend MakeMKV. You can also rip DVD's with it.

**Comment by F1ReB4LL** [comment]
> You can do DVD to MKV !
> 
> Just drop the vob files. Take a look at that guide. https://github.com/staxrip/staxrip/wiki/VOB-%28DVD%29-Processing-Tips

But you can't split it by chapters and work with specific titles/chapters only, like in Hybrid/HandBrake/VidCoder, correct? Like, to encode Title 5 from Chapter 1 to Chapter 2 only. If so, you shouldn't say it does DVD to MKV, but VOB to MKV.
