### ISSUE TITLE
I have a question about duplicity

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#686]
Hi guys,

First, many thanks for the new release.

How about when I have duplicity funtions?

Let me explain

Sometimes I select a specificic filter and in my video codec I have the same funtion.

For example
VS filter: Colorspace
NVenc: Colorspace

Which does StaxRip use, VS or Codec?`
If StaxRip use both, Is it good or not?
Which have the priority?
If I have one I must disable the other one in order to work fine?
Which of both is better, in general? 
VS/AS Filter is better than video codec option?

Best Regards

**Comment by Dendraspis** [comment]
Very simple answer:  there are no `duplicity funtions`. And this should answer almost every of your questions.

The FrameServer (mostly AVS/VS) reads and prepares the source. Then these information are given towards the encoder (for example x265).
Both can have **similar** functions, but can work differently under the hood.

**Comment by papa-pitufo** [comment]
Ok, I understand it perfectly

Best regards
