### ISSUE TITLE
HDR10+ & Dolby Vision

### ISSUE THREAD

**Issue by Harybo** [staxrip/staxrip#687]
Hey,

I would like to know if staxrip supports hdr10 + and dolby vision if so how to best configure them

**Comment by JJKylee** [comment]
For **Dolby Vision**, refer to [this post](https://forum.doom9.org/showthread.php?p=1941809#post1941809) on Doom9.

For **HDR10+**, you need to employ [`hdr10plus_parser`](hdr10plus_parser) instead of `dovi_tool` in order to extract the _dynamic metadata_ of the video stream.

In `x265`, the path to the `json` file containing the dynamic metadata can be set in `VUI` > `HDR10 Info File`.

For HDR10+ only, `NVEnc` can be used as well. With `NVEnc`, you don't need to extract the dynamic metadata from the input. Instead, you can use `copy` instead of the `json` file path in  `VUI` > `HDR10 Info File`.

![StaxRip_2 5 0_NVEnc_HDR10+_20210503](https://user-images.githubusercontent.com/3157518/116915945-89b1ae80-ac01-11eb-86f1-5a72a3be584d.png)

Of course, you're required to use H265 for high bit depth.

**Comment by 44vince44** [comment]
@JJKylee i suggest i do a guide, if you're not upto it.

**Comment by JJKylee** [comment]
@44vince44,
I'm kind'a busy doing something else, so go ahead, plz. 😄

**Comment by 44vince44** [comment]
With pleasure ! 
I'll do it tomorrow PM !!

**Comment by Harybo** [comment]
Thank you, other questions about smpte 2094 support coming soon

**Comment by Harybo** [comment]
i just tested it all and i see it already supports my bad and thanks for your help

**Comment by 44vince44** [comment]
Here is a screenshot of the HDR10+ Info File , I post it here to use it in the Wiki.
![SNAG-0000](https://user-images.githubusercontent.com/17828567/117060820-12c40500-ad2a-11eb-8713-c506a57ad51e.jpg)

**Comment by 44vince44** [comment]
@JJKylee @Dendraspis Can you take a look here:
- https://github.com/staxrip/staxrip/wiki/Encoding-Dolby-Vision-with-StaxRip-using-x265
- https://github.com/staxrip/staxrip/wiki/Encoding-Dynamic-HDR10.Plus-with-StaxRip-using-x265-or-NVEnc.H265

They are already referred to in the home page of the Wiki.
Dynamic HDR10.Plus is the only way I found to write that in the title, because I cannot place the sign `+` in the title....

**Comment by JJKylee** [comment]
> `Dynamic HDR10.Plus` is the only way I found to write that in the title, because I cannot place the sign `+` in the title....
> 
> @JJKylee please correct or complete whenever you've got some time...

Got it. I've also found the weird limit in titling a _wiki_ document: `+` cannot be used. So basically `AviSynth+` couldn't be put in the title in my case. 😅

I guess Github needs to update their Wiki module asap 'cuz there are so many missing features like lack of attachment support, lack of shortcut support, limit in titling a document, etc. 🤔

As you seem to have changed the document title, I've updated the link as follows:

https://github.com/staxrip/staxrip/wiki/Encoding-Dynamic-HDR10plus%C2%AD-with-StaxRip-using-x265-or-NVEnc.H265

Let me fill in some more material at a later time. 😁

**Comment by Harybo** [comment]
On the other hand for the dolby vision, I did both ways because in the meantime I think that there has been an update of dovi_tool. When I encode it leaves me the video without dolby vision out I did like what you showed me

**Comment by 44vince44** [comment]
Can you post the log ?

**Comment by Harybo** [comment]
[2021-05-06 - 09.08.12 - Law.Abiding.Citizen.2009.2160p.UHD.BLURAY.REMUX.HEVC.MULTI.TRUEFRENCH.DTS-HDMA.DoVi-KLP33 - 22_staxrip.log](https://github.com/staxrip/staxrip/files/6432878/2021-05-06.-.09.08.12.-.Law.Abiding.Citizen.2009.2160p.UHD.BLURAY.REMUX.HEVC.MULTI.TRUEFRENCH.DTS-HDMA.DoVi-KLP33.-.22_staxrip.log)

**Comment by Harybo** [comment]
x265 [INFO]: HEVC encoder version 3.5+10+13-7c9bc0cb14 [Mod by Patman]
x265 [INFO]: build info [Windows][GCC 10.2.0][64 bit] 10bit
x265 [INFO]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [INFO]: Main 10 profile, Level-5 (Main tier)
x265 [INFO]: Thread pool created using 32 threads
x265 [INFO]: Slices                                  : 1
x265 [INFO]: frame threads / pool features           : 5 / wpp (25 rows)
x265 [INFO]: Coding QT: max CU size / min CU size    : 64 / 8
x265 [INFO]: Residual QT: max TU size / max TU depth : 32 / 1 inter / 1 intra
x265 [INFO]: ME / range / subpel / merge             : star / 57 / 3 / 3
x265 [INFO]: Keyint min / max / scenecut / bias      : 23 / 250 / 40 / 5.00 
x265 [INFO]: Lookahead / bframes / badapt            : 25 / 4 / 2
x265 [INFO]: b-pyramid / weightp / weightb           : 1 / 1 / 0
x265 [INFO]: References / ref-limit  cu / depth      : 4 / on / on
x265 [INFO]: AQ: mode / str / qg-size / cu-tree      : 2 / 1.0 / 32 / 1
x265 [INFO]: Rate Control / qCompress                : CRF-22.0 / 0.60
x265 [INFO]: VBV buffer / maxrate / init             : 4000 / 8000 / 0.900
x265 [INFO]: tools: rect limit-modes rd=4 psy-rd=2.00 rdoq=2 psy-rdoq=1.00
x265 [INFO]: tools: rskip mode=1 signhide tmvp strong-intra-smoothing lslices=4
x265 [INFO]: tools: deblock sao
x265 [WARN]: Dolby Vision RPU count is greater than frame count in x265
x265 [INFO]: VES muxing with Dolby Vision RPU file successful in x265
x265 [INFO]: frame I:    377, Avg QP:25.05  kb/s: 11554.11
x265 [INFO]: frame P:  11662, Avg QP:25.75  kb/s: 7728.86 
x265 [INFO]: frame B:  40364, Avg QP:28.94  kb/s: 2891.62 
x265 [INFO]: Weighted P-Frames: Y:11.2% UV:9.0%
x265 [INFO]: consecutive B-frames: 6.6% 3.4% 5.5% 17.0% 67.5% 
encoded 52403 frames in 17378.70s (3.02 fps), 4030.44 kb/s, Avg QP:28.20

**Comment by Harybo** [comment]
being in 3 chunk can break the dolby vision

**Comment by Harybo** [comment]
[2021-05-06 - 10.24.51 - dolby-vision-amaze_staxrip.log](https://github.com/staxrip/staxrip/files/6432986/2021-05-06.-.10.24.51.-.dolby-vision-amaze_staxrip.log)

**Comment by 44vince44** [comment]
> being in 3 chunk can break the dolby vision

This is probably due to the avs/vpy reader of x265.
It may be very difficult to make the x265 use the portion of the RPU file corresponding to the encoding range of the chunk.

Now, when you encode Dolby Vision, you are encoding 4K resolution. At the resolution, you don't need to use chunks.
This is important, I will put a warning in the guide.
ALSO it won't work if you select a range in the preview.

QUESTION : if you use 1 chunk only, FULL VIDEO (from video start to end, no range), is the Dolby Vision rpu data applied correctly ?

**Comment by Harybo** [comment]
> > being in 3 chunk can break the dolby vision
> 
> This is probably due to the avs/vpy reader of x265.
> It may be very difficult to make the x265 use the portion of the RPU file corresponding to the encoding range of the chunk.
> 
> Now, when you encode Dolby Vision, you are encoding 4K resolution. At the 4K resolution, you don't need to use chunks.
> This is important, I will put a warning in the guide.
> ALSO it won't work if you select a range in the preview.
> 
> QUESTION : if you use 1 chunk only, FULL VIDEO (from video start to end, no range), is the Dolby Vision rpu data applied correctly ?

same problem when I do everything in one block. It's exactly the same message as with 3 chunks

**Comment by Harybo** [comment]
[2021-05-06 - 15.00.23 - P81_GlassBlowing2_3840x2160@59.94fps_15200kbps_fmp4_staxrip.log](https://github.com/staxrip/staxrip/files/6435954/2021-05-06.-.15.00.23.-.P81_GlassBlowing2_3840x2160%4059.94fps_15200kbps_fmp4_staxrip.log)

**Comment by 44vince44** [comment]
This requires the comment of a specialist in DolbyVision.
The log shows the rpu has been used.
However, it can be the profile....
Now, If you have some time, you can try this build of x265:
https://github.com/DJATOM/x265-aMod/releases/download/3.5%2B20/x265-x64-v3.5+20-aMod-gcc10.2.1+opt.7z

Do you know how to replace the x265.exe in staxrip with this one (inside the archive, renamed to x255.exe) ?
The idea is to test this build and see if there is a difference.....

I have no dolbyvision material so I cannot test...

**Comment by Harybo** [comment]
I am doing the test with the version of x265 that you gave me

**Comment by Harybo** [comment]
[Uploading 2021-05-06 - 19.46.10 - P81_GlassBlowing2_3840x2160@59.94fps_15200kbps_fmp4_staxrip.log…]()

**Comment by Harybo** [comment]
[2021-05-06 - 19.46.10 - P81_GlassBlowing2_3840x2160@59.94fps_15200kbps_fmp4_staxrip.log](https://github.com/staxrip/staxrip/files/6436684/2021-05-06.-.19.46.10.-.P81_GlassBlowing2_3840x2160%4059.94fps_15200kbps_fmp4_staxrip.log)

**Comment by JJKylee** [comment]
@Harybo,

The Dolby Vision **_profile_** of your _**source**_ is **5** (dvhe.**05**.09, BL+RPU) and you are trying to encode it to **_Profile 8.2_** (`--dolby-vision-profile 8.2`). I guess it's a profile conflict. Try profile 5 instead of 8.2 in x265.

Maybe [this document](https://avdisco.com/t/demystifying-dolby-vision-profile-levels-dolby-vision-levels-mel-fel/95) can be of help in understanding why profiles are important in Dolby Vision.

AFAIK, `dovi_tool` is not providing any mode to convert profile 5 to profile 8.2 as of now.

If you want to encode to SDR, maybe [tonemapping](https://github.com/staxrip/staxrip/wiki/How-to-tonemap-HDR-to-SDR) is a more appropriate approach.

And since the dynamic metadata is dependent on frames, splitting frames by enabling chunk encoding is definitely not going to work well with RPU files.

**Comment by Harybo** [comment]
> @Harybo,
> 
> The Dolby Vision **_profile_** of your _**source**_, `dolby-vision-amaze.mp4`, is **5** (dvhe.**05**.09, BL+RPU) and you are trying to encode it to **_Profile 8.2_** (`--dolby-vision-profile 8.2`). I guess it's a profile conflict. Try profile 5 instead of 8.2 in x265.
> 
> Maybe [this document](https://avdisco.com/t/demystifying-dolby-vision-profile-levels-dolby-vision-levels-mel-fel/95) can be of help in understanding why profiles are important in Dolby Vision.
> 
> AFAIK, `dovi_tool` is not providing any mode to convert profile 5 to profile 8.2 as of now.
> 
> If you want to encode to SDR, maybe [tonemapping](https://github.com/staxrip/staxrip/wiki/How-to-tonemap-HDR-to-SDR) is a more appropriate approach.
> 
> And since the dynamic metadata is dependent on frames, splitting frames by enabling chunk encoding is definitely not going to work well with RPU files.

on the last encode I did is dvhe.08.09 the source.  because if I refer to the table in the document you gave me I can go up to profile 13 if I understand correctly.  finally Dolby vision is something that I do not yet master

**Comment by JJKylee** [comment]
> on the last encode I did is dvhe.08.09 the source. because if I refer to the table in the document you gave me I can go up to profile 13 if I understand correctly.

No. x265 can only encode Dolby Vision profiles 5, 8.1, and 8.2.

In the case of `P81_GlassBlowing2` (profile 8.1), you definitely need to refer to [this document](https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/) in setting up the x265 command line for profile 8.1. Parameters like `max-cll`, `vbv-bufsize`, `vbv-maxrate` should also be considered.

If it still does not work, maybe there's something else not noticed here.

**Comment by Harybo** [comment]
> > on the last encode I did is dvhe.08.09 the source. because if I refer to the table in the document you gave me I can go up to profile 13 if I understand correctly.
> 
> No. x265 can only encode Dolby Vision profiles 5, 8.1, and 8.2. Maybe you're talking about _levels_, not profiles. Well, you're supposed to be able to distinguish between those two.
> 
> In the case of `P81_GlassBlowing2` (profile 8.1), I strongly recommend you to refer to [this document](https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/) in setting up the x265 command line for profile 8.1. Parameters like `max-cll`, `vbv-bufsize`, `vbv-maxrate` along with other HDR related parameters should also be considered. And make sure the RPU file is correctly input.
> 
> If it still does not work, maybe there's something else not noticed here.

thank you, i will read all this and test tomorrow

**Comment by 44vince44** [comment]
@JJKylee thanks for all this important info.

I found this site that has REAL Dolby Vision demos, in profiles 5 and 8.1.

https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/

**Comment by JJKylee** [comment]
```
avs+ [INFO]: 3840x2160 fps 69/472
```

The frame rate is weird. Maybe L-SMASH cannot handle the particular source correctly. Try another source filter like _FFvideosource_, or use FFmpeg as the decoder in the _command line_ (as in the post I recommended to read in my previous reply).

```
ffmpeg -i INPUT -f yuv4mpegpipe -strict -1 -pix_fmt yuv420p10le - | C:\StaxRip\Apps\Encoders\x265\x265.exe - --output-depth 10 --y4m --preset slow --crf 22 --master-display "G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(40000000,50)" --max-cll "0,0" --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --dolby-vision-rpu E:\Transcod\RPU.bin --dolby-vision-profile 8.1 --vbv-bufsize 2000000 --vbv-maxrate 2000000 --output [...]_out.hevc
```

And why are there `--hdr10`, `--hdr10-opt` parameters? This is not about HDR10. 🤨

If you still have problems, maybe you better go without Dolby Vision but _try HDR10 instead_.

**Comment by JJKylee** [comment]
I tried encoding `iOS_P5_GlassBlowing2_1920x1080@59.94fps_15200kbps.mp4`(Dolby Vision Profile 5) from [the site @44vince44 has found](https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/), and have found that `mkvmerge` _still_ can_not_ support Dolby Vision muxing. Currently only `tsMuxeR` can preserve the Dolby Vision layer in the video stream.

[iOS_P5_GlassBlowing2_1920x1080_out.**_ts_** mediainfo]
```
Video

ID                              : 4117 (0x1015)
Menu ID                         : 1 (0x1)
Format                          : HEVC
Format/Info                     : High Efficiency Video Coding
Format profile                  : Main 10@L5.2@High
HDR format                      : Dolby Vision, Version 1.0, dvhe.05.05, BL+RPU
Codec ID                        : 36
Duration                        : 2mn 54s
Bit rate                        : 2903 Kbps
Width                           : 1920 pixel
Height                          : 1080 pixel
Display aspect ratio            : 16:9
Frame rate                      : 59.940 (60000/1001) fps
Color space                     : YUV
Chroma subsampling              : 4:2:0
Bit depth                       : 10 bit
Bits/(Pixel*Frame)              : 0.023
Stream size                     : 60.6 MiB (95%)
Writing library                 : x265 3.5+10+13-7c9bc0cb14:[Windows][MSVC 1928][64 bit] 10bit
...
```

**Comment by JJKylee** [comment]
I downloaded `P81_GlassBlowing2_1920x1080@59.94fps_15200kbps_fmp4.mp4` (Profile 8.1) from [here](https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/) and did the Dolby Vision re-encoding.

`LSMASHVideoSource` (20210423 HolyWu) seems to have an issue with opening the Dolby Vision hevc streams (both Profile 5 and Profile 8.1): the frame rate is totally wrong.

So I adopted `FFVideoSource` and succeeded in creating a `hevc` stream containing the RPU metadata.

Currently the _only_ muxer that preserves the Dolby Vision info in the video stream seems to be `tsMuxeR`.

Refer to the [wiki document](https://github.com/staxrip/staxrip/wiki/Encoding-Dolby-Vision-with-StaxRip-using-x265) that I've updated accordingly.

**Comment by JJKylee** [comment]
@44vince44,

I was wondering why there is this weird character `%C2%AD` in the HDR10+ wiki document,

```
...HDR10plus%C2%AD-with-StaxRip...
```

and I've found out what it is in the course of putting the link in Doom9's forum. It's a hidden asterisk(*) character!

So renamed the title, and the weird character is gone now.

https://github.com/staxrip/staxrip/wiki/Encoding-Dynamic-HDR10plus-with-StaxRip-using-x265-or-NVEnc.H265

GitHub does need to fix their Wiki module. 🤔

**Comment by Harybo** [comment]
Wow, great job.  on the other hand I am missing one thing how do you ask staxrip and not do the multiplexing with mkvmerge at the end

**Comment by JJKylee** [comment]
> on the other hand I am missing one thing how do you ask staxrip and not do the multiplexing with mkvmerge at the end

Can’t. You need to do an extra muxing with files in the temp folder via `tsMuxeR` afterwards.

I guess it’s somehow possible to incorporate `tsMuxeR` like other muxers in StaxRip, but that requires code work on the program source. 😝

**Comment by Harybo** [comment]
I contacted friends who manage to integrate the dolby vision in mkv files. They made a little DIY program for them. But they are impatiently waiting for mkvmerge to consider adding dolby vision metadata

**Comment by 44vince44** [comment]
@JJKylee GREAT FIND !!!! so it was a muxing issue!
@Harybo thanks for the info. It is certain that one days Moritz will include this feature in his MKVMerge.

Now the sad thing is that we cannot see any dolby vision improvements on popular player (yet), because we saw the result in profile 5.
And What we are actually seeing in profiles 8.x is either the SDR fallback or the HDR10 fallback (whether it's sub-version 1 or 2)...
That's really sad ... :(

**Comment by JJKylee** [comment]
> It is certain that one days Moritz will include this feature in his MKVMerge.

I hope so, too.

> BTW, you can ask Staxrip not to mux, by selecting the option "No Muxing" instead of MKV.

I forgot. 😅 Thanks for the reminder. 😉

**Comment by JJKylee** [comment]
I think enough info has been communicated and so we can close this thread now. 😊

**Comment by JJKylee** [comment]
After further testing, I've found that **_remuxing_** the output `mkv` or `mp4` file to `ts` using `tsMuxeR` revives the Dolby Vision info in the mediainfo video stream metadata.

So you don't have to disable muxing. You just need to take this _extra step of remuxing the output to `ts`_.

**Comment by Salem874** [comment]
Dolby Vision Profile 8.4 supports both Dolby Vision and compatibility with HDR10+

Is there a way to use StaxRip to re-encode content in DV 8.4, whilst still maintaining both DV and HDR10+ support?

Is it possible to use a combination of both Dolby Vision and HDR10+ workflows highlighted above?
