### ISSUE TITLE
How to check script output Bit-depth?

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#688]
Hello everyone.

As far as i know some filters prosess high bit-depth but return to 8bit or need some parameters for high bit-depth output, i want to feed encoder with high bit-depth as possible.
Are there a way to check script output bit-depth?

**Comment by JJKylee** [comment]
http://avisynth.nl/index.php/High_bit_depth

**Comment by darkcity87** [comment]
@JJKylee 
Great. What i want thanks.

I must poke more, I looked the features are there
