### ISSUE TITLE
Frames repeats after encoding, leads to audio & subtitles out of synch

### ISSUE THREAD

**Issue by inter5tella** [staxrip/staxrip#691]
After encoding a video file to HEVC using XViD with a .ass subtitle as a source, the output seems to be out of sync after a few seconds. You can clearly see that some frames at the beginning of the videos are repeating and gaps of 2-4 seconds will be created to the sound and the subtitles.
The encoded file itself has no longer duration because of that, it just seems to repeat some frames and do a jump after that.

I've already tried different types of media players (in precise, VLC, mpv.net, Plex Desktop & Android) and all of them show some tested key scenes from the source file in sync. But after encoding, the video is not synced with audio & subtitles anymore.
A file comparison within staxrip shows exactly the same frame on each timestamp of both files, but no media player was capable to play the encode without de-synch.

The source file is part of a season that was using the same codec in the source files and all of these files were re-encoded with the same settings due to using batch-encode. Only the last 4 files are affected by the described issue.

Mediainfo:

> Count                           : 332
Count of stream of this kind    : 1
Kind of stream                  : General
Stream identifier               : 0
Unique ID                       : 28932672407270877338617005428315818513
Unique ID                       : 28932672407270877338617005428315818513 (0x15C43AE254A267F736E6F3BE55688A11)
Count of video streams          : 1
Count of audio streams          : 1
Count of text streams           : 1
Video_Format_List               : MPEG-4 Visual
Video_Format_WithHint_List      : MPEG-4 Visual (XviD)
Codecs Video                    : MPEG-4 Visual
Audio_Format_List               : AAC LC
Audio_Format_WithHint_List      : AAC LC
Audio codecs                    : AAC LC
Audio_Language_List             : ja
Text_Format_List                : ASS
Text_Format_WithHint_List       : ASS
Text codecs                     : ASS
Text_Language_List              : de
Complete name                   : E:\Downloads\Mahoromatic S2\[GFE]Mahoromatic_S2_11_[4F60E12B]_new.mkv
Folder name                     : E:\Downloads\Mahoromatic S2
File name extension             : [GFE]Mahoromatic_S2_11_[4F60E12B]_new.mkv
File name                       : [GFE]Mahoromatic_S2_11_[4F60E12B]_new
File extension                  : mkv
Format                          : Matroska
Format/Url                      : https://matroska.org/downloads/windows.html
Format/Extensions usually used  : mkv mk3d mka mks
Commercial name                 : Matroska
Format version                  : Version 4
File size                       : 252221264
File size                       : 241 MiB
File size                       : 240.5 MiB
Duration                        : 1452116
Duration                        : 24mn 12s
Duration                        : 24mn 12s 116ms
Duration                        : 00:24:12.116
Duration                        : 00:23:43:16
Duration                        : 00:24:12.116 (00:23:43:16)
Overall bit rate                : 1389538
Overall bit rate                : 1390 Kbps
Frame rate                      : 21.597
Frame rate                      : 21.597 fps
Frame count                     : 31322
Stream size                     : 1227422
Stream size                     : 1.17 MiB (0%)
Stream size                     : 1 MiB
Stream size                     : 1.2 MiB
Stream size                     : 1.17 MiB
Stream size                     : 1.171 MiB
Proportion of this stream       : 0.00487
IsStreamable                    : Yes
Title                           : [GFE]Mahoromatic 11 - Ein Wunsch, die Farbe der Kirschblueten
Movie name                      : [GFE]Mahoromatic 11 - Ein Wunsch, die Farbe der Kirschblueten
Encoded date                    : UTC 2021-05-04 01:58:09
File creation date              : UTC 2021-05-04 01:58:09.605
File creation date (local)      : 2021-05-04 03:58:09.605
File last modification date     : UTC 2021-05-04 01:58:11.747
File last modification date (local): 2021-05-04 03:58:11.747
Writing application             : mkvmerge v56.0.0 ('Strasbourg / St. Denis') 64-bit
Writing library                 : libebml v1.4.2 + libmatroska v1.6.4
Attachments                     : Cassia Regular.ttf / Chick.ttf / cobb.ttf / One Stroke Script LET Plain_.ttf / ResPublica.ttf / RustysHand Regular.ttf / Staccato 222 BT.ttf / Tahoma.ttf

>Video
Count                           : 377
Count of stream of this kind    : 1
Kind of stream                  : Video
Stream identifier               : 0
StreamOrder                     : 0
ID                              : 1
Unique ID                       : 1766918845
Format                          : MPEG-4 Visual
Commercial name                 : MPEG-4 Visual
Format profile                  : Advanced Simple@L5
Format settings                 : BVOP2 / QPel
Format settings, BVOP           : 2
Format settings, QPel           : Yes
Format settings, GMC            : 0
Format settings, GMC            : 0 warppoint
Format settings, Matrix         : Default (H.263)
Internet media type             : video/MP4V-ES
Muxing mode                     : MuxingMode_PackedBitstream
Codec ID                        : V_MS/VFW/FOURCC / XVID
Codec ID/Hint                   : XviD
Codec ID/Url                    : http://mediaarea.net/XVID
Duration                        : 1450326.000000
Duration                        : 24mn 10s
Duration                        : 24mn 10s 326ms
Duration                        : 00:24:10.326
Duration                        : 00:23:43:16
Duration                        : 00:24:10.326 (00:23:43:16)
Bit rate                        : 1226570
Bit rate                        : 1227 Kbps
Width                           : 720
Width                           : 720 pixel
Height                          : 480
Height                          : 480 pixel
Sampled_Width                   : 720
Sampled_Height                  : 480
Pixel aspect ratio              : 1.215
Original pixel aspect ratio     : 1.000
Display aspect ratio            : 1.823
Display aspect ratio            : 1.85:1
Original display aspect ratio   : 1.500
Original display aspect ratio   : 3:2
Frame rate mode                 : VFR
Frame rate                      : 21.597
Frame rate                      : 21.597 fps
Original frame rate             : 23.976
Original frame rate             : 23.976 fps
Frame count                     : 31322
Color space                     : YUV
Chroma subsampling              : 4:2:0
Bit depth                       : 8
Bit depth                       : 8 bit
Scan type                       : Progressive
Compression mode                : Lossy
Bits/(Pixel*Frame)              : 0.164
Delay                           : 0
Delay                           : 00:00:00.000
Delay, origin                   : Container
Stream size                     : 222365966
Stream size                     : 212 MiB (88%)
Stream size                     : 212 MiB
Stream size                     : 212.1 MiB
Proportion of this stream       : 0.88163
Writing library                 : XviD0041C
Writing library                 : XviD 1.1.0 (UTC 2005-11-22)
Encoded_Library_Name            : XviD
Encoded_Library_Version         : 1.1.0
Encoded_Library_Date            : UTC 2005-11-22
Default                         : Yes
Forced                          : No

>Audio
Count                           : 280
Count of stream of this kind    : 1
Kind of stream                  : Audio
Stream identifier               : 0
StreamOrder                     : 1
ID                              : 2
Unique ID                       : 14643683833126283333
Format                          : AAC
Format                          : AAC LC
Format/Info                     : Advanced Audio Codec Low Complexity
Commercial name                 : AAC
Format_AdditionalFeatures       : LC
Codec ID                        : A_AAC-2
Duration                        : 1452096.000000
Duration                        : 24mn 12s
Duration                        : 24mn 12s 96ms
Duration                        : 00:24:12.096
Duration                        : 00:24:08:11
Duration                        : 00:24:12.096 (00:24:08:11)
Bit rate                        : 157586
Bit rate                        : 158 Kbps
Channel(s)                      : 2
Channel(s)                      : 2 channel
Channel positions               : Front: L R
Channel positions               : 2/0/0
Channel layout                  : L R
Samples per frame               : 1024
Sampling rate                   : 48000
Sampling rate                   : 48.0 KHz
Samples count                   : 69700608
Frame rate                      : 46.875
Frame rate                      : 46.875 fps (1024 SPF)
Frame count                     : 68067
Compression mode                : Lossy
Delay                           : 20
Delay                           : 20ms
Delay                           : 00:00:00.020
Delay, origin                   : Container
Delay relative to video         : 20
Delay relative to video         : 20ms
Delay relative to video         : 00:00:00.020
Stream size                     : 28603868
Stream size                     : 27.3 MiB (11%)
Stream size                     : 27 MiB
Stream size                     : 27.3 MiB
Stream size                     : 27.28 MiB
Proportion of this stream       : 0.11341
Language                        : Japanese
Language                        : jpn
Default                         : Yes
Forced                          : No

>Text
Count                           : 238
Count of stream of this kind    : 1
Kind of stream                  : Text
Stream identifier               : 0
StreamOrder                     : 2
ID                              : 3
Unique ID                       : 783458530449960846
Format                          : ASS
Format/Url                      : http://ffdshow.sourceforge.net/tikiwiki/tiki-index.php?page=Getting+ffdshow
Commercial name                 : ASS
Codec ID                        : S_TEXT/ASS
Codec ID/Info                   : Advanced Sub Station Alpha
Duration                        : 1438120.000000
Duration                        : 23mn 58s
Duration                        : 23mn 58s 120ms
Duration                        : 00:23:58.120
Bit rate                        : 133
Bit rate                        : 133 bps
Frame rate                      : 0.229
Frame rate                      : 0.229 fps
Frame count                     : 330
Count of elements               : 330
Compression mode                : Lossless
Stream size                     : 24008
Stream size                     : 23.4 KiB (0%)
Stream size                     : 23 KiB
Stream size                     : 23.4 KiB
Stream size                     : 23.45 KiB
Proportion of this stream       : 0.00010
Language                        : German
Language                        : deu
Default                         : No
Forced                          : No

Here you will find the log:
[[GFE]Mahoromatic_S2_11_[4F60E12B]_new_new_staxrip.log](https://github.com/staxrip/staxrip/files/6424067/GFE.Mahoromatic_S2_11_.4F60E12B._new_new_staxrip.log)

No additional filters have been used.

Do not hesitate to ask me for source and encoded file. I'm just not sure how to provide without breaking any rules.

**Comment by JJKylee** [comment]
So, your original statement was kind of misleading. The **source** is _Xvid_ (MPEG-4 ASP) and you encoded it to _HEVC_ using _**x265**_.

Anyway... This is about _putting back the extracted(demuxed) timestamps file of a **VFR** `mkv` source to the output `mkv` file_.

> Frame rate mode : **VFR**
> Frame rate : 21.597
> Frame rate : 21.597 fps

Don't forget to include the extracted timestamps file, `[...]_new_timestamps.txt`, _manually_ in `MKV Container Options` > `Options` > `Timestamps`.

![StaxRip_2 5 0_mkv_timestamps_20210504](https://user-images.githubusercontent.com/3157518/117081186-44ba7480-acf4-11eb-9a8e-d1bdf64f2bbc.png)

As of now, StaxRip can extract the timestamps of a _VFR_ mkv source, but cannot _automatically_ remux the timestamps file back to the output mkv. It is still remaining as a feature request (because there have been no VFR mkv samples so far). See #373.

If you're willing to provide such sample files, maybe it will help @Dendraspis or @stax76 introduce this feature in future releases. 😝

**Comment by 44vince44** [comment]
**Here are two ways to fix your problem:**

### 1) Include the timestamps file, method described by @JJKylee in the above post

Your log shows that the timestamps file is:
[GFE]Mahoromatic_S2_11_[4F60E12B]_new_timestamps.txt

So, just browse to it as shown in the post above.

### 2) Convert to Constant Frame Rate
This method is recommended if you must trim inside the video.
Here is a guide:
https://github.com/staxrip/staxrip/wiki/How-to-edit-a-VFR%28Variable-Frame-Rate%29-video-%28from-smartphones%2C-etc%29-avoiding-audio-sync-issues-in-StaxRip

**Comment by inter5tella** [comment]
@JJKylee @44vince44 Many thanks for your explanation. I will give this a try and check back after the results.

Indeed, I'm willing to offer the sample files to you. How will it be able to send them to you in a not-so-public way?

**Comment by 44vince44** [comment]
Don't worry, you'll probably not need to send us samples, because I found another VFR file that we can use for testing purpose. Thanks anyway 😃

**Comment by inter5tella** [comment]
Retested and worked like a charm.
Indeed, my description was not that perfect and maybe misleading, but thanks both of you to still understand it anyway. Also a big thanks for your clear advice. Tbh, I wasn't even aware that something like VFR was existing...
