### ISSUE TITLE
'Show progress header' option missing for latest DJATOM's mod x264 build

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#696]
StaxRip version: v2.5.0

In trying out [DJATOM's new x264 mod build (163-r3059+16-aMod)](https://github.com/DJATOM/x264-aMod/releases/tag/r3059%2B16), I've found that _Show progress header_ option is missing (in _Input/Output 3_).

![StaxRip_2 5 0_x264_DJATOM-mod_show-progress-header_option_missing_20210508](https://user-images.githubusercontent.com/3157518/117546144-dd474200-afdd-11eb-98bf-2705743c93af.png)

(Refer to [this wiki document](https://github.com/staxrip/staxrip/wiki/x264-x265-Customized-Progress-Text-Tweaks) to see what it used to be like.)

As a result, the _progress header_ without its content appears in the processing window unless `--no-progress-header` option is put explicitly in the _Custom_ field.

![StaxRip_2 5 0_x264_DJATOM-mod_progress-header_in_Processing_20210508](https://user-images.githubusercontent.com/3157518/117546310-aaea1480-afde-11eb-85b3-6216c0644f07.png)

Plz take a look. 🙏

**Comment by DJATOM** [comment]
It weirdly shows GCC 10.2.1 while I'm now using 10.3
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\m64-103\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/msys64/m64-103/bin/../libexec/gcc/x86_64-w64-mingw32/10.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: /home/ma/m/source/gcc-g/configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-nls --enable-languages=c,c++,objc,obj-c++ --with-gmp=/home/ma/m/build/for_target --with-mpfr=/home/ma/m/build/for_target --with-mpc=/home/ma/m/build/for_target --with-isl=/home/ma/m/build/for_target --enable-twoprocess --disable-libstdcxx-pch --disable-win32-registry --disable-shared --enable-fully-dynamic-string --prefix=/home/ma/m/target --with-sysroot=/home/ma/m/target
Thread model: win32
Supported LTO compression algorithms: zlib
gcc version 10.3.0 (GCC)
```

**Comment by 44vince44** [comment]
@DJATOM this is logged information that StaxRip reads from what has been set in StaxRip's app manager. @JJKylee must have probably written 10.2.1 when he was told to input the version number of the new exe.

**Comment by JJKylee** [comment]
@DJATOM,

@44vince44 is right. I put in GCC version number on my own 'cuz I couldn't get the compiler info from the console help or anywhere else. 😝

**Comment by Dendraspis** [comment]
@DJATOM 
In the last build, when this feature was implemented, your name was printed out when calling `x264.exe --version`. The current version returns just:
```
x264 0.163.3059+16 780a775
(libswscale 5.8.100)
(libavformat 58.65.101)
(ffmpegsource 2.40.0.0)
(lsmash 2.16.1)
built on May  8 2021, gcc: 10.3.0
x264 configuration: --chroma-format=all
libx264 configuration: --chroma-format=all
x264 license: GPL version 2 or later
libswscale/libavformat/ffmpegsource license: GPL version 3 or later
```

When you could add **DJATOM** to it, for example behind the version number, StaxRip could recognize your versio and show the mentioned option again.  🙂

**Comment by DJATOM** [comment]
Well, OK, I thought I have patched all needed stuff. Time to amend commits again.

**Comment by JJKylee** [comment]
C'mon, @DJATOM. Don't be shy. You deserve credit for the mod. 😁

**Comment by DJATOM** [comment]
Anyway I just added new release (under the same tag). Just re-download.

**Comment by DJATOM** [comment]
https://github.com/staxrip/staxrip/blob/master/Source/Encoding/x264Enc.vb#L923
I'm not a visual basic expert, but is that it?

**Comment by JJKylee** [comment]
Seems like there's an inappropriate parameter in the source.

`x265Type` ⇨ `x264Type`

But again, there's no criterion in the code to distinguish b/w Patman's x264 build and DJATOM's x264 build.

Let's hope @Dendraspis will fix this nicely. 😁

**Comment by Dendraspis** [comment]
@DJATOM 
Nobody is a VB.NET expert - the language is too weird.
But of course this was the problem. 👍   Haven't checked it further without a proper x264 version tag. But thanks for helping. 🙂 

So nobody recognized the bug when we used *DJATOM builds* because both x264 and x265 were from @DJATOM and the check checked the x265 version. 😁  Now using builds from different coders, this doesn't work anymore - obviously.  😂 

I fixed the issue and checked it  ..  and it works like a charm.

**Comment by Dendraspis** [comment]
@DJATOM 
I must apologize for the confusion and providing wrong information.  😞   I should have gone to bed yesterday a "bit" earlier.
Your build provides the same output as the original one. So the switch should always be visible, except when it recognizes the modified builds by Patman that don't have the header. So this means:  Your builds don't have to be *signed* by you. Seems I was in *x265* mode yesterday.  🙄 
**Sorry for that!** 😞

**Comment by DJATOM** [comment]
No problem. Now it prints mod author via `--version`, it's easier to distinguish between them.

**Comment by JJKylee** [comment]
I'm afraid this issue is _not_ properly fixed yet.

In testing @Patman86's new x264 build, [`x264-0.163.3059+11-1aa8b82-[Mod-by-Patman]`](https://github.com/Patman86/x264-Mod-by-Patman/releases), I've found that this `Show progress header` option shows up in the Options window. As this parameter option is missing from his build, this results in an error.

See this:

![StaxRip_2 5 9_Patman-x264_wrong_option_20210518](https://user-images.githubusercontent.com/3157518/118666972-73caee80-b7a8-11eb-9a08-d6a3a5d5502c.png)

Just in case, his signature exists in `--version`:

```
x264 0.163.3059+11 1aa8b82 [Mod by Patman]
(libswscale 6.0.100)
(libavformat 59.2.100)
(ffmpegsource 2.40.0.0)
(lsmash 2.16.1)
built on May 18 2021, gcc: 10.3.0
x264 configuration: --chroma-format=all
libx264 configuration: --chroma-format=all
x264 license: GPL version 2 or later
libswscale/libavformat/ffmpegsource license: GPL version 2 or later
```

**Comment by Dendraspis** [comment]
💣 💣 💣 💣 💣 💣 💣 💣  😲  💣 💣 💣 💣 💣 💣 💣 💣 

I fixed the problem .... now ... again.  🙄 
Totally weird, so either x264 changed its output stream or I'm completely lost.  But I also had no ambition to research the reason. 🤐 

Btw:  the astonished emoji in between the bombs .... that's you, @JJKylee  😜
