### ISSUE TITLE
Make it possible to drag-n-drop files to the video comparison

### ISSUE THREAD

**Issue by inter5tella** [staxrip/staxrip#697]
Adding a file to the 'video comparison' is only possible by browsing. Adding them via drag-n-drop would make some situations much easier.

By now you can only add a file to the video comparison by browsing through your filesystem. This will take some time if you use an in-depth folder structure i.e. of extras/specials etc. on network-connected storage.

A drag-n-drop feature would make things easier if you have already opened the destination folder in your file explorer

All my video files are stored on a NAS in my home network and I'm upscaling SD files to 720p/1080p. After the upscaling is done, I check the re-encoded files with the video comparison feature. Mostly, I've already opened the folder of the mentioned files on my file explorer but have to add them to the comparison by dig into the sub-folders again to select the files.

Screenshot of being not allowed to paste files:
![grafik](https://user-images.githubusercontent.com/12923644/117550928-41e8b800-b043-11eb-944f-0d1db46dff14.png)

**Comment by Dendraspis** [comment]
It is implemented and will be available with the next release.
I also changed the default behavior a bit when opening the comparison, so that it auto loads the source file.
