### ISSUE TITLE
Add slider to video comparison tool

### ISSUE THREAD

**Issue by ukmark62** [staxrip/staxrip#699]
Would it be possible to add a slider to the video comparison tool? Many thanks.

**Comment by 44vince44** [comment]
Please can you explain more ? What kind of slider you want ? what would that slider do ?

**Comment by Dendraspis** [comment]
...and why you didn't use and fill out the ***Request a feature*** template?  Would have helped a lot.

**Comment by ukmark62** [comment]
I'll close this issue and open a new request with more info.
