### ISSUE TITLE
tools that need to be updated

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#7]
Hey, post here filters that need to be updated.

TemporalDegrain2

**Comment by stax76** [comment]
NVEnc v4.42: https://github.com/rigaya/NVEnc/releases
QSVEnc v3.21: https://github.com/rigaya/QSVEnc/releases

**Comment by iAM261917** [comment]
qaac 2.68: https://github.com/nu774/qaac

**Comment by stax76** [comment]
Vapoursynth R46: https://github.com/vapoursynth/vapoursynth/releases

**Comment by stax76** [comment]
MP4Box 0.8.0: https://www.videohelp.com/software/MP4Box

**Comment by stax76** [comment]
For every tool and version there should probably be a separate issue/thread.
