### ISSUE TITLE
Change color version to B&W version

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#700]
Probably is a silly question.

But I have an old colored film and I would like to change to B&W version.

I read that AviSynth had GreyScale, buy I don't see in StaxRip.

Probably there is a newest filter that make it, but I don' find it.

Anyone could help me?

Best Regards

**Comment by 44vince44** [comment]
@papa-pitufo, use AVS filter:

COLOR > COLORYUV > TWEAK >  select "Neutral"

Then edit code, and replace sat = 1 with sat = 0.

Or simply edit code, and place wherever you want (but it must be under the source filter):
Tweak(sat=0)

**Comment by papa-pitufo** [comment]
> @papa-pitufo, use AVS filter:
> 
> COLOR > COLORYUV > TWEAK > select "Neutral"
> 
> Then edit code, and replace sat = 1 with sat = 0.
> 
> Or simply edit code, and place wherever you want (but it must be under the source filter):
> 
> `Tweak(sat=0)`

Great!!!

Thanks a lot

**Comment by JJKylee** [comment]
Another 'simple' method is putting [`Greyscale()`](http://avisynth.nl/index.php/GreyScale) beneath the source filter. 😄

![StaxRip_2 5 0_Code-Editor_add_Empty-Filter_20210509](https://user-images.githubusercontent.com/3157518/117583083-0ccb7c80-b0ba-11eb-92a5-b56851ff9cd5.png)

**Comment by Dendraspis** [comment]
If anybody has the ambition to create a filter profile for that .... feel free.  😉

**Comment by JJKylee** [comment]
@Dendraspis,

I thought `Greyscale()` is so simple that it is not even worth a pull request. 😋

![StaxRip_2 5 0_AVS_filter-profiles_Grayscale_20210509](https://user-images.githubusercontent.com/3157518/117583344-8d3ead00-b0bb-11eb-9c18-c1374d1624f3.png)

**Comment by JJKylee** [comment]
OK. I will.

BTW, is there any difference b/w those two approaches? I can't see any. 🙄❓

**Comment by Dendraspis** [comment]
Depends how `Grayscale` works, but I guess they produce the same result, because setting the saturation to 0 is the easiest way to do that.

**Comment by JJKylee** [comment]
Exactly.
Sometimes there are too many methods to do just one single thing. 😝

**Comment by papa-pitufo** [comment]
Hi everybody

I would like to write in filter folder, Greyscale or Grayscale (which one?), and i don't find the Greyscale filter, coould anyone attached it?

And finally

Must I copy/paste:
Grayscale | Desaturate = Tweak(sat = 0)
Grayscale | Grayscale = Grayscale()

Like JJKylee write it?


Best regards

**Comment by JJKylee** [comment]
> I would like to write in filter folder, Greyscale or Grayscale (which one?), and i don't find the Greyscale filter, coould anyone attached it?

`Greyscale` = `Grayscale`. The spelling doesn't matter.
It's an internal filter that's natively available in AviSynth. Which means you don't need any extra stuff.
Internal filters are readily available in StaxRip. You just need to add an extra empty filter line in the _Code Editor_.
 
> Must I copy/paste:
> Grayscale | Desaturate = Tweak(sat = 0)
> Grayscale | Grayscale = Grayscale()
> 
> Like JJKylee write it?

Put them in `AVS Filters` > `Profiles...`.

> P.D.: please take note that I am a simple learner

If you are a learner, then start with the [AviSynth wiki](http://avisynth.nl/index.php/Main_Page) and StaxRip wiki documents here.
If I were you, I would first take time to read recent posts in Doom9's forum, StaxRip documents, etc.

**Comment by papa-pitufo** [comment]
Ok, thank you very much for your help.

**Comment by papa-pitufo** [comment]
Hi everybody

I think there is a confict when I write GrayScale in Profiles AVS,

I put both types os GrayScale in Misc section.

I reset StaxRip

I select my BD folder, but It takes much longer than it already took and we knew!!! Close to 60min!!!

Finally I have my work, 

I try to select Grayscale and Desaturate (by example), I push OK, and StaxRip freeze (no response), during 15min!!!!

Finally I have my filter.

Ok, I push run and theorically show me a screen with FFmpeg, x264, etc., I said theorically, because in fact StaxRip freeze again (no response), now during 10 min.  Then work right.

I remove GrayScale and reset.

everything goes back to normal


Have I done something wrong? or is a bug? Or GrayScale is a special filter that produces this delay?

Best Regards

P.D.: I think this question should be here nor in discussion module, but if it's not, my apologize.

**Comment by papa-pitufo** [comment]
> There are so many possibilities depending on your source. We don't know anything about it, so we can't tell.

Ok, thanks I'll keep going test

**Comment by papa-pitufo** [comment]
oops, sorry
