### ISSUE TITLE
Demux preferred languages but don't include them

### ISSUE THREAD

**Issue by creeve4** [staxrip/staxrip#704]
**Describe the bug**
When selecting "Demux preferred languages but don't include them" from Options>Subtitles, subtitles are still added to the output file and can be found in Container Options.

**Expected behavior**
Unless I misunderstand the "Demux preferred languages but don't include them" option, subtitles shoudl be demuxed, but not included in the output container.

**How to reproduce the issue**
Using Automatic workflow:
1. From Options>Subtitles select "Demux preferred languages but don't include them".
2. Add any source file with subtitle tracks.
3. Open the Container Options menu and observe the subtitle tracks that have been added.

**Provide information**
- StaxRip version 2.5.0

**Comment by Dendraspis** [comment]
@creeve4 
Of course they are added to the muxer configuration, but all of them are **not enabled**. Please re-check this.

![SR](https://user-images.githubusercontent.com/50659978/118049335-e3db0e00-b37d-11eb-8ea8-82f8713ba141.JPG)

**Comment by creeve4** [comment]
I am a fool. Thank you for pointing this out to me!

**Comment by Dendraspis** [comment]
No problem, depending of what you expect, this can be difficult to see.
Gladfully we could solve it pretty fast. 🙂
