### ISSUE TITLE
Problem embedding JPEG images

### ISSUE THREAD

**Issue by D0LLYNH0** [staxrip/staxrip#706]
As of version "MP4Box 1.1.0 rev506 gcc10.2 Patman", several jpeg images are not embedded correctly, they are no longer displayed as a cover, but are added to the container.
I can't tell what the difference is between images that are embedded and those that are not, but any image edited in Photoshop and exported as a jpeg is not embedded correctly.
Reverting to the version "MP4Box 1.1.0-rev447-g8c190b551-gcc10.2.0 Patman" solved the problem.

**Comment by 44vince44** [comment]
@D0LLYNH0  This is a tool issue, thanks for reporting it, however we would appreciate if you report it directly to the coders of MP4Box, here:
https://github.com/gpac/gpac/issues

That would be of great help, none of the coders of staxrip actually uses Mp4Box to mux, this is why we didn't notice it!

**Comment by D0LLYNH0** [comment]
@44vince44, thanks for the reply, I already [reported](https://github.com/gpac/gpac/issues/1790) to those responsible.

**Comment by 44vince44** [comment]
@D0LLYNH0 Thanks, I saw it ! That helps us very much!

**Comment by D0LLYNH0** [comment]
Bug [fixed](https://github.com/gpac/gpac/commit/67b51ece19fb3b326bde6bd89baeb22c632634d0), so I will close this issue. Thanks.

**Comment by Dendraspis** [comment]
@Patman86 
Seems like we would need an update.  😉  👀 

@D0LLYNH0 
Thanks for the information.  👍

**Comment by Patman86** [comment]
@Dendraspis DONE!!! 😁😜
