### ISSUE TITLE
Audio right-click text color

### ISSUE THREAD

**Issue by almanteka** [staxrip/staxrip#709]
is possible for the text "right-click" of the audio input be colored to red for example? just the right-click word, that way if there is no audio from the source file, there is an indicator that can be easily seen! there is no need to be red, any color can make the difference! thanks for the great work!

![staxaudio](https://user-images.githubusercontent.com/42816936/118420092-f316d000-b68b-11eb-9b8e-f3d37b292fe2.jpg)

**Comment by 44vince44** [comment]
Careful: red color is reserved for blocking messages. _No audio_ is not a blocking status.

**Comment by almanteka** [comment]
as a quote from the original message

> there is no need to be red, any color can make the difference!

**Comment by Dendraspis** [comment]
@almanteka 
I'm pretty sure his comment was addressed to me, with at least 50%.  😁 

I'm still thinking of a good solution .... will take a bit.

**Comment by almanteka** [comment]
hahaha! sorry!
![staxaudio2](https://user-images.githubusercontent.com/42816936/118542278-cc56a900-b720-11eb-981a-807a1d80b799.jpg)

**Comment by Dendraspis** [comment]
Sorry, we won't change it in any way.

Using a dark theme makes "right-click" a bit less visible, because the placeholder is written in system colors. 

![image](https://user-images.githubusercontent.com/50659978/119179301-0b616300-ba6f-11eb-9652-12cf0e9e272d.png)

Using a color, that catches the eye, would interfere with the Assistant. As everywhere else you have to (quick) check the settings before you proceed.
If there are (much) more requests, we could re-think it, but not at the moment.

**Comment by almanteka** [comment]
thanks! i understand the problem with the text color! what about using an option in the assistant to remind that there is no audio file? these are just suggestions, thanks for even considerate it! keep up the great work!

![staxaudio3](https://user-images.githubusercontent.com/42816936/119243341-b89daf00-bb33-11eb-959d-341285b8d084.jpg)

**Comment by Dendraspis** [comment]
I totally forgot about the Assistant settings .... way too obvious.  😂 
Good idea!  👍 

It will be available from now on. Here is the latest DEV version:
[StaxRip_v2.6.2.zip](https://github.com/staxrip/staxrip/files/6527928/StaxRip_v2.6.2.zip)

**Comment by almanteka** [comment]
thanks!!! 

![image](https://user-images.githubusercontent.com/42816936/119272174-b6d6f880-bbd2-11eb-9b37-d6b66b28d388.png)

**Comment by almanteka** [comment]
![staxaudio5](https://user-images.githubusercontent.com/42816936/119285196-88c3d980-bc0f-11eb-9cf9-1919a9fb3597.jpg)


nice touch! wonderful!!!
