### ISSUE TITLE
Maybe not a bug, but preview video file changed from before

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#71]
Hi again Stax,

When using external player mpv.net (from the preview window or from the AVS Filters menu),
the file played is Filename.avs
Before, the latest changes it was Filename**_play**.avs

And now there is no more Filename**_play**.avs generated in the temp folder.

In the code (Forms/CodeEditor.vb), from the Sub PlayScriptWithMpvnet():  
script.Path = p.TempDir + p.TargetFile.Base + "_play." + script.FileType
Shouldn't the command to play with mpv.net use this sub? 

I saw the difference because now the preview video in mpv.net has colormatrix handled differently!

**Comment by stax76** [comment]
Yes I think there was still an issue, please try 2.0.4.9.

**Comment by 44vince44** [comment]
Yes, it is fixed indeed. Thank you very much! I'll continue testing other things tomorrow.

**Comment by 44vince44** [comment]
So far everything works OK, thank you for the excellent work !!
