### ISSUE TITLE
x264 16 bit support

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#711]
I am getting this error

![image](https://user-images.githubusercontent.com/2351785/118712637-5128ec00-b821-11eb-80e6-d5cad50dd358.png)

when trying to directly feed a AVS with 16 bit depth to JP latest x264 build.

That build supports direct AVS with no need for pipe.

Would you please test and remove that warning when such build is found or, at least, give the possibility to push the next button ignoring such warning?

**Comment by 44vince44** [comment]
@Dendraspis : This is merely a feature request to make Staxrip more flexible.

**Comment by 44vince44** [comment]
@tormento 
The fix is on its way.

BUT you can make it work right now, without waiting next release.

Go in your App Manager, select x264, change version (F12), and add to the version name the suffix: `no-amod`

This will immediately cancel the error message.

**Comment by 44vince44** [comment]
@tormento

THis won't work, unfortunately the message will be gone, but you will have problem with a switch unknown to JPSDR's build (--synth-lib)

So you'll have to wait next release...

**Comment by tormento** [comment]
> @Dendraspis : This is merely a feature request to make Staxrip more flexible.

It's a blocking warning, not just a hint :)

**Comment by 44vince44** [comment]
@tormento, after @Dendraspis checked the code, it appears that the "Version Trick" that I showed you above WILL WORK !!!!

However, you will need to have AviSynth installed on your system.

You must understand that for the following reasons, Staxrip will ONLY use amod, DJATOM and Patman builds:
- proper AVS/VPY reader
- PROPER HANDLING OF AVISYNTH DLL LOCATION

So whether you use the `no-amod` trick in the version name, or wait for next build (if mod is accepted by @Dendraspis), you'll have to make sure that there is a avisynth.dll present in you system32 folder.

**Comment by Dendraspis** [comment]
I don't get the benefit of changing the build.  😕 
Also I don't want to add more build differentiations.

But I changed the code a bit which also optimizes it. After adding `amod` to the app version, as @44vince44 already mentioned above, the colorspace check will be skipped.
 

> > @Dendraspis : This is merely a feature request to make Staxrip more flexible.
>
> It's a blocking warning, not just a hint :)

Nevertheless this is a feature request.  😉

**Comment by 44vince44** [comment]
OK, So @tormento, you've got your answer from @Dendraspis , and your solution:

- add `amod` to the version name, or preferably `no-amod` but any of them would work
- make sure Avisynth is installed in your system
