### ISSUE TITLE
DGHDRtoSDR causes Script Error

### ISSUE THREAD

**Issue by Harybo** [staxrip/staxrip#712]
I used the tonemap tutorial but it gives me an error code

https://github.com/staxrip/staxrip/wiki/How-to-tonemap-HDR-to-SDR

![image](https://user-images.githubusercontent.com/29784405/119134941-118b1b80-ba3e-11eb-9da2-c1319e2abc0f.png)

**Comment by Patman86** [comment]
Have you downloaded the plugin from [here](http://rationalqm.us/hdr/)?

**Comment by Patman86** [comment]
Can you post your log file?

**Comment by Harybo** [comment]
yes I took version 1.4

I cannot have a log since I cannot start the encoding

**Comment by Patman86** [comment]
Your system is?

**Comment by Harybo** [comment]
windows 10

**Comment by 44vince44** [comment]
It seems simply that you didn't put DGHDRtoSDR.dll in the right place! 
Si le module est inrtrouvable, c'est que ta dll n'est pas au bon endroit....

**Comment by 44vince44** [comment]
OK there is a problem with the guide:

This:

> LoadPlugin("%settings_dir%Plugins\Dual\DGHDRtoSDR\DGHDRtoSDR.dll")
> DGHDRtoSDR(mode="pq", white=50)

1) you must remove the line:
`LoadPlugin("%settings_dir%Plugins\Dual\DGHDRtoSDR\DGHDRtoSDR.dll")
2) just make sure that the dll file DGHDRtoSDR.dll is in the right place. To do so:
- open Staxrip
- go to menu Tools > Folders > Settings   click on it (Settings), this opens a browser
- browse to Plugins > Dual  and copy DGHDRtoSDR.dll directly there.
Now it should work.

**Comment by Harybo** [comment]
Thanks, staxrip add row by itself when add filter. It should therefore be corrected in a future update

**Comment by 44vince44** [comment]
The Guide must be corrected, not Staxrip....

**Comment by Dendraspis** [comment]
Did it help?

If not, please post the code lines you use in CodeEditor.

**Comment by Harybo** [comment]
thank you

**Comment by 44vince44** [comment]
For the record:
- The guide is correct, the LoadPlugin line is correctly set (by JKyle) to work in all circumstances (external, internal frameserver)
- The whole problem was probably that the user did not place the dll correctly where is should have been placed, according to the guide.
