### ISSUE TITLE
External Subtitles dont get correct stream language set to it after muxing

### ISSUE THREAD

**Issue by kvanbiesen** [staxrip/staxrip#714]
**Describe the bug**
External subs (.en.srt) dont get recognized as English anymore

**Expected behavior**
In version 1, if you included the external subtitles next to a movie in .en.srt ending with the same name, the track title automaticly gets set to to english (if it was .nl.srt, it was was set to dutch)

Now it it leaves it blank, or if it set it in option s to native stream, it sets it to invariant country (for all tracks).

Tracks That are included in the mkv with proper headings gets copied withouth issues, its with external ones that has the problem.

Using staxrip 2.4..

I tested same video with staxrip 2.1.8.0, and does it correctly. (the i left the track name empty)

Now i have to set the subtrack of all the with mkvpropedit afterwards.

**Comment by Dendraspis** [comment]
I checked the code back to v2.1.5.5 and it also did not work that way.

You have to use the whole correct English name in the file name. For example:

`Holiday.mkv`
`Holiday_English.Forced.srt`
`Holiday.french.srt`
`Holiday.german_forced.srt`


> I tested same video with staxrip 2.1.8.0, and does it correctly. (the i left the track name empty)

This only happens with SUB/IDX subtitles, where the language can be (and is) read out.

**Comment by kvanbiesen** [comment]
Weird, on version 2.1.8.0 it seemed to work. But now that i know i just have to use the full names, its not much if on issue. I'll Work it this way. Thanks for the help :)

**Comment by Dendraspis** [comment]
You're welcome!

**Comment by 44vince44** [comment]
@kvanbiesen If I remember correctly, the language name must be spelled entirely, and fort letter must be capital...
