### ISSUE TITLE
Can we preselect audios base on demuxed audios ID numbers before adding source files for batch process

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#715]
**Is your feature request related to a problem? Please describe.**
If there is multiple audios from same language (main audio+commentary) or have more than 2 audios setting audio order cant possible with batch process need to externally encode and mux again.

**Describe the solution you'd like**
If we can select audios base on audio ID number before adding source file everything done internally make it simple.

I know there is options>audio>Preferred languages options but this not exactly doing what i descript.

Example=
-------------
Source:
ID2=eng main audio
ID3=...... dub
ID4=...... dub
ID5=eng commentary

Staxrip main page audio:
audio 1=ID2
audio 2=no audio
------------
Source:
ID2=jpn original audio
ID3=...... dub
ID4=...... dub
ID5=eng dub
ID6=...... dub
...

Staxrip main page audio:
audio 1=ID2
audio 2=ID5
-------------

**Describe alternatives you've considered**

**Explain why the feature matters to you**
This is not problem for few files but dealing many files one by one take really some time and need to check audio language check everthing one by one.

--------------
If this is hard to make or declined for any reason i appreciate anyway.

**Comment by almanteka** [comment]
what happens when you select the preferred languages under options > audio?

![image](https://user-images.githubusercontent.com/42816936/119272445-e5090800-bbd3-11eb-995b-60464af1aac1.png)

**Comment by darkcity87** [comment]
can i set audio order from "preferred languages"?
like
audio1: ID4
audio2: ID2

**Comment by almanteka** [comment]
i don't know exactly how it works, but, can you set preferred languages as 4 2 > demux audio to all and test it out? i can't test it right now, i'll try it later.

**Comment by almanteka** [comment]
well, i use the preferred language IDs as 4 2 > demux audio to preferred languages, but the first audio is not 4, but 2, then 4. i think staxrip should use 4 as the first preferred language, then 2 when selected there

![image](https://user-images.githubusercontent.com/42816936/119279820-24e3e580-bbfc-11eb-8931-4ca51a9e2961.png)

**Comment by almanteka** [comment]
another test! if i select japanese and english as my preferred languages, or viceversa, english and japanese, the first one is the one with the lowest ID. staxrip can be adjusted to always use the preferred languages option as the order for the audio to be output and not the ID order from the source! this is just a suggestion, i know that there is so much work involved to make these type of changes!

![image](https://user-images.githubusercontent.com/42816936/119280539-e2bca300-bbff-11eb-9cbf-64eee7351f59.png)

![image](https://user-images.githubusercontent.com/42816936/119280681-71312480-bc00-11eb-8e62-2f6bbfde8d28.png)

**Comment by almanteka** [comment]
@darkcity87 , you can select the audio ID on options > audio > preferred language and select preferred languages in demux audio and create a template for the changes to be saved! just remember to use the same template for this type of project. just one thing, the lowest ID always will be the first in the output!

![image](https://user-images.githubusercontent.com/42816936/119281871-6200a580-bc05-11eb-8aa9-91a524287bab.png)

**Comment by darkcity87** [comment]
@almanteka
As you can see there is some limitations you cant determine audio order from preferred language order automatically set by lowest ID.

If developers dont want to implement this i understand they can close this issue. There is not much case people want this feature.

**Comment by almanteka** [comment]
@darkcity87 i found out something that can help you until the developers take a look on this! if you click on edit in the audio area, under language you select your preference, then, go to the second audio and do the same for the other audio! save this as a template! then open a source file, and voila! you got the audio in the order you prefer! i tested this out and worked for me using two different languages! give it a try and check if this work for you! i didn't even went to the preferences language options!

![image](https://user-images.githubusercontent.com/42816936/119383780-c36e5600-bc91-11eb-800c-a625697a7370.png)

as you can see in the next picture, the ID doesn't matter

![image](https://user-images.githubusercontent.com/42816936/119383907-f0226d80-bc91-11eb-98c3-ade0b065ae1f.png)

**Comment by Dendraspis** [comment]
It's not that easy, because every step has multiple dependencies.

But I think making the *preferred languages* handle the order should work here and makes overall sense.

But it will take a while...

**Comment by almanteka** [comment]
> It's not that easy, because every step has multiple dependencies.
> 
> But I think making the _preferred languages_ handle the order should work here and makes overall sense.
> 
> But it will take a while...

yes, preferred languages is the way to go! thanks!

**Comment by darkcity87** [comment]
I tought selecting audio order from ''Audio Mux Options'' easier because when you selecting audio language in ''Audio Mux Options'' its calling matched language audio to that line. I tought instead calling audio base on language we can call audio to that line base on audio ID.

Example=
''preferred languages'' demux all or choose what you want

Audio=1
''Audio Mux Options''
Select audio from demuxed audio base on ID: ID5
Language=...

Audio=2
''Audio Mux Options''
Select audio from demuxed audio base on ID: ID2
Language=...

If  ''Select audio from demuxed audio base on ID:'' empty or no selected calls audio base on language+lowest ID like existing now.

After adding source file Audio>Rightclick already list audios base on ID im just saying selecting audios before adding source file.

I tought this easier no change on ''preferred languages'' and less dependencies but i dont know anything about programing i can be completely wrong or not suit for staxrip. You know better.

**Comment by almanteka** [comment]
if you like to pre-select audios before adding source, you can create a template that includes your preferences. but right now, without the ID preference sort, is not possible for one ID to be the first selection. on the other way, the language ID, you can select which one is your preferred before adding the source and you can keep this order using a template.

**Comment by almanteka** [comment]
there are 9 profiles there for AAC, MP3, AC3, etc. etc. i think that, to accommodate a new option, each of them will need to be re-worked! i'm just assuming, i'm not a coder or developer either.

**Comment by Dendraspis** [comment]
@darkcity87 
Even if it doesn't look like so, I'm still on it and already re-wrote 70% of the track loading algorithms...

**Comment by jlw4049** [comment]
Any progress on this at all? 

I didn't even know about the ID feature. Can this be added to the docs?

**Comment by Dendraspis** [comment]
Still in pipeline, actually thought about it last week. I'll try to bring it a bit more up....
