### ISSUE TITLE
BUG: preview window and cutting : every preview window makes a new cutting filter when closed

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#72]
Hi Stax,

in Beta 2.0.4.9:
This bug appears when you use cutting and you open several preview windows for comparison.
Here' how to reproduce the bug:
1. open video
2. open preview, create range
3. close preview
4. open preview, do not close
5. open another preview window
6. close the two preview windows

Result:  you get 2 identical cutting filters (there should be only one). If you open preview again, Staxrip crashes with an overflow error.

Thanks for checking !

**Comment by stax76** [comment]
Hello Vince,

I could reproduce the trim filter being added more than one time but not the crash.

Sorry about all the bugs recently, I've uploaded a new build:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by 44vince44** [comment]
Thank you for all the good work Stax, i should be sorry not you, for harassing you with bug reports ;-)

**Comment by 44vince44** [comment]
It seems fixed all right! thanks for all the good work Stax!
