### ISSUE TITLE
UI Not Setting NVEnc --vpp-pad Switch Values Correctly

### ISSUE THREAD

**Issue by AYColumbia** [staxrip/staxrip#723]
I just grabbed the latest version so am on 2.6.0.

**Describe the bug**
Setting padding value(s) does not add all 4 (l,t,r,b) values for --vpp-pad.  Setting top and bottom only causes error: `Error: Invalid value "60,60" for "--vpp-pad"`

**Expected behavior**
Switch values for setting top and bottom padding of 60.  Switch expected to render as:
--vpp-pad=0,60,0,60

**How to reproduce the issue**
1. Select the NVidia H264 encoder
2. Click **Encoder Options** to configure
3. Configure generic
4. Now go to **VPP** to **Misc 2**
5. Check to enable the **Padding** section
6. Set only top and bottom to anything other than 0
7. Note in the preview at bottom the --vpp-pad switch is added with only the values you change from 0 (should always have all 4 once you change one to other than 0).

**Provide information**
Current NVEncC64.exe with 2.6.0:
NVEncC (x64) 5.32 (r1925) by rigaya, May 18 2021 14:30:14 (VC 1928/Win/avx2)

Reference for switch:
```
   --vpp-pad <int>,<int>,<int>,<int>
     add padding to left,top,right,bottom (in pixels)
```

**Comment by JJKylee** [comment]
Confirmed.

**Comment by Dendraspis** [comment]
Is fixed and will be included in the next release.

@AYColumbia 
Thanks for the report, which was additionally very detailed.

**Comment by AYColumbia** [comment]
Glad to help. Thank you.
