### ISSUE TITLE
Encoding cannot proceed if 2-pass is enabled for SVT-AV1

### ISSUE THREAD

**Issue by banjaminicc** [staxrip/staxrip#731]
The first pass creates an unreable .ivf file that mkv fails to mux and halts the second pass causing the crash
It is expected that staxrip proceeds the second pass before it initiates the muxing procedure

Any file should be able to be used to reproduce this issue simply by adding '--passes 2' into the custom option of SVT-AV1
Staxrip version used is 2.6.0

A clip of the log is provided below

```
--------------------------- Video encoding ---------------------------

SVT-AV1 0.8.7-4-g786c4dac-x64-gcc10.3.0 Patman

E:\Programmes\StaxRip-v2.6.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -i R:\Sample_temp\Sample_new.avs -f yuv4mpegpipe -strict -1 -loglevel fatal -hide_banner - | E:\Programmes\StaxRip-v2.6.0-x64\Apps\Encoders\SVT-AV1\SvtAv1EncApp.exe --passes 2 -rc 1 --preset 5 -tbr 2000 -n 302 -i stdin -b R:\Sample_temp\Sample_new_out.ivf

-------------------------------------------
SVT [version]:	SVT-AV1 Encoder Lib v0.8.7-4-g786c4dac-dirty
SVT [build]  :	GCC 10.3.0	 64 bit
LIB Build date: May 22 2021 10:20:52
-------------------------------------------
Svt[warn]: The 2-pass encoding support is a work-in-progress, it is only available for experimental and further development uses and should not be used for benchmarking until fully implemented.
Svt[warn]: The VBR and CVBR rate control modes are a work-in-progress projects, and are only available for demos, experimental and further development uses and should not be used for benchmarking until fully implemented.
Number of logical cores available: 12
Number of PPCS 9
[asm level on system : up to avx2]
[asm level selected : up to avx2]
------------------------------------------- 
SVT [config]: Main Profile	Tier (auto)	Level (auto)	
SVT [config]: Preset 								: Pass 1 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat	: 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight					: 1920 / 1080 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType 	: 30000 / 1001 / 33 / 2
SVT [config]: HierarchicalLevels  / PredStructure				: 0 / 2
SVT [config]: BRC Mode / CQP Assignment / SceneChange				: CQP / 50 / 0 
------------------------------------------- 
warning: -rc will be deprecated soon, please use --rc
warning: -tbr will be deprecated soon, please use --tbr
Pass 1/2 Encoding          
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames		Frame Rate		Byte Count		Bitrate
         302		29.97 fps		      5506		 4.37 kbps
Channel 1
Average Speed:		100.638 fps
Total Encoding Time:	3001 ms
Total Execution Time:	4000 ms
Average Latency:	40 ms
Max Latency:		999 ms
-------------------------------------------
SVT [version]:	SVT-AV1 Encoder Lib v0.8.7-4-g786c4dac-dirty
SVT [build]  :	GCC 10.3.0	 64 bit
LIB Build date: May 22 2021 10:20:52
-------------------------------------------
Error instance 1: Source Width must be at least 64
Error instance 1: Source Width must be at least 64
Svt[warn]: The 2-pass encoding support is a work-in-progress, it is only available for experimental and further development uses and should not be used for benchmarking until fully implemented.
Svt[warn]: The VBR and CVBR rate control modes are a work-in-progress projects, and are only available for demos, experimental and further development uses and should not be used for benchmarking until fully implemented.
warning: -rc will be deprecated soon, please use --rc
warning: -tbr will be deprecated soon, please use --tbr
Pass 2/2 Encoding          
Error encoding at channel 1! Check error log file for more details ... 

Start:    2:46:01 pm
End:      2:46:06 pm
Duration: 00:00:04

General
Complete name : R:\Sample_temp\Sample_new_out.ivf
File size     : 0.00 Byte

------------------------- Error Muxing to MKV -------------------------

Muxing to MKV returned exit code: 2 (0x2)


---------------------------- Muxing to MKV ----------------------------

mkvmerge 56.1

E:\Programmes\StaxRip-v2.6.0-x64\Apps\Support\MKVToolNix\mkvmerge.exe -o R:\Sample_new.mkv --default-duration 0:29.970030fps R:\Sample_temp\Sample_new_out.ivf --ui-language en

mkvmerge v56.1.0 ('My Friend') 64-bit
Error: The file 'R:\Sample_temp\Sample_new_out.ivf' could not be opened for reading: end of file error.

---------------------------- Muxing to MKV ----------------------------

mkvmerge 56.1

E:\Programmes\StaxRip-v2.6.0-x64\Apps\Support\MKVToolNix\mkvmerge.exe -o R:\Sample_new.mkv --default-duration 0:29.970030fps R:\Sample_temp\Sample_new_out.ivf --ui-language en

mkvmerge v56.1.0 ('My Friend') 64-bit
Error: The file 'R:\Sample_temp\Sample_new_out.ivf' could not be opened for reading: end of file error.

Start:    2:46:06 pm
End:      2:46:06 pm
Duration: 00:00:00
```

**Comment by JJKylee** [comment]
Like the warning says...

```
Svt[warn]: The 2-pass encoding support is a work-in-progress, it is only available for experimental...
```

IMO, you better not bother. It's a tool issue. There's nothing that can be done on StaxRip side regarding this matter.

BTW, we need to update the command line for `SVT-AV1` anyway according the warnings:

```
warning: -rc will be deprecated soon, please use --rc
warning: -tbr will be deprecated soon, please use --tbr
```

**Comment by banjaminicc** [comment]
> Like the warning says...
> 
> ```
> Svt[warn]: The 2-pass encoding support is a work-in-progress, it is only available for experimental...
> ```
> 
> IMO, you better not bother. It's a tool issue. There's nothing that can be done on StaxRip side regarding this matter.
> 
> BTW, we need to update the command line for `SVT-AV1` anyway according the warnings:
> 
> ```
> warning: -rc will be deprecated soon, please use --rc
> warning: -tbr will be deprecated soon, please use --tbr
> ```

It's not an issue with SVT-AV1 as I'm able to use 2-pass with other GUIs and their CLI. Sounds like a staxrip issue to me

**Comment by JJKylee** [comment]
This seems more like a _feature request_ than an issue report since 2-pass encoding is still experimental even with `SVT-AV1` itself, and StaxRip hasn't implemented 2-pass encoding for `SVT-AV1` for this reason as of yet.

(BTW, IMHO, `SVT-AV1` looks kind of crude since it doesn't even support piping. 🤔)

I don't know how many people would want 2-pass encoding for `SVT-AV1`, but let's see if @Dendraspis or @stax76 is interested in implementing this 'feature'.

**Comment by Dendraspis** [comment]
> IMO, you better not bother. It's a tool issue. There's nothing that can be done on StaxRip side regarding this matter.

I would confirm, but it looks a bit strange, because the width is identified with `1920` pixels before. Maybe a width and height setting is needed. 🤔 

@banjaminicc 
What happens, if you set `-w 1920` and `-h 1080` additionally ?


Reminder:
```
warning: -rc will be deprecated soon, please use --rc
warning: -tbr will be deprecated soon, please use --tbr
```

**Comment by banjaminicc** [comment]
> 
> 
> > IMO, you better not bother. It's a tool issue. There's nothing that can be done on StaxRip side regarding this matter.
> 
> I would confirm, but it looks a bit strange, because the width is identified with `1920` pixels before. Maybe a width and height setting is needed. 🤔
> 
> @banjaminicc
> What happens, if you set `-w 1920` and `-h 1080` additionally ?
> 
> Reminder:
> 
> ```
> warning: -rc will be deprecated soon, please use --rc
> warning: -tbr will be deprecated soon, please use --tbr
> ```

It would freeze at 99.67% and does not proceed
Generating the same 0 byte file just like previously

**Comment by Dendraspis** [comment]
I've done some tests and for me the `--passes 2` param is applied correctly. The encoder starts running, so there is everything fine with StaxRip.
Almost every setting produces a `work-in-progress` message, except the default ones, that create a good output file, so....

**Comment by JJKylee** [comment]
Since @banjaminicc says as follows,

> It's not an issue with SVT-AV1 as I'm able to use 2-pass with other GUIs and their CLI. Sounds like a staxrip issue to me

we need a _working_ command line sample that _successfully_ does the 2-pass encoding with `SVT-AV1`. If the same command line fails with the `SVT-AV1` executable currently shipped with StaxRip, then it means there's some issue with @Patman86's build of `SVT-AV1`.

Plz provide the command line sample, @banjaminicc.

**Comment by Dendraspis** [comment]
I won't try to create workarounds for experimental tool features, that are not even well documented.
Further @banjaminicc said, that he used other tools to get the wanted results, **not** an *SVT-AV1* CLI app.

`--passes 2` works as command line parameter, the tool just outputs an empty file. So I'm pretty sure it's a tool issue.

**Comment by Patman86** [comment]
The problem with the --passes 2 option comes from the pipe method with FFMPEG `-f yuv4mepegpipe`. I've done some tests on this. But if you use the 2-pass procedure and use two commands, namely `--pass 1` including `--stats test_file.stat` and then `--pass 2` including `--stats test_file.stat -b output.ivf`, it works smoothly. So it's not because of SVT-AV1!!! See [here](https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/svt-av1_encoder_user_guide.md#2-pass-vbr-1000-kbps-at-maximum-quality-from-24fps-yuv-1920x1080-input)

**Comment by Dendraspis** [comment]
Duh.  🤦‍♂️ 

I'll try to implement something before the next release .... interesting adventure. 🙄

**Comment by Dendraspis** [comment]
Thanks to @Patman86 this could be added/fixed.  👍 
I've tested it with 1- pass and 2-pass and it works now.  🙄

**Comment by banjaminicc** [comment]
> Thanks to @Patman86 this could be added/fixed. 👍
> I've tested it with 1- pass and 2-pass and it works now. 🙄

Ayy you lads fixed it
Thanks a lot!
