### ISSUE TITLE
AMD X265 change codec

### ISSUE THREAD

**Issue by error105** [staxrip/staxrip#733]
There is any chance that i can convery movie using AMD X265 VCE, but with other mpeg codec than MPEG-H part2 ? My TV need MPEG2 or MPEG4 (OLED65B8PLA).

**Comment by JJKylee** [comment]
That depends on whether your AMD graphics card supports MPEG-2 or MPEG-4 encoding. But in fact, I highly doubt it.

For double check, go to _Encoder Options_ of your AMD encoder, run _Check Features_(`Ctrl`+`F`) and see if those two are supported.
