### ISSUE TITLE
No force and default Subtitle with mp4box muxer

### ISSUE THREAD

**Issue by MotorSportF1** [staxrip/staxrip#737]
Hello,

StaxRip    : v2.6.0
Container/Muxer Profile : MP4 (mp4box)

After encoding a mp4 file, I noticed that the subtitle was not tagged "force" even though I had checked the force box via mp4box of the staxrip.

I found the fix.

normal command line do with staxrip :

`D:\StaxRip\Apps\Support\MP4Box\MP4Box.exe -add "E:\Input\Movie (2020)\Movie (2020)_temp\Movie (2020)_out.mp4#video:name=" -add "E:\Input\Movie (2020)\Movie (2020)_temp\ID2 French {Surround 5.1}_1997614654.m4a#audio:lang=fre:name=French" -add "E:\Input\Movie (2020)\Movie (2020)_temp\Movie (2020).srt:lang=fre:name=Français (forced)" -chap "E:\Input\Movie (2020)\Movie (2020)_temp\Coyote Ugly.chapters.txt" -itags = -new "E:\output\Movie (2020).mp4"`

With fix this issu, just add `:txtflags=0xC0000000` after ......srt:lang=fre:name=Français (forced)
Like this :

`D:\StaxRip\Apps\Support\MP4Box\MP4Box.exe -add "E:\Input\Movie (2020)\Movie (2020)_temp\Movie (2020)_out.mp4#video:name=" -add "E:\Input\Movie (2020)\Movie (2020)_temp\ID2 French {Surround 5.1}_1997614654.m4a#audio:lang=fre:name=French" -add "E:\Input\Movie (2020)\Movie (2020)_temp\Movie (2020).srt:lang=fre:name=Français (forced):txtflags=0xC0000000" -chap "E:\Input\Movie (2020)\Movie (2020)_temp\Coyote Ugly.chapters.txt" -itags = -new "E:\output\Movie (2020).mp4"`

Possible to fix in staxrip ?

I check for default tag but not found the txtflags for that, sorry

Thanks

**Comment by JJKylee** [comment]
Confirmed.

I muxed an external `srt` subtitle file into the output `mp4` with video/audio stream copies and set the subtitle to `forced` as follows.

![StaxRip_2 6 21_MP4Box_srt_mux_forced_bug_muxer-subtitle-options-setting_20210708](https://user-images.githubusercontent.com/3157518/125012112-7c100f00-e01e-11eb-87ed-d7b94a09b0af.png)

But as we can see in the log here,

[Subtitle test_srt-mux_staxrip.log](https://github.com/staxrip/staxrip/files/6788191/Subtitle.test_srt-mux_staxrip.log)

`MP4Box` fails to add the necessary switch `:txtflags=0xC0000000` in the command line (Line 190), and thus the output mp4 file has a subtitle track that is _not forced_ (Line 265).

```
Forced                  : No
```

For reference, see [this post](https://video.stackexchange.com/questions/10423/force-subtitles-to-play-as-default).

**Comment by Dendraspis** [comment]
Does anybody have a clue where to find the documentation of `txtflags` ??

At the moment `Forced` is ignored as well as `Default`, with should be set with this parameter. But I can't find any hint how to set it properly.  🤔

**Comment by MotorSportF1** [comment]
> 
> 
> Does anybody have a clue where to find the documentation of `txtflags` ??
> 
> At the moment `Forced` is ignored as well as `Default`, with should be set with this parameter. But I can't find any hint how to set it properly. 🤔

I found this but not sure.
https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-SW80

**Comment by JJKylee** [comment]
There's an item `txtflags` in _MP4Box_ command line help (`MP4Box.exe -h opts`) or [online help](https://github.com/gpac/gpac/wiki/mp4box-import-opts).

```
:txtflags (int):    set display flags (hexa number) of text track. Use txtflags+=FLAGS to add flags and txtflags-=FLAGS to remove flags
```

I also can't find samples of `FLAGS` in the help, but I can at least confirm that `:txtflags=0xC0000000` sets the subtitle to _forced_.

For example, I ran the following _MP4Box_ command line to have a _forced_ subtitle track:

```
[...]\MP4Box.exe -add "D:\Test\Subtitle test.mp4#video:name=" -add "D:\Test\Subtitle test.mp4#trackID=2:lang=jpn:name=" -add "D:\Test\Subtitle test.srt:txtflags=0xC0000000:lang=kor:name=" -new "D:\Test\Subtitle test_srt-mux.mp4"
```

and it works as expected. The resulting subtitle track is set to `forced`.

However, I can't find a way to set the subtitle track to _default_. No clues as of now.

I'm curious: does `MP4Box` support a _default_ subtitle anyway? 🤔

**Comment by MotorSportF1** [comment]
Here for more information 
https://github.com/gpac/gpac/wiki/Subtitling-with-GPAC

**Comment by MotorSportF1** [comment]
Or this PDF file 
https://www.etsi.org/deliver/etsi_ts/126200_126299/126245/11.00.00_60/ts_126245v110000p.pdf

I try to search for default tag

**Comment by Dendraspis** [comment]
@JJKylee 
That's the point, there's no documentation about the flag values, for example for *Default*.  🤮 
And there must/should be one .... and *Forced* is also not documented.  🙄 

@MotorSportF1 
Thanks, but those are all not really related to the issue we have right now. The last post by @JJKylee points it out pretty well.

**Comment by JJKylee** [comment]
> _Forced_ is also not documented. 🙄

Well, this part in

> https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-SW80

seems to give a pointer about _forced_:

> All samples are forced
    > If this flag is set, the subtitle media handler treats all samples as forced subtitles, regardless of the presence or absence of a 'frcd' atom. This flag’s value is 0x80000000. If this flag is set, the Some Samples Are Forced flag must also be set (making 0xC0000000).

But I still can't find a clue for _default_. 🤔

**Comment by Dendraspis** [comment]
Yeah, from Apple in a side mark.  🙄 
I would like to have a documentation from the developers, but hey, better than nothing ... I guess. And yes, I know you confirmed it already.  😊 

I have just found this here:
https://github.com/gpac/gpac/issues/1012 
...but it's not very helpful. Seems like a volunteer has to check the values one by one.  🙄  🤮

**Comment by MotorSportF1** [comment]
> 
> 
> Yeah, from Apple in a side mark. 🙄
> I would like to have a documentation from the developers, but hey, better than nothing ... I guess. And yes, I know you confirmed it already. 😊
> 
> I have just found this here:
> [gpac/gpac#1012](https://github.com/gpac/gpac/issues/1012)
> ...but it's not very helpful. Seems like a volunteer has to check the values one by one. 🙄 🤮

I have made a powershell script for this.
Tomorow, I return all my test.
just waiting my result.

I go to bed now

**Comment by JJKylee** [comment]
> I'm curious: does `MP4Box` support a _default_ subtitle anyway? 🤔

For reference, the `mp4` container format itself supports the _Default_ tag in a subtitle track (although I haven't found a way to set it to both _Default_ and _Forced_). Read [this](https://superuser.com/questions/700082/is-there-an-option-in-ffmpeg-to-specify-a-subtitle-track-that-should-be-shown-by) to see how to do it with `ffmpeg`.

**Comment by Patman86** [comment]
> Does anybody have a clue where to find the documentation of `txtflags` ??
> 
> At the moment `Forced` is ignored as well as `Default`, with should be set with this parameter. But I can't find any hint how to set it properly. 🤔

[Link](https://github.com/gpac/gpac/wiki/Subtitling-with-GPAC)

**Comment by JJKylee** [comment]
Long time no see, @Patman86. Welcome back. 😊

Thanks for the links, but they have already been visited and studied.
Currently, putting `Forced` is already resolved and implemented in the dev build. The only remaining issue is how to put `Default` tag on the subtitle in `MP4Box`. 😥

**Comment by Patman86** [comment]
i found [that](https://sourceforge.net/p/gpac/discussion/327349/thread/0297efc9/)

**Comment by JJKylee** [comment]
> i found [that](https://sourceforge.net/p/gpac/discussion/327349/thread/0297efc9/)

Super! Adding **`:group=1`** puts `Default` tag on both audio and subtitle. Along with **`:txtflags=0xC0000000`**, the subtitle track now becomes **`Forced` _and_ `Default`**.

```
[...]\MP4Box.exe -add "D:\Test\Subtitle test.mp4#video:name=" -add "D:\Test\Subtitle test.mp4#trackID=2:lang=jpn:name=:group=1" -add "D:\Test\Subtitle test.srt:lang=kor:name=:txtflags=0xC0000000:group=1" -new "D:\Test\Subtitle test_mux.mp4"
```

**[MediaInfo subtitle track]**

> Text
> 
> ID                              : 3
> Format                          : Timed Text
> Codec ID                        : tx3g
> Duration                        : 1h 1mn
> Bit rate mode                   : VBR
> Bit rate                        : 26 bps
> Stream size                     : 11.6 KiB (0%)
> Language                        : Korean
> Default                         : Yes
> Forced                          : Yes
> Alternate group                 : 1
> Encoded date                    : UTC 2021-07-15 20:43:57
> Tagged date                     : UTC 2021-07-15 20:43:57

👍👍👍👍👍

**Comment by Patman86** [comment]
Can you please try the second variant? Mark two audio files, one AAC and the other AC3, both :group=1 and AC3 with :group=1:disabled. Then the AAC should be default, regardless of whether audio track 1 or 2.

**Comment by JJKylee** [comment]
I grouped 2 audio tracks into one group and set the _first_ audio track to _non-default_ (`:disabled`).
And **_yes_**, the first audio track has `Default: No` and the second has `Default: Yes` as intended.

BUT there's a **_warning in the log_**:

```
Option disabled not described in doc, please report to GPAC devs!
        ! Import option `disabled` not available for ISOBMFF/QT sources, ignoring !
```

I'm afraid this warning will make StaxRip pop up an error although the output is yielded as expected. 🤔

**Comment by Patman86** [comment]
That is strange. The statement was made by the developer. We only have to try. I believe such warnings from MP4Box should be ignored if I remember correctly.

**Comment by JJKylee** [comment]
Ditto. I only wish the warning does _not_ prevent StaxRip from processing `MP4Box` muxing smoothly.

**Comment by JJKylee** [comment]
I think I figured out how to avoid the warning: **_exclude the non-default tracks from any group_**!

In the above two audio sample, if I group only the second audio track (`:group=1`) but don't put the group option on the first audio track, only the second audio will have `Default: Yes` _without any warning in the log_.

Plus, as can be guessed from its name, `:txtflags=0xC0000000` does not put `Forced` tag on audio tracks. But I'm not sure if it's even possible at all as of now. 😅

Anyways... It's been a long trip just to find this _simple_ solution. 😂

**Comment by JJKylee** [comment]
Side note:

Currently, _Default_ option becomes missing in _Audio Settings_ when the muxer is `MP4Box`, unlike `mkvmerge`.

![StaxRip_2 6 41_missing_Default-option_in_audio_20210715](https://user-images.githubusercontent.com/3157518/125864314-5dd20774-7d2b-4614-99b4-3bfc1ca7d7a0.png)

Since we've figured out how to put the `Default` tag on tracks in general, maybe we can revive the corresponding option in audio. 🙄

**Comment by Dendraspis** [comment]
Everything should be added/fixed/done.
