### ISSUE TITLE
Better Documentation and User Friendliness for users new to StaxRip/encoding

### ISSUE THREAD

**Issue by expanse191** [staxrip/staxrip#74]
Hello, I'd like to offer some suggestions about StaxRip. Although StaxRip is such a great and useful tool for video encoding, it lacks user friendliness(to users new to StaxRip or new to encoding at all) and the [documentation](https://staxrip.readthedocs.io/) although complete, isn't helpful to new users as to what settings to use, which filters, what advantages/disadvantages some common filters or settings have, etc.

1. Improve user-friendliness of StaxRip. Specifically some ideas:
- In the filters section, when wanting to e.g deinterlace or denoise, a default filter(one that balances speed and quality) should be auto-selected, because newbies wouldn't know which to use. Of course, it would still be possible to choose another filter.
- More useful tooltips/hints that help choose what setting to use(for example when hovering over the x264 mode, a hint would appear that would tell you which one to choose, e.g. quality is faster than 2 pass and offers same/better quality).
- Adaptive defaults. For example when opening a 480p video, the default CRF value could be CRF 20 but when opening a 1080p video, it would automatically be CRF 22. (CRF values are used as an example only). Also, if the video source is interlaced, it could automatically enable the deinterlace filter or suggest/hint the user to enable it.
- Better defaults. Some settings should have different defaults. For example, for x265 video, the default shouldn't be CRF 28, thats too low. Also, in my opinion, the default mode should Quality and not 2-pass. Another example, the default setting for x264 shouldn't be 10-bit but 8-bit instead since that's the one mostly used for x264 and 10-bit is significantly slower. (x265 10 bit should remain as default). Also, default codec for audio shouldn't be opus since it isn't ideal for movies and isn't widely supported. Moreover, VapourSynth should be default since Avisynth doesn't use the full potential of processors on CPUs with more than 6 cores(it's slower on multithreaded).
- Start offering installers instead of zipped file(at least for stable builds).

2. Better documentation for newbies at https://staxrip.readthedocs.io/
It would be useful if the documentation besides being technical, was also helpful to newbies as to differences between deinterlace, denoise filters, which to use and when. When to use 2-pass, when to use CRF,

**Comment by stax76** [comment]
Why is Opus not ideal for movies? All AAC encoders have licensing issues regarding of distribution which I'm tired of.

**Comment by Havokdan** [comment]
I'm sorry, i'm using google translator.
I would like to take this opportunity to leave again my thanks to @stax76 by the great tool.
Let's go, I recommend that the documentation consists of the application or tool, restricting the functionality of the application, for example, in the documentation regarding the x264 video codec, which refers to that CRF or any other configuration of the codec to documentation of the tool itself, so for all of the tools in the command line used by the application, thus restricting the documentation of StaxRip features, such as batch conversion, preview, jobs and etc.

**Comment by expanse191** [comment]
> 
> 
> Why is Opus not ideal for movies? All AAC encoders have licensing issues regarding distribution which I'm tired of.

I'm sorry, I didn't know that. Based on a cursory reading on various forums I read opinions that OPUS isn't for movies and it's only ideal for very-low bitrate encodes.
This kind of information would be useful(at least for newbies or someone like me who knows only some basics about encoding and codecs) if it was present in the StaxRip documentation explaining when OPUS should be used and why it's better and so on. Not only for opus but for other settings as well(CRF, 2 pass, deinterlace filters, denoisers, x264 vs x265, etc.).
Of course I'm NOT suggesting it should be your TOP priority to improve documentation and UI friendliness right away. I'm just saying that it would be nice if they were implemented sometime in the near-future, let's say for StaxRip 2.1.0

**Comment by Revan654** [comment]
>I read opinions that OPUS isn't for movies and it's only ideal for very-low bitrate encodes.

Who ever said that has no idea what there talking about. OPUS is designed to give you same or better results at lower bitrate (Similar to x264 => x265). It will produce better results then AAC, of course you don't have to Re-Encode the Audio you can just use the direct stream.

Your looking for the Do's & Don't of Encoding, Which is going a bit off road with Application Doc, What your looking for is a Tutorial on Encoding.

**Comment by expanse191** [comment]
Ok then, thanks anyway! :)

**Comment by stax76** [comment]
In Germany, we have an amazing site.

https://encodingwissen.de/
