### ISSUE TITLE
'SEI writing options'(--opts) in x264 is deprecated

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#748]
StaxRip version: v2.6.0 (and v2.6.41 as well)

As pointed out in [this post](https://forum.doom9.org/showthread.php?p=1947930#post1947930) in Doom9, the following option of `x264` (`--opts`) does not work anymore.

![StaxRip_2 6 0_x264_Options_--opts_bug_20210718](https://user-images.githubusercontent.com/3157518/126075962-0ea9337a-9cf1-4993-b070-76184c5c6308.png)

Error log:

```
--------------------------- Video encoding ---------------------------

x264 0.163.3059+11-1aa8b82-.Mod-by-Patman.-x64-gcc10.3.0

D:\Tmp\StaxRip-v2.6.0-x64\Apps\Encoders\x264\x264.exe --opts 1 --synth-lib D:\Tmp\StaxRip-v2.6.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --output "D:\Test\Two audio sample_temp\Two audio sample_new_out.h264" "D:\Test\Two audio sample_temp\Two audio sample_new.avs"

D:\Tmp\StaxRip-v2.6.0-x64\Apps\Encoders\x264\x264.exe: unknown option -- opts
```

**Comment by Dendraspis** [comment]
Thanks!  🙂
