### ISSUE TITLE
File not found - Event Cmd: After Video Encoded

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#755]
StaxRip 2.6.0

When using "After Video Encoded" Event Command to change name of output file (Target File Path) StaxRip cannot find file.

**Expected behavior**

When Target File Path is used to change the name of the output file StaxRip should still be able to find the file by using the original file name NOT the changed file name.

**How to reproduce the issue**

Create an Event Command:
Event: After Video Encoded
Match Any
Target Image Height - is - 1080
Target Image Width - is - 1920
Use the event command: Set Target File
Parameters: Target File Path
%target_dir%%source_name%.1080p.%encoder_ext%.%muxer_ext%

Attempt to encode a 1920x1080 file.

ERROR INFO: (Input File name: S01E01.mkv)

Error Muxing to MKV (v2.6.0)

Muxing to MKV returned exit code: 2 (0x2)

It's unclear what this exit code means, in case it's
a Windows system error then it possibly means:

# for hex 0x2 / decimal 2
  STATUS_WAIT_2                                                  ntstatus.h   
  ERROR_FILE_NOT_FOUND                                           winerror.h   
# The system cannot find the file specified.
# as an HRESULT: Severity: SUCCESS (0), FACILITY_NULL (0x0), Code 0x2
# for hex 0x2 / decimal 2
  ERROR_FILE_NOT_FOUND                                           winerror.h   
# The system cannot find the file specified.

---------------------------- Muxing to MKV ----------------------------

mkvmerge 56.1

mkvmerge v56.1.0 ('My Friend') 64-bit
Error: The file 'X:\VidTemp\S01E01_temp\S01E01.1080p.h265_out.h265' could not be opened for reading: open file error.

StaxRip.ErrorAbortException: Muxing to MKV returned exit code: 2 (0x2)

---------------------------- Muxing to MKV ----------------------------
   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 361
   at StaxRip.MkvMuxer.Mux() in D:\Code\Github\staxrip\staxrip\Source\General\Muxer.vb:line 622
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 378

**Comment by Dendraspis** [comment]
StaxRip encodes your source to `X:\VidTemp\S01E01_temp\S01E01.1080p.h265_out.h265`, before it is muxed to `X:\VidTemp\S01E01_temp\S01E01.1080p.h265.mkv`.

What you do is:
After encoding, you rename the intermediate file `X:\VidTemp\S01E01_temp\S01E01.1080p.h265_out.h265` to something else so StaxRip does not know where it is.

What you wanna do is using events like `After Job Processed` or similar, to rename the output file of the project/job.

**Comment by Dendraspis** [comment]
Will be fixed in v2.7.0 ..... hopefully.  😅
