### ISSUE TITLE
New VCEEnc features

### ISSUE THREAD

**Issue by NikosDi** [staxrip/staxrip#757]
Hello.

The amount of work and support for AMD's HW encoder has definitely been increased for StaxRip (and Rigaya's VCEEnc) so I would like to add just a few features / parameters more:

a) Latest version is 6.12 (no difference than 6.11)

b) New functions / switches have been added (they are probably old but appeared in help since v6.11)

   --vbaq                     enable VBAQ
   --pe                         enable Pre Encode
   --pa                         enable Pre Analysis
   --pa-sc <string>             sensitivity of scenechange detection
                                 - none, low, medium(default), high
   --pa-ss <string>             sensitivity of static scene detection
                                 - none, low, medium(default), high
   --pa-activity-type <string>  block activity calcualtion mode
                                 - y (default, yuv)
   --pa-caq-strength <string>   Content Adaptive Quantization (CAQ) strength
                                 - low, medium(default), high
   --pa-initqpsc <int>          initial qp after scene change
   --pa-fskip-maxqp <int>       threshold to insert skip frame on static scene

c) New --vpp-delogo

d) The --vpp-smooth filter is a denoiser so it could probably be moved from "Misc 2" to "Denoise" section of StaxRip

BR,
Nikos

**Comment by Dendraspis** [comment]
1. Done ... but don't forget you can update it also by yourself, every time 😉 
2. Such implementations are time consuming and it seems like not many users are using VCEEnc. Nevertheless I've implemented some params for the next release.
3. Not at the moment... same for NVEnc.
4. The effect might be similar, but it's definitely not a pure denoiser.
