### ISSUE TITLE
Log File - Output File Name/Location

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#76]
What file is being converted and what file is being created is what StaxRip is all about.

Good user interface design calls for the input/output file name and path to be the first entry in the log file. (even before the System Environment info) as well as being the first entry in the Job Processing output (at the top of all sections or in some sort of - always visible - status bar. 

After converted several files, I could not find one of the files I converted early on - made a mistake and put it in the wrong folder. 

After searching the log file I finally found a log file entry that listed the output file path and name buried near the end of the log file in the mkvmerge section - not user friendly.

**Comment by stax76** [comment]
I think scrolling to the end, looking for the last MediaInfo entry is easy enough. Most people don't look at all at the log file even though they should. Take a look how cryptic and ugly log files of other encoders and apps are, for instance megui.

**Comment by noblemd00** [comment]
> I think scrolling to the end, looking for the last MediaInfo entry is easy enough. Most people don't look at all at the log file even though they should. Take a look how cryptic and ugly log files of other encoders and apps are, for instance megui.

As I stated , NOT VERY USER FRIENDLY having to search for such basic user/program information. What is important is it being easy for the USER to find and not having to search in such an obscure location (mkvmerge ?????). 

The USER should have instant access to the output file information before, during and after conversion.

The input file is noted at the beginning of the log why not the output information - which is actually more important to the USER than the input file information. 

WHY NOT (in the log file)...

------------------------ Target File ------------------------
\\Movies\SciFi\ Some Media file Converted.mkv

------------------------ MediaInfo Source File ------------------------
F:\Convert\Some media file.mkv

**Comment by Patman86** [comment]
I think the users of such tools as StaxRip should have some understanding and know-how in dealing with them. StaxRip only depicts a visualization of the individual tools and makes it easier to handle them, so that you do not have to do everything in the command line.

**Comment by 44vince44** [comment]
Comparing to other software, I find Staxrip log files very easy to read and to understand once you get used to it.  It is difficult to present all this information in a clear way, and Staxrip does it successfully. You just need some experience with it

**Comment by noblemd00** [comment]
The lack of an explicitly clear log entry for the output file is a glaring USER INTERFACE omission which should be corrected ASAP.  

This is a simple request that will improve the program. 

1. What is more important to the USER than the file output by the program?

2. What is the purpose of StaxRip other than to create a converted file?

3. Why is a log entry for that output file and location missing?

4. Every other file created/used by StaxRip is explicitly noted in the log file - usually several times, but not the most important USER information - the file being created. You know... the one that the USER is creating by using the program.

Once again, this is simply a request - an important request..

**Comment by stax76** [comment]
Just think this through, it's not even possible...

Because as soon as you open a file much info is already written to the log file, demuxing, indexing etc., the log file is a timeline and the decision to change the output folder might be made very late in the timeline.

**Comment by noblemd00** [comment]
Okay, understood.

It is simple to insert text in a text (log) file, though.

However, to make it easier to do - locate the info at the very end.of the log file. With no extraneous text to hide or camouflage it 

This is also an appropriate location since it is the  "Job Complete" log area.

A note at the beginning of the log file could direct the user where to find the output info.

Note: Output file information (name and path) is listed at the end of the log file.

This would allow the user to immediately see where the output info is located without resorting to external help.

----------------------------- Job Complete -----------------------------
Output File: 
D:\Videos\Converted\xyz.videofile.mkv

Start:    11:28:53
End:      11:35:03
Duration: 00:06:10
