### ISSUE TITLE
Title/name is not getting changed

### ISSUE THREAD

**Issue by inter5tella** [staxrip/staxrip#764]
When I do remove/clear the title field in the container configuration, the previous value is still getting taken over into the new output.

To reproduce:
1. Load a file that has a 'Movie name' clearly shown in MediaInfo, or add a title via ToolNix etc.
2. Do changes as you like (Video/Audio encoding)
3. Click on 'Container Options'
4. Swith to the 'Options' tab
5. Remove the content of the field 'Title:'
6. Complete the job
7. Check the title of the new output file again with MediaInfo

Used StaxRip version v2.8.0 but issue has already been noticed since v2.6.0 or earlier (not sure anymore).

**Comment by Dendraspis** [comment]
Thanks for reporting.

Either the last tool updates fixed this issue or it was something else, because I've tested it with v2.8.2 and it works like expected, meaning the title is empty.

So I close this one...
