### ISSUE TITLE
mpv.net error

### ISSUE THREAD

**Issue by jerethi** [staxrip/staxrip#770]
When starting mpv.net, with or without loading an avisynth/vpsynth script, I receive the following error:
![image](https://user-images.githubusercontent.com/47827013/129467684-6506833e-5fe7-421f-bb94-1ff7c9f1b56c.png)

I am using a fresh install of StaxRip 2.8.

**Comment by JJKylee** [comment]
Confirmed.

Remove the following two folders that shouldn't be existing in `<StaxRip-Folder>\Apps\Support\mpv.net`:

`Extensions`
`Scripts`

then it will work without errors.

**Comment by sheik124** [comment]
https://github.com/stax76/mpv.net/issues/256
This happens with StaxRip v2.7.0 and v2.8.0 which both include mpv.net 5.4.9.0 but did not with v2.6.0 which came with 5.4.8.6.
![image](https://user-images.githubusercontent.com/2312934/132897342-ff8f6a80-03de-45ed-82fa-e123ced8d394.png)
mpv.net 5.4.9.0 itself did not come with the Extensions folder while 5.4.8.6 did.
When mpv.net was updated (locally? in your build environment I guess) in StaxRip, was it copied "over" the old files? They should be removed.
