### ISSUE TITLE
outputted data files from AVS (such as from WriteFile) get overwritten with empty data upon job completion

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#777]
I'm trying to use TFM and TDecimate from the TIVTC package, in VFR mode (mode=5)
this requires two passes with the first pass (mode=4) being used to create metrics files which are then read during the second pass (mode=5)

first pass (mode=4) : 
```
D2VSource("D:\sourcefile.d2v")
TFM(d2v = "D:\sourcefile.d2v", output = "D:\tfm.txt", mode = 3, slow = 2, MI = 20, micmatching = 1, flags = 3)
TDecimate(mode = 4, output = "D:\tdecimate.txt")
```

This would normally produce a large file for each output, with a line for every frame containing metrics info. For my source video which is around 50,000 frames, these files will be pretty large, at least several hundred kb each. Instead I end up with very small files with only the top few lines present. here's the entire contents of both output files at the end of the first pass:

tfm.txt :
```
#TFM v1.0.7 by tritical
field = top
crc32 = 5dcb7f8a
0 c - [0]
1 c - [0]
2 c - [0]
3 c - [0]
4 c - [0]
5 c - [0]
6 c - [0]
7 c - [0]
8 c - [0]
9 c - [0]
10 c - [0]
11 c - [0]
12 c - [0]
13 c - [0]
14 c - [0]
15 c - [0]
```

tdecimate.txt :
```
#TDecimate v1.0.8 by tritical
crc32 = 5ba1c37a, blockx = 32, blocky = 32, chroma = T
```

this means that my second pass produces an error, because it's expecting these files to contain data

second pass (mode=5, hybrid=2) : 
```
D2VSource("D:\sourcefile.d2v")
TFM(d2v = "D:\sourcefile.d2v", input = "D:\tfm.txt", mode = 3, slow = 2, MI = 20, micmatching = 1, flags = 3)
TDecimate(input = "D:\tdecimate.txt", tfmin = "D:\tfm.txt", mkvout = "D:\timecodes.txt", vfrdec = 1, mode = 5, hybrid = 2, vidthresh = 13)
```

at first I wondered if something was up with my script, but after trying a few times I noticed something - while the script is encoding, these output files remain empty (0 bytes). when the script is completed, presumably the file writers are closed, and this is when the data appears, and at this moment both files are actually quite large, around 700kb each

staxrip then muxes the encoded video to MKV, this takes around 20 seconds or so, and while this is happening both files remain 700kb in size. during this time I can double click one to open it in notepad++ and all the data is there and looks correct

once the MKV muxing is completed, and the whole job is completed, at this moment suddenly both files are truncated and will now appear as I've shown above, with just a few lines. I'm sure the AVS script has stopped running, and closed all files, when the encoding finished and the muxing begins, so I don't think it can be AVS, or TIVTC, or my script doing something to break these files now - it looks like Staxrip is doing something when the overall job is completed, and it cleans up, that causes these files to lose data

These files are not being saved in the temp folder, and Staxrip is also not deleting temp files, so I don't know why these files get truncated when the job is completed

I've since tried opening the .avs file that Staxrip generates for this job, in MeGUI, to see what happens if I try it there. it's the same .avs file, it's using the same version of TIVTC. I guess some things can still be different, but I figure if there's a problem in my script, or in AVS/TIVTC outputting the data, then the problem should happen here as well. I get the correct output on these files if I run them in MeGUI, both files end up full of data. so for now I can run my first pass in MeGUI and the second pass in Staxrip, but this is messy and I don't like MeGUI... 

I was having this problem in 2.5.0 and that led me to come here, where I found 2.8.0, I've installed that and the problem remains there as well. I'd like to know if this problem happens to anyone else!

**Comment by Statick** [comment]
bumping this - I've noticed the same issue with files outputted using the AVS built in function WriteFile

my script is outputting some reporting data to a file. it has a function at the top WriteFileStart() which outputs a small header, then WriteFile() happens per frame to output some information about each frame

when I open the project in staxrip, and the AVS script is loaded, the data file is immediately generated and the header from WriteFileStart() is written. this happens before I even start the encode, it's as soon as the project is opened that the file is created and this header is written to it

then when I start the encode, this file fills up with data, then the encode is completed, the job is muxed, and when the muxing is completed - the file is suddenly overwritten with empty data and it shows just the header from WriteFileStart() again

it looks to me as though the AVS script is being reloaded upon project completion, and as a consequence any outputted data files are overwritten with new empty files. I've tried setting Staxrip to close down upon project completion, but this doesn't help, these files are overwritten just the same

can this please be looked into because it's a solid barrier preventing the use of two pass VFR encoding in TIVTC using Staxrip, which requires that you output a metrics file in one pass and then load that file into a second pass for the final encode

**Comment by Statick** [comment]
to fully clarify this, here is a simple test which fails

add this code to a script, watch the output file get generated including data for the first few frames, then run the encode, you can watch the output file fill up with data, then when muxing is completed you can watch it get erased again, and the file will return to the state it was when it was first generated (just the header and data for a few frames). this happens every time, it is 100% reproducable


```
colon = ": "
header = "This is the top of the file"
WriteFileStart("%source_dir%test.txt", "header")
WriteFile("%source_dir%test.txt", "current_frame", "colon", "AverageLuma")
```

**Comment by Dendraspis** [comment]
I that code written inside the `Source` section?
Can you make a screenshot of the Code Editor with such an example?

**Comment by Dendraspis** [comment]
Can you check out this version and tell me, if it works for you, please?  It ***should*** fix your problems...
[StaxRip-v2.11.10.zip](https://github.com/staxrip/staxrip/files/8473720/StaxRip-v2.11.10.zip)
