### ISSUE TITLE
requests: reload video button within preview window, and "no output" option for first pass scripts

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#778]
Being able to refresh/reload the video from within the preview window, rather than closing and re-opening the window, would be very helpful when building override files. At the moment every time I add a frame to an override file, I have to close and re-open the preview window in order to refresh and see if the override is good or not. When this action has to be repeated several hundred times, it gets very tedious. A refresh button next to the nav buttons in the preview window would be amazing, and would save a lot of time clicking around

Also, a "no output" option in the encoder/container options would be great for running first pass scripts that don't care about the video output. I have some filters that require two passes, the first pass outputs some metrics to some data files, then the second pass imports these files to produce the final encode. The output of the first pass can be ignored, I just need to generate the metrics files, at the moment when I do this I have to encode to x264 using ultra fast settings, and then remember to delete the large encoded video file before running the second pass. It would be great to be able to choose "no output" as a video encoder, and then the output of the avs script is ignored entirely

MeGUI has both these features and I feel Staxrip would benefit from both

**Comment by Dendraspis** [comment]
I have to reject the first request, as it's too error prone. Not with this programming structure.  

You can achieve this behavior by setting the container to `No Muxing` and the encoder to `Command Line` using 
`"%app:vspipe%" %script_file% ... -` which should be enough to start the script and create those files.
If not, we can talk about it again.....
