### ISSUE TITLE
Audio out of sync on DVD

### ISSUE THREAD

**Issue by epiccofficial** [staxrip/staxrip#78]
After ripping Spongebob with MakeMKV, I put it through StaxRip, hoping to achieve a smaller file size while retaining the quality. However, after it had finished, I opened up the video and the audio was very out of sync. It only seems to happen on Spongebob and it happens on multiple episodes. I am using the setting "Copy/Mux" for the audio. I can provide an example if you want me to. Also, can anyone recommend a good deinterlace setting that doesn't leave a combing/ghosting effect?
Thanks,
EpicC.

**Comment by stax76** [comment]
I almost always need a full log file.

The best deinterlacer is QTGMC.

**Comment by epiccofficial** [comment]
[E01 - Reef Blower_new_staxrip.log](https://github.com/staxrip/staxrip/files/3743387/E01.-.Reef.Blower_new_staxrip.log)
Here is the log file, sorry I took so long to respond.
It seems that the video slows down a bit at the start, then goes back to it's normal speed, leaving the audio out of time.

**Comment by epiccofficial** [comment]
Also, when I use Nvidia H.265, the frame rate doubles. Why does it do this?

**Comment by stax76** [comment]
It contains timestamps and NTSC, I've forgotten everything I knew about that, ask at doom9 or videohelp, both forums have many competent users that will happily help you with it.
