### ISSUE TITLE
Relative Speed of encoding and Compression

### ISSUE THREAD

**Issue by Phantom1472** [staxrip/staxrip#781]
When StaxRip is running, it displays FPS, but it would be useful to also display the relative speed of the current job (compared to the video real time).

For example, if the current job is running on a 20min video, and it took 10min to run, it's avg "speed" was x2.00. If the video is 30FPS, and the job is currently running at 60FPS, then it's current "speed" is x2.00

ffmpeg shows current speed when running and it's very useful IMO.

Also, having a compression % to see much compressed the new file is, will be very useful. It currently only displays est. final size, but not % compared to original file.

Thanks!

**Comment by Dendraspis** [comment]
On the one side a nice additional information, on the other side it's just a "toy" for users, who prefer speed over quality. 
Because the encoder output is taken for the status line, it would be possible to implement it via StaxRip through "Output Formatting", but I don't like the idea of creating a lot of overhead. I think if this should be implemented properly, it should be done inside the encoder(s).

@Patman86 
Are you willed to implement this into your build(s)?

**Comment by Patman86** [comment]
I could do it when I have a little more time. I do my best, but it has no priority.

**Comment by Dendraspis** [comment]
Same for me.  😅   Thanks. 😊

**Comment by Dendraspis** [comment]
Almost 2 years are gone .... wow.

So I'll implement it in StaxRip for x264 and x265, other encoders might be added later.

**Comment by Phantom1472** [comment]
2 years in the making! Didn't think it will get added but thanks for the effort!

**Comment by Dendraspis** [comment]
Making .... let's say *hanging around* due to more important bugs and my break. But:

![image](https://github.com/staxrip/staxrip/assets/50659978/a156f0d7-91f1-4d13-a1cb-a3ca61e433fb)

**Comment by Phantom1472** [comment]
> Making .... let's say *hanging around* due to more important bugs and my break. But:
> 
> ![image](https://github.com/staxrip/staxrip/assets/50659978/a156f0d7-91f1-4d13-a1cb-a3ca61e433fb)
> 

Lol I'll take it! Anyway, thanks a lot!

**Comment by Dendraspis** [comment]
Oh, forgot to mention:
At least at the moment this only works with `x264` and `x265` when `Progress Reformatting` is enabled (which it is by default).
So don't tell me you're using another encoder.  😅

**Comment by tormento** [comment]
@Dendraspis what will happen if I use DJATOM or jpsdr builds, that relies on Patman patches but don't have yet the patch for X value? I love DJATOM ones as they have different cpu optimized builds.

@Patman86 do you think you could compile separate builds? Sandy Bridge, Haswell, etc?

**Comment by Dendraspis** [comment]
DJATOM's builds are also supported, as long as he didn't remove his name from the log output and changed the progress output.  If it doesn't work, then the whole Progress Reformatting isn't working, so I have to adjust it.

**Comment by Patman86** [comment]
> @Dendraspis what will happen if I use DJATOM or jpsdr builds, that relies on Patman patches but don't have yet the patch for X value? I love DJATOM ones as they have different cpu optimized builds.
> 
> @Patman86 do you think you could compile separate builds? Sandy Bridge, Haswell, etc?

I can do that. I will make them available at the weekend.
