### ISSUE TITLE
Frame rate mode : Variable  not constant

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#782]
hello,

when i do recode one of my video.mkv  i can see  in mediainfo somephing like that:

<HTML><HEAD></HEAD>
<BODY>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR><TD><I>**Frame rate mode :**</I></TD>
<TD colSpan=3>**Variable**</TD></TR></TBODY></TABLE></BODY></HTML>

and when i look up on the internet to compare i see that all rips have 

<HTML><HEAD></HEAD>
<BODY>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR><TD><I>**Frame rate mode :**</I></TD>
<TD colSpan=3>**Constant**</TD></TR></TBODY></TABLE></BODY></HTML>

is it possible to add option to define it " the same like source " ?

**Comment by madey83** [comment]
StaxRip 1.8.0 produced 
<html>
<body>


**Frame rate mode :** | **Constant**
-- | --



</body>
</html>

i did the test with the same settings

**Comment by Dendraspis** [comment]
As far as I remember `Frame Rate Mode` is not a property, it is a value calculated by MediaInfo based on the first few frames. So this is tool(s) issue and nothing we can influence directly.

**Comment by madey83** [comment]
hi,
thank you for explanation.
I did new test with StaxRip 2.10 and this is still valid.
When i manually created mkv file Frame rate mode is shown as constan
![Capture](https://user-images.githubusercontent.com/34553588/136324527-bd679e1c-074a-4cec-b300-bb402deb6957.PNG)
t.
