### ISSUE TITLE
Encode x265 mp4 with dolby vision audio sync issue

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#783]
**Describe the bug**
video and audio sync issue when i re-encode mp4 with dolby vision

**Expected behavior**
video and audio after re-encode must be in sync like original mp4 file.

**How to reproduce the issue**
my test settings:

"E:\4k encode\apps\StaxRip-v2.8.0-x64\Apps\Support\avs2pipemod\avs2pipemod64.exe" -dll="E:\4k encode\apps\StaxRip-v2.8.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" -y4mp "E:\4k encode\TEST_temp\TEMP_new.avs" | "E:\4k encode\apps\StaxRip-v2.8.0-x64\Apps\Encoders\x265\x265.exe"  --crf 20 --preset fast --output-depth 10 --profile main10 --level-idc 5.2 --high-tier --rd 3 --psy-rd 3 --rdoq-level 2 --psy-rdoq 2.5 --tu-intra-depth 2 --tu-inter-depth 2 --refine-mv 1 --early-skip --b-intra --scale-factor 1 --zones "38110,39218,b=0.1" --aq-mode 3 --qg-size 64 --aq-strength 0.9 --qcomp 0.7 --cbqpoffs -1 --crqpoffs -1 --vbv-bufsize 7000 --vbv-maxrate 10000 --subme 5 --max-merge 3 --weightb --b-adapt 2 --bframes 8 --rc-lookahead 75 --min-keyint 24 --frame-threads 5 --master-display "G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1)" --hdr10 --colorprim bt2020 --colormatrix bt2020nc --transfer smpte2084 --range full --max-luma 1023 --hdr10-opt --chromaloc 2 --dolby-vision-profile 5 --dolby-vision-rpu "E:\4k encode\TEST_test.rpu" --repeat-headers --hrd --deblock -2:-2 --no-sao --seek 0 --frames 1200 --y4m --output "E:\4k encode\TEMP_temp\TEST_test_new_out.hevc" -

**Provide information**

no error appeared during encode process
 
If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version:  2.8.0

**Comment by Dendraspis** [comment]
Can you provide a short sample ?

**Comment by madey83** [comment]
I did test one more time and i saw huge delay on audio (2800 ms) and that was the problem.
When i adjusted it in MPC it was ok.

Next question is why Staxrip did not adjust delay in mp4 when container was created after re-encode?
