### ISSUE TITLE
AOMEnc Encoding Option/UI Discrepancy

### ISSUE THREAD

**Issue by sheik124** [staxrip/staxrip#785]
**Describe the bug**
* Ticking the option for "_Adaptive quantize\_b_" does not work as it should. It populates the command line with `--quant-b-adapt`, which is invalid.
* Additionally, the "Bitrate" shown in the main StaxRip window and the "Target Bitrate" in the encoder options are not connected like they are for other encoders, e.g. x264, x265.

**Expected behavior**
* `--quant-b-adapt=1` should appear in the command line. Note the =1.
* Changing the bitrate in the main StaxRip window, beneath the output filename, should change the bitrate shown under "Target Bitrate" in the Encoding options, and vice versa.

**How to reproduce the issue**
quant-b-adapt bug
1. Select **AV1** -> **AOMenc** as the Encoder
2. Open "Encoder Options"
3. Go to the "_AV1 Specific 5_" page of AOMEnc's options and try enabling the fifth option, "_Adaptive quantize\_b_"

bitrate bug
1. Pick VBR or CBR Rate Mode on Rate Control 1.
2. Click OK.
3. Type any bitrate in beneath the filename.
4. Open Encoder Options again, note the command line arguments have changed, but the "Target Bitrate" selection still shows "0".
5. Try changing the "Target Bitrate" under Rate Control 1.
6. This overrides the bitrate shown in the main StaxRip window and will always be the value passed to `--target-bitrate=`

**Provide information**
Didn't really feel like a log file or a screenshot of the error was necessary here, since I just unticked the box and manually added `--quant-b-adapt=1` to my first/second pass arguments on the _Custom_ page instead. It just spawns a comically large Windows error box that reminds you that `quant-b-adapt requires an argument and no argument was passed to it`
- Used StaxRip version
v2.8.0

**Notes before posting**
- Please also try the latest release of StaxRip. **I am using it**
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. **The issue is with StaxRip itself and how it is generating the command line arguments based on the selections made in the UI.**
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is especially true on the VapourSynth side, which will crash if your CPU don't support it. **My machine is junk without AVX2 support but there are no filters involved here, and the encode progressed normally once I manually added the desired commandline argument.**
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet. **I am using _AOMEnc 3.1.2-588-gd1b830121-x64-gcc10.3.0 Patman_ as supplied with StaxRip**

**Additional context**
Should be an easy fix, no?

**Please be as clear and as detailed as possible**
![image](https://user-images.githubusercontent.com/2312934/135937634-c1e05272-c643-4547-99bc-23d843116b8e.png)
This is broken.

![image](https://user-images.githubusercontent.com/2312934/135937726-37319310-76ca-49ed-b57d-2e01f81b665f.png)
Doing it manually this way works fine.

The "Target Bitrate" box "overrides" the "Bitrate" option in the main StaxRip window and changes the actual command line argument.
![image](https://user-images.githubusercontent.com/2312934/135937918-be296845-7108-4e8f-83a5-564882b28337.png)
It's still set to the same 3000 kbps in the main StaxRip window, but once you set any value in the "Encoding Options" target bitrate, you can change the value back in the main StaxRip window as many times as you want without it changing the command line, or the value shown in the UI's "Target Bitrate" on that page. The Target Bitrate selection in that screenshot above **must** be set to 0 for the bitrate selection in the main StaxRip window to function.
It should behave more like the Encoding Options dialogues for x264/x265, where changing either of them changes the other automatically.

**Comment by Dendraspis** [comment]
One of the most detailed bug reports I've ever seen.  ☺️ 
Thanks, both issues will be fixed in the next release.  👍
