### ISSUE TITLE
Anamorphic always stays Anamorphic

### ISSUE THREAD

**Issue by bobdig** [staxrip/staxrip#786]
I wasn't able to get the file to be not anamorphic anymore with any resize filter, preview looked ok, file after encoding didn't.
Finally I found a filter called Anamorphic to Standard under misc, but even with this, file was not ok in the end.

[test.zip](https://github.com/staxrip/staxrip/files/7284699/test.zip)

I am pretty sure this had worked in the past.

**Comment by Dendraspis** [comment]
StaxRip Version?
Log file(s)?
Settings?
Source Filter?
Anamorph in which way?
How to reproduce?
.....

You haven't filled out the Bug Report Template and then you give us almost no information to deal with this issue or try to reproduce it.... 
Sorry, we need more.

**Comment by Ding-adong** [comment]
Use resize filter to 1024x576 aka 16/9 to convert anamorphic to standard square pixel.
