### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by jerethi** [staxrip/staxrip#787]
**Describe the bug**
After a fresh install of StaxRip 2.9, when select Vapoursynth from the AVS Filters menu, I receive the following error:
Script Error

Python exception: module 'vapoursynth' has no attribute 'get_core'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2759, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2760, in vapoursynth._vpy_evaluate
  File "path to video source", line 3, in <module>
    core = vs.get_core()
AttributeError: module 'vapoursynth' has no attribute 'get_core'

**Expected behavior**
Normally the video sources opens without an error message.

**How to reproduce the issue**
Open a video source, then select Vapoursynth from the AVS Filters menu.

**Provide information**
Script Error

Python exception: module 'vapoursynth' has no attribute 'get_core'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2759, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2760, in vapoursynth._vpy_evaluate
  File "path to video source", line 3, in <module>
    core = vs.get_core()
AttributeError: module 'vapoursynth' has no attribute 'get_core'

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version
2.9

**Notes before posting**
- Please also try the latest release of StaxRip.
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. 
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is especially true on the VapourSynth side, which will crash if your CPU don't support it.
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet.

**Additional context**
Add any other information or additional context that can be helpful.

**Please be as clear and as detailed as possible**

**Comment by jerethi** [comment]
Yes, I started a project from scratch. The error occurs even when I open a source file using the Automatic Workflow template; the moment I select VapourSynth, I see the error.

I wonder if it has something to do with this comment on the VapourSynth website:

> Many script functions were marked as obsolete or removed. The most common construct is probably vs.get_core() that no longer works. Use vs.core instead you lazy script writers! Many other functions like plugin/function enumeration were changed but the old functions simply have deprecation warnings. For now.

Based on this, it seems the source filter is using a vs.get_core() function rather than vs.core?

**Comment by Dendraspis** [comment]
Okay, investigating....

**Comment by Dendraspis** [comment]
@jerethi 
Thanks a lot. And yes, this was the culprit, that was removed already in R55! 👍 

Will be fixed in a few minutes in the next release....
