### ISSUE TITLE
Overflow Exception

### ISSUE THREAD

**Issue by jerethi** [staxrip/staxrip#788]
**Describe the bug**
Greetings,
It's me again! I downloaded the 2.9.2 you posted on the Discord server. While I am able to properly load source file with VapourSynth, when I attempt to open a preview window for the source file, I receive the error below:

![image](https://user-images.githubusercontent.com/47827013/136083079-09669880-d9cc-4af7-a9b6-6492767e7665.png)

**Expected behavior**
To see a window previewing the video source.

**How to reproduce the issue**

Open a video source, select VapourSynth, and then click on preview.

- Used StaxRip version
2.9.2

**Comment by Dendraspis** [comment]
Thanks a lot, due to downgrading to VapourSynth R64, this issue is gone.
