### ISSUE TITLE
interface colors

### ISSUE THREAD

**Issue by SkyAFS** [staxrip/staxrip#79]
Hi, i know that this is probably very low on the priority list, but i have a problem for almost 4 years now and only now discover that i could talk to you guys here, 

i hate white theme for windows, to much in the eyes, so i use custom themes for windows, i tested 30 themes in the past 4 years and all of then have one problem with staxrip, 

the color of the progression bar on the job window,
![StaxRip_JDfZBkHu6n](https://user-images.githubusercontent.com/16105922/67654200-844c1780-f92b-11e9-9023-0448e4c41ea2.png)

As you can see, the progress color and the text always become almost the same, and i cant see at all.

I don't know how hard is to fix this, but if you could change only this color to work on white and dark text, would work to everyone.

Love your software for many years and i will continue to use even if its not fixed, but this would help a lot me and my friends.

**Comment by SkyAFS** [comment]
i was just thinking, and it must be awesome, you probably proud of your work, just imagine, your software is so good that the only problem i can find is one color on the interface hahaha

**Comment by stax76** [comment]
Hi, next build has a change that is trying to fix it. Thanks for the feedback.

**Comment by stax76** [comment]
Please try the new beta:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by stax76** [comment]
I'm currently using hard coded colors in places where I should rather use system colors, I guess I will change this soon.

https://devblogs.microsoft.com/wpf/systemcolors-reference/
