### ISSUE TITLE
Please update encoders

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#791]
Would you please provide x264/x265 latest iterations, compatible with "enhanced" process window?

**Comment by tormento** [comment]
@Dendraspis progress reformatting doesn't work with vanilla builds, such the latest updates of x264 and x265 from repositories.

I'd like to see a newer version of the included x26*.

**Comment by Patman86** [comment]
Pls close issue.

**Comment by tormento** [comment]
@Patman86 your last encoders disappeared from GitHub. I can see July only.

Do you plan to release x264 3075 and latest x265 too?

**Comment by Patman86** [comment]
> @Patman86 your last encoders disappeared from GitHub. I can see July only.
> 
> Do you plan to release x264 3075 and latest x265 too?

Done!

[MediaFire](https://www.mediafire.com/folder/vkt2ckzjvt0qf/Tools_for_StaxRip_by_Patman)
[x264Mod](https://github.com/Patman86/x264-Mod-by-Patman/releases/latest)
[x265Mod](https://github.com/Patman86/x265-Mod-by-Patman/releases/latest)

**Comment by tormento** [comment]
@Patman86 thanks!

**Comment by tormento** [comment]
@Patman86 as side note, x265 MSVC is 10% faster than GCC version on my i7-2600k. Please, if you have time, provide x264 MSVC build too and, when you will have time, ICL ones for speed comparison.

**Comment by Patman86** [comment]
I've noticed this on earlier versions. I'll see what I can do!

**Comment by tormento** [comment]
@Patman86 another refresh is available. Please, when you will have time! 👍

**Comment by Patman86** [comment]
I will do in the next few days.

**Comment by Patman86** [comment]
I have not forgotten you @tormento! I made some changes this time and now i'm in the process of preparing staxrip for vapoursynth r57 and higher.

**Comment by Dendraspis** [comment]
@Patman86 is going to update the tools for the next release, so I'll close this for now...

**Comment by tormento** [comment]
@Patman86 friendly reminder to update (again :) encoder builds. You know I love your ones, buddy. ;)

**Comment by Patman86** [comment]
i will do it during the week.

**Comment by tormento** [comment]
@Patman86 friendly reminder ;)

**Comment by Patman86** [comment]
oh yes, no problem. I was a bit busy during the week... the tools update will be carried out on sunday. I've already synchronized the sources, so it's just about building.

**Comment by Patman86** [comment]
Tools updated.
x264 and x265 were not updated, no changes in the branches or only marginally.
