### ISSUE TITLE
How to copy all the audios of a video?

### ISSUE THREAD

**Issue by LarryEastwood** [staxrip/staxrip#795]
I have a video with 3 audios but it only copies the first 2, how can I copy all the audios of the video automatically?

I have 180 videos with 3 audios and I would like to copy them all automatically

thanks.

**Comment by Patman86** [comment]
Only copy, not a new audio format?

**Comment by LarryEastwood** [comment]
Yes, just copy.

**Comment by Patman86** [comment]
You can use the container options for this. Unfortunately, demuxing the audio files is necessary for this.

![image](https://user-images.githubusercontent.com/54327252/140015482-2c304380-e8e0-400b-ad21-f3e8de43285f.png)

**Comment by LarryEastwood** [comment]
Thanks, I can't believe that all the audios cannot be copied automatically and it has to be done manually, from the third audio track
