### ISSUE TITLE
Audio missing when doing AAC 7.1 encodes 

### ISSUE THREAD

**Issue by AdithyanNellickal** [staxrip/staxrip#796]
Hi, this is my first time reporting an issue. So please forgive me if there's any mistakes.

Now on to the issue. Whenever I try to do AAC 7.1 Channel encodes, the resultant video doesn't have an audio file in that. The sources are usually TrueHD 7.1 or DTS 7.1. And I do x265 10bit only. The bitrate used for AAC 7.1 is 424 which came automatically. Am I doing anything wrong or is this some kind of bug ? Please help. 

Thanks in advance.

**Comment by Patman86** [comment]
Did you click the "more" button in the audio settings and set the decoding method to "pipe" in the advanced audio settings under "General"? If not, the audio conversion will be skipped.

![image](https://user-images.githubusercontent.com/54327252/139930458-bb4f1a5a-0c7e-4c75-9075-0c20af7f8bc9.png)
![image](https://user-images.githubusercontent.com/54327252/139930511-8b6a7a5c-feb7-4731-beb8-3c99aa12f446.png)

**Comment by AdithyanNellickal** [comment]
@Patman86 I didn't knew about that bro.. Thanks for the answer 😍😍

Will try that as soon as current queue is finished.

**Comment by Dendraspis** [comment]
Seems this is solved, I'll close it for now...
