### ISSUE TITLE
VSfilter SMDegrain below Removegrain

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#797]
**Describe the bug**
VSfilter SMDegrain below Removegrain filter

**Expected behavior**
SMDegrain separated from Removegrain

![smdegrain](https://user-images.githubusercontent.com/12258051/138751763-9317b22b-1c72-4d1b-a92b-6d4f87403dd0.jpg)

Also SMDegrain parameters suggestion if you willing to add

```
Light
clip = havsfunc.SMDegrain(clip, tr=1, thSAD=300, RefineMotion=True)

Medium
clip = havsfunc.SMDegrain(clip, tr=2, thSAD=300, RefineMotion=True)

Hard
clip = havsfunc.SMDegrain(clip, tr=3, thSAD=600, RefineMotion=True)
```

**Comment by Dendraspis** [comment]
Thanks, never saw that.  Will be moved in the next release...
