### ISSUE TITLE
Why not try to support mux and demux while encoding?

### ISSUE THREAD

**Issue by cms42** [staxrip/staxrip#799]
**Is your feature request related to a problem? Please describe.**
Partly Yes. Actually I've tried to process about 300GB 4k video with `NVENC` and ran into a problem that staxrip spent a far more time on muxing and demuxing the video (using `mp4box` or `mkvmerge` or that kind of thing) , not about "REAL" encoding.

**Describe the solution you'd like**
Encoding one video, demuxing and muxing several(configurable) video files at the same time in file batch mode. If we can start several audio encoding processes at the same time that would be even better.

**Explain why the feature matters to you**
It can REALLY save a lot of time, especially when processing a huge number of large files.

**Comment by Dendraspis** [comment]
StaxRip uses command line encoders and tools to handle the tasks. Because none of them supports that, we had to  build such a huge construct to realize it and that won't happen, especially it can cause a lot of issues.
So yes, basically a very nice idea, but at least at the moment: *Refused*.
