### ISSUE TITLE
DAR in Video vs. DAR in Container (and not only)

### ISSUE THREAD

**Issue by Zet-Kaz** [staxrip/staxrip#8]
1. For anamorphic SD sources, the Resize section incorrectly calculates the values of its parameters. When PAR 65:45 (Snap2.jpg) is left for the output file, and in the 'Container Options' window set 'Display Aspect Ratio' = 0, then a movie will be obtained (PAR changes to 1: 1) recognized as material:
- anamorphic (eg in mpv Player and in VLC media player), or as
- unanamorphic, distorted - in MPC-HC, or in daum PotPlayer.
The proportions of the sides of the MTN thumbnails are 16: 9 (correct, as determined on the basis of the DAR video), and the StaxRip miniatures (they are bad, as determined on the basis of the container DAR) are 5: 4.
![Snap1](https://user-images.githubusercontent.com/51753271/59362626-13b5ad00-8d34-11e9-9aec-641e20d1905c.jpg)
![Snap2](https://user-images.githubusercontent.com/51753271/59362640-187a6100-8d34-11e9-8454-6dfdad8eb887.jpg)

MediaInfo - fragment:
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 5:4             /MediaInfo treats this as a video parameter, and does not indicate that we are dealing with the .mkv container parameter (Zet-Kaz)/
Original display aspect ratio            : 16:9
Frame rate mode                          : Constant
Frame rate                               : 50.000 FPS

The existence of a DAR setting in the 'Container - MKV (merge)' window causes (for me) a bit of confusion. Why can not I stay with the DAR parameter defined only for the resulting video, as it is in StaxRip 32-bits?

2. Why when creating Templates, StaxRip always assumes that the source file is 1920x1088 PAR 1: 1 video, and for such source forces the indication in the 'Resize' section?

3. In addition, no longer associated with the DAR: MTN thumbnails are mostly incorrect timestamps, while the StaxRip thumbnails are all correct.

Regards,
Zet-Kaz
/PS Sorry for my Google-english/

**Comment by stax76** [comment]
Hey,

I'll investigate it later today.

Every time somebody posts an aspect ratio problem I'm very skeptical because this area was always something that staxrip did much better than other apps.

There were breaking changes in MediaInfo which could have introduced a bug, we'll see.

**Comment by stax76** [comment]
Can you upload a sample and a full log file? If possible please split the post into independent issues, so far I'm not understanding anything, sorry.

**Comment by stax76** [comment]
You can try setting MPEG2Source before opening the source file. You are not gaining anything with DGSource because DVDs take little CPU time to decode, the difference should be little to none.

Aspect Ratio detection might be broken for DGSource and DVD, you can set the source PAR manually to 16:11.

I've not installed DGSource so I cannot test it.

**Comment by Zet-Kaz** [comment]
**DAR in Video vs. DAR in Container - in another way**
My 30-second source file comes from the Disney XD TV channel. This is AVC 720x576 with DAR = 1.7777777777 - so PAR = 64:45, and this value is always defined by myself in StaxRip (Options → Image → Aspect Ratio → Source PAR).
I know that DGSource can have problems here and I never rely on it. A few years ago, Disney XD sent an MPEG-2 704x576 picture with DAR = 1.7777777777 - then PAR was supposed to write 16:11, but that's another story. Correctness of the calculated PAR source file, I confirm in MediaCoder.
Today I want to use StaxRip to only remove the interlace from the image and re-encode the movie in x264. I expect the resulting file will remain anamorphic and the player will display the video in the correct proportions based on the read PAR. So far, when I used to encode a 32 bit StaxRip (also using DGSource), the obtained result files were displayed in a proportional manner, regardless of the used player.
When I use StaxRip 64-bits 2.0.2.0 Stable Release (Container Options → Display Aspect Ratio: 0 / Automatic /), the received result file is treated differently by video players - keeping the proportions when using PAR 64:45 or without correct proportions, i.e. PAR 1: 1 will be used.

One more thing.
In the attached screenshot of 2 StaxRip screens, StaxRip 2.0.2.0 shows (in my opinion) an incorrect value for Error: -29.69%, and StaxRip 1.2.2.0 does not state this error.

![Snap3](https://user-images.githubusercontent.com/51753271/59392983-ef7cbf00-8d79-11e9-806e-e3388295f5d8.jpg)
This is the same file (from StaxRip 2.0.2.0) played in MPC-HC, and next - in mpv Player:
![Snap4](https://user-images.githubusercontent.com/51753271/59392992-f60b3680-8d79-11e9-9a47-9305bbf9ba41.jpg)

**Comment by stax76** [comment]
why set ar in muxer?

**Comment by stax76** [comment]
In your target video file there is DAR of 1.25 reported by MediaInfo, that's the reason why the thumbnails AR is not correct and it's probably also the reason why mpc-hc shows a wrong AR. I don't see any bug in staxrip.

**Comment by iAM261917** [comment]
Tried your sample with default settings(didn't change anything but codec, that's doesn't affect the ratio), looks fine.
My player says it's DAR is 1.82:1, not sure why, but same as the original file.
![n](https://user-images.githubusercontent.com/42721712/59432240-7339b880-8e19-11e9-855d-d2aac1970fba.jpg)

**Comment by stax76** [comment]
@Zet-Kaz 

The setting exists in staxrip because it exists in mkvmerge and mp4box, you should never use it except you know exactly what you are doing.

Next build will have a tooltip that shows when you right click the setting or open the help of the dialog:

> Display Aspect Ratio to be applied by mkvmerge/MP4Box. By default and best practice the aspect ratio should be signalled to the encoder and not to the muxer, use this setting at your own risk.

I must not always be right, sometimes I'm wrong and apologize and sometimes I don't have enough patience. Imagine every week or every month somebody screws his encode by changing a setting he doesn't understand, then he comes to the support and it's difficult for everybody to find the root cause because the user has little encoding and little English knowledge.

If you use Chrome I recommend using this extensions:

dict-cc

Grammar and Spell Checker - LanguageTool

You can also use a machine learning based translation software like this:

https://www.deepl.com/translator

With little better english you can get help in the doom9 or videohelp forum.

I was a bit stressed out because I try to learn web programming, I'm sorry for that.

**Comment by Zet-Kaz** [comment]
Thanks for the link to the translator.
I'm sorry, but now I've stopped understanding anything...  Allow me to disagree with the content of the proposed ToolTip:
"Display Aspect Ratio to be applied by mkvmerge/MP4Box. By default and best practice the aspect ratio should be signalled to the encoder and not to the muxer, use this setting at your own risk."
In my opinion, after several years of using StaxRip, it is as below:
1. the Display Aspect Ratio parameter (of course we are talking about the settings from the Container window) is not used by the encoder, and the StaxRip places it (this parameter) in the .mkv container (unless otherwise, because MediaInfo treats it as the next DAR parameter in the video path), which is created by the mixer,
2. the encoder, however, takes into account the data contained in the 'Resize' section of the main StaxRip window,
3. the above can be seen using gMKVExtractGUI (v2.4.2.0 -- By Gpower2), and extracting the .avc video track from the .mkv container and then analyzing its properties,
4. interestingly, mkvmerge (via MKVToolNix GUI v33.1.0) does not "see" the DAR parameter specified in StaxRip in the 'Container' window at all (you can enter it again by selecting the appropriate value from the drop-down list), and using mkvmerge will create (for our, discussed .mkv) new .mkv file - now it has the form I meant from the very beginning, i.e. certainly 'unambiguously' anamorphous: with PAR 64:45 and with DAR always = 1,7777777777.

Or maybe it would be enough for the ToolTip mentioned above to contain only a short list of the most popular video players, which will interpret the DAR parameter well (or even need it) and those who will not use it. As you can see, e.g. Automatic option (value='0') may cause some confusion.
For the sake of clarity, I propose to add one more option to the DAR list, the "Do not use" type, which will simply clear the contents of this field (value=''). Well, I guess I've already gone too far...
In case of lack of time, please do not answer this entry - after all, no one is interested, as you can see, in our exchange of opinions.

Best greetings, congratulations on a job well done, useful for many people.

**Comment by stax76** [comment]
I think we are discussing something relatively simple and writing large posts make something simple difficult.

By default, StaxRip has always set the pixel aspect ratio in the encoder, it has by default never set the pixel aspect ratio in the muxer.

Just the check the log file and the command line preview feature in the encoder and muxer dialogs.

If you still have problems to understand everything then please create a thread at doom9 or videohelp, there are probably people that can explain it better than me.

![encoder](https://user-images.githubusercontent.com/11410540/59553227-62f91900-8f92-11e9-9687-905024b31edc.png)

![muxer](https://user-images.githubusercontent.com/11410540/59553228-6391af80-8f92-11e9-810d-a5aa0a2003d4.png)
