### ISSUE TITLE
My expirence

### ISSUE THREAD

**Issue by Adramelramalech** [staxrip/staxrip#80]
My experience is, THIS DOES NOT WORK AT ALL!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I am literally getting nonstop errors, error after error after error. I can't even open the program without error, I can not encode anything with out an error. Templates don't work, open source does not work, batch does not work. Nothing, not one single element in the entire user interface works. So why am I dealing with this? Why is I make settings, open source, press next or start, then stax disregards my settings and uses its own crap settings. Why is there settings built into the program automatically? I had a encode failed because I copy and paste my command line into the custom then stax tried to do a 2 pass on CRF and i could not figure out why until I saw that the x265 settings literally have settings embedded that need to be omitted before you do anything, dumb. This entire program is a joke and seriously have no clue how any one is using it. I can just keep going on and on and on.

And what is this?

![gohuighuivh](https://user-images.githubusercontent.com/52721957/67680811-736ac880-f962-11e9-89b2-46afb3f67a46.png)

**Comment by stax76** [comment]
Try the latest beta.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by Gorkan422** [comment]
Agreed, I just don't have the time to invest learning 20+ new pieces of software.
After 5 hours of error after error, I consider this to be a huge work-around to using Handbrake or Videoproc. 
Some may enjoy the challenge.
I just want to transcode video.
