### ISSUE TITLE
Script Error: Zs_RF_Shared.avsi [2.10.0]

### ISSUE THREAD

**Issue by upyzl** [staxrip/staxrip#800]
When use QTGMC, staxrip 2.10.0 report:
----
Script Error

Parse error: string missing closing quotation marks
(C:\enc\StaxRip\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi, line 1635, column 13)
----

replace by https://raw.githubusercontent.com/realfinder/AVS-Stuff/master/avs%202.5%20and%20up/Zs_RF_Shared.avsi
is ok

hope update by next version...

**Comment by Patman86** [comment]
This is weird because the file you replaced is exactly the same as that in StxRip 2.10.0

**Comment by upyzl** [comment]
> This is weird because the file you replaced is exactly the same as that in StaxRip 2.10.0

I konw the point... my network issue.
Re-download 7z files is ok...
