### ISSUE TITLE
x264 2-pass encode wrong file size v2.10.0

### ISSUE THREAD

**Issue by WIGGER-BG** [staxrip/staxrip#801]
**Describe the bug**
I tried 3 times an encode with DVD/BD-5 file size and result is always 4,17 GB. I use BluRay remux file with dtshd audio stream, which I'd like converted in AC3 5.1 640 kbps. Encode is of TV series, so I made E01 and E02 in the same way with audio encode in StaxRip. Both were 4,17 GB. Then I made eac3to encode of the audio of E01 and in StaxRip pointed Copy/Mux function. Again the resulting mkv file is 4,17 GB.

**Expected behavior**
I expect file size of 4,7 GB.

**How to reproduce the issue**

Try to encode with --bitrate parameter.

**Provide information**

> _SOURCE:_ 

G: Matroska, 8.55 GiB, 1 h 11 min, 17.1 Mb/s

V: AVC, High@L4, 1920x1080, 23.976 FPS, 14.9 Mb/s

A: English, DTS XLL, 2 149 kb/s, 6ch, 48.0 kHz, Default

T: Bulgarian, UTF-8, Default
T: English, PGS

M: Menu

General

Unique ID                       : 219839108469870944882908107557437440729 (0xA56378E1C4B357BE9AFEAE0DED7002D9)
Complete name                   : E:\TEMP\Leftovers S01\The.Leftovers.S01E01.mkv
Format                          : Matroska
Format version                  : Version 4
File size                       : 8.55 GiB
Duration                        : 1h 11mn
Overall bit rate mode           : VBR
Overall bit rate                : 17.1 Mbps
Movie name                      : The Leftovers Season 1 Disc 1
Encoded date                    : UTC 2021-09-06 08:50:08
Writing application             : mkvmerge v61.0.0 ('So') 64-bit
Writing library                 : libebml v1.4.2 + libmatroska v1.6.4
Cover                           : Yes
Attachments                     : cover.jpg

Video

ID                              : 1
ID in the original source medium: 4113 (0x1011)
Format                          : AVC
Format/Info                     : Advanced Video Codec
Format profile                  : High@L4
Format settings                 : CABAC / 2 Ref Frames
Format settings, CABAC          : Yes
Format settings, ref frames     : 2 frame
Codec ID                        : V_MPEG4/ISO/AVC
Duration                        : 1h 11mn
Bit rate mode                   : VBR
Bit rate                        : 14.9 Mbps
Width                           : 1920 pixel
Height                          : 1080 pixel
Display aspect ratio            : 16:9
Frame rate mode                 : CFR
Frame rate                      : 23.976 (24000/1001) fps
Color space                     : YUV
Chroma subsampling              : 4:2:0
Bit depth                       : 8 bit
Scan type                       : Progressive
Bits/(Pixel*Frame)              : 0.300
Stream size                     : 7.46 GiB (87%)
Default                         : Yes
Forced                          : No
OriginalSourceMedium            : Blu-ray

Audio

ID                              : 2
ID in the original source medium: 4352 (0x1100)
Format                          : DTS XLL
Format/Info                     : Digital Theater Systems
Commercial name                 : DTS-HD Master Audio
Codec ID                        : A_DTS
Duration                        : 1h 11mn
Bit rate mode                   : VBR
Bit rate                        : 2149 Kbps
Channel(s)                      : 6 channel
Channel layout                  : C L R Ls Rs LFE
Sampling rate                   : 48.0 KHz
Frame rate                      : 93.750 fps (512 SPF)
Bit depth                       : 16 bit
Compression mode                : Lossless
Stream size                     : 1.07 GiB (13%)
Language                        : English
Default                         : Yes
Forced                          : No
OriginalSourceMedium            : Blu-ray

Text #1

ID                              : 3
Format                          : UTF-8
Codec ID                        : S_TEXT/UTF8
Codec ID/Info                   : UTF-8 Plain Text
Duration                        : 1h 10mn
Bit rate                        : 70 bps
Count of elements               : 572
Stream size                     : 36.0 KiB (0%)
Language                        : Bulgarian
Default                         : Yes
Forced                          : No

Text #2

ID                              : 4
ID in the original source medium: 4608 (0x1200)
Format                          : PGS
Muxing mode                     : zlib
Codec ID                        : S_HDMV/PGS
Codec ID/Info                   : Picture based subtitle format used on BDs/HD-DVDs
Duration                        : 1h 11mn
Bit rate                        : 58.3 Kbps
Count of elements               : 1614
Stream size                     : 29.8 MiB (0%)
Language                        : English
Default                         : No
Forced                          : No
OriginalSourceMedium            : Blu-ray

Menu

00:00:00.000                    : Chapter 01
00:09:28.442                    : Chapter 02
00:19:25.873                    : Chapter 03
00:32:24.859                    : Chapter 04
00:39:09.263                    : Chapter 05
00:50:34.114                    : Chapter 06
01:00:21.951                    : Chapter 07
01:10:01.405                    : Chapter 08

> _ENCODE:_

G: Matroska, 4.17 GiB, 1 h 11 min, 8 341 kb/s

V: AVC, High@L4.1, 1920x1080, 23.976 FPS, 7 694 kb/s

A: English, AC-3, 640 kb/s, 6ch, 48.0 kHz, Default

T: Bulgarian, UTF-8, Default
T: English, VobSub

M: Menu

General

Unique ID                       : 123148300850615496053527460669794637163 (0x5CA580015DFCAA4313D5635354CD556B)
Complete name                   : E:\TEMP\Leftovers S01\The.Leftovers.S01E01-STM.mkv
Format                          : Matroska
Format version                  : Version 4
File size                       : 4.17 GiB
Duration                        : 1h 11mn
Overall bit rate                : 8341 Kbps
Movie name                      : The.Leftovers.S01E01-STM
Encoded date                    : UTC 2021-10-30 19:11:00
Writing application             : mkvmerge v61.0.0 ('So') 64-bit
Writing library                 : libebml v1.4.2 + libmatroska v1.6.4
Cover                           : Yes
Attachments                     : cover.jpg

Video

ID                              : 1
Format                          : AVC
Format/Info                     : Advanced Video Codec
Format profile                  : High@L4.1
Format settings                 : CABAC / 4 Ref Frames
Format settings, CABAC          : Yes
Format settings, ref frames     : 4 frame
Codec ID                        : V_MPEG4/ISO/AVC
Duration                        : 1h 11mn
Bit rate                        : 7694 Kbps
Width                           : 1920 pixel
Height                          : 1080 pixel
Display aspect ratio            : 16:9
Frame rate mode                 : CFR
Frame rate                      : 23.976 (24000/1001) fps
Color space                     : YUV
Chroma subsampling              : 4:2:0
Bit depth                       : 8 bit
Scan type                       : Progressive
Bits/(Pixel*Frame)              : 0.155
Stream size                     : 3.85 GiB (92%)
Title                           : WIGGER @ Scary-Team®
Writing library                 : x264 core 164 r3065+9 7a0e6e8 [Mod by Patman]
Encoding settings               : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=24 / lookahead_threads=4 / sliced_threads=0 / slices=4 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=300 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=7694 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Default                         : Yes
Forced                          : No
Color range                     : Limited
Color primaries                 : BT.709
Transfer characteristics        : BT.709
Matrix coefficients             : BT.709

Audio

ID                              : 2
Format                          : AC-3
Format/Info                     : Audio Coding 3
Commercial name                 : Dolby Digital
Codec ID                        : A_AC3
Duration                        : 1h 11mn
Bit rate mode                   : CBR
Bit rate                        : 640 Kbps
Channel(s)                      : 6 channel
Channel layout                  : L R C LFE Ls Rs
Sampling rate                   : 48.0 KHz
Frame rate                      : 31.250 fps (1536 SPF)
Compression mode                : Lossy
Stream size                     : 328 MiB (8%)
Title                           : English AC3 5.1
Language                        : English
Service kind                    : Complete Main
Default                         : Yes
Forced                          : No

Text #1

ID                              : 3
Format                          : UTF-8
Codec ID                        : S_TEXT/UTF8
Codec ID/Info                   : UTF-8 Plain Text
Duration                        : 1h 10mn
Bit rate                        : 70 bps
Count of elements               : 572
Stream size                     : 36.0 KiB (0%)
Title                           : Bulgarian
Language                        : Bulgarian
Default                         : Yes
Forced                          : No

Text #2

ID                              : 4
Format                          : VobSub
Muxing mode                     : zlib
Codec ID                        : S_VOBSUB
Codec ID/Info                   : Picture based subtitle format used on DVDs
Duration                        : 1h 11mn
Bit rate                        : 9078 bps
Count of elements               : 807
Stream size                     : 4.64 MiB (0%)
Title                           : English
Language                        : English
Default                         : No
Forced                          : No

Menu

00:00:00.000                    : Chapter 01
00:09:28.442                    : Chapter 02
00:19:25.873                    : Chapter 03
00:32:24.859                    : Chapter 04
00:39:09.263                    : Chapter 05
00:50:34.114                    : Chapter 06
01:00:21.951                    : Chapter 07
01:10:01.405                    : Chapter 08

**Comment by Patman86** [comment]
If you choose the 2pass mode for x264, please pay attention to the settings (see screenshot)

![image](https://user-images.githubusercontent.com/54327252/139928683-b5f7d0ec-9d6e-43f0-acb7-060a3e63fe5a.png)

If you have entered a defined size here, this will always be achieved in 2pass mode, regardless of whether you are converting or muxing the audio file. Only the bitrate of the video stream should be different...

**Comment by WIGGER-BG** [comment]
@Patman86, thank you for your reply. This is exactly what I meant saying "DVD/BD-5 file size and result is always 4,17 GB". Size in MB is 4480, Video bitrate changes accordingly if I change the Audio (DTS to AC3 conversion or AC3 copy/mux). In other words, Video bitrate is variable, Size in MB is fixed:
![image](https://user-images.githubusercontent.com/77631602/140164539-e7682620-9933-46c8-9f67-570ff2b41fd7.png)
So, instead of 4,37 GB I always got 4,17 GB file.

**Comment by WIGGER-BG** [comment]
If box is unchecked (Size in MB), video bitrate is 7694. If box is checked (Size in MiB as on your screen), video bitrate is 8100. Increased bitrate could mean bigger file size, so I'll test and report.

**Comment by WIGGER-BG** [comment]
Case solved, thank you @Patman86!

![image](https://user-images.githubusercontent.com/77631602/140492068-e68d4ed1-44a9-405b-a576-e0730889021a.png)

Size in MiB is the right setting to achieve proper file size using pre-defined DVD/BD disc volumes.
