### ISSUE TITLE
Audio time offset for FFMPEG encoder ignored or not implemented

### ISSUE THREAD

**Issue by EA117** [staxrip/staxrip#804]
Problem:

With FFMPEG set as the audio decoder, the automatic audio "Delay:" value StaxRip determines based on the source audio file, or any manual offset I increase or decrease this "Delay:" value to using the StaxRip UI, does not cause any parameter to be added to the FFMPEG command line preview.

And indeed, ultimately once the FFMPEG-encoded audio file is muxed back with the video it was in sync with, the synchronization is now completely off because the delay was not added/maintained.

Expected behavior:

Presumably the StaxRip UI should be pushing a negative or positive "-itsoffset" parameter onto the FFMPEG command line, to reflect the "Delay:" value that has been set.  If I manually run the FFMPEG command line that StaxRip has generated, but add the needed "-itsoffset" parameter onto the FFMPEG command line, the muxed .MP4 file plays with the synchronized audio as expected.

I should also note that you cannot use the StaxRip UI's audio "Edit:" dialog's "Custom:" field to insert the needed "-itsoffset" parameter onto the FFMPEG command line.  Because anything in the "Custom:" field will be inserted to precede the output file on the FFPMEG command line, rather than preceding the input file.  For FFMPEG the "-itsoffset" parameter is an input modification parameter.

To duplicate this issue:

1. Using any recent StaxRip release up to and including 2.10.0, open StaxRip with the default "Manual workflow" template.

2. Without even specifying any source file, simply change the first audio file from "Copy/Mux" to "AAC", and then go to the audio "Edit" button.

3. Change the "Encoder:" drop-down from "Automatic" to "FFMPEG", and confirm that the command line preview now reads FFPMEG.

4. Now change the "Delay:" value in any positive or negative direction, and confirm that nothing is changing in the command line preview that would implement this delay on the FFPMEG command line.

When the encoder is left as "Automatic", a delay parameter is specified to qaac.  When the encoder is forced to EAC3TO, a delay parameter is added to the command line.  But no command line parameter is added when the encoder is forced to FFMPEG.

**Comment by Dendraspis** [comment]
This is an expected and correct behavior. The delay is written to the file name which then is interpreted by the muxing app like `mkvmerge`.
