### ISSUE TITLE
Hello! Need "CUT"

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#809]
Hello, your wonderful program lacks the function of slicing video duration by microseconds.
Please add slicing function - by microseconds.

       hh: mm: ss: msms

source 00:00:00:00 - 01:30:25:33
cutting 00:41:10:25 - 00:48:11:13
or cut 25 seconds

**Comment by Valdiralita** [comment]
You can cut inside the Preview window, use these buttons:
![grafik](https://user-images.githubusercontent.com/1066165/145707728-dfc0de1b-bc93-438a-9e87-4cd710c8d598.png)
Remember that you specify what is **included** in the output. Green sections are outputted, white sections are cut out.

**Comment by Discograp** [comment]
cut frame by frame - no good :(((

**Comment by Dendraspis** [comment]
Additionally you can use the info view to display the time of the current position. This is all we can offer for the moment.
To enable it go to `Menu button / right click on picture » View » Info` or press `I`.
