### ISSUE TITLE
Indexing using ffmsindex failed with exit code: 1 (0x1) - StaxRip-x64-2.0.4.10-beta

### ISSUE THREAD

**Issue by kunjar** [staxrip/staxrip#81]
Hello i receive this error when importing a video into StaxRip-x64-2.0.4.10-beta

-------------------------- System Environment --------------------------

StaxRip    : 2.0.4.10
Windows    : Windows 10 Pro 1903
Language   : English (United Kingdom)
CPU        : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
GPU        : Intel(R) UHD Graphics 620
Resolution : 1920 x 1080
DPI        : 120

------------------------ MediaInfo Source File ------------------------

D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).mkv

General
Complete name            : D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).mkv
Format                   : Matroska
Format version           : Version 2
File size                : 919 MiB
Duration                 : 23 min 52 s
Overall bit rate         : 5 385 kb/s
Encoded date             : UTC
Writing application      : HandBrake 0.10.2 2015060900
Writing library          : Lavf55.12.0

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4.1
Format settings          : CABAC / 5 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 5 frames
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 23 min 52 s
Bit rate                 : 5 000 kb/s
Width                    : 1 440 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 4:3
Frame rate mode          : Constant
Frame rate               : 29.970 (30000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.107
Stream size              : 835 MiB (91%)
Writing library          : x264 core 142 r2479 dd79a61
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 2
Format                   : AC-3
Format/Info              : Audio Coding 3
Commercial name          : Dolby Digital
Codec ID                 : A_AC3
Duration                 : 23 min 52 s
Bit rate mode            : Constant
Bit rate                 : 384 kb/s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 31.250 FPS (1536 SPF)
Compression mode         : Lossy
Delay relative to video  : -5 ms
Stream size              : 65.6 MiB (7%)
Title                    : Stereo
Service kind             : Complete Main
Default                  : Yes
Forced                   : No

------------------ Demux MKV using mkvextract 38.0.0 ------------------

D:\Apps\StaxRip-x64-2.0.4.10-beta\Apps\Support\MKVToolNix\mkvextract.exe "D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).mkv" tracks 1:"D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh  ID1 -5ms.ac3" --ui-language en

Extracting track 1 with the CodecID 'A_AC3' to the file 'D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh  ID1 -5ms.ac3'. Container format: Dolby Digital (AC-3)

Start:    19:43:13
End:      19:43:22
Duration: 00:00:08

General
Complete name         : D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh  ID1 -5ms.ac3
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
File size             : 65.5 MiB
Duration              : 23 min 51 s
Overall bit rate mode : Constant
Overall bit rate      : 384 kb/s

Audio
Format                : AC-3
Format/Info           : Audio Coding 3
Commercial name       : Dolby Digital
Duration              : 23 min 51 s
Bit rate mode         : Constant
Bit rate              : 384 kb/s
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 SPF)
Compression mode      : Lossy
Stream size           : 65.5 MiB (100%)
Service kind          : Complete Main

-------------------- Error Indexing using ffmsindex --------------------

Indexing using ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

----------------------- Indexing using ffmsindex -----------------------

D:\Apps\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\both\ffms2\ffmsindex.exe "D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).mkv" "D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).ffindex"

Writing index... Error writing index: Failed to open 'D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).ffindex'

----------------------- Indexing using ffmsindex -----------------------

D:\Apps\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\both\ffms2\ffmsindex.exe "D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).mkv" "D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).ffindex"

Writing index... Error writing index: Failed to open 'D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).ffindex'

Start:    19:43:23
End:      19:43:24
Duration: 00:00:00

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: Indexing using ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

----------------------- Indexing using ffmsindex -----------------------

D:\Apps\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\both\ffms2\ffmsindex.exe "D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).mkv" "D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).ffindex"

Writing index... Error writing index: Failed to open 'D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).ffindex'

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 340
   at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Project proj) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 678
   at StaxRip.MainForm.Indexing() in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 3167
   at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath) in D:\Projekte\VB\staxrip\General\VideoScript.vb:line 209
   at StaxRip.VideoScript.GetFramerate() in D:\Projekte\VB\staxrip\General\VideoScript.vb:line 411
   at StaxRip.MainForm.ModifyFilters() in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 2283
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 1998

[The Fresh_staxrip.log](https://github.com/staxrip/staxrip/files/3790877/The.Fresh_staxrip.log)

**Comment by stax76** [comment]
> Writing index... Error writing index: Failed to open 'D:\Downloads\19.02.03\The.Fresh.Prince.Of.Bel-Air.S01.1080p.NF.WEBRip.DD2.0.x264-NOGRP[rartv]\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1)_temp\The Fresh Prince Of Bel-Air - S01E08 - Someday Your Prince Will Be In Effect (Part 1).ffindex'

That path is more than 260 character long, WinAPI has a traditional limit of 260, theoretically Win 10 supports more but many of the tools used by staxrip still don't.
