### ISSUE TITLE
How to disable indexing for mkv files

### ISSUE THREAD

**Issue by dhlalit11** [staxrip/staxrip#811]
Hello all

I want to disable indexing step which happens when opening source file, i recently started using staxrip and found that it reads the whole file and creates an index which consumes alot of time on big files and causes unnecessary hdd activity (have already disabled all demuxing option to reduce hdd activity) previous encoder gui that i used only read about 10-20MB of data to index mkv files

I cannot seem to open mkv file with dds2 as source can anyone help me with this and also please help me on how can i install lav filter

![Screenshot_20211209-181105__01__01](https://user-images.githubusercontent.com/58910804/145506282-28f70a59-1df7-4008-a0f9-5e1abf19f616.jpg)

**Comment by darkcity87** [comment]
You can use ''Re-mux'' template that use DSS2 but ''Outomatic Workflow'' recommended.
