### ISSUE TITLE
How to enable turbo 1st pass for x265 encoding?

### ISSUE THREAD

**Issue by ElektroStudios** [staxrip/staxrip#813]
Hi. Someone could please explain me how do I enable turbo 1st pass for x265 encoding (when two-pass encoding)?.

I can't find the option. The option that I mean is the equivalent of this in **Handbrake**:

![](https://i.imgur.com/B8ZOgDS.png)

**Comment by Patman86** [comment]
uncheck the marked option

![Unbenannt](https://user-images.githubusercontent.com/54327252/146464543-86d6c9ac-a038-49d4-bedf-8867a1a8ce44.png)

**Comment by ElektroStudios** [comment]
I totally missed that one when reading the checkbox names. Thanks!!
