### ISSUE TITLE
for HLG HDR atc-sei needs to be 18 but only up to 12 is possible to be set in GUI

### ISSUE THREAD

**Issue by erazortt** [staxrip/staxrip#815]
**Is your feature request related to a problem? Please describe.**
in order to produce a valid HLG HDR encoding, it is necessary to set the stc-sei flag ("Alternative transfer SEI") to 18. However the GUI lets the user only insert values up to 12.

**Describe the solution you'd like**
The user should be able to set values up to 18 in this field.

**Describe alternatives you've considered**
Until then, it is possible to set the flag under custom command line options

**Additional context**
See the field in the screenshot under "Alternative transfer SEI", a max of 12 is allowed.

![atc-sei18](https://user-images.githubusercontent.com/4786333/146964744-8063ca7d-d721-44fd-b9d3-b8ccea34a16c.png)

**Comment by Dendraspis** [comment]
I have raised the limit to 99.  😁 
It will be available with the next release....
