### ISSUE TITLE
How Can I Disable All IVTC on a MPEG2 Stream?

### ISSUE THREAD

**Issue by JonathonSunshine** [staxrip/staxrip#816]
I have a bunch of DVD Remux of a cartoon series, when I play it in MPC-HC I see the frame rate jumping around a lot, sometimes film 24fps, sometimes 30, sometimes 60.

I'm trying to do a QTGMC encode, some parts of the cartoon are legitimately 60 fps, I don't wanna mess around with / learn how to do VFR, I just want to do a 60fps encode of it. One of the vids has come out at 55fps and is out of sync, any ideas how I can fix this?

Sample https://files.catbox.moe/tp71j6.mkv

**Comment by mirh** [comment]
I'm pretty sure both TIVTC and AnimeIVTC are supposed to take care of VFR.

**Comment by Dendraspis** [comment]
I used your sample and can't reproduce it, the resulting audio/video was perfectly synced.

Make sure timestamps are taken over:
![image](https://user-images.githubusercontent.com/50659978/159865591-742c2c6a-b186-428c-9d35-ca708c810206.png)
