### ISSUE TITLE
Staxrip creates variable frame rate mkv from constant frame rate ones

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#817]
I am currently encoding some anime and they have all the same video structure:

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 23 min 53 s
Nominal bit rate               : 8 000 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.161
Writing library                : x264 core 142
Encoding settings              : cabac=1 / ref=4 / deblock=1:1:1 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=2 / keyint=96 / keyint_min=48 / scenecut=40 / intra_refresh=0 / rc_lookahead=48 / rc=2pass / mbtree=1 / bitrate=8000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=12000 / vbv_bufsize=18000 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:0.60
Default                        : Yes
Forced                         : No
VARIANT_BITRATE                : 0

but the output, automatically applying timestamp, gets variable framerate:

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4.1
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 23 min 53 s
Bit rate                       : 2 786 kb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Variable
Frame rate                     : 23.976 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.056
Stream size                    : 476 MiB (95%)
Writing library                : x264 core 164 r3079+8 85d787e [Mod by Patman]
Encoding settings              : cabac=1 / ref=4 / deblock=1:1:1 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=5 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=20.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:0.60
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.709
Transfer characteristics       : BT.709
Matrix coefficients            : BT.709

More than being a "cosmetical" issue, this sometime leads to audio desync.

I could disable the "extract the timestamp" option or select "...only extract timestamps from VFR" but that would lead me to check every single file in a batch encoding.

Can you please check it out? I am attaching the timestamp from the original file.

[01 Asta e Yuno_timestamps.zip](https://github.com/staxrip/staxrip/files/7784252/01.Asta.e.Yuno_timestamps.zip)

**Comment by Patman86** [comment]
I searched for a while, but I was able to track down who was causing the problem. If you unzip your files with mkvextract, errors can occur. If you use ffmpeg, on the other hand, you get a clean output. Please try that out. Deactivate mkvextract under Tools / Settings / Preprocessing and add mkv to ffmpeg.

**Comment by tormento** [comment]
@Patman86 I saw your reply by email but not here. Did you delete that?

**Comment by Patman86** [comment]
Yes, I deleted my comment. I still have to do a little more research. The cause of this problem is definitely mkvextract, it doesn't happen with ffmpeg.

**Comment by tormento** [comment]
@Patman86 does ffmpeg extract timestamps too? Never tried it. If it doesn't, it can't cause the problem. :)

**Comment by lazyjss** [comment]
has there been any progress?   i found this post as staxrip is outputting vfr videos after encoding from cfr 23.976 source material.
using media info to examine files and am not a pro so any help is appreciated on hoe to get a constant frame rate with staxrip encoding.  have tried x265, x264 and both result in vfr

**Comment by mirh** [comment]
This is not the case in my experience. CFR stays CFR, as long as you aren't providing a timestamp to the program. 
The problem if any is autofill. 

If you had previously opened an mkv once with the default seting, despite whatever *ExtractTimestamps* and *ExtractTimestampsVfrOnly* may be later, the .txt in the _temp folder will always be automatically loaded.

**Comment by Dendraspis** [comment]
We already had the discussion here:  #782 

> As far as I remember `Frame Rate Mode` is not a property, it is a value calculated by MediaInfo based on the first few frames. So this is tool(s) issue and nothing we can influence directly.

So there is basically no real issue, except that MediaInfo tells you it is `Variable`, even it is constant.

**Comment by tormento** [comment]
@Dendraspis audio goes out of sync too. It's not a matter of video only.

**Comment by Dendraspis** [comment]
Looks like I need the whole log file and/or the used settings ... and a short sample file could be useful, too. 
I've check my recent encodes (x265) and encoded some samples with x264, but the result was always: `Constant` . So sadly I cannot reproduce it.  😕

**Comment by madey83** [comment]
i had the same issue and i though that is related to MKVToolnix but i found solution.
To have constant Frame rate mode when your encode is done you need to mux up video, audio and other files via mvktoolnix Gui, then it shows constant.

When Staxrip does mux up i have got every time **Frame rate mode : Variable** so may be there is problem with command line ...

**Comment by Patman86** [comment]
I can not confirm that! The thing with the frame rate mode: variable also occurs with the mkvtoolnix GUI when you integrate the timestamps. So there is no error with the command line.

**Comment by madey83** [comment]
my last encode and mux up had video, audio, subtitles (SUP) and chapter (xml), nothing else.

this is what i observed.

**Comment by madey83** [comment]
![image](https://user-images.githubusercontent.com/34553588/160717261-75c86eb8-d55d-450f-93fe-6c61aeb59757.png)

on the left mux up via StaxRip on the right manual by GUI

**Comment by Patman86** [comment]
StaxRip automatically creates a timestamps file when extracting with mkvtoolnix.  When muxing, this file is then automatically included and thus causes the change in the frame rate mode.  If you do this manually via the GUI and do not include the timestamps, the frame rate mode remains.

**Comment by madey83** [comment]
solution:

Options -> Timestamps select BOTH options. then you will get constant

**Comment by mirh** [comment]
If you already opened the video once, that still wouldn't be enough. 
It will auto-fill the settings with the old cached timestamp.txt.

**Comment by vonH** [comment]
This is still an issue as of 2.13.0 - constant framerate file goes in, variable framerate file comes out. This was not an issue on 2.4.0 (the version I was using before - I started fresh with no settings or templates carried over, and the install is portable).
