### ISSUE TITLE
Invisible text in Settings (compatibility issue with MacType)

### ISSUE THREAD

**Issue by nvxarm** [staxrip/staxrip#818]
**Describe the bug**

Much text is invisible in Settings, see screen capture below.

**Expected behavior**

Text should be visible.

**How to reproduce the issue**

1. Click on "Tools" in menu bar

2. Click on "Settings"

**Provide information**

- Version is `2.10.0`

- Log is not found anywhere

- Preview

![1](https://user-images.githubusercontent.com/16894061/147879791-d804a432-d132-4903-8c01-ec8f483c482b.png)
![2](https://user-images.githubusercontent.com/16894061/147879793-1a03a9be-637c-478b-ab91-e43e7de5f1ff.png)
![3](https://user-images.githubusercontent.com/16894061/147879796-2e32fa9e-2725-45a7-ad41-85246fea5f0b.png)

- Screen capture

https://user-images.githubusercontent.com/16894061/147879692-95e23989-b234-4d5f-9c0d-c7fd8f033cc0.mp4

**Notes before posting**

**Additional context**

OS version is `Windows 10 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)`

**Please be as clear and as detailed as possible**

**Comment by DestroyTargetNonBasicLand** [comment]
Do you use MacType by any chance? 

If so, make sure to exclude staxrip.exe in 'process manager'.

**Comment by nvxarm** [comment]
@DestroyTargetNonBasicLand 

It works like a charm! Do you know why it doesn't work with MacType? Thanks anyway!

**Comment by DestroyTargetNonBasicLand** [comment]
Glad to heat it!

`Do you know why it doesn't work with MacType?`
Don't know for sure, but Mactype has a history of compatibly issues with various programs/system apps, so I wouldn't necessarily pin it on staxrip IMO.

**Comment by nvxarm** [comment]
@DestroyTargetNonBasicLand 

Thank you for your reply! I didn't think about it at all, because I use MacType (with default.ini) globally, and every other app works well. That's just why I'm curious how you know that.

**Comment by DestroyTargetNonBasicLand** [comment]
@nvxarm Oh haha, forgot to mention I've been in the same boat as you for the longest time (see https://github.com/staxrip/staxrip/issues/726#issuecomment-854818271), and just sort of rolled with it after an unsuccessful troubleshoot..

It was not until recently that the bright idea to blacklist Staxrip presented itself, funnily enough just shorty before I stumbled across your post when I came down here to request a feature -- a strange twist of fate if you ask me!

**Comment by nvxarm** [comment]
@DestroyTargetNonBasicLand 

Wow! Then we really have a fate! It seems that everyone thought it was the theme that caused the text to be invisible 😂

Before I could change the theme, I felt that these settings were not right, because I have obsessive-compulsive disorder, and must go through all of its options first, before I can actually use an app 😣

**Comment by DestroyTargetNonBasicLand** [comment]
> Before I could change the theme, I felt that these settings were not right, because I have obsessive-compulsive disorder, and must go through all of its options first, before I can actually use an app 😣

Well I'm very glad to hear that! - staxrip is wonderful piece of software that no one should miss out on.. I truly believe that.

Nonetheless, I still think that Staxrip isn't necessarily the culprit here, so I'd advice you to close this issue before reporting it to Mactype's devs instead: https://github.com/snowie2000/mactype/issues. 

This way, they'll either look for a way to fix the problem or whitelist staxrip by default so other users don't have to face the same issue.

Good luck to you my friend, and much love!!

**Comment by nvxarm** [comment]
@DestroyTargetNonBasicLand 

How come I didn't think of this great idea! It looks like MacType has too many problems piling up on its side. Anyway, now it works.

By the way, this is the first time I meet someone who uses Latin alphabets is using MacType too. I thought Windows was ugly only when rendering complex characters like CJK. (I feel your expression quite authentic, so I guess you use English.) 🤔

**Comment by Dendraspis** [comment]
Thanks to @DestroyTargetNonBasicLand this is solved ... interesting one.  🥴  👍
