### ISSUE TITLE
Auto Preview Refresh

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [staxrip/staxrip#819]
As the title suggests, I would love for staxrip to automatically try to refresh the preview whenever it detects a change in the synth's code.

It would be very convenient to directly see the changes, as opposed to having to restart the preview (it takes ages sometimes when many dependencies are loaded) everytime I want to tweak my script.

Thank you kindly!

**Comment by Dendraspis** [comment]
I doubt that is possible. It is impossible to verify the script without executing it ... which takes time ... so every change would lead in a short (or long) break to execute the script and I guess nobody wants that.  😅 

Sadly not doable...
