### ISSUE TITLE
Error when trying to use MCTemporalDenoise

### ISSUE THREAD

**Issue by gelsas** [staxrip/staxrip#82]
When I try to use MCTemporalDenoise It shows this error:

Script error: expected "val", "bool", "int", "float", "string", "array", or "clip"
(C:\Users\gelsas\Desktop\StaxRip-x64-2.0.4.0-stable\Apps\Plugins\AVS\GradFun2DB\GradFun2DBmod.avsi, line 137, column 0)
(D:\Tests\The Good_temp\The Good.avs, line 11)

How can I fix it?

(Running windows 10, latest stable version of Staxrip)

**Comment by stax76** [comment]
I don't know either, on my system (GT 1030) I get:

```
Script Error

Cannot load file 'D:/Projekte/VB/staxrip/bin/Apps/Plugins/avs/FFT3DGPU/FFT3dGPU.dll'. Platform returned code 126:
The specified module could not be found.
```

**Comment by gelsas** [comment]
Got it working. In deleted the GradFun2BMod.avsi file and replaced it with the version from the doom9 website. 

After that it worked as it should.
