### ISSUE TITLE
How to Set Chunks Encoding on x264

### ISSUE THREAD

**Issue by Daringbaaz** [staxrip/staxrip#824]
Hello Team's, 

I Want to Know About How I Can Encode any video on x264 Profile With Chunks Encoding,

I Have 32 Core Threadripper and I Want to utilize full processing power of my pc while encoding, is there any way to encode Video into Multiple Chunks at once to Speed Encoding and Delivery Time, (I Had found Chunks options in x265 Profile but Not in x264)

Thanks

**Comment by Patman86** [comment]
Use threads for that! x264 options -> input/output2
