### ISSUE TITLE
What the hell is this? 

### ISSUE THREAD

**Issue by bakamosokyo** [staxrip/staxrip#83]
**I got this problem on 2.0.4.0 Stable someday. And I guess you already know what happened then, both version got same error.

Full log here:**

Encoder output file is missing (2.0.4.10)

D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_temp\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_new_out.hevc

StaxRip.ErrorAbortException: D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_temp\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_new_out.hevc
   場所 StaxRip.VideoEncoder.AfterEncoding() 場所 D:\Projekte\VB\staxrip\Encoding\VideoEncoder.vb:行 167
   場所 StaxRip.x265Enc.Encode() 場所 D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:行 51
   場所 StaxRip.GlobalClass.ProcessVideo() 場所 D:\Projekte\VB\staxrip\General\GlobalClass.vb:行 228
   場所 System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 StaxRip.GlobalClass.ProcessJob(String jobPath) 場所 D:\Projekte\VB\staxrip\General\GlobalClass.vb:行 138

-------------------------- System Environment --------------------------

StaxRip    : 2.0.4.10
Windows    : Windows 10 Pro 1903
Language   : Japanese (Japan)
CPU        : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU        : NVIDIA GeForce GTX 960
Resolution : 3840 x 2160
DPI        : 192

------------------------ MediaInfo Source File ------------------------

D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p].mkv

General
Complete name            : D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p].mkv
Format                   : Matroska
Format version           : Version 4
File size                : 1.34 GiB
Duration                 : 23 min 40 s
Overall bit rate         : 8 095 kb/s
Encoded date             : UTC 2010-02-22 21:41:29
Writing application      : no_variable_data
Writing library          : no_variable_data
Attachments              : OpenSans-Semibold.ttf

Video
ID                       : 1
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, Reference frames : 4 frames
Format, GOP              : M=1, N=48
Codec ID                 : V_MPEG4/ISO/AVC
Duration                 : 23 min 40 s
Nominal bit rate         : 8 000 kb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 23.976 (24000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Bits/(Pixel*Frame)       : 0.161
Writing library          : x264 core 142
Default                  : Yes
Forced                   : No
Statistics Tags Issue    : no_variable_data 1970-01-01 00:00:00 / no_variable_data 2010-02-22 21:41:29
FromStats_BitRate        : 7963644
FromStats_Duration       : 00:23:40.002000000
FromStats_FrameCount     : 34046
FromStats_StreamSize     : 1413548889

Audio
ID                       : 2
Format                   : AAC LC
Format/Info              : Advanced Audio Codec Low Complexity
Codec ID                 : A_AAC-2
Duration                 : 23 min 40 s
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 44.1 kHz
Frame rate               : 43.066 FPS (1024 SPF)
Compression mode         : Lossy
Language                 : Japanese
Default                  : Yes
Forced                   : No
Statistics Tags Issue    : no_variable_data 1970-01-01 00:00:00 / no_variable_data 2010-02-22 21:41:29
FromStats_BitRate        : 127999
FromStats_Duration       : 00:23:40.063000000
FromStats_FrameCount     : 61157
FromStats_StreamSize     : 22721005

Text
ID                       : 3
Format                   : ASS
Codec ID                 : S_TEXT/ASS
Codec ID/Info            : Advanced Sub Station Alpha
Compression mode         : Lossless
Language                 : English
Default                  : Yes
Forced                   : No
Statistics Tags Issue    : no_variable_data 1970-01-01 00:00:00 / no_variable_data 2010-02-22 21:41:29
FromStats_BitRate        : 138
FromStats_Duration       : 00:23:37.370000000
FromStats_FrameCount     : 318
FromStats_StreamSize     : 24562

----------------------- Indexing using ffmsindex -----------------------

D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\both\ffms2\ffmsindex.exe "D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p].mkv" "D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_temp\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p].ffindex"

Writing index... done.

Start:    18:42:43
End:      18:42:51
Duration: 00:00:07

-------------------------- VapourSynth Script --------------------------

import os, sys
import vapoursynth as vs
core = vs.get_core()
sys.path.append(r'D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\Scripts')
import importlib.machinery
mvsfunc = importlib.machinery.SourceFileLoader('mvsfunc', r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\Scripts\mvsfunc.py").load_module()
adjust = importlib.machinery.SourceFileLoader('adjust', r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\Scripts\adjust.py").load_module()
havsfunc = importlib.machinery.SourceFileLoader('havsfunc', r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\Scripts\havsfunc.py").load_module()
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\AWarpSharp2\libawarpsharp2.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\both\ffms2\ffms2.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\both\flash3kyuu_deband\flash3kyuu_deband.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\CTMF\CTMF.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\DCTFilter\DCTFilter.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\Deblock\Deblock.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\DFTTest\DFTTest.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\EEDI2\EEDI2.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\EEDI3m\EEDI3m.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\FFT3DFilter\fft3dfilter.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\FluxSmooth\libfluxsmooth.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\fmtconv\fmtconv.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\HQDN3D\libhqdn3d.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\both\KNLMeansCL\KNLMeansCL.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\BM3D\BM3D.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\mvtools\libmvtools.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\nnedi3\libnnedi3.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\nnedi3\NNEDI3CL.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\Sangnom\libsangnom.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\scenechange\scenechange.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\SVPFlow\svpflow1_vs64.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\SVPFlow\svpflow2_vs64.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\vs\TTempSmooth\TTempSmooth.dll")
core.std.LoadPlugin(r"D:\StaxRip-x64-2.0.4.10-beta\Apps\Plugins\VS\nnedi3\vsznedi3.dll")
clip = core.ffms2.Source(r'D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p].mkv', cachefile=r'D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_temp\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p].ffindex')
#clip = core.std.AssumeFPS(clip, None, 25, 1)
clip = core.f3kdb.Deband(clip, preset="high", output_depth="10")
clip = havsfunc.santiag(c=clip, opencl=True, nns=3, nsize=3, qual=2)
clip = core.warp.AWarpSharp2(clip=clip, type=1, chroma=1, thresh=32)
clip.set_output()

-------------------------- Script Properties --------------------------

Source Frame Count : 34046
Source Frame Rate  : 23.976024
Source Duration    : 00:23:40.0020000
Target Frame Count : 34046
Target Frame Rate  : 23.976024
Target Duration    : 00:23:40.0020000

----------------------- MediaInfo Audio Source 1 -----------------------

General
Complete name         : D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p].flac
Format                : FLAC
Format/Info           : Free Lossless Audio Codec
File size             : 84.9 MiB
Duration              : 23 min 40 s
Overall bit rate mode : Variable
Overall bit rate      : 502 kb/s

Audio
Format                : FLAC
Format/Info           : Free Lossless Audio Codec
Duration              : 23 min 40 s
Bit rate mode         : Variable
Bit rate              : 501 kb/s
Channel(s)            : 2 channels
Channel layout        : L R
Sampling rate         : 44.1 kHz
Bit depth             : 16 bits
Compression mode      : Lossless
Stream size           : 84.9 MiB (100%)
Writing library       : libFLAC 1.3.2 (UTC 2017-01-01)

---------- Video encoding using x265 3.2+5-gfbe9fef31 Patman ----------

"C:\Program Files\VapourSynth\core\vspipe.exe" "D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_temp\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_new.vpy" - --y4m | D:\StaxRip-x64-2.0.4.10-beta\Apps\Encoders\x265\x265.exe --crf 16 --preset veryslow --level-idc 4 --output-depth 10 --rd 4 --ctu 32 --limit-refs 0 --analysis-reuse-level 4 --limit-tu 0 --no-rect --no-amp --early-skip --rskip --ssim-rd --qg-size 8 --aq-strength 0.8 --qcomp 0.65 --cbqpoffs -2 --crqpoffs -2 --pbratio 1.2 --merange 44 --rc-lookahead 80 --lookahead-slices 1 --min-keyint 1 --keyint 540 --limit-sao --sao-non-deblock --frames 34046 --y4m --output "D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_temp\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_new_out.hevc" -

指定された行数および桁数に画面を設定できません
Google Translate: Unable to set the screen to the specified number of lines and columns

Start:    18:50:10
End:      18:50:10
Duration: 00:00:00

-------------------- Encoder output file is missing --------------------

D:\video\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_temp\[HorribleSubs] Sword Art Online - Alicization - War of Underworld - 03 [1080p]_new_out.hevc

**Comment by stax76** [comment]
It's not reproducible for me, I tried by using the same script and x265 settings and the same filename and it was working.

The error message talks about columns and lines and that sounds like cmd is causing this error 
 but it's strange that the exit code is 0 which means no errors.

I'll research it.

**Comment by bakamosokyo** [comment]
> It's not reproducible for me, I tried by using the same script and x265 settings and the same filename and it was working.
> 
> The error message talks about columns and lines and that sounds like cmd is causing this error
> but it's strange that the exit code is 0 which means no errors.
> 
> I'll research it.

Speaking about cmd, my cmd is crashing. I remember this was happened after I failed abort a project, and have to close it manually in task manager. I don't have information about this, it's just freezing and no respond.
This seems like just another bug of windows 10. I guess I can only reinstall windows. 

Thanks for your work, have a nice day.
