### ISSUE TITLE
Distorted video frame rate after encoding

### ISSUE THREAD

**Issue by mrtaichi** [staxrip/staxrip#836]
Ver 2.7.0 to 2.10.0 - All distort the video frame rate after encoding.

They may either increase the video frame rate or decrease compared to the original. 
For example, 23.976 to 23.81 & 29.97 to 30.303.

I have tried a fresh (portable) setup from each of the above version. Tried on quite a few different video files.
I also used different codecs for encoding and different (Avisynth) sources as well.

However version 2.6.0 does it right.

Update # 1: 
The problem source is identifiable in the temp folder. Since using a temp folder created by the problem versions, creates the same problem with version 2.6.0 as well.

Update # 2:
I see that even 2.6.0 can also have that problem, though definitely not as much.
Interestingly, that problem seemed to specially trigger with the opening feature(s) of a video.
I batch encoded an anime series. It had 5 opening themes. Very strangely, the issue appeared for exactly 3 groups of episodes which start with 3 of the opening themes. The other 2 op theme groups were correctly encoded. & no, those 3 problem groups were not consecutive.

**Comment by Dendraspis** [comment]
This seems to be a very specific problem. I doubt we can help without more information about the source, the used filters, encoder, .....
Is it possible to provide a short sample file that also fails?

Did you check the resulting frame rate in the `Target` section?

**Comment by mrtaichi** [comment]
> This seems to be a very specific problem. I doubt we can help without more information about the source, the used filters, encoder, ..... Is it possible to provide a short sample file that also fails?
> 
> Did you check the resulting frame rate in the `Target` section?

I tested with multiple encoders such as x264, x265, Nvidia H264, H265 etc. 
No additional filters were used. 
Source was default. But I tested with all the available source options.
Yes, I also looked at the FPS in the Target section. It shows the same as the input. There were cases the input FPS (& thus output) were not shown correctly. But when used LWlibavVideosource (source filter) the input and output were shown correctly. However, in ALL cases, the encoded video FPS was wrong, no matter what.

However, this issue never happens when I encoded the videos with Handbrake. Here the output has the same framerate and  same number of frames (Frame rate settings: same as source, constant frame rate)

I will upload a file, sized 375 MB, which caused issues with ver 2.6.0 as well. This file causes huge difference in frame rate. 29.97 to around 24. 
I will admit not all software can read this file video frame rate correctly, however all info above is still true. Handbrake can encode this correctly. In staxrip, using LWlibavVideosource correct source & destination FPS is shown, but encode output fps and frames are incorrect.

File name: [Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358].mkv (375 MB)
File Link: mega.nz/file/2CghFCqY#ivKBFvHMXEmZtbQpprIqOybJq1qwkASr93N5l_znPHw
if there is a problem with download link, the file also obtainable through nyaa torrent website or other sources.
I hope the file size does not cause any inconvenience.

**Comment by mrtaichi** [comment]
MKV VFR timestamps extraction is turned on & also container options has the timestamps file selected. They always were.

Though the source filter (from AVSFilter edit code ) default shows as follows:
`FFVideoSource("%source_file%", cachefile="%source_temp_file%.ffindex")`

It is mentionable all the above the settings were untouched defaults for all the versions I tested. 
It seems to me though the source filter code might be the potential issue here.

I tried the paste your code in the edit code window of AVSFilters. It shows an error Script Error

```
Script error: expected a , or )
(D:\[ Downloads ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_temp\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_new.avs, line 4, column 155)
```

**Comment by mrtaichi** [comment]
attached the following files:
[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_new.avs
[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_new_source.avs

[avs files.zip](https://github.com/staxrip/staxrip/files/8342667/avs.files.zip)

**Comment by Dendraspis** [comment]
Okay, I'm completely lost now. You are using VapourSynth commands inside a AviSynth file !?!
Something is wrong here ... and it looks like a usage mistake....

My VS script file:
```
import os, sys
import vapoursynth as vs
core = vs.get_core()

sys.path.append(r"X:\Apps\Plugins\VS\Scripts")
core.std.LoadPlugin(r"X:\Apps\Plugins\Dual\ffms2\ffms2.dll", altsearchpath=True)
tcFile = r"A:\[ Download ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_temp\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_timestamps.txt" # timestamps file path
clip = core.ffms2.Source(r"A:\[ Download ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358].mkv", cachefile=r"A:\[ Download ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"A:\[ Download ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358].mkv", cachefile=r"A:\[ Download ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_temp\temp.ffindex")
clip.set_output()
```

My AVS script file:
```
AddAutoloadDir("X:\Apps\FrameServer\AviSynth\plugins")
LoadPlugin("X:\Apps\Plugins\Dual\ffms2\ffms2.dll")
FFMS2("A:\[ Download ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358].mkv", atrack=-1, cachefile="A:\[ Download ]\[Yellow-Flash]_Naruto_Shippuden_001-151\[Yellow-Flash]_Naruto_Shippuden_-_004_[DVD][576p][10bit][748B8358]_temp\temp.ffindex")
``` 

Both projects ran fine and created an expected (and synced) result...

**Comment by mrtaichi** [comment]
> Okay, I'm completely lost now. You are using VapourSynth commands inside a AviSynth file !?!
> Something is wrong here ... and it looks like a usage mistake....

Well yes it seems so. Like I said in the last post, I copy pasted your code in the AVSFilter source edit code. The reason for me doing that is that I did not know that code is applicable to VSFilter source. 

However this does not change the situation since it is a one time case. All other times, they were as they should be. Both the Avisynth and VapourSynth script are like the one you showed in your last post, Except my Vapoursynth file does not have any tcFile and timecodes elements.

Now following up with my next attempts:
This time around I encoded with ffms2 source & LWLibavSource, to see if VPS (Vapoursynth) may correct the issue as I have never used VPS before. It did not.

Then I used your code with ffms2 VPS. However even then the issue remained the same. 

I have tested with portable setup with fresh settings for all the versions. So there should be any issue of user modification that may cause this issue. I do not know if this problem can be attributed to the system somehow.

Can you check the following for your output file?
Original and thus output file should have the following features:
FPS=29.97 & video frames = 38881

**Comment by Dendraspis** [comment]
Ah, okay. I posted it just for comparison reasons and to show you how it could look like.  😁 

> Except my Vapoursynth file does not have any tcFile and timecodes elements.

The entry only appears if your source file has timestamps, like a VFR video file, like the one you provided. So in this case your *Source Filter* should look like mine.

> Original and thus output file should have the following features:
> FPS=29.97 & video frames = 38881

Via MediaInfo I get these info:
#### Original
```
Duration                       : 21 min 37 s
Frame rate mode                : Variable
Frame rate                     : 23.976 (23976/1000) FPS
Frame count                    : 31097
```
#### Encode
```
Duration                       : 21 min 37 s
Frame rate mode                : Variable
Frame rate                     : 23.976 (23976/1000) FPS
Original frame rate            : 23.976 (24000/1001) FPS
Frame count                    : 31097
```

I don't know why you have more problems than me, but I guess the problem is the whole source file. 
MediaInfo tells me it is `21m37s` long, whereas my player tells me `36m03s`, stopping at `21m37s`. The issue seems to be the sound file. When you demux the original file, the video file is `17m17s` long, whereas the audio file is `36m03s`long and stops playing at  `21m37s`.
So for me there is something broken, at least very difficult to handle. 
Maybe you should try to re-mux the file via StaxRip, MKVToolNix or mkvmerge and retry the encode. I don't think I can help you any further, because for me it works.  😕

**Comment by Dendraspis** [comment]
Sure, but it seems to be related to the source and the kind of video file. And sadly I can't reproduce your problem, because for me it works ... the encode is smooth and in sync.  😕 

> However I don't think the info mediainfo shows is correct.

I agree, because it seems to be 23.810 fps.

> Playback duration has never been a problem with any software for any of the videos.

Like already mentioned: My encodes work great. I had to force the out-of-sync-issue by removing the timestamps, but with it there was no problem.

**Comment by mrtaichi** [comment]
> I agree, because it seems to be 23.810 fps.

um it's 23.810 vs 29.97 (original) & 30889 vs  38881 (original). Audio issues also occur for some files or series.

Anyway thank you for your support. You can close the thread if you wish.

**Comment by Dendraspis** [comment]
No, I meant the original one has 23.810 fps (average). The different frame count between you and me is really annoying, because every of my files (original and encodes) have 31097 frames.  😕 

Yeah, it seems to be system related, at least it is not reproducible at all. I hope you'll find the culprit!
Feel free to reopen the issue if you have new information.

**Comment by mrtaichi** [comment]
> No, I meant the original one has 23.810 fps (average). The different frame count between you and me is really annoying, because every of my files (original and encodes) have 31097 frames. 😕

It seems there are still some misunderstanding. Just to clear that.

I too get 31097 frames for the both input & output videos, IF I use mediainfo, like you.

However the result is very different if analyzed with mkvinfo, Lossless cut and potplayer's (own Tab info). That's why I think you will get the modified readings as well if you use these programs.

**Comment by Dendraspis** [comment]
Yes, it was indeed. Nevertheless the frameservers confirm MediaInfo.
MkvInfo and some other tools are surely *confused * by the whole length due to the (maybe broken) audio file.

**Comment by mrtaichi** [comment]
I have remuxed the mkv file keeping only the video. The encode result is the same. So is the video data with those software, both before and after the muxing. If the problem is due to the audio file analysis, should not the remuxing have solved the issue?

Also can you tell me how do you see the framecount with the frameserver method?

**Comment by Dendraspis** [comment]
Totally depends on the previous made settings and how the audio file were muxed, extracted and re-muxed.  It also depends which tool you use for extraction. I've got an MKV file, where the tracks are 3s shorter or longer, depending on the tool you used for extraction.

So sadly I can't give you a recommendation on this one, because it seems to be too specific.

> Also can you tell me how do you see the framecount with the frameserver method?

Sadly no, but I would advice you to join in our [Discord server](https://discord.gg/uz8pVR79Bd) and ask other users and/or use a forum to ask others. See also: [Community](https://github.com/staxrip/staxrip#community)

**Comment by mrtaichi** [comment]
@Dendraspis
The file I provided do not have noticeable audio sync issue after encoding with staxrip. 
However I said before in a post that most of the anime I am trying to encode is showing this problem & many with audio sync issue. 

In this post I will list some anime from different release groups (with links) and also audio sync problems. It is difficult to think that all these release groups have problematic audios.

If you are interested, you can explore the problem deeper.

#1. Naruto [(by Yellow-Flash)](https://nyaa.si/view/1246892)
**#2. Naruto Shippuden** [(by Yellow-Flash)](https://nyaa.si/view/1501749)
**#3. Jyu Oh Sei**  [(by Yellow-ASS)](https://nyaa.si/view/1256082) - A different release group
#4. Rurouni Kenshin [(by SOFCJ-Raws)](https://nyaa.si/view/1252970)

#1. Naruto - wrong FPS problem is there. But no significant audio sync issue. So I encoded the whole batch & kept it like so.

#2. Naruto Shippuden - I have encoded the batch & I have found that most of the files suffer from audio sync issue, some more than others. The desync can be more significant at any part of the video like in the middle (i.e. ep 8) or more toward the end etc.

#3. Jyu Oh Sei - Here the **japanese audio** gets out of sync. Staxrip ver. 2.6.0 can output 4 out of 11 files correctly. Other versions would probably mess up more. You can try ep 3 or 4. I have tried encoding with the audio as well (only japanese or both). Still did not work. Very strangely though, out of many attempts, one attempt of encoding ep 3 with jp audio only somehow produced correctly synced audio while the wrong FPS was there. Could not reproduce this.

#4. Rurouni Kenshin - FPS problem is there. But no noticeable audio sync issue. (tested only one eps)

The thing is I can't encode a whole series with issues mentioned above without having desynced audios. I am confident you will find the same issues. I hope that you can at least suggest a way following which the audio sync issues can be avoided.

I should state that, FFBatch, a ffmpeg based batch encoder, does a perfect job of maintaining correct FPS, video frame count & audio sync.
