### ISSUE TITLE
Implement option to utilize Intel Quick Sync encoding of VP9 video (via VP9_QSV for Icelake+)

### ISSUE THREAD

**Issue by ray890** [staxrip/staxrip#840]
In 2019-11-04, FFmpeg added the VP9_QSV encoder library to enable Intel Icelake and later processors to hardware encode to VP9 through Quick Sync Video. 

Implementation of this option will allow those with supported hardware to have an user-friendly way to take advantage of this hardware encoding to VP9.

**Comment by Dendraspis** [comment]
The next release will have the newest QSVEnc release included, which supports VP9. This should suit your needs.
