### ISSUE TITLE
Please fix batch encoding 

### ISSUE THREAD

**Issue by kusy0** [staxrip/staxrip#843]
Hi 
I used file batch to hardcode videos but subtitles didn't include although I chose the option to include and  hardcode it

**Comment by Dendraspis** [comment]
Please use the ***Report a bug*** template and fill it with useful information....

**Comment by kusy0** [comment]
![Screenshot_٢٠٢٢٠٤١١-١٠٤٧١٠_Microsoft Remote Desktop](https://user-images.githubusercontent.com/47747156/162689518-35c5d5f9-c541-40c7-b93d-928eb4d944e6.jpg)
 I need to batch encode videos with uardcoded subtitles but although I chose this option subtitle wasn't burned
And is there an option to automaticly choose the subtitle with the same name to be included not the demuxed one.

**Comment by Dendraspis** [comment]
I've checked it with three test files and couldn't reproduce your issue. The (first) subtitles were always burned in. Seems to be something special with your files or your config. But it works, when you open each file separately?

> And is there an option to automaticly choose the subtitle with the same name to be included not the demuxed one.

No.
