### ISSUE TITLE
TemporalDegrain2 update

### ISSUE THREAD

**Issue by shodan5000** [staxrip/staxrip#844]
Can TemporalDegrain2 for VapourSynth/Avisynth please be updated? The current version is 2.4.3 while the StaxRip version is 2.3.1. Thanks.

**Comment by Dendraspis** [comment]
TemporalDegrain v2 will be updated in the next release, but you know, that you can update tools and scripts manually for your needs?  😉

**Comment by DestroyTargetNonBasicLand** [comment]
While you're at it, please update G41Fun (TemporalDegrain2 for VS (among other things)) to the latest version: https://github.com/Vapoursynth-Plugins-Gitify/G41Fun/blob/master/G41Fun.py

Thanks!

**Comment by Dendraspis** [comment]
Done.   😁👍
