### ISSUE TITLE
Add Auto Rename Feature for Already Existing Output Files

### ISSUE THREAD

**Issue by iamsrk48** [staxrip/staxrip#850]
Feature that can auto add custom words to output files

eg:
"Fast and Furious 9.mkv" Already Encoded and Exists in Target Directory so Staxrip will Automatic Add a Specific word to new Pending Encodings instead of Overwrite "Fast and Furious 9_Staxrip1.mkv"

**Comment by Dendraspis** [comment]
To avoid the message, overwriting or similar you can set the output name to something like `%source_name%_%random:6%`, which should solve your issue.

Side note.
Please fill out the template next time you create an issue/feature request.
