### ISSUE TITLE
Audio Encoding - Command Line

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#853]
"%app:ffmpeg%" -i **"**%input%**"** -b:a %bitrate%k -y -hide_banner **"**%output%**"**

The Command Line as it is now doesn't work. It worked in previous versions. It is because of
"%input%"
"%output%"

It seems that %input% and %output% already have **"** inside and putting a second **"** causes it not to work.

it should be
"%app:ffmpeg%" -i %input% -b:a %bitrate%k -y -hide_banner %output%

**Comment by Dendraspis** [comment]
Thanks, will be fixed in the next release...
