### ISSUE TITLE
WAV FLAC encoding to AAC etc not working for channel conversion.

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#854]
Because channel conversion 6CH to stereo or Normalize is done in the converting to FLAC step, if your original audio file is already FLAC, staxrip does not do a FLAC conversion anymore.

So if you have a 6CH FLAC, you can not convert it to Stereo AAC. After conversion it will be 6CH AAC.

**Comment by Dendraspis** [comment]
You can set `Pipe` (or `W64`) as `Decoding Method` to avoid that:

![image](https://user-images.githubusercontent.com/50659978/162609449-74871622-e005-4de3-963c-a1625bf834fe.png)

![image](https://user-images.githubusercontent.com/50659978/162609468-1b63eba7-7e93-44c9-859a-2f1310ac12d1.png)

**Comment by Zodler** [comment]
Will you fix it or we should always use pipe?

**Comment by Dendraspis** [comment]
Sorry, I forgot to tell, that StaxRip will use ffmpeg automatically to convert and pipe it to qaac, like selecting `Pipe` by hand.
