### ISSUE TITLE
DGHDRtoSDR ignored

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#855]
My script gets a 4k HDR input and converts it to 1080 SDR:

```
SetMemoryMax()
SetFilterMTMode("DEFAULT_MT_MODE", 2)
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
LoadPlugin("D:\Eseguibili\Media\DGHDRtoSDR\DGHDRtoSDR.dll")
DGSource("F:\In\2_55 padrino 1, Il 4K\padrino1.dgi",ct=52,cb=44,cl=0,cr=0, rw=1920, rh=1032)
DGHDRtoSDR(fulldepth=true,mode="pq",white=1500,black=0,gamma=0.42,r=1.00,g=1.00,b=1.15,tm=0.90,roll=0.70)
SMDegrain (tr=3, thSAD=300, refinemotion=true, contrasharp=false, PreFilter=5, plane=4, chroma=true)
fmtc_bitdepth (bits=10,dmode=8)
Prefetch(6)
```

However StaxRip, even giving it the .AVS as input, keeps on passing parameters and color space to x265 such as it is still HDR, perhaps reading the M2TS source.

How can I make it ignore what the source is and simply follow what is given by AVS script?

**Comment by Dendraspis** [comment]
This could solve your problems:
[How to register DGDecNV(DGSource and DGIndexNV) in StaxRip](https://github.com/staxrip/staxrip/wiki/How-to-register-DGDecNV%28DGSource-and-DGIndexNV%29-in-StaxRip)

I also highly recommend to join in out [Discord server](https://discord.gg/uz8pVR79Bd).

**Comment by tormento** [comment]
@Dendraspis I properly set DGDecNV already but that was not the issue, as it happens with other decoders too.

I have found that the "fault" comes from the following option

![image](https://user-images.githubusercontent.com/2351785/162616276-f6bde337-afe6-455a-bc3f-17b357b41cc7.png)

and disabling it, avoids the parameter bypass.

**Comment by Dendraspis** [comment]
Thanks for letting us know what caused the behavior, I'll close it now.
