### ISSUE TITLE
Dolby Vision

### ISSUE THREAD

**Issue by Maxiz80** [staxrip/staxrip#858]
Hi.
I'm using latest version and I'm trying to encode some 4K video.
Those videos has Dolby Vision track too.
I don't get how to use it and how to extract it correctly.

Thanks

**Comment by Dendraspis** [comment]
Have a look at: [Encoding Dolby Vision with StaxRip using x265](https://github.com/staxrip/staxrip/wiki/Encoding-Dolby-Vision-with-StaxRip-using-x265)
Sadly it's not that easy and comfortable to handle with....

**Comment by pannal** [comment]
Hey, I'd like to revive this issue.

Dolby vision is now possible in mkv and the guide is outdated. Dovi tool can reinject DV data into video streams even if they're resized or cropped.

It would be awesome to have proper DV support via dovi_tool in staxrip as the manual process is a lot of steps, that could be well integrated into staxrip work flow.
