### ISSUE TITLE
x265 encoder: no estimated file size

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#86]
Hi Stax, Hi Patman,
The x265 encoder included in v2.0.6.0 does not show the estimated file size. I remember that the beta 2.0.4.10 did, and the x265 was Patman's.
That was a nice feature, I hope you'll put it back!
Thanks for the good work!

**Comment by Patman86** [comment]
Hi vince,

i think that had something to do with my custom build. At the weekend i want to compile and test new builds.

**Comment by 44vince44** [comment]
Thanks :) when available could we have a link to download it?

**Comment by Patman86** [comment]
[Here](http://www.mediafire.com/file/sgkjcujl2wq7lho/x265_custom-3.2%252B15-04db2bfee5d6.7z/file)

**Comment by 44vince44** [comment]
Many Thanks, Patman! I've been very busy yesterday, but now I'm gonna try it!

**Comment by 44vince44** [comment]
Thanks again Patman! It's a small feature but I find it very useful!!
