### ISSUE TITLE
AC3 encode.....Demux audio returned exit code: 1 (0x1)

### ISSUE THREAD

**Issue by dsyuan** [staxrip/staxrip#860]
Error Demux audio (v2.11.0)

Demux audio returned exit code: 1 (0x1)

the video file is here:

https://drive.google.com/file/d/1BzVWYzwreVTWLt0yaptFvNSrAOxD1BqJ/view?usp=sharing

StaxRip config file( intel.srip ) is here:

https://drive.google.com/file/d/1dEwKY6sUPI_I4BUOFQPTvFZDA3KWGZ81/view?usp=sharing

If the audio encoding of the video file is AAC（Not AC3 in this file）, it works well.  Bigasoft Total Video Converter 6 can converte this video file.

===================================================================
Error Demux audio (v2.11.0)

Demux audio returned exit code: 1 (0x1)

----------------------------- Demux audio -----------------------------

MP4Box 2.1-DEV-rev79-gdf29bc8a0-x64-gcc11.2.0 Patman

C:\Users\asdf\Desktop\StaxRip-v2.11.0-x64\Apps\Support\MP4Box\MP4Box.exe -raw 4352 -out "C:\Users\asdf\Downloads\Video\cccc_temp\ID1 -80ms.ac3" C:\Users\asdf\Downloads\Video\cccc.mp4

[iso file] Unknown top-level box type G@0010
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G@0010" (start 0) has 21001720 extra bytes
[iso file] Unknown top-level box type G101112
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G101112" (start 21001728) has 619035736 extra bytes
[iso file] Unknown top-level box type 9FD9tq
[iso file] Incomplete box 9FD9tq - start 640037472 size 2056110018
[iso file] Incomplete file while reading for dump - aborting parsing
[iso file] Unknown top-level box type G@0010
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G@0010" (start 0) has 21001720 extra bytes
[iso file] Unknown top-level box type G101112
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G101112" (start 21001728) has 619035736 extra bytes
[iso file] Unknown top-level box type 9FD9tq
Truncated file - missing 2056110018 bytes
Error opening file C:\Users\asdf\Downloads\Video\cccc.mp4: IsoMedia File is truncated

StaxRip.ErrorAbortException: Demux audio returned exit code: 1 (0x1)

----------------------------- Demux audio -----------------------------

MP4Box 2.1-DEV-rev79-gdf29bc8a0-x64-gcc11.2.0 Patman

C:\Users\asdf\Desktop\StaxRip-v2.11.0-x64\Apps\Support\MP4Box\MP4Box.exe -raw 4352 -out "C:\Users\asdf\Downloads\Video\cccc_temp\ID1 -80ms.ac3" C:\Users\asdf\Downloads\Video\cccc.mp4

[iso file] Unknown top-level box type G@0010
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G@0010" (start 0) has 21001720 extra bytes
[iso file] Unknown top-level box type G101112
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G101112" (start 21001728) has 619035736 extra bytes
[iso file] Unknown top-level box type 9FD9tq
[iso file] Incomplete box 9FD9tq - start 640037472 size 2056110018
[iso file] Incomplete file while reading for dump - aborting parsing
[iso file] Unknown top-level box type G@0010
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G@0010" (start 0) has 21001720 extra bytes
[iso file] Unknown top-level box type G101112
[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[iso file] Box "G101112" (start 21001728) has 619035736 extra bytes
[iso file] Unknown top-level box type 9FD9tq
Truncated file - missing 2056110018 bytes
Error opening file C:\Users\asdf\Downloads\Video\cccc.mp4: IsoMedia File is truncated

   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 361
   at StaxRip.MP4BoxDemuxer.DemuxAudio(String sourcefile, AudioStream stream, AudioProfile ap, Project proj, Boolean overrideExisting) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 675
   at StaxRip.MP4BoxDemuxer.Run(Project proj) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 503
   at StaxRip.MainForm.Demux() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 3412
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2215

**Comment by Dendraspis** [comment]
This is because the file is **not** an `MP4` file, it's an `M2TS` file. StaxRip uses the file extension to choose the right tools. Rename it and it will work.
