### ISSUE TITLE
QTGMC's BWDIF+NNEDI3 option broken and Avisynth scripts it uses outdated

### ISSUE THREAD

**Issue by Hackerpcs** [staxrip/staxrip#861]
QTGMC included in the latest 2.11 release is not the latest available one
https://github.com/realfinder/AVS-Stuff/blob/master/avs%202.6%20and%20up/QTGMC.avsi
and `EdiMode="BWDIF+NNEDI3"` is broken because Vinverse_avsi is not included
https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/Vinverse_avsi.avsi
and not loaded when QTGMC is selected, it needs manual loading
```
Import("C:\StaxRip\StaxRip\Data\avisynth_misc\Vinverse_avsi.avsi")
QTGMC(EdiMode="BWDIF+NNEDI3",ThSAD1=1500,MatchTR2=2,tr2=2,EdiThreads=3)
```

Also, from all the plugins that are loaded if QTGMC is selected,
```
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\AddGrainC\AddGrainC.dll")
Import("C:\StaxRip\Apps\Plugins\AVS\AnimeIVTC\AnimeIVTC.avsi")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\Average\Average.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\DFTTest\dfttest.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\Dual\DFTTest Neo\neo-dfttest.dll")
Import("C:\StaxRip\Apps\Plugins\AVS\Dither\dither.avsi")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\Dither\dither.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\EEDI2\EEDI2.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\EEDI3\eedi3.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\Dual\FFT3D Neo\neo-fft3d.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\FFT3DFilter\fft3dfilter.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\Dual\KNLMeansCL\KNLMeansCL.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\masktools2\masktools2.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\modPlus\modPlus.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\mvtools2\mvtools2.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\RgTools\RgTools.dll")
Import("C:\StaxRip\Apps\Plugins\AVS\SMDegrain\SMDegrain.avsi")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\MedianBlur2\MedianBlur2.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\TDeint\TDeint.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\yadifmod2\yadifmod2.dll")
Import("C:\StaxRip\Apps\Plugins\AVS\Zs_RF_Shared\Zs_RF_Shared.avsi")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\masktools2\masktools2.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\vinverse\vinverse.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\Bwdif\BWDIF.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\Dual\ffms2\ffms2.dll")
LoadPlugin("C:\StaxRip\Apps\Plugins\AVS\JPSDR\Plugins_JPSDR.dll")
Import("C:\StaxRip\Apps\Plugins\AVS\QTGMC\QTGMC.avsi")
```
besides QTGMC itself, there are some that were not updated in the latest release and could be updated to latest in the next release:
AddGrainC
https://github.com/pinterf/AddGrainC/releases
AnimeIVTC
https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/AnimeIVTC.avsi
Average
https://github.com/pinterf/Average/releases
DFTTest
https://github.com/pinterf/dfttest/releases
Dither
http://ldesoras.free.fr/prod.html#src_ditheravsi
EEDI2
https://github.com/Asd-g/AviSynth-EEDI2/releases
FFT3DFilter
https://github.com/pinterf/fft3dfilter/releases
JPSDR
https://github.com/jpsdr/plugins_JPSDR/releases
Masktools2
https://github.com/pinterf/masktools/releases/
ModPlus
http://avisynth.nl/index.php/ModPlus
https://web.archive.org/web/20200924160955/http://www.avisynth.nl/users/vcmohan/modPlus/modPlus.7z
SMDegrain
https://github.com/Dogway/Avisynth-Scripts/blob/master/SMDegrain%20v3.4.9d/SMDegrain%20v3.4.9d.avsi
Zs_RF_Shared
https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/Zs_RF_Shared.avsi

**Comment by Hackerpcs** [comment]
Another note, the actual latest QTGMC (v3.384s, Community branch is the main, not the master I linked above)
https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.6%20and%20up/QTGMC.avsi

doesn't use Vinverse_avsi that isn't used anymore, it uses `vinverse.dll` by Asd-g
https://github.com/Asd-g/vinverse/releases
which updates the 2013 version included in latest StaxRip 2.11 so it should be updated to make QTGMC lastest work

**Comment by Dendraspis** [comment]
Thanks very much, I'll update all scripts for release **v2.13.0**, because it takes some time to do it. I think release will take place early next week.

Please have a look at our [Tool Request Wiki-Page](https://github.com/staxrip/staxrip/wiki/Tool-Update-Requests), where you can edit the page I try to check before each release, except the next one. 😅

**Comment by Dendraspis** [comment]
Are updated and will be distributed with the next release.

Thanks.  👍
