### ISSUE TITLE
SVT-AV1 - Two small UI bugs

### ISSUE THREAD

**Issue by McMasterGold** [staxrip/staxrip#863]
There are two small UI bugs with SVT-AV1:

1. When the QP value is set to 50 (default), the encoder seems to use CRF 35 instead. This is what it says in the log while encoding:

Svt[info]: SVT [config]: BRC Mode / Rate Factor / SceneChange : CRF / 35 / 0

Any other value seems to work correctly.

2. SVT-AV1 0.9.x added four new presets, 9-12 (there is also preset 13 but as far as I understand that's for debugging only). However, they are not listed in the drop-down Preset menu (in Encoder Options), it only goes down to "8: Ultra Fast". This is only a minor issue however, as the faster presets can be used by adding the --preset custom parameter.

The issues occur with the latest v2.12.0 build.

**Comment by Dendraspis** [comment]
To be precise a lot of options are missing, but I fixed both mentioned issues and added `--aq-mode` for now.

> When the QP value is set to 50 (default), the encoder seems to use CRF 35 instead

35 is the right default, the UI showed the wrong default.

> SVT-AV1 0.9.x added four new presets, 9-12 (there is also preset 13 but as far as I understand that's for debugging only).

-2 and -1 are for debugging, the others are normal values.

You can use this one till the next release, which should be next week:
[StaxRip-v2.12.2.zip](https://github.com/staxrip/staxrip/files/8520026/StaxRip-v2.12.2.zip)
