### ISSUE TITLE
Strange behaviour while deinterlacing

### ISSUE THREAD

**Issue by bananenmann66** [staxrip/staxrip#864]
**Describe the bug**
While using QTGMC for deinterlacing older MPEG2-/-VOB-files (Pal, NTSC but also 1080p-MPEG2-HDTV-files) the produced material is NOT progressive, when I choose ffmpeg-ProRes output in a MOV Container.  MediaInfo reports the produced file to be formerly progressive and afterwards changed  to "interlaced" (?) - what is definetively wrong. The source material had been interlaced. I tried it with different interlaced video clips and everytime got the same mediainfo report.

**10 second testfile (with StaxRip 2.11 and 2.12 - OR with StaxRip 2.10 with ffmpeg from Staxrip 2.11 or 2.12):**
Video
ID                                           : 1
Format                                   : ProRes
Format version                      : Version 0
Format profile                       : 422 HQ
Codec ID                               : apch
Duration                                : 10 s 0 ms
Bit rate mode                         : Variable
Bit rate                                   : 111 Mb/s
Width                                     : 720 pixels
Height                                    : 576 pixels
Display aspect ratio                : 4:3
Frame rate mode                    : Constant
Frame rate                               : 50.000 FPS
Color space                              : YUV
Chroma subsampling               : 4:2:2
**Scan type                                 : Interlaced
Original scan type                    : Progressive
Scan type, store method          : Interleaved fields
Scan order                                : Top Field First**
Bits/(Pixel*Frame)                     : 5.363
Stream size                               : 133 MiB (98%)
Writing library                          : fmpg

**Same Video-File with StaxRip 2.10:**
Video
ID                                       : 1
Format                                   : ProRes
Format version                           : Version 0
Format profile                           : 422 HQ
Codec ID                                 : apch
Duration                                 : 10 s 0 ms
Bit rate mode                            : Variable
Bit rate                                 : 111 Mb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 50.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:2
**Scan type                                : Progressive**
Bits/(Pixel*Frame)                       : 5.363
Stream size                              : 133 MiB (98%)
Writing library                          : fmpg

**Expected behavior**
With staxrip 2.10 medianfo reports the same video sources as "progressive" after deinterlacing with QTGMC (as it should be). The bug is in Version 2.11 and in Version 2.12 as well.

**Additional context**
I'm not a specialist in encoding, but I found out, that the bug has something to do with the new ffmpeg-version in the "StaxRip\Apps\FrameServer\AviSynth"-Folder. (I returned back to version 2.10 and replaced a few newer files from version 2.12 - and after I replaced that ffmpeg file the mysterious behavior came back.). Then I tried something else: I replaced the ffmpeg.exe with the one from here: https://www.gyan.dev/ffmpeg/builds/ ... and got the same (buggy ?) results like with StaxRip 2.11 and 2.12. It seems to be a problem with newer ffmpeg builds?!

Thanx in advance - and sorry if my report is too simple. I'm not a specialist, as I mentioned before. Have a nice day!!! ;)

**Comment by Dendraspis** [comment]
As far as I remember nothing has changed, except ffmpeg itself.

You can replace the new `ffmpeg.exe` with the old one and check the result. If the result is `progressive` then you've found the reason.

**Comment by Dendraspis** [comment]
So I close it for now...

**Comment by bananenmann66** [comment]
Sorry, it IS reproducable.... everytime...
As I told here in my starting post: When I take the newest Staxrip Release (2.12) and replace the (new) ffmpeg which is included in it with the old one (from Staxrip 2.10) the result is always "progressive" !!! When I don't do this the result is always "interlaced".
