### ISSUE TITLE
Says demuxing audio failed. Attaching the log file too.

### ISSUE THREAD

**Issue by rohitghali** [staxrip/staxrip#865]
Just added the file by dragging and dropping and the error popped.
[LG OLED TV 2020 in 4K HDR 30 fps - LG Demo OLED TV_staxrip.log](https://github.com/staxrip/staxrip/files/8560847/LG.OLED.TV.2020.in.4K.HDR.30.fps.-.LG.Demo.OLED.TV_staxrip.log)

**Comment by Dendraspis** [comment]
Seems your file is a TS file, not an MP4. Additionally it could be broken.
