### ISSUE TITLE
After cutting,the video processing's speed became slow

### ISSUE THREAD

**Issue by WildEgoLee** [staxrip/staxrip#875]
Hello,I found a question in staxrip 2.12.0.When I use NVEnc to process a 1080P video ,the speed can reach 120 fps.
But when I use cutting and only process the cut video ,the speed reached 48 fps.Why the speed declined so much.
And when I process a 2160P video,the speed can reach 50 fps.When I use cutting,the speed also can reach 45 fps.
So why 1080p and 2160p videos' speed almost become same.
Wish you can give me some suggestion.Thanks!

**Comment by Dendraspis** [comment]
Should be related to the source filter and frame server, maybe other filters as well.
