### ISSUE TITLE
how to set the output frame rate?

### ISSUE THREAD

**Issue by 032** [staxrip/staxrip#88]
how to set the output frame rate?

**Comment by Patman86** [comment]
More infos pls. Which encoder, settings etc.

**Comment by 44vince44** [comment]
I'm taking a guess: 032, you can "set" the output frame rate by using a filter such as "AssumeFPS" or "ConvertFPS". It is done with filters!

**Comment by 032** [comment]
> I'm taking a guess: 032, you can "set" the output frame rate by using a filter such as "AssumeFPS" or "ConvertFPS". It is done with filters!

thanks
