### ISSUE TITLE
Can I combine two audio streams in a mux

### ISSUE THREAD

**Issue by RagingFlames** [staxrip/staxrip#885]
I basically have a video file that has two audio streams, and I want to combine them into one audio stream. Preferably, I'd like this to happen as fast as possible, but sometimes I need to do this while transcoding the video. Can I do this using staxrip, and if so how?

**Comment by Dendraspis** [comment]
This cannot be done in StaxRip itself and needs to be done externally or at least via execution of a tool like `ffmpeg` or so.
