### ISSUE TITLE
mkvmerge versions bigger then v64 do not work with Windows 7

### ISSUE THREAD

**Issue by crisc2000** [staxrip/staxrip#886]
Hello,
I use Windows 7 x64. I updated from version StaxRip-v2.7.0 to StaxRip-v2.13.0

After that my MKV files were not created anymore. **I saw no error message on the screen**. The log file showed a message that the mkv was not created.

Maybe has something to do with the fact that last version of MKVToolNix bigger then v64 are not compatible with Windows 7?

So I downgraded to StaxRip-v2.10.0 that use MKVToolNix v61.0 and now it's working fine.
StaxRip-v2.11.0 use MKVToolNix v66.0 , I didn't tested if it's working on Windows 7.

I search google and found no documented page of this issue, that's why I have created this report.

My suggestion is:
- StaxRip should have a version that use the mkvmerge v64, the last version that is compatible with Window 7
- For other StaxRip versions that use mkvmerge bigger then v64, should show a warning to the Window 7 user when choosing "mkv" file output, showing a warning message with the last version of Staxrip and MkvMerge that is compatible with Win 7.

**Comment by fredlkrue** [comment]
I have the same issue, but version 66 of mkvtoolnix works with Windows 7. I just replace mkvtoolnix 66 with the version that comes with StaxRip 2.13.0 and works fine.

**Comment by zettimetti** [comment]
MKVToolNix don't support Windows 7 anymore, check this thread:
https://forum.doom9.org/showpost.php?p=1967393&postcount=1566

mkvtoolnix-64-bit-68.0.0-revision-001-g6a55c58d2 is reported to work, you can download it here:
https://mkvtoolnix.download/windows/continuous/64-bit/68.0.0/

And you can check this thread for working versions:
https://forum.doom9.org/showthread.php?t=184092

**Comment by nikolasr** [comment]
OK, so what to do now? I'd suggest implementing a warning in Staxrip if Windows <=Windows7 is detected, informing the shipped mkvtoolnix version is incompatible with windows 7 or earlier. Maybe combined with a helpful hint/workaround that, while being unspported, it is possible to use own versions of tools and to manually download and use version 64 instead?

**Comment by crisc2000** [comment]
> I'd suggest implementing a warning in Staxrip if Windows <=Windows7 is detected, informing the shipped mkvtoolnix version is incompatible with windows 7 or earlier. Maybe combined with a helpful hint/workaround that, while being unsupported, it is possible to use own versions of tools and to manually download and use version 64 instead?

Yes. Good idea.

**Comment by Ding-adong** [comment]
Just dl staxrip and extract all the files except mkvtoolnix folder and paste over your existing staxrip that works with max version 67.

**Comment by Dendraspis** [comment]
Just extract StaxRip and replace MKVToolNix with a Windows7 compatible version, for example v67.0.

**Comment by Dendraspis** [comment]
The Readme is going to be updated with the next release, so I close this now...

**Comment by Dendraspis** [comment]
...and I've added a quick check and a warning on Windows7 machine, just to inform the user about incompatible tools.

**Comment by crisc2000** [comment]
> ...and I've added a quick check and a warning on Windows7 machine, just to inform the user about incompatible tools.

Great, thanks
