### ISSUE TITLE
Bug frame-rate after encoding

### ISSUE THREAD

**Issue by MarcoHD75** [staxrip/staxrip#889]
In the latest version , after encoding a movie of 24fps, the frame-rate in the mediainfo report is correct (screenshot below) but in reality it is not true.
![1](https://user-images.githubusercontent.com/106778426/171744531-4af5d458-2651-4197-a40e-d7402b4e9c37.png)

If I play the movie with Media Player Classic, as seen in the screenshot, the exact frame-rate is 23,810.
![2](https://user-images.githubusercontent.com/106778426/171744525-29d9df14-a6ee-428e-bd0b-bdbadeb2028d.png)

I tried to apply various Framerate filters, setting 24,25,60 ..., but the result is the same.

With version 2.5.0 it works correctly.

Bye.

**Comment by darkcity87** [comment]
Most likely your source video constant 24 fps but because of timestamps mediainfo shows false vfr and mpc shows false 23,810 fps. Unclick (Options>timestamps>Extract timestamps from mkv) before adding video or remove timestamps from (Container Options>Timestamps) after adding video

**Comment by MarcoHD75** [comment]
I had read in another problem but i had done the opposite by clicking the 2 options. Tnank you :)
Problem solved
