### ISSUE TITLE
SVT-AV1 requires `--pred-struct 1`  for CBR

### ISSUE THREAD

**Issue by BuyMyMojo** [staxrip/staxrip#890]
**Describe the bug**
At least with the 1.0-1.1 releases of SVT-AV1 CBR isn't supported when the prediction structure is set to random access, which is the default, so it requires `--pred-struct 1` to be added since it isn't handled automatically.

**Expected behavior**
A CBR/CVBR video.

**How to reproduce the issue**

1. Set the encoder to `AV1 > SVT-AV1` with the latest standalone encoder
2. Under "Encoder Options" set mode to `2: CVBR`
3. Encode

**Provide information**

It will print out `Svt[warn]: CBR Rate control is currently not supported for PRED_RANDOM_ACCESS, switching to VBR` in the processing window.

Full output:

```log
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.1.0
Svt[info]: SVT [build]  :	Visual Studio 2019 64 bit
Svt[info]: -------------------------------------------
Svt[warn]: CBR Rate control is currently not supported for PRED_RANDOM_ACCESS, switching to VBR
Svt[info]: -------------------------------------------
Svt[info]: SVT [config]: preset 							: Pass 1
Svt[info]: -------------------------------------------
Encoding          
Average System Encoding Speed:        100.00
```

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version: 2.13.0

**Comment by Dendraspis** [comment]
As this is so old now and SVT-AV1 will be updated to `v1.6.0`, I close this for now...
