### ISSUE TITLE
x265 option Scenecut Aware QP is implemented incorrectly in StaxRip's GUI

### ISSUE THREAD

**Issue by Hasselshoff** [staxrip/staxrip#891]
**Describe the bug**
In the Rate Control 3 section of the x265 Options menu, the "Scenecut Aware QP" option appears to be incorrectly implemented. Thanks to StaxRip displaying the actual command arguments added after selecting encoder options, I can see that the flag being added to the command line is: 
`--scenecut-aware-qp`

![image](https://user-images.githubusercontent.com/69090157/172239080-d9359739-bd15-4a4a-b319-5be27daa12b1.png)

However, according to the [x265 docs](https://x265.readthedocs.io/en/master/cli.html?highlight=scenecut#cmdoption-scenecut-aware-qp) (screenshotted below), usage of the Scenecut Aware QP flag requires specifying an integer parameter to indicate one of three modes: Forward, Backward, & Bi-directional QP modification.

![image](https://user-images.githubusercontent.com/69090157/172231297-b99b01b3-ccfb-4f28-89f6-6244e12997f5.png)

Attempting to run the command without specifying an integer argument causes the encode process to fail, returning an invalid argument error because x265 was expecting an integer argument for `--scenecut-aware-qp`.

**Expected behavior**
There should be a dropdown with the 4 mode options: disabled, Forward, Backward, & Bi-directional QP modification. This allows the user to specify which mode to use, same as the dropdowns for RD modes & AQ modes.

**How to reproduce the issue**
1)  select x265 encoder → Options → Rate Control 3 → enable Scenecut Aware QP
2)  Attempt to run the encode job.
3)  Encode fails & returns invalid argument error.
Source video file does not change the behavior, but I have tested using several different videos just to be sure.

**Provide information**
Here is the invalid argument error. Note that in this case this error message includes the `--colorprim` flag simply because that happened to be the very next flag in my command, where x265 was expecting an integer argument for `--scenecut-aware-qp`:

```
Error Video encoding (v2.13.0)

Video encoding returned exit code: 1 (0x1)


--------------------------- Video encoding ---------------------------

x265 3.5+37+12-4e46995bc-.Mod-by-Patman.-x64-msvc1931

C:\Users\Shoff\Programs\StaxRip-v2.13.0-x64\Apps\Encoders\x265\x265.exe --reader-options library=C:\Users\Shoff\Programs\StaxRip-v2.13.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --crf 18 --output-depth 10 --rd-refine --ssim-rd --dynamic-refine --aq-mode 5 --aq-motion --scenecut-aware-qp --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --output C:\Users\Shoff\Videos\StaxRip\UFC_test\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_temp\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_x265_crf_18_aqmode5_aq-motion_scenecut_aware_out.hevc C:\Users\Shoff\Videos\StaxRip\UFC_test\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_temp\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_x265_crf_18_aqmode5_aq-motion_scenecut_aware.avs

x265 [FLAW]: invalid argument: scenecut-aware-qp = --colorprim

StaxRip.ErrorAbortException: Video encoding returned exit code: 1 (0x1)


--------------------------- Video encoding ---------------------------

x265 3.5+37+12-4e46995bc-.Mod-by-Patman.-x64-msvc1931

C:\Users\Shoff\Programs\StaxRip-v2.13.0-x64\Apps\Encoders\x265\x265.exe --reader-options library=C:\Users\Shoff\Programs\StaxRip-v2.13.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --crf 18 --output-depth 10 --rd-refine --ssim-rd --dynamic-refine --aq-mode 5 --aq-motion --scenecut-aware-qp --colorprim bt709 --colormatrix bt709 --transfer bt709 --range limited --output C:\Users\Shoff\Videos\StaxRip\UFC_test\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_temp\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_x265_crf_18_aqmode5_aq-motion_scenecut_aware_out.hevc C:\Users\Shoff\Videos\StaxRip\UFC_test\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_temp\sample-ufc.fight.night.184.overeem.vs.volkov.prelims.1080p.hdtv.x264-verum_x265_crf_18_aqmode5_aq-motion_scenecut_aware.avs

x265 [FLAW]: invalid argument: scenecut-aware-qp = --colorprim


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 361
   at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Code\Github\staxrip\staxrip\Source\Encoding\x265Enc.vb:line 74
   at StaxRip.x265Enc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\x265Enc.vb:line 42
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 371
```

**Additional context**
I made an effort to search for mentions of this error on GitHub & using Internet search engines, but I have not looked closely at the latest source code, so it's entirely possible you have already noticed & fixed this checkbox behavior.

**Comment by sheik124** [comment]
Good catch. It didn't appear to be fixed yet, and I was already poking around in there for a different bug with x265 settings so I gave it a go.

**Comment by Dendraspis** [comment]
Thanks for the very detailed report and sorry for the long waiting.
I fixed it now and it will be published with the next release...

**Comment by sheik124** [comment]
Guess that PR was a waste of time.

**Comment by Dendraspis** [comment]
Nope, it's just not merged yet, but it will be...
