### ISSUE TITLE
Audio bitrate

### ISSUE THREAD

**Issue by Maxiz80** [staxrip/staxrip#892]
Hi.
I've noticed that there's a problem when calculating bitrate with some "HD" audio format.
I think the best way to get always correct bitrate is using GetBitrateFromFile instead of GetAudioBitrateFromAudioProfile
    Shared Function GetAudioBitrate() As Double
        'Dim b0 As Double = GetAudioBitrateFromAudioProfile(p.Audio0)
        'Dim b1 As Double = GetAudioBitrateFromAudioProfile(p.Audio1)

        Dim b0 As Double = GetBitrateFromFile(p.Audio0.File, p.SourceSeconds)
        Dim b1 As Double = GetBitrateFromFile(p.Audio1.File, p.SourceSeconds)

        Return b0 + b1 + p.AudioTracks.Sum(Function(arg) arg.Bitrate)
    End Function

**Comment by Dendraspis** [comment]
The whole audio track thingy is going to be re-implemented probably in `v2.42`, so I close this one...
