### ISSUE TITLE
Add uvg266 and other svt-av1 options

### ISSUE THREAD

**Issue by ls-milkyway** [staxrip/staxrip#893]
**Is your feature request related to a problem? Please describe.**
uvg266 is [an open source vvc encoder](https://github.com/ultravideo/uvg266) and lot of important svt-av1 options are missing in the encoder's settings.

**Describe the solution you'd like**
i want uvg266 to be included in staxrip by default & other important svt-av1 parameters...rather than custom command box.
If aomenc settings can be included then svt-av1 should also be considered.

**Describe alternatives you've considered**
No alternatives available.

**Explain why the feature matters to you**
vvc is considered as one of the best video encoder.

**Additional context**
[Link to additional svt-av1 settings.](https://github.com/AOMediaCodec/SVT-AV1/blob/master/Docs/Parameters.md)

**Comment by Dendraspis** [comment]
Repository moved, current parameter information:  https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md
