### ISSUE TITLE
encoder tuning overwrites parameters

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#894]
If you select some tune, such as animation in x265, custom parameters becomes overwritten.

Try, as example, to set --aq-mode 5 and then set tune animation.

--aq-mode 5 will be reset to 2

A correct behaviour would be to change only the parameters that the tune effectively influence.

**Comment by Dendraspis** [comment]
Sorry, strangely missed your report. I'll have a look at it...

**Comment by Dendraspis** [comment]
This behavior lasted for over 7 years, but I agree, it is a bit odd when a tune selection overwrites other settings than the necessary ones. 

Let's see, if anybody bringt up a use case, in which it is necessary.  😬
