### ISSUE TITLE
Skip Temp File Generation When Loading Single File

### ISSUE THREAD

**Issue by ddelella** [staxrip/staxrip#896]
When I want to load a single video file I have to wait for 20-30 minutes for REMUX mvk to load.  

There is no reason the system should have to pull all the audio tracks, subtitles, indexes, etc. to just give me the options screen so I can configure what I want and add to queue.  ALL processing should happen at queue execution.  This works fine for bulk loading but just not for single file load.

The main reason I cannot bulk load is because there is no good way to control my audio track default settings.  Handbrake allow me to set language preference, pass through preferences and allowable track formats.

**Comment by ChocOranger** [comment]
https://staxrip.readthedocs.io/usage.html#batch-processing

Note especially: "Indexing can be disabled by installing LAV Filters and by enabling the DSS2 source filter." 
You can find LAV filters at https://github.com/Nevcairiel/LAVFilters.

All other demuxing  (audio, subs etc) can be disabled in the options.

**Comment by ddelella** [comment]
I was able to figure it out with lots of menu settings and the LAV download.  I guess my request would be to make that the default settings.  If the user wants to pre-process they should have to customize.

**Comment by ChocOranger** [comment]
Glad you've got it sorted.

I agree with you that the default behaviour should be to not pre-process.  I can see many users being put off at having to wait when they load a file especially the first time they use StaxRip.

Although, registering the LAV filters 'breaks' the portability of StaxRip I think many users would prefer an option, maybe on first run, to select whether to pre-process or not (ie an easy 'master switch').
