### ISSUE TITLE
Old audio codec Vorbis (ACM) support

### ISSUE THREAD

**Issue by vamfish** [staxrip/staxrip#899]
**Is your feature request related to a problem? Please describe.**
I was dealing with some old videos. The audio format is vorbis (codec ID: 676F), but the vorbis codec provided by ffmpeg could not decode the audio. After searching around the internet, I found the audio codec is so called ACM codec (vorbis.acm).
Two other similar issues on the internet, these information may help: 
1. [Audio Codec Vo1+ problem](https://forum.videohelp.com/threads/400473-Audio-Codec-Vo1-problem); 
2. [Support Ogg/Vorbis in avi](https://trac.ffmpeg.org/ticket/1690)

**Describe the solution you'd like**
I would like to have a support on the old acm vorbis codec for decoding. **Possible decoder (AcmVorbis64.dll)** is found in potplayer which is able to play the video. Maybe you could help me to make this decoder working on converting rather than playing the video?

**Describe alternatives you've considered**
Maybe you could give me some suggestions to solve the problem, such as how to make ffmpeg work with external decoder.

**Explain why the feature matters to you**
1. It helps me to remaster the old videos, and save much more space on hard drivers.
2. I have tried 10+ video convert softwares, none of them could solve the issue.

**Additional context**
The log file is attached
[n0027_staxrip.log](https://github.com/staxrip/staxrip/files/8972992/n0027_staxrip.log)

**Comment by ChocOranger** [comment]
Have you tried installing the Directshow filters for Vorbis and then in Audio options  in Staxrip set the decoder to Directshow?

Directshow filters are available from https://xiph.org/downloads/

**Comment by vamfish** [comment]
> Have you tried installing the Directshow filters for Vorbis and then in Audio options in Staxrip set the decoder to Directshow?
> Directshow filters are available from https://xiph.org/downloads/

Thank you for your advice, but it didn't help. The problem is that the Staxrip need to demux the audio stream before Directshow could decode the audio stream.

The error occurred when Staxrip try to demux audio but fail on finding the codec parameters for the audio stream (what one can find out in the log file [n0027_staxrip.log](https://github.com/staxrip/staxrip/files/8972992/n0027_staxrip.log)).

And I also tried to turn off the preprocessing in the setting, the Staxrip report a similar error when Find Gain 1. The log attached here: [n0027_staxrip(2).log](https://github.com/staxrip/staxrip/files/8986350/n0027_staxrip.log)

In both cases, Staxrip tried to handle the audio with ffmpeg and failed to get the codec for audio stream. Is there any other way to demux the audio?

**Comment by ChocOranger** [comment]
Don't demux the audio.
To stop the Find Grain 1 error: In Audio options disable Normalize. That should skip the Find Grain step.

Staxrip should then use the direct show filters for the audio.

**Comment by vamfish** [comment]
> Don't demux the audio. 
> To stop the Find Grain 1 error: In Audio options disable Normalize. That should skip the Find Grain step.
> 
> Staxrip should then use the direct show filters for the audio.

I tried to uncheck the Normalize in Audio settings. And there is another error occurred (AVS to WAV).
[n0027_staxrip(3).log](https://github.com/staxrip/staxrip/files/8987392/n0027_staxrip.log)
It says that `DirectShowSource: RenderFile, the filter graph manager won't talk to me` in the log file. Does that mean the direct show filters do not work with the audio?

And I also tried to select **None** for Demux Audio under Project Options/Audio, but the same error occurred.

**Comment by ChocOranger** [comment]
> It says that `DirectShowSource: RenderFile, the filter graph manager won't talk to me` in the log file. Does that mean the direct show filters do not work with the audio?

Try to play the file in Windows Media Player as that will the direct show filters. If you get sound then the direct show filters are working but not providing avisynth what it needs. If no sound then a different version of the filters is needed or an alternative workaround.

Does the file play in VLC? If it does you could try converting there or at least do the audio and then batch convert using StaxRip since audio is way faster than video.

**Comment by ChocOranger** [comment]
Having had a quick look, if it does play in VLC you can do a batch conversion using a VLC command line. It may be sufficient for your needs if you're just converting a few old file.

**Comment by ChocOranger** [comment]
Without knowing if the direct show filters work it's hard to know what to suggest. Possibly find a direct show compatible player to check they work.

Since the audio is already quite small less than 10% of the file size you could consider reencoding the video and just copying the audio. This would mean having to play the files with Potplayer (no great loss as it's a fantastic player)

Can you upload one of the smaller files somewhere? I know they are NSFW.

**Comment by vamfish** [comment]
I just found a specific way to go around the issue. Since I can play the video normally in with potplayer, I am able to record the audio using the potplayer itself or other audio recoding software. After that, I could handle the audio with ffmpeg or any other tools.

Since the origin video could not be cut into small clips, I may upload the whole video file. The size is about 500 MB. If you do want the NSFW video for further investigation, I could send you a link (maybe mega.nz?) to your email

**Comment by ChocOranger** [comment]
Glad you've found a solution you're happy with. I wouldn't have suggested it as it's a real-time recording... I hope you haven't too many to do :)

No need to upload if you're happy with your solution.

**Comment by vamfish** [comment]
Though the solution is somehow stupid but I am happy with it.

Thank you very much for your kindly help!

**Comment by darkcity87** [comment]
@vamfish 
https://www.videohelp.com/software/FFMPEG-Audio-Encoder
try this

**Comment by ChocOranger** [comment]
> @vamfish
> https://www.videohelp.com/software/FFMPEG-Audio-Encoder
> try this

Staxrip uses ffmpeg as does the software you linked. ffmpeg doesn't decode his files.

**Comment by sheik124** [comment]
The solution is described in your first link @vamfish - you have to install the old Vorbis ACM codec manually by forcing it to install as 32-bit. I honestly would **not** recommend that.

Although **avidemux 2.8.0** was seemingly unable to play back this [test file with VP8/Vorbis](http://samples.ffmpeg.org/A-codecs/vorbis/vp8OggVorbis1.avi) in AVI (why would anyone have ever done such a thing...) it **was** able to demux the audio.

Open avidemux, load your AVI in there, go to **Audio** -> **Save Audio** and **manually append .ogg to the output filename.** You'll still have to do it manually, but it will be far far quicker than manually recording PotPlayer output, and you won't have to manually synchronize it afterwards either.
