### ISSUE TITLE
Use pipeline instead of converting audio to wav?

### ISSUE THREAD

**Issue by iAM261917** [staxrip/staxrip#9]
I've noticed that when StaxRip encoding a flac track using encoder fdkaac, it will be first converted to wav, but fdkaac does receive from pipeline, wouldn't it be better to use it? (can decrease some hard drive stress at least)

**Comment by stax76** [comment]
next release has:

- added fdkaac pipe input support, in the audio settings
  go to: More > General > Decoding Mode > Pipe
