### ISSUE TITLE
Enable Processing of HDR10Plus automatically in BatchMode

### ISSUE THREAD

**Issue by UnAnalogFG** [staxrip/staxrip#900]
Doing the extraction of the HDR10 Metadata and adding it to the Encoding Parameters manually is not 
feasible in Batch Mode. 

It would be great if the Demuxing of the h265 file, together with the extraction of the metadata.json as well as the automatic insertion into the encoding params would be automated for batch processing.

**Comment by jlw4049** [comment]
Metadata json extraction requires an alternative program. Doing this is batch mode I'm sure is possible, but would be pretty error prone and complicated.

**Comment by Dendraspis** [comment]
Meanwhile implemented....
