### ISSUE TITLE
Stuff written into the template.srip file itself instead of into .log file.

### ISSUE THREAD

**Issue by jalba69** [staxrip/staxrip#905]
Hello all, 

long time no see ;) 

Following the next steps we are able to write some content usually sent to the .log files directly into a template.srip file : 

**- Steps :** 

- Open StaxRip with a test template 
( your template will be messed up at the end so be sure to use a dummy or duplicated template ) 

- Don't load anything into Staxrip as input for video

- Go to menus to create an animated APNG 
( Not sure where it is on an unmodified StaxRip installation, i have heavy modified menu's on mine )

- A window opens up to choose an input, select a video input, set some parameters and create the Apng

- Now "Save Project as Template" as we usually do to save one 

 **- Result :**

The log infos that should have gone into a .log file are now stored inside your template.srip file and the next times you will use this template all log infos from this Apng creation will be printed to all new log files printed by your new projects .
Some content of the Template.srip file opened in notepadd++ :
```
m_StringValuem_currentThread   ÿÿÿú     „
---------------------------- Encoding PNG ----------------------------

ffmpeg N-106445-g723065a346-x64-gcc11.2.0

C:\Users\USer\Desktop\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe  -ss 15.0 -t 3.8 -i "H:\Knight.mkv" -lavfi "fps=29,scale=320:-1:flags=spline" -plays 0 -loglevel quiet -an -y "H:\Knight.apng"

Start:    18:26:56
End:      18:27:00
Duration: 00:00:03

--------------------------- Optimizing PNG ---------------------------

PNGopt 1.4

C:\Users\USer\Desktop\StaxRip\Apps\Thumbnails\PNGopt\apngopt.exe -z0 "H:\Knight.apng" "H:\\KnightKnight.png"

Start:    18:27:00
End:      18:27:09
Duration: 00:00:09

    °   1      ÿÿÿÿ          ?StaxRip, Version=2.13.0.0, Culture=neutral, PublicKeyToken=null 
```

- The next time you use a template for a normal input video, all logs content will start with : 

```
---------------------------- Encoding PNG ----------------------------

ffmpeg N-106445-g723065a346-x64-gcc11.2.0

C:\Users\USer\Desktop\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe  -ss 15.0 -t 3.8 -i "H:\Knight.mkv" -lavfi "fps=29,scale=320:-1:flags=spline" -plays 0 -loglevel quiet -an -y "H:\Knight.apng"

Start:    18:26:56
End:      18:27:00
Duration: 00:00:03

--------------------------- Optimizing PNG ---------------------------

PNGopt 1.4

C:\Users\USer\Desktop\StaxRip\Apps\Thumbnails\PNGopt\apngopt.exe -z0 "H:\Knight.apng" "H:\\KnightKnight.png"

Start:    18:27:00
End:      18:27:09
Duration: 00:00:09

------------------------- System Environment -------------------------

StaxRip    : v2.13.0	
etc etc ....
```

**- Expected Result :**

 if there is no log file already created as we did not load up a video before making an Apng then nothing is written at all, or create a log file in the temp directory just for this but not write anything to the templates, this shouldn't be possible.

It appears that many of my templates are messed up because i tried once to do an apng and then modified settings before saving as template and did not noticed this problem and since i mostly duplicated a messed up template that i modified following my needs so 90% of my template have now this issue.

Tried to manually edit them but it seems fails when loaded into StaxRip and they are reset by the program, didn't had time to try to open them in VS22 or else yet, so if you have any solution to manually edit a template it will be really helpful ^^

Thanks guys :)

**PS : it also happens when instead of creating an Apng we do the same for a Gif creation using menu " Animated Gif  "**

**Comment by Dendraspis** [comment]
Sorry for the late response.  😖 

Thanks for the detailed report, helped a lot. It will be fixed with the next release ... finally.

**Comment by jalba69** [comment]
Better late than never :)

Thank you very much.
