### ISSUE TITLE
"dfttest.dll"platform retuned code-1073741795,unknown error

### ISSUE THREAD

**Issue by hintlou** [staxrip/staxrip#91]
![360截图20191129101601302](https://user-images.githubusercontent.com/53346325/69839570-f9946a80-1292-11ea-968f-76ab81c1bdca.jpg)
![360截图20191129101406653](https://user-images.githubusercontent.com/53346325/69839587-1466df00-1293-11ea-81e5-f21f720ad1f0.jpg)
how can i fix it,please help,thanks!

**Comment by hydropunk69** [comment]
Same error using w10
