### ISSUE TITLE
Add AVISynth-DPID (Detail-Preserving Image Downscaler)

### ISSUE THREAD

**Issue by GlitterKill** [staxrip/staxrip#911]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement for use

**Describe alternatives you've considered**

**Explain why the feature matters to you**
Downscaled video and images with more details

**Additional context**
Project is here:
[https://github.com/Asd-g/AviSynth-DPID/](https://github.com/Asd-g/AviSynth-DPID/)

**Comment by Dendraspis** [comment]
Will be available in the next release....
