### ISSUE TITLE
QAAC normalize setting doesn't work.

### ISSUE THREAD

**Issue by SuperTech22** [staxrip/staxrip#914]
The normalize option in the audio setting does not work for qaac. I noticed that the "--normalize" argument is not passed when the encoding takes place. 

![img1](https://user-images.githubusercontent.com/109566742/181095732-a4dbc125-e06c-4a0e-a03e-5fae319341b9.jpg)

![img2](https://user-images.githubusercontent.com/109566742/181095747-cdc79e5c-25f4-42ca-8a75-22e20a408ea1.jpg)

But it will work if I manually provide the arguement in the custom field under the audio settings for qaac.

![img3](https://user-images.githubusercontent.com/109566742/181095752-b79f04d6-6dc0-4ed2-af78-491fb8e27f75.jpg)

![img4](https://user-images.githubusercontent.com/109566742/181095757-b19af4ed-c7cc-4e2f-a5f7-7691b05ef7d0.jpg)

**Comment by Dendraspis** [comment]
I have to close this one because of not enough information, especially a missing log file.
Normalization is outsourced to ffmpeg in some cases, so it is pretty likely applied in a previous step.
