### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by satstarter** [staxrip/staxrip#915]
if i want to convert a serie with 20 or more episodes select project template add source files batch
many times i get file not found error sometimes a couple of files are found is this someting in settings ore is it a bug??

**Comment by Rick-N-Thailand** [comment]
I also have this problem.  For some reason in File Batch mode, it fails to create the Temp Directory / Script files if the Source FILE NAME is too long including source path.   Staxrip software at the install requests disabling file path length but noticed on my Windows 11 system, it was not disabled. 

OS: Windows 11
Staxrip v2.13.0

_For me I fixed it by modifying the following registry key:_

**HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem**

Enable "**longpathenabled**" DWORD from 0 to **1** 

Reference:  [https://www.thewindowsclub.com/how-to-enable-or-disable-win32-long-paths-in-windows-11-10#:~:text=In%20the%20Registry%20Editor%20windows,address%20bar%20and%20press%20Enter.&text=In%20the%20FileSystem%20folder%2C%20find,OK%20to%20save%20the%20changes.](url)
