### ISSUE TITLE
x265 "console help" doesn't function because "x265 Help.txt" is not being generated properly

### ISSUE THREAD

**Issue by sheik124** [staxrip/staxrip#916]
**Describe the bug**
See title. Right clicking encoder settings gives an option to open "Online Help" or "Console Help".
![image](https://user-images.githubusercontent.com/2312934/182036453-58424f3e-ffe2-4521-807e-fd5d2845d4c5.png)

StaxRip returns the following error for ALL settings, because the .txt file it generates and then checks is a blank, 4 byte, file with only a few line breaks in it.
![image](https://user-images.githubusercontent.com/2312934/182036478-668571c9-c6be-49b3-9ef5-81fdf0947a0c.png)

**Expected behavior**
It should open a console window with the relevant setting highlighted, as it used to in the past. The following screenshot is from "StaxRip 2.0.0.0 Stable Release"

![image](https://user-images.githubusercontent.com/2312934/182036515-0bb8a732-66a2-45e6-87dc-3503fb1e9415.png)

~~**It's easily fixed?**~~ I figured it out entirely and am opening a PR.

I saved the output from `x265.exe --fullhelp` to `x265 Help.txt` and that fixes "Console Help" immediately.
```
\StaxRip-v2.13.0-x64\Apps\Encoders\x265>x265.exe --fullhelp > "x265 Help.txt"
x265 [INFO]: HEVC encoder version 3.5+37+12-4e46995bc [Mod by Patman]
x265 [INFO]: build info [Windows][MSVC 1931][64 bit] 8bit+10bit+12bit

\StaxRip-v2.13.0-x64\Apps\Encoders\x265>dir
 Volume in drive 
 Volume Serial Number is 

 Directory of \StaxRip-v2.13.0-x64\Apps\Encoders\x265

07/31/2022  12:58 PM    <DIR>          .
07/31/2022  12:58 PM    <DIR>          ..
07/31/2022  12:58 PM            32,757 x265 Help.txt
04/01/2022  06:08 PM         1,383,936 x265.exe
               2 File(s)      1,416,693 bytes
               2 Dir(s)  
```
![image](https://user-images.githubusercontent.com/2312934/182037262-0b79176b-9216-4516-895c-9d03df337c22.png)
Tada.

Which tells me that something is wrong in the way StaxRip is trying to generate `x265 Help.txt`!

I checked [Source/General/Package.vb](https://github.com/staxrip/staxrip/compare/master...sheik124:staxrip:patch-1#diff-4fd91ea2e98ffdbeaeefbf0791ba910e2c84e1bda38d81fd1cb4ef1719712420) and found the issue. It does actually appear to be specific to Patman's build, my own x265.exe built from x265-git using MABS allows `full`, Patman's build only allows `FULL`. Either way, specifying the `--log-level` for `--fullhelp` is doubly redundant - the console will print the `--fullhelp` regardless of what you set, **and** `full` is the default `--log-level`...

```
\StaxRip-v2.13.0-x64\Apps\Encoders\x265>x265 --log-level full --fullhelp
x265 [FLAW]: invalid argument: log-level = full

\StaxRip-v2.13.0-x64\Apps\Encoders\x265>x265 --log-level FULL --fullhelp
x265 [INFO]: HEVC encoder version 3.5+37+12-4e46995bc [Mod by Patman]
x265 [INFO]: build info [Windows][MSVC 1931][64 bit] 8bit+10bit+12bit

Syntax: x265 [options] infile [-o] outfile
    infile can be AVS, VPY, YUV or Y4M
    outfile is raw HEVC bitstream

Executable Options:
-h/--help                        Show this help text and exit
   --fullhelp                    Show all options and exit
-V/--version                     Show version info and exit

Output Options:
-o/--output <filename>           Output file name can be *.gop or *.hevc
-D/--output-depth 8|10|12        Output bit depth (also internal bit depth). Default 8
   --log-level <string>          Logging level: none error warning info debug full. Default FULL
/SNIP/
```
Compare with vanilla x265, `--log-level` isn't case sensitive:
```
Q:\media-autobuild_suite-master\local64\bin-video>x265 --log-level full --fullhelp
x265 [info]: HEVC encoder version 3.5+37-b4f48a3ff
x265 [info]: build info [Windows][GCC 12.1.0][64 bit] 8bit

Syntax: x265 [options] infile [-o] outfile
    infile can be YUV or Y4M
    outfile is raw HEVC bitstream

Executable Options:
-h/--help                        Show this help text and exit
   --fullhelp                    Show all options and exit
-V/--version                     Show version info and exit

Output Options:
-o/--output <filename>           Bitstream output file name
-D/--output-depth 8|10|12        Output bit depth (also internal bit depth). Default 8
   --log-level <string>          Logging level: none error warning info debug full. Default full
/SNIP/
```
And `--fullhelp` will still print even if you set `--log-level` to `none`
```
Q:\media-autobuild_suite-master\local64\bin-video>x265 --log-level none --fullhelp
x265 [info]: HEVC encoder version 3.5+37-b4f48a3ff
x265 [info]: build info [Windows][GCC 12.1.0][64 bit] 8bit

Syntax: x265 [options] infile [-o] outfile
    infile can be YUV or Y4M
    outfile is raw HEVC bitstream

Executable Options:
-h/--help                        Show this help text and exit
   --fullhelp                    Show all options and exit
-V/--version                     Show version info and exit

Output Options:
-o/--output <filename>           Bitstream output file name
-D/--output-depth 8|10|12        Output bit depth (also internal bit depth). Default 8
   --log-level <string>          Logging level: none error warning info debug full. Default full
/SNIP/
```

**How to reproduce the issue**
See above.

1. Right click any setting for x265 in StaxRip >=2.7.0, potentially even older versions.
2. Select console help.

**Provide information**
Used StaxRip version
- Issue appears in 2.7.0, 2.8.0, and 2.13.0, didn't check others, presumably exists in all versions that came with Patman x265.
- Issue did not exist in 2.0.0.0

**Notes before posting**
- Please also try the latest release of StaxRip. **I did**
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there.  **It's technically a Patman x265 issue, but it can be fixed on StaxRip's end by changing the way it tries to access `--fullhelp`**
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is especially true on the VapourSynth side, which will crash if your CPU don't support it. **Doesn't apply**
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet. **Doesn't apply**

**Additional context**
Fixing it myself!

**Please be as clear and as detailed as possible**
I hope I have been!

**Comment by sheik124** [comment]
I thought this commit https://github.com/Patman86/x265-Mod-by-Patman/commit/d82def7ab1e8ecd55a111cadb925af042c99b9f1 might have been the cause but 2.7.0 shipped with a version of x265 that predated it by nearly an entire year and it still behaves the same way.

**Comment by Dendraspis** [comment]
Thanks for the report and the effort you put in this issue. 👍  Sadly it took a while, sorry about that!
But now it's fixed and will be published with the next release...
