### ISSUE TITLE
x265 --log-level options are mapped incorrectly.

### ISSUE THREAD

**Issue by sheik124** [staxrip/staxrip#918]
**Describe the bug**
x265 `--log-level` settings do not match Patman's x265 .exe.

![image](https://user-images.githubusercontent.com/2312934/182038886-48d7a1fd-b138-41fb-9015-572798505928.png)

**Expected behavior**
The command line generated by StaxRip matches vanilla x265.exe, and presumably the other forks. Patman does not use the same parameters. https://github.com/Patman86/x265-Mod-by-Patman/commit/d82def7ab1e8ecd55a111cadb925af042c99b9f1

**How to reproduce the issue**

Set any log-level in x265 other than the default highlighted "Info", which technically isn't correct anyways since the default is ~~full~~ `FULL`

If the issue happens only under special conditions then please describe how this conditions can be reproduced:

1. Encode with x265
2. Change `log-level` to anything
3. x265 crashes immediately, no encoding happens

**Provide information**

See above.

**Notes before posting**
- Please also try the latest release of StaxRip. **yup...**
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there.  **it's a bit of both**
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is especially true on the VapourSynth side, which will crash if your CPU don't support it. **doesn't apply**
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet. **using x265 included with StaxRip**

**Additional context**
Add any other information or additional context that can be helpful.

[x265-git has `--log-level` defined](https://bitbucket.org/multicoreware/x265_git/src/master/source/common/param.h) the same way StaxRip maps its command line options:
```C++
/* this table is kept internal to avoid confusion, since log level indices start at -1 */
static const char * const logLevelNames[] = { "none", "error", "warning", "info", "debug", "full", 0 };
```
[Patman](https://github.com/Patman86/x265-Mod-by-Patman/blob/master/source/common/param.h) is using:
```C++
/* this table is kept internal to avoid confusion, since log level indices start at -1 */
static const char * const logLevelNames[] = { "NONE", "FLAW", "WARN", "INFO", "DEBU", "FULL", 0 };
```

The console output from Patman's x265.exe doesn't reflect this change either, either for `--fullhelp`/`--help` or when trying to pass one of the `--log-level` parameters from vanilla through.

**Please be as clear and as detailed as possible**
I hope I have been.

**Comment by Ding-adong** [comment]
What was the point of changing loglevelnames?

What is "DEBU"?

Is it really necessary to leave out the "G"?

**Comment by sheik124** [comment]
I don't know, you would have to ask Patman. I really don't understand why it was done either.

**Comment by sheik124** [comment]
I already asked if there was any particular reason it was done BTW
https://github.com/Patman86/x265-Mod-by-Patman/commit/d82def7ab1e8ecd55a111cadb925af042c99b9f1#commitcomment-79879477
No answer

**Comment by Dendraspis** [comment]
I think it was just a mistake changing the parameter names.
As far as I remember the goal was to achieve 4 char long console output classes.

I'll leave it as it is, because it could be fixed by @Patman86 for a new release.
If it is important to you, try the latest [release by DJATOM](https://github.com/DJATOM/x265-aMod/releases).

**Comment by Dendraspis** [comment]
The next build from Patman86 does have the original log-levels, so I can close this again.  😁 
https://github.com/Patman86/x265-Mod-by-Patman/releases/tag/3.5%2B104%2B11
