### ISSUE TITLE
QSVEnc 7.07 AV1 support?

### ISSUE THREAD

**Issue by mikk9** [staxrip/staxrip#919]
I would like to ask about QSVEnc 7.07 and AV1 support in the Staxrip GUI for upcoming Arc dGPUs. Furthermore there are some more options which could be added like device option when more than one GPU is enabled. I copy and paste the important ones. I hope this can be added in the next version of Staxrip. Thanks.

d,--device <string> or <int>   set device number to encode
                                 - auto(default), 1, 2, 3, 4

-c,--codec <string>         - av1

--level <string>              -AV1:   auto(default), 2, 2.1, 2.2, 2.3, 3
                                         3.1, 3.2, 3.3, 4, 4.1, 4.2, 4.3, 5
                                         5.1, 5.2, 5.3, 6, 6.1, 6.2, 6.3, 7
                                         7.1, 7.2, 7.3

--profile <string>          - AV1:   auto(default), main, high, pro

--hyper-mode <string>        set Deep Link Hyper Mode
                                - off, on, adaptive (=default)

--tskip --no-tskip (tskip off improves bitrate efficiency in many cases on Xe GPUs, there is no tskip off option in Staxrip)

**Comment by Dendraspis** [comment]
Sorry for the massive delay.
Parameters will be added in the next release.

> --tskip --no-tskip (tskip off improves bitrate efficiency in many cases on Xe GPUs, there is no tskip off option in Staxrip)

`--tskip` is only available for HEVC codec and there is no `--no-tskip` mentioned in the docs.


Documentation:
https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md

**Comment by mikk9** [comment]
--no-tskip works, same for SAO. These features can be disabled.

**Comment by Dendraspis** [comment]
Yes, but according to the documentation they should only work with HEVC. Internally they are even called `hevc_tskip` and `hevc_sao`. 😅  Haven't checked it in detail, but they really should  only work with HEVC.

**Comment by mikk9** [comment]
Yes it only works for HEVC. It sometimes can be beneficial to disable it, there is only little difference though.

**Comment by Dendraspis** [comment]
Both params are set to work in HEVC mode only, so everything is fine (in the next release).  👍
