### ISSUE TITLE
Deinterlacing with NVenc not working

### ISSUE THREAD

**Issue by epiccofficial** [staxrip/staxrip#92]
Trying to re-encode a VOB file and deinterlace it using NVenc. It works if I do it with AviSynth/VapourSynth decoder but when set to NVenc native, it doesn't deinterlace. Also, the cuda option doesn't work, saying
`Error Video encoding using NVEnc 4.46 (2.0.4.0)

Video encoding using NVEnc 4.46 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 4.46 -------------------

"D:\Program Files\StaxRip\Apps\Encoders\NVEnc\NVEncC64.exe" --avhw cuda --cbr 5034 --preset quality --output-depth 10 --sar 10:11 --colorprim bt470m -i "[DIRECTORY]\VTS_03_1.VOB" -o "[DIRECTORY]\file_out.h264"

Error: Unknown option: "cuda"

StaxRip.ErrorAbortException: Video encoding using NVEnc 4.46 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 4.46 -------------------

"D:\Program Files\StaxRip\Apps\Encoders\NVEnc\NVEncC64.exe" --avhw cuda --cbr 5034 --preset quality --output-depth 10 --sar 10:11 --colorprim bt470m -i "[DIRECTORY]\VTS_03_1.VOB" -o "[DIRECTORY]\file_out.h264"
Error: Unknown option: "cuda"

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 339
   at StaxRip.NVEnc.Encode() in D:\Projekte\VB\staxrip\Encoding\NVEnc.vb:line 82
   at StaxRip.GlobalClass.ProcessVideo() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 228
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 138`
I've got a cuda dll in the NVenc folder so I don't think that's the problem.
Thanks,
EpicC.

**Comment by GraemeHW** [comment]
Just tried encoding a 1080i remux - Staxrip flagged it as interlaced - no errors on encoding - but video of encode ran at 1/2 speed - so double frames done  - Video length the same - so audio matched the length - but only 1/2 the video encoded. - also encoding NVENC H265 with a turing GPU  Thanks Graeme -

**Comment by GraemeHW** [comment]
I converted  it too progressive & obviously it then encoded fine

**Comment by epiccofficial** [comment]
Now, when I try and encode with NVenc it says my graphics cart (1050 TI) doesn't support h264 or h265. This is after updating. Can someone help?
Thanks,
EpicC.

**Comment by epiccofficial** [comment]
Nevermind, something went wrong with my drivers. I just had to reinstall NVidia Control panel.
