### ISSUE TITLE
Error VCEEnc resize Lanczos

### ISSUE THREAD

**Issue by Begemotoid** [staxrip/staxrip#921]
<a href="https://radikal.host/i/cgi6K"><img src="https://a.radikal.host/2022/08/02/ErrorLanzf65def875b02ab39.md.jpg" alt="ErrorLanzf65def875b02ab39.md.jpg" border="0"></a>

If you select VCEEnc resize Lanczos and Hardware Encoder in the filters, there will be an error. The line shows that it says "lanczos". But there is no such value in the VCEEnc specification. Correct values "lanczos2" "lanczos3" "lanczos4".

https://github.com/rigaya/VCEEnc/blob/master/VCEEncC_Options.en.md#--vpp-resize-string

If you write the correct values manually into the string in coder options Others-Custom, then there is no error.

**Comment by Dendraspis** [comment]
Thanks for reporting. Meanwhile in v2.14 the parameters are up to date to work with the latest VCEEnc version.

**Comment by Begemotoid** [comment]
The error was repeated on the new version.

> Error Video encoding (v2.14.0)
> 
> Video encoding returned exit code: 1 (0x1)
> 
> 
> --------------------------- Video encoding ---------------------------
> 
> VCEEnc 8.10
> 
> ...\StaxRip-v2.14.0-x64\Apps\Encoders\VCEEnc\VCEEncC64.exe --avsdll ...\StaxRip-v2.14.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --codec hevc --vpp-resize lanczos --cqp 22:24:27 --output-res 720x1280 -i ...
> 
> Error: Invalid value "lanczos" for "--vpp-resize"
>   Option value should be one of below...
>     auto, bilinear, spline16, spline36, spline64, lanczos2, lanczos3, lanczos4, 
>     amf_bilinear, amf_bicubic, amf_fsr, amf_point

**Comment by Dendraspis** [comment]
You were absolutely right, I missed the changed parameters.
They will be fixed in the next release, meanwhile you can use this if you want: [StaxRip v2.14.4.zip](https://github.com/staxrip/staxrip/files/10988461/StaxRip.v2.14.4.zip)
