### ISSUE TITLE
Do not parse Path (Folder names) for language name

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#924]
When you add a subtitle like this

movie.French.srt

It is correctly added as French. But if in the path there is English for example like this

C:\Movies\English\Movie1\movie.French.srt

The subtitle is added as English and not French.

So the program should only parse file names for language names and not full path.

**Comment by Dendraspis** [comment]
Thanks for the report, I was able to reproduce it and it will be fixed in the next release.
