### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Maxiz80** [staxrip/staxrip#925]
First of all, no comment in source code is very bad :)
Second I'm almost sure that the source code doesn't correspond to the exe file published.
The first setup of  "settings.dat" doesen't serialize correctly.

StaxRip.exe from 7z archive 2.549.248
Settings.dat from first run 182.801

StaxRip.exe from VS2022     2.548.224
Settings.dat from first run   128.512

Did I missing something?

**Comment by Dendraspis** [comment]
I think so, but I don't know what....
