### ISSUE TITLE
DgMpgDec is using the wrong DGDecode.dll

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#928]
DgMpgDc should be using the 64 bit version of the .dll

This causes the program to crash when accessing this

**Comment by HASJ** [comment]
Started getting this error too.

```
Script Error

Cannot load a 32 bit DLL in 64 bit Avisynth: 'C:/tools/StaxRip/StaxRip-v2.13.0-x64/Apps/Support/DgMpgDec/DGDecode.dll'.

(D:\Videos\Movies\LOTR2\VIDEO_TS\VTS_01_0_temp\VTS_01_0_source.avs, line 2)
```

**Comment by jlw4049** [comment]
Just go to DGDecodes website. Replace the dll on staxrip with the x64 bit fll from DGDecode. It'll then work fine.

**Comment by Dendraspis** [comment]
Issue should have been fixed with the latest release...
