### ISSUE TITLE
SMDegrain error

### ISSUE THREAD

**Issue by bob2456436** [staxrip/staxrip#931]
Hi, Im using the latest version of Staxrip. I get this error when I try to use SMDegrain:

Script Error

Script error: There is no function named 'ex_bs'.
(D:\-=Apz=-\StaxRip-v2.13.0-x64\Apps\Plugins\AVS\SMDegrain\SMDegrain.avsi, line 248)
(D:\0000_temp\0000.avs, line 18)

**Comment by madey83** [comment]
hi,

go here: https://github.com/Dogway/Avisynth-Scripts. Download it and import dependent scripts
