### ISSUE TITLE
MediaInfo flags do not match video stream

### ISSUE THREAD

**Issue by pianistrevor** [staxrip/staxrip#932]
**Describe the bug**
When encoding a 24p CFR video to MKV, the flag will be set to VFR and the details flag for the frame rate is set at 23.810 FPS. This also happens with other frame rates such as 24000/1001p.

**Expected behavior**
When encoding a 24p CFR video to MKV, the flag should still be set at CFR and the details flag for the frame rate should be 24 FPS. This should also be the case for other frame rates.

**How to reproduce the issue**

Encode any video. Open the video in MPC-HC (since this is where I can distinguish between the Details flags and the MediaInfo flags). This discrepancy should be fairly obvious.

**Provide information**
- Settings file (renamed with .txt to allow uploading): 
[Settings.dat.txt](https://github.com/staxrip/staxrip/files/9538340/Settings.dat.txt)
- Template (also renamed with .txt): 
[Template.srip.txt](https://github.com/staxrip/staxrip/files/9538348/Template.srip.txt)
- Used StaxRip version 2.13.0

**Additional context**
Muxing again with my installation of MKVToolNix 70 and selecting "Fix bitstream timing info" fixes these problems. It appears to be a problem with StaxRip's flags that are passed to mkvmerge or mkvinfo.

**Comment by pianistrevor** [comment]
Update: The issue is resolved when I turn off extracting timestamps. Here is an example timestamps file:
[Star Trek VI꞉ The Undiscovered Country (1991)_timestamps.txt](https://github.com/staxrip/staxrip/files/9562420/Star.Trek.VI.The.Undiscovered.Country.1991._timestamps.txt)
As you can see, the last timestamp is not at a granularity of 1 ms, so the muxer was writing a VFR flag to the MKV.

Is this an issue that needs to be fixed in the timestamp extraction, or is this intended behavior?

**Comment by Dendraspis** [comment]
Thanks for reporting and also telling the solution.
The never ending story with Timestamps, sadly there seems to be no *way to go* for it...

**Comment by pianistrevor** [comment]
[S02E06. Boober's Dream_new_timestamps.txt](https://github.com/staxrip/staxrip/files/10985276/S02E06.Boober.s.Dream_new_timestamps.txt)

A problem still exists. I've gotten 2.14.0 and changed no template settings. 60000/1001 fps but the last timestamp is offset 33 ms instead of the expected 17.

**Comment by Dendraspis** [comment]
The timestamps are not written by StaxRip itself, they are extracted with `mkvextract` so the solution seems to be create an issue for `mkvextract`.  🤔
