### ISSUE TITLE
How to use filter to change the contrast, brightness, saturation and gamma at once?.

### ISSUE THREAD

**Issue by ElektroStudios** [staxrip/staxrip#934]
- I would like to encode a DVD5 using x265 single-pass with SLOW profile (I prefer to use x265 than x264 even for SD videos like this) with the default encoder parameters untouched. 
- And I need to crop the image to remove top and bottom black borders. 
- The DVD is not interlaced so I'm not going to use a field/deinterlace filter
   (unless necessary to improve the image quality results of this request).

Please take these things above into account in case of my encoding methodology could affect in a bad way the image quality results of this request:

----------------------------------

I would like to know which filter I should use, and which exact syntax the command would have to correct the image color using these settings:

Contrast: +12
Saturation: -8
Brightness: -1
Gamma: +3
HUE: 0

I think that I should use the ColorYUV->Tweak filter but I'm not sure about how to write the exact syntax for the configuration that I specified and also having the right behavior to prevent from change/correct any other aspect of the image.

Thanks in advance.

**Comment by darkcity87** [comment]
@ElektroStudios You should ask this kind questions on discord.

**Comment by ElektroStudios** [comment]
@darkcity87 Thanks for comment, but I don't have and I'm not willing to install Discord.

Please do not take it personally, your comment did not bother me and I hope mine does not bother you, I simply explain my reasons as seriously as possible:

I'm just not willing to feel forced to install an app I don't want to have, when GitHub and the developer of this app already provide the feature to ask specific questions about StaxRip:

![https://i.imgur.com/qDCWdCb.png](https://i.imgur.com/qDCWdCb.png)

I really hope and wish that I can get help here on GitHub, and not be forced to interact in a third-party software chat room.

Cheers.

**Comment by darkcity87** [comment]
@ElektroStudios I just wanted to help you. Developers didnt answer any questions recently. Its not bug report or feature request just usage question there are active staxrip users on discord they can help you. Its up to you join or not also you dont need to install discord app you can login from browser.

check this page about Tweak parameters
http://avisynth.nl/index.php/Tweak

add Tweak filter > right click > Edit code > change parameters to your preference

Tweak(hue=0, sat=-1, bright=-8, cont=12)

**Comment by ElektroStudios** [comment]
[darkcity87](https://github.com/darkcity87) Yes, I understood that you wanted to help me by pointing me to a chat room where I could (or could not) get help. That is why I was worried that you would take my comment badly. I appreciate your help.

Thanks for the Tweak syntax example, that is what I needed to know from the start!!

Cheers.
