### ISSUE TITLE
it will be a very good tool if we can preview the encoded frame and compare it with the original one at same time

### ISSUE THREAD

**Issue by ruixingchen** [staxrip/staxrip#935]
in a common situation, when encoding a video, we will want to compare frames with the original one to get a clear brief of the final encoded, currently we have a preview and a video compare tool, but can only do it  separately, so I think it will be a very good tool if we can preview the encoded frame and compare it with the original one at same time
Thanks

**Comment by Dendraspis** [comment]
Since `StaxRip v2.25.0` this is possible using the Video Comparison, that now can load also scripts, so you can load the source file (or source temp script) and also the current script, that includes all set filters.

Pretty sure this solves this issue, so I close it finally.  😁
