### ISSUE TITLE
Demux is not working

### ISSUE THREAD

**Issue by Ding-adong** [staxrip/staxrip#939]
**Describe the bug**
Demux of subtitles and sometimes audio does not work through options menu and tools - advance - demux.

**Expected behavior**
All files in version 2.8 were demuxed.

Update to 2.13 and files are not demux.

Log shows error as 

-------------------------------- Error --------------------------------

no output found

**How to reproduce the issue**

Open Mkv file and try demux.

Tests
1
- Delete files in C:\Users\NOYB\Desktop\Small Files\StaxRip-v2.13.0-x64\Apps\Support\MKVToolNix 
- Copy files from C:\Users\NOYB\Desktop\Small Files\StaxRip-v2.8.0-x64\Apps\Support\MKVToolNix **to** C:\Users\NOYB\Desktop\Small Files\StaxRip-v2.13.0-x64\Apps\Support\MKVToolNix
- Start staxrip 2.13
- Demux using options menu, subtitles, eng, und only. All files and all subtitles files was extracted - **fail**.
- Demux using tools - advance - demux and click on eng only and all files and english subtitle file was extracted - **pass**.

For some reasons using options menu the log reported that all subtitles files are treated as chapters.

2
- Demux using options menu, subtitles, eng, und only. Uncheck demux chapters. All files and all subtitles files was extracted - **fail**.
- Demux using tools - advance - demux and click on eng only. Uncheck demux chapters. All files and english subtitle file was extracted - **pass**.

Above tests using "demux preferred language don't include them."

Changed to using "Show dialogue to show subtitles to be included."
- Demux using options menu, subtitles, eng, und only. All files and english subtitle file was extracted - **pass**.

I had to go back to v2.8 as last working release.

3
- Start staxrip 2.8
- Use "demux preferred language don't include them."
- Demux using options menu, subtitles, eng, und only. All files and english subtitle file was extracted - **pass**.
- Demux using tools - advance - demux and click on eng only and all files and english subtitle file was extracted - **pass**.

2.8 works flawlessly. MKV works in 2.8 but not 2.13.

**Comment by dustsigns** [comment]
I can confirm this issue. It happens only with few MKV files to me, but what they have in common is that they have at least one PCM audio track, chapters and multiple subtitles. Only the PCM audio track can be demuxed, the rest (subtitles and AC-3 audio tracks) are not demuxed at all or to 0-byte files.

**Comment by Dendraspis** [comment]
I know, it's been a while, but does that mean, that v2.13 works for you, when you copy the MKVToolNix folder over from v2.08 ?

**Comment by Ding-adong** [comment]
No, see test 1 in first post, it failed when i did that. Will test latest 2.14 tomorrow.

**Comment by Dendraspis** [comment]
Problem solved?
