### ISSUE TITLE
QSVEnc Hardware AV1 FPS Bug

### ISSUE THREAD

**Issue by NyaakoYT** [staxrip/staxrip#942]
**Describe the bug**

The output video always finishes at 25fps when encoding with Staxrip QSVEnc Intel AV1 hardware encoder.

**Expected behavior**

Seems like a bug in the default duration/FPS upon video muxing because it's fixed by setting the FPS in MKVToolNix to 60 for the video file itself.

**How to reproduce the issue**

First I used Rigaya's QSVEnc fork and replaced QSVEnc in Staxrip default: https://github.com/rigaya/QSVEnc/releases
Then I put in a random video, like an Overwatch Highlight video (plays at 60fps).
Encoder Profile > Intel > AV1 (Experimental)
QSVEnc Options
Basic > Codec: Intel AV1 (Experimental)
Input/Output > Decoder: QSVEnc Hardware

**Provide information**

- Used StaxRip v.2.13.0

**Comment by Discograp** [comment]
use NVENC(265)main from nvidia

25fps is an old QSVENC bug

**Comment by NyaakoYT** [comment]
> 

Interesting, I also found out another interesting thing is that when fooling StaxRip by switching from FFMPEG - MP4/MKV container to MP4 (mp4box) or MKV (mkvmerge), the 25FPS issue with QSVEnc is gone and the FPS is correct.

**Comment by Discograp** [comment]
ok

**Comment by NyaakoYT** [comment]
I don't know why, but normally it wouldn't allow me to use mp4box/mkvmerge because there's a warning that says that "av1" is not supported and then it wouldn't allow me to start the job. So I guess that's another bug for StaxRip, but one that I would be fine to keep in since it allowed me to get through it well.

**Comment by Discograp** [comment]
take into account
StaxRip is the launcher
all these codec and filters - all code manipulations - directly depend on optimization.
these "drivers" are already out of date.
CPU and VGA have become better

**Comment by NyaakoYT** [comment]
I actually found a way to do it. I used the video encoder Command Line option.

%app:QSVEnc% --avhw --codec av1 --quality best --ref 8 --bframes 3 --icq 18 -i "%source_file%" -o "%encoder_out_file%" --output-res %target_width%:%target_height%

Output File Type: "mkv" or "mp4"

Turned out very well and didn't need to remux the timecode in through MKVToolnix.

**Comment by NyaakoYT** [comment]
I wouldn't say it's been fixed. Just tried it out when StaxRip 2.14.0 came out with the latest QSVEnc and the 25fps bug still persists without using "--output-format mp4".

**Comment by pat-e** [comment]
Damn, I just found this thread here AFTER opening my own issue:

https://github.com/staxrip/staxrip/issues/982

I just hope it gets fixed as it makes it quite complex to "not" merge the output-files and later manually merge them all together in MKVToolNix.

**Comment by NyaakoYT** [comment]
> Damn, I just found this thread here AFTER opening my own issue:
> 
> #982
> 
> I just hope it gets fixed as it makes it quite complex to "not" merge the output-files and later manually merge them all together in MKVToolNix.

I feel ya. If Staxrip can update to let av1 work with mkvmerge, then it's all good!

**Comment by Dendraspis** [comment]
As you can see in #982 **.av1** files are now valid input sources, so this should work without additional parameter anymore.
