### ISSUE TITLE
add NVEncC AV1 support

### ISSUE THREAD

**Issue by hsinyu-chen** [staxrip/staxrip#949]
**Describe the solution you'd like**
cloud you add NVEncC AV1 support? the NVEncC now support AV1

**Comment by Discograp** [comment]
oh, great news! please give me links

**Comment by hsinyu-chen** [comment]
@Discograp  https://github.com/rigaya/NVEnc

**Comment by Dendraspis** [comment]
```
Add experimental support for AV1 hw encoding in RTX40xx series.
Please note that this is experimental and currently not tested at all, as I haven't been able to get RTX40xx series yet.
```
As long as it is just (highly) experimental for a very small range of graphic cards, I hesitate to add it. Let's wait for a proper implementation...

**Comment by Ibbanez** [comment]
Just wanted to chime in, I can help test with a RTX 4090 if you need any help. I would love to add Nvenc AV1 support if possible.

**Comment by Dendraspis** [comment]
NVEncC AV1 support will be added. Soon...  😏 

@Ibbanez 
Thanks for the willingness to help, really appreciated! When there will be issues with the AV1 support I may contact you again.  😁
