### ISSUE TITLE
Preview bug in 2.0.6.1 beta

### ISSUE THREAD

**Issue by ukharley** [staxrip/staxrip#95]
Just tried the new 2.0.6.1 beta. Preview is a lot smoother but it's upside down on my system!

**Comment by stax76** [comment]
It might be necessary to create and use a build with special logging code to find the reason.

Which Windows version?
Which source filter?
Which type of source file?

**Comment by ukharley** [comment]
Windows 10 Pro x64 1909.
Tried all source filters except LibavSMASH as it needs Haali splitter. Files used are MP4 or MPV of any size or bit rate with x264 and/or Intel x264 encoder.
Vapoursynth system, i don't have Avisynth+ installed. I've never installed it, going all the way back to version 1.7. Same with Haali splitter, never installed it.
Hopefully this will shed some light on why it's happening to me.

**Comment by stax76** [comment]
I've flipped it for AviSynth and forgot to do it with VapourSynth too, sorry about that.

L-Smash-Works don't has a Haali splitter dependency! Some people like the ripbot author prefer L-Smash over ffms2.

Thanks for reporting! I'll upload a fix shortly.

**Comment by ukharley** [comment]
Thanks, works fine now. I also only use ffms2 as a last resort.
