### ISSUE TITLE
Amd VCEenc & FpsChange (StaxRip 2.13.0)

### ISSUE THREAD

**Issue by metagondria** [staxrip/staxrip#950]
Hello,

Iam searching for an away to convert old dvd content using my RX6600 gpu (VCE).
VCe in staxrip works awesome (very fast xxx fps), as long i don't change pal fps to film fps !!

And that's the main issue i have right now!

When i use changeFps to 24 , staxrip tells me the output will be 24fps... But the actuall output file is still 25fps (mediainfo) !!!

Not matter which frameserver i use (LwlibavSource , D2Vsource), the output file is always 25fps !!!
Only Cpu methode encode applies the right fps (avisynth/vapour)!!!

Also, using other filters like "selectEvery(), doesn't apply 25fps → 24fps neither !

I hope there's some sollution (workarround) to convert pal 25fps to 24fps using amd VCE...

Pc config:

Mobo: Asus Sabretooth FX-990 R2.0
Cpu: fx-8350 @4700Mhz
Ram: DDR3-1866
SSD: Samsung EVo850 Pro
Gpu: RX6600
OS: Win 10 Build 10.0.19045

much obliged,

cheers,

**Comment by Dendraspis** [comment]
Sorry, I'm not that familiar with VCEEnc and framerate changing filters. Please visit [look here](https://github.com/staxrip/staxrip#community) for more help...
