### ISSUE TITLE
Unzipping Program

### ISSUE THREAD

**Issue by RKEP71** [staxrip/staxrip#951]
Hi

I am really eager to use this program but for some reason I cannot unzip any version of the program. I just get alot of errors and the final unzipped program is not recognized by windows because I assume it hasn't unzipped the information, hense the errors.

Please help! I have no idea why this is happening. Obviously it works for so many people, so what am I doing wrong?

**Comment by Discograp** [comment]
this happened to me because of the antivirus or the defender of windows. they removed some kind of code inside

**Comment by Discograp** [comment]
turn them off and add them to exclusions then turn them on

**Comment by RKEP71** [comment]
Thx for the advice. I have been using winrar and for some reason this will not work even with antivirus disabled. I tried 7zip and it is working. I am now in business, thx again
