### ISSUE TITLE
Avisynth filters with NVENC codec

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#952]
Hi,
when i try to do avisyth filter with latest version of NVENC i got this:

Error Video encoding (v2.13.0)

Video encoding returned exit code: 1 (0x1)

--------------------------- Video encoding ---------------------------

NVEnc 7.04

E:\4k_Encode\apps\NVEncC_7.04_x64\NVEncC64.exe --avsdll E:\4k_Encode\apps\StaxRip-v2.13.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll  --cqp 18 --codec h265 --dolby-vision-rpu "E:\DoVi_Scripts_1.6.5_TOOLS\MyVideo_RPU.bin" --dolby-vision-profile 5.0 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --colorrange full --chromaloc 2 --mv-precision q-pel --cabac -i "E:\4k_Encode\DoVi_Scripts_1.6.5_TOOLS\MyVideo_temp\MyVideo.avs" -o "E:\4k_Encode\DoVi_Scripts_1.6.5_TOOLS\MyVideo.h265"

--------------------------------------------------------------------------------
E:\4k_Encode\DoVi_Scripts_1.6.5_TOOLS\MyVideo.h265
--------------------------------------------------------------------------------
Please use VBR mode for dolby vision output.

StaxRip.ErrorAbortException: Video encoding returned exit code: 1 (0x1)

--------------------------- Video encoding ---------------------------

NVEnc 7.04

E:\4k_Encode\apps\NVEncC_7.04_x64\NVEncC64.exe --avsdll E:\4k_Encode\apps\StaxRip-v2.13.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll  --cqp 18 --codec h265 --dolby-vision-rpu "E:\DoVi_Scripts_1.6.5_TOOLS\MyVideo_RPU.bin" --dolby-vision-profile 5.0 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --colorrange full --chromaloc 2 --mv-precision q-pel --cabac -i "E:\4k_Encode\DoVi_Scripts_1.6.5_TOOLS\MyVideo_temp\MyVideo.avs" -o "E:\4k_Encode\DoVi_Scripts_1.6.5_TOOLS\MyVideo.h265"

--------------------------------------------------------------------------------
E:\4k_Encode\DoVi_Scripts_1.6.5_TOOLS\MyVideo.h265
--------------------------------------------------------------------------------
Please use VBR mode for dolby vision output.

   w StaxRip.Proc.Start() w D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:wiersz 361
   w StaxRip.NVEnc.Encode() w D:\Code\Github\staxrip\staxrip\Source\Encoding\NVEnc.vb:wiersz 107
   w System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w StaxRip.GlobalClass.ProcessJob(String jobPath) w D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:wiersz 371

**Comment by Discograp** [comment]
new driver versions are needed for GTX 40XX

**Comment by madey83** [comment]
i have found where the issue was: i have used CQP instead VBR mode.
