### ISSUE TITLE
"Normalize to a specific db level" option

### ISSUE THREAD

**Issue by Augur1989** [staxrip/staxrip#957]
I'm missing an option, that allows me to change the audio volume to a specific db lvl without having to check it's current volume.

When i have a very quiet audio, Xmedia Recode for example shows me that the audio lvl is 76,5 db and if i want it to be at 89 db (default), the gain would be 12,5 db.
![image](https://user-images.githubusercontent.com/104071754/205375631-c85aec95-aa95-4d06-b09e-8695eaa4643d.png)

Can we please get such an option, so that i can set my target volume level (89 db) and the encoder adds the required gain value so that the output is at 89 db?

That would save a lot of time for batch converting at the end of the day

**Comment by Dendraspis** [comment]
`Normalize` by definition means setting the volume of the loudest peak to 0.0dB. This can be done via the `Normalize` checkbox. If you want to adjust it more (for whatever reason), you can use the `Gain` control, but basically `Normalize` is all you need to get the best result.

**Comment by Augur1989** [comment]
No, that's not what i mean.
when you got different movies at different loudness levels, you need to find out the gain value every time.
i'm looking for a way that does that automatically and tells me which gain level i need to enter so that the movie is at that level i want it to be. Even better was it, if it just would calculate and enter that value automatically, so that you just would need to enter the desired value once and it always corrects the level automatically. 
you know what i mean?

**Comment by Kartus22** [comment]
Please add this option, that would be great.
