### ISSUE TITLE
MKVExtract and FFMSIndex Phase is super slow, even on NVME SSD

### ISSUE THREAD

**Issue by voltuz** [staxrip/staxrip#958]
MKVExtract and FFMSIndex Phase is super slow, even on NVME SSD. It takes almost 30min to go through both of the stages.
Source video i'm trying to convert is a 4k hdr h265 mkv.
Both disk and cpu are not being utilized at the maximum.
<img width="218" alt="Taskmgr_KQSSCr93ha" src="https://user-images.githubusercontent.com/68356371/205669720-c05f7282-6fe9-45ec-8a8e-bdeae4d4d5c5.png">

My hardware
Ryzen 7 5800x
64gb ram
8tb Sabrent NVME SSD (Disk where the video i'm trying to convert is located)
500gb WD black NVME SSD (disk where the os is installed)

- Used StaxRip version v2.13

**Comment by ChocOranger** [comment]
See replies on https://github.com/staxrip/staxrip/issues/896

I don't see any point in demuxing.

**Comment by Dendraspis** [comment]
Do you let the video track also demux?

It's like it is and also mentioned in #896 - You can choose prefilters, that are a bit faster and don't need that time consuming indexing. Nevertheless this is the best solution in terms of compatibility so we'll keep it at the moment.
