### ISSUE TITLE
Add ability to set Commentary flag on audio and subtitle tracks from the container options 

### ISSUE THREAD

**Issue by xEsteem** [staxrip/staxrip#959]
Should be able to set the `--commentary-flag TID[:bool]` flag on audio and subtitle tracks from the container options.
https://mkvtoolnix.download/doc/mkvmerge.html

Its a setting available in MKVToolNixGUI so would be nice to be able to set within staxrip container options also

**Comment by Dendraspis** [comment]
Took a while, but will be available in the next release.
