### ISSUE TITLE
Add support for Dolby Encoding Engine (DEE)

### ISSUE THREAD

**Issue by xEsteem** [staxrip/staxrip#961]
Add support for Dolby Encoding Engine (DEE)
At the moment the best way to use DEE for encoding dolby audio is using this wrapper https://github.com/pcroland/deew

Annoyingly you cant use DEEW with staxrip over commandline because it throws an exception with the commandline output that DEEW spits out. Would be nice to do the equivalent of DEEW within staxrip, which it looks like ultimately is creating a temp wav file and a DEE XML config and then running DEE 

DEE isn't free, however, so this would be something users would need to acquire themselves and setup in staxrip (like some of the other paid for software it supports)

**Comment by Dendraspis** [comment]
ddew's requirements are:
- ffmpeg
- ffprobe
- Dolby Encoding Engine

Have you tried to add all paths to those tools (meaning the exe files) to your Environment PATH variable? StaxRip launches `deew.exe` successfully, so this could help.

**Comment by xEsteem** [comment]
> Have you tried to add all paths to those tools (meaning the exe files) to your Environment PATH variable? StaxRip launches `deew.exe` successfully, so this could help.

Yes, i have DEEW running fine. Have you got it working from stax rip? if i change the audio encoding the command line and set up deew i get an exception because stax cant handle the formatting out the stdout. Also DEEW to my knowledge cant specify an exact output file name. I've raised both these issues on the DEEW github

https://github.com/pcroland/deew/issues/49
https://github.com/pcroland/deew/issues/48

Although i think for staxrip it would be nice to just have native DEE support rather than using a wrapper

**Comment by Dendraspis** [comment]
Can you check the same attempt with this exe file?  
[StaxRip v2.14.9.zip](https://github.com/staxrip/staxrip/files/11012268/StaxRip.v2.14.9.zip)

Because I have no DEE I cannot test it by myself.

**Comment by xEsteem** [comment]
```
Error Audio Encoding: Command Line (v2.14.9)

Audio Encoding: Command Line returned exit code: 1 (0x1)


-------------------- Audio Encoding: Command Line --------------------

deew -i "[redacted]/input.thd" -b 640 -f dd

Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
  File "deew\__main__.py", line 552, in main
  File "rich\__init__.py", line 74, in print
  File "rich\console.py", line 1667, in print
  File "rich\console.py", line 869, in __exit__
  File "rich\console.py", line 827, in _exit_buffer
  File "rich\console.py", line 2024, in _check_buffer
  File "rich\_windows_renderer.py", line 17, in legacy_windows_render
  File "rich\_win32_console.py", line 442, in write_styled
  File "rich\_win32_console.py", line 403, in write_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-5: character maps to <undefined>
[35540] Failed to execute script '__main__' due to unhandled exception!

StaxRip.ErrorAbortException: Audio Encoding: Command Line returned exit code: 1 (0x1)


-------------------- Audio Encoding: Command Line --------------------

deew -i "[redacted]/input.thd" -b 640 -f dd

Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
  File "deew\__main__.py", line 552, in main
  File "rich\__init__.py", line 74, in print
  File "rich\console.py", line 1667, in print
  File "rich\console.py", line 869, in __exit__
  File "rich\console.py", line 827, in _exit_buffer
  File "rich\console.py", line 2024, in _check_buffer
  File "rich\_windows_renderer.py", line 17, in legacy_windows_render
  File "rich\_win32_console.py", line 442, in write_styled
  File "rich\_win32_console.py", line 403, in write_text
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-5: character maps to <undefined>
[35540] Failed to execute script '__main__' due to unhandled exception!


   at StaxRip.Proc.Start()
   at StaxRip.BatchAudioProfile.Encode()
```

**Comment by Dendraspis** [comment]
Okay, last test to see if this would work:
[StaxRip v2.14.10.zip](https://github.com/staxrip/staxrip/files/11015084/StaxRip.v2.14.10.zip)

**Comment by xEsteem** [comment]
```
Error Audio Encoding: Command Line (v2.14.10)

Audio Encoding: Command Line returned exit code: 1 (0x1)


-------------------- Audio Encoding: Command Line --------------------

deew -i "[redacted]/input.thd" -b 640 -f dd

牔捡扥捡⁫洨獯⁴敲散瑮挠污⁬慬瑳㨩਍†楆敬∠彟慭湩彟瀮≹‬楬敮㘠‬湩㰠潭畤敬ാ 䘠汩⁥搢敥屷彟慭湩彟瀮≹‬楬敮㔠㈵‬湩洠楡൮ 䘠汩⁥爢捩屨彟湩瑩彟瀮≹‬楬敮㜠ⰴ椠⁮牰湩൴ 䘠汩⁥爢捩屨潣獮汯⹥祰Ⱒ氠湩⁥㘱㜶‬湩瀠楲瑮਍†楆敬∠楲档捜湯潳敬瀮≹‬楬敮㠠㤶‬湩张敟楸彴ൟ 䘠汩⁥爢捩屨潣獮汯⹥祰Ⱒ氠湩⁥㈸ⰷ椠⁮敟楸彴畢晦牥਍†楆敬∠楲档捜湯潳敬瀮≹‬楬敮㈠㈰ⰴ椠⁮损敨正扟晵敦൲ 䘠汩⁥爢捩屨睟湩潤獷牟湥敤敲⹲祰Ⱒ氠湩⁥㜱‬湩氠来捡役楷摮睯彳敲摮牥਍†楆敬∠楲档彜楷㍮弲潣獮汯⹥祰Ⱒ氠湩⁥㐴ⰲ椠⁮牷瑩彥瑳汹摥਍†楆敬∠楲档彜楷㍮弲潣獮汯⹥祰Ⱒ氠湩⁥〴ⰳ椠⁮牷瑩彥整瑸਍†楆敬∠湥潣楤杮屳灣㈱㈵瀮≹‬楬敮ㄠⰹ椠⁮湥潣敤਍湕捩摯䕥据摯䕥牲牯›挧慨浲灡‧潣敤⁣慣❮⁴湥潣敤挠慨慲瑣牥⁳湩瀠獯瑩潩⁮ⴱ㨵挠慨慲瑣牥洠灡⁳潴㰠湵敤楦敮㹤਍㉛ㄸ〶⁝慆汩摥琠⁯硥捥瑵⁥捳楲瑰✠彟慭湩彟‧畤⁥潴甠桮湡汤摥攠捸灥楴湯ഡ

StaxRip.ErrorAbortException: Audio Encoding: Command Line returned exit code: 1 (0x1)


-------------------- Audio Encoding: Command Line --------------------

deew -i "[redacted]/input.thd" -b 640 -f dd

牔捡扥捡⁫洨獯⁴敲散瑮挠污⁬慬瑳㨩਍†楆敬∠彟慭湩彟瀮≹‬楬敮㘠‬湩㰠潭畤敬ാ 䘠汩⁥搢敥屷彟慭湩彟瀮≹‬楬敮㔠㈵‬湩洠楡൮ 䘠汩⁥爢捩屨彟湩瑩彟瀮≹‬楬敮㜠ⰴ椠⁮牰湩൴ 䘠汩⁥爢捩屨潣獮汯⹥祰Ⱒ氠湩⁥㘱㜶‬湩瀠楲瑮਍†楆敬∠楲档捜湯潳敬瀮≹‬楬敮㠠㤶‬湩张敟楸彴ൟ 䘠汩⁥爢捩屨潣獮汯⹥祰Ⱒ氠湩⁥㈸ⰷ椠⁮敟楸彴畢晦牥਍†楆敬∠楲档捜湯潳敬瀮≹‬楬敮㈠㈰ⰴ椠⁮损敨正扟晵敦൲ 䘠汩⁥爢捩屨睟湩潤獷牟湥敤敲⹲祰Ⱒ氠湩⁥㜱‬湩氠来捡役楷摮睯彳敲摮牥਍†楆敬∠楲档彜楷㍮弲潣獮汯⹥祰Ⱒ氠湩⁥㐴ⰲ椠⁮牷瑩彥瑳汹摥਍†楆敬∠楲档彜楷㍮弲潣獮汯⹥祰Ⱒ氠湩⁥〴ⰳ椠⁮牷瑩彥整瑸਍†楆敬∠湥潣楤杮屳灣㈱㈵瀮≹‬楬敮ㄠⰹ椠⁮湥潣敤਍湕捩摯䕥据摯䕥牲牯›挧慨浲灡‧潣敤⁣慣❮⁴湥潣敤挠慨慲瑣牥⁳湩瀠獯瑩潩⁮ⴱ㨵挠慨慲瑣牥洠灡⁳潴㰠湵敤楦敮㹤਍㉛ㄸ〶⁝慆汩摥琠⁯硥捥瑵⁥捳楲瑰✠彟慭湩彟‧畤⁥潴甠桮湡汤摥攠捸灥楴湯ഡ


   at StaxRip.Proc.Start()
   at StaxRip.BatchAudioProfile.Encode()
```

hymm not quite. Failed for exit code even tho if i run that command line directly its fine.
In any case, the DEEW issues can be solved by the DEEW team i suspect. Really this request was more about native DEE support (without the wrapper) in the same way as it natively supports the likes of ffmpeg, qaac, etc etc.

**Comment by Dendraspis** [comment]
Okay, so it is an encoding issue and because (almost) every tool can be started normally, it should be a "problem" on DEEW's side. I would guess it's just a small configuration issue, but sadly I can't help with Python.

Hope it will be fixed....

**Comment by xEsteem** [comment]
Cool, as mentioned, this request wasnt for DEEW support but for native DEE support (without needing to use DEEW), so please keep this request open unless it is denied

**Comment by jlw4049** [comment]
@Dendraspis esteem and myself has built another cli you'd be able to integrate to stax for encoding with dee at some point if you are interested

**Comment by Dendraspis** [comment]
Sounds interesting.
If it's okay for you, let's talk about the details via DC DM....

**Comment by jlw4049** [comment]
> Sounds interesting. If it's okay for you, let's talk about the details via DC DM....

Sounds great. I added you/sent you a PM.
