### ISSUE TITLE
Add KTGMC - Nvida Cuda Accelarated QTGMC De-interlacing 

### ISSUE THREAD

**Issue by harrypm** [staxrip/staxrip#963]
This filter would be a great addition to StaxRip, and allow much faster GPU-based de-interlacing.

https://github.com/nekopanda/AviSynthCUDAFilters

**Comment by Dendraspis** [comment]
As far as I can tell, due to the fact, that all information are Japanese only, it seems KTGMC needs a modified Version of AviSynth+ called AviSynth Neo. So sadly I can't include this filter...
