### ISSUE TITLE
HW NV encoder resize Default option is now Auto in rigaya Build

### ISSUE THREAD

**Issue by AYColumbia** [staxrip/staxrip#964]
**Describe the bug**
The current resize options for NV encoder for resize (see image) has the old Default option which has been changed to Auto.  These are the switch and options in the current rigaya build 7.06 (also in 6.10 packaged with StaxRip):

```
--vpp-resize <string>        auto, bilinear, nearest, spline16, spline36
                                spline64, lanczos2, lanczos3, lanczos4, nn
                                npp_linear, cubic, super, lanczos
                                 default: auto
```

**Expected behavior**
Resize list to contain Auto instead of Default.

**How to reproduce the issue**
1. Choose Nvidia - h.264 or h.265 for a hw encoder
2. Click on Encoder Options
3. Go to VPP | Misc and select the Resize pulldown list (see image)
4. If you choose Default, the latest NV encoder will error on the resize switch since it expects Auto rather than Default which is what's added to the command line.

**Provide information**
StaxRip version 2.13.0
NV encoder version 7.06 rigaya (https://github.com/rigaya/NVEnc/releases/tag/7.06)

Issue also exists with NV encoder packages with StaxRip, i.e.,
NVEncC (x64) 6.01 (r2167) by rigaya,

![2022-12-18 22_43_28-NVEnc Options (219 options)](https://user-images.githubusercontent.com/6758781/208351005-562a77db-90c1-43a1-be59-51d259eb46e5.png)

Thank you and please let me know if you need any other info.

**Comment by Dendraspis** [comment]
Thanks for the superb report.
I also fixed the old parameter names and added the belonging missing parameters. 
They will be available in the next release...
