### ISSUE TITLE
High CPU load with AMD Ryzen 5600G and AMD 6750XT

### ISSUE THREAD

**Issue by ah-its-andy** [staxrip/staxrip#969]
**Describe the bug**
Hardwares:
CPU: AMD Ryzen 5600G (with graphic cores)
GPU: AMD 6750XT

VCEEnc report a error message 'Error (clGetDeviceIDsFromD3D11KHR): device not found. device #2: failed to find d3d11 device' when I start task.  Then the task will starting but my CPU load went above 90% and GPU load only 10%.

**Expected behavior**
CPU load should not that high, and GPU should go high.

**How to reproduce the issue**
Use AMD Ryzen 5600G (with graphic cores) and AMD 6750XT in a windows 11 PC, enable core graphic in bios. Then start AMD h265 task.

**Provide information**
I assume this cause by VNCEnc because of the graphic cores in 5600G not support AMF, maybe block them from VNCEnc should work.

**Notes before posting**
- Please also try the latest release of StaxRip.
- Only open an issue if it's tied to StaxRip, if the issue is tied to an external program or filter then head to that project and open an issue there. 
- Check your CPU specs, many newer filters are AVX2 enabled with no AVX1 support, this is especially true on the VapourSynth side, which will crash if your CPU don't support it.
- Lastly, only files that are released with StaxRip are fully supported, this is done to make debugging easier. Also since all filters have been tested before the release, newer versions can have changes which have not been added to StaxRip yet.

**Additional context**
Add any other information or additional context that can be helpful.

**Please be as clear and as detailed as possible**

**Comment by Discograp** [comment]
use x264 - high10 10bit for av1

**Comment by Discograp** [comment]
your problem is that
your VGA is brand new
and staxrip uses old "scripts/algorithms"
try to update VNCEnc

or use X264/265 (CPU)

**Comment by Discograp** [comment]
use this https://github.com/rigaya/VCEEnc/releases

**Comment by Dendraspis** [comment]
Seems like a new version of VCEEnc is needed, otherwise there's nothing I can do I guess.

Next release with new VCEEnc version will be released soon. Feel free to re-open this issue if it won't work...
