### ISSUE TITLE
Add CCD filter for Vapoursynth

### ISSUE THREAD

**Issue by SuperMagicom** [staxrip/staxrip#972]
Would like to see the Vapoursynth port of the Virtualdub filter CCD added to StaxRip if possible.

https://github.com/End-of-Eternity/vs-ccd

This is arguably the best filter for fixing VHS chroma rainbows.

**Comment by Ding-adong** [comment]
You can add any filters you want yourself.
AVS filters - right click - profiles

**Comment by Dendraspis** [comment]
Additionally:  https://github.com/staxrip/staxrip/wiki/Usage#video-processing  ☺️ 
...and of course:  https://github.com/staxrip/staxrip#community

I don't think it is necessary to add such a special filter for all....
