### ISSUE TITLE
fade-compensate in x264 not working

### ISSUE THREAD

**Issue by Leinad4Mind** [staxrip/staxrip#973]
**Describe the bug**
If I enable fade-compensation in x264, it gives error on the encode process. Removing the option by setting 0, it encodes properly.

**Expected behavior**
I was expecting to be able to use fade-compensation and even fgo, but didnt saw that one on the configs.

I am using last staxrip version. And was encoding an x265 8bit video to x264 8bit.

**Comment by Dendraspis** [comment]
As far as I remember the fade-compensate patch was never officially built/activated for x264. You need a build, that was compiled with the fade-compensate patch, so you can use the parameter.

Btw:  `x265 8bit video to x264 8bit` .... why??

**Comment by Leinad4Mind** [comment]
Ahah I know its odd to go down to x264, but basically I didnt found any software that worked well for cutting my x265 videos on exact frames without reencoding it (I know I can only cut on I-frames, but some softwares reencode few frames between the closest I-frame and the exact frame I want to cut). I tried at least 4 of them... including videoredo (that seemed the best one) but they dont support x265, or at least my x265 encodes... So changing to x264 solved my problem. 
And we're talking about VHSRips, so, there is no visible quality loss, only bigger files.

**Comment by Leinad4Mind** [comment]
Btw, I've a build with fade-compensate and fgo, is it possible to have the fgo parameter too since my build have it?

**Comment by Dendraspis** [comment]
`--fgo` was basically replaced through `--psy-rd`  and is pretty deprecated, so I won't add it.
But you can use the *Custom* field to add whatever you want.  🙂
