### ISSUE TITLE
staxrip don`t use 100% from cpu

### ISSUE THREAD

**Issue by mr-qansuh** [staxrip/staxrip#976]
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).

how can i use 100% from cpu when i encoding

**Comment by Kartus22** [comment]
Depends on your settings and which Encoder you are using, if you are using AV1 AOMenc, multithreading is not a strength of that encoder. More Information would be good. Staxrip is working fine an using full CPU avaiable load.

**Comment by mr-qansuh** [comment]
> Depends on your settings and which Encoder you are using, if you are using AV1 AOMenc, multithreading is not a strength of that encoder. More Information would be good. Staxrip is working fine and using full CPU capacities for x264 and x265 for me.

staxrip 1.7.0.0 use 100% of cpu when i use 2.13.0 do not use 100%

**Comment by Dennis50300** [comment]
which avs filters do you use ?
i use nvenc, h264 oder h265, gpu does it more efficienc
x264 and x265 are not a problem with cpu
