### ISSUE TITLE
Missing description of every checkbox

### ISSUE THREAD

**Issue by sixSextant** [staxrip/staxrip#978]
**Describe the bug**
There's no text displayed beside every checkbox. Every option becomes unrecognizable.

**Expected behavior**
Displaying description beside checkbox.

**How to reproduce the issue**

Download, unzip and execute the main executable.

**Provide information**

- Latest release: v2.13.0
- Windows 10 22H2, 19045.2604

![image](https://user-images.githubusercontent.com/50039750/221398445-74f571b7-795a-4568-a2ba-c53ee9e1d9af.png)
![image](https://user-images.githubusercontent.com/50039750/221398469-00c802fa-ec0a-480c-8466-0712e4b412ea.png)

**Comment by Dendraspis** [comment]
Sadly the whole core of StaxRip is pretty old and some things had to be tweaked.
It looks like there is a disadvantageous interaction between your Windows version, graphics drivers, resolution, display scaling, etc.  

There is just one point we could check:
Please check *UI scale* in the settings, set it to `1.00` and restart StaxRip. Do you see the text now?

![image](https://user-images.githubusercontent.com/50659978/223879730-69556781-c8c7-467a-b1f8-ddc0fe31a3fc.png)

**Comment by Dendraspis** [comment]
Sorry, I have seen it on the first picture, but forgot it while thinking afterwards.  😁 
Did you try setting it to 0.9 and/or 1.1 ?  Maybe this could solve the issue for you.

> I'm scaling at 125% on the system level, as it recommends.

Could you please try 100% and/or 150%? As far as I remember 125% was a problem a few times. Of course this is just a quick workaround, but it could help me. I'll have a look at the implementation of the checkboxes when I've got more time...

**Comment by sixSextant** [comment]
Sorry for the late reply. I've been working on my computer build, so...

> Could you please try 100% and/or 150%?

I just tried both 100% and 150%. Sadly neither of them worked.

**Comment by Dendraspis** [comment]
Can you check if that makes any difference for you?
[StaxRip v2.17.5.zip](https://github.com/staxrip/staxrip/files/11524092/StaxRip.v2.17.5.zip)

**Comment by Dendraspis** [comment]
I have added a setting that allows you to use a conventional text drawing, which should fix your issues, at least with the checkboxes. 
When there are more issues with missing text, don't hesitate to come back.

The next release will have the setting.....
