### ISSUE TITLE
Beta 2.0.6.2 various little things

### ISSUE THREAD

**Issue by jalba69** [staxrip/staxrip#98]
Hello Stax,

Encoding in vp8 or vp9 doesn't work, replacing bundled ffmpeg with latest Zeranoe's ffmpeg works.
 
Error message mention "Unknown encoder 'libvpx-vp9'& Unknown encoder 'libvpx' for VP9 and VP8.
Not sure this ffmpeg build included have those flags turned on or even the libs needed.

Also when switching to a container not compatible with vp9 encoder  we have this message :
![2019-12-27_093034](https://user-images.githubusercontent.com/15131985/71510801-6732b700-2890-11ea-8a39-b4080d14cfa6.png)
Shouldn't it say webm ( or even vp9-8 ) like in previous 1.7 versions instead of MKV ?
![2019-12-27_093027](https://user-images.githubusercontent.com/15131985/71510810-6e59c500-2890-11ea-86b4-839d9de035b8.png)

While i think at it, selecting no muxing when using VP9 should add automatically the .webm extension ( it is on the list of muxers and we can select it manually but would be better to have this automatically done like in the older 1.7 versions maybe ) 
Right now selecting no muxing when encoder is vp8 or vp9 switches to MKV for the muxer.

----------

Speaking of containers, trying AV1 with MP4 for container brings a similar warning, but it should be possible : 
https://gpac.wp.imt.fr/2018/10/27/official-av1-and-vp9-support-in-gpac/

Did not tried much as AV1 on my system is a painfully slow to encode but mp4box used in command line with av1 input works. 
`mp4box -add input.av1 -add audio.m4a -new output.mp4`

Also it is apparently not possible to have a no muxer output for av1, I mean having only the encoder ffmpeg>av1 and output being extension .av1 only, a bit like x265 without no muxing option producing a .hevc file.

Might be possible to add it myself but have not looked into it yet, still have not finished to import all my stuff and testing a few things while doing so.

That's all for now ;)
Thank you.

**Comment by Patman86** [comment]
Hi Jalba69,

download ffmpeg from [here](https://www.mediafire.com/folder/vkt2ckzjvt0qf/StaxRip_Tools). The included Version of ffmpeg in StaxRip 2.0.6.2 has no lib for vpx but i've fixed that.

**Comment by jalba69** [comment]
Hi,

grabbed it,  had not time to test yet but will do in the next days, I'm sure it will be fine.

I suppose next versions of Staxrip will include the one with correct libs so i'm closing this issue.

Thanks again for all Patman :)

**Comment by jalba69** [comment]
Silly me...thought i was on another topic page with a single issue reported, hence why closing it on last answer, but nope..

Re-Opening this for other little things...

**Comment by stax76** [comment]
VP9 encoding works with the last beta.

**Comment by stax76** [comment]
OK, I needed some time to understand and find the problem, will be fixed in 2.0.7.4
