### ISSUE TITLE
Update vapoursynth to latest version

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#981]
I'd like staxrip to be updated to the latest version. 

DJatom had a PR but deleted a while back.

**Comment by TheMaskedOnion** [comment]
I would love to see the latest version of Vapoursynth added as well.

This is the PR that DJatom made. 

https://github.com/staxrip/staxrip/pull/841

I did build staxrip 2.13 with DJatom changes and i could open a video with VS v60. I did however have issue with a lot of the desnoising presets and i couldn't figure out how to update them.

**Comment by DJATOM** [comment]
> DJatom had a PR but deleted a while back.
When you're deleting forked repository, github closes all PRs made from that repo. I didn't know. 
My commits are still accessible, just export as patches ([c1](https://github.com/staxrip/staxrip/commit/e8dc8655ced62551fccded0b4d1e2abf227c4370.patch), [c2](https://github.com/staxrip/staxrip/pull/841/commits/67a96528e4a985c684d753de5e679c8b004525ed.patch)) and apply to original repo, if my solution preferred.

**Comment by Dendraspis** [comment]
I know, thanks. They will be used (I guess) when I have time to deal with the whole process.

**Comment by Dendraspis** [comment]
Almost finished, so it will be available in the next release.  

Thank you for your contributions!  👍
