### ISSUE TITLE
QSVEnc AV1 and MKV (mkvmerge) container conflict (Staxrip v2.14.0)

### ISSUE THREAD

**Issue by pat-e** [staxrip/staxrip#982]
When trying to use the Intel AV1 - Encoder, Staxrip gives an error that the output 'av1' is not supported by the container 'MKV (mkvmerge)':
![2023-03-13_222316](https://user-images.githubusercontent.com/11069987/224836227-9cce5afc-3184-4cdb-b25d-b593c4f1f31e.png)

But using the official MKVToolNix GUI v74.0.0, the AV1 - file can be included correctly and muxed into a working file:

![2023-03-13_222531](https://user-images.githubusercontent.com/11069987/224836390-bb621282-720f-4843-b1ab-821901d4c0fc.png)

Is it possible to include "av1" into MKV using the MKVmerge?

**Comment by Discograp** [comment]
av1 codec - support only mp4

**Comment by pat-e** [comment]
> av1 codec - support only mp4

But why can MKVToolNix merge the AV1 - File into a correct MKV-File ?

**Comment by Discograp** [comment]
the script is different
even in the name it says that it can

**Comment by Discograp** [comment]
you should be worried about the quality of the image and not the container

**Comment by Discograp** [comment]
understand

- Staxrip
- MKVToolNix

regular launchers with a user-friendly interface like Steam or other game launchers

**Comment by Dendraspis** [comment]
You're right, meanwhile mkvmerge is able to open them directly. Thanks for the report.
It will be fixed in the next release. In the meanwhile, if you want to use (and test) it...
[StaxRip v2.14.2.zip](https://github.com/staxrip/staxrip/files/10985018/StaxRip.v2.14.2.zip)

**Comment by pat-e** [comment]
I tested the Version and it works now (almost) perfectly.

Thanks for the quick fix.
