### ISSUE TITLE
QSVEnc allow 10 Bit-Output as select-able button/switch/etc.

### ISSUE THREAD

**Issue by pat-e** [staxrip/staxrip#984]
The official documentation of QSVEnc allows to set an output-depth of 10 Bit:

https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--output-depth-int

`--output-depth <int>`
> Set output bit depth. Default is 8.
> 8, 10

Currently, I use the "Custom" - field to enter that option  (while using the QSVEnc AV1 - Encoder), but it would be nice if that Option is available as an easy select-able switch / button / drop-down menu. 

Best regards,

**Comment by Dendraspis** [comment]
I've added a drop-down menu, which will be available in the next release.  🙂

**Comment by Discograp** [comment]
next release when?

**Comment by Dendraspis** [comment]
We will see...
