### ISSUE TITLE
Remember the size of the Preview window

### ISSUE THREAD

**Issue by Galaxoid-333** [staxrip/staxrip#986]
Make the Preview window remember the last size. Now, each time you open the Preview window, you need to stretch it to the same size. It is especially inconvenient when you open several preview windows.

**Comment by Galaxoid-333** [comment]
I will correct myself. Tools has a constant window size setting. The maximum size is 90%. True, it seems to me that this is not exactly 90%, and it was possible to increase the maximum size. In other words, there is a lot of empty space before the taskbar.

**Comment by Galaxoid-333** [comment]
I think there is a preview window size in the general settings, which may be sufficient. Or abandon this setting and leave manual resizing. Otherwise, these functions intersect.

**Comment by Dendraspis** [comment]
Before I'm starting to implement a possible option: Did you try this setting?

![image](https://github.com/staxrip/staxrip/assets/50659978/d368a983-feb7-4231-bcc6-e53113775776)

It should already solve the issue you have.  🤔

**Comment by Galaxoid-333** [comment]
Yes, I have tried this setting. As I wrote above. This intersects with remembering the size of the window. You need to choose one of them. One clarification, 90% leaves free space on the screen, you can probably make a maximum of 95%.

**Comment by Dendraspis** [comment]
Ok, sorry, I thought in the wrong direction - you want to make and use it bigger instead of using a smaller specific size.

I will see what's possible...

**Comment by Galaxoid-333** [comment]
> I thought in the wrong direction - you want to make and use it bigger instead of using a smaller specific size.

this is also useful, but sometimes. when you open 4 preview windows.

**Comment by Dendraspis** [comment]
Have that request still on my list, but does the reload function solves your problems meanwhile? Or is it even better?

**Comment by Galaxoid-333** [comment]
Do you mean try the new version?

I'll see.

**Comment by Galaxoid-333** [comment]
I checked on the latest version. I don't see any changes. As before, manual changes to the preview window are not saved. The maximum size (90%) of previews in the settings is far from the maximum possible window size.
