### ISSUE TITLE
AMD VCEEnc Decoder is not working

### ISSUE THREAD

**Issue by SuperMitic** [staxrip/staxrip#987]
**Describe the bug**

I tried using StaxRip and AMD VCEEnc to encode a video. Encoding using VCEEnc HW Encoding and CPU Decoding is working, but if in StaxRip i select VCEEnc as Decoder (in order to use GPU HW Decoding), encoding is not working and it crash with this error:

```
AMFDEC: ERROR: Resolution changed during decoding.
AMFDEC: Failed to load input frame: unknown error..
Break in task AMFDEC: unknown error..
encoded 0 frames, 0.00 fps, 0.00 kbps, 0.00 MB
encode time 0:00:00, CPULoad: 0.0
Finished with error in VCEEncC.
```

These are the parameter i'm using: `--avhw --codec hevc --output-depth 10 --quality slow --max-bitrate 21000 --colorprim bt709 --vbr 18000 -i`. This issue appear when using --avhw.

GPU: RX 6600 with latest 23.3.2 driver
I don't if this problem is caused by latest 23.3.2 driver.

**Expected behavior**

VCEEnc Decoder should work.

**How to reproduce the issue**

Import a video and then select AMD H265 and Decoder: VCEENc.

**Provide information**

AMFDEC: ERROR: Resolution changed during decoding.
AMFDEC: Failed to load input frame: unknown error..
Break in task AMFDEC: unknown error..
encoded 0 frames, 0.00 fps, 0.00 kbps, 0.00 MB
encode time 0:00:00, CPULoad: 0.0
Finished with error in VCEEncC.

Using latest StaxRip 2.14
GPU: RX 6600 with latest 23.3.2 driver

**Comment by Discograp** [comment]
VCEEnc 8.10 try this https://github.com/rigaya/VCEEnc/releases

    Avoid crush on encoder calls.
    Avoid audio and subtitles to have negative timestamps.
    Fix --vpp-overlay not working when overlay target is video.
    Fix --vpp-colorspace crushing from VCEEnc 8.09.
    Improve log output.

**Comment by SuperMitic** [comment]
> VCEEnc 8.10 try this https://github.com/rigaya/VCEEnc/releases
> 
> ```
> Avoid crush on encoder calls.
> Avoid audio and subtitles to have negative timestamps.
> Fix --vpp-overlay not working when overlay target is video.
> Fix --vpp-colorspace crushing from VCEEnc 8.09.
> Improve log output.
> ```

StaxRip 2.14 comes with VCEEnc 8.10

**Comment by Discograp** [comment]
write a complaint to Rigaya

Staxrip is a script launcher

**Comment by Dendraspis** [comment]
It seems like VCEEnc doesn't want to decode using your graphics card. Maybe due to old graphic driver or unsupported graphics card.

From what I can see it should be a tool issue, because the parameter is applied and executed, so nothing I can help with. Please ask Rigaya what's wrong.
