### ISSUE TITLE
Need a new resize

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#988]
when inputting so that the resolution does not change /// resolution limit - NONE

![001](https://user-images.githubusercontent.com/95682410/228399688-8ad52f2d-f843-4417-b4f0-60c672bfbc55.jpg)

**Comment by Dendraspis** [comment]
I don't get it. What is the problem?

Btw: Using the template when creating an issue could be useful.

**Comment by Discograp** [comment]
![channels4_profile](https://user-images.githubusercontent.com/95682410/228415407-d16db262-42d7-41d8-b2d9-f29c76f1b7bd.jpg)
done :))
