### ISSUE TITLE
Please answer!

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#989]
what is it? how does it work?
need links to description/website

![123](https://user-images.githubusercontent.com/95682410/228819312-94563ad6-bc25-4df6-908b-caefc0271637.jpg)

Thanks!

**Comment by Dendraspis** [comment]
1. Next time choose a proper title for your question.
2. Use Google or any other search engine and type in: `avisynth changefps` - you will be impressed.  I recommend the result titled `FPS Filters — AviSynth+ 3.7 documentation`.
