### ISSUE TITLE
stax can not use cpu well

### ISSUE THREAD

**Issue by mr-qansuh** [staxrip/staxrip#991]
this is video i convert using staxrip in first some minutes stax using over 76% form cpu and after some minutes it using from 10 to 15 %

picture from my task manger

![01](https://user-images.githubusercontent.com/79289286/229553201-7978a0e0-854e-405e-9594-554e8b24aabb.PNG)

**Comment by mr-qansuh** [comment]
video link
[https://www97.uptobox.com/dl/inZBuXzqb78c8IWn4197WOYWp6VqPlglPTd1QUs_l4N2bffLRmtNrisHOuBzD4026RqI9P9RSDJeyR_uo1TwW4R4qeVGLkiJzccfWauvJCuXDjjX-GmEXjDUynJc7ZxQ/WWE.WrestleMania.39.Sunday.720p.WEB.h264-HEEL.mp4](https://www97.uptobox.com/dl/inZBuXzqb78c8IWn4197WOYWp6VqPlglPTd1QUs_l4N2bffLRmtNrisHOuBzD4026RqI9P9RSDJeyR_uo1TwW4R4qeVGLkiJzccfWauvJCuXDjjX-GmEXjDUynJc7ZxQ/WWE.WrestleMania.39.Sunday.720p.WEB.h264-HEEL.mp4?fbclid=IwAR16PsHCtzoqiehI3W3LMPiNDUv-WqjXEVDFkpCMY21I480AZH_6uH11jGM)

**Comment by Dendraspis** [comment]
1. StaxRip itself does not use it, it's AviSynth/VapourSynth, the used scripts and the encoder.
2. Usage depends on the given hardware and used settings. Choose more demanding settings or use an older PC.
3. What do you expect without providing any information?

**Comment by Discograp** [comment]
4. need tech.info

cpu ???
os ???
codec ???
