### ISSUE TITLE
when use NVEnc to encoding video,4070ti only 50% usage.

### ISSUE THREAD

**Issue by ewanbandit** [staxrip/staxrip#992]
Stax rip v2.130
NVEnc 7.21

E:\StaxRip-v2.13.0-x64\StaxRip-v2.13.0-x64\Apps\Encoders\NVEnc\NVEncC64.exe --avhw --vbr 6000 --codec h265 --preset P7 --multipass 2pass-full --max-bitrate 0 -i "F:\PR daochu\186.mp4" -o "F:\PR daochu\186_temp\186_new_out.h265"

--------------------------------------------------------------------------------
F:\PR daochu\186_temp\186_new_out.h265
--------------------------------------------------------------------------------
NVEncC (x64) 7.21 (r2490) by rigaya, Mar 13 2023 14:18:26 (VC 1929/Win)
OS Version     Windows 10 x64 (19045) [UTF-8]
CPU            13th Gen Intel Core i7-13700K [4.19GHz] (8P+8E,16C/24T)
GPU            #0: NVIDIA GeForce RTX 4070 Ti (7680 cores, 2685 MHz)[PCIe4x16][531.41]
NVENC / CUDA   NVENC API 12.0, CUDA 12.1, schedule mode: auto
Input Buffers  CUDA, 20 frames
Input Info     avcuvid: H.265/HEVC, 1920x1080, 60/1 fps
AVSync         vfr
Vpp Filters    copyDtoD
Output Info    H.265/HEVC main @ Level auto
               1920x1080p 1:1 60.000fps (60/1fps)
Encoder Preset quality
Rate Control   VBR
Multipass      2pass-full
Bitrate        6000 kbps (Max: 19200 kbps)
Target Quality auto
Initial QP     I:20  P:23  B:25
QP Offset      cb:0  cr:0
VBV buf size   auto
Lookahead      off
GOP length     600 frames
B frames       3 frames [ref mode: middle]
Ref frames     3 frames, MultiRef L0:auto L1:auto
AQ             off
CU max / min   auto / auto
Others         mv:auto

**Comment by ChocOranger** [comment]
NVEnc uses a small specific area of the gpu to encode. Some functions can be offloaded to the main GPU for processing. The main purpose was originally to enable gaming streamers to encode videos without adversely affect gameplay fps

https://developer.nvidia.com/video-codec-sdk#:~:text=NVIDIA%20GPUs%20contain%20one%20or,are%20free%20for%20other%20operations.****

I wouldn't expect 100% GPU usage for encoding.

Staxrip displays the VE% when encoding. That should be very high.

**Comment by Discograp** [comment]
try this

![001](https://user-images.githubusercontent.com/95682410/230751500-7ddcb947-45e9-4e12-a97b-a9455bc86fbe.jpg)

**Comment by Discograp** [comment]
NVENC codec always loads video card at 100%
but due to heating, it reduces the speed/FPS

**Comment by ChocOranger** [comment]
> NVENC codec always loads video card at 100%

Please check the link I posted previously. NVENC is a small sub-section of the video card that's been highly optimised for encoding. Its entire point is not to overload the CUDA cores on the video card.

**Comment by ChocOranger** [comment]
The reason it's using just 50% is that the current NVENC SDK 12.0 does not provide method to select or handle the 2 encoders.

See https://github.com/rigaya/NVEnc/issues/474

**Comment by Discograp** [comment]
then it's nvidia's fault, not staxrip's

delete post
