### ISSUE TITLE
codec VP9 - muxing bugged

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#993]
when i load vp9.mkv
then Staxrip reports an ERROR - "RED"

![001](https://user-images.githubusercontent.com/95682410/229982813-d208556e-da26-4b70-b5ed-5e4d8cfbd8ff.jpg)

**Comment by Dendraspis** [comment]
Have you read the error message?
Do you think you got this message?

**Comment by Discograp** [comment]
vp9 codec is compatible with webmv(mkv) +modified mp4/mkv

why error?

**Comment by Discograp** [comment]
why error?
