### ISSUE TITLE
issue with encoding ts file

### ISSUE THREAD

**Issue by mr-qansuh** [staxrip/staxrip#996]
issue with encoding ts file 
when i encoding ts file audio delay some seconds from video with 2.14.0.0
and when i encoding in staxrip 1.7.0.0

link for the video 
https://www110.uptobox.com/dl/yjTzpHK4h804FzvO5GarP9fcJFOhCbvbjsfBnvrE6dEw6NLA0fckPmaboDqZLoRkOP25YZnJeWvObL8tkEIzcd1-BYxD3ebmQrggoIaICnhAN_AhFgrW5izg4u3XepoU/The.Shadow.Team.S03-E23.1080p.HilalPlay.WEB-DL.ts

**Comment by Discograp** [comment]
how long is the video?
errors with audio occur if the video is long - try deinterlacing without touching the fps(х2)/(change)
